### ISSUE TITLE
Circular dependency matplotlib <- ipython <- matplotlib

### ISSUE THREAD

**Issue by daym** [ipython/ipython#10003]
Hi,

when using matplotlib-1.5.3 and ipython 3.2.1 there's a circular dependency.

matplotlib requires ipython in order to build the docs.

ipython requires matplotlib.sphinxext.mathmpl .

Also, there's an extra cycle: python-ipython requires python-numpy requires python-matplotlib requires python-ipython.

Can this be disentangled?

**Comment by tacaswell** [comment]
I suggest we keep this discussion in the mpl issue.

**Comment by ivanov** [comment]
closing this, the discussion continued in matplotlib/matplotlib/issues/7264.
