### ISSUE TITLE
Jupyter notebook kernel died (memory shortage)

### ISSUE THREAD

**Issue by csh412** [ipython/ipython#10002]
Hi, 
I have a problem when I use keras model (deep learning library) in jupyter notebook
This problem occured after i instsalled scipy, matploliab libraries in conda

Before executing code cell, my computer GPU memory is like below
![fig1](https://cloud.githubusercontent.com/assets/22813788/19346585/19dad2f4-917f-11e6-80b3-989c0aab47f6.jpg)

And I executed simple keras model code
![fig2](https://cloud.githubusercontent.com/assets/22813788/19346635/7343a1ea-917f-11e6-872c-25d4cc6112a9.jpg)

After executing above code, GPU memory usage change from 241MB -> 7754MB
![fig3](https://cloud.githubusercontent.com/assets/22813788/19346664/9275d8da-917f-11e6-8f0c-d22c4caf00cf.jpg)

So, when I run training cell code, jupyter died 
This problem happend again and again... even though I restarted my jupyter notebook..

Is there any good idea to solve this problem??
Please somebody help me...TT

**Comment by takluyver** [comment]
I think you need to ask about that on a Keras mailing list or something; we don't know much about Keras.
