### ISSUE TITLE
impossible to exit debugger traces

### ISSUE THREAD

**Issue by amueller** [ipython/ipython#10006]
I like to set traces, and from what I understand from the docs, The Right Way is to use `TerminalPdb`.
However, I can not find out how to quit the `TerminalPdb` debugger---maybe I'm just daft.
Say I set a trace in a long loop:

``` python
from IPython.terminal.debugger import TerminalPdb
pdb = TerminalPdb()

while True:
    pdb.set_trace()
```

The only way to exit this program that I found is to kill it.

My questions are:
- Is TerminalPdb the best way to set traces?
- Is this expected behavior?
- How do I quit?

Thanks!

(I'm on IPython 5.1.0)

**Comment by Carreau** [comment]
> Is TerminalPdb the best way to set traces?

Likely. We added from `IPython.terminal.debugger:set_trace()` recently. There might better packages on PyPI that have more advance features. 

> Is this expected behavior?

I'm unsure. 

> How do I quit?

`IPython.embed()` have a `kill embed` that prevent a specific instance to be re-entered and add an ability to raise on exit. I'm still unsure why TerminalPdb  does not raise on exit like normal Pdb.

**Comment by amueller** [comment]
Thanks for your quick reply.

My intuition would have been that ``Ctrl + D`` quits and ``Ctrl + Z`` suspends. ``Ctrl + Z`` does nothing, ``Ctrl + D`` skips to the next iteration, I think.

Being compatible with ``pdb`` would probably be the most intuitive for most users. I'm happy to work on it if it's something that should be reasonably easy.

**Comment by Carreau** [comment]
> Thanks for your quick reply.
> 
> My intuition would have been that Ctrl + D quits and Ctrl + Z suspends. Ctrl + Z does nothing, Ctrl + D skips to the next iteration, I think.
> 
> Being compatible with pdb would probably be the most intuitive for most users. I'm happy to work on it if it's something that should be reasonably easy.

Yeah, that should not be too hard. 

It seem to be `IPython.core.debugger:Pdb.trace_dispatch` which explicitly silence `BdbQuit` since ec2d023d. I see why one would like to not raise on exit and vice-versa, so we can try to fing a compromise.

**Comment by bobcolner** [comment]
why is this issue closed? the bug is still as glaring as ever in ipython 5.2

**Comment by Carreau** [comment]
Thank you @bobcolner for your feedback, This issue has been closed as PR #10009 has been merged and was meant to fix the original use case brought up by @amueller. This PR seem to be present in the 5.2 release, and I'm able to check that it fixes above use case locally when using IPython 5.2.

```
~/dev/ipython 5.2.0 "!!" $ python foo.py
> $HOME/dev/ipython/foo.py(5)<module>()
      1 from IPython.terminal.debugger import TerminalPdb
      2 pdb = TerminalPdb()
      3
      4 while True:
----> 5     pdb.set_trace()

ipdb> ^D

Traceback (most recent call last):
  File "foo.py", line 5, in <module>
    pdb.set_trace()
  File "foo.py", line 5, in <module>
    pdb.set_trace()
  File "$HOME/anaconda/lib/python3.5/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "$HOME/anaconda/lib/python3.5/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

 ~/dev/ipython 5.2.0 [1]"!!" $ cat foo.py
from IPython.terminal.debugger import TerminalPdb
pdb = TerminalPdb()

while True:
    pdb.set_trace()
```

Did you update IPython ? How did you upgrade ? How are you using PDB ? Are you sure your system is picking up IPython 5.2 ?

**Comment by alex-git-rd** [comment]
I'm on IPython 6.4, Python 3.6.6 and I'm still getting this issue. Specifically, if I do any `.groupby("col").apply(f)` in pandas for some function `f` that has a `set_trace()`, ipdb doesn't let me quit by typing `q` but rather keeps re-running to the next iteration.

**Comment by sizhky** [comment]
Use exit()
