### ISSUE TITLE
"Kernel appears to have died" while from keras.preprocessing.image import ImageDataGenerator

### ISSUE THREAD

**Issue by larrygao** [ipython/ipython#10017]
I was running some code about Kaggle Second Annual Data Science Bowl. The code is here.https://github.com/fchollet/keras-resources.
I have installed anaconda, tensorflow, keras and jupyter notebook on Ubuntu 16.04

When I ran the code, everything was fine, except can't import h5py when saving weights. So I installed h5py to run the code with conda install h5py. Now I can import h5py, but the jupyter notebook always pop up the kernel appears to have died.

The exact line of code is 
from keras.preprocessing.image import ImageDataGenerator

**Comment by larrygao** [comment]
This is the information from the terminal
(tensorflow) larry@larry-LIFEBOOK-AH531:~$ jupyter notebook
[I 20:24:36.798 NotebookApp] Serving notebooks from local directory: /home/larry
[I 20:24:36.798 NotebookApp] 0 active kernels 
[I 20:24:36.798 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 20:24:36.798 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 20:24:51.605 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20161021202436 (127.0.0.1) 8.98ms referer=http://localhost:8888/notebooks/2ndreaddata.ipynb
[I 20:24:51.635 NotebookApp] Kernel started: 50d17a42-e4e6-487e-b89e-a7250e7f78e7
[I 20:25:15.638 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 50d17a42-e4e6-487e-b89e-a7250e7f78e7 restarted
[I 20:25:42.651 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 50d17a42-e4e6-487e-b89e-a7250e7f78e7 restarted
[I 20:25:53.983 NotebookApp] Saving file at /2ndreaddata.ipynb

**Comment by minrk** [comment]
It's certainly unusual to have no output. Can you try running the same code in a pure Python script?

**Comment by larrygao** [comment]
Thank you minrk.
I have reinstalled Tensorflow.  Now it works now.

**Comment by bdevyansh** [comment]
try using import numpy before keras or tensorflow
