### ISSUE TITLE
Pasting string containing '(.*)' triggers shell expansion (ipython running in conemu)

### ISSUE THREAD

**Issue by lv-gh** [ipython/ipython#10020]
> ipython -V
5.1.0

Clipboard contains '(.*)'
Pasting it results in something like that:

> In [46]: (..anaconda/ .android/ .CrowTDE/ .designer/ .freemind/ .gimp-2.8/ .idlerc/ .ipython/ .jupyter/ .kdiff3rc .matplo
>     ...: tlib/ .node-gyp/ .node_repl_history .oracle_jre_usage/ .pagerc .spyder/ .ssh/ .thumbnails/ .VirtualBox/)

I'm not sure if it's a bug or a feature of conemu itself, though shell expansion doesn't happen when pasting in cmd, Far, Cygwin, Python running in conemu.

**Comment by takluyver** [comment]
Are you pasting with Ctrl-V, or some paste option in ConEmu? IPython handles Ctrl-V for paste, but it's reading the clipboard in a fairly normal way.

**Comment by lv-gh** [comment]
Confused; now pasting works as expected. I am sure, that i tried both variant (Shift+INS, Ctrl+V).  And i'm sure, that incorrect paste effect actually happens, but now i can't reproduce it.

**Comment by lv-gh** [comment]
Well, reproduced again: pasting (Ctrl+V, Shift+INS) '.\*' always results in wildcard expansion in IPython running in conemu, **if current keyboard is Lithuanian**. Looks like it could be [yet another bug](https://github.com/ipython/ipython/issues/10004) of prompt_toolkit.

**Comment by takluyver** [comment]
@jonathanslenders any idea if something weird could be happening on paste with ConEmu and a Lithuanian keyboard?

I'm not sure how a bug in prompt_toolkit could directly cause this, because it's unlikely that it does shell expansion. My guess is that we're triggering something in ConEmu that tries to be clever.

**Comment by jonathanslenders** [comment]
There is nothing in prompt_toolkit that implements shell expansion, so it should be ConEmu doing that.
What version of ConEmu is that? Does it also happen when pasting outside of prompt_toolkit?

**Comment by lv-gh** [comment]
@jonathanslenders 

Conemu 160914 [64] (Stable)
Like i already wrote: it doesn't happen in other shells/programs running in conemu: cmd, Far, python, cygwin. Only in IPython.

**Comment by lv-gh** [comment]
Some crude debugging; prompt_toolkit/terminal/win32_input.py:_event_to_key_presses():
>         if result:
>             meta_pressed = ev.ControlKeyState & self.LEFT_ALT_PRESSED
> 
>             if meta_pressed:
>                 **print("meta: ", result) 
>                 return [KeyPress(Keys.Escape, ''), result]
>             else:
>                 **print(result)  
>                 return [result]

When keyboard is EN/RU (haven't tried others), pasting '.*' outputs:

> In [4]: KeyPress(key='.', data='.')
> KeyPress(key='\*', data='\*')
> .*

But when keyboard is LT:

> In [6]: KeyPress(key='.', data='.')
> meta:  KeyPress(key='\*', data='\*')
> ..anaconda/ .android/ .CrowTDE/ .designer/ .freemind/ .gimp-2.8/ .idlerc/ .ipython/ .jupyter/ .kdiff3rc .matplot        l
>    ...: ib/ .node-gyp/ .node_repl_history .oracle_jre_usage/ .pagerc .spyder/ .ssh/ .thumbnails/ .VirtualBox/
>

**Comment by lv-gh** [comment]
Digging deeper. This seems to be rather strange and undocumented OS (ReadConsoleInputW) behavior: when default keyboard (in my case it's Lithuanian) is selected and Shift+INS (or Ctrl+V) is pressed ReadConsoleInputW() sets dwControlKeyState (https://msdn.microsoft.com/en-us/library/windows/desktop/ms684166%28v=vs.85%29.aspx) to RIGHT_ALT_PRESSED and LEFT_CTRL_PRESSED **in cmd** and LEFT_CTRL_PRESSED and LEFT_ALT_PRESSED **in conemu**. 

If other keyboards are selected, then no CTRL or ALT flags are set neither in cmd, nor in conemu.

**Comment by lv-gh** [comment]
Here is the output (pressing Shift+INS, when clipboard contains '.*') from a [KeyPress](http://heanet.dl.sourceforge.net/project/conemu/OldReleases/FarPlugins/KeyEvents4.7z) program running in conemu:

(**Note the difference of Ctrl flag of VK_8 key**)

**Lithuanian** (default) keyboard selected:

```
 02:43:46 KEY_EVENT_RECORD: Dn, 1, Vk="VK_SHIFT" [16/0x0010], Scan=0x002A uChar=[U=' ' (0x0000): A=' ' (0x00)]
          Ctrl=0x000000B0 (caSac - eCNs) (Windowed)
 02:43:46 KEY_EVENT_RECORD: Dn, 1, Vk="VK_OEM_PERIOD" [190/0x00BE], Scan=0x0034 uChar=[U='.' (0x002E): A='.' (0x2E)]
          Ctrl=0x00000000 (casac - ecns) (Windowed)
 02:43:46 KEY_EVENT_RECORD: Up, 1, Vk="VK_OEM_PERIOD" [190/0x00BE], Scan=0x0034 uChar=[U='.' (0x002E): A='.' (0x2E)]
          Ctrl=0x00000000 (casac - ecns) (Windowed)
 02:43:46 KEY_EVENT_RECORD: Dn, 1, Vk="VK_8" [56/0x0038], Scan=0x0009 uChar=[U='*' (0x002A): A='*' (0x2A)]
          Ctrl=0x0000001A (CASac - ecns) (Windowed)
 02:43:46 KEY_EVENT_RECORD: Up, 1, Vk="VK_8" [56/0x0038], Scan=0x0009 uChar=[U='*' (0x002A): A='*' (0x2A)]
          Ctrl=0x0000001A (CASac - ecns) (Windowed)
 02:43:46 KEY_EVENT_RECORD: Up, 1, Vk="VK_SHIFT" [16/0x0010], Scan=0x002A uChar=[U=' ' (0x0000): A=' ' (0x00)]
          Ctrl=0x000000A0 (casac - eCNs) (Windowed)

``` 

**English:**
```
 02:42:44 KEY_EVENT_RECORD: Dn, 1, Vk="VK_SHIFT" [16/0x0010], Scan=0x002A uChar=[U=' ' (0x0000): A=' ' (0x00)]
          Ctrl=0x000000B0 (caSac - eCNs) (Windowed)
 02:42:44 KEY_EVENT_RECORD: Dn, 1, Vk="VK_OEM_PERIOD" [190/0x00BE], Scan=0x0034 uChar=[U='.' (0x002E): A='.' (0x2E)]
          Ctrl=0x00000000 (casac - ecns) (Windowed)
 02:42:44 KEY_EVENT_RECORD: Up, 1, Vk="VK_OEM_PERIOD" [190/0x00BE], Scan=0x0034 uChar=[U='.' (0x002E): A='.' (0x2E)]
          Ctrl=0x00000000 (casac - ecns) (Windowed)
 02:42:44 KEY_EVENT_RECORD: Dn, 1, Vk="VK_8" [56/0x0038], Scan=0x0009 uChar=[U='*' (0x002A): A='*' (0x2A)]
          Ctrl=0x00000010 (caSac - ecns) (Windowed)
 02:42:44 KEY_EVENT_RECORD: Up, 1, Vk="VK_8" [56/0x0038], Scan=0x0009 uChar=[U='*' (0x002A): A='*' (0x2A)]
          Ctrl=0x00000010 (caSac - ecns) (Windowed)
 02:42:45 KEY_EVENT_RECORD: Up, 1, Vk="VK_SHIFT" [16/0x0010], Scan=0x002A uChar=[U=' ' (0x0000): A=' ' (0x00)]
          Ctrl=0x000000A0 (casac - eCNs) (Windowed)
```

**Russian:**
```
02:54:43 KEY_EVENT_RECORD: Dn, 1, Vk="VK_SHIFT" [16/0x0010], Scan=0x002A uChar=[U=' ' (0x0000): A=' ' (0x00)]
         Ctrl=0x00000030 (caSac - ecNs) (Windowed)
02:54:43 KEY_EVENT_RECORD: Dn, 1, Vk="VK_OEM_2" [191/0x00BF], Scan=0x0035 uChar=[U='.' (0x002E): A='.' (0x2E)]
         Ctrl=0x00000000 (casac - ecns) (Windowed)
02:54:43 KEY_EVENT_RECORD: Up, 1, Vk="VK_OEM_2" [191/0x00BF], Scan=0x0035 uChar=[U='.' (0x002E): A='.' (0x2E)]
         Ctrl=0x00000000 (casac - ecns) (Windowed)
02:54:43 KEY_EVENT_RECORD: Dn, 1, Vk="VK_8" [56/0x0038], Scan=0x0009 uChar=[U='*' (0x002A): A='*' (0x2A)]
         Ctrl=0x00000010 (caSac - ecns) (Windowed)
02:54:43 KEY_EVENT_RECORD: Up, 1, Vk="VK_8" [56/0x0038], Scan=0x0009 uChar=[U='*' (0x002A): A='*' (0x2A)]
         Ctrl=0x00000010 (caSac - ecns) (Windowed)
02:54:43 KEY_EVENT_RECORD: Up, 1, Vk="VK_SHIFT" [16/0x0010], Scan=0x002A uChar=[U=' ' (0x0000): A=' ' (0x00)]
         Ctrl=0x00000020 (casac - ecNs) (Windowed)
```

**Comment by lv-gh** [comment]
@jonathanslenders

I think i found the root of the problem. Here is suggested patch:
```
--- prompt_toolkit/terminal/win32_input.py.orig	2016-10-21 18:35:26.000000000 +0300
+++ prompt_toolkit/terminal/win32_input.py	2016-10-26 20:12:36.503011700 +0300
@@ -277,8 +277,11 @@
         #       typing some special characters, like a backslash. We don't want
         #       all backslashes to be prefixed with escape. (Esc-\ has a
         #       meaning in E-macs, for instance.)
+        # On some keyboards ALTGR can be emulated as LALT + LCTRL, so actually
+        # we need to distinguish single LALT (Meta) from LALT + LCTRL.
         if result:
-            meta_pressed = ev.ControlKeyState & self.LEFT_ALT_PRESSED
+            meta_pressed = (ev.ControlKeyState & self.LEFT_ALT_PRESSED and
+                                not ev.ControlKeyState & self.LEFT_CTRL_PRESSED)
 
             if meta_pressed:
                 return [KeyPress(Keys.Escape, ''), result]



```

**Comment by takluyver** [comment]
Closing as this doesn't seem to be a bug in IPython's code.
