### ISSUE TITLE
Qt Console: Realtime output from multiple processes not working

### ISSUE THREAD

**Issue by chrisgmorton** [ipython/ipython#10034]
Running on Mac OS X Yosemite (10.10.2), IPython 1.1.0, Python 2.7.3

The following test case will print out in realtime as each task starts and completes, when run in an IPython console:

```
import multiprocessing
import time
import sys

tasks = (('a', 2), ('b', 4),('e', 1), ('f', 3), ('g', 5))

def mp_worker((inputs, the_time)):
    sys.stdout.write('Job {}:\tWaiting {} seconds.\n'.format(inputs, the_time))
    sys.stdout.flush()
    time.sleep(the_time)
    sys.stdout.write('Job {}:\tDone.\n'.format(inputs))
    sys.stdout.flush()

if __name__ == '__main__':

    print 'Let\'s get started.'

    jobs=[multiprocessing.Process(target=mp_worker, args=(task,)) for task in tasks]

    [p.start() for p in jobs]
    [p.join() for p in jobs]

    print 'Were done.\n'
```

When run in an IPython Qt Console, the sub-process output only shows up in the console window once all jobs are completed. The Qt Console output would suggest that it is handling the output from sub-processes as a separate step, on completion of script execution:

```
Let's get started.
Were done.

Job a:  Waiting 2 seconds.
Job b:  Waiting 4 seconds.
Job e:  Waiting 1 seconds.
Job f:  Waiting 3 seconds.
Job g:  Waiting 5 seconds.
Job a:  Done.
Job b:  Done.
Job e:  Done.
Job f:  Done.
Job g:  Done.
```

Suggestion on how to work around would be much appreciated.

Chris.

**Comment by Carreau** [comment]
Hi there, thanks for your report. Current Stable version of IPython (and qtconsole) are the 5.x series. Can you try with these? Thanks!

**Comment by chrisgmorton** [comment]
Will try next week. Last time I tried installing Jupiter I had no luck, hence the old version of IPython.
Chris.

**Comment by minrk** [comment]
There are fixes specifically for this multi-process output in ipykernel 4.3, so you might have some luck if you are able to upgrade.

If everything is happy:

```bash
pip install --upgrade setuptools pip
pip install --upgrade jupyter
```

**Comment by chrisgmorton** [comment]
Was able to verify resolution of this issue using Python 3.5.2, QtConsole 4.2.1, PyQt5. Closing. Thanks.
