### ISSUE TITLE
Seed (random) not working!

### ISSUE THREAD

**Issue by gustavooferreira** [ipython/ipython#10036]
Hello, if I do this in python shell:
>>> import random
>>> random.seed(100)
>>> random.random()
0.1456692551041303
>>> random.seed(100)
>>> random.random()
0.1456692551041303

It works as expected! Same "random" number.
But if I do the same in Ipython, it does not work.
Any hints?

**Comment by takluyver** [comment]
This does work for me most of the time in IPython. But I would guess that something in the code is using a random number before you call `random.random()`.

If you want to have your own sequence of random numbers independent of any other code using them, create a new random.Random instance as the [docs mention](https://docs.python.org/3/library/random.html#notes-on-reproducibility):

> The functions supplied by this module are actually bound methods of a hidden instance of the random.Random class. You can instantiate your own instances of Random to get generators that don’t share state.

```
 23│ myrand = random.Random(100)

 24│ myrand.random()
 24> 0.1456692551041303
```
