### ISSUE TITLE
elegant way to display gif file in notebook?

### ISSUE THREAD

**Issue by hainm** [ipython/ipython#10045]
Hi,

Is there any way to display gif file in super short way? I have at two ways but none of them are really what I want

- Using `HTML`
```python
def display_gif(fn):
    from IPython import display
    return display.HTML('<img src="{}">'.format(fn))
```

This does not play nicely with browser's cache. If I remake an image with the same filename, the new image won't be updated.

- Rename `.gif` to `.png` and then use `display.Image(fn)`.

thanks.

**Comment by takluyver** [comment]
Anyone know if data urls work across browsers with gifs? Maybe we just need to add it to `IPython.display.Image._ACCEPTABLE_EMBEDDINGS`.

**Comment by vbraun** [comment]
Data uris of course work with gif, or any other mime type that the browser supports:

    '<img src="data:image/gif;base64,{0}"/>'.format(base64.b64encode(gif))

**Comment by gnestor** [comment]
As discussed, there are couple different ways to do this:

### HTML

```py
from IPython.display import HTML
HTML('<img src="../giphy.gif">')
```
### `Image(filename=*)` or `Image(url=*)` by adding a `png` extension to GIF file

```py
from IPython.display import Image
Image(filename="../giphy.gif.png")
```

### `Image(data=*)`

```py
with open('../giphy.gif','rb') as f:
    display(Image(data=f.read(), format='png'))
```

Ideally, we want to be able to `Image(filename=*)` or `Image(url=*)` without being required to rename the file and be able to use `format="gif"`. Is there any reason that GIF is not supported format yet? If not, I say we support it 👍

**Comment by ferreirafabio** [comment]
how to arrange them horizontally?

**Comment by gnestor** [comment]
Using `HTML`, it's pretty straight-forward:

```py
from IPython.display import display, HTML

HTML('''<div style="display: flex; justify-content: row;">
    <img src="../giphy.gif">
    <img src="../giphy.gif">
    <img src="../giphy.gif">
</div>''')
```

**Comment by denfromufa** [comment]
Only the third option works in Colab notebooks:

https://github.com/ipython/ipython/issues/10045#issuecomment-318202267

**Comment by Miladiouss** [comment]
Just to make it easier to copy, I will repeat the method that works in IPython, Jupyter, and CoLab:

```Python
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
from IPython import display
```

It is important to run the above cell _before_ running the cell below.

```Python
from pathlib import Path
gifPath = Path("/path/to/my.gif")
# Display GIF in Jupyter, CoLab, IPython
with open(gifPath,'rb') as f:
    display.Image(data=f.read(), format='png')
```

And just to be complete, here is how you make gifs in python:

```Python
# Generate GIF
import imageio
from pathlib import Path

picsPath = Path("/path/to/pics/folder/")
images = []
for f in picsPath.glob("*.png"):
    images.append(imageio.imread(f))
imageio.mimsave(picsPath / 'movie.gif', images)
```

**Comment by mmhasnat17** [comment]
If you want to use GIF on the Jupyter Notebook do the following:

![](https://media.giphy.com/media/3oD3YveOJWdwIAfZ5e/giphy.gif)

**Comment by gaurav-vision** [comment]
Any image format either png, jpg, jpeg or gif etc, you want to show in python jupyter notebook then simply use matplotlib library.
"import matplotlib.pyplot as plt"
"import matplotlib.image as mpimg"
img = mpimg.imread("/home/gaurav/soft computing assignment/soft computing/river.gif")
plt.imshow(img)

**Comment by LeeRippon** [comment]
> Just to make it easier to copy, I will repeat the method that works in IPython, Jupyter, and CoLab:
> 
> ```python
> from IPython.core.interactiveshell import InteractiveShell
> InteractiveShell.ast_node_interactivity = "all"
> from IPython import display
> ```
> 
> It is important to run the above cell _before_ running the cell below.
> 
> ```python
> from pathlib import Path
> gifPath = Path("/path/to/my.gif")
> # Display GIF in Jupyter, CoLab, IPython
> with open(gifPath,'rb') as f:
>     display.Image(data=f.read(), format='png')
> ```
> 
> And just to be complete, here is how you make gifs in python:
> 
> ```python
> # Generate GIF
> import imageio
> from pathlib import Path
> 
> picsPath = Path("/path/to/pics/folder/")
> images = []
> for f in picsPath.glob("*.png"):
>     images.append(imageio.imread(f))
> imageio.mimsave(picsPath / 'movie.gif', images)
> ```

Thank you. This worked for me. Is there any way to center the output image in Colab?

Also (for anyone) is there any way to display the gif in a Markdown cell in Colab when the gif is stored in Google Drive?

**Comment by maedoc** [comment]
Alright, here's my submission despite the issue being closed: when I tried the other options above, the exported HTML file doesn't show the GIF, since it doesn't get embedded base64, so I have the following working solution, (in Python 3.6+)
```python
def show_gif(fname):
    import base64
    from IPython import display
    with open(fname, 'rb') as fd:
        b64 = base64.b64encode(fd.read()).decode('ascii')
    return display.HTML(f'<img src="data:image/gif;base64,{b64}" />')

show_gif('pikachu.gif')
```

**Comment by kareido** [comment]
I find this package very helpful for rendering git on notebook. https://github.com/google/mediapy

**Comment by zba** [comment]
> Any image format either png, jpg, jpeg or gif etc, you want to show in python jupyter notebook then simply use matplotlib library. "import matplotlib.pyplot as plt" "import matplotlib.image as mpimg" img = mpimg.imread("/home/gaurav/soft computing assignment/soft computing/river.gif") plt.imshow(img)

shows as png data
