### ISSUE TITLE
Calling get_terminal_size when there is no terminal

### ISSUE THREAD

**Issue by tmr232** [ipython/ipython#10040]
When formatting exceptions, IPython uses `shutil.get_terminal_size`. When there is no terminal (due to output redirection) this results in unhandled exceptions. See https://github.com/james91b/ida_ipython/pull/34 and https://github.com/james91b/ida_ipython/pull/33

**Comment by ivanov** [comment]
Thanks for your report, @tmr232 - looking at the traceback, I think this is only an issue with IDA_IPython, which overrides stdout, but does not behave like a file descriptor.

```python
size = _get_terminal_size(sys.__stdout__.fileno())
AttributeError: IDAPythonStdOut instance has no attribute 'fileno'
```

Redirected output to a shell works as expected:
```shell
$ python3 -c 'from IPython.utils.terminal import get_terminal_size as g; print(g())'
os.terminal_size(columns=209, lines=52)
$ python3 -c 'from IPython.utils.terminal import get_terminal_size as g; print(g())' > out; cat out
os.terminal_size(columns=80, lines=25)
```

**Comment by takluyver** [comment]
I don't think we should catch the AttributeError at the IPython level, because it's easy to conceal real bugs by catching AttributeError. Looking at the code in shutil, it should fall back to the defaults if `sys.__stdout__.fileno()` raises `OSError` - as ipykernel's `OutStream` class already does.

**Comment by takluyver** [comment]
Snap, @ivanov ;-)

**Comment by ivanov** [comment]
Closing this. Feel free to re-open if you come up with a scenario where we don't do the right thing.

**Comment by tmr232** [comment]
Thanks for the quick response 👍
