### ISSUE TITLE
QTConsole with --ssh option and kernel interrupt

### ISSUE THREAD

**Issue by ohe** [ipython/ipython#1004]
In current master branch, when using a remote kernel, accessed via the `--ssh` option of `ipython qtconsole`. There is no way to interrupt a python call, either with CTRL+C either with the "Kernel" menu. In both case, the following message appears : 

`Kernel process is either remote or unspecified. Cannot interrupt`.

By digging on this tracker, this seems to be the "normal"  behavior when someone tries to send an interrupt/restart order to a remote kernel.

what are the sticking points related to this "feature"?
Is there any plans to fix this issue?

BTW, thanks for all the work done so far.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
