### ISSUE TITLE
display jpg image doesn't work

### ISSUE THREAD

**Issue by mickeydonkey** [ipython/ipython#10042]
```
from IPython.core.display import *
Image(data='https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Pomegranate03_edit.jpg/320px-Pomegranate03_edit.jpg', embed=True,format='jpeg')

Out[16]: <IPython.core.display.Image object>
```
qtconsole=4.2.1
python=3.5

**Comment by ivanov** [comment]
Thank you for your report. Can you specify what platform this is on?

**Comment by mickeydonkey** [comment]
windows 10 
python=3.5

**Comment by mickeydonkey** [comment]
Sorry, I forget to mention the above code is ran inside IPython qtconsole, not notebook

**Comment by ivanov** [comment]
yes, thanks, the https://github.com/jupyter/qtconsole  repo would be the right place to post this issue. You can add that it appears to be a Python3 issue, as I cannot reproduce it in Python2, but do see it in Python3.

**Comment by takluyver** [comment]
Follow up is jupyter/qtconsole#158
