### ISSUE TITLE
SVG display support of Image object.

### ISSUE THREAD

**Issue by mickeydonkey** [ipython/ipython#10043]
`Image('/path/to/pattern.svg')` gives an error `Cannot embed the 'svg' image format `. I've managed to display SVG in qtconsole, but It seems not the first-class citizen like png and jpeg. 
```
svg = open('/home/luot/Pictures/pattern.svg', 'r').read()
display_svg(svg, raw=True)
```

**Comment by takluyver** [comment]
There's a separate class `IPython.display.SVG` for displaying SVG files. `Image` appears to be intended for bitmap images - primarily png and jpg.

**Comment by mickeydonkey** [comment]
@takluyver I'm happy with your solution, Thanks.

**Comment by takluyver** [comment]
No problem :-)

**Comment by mpacer** [comment]
@takluyver @Carreau @minrk Is there a reason the Image class is only intended to support bitmap images? It seems like svg would be a reasonable inclusion.

**Comment by takluyver** [comment]
To my mind, SVG is a totally different kind of thing to a bitmap image, so it makes sense for them to be different classes.

**Comment by mpacer** [comment]
But isn't there also an PNG class? My suggestion was to think of image as a wrapper class for all image types and then make Bitmap a class for just bitmap images. But anyway I’ve been working on a different approach to the display metadata and uniform interface problem over the last few days with @minrk and @Carreau. Should have something interesting soon.

**Comment by mpacer** [comment]
But in part this comes down to that wonderful problem of naming, where `Image` seems like it should more general than just `Bitmap` rather than a synonym.

**Comment by takluyver** [comment]
There are not separate classes, nor aliases, for PNG, JPEG, or Bitmap.

**Comment by mpacer** [comment]
I'm suggesting to invent them anyway it's moot now.
