### ISSUE TITLE
Ability to specify custom mimetypes

### ISSUE THREAD

**Issue by rgbkrk** [ipython/ipython#10058]
It would be nice if I could declare (without overriding the base formatters in IPython) a repr for arbitrary mimebundles like this:

```python
class Thing(object):
    def _repr_mimebundle_(self):
        return {
            'custom+json': '',
        }
```

**Comment by takluyver** [comment]
Should that override any other `_repr_foo_` outputs, or should those be merged into the dictionary? If you only want it to use that mimebundle, it should be fairly easy to do it with `def _ipython_display_(self):`.

**Comment by rgbkrk** [comment]
Ohhhhhh that's the one I need then, thanks! I'll give that a go.

**Comment by rgbkrk** [comment]
Ah, this can only do `display_data` or otherwise directly. It can't end up as an `execute_result`.

**Comment by rgbkrk** [comment]
Closing in favor of #10090.
