### ISSUE TITLE
add a post_exception hook

### ISSUE THREAD

**Issue by sprig** [ipython/ipython#10063]
Hello,

It could be useful to have a 'post_exception' hook, which would run if there is an unhandled exception (basically in cases where now I would see a traceback).

Example use cases:

Would allow for automatic variable injection in sage for undefined variables (by wrapping NameError) this is the actual current motivation.
Would allow automatically restarting/reporting when exceptions are raised from long-running code.
Would a PR implementing this be accepted (assuming it works well, etc)?

Not sure where this is related to #54

**Comment by minrk** [comment]
There is already [ip.set_custom_exc](http://ipython.readthedocs.io/en/stable/api/generated/IPython.core.interactiveshell.html#IPython.core.interactiveshell.InteractiveShell.set_custom_exc), which can register custom exception handlers, which are called when an error is raised. Is that sufficient for what you are after?

**Comment by sprig** [comment]
@minrk Thanks! It is. Don't know how I missed it...
