### ISSUE TITLE
IPython startup scripts fails to load

### ISSUE THREAD

**Issue by keshavramaswamy** [ipython/ipython#10068]
* I have a startup script in `~/.ipython/profile_default/startup/`
* IPython throws a warning when I open any notebook: `[IPKernelApp] WARNING | Unknown error in handling startup files:`
Is there something I am missing?

**Comment by takluyver** [comment]
It should show the error after that line, but I guess that in the notebook the error is redirected somewhere and gets lost. Try starting `ipython` in a terminal, it should show you the error.

**Comment by keshavramaswamy** [comment]
Perfect! I had `%matplotlib inline` in the script causing a Syntax Error. 
Thanks @takluyver

**Comment by takluyver** [comment]
Aha. You can use IPython special syntax in startup scripts if you give them a `.ipy` extension.

**Comment by neighthan** [comment]
In case others have a similar issue, make sure that you run `ipython` in the same environment as the kernel you were using when you got the `[IPKernelApp] WARNING | Unknown error in handling startup files:` warning. It took me awhile to realize that I only had this problem with a particular kernel from a conda environment which didn't have a library installed that one of my startup scripts used.

**Comment by cgironda** [comment]
Thank you @neighthan, your comment was useful to solve a similar problem that I had.

Also thank you @keshavramaswamy to open this issue.
