### ISSUE TITLE
IPython crashes when 8 == 9 and math makes no sense at all

### ISSUE THREAD

**Issue by CrazyPython** [ipython/ipython#10066]
I know, that's a ludicrous title, but just try running:

```
import ctypes
ctypes.cast(id(8), ctypes.POINTER(ctypes.c_int))[6] = 9
```

on the iPython interpreter. When run in vanilla CPython, it returns:
```
Python 3.5.2 (default, Jun 29 2016, 13:43:58) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> ctypes.cast(id(8), ctypes.POINTER(ctypes.c_int))[6] = 9
>>> 8 == 9
True
```

Vanilla CPython does not crash. Even performing arithmetic with 8 and 9 will not cause it to crash.

**Comment by CrazyPython** [comment]
```
import ctypes
ctypes.cast(id(1), ctypes.POINTER(ctypes.c_int))[6] = 100
```

also crashes iPython

**Comment by CrazyPython** [comment]
`ctypes.cast(id(92), ctypes.POINTER(ctypes.c_int))[6] = 3` just causes no response

**Comment by minrk** [comment]
Fun experiment, but what should we do about a deliberately broken Python being broken as intended? Any code that encounters the corrupted number will behave incorrectly. It appears that IPython's repl is likely to encounter 8, but `python -i` isn't.

I don't think we can protect IPython (or any Python code) against numbers being untrustworthy.

**Comment by takluyver** [comment]
This is probably because IPython is written entirely in Python, whereas the plain Python shell is, as far as I know, mostly implemented in C, so it's not affected by breaking the Python world so much.
