### ISSUE TITLE
Filename completion with quotes in filename does not escape the quotes

### ISSUE THREAD

**Issue by t-8ch** [ipython/ipython#10069]
When completing filenames containing quotes those are completed verbatim, closing the string.
The user has to go back in the string to escape the quotes manually.

```
$ touch /tmp/foo\'bar
$ ipython
In [1]: open('/tmp/foo<TAB>
# actual
In [1]: open('/tmp/foo'bar
# Expected:
In [1]: open('/tmp/foo\'bar
```

```python
{'commit_hash': '3a3686a',
 'commit_source': 'repository',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/t-8ch/Projekte/ipython/IPython',
 'ipython_version': '6.0.0.dev',
 'os_name': 'posix',
 'platform': 'Linux-4.8.10-1-ARCH-x86_64-with-arch',
 'sys_executable': '/home/t-8ch/.local/share/virtualenvs/ipython/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.5.2 (default, Nov  7 2016, 11:31:36) \n[GCC 6.2.1 20160830]'}
```

**Comment by chrisaycock** [comment]
Windows escapes a string by wrapping it with a double quote. In particular, Windows is only concerned with spaces in a string.

So what does that mean for the sample string? Are the surrounding single quotes replaced by double quotes? I'm not sure how to interpret this.

@Carreau says [we should only protect on Windows](https://github.com/ipython/ipython/pull/10533#issuecomment-300855578).

**Comment by Carreau** [comment]
> @Carreau says we should only protect on non-Windows.

not sure for "should", but if we are unsure we can always improve the experience on unix-like without changing the experience on windows, and decide about the windows codepath later :-)
