### ISSUE TITLE
Request a way to re-enable HTML repr for pandas DataFrames

### ISSUE THREAD

**Issue by DrEhrfurchtgebietend** [ipython/ipython#10062]
Pandas DataFrames no longer use the HTML rendering. I had hoped that there was some way to re-enable this just Pandas. I asked here pandas-dev/pandas/issues/14706 but it seems there is no easy way to do this. 

I see that there is good reason for wanting to have it disabled as outlined in ipython/ipython/pull/5763 but there are also some cases where one would want this at least for DataFrames . Is there or could there be a way to re-enable it if the user decides to do so but have it off by default to preserve the current stability?

**Comment by minrk** [comment]
Following up on the other issues, this is a question about the QtConsole, not IPython itself. IPython (the Kernel) can't really do this as configuration, but we could add an option to the QtConsole to allow HTML output. It couldn't be done for just pandas though, it would have to be all or nothing. The reason being that IPython, which knows *what* it is displaying, doesn't know what the frontend (QtConsole or notebook) supports or not. But the QtConsole only knows that it got HTML output, not that it got the tiny subset of HTML that it can support, or that it was a DataFrame.

But we could have an off-by-default option to enable HTML in the QtConsole for users who prefer semi-supported HTML output to none at all.

**Comment by ccordoba12** [comment]
@minrk, what if we open a QDialog with a QWebView widget inside it to display HTML content in `qtconsole`?

That shouldn't be hard to do and would restore HTML support to `qtconsole` right away :-)

**Comment by ccordoba12** [comment]
And (of course) then qtconsole would display any HTML content and not just a minimal subset of it :-)

**Comment by minrk** [comment]
@ccordoba12 great idea! I'll leave that to you.

**Comment by ccordoba12** [comment]
Ok, I'll do it when I have some free time :-)

Could you move this issue to the qtconsole repo? Thanks!

**Comment by DrEhrfurchtgebietend** [comment]
Closed this issue and opened jupyter/qtconsole/issues/165
