### ISSUE TITLE
Curly braces stripped from magic input.

### ISSUE THREAD

**Issue by BoPeng** [ipython/ipython#10072]
I noticed a weird problem when I am working on my ipython magic. Basically, if the user inputs

```
%sos a = '{100}'
```

my `sos` magic would get

```
a = '100'
```

as line input. I googled a bit and found that this is a [bug that has been reported back in 2013](https://mail.scipy.org/pipermail/ipython-dev/2013-September/012264.html), and there is even a github [gist](https://gist.github.com/jiffyclub/6399267) to demonstrate the problem. Can anyone let me know the status of this bug?

I am using IPython 5.1.0 for Python 3.5.2 and anaconda 4.4.1, on a mac machine.

**Comment by takluyver** [comment]
It's a questionable feature rather than a bug. Magics use curly braces as Python formatting syntax, so that you can use Python variables in magic commands:

```python
x = '--foo' if a else '--bar'
%run script.py {x}
```

You can escape the braces by doubling them, i.e. `{{100}}`.

See #5978 for more discussion about this.
