### ISSUE TITLE
Non-intuitive error with %gui qt if Qt is version 5

### ISSUE THREAD

**Issue by astrofrog** [ipython/ipython#10080]
I have PyQt5 installed. If I do the following, I get a non-intutive error:

```
In [1]: %gui qt
ERROR:root:'list' must be None or a list, not <class 'str'>
```

Note that ``%gui qt5`` works, but the error above is not clear (and if ``qt`` is specified, shouldn't it use Qt5 if Qt4 is not available?)

**Comment by minrk** [comment]
That certainly is a weird error! What IPython version? It succeeds when I run it, so maybe something weird is happing in the qt setup.

**Comment by takluyver** [comment]
A similar error message has been reported on the Qt console, as jupyter/qtconsole#168

One upside of wading through >100 issues in a single day ;-)

**Comment by takluyver** [comment]
#10148 should fix this
