### ISSUE TITLE
interact not functioning properly

### ISSUE THREAD

**Issue by johnashcroft105** [ipython/ipython#10087]
- Just getting ipython setup, but interact doesn't work for some reason

- I'm using ipython version 5.1.0 on macOSX 10.11.5 in native bash terminal

- I ran the following to double check my setup:
jupyter nbextension enable --py widgetsnbextension --sys-prefix
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK

- opened up ipython and ran:

```
In [1]: from __future__ import print_function
   ...: from ipywidgets import interact, interactive, fixed
   ...: import ipywidgets as widgets
   ...: 
```

- and everything imported fine.

```
In [2]: def f(x):
   ...:       return x
   ...: 

In [3]: interact(f, x=10);
....
AttributeError: 'NoneType' object has no attribute 'session'
```

logfile attached:
[interact_logfile.txt](https://github.com/ipython/ipython/files/647500/interact_logfile.txt)

I'm not sure what the problem is. If you have any suggestions let me know. 

Thanks

**Comment by takluyver** [comment]
The widgets work in the Jupyter notebook, not in IPython terminal.

@SylvainCorlay it would be nice if the error was a bit more descriptive here.

**Comment by johnashcroft105** [comment]
That's a bummer. Is there a current command line version of this?

from IPython.html.widgets import interact, fixed



Or the only answer is to use jupyter?

**Comment by SylvainCorlay** [comment]
That is right, you need a web front-end.

**Comment by takluyver** [comment]
Opened ipython/ipywidgets#1037 for a clearer error message. Closing this issue as there's nothing to do in IPython.
