### ISSUE TITLE
Weird random behaviour with ClassicPrompts

### ISSUE THREAD

**Issue by baco** [ipython/ipython#10088]
When launching ``$ ipython --classic`` I randomly get the green colored ``>>> `` prompt or a colourless version of the ``In [1]: `` prompt:

![IPython ClassicPrompts](https://cloud.githubusercontent.com/assets/102958/21163711/71973446-c173-11e6-97aa-d139641fdd0e.png)

It happens with either the package version from Debian repositories or with the pip-installed version.

**Comment by takluyver** [comment]
I have reproduced this, and I'm trying to track it down.

**Comment by takluyver** [comment]
It was the config system trying to be clever. I'm not fond of the config system. ipython/traitlets#355 should fix it.
