### ISSUE TITLE
IPython display can wrongly decode SVG

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#10086]
cf https://github.com/matplotlib/matplotlib/issues/7611

it seem like the read flags of an "open" call should get an extra "b" flag.

**Comment by takluyver** [comment]
I think adding `b` is the right thing to do. The issue is that although XML is a text-based format, the encoding is declared inside the file, so you have to start reading the file as binary data to find what it is. Presumably minidom does the right thing with the encoding when we parse it.
