### ISSUE TITLE
Ctrl-C during exit confirmation prints the confirmation in the same line

### ISSUE THREAD

**Issue by sachet-mittal** [ipython/ipython#10098]
First of all I am not sure this is a bug or as per design. 

After Pressing Ctrl-D to exit we are asked confirmation to exit.
If we press any key except 'y' or 'n' the same question is asked again but this is done in a new line as shown below:
```
In [1]:
Do you really want to exit ([y]/n)? q
Do you really want to exit ([y]/n)? ads
Do you really want to exit ([y]/n)? sjfv
Do you really want to exit ([y]/n)?
```

But if we press Ctrl-C, the confirmation is asked in the same line:

```
In [1]:
Do you really want to exit ([y]/n)? Do you really want to exit ([y]/n)?
```

Expection: The confirmation should be asked in the newline.

**Comment by sachet-mittal** [comment]
system information:

```
root@ubuntu:~/nsx-qe/systest[9671](master)# python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': u'1be7c45',
 'commit_source': 'installation',
 'default_encoding': 'utf-8',
 'ipython_path': '/usr/local/lib/python2.7/dist-packages/IPython',
 'ipython_version': '3.1.0',
 'os_name': 'posix',
 'platform': 'Linux-3.2.0-26-generic-x86_64-with-Ubuntu-12.04-precise',
 'sys_executable': '/usr/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.3 (default, Sep 26 2012, 21:51:14) \n[GCC 4.7.2]'}
```

**Comment by sachet-mittal** [comment]
If the issue is accepted then I think the fix would be in:
https://github.com/ipython/ipython/blob/6a5220d032f5a60267b051783721aa0d5a0e3373/IPython/utils/io.py. ask_yes_no()

```
except KeyboardInterrupt:
       if interrupt:
             ans = interrupt
```

should become:
```
except KeyboardInterrupt:
       print("\r")
       if interrupt:
             ans = interrupt
```

**Comment by takluyver** [comment]
Sounds reasonable, though I'd probably put it after the `if interrupt` clause. Do you want to make a PR?

**Comment by sachet-mittal** [comment]
Yes. :)
But I am not sure about the procedure.
Do you mind guiding me in this regard?

**Comment by sachet-mittal** [comment]
The pull request for this is:
https://github.com/ipython/ipython/pull/10102

I am not sure if I followed the correct procedure or not.
Correct me if I am wrong.

**Comment by takluyver** [comment]
That's great, thanks. I've left a comment on there for one minor change.

**Comment by srinivasreddy** [comment]
pls close this issue :)
