### ISSUE TITLE
underscore broken in 5.1.0

### ISSUE THREAD

**Issue by talkaminker** [ipython/ipython#10095]
instead of having the last computation it holds:
`<bound method NullTranslations.gettext of <gettext.NullTranslations instance at 0x7f52f40945f0>>`
how to reproduce (at least on ubuntu 64-bit installed from conda)
```
>>> 1
1
>>> _
<bound method NullTranslations.gettext of <gettext.NullTranslations instance at 0x7f52f40945f0>>
```

downgrading to ipython 4.2 fixes the problem

**Comment by takluyver** [comment]
It's common for code that needs strings translated to bind `_` to the translation machinery globally for easy access. IPython does not do this,  but I guess that something else in your system is getting called and does it.

Places to look: the `$PYTHONSTARTUP` environment variable, IPython [startup files](http://ipython.readthedocs.io/en/stable/interactive/tutorial.html#startup-files), and `.pth` files (which can run code when Python launches).

**Comment by takluyver** [comment]
(For the record, I can't reproduce this problem on master)

**Comment by Carreau** [comment]
Actually we even have recent code that pay attention as whether `_` in the builtins not to shadow it. 

The lines you are likely looking for are something that does:

```
import gettext
gettext.install('<a string>')
```

This is waht replace underscore.
