### ISSUE TITLE
Add repr method for arbitrary mime-types

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#10090]
We have `_repr_foo_` methods for a few common mime-types, but this mapping doesn't extend well to custom mime-types. I propose we add a new magic method that returns the full, formatted mime data, such as:

```python
def _repr_mime_(self):
    """Return mimetype-bundled representation(s) of me"""
    return {
        'data': {
            'application/vnd.tableschema.v1+json': {...},
            'text/html': '<div>...',
        'metadata': {},
    }
```

details: should this override or be in addition to existing methods if found?

cc @rgbkrk

**Comment by rgbkrk** [comment]
Thanks for raising this up! It should likely override since it's a full manifest.

**Comment by minrk** [comment]
Oops, sorry for the dupe of #10058. Copying comment from there: The `_ipython_display_` escape hatch makes this less urgent (and is perhaps why we still haven't done it), but this should still be done nonetheless.

**Comment by Carreau** [comment]
Do any of you want to tackle that for 6.0, or should we bump to wishlist ?

**Comment by rgbkrk** [comment]
Wishlist is fine, I'm working on other items for the next couple weeks.
