### ISSUE TITLE
remove python 2.x specific code in IPython source repo.

### ISSUE THREAD

**Issue by srinivasreddy** [ipython/ipython#10106]
This is tracking issue for that.

- I removed iteritems(), xrange from repo. https://github.com/ipython/ipython/pull/10105

**Comment by srinivasreddy** [comment]
I think we can close this. Looks like i am done with remove python 2 stuff. If i miss anything, let me know.  :)

**Comment by takluyver** [comment]
Thanks @srinivasreddy
