### ISSUE TITLE
Preview raw command passed to shell and python/shell mixing

### ISSUE THREAD

**Issue by grmpyninja** [ipython/ipython#10111]
Is there a way to preview a raw command which is passed to shell for its execution?

I wanted to execute the following small piece of code

```
x = "aaaa bbb"
!echo "$x" | awk '{print $1}'
```

but apparently it simply doesn't work. I've figured out that the working code should look like this

```
x = "aaaa bbb"
!echo "{x}" | awk '{{print $$1}}'
```

but I simply tested multiple variations or quotes, double quotes, brackets and dollar sign. It'd be much easier to set some verbose mode to command executer to see the actual command after it's evaluated by ipython.

Anyway, is it the only way of mixing python and shell parameters? Isn't there a more elegant and more shell-like way of doing it? without all those escape sequences? (additional brackets and dollar). I'd like to copy paste the very same command to shell and get the results instead of escaping everything.

**Comment by minrk** [comment]
A flag to echo the command-to-be-executed would be useful. The method used to format these is `get_ipython().var_expand(line)`, which you can use to see what a command would be:

```python
ip = get_ipython()
ip.var_expand("""
echo "{x}" | awk '{{print $$1}}
'""")
```

We could implement a more bash-like parsing, which doesn't reach into single-quoted strings. That seems desirable, to me.

**Comment by eyaler** [comment]
In python single quotes and double quotes are equivalent, so this breaks python conventions, as well as the rule of least surprise.
Also, this is a major breaking change, as it has just broke tens of my google colabs.
