### ISSUE TITLE
shouldn't we run the build on windows as well?

### ISSUE THREAD

**Issue by srinivasreddy** [ipython/ipython#10116]
cc @minrk  @Carreau

**Comment by minrk** [comment]
Now that AppVeyor is a thing, it's worth doing. Would you like to explore adding appveyor configuration?

**Comment by srinivasreddy** [comment]
yes

**Comment by takluyver** [comment]
@srinivasreddy I've just noticed that while Appveyor is running on an impressive 8 Python installations, it runs `python -c 'True'`, which is perhaps not the most rigorous test of our code. ;-) Want to make it run the tests as well?

**Comment by takluyver** [comment]
Also, it currently installs IPython from PyPI, not from the checkout it needs to be testing.

**Comment by Carreau** [comment]
> `python -c 'True'`

I did that as appveyor was configured and test were not passing, so it was failing everywhere. (it was using nosetest instead of iptest at least).

This was not to block other PR on waiting the testing on Appveyor worked. @srinivasreddy may have missed that on the other PR.

**Comment by takluyver** [comment]
Ah, OK, sorry for wrongly pointing the finger. Let's get it running the tests, anyway.

**Comment by takluyver** [comment]
Fixed by #10164
