### ISSUE TITLE
pyreadline is not available on github

### ISSUE THREAD

**Issue by eric-wieser** [ipython/ipython#10129]
According to the ipython webpage, [the latest release is 1.7](https://ipython.org/pyreadline.html)

According to github, [the latest release is 2.0 + a few commits](https://github.com/pyreadline/pyreadline/commits/master)

According to PyPI, [the latest release is 2.1](https://pypi.python.org/pypi/pyreadline)

Where is the source code for 2.1, and why is it not on github? ( pyreadline/pyreadline#41 )

Pinging @jstenar

**Comment by takluyver** [comment]
Please file pyreadline issues on pyreadline's repo. IPython no longer uses pyreadline as of IPython 5.0.

**Comment by eric-wieser** [comment]
@takluyver: Good to know, but in that case shouldn't the pyreadline page on ipython.org be removed?

**Comment by takluyver** [comment]
Good point, just made ipython/ipython-website#123. I'm leaving a minimal page there to avoid breaking links.
