### ISSUE TITLE
Initial blank line of multiline output

### ISSUE THREAD

**Issue by kwankyu** [ipython/ipython#10138]
The following is normal.
```
In [1]: class Foo(object):
   ...: 
   ...:     def __repr__(self):
   ...:         return "foo"
   ...: 
   ...: 
   ...: class Bar(object):
   ...: 
   ...:     def __repr__(self):
   ...:         return "bar\nbar"
   ...:     

In [2]: Foo()
Out[2]: foo

In [3]: Bar()
Out[3]: 
bar
bar
```
But in Sage that uses IPython, the initial blank line for multiline output is just redundant.
```
sage: class Foo(object):
....: 
....:     def __repr__(self):
....:         return "foo"
....: 
....: 
....: class Bar(object):
....: 
....:     def __repr__(self):
....:         return "bar\nbar"
....:     
sage: 
sage: Foo()
foo
sage: Bar()

bar
bar
```
I am not sure if this is a bug of IPython or of Sage. I would appreciate comments by anyone who knows better.

**Comment by kwankyu** [comment]
I investigated this issue a bit more. The method `write_output_prompt` in the class `RichPromptDisplayHook` sets the attribute `prompt_end_newline` to true when the output prompt ends explicitly with `\n`. In Sage, the output prompt is just empty string. I think that in this case too, the attribute `prompt_end_newline` should be set true. Thus we can consider that the current erroneous behavior in Sage is caused by this bug in IPython.

**Comment by takluyver** [comment]
Sounds reasonable. Do you want to make a PR?

**Comment by kwankyu** [comment]
Actually I am not familiar with IPython code and collaborative development in Github. So it would take some time for me to make a pull request of a patch. If you or any one can do this easily, then I would be happy to concede.

**Comment by takluyver** [comment]
OK, see #10146
