### ISSUE TITLE
When do we want to drop Python 3.3 support?

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#10161]
Now that we're dropping 2.7 support, I've started to notice the points where supporting Python 3.3 requires extra work. For instance, 3.4 introduced `pathlib` and `unittest.mock` into the standard library, so we have a couple of dependencies which are only needed on 3.3.

It also means tests take longer, especially on Appveyor which only runs one build at a time.

Python 3.4 was released in March 2014, so it's not yet 2 years old. So I don't think we should drop 3.3 yet, but I wanted to open the discussion.

**Comment by willingc** [comment]
Perhaps match the end-of-life date that is published by CPython: 2017-09-29

Currently, CPython releases are typically end-of-life at 5 years from original release date.
[Reference](https://docs.python.org/devguide/#status-of-python-branches)

**Comment by takluyver** [comment]
That sounds like a reasonable date. Thanks!

**Comment by Carreau** [comment]
Agreed, that's seam reasonable. 

We have 2 ways of seeing that (in general):
  - Stop support slightly after, cause their might still be bugfixes, and we usually release version with  support for X.y after X.y got released, so all is delayed. 
  - Stop supporting a bit before to give a signal to Python core that they can safely stop support as no new release will target X.y.

Also I don't see any reason, nor think we should stop support in between minor revisions. 

Also I'm going to guess this is prompted by #10159. I did not meant to drop support for 3.3 in it, I'll put that on the jetlag.

**Comment by minrk** [comment]
👍 for EOL + ϵ as the time to start considering it. I'd like to keep the bar for dropping any kind of support as "maintaining support for X is causing a problem".

**Comment by Carreau** [comment]
> for EOL + ϵ as the time to start considering it. I'd like to keep the bar for dropping any kind of support as "maintaining support for X is causing a problem".

I think that's also a question of what do we call "support" we can perfectly go through:
- Not officially supported in docs
- Not tested
- No active bugfixes, but PR welcome
- actively incompatible.

Also "is causing a problem" can be quite subjective :-)

**Comment by willingc** [comment]
Looks like numpy may have already dropped 3.3 support [Travis build on recent IPython doc PR](https://travis-ci.org/ipython/ipython/jobs/192415150) cc/@takluyver

**Comment by Carreau** [comment]
> Looks like numpy may have already dropped 3.3 support Travis build on recent IPython doc PR  cc/@takluyver numpy changelog

Yep, just noticed that. Download [for last year](https://bigquery.cloud.google.com:443/savedquery/420132102859:c4b683833c6245f591b9461c600c154e):
- 3.2: `  2 230`
- 3.3: ` 19 913`
- 3.4: `552 197`
- 3.5:  `758 073`
- 3.6: ` 11 891`

**Comment by takluyver** [comment]
I've got the tests running on Travis again by only installing numpy on 3.4 and above.

**Comment by minrk** [comment]
@Carreau good point about stages, I mainly refer to the last stage. I only meant that dropping support should only be done as part of "solving a problem", rather than a "deadline passed, breaking everything now" sort of thing. That could be a new feature or bugfix that requires 3.4 syntax, import machinery, etc. As time goes on, the bar for whether a problem is enough to trigger dropping support vs being worked around gets lower and lower. You are right that it's completely subjective, but I trust that we can make these completely subjective decisions together when the time comes.

**Comment by Carreau** [comment]
One more point to drop 3.3 (and 3.4.. but I understand this one is harder to justify). 
I'm working with `async/await` and they are syntax error in 3.3/3.4 which make testing hard as nose seem to refuse to not even try to parse file and crash, unless I get to crazy hacks like `eval` in current namespace.

**Comment by hugovk** [comment]
CPython 3.3 reaches end-of-life this week: 2016-02-27.

https://en.wikipedia.org/wiki/CPython#Version_history

**Comment by takluyver** [comment]
Thanks for the reminder. I've opened #10833 to drop support. Rereading this, though, I realise I'm being more aggressive about it than Min suggested. I'm happy to wait until we're considering a change that would break 3.3 support, but I also think there's an argument for clearly signalling to users and contributors that we're targeting 3.4+.

**Comment by willingc** [comment]
I think most are on 3.4 or higher. Thanks @takluyver.

**Comment by hugovk** [comment]
Here's the pip installs for ipython from PyPI for the last month, confirming over 99% are on 2.7 or 3.4+:
```
$ pypinfo --percent --pip ipython pyversion
python_version percent download_count
-------------- ------- --------------
2.7              50.6%        576,607
3.6              18.3%        208,524
3.4              16.8%        191,688
3.5              13.5%        153,345
2.6               0.6%          6,902
3.7               0.1%          1,258
3.3               0.1%            873
None              0.0%             16
3.2               0.0%             10
3.1               0.0%              1

```

**Comment by hugovk** [comment]
https://github.com/ipython/ipython/pull/10833 has been merged. Can this be closed?
