### ISSUE TITLE
Rename wiki gallery page?

### ISSUE THREAD

**Issue by fperez** [ipython/ipython#10166]
We have two options for the title of our gallery page:

1. [Its old name that refers to "IPython" notebooks](https://github.com/ipython/ipython/wiki/A-gallery-of-interesting-IPython-Notebooks), 

1. perhaps better would be to use [Jupyter explicitly in the name](https://github.com/ipython/ipython/wiki/A-gallery-of-interesting-Jupyter-and-IPython-Notebooks).

The problem with renaming from option 1 to option 2 the title of the page dictates the URL.  So if we rename the page, the URL changes and all existing links everywhere, search engine optimization, etc, falls out of date.  This is just how the Github wiki works.  Furthermore, there's no way to set up a proper HTML redirect.  In the past I tried to make this change and got bitten by it, I ended up reverting it for that reason.  Most recently it happened to @JamiesHQ as well.

The fact that it's happened to both @JamiesHQ and me is indicative that it's a natural trap to fall into, and it will probably keep on happening.

@rgbkrk seemed to be in support of changing, though @Carreau was concerned about search engine optim. and links that will never be updated.

If we move forward, the best we can do would be to add to [the old URL](https://github.com/ipython/ipython/wiki/A-gallery-of-interesting-IPython-Notebooks) a short note that points to the new page.

Even though I backed out myself earlier on, I'm now thinking that we should just bite the bullet and do it.  It already hit Jamie and it will likely happen again, so might as well.  Eventually old links will get updated and fresh, high-value content will point to the new one.

Thoughts?

**Comment by rgbkrk** [comment]
Facts:

* We can't change all the old links
* Google will only adjust rankings once a new page is in place
* Scattered pages with conflicting naming affect the marketing of Jupyter
* People will tend to link the source of truth, not an intermediate page

Creating new pages has to be done swiftly and with firm leadership. Thanks for kicking this off.

We also need to move the "IPython kernels" and "URL Mapping" page. Should we establish these wiki pages on jupyter/jupyter?

**Comment by fperez** [comment]
Thanks @rgbkrk, good point about the other pages we need to keep in mind. Can you think of any others?  This point reinforces my thought that we should bite the bullet and do the move, and include all relevant pages that are jupyter-generic (and I agree that they should move to the jupyter/jupyter wiki).  While wikis are an imperfect tool and they get messy/weedy over time, they are still very valuable for this kind of table/list information that needs tons of very small updates from a wide range of people with minimal effort.  I'm convinced if we had those tables in our static docs, they would see a fraction of the contributions, as the barrier would be too high.

**Comment by rgbkrk** [comment]
Done, moved all three with references into jupyter/jupyter.

Totally agree with the wiki vs. documentation barriers to entry.

**Comment by rgbkrk** [comment]
* https://github.com/jupyter/jupyter/wiki/A-gallery-of-interesting-Jupyter-and-IPython-Notebooks
* https://github.com/jupyter/jupyter/wiki/Jupyter-kernels
* https://github.com/jupyter/jupyter/wiki/Jupyter-Notebook-Server-API

**Comment by fperez** [comment]
Should we take the opportunity to rename the gallery to be just "interesting Juptyer notebooks"?  For the notebooks, it's probably ok at this point (and thinking of the future) to stick to the Jupyter branding in the title (the main text can retain Jupyter/IPython for ease of discoverability and to maintain institutional memory).

**Comment by JamiesHQ** [comment]
Thanks @fperez & @rgbkrk - I appreciate you moving this through! I would like the page to say Jupyter Notebooks; however, in a quick glance through a couple online courses that use the notebook, some are still using  "IPython Notebooks" so there may be value in keeping IPython in there for the time being. I don't have strong feelings about it either way though.

**Comment by rgbkrk** [comment]
I think we can include IPython in the body, we should probably keep the URL the way we want it to fit marketing wise.

**Comment by willingc** [comment]
cc @ruv7 @ellisonbg

**Comment by fperez** [comment]
Yup, my suggestion was to do:

* Title: Jupyter only - long term.
* Body: Jupyter/IPython - preserve memory, increase discoverability.

How does that sound?

**Comment by damianavila** [comment]
> How does that sound?

Good!

**Comment by minrk** [comment]
@fperez sounds great! I've been using Jupyter notebook as much as possible when talking about the project, but keeping "IPython Notebook" as a valid term referring to a notebook that uses the IPython kernel, as opposed to an "IJulia Notebook", which specifies that it uses the IJulia kernel, etc.

**Comment by fperez** [comment]
@minrk, I agree with you and often follow the same pattern :)

It seems everyone's happy with this.  I only have one question before we close: I think the new page should be titled simply "A gallery of interesting Jupyter Notebooks", *without* IPython in that name, using IPython only in the body.  Before we were doing both as a way to try to bridge from the old IPython wiki, but if we're going to clean this up, let's just do it right once and for all...  The overall name should be "Jupyter notebooks" (since those listed can be in any language, even if there's a preponderance of IPython ones), and we can mention IPython in the body.

Feel free to emojivote this, and we can wrap it up!

**Comment by takluyver** [comment]
I've updated the title. Hopefully not too many people have linked to the intermediate title in the last month.
