### ISSUE TITLE
Jupyter Notebook Error: error loading notebook

### ISSUE THREAD

**Issue by youfulei** [ipython/ipython#10174]
I had an issue opening any of my jupyter notebooks.

An unknown error occurred while loading this notebook. This version can load notebook formats v4 or earlier. See the server log for details.

[E 09:04:29.984 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/opt/packages/anaconda3.4.1.1/lib/python3.5/site-packages/traitlets/traitlets.py", line 501, in get
        value = obj._trait_values[self.name]
    KeyError: 'notary'

I have tried the following methods as suggested on similar issues, but none worked.

cd $(jupyter --data-dir) mv nbsignatures.db nbsignatures.db.bak

rm ~/Library/Jupyter/nbsignatures.db

rm ~/.ipython/profile_default/history_sqlite

rm ~/.ipython/profile_default/security/nbsignatures.db

**Comment by takluyver** [comment]
Can you check that your `notebook` and `nbformat` packages are up to date?

**Comment by youfulei** [comment]
Thanks takluyver. jupyter is version 4.1.0. Not sure how to check nbformat... Sorry, newbie here. A little more context. I'm using the notebook on a company server, I asked around and looks like nobody else had the same issue.

jupyter --version
4.1.0

**Comment by takluyver** [comment]
The easiest way to see the version of all the different bits is to run `pip list` (or `conda list` if you installed with conda). In particular, `jupyter --version` only gives you the version of the `jupyter_core` package, which may be different from the notebook version you're using.

**Comment by youfulei** [comment]
This is what I see on the conda tab on the notebook.
nbformat          4.0.1          py35_0
notebook          4.2.1          py35_0

**Comment by takluyver** [comment]
There should be newer versions of both of those if you want to upgrade with `conda update notebook nbformat`.

**Comment by youfulei** [comment]
My issue was resolved, looks like I accidentally added a c.session value instead of the default value in jupyter_notebook_config.py which was causing the issue. Once I commented out that line the issue is gone. I found this out only when I tried to copy a jupyter notebook file (which couldn't open but I tried anyway), it gave me an error message indicating some abnormal value of notebooknotary - I should have noticed it's the same type of error in log file, I just didn't know where to look for the notebook notary value. Thanks.

**Comment by bgpatel** [comment]
I get the same error i.e. An unknown error occurred while loading this notebook. This version can load notebook formats v4 or earlier. See the server log for details.

- I have tried everything that was suggested but still keep getting the same error.

Question: Where I can find this log file?
Thanks

**Comment by kashyapkitchlu** [comment]
i am getting the same error and i am unable to solve on kubuntu .kindly help.

**Comment by keineahnung2345** [comment]
Same problem here.

**Comment by waboke** [comment]
I am having the same issue.

**Comment by dicksonj** [comment]
Try clearing the hard disk memory! Jupyter creates this error while opening a new or existing notebook, if there is not enough disk space

**Comment by anchor228** [comment]
I had this problem and turns out I just ran out of space. So I deleted a bunch of large files and now I can open all my notebooks again.

**Comment by rsiu01** [comment]
I had this issue and it turned out to be the dropbox folder that I was using to save the notebooks. I had forgot that I turned on smart sync and it made the entire folder online only. After changing the smart sync settings to local only, I could open the notebook.

**Comment by xavbart** [comment]
> I had this issue and it turned out to be the dropbox folder that I was using to save the notebooks. I had forgot that I turned on smart sync and it made the entire folder online only. After changing the smart sync settings to local only, I could open the notebook.

Just adding comment to that effect : had migrated machine and DB defaulted to smartsync. So i got the dreaded message :

> An unknown error occurred while loading this notebook. This version can load notebook formats v4 or earlier. See the server log for details.

together with 

> OSError: [Errno 5] Input/output error:

Combo of both of those can be caused by files that are not saved locally by Dropbox, hope this gets the answer found on search engine for others.
