### ISSUE TITLE
No such comm target registered error

### ISSUE THREAD

**Issue by rylanchiu** [ipython/ipython#10188]
When I start a python3 notebook in conda environment, I got such an error in terminal:

    [I 21:59:46.185 NotebookApp] Creating new notebook in /Untitled Folder
    [I 21:59:47.071 NotebookApp] Kernel started: a8c53aaf-8282-479d-b3ec-afb9433c30e6
    [IPKernelApp] ERROR | No such comm target registered: ipython.widget

But if I start python2 instead, this error disappears. Do you know how I can deal with this problem? Thanks in advance!

**Comment by takluyver** [comment]
I think you can safely ignore it, but if you prefer not to, I think installing the ipywidgets package should make it go away.

**Comment by rylanchiu** [comment]
@takluyver Thanks for your quick reply. It works perfectly!
