### ISSUE TITLE
%s will be deprecated please use string.format(...)

### ISSUE THREAD

**Issue by srinivasreddy** [ipython/ipython#10194]
This is tracking issue for replacing 
```
(%s, %s) %("one", "two") 
```
with 
```
"{},{}".format("one", "two")
```

**Comment by Carreau** [comment]
`%s` is not deprecated, it is deemphasized (which is different). If it was deprecated then it would be written in the docs, and it would issue a DeprecationWarning, or a PendingDeprecationWarning more exactly (which ipython test-suite enable [by default](https://github.com/ipython/ipython/blob/master/IPython/testing/iptest.py#L49)). 

There is also a difference in what `%s` vs `.format()` does, in that format is a method call, so have to do extra lookup, `%s` is faster, and may even in some case allow (IIRC) the python peephole optimizer to fold values. 

While it's true that we should prefer `.format()` when possible, it is regularly more cumbersome than `.format()`, and you will annoy a few people it you replace their `%s` with `{}`, so be careful.

**Comment by takluyver** [comment]
I think the `%s` style formatting was briefly considered deprecated - the 3.1 docs describe it as such, but it is still very widely used, and newer versions just recommend the `{}` style without saying that `%s` is deprecated.

I think we should generally try to use `{}` formatting in new code, but I'm not even consistent about that. Changing all of the existing code away from `%s` is not useful - Matthias described our objections to big 'cleanups' in #10195.

(For the record, any performance difference is almost never going to be important, so please don't start changing code the other way in an effort to make things faster.)

Closing this as I don't think it's something we want to do.
