### ISSUE TITLE
Releasing 5.2

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#10218]
@takluyver , @minrk there are 2 pending PRs (including one backport, which is just waiting for test to pass)  for 5.2.

Any objection of me releasing 5.2 after that ?

@willingc you also asked to be pinged on any new release IIRC.

**Comment by Carreau** [comment]
Correction, both are backports now. (Thanks @takluyver)

**Comment by takluyver** [comment]
Sounds good to me. I assume you have done/will do a quick scan of the issues without a milestone to see if there's anything that should be fixed quickly? I would offer to do it, but it's late here, so I'm not going to be doing much until tomorrow.

**Comment by Carreau** [comment]
> Sounds good to me. I assume you have done/will do a quick scan of the issues without a milestone to see if there's anything that should be fixed quickly? I would offer to do it, but it's late here, so I'm not going to be doing much until tomorrow.

Already did on friday, but yes, I reviewed all things marked 5.2 not backported, backported them, and merged them, plus did a quick tour of what's new.

**Comment by minrk** [comment]
Sounds great, thanks @Carreau!

**Comment by Carreau** [comment]
OK, I'll release later when I'm not tethering then :-)

**Comment by Carreau** [comment]
In progress....

**Comment by Carreau** [comment]
Closing in order to close milestone.
It is uploaded to PYPI, and pushed so need to : 
   - draft/post annouce, 
   - update conda forge
