### ISSUE TITLE
NameError: name 'warnings' is not defined

### ISSUE THREAD

**Issue by kernc** [ipython/ipython#10236]
IPython 5.2.1 (current stable) doesn't start. Run as jupyter-notebook or as ptpython, it errors:
```text
Traceback (most recent call last):
  ...
  File "/home/user/.venv/test/lib/python3.4/site-packages/IPython/core/completer.py", line 546, in _limit_to_all_changed
    warnings.warn('`IPython.core.IPCompleter.limit_to__all__` configuration '
NameError: name 'warnings' is not defined
```
The [`import warnings` line in the offending file](https://github.com/ipython/ipython/blob/8970389fbc7a64279ffb9b62fcb0ad176f4084f0/IPython/core/completer.py#L28) seems to [not have been backported](https://github.com/ipython/ipython/blob/5.2.1/IPython/core/completer.py).

**Comment by takluyver** [comment]
Just released 5.2.2, which should fix this.
