### ISSUE TITLE
Autoreload Enum Error

### ISSUE THREAD

**Issue by alexmarder** [ipython/ipython#10232]
I'm getting a weird error when trying to use autoreload and Enums. I have an Enum class defined in a file as:
```python
class MyEnum(Enum):
    A = 'A'
    B = 'B'
```
Using `%autoreload 2`, if I try to add `C = 'C'` to `MyEnum`, or remove an existing definition, I get the following error:
```
[autoreload of updates_type failed: Traceback (most recent call last):
  File "/home/amarder/anaconda3/lib/python3.5/site-packages/IPython/extensions/autoreload.py", line 247, in check
    superreload(m, reload, self.old_objects)
RecursionError: maximum recursion depth exceeded
]
```
Sometimes it is a different error:
```
[autoreload of updates_type failed: Traceback (most recent call last):
  File "/home/amarder/anaconda3/lib/python3.5/site-packages/IPython/extensions/autoreload.py", line 247, in check
    superreload(m, reload, self.old_objects)
AttributeError: __abstractmethods__
]
```

I'm running the code on Debian Linux, using Anaconda with python 3.5.

**Comment by takluyver** [comment]
autoreload is a bit black magic, so it's not a big surprise when it breaks.

I'd guess that the recursion error is because enum values have a reference back to their class (e.g. `MyEnum.A.__objclass__`, so there's an infinite chain of attributes that it's trying to replace: `MyEnum.A.__objclass__.A.__objclass__.<etc>`

**Comment by alexmarder** [comment]
If that's true, is there a way to mark a class as having been already reloaded so autoreload does not try again?

**Comment by takluyver** [comment]
Not at present. Actually, I now think my guess was wrong; MyEnum.A is not a type, so it should be updated like that. You can see the code updating a class object here:
https://github.com/ipython/ipython/blob/e8341164d5f525a3bb3bf440cb042cc8145a5642/IPython/extensions/autoreload.py#L276

**Comment by Carreau** [comment]
seem like in `update_class` the two references `old_obj` and  `new_obj` can be the same (I'm going to guess that's the point of enums, where instances are shared. 
So `continue` if they are the same should be enough.

**Comment by Carreau** [comment]
also we should bump the number of stacks shown to something like 10-ish (or make it configurable) to be able to debug things like that better.
