### ISSUE TITLE
ipython 5.2.0-py36_0 (conda-forge) is broken 

### ISSUE THREAD

**Issue by meowklaski** [ipython/ipython#10242]
``` 
ipython 

Traceback (most recent call last):
... 
File "/Library/anaconda/envs/py36/lib/python3.6/site-packages/IPython/core/completer.py", line 546, in _limit_to_all_changed
    warnings.warn('`IPython.core.IPCompleter.limit_to__all__` configuration '
NameError: name 'warnings' is not defined
```

I can't find where `import warnings` was deleted from IPython/core/completer.py in the commit history. It seems to always be present. Anyway, it is missing in the released code on conda-forge. Perhaps a bad merge.

Reverting to 5.1.0 is a temporary solution.

**Comment by takluyver** [comment]
5.2.2 is out, there's a PR here to update it on conda-forge:
https://github.com/conda-forge/ipython-feedstock/pull/26

**Comment by meowklaski** [comment]
Just curious - how did 5.2.0 make it passed unit testing? (not being snarky, genuine question)

**Comment by takluyver** [comment]
There's something set in your config (`IPCompleter.limit_to__all__`) which it's trying to warn you about, which is what goes wrong. The tests usually run with the default config, so that warning wasn't tested.

**Comment by Carreau** [comment]
Thanks @takluyver  !

**Comment by Carreau** [comment]
Closing as newer version got released.
