### ISSUE TITLE
_ipython_display_, return value, and output prompt behavior

### ISSUE THREAD

**Issue by TomAugspurger** [ipython/ipython#10247]
I might have found a strange interaction between `_ipython_display_` the in output prompt system. Given this file:

```python
# tst.py
from IPython import display

class A:
    def __repr__(self):
        return "    A\n0   B"


class B(A):
    def _ipython_display_(self):
        data = {'text/plain': repr(self)}
        display.display(data, raw=True)

class C(B):
    def _ipython_display_(self):
        super()._ipython_display_()
        return "C"
```

Here's the output:

```python
In [1]: from tst import *

In [2]: A()
Out[2]:
    A
0   B

In [3]: B()
Out[3]:     A
0   B

In [4]: C()
Out[4]:     A
0   B
```

I think the correct output for `In[3]` is just the `repr(self)`, but no `Out[3]` tag, since nothing is returned? I have no idea what the correct output of `In[4]` is, but maybe

```     
    A  # the super
0   B
"C"  # the return value of C._ipython_display_()
```
but I don't know if / where the `Out[4]` tag would go.

For background, we're working on a table schema repr for pandas in https://github.com/pandas-dev/pandas/pull/14904.

This is on IPython master from about 3 weeks ago.

cc @minrk

**Comment by minrk** [comment]
Thanks, @TomAugspurger! I think #10249 should fix it.
