### ISSUE TITLE
Running Bash Scripts in IPython

### ISSUE THREAD

**Issue by rvadaga** [ipython/ipython#10246]
I wrote a bash script, `run.sh` which has a python command with multiple options -

```
python train.py --lr 0.01 \
            --momentum 0.5 \
            --num_hidden 3 \
            --sizes 100,100,100 \
            --activation sigmoid \
            --loss sq \
            --opt adam \
            --batch_size 20 \
            --anneal true
```
I tried running this command in IPython -
```
!./run.sh
```
However, in IPython I'm not able to access the variables of the python script `train.py`. Is there some way to run the bash script in IPython so that I can access the variables? I don't want to copy paste the above command from the bash script each and every time.

I'm currently using IPython 5.1.0 on macOS Sierra.

**Comment by takluyver** [comment]
If you do it through a bash script, then it runs in a separate instance of Python, and the variables are lost when it finishes.

If you want to see the variables, you need to use the `%run` magic in IPython to run it in the same Python interpreter. If you want to avoid typing, you can use IPython's history to find the command again, or make it a macro with `%macro`.

**Comment by ivanov** [comment]
To rephrase what Thomas said, @rvadaga you should be able to do this from inside IPython.

I wrote a simple `foo.py`:
```python
import sys
print(sys.argv)
x = len(sys.argv)
```

And then I run it from IPython:
```
In [1]: %run foo.py
['foo.py']

In [2]: %run foo.py --hello there
['foo.py', '--hello', 'there']

In [3]: x
Out[3]: 3
```
