### ISSUE TITLE
ctrl-z does not suspend to background in debugger

### ISSUE THREAD

**Issue by nonagonal** [ipython/ipython#10254]
I'm using IPython 5.2.2 under Ubuntu and within ipdb, ctrl-z no longer suspends the process.

It looks like the problem is that in terminal/debugger.py, the call to create_prompt_application is not passing enable_system_bindings=True, so prompt_toolkit is not enabling the shortcut ctrl-z -> suspend process.

Would it be possible to have system bindings enabled? From the prompt toolkit source it looks like this simply enabled ctrl-z on systems which support suspending the process. The only other side effects I see are applicable only in emacs and vi modes (where other system shortcuts are enabled).

**Comment by takluyver** [comment]
You're always in one of emacs or vi modes (emacs is the default, vi is an option), so I'd like to know what the other ones are before doing this. If it's too much, we can just set a shortcut for Ctrl-Z specifically.

**Comment by nonagonal** [comment]
Aha I didn't realize you're always in one of those modes. There's indeed a few more then (from prompt_toolkit/key_binding/bindings/emacs.py): meta-! to open system prompt, esc/ctrl-g/ctrl-c to cancel it, ctrl-j to run a system command.

**Comment by takluyver** [comment]
OK, I think in that case I'd rather just enable Ctrl-Z. PR coming up.

**Comment by nonagonal** [comment]
Awesome, thanks! Apologies for my ignorance but should I close the issue or will someone else do that at a later time?

**Comment by takluyver** [comment]
No problem - it will get closed automatically when someone merges the PR.
