### ISSUE TITLE
Ipython show old code

### ISSUE THREAD

**Issue by vladimircape** [ipython/ipython#10252]
I had a code
"hi = img-resize(lo,hw)"
but got
NameError: global name 'low' is not defined
I even restart kernel,not helps

Exception AssertionError: AssertionError("Nesting violated for default stack of <class 'tensorflow.python.framework.ops.Graph'> objects",) in <bound method InteractiveSession.__del__ of <tensorflow.python.client.session.InteractiveSession object at 0x7f25fd3bc590>> ignored
Exception AssertionError: AssertionError("Nesting violated for default stack of <type 'weakref'> objects",) in <generator object get_controller at 0x7f25faef05a0> ignored

**Comment by takluyver** [comment]
Sorry, it's not clear from your description what's going wrong. Where do you have that code?

**Comment by vladimircape** [comment]
I delete some Tensorflow files, and error disappear.

**Comment by takluyver** [comment]
Ok, closing this, then.
