### ISSUE TITLE
Add 'v' binding in vi-navigation-mode to %edit (#10225) -- rollback or not?

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#10259]
In #10225 I added a keybinding so that when using vi keybindings, 'v' in normal mode edits the current input in $EDITOR.  This behavior is consistent with readline and zsh's vi-mode.

However I failed to consider that 'v' is actually already bound by PTK to visual mode (i.e. highlight-select), which is the behavior of vi and vim (the editors).

I still think the former is much more useful than the latter when working at a prompt, but I'm opening this issue just in case others want to propose to revert the PR.

Apparently I have a habit of proposing questionable ideas (see #9449)....

**Comment by takluyver** [comment]
Added to the milestone for the next release so we can consider this. Could you mention it on the ipython-dev mailing list so more people can weigh in?

My inclination is that vi mode should probably be based on what vi does, but I don't use vi mode.

**Comment by anntzer** [comment]
There's what vi (the editor) does and what vi (the readline/zsh mode) does...  I'll write an email to the mailing list.

**Comment by anntzer** [comment]
Actually let's ping @jonathanslenders first, given that he already had to deal with similar issues in https://github.com/jonathanslenders/python-prompt-toolkit/issues/431.

**Comment by jonathanslenders** [comment]
I think this is just a matter of preference or configuration. Either we have 'v' open the $EDITOR, or we go in selection mode.

By the way, you can enable/disable it by passing True or False to ``enable_open_in_editor``:
https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/key_binding/manager.py#L51

**Comment by takluyver** [comment]
Aha! Why don't we make a config option for that, and leave visual mode as the default, and then people who want to use `v` that way can set the option.

We need to think about what we call the option, because we have F2 to open in editor, regardless of that setting. `editor_editor_bindings`? :-P

**Comment by anntzer** [comment]
@jonathanslenders totally hijacking this thread, but it looks like you have a duplicated line in your docstring for this option (line 35/36)
