### ISSUE TITLE
failure to recognize complete line after `{:#.2g}.format(42)`

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#10268]
Tested both on IPython 5.2.2 and master, with Python 3.6.
`"{:.2g}".format(1)<ENTER>` triggers evaluation of the code, as expected.  But adding a `#` to make it `"{:#.2g}".format(1)<ENTER>` (which is a valid format specifier -- try `format(1, "#.2g")`) makes <ENTER> not trigger code evaluation anymore -- IPython seems to believe the expression is not complete.

**Comment by takluyver** [comment]
#10270 should resolve this.
