### ISSUE TITLE
Simplify InputSplitter

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#10272]
InputSplitter was originally developed with a stateful API in mind mostly because Readline was feeding input one line after another. Now that we do not use readline, we should be able to get rid of its statefulness.

That's no hurry, it's mostly code cleaning. Assigning @takluyver, ~~but as marking that we welcome anyone that would like to try it.~~ 

We might want a deprecation period as well before actually removing.

**Comment by takluyver** [comment]
This is one that I actually don't want to invite people to try. That code is old, tricky and critical - exactly the sort of thing where someone with good intentions could come in to do a helpful bit of cleanup and cause subtle breakage. I asked to be assigned on it to gently ward people off. I'd rather one of the core team did this - and as I'm the most familiar with that part of the code, I'm the first choice to look at it. ;-)

**Comment by Carreau** [comment]
Fair enough. I stoke the comment i posted initially  then.

**Comment by Carreau** [comment]
Closing, has this have been fixed by #11041.
