### ISSUE TITLE
Crash when execute "''.join?" or "'' join?" or "''.join??'

### ISSUE THREAD

**Issue by shengdexiang** [ipython/ipython#10289]
No matter when I open a new ipython session and execute `''.join?` or `'' join?` or `''.join??` or `'' join??`, it creashs.
[Crash_report_ipython.txt](https://github.com/ipython/ipython/files/768417/Crash_report_ipython.txt)

**Comment by takluyver** [comment]
Thanks. The fix should be in PR #10231 . In the meantime, you can work around this by downgrading prompt_toolkit to <1.0.10.

**Comment by takluyver** [comment]
Closing as this is fixed in master; we're heading towards a new release that will include the fix.
