### ISSUE TITLE
Python completions come up inside strings

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#10283]
I have files called e.g. `embed-test.py`. If I type `open('embed-<TAB>`, I see this:

![screenshot from 2017-02-10 14-16-38](https://cloud.githubusercontent.com/assets/327925/22829715/d16cd64a-ef9b-11e6-9d04-fae716eced55.png)

I think this is new with the Jedi completion system. We shouldn't be calculating Python completions when we're inside a string literal.

**Comment by tonyzhoujingtao** [comment]
Do you expect no completion or intelligently showing files in the current directory?

**Comment by takluyver** [comment]
The files - it already does this, but those completions are getting buried amidst the erroneous completions in master.

**Comment by Carreau** [comment]
> The files - it already does this, but those completions are getting buried amidst the erroneous completions in master.

That a side effect / compound effect  of Jedi + IPython completion. 
technically there is 2 bugs: 
   1) Jedi return only the part after the `-` (abs, all, and), 

But because IPython requires all completion to have the same start and end, and that IPython does return `embed-test`, then the wrapper have to "pad" jedi completion with `embed-`.

**Comment by takluyver** [comment]
Right, the padding makes sense, but I don't want those completions in that
place at all.

**Comment by Carreau** [comment]
Opened https://github.com/davidhalter/jedi/issues/860. I have an idea fro a workaround.

**Comment by Carreau** [comment]
> Right, the padding makes sense, but I don't want those completions in that
> place at all.

Just as a note, `open('<tab>` and `open('embed-<tab>` are two different cases, one of which is a regression and simple to fix (see #10286) the other one being the current behavior of IPython since long ago, and would require quite a bit more refactor.

**Comment by takluyver** [comment]
Fixed for now by #10286.

The follow up issue #10292 is to move to a cleaner fix when possible.
