### ISSUE TITLE
Jupyter Notebook toolbar not coming up

### ISSUE THREAD

**Issue by sunladyjoy** [ipython/ipython#10291]
![jupyter notebook](https://cloud.githubusercontent.com/assets/1957700/22878906/957f139a-f1a9-11e6-9881-4e66b33ccf74.png)

Installed Anaconda, Python 3.6, Launched Jupyter Notebooks, new folder, typed in short code to run (teaching myself Python), and then noticed there isn't a toolbar installed.  New to Anaconda and Jupyter Notebooks, assistance appreciated!

**Comment by takluyver** [comment]
Hi Joy! You appear to be editing a text file there. Jupyter has a very basic text editor embedded, but its main focus is on *notebooks*, documents with code cells and markdown cells. You can create a notebook from the file list with the *New* button: the section at the bottom of the pop-up menu is for notebooks.

**Comment by sunladyjoy** [comment]
That is what I did, then typed in the code you see.  I had not realized
that the toolbar didn't show up.

**Comment by willingc** [comment]
Hi @sunladyjoy,

When you launch Jupyter notebooks, do you see?

<img width="1173" alt="screenshot 2017-02-13 08 43 27" src="https://cloud.githubusercontent.com/assets/2680980/22892829/b54a8334-f1c8-11e6-9f2b-d4dbc63abb94.png">

If you do (note: it may look slightly different than on my development machine), then select New on the righthand side and choose Python 3 (or Python) from the dropdown.

<img width="1203" alt="screenshot 2017-02-13 08 43 47" src="https://cloud.githubusercontent.com/assets/2680980/22892840/bd78fa04-f1c8-11e6-9c94-429b05f0e052.png">

Now, you should see a notebook like this.

<img width="1199" alt="screenshot 2017-02-13 08 44 01" src="https://cloud.githubusercontent.com/assets/2680980/22892851/cdbc461e-f1c8-11e6-98cd-044da72c1f9d.png">

Enter your code in the cell. Then hit Shift-Enter to run.

Hope this helps :smile:

**Comment by sunladyjoy** [comment]
Thank you!  I think that will do it!  I have to wait until tonight to try
as Jupyter is on the laptop I leave at work.  Guess I should install it
here too!

**Comment by willingc** [comment]
Hi @sunladyjoy, You are very welcome. Feel free to @-mention me if you run into any hurdles.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. We didn't hear back from @sunladyjoy, hopefully that's because the issue was resolved with the extra pointers.

Thanks everyone and happy hacking! :bowtie:
