### ISSUE TITLE
where's iPython 6.0?

### ISSUE THREAD

**Issue by anderson-dan-w** [ipython/ipython#10309]
Documentation at [read the docs](https://ipython.readthedocs.io/en/latest/about/index.html) says iPython 6.0 is available, but currently in development. How does someone get access to it? All the documentation is for installing current latest *stable* release, aka 5.2.2 - the docs say "just `pip install ipython`" or to download the latest tarball from PyPi - but neither of those allow the user to specify they want iPython 6.0

**Comment by willingc** [comment]
Hi @anderson-dan-w,

Here's some documentation on building a development version: https://ipython.readthedocs.io/en/latest/install/install.html#devinstall

**Comment by anderson-dan-w** [comment]
Ah geez, I need to scroll about ...2 lines further. Sorry! And thanks for the prompt response!
