### ISSUE TITLE
InteractiveShell.magic is deprecated but is what we use in history.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#10327]
All in title.

**Comment by srinivasreddy** [comment]
I do not understand, and could you please care to explain?

**Comment by takluyver** [comment]
There's a method called `InteractiveShell.magic` that we use somewhere in the history code (not sure where - you could have been more precise, @Carreau ;-). We're now encouraging people to use `InteractiveShell.run_line_magic` instead.

**Comment by Carreau** [comment]
You can see that magic is used in a couple of places (interaciveshell, line 2029) we call `self.magic('color %s` % self.colors)` instead of `self.run_line_magic('color', self.colors)`.

And if you run the hist magic:
```
In [1]: time 1+1
CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 5.72 µs
Out[1]: 2

In [2]: hist -t
get_ipython().magic('time 1+1')
get_ipython().magic('hist -t')`
```

You see that what was executed is `get_ipython().magic(...)` instead of `get_ipython().run_line_magic()`

**Comment by Carreau** [comment]
(Note, one possible thing is to un-deprecate magic if it's too painful to update.

**Comment by srinivasreddy** [comment]
I am taking it

**Comment by adityausathe** [comment]
We need to also make changes to a lot of core test cases, if we replace `get_ipython().magic(..)` with `get_ipython().run_line_magic(..)`. We can simply un-deprecate `get_ipython().magic(..)`.

**Comment by Carreau** [comment]
> We need to also make changes to a lot of core test cases, if we replace get_ipython().magic(..) with get_ipython().run_line_magic(..). We can simply un-deprecate get_ipython().magic(..).

Yes, we can also undeprecate `magic()`, in general we should figure out why (and when?) it was deprecated. It is still likely something we want to keep for backward compatibility for a while anyway.

**Comment by adityausathe** [comment]
Please, have a look at PR #10638. I have resolved the issue and also kept backward compatibility support for `get_ipython().magic()`
