### ISSUE TITLE
Road to 6.0

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#10329]
We are closing in on 6.0 (I think). There are [35 open issues/PR](https://github.com/ipython/ipython/milestones/6.0) targeted 6.0 and [about 10 for 5.3](https://github.com/ipython/ipython/milestones/5.3). While usually we would stop working on 5.x after 6.0, 5.x is our LTS, so I don't want to block on it too much. Ie 5.3 can happen post 6.0 and we'll likely have a 5.4 and 5.5. 

I'll use this as a meta issue to track the status of 6.0 release. 

## Completer API.

Notebook 5.0 is about to be released, so I don't see a point in refactoring Completion API to send extra info in metadata now. I think we can experiment with 5.1/Lab

Completer API is marked as unstable so we can still make changes afterward the old API has not been removed. 

AFAICT, we have no more crashes with Jedi 0.10. I have pending PR to speed things up, but I doubt it's worth waiting for a 0.11 (we might want to bump to 0.10.1 though because of a messed up 0.10.tgz).

## pip magic

Twitter is happy about it, but would like more. Do we ? Do we backport to 5.3 ?

Many issues can be bumped or are significant refactor.

I'm worried about the GeoJson display class. Which is _relatively_ new. And whether is should be in core.

**Comment by Carreau** [comment]
cc @JamiesHQ , @willingc I'd like to have 6.0  out likely by mid March , at least be mid April to have it settled for PyCon.

**Comment by Carreau** [comment]
Oh, a Big thing to be careful, this release if Python 3 only.

**Comment by JamiesHQ** [comment]
I've created a card on the release calendar: https://github.com/orgs/jupyter/projects/4

**Comment by jtratner** [comment]
Just wanted to give you a heads up that the 6.0.0rc1 release is having a weird interaction with setuptools when unversioned `ipython` is a requirement - https://github.com/pypa/setuptools/issues/1009 (even though pip still seems to do the right thing so far).  I don't think this is anything you folks have control over, but I figure quite a few people will start hitting this soon.

**Comment by takluyver** [comment]
I guess setuptools' dependency finding thing doesn't know about the requires-python metadata which handles avoiding the version for pip. As suggested on that issue, does it work if you try `pip install -e .` instead of `python setup.py develop`?

I guess the most practical way forwards is going to be to patch projects that require IPython to do something like this:

```python
install_req = ['ipython']
if sys.version_info[0] < 3 and 'bdist_wheel' not in sys.argv:
    install_req.remove('ipython')
    install_req.append('ipython<6')

setup(
    ...
    install_requires=install_req
)
```

**Comment by jtratner** [comment]
Yes I think you are correct. (And pip install does the right thing). Like I
said, just wanted to give you a heads up.

**Comment by takluyver** [comment]
Thanks :-)

**Comment by Carreau** [comment]
I'm going to start the release process of 6.0.

**Comment by mpacer** [comment]
Ok, @Carreau has some issues with the github api but now we're back on track for the release schedule. 

note to all others: if you ever are getting 401's even from https://api.github.com, check your `.netrc` because `requests` will look there and automatically append authentication headers to your requests & they might be out of date.

**Comment by Carreau** [comment]
Strangely @takluyver appears to be the one uploading zip files to GitHub :-) 
https://github.com/ipython/ipython/releases/tag/6.0.0

**Comment by Carreau** [comment]
Released. Drafting the announcements.

**Comment by takluyver** [comment]
Weird, I don't know how it got that.

**Comment by takluyver** [comment]
👍 thanks for doing the release

**Comment by Carreau** [comment]
Can SO update RTD  and mark 6.0 as stable, I lost my PW and the reset link seem to not want to make its way my inbox. 

> Weird, I don't know how it got that

Hope your creds are not somewhere in the source tree.

**Comment by takluyver** [comment]
I hope so too!

I've updated the 'stable' version on RTD to point to 6.0.0.

**Comment by Carreau** [comment]
Cool thanks.

**Comment by Carreau** [comment]
TODO: 
 - [ ] BlogPost announce (@mpacer is on it)
 - [ ] Update IPython.org (I'm on it just need the blog post to be posted to get the URL)
 - [ ] Twitter
 - [ ] Mailing list
 - [ ] Conda forge in progress (https://github.com/conda-forge/ipython-feedstock/pull/29)
 - [x] PyPI done and 5.3 re-markes as still stable and unhidden.

**Comment by willingc** [comment]
Nice! :sunny:
