### ISSUE TITLE
ImportError: No module named shutil_get_terminal_size  (macOS 10.12.3)

### ISSUE THREAD

**Issue by ggrrll** [ipython/ipython#10323]
Hi,

I tried to install the dev version of matplotlib, following [this instructions](https://github.com/matplotlib/matplotlib/blob/master/README.osx), after I had some  [issue with a function.](https://github.com/matplotlib/matplotlib/issues/8122)

and I get this (apparently common) error `ImportError: No module named shutil_get_terminal_size `, when I type `ipython2` or `ipython`

**Comment by ggrrll** [comment]
some details:

- pip is in `/Library/Frameworks/Python.framework/Versions/3.6/bin/pip`
- python is in `/Library/Frameworks/Python.framework/Versions/3.6/bin/ipython`
- python2 is in `/usr/local/bin/ipython2`

**Comment by ggrrll** [comment]
also problems with pip:

-`pip3 install --upgrade pip` -> `Requirement already up-to-date`
- `pip install --upgrade pip` -> `The 'pip==9.0.1' distribution was not found and is required by the application` 
-`pip3.6 install --upgrade pip` -> `ImportError: Entry point ('console_scripts', 'pip3.6') not found`

**Comment by ggrrll** [comment]
`pip3 install --upgrade backports.shutil_get_terminal_size` gives `Requirement already up-to-date`

**Comment by ggrrll** [comment]
`find ~ -name backports`:

- `~/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/backports`
- `~/Python/2.7/lib/python/site-packages/backports`
- `~/Library/Python/2.7/lib/python/site-packages/future/backports`
- `~/Library/R/3.3/library/backports`
- `~/Library/R/3.3/library/backports/R/backports`

**Comment by takluyver** [comment]
Gah, I hate namespace packages :angry: .

Can you run this script and paste the output somewhere? There have been a series of people with similar problems, and I can't work out exactly what's causing it.

Debug script: https://gist.github.com/takluyver/73cf4e7e7cff4d95f3b23ea80d59bcab

**Comment by ggrrll** [comment]
thanks! here you go:

`python debug_namespace_pkg.py` gives: 

```
mod: <module 'backports' (built-in)>

backports.__path__ = ['/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/backports']

-- Found /Users/lazzari/Library/Python/2.7/lib/python/site-packages/backports --
Files: ['__init__.py', '__init__.pyc', 'ssl_match_hostname']
__init__.py contains:
# This is a Python "namespace package" http://www.python.org/dev/peps/pep-0382/
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)


-- Found /usr/local/lib/python2.7/site-packages/backports --
Files: ['configparser']
No __init__.py found

-- Found /Library/Python/2.7/site-packages/backports --
Files: ['__init__.py', '__init__.pyc', 'shutil_get_terminal_size']
__init__.py contains:
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
```

**Comment by ggrrll** [comment]
`python3.6 debug_namespace_pkg.py` gives: 

```
mod: <module 'backports' from '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/backports/__init__.py'>

backports.__path__ = ['/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/backports']

-- Found /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/backports --
Files: ['__init__.py', '__pycache__', 'shutil_get_terminal_size']
__init__.py contains:
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
```

**Comment by takluyver** [comment]
For Python 3, you shouldn't need that backports package at all - it's a backport of something that's already in Python 3.

For Python 2, can you try copying one of those `__init__.py` files it shows into `/usr/local/lib/python2.7/site-packages/backports`?

Once again, I'm mystified as to why or where it's finding `/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/backports`. :confused:

**Comment by ggrrll** [comment]
in `/Library/Python/2.7/lib/python/site-packages/backports/ __init__.py`:

```
# This is a Python "namespace package" http://www.python.org/dev/peps/pep-0382/
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
```

**Comment by ggrrll** [comment]
there is already similar file in that folder:
 `/usr/local/lib/python2.7/site-packages/backports/configparser/__init__.py`

**Comment by takluyver** [comment]
I meant putting one of those `__init__.py` files one level above that (in the `backports` folder rather than the `configparser` folder).

Have you got it working?

**Comment by ggrrll** [comment]
yeah, indeed...that's why I closed it :)

**Comment by takluyver** [comment]
Great :) Can we ask you to describe what you did, for anyone with a similar issue who reads this?

**Comment by ggrrll** [comment]
I copied `__init__.py` 
```
# This is a Python "namespace package" http://www.python.org/dev/peps/pep-0382/
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
```

in `/usr/local/lib/python2.7/site-packages/backports/`

**Comment by takluyver** [comment]
Ah, OK, it was my suggestion. I wasn't entirely expecting that to work, but apparently it did ;-)

**Comment by ggrrll** [comment]
yes...I worked straight away :)...such a simple, 'stupid' thing...
(this mean that someone else should fix it quickly )
