### ISSUE TITLE
ImportError: No module named shutil_get_terminal_size

### ISSUE THREAD

**Issue by nicolargo** [ipython/ipython#10347]
Hi, first of all thanks for this wonderful software.

I have a problem running ipython on my Ubuntu 16.04 laptop:

```
$ ipython
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 7, in <module>
    from IPython import start_ipython
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/ultratb.py", line 128, in <module>
    from IPython.utils.terminal import get_terminal_size
  File "/usr/local/lib/python2.7/dist-packages/IPython/utils/terminal.py", line 22, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size
```

I have try to upgrade it but everything looks up to date:

```
$ sudo pip install --upgrade ipython
The directory '/home/nicolargo/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nicolargo/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: ipython in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: pickleshare in /usr/local/lib/python2.7/dist-packages (from ipython)
Requirement already up-to-date: simplegeneric>0.8 in /usr/local/lib/python2.7/dist-packages (from ipython)
Requirement already up-to-date: traitlets>=4.2 in /usr/local/lib/python2.7/dist-packages (from ipython)
Requirement already up-to-date: backports.shutil-get-terminal-size; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from ipython)
Requirement already up-to-date: decorator in /usr/local/lib/python2.7/dist-packages (from ipython)
Requirement already up-to-date: pygments in /usr/local/lib/python2.7/dist-packages (from ipython)
Requirement already up-to-date: pexpect; sys_platform != "win32" in /usr/local/lib/python2.7/dist-packages (from ipython)
Requirement already up-to-date: pathlib2; python_version == "2.7" or python_version == "3.3" in /usr/local/lib/python2.7/dist-packages (from ipython)
Requirement already up-to-date: setuptools>=18.5 in /usr/local/lib/python2.7/dist-packages (from ipython)
Requirement already up-to-date: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python2.7/dist-packages (from ipython)
Requirement already up-to-date: enum34; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from traitlets>=4.2->ipython)
Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from traitlets>=4.2->ipython)
Requirement already up-to-date: ipython-genutils in /usr/local/lib/python2.7/dist-packages (from traitlets>=4.2->ipython)
Requirement already up-to-date: ptyprocess>=0.5 in /usr/local/lib/python2.7/dist-packages (from pexpect; sys_platform != "win32"->ipython)
Requirement already up-to-date: scandir; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython)
Requirement already up-to-date: appdirs>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from setuptools>=18.5->ipython)
Requirement already up-to-date: packaging>=16.8 in /usr/local/lib/python2.7/dist-packages (from setuptools>=18.5->ipython)
Requirement already up-to-date: wcwidth in /usr/local/lib/python2.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython)
Requirement already up-to-date: pyparsing in /usr/local/lib/python2.7/dist-packages (from packaging>=16.8->setuptools>=18.5->ipython)
```

Any idea to solve my issue ?

PS: here is a pip freeze pastebin http://pastebin.com/VbFHcvY1

**Comment by Carreau** [comment]
Hi @nicolargo, 

[shutil_get_terminal_sizeis in setup.py ](https://github.com/ipython/ipython/blob/5.x/setup.py#L208) and looking at the the pip freeze you gave, it is installed. 

The lines you pasted (`sudo pip install`) and the result are concerning though:

```
$ sudo pip install --upgrade ipython
The directory '/home/nicolargo/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nicolargo/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
```

pip should almost never be used with sudo. By doing that you are fighting system installed packages that may end up breaking your python install (or worse), it is better to use `pip install --user`.

With the error message you got, you likely have broken in some way the `backports` namespace package which you seem to have two part on your system:

```
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
```

You will likely need to clean that up, and figure out why `import backports.shutil-get-terminal-size` is corrupted (it's likely not corrupted itself, it might be backport or backports.ssl-match-hostname that is).

That's likely means poking around `/usr/local/lib/python2.7/dist-packages/backports`, removing everything that should not be there and restoring files that were replaced by pip by the original ones. I'm unsure how to do that though. You'll have to dig into `apt` and `dpkg` likely. 

@takluyver you use linux. Any advices ?

**Comment by takluyver** [comment]
> @takluyver you use linux. Any advices ?

Other than *kill namespace packages with fire* :fire: ?

- If practical, use Python 3, which avoids needing the backport in the first place
- Run [this debugging script](https://gist.github.com/takluyver/73cf4e7e7cff4d95f3b23ea80d59bcab) and post the output. A number of people have had this problem, and so far I haven't been able to pin down the cause.

**Comment by nicolargo** [comment]
@takluyver here is the output of the debugging script:

```
mod: <module 'backports' (built-in)>

backports.__path__ = ['/home/nicolargo/.local/lib/python2.7/site-packages/backports']

-- Found /home/nicolargo/.local/lib/python2.7/site-packages/backports --
Files: ['configparser']
No __init__.py found

-- Found /usr/local/lib/python2.7/dist-packages/backports --
Files: ['__init__.py', '__init__.pyc', 'shutil_get_terminal_size', 'ssl_match_hostname']
__init__.py contains:
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)


-- Found /usr/lib/python2.7/dist-packages/backports --
Files: ['__init__.py', '__init__.pyc', 'ssl_match_hostname']
__init__.py contains:
# This is a Python "namespace package" http://www.python.org/dev/peps/pep-0382/
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
```

**Comment by takluyver** [comment]
Can you try copying one of those `__init__.py` files that it found to the location where it didn't find one?

**Comment by nicolargo** [comment]
@takluyver Thanks it solve the issue !

**Comment by takluyver** [comment]
Thanks! That's a couple of people who've fixed it in the same way. Maybe we're finally starting to zero in on what's going wrong here.

**Comment by gr1d99** [comment]
i just had to comment out 
`try:
    from shutil import get_terminal_size as _get_terminal_size
except ImportError:
    # use backport on Python 2
    pass
    # from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
`

**Comment by raymondzhaoy** [comment]
I solved this problem by this way ! Thanks !  @gr1d99

**Comment by xiaoxiongli** [comment]
please do like this, it works:

/usr/local/lib/python2.7/dist-packages$ vi IPython/utils/terminal.py

try:
    from shutil import get_terminal_size as _get_terminal_size
except ImportError:
    # use backport on Python 2
    #from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
    from shutil_backports import get_terminal_size as _get_terminal_size

**Comment by shatu** [comment]
Even after trying all the suggestions from above, nothing worked for me.

So, if you are someone who has a similar problem, following worked for me :- 

- Get a list of all your installed packages using pip freeze > requirements.txt
- Make a new virtualenv with the **--no-site-packages** flag
- Install all the packages from the requirements file using pip install -r requirements.txt

**Comment by takluyver** [comment]
We hope that we'll have worked around this problem for 5.4 - see PR #10587.
