### ISSUE TITLE
Timeit results does not show -r value

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#10359]
```
In [1]: timeit -o -r7 -n11 1+1
11 loops, average of 7: 33.1 ns +- 8.77 ns per loop (using standard deviation)
Out[1]: <TimeitResult : 11 loops, average of 7: 33.1 ns +- 8.77 ns per loop (using standard deviation)>
```

Should show r=7.

**Comment by Carreau** [comment]
The format is also confusing (see proposed format [here](https://github.com/ipython/ipython/issues/9643#issuecomment-282504120), and it shoudl get a note into the what's new.

**Comment by 3lnc** [comment]
How should this looks like? Its already shows `average of`. Is this a question of phrasing?

**Comment by Carreau** [comment]
Sorry if I misexpressed myself. There are 2 things here r, and n. And the
way timeit works is to for example run log(x) n=1000000 times, mesure the
time and do this r=10 times.

The result array is r long, and the average/std is over the r
measurements.  N is shown but not R.

Does that make sense ?

**Comment by nosarthur** [comment]
`Out[1]: <TimeitResult : 11 loops, average of 7: 33.1 ns +- 8.77 ns per loop (using standard deviation)>`

I also couldn't understand the issue. It does show both r=7 (`average of 7`) and n=11 (`11 loops`).

**Comment by Carreau** [comment]
> I also couldn't understand the issue. It does show both r=7 (average of 7) and n=11 (11 loops).

Ah, yes, you are right, then the error message is confusing, this reads to me as "I took 7 of the 11 loops and averaged" which is not right. Though you are right it shows both.
