### ISSUE TITLE
Save/restore namespace

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#1035]
[Dill](http://dev.danse.us/trac/pathos/browser/dill/dill/dill.py) allows us to save an interactive namespace, including things like storing interactively defined classes, that pickle couldn't normally handle.

This might take a bit of thought - e.g. if we restore the `In[n]` and `Out[n]` storage, should we also restore prompt numbers?

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one, as it is a duplicate of #112.

Thanks everyone and happy hacking! :bowtie:
