### ISSUE TITLE
Executing the current input while cursor is not at the end

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#10374]
`|` marks cursor position
Emacs-mode seems reasonable:
```
pri|nt() <enter> => executes
print(|) <enter> => newline
print(|) <esc-enter> => executes
```

But vi-mode doesn't have `<esc-enter>` (probably because `<esc>` itself is already taken...)
```
pri|nt() <enter> => executes
print(|) <enter> => newline
print(|) <esc-enter> => newline
```

It'd be nice if there was a way to always execute the current input regardless of whether the cursor is in parentheses or not.

Version:
```
Python 3.6.0 (default, Jan 16 2017, 12:12:55) 
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
```

xref https://github.com/ipython/ipython/issues/9283#issuecomment-283754350.

**Comment by takluyver** [comment]
For me, `Esc, enter` or `Alt-enter` is working in vi mode as well.

**Comment by anntzer** [comment]
Hum, actually, esc-enter is working for me now.  Not sure what happened before, sorry for the noise.

**Comment by takluyver** [comment]
No problem. Closing as it seems to work.
