### ISSUE TITLE
Deleting working directory breaks stuff

### ISSUE THREAD

**Issue by lheckemann** [ipython/ipython#10378]
A variety of commands (including importantly `%cd`, which could otherwise be used to recover from the situation) cease to function if the working directory of the ipython kernel is removed. This can still be recovered from using `os.chdir`, but it's quite a pain nonetheless...

> {'commit_hash': u'5c9c918',
>  'commit_source': 'installation',
>  'default_encoding': 'UTF-8',
>  'ipython_path': '/nix/store/q5xrpwl38a9hlww21jd6hk0mxggvy2q4-python2.7-ipython-5.1.0/lib/python2.7/site-packages/IPython',
>  'ipython_version': '5.1.0',
>  'os_name': 'posix',
>  'platform': 'Linux-4.9.11-x86_64-with-glibc2.2.5',
>  'sys_executable': '/nix/store/a21ahiimxzb3gc9vgdvxqlv4p4n5iph8-python-2.7.13/bin/python2.7',
>  'sys_platform': 'linux2',
>  'sys_version': '2.7.13 (default, Dec 17 2016, 20:05:07) \n[GCC 5.4.0]'}

**Comment by Carreau** [comment]
I'm marking this as wishlist. 

It's understandable that it _might_ work if cwd is gone, but I'm not sure it's worth the effort. We'll happily accept PR though. 

Thanks !

**Comment by takluyver** [comment]
I think it's probably worth ensuring that at least `cd` works if the cwd has gone, even if lots of other things don't.

**Comment by takluyver** [comment]
I've made #10397 which at least allows the `%cd` and `%pwd` magics to work when the CWD is deleted, so recovery is a bit easier.
