### ISSUE TITLE
Make %matplotlib inline side effect free

### ISSUE THREAD

**Issue by andim** [ipython/ipython#10383]
Currently matplotlib inline sets a number of rc parameters. If you naively assume (as I did until recently) that it simply instructs the notebook to show plots inline, this can lead to bugs overwriting earlier defined rc settings. With the stylesheet support that matplotlib now has it might be better to separate the backend choice from loading a style sheet that looks nice in the notebook.

I raised the issue with Fernando on Twitter who encouraged me to propose PR. I am posting it here to solicit more feedback before moving forward.

**Comment by Carreau** [comment]
Thanks for the issue. 

I believe that we have another issue opened for that but I can't find it. 
It ties into #10128 and #10255 and IIRC when we did go back and forth between changing the default and not and in both cases we got complaints so this is delicate. 

In particular IIRC, the background color and default size if we don't change them are problematic. 
But I believe its a good time to revisit these default.

**Comment by fperez** [comment]
I completely agree that we should now revert this behavior in `InlineBackend`, esp. now that `%matplotlib inline` isn't explicitly required anymore in most cases. This results in super confusing behavior, as we only do the override _when the first plot call is made_. This leads to this type of situation:

![image](https://user-images.githubusercontent.com/57394/167990209-2169b022-cb98-41db-8d25-6a4a1fc129cc.png)

So if a user wants to set some rcParams at the top of their file, they basically get overridden on first plot call. They have to go back and rerun that first cell again for their changes to take, for no comprehensible reason. I just spent a good 1/2 hour debugging this just now, even though I know I was one of the people who wrote that code years ago! :)

I think we should fall back to being as hands-off as possible now, and leave this configuration to mpl/the users. We made those choices for good reason early on when the notebook was very new (I actually think we started that with the Qt console), but now I think it causes more confusion than good. I think we should revert our overrides, and let folks make their fine-tuning as they wish, using standard mechanisms.

My vote would be to drop [all our overrides here](https://github.com/ipython/matplotlib-inline/blob/master/matplotlib_inline/config.py#L32) and leave things clean (note that code now lives in the separate `matplotlib_inline` package). 

I ran some quick tests manually restoring the values we override, and things seem to work fine.

**Comment by fperez** [comment]
👍 I have a few min in between meetings, let me whip up a PR real quick :)

**Comment by fperez** [comment]
Oops!!! Sorry - I was being lazy and used the in-browser code editor (`.`) and I didn't realized it pushed straight to master!! 😱 

I quickly force-pushed to revert, and will make a PR next. Serves me well! 🤦

**Comment by fperez** [comment]
OK, now it's there, properly made. I have never touched that repo, so LMK if you'd like a bit of doc update too, happy to do it. gotta run now...

**Comment by davidnero** [comment]
It's been a few months since this issue was fixed. If anyone here is also a maintainer on matplotlib-inline, could you publish an updated version?

**Comment by fperez** [comment]
@davidnero - see [here](https://github.com/ipython/matplotlib-inline/issues/16#issuecomment-1213577961) where we're discussing indeed making a release. I'm volunteering for it b/c I need this before I start teaching! 

Should happen soon.

**Comment by fperez** [comment]
I'm going to close this as the real issue is in the matplotlib-inline repo, fixed and only pending release of a new version.
