### ISSUE TITLE
ENTER within brackets of one-liner gives newline instead of executing

### ISSUE THREAD

**Issue by mspacek** [ipython/ipython#10405]
This could very well be due to the move away from readline, but I couldn't quite find an existing open issue on this, only an indirect mention of it [here](https://github.com/ipython/ipython/issues/2493#issuecomment-264454032):

I've noticed a change of behaviour of the ENTER key in recent versions of terminal IPython. It used to be when I hit ENTER at any point on a line, the line would be executed. Now, if the cursor falls within some kind of brackets (parentheses, curly, or square), ENTER inserts a new line.
```
In [1]: a = (1 + 1)
# highlight the + sign with the cursor and hit ENTER:
In [2]: a = (1     
   ...: + 1)
```
This behaviour only really depends on the presence of the first bracket, not the second. More generally, when the cursor is to the right of an open bracket, but not at the end of the one-liner, the only way to make it execute instead of inserting a newline is to hit ALT+ENTER.

For one-liners, I'd prefer the opposite key mapping: ALT+ENTER inserts a newline, while ENTER executes regardless of cursor position (except maybe when the line ends with a colon and the cursor is at the end of the line).
```
{'commit_hash': '5a894b9',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python3.5/dist-packages/IPython',
 'ipython_version': '5.3.0',
 'os_name': 'posix',
 'platform': 'Linux-4.4.0-64-generic-x86_64-with-Ubuntu-16.04-xenial',
 'sys_executable': '/usr/bin/python3',
 'sys_platform': 'linux',
 'sys_version': '3.5.2 (default, Nov 17 2016, 17:05:23) \n[GCC 5.4.0 20160609]'}

Name: prompt-toolkit
Version: 1.0.13
```

**Comment by takluyver** [comment]
I'd like to keep the shortcuts consistent (enter to guess what to do, alt-enter to force execution - unfortunately we can't detect Ctrl-enter), but if you want to customise what they do yourself, see here:
http://ipython.readthedocs.io/en/stable/config/details.html#keyboard-shortcuts

Unfortunately it requires a bit of digging around in prompt_toolkit to find the functions you need.

**Comment by mspacek** [comment]
Thanks, though I'm not quite sure what you mean by "enter to guess what to do"...

Hmm. So this is considered a feature, not a bug? Is there a discussion somewhere that justifies the change in behaviour from previous versions of IPython?

**Comment by takluyver** [comment]
> Thanks, though I'm not quite sure what you mean by "enter to guess what to do"...

Sorry, that was too brief a description. When you press enter, it tries to guess whether you want a new line at that point, or to execute the code. So `x = 1<ENTER>` will execute, but `for a in range(5):<ENTER>` will give you a new line. The reason I say 'guess' is because this turns out to be really complex, and there are situations, like the one you describe, where it's not clear what the user wants:

```
x = (1, 2,|)
```

If `|` represents the cursor when you press enter, you could reasonably expect it to insert a newline before the right-paren, or to execute the code. 

> Hmm. So this is considered a feature, not a bug? Is there a discussion somewhere that justifies the change in behaviour from previous versions of IPython?

It wasn't deliberately changed - it's a side-effect of the new prompt_toolkit interface - but it's not clear to me that the old behaviour is better than the new. Because I know that code is fiddly, my default preference is not to change it more often than I need to. ;-)

You can see the code in question here:
https://github.com/ipython/ipython/blob/5.3.0/IPython/terminal/shortcuts.py#L85

I think the behaviour you don't like is that it asks 'is this complete' on the text *before* the cursor - so in your case, it sees an unmatched left-paren, and gives you a new line to complete the expression. I don't think always considering the whole text works well either, though, now that real multiline editing works. Maybe there's something smarter we can do with considering to the end of the line the cursor is on, but I suspect there would be cases where that's not quite what we want either.

**Comment by ixarka** [comment]
In case someone else comes across this, the following code did the trick for me, stuck inside of <profile>/startup/disableSmartEnter.py

```python
from IPython import get_ipython
from prompt_toolkit.enums import DEFAULT_BUFFER
from prompt_toolkit.keys import Keys
from prompt_toolkit.filters import HasFocus, HasSelection, ViInsertMode, EmacsInsertMode

ip = get_ipython()
insert_mode = ViInsertMode() | EmacsInsertMode()

def insert_unexpected(event):
    buf = event.current_buffer
    buf.accept_action.validate_and_handle(event.cli, buf)

# Register the shortcut if IPython is using prompt_toolkit
if getattr(ip, 'pt_cli'):
    registry = ip.pt_cli.application.key_bindings_registry
    registry.add_binding(Keys.Enter,
                     filter=(HasFocus(DEFAULT_BUFFER)
                             & ~HasSelection()
                             & insert_mode))(insert_unexpected)
```

**Comment by carlsmith** [comment]
I'm personally -1 on always having to use a modifier to enter a newline.
That's what DevTools does, and even with years of practice, I still
frequently hit Enter by force of habit. It's frustrating.

If psychic-return is ever scrapped, IMO, it should be the opposite way
round, so Enter always enters a newline, and Alt-Enter executes.

I've plugged the following idea already, so will keep it brief: It's
trivial to detect that the input is a one-liner and starts with a bang or
line magic (even with automagic on). My prompt detects this state already.
We could have an option that makes one-line 'commands' auto-execute, and
regular Python not do so. You could then either type a one-line command and
hit Enter, or enter Python code in multi-line mode. I implemented this once
in another, similar Python shell, and it quickly became intuitive.

Maybe we could ask the list for what logic people would prefer, sticking to
things that are simple to implement and document, and see if we can
shortlist a small set of options that would keep most people happy??

**Comment by mspacek** [comment]
Thanks for the tips on changing the default behaviour of ENTER. However, I'm more concerned about the default behaviour itself, out of the box, not changing it for specific installations, e.g. for teaching a class.

What about making the default behaviour check for matching brackets? If the closing bracket is missing, start a new line. If all opened brackets have a closing bracket, execute the line (unless other conditions apply, such as the line ending with a colon). I don't know how complex that would be to implement. Perhaps the Python parser itself can simplify such a task?

**Comment by mspacek** [comment]
Sorry, regarding @takluyver 's comment:

> `x = (1, 2,|)`
> If | represents the cursor when you press enter, you could reasonably expect it to insert a newline before the right-paren, or to execute the code.

I would say it's more reasonable to expect it to execute the code, as (I'm pretty sure) used to be the case. If you want to make it multiline, delete the closing bracket, then hit enter, and continue typing.

**Comment by carlsmith** [comment]
If this stuff was controllable in the config options, the default could
then be something simple, either Enter to execute and Alt+Enter to add a
newline, or the opposite way around.

The current default is not really a default. It's generally just how things
always worked for everyone. If you only have one way of handling input,
then it makes sense to try and be clever about it. If you have options,
then the default can and probably should be simple. Having a system that's
so complex that people aren't always sure what should happen isn't a good
default.

The current logic is just too complicated.

**Comment by takluyver** [comment]
I don't want to scrap 'psychic return' (thanks for that name ;-). It would undoubtedly make my life easier as the maintainer to say that it won't try to guess, but as a user I like it to guess.

Just today I saw someone fall foul of this change in behaviour with IPython 5, though. I wonder if we should change the behaviour to prefer executing more if there's only one line. So (with `|` representing the cursor again):

```python
a = (1, 2,|)   # Would execute
```

But:

```python
a = 1
b = (2, 3,|)  # Would insert a newline, because you're already in a multiline cell
```

**Comment by mspacek** [comment]
>  I wonder if we should change the behaviour to prefer executing more if there's only one line.

That seems reasonable to me. As a user, I also very much appreciate "psychic return"! Unfortunately, to make it sufficiently psychic, I suspect we probably can't avoid using a collection of ad-hoc rules. Maybe they can be kept reasonable simple by just using a flat if...elif...elif... block, with rules ordered in decreasing priority? It would also be good if those rules could then be exposed in documentation, to help the user help IPython guess more accurately.

**Comment by carlsmith** [comment]
So, it's definitely a feature people want to keep, at least generally, so
tweaking the logic seems like the best thing to do.

I'm not sure what I can add right now that's useful.

**Comment by carlsmith** [comment]
We could use machine learning :)

**Comment by Carreau** [comment]
I would be happy to push the threshold to execute more often if only one line. It also often bother be, as I rarely break a single line into multiple one with single statements.

**Comment by Carreau** [comment]
> We could use machine learning :)

Watch out, if you go too far IPython will replace you.

**Comment by jslavin** [comment]
I side with those who want Enter to execute the line as previously.  For one thing, it's like it is for the shell command line (bash or tcsh).  I often want to do up arrow (N times), edit, execute.  With the current default, I need to go to the end of the line, which I tend to forget.

In any case, the change needs to be more prominent in the docs.  This is the first place where I've seen the bit about using alt+enter to execute.

**Comment by tstarbow-sfdc** [comment]
On my mac I have to hit esc-enter to execute. Enter, cmd-enter, ctrl-enter and option/alt-enter all inserts a newline, which is very confusing after years of bash. I see this doesn't happen if the line has no parens, but really I am almost always editing a statement inside parenthesis. So thumbs up to changing the guessing to guess execute more often on single line statements.

**Comment by carlsmith** [comment]
The shortcut is technically <kbd>Meta</kbd> `+` <kbd>Enter</kbd>. You need your terminal emulator configured to use <kbd>Option</kbd> as the <kbd>Meta</kbd> key.

In the Apple Terminal, in the *Keyboard* tab of the *Preferences* window, you can check **Use Option as Meta key** near the bottom.

**Comment by carlsmith** [comment]
Quite a few people have expressed a view on this now, and apart from me, everyone seems to want it work like it used to. A pretty large majority of users are probably going to agree with the consensus here. My reasons are subjective as well; it's not like I know something anyone else missed.

I initially thought I was speaking for a much larger percentage of users, but seeing what everyone else thinks, I don't have any objections.
e
I'll look at hacking something together using the config system, maybe create a gist or something.

**Comment by not-raspberry** [comment]
Unfortunately, the snippet posted by @ixarka also disables ^v^j. (Just FYI.)

**Comment by alexrichert** [comment]
Maybe "shift+enter" could be used to request a new line, and plain "enter" could have the old behavior (enter command)? "Shift-enter" is slightly easier to enter with one hand than "alt-enter".

**Comment by takluyver** [comment]
We can't detect shift-enter or ctrl-enter in the terminal. They come through exactly the same as enter by itself. Even detecting alt-enter only works on some platforms.

**Comment by ixarka** [comment]
Since this thread is still kicking, I thought I'd post an update to my earlier snippet.  I got annoyed that enter always did a newline since it effectively broke multi-line editing.  I ran into the annoying ctrl-enter problem as well (which is not prompt-toolkit's fault, as pointed out).  I settled on ctrl-N for a newline.  Note that indenting is broken if you need to nest.  I'm sure there are smarter ways to do it but I usually bust out an editor if I need to indent more than 2 levels in an ipython shell.  This 95% solution works well enough until I come across a full-featured "smart enter" implementation.

`from IPython import get_ipython
from prompt_toolkit.enums import DEFAULT_BUFFER
from prompt_toolkit.keys import Keys
from prompt_toolkit.filters import HasFocus, HasSelection, ViInsertMode, EmacsInsertMode

ip = get_ipython()
insert_mode = ViInsertMode() | EmacsInsertMode()

def eval_line(event):
    buf = event.current_buffer
    buf.accept_action.validate_and_handle(event.cli, buf)

def new_line(event):
    buf = event.current_buffer
    buf.insert_text('\n' + '    ')

# Register the shortcut if IPython is using prompt_toolkit
if getattr(ip, 'pt_cli'):
    registry = ip.pt_cli.application.key_bindings_registry
    registry.add_binding(Keys.Enter,
                     filter=(HasFocus(DEFAULT_BUFFER)
                             & ~HasSelection()
                             & insert_mode))(eval_line)
    registry.add_binding(Keys.ControlN,
                     filter=(HasFocus(DEFAULT_BUFFER)
                             & ~HasSelection()
                             & insert_mode))(new_line)

`

**Comment by Carreau** [comment]
We released IPython 5.4 and 6.1 yesterday that give you a clean hook to register custom function for `Enter`.

**Comment by ceilingcat** [comment]
@Carreau Can you give an example of how this can be done in the new IPython release? Thanks!

**Comment by Carreau** [comment]
[Here](http://ipython.readthedocs.io/en/stable/config/details.html#keyboard-shortcuts) is a full section in the docs. If something is missing, or could be better expressed feel free to open an issue (or send a PR). Happy to get more examples.

**Comment by carlsmith** [comment]
I wrote something about this, posted to the mailing list, but didn't get a reply. The current docs don't cover things very well, but I think the API should be improved a bit too.

While `handle_return` is designed for customising when IPython executes code or inserts a newline, in practice, users want to execute code or insert a newline *with automatic indentation*.

The docs show how to execute code and how to insert a newline, but it's not clear how to insert the correct number of spaces after the newline. I ended up with this:

``` python
def psychic_return(shell):

    def handle(event):

        def should_execute(): ... # custom heuristics go here

        buffer = event.current_buffer
        document = buffer.document
        text = document.text

        if should_execute(): # this block just executes the input...

            buffer.accept_action.validate_and_handle(event.cli, buffer)

        else: # this block inserts a newline with auto-indentation...

            if document.line_count > 1: text = text[:document.cursor_position]
            indent = shell.input_splitter.check_complete(text + '\n')[1] or 0
            buffer.insert_text("\n" + " " * indent)

    return handle

c.TerminalInteractiveShell.handle_return = psychic_return
```

The three lines in the else-block are pretty messy, considering that is what most users will want to do. They are usually only customising *when* IPython executes or inserts a newline, not *how* the newline is inserted.

If you look at the `psychic_return` function as a whole, it's all boilerplate. Users will normally only need to customise the logic in the `should_execute` function, which returns a bool. The API should really allow users to just implement that part.

I was thinking the user could provide a function that returns `True` if it wants IPython to execute the input, `False` if it wants IPython to insert a newline (observing any auto-indentation settings) and return `None` if it wants IPython to do nothing, allowing the user's function to handle the situation itself, as it does in every case currently. Something like that.

**Comment by Carreau** [comment]
Thanks Carl, do you want to attempt a PR against the documentation. help is always welcome. 

Sorry to have missed your mail on the mailing list it's hard to track everything which is happening.

**Comment by carlsmith** [comment]
No problem. I know some things slip through the net on the mailing list. I'll look at updating the docs now.

**Comment by mspacek** [comment]
Is it just me, or has IPython 6.1.0 somehow solved this problem? I don't seem to experience it any more after upgrading with pip. However, now from the first example:
```python
In [1]: a = (1 + 1)
# highlight the + sign with the cursor and hit ENTER, or ALT/CTRL/SHIFT + ENTER:
In [2]: a
Out[2]: 2
```
I can't seem to force a new line (not that this personally bothers me though). After browsing recent commits, I see that CTRL+O does seem to work though.

Strange, this problem is also solved for me in IPython 5.1.0 on Python 2.7.12. Maybe I changed some ipythonrc setting that applies to both?

**Comment by Carreau** [comment]
I believe this was fixed by https://github.com/ipython/ipython/pull/10489/, 5.1 may not have this "bug". You can find that in the [what's new in 5.4](http://ipython.readthedocs.io/en/stable/whatsnew/version5.html#ipython-5-4) docs.

**Comment by mspacek** [comment]
Great! I'll close this one then.

**Comment by Carreau** [comment]
Thanks !
