### ISSUE TITLE
pylab --no-import-all from command line?

### ISSUE THREAD

**Issue by lebedov** [ipython/ipython#10429]
Is there a builtin way to start ipython --pylab from the command line without importing everything in numpy/pylab into the global namespace (i.e., equivalent to running %pylab --no-import-all from within ipython)? Or does doing so necessitate a custom profile?

**Comment by minrk** [comment]
You can do:

- `ipython --matplotlib auto` to setup interactive matplotlib without importing anything into the global namespace
- `ipython --pylab auto` to import everything into the global namespace
- set `c.InteractiveShellApp.pylab_import_all = False` in your `ipython_config.py` to change the default import behavior of `--pylab` above
- set the same flag on the command-line for a single call: `ipython --pylab auto --InteractiveShellApp.pylab_import_all=False`
- pass arbitrary lines of execution to initialize IPython: `ipython -i -c "%pylab --no-import-all"`

Technically, all options that can be set in a profile can be set on the command-line (replace `c.Class.trait = value` with `--Class.trait=value`), but the args quickly become too long to type out regularly. Setting preferences in a config file is generally the better way to go, unless it's really for a one-off deviation from your preferences.

**Comment by lebedov** [comment]
Great - thanks!
