### ISSUE TITLE
IPython 5.3 terminal: enter should execute not insert line break

### ISSUE THREAD

**Issue by bmerry** [ipython/ipython#10425]
This is a regression from 5.2.2 to 5.3 when using the terminal interface: if the cursor is in the middle of a line and I press enter, a line break is inserted into the line. On 5.2.2, pressing enter had the same effect as if the cursor was at the end of the line i.e. it executes the line I've just entered.

To reproduce: type `foo(2, 3)` (without pressing enter), move the cursor to be on the 3, then press enter.

It's extremely rare that one wants to break lines in an interactive session, but quite common to go back to a line from history, modify the contents, and then immediately want to execute it. Please bring back the old behaviour.

**Comment by gatagat** [comment]
I also find this new behavior annoying. If reverting it completely is not possible, would it work to have `Shift+Enter` to execute (as in notebooks) when in the middle of a line? At the end of the line, both `Shift+Enter` and `Enter` would execute.

**Comment by Carreau** [comment]
> If reverting it completely is not possible, would it work to have Shift+Enter to execute (as in notebooks) when in the middle of a line?

Unfortunately terminals technical limitation prevent us to do that. You can use `Esc` followed by `Enter` though.

**Comment by carlsmith** [comment]
> It's extremely rare that one wants to break lines in an interactive session...

Personally, since IPython 5 moved to using Prompt Toolkit, I often write multiline code interactively. It actually annoys me that IPython executes so eagerly. I find larger chunks of code easier to manage than lots of separate lines. Each to their own.

**Comment by bmerry** [comment]
Indeed, you'll never keep everyone happy. @carlsmith: out of interest, when writing multiline code are you breaking lines in the middle of statements (e.g. inside parentheses) or between statements? The behaviour I'm finding annoying is IPython inserting line breaks when the cursor is between parentheses within a statement.

**Comment by carlsmith** [comment]
I've not really thought about it, but it would probably be both.

It's one of those things that everyone approaches differently, and as it makes no sense to promote a specific coding style for working in a shell, it's difficult to know what would work best for most people.

**Comment by iblis17** [comment]
Is there any way to configure this behavior?
I expect the command should be executed instantly as well...

**Comment by takluyver** [comment]
#10489 attempts to improve this, but I'm not sure that it's quite right.
