### ISSUE TITLE
osx - separate windows aren't created ; terminal displasy "ApplePersistence"

### ISSUE THREAD

**Issue by vichug** [ipython/ipython#10421]
Hey, suddenly today using iPython, trying to display a picture or a graph, it doesn't work anymore. The terminal displayed these lines :
`2017-03-30 23:39:36.054 python[3032:29352] ApplePersistence=YES
Out[2]: <matplotlib.text.Text at 0x1171f7c18>
`
It seems linked to this issue : http://www.openradar.me/28409008 or https://github.com/lionheart/openradar-mirror/issues/15902

i'm using osx 10.10.5 (14F2109)

**Comment by takluyver** [comment]
Have you used the `%matplotlib` magic to integrate matplotlib's GUI interface with IPython?

**Comment by vichug** [comment]
@takluyver thanks a lot, indeed i did not, and indeed it was the problem. For some reason i thought this magic was only necessary inside a jupyter notebook, not inside the CLI. So in the end the problem was between the keyboard and the chair :))
About this message i see, it should be just noise, from the radar issue, but not specially related to ipython. Closing this issue, have a nice day

**Comment by takluyver** [comment]
No worries. In earlier versions of IPython it worked in some situations without running the `%matplotlib` magic, but that wasn't really intentional, and I didn't even know it used to do that until people started reporting that it didn't. ;-)
