### ISSUE TITLE
Outreach re: ipython 6.0.0rc1 breaking builds of related projects on Python 2.7

### ISSUE THREAD

**Issue by nealmcb** [ipython/ipython#10438]
After the [ipython 6.0.0rc1 release](https://github.com/ipython/ipython/releases/tag/6.0.0rc1), the [python-fire](https://github.com/google/python-fire) project ran in to Travis CI failures for internal builds, as noted in https://github.com/google/python-fire/issues/57

It would be helpful to have more readily visible or even proactive advice on how to configure `setup.py`, pip, and other dependency-management systems for a wide variety of use cases.  E.g. how to configure a project to depend on ipython 6 for supported python versions, but version 5 otherwise.

**Comment by nealmcb** [comment]
The discussion in https://github.com/ipython/ipython/pull/9900 is pointed to from the README, and was indeed proactive and very helpful. But it only covers the case "I'm installing IPython itself".  Extending that effort with tips for the other projects which depend on IPython (and also have naive users doing source builds) is what I'm talking about here.

A blog post about 6.0.0rc1 and its impact would be most welcome.

**Comment by nealmcb** [comment]
It looks offhand like [pypi-data](https://github.com/nathforge/pypi-data) could be used to find most of the pip-installable packages that depend on IPython.

**Comment by willingc** [comment]
Hi @nealmcb,

I'll let @takluyver and @carreau provide more details on the possibility of editing error messages/install messages on discontinuing 2.7 support beyond the IPython 5 LTS release.

>It would be helpful to have more readily visible or even proactive advice on how to configure setup.py, pip, and other dependency-management systems for a wide variety of use cases. E.g. how to configure a project to depend on ipython 6 for supported python versions, but version 5 otherwise.

We can definitely look at the docs and README to further highlight Python 2 support and IPython 5 LTS.

> A blog post about 6.0.0rc1 and its impact would be most welcome.

Thanks for the suggestion. We typically do blog posts for major releases and mailing list posts for release candidates.

Thanks!

**Comment by takluyver** [comment]
Many packages are only uploaded as source packages, and the setup script can ask for different dependencies depending on the environment (e.g. require x only on Windows, or only on Python 2). So you can't have a static list of all a packages dependencies in general.

There are better ways to handle conditional dependencies now - you can make a static list with 'environment markers' to filter which ones are used. If packages provide the information, PyPI can record dependencies (e.g. [astsearch](https://pypi.python.org/pypi/astsearch) shows the dependency on astcheck). But many packages don't.

**Comment by jtratner** [comment]
Heads up that latest pip doesn't actually appear to respect the requirement identifiers for ipython https://github.com/pypa/setuptools/issues/1009 - https://github.com/pypa/setuptools/issues/1009#issuecomment-293333034

**Comment by Carreau** [comment]
> A blog post about 6.0.0rc1 and its impact would be most welcome.

yes, we'll write blog post fro the final release as @Willingc pointed out

> Heads up that latest pip doesn't actually appear to respect the requirement identifiers for ipython pypa/setuptools#1009 - pypa/setuptools#1009 (comment)

The setuptools maintainers are wrong : https://github.com/pypa/pip/pull/3877
We contributed the patches upstream to pip, pypi and warehouse to support this.

**Comment by takluyver** [comment]
Closing this - we've made some efforts to promote the `Requires-Python` metadata, and things largely seem to have shaken out.
