### ISSUE TITLE
Jedi inspected functions cannot be queried for docstring

### ISSUE THREAD

**Issue by stefanv** [ipython/ipython#10469]
```
In [1]: d = {'f': 'asd'}

In [2]: d['f'].capitalize?
Object `capitalize` not found.
```

**Comment by Carreau** [comment]
:-) that's unrelated to jedi, it just never worked. But I can see why someone would expect it to work now.

**Comment by takluyver** [comment]
Closing for now, because I don't see a way to do this that's not essentially reimplementing a parser badly. See #10703 for more discussion.
