### ISSUE TITLE
PySpark issue 

### ISSUE THREAD

**Issue by upavan** [ipython/ipython#10462]
Hi Team., 
I'm facing an issue with PySpark.. My environment details are:
1. OS - Windows 10
2. Python 3
4. Spark 2.1

Error Text:
**Unknown error in handling PYTHONSTARTUP file C:\opt\spark\spark-2.1.0-bin-hadoop2.7\spark-2.1.0-bin-hadoop2.7\bin\..\python\pyspark\shell.py:**

Please let me know how can I overcome this issue.

**Comment by MrMino** [comment]
Hi. A more suitable place for this question would be StackOverflow or the like; it doesn't seem to be related in any way to **I**Python, which this issue tracker is for.
