### ISSUE TITLE
ipython 5.3 doesn't respect --classic, nor --simple-prompt

### ISSUE THREAD

**Issue by vspinu** [ipython/ipython#10460]
I am trying to get standard python `>>>` prompt with ipython `5.3.0`.  I can get it with ipython 2.4.1 with `--classic` option, but not with `5.3.0`. `--simple-prompt` doesn't have an effect on the prompt shape either. 

This is ubuntu standard install. 

```
~$ ipython3 --classic --simple-prompt
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]:
```

```
~$ python3 -c "import IPython; print(IPython.sys_info())"
{'commit_hash': '5a894b9',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python3.5/dist-packages/IPython',
 'ipython_version': '5.3.0',
 'os_name': 'posix',
 'platform': 'Linux-4.4.0-57-generic-x86_64-with-Ubuntu-16.04-xenial',
 'sys_executable': '/usr/bin/python3',
 'sys_platform': 'linux',
 'sys_version': '3.5.2 (default, Nov 17 2016, 17:05:23) \n[GCC 5.4.0 20160609]'}
```

**Comment by Carreau** [comment]
I think you can't use both --classic  and --simple-prompt

--simple-prompt is meant to remove all the bells an wistle when controlling IPython from a subprocess. You likely do not want to set it interactively. Making both working as the same time could be doable, but might not be worth the cost/benefit with the number of people using both. 

--classic alone should work on 5.3, at least it does here in a fresh conda environment. Do you have any custom config ?

**Comment by vspinu** [comment]
Thanks for the pointers. I think something is amiss with my ubuntu default install of ipython. It works correctly with ipython installed inside virtual environments.
