### ISSUE TITLE
Syntax highlighting doesn't know about PEP 515

### ISSUE THREAD

**Issue by daviewales** [ipython/ipython#10461]
Using IPython 5.1.0, numeric literals formatted using underscores as described in [PEP 515](https://www.python.org/dev/peps/pep-0515/) do not have correct syntax highlighting.

For example,

```python
1000
```
will be highlighted in green, while 
```python
1_000
```
will have the first digit in green, while the underscore and remaining digits are white.

![screen shot 2017-04-18 at 5 00 52 pm](https://cloud.githubusercontent.com/assets/2499066/25118223/af0a07e8-2458-11e7-9c71-8505c0e0ff44.png)

**Comment by takluyver** [comment]
This needs to be fixed in pygments, which does the syntax highlighting.

https://bitbucket.org/birkenfeld/pygments-main/issues/1299/add-support-for-underscores-to-python

**Comment by carlsmith** [comment]
Pygments *seem* to have added [support for IPython Session Syntax Highlighting][1] with an `IPythonConsoleLexer` class, but in IPython itself, things like `files =! ls` still look broken.

I found the PR confusing, and am not clear what the status is, but it would obviously be nice to get this working. My editor supports IPython syntax, but IPython does't!

Does anyone know what it would take to get this working?

[1]: https://bitbucket.org/birkenfeld/pygments-main/issues/938/support-for-ipython-session-syntax

**Comment by tchajed** [comment]
This has been fixed upstream and will be available in pygments 2.2.1: https://bitbucket.org/birkenfeld/pygments-main/pull-requests/703/add-lexing-for-pep-515-underscores-in/diff.

**Comment by takluyver** [comment]
Thanks. Closing this issue, then, since there's nothing for us to change.
