### ISSUE TITLE
pdb completion menu not honouring prompt_toolkit style

### ISSUE THREAD

**Issue by memeplex** [ipython/ipython#10478]
The menu colors look different when inside pdb (after %debug) than when outside it.
In particular, neither of:

```
Token.Menu.Completions
Token.Menu.Completions.Completion
Token.Menu.Completions.Completion.Current
Token.Menu.Completions.Meta
Token.Menu.Completions.Meta.Current
Token.Menu.Completions.MultiColumnMeta
```

is taken into account.

**Comment by memeplex** [comment]
Well `create_prompt_application` in `debugger.py` is not using the style at all, I will try to fix this and let you know.

**Comment by memeplex** [comment]
Well, this was easier than I thought, here is a simple fix:

```
@@ -17,6 +17,7 @@ from prompt_toolkit.token import Token
 from prompt_toolkit.shortcuts import create_prompt_application
 from prompt_toolkit.interface import CommandLineInterface
 from prompt_toolkit.enums import EditingMode
+from prompt_toolkit.styles import DynamicStyle
 
 
 class TerminalPdb(Pdb):
@@ -63,6 +64,7 @@ class TerminalPdb(Pdb):
                             mouse_support=self.shell.mouse_support,
                             get_prompt_tokens=get_prompt_tokens,
                             display_completions_in_columns=multicolumn,
+                            style=DynamicStyle(lambda: self.shell._style)
         )
         self.pt_cli = CommandLineInterface(self._pt_app, eventloop=self.shell._eventloop)
```

Problem is `shell._style` is "private", so wouldn't it be desirable to expose `shell.style` as `DynamicStyle(lambda:...)`?

**Comment by Carreau** [comment]
I don't have particular preference. Feel free to send a PR :-)

**Comment by memeplex** [comment]
Also, I'm not really sure keeping `shell._style` as an attribute has any point.

**Comment by Carreau** [comment]
> lso, I'm not really sure keeping shell._style as an attribute has any point.

Maybe not, there've been a lot of refactor. It's still half a mess and need a lot of cleaning.

**Comment by memeplex** [comment]
It still might be useful as a cache, I guess.
