### ISSUE TITLE
iPython Error for magic

### ISSUE THREAD

**Issue by schiravuri** [ipython/ipython#10487]
Hi,

I'm just started Brandon Rhode's Python tutorial from PyCon 2015

[Tutorial](https://www.youtube.com/watch?v=5JnMutdy6Fw)

It seems that I'm having a similar issue as [9005](https://github.com/ipython/ipython/issues/9005), but my iPython notebook is up to date 
![image](https://cloud.githubusercontent.com/assets/5534738/25383588/d080ab34-298a-11e7-932c-7fc58c6e5526.png)

Below is the series of errors that I'm seeing when I run the 
KeyError                                  Traceback (most recent call last)
<ipython-input-2-fbc154654837> in <module>()
----> 1 get_ipython().magic(u'matplotlib inline|')
      2 import pandas as pd
      3 import sys
      4 reload(sys)
      5 sys.setdefaultencoding('utf-8')

C:\Users\chiravuri43\AppData\Local\Continuum\Anaconda2\lib\site-packages\IPython\core\interactiveshell.pyc in magic(self, arg_s)
   2156         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2157         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2158         return self.run_line_magic(magic_name, magic_arg_s)
   2159 
   2160     #-------------------------------------------------------------------------

C:\Users\chiravuri43\AppData\Local\Continuum\Anaconda2\lib\site-packages\IPython\core\interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2077                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2078             with self.builtin_trap:
-> 2079                 result = fn(*args,**kwargs)
   2080             return result
   2081 

<decorator-gen-105> in matplotlib(self, line)

C:\Users\chiravuri43\AppData\Local\Continuum\Anaconda2\lib\site-packages\IPython\core\magic.pyc in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

C:\Users\chiravuri43\AppData\Local\Continuum\Anaconda2\lib\site-packages\IPython\core\magics\pylab.pyc in matplotlib(self, line)
     98             print("Available matplotlib backends: %s" % backends_list)
     99         else:
--> 100             gui, backend = self.shell.enable_matplotlib(args.gui)
    101             self._show_matplotlib_backend(args.gui, backend)
    102 

C:\Users\chiravuri43\AppData\Local\Continuum\Anaconda2\lib\site-packages\IPython\core\interactiveshell.pyc in enable_matplotlib(self, gui)
   2935         """
   2936         from IPython.core import pylabtools as pt
-> 2937         gui, backend = pt.find_gui_and_backend(gui, self.pylab_gui_select)
   2938 
   2939         if gui != 'inline':

C:\Users\chiravuri43\AppData\Local\Continuum\Anaconda2\lib\site-packages\IPython\core\pylabtools.pyc in find_gui_and_backend(gui, gui_select)
    274     if gui and gui != 'auto':
    275         # select backend based on requested gui
--> 276         backend = backends[gui]
    277     else:
    278         # We need to read the backend from the original data structure, *not*

KeyError: u'inline|'

**Comment by takluyver** [comment]
It looks like you've entered `%matplotlib inline|` (with an extra `|` on the end).

**Comment by takluyver** [comment]
i.e. it should just be `%matplotlib inline`

**Comment by schiravuri** [comment]
Thank you!
