### ISSUE TITLE
plotly causing browser-crash

### ISSUE THREAD

**Issue by shivanand3939** [ipython/ipython#10482]
Hi,

I am using plotly to plot some histograms. Below is the code

        
trace1 = go.Histogram(
    x=df['dti']
)
trace2 = go.Histogram(
    x=df['revol_bal']
)
trace3 = go.Histogram(
    x=df['inq_last_6mths']
)

trace4 = go.Histogram(
    x=df['pub_rec']
)
trace5 = go.Histogram(
    x=df['open_acc']
)
trace6 = go.Histogram(
    x=df['annual_inc']
)
trace7 = go.Histogram(
    x=df['recoveries']
)
trace8 = go.Histogram(
    x=df['int_rate']
)
trace9 = go.Histogram(
    x=df['total_acc']
)

fig = tools.make_subplots(rows=3, cols=3)

fig.append_trace(trace1, 1, 1)
fig.append_trace(trace2, 1, 2)
fig.append_trace(trace3, 1, 3)
fig.append_trace(trace4, 2, 1)
fig.append_trace(trace5, 2, 2)
fig.append_trace(trace6, 2, 3)
fig.append_trace(trace7, 3, 1)
fig.append_trace(trace8, 3, 2)
fig.append_trace(trace9, 3, 3)

fig['layout'].update(height=600, width=600, title='data  distributions subplots')
py.iplot(fig, filename='simple-subplot')

it works fine, but I make some modifications and replot 
        
trace1 = go.Histogram(
    x=df['dti'].apply(lambda x: math.log(x+1))
)
trace2 = go.Histogram(
    x=df['revol_bal'].apply(lambda x: math.log(x+1))
)
trace3 = go.Histogram(
    x=df['inq_last_6mths'].apply(lambda x: math.log(x+1))
)

trace4 = go.Histogram(
    x=df['pub_rec'].apply(lambda x: math.log(x+1))
)
trace5 = go.Histogram(
    x=df['open_acc'].apply(lambda x: math.log(x+1))
)
trace6 = go.Histogram(
    x=df['annual_inc'].apply(lambda x: math.log(x+1))
)
trace7 = go.Histogram(
    x=df['recoveries'].apply(lambda x: math.log(x+1))
)
trace8 = go.Histogram(
    x=df['int_rate'].apply(lambda x: math.log(x+1))
)
trace9 = go.Histogram(
    x=df['total_acc'].apply(lambda x: math.log(x+1))
)

fig = tools.make_subplots(rows=3, cols=3)

fig.append_trace(trace1, 1, 1)
fig.append_trace(trace2, 1, 2)
fig.append_trace(trace3, 1, 3)
fig.append_trace(trace4, 2, 1)
fig.append_trace(trace5, 2, 2)
fig.append_trace(trace6, 2, 3)
fig.append_trace(trace7, 3, 1)
fig.append_trace(trace8, 3, 2)
fig.append_trace(trace9, 3, 3)

fig['layout'].update(height=600, width=600, title='data  distributions subplots')
py.iplot(fig, filename='simple-subplot')

But the browser crashes. with the following message

[W 15:54:29.018 NotebookApp] Notebook Untitled.ipynb is not trusted
[I 15:54:31.529 NotebookApp] Adapting to protocol v5.1 for kernel 6a420be1-f92f-42e9-a82b-f1ea22998525
[I 16:06:33.034 NotebookApp] Saving file at /Untitled.ipynb
[W 16:06:33.034 NotebookApp] Saving untrusted notebook Untitled.ipynb
[W 16:06:48.509 NotebookApp] 404 GET /static/plotly.js?v=20170424154932 (127.0.0.1) 83.03ms referer=http://localhost:8888/notebooks/Untitled.ipynb?token=ed1a5532db955c5c38e0162fc9e9a200f887067642910b89
[I 16:08:33.314 NotebookApp] Saving file at /Untitled.ipynb
[W 16:08:33.315 NotebookApp] Saving untrusted notebook Untitled.ipynb
[I 16:10:33.436 NotebookApp] Saving file at /Untitled.ipynb
[W 16:10:33.436 NotebookApp] Saving untrusted notebook Untitled.ipynb
--2017-04-24 16:12:32--  https://clients2.google.com/cr/report
Resolving clients2.google.com (clients2.google.com)... 216.58.220.14, 216.58.220.14, 216.58.220.14, ...
Connecting to clients2.google.com (clients2.google.com)|216.58.220.14|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/dev/fd/3’

     0KCrash dump id:  d8138a4e80000000 
                                                      1.13M=0s

2017-04-24 16:12:35 (1.13 MB/s) - ‘/dev/fd/3’ saved [16]

[W 16:13:30.539 NotebookApp] Notebook Untitled.ipynb is not trusted
[I 16:13:32.976 NotebookApp] Adapting to protocol v5.1 for kernel 6a420be1-f92f-42e9-a82b-f1ea22998525

**Comment by takluyver** [comment]
It seems like that's likely to be a bug in your browser - it shouldn't be possible for any web content it shows to crash it. I don't think there's anything we can do about it from our side.

**Comment by Carreau** [comment]
There is nothing we can do for this, maybe try Google Chrome beta? 
Closing as this is a Chrome issue, feel free to keep commenting. Thanks !
