### ISSUE TITLE
How to enter the  IPython 6.0

### ISSUE THREAD

**Issue by continuesmile** [ipython/ipython#10480]
I  installed both anaconda2 and anaconda3 on my ubuntu system, so i enter the `ipython 5.3.0` when i used the command line--`ipython`, then i used `pip3 install ipython --upgrade`  and it showed the ipython-6.0.0  installed sucessfully, but i dont konw how to enter the ipython6.0, because i still enter `ipython 5.3.0` when i run the command `ipython`.
Thanks for any help.

**Comment by Carreau** [comment]
You shouldn't install both anaconda 2 and 3 on your system, you should install one and use conda environments if you want to use both Python 2 and 3. 
If you issue a `$ which pip3` you will see that `pip3` is (most likely)  __not__ the pip of anaconda.
To upgrade Ipython  for anaconda you __must__ use `pip`, and if you want to install in an environment using pip you __must__ `source activate <env>` before installing.

**Comment by continuesmile** [comment]
@Carreau ,thanks for your reply.
AS you said, the pip3 is not in anaconda. I installed anaconda3 because i  konw the ipython 6.0 only support python3, and i dont want to  discard python2, must i uninstall either of them? If i hope use the ipython 6.0 what should i do ?

**Comment by Carreau** [comment]
As I said above, if you want to use Python 3 and 2 next to each other you need to use envs.
See [conda envs](https://conda.io/docs/using/envs.html).

Wether you want to use anaconda2 or anaconda3 is up to you. You can't really use both anaconda at the same time. Likely the one you installed most recently will take precedence. There is no _need_ to uninstall, but one will just be unavailable.

The major difference will be the default environment called "root" which will be Python 2 for anaconda 2, python 3 for anaconda 3. The rest will be identical. Then in a Python 3 env, you will be able to `pip install ipython` without issue and get ipython 6. But what I say won't make sens before you learn to use envs.

**Comment by Carreau** [comment]
Closing, feel free to keep commenting.

**Comment by takluyver** [comment]
To clarify a bit, once you have one version of Anaconda installed, you can create an environment for the other Python by doing:

```
conda create -n my-py2-env python=2
```

That command creates an environment named `my-py2-env` using Python 2. You can activate it in the terminal to use Python 2, or deactivate it to go back to the Anaconda 'root environment'.

For more info, see the conda docs @Carreau linked to above.
