### ISSUE TITLE
Document and example for #10496 _repr_mimebundle_

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#10502]
#10496 introduced `_repr_mimebundle_` , we need to add narrative docs and examples for it to be used. 
Then backport to 5.x

**Comment by Carreau** [comment]
Done in #10527

**Comment by tswast** [comment]
For those that are landing here as the top hit for "_repr_mimebundle_" example, the examples are included in the [Custom Display Logic](https://github.com/ipython/ipython/blob/master/examples/IPython%20Kernel/Custom%20Display%20Logic.ipynb) notebook ([nbviewer link](http://nbviewer.jupyter.org/github/ipython/ipython/blob/master/examples/IPython%20Kernel/Custom%20Display%20Logic.ipynb)).

**Comment by johann-petrak** [comment]
Sadly that notebook does not explain either how to pass which metadata back to Ipython when using the two-value return approach for `_repr_mimebundle_`. There could also be a link to the Notebook in the API documentation. 

The whole API documentation for `_repr_*_` is not very detailled. For example it says nothing about any limitations in the HTML that gets returned from `_repr_html_`, does not mention what happens with javascript or  how ids and classes may class with other instances of self or Ipython, and also does not mention what viewport size the HTML will get to be displayed in and how to change that, if at all possible. 

If the HTML returned is styled to adapt to the window size, which window height will it receive? How can that be changed?
