### ISSUE TITLE
ipython tab completion causing side effects when reading descriptors

### ISSUE THREAD

**Issue by mentaal** [ipython/ipython#10521]
I have a test class which, when tab completed from an interactive terminal, causes side effects.
Test class and descriptor:

```python
class TestDescr():

    def __get__(self, obj, objtype):
        print("Side effects!")
        return 1

    def __set(self, obj, value):
        raise AttributeError("Error, read only attribute")

class TestClass():
    td = TestDescr()
```

Below is a copy of an ipython interactive session: (tried on pip version and master version)

```
> python __main__.py
Python 3.6.1 |Anaconda custom (64-bit)| (default, Mar 22 2017, 20:11:04) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: cd ../../
c:\projects\mban_fpga_eval_fw_test

In [2]: %run test_file.py

In [3]: tc = TestClass()

Side effects!
Side effects!
In [4]: tc.td

``` 
Just to explain, when I type: `tc.` and then press `tab`, `Side effects!` is then printed twice. 

I have tried this with Ipython version 5.3 with no such issues:

```
> ipython
Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:27:37) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: %run test_file.py
ERROR:root:File `'test_file.py'` not found.

In [2]: cd ..
c:\projects\mban_fpga_eval_fw_test

In [3]: %run test_file.py

In [4]: tc = TestClass()

In [5]: tc.td
```

**Comment by mentaal** [comment]
One other delta in the aforementioned setups which I didn't explicitly mention is that in the ipython 5.3 example, I am using python 3.5

**Comment by takluyver** [comment]
The most likely cause is the use of jedi for completions in IPython 6.

We restrict what we complete in order to avoid the things with the highest potential for side effects (e.g. `foo().<tab>` won't call `foo()`), but our completion machinery has always done some things that can have side effects. Python makes it possible to override so many operations that it's really hard to guarantee you're avoiding it and still do something useful.

We also deliberately call into some things that can have side effects, to allow for customisation - e.g. this one happens in IPython 5.x as well:

```python
class TestDir(object):
    def __dir__(self):
        print("Side effects")
        return ["foo"]

td = TestDir()
####
td.<tab>
```

**Comment by Carreau** [comment]
> The most likely cause is the use of jedi for completions in IPython 6.

yes it's a Jedi thing, you can reproduce with 

```
from jedi import Interpreter
import pdb
class TestDescr():

    def __get__(self, obj, objtype):
        print("Side effects!")
        return 1

class TestClass():
    td = TestDescr()
tc = TestClass()
interpreter = Interpreter('tc.td', [{**locals()}], line=1, column=5)
interpreter.completions()
```

Though I don't know how to check that an object has a custom `__get__`, it does not appear in hasattr, nor in `dir()`.

The relevant line of jedi is:
```
> /jedi/evaluate/compiled/__init__.py(300)get()
-> getattr(obj, name)
(Pdb) ll
295  	    @memoize_method
296  	    def get(self, name):
297  	        name = str(name)
298  	        obj = self._compiled_object.obj
299  	        try:
300  ->	            getattr(obj, name)
301  	            if self._is_instance and name not in dir(obj):
302  	                return []
303  	        except AttributeError:
304  	            return []
305  	        except Exception:
306  	            # This is a bit ugly. We're basically returning this to make
307  	            # lookups possible without having the actual attribute. However
308  	            # this makes proper completion possible.
309  	            return [EmptyCompiledName(self._evaluator, name)]
310  	        return [self._create_name(name)]
```

**Comment by takluyver** [comment]
There's a [getattr_static](https://docs.python.org/3/library/inspect.html#inspect.getattr_static) function which could be used to avoid triggering descriptors.

**Comment by ifischer** [comment]
Upgrading Jedi to 0.11 solved the problem for me

**Comment by MrMino** [comment]
This was fixed in `jedi`.
