### ISSUE TITLE
display_* not respected if _repr_mimebundle_ defined. 

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#10526]
See https://github.com/ipython/ipython/pull/10496#issuecomment-300641192
![screen shot 2017-05-10 at 16 33 23](https://cloud.githubusercontent.com/assets/335567/25925610/73516ca8-359e-11e7-9b16-b8d5d1655f6d.png)

**Comment by Carreau** [comment]
Currently looking into this one.

**Comment by Carreau** [comment]
@rgbkrk , @minrk should `_repr_mimebundle_` be given the `exclude`/`include` keywords to potentially skip computation of expensive representation, these are options of `display()`. 

Thought ?

**Comment by minrk** [comment]
I'm torn on the kwargs. It seems reasonable to pass through arguments from `display` down to `_repr_mimetype_`, but I also don't like the "You must accept and ignore `**kwargs`" API proscription required for future-compatibility. Especially since `display_png` and friends are ~never used outside of our own Rich Output tutorial notebook.

**Comment by Carreau** [comment]
I also think that `display(..., include={'image/png'})` should be in our tutorials, I was not even aware of it until diving in the code.

**Comment by Carreau** [comment]
@meeseeksdev backport

**Comment by minrk** [comment]
> I also think that display(..., include={'image/png'}) should be in our tutorials, I was not even aware of it until diving in the code.

I kind of feel the opposite - that we should possibly consider deprecating it because even we don't know that it exists and never really documented it. But if we should keep it, then we should probably promote it over the `display_png` because it's the only way to limit to arbitrary mime-types.

**Comment by Carreau** [comment]
Well, the whitelist and blacklist are definitively more powerful (and flexible) than `display_x()`, as you can filter arbitrly (GeoJson for example) andmore composable.
