### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by larryKra** [ipython/ipython#10553]
When I tried to use Theano on Centos 6, I got the following error message:
Exception: ('The following error happened while compiling the node', DotModulo(A, s, m, A2, s2, m2), '\n', "Compilation failed (return status=1): /tmp/ccKAbGNg.s: Assembler messages:. /tmp/ccKAbGNg.s:3005: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'. /tmp/ccKAbGNg.s:3013: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rsi)'. /tmp/ccKAbGNg.s:3015: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'. /tmp/ccKAbGNg.s:3017: Error: no such instruction: `vextracti128 $0x1,%ymm0,48(%rsi)'. ", '[DotModulo(A, s, m, A2, s2, m2)]')

What's wrong with that?

**Comment by takluyver** [comment]
You probably need to ask about that on a forum relating to Theano.

**Comment by ivanov** [comment]
Hey there, I'm going through issues and it seems to me that it makes sense to close this one: @larryKra seems to be having trouble with [theano](https://github.com/Theano/Theano), not IPython itself.

Thanks everyone and happy hacking! :bowtie:
