### ISSUE TITLE
enable_gui does not seem to work

### ISSUE THREAD

**Issue by jvbsl** [ipython/ipython#10568]
https://github.com/ipython/ipython-in-depth/blob/master/examples/IPython%20Kernel/gui/gui-gtk.py
need %gui gtk for the GUI to show up, tried the same with GTK3 and need %gui gtk3 for the gui to show up, tried different ways none of them worked.

I can't use get_ipython() as that returns None(because the terminal hasn't started yet, but as embed() is synchronuous I can't call that function afterwards either)

IPython.lib.inputhook.enable_gui('gtk3') should be the proper way, should it not?

**Comment by takluyver** [comment]
Sorry, I can't understand from that description what you're trying to run from where and what the results are.

**Comment by jvbsl** [comment]
e.g. If I'm running that example Program from console: "python ./gui-gtk.py" the gui doesn't show up till I type in "%gui gtk"(I used embed() to show the ipython console), but shouldn't https://github.com/ipython/ipython-in-depth/blob/master/examples/IPython%20Kernel/gui/gui-gtk.py#L37 have the same effect as typing in that magic by hand?

**Comment by takluyver** [comment]
I think you need to have the GUI integration enabled before running the script, so it won't work with `python gui-gtk.py`.

The `inputhook` module is deprecated. The API call to do GUI integration is `shell.enable_gui('gtk3')` - which needs an IPython shell instance to be created first. If you want to embed a shell, I think you can do it like this:

```python
from IPython.terminal.embed import InteractiveShellEmbed
shell = InteractiveShellEmbed()
embed.enable_gui('gtk3')

# Where you want to embed it:
shell()
```

**Comment by jvbsl** [comment]
thank you very much, it worked like a charm(just needed to use shell.enable_gui instead of embed.enable_gui^^)

(Should I close the issue myself then?)

**Comment by takluyver** [comment]
Ah, thanks. I've updated the name above so it's clearer for other people reading this.
