### ISSUE TITLE
Do we need to keep the deprecated docker file?

### ISSUE THREAD

**Issue by srinivasreddy** [ipython/ipython#10572]
If it is deprecated, isn't it safe to remove it in the next major release? What was original decision ?

**Comment by takluyver** [comment]
Yeah, it's been two years since it was deprecated, and I think even the thing it points to is deprecated now, so I think we can get rid of it.

**Comment by srinivasreddy** [comment]
Closing this issue as the PR https://github.com/ipython/ipython/pull/10573 merged.
