### ISSUE TITLE
Cannot connect to GPIB interface instruments

### ISSUE THREAD

**Issue by uv-04** [ipython/ipython#10576]
I'm trying to connect to a GPIB instrument using pyVISA but I get an error. I'm following the simple example on the pyVISA website: http://pyvisa.readthedocs.org/en/master/

I type the following code into the IPython console:

import visa
rm = visa.ResourceManager()
rm.list_resources()

Out[4]:
(u'USB0::0x0957::0x0D0B::MY49431510::INSTR',
 u'USB0::0x0957::0x17BC::MY52400338::INSTR',
 u'ASRL1::INSTR',
 u'ASRL2::INSTR',
 u'ASRL5::INSTR',
 u'ASRL6::INSTR',
 u'ASRL7::INSTR',
 u'ASRL8::INSTR',
 u'ASRL9::INSTR',
 u'ASRL10::INSTR')
However, my GPIB instruments do not show up, just the serial ports and my USB instruments. When I launch the Agilent Connection Expert (or NI MAX) I can see all my GPIB instruments and can communicate with them. I also am able to communicate with the instruments without issue with Matlab.

So when I try and connect to the instrument with the line:

inst = rm.open_resource('GPIB0::19::INSTR')
It throws an error:  VisaIOError: VI_ERROR_INTF_NUM_NCONFIG (-1073807195): The interface type is valid but the specified interface number is not configured.

**Comment by takluyver** [comment]
I think you'll need to start investigating this in a pyVISA issue or mailing list - it's possible that there's some difference in the environment in IPython that's causing this, but we don't know about pyVISA, so we can't really help debug issues.
