### ISSUE TITLE
`display_id = 1` always generates a new ID

### ISSUE THREAD

**Issue by ivanov** [ipython/ipython#10597]
This came up in #10596, which fixes the issue, but I wanted to document this bug in case anyone else comes across it. The code we have checks `if display_id == True:` - and generates a new id if that is the case. But that code evaluates to True when `display_id=1` - so there was no way to have id==1 without generating a new ID. 

The fix is simple, `if display_id is True:` - and will be merged when #10596 is merged

**Comment by Carreau** [comment]
marking as 5.4. update_display has been backported, and the behavior should be identical.

**Comment by Carreau** [comment]
Closed by #10596
