### ISSUE TITLE
Release 6.1 and 5.4 soon ?

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#10603]
I'm thinking of trying to release 5.4/6.1 soon. 6.0 was about a month and a half ago, and 5.4 has API backports.

I'd like to release both back to back (same day?) this should give us more insight on the Python2 vs Python3 ratio as we can't see see the "No you're already up to date" pip messages (see [here](https://github.com/Carreau/miscs/blob/master/IPython-dls.ipynb))

@takluyver do you have any thoughts on this ?

The only thing I would potentially wait for is "inject display in builtins" which I'd like to backport to 5.x for consistency.

**Comment by takluyver** [comment]
That makes sense to me. I would wait for #10596 if we're planning to backport that.

**Comment by Carreau** [comment]
I'm going to start the release process.

**Comment by Carreau** [comment]
Oh, wait no, there is still #10618  pending. Sorry.

**Comment by Carreau** [comment]
FYI I released 5.4 and 5.4.1 about 2 hours later that fixes #10629.
