### ISSUE TITLE
display() instantiates a shell in pure Python

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#10617]
See #10596 conversation near the end.

We should likely fallback to print (with a warning) on pure Python.

**Comment by mraduldubey** [comment]
OK

**Comment by adityausathe** [comment]
Hey, I'm a newbie to IPython. I am trying to work on this issue, but I don't know how to distinguish calls to display() from Pure Python interpreter and IPython interpreter.
@Carreau

**Comment by mraduldubey** [comment]
#10634 
This should fix the issue. I have not issued a warning to users. Just printed the objects.

**Comment by srinivasreddy** [comment]
@takluyver  safely closed?

**Comment by takluyver** [comment]
Yup, thanks
