### ISSUE TITLE
ipython does not work with python compiled with openssl in fips mode. 

### ISSUE THREAD

**Issue by srinathgs** [ipython/ipython#10615]
in fips mode, md5 is disabled. hence, ipython fails with 

```
    hash_digest = hashlib.md5(code.encode("utf-8")).hexdigest()
ValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips
```
this error.

A fix is changing md5 to sha256 in `IPython/core/compilerop.py` [in this line](https://github.com/ipython/ipython/blob/master/IPython/core/compilerop.py#L58). I can raise a pull request if the change looks fine.

**Comment by takluyver** [comment]
Sounds OK to me, go ahead and make a PR :-)

**Comment by Carreau** [comment]
Why not "Just" `hex(abs(hash("""this is a string """)))` if it's not cryptographically secure ?

**Comment by takluyver** [comment]
`hex(abs(hash()))` may give you a shorter string if hash() happens to return a number close to 0. That may not be a problem, but it might mean that e.g. regexes looking for 12 hex characters don't work.

**Comment by Carreau** [comment]
Ad, but we can pad to 12 with 0s then.

**Comment by srinathgs** [comment]
@ivanov: I somehow missed this thread because of the whole hoard of notifications from my github subscriptions.

 I just verified `sha1` is available in FIPS mode, I have created a PR which changes `md5` to `sha1`. Thanks.
