### ISSUE TITLE
Synchronize 6.x / Master

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#10628]
I pushed a 6.x branch to have stable links to a couple of notebooks on nbviewer. 
We need to rememeber to keep the 6.x branch in sync with master. This issue should likely be keep on a `6.somethning` milestone until master becomes 7.x

**Comment by takluyver** [comment]
I've updated the 6.x branch, and master is now heading for 7.0, so they no longer need to be kept in sync.
