### ISSUE TITLE
Execute multiple lines of code at once

### ISSUE THREAD

**Issue by maria8899** [ipython/ipython#10631]
Hi,
I am trying to execute multiple lines of code using ipython 6.0.1 (I also have tried 6.0.0) but cannot find any shortcut working (i.e. alt + enter or shift + enter) to get a new line. I am not sure if this is a bug or if I am missing something?
For example if I want to write and execute these multiple lines of code at once:
```
In [5]: import numpy as np
   ...: a = np.array([1])
   ...: print(a)
   ...: 
[1]
```

At the moment I need to explicitly write the backslash operator to get a new line, i.e.
```
In [4]: import numpy as np \
   ...: a = np.array([1]) \
   ...: print(a)
```
and then remove manually the backslash operators to make it run as in the first example, otherwise ipython is complaining:
```
In [6]: import numpy as np \
   ...: a = np.array([1]) \
   ...: print(a)
  File "<ipython-input-6-b0ea1b71283b>", line 1
    import numpy as np a = np.array([1]) print(a)
                       ^
SyntaxError: invalid syntax
```
I have tried 2 different terminals but get the same problem. Any help would be appreciated!

**Comment by takluyver** [comment]
There's only so much we can do in the terminal interface - we can't detect shift-enter or ctrl-enter. We can detect alt-enter on some systems, but we use that to force execution rather than force a new line.

What you can do is press F2 to go into your editor (you can control which editor with the EDITOR environment variable). Write multiple lines in there, save and quit, and they'll be brought into the IPython prompt.

**Comment by benyoti** [comment]
Thanks, I see. I thought it was something I was missing as it is what is shown on the main documentation in the picture: https://ipython.readthedocs.io/en/stable/_images/ipython-6-screenshot.png

In the meantime I have found out a shortcut that is somewhat working (in my settings ?) which is ctrl+o. This actually start a new line (with the 3 dots '...'), except the cursor is staying at the same place and I need to press the arrow key to put the cursor on the new line. This is not the best but still better than the backslash!

**Comment by maria8899** [comment]
Thanks, I see. I thought it was something I was missing as it is what is shown on the main documentation in the picture: https://ipython.readthedocs.io/en/stable/_images/ipython-6-screenshot.png

In the meantime I have found out a shortcut that is somewhat working (in my settings ?) which is ctrl+o. This actually start a new line (with the 3 dots '...'), except the cursor is staying at the same place and I need to press the arrow key to put the cursor on the new line. This is not the best but still better than the backslash!

**Comment by takluyver** [comment]
Oh yeah, I'd forgotten about that shortcut. I think the screenshot is showing that you can paste multiline code in and it works correctly.

**Comment by Carreau** [comment]
Closing as nothing to do. IPython 6.1 has been released yesterday you can bind any function to enter if you want to change the behavior of newline vs execute.

**Comment by IgnacioDeveloper** [comment]
There is a trick you can use. You can use parenthesis in the beginning of the code-block you want to write, when hit enter-key, it will automatically add lines to your command meanwhile the parenthesis in the beginning is not closed. Before executing you must remove parenthesis. Another common way it's if you have a block defined by after ':', everytime you hit enter-key it will add conforming the identetion f the block (which is nice if you need to write and execute a for loop). If you add a line with any of these maners and in the final line you hit enter, (and all parenthesis previously closed if any) it will execute the whole block. You can try and discover many other ways. But it's possible. You don't have to argue to one-line convention if needed a multiple-line execution or block one

**Comment by CRTejaswi** [comment]
Press `^o` (or `O` for vi-mode).
