### ISSUE TITLE
bug-report jupiter's ipython notebook

### ISSUE THREAD

**Issue by ethan1987-2** [ipython/ipython#10646]
i was scripting with spyder 3 and using ipython and noticed that jupiter's nb can't work this:
```
import scipy as sp
...
sp.integrate.nquad(f,intervs)
```
it yields and error stating that there is no integrate function in module sp

but if you do:
```
import integrate from scipy
...
integrate.nquad(f,intervs)
```
then there is no problem at all!

**Comment by Carreau** [comment]
sp.integrate is a submodule of SciPy, so you need to import it once for it
to be available.
That's how python work so I'd be worried about changing the behavior.
The confusion is likely that many modules do implicitly import their
submodules, which makes things like `import foo; foo.bar.func()` appear to
be correct, though it is likely not. One classic example is matplotlib that
used to have a `matplotlib.finance` submodule.

It is - I agree - a behavior of python that may be confusing at first sight
but is the reasonable one.

Sorry I'm on my phone so code examples are hard to write.

**Comment by Carreau** [comment]
Well because something else does import it. 
I don't know what, I don't have the code to inspect, but it's easy to replicate:

```
$ cat foo.py
import scipy.integrate

$ python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 13:19:00)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy as sp
>>> sp.integrate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'scipy' has no attribute 'integrate'
>>> import foo
>>> sp.integrate
<module 'scipy.integrate' from '/Users/bussonniermatthias/anaconda/lib/python3.6/site-packages/scipy/integrate/__init__.py'>
>>>
```

So if something else is importing it, it will be available, and as you see it's Python behavior not IPython or Jupyter. Spyder may do imports as well, maybe it import `scipy.integrate`. @ccordoba12 an idea ofwhere this difference could come from on the Spyder Side ?
