### ISSUE TITLE
IPython console in Spyder

### ISSUE THREAD

**Issue by BruceSherwood** [ipython/ipython#10656]
The following issue might be a Spyder issue, or a VPython issue, but it seems possible that it's an IPython issue.

I'm the principal developer of the new VPythons (plural), with the same API in the browser (glowscript.org, using the RapydScript-NG Python-to-JavaScript transpiler), in a Jupyter notebook using true Python, or, as of two days ago, in IDLE or Spyder (see vpython.org for details).

I can import vpython and run in Spyder if I choose the deprecated Python console or an external System terminal.

If I choose the IPython console, I get this output, and no 3D display:

runfile('C:/Users/Bruce/.spyder-py3/temp.py', wdir='D:/Documents/0GlowScriptWork/LocalServer')
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>

I don't have any difficulties running from IDLE.

Since the Spyder Python console is going away, can you offer any insight into what could be the problem with trying to run a program that imports vpython, when using the IPython console? The vpython module when running outside the Jupyter notebook environment sets up an http server to serve image files (for textures on 3D objects) and font files (for extruding 3D text), and it sets up a websocket server for rapid two-way communications between the Python program and a JavaScript program in the browser that calls upon the GlowScript library for WebGL rendering. 

The vpython module when not running in a Jupyter notebook makes no references to IPython other than to check whether the user is or is not running in a notebook, so the output shown above suggests that it is the IPython console itself that is unhappy.

Thanks for any advice you can offer!

**Comment by ccordoba12** [comment]
This is the same as spyder-ide/spyder#4582, so please close this one. The discussion will continue there.
