### ISSUE TITLE
ScriptMagics creates uncollectable garbage on Python 2

### ISSUE THREAD

**Issue by mdickinson** [ipython/ipython#10657]
The `IPython.core.script.ScriptMagics` object is uncollectable on Python 2: it's part of a reference cycle, and its `__del__ ` method ensures that the cyclic garbage collector can't collect it: a call to `gc.collect()` ends up putting the `ScriptMagics` object into `gc.garbage`.

This also means that the `__del__` method will never be executed on Python 2, so the cleanup won't occur unless triggered directly.

Things should be fine on Python 3, thanks to [PEP 442](https://www.python.org/dev/peps/pep-0442/).

Software and platform versions:
- Python 2.7.13
- IPython 5.3.0
- ipykernel 4.5.2
- macOS 10.12.5

Here's an image showing one of the reference cycles (though I believe not the only one) involved:

![refcycle](https://user-images.githubusercontent.com/662003/27025563-dcd62614-4f52-11e7-9200-e18d5af0c1d0.png)

**Comment by takluyver** [comment]
Is this a practical issue? I think that normally only one instance of each Magics class is created, and it sticks around until the process is executing anyway. So it's not a waste of memory. We register the cleanup on an atexit handler as well, so that should still happen. If it's just of theoretical interest, and it's already fixed in Python 3, I think we can just leave it as is.

**Comment by mdickinson** [comment]
I guess it's not a practical issue, normally. It's a practical issue for me, because I have a large test suite for an IPython-using application, and many of the tests in that test suite start and then stop IPython. The leftover `ScriptMagics` instance keeps a reference to the interactive shell, which in turn keeps a reference to the kernel, and a large swathe of IPython machinery is left alive at the end of the test, causing peculiar interactions  with later tests.

**Comment by mdickinson** [comment]
> It's a practical issue for me

I should clarify: I've already worked around this for my test suite, by adding a test-cleanup step that finds the `ScriptMagics` instances and breaks the cycles. I'm also manually running (and then deleting) the related atexit handler, but that's not enough by itself to free up the various IPython objects being kept alive. So it's not really true to say that it's a practical issue for me any longer: while I'd be delighted if this were fixed upstream, I'm mostly opening this issue to alert the IPython devs to the issue, in case they want to fix it.

**Comment by takluyver** [comment]
Aha, thanks. So it is a practical issue in at least some circumstances. I guess that you'd need some workaround even if it weren't a reference cycle, though, because the global atexit handler would presumably keep a reference to it anyway if you didn't handle that.

**Comment by mdickinson** [comment]
> So it is a practical issue in at least some circumstances.

Yes, though I guess it's something of a niche use-case, and the fact that it's not an issue in Python 3 is a strong argument for not fixing it.

> because the global atexit handler would presumably keep a reference to it anyway

Right. My current cleanup step is quite elaborate. :-) I'm running and removing relevant `atexit` exithandlers, calling `clear_instance` on various traitlets `SingletonConfigurable` subclasses (and similar classes) that keep track of their current singleton instance, deleting `IPython.utils.io.stdout` and friends, restoring various `sys` attributes (e.g., `stdout` and co, `displayhook`, `excepthook`, etc.), and breaking the `ScriptMagics` cycle to avoid ending up with stuff in `gc.garbage` that keeps everything else alive. Most of this seems somewhat reasonable and straightforward. The `ScriptMagics` cleanup definitely stands out as the most awkward part.

**Comment by takluyver** [comment]
`ip.restore_sys_module_state()` might help with some of those bits. It is definitely written like an application, not a library, so it assumes it has the process to itself. I was trying to push at one point for making it practical to run multiple shell instances in the same process, but it didn't get very far - it's a lot of work for a fairly niche use cases.

What are your tests doing? Are there any of them which could use just part of the IPython machinery, rather than creating and tearing down the whole shell system?

**Comment by mdickinson** [comment]
> ip.restore_sys_module_state() might help with some of those bits

Ah, that's good to know. Thanks. I'd definitely prefer to use existing cleanup functionality where it's available; for one thing, this makes our application more future-proof against upstream IPython changes.

The tests are doing many things: this is a test suite for an application with a pluggable architecture, where one of the core plugins provides an IPython kernel and (qtconsole) frontend. There are around 3000 individual tests, many of which indeed don't need the IPython machinery (though the IPython component is a fairly key part of the whole application), and we're currently using a mix of approaches, including mocking the bits of IPython that we need for tests that aren't directly IPython-related, avoiding IPython altogether where possible, and running some integration-level tests in a separate process to avoid having to deal with test interactions. But even with all this, there's still a need to have some in-process tests that don't mock. We did consider running each IPython-using unit test in its own process. In principle, that's probably the cleanest way to do things (and the way that's most in-keeping with the way that IPython is intended to be used), but it has a cost in convenience and test-run time.

I'm perfectly happy with this being closed as a "won't fix": we've already worked around it, and the only point to fixing it would be if the fix would benefit others in a similar situation. I'm quite prepared to believe that there aren't that many others doing this sort of thing.

**Comment by takluyver** [comment]
Thanks. I'm think I'm inclined to wontfix it, but try to keep in mind such use cases for future development.

I was just about to write about an issue open on ipykernel for easier cleanup, but when I went to find it, it turned out to be your issue. Here's the link for anyone else reading: https://github.com/ipython/ipykernel/issues/221
