### ISSUE TITLE
ipcluster and ipcontroller

### ISSUE THREAD

**Issue by Yoonsen** [ipython/ipython#10665]
ipcluster exits after starting engines with an unspecified error. When starting the ipcontroller, there are a couple of messages of which the last one is that the file ipcontroller.pid is empty: 

raise PIDFileError("invalid pid file: %s (contents: %r)"%(pid_file, s))
ipyparallel.apps.baseapp.PIDFileError: invalid pid file: /home/larsj/.ipython/profile_default/pid/ipcontroller.pid (contents: '')

Any ides where to go from here?

**Comment by Yoonsen** [comment]
The files ipcontroller-client.json and ipcontroller-engine.json are written to and ok Everything works until it tries to access/write the fileipcontroller.pid

**Comment by Carreau** [comment]
Hum that may be an issue for https://github.com/ipython/ipyparallel, have you tried updating to its latest version ?

**Comment by Yoonsen** [comment]
Thanks for suggestion -  The system worked fine until the disk got full, but after freeing space, it stopped working. I'll try upgrading and report back.

**Comment by Yoonsen** [comment]
I move the question to ipyparallel
