### ISSUE TITLE
get_ipython returns None when called from startup file

### ISSUE THREAD

**Issue by memeplex** [ipython/ipython#10661]
I'm following the instructions given [here](http://ipython.readthedocs.io/en/stable/config/details.html#keyboard-shortcuts). Nevertheless, and despite https://github.com/ipython/ipython/issues/9791 and https://github.com/ipython/ipython/pull/9818:

i. `get_ipython` is not exposed as a builtin.
ii. Even when imported as described in the documentation, `get_ipython()` returns `None`.

The startup file is just `profile_default/ipython_config.py`.

I'm testing this agaist the latest revision:

```
ipython --version
6.2.0.dev

git log
commit 3a7e880c793ab1477c2180376a4bd98651febc03 (HEAD -> master, upstream/master, upstream/HEAD)
Merge: ebb001ec4 6d2b31146
Author: Matthias Bussonnier <bussonniermatthias@gmail.com>
Date:   Mon Jun 12 08:18:57 2017 -0700

    Merge pull request #10655 from adityausathe/master
    
    Feature req #10556: %timeit could use local scope
```

**Comment by takluyver** [comment]
> The startup file is just profile_default/ipython_config.py.

That's not a startup file! See the section *Startup files* here:

http://ipython.readthedocs.io/en/stable/interactive/tutorial.html#startup-files

**Comment by takluyver** [comment]
Config files have to be read before IPython is set up, because we use the config from them to set up IPython. Startup files are read later, so the IPython object is available to them.

**Comment by memeplex** [comment]
Ahhh ok then. I didn't know about that difference. Thanks!

**Comment by memeplex** [comment]
@takluyver now I have the problem that I was "inheriting" my default profile from another one (`load_subconfig(....)`) but that is not out-of-the-box possible for a startup file (`name 'load_subconfig' is not defined`). Is it any way to inherit startup files? Should I symlink it?

**Comment by takluyver** [comment]
Yeah, symlinking it should work fine. They're executed in name order, so if you need it to run before another script, just name them accordingly.

**Comment by kirankotari** [comment]
@memeplex do you have any sample code. I am facing the same problem, but couldn't able to get your conversation about reading the config file @takluyver 

```python
def initialize(self):
    if ipy.get_ipython() is None:
        self._create_profile() #  passing command to subprocess to create a profile
    print(f'ipython profile: {ipy.get_ipython()}') # still I am getting None
```

```bash
⋊> ~/c/i/i/ipycli on master ⨯ ipython profile create
[ProfileCreate] Generating default config file: '/Users/xyz/.ipython/profile_default/ipython_config.py'
[ProfileCreate] Generating default config file: '/Users/xyz/.ipython/profile_default/ipython_kernel_config.py'
⋊> ~/c/i/i/ipycli on master ⨯
```
do I need to change any config under `ipython_config.py`, my objective is to `define_macro` in ipython
