### ISSUE TITLE
No module named sphinx.util.compat error using `IPython.sphinxext` with Sphinx pre1.7 master branch

### ISSUE THREAD

**Issue by jfbu** [ipython/ipython#10666]
Trying out `IPython.sphinxext` 6.1.0 with ``Sphinx==1.7.dev20170617`` I get the following error on a Sphinx project:

```
Extension error:
Could not import extension IPython.sphinxext.ipython_directive (exception: No module named 'sphinx.util.compat')
```

Indeed, the `sphinx.util.compat` is deprecated at 1.6 and will be [removed at  Sphinx 1.7](https://github.com/sphinx-doc/sphinx/blob/3d5e0c5d7/CHANGES#L45).

To reproduce, in a virtual env with IPython 6.1.0 run

    pip install git+https://github.com/sphinx-doc/sphinx

and then 

```
mkdir /tmp/IPython-test
cd /tmp/IPython-test
yes "n" | sphinx-quickstart --dot _ --project IPython-test --author "Example" -v 0 --release 0 --language en --suffix .rst --master index --makefile --batchfile .
echo '
extensions = [
    "IPython.sphinxext.ipython_directive",
]
' >> conf.py
make html
```

**Comment by jfbu** [comment]
Quoting [Sphinx CHANGES (Deprecated at 1.6b1)](http://www.sphinx-doc.org/en/stable/changes.html#id7): 

> sphinx.util.compat.Directive class is now deprecated. Please use instead docutils.parsers.rst.Directive

**Comment by Carreau** [comment]
Thanks for the heads up. 

You seem to have already dug into what needs to be done, do you want to submit a PR ?

**Comment by jfbu** [comment]
Done at #10668.

**Comment by Carreau** [comment]
> Done at #10668.

Thank you ! And thank you again for trying beta of sphinx.

**Comment by jakirkham** [comment]
When is this scheduled to land in a release?

**Comment by Carreau** [comment]
As soon as I have time to polish release notes, triage issues and make a release. Mid September if all goes well.
