### ISSUE TITLE
history -o not displaying output

### ISSUE THREAD

**Issue by adityausathe** [ipython/ipython#10664]
In the documentation it is mentioned that `-o` option to `history` magic will display execution history along with the output. But, it is only displaying execution history and no output.
Little bit digging into it, I have found that `History_database` is returning `None` when we query to it with `output=True`. So, I'm not sure whether we are recording the `output` into `history_database` in the first place?

**Comment by adityausathe** [comment]
I am not getting the following behaviour of `history -o`. Am I doing something wrong here?
```
In [1]: def f():
   ...:     print('hey!!')
   ...:     

In [2]: f()
hey!!

In [3]: print('message')
message

In [4]: history -o
def f():
    print('hey!!')
f()
print('message')
history -o

In [5]: 
```

**Comment by takluyver** [comment]
A couple of follow up notes:

Output, for this purpose, is only things that are shown with an `Out` prompt:

```
 1│ 2+3
 1> 5

 2│ print(2+3)
5

 3│ hist -no
   1: 2+3
5
   2: print(2+3)
   3: hist -no
```

Also, we don't store output in the history database by default, so unless you've enabled that in config, output history is only available for the current session.
