### ISSUE TITLE
Dead kernel in Jupyter notebook after Anaconda(Python 2.7) installation

### ISSUE THREAD

**Issue by SudeshnaD** [ipython/ipython#10672]
Hi , I have just started learning Python, and have installed Anaconda Python 2.7 version  I use Windows 7 64 bit. I have installed igraph and pycairo as well , which are functioning okay, but when I am accessing Jupyter notebook, I constantly get the dead kernel issue. 

In the kernel option in jupyter, only one kernel shows : Python 2
In the console I read and ImportError: No module named shutil.get.terminal.size

Can anyone help me in this?

**Comment by takluyver** [comment]
Try `conda update ipython`. That's a long-standing issue which we recently added a workaround for.

> I have just started learning Python, and have installed Anaconda Python 2.7

I'd definitely recommend starting with Python 3 now. Along with quite a few other projects, we'll be [ending Python 2 support by 2020](http://www.python3statement.org/).

**Comment by SudeshnaD** [comment]
Hi @takluyver yes I solved by unistalling and resinstalling the shutil.get.terminal.size module. Didn't have to try conda update ipython. Thanks! 👍

**Comment by takluyver** [comment]
OK, great.
