### ISSUE TITLE
ipython command not found

### ISSUE THREAD

**Issue by CHK16** [ipython/ipython#10678]
I installed anaconda python 3.6 version on a window 10. 
I am sure that I install anaconda as my default Python. 
I can run ipython by click on the ipython icon in the start menu.
But I am still getting error in Git bash says : bash : ipython command not found

Is there any way I can run ipython in git bash?

Thanks.

**Comment by takluyver** [comment]
I'm not very familiar with Windows, but I think that you can't use Windows Python from git-bash.

**Comment by CHK16** [comment]
I added a path to it and it's working now.
→ $ PATH=$PATH:/c/Users/chk16/Anaconda3/Scripts 
(Make sure to create a path to the directory "Scripts" where the IPython and Jupyter notebook are installed)
