### ISSUE TITLE
Jupyter Notebook does not close properly

### ISSUE THREAD

**Issue by bhaskar21** [ipython/ipython#10679]
Hello Team,

We are using HPC/LSF farm. When we use Jupiter notebook to be launched on remote machine and when we try closing by either:

Closing browser
Or
Ctrl+c

This is not exactly closing all the incidents of Jupiter notebook on execution machine. 
I think DBUS instance might be causing the issue.  
Could you please help in what process, variables need to be checked to see Jupiter notebook closes correctly?

Thanks & Regards,
Bhaskar

**Comment by takluyver** [comment]
> Closing browser

This doesn't do anything to stop the notebook server running.

> Ctrl+c

This should work - what do you see when you do it?

> I think DBUS instance might be causing the issue.

I don't think we do anything with DBus.

**Comment by takluyver** [comment]
That looks normal. Does it do that even if you shut the server down before starting any kernels?

**Comment by bhaskar21** [comment]
Am sorry for coming back on this very late...
Actually am not starting any kernel here. Am just launching the notebook in remote machine and tried closing this with <ctrl+c>.  Will check on this and get back to you.

**Comment by MrMino** [comment]
Looks like this has been solved, or at least isn't coming up for anyone anymore. Ping us if you think it should be reopenned.
