### ISSUE TITLE
Ipython 5 hangs with eventlet monkey patching

### ISSUE THREAD

**Issue by marco-lavagnino** [ipython/ipython#10675]
To reproduce, inside ipython do:

```
import eventlet
eventlet.monkey_patch()
```

It happens for all Ipython 5 releases (from 5.0.0b1 to 5.4.1), and only when using python 2 (I tested only 2.7.13, 2.7.12 and 3.5.2). Eventlet version does not seem to matter. It happens at least on Linux and osX.

This issue was already posted at eventlet/eventlet#395, but since it only affects a version of ipython, maybe the fix should be on ipython's side.

**Comment by takluyver** [comment]
Might be similar to #10251.

IPython is running the interface in the same Python process as your code runs, so code you run can break what IPython needs. Libraries taking a 'monkey patch the world' approach change the ground we're standing on, so I tend to feel that you should expect stuff to break when you do that.

**Comment by marco-lavagnino** [comment]
Closing since Python 2 is not relevant anymore.
