### ISSUE TITLE
Traceback error with Python 3.6

### ISSUE THREAD

**Issue by georgebv** [ipython/ipython#10687]
Below is a full error text. Happens for any error since I upgraded to Python 3.6 (occurs even on clean install).

```
Traceback (most recent call last):
  File "D:\Python3.6.1\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-e6cc46dee2ed>", line 1, in <module>
    prin
NameError: name 'prin' is not defined
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Python3.6.1\lib\site-packages\IPython\core\interactiveshell.py", line 2808, in run_ast_nodes
    if self.run_code(code, result):
  File "D:\Python3.6.1\lib\site-packages\IPython\core\interactiveshell.py", line 2879, in run_code
    self.showtraceback(running_compiled_code=True)
TypeError: showtraceback() got an unexpected keyword argument 'running_compiled_code'
```

**Comment by takluyver** [comment]
What does it show you if you do this:

```python
ip = get_ipython()
ip.showtraceback??
```

Also, what version of IPython do you have?

**Comment by georgebv** [comment]
Version 6.1.0

```
In [1]: ip = get_ipython()
   ...: ip.showtraceback??
   ...:
Signature: ip.showtraceback(exc_tuple=None, filename=None, tb_offset=None, exception_only=False, running_compiled_code=F
alse)
Source:
    def showtraceback(self, exc_tuple=None, filename=None, tb_offset=None,
                      exception_only=False, running_compiled_code=False):
        """Display the exception that just occurred.

        If nothing is known about the exception, this is the method which
        should be used throughout the code for presenting user tracebacks,
        rather than directly invoking the InteractiveTB object.

        A specific showsyntaxerror() also exists, but this method can take
        care of calling it if needed, so unless you are explicitly catching a
        SyntaxError exception, don't try to analyze the stack manually and
        simply call this method."""

        try:
            try:
                etype, value, tb = self._get_exc_info(exc_tuple)
            except ValueError:
                print('No traceback available to show.', file=sys.stderr)
                return

            if issubclass(etype, SyntaxError):
                # Though this won't be called by syntax errors in the input
                # line, there may be SyntaxError cases with imported code.
                self.showsyntaxerror(filename, running_compiled_code)
            elif etype is UsageError:
                self.show_usage_error(value)
            else:
                if exception_only:
                    stb = ['An exception has occurred, use %tb to see '
                           'the full traceback.\n']
                    stb.extend(self.InteractiveTB.get_exception_only(etype,
                                                                     value))
                else:
                    try:
                        # Exception classes can customise their traceback - we
                        # use this in IPython.parallel for exceptions occurring
                        # in the engines. This should return a list of strings.
                        stb = value._render_traceback_()
                    except Exception:
                        stb = self.InteractiveTB.structured_traceback(etype,
                                            value, tb, tb_offset=tb_offset)

                    self._showtraceback(etype, value, stb)
                    if self.call_pdb:
                        # drop into debugger
                        self.debugger(force=True)
                    return
                # Actually show the traceback
                self._showtraceback(etype, value, stb)

        except KeyboardInterrupt:
            print('\n' + self.get_exception_only(), file=sys.stderr)
File:      d:\python3.6.1\lib\site-packages\ipython\core\interactiveshell.py
Type:      method

In [2]:

```
![image](https://user-images.githubusercontent.com/22249152/27799367-e490515e-5fe2-11e7-8105-61f6c3a1b839.png)

**Comment by takluyver** [comment]
:confused: 

The signature and the source code clearly show that it has the `running_compiled_code` parameter, which the error says it doesn't.

**Comment by georgebv** [comment]
I dunno why - I noticed it too, but I have this error on 3 machines where I had clean installation of python / ipython.

**Comment by takluyver** [comment]
Maybe it's a stale .pyc file somewhere? Doesn't make a lot of sense, but it's a common culprit when the code doesn't match the source.

**Comment by georgebv** [comment]
You were right, I removed the corresponding .pyc and everything is smooth again. You can close this issue, thank you!

**Comment by pietromarchesi** [comment]
I have the same problem, but I don't understand: which .pyc do you mean by the _corresponding_ .pyc?

**Comment by georgebv** [comment]
There is an error in interactiveshell.py - the corresponding .pyc file is interactiveshell.pyc. You can try searching for it in the python directory. Simply delete it and python will "recompile" it when you make a call to it

**Comment by mcdallas** [comment]
Hi @takluyver,  I am having the same issue and when I type 

```
ip = get_ipython()
ip.showtraceback??
```

I am getting 
`Signature: ip.showtraceback(exc_tuple=None, filename=None, tb_offset=None, exception_only=False)`

no `running_compiled_code` parameter. Any Ideas ?

**Comment by mcdallas** [comment]
I downgraded from 6.1.0 to 5.3.0 and everything works fine now

**Comment by Carreau** [comment]
> I downgraded from 6.1.0 to 5.3.0 and everything works fine now

Why 5.3 and not 5.4 ?

Still you should figure out where your stale pyc file is, of you will likely get more issue later on.

**Comment by mcdallas** [comment]
Didn't notice there is a newer one out.

@Carreau I deleted interactiveshell.pyc as suggested above before downgrading but the problem persisted.

**Comment by Carreau** [comment]
Then we need to figure out why. 

```
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.showtraceback??
```

Shoudl give you the file in which `showtraceback` is defined. What is this file, what does the definition of `showtraceback` looks like in this file.

**Comment by khrystyna-skopyk** [comment]
I'm having the same issue with the persistent error but there's no _interactiveshell.pyc_ in `~/miniconda3/lib/python3.6/site-packages/IPython/core` or enywhere else.

Using `IPython 6.1.0`.

```
>> from IPython.core.interactiveshell import InteractiveShell
>> InteractiveShell.showtraceback??

Signature: InteractiveShell.showtraceback(self, exc_tuple=None, filename=None, tb_offset=None, exception_only=False, running_compiled_code=False)
Source:   
    def showtraceback(self, exc_tuple=None, filename=None, tb_offset=None,
                      exception_only=False, running_compiled_code=False):
        """Display the exception that just occurred.

        If nothing is known about the exception, this is the method which
        should be used throughout the code for presenting user tracebacks,
        rather than directly invoking the InteractiveTB object.

        A specific showsyntaxerror() also exists, but this method can take
        care of calling it if needed, so unless you are explicitly catching a
        SyntaxError exception, don\'t try to analyze the stack manually and
        simply call this method."""

        try:
            try:
                etype, value, tb = self._get_exc_info(exc_tuple)
            except ValueError:
                print(\'No traceback available to show.\', file=sys.stderr)
                return

            if issubclass(etype, SyntaxError):
                # Though this won\'t be called by syntax errors in the input
                # line, there may be SyntaxError cases with imported code.
                self.showsyntaxerror(filename, running_compiled_code)
            elif etype is UsageError:
                self.show_usage_error(value)
            else:
                if exception_only:
                    stb = [\'An exception has occurred, use %tb to see \'
                           \'the full traceback.\\']
                    stb.extend(self.InteractiveTB.get_exception_only(etype,
                                                                     value))
                else:
                    try:
                        # Exception classes can customise their traceback - we
                        # use this in IPython.parallel for exceptions occurring
                        # in the engines. This should return a list of strings.
                        stb = value._render_traceback_()
                    except Exception:
                        stb = self.InteractiveTB.structured_traceback(etype,
                                            value, tb, tb_offset=tb_offset)

                    self._showtraceback(etype, value, stb)
                    if self.call_pdb:
                        # drop into debugger
                        self.debugger(force=True)
                    return

                # Actually show the traceback
                self._showtraceback(etype, value, stb)

        except KeyboardInterrupt:
            print(\'\\' + self.get_exception_only(), file=sys.stderr)
File:      ~/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py
Type:      function
```

Any other ideas how to solve this?

**Comment by takluyver** [comment]
Have a look for a `__pycache__` directory - Python 3 stores bytecode files in there.

**Comment by khrystyna-skopyk** [comment]
I found `interactiveshell.cpython-36.pyc` in `__pycache__` and removed it, but the error still persists. Shall I remove other cached files?

**Comment by takluyver** [comment]
Can you show the traceback you're seeing?

**Comment by rockg** [comment]
This may be due to a subclass that calls `run_code` but implements its own `showtraceback`.  For example, I'm seeing this in PyDev using IPython 6.2.1.  Printing `self.showtraceback` reveals that it's a subclass.

self.showtraceback: <bound method PyDevTerminalInteractiveShell.showtraceback of <_pydev_bundle.pydev_ipython_console_011.PyDevTerminalInteractiveShell object at 0x0000000004DCA978>>

Sure enough that class reimplements `showtraceback` and is missing the extra argument. @fabioz

**Comment by khrystyna-skopyk** [comment]
@takluyver Sorry for the belated answer!
Here it is, for example:
```
>>> 'a'+3
Traceback (most recent call last):
  File "/Users/apple/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-34-5a91af991cb1>", line 1, in <module>
    'a'+3
TypeError: must be str, not int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2808, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/apple/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2879, in run_code
    self.showtraceback(running_compiled_code=True)
TypeError: showtraceback() got an unexpected keyword argument 'running_compiled_code'
```

**Comment by takluyver** [comment]
Aha, thanks @rockg for the detective work. @khrystyna-skopyk are you using IPython inside another tool like PyDev, which might have overridden the method?

This is where we suffer for having no properly agreed on public API - we felt free to change that method, and didn't think about people subclassing it.

**Comment by AILalsingh** [comment]
I'm having the same issue. I've deleted the .pyc file and it still occurrs. Here is the output from the traceback:

Signature: InteractiveShell.showtraceback(self, exc_tuple=None, filename=None, tb_offset=None, exception_only=False, running_compiled_code=False)
Source:   
    def showtraceback(self, exc_tuple=None, filename=None, tb_offset=None,
                      exception_only=False, running_compiled_code=False):
        """Display the exception that just occurred.

        If nothing is known about the exception, this is the method which
        should be used throughout the code for presenting user tracebacks,
        rather than directly invoking the InteractiveTB object.

        A specific showsyntaxerror() also exists, but this method can take
        care of calling it if needed, so unless you are explicitly catching a
        SyntaxError exception, don't try to analyze the stack manually and
        simply call this method."""

        try:
            try:
                etype, value, tb = self._get_exc_info(exc_tuple)
            except ValueError:
                print('No traceback available to show.', file=sys.stderr)
                return

            if issubclass(etype, SyntaxError):
                # Though this won't be called by syntax errors in the input
                # line, there may be SyntaxError cases with imported code.
                self.showsyntaxerror(filename, running_compiled_code)
            elif etype is UsageError:
                self.show_usage_error(value)
            else:
                if exception_only:
                    stb = ['An exception has occurred, use %tb to see '
                           'the full traceback.\n']
                    stb.extend(self.InteractiveTB.get_exception_only(etype,
                                                                     value))
                else:
                    try:
                        # Exception classes can customise their traceback - we
                        # use this in IPython.parallel for exceptions occurring
                        # in the engines. This should return a list of strings.
                        stb = value._render_traceback_()
                    except Exception:
                        stb = self.InteractiveTB.structured_traceback(etype,
                                            value, tb, tb_offset=tb_offset)

                    self._showtraceback(etype, value, stb)
                    if self.call_pdb:
                        # drop into debugger
                        self.debugger(force=True)
                    return

                # Actually show the traceback
                self._showtraceback(etype, value, stb)

        except KeyboardInterrupt:
            print('\n' + self.get_exception_only(), file=sys.stderr)
File:      c:\programdata\anaconda3\lib\site-packages\ipython\core\interactiveshell.py
Type:      function

**Comment by takluyver** [comment]
Are you using IPython inside another tool like PyDev, which might have overridden the method?

**Comment by AILalsingh** [comment]
I'm using it to create Plot.ly graphs. I'm not sure if that qualifies as in another program.

**Comment by takluyver** [comment]
I don't think plotly could be involved with this. Since I don't understand it, all I can suggest is uninstalling and reinstallling stuff and hoping that it starts working.

**Comment by khrystyna-skopyk** [comment]
@takluyver Yep, I'm using it inside PyDev.

**Comment by Scharlotten** [comment]
Hi,
I am also seeing this error. 
Is there a solution for this in version 3.6, I also went back to 3.5 and now everything seems to work, but would be great to start using version 6...
Thanks

**Comment by mcdallas** [comment]
@Scharlotten are you running Ipython through PyCharm or another IDE? In my case upgrading PyCharm fixed the issue.

**Comment by fabioz** [comment]
As a note, the latest PyDev release should have this fixed (and pydevd in pypi was also updated to have this fix).

**Comment by Scharlotten** [comment]
I updated PyCharm and now it all works nice and smooth, thanks for this. I couldn't use matplotlib in the same time with this error message: [app = QtGui.QApplication([" "])
AttributeError: module 'PyQt5.QtGui' has no attribute 'QApplication' ](url)
But this also seems to have solved the issue.
Thanks, again

**Comment by Shahinur-Shakib** [comment]
I'm facing some problem about this code on pycharm but same code is ok on spyder

import numpy as np
from keras.preprocessing import image
test_image = image.load_img('C:/Users/Shahinur Shakib/PycharmProjects/OK2/Datasets/test_set/Cat/6922.jpg', target_size = (64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = classifier.predict(test_image)
training_set.class_indices
if result[0][0] == 1:
    prediction = 'dog'
else:
    prediction = 'cat'
print(prediction)


Traceback (most recent call last):
  File "G:\anaconda_installation_file\lib\site-packages\IPython\core\interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-e2c6e2e7e2fd>", line 6, in <module>
    result = classifier.predict(test_image)
NameError: name 'classifier' is not defined

**Comment by selamabebeselam** [comment]
Traceback (most recent call last):

  File "C:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-2b26fc3ef99b>", line 1, in <module>
    import matplotlib.pyplot as plt

  File "C:\Anaconda\lib\site-packages\matplotlib\__init__.py", line 107, in <module>
    from . import cbook, rcsetup

  File "C:\Anaconda\lib\site-packages\matplotlib\cbook\__init__.py", line 28, in <module>
    import numpy as np

  File "C:\Anaconda\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core

  File "C:\Anaconda\lib\site-packages\numpy\core\__init__.py", line 81, in <module>
    from . import function_base

  File "C:\Anaconda\lib\site-packages\numpy\core\function_base.py", line 113
    num = operator.index(num)
                             ^
IndentationError: unindent does not match any outer indentation level
