### ISSUE TITLE
Exception throwed when type(item) != type(line), 

### ISSUE THREAD

**Issue by newbie-Leo** [ipython/ipython#10681]
```
    item += '    %s\n' % line.strip()

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 48: ordinal not in range(128)
```

When Chinese in my code and "Traceback" showed， UnicodeDecodeError occured,
mybe need
```
                if type(line) == unicode:
                    item += '    %s\n' % line.strip()
                else:
                    .............
```
in ultratb.py

**Comment by srinivasreddy** [comment]
can you paste the output of line?

**Comment by newbie-Leo** [comment]
```
line = "data = pd.read_excel(dish_profit, index_col = u'\xe8\x8f\x9c\xe5\x93\x81\xe5\x90\x8d')"
item = u'  File \x1b[0;32m"C:/Users/liurunze/Desktop/data_learn/3-3_dish_pareto.py"\x1b[0m, line \x1b[0;32m8\x1b[0m, in \x1b[0;35m<module>\x1b[0m\n'
```

**Comment by newbie-Leo** [comment]
Ok !   the output is this


I found line = "data = pd.read_excel(dish_profit, index_col = u'\xe8\x8f\x9c\xe5\x93\x81\xe5\x90\x8d')"
item = u'  File \x1b[0;32m"C:/Users/liurunze/Desktop/data_learn/3-3_dish_pareto.py"\x1b[0m, line \x1b[0;32m8\x1b[0m, in \x1b[0;35m<module>\x1b[0m\n'
When i edited ultratb.py line 682 like this:

The line and item in Traceback returned to normal


I am using 
Python 2.7.13 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:17:26) [MSC v.1500 64 bit (AMD64)]

Type "copyright", "credits" or "license" for more information.



IPython 5.3.0 -- An enhanced Interactive Python.

Now the code in https://github.com/ipython/ipython/blob/master/IPython/core/ultratb.py   is line 656






lrz4119@163.com
 From: Srinivas Reddy ThatiparthyDate: 2017-06-28 19:14To: ipython/ipythonCC: Runze Liu; AuthorSubject: Re: [ipython/ipython] Exception throwed when type(item) != type(line), (#10681)can you paste the output of line?
