### ISSUE TITLE
ipython 6.1.0 ansi color style attribute seem not work.

### ISSUE THREAD

**Issue by sunose** [ipython/ipython#10682]
now using window 10 console cmd.exe
**python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.**

the ansi color escape codes underline style not work.
print("\033[4;37;40m Underlined text\033[0m \n")

**Comment by Carreau** [comment]
does it work in pain Python console ? IPython does not process the escape code. your console does. If it does not work in your console it is likely a bug in your console.

**Comment by takluyver** [comment]
@Carreau that's not quite accurate on Windows - we set up the `colorama` library to transform ANSI escapes into Windows console API calls.

@sunose Do you see colours in the output of `zip?`?

**Comment by sunose** [comment]
@takluyver  most ansi color scheme worked,but only Underline style not work.
it seem ansi convert to win32 miss underline style.

**Comment by takluyver** [comment]
In that case, I think you need to request it as a feature in [colorama](https://github.com/tartley/colorama/). I don't think we use underlines anywhere within IPython, so this isn't a bug from our point of view.

**Comment by Carreau** [comment]
6.x is old stable..closing.
