### ISSUE TITLE
AttributeError: ipython fails due to sys.platform="win32"

### ISSUE THREAD

**Issue by dropnz** [ipython/ipython#10685]
in python shell it works find: 
```
$ python2
Python 2.7.13 (default, Feb 11 2017, 12:22:40) 
[GCC 6.3.1 20170109] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.platform = "win32"
>>> 

```

***************************************************************************

IPython post-mortem report

{'commit_hash': u'<not found>',
 'commit_source': '(none found)',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/lib/python2.7/site-packages/IPython',
 'ipython_version': '5.3.0',
 'os_name': 'posix',
 'platform': 'Linux-4.11.5-1-ARCH-x86_64-with-glibc2.2.5',
 'sys_executable': '/usr/bin/python2',
 'sys_platform': 'win32',
 'sys_version': '2.7.13 (default, Feb 11 2017, 12:22:40) \n[GCC 6.3.1 20170109]'}

***************************************************************************

***************************************************************************

Crash traceback:

---------------------------------------------------------------------------
---------------------------------------------------------------------------
AttributeError                              Python 2.7.13: /usr/bin/python2
                                                   Thu Jun 29 18:21:49 2017
A problem occurred executing Python code.  Here is the sequence of function
calls leading up to the error, with the most recent (innermost) call last.
/usr/bin/ipython2 in <module>()
      1 #!/usr/bin/python2
      2 # This script was automatically generated by setup.py
      3 if __name__ == '__main__':
      4     from IPython import start_ipython
----> 5     start_ipython()
        global start_ipython = <function start_ipython at 0x7f0b9f9d7050>

/usr/lib/python2.7/site-packages/IPython/__init__.pyc in start_ipython(argv=None, **kwargs={})
    104     This is a public API method, and will survive implementation changes.
    105     
    106     Parameters
    107     ----------
    108     
    109     argv : list or None, optional
    110         If unspecified or None, IPython will parse command-line options from sys.argv.
    111         To prevent any command-line parsing, pass an empty list: `argv=[]`.
    112     user_ns : dict, optional
    113         specify this dictionary to initialize the IPython user namespace with particular values.
    114     kwargs : various, optional
    115         Any other kwargs will be passed to the Application constructor,
    116         such as `config`.
    117     """
    118     from IPython.terminal.ipapp import launch_new_instance
--> 119     return launch_new_instance(argv=argv, **kwargs)
        launch_new_instance = <bound method MetaHasTraits.launch_instance of <class 'IPython.terminal.ipapp.TerminalIPythonApp'>>
        argv = None
        kwargs = {}
    120 
    121 def start_kernel(argv=None, **kwargs):
    122     """Launch a normal IPython kernel instance (as opposed to embedded)
    123     
    124     `IPython.embed_kernel()` puts a shell in a particular calling scope,
    125     such as a function or method for debugging purposes,
    126     which is often not desirable.
    127     
    128     `start_kernel()` does full, regular IPython initialization,
    129     including loading startup files, configuration, etc.
    130     much of which is skipped by `embed()`.
    131     
    132     Parameters
    133     ----------
    134     

/usr/lib/python2.7/site-packages/traitlets/config/application.pyc in launch_instance(cls=<class 'IPython.terminal.ipapp.TerminalIPythonApp'>, argv=None, **kwargs={})
    643             lines.append(cls.class_config_section())
    644         return '\n'.join(lines)
    645 
    646     def exit(self, exit_status=0):
    647         self.log.debug("Exiting application: %s" % self.name)
    648         sys.exit(exit_status)
    649 
    650     @classmethod
    651     def launch_instance(cls, argv=None, **kwargs):
    652         """Launch a global instance of this Application
    653 
    654         If a global instance already exists, this reinitializes and starts it
    655         """
    656         app = cls.instance(**kwargs)
    657         app.initialize(argv)
--> 658         app.start()
        app.start = <bound method TerminalIPythonApp.start of <IPython.terminal.ipapp.TerminalIPythonApp object at 0x7f0ba6c2f2d0>>
    659 
    660 #-----------------------------------------------------------------------------
    661 # utility functions, for convenience
    662 #-----------------------------------------------------------------------------
    663 
    664 def boolean_flag(name, configurable, set_help='', unset_help=''):
    665     """Helper for building basic --trait, --no-trait flags.
    666 
    667     Parameters
    668     ----------
    669 
    670     name : str
    671         The name of the flag.
    672     configurable : str
    673         The 'Class.trait' string of the trait to be set/unset with the flag

/usr/lib/python2.7/site-packages/IPython/terminal/ipapp.pyc in start(self=<IPython.terminal.ipapp.TerminalIPythonApp object>)
    333         if self.log_level <= logging.INFO: print()
    334 
    335     def _pylab_changed(self, name, old, new):
    336         """Replace --pylab='inline' with --pylab='auto'"""
    337         if new == 'inline':
    338             warnings.warn("'inline' not available as pylab backend, "
    339                       "using 'auto' instead.")
    340             self.pylab = 'auto'
    341 
    342     def start(self):
    343         if self.subapp is not None:
    344             return self.subapp.start()
    345         # perform any prexec steps:
    346         if self.interact:
    347             self.log.debug("Starting IPython's mainloop...")
--> 348             self.shell.mainloop()
        self.shell.mainloop = <bound method TerminalInteractiveShell.mainloop of <IPython.terminal.interactiveshell.TerminalInteractiveShell object at 0x7f0b9f94f110>>
    349         else:
    350             self.log.debug("IPython not interactive...")
    351 
    352 def load_default_config(ipython_dir=None):
    353     """Load the default config file from the default ipython_dir.
    354 
    355     This is useful for embedded shells.
    356     """
    357     if ipython_dir is None:
    358         ipython_dir = get_ipython_dir()
    359 
    360     profile_dir = os.path.join(ipython_dir, 'profile_default')
    361 
    362     config = Config()
    363     for cf in Application._load_config_files("ipython_config", path=profile_dir):

/usr/lib/python2.7/site-packages/IPython/terminal/interactiveshell.pyc in mainloop(self=<IPython.terminal.interactiveshell.TerminalInteractiveShell object>, display_banner=<object object>)
    471                 if (not self.confirm_exit) \
    472                         or self.ask_yes_no('Do you really want to exit ([y]/n)?','y','n'):
    473                     self.ask_exit()
    474 
    475             else:
    476                 if code:
    477                     self.run_cell(code, store_history=True)
    478 
    479     def mainloop(self, display_banner=DISPLAY_BANNER_DEPRECATED):
    480         # An extra layer of protection in case someone mashing Ctrl-C breaks
    481         # out of our internal code.
    482         if display_banner is not DISPLAY_BANNER_DEPRECATED:
    483             warn('mainloop `display_banner` argument is deprecated since IPython 5.0. Call `show_banner()` if needed.', DeprecationWarning, stacklevel=2)
    484         while True:
    485             try:
--> 486                 self.interact()
        self.interact = <bound method TerminalInteractiveShell.interact of <IPython.terminal.interactiveshell.TerminalInteractiveShell object at 0x7f0b9f94f110>>
    487                 break
    488             except KeyboardInterrupt as e:
    489                 print("\n%s escaped interact()\n" % type(e).__name__)
    490             finally:
    491                 # An interrupt during the eventloop will mess up the
    492                 # internal state of the prompt_toolkit library.
    493                 # Stopping the eventloop fixes this, see
    494                 # https://github.com/ipython/ipython/pull/9867
    495                 if hasattr(self, '_eventloop'):
    496                     self._eventloop.stop()
    497 
    498     _inputhook = None
    499     def inputhook(self, context):
    500         if self._inputhook is not None:
    501             self._inputhook(context)

/usr/lib/python2.7/site-packages/IPython/terminal/interactiveshell.pyc in interact(self=<IPython.terminal.interactiveshell.TerminalInteractiveShell object>, display_banner=<object object>)
    454                 # Older version of prompt_toolkit; it's OK to set the document
    455                 # directly here.
    456                 set_doc()
    457             self.rl_next_input = None
    458 
    459     def interact(self, display_banner=DISPLAY_BANNER_DEPRECATED):
    460 
    461         if display_banner is not DISPLAY_BANNER_DEPRECATED:
    462             warn('interact `display_banner` argument is deprecated since IPython 5.0. Call `show_banner()` if needed.', DeprecationWarning, stacklevel=2)
    463 
    464         self.keep_running = True
    465         while self.keep_running:
    466             print(self.separate_in, end='')
    467 
    468             try:
--> 469                 code = self.prompt_for_code()
        code = u'sys.platform="win32"'
        self.prompt_for_code = <bound method TerminalInteractiveShell.prompt_for_code of <IPython.terminal.interactiveshell.TerminalInteractiveShell object at 0x7f0b9f94f110>>
    470             except EOFError:
    471                 if (not self.confirm_exit) \
    472                         or self.ask_yes_no('Do you really want to exit ([y]/n)?','y','n'):
    473                     self.ask_exit()
    474 
    475             else:
    476                 if code:
    477                     self.run_cell(code, store_history=True)
    478 
    479     def mainloop(self, display_banner=DISPLAY_BANNER_DEPRECATED):
    480         # An extra layer of protection in case someone mashing Ctrl-C breaks
    481         # out of our internal code.
    482         if display_banner is not DISPLAY_BANNER_DEPRECATED:
    483             warn('mainloop `display_banner` argument is deprecated since IPython 5.0. Call `show_banner()` if needed.', DeprecationWarning, stacklevel=2)
    484         while True:

/usr/lib/python2.7/site-packages/IPython/terminal/interactiveshell.pyc in prompt_for_code(self=<IPython.terminal.interactiveshell.TerminalInteractiveShell object>)
    348                         processor=HighlightMatchingBracketProcessor(chars='[](){}'),
    349                         filter=HasFocus(DEFAULT_BUFFER) & ~IsDone() &
    350                             Condition(lambda cli: self.highlight_matching_brackets))],
    351                 }
    352 
    353     def _update_layout(self):
    354         """
    355         Ask for a re computation of the application layout, if for example ,
    356         some configuration options have changed.
    357         """
    358         if self._pt_app:
    359             self._pt_app.layout = create_prompt_layout(**self._layout_options())
    360 
    361     def prompt_for_code(self):
    362         document = self.pt_cli.run(
--> 363             pre_run=self.pre_prompt, reset_current_buffer=True)
        global pre_run = undefined
        self.pre_prompt = <bound method TerminalInteractiveShell.pre_prompt of <IPython.terminal.interactiveshell.TerminalInteractiveShell object at 0x7f0b9f94f110>>
        global reset_current_buffer = undefined
        global True = undefined
    364         return document.text
    365 
    366     def enable_win_unicode_console(self):
    367         if sys.version_info >= (3, 6):
    368             # Since PEP 528, Python uses the unicode APIs for the Windows
    369             # console by default, so WUC shouldn't be needed.
    370             return
    371 
    372         import win_unicode_console
    373 
    374         if PY3:
    375             win_unicode_console.enable()
    376         else:
    377             # https://github.com/ipython/ipython/issues/9768
    378             from win_unicode_console.streams import (TextStreamWrapper,

/usr/lib/python2.7/site-packages/prompt_toolkit/interface.pyc in run(self=<prompt_toolkit.interface.CommandLineInterface object>, reset_current_buffer=True, pre_run=<bound method TerminalInteractiveShell.pre_promp...nteractiveshell.TerminalInteractiveShell object>>)
    397             place. This allows custom initialisation.
    398         """
    399         assert pre_run is None or callable(pre_run)
    400 
    401         try:
    402             self._is_running = True
    403 
    404             self.on_start.fire()
    405             self.reset()
    406 
    407             # Call pre_run.
    408             self._pre_run(pre_run)
    409 
    410             # Run eventloop in raw mode.
    411             with self.input.raw_mode():
--> 412                 self.renderer.request_absolute_cursor_position()
        self.renderer.request_absolute_cursor_position = <bound method Renderer.request_absolute_cursor_position of <prompt_toolkit.renderer.Renderer object at 0x7f0b9f6b15d0>>
    413                 self._redraw()
    414 
    415                 self.eventloop.run(self.input, self.create_eventloop_callbacks())
    416         finally:
    417             # Clean up renderer. (This will leave the alternate screen, if we use
    418             # that.)
    419 
    420             # If exit/abort haven't been called set, but another exception was
    421             # thrown instead for some reason, make sure that we redraw in exit
    422             # mode.
    423             if not self.is_done:
    424                 self._exit_flag = True
    425                 self._redraw()
    426 
    427             self.renderer.reset()

/usr/lib/python2.7/site-packages/prompt_toolkit/renderer.pyc in request_absolute_cursor_position(self=<prompt_toolkit.renderer.Renderer object>)
    328             raise HeightIsUnknownError('Rows above layout is unknown.')
    329 
    330     def request_absolute_cursor_position(self):
    331         """
    332         Get current cursor position.
    333         For vt100: Do CPR request. (answer will arrive later.)
    334         For win32: Do API call. (Answer comes immediately.)
    335         """
    336         # Only do this request when the cursor is at the top row. (after a
    337         # clear or reset). We will rely on that in `report_absolute_cursor_row`.
    338         assert self._cursor_pos.y == 0
    339 
    340         # For Win32, we have an API call to get the number of rows below the
    341         # cursor.
    342         if is_windows():
--> 343             self._min_available_height = self.output.get_rows_below_cursor_position()
        self._min_available_height = 0
        self.output.get_rows_below_cursor_position = undefined
    344         else:
    345             if self.use_alternate_screen:
    346                 self._min_available_height = self.output.get_size().rows
    347             else:
    348                 # Asks for a cursor position report (CPR).
    349                 self.waiting_for_cpr = True
    350                 self.output.ask_for_cpr()
    351 
    352     def report_absolute_cursor_row(self, row):
    353         """
    354         To be called when we know the absolute cursor position.
    355         (As an answer of a "Cursor Position Request" response.)
    356         """
    357         # Calculate the amount of rows from the cursor position until the
    358         # bottom of the terminal.

AttributeError: 'Vt100_Output' object has no attribute 'get_rows_below_cursor_position'

***************************************************************************

History of session input:get_ipython().magic(u'config Application.verbose_crash=True')import syssys.platform="win32"
*** Last line of input (may not be in above history):
sys.platform="win32"

**Comment by Carreau** [comment]
Hum,  technically you should not really assign to that. I doubt we can protect against dynamically changing this value as a lot of underlying library will peek at sys.platform to change their behavior.

**Comment by dropnz** [comment]
this "bug" don't bother me. I just thought that you would be interested to know about that
