### ISSUE TITLE
quit from attached kernel with keep_kernel=True when Ctrl-\ is pressed

### ISSUE THREAD

**Issue by lebedov** [ipython/ipython#10701]
In the past, it was possible to exit an IPython console instance connected to a running kernel without terminating the latter by pressing Ctrl-\. With IPython 5.3.0 (used with Python 2.7.13), this no longer appears to be the case; I have to manually run `quit(keep_kernel=True)`, and Ctrl-\ doesn't have any effect. Does the console frontend catch SIGQUIT? If so, is there some way to enable the old behavior (either programatically or via a config option)?

**Comment by takluyver** [comment]
NB IPython does not act as a frontend for Jupyter kernels - if you're using a Jupyter frontend in the terminal, that's now [jupyter_console](https://github.com/jupyter/jupyter_console)

**Comment by lebedov** [comment]
Resubmitting as jupyter_console issue.
