### ISSUE TITLE
Autocompletion works in iPython but not in jupyter-console

### ISSUE THREAD

**Issue by verginer** [ipython/ipython#10715]
I am having trouble using auto-complete in jupyter while not in ipython.

I am trying to use this package ([pathpy](https://github.com/verginer/pathpy)) in jupyter,
but as soon as I import it and hit `pathpy.<TAB>` i get the following erro message and auto completion stops working completely. 

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "~/anaconda3/envs/scimob/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "~/anaconda3/envs/scimob/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 434, in complete_request
    matches = self.do_complete(code, cursor_pos)
  File "~/anaconda3/envs/scimob/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 257, in do_complete
    txt, matches = self.shell.complete('', line, line_cursor)
  File "~/anaconda3/envs/scimob/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 1974, in complete
    return self.Completer.complete(text, line, cursor_pos)
  File "~r/anaconda3/envs/scimob/lib/python3.6/site-packages/IPython/core/completer.py", line 1837, in complete
    PendingDeprecationWarning)
PendingDeprecationWarning: `Completer.complete` is pending deprecation since IPython 6.0 and will be replaced by `Completer.completions`.
```
I have tried to isolate the problem by selectively removing parts from the package, but I can't
figure out the cause of the error.

The strange thing is that autocompletion works in iPython while not Jupyter, it might have something to do with `jedi`, but don't know enough to debug it.

Version details:

```
{'commit_hash': 'd86648c5d',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '~/anaconda3/envs/scimob/lib/python3.6/site-packages/IPython',
 'ipython_version': '6.1.0',
 'os_name': 'posix',
 'platform': 'Darwin-16.6.0-x86_64-i386-64bit',
 'sys_executable': '~/anaconda3/envs/scimob/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, '
                '13:14:59) \n'
                '[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]'}
```

```
$ jupyter console --version
5.1.0
```

**Comment by takluyver** [comment]
Somethign is setting the [warnings filter](https://docs.python.org/3/library/warnings.html#the-warnings-filter) to turn warnings into errors. So that warning, which you can safely ignore, is being raised as an error.

**Comment by verginer** [comment]
That was exactly the problem thanks!
After removing `warnings.filterwarnings('error')` autocomplete works perfectly again.

**Comment by takluyver** [comment]
Great :-)

It's an unfortunate side effect of running IPython code in the same interpreter as user code - global changes made by user code can interact badly with IPython.
