### ISSUE TITLE
ipython freezes when using ctrl-space and autocomplete does not work anymore

### ISSUE THREAD

**Issue by floatingpurr** [ipython/ipython#10714]
I've ever worked with ipython inside a virtualenv without problems. 

Now I'm experiencing a strange behaviour. When I hit ctrl+space for the autocomplete, it does not work anymore and ipython seems stuck. There is the same problem outside of that virtualenv :/

I've already tried to remove and reinstall ipython with no luck. I don't know if it could be the cause, but I had just installed jupyter in the same virtualenv.

I'm working with Python 2 on Ubuntu 16.04 LTS

**Comment by Carreau** [comment]
Control-Space toggle selection. Completion is Tab.

![select](https://user-images.githubusercontent.com/335567/28579249-f520db30-7110-11e7-9fba-fb958d51c26b.gif)

Does that make sens ?

**Comment by superciccio14** [comment]
Yep, thanks! It does really make sense. I'm using too much editors and I was confusing about the shortcuts. Sorry for the question.

**Comment by UgurcanAkkok** [comment]
but why does it freeze? it is really annoying

**Comment by Carreau** [comment]
> but why does it freeze

It does not freeze. It is in selection mode. Press Ctrl-space again to exit selection mode.

**Comment by tombohub** [comment]
@Carreau its still freeze, does not help

**Comment by jayemes** [comment]
> @Carreau its still freeze, does not help

@tombohub Try pressing Del. That solves it for me

**Comment by Carreau** [comment]
Closing;
