### ISSUE TITLE
runtime configuration when embedding ipython

### ISSUE THREAD

**Issue by blueForestIcarus** [ipython/ipython#10724]
It seems that there is no way to set configuration options from a Python source file before embedding (either with .embed or .start_ipython). For example, I would like to set exec_lines right before calling start_ipython or embed. The versatility and simplicity of a python based configuration system are lost if the programmer does not have the ability to set configuration options in his own code just as they are set in the config file. If this is possible in the current system, then it should be documented (I looked through the IPython and Traitlets doc's and haven't seen anything), otherwise, I believe it should be added.

**Comment by takluyver** [comment]
Something like this:

```python
from traitlets.config import Config
import IPython
c = Config()
c.Class.config_value = 'foo'
IPython.start_ipython(config=c)
```

**Comment by blueForestIcarus** [comment]
After seeing your response and looking back at the [docs](https://ipython.readthedocs.io/en/stable/interactive/reference.html) I noticed similar code In one of the embed examples; my bad, I should have looked closer.

**Comment by takluyver** [comment]
Yeah, docs can be tricky - there's a million things people might want to do, and it's not obvious where to look, or where to put things for people to find. Where were you looking for this? Is there somewhere where an example would clearly benefit from showing it?

**Comment by blueForestIcarus** [comment]
The best place for an example would probably be here https://ipython.readthedocs.io/en/stable/config/intro.html. That was where I first looked for config documentation, and it explained three ways to set configuration but lacked any information on how to set configuration when embedding IPython. A fourth section to this page with an example would be great, and a link to it from [this](https://ipython.readthedocs.io/en/stable/interactive/reference.html#embedding-ipython) page would be useful as well.

**Comment by takluyver** [comment]
Sounds sensible. Do you want to make a PR adding a short section about it? The docs are in the `docs/source` folder of this repo.
