### ISSUE TITLE
tab completion now ignores case?

### ISSUE THREAD

**Issue by cottrell** [ipython/ipython#10728]
I looks like the new tab completion now ignores case. In the old versions of IPython this was not the case. Not a big deal really, but probably should be reverted if not intended.

 $ cat j.py
def this_one():
    pass

def this_ONE():
    pass

In [2]: j.this_O<TAB>
                 this_ONE()
                 this_one()

**Comment by Carreau** [comment]
Yes, I believe that is recent. You can also have a look at https://github.com/ipython/ipython/pull/10537/ which also add some fuzzy matching. I don't remember which PR made completion case insensitive though.

**Comment by cottrell** [comment]
Anyone know how to turn this off? I would vote for case sensitive being default given past behaviour and usage patterns in python.

**Comment by cottrell** [comment]
This seems to get rid of the bad column displays where it doesn't show you all the options.

`c.TerminalInteractiveShell.display_completions = 'readlinelike'
`

**Comment by pitrou** [comment]
I would also like to turn this off. False positives due to case insensitive matching are annoying as they lead to more typing.

**Comment by cottrell** [comment]
https://github.com/cottrell/ipython/commit/c07e32e1f996966e1322b679f6734816cfae567b

**Comment by GF-Huang** [comment]
4 years, any progress?

**Comment by GF-Huang** [comment]
> I would also like to turn this off. False positives due to case insensitive matching are annoying as they lead to more typing.

How did you turn it on?

**Comment by GF-Huang** [comment]
I want to turn it on, how to do that???????????????

**Comment by MrMino** [comment]
@GF-Huang Instead of duplicating your comments and abusing the question mark key, you could've just look into commits linked in this issue:

https://github.com/cottrell/ipython/commit/2903df30ec5ce51ac0abcdf12a90ce5d5fb380c1#diff-f10e4b6051cca1d8ce27936518d6908de43b5fd861902cd3923a4342e8d4fc5aR146-R147

![image](https://user-images.githubusercontent.com/6691643/133717259-9049c720-fa1c-4a6a-88e4-44518648f34c.png)

⬇

![image](https://user-images.githubusercontent.com/6691643/133717357-f33bfcf8-544e-40a5-95a0-f934b3ef6443.png)

Simple stuff. Read the code. Don't expect others to do it for you. Don't be a nuisance.

**Comment by MrMino** [comment]
I think this issue has been settled. The status-quo has been agreed upon in #10999, if someone wants to challange it - please raise a separate issue.

The behavior outlined in this post can be achieved using

```
import jedi
jedi.settings.case_insensitive_completion = True
```

**Comment by GF-Huang** [comment]
> I think this issue has been settled. The status-quo has been agreed upon in #10999, if someone wants to challenge it - please raise a separate issue.
> 
> Previous behavior can be achieved using
> 
> ```python
> import jedi
> jedi.settings.case_insensitive_completion = True
> ```

So I must type these codes every time when I launch ipython and jupyterlab? There is not a global setting?

**Comment by MrMino** [comment]
You can put it into config. Please familiarize yourself with the documentation.

https://ipython.readthedocs.io/en/stable/config/intro.html#setting-configurable-options

**Comment by GF-Huang** [comment]
> You can put it into config. Please familiarize yourself with the documentation.
> 
> [ipython.readthedocs.io/en/stable/config/intro.html#setting-configurable-options](https://ipython.readthedocs.io/en/stable/config/intro.html#setting-configurable-options)

Thank you very much, you solve my long time issue.
