### ISSUE TITLE
Failed magic import appears not to throw error

### ISSUE THREAD

**Issue by jpvelez** [ipython/ipython#10736]
I'm trying to test that an ipython magic works inside of jupyter by doing this: `jupyter nbconvert --execute --to html tests/bigquery.ipynb`, where the `biquery.ipynb` notebook imports a magic called `%bigquery`. Currently, the `%bigquery` magic, which allows you to query Google's BigQuery service, is not importing due to a config problem.

Unexpectedly, even though the output html says `ERROR:root:Line magic function %bigquery not found.`, the jupyter nbconvert command itself does not crash, even though it's supposed to if any exceptions arise. 

If it doesn't crash when it's supposed to, I can't reliably test whether the magic is in fact working. This appears to be the default ipython behavior. As @minrk put it in gitter: "The error handling in magics is probably an IPython thing. For a long time, the only thing that mattered for IPython was what it looked like. But then Jupyter came around, and it now makes a difference whether an error was raised, or just 'reported' to output. This is the kind of thing that affects nbconvert's "this failed". But there are still a number of 'errors' that are caught and displayed as nicer errors than tracebacks, but now Jupyter frontends don't know that the cell failed."

To reproduce the issue in ipython:
```python
In [2]: import IPython
In [3]: shell = IPython.core.interactiveshell.InteractiveShell.instance()
In [4]: shell.run_cell('%bigquery')
ERROR:root:Line magic function `%bigquery` not found.
Out[4]: <ExecutionResult object at 7f27b7605e50, execution_count=None error_before_exec=None error_in_exec=None result=None>
```

Just wanted to flag this bug!

**Comment by minrk** [comment]
Thanks for reporting! Should be fixed by #10737
