### ISSUE TITLE
Attempting to interrupt the kernel while autocomplete is thinking crashes the runtime

### ISSUE THREAD

**Issue by craigcitro** [ipython/ipython#10733]
Backstory: we've added some custom completers, some of which do things that amount to making a network request (say to find out the potential arguments to a function). Sometimes, this can be slow, and users are tempted to interrupt their kernel. Doing so then crashes the kernel.

Here's a really goofy repro:

```
def bad_completer(*args, **kwargs):
    import time
    time.sleep(10)
    return ['houses']

get_ipython().set_hook('complete_command', bad_completer, re_key='%%file')

%%file <TAB>
```

and then interrupt while you're waiting.

A naive fix would be to simply catch any exception [here](https://github.com/ipython/ipython/blob/268a37740656a2cfb033e6803e2459fdf4ece516/IPython/core/completer.py#L1703), but I'm not sure if that should happen in a more central place. 

In particular, if a user does interrupt a completer, do we want to continue with the next one, or cancel completion completely?

**Comment by Carreau** [comment]
Ouch, thanks, we should definitively not crash. 

I'm slowly thinking on how we can make a better completer, in particular now that master is Python 3 only I have the vague plan on trying to make everything generator/coroutine. I also want to implement a kind of timeout for completer. If you have any ideas about that that they are welcome.

**Comment by chmp** [comment]
A very similar issue arises on the code path for non-custom completes (see [here](https://github.com/ipython/ipykernel/issues/261)).
