### ISSUE TITLE
Linux CLI: Can't select nor copy

### ISSUE THREAD

**Issue by ormung** [ipython/ipython#10742]
Linux, tried with gnome-terminal and xterm. Ipython 6.1.

Curiously, I can select and copy when using ipython through the jupyter console.

**Comment by takluyver** [comment]
How are you trying to select and copy? If you're trying to do it with keyboard shortcuts, it's possible that the interface interferes with them. I use gnome-terminal normally, and I can select and copy using the mouse.

**Comment by ormung** [comment]
I tried with a fresh config, and it worked for me too. Found the problem! I had to disable "c.TerminalInteractiveShell.mouse_support", which I had set to True.
Maybe it could be useful for others to change the config from:

```
## Enable mouse support in the prompt
```

to 
```
## Enable mouse support in the prompt
## (note: prevents selecting text with the mouse)
```

as it's a bit counterintuitive, to me at least.

**Comment by takluyver** [comment]
Ah, thanks for the follow up. The description comes from here if you want to make a pull request: https://github.com/ipython/ipython/blob/5319d5c06637ec34b6401a189f49975ce16fe55a/IPython/terminal/interactiveshell.py#L128
