### ISSUE TITLE
`%matplotlib` is not showing when pressing tab for autocompletation after `%pylab`

### ISSUE THREAD

**Issue by rubennj** [ipython/ipython#10754]
The issue appears in IPython 6.1, but not in 6.0
I first realize about it using Spyder: spyder-ide/spyder#5020

Nevertheless, even if it is not shown, `%matplotlib`can be executed and it works.

**Comment by Carreau** [comment]
Copying my answer from linked issue:

That's a side effect of https://github.com/ipython/ipython/pull/10542, basically %pylab injects `matplotlib` into the namespace and thus is not completed as a magic anymore. This was requested in  https://github.com/ipython/ipython/issues/4877, We should probably be less extream and still complete to magics if the text starts with `%`/`%%`
