### ISSUE TITLE
Documentation ipykernel add install instructions

### ISSUE THREAD

**Issue by NumesSanguis** [ipython/ipython#10763]
Please add something like the following:

If you want to have multiple IPython kernels for different virtualenvs or conda environments, you will need to specify unique names for the kernelspecs.

Make sure you have installed `ipykernel` into your environment before you continue:

    source activate myenv
    conda install ipykernel

to http://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-different-environments. 

Would have saved me (and probably others) issues like:
https://github.com/jupyter/jupyter/issues/245#issuecomment-325551156

p.s. `Edit on Github` button in top-right of documentation is broken.

**Comment by Carreau** [comment]
> p.s. Edit on Github button in top-right of documentation is broken.

Hum, you may have encounterd a github bug. Tags have apparently a commitish that differs from the commit they point to, and github does not expose that...
