### ISSUE TITLE
error opening an old ipynb file

### ISSUE THREAD

**Issue by en-wai** [ipython/ipython#10762]
I created and ipynb file about a year ago and I am trying to open it now on my Mac but I get the following error:
 
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdb in position 131076: invalid continuation byte

I get the same error when I try to convert this notebook to html too.

**Comment by takluyver** [comment]
Something may have erroneously saved it in another encoding. This Python code should re-encode it so you can open it, but it might contain some mistakes if latin-1 isn't correct either.

```python
with open('broken.ipynb', 'r', encoding='latin1') as fin, open('fixed.ipynb', 'w', encoding='utf-8') as fout:
    fout.write(fin.read())
```
