### ISSUE TITLE
Documentation for 5.x LTS on readthedocs.io?

### ISSUE THREAD

**Issue by rolweber** [ipython/ipython#10765]
ipython.readthedocs.io shows a prominent notice which refers to "the IPython 5.x LTS release". Would it be possible to publish the documentation for that LTS release alongside the current and latest versions? Or is it already published and I just don't know where to find it?

https://ipython.readthedocs.io/en/latest/    6.2.0 dev
https://ipython.readthedocs.io/en/stable/   6.1.0
https://ipython.readthedocs.io/en/lts/         (does not exist)

Or maybe create "ipython-lts.readthedocs.io" with its own stable and latest versions?

**Comment by takluyver** [comment]
http://ipython.readthedocs.io/en/5.x/

We could probably get rid of the "development version" warning on that - it's technically accurate, because the docs are not built from a release tag, but it won't be significantly different from the last 5.x release.

**Comment by rolweber** [comment]
Thanks!

**Comment by rolweber** [comment]
And now I also spotted the drop-down menu on the bottom left for switching between versions...
