### ISSUE TITLE
New namespace for Demo class

### ISSUE THREAD

**Issue by pepie34** [ipython/ipython#10771]
https://github.com/ipython/ipython/blob/ca86b79bfd5cdd633ea6cb9c18bb2c1c493402a1/IPython/lib/demo.py#L112

"from IPython.demo import Demo"  should be "from IPython.lib.demo import Demo"

**Comment by takluyver** [comment]
Thanks - do you want to make a pull request?

**Comment by pepie34** [comment]
Done here https://github.com/ipython/ipython/pull/10775

**Comment by takluyver** [comment]
Thanks!
