### ISSUE TITLE
Test group: utils from iptest fails with encoding errors

### ISSUE THREAD

**Issue by teojgo** [ipython/ipython#10780]
When running iptest in a system with character encoding other than utf-8 the following error appears:

`ERROR: IPython.utils.tests.test_path.test_ensure_dir_exists`

The error can be easily reproduced in a Linux system by running the following commands before executing iptest:

```
sudo locale-gen es_CO
export LANG=es_CO
```

The errors seems to be caused by the following two lines of IPython/utils/tests/test_path.py:
399 -> d = os.path.join(td, '∂ir')
403 ->  f = os.path.join(td, 'ƒile')

which contain characters ∂ and ƒ respectively.

**Comment by takluyver** [comment]
Thanks, I think #10782 should fix it.
