### ISSUE TITLE
Invalid path completion when not at end of string

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#10781]
As of 6.1 and master (with an empty profile)
```
with IPython.core.completer.provisionalcompleter():
    print(list(ip.Completer.completions("Path('/tmp/", 11)))
```
i.e. complete `Path('/tmp/_` where _ indicates the cursor position, returns a correct list of subpaths from /tmp, but
```
with IPython.core.completer.provisionalcompleter():
    print(list(ip.Completer.completions("Path('/tmp/')", 11)))
```
i.e. complete `Path('/tmp/_')` (which is common in a style of typing where you immediately close your paired delimiters/brackets) returns a bunch of useless completions (basically the entire global namespace, and also the correct completions too).

The behavior is also seen by manually triggering the completion, of course.

**Comment by Carreau** [comment]
Thanks, i've seen another issue about that, I think that an interaction between old completion API and new completion API.

**Comment by Carreau** [comment]
Ok, we _do_ have the logic for that (`completer.py:1357`), the logic only works if the string is (indeed) unfinished. We need to just find the right test to check - when the syntax is valid – whether the cursor is currently in a string.

**Comment by Carreau** [comment]
I'm going to push that to 6.3, because Jedi recently switched parser and doing what I want require using private API in jedi, so I'd prefer to not have 3 branches depending on the version of Jedi.

**Comment by takluyver** [comment]
@Carreau is this any easier to tackle now, or does it get bumped again?

**Comment by takluyver** [comment]
#10966 looks like it's an attempt to fix this issue, but I think it only does the right thing when completing on the first line of a cell.
