### ISSUE TITLE
Problem with Atom. No ipykernel_launcher

### ISSUE THREAD

**Issue by FranekW** [ipython/ipython#10796]
On my Linux distribution (CentOS 7), python package is very outdated--it is Python 2.7. I have install the whole Anaconda Python package along with IPython (5.3.0) and Jupyter (4.3.0).

I would like to use Atom editor with its Hydrogen package--I can run Python code in this editor and I also like the editor itself. As far as I can understand, Hydrogen executes codes using messaging to and from Jupyter kernels via ZeroMQ protocol (not sure what that really means).

The problem is that Hydrogen does not recognises Anaconda Python automatically therefore I have had to provide details regarding the kernel in Jupyter kernel in json format. `jupyter kernelspec list --json` gives me some details about the installed kernel:

```json
{
  "python3": {
    "resource_dir": "/opt/anaconda3/share/jupyter/kernels/python3",
    "spec": {
      "argv": [
        "python",
        "-m",
        "ipykernel_launcher.py",
        "-f",
        "{connection_file}"
      ],
      "env": {},
      "display_name": "Python 3",
      "language": "python"
    }
  }
}
```

This is what I would need to copy in order for Hydrogen to work. The problem is that Hydrogen still complains about the kernel:

"No kernel for grammar 'Null Grammar' found. Check that language for this file is set in Atom and that you have a Jupyter kernel installed for it."

What else can I do?

Thanks

**Comment by takluyver** [comment]
The `.py` there looks wrong - I think that `ipykernel_launcher.py` should just be `ipykernel_launcher`. I don't know if that's what's causing the issue, though.

**Comment by FranekW** [comment]
I added .py to `ipykernel_launcher` but there is still the same error.

**Comment by takluyver** [comment]
I meant remove `.py`. This is what it looks like on my system:

```json
"python3": {
      "resource_dir": "/home/takluyver/.local/share/jupyter/kernels/python3",
      "spec": {
        "argv": [
          "python",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python",
        "metadata": {}
      }
    }
 ```

If you still see it, I think you should go and file an [issue on Hydrogen](https://github.com/nteract/hydrogen) to try debugging it.

**Comment by FranekW** [comment]
Sorry, my bad. The command `jupyter kernelspec list --json` generates correct list without .py and this is what I have now. My text looks almost exactly like yours. The only difference is jupyter is installed via Anaconda and kernels are stored in `/opt/anaconda3/share/jupyter/kernels/...`. If I run `cat /opt/anaconda3/share/jupyter/kernels/python3/kernel.json`, I get thid:

	{
	 "argv": [
		"python",
		"-m",
		"ipykernel_launcher",
		"-f",
		"{connection_file}"
	 ],
	 "display_name": "Python 3",
	 "language": "python"

It looks like Python and Jupyter are installed correctly.

**Comment by takluyver** [comment]
OK, in that case drop Hydrogen a line, the devs there probably know more about debugging this kind of thing.

**Comment by FranekW** [comment]
OK. Thanks for your time

**Comment by FranekW** [comment]
Just read that when atom must be run from terminal:
`atom .`

Otherwise, Hydrogen can't recognise kernels. I did it and it's working now.

**Comment by takluyver** [comment]
Thanks for the follow up. Sounds like an issue with environment variables that are only set in the terminal.
