### ISSUE TITLE
IPython completer crashes when invoked at the start of a line

### ISSUE THREAD

**Issue by ian-r-rose** [ipython/ipython#10814]
Most frontends don't invoke the completer at the start of a new line, so this doesn't come up much, but I came across it when tracking down a different bug.

If the completer is invoked at the start of a new line, it crashes. It seems that this is due to it identifying the previous line as the one for which it needs completions, rather than the current (empty) line. The trouble looks like it is in `IPython.utils.tokenutil.line_at_cursor`.

The bug may be reproduced by running:
```python
import IPython
c = IPython.get_ipython().Completer
txt = 'One\nTwo\n'

c.complete(text=None, line_buffer=txt, cursor_pos=4)
```

Edit: as the example shows, it doesn't need to be an empty line, just the start of a line.

**Comment by takluyver** [comment]
Yup, I think you're right. It's counting the newline character as part of the preceding line.

**Comment by takluyver** [comment]
I made #10835 to fix this, but it doesn't fix the example script you gave, because the completer code doesn't use `line_at_cursor` at all. That is done in ipykernel. Is there an easy way to trigger this for manual testing?

**Comment by ian-r-rose** [comment]
You can also test this using JupyterLab 0.27.0, which was mistakenly invoking the completer at the start of the line.
