### ISSUE TITLE
Starts 5.5 and 6.2 release process.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#10811]
I'm going to start the release process for 6.2 once https://github.com/ipython/ipython/pull/10810 is merged , i'm going to pre-build and prepare the PR for 5.5 as well. 
 - [x] collect stast 5.5, add to stast, and push on 5.x branch:
 - [x] build 5.5 whl/sdists
   - sha256 sdist
     - 578e2f3d779ed130a3cfefc09b2eb965a81457f6a31a25cd38e0bab622d4777d  dist/ipython-5.5.0-py2-none-any.whl
     - 185ef2093dbac6d7250fe9ed4d4dd0f18f10d0a6ac6169f3eeb2ff0663d96b92  dist/ipython-5.5.0-py3-none-any.whl
     - 66469e894d1f09d14a1f23b971a410af131daa9ad2a19922082e02e0ddfd150f  dist/ipython-5.5.0.tar.gz
 - [x] build 6.2 whl/sdists
    - sha256 sdist
     - 0faac098d0e5a79272d1a8dd95d568c7ae7a823c9b21b1bca5800541aa994e6f  dist/ipython-6.2.0-py3-none-any.whl
     - 81b0d6936f87002e6972eccc7e4085f5c2d0673decff22724b53cf34809ffacf  dist/ipython-6.2.0.tar.gz
 - [x] release 5.5 on PyPI, and archive.ipython.org
 - [x] release 6.2 on PyPI, and archive.ipython.org
 - [x] update conda-force recipes
   - https://github.com/conda-forge/ipython-feedstock/pull/33
   - https://github.com/conda-forge/ipython-feedstock/pull/34
 - [x] Check readthedocs.
 - [x] Blog Post.
 

Misc for Later:
  - reproductible builds
     - [ ] document https://github.com/ipython/ipython/pull/10830
     - [ ] raise at release time.
  - Prevent upload to upload unrelated files
    -  [ ] https://github.com/ipython/ipython/pull/10831

**Comment by Carreau** [comment]
TODO next release, document the TIMESTAMP and attempt to have reproductible builds.

**Comment by Carreau** [comment]
Fix `./tools/release upload` to only upload whl and tgz. it crashed because I had a .DStore file as the OSX finder was open.

**Comment by Carreau** [comment]
Here are some download stats graphs:

![download](https://user-images.githubusercontent.com/335567/30826035-d2eb5c5c-a1e9-11e7-9388-64708f25308e.png)

We can see that most of our 5.4 downloads are now 5.5 downloads, ad there is a peak of 5.3 download o_O.

Most 6.1 downloads are now 6.2 downloads.

Downloads of using new-pi vs old pip:
![download-1](https://user-images.githubusercontent.com/335567/30826096-0dfcacce-a1ea-11e7-9aa4-5f724f96a0d6.png); 

Not much change in the proportion of new pip user since beginning of year.

**Comment by takluyver** [comment]
cc @Carreau can you have a look at the unticked boxes above, determine if anything still needs to be done, and close this issue? The versions in question were released.
