### ISSUE TITLE
Console output from ODR iprint does not show in Jupyter Notebook cell output

### ISSUE THREAD

**Issue by dgua** [ipython/ipython#10817]
Hello, I am using the scipy.ODR package in a Jupyter Notebook. Python 3.6 anaconda install on macos Sierra.

When I setup the iprint output, e.g. like this:

   
`    odr_model = sp.odr.Model(model)`
`    odr_data = sp.odr.Data(data[0],data[1])`
`    odr = sp.odr.ODR(odr_data,odr_model,np.array(beta0),ifixb=ifixb)`
`   odr.set_job(fit_type=fit_type)`
`  odr.set_iprint(iter=2,init=2,final=2,iter_step=1)`
` odr.output = odr.run()`

I noticed the output goes to the terminal where I have lanuched Jupyter instead of to the cell output. 

What am I missing?

**Comment by takluyver** [comment]
Stuff printed by compiled code doesn't automatically get captured by our output redirection (because the redirection is in Python, which works at a level above that code). You can use Min's package [wurlitzer](https://github.com/minrk/wurlitzer) to show it - see the example with `sys_pipes`.

**Comment by dgua** [comment]
@takluyver: works perfectly. Many thanks!
