### ISSUE TITLE
Add magic to open quick editing of imported code

### ISSUE THREAD

**Issue by edoarad** [ipython/ipython#10848]
The magic command "??" displays the code of a function in the interpreter. Instead of that, I would like an option to open the source file for editing in an external editor (as in %edit).

For example, the magic "?!" could be used as follows:
```
import re  
re.find?!
```
would open the re.py module for editing. Possibly, placing the marker on the correct line.

**Comment by takluyver** [comment]
I'm personally -1 on adding any new special syntax to IPython.

**Comment by Carreau** [comment]
You can already do that with edit. If I use `%edit re.findall` I get beamed directly on the right file of the standard library at the point of the function definition. 

If you want a different magic, you do not need to modify IPython, you can just [define your own](http://ipython.readthedocs.io/en/stable/config/custommagics.html)

Closing as I don't think there is anything to do; but feel free to reopen.
