### ISSUE TITLE
sys.stdout crashed with close method

### ISSUE THREAD

**Issue by XinhaiWang** [ipython/ipython#10847]
In [1]: import sys

In [2]: sys.stdout.write('hello world\n')
hello world
Out[2]: 12

In [3]: import sys

In [4]: tem = sys.stdout

In [5]: sys.stdout = open('log.txt', 'a')
In [6]: print('spam')
In [7]: print(1, 2, 3)
In [8]: sys.stdout.close()
Traceback (most recent call last):
  File "/Users/xinhai/anaconda3/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/xinhai/anaconda3/lib/python3.6/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/xinhai/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/xinhai/anaconda3/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/Users/xinhai/anaconda3/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 480, in mainloop
    self.interact()
  File "/Users/xinhai/anaconda3/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 460, in interact
    print(self.separate_in, end='')
ValueError: I/O operation on closed file.

**Comment by minrk** [comment]
I think this is the correct behavior. If you close `sys.stdout`, then IPython can't write to stdout anymore. This includes displaying output,etc.

**Comment by takluyver** [comment]
If you want to temporarily redirect stdout, you need to make sure you put the original back before closing it.

```python
tem = sys.stdout
sys.stdout = f = open('log.txt', 'a')
# ...
sys.stdout = tem
f.close()
```

If you want to log things to a file, you might also be interested in the [%logstart magic](http://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-logstart).

**Comment by rodhash** [comment]
> If you want to temporarily redirect stdout, you need to make sure you put the original back before closing it.
> 
> ```python
> tem = sys.stdout
> sys.stdout = f = open('log.txt', 'a')
> # ...
> sys.stdout = tem
> f.close()
> ```
> 
> If you want to log things to a file, you might also be interested in the [%logstart magic](http://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-logstart).





Thank you @takluyver !

One weird thing is, on windows ipython doesn't crash even if we do not set "sys.stdout" back to its original. However on Gnu/Linux it does, at least on Debian 10.

> PC ~ ➜  ipython
>Python 3.8.5 (default, Aug 23 2020, 13:38:12)
>Type 'copyright', 'credits' or 'license' for more information
>IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.

Any clue why?

I've updated to the latest versions but still no luck. A simple redirection can cause the issue.

- Reproducing the error (on my case):

>In [1]: import sys
>
>In [2]: default_stdout = sys.stdout
>
>In [3]: with open('stdout.out', 'w') as sys.stdout:
>   ...:     print(f'Output redirecting:')
>   ...:     help(sys)
>   ...:     #sys.stdout = default_stdout  #this is the line fixing this weird behavior on Linux
