### ISSUE TITLE
Terminal title is not reset after exiting IPython

### ISSUE THREAD

**Issue by cbrnr** [ipython/ipython#10856]
By default, IPython changes the terminal title to `IPython: {cwd}`. However, this change is not reset to the original terminal title after exiting IPython (I'm on macOS High Sierra).

Here's the output of `IPython.sys_info()`:

```
{'commit_hash': 'd86648c5d',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/clemens/anaconda/lib/python3.6/site-packages/IPython',
 'ipython_version': '6.1.0',
 'os_name': 'posix',
 'platform': 'Darwin-17.0.0-x86_64-i386-64bit',
 'sys_executable': '/Users/clemens/anaconda/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 12:04:38) \n'
                '[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]'}
```

**Comment by takluyver** [comment]
I don't believe we have a good way to reset the previous terminal title, so it's up to your shell to set it again after IPython exits.

I found some info [here](https://mail.python.org/pipermail/python-list/2013-October/657961.html) about retrieving or storing terminal titles, but it sounds like most terminal emulators don't support it by default. I tried the code suggested on Gnome terminal, but no joy.

**Comment by cbrnr** [comment]
Hm, so you're saying there's no way to retrieve the current terminal title? I thought that because IPython sets the title it would also be easy to retrieve the current title (sorry, I didn't have time to poke around the source code to find the relevant lines). I know that you can disable this behavior in the profile, but given that the behavior is somewhat suboptimal would it make sense to change the default value of `c.TerminalInteractiveShell.term_title` to `False`?

**Comment by takluyver** [comment]
> Hm, so you're saying there's no way to retrieve the current terminal title?

My brief investigation suggests that there is no way which works reliably across different terminal emulators, yes.

> given that the behavior is somewhat suboptimal would it make sense to change the default value of c.TerminalInteractiveShell.term_title to False?

Well, suboptimal is a matter of opinion. I'm fine with it. ;-)

**Comment by cbrnr** [comment]
> Well, suboptimal is a matter of opinion. I'm fine with it. ;-)

Sure, for me it's a bug :smile: - if starting and exiting IPython does not result in the original state then surely this cannot be the intended behavior if the terminal title is always `IPython: /Users/whatever` (not even the cwd changes).

**Comment by takluyver** [comment]
If no program can restore the terminal title, should no program ever change it? I'd agree that we should restore the previous state if that was feasible, but as it's not, I don't think it's a bug that we change the terminal title.

**Comment by cbrnr** [comment]
I think there might be other ways to modify the terminal title. For example, macOS Terminal.app can display a whole bunch of information in the title, including the working directory, path, the active process name, and so on - but I'm no expert on this topic. From a usability perspective, you shouldn't change the terminal title if you know you can't revert it. For me this is not a big deal because I can change the setting, but I feel that if I had to explain this behavior to the students in my beginner's Python course this would definitely sound like a bug don't you think?

**Comment by Carreau** [comment]
Unfortunately the ability to set terminal title rely on extremely old technology, and no there are not way to restore it to it's previous value from within IPython, as there is no way to get the current value. It's up to the calling shell to save/restore on entry/exit of a subprocess. 

The way it works is by writing an escape sequence with the new title to stdout; there is no way to "get informations back", so no way to reset to a previous state; and no terminal (as far as I can tell), support a "Push/Pop" behavior. 

You can try it by yourself in bash:

```
echo -ne "\033]0;MyTitle\007"
```

Most sell do this before/after running a subprocess, hence why the title appear to be reseted.

This is the reason why there is the `c.TerminalInteractiveShell.term_title` flag, to be able to deactivate this.

Most of the "More modern" way to add badges/info to terminals are terminal emulator specific, and while you can do so using extensions, like for example [iterm2-tools](https://github.com/asmeurer/iterm2-tools), this will likely not go in the core. 

I'm closing as there is likely not much we can do; but feel free to continue discussing, we can reopen if we find a way.

**Comment by cbrnr** [comment]
Thanks @Carreau for this detailed explanation. This is exactly my point, given that changing the terminal title relies on ancient technology maybe IPython shouldn't do it _by default_.

**Comment by takluyver** [comment]
The whole of the terminal is kind of ancient technology. It's emulating a [VT100 terminal](https://en.wikipedia.org/wiki/VT100) from the 70s.

**Comment by eirnym** [comment]
Actually, Vim does reset it.

**Comment by eirnym** [comment]
@takluyver Please, reopen this ticket

**Comment by Carreau** [comment]
Vim uses CST/SSI CRT/SRI termcap that are non standard (can't even find it on google), which require detection of the termcap of the current terminal via infocmp, and them mapping the correct escape sequences. That is a complex endeavour for a (small) return. These capabilities might also be available only when using alternate screen, which we are not.

Feel free to send a PR that fixes bugs it or implement the capability, but we're going to keep that close as we have no intention of working on it seeing the cost/benefits ratio.

Thanks.

**Comment by cbrnr** [comment]
I'd still vote for changing the default to `c.TerminalInteractiveShell.term_title = False` given that the title can't be easily reset.

**Comment by andersk** [comment]
IPython could at least reset the terminal title to the empty string on exit. Then if the shell knows how to set it to something useful, great, but if not, at least it won’t show something actively misleading.
