### ISSUE TITLE
No way to disable Ctrl-\ binding (this always exits the IPython prompt)

### ISSUE THREAD

**Issue by leoalekseyev** [ipython/ipython#10853]
It seems that during transition away from readline, the Ctrl-\ binding became hardcoded to fix https://github.com/ipython/ipython/issues/9810 (see #9820 for commit). This setting should ideally be configurable, since Ctrl-\ is sometimes used for other purposes, e.g. as an escape sequence for GNU Screen/Tmux.  When this is the case, inadvertent force-quitting of the IPython shell can easily occur.

Now that `c.TerminalIPythonApp.interactive_shell_class` is a configuration option, perhaps there is a way to overload the class to remove the binding?  If so, can someone provide some sample configuration code that achieves this?

**Comment by takluyver** [comment]
Ugh, I can see this being a classic 'every fix breaks something else' situation. Are you running screen/tmux inside IPython, or IPython inside screen/tmux? Or some other combination?

Normally the terminal converts Ctrl-\ to a signal (SIGQUIT, I think) which is sent to the current foreground process in the terminal. However, applications running in the terminal can turn off that conversion so they get the raw byte `1C` instead. We made that behave like SIGQUIT. I'm not sure how it interacts with other processes also capturing terminal interaction.

There isn't an easy way to configure it at the moment, but we could probably add something if we can't think of anything smarter to do about it.

cc @jonathanslenders for info

**Comment by leoalekseyev** [comment]
To clarify the screen/tmux point: I run into this issue when IPython is run outside tmux, because the Ctrl-\ binding is in my muscle memory. As a result, sometimes I hit the keycombo forgetting that I'm outside tmux, and poof, there goes the IPython session.

At the very least, it would be very useful to have an option to disable this binding.  This has come up as an issue in the past for readline (see https://stackoverflow.com/questions/21255480/preventing-sigquit-from-terminating-interactive-python/21255589), but the proposed solutions no longer work.

**Comment by takluyver** [comment]
Ah, I understand now.

Actually, perhaps you can do it from a startup file. Try making a file `~/.ipython/profile_default/startup/no-ctrl-backslash.py` with contents like this:

```python
from IPython.terminal.shortcuts import force_exit
ip.pt_cli.application.key_bindings_registry.remove_binding(force_exit)
```

**Comment by leoalekseyev** [comment]
Thanks, that is a reasonable workaround, I'll close this issue since it solves the problem I was raising.
Correct code snippet is the following:
```
from IPython.terminal.shortcuts import force_exit
from IPython import get_ipython
ip = get_ipython()
ip.pt_cli.application.key_bindings_registry.remove_binding(force_exit)
```
