### ISSUE TITLE
ipython > matplotlib

### ISSUE THREAD

**Issue by SchwarzschildK** [ipython/ipython#10860]
Hi everyone,
I am new user of ipython.
I would like to install matplotlib on my machine. I did it by commands. I installed pip and matplotlib successfully but after open "ipython" in terminal and typing %matplotlib I got "ImportError: No module named matplotlib"
I tried install it by file from official web-page but it doesn't work at all.
Can someone help me?

**Comment by takluyver** [comment]
It sounds like you're trying an import in two different installations of Python, or two different environments. Check `sys.executable` to see which Python and environment you're running in, and `sys.path` to see where it looks to import modules.

Python packages must be installed separately for each copy of Python you use, and if you are using virtualenvs or conda envs, packages must be installed into each environment where you need them. Either the package is not installed in one, or a different version of the package is installed.

To install packages to a particular Python installation or environment using pip, you can run it like this:

```shell
path/to/python -m pip install ...
# Replace path/to/python with the path of the Python executable (sys.executable)
```

If you are using conda environments, you can install packages from conda like this:

```shell
source activate myenv  # On Windows, just 'activate myenv' (no 'source')
conda install ...
```

[ This is a saved reply because I answer similar questions often - sorry if it doesn't exactly fit your case ]

**Comment by SchwarzschildK** [comment]
I type sys.executable in my terminal and the message is "I cant find that kind of command"

I am working on linux mint.

**Comment by takluyver** [comment]
> I got an error instead about setuptools

Can you show the error you got? That sounds like something might be wrong with your installation.

**Comment by SchwarzschildK** [comment]
Today when I want to show you the error, I got it.
I did again "import sys" after it "sys.executable.
 (In [5]: sys.executable
Out[5]: '/usr/bin/python' )


In [2]: /usr/bin/python -m pip install d
  File "<ipython-input-2-2881683549b5>", line 1
    usr(/bin/python, -m, pip, install, d)
        ^
SyntaxError: invalid syntax

**Comment by takluyver** [comment]
Sorry, the `/usr/bin/python -m pip install ...` commands need to be run in bash (in a terminal), not inside Python.

**Comment by SchwarzschildK** [comment]
I did installation using apt-get.
I got errors about matplotlib inside python but i installed tkinter.

Now in ipython after typing %matplotlib I got it. Is it working now?
In [2]: %matplotlib
Using matplotlib backend: TkAgg

**Comment by takluyver** [comment]
That looks like it's working.

**Comment by SchwarzschildK** [comment]
Thanks for your patience and help :)

Can you recommend me a guide of python or kind of help.

**Comment by takluyver** [comment]
There's quite a lot of them, and I don't really know which ones are good!

I have a lot of respect for Al Sweigart, who wrote [Automate the Boring Stuff with Python](https://automatetheboringstuff.com/) and [Invent your own Computer Games with Python](http://inventwithpython.com/). If you don't click with those, there's a whole [list of introductory books](https://www.reddit.com/r/learnpython/wiki/index#wiki_new_to_programming.3F) on the wiki of the learnpython subreddit.

There are also online courses on platforms like Udemy if you prefer to learn that way.

**Comment by SchwarzschildK** [comment]
Like I wrote before.
Now I have same problem. Do you know what I should to do?
![errorpy](https://user-images.githubusercontent.com/32834500/31769471-13847468-b4d4-11e7-84ae-a8a8afd33b9b.png)

**Comment by takluyver** [comment]
Weird, I don't know how you get into that state. Try `/usr/bin/python -m pip install setuptools`.

**Comment by SchwarzschildK** [comment]
I installed Visual Studio Code to working better in python.
This command doesnt work.
When I type ipython in normal terminal and after it, in python I type %matplotlib I got Using matplotlib backend: TkAgg
So its kind of working but working in visual studio code my machine doesnt see this installed programs. If I am not mistaken.

**Comment by takluyver** [comment]
That sounds like the original issue with separate Python installations again - see my initial comment.

**Comment by SchwarzschildK** [comment]
Its look like I got python on my machine but if I want to work in this app I should add extension. 
I hope it is a mistake.
