### ISSUE TITLE
How to set highlighting_style_overrides?

### ISSUE THREAD

**Issue by ProbonoBonobo** [ipython/ipython#10862]
Where are the settings loaded into highlighting_style_overrides (line 147 of https://github.com/ipython/ipython/blob/master/IPython/terminal/interactiveshell.py) actually set?

**Comment by takluyver** [comment]
Can be various places, most likely in a config file. Have a look at the config docs:

http://ipython.readthedocs.io/en/stable/config/intro.html

**Comment by mpenkov** [comment]
I had a look at the docs and confirmed that they actually explain what needs to be done.

@meeseeksdev[bot] close
