### ISSUE TITLE
ipython kernel keeps restarting on ubuntu 16.04 but works on ubuntu 14.x

### ISSUE THREAD

**Issue by vaibhavkhanduja** [ipython/ipython#10874]
My jupyter notebook ipython kernel keeps restarting but work well on ubuntu 14.x .. logs below ..

jupyter version is 4.3.0

[D 22:19:58.625 NotebookApp] Using contents: services/contents
[D 22:19:58.626 NotebookApp] 200 GET /tree/Shared%20Code/gleason_grading (127.0.0.1) 1.13ms
[D 22:19:58.645 NotebookApp] 304 GET /custom/custom.css (127.0.0.1) 0.57ms
[D 22:19:58.757 NotebookApp] 200 GET /api/config/tree?_=1509340798711 (127.0.0.1) 2.20ms
[D 22:19:58.759 NotebookApp] 200 GET /api/config/common?_=1509340798712 (127.0.0.1) 1.92ms
[D 22:19:58.766 NotebookApp] 200 GET /api/terminals?_=1509340798713 (127.0.0.1) 0.99ms
[D 22:19:58.769 NotebookApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 22:19:58.769 NotebookApp] Found kernel python2 in /usr/local/share/jupyter/kernels
[D 22:19:58.769 NotebookApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 22:19:58.769 NotebookApp] Found kernel python2 in /usr/local/share/jupyter/kernels
[D 22:19:58.770 NotebookApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 22:19:58.770 NotebookApp] Found kernel python2 in /usr/local/share/jupyter/kernels
[D 22:19:58.771 NotebookApp] 304 GET /api/kernelspecs (127.0.0.1) 2.14ms
[D 22:19:58.772 NotebookApp] 200 GET /api/sessions?_=1509340798714 (127.0.0.1) 0.67ms
[D 22:19:58.773 NotebookApp] 200 GET /api/terminals?_=1509340798715 (127.0.0.1) 0.47ms
[D 22:19:58.814 NotebookApp] 304 GET /custom/custom.js?v=20171029221519 (127.0.0.1) 0.70ms
[D 22:19:58.817 NotebookApp] 200 GET /api/contents/Shared%20Code/gleason_grading?type=directory&_=1509340798716 (127.0.0.1) 2.41ms
[D 22:20:01.422 NotebookApp] Using contents: services/contents
[D 22:20:01.434 NotebookApp] Path base/images/favicon-file.ico served from /usr/local/lib/python2.7/dist-packages/notebook/static/base/images/favicon-file.ico
[D 22:20:01.435 NotebookApp] Path components/codemirror/addon/dialog/dialog.css served from /usr/local/lib/python2.7/dist-packages/notebook/static/components/codemirror/addon/dialog/dialog.css
[D 22:20:01.435 NotebookApp] Path edit/js/main.min.js served from /usr/local/lib/python2.7/dist-packages/notebook/static/edit/js/main.min.js
[D 22:20:01.437 NotebookApp] 200 GET /edit/Shared%20Code/gleason_grading/triplenet_combined_labels_40x_log.txt (127.0.0.1) 15.92ms
[D 22:20:01.461 NotebookApp] 304 GET /custom/custom.css (127.0.0.1) 0.54ms
[D 22:20:01.616 NotebookApp] 200 GET /api/config/edit?_=1509340801556 (127.0.0.1) 1.22ms
[D 22:20:01.617 NotebookApp] 200 GET /api/config/common?_=1509340801557 (127.0.0.1) 1.07ms
[D 22:20:01.650 NotebookApp] 200 GET /api/contents/Shared%20Code/gleason_grading/triplenet_combined_labels_40x_log.txt?type=file&format=text&_=1509340801558 (127.0.0.1) 0.85ms
[D 22:20:01.656 NotebookApp] 304 GET /custom/custom.js?v=20171029221519 (127.0.0.1) 0.46ms
[I 22:21:34.577 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 8f743e94-34e3-4a5d-a3b1-26fd961b3635 restarted
[D 22:21:34.579 NotebookApp] Starting kernel: ['/usr/bin/python', u'-m', u'ipykernel_launcher', u'-f', u'/run/user/1000/jupyter/kernel-8f743e94-34e3-4a5d-a3b1-26fd961b3635.json']
[D 22:21:34.584 NotebookApp] Connecting to: tcp://127.0.0.1:60531
[D 22:21:37.587 NotebookApp] KernelRestarter: restart apparently succeeded

**Comment by takluyver** [comment]
Did you find a solution? It would be great if you could write a short description of what you found, to point other people having similar problems in a helpful direction.

**Comment by takluyver** [comment]
(I mean, if people have similar problems in the future and find this issue while looking for information)
