### ISSUE TITLE
Nbcovert-pdfvialatex-table format

### ISSUE THREAD

**Issue by Rhadadi** [ipython/ipython#10889]
When I export as pdf via latex from jupyter notebook menu, it creates a nice pdf documents but Pandas output tables do not produced nice. Is there any way that I customise the table format, like the font size, headers, ...?

**Comment by takluyver** [comment]
[Pandas options](http://pandas.pydata.org/pandas-docs/stable/options.html#available-options) include some settings to control its latex output - look for the ones starting `display.latex`

**Comment by Rhadadi** [comment]
Thanks, Thomas!

**Comment by takluyver** [comment]
You can register a custom Latex formatter to produce whatever you want. The code would look something like this:

```python
import pandas as pd

def dataframe_latex(df):
    return '... latex ...'

get_ipython().display_formatter.formatters['text/latex'].for_type(
    pd.DataFrame, dataframe_latex)
```

You might want to look at pandas' `DataFrame.to_latex()` method as a base for writing your own formatter.

**Comment by Rhadadi** [comment]
Thank you for your detailed comment.

**Comment by takluyver** [comment]
No problem. I've opened PR #10890 to have an example of registering a formatter function in the docs.
