### ISSUE TITLE
Are jedi and pygments intended to be *compulsory* dependencies?

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#10880]
Currently, jedi is listed in install_requires, but there is some code to work around a failure to import jedi (try: import jedi except ImportError: ...)
This causes the Arch Linux maintainers to package IPython without jedi (or, likewise, pygments), as a dependency (https://bugs.archlinux.org/task/56200#comment163092).
Could the IPython devs clarify their intent regarding whether downstream packages should declare jedi and pygments as compulsory dependencies?

**Comment by takluyver** [comment]
We're in a transition with respect to Jedi, as @Carreau is experimenting with the completion machinery. Pygments is required for the terminal interface.

I would recommend that downstream packagers should turn all of the install_requires into dependencies (or at least 'recommended' in Debian packaging).

**Comment by anntzer** [comment]
thanks.
