### ISSUE TITLE
Can't use multiprocessing module in IPython

### ISSUE THREAD

**Issue by aking7** [ipython/ipython#10894]
I am having issues with the `multiprocessing` module when using IPython. It works fine running in my console. Simple example:
```
from multiprocessing import Pool

def f(x):
    return x*x

if __name__ == '__main__':
    p = Pool(5)
    print(p.map(f, [1, 2, 3]))
```

```
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "C:\Users\kinga\Anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
Process SpawnPoolWorker-3:
  File "C:\Users\kinga\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\kinga\Anaconda3\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Users\kinga\Anaconda3\lib\multiprocessing\queues.py", line 337, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
Traceback (most recent call last):
Process SpawnPoolWorker-4:
  File "C:\Users\kinga\Anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "C:\Users\kinga\Anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\kinga\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\kinga\Anaconda3\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Users\kinga\Anaconda3\lib\multiprocessing\queues.py", line 337, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
  File "C:\Users\kinga\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\kinga\Anaconda3\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Users\kinga\Anaconda3\lib\multiprocessing\queues.py", line 337, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
```

**Comment by takluyver** [comment]
I think that's a limitation of multiprocessing, especially on Windows. This is from the multiprocessing docs:

> Functionality within this package requires that the `__main__` module be importable by the children. This is covered in Programming guidelines however it is worth pointing out here. This means that some examples, such as the `multiprocessing.pool.Pool` examples will not work in the interactive interpreter.

https://docs.python.org/3/library/multiprocessing.html#using-a-pool-of-workers

**Comment by Turim** [comment]
Nevertheless, the workaround exists (at least, works for me), as mentioned in https://stackoverflow.com/questions/41385708/multiprocessing-example-giving-attributeerror/42383397
FYI.

**Comment by AbhinavBangia** [comment]
This problem would be headache for people using Jupyter on windows. The code would run fine on Linux system.

In order to run the code on windows,

1. Put the function definition in a separate ipynb file.
2. import the file using from ipynb.fs.full.functions import func ( make sure you pip install ipynb first)
3. This would definitely solve this.

**Comment by sun-te** [comment]
When I use the `pdb` when importing multiprocessing, all went well. I wonder if it is only a problem with `ipdb`

**Comment by quick-sort** [comment]
Why the anaconda jupyter doesn't have this problem?

**Comment by marmistrz** [comment]
It's really a headache when using SageMath, even on Linux, which slightly modifies the Python syntax, e.g. to make `^` signify exponentiation.

**Comment by fsan** [comment]
I get the same issue when declaring the method I want to parallelize  before  defining the pool.
Example

```python3

p = Pool(N_WORKERS)

def image_name_generator():
    for name in [ f'name{i}.jpg' for i in range(30) ]:
        yield name


def download_and_process(name):
    print(f'downloads {name}')
    time.sleep(1./100.)

with p:
    p.map(download_and_process, image_name_generator())
```

and this seems to solve my case:
```python3
def image_name_generator():
    for name in [ f'name{i}.jpg' for i in range(30) ]:
        yield name


def download_and_process(name):
    print(f'downloads {name}')
    time.sleep(1./100.)

p = Pool(N_WORKERS)
with p:
    p.map(download_and_process, image_name_generator())
```

**Comment by fxmarty** [comment]
This should be explicitly stated in the documentation or in tutorials examples.

**Comment by fsan** [comment]
> This should be explicitly stated in the documentation or in tutorials examples.

i guess this should be a nice note in the documentation too.
but  I think it's not only exclusive to ipython

what happens is that when you use multiprocess you fork the process and all known things to that name space are cloned in the child.
then if you declare other names later they won't get replicated (as expected)

so the pool for multiprocess should be declare only after the required items in the namespace are declared.

**Comment by soerendip** [comment]
I have that error in a JupyterNotebook running in JupyterLab 3 on Ubuntu.

**Comment by Python-Ninja-Hebi** [comment]
That occurs on Mac too

**Comment by aking7** [comment]
> I think that's a limitation of multiprocessing, especially on Windows. This is from the multiprocessing docs:
> 
> > Functionality within this package requires that the `__main__` module be importable by the children. This is covered in Programming guidelines however it is worth pointing out here. This means that some examples, such as the `multiprocessing.pool.Pool` examples will not work in the interactive interpreter.
> 
> https://docs.python.org/3/library/multiprocessing.html#using-a-pool-of-workers

I'm closing this as it is a limitation of the multiprocessing module not IPython.
