### ISSUE TITLE
Tab completion segfault

### ISSUE THREAD

**Issue by simonbyrne** [ipython/ipython#10899]
I keep seeing segfaults when trying to do tab-completion with [pyjulia](https://github.com/JuliaPy/pyjulia) in IPython on OS X, see https://github.com/JuliaPy/pyjulia/issues/132

Interestingly I don't see the problem with normal python3 tab-completion, which makes me wonder if it is an IPython issue? Is there any information I can give that would be useful?

**Comment by takluyver** [comment]
I would guess this is a consequence of the completions being calculated in a separate thread. Apparently prompt_toolkit 2.0 is going to have an option to do completions in the main thread, which I think we'll use.

In the meantime, using `jupyter_console` might be a workaround - that talks to a kernel process, which runs completions in its main thread.

**Comment by simonbyrne** [comment]
Is there anything we can do on the `pyjulia` end to fix this, even if temporarily?

**Comment by takluyver** [comment]
If it's possible to make any kind of protection for tab completion running in a separate thread from the main interpreter, that would probably help. I don't know if that's something pyjulia can do, though.

**Comment by tkf** [comment]
I think you can close it now that you have #11177 in master.  I just tried it and it worked perfectly. https://github.com/JuliaPy/pyjulia/issues/132#issuecomment-409390772 Thanks a lot!

![image](https://user-images.githubusercontent.com/29282/43490988-a6374234-94d7-11e8-96c0-717ad613bcb3.png)

**Comment by tkf** [comment]
@meeseeksdev close

(Just interested in trying it out :smiley: )
