### ISSUE TITLE
Naming Convention Change for Contributor-Friendly Issues

### ISSUE THREAD

**Issue by jzf2101** [ipython/ipython#10906]
Based on discussion from https://github.com/jupyter/governance/issues/40 , this issue would adopt the labels `good first issue` and `help wanted` based on [GitHub's conventions](https://help.github.com/articles/about-labels/)

**Comment by jzf2101** [comment]
@takluyver @Carreau @minrk could we get confirmation so I can make the change and close the issue?

**Comment by takluyver** [comment]
Go for it - as far as I'm concerned, we agreed on this change project-wide.

**Comment by Carreau** [comment]
Do we want to also keep the color the same across repositories and switch or "Good first issue" to purple-ish ?

**Comment by jzf2101** [comment]
i'm ok with that
