### ISSUE TITLE
Jupyter notebook (with R) validation failed

### ISSUE THREAD

**Issue by bioatmosphere** [ipython/ipython#10909]
Here is what i got everytime i launch the jupyter notebook using R via the IRkernel. pls note that it is working without any issues for python-based notebooks.

And though with this popping up every time, i can run the cells, save it, and pretty much everything. It is really annoying to have this. 

Looking forward to your answers

-OS high sierra 
-Latest R version
-lastest Jupyter notebook
-IRkernall: 0.8.9

-------------------------

Notebook validation failed: Additional properties are not allowed ('source' was unexpected):
{
 "data": {
  "image/png": "iVBORw0KGgoAAAANSUhEUgAAAeAAAAHgCAYAAAB91L6VAAAEDWlDQ1BJQ0MgUHJvZmlsZQAA\nOI2NVV1oHFUUPrtzZyMkzlNsNIV0qD8NJQ2TVjShtLp/3d02bpZJNtoi6GT27s6Yyc44M7v9\noU9FUHwx6psUxL+3gCAo9Q/bPrQvlQol2tQgKD60+INQ6Ium65k7M5lpurHeZe58853vnnvu\nuWfvBei5qli
.............(super long 'ET' characters omitted !!!)
SMBCAhwDthAmsyIBEiABEiABswQowGZJcT8SIAESIAESsJAABdhC\nmMyKBEiABEiABMwSoACbJcX9SIAESIAESMBCAhRgC2EyKxIgARIgARIwS4ACbJYU9yMBEiAB\nEiABCwlQgC2EyaxIgARIgARIwCwBCrBZUtyPBEiABEiABCwk8P9cxV1usyNojQAAAABJRU5E\nrkJggg=="
 },
 "metadata": {},
 "output_type": "display_data",
 "source": "R display func"
}

**Comment by takluyver** [comment]
Something appears to have created an invalid notebook. If you edit the file in a text editor and delete the line `"source": "R display func"`, along with the comma on the line before, it should open again. But the problem might occur again if whatever tool wrote it before makes the same mistake again.

**Comment by takluyver** [comment]
Looks like it's coming from IRkernel. This PR should fix it: https://github.com/IRkernel/IRkernel/pull/523

**Comment by bioatmosphere** [comment]
@takluyver Thx a lot. The issue was just gone when i opened the notebook minutes ago this morning. It is weird and do not know why. hope it won't show up again.

**Comment by lesley2958** [comment]
has this been fixed since?

**Comment by bioatmosphere** [comment]
This issue has been basically fixed. maybe the version then was stlll not
yet stable.

Bin Wang (PhD)
Department of Environmental Sciences
University of Virginia
291 McCormick Rd, Charlottesville, Virginia 22904, USA
