### ISSUE TITLE
'graphviz' warning when building docs

### ISSUE THREAD

**Issue by olesyabar** [ipython/ipython#10915]
When Travis builds the docs, there is following warning:
WARNING: dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting
(See https://github.com/ipython/ipython/issues/10895 for the whole story. This issue is to address that remaining warning.)

**Comment by olesyabar** [comment]
@jzf2101 - I'm working on it

**Comment by olesyabar** [comment]
I was able to solve it locally by installing Graphviz and specifying 'sphinx.ext.graphviz' in conf.py + path to dot.exe in make.cmd

**Comment by takluyver** [comment]
Thanks. So the trick is figuring out how to install Graphviz on Travis.

**Comment by olesyabar** [comment]
I've figured out 'too simple' way to do this, but the build is green & the warning is gone. Thus submitting PR.

**Comment by olesyabar** [comment]
I don't know if we need to make it OS dependent & include Windows - Travis doesn't run Windows anyways, from what I understood. If someone would want to build docs on Windows, then I described in comments how to do that (may document somewhere else if needed).

**Comment by takluyver** [comment]
Yup, Travis is only running tests on Linux. There's a separate build service called Appveyor which runs on Windows. Testing docs there is not a priority, though.

**Comment by ATidmore** [comment]
> I was able to solve it locally by installing Graphviz and specifying 'sphinx.ext.graphviz' in conf.py + path to dot.exe in make.cmd

Where exactly did you add this in the Makefile?
