### ISSUE TITLE
Implementing Block indent in qtconsole

### ISSUE THREAD

**Issue by JeremySikes73** [ipython/ipython#10927]
I'd like to see block indent implemented in qtconsole, it's a pet peeve I hit every day. 
Wrapping a piece of code in an `if` tediously involves manually indenting N lines. Pasting in an indented
position also doesn't preserve the indentation of the block pasted.

If one of the developers would kindly point me in the right direction, I'll like to code this up. And If there's interest, a PR may follow.

**Comment by takluyver** [comment]
The Qt console is in a separate repo now: https://github.com/jupyter/qtconsole

**Comment by JeremySikes73** [comment]
Moved.
