### ISSUE TITLE
Can display gif infinite loop?

### ISSUE THREAD

**Issue by tohnperfect** [ipython/ipython#10929]
Currently the gif display only works once and then the display is freezed at the last frame of the gif.
It could not replay the animated gif again when I re-execute the command, even after restart the jupyter kernel.

I wonder if it possible to display animated gif for infinite loop or what is the correct way to call the display function for gif to make it able to replay whenever i execute the display command?

below is how i call the display function
`from IPython.display import Image, display`
`X = Image(filename=path2gif, format='gif')`
 `display(X)`

**Comment by Carreau** [comment]
Hi there, 

I'm not sure why or how a gif would play only once, one would need to experiment with the `Html` object and see how to modify the `Image` object to automatically loop. It should not be too hard, so marking as "good first issue"

Thanks For the report !

**Comment by takluyver** [comment]
I think it might be a property of the gif file itself, rather than the HTML tag: https://en.wikipedia.org/wiki/GIF#Animated_GIF

**Comment by yongzx** [comment]
I would like to work on this issue - is there anyone currently working on this issue?

**Comment by takluyver** [comment]
I don't think there's anything to do - as far as I know, the looping is up to the gif file, not how we display it.

**Comment by takluyver** [comment]
But it would be good if you could test this out with a gif that does loop, to check that it's working correctly so we can close it.

**Comment by tohnperfect** [comment]
The problem is once the gif looping is done there is no other ways to replay it again unless you terminate the ipython session.

**Comment by takluyver** [comment]
In Firefox, rerunning the cell that displays it will start it playing again. In Chromium, it doesn't.

I don't think Jupyter should try to do anything special around this. We send the image, it's up to the browser how it displays it. If you want to control the playback, use a video rather than a GIF.

**Comment by yongzx** [comment]
I will check the looping of the gif file.

**Comment by yongzx** [comment]
`from IPython.display import Image, display
X = Image(url='test.gif')
display(X)`

I tested the code and gif file with Jupyter notebook opened in Safari, Chrome and Firefox browsers and the gif file can run infinitely.

**Comment by takluyver** [comment]
Thanks for confirming. I'm closing this as I don't think there's anything for IPython to do. How the animation is displayed is up to the browser, I think.
