### ISSUE TITLE
IPython3 crashes when hint ?? is assigned to a variable

### ISSUE THREAD

**Issue by amitt001** [ipython/ipython#10933]
When running IPython3 when I assigned function hint using `??` output to a variable it crashed. What I did was

```
In [1]: import csv
In [2]: csv.reader??
In [3]: # The above worked code worked but the below code crashed IPython3
In [4]: reader=csv.reader??

```

This is not happening for all the modules but during testing, I observed one more case with os module

```
import os
curdir=os.curdir??
```

A more detailed crash report is here [Crash_report_ipython.txt](https://github.com/ipython/ipython/files/1520883/Crash_report_ipython.txt)

This only happens with IPython3.

**Comment by takluyver** [comment]
That was fixed already (#10231), but you're running an old version of IPython. Time to upgrade!
