### ISSUE TITLE
Strange behaviour after semicolon

### ISSUE THREAD

**Issue by gizzatov** [ipython/ipython#10949]
Hey guys, I found strange behaviour of code after semicolon in ipython:

```Python 
Python 3.5.2 (default, Oct 27 2016, 17:37:32)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: ; dict
Out[1]: {}

In [2]: ; 1111
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-bdc4828025e6> in <module>()
----> 1 1111("")

TypeError: 'int' object is not callable

In [3]: ; [11111]
Out[3]: '[11111]'

In [4]: ; [int]
Out[4]: '[int]'
```

In native python interpreter I had normal behaviour:
```Python
Python 3.5.2 (default, Oct 27 2016, 17:37:32)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ; dict
  File "<stdin>", line 1
    ; dict
    ^
SyntaxError: invalid syntax
>>> ; 1111
  File "<stdin>", line 1
    ; 1111
    ^
SyntaxError: invalid syntax
```

**Comment by takluyver** [comment]
This is actually a feature! Just not one many people know about. It's a shortcut to save you typing parentheses and quotation marks, and it's meant to be used like this:

```
 3│ ;len Here are some words
 3> 19
```

You can see the 'translated' code by running `%history -t` ([%history magic](http://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-history)).

There are a couple of other prefixes that do similar things:

```
/divmod 7 2  # Split on space, pass arguments without quoting
,max abc def  # Split on space, quote arguments
```

**Comment by gizzatov** [comment]
Wow. I really see that expression in first time. Thanks! Where I can read more about shortcuts like that?

**Comment by takluyver** [comment]
Here it is: http://ipython.readthedocs.io/en/stable/interactive/reference.html#automatic-parentheses-and-quotes
