### ISSUE TITLE
Ownership of "ipython" command on mixed 2.7 and 3 systems

### ISSUE THREAD

**Issue by tkuester** [ipython/ipython#10942]
This issue is related to #4368 and #9869.

[PEP 394](https://www.python.org/dev/peps/pep-0394/) recommends the following:

> for the time being, all distributions should ensure that python refers to the same target as python2.

Given the backwards incompatibility of python2 and python3, I do not believe it wise for ipython3 to take ownership of the ipython command -- especially if the order ipython versions are installed decides which version of python is run.

**Comment by takluyver** [comment]
-1 - many people will be using it with only Python 3 installed, and we want the command `ipython` to work for them.

This is also consistent with how conda environments and virtualenvs work: they contain only one version of Python, which can be used as `python` inside the environment.

**Comment by takluyver** [comment]
* Not everybody is following that recommendation, so it's already not terribly useful.
* Almost every Python package that installs scripts does this - pip, pytest, pep8, and so on. If you install it on both versions of Python, the last one installed 'wins' the script.
* Downstream packagers like Linux distros can and do handle this differently in line with their own policies.
