### ISSUE TITLE
OrderedDict output differs in ipython from python (and official documentation)

### ISSUE THREAD

**Issue by annesession** [ipython/ipython#10950]
[collections — Container datatypes](https://docs.python.org/3/library/collections.html#collections.OrderedDict)

An ordered dictionary can be combined with the Counter class so that the counter remembers the order elements are first encountered:

```
from collections import Counter, OrderedDict

class OrderedCounter(Counter, OrderedDict):
    'Counter that remembers the order elements are first encountered'

    def __repr__(self):
        return '%s(%r)' % (self.__class__.__name__, OrderedDict(self))

    def __reduce__(self):
        return self.__class__, (OrderedDict(self),)
```
This is based off a Raymond Hettinger - Super considered super! - PyCon 2015, and his blog post [Python’s super() considered super!](https://rhettinger.wordpress.com/2011/05/26/super-considered-super/).

My confusion is IPython returns a result that differs from the Python it's built on.  The ordering of the output is important and the recipe in Hettinger's blog and the official documentation preserves the insertion order but IPython 6.1.0 built on Python 3.6.3 does not.  However if I execute directly in Python 3.6.3 I receive the expected desired result.

`oc = OrderedCounter('abracadabra')`

output in Python 3.6.3 (and Python 2.7.14)
`OrderedCounter(OrderedDict([('a', 5), ('b', 2), ('r', 2), ('c', 1), ('d', 1)]))`

output in IPython 6.1.0 on Python 3.6.3 Anaconda
`OrderedCounter({'a': 5, 'b': 2, 'c': 1, 'd': 1, 'r': 2})`  //ordering is not preserved, seems sorted by key

Would someone kindly explain why the output is different in IPython 6.1.0

**Comment by annesession** [comment]
I know the above recipe isn't really needed in python 3.6 as dictionary preserves insert order (not absolute guaranteed until maybe 3.7).
```
from collections import Counter
c = Counter('abracadabra')
```
output 3.6.3
`Counter({'a': 5, 'b': 2, 'r': 2, 'c': 1, 'd': 1})`

Here, too, IPython seems to be doing some implicit sort.
output IPython 6.1
`Counter({'a': 5, 'b': 2, 'c': 1, 'd': 1, 'r': 2})`

**Comment by takluyver** [comment]
Thanks, #10959 should fix this.
