### ISSUE TITLE
Is it valid to use or change OutputArea.prototype personally by nbextension?

### ISSUE THREAD

**Issue by avriLee** [ipython/ipython#10954]
Hi, as notebook faces the problem of storing large amounts of running result data in the _.ipynb_ file, and the solution of it is to limit merging of stream output(_merged_). 
However, our demand is:
- *only* a part of cells' outputs needs to be not stored

So, we gave a way to deal with it:
- Firstly, we register our own(_create a new_) `mimeType` by 
<pre><code>require(["notebook/js/outputarea"], function(oa){  
    var personal_mime = 'nb/image+video';     
    oa.OutputArea.prototype.register_mime_type(personal_mime, function(code, md, element) { 
        // code to eval the code...
    }, { 
        safe: true
    }); 
});
</code></pre> 

- and then change the process of original `OutputArea.prototype.handle_output` by
<pre><code>require(["notebook/js/outputarea"], function(oa){
    // ...
    oa.OutputArea.prototype._handle_output = oa.OutputArea.prototype.handle_output
    oa.OutputArea.prototype.handle_output = function (msg){
        // code to filter the output to be stored in the .ipynb file...
        return this._handle_output(msg);
    };
});
</code></pre>

- Finally, we use `nbextension` to install and enable it. Use it by 
<pre><code>publish_display_data({_personal_mime: code_str})</code></pre>

_**reference:** [js code from Carreau](https://github.com/ipython/ipython/issues/6516)_ @Carreau 

Btw, here are some msgs:
<pre><code>{
 'commit_hash': u'5a894b9',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/jenkins/anaconda2/lib/python2.7/site-packages/IPython',
 'ipython_version': '5.3.0',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-103-generic-x86_64-with-debian-jessie-sid',
 'sys_executable': '/home/jenkins/anaconda2/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.13 |Anaconda 4.4.0 (64-bit)| (default, Dec 20 2016, 23:09:15) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'
}</code></pre>

Thanks for your time and looking forward to receiving your reply!

**Comment by takluyver** [comment]
None of the JS API is really documented, so if it works, I think you're free to do it, but there's no guarantee that it won't break in the future or interfere with other nbextensions.

If you want to open an issue on [jupyter/notebook](https://github.com/jupyter/notebook) with some more detail about what you're doing, we might be able to point to a better path, or make some changes to the API to make it easier to do what you want.

**Comment by ivanov** [comment]
Looks like @avriLee opened jupyter/notebook#3155 in response to this, and the indefatigable @takluyver chimed in there to save the day (once again!), and since that issue is now close, I'm closing this one as well. 

Happy hacking! :bowtie:
