### ISSUE TITLE
_repr_svg_ needs better documentation

### ISSUE THREAD

**Issue by dsblank** [ipython/ipython#10973]
`_repr_svg_` has additional return options as mentioned by @takluyver here: https://github.com/igraph/python-igraph/issues/145#issuecomment-344283193

I couldn't find the fact that `_repr_svg_` could return a tuple mentioned anywhere. Specifically, this could be mentioned here:

* http://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html
* http://ipython.readthedocs.io/en/stable/api/generated/IPython.core.formatters.html

Perhaps there are other `_repr_` functions that are also under-documented.

**Comment by takluyver** [comment]
I think all the `_repr_*_` functions can now return a data, metadata tuple. I only became aware of it recently, but I'm not sure when it started.

Here's another place this could be documented - I think narrative docs may be better for this than API docs.
http://ipython.readthedocs.io/en/stable/config/integrating.html#rich-display

**Comment by jzf2101** [comment]
Can we make this a `good first issue`?

**Comment by ivanov** [comment]
marked it as "good first issue" @jzf2101

**Comment by pulkitmaloo** [comment]
Can I work on this?

**Comment by takluyver** [comment]
Yes! Do you follow the discussion above about what needs doing?

**Comment by a1shadows** [comment]
does this issue need any more work?

**Comment by GabrielSimonetto** [comment]
Hi, it seems to me this issue can be closed since it was resolved on [PR #11352](https://github.com/ipython/ipython/pull/11352), @takluyver, @dsblank
