### ISSUE TITLE
Completion broken for objects with custom __dir__ method

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#10977]
I think this may have been lost in the switch to Jedi.

Run this code, and then try completing `ca.<tab>`. No completions are offered.

```python
class CompleteAttrs(object):
    def __getattr__(self, name):
        if name == 'foo':
            return 1
        if name == 'bar':
            return 2
        raise AttributeError(name)
    
    def __dir__(self):
        return ['foo', 'bar'] + object.__dir__(self)

ca = CompleteAttrs()
```

**Comment by Carreau** [comment]
Might be related to https://github.com/davidhalter/jedi/issues/997

**Comment by davidhalter** [comment]
I'm pretty sure this is a separate issue. Please open an issue :)

**Comment by takluyver** [comment]
Thanks; see https://github.com/davidhalter/jedi/issues/1027

**Comment by takluyver** [comment]
The issue in Jedi has been fixed, so this should work from the next Jedi release (0.12?).
