### ISSUE TITLE
IPython in a conda environment calls the wrong python

### ISSUE THREAD

**Issue by tritemio** [ipython/ipython#10986]
When I launch ipython from within a conda environment, ipython runs the python from the base conda environment instead of the python from the current environment.

This is a recent conda installation on macOS.

```
(phforge-test) Antonios-MacBook-Pro:~ anto$ which python
/Users/anto/miniconda3/envs/phforge-test/bin/python
(phforge-test) Antonios-MacBook-Pro:~ anto$ which ipython
/Users/anto/miniconda3/envs/phforge-test/bin/ipython
(phforge-test) Antonios-MacBook-Pro:~ anto$ python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
(phforge-test) Antonios-MacBook-Pro:~ anto$ ipython
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: quit()
(phforge-test) Antonios-MacBook-Pro:~ anto$ 
```

**Comment by takluyver** [comment]
Have you done `hash -r` since entering the conda environment? Bash can cache paths to executables, so sometimes it doesn't use the one reported by `which`. Running `hash -r` resets the cache.

**Comment by tritemio** [comment]
@takluyver, that was it. Thanks, I learned something new today.

**Comment by takluyver** [comment]
I'm glad it was that, because there's been a flurry of perplexing issues that I've no idea about recently. ;-)

**Comment by tommylees112** [comment]
Dear @takluyver sorry to bring this back but I am having difficulties. I have also tried to run the `hash -r` command but to no avail.

I have this bizarre situation where in my environment with Python 2.7 installed, the call to `python` uses Python 2.7

But the call to IPython uses Python 3.6

It's only in this environment and not my other environment with python 2.7.

`(chirps_analysis) ➜  chirps_data python -c "import sys; print(sys.version)"
2.7.14 | packaged by conda-forge | (default, Mar 30 2018, 18:21:11)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
(chirps_analysis) ➜  chirps_data ipython -c "import sys; print(sys.version)"
Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib
3.6.3 |Anaconda custom (x86_64)| (default, Oct  6 2017, 12:04:38)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]`

**Comment by takluyver** [comment]
Try `which ipython` to see where it's finding it. You can also always start it with a particular Python by runing `python -m IPython` (this is a good general tip - most Python tools now offer a `python -m` way to launch them).

**Comment by billtubbs** [comment]
I am having the same issue as @tommylees112 .  (I tried closing/opening a new terminal and also `hash -r`).  But the python versions still differ between `python` and `ipython`:

```
Last login: Sat Sep  1 15:35:11 on ttys001
BillsMacBookPro:~ billtubbs$ source activate skl
Vendor:  continuum
Product: anaconda
Message: trial mode expires in 30 days
(skl) BillsMacBookPro:~ billtubbs$ which python
/Users/billtubbs/anaconda/envs/skl/bin/python
(skl) BillsMacBookPro:~ billtubbs$ python
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
(skl) BillsMacBookPro:~ billtubbs$ ipython
Vendor:  continuum
Product: anaconda
Message: trial mode expires in 30 days
Python 2.7.3 |Anaconda custom (64-bit)| (default, Dec 20 2012, 09:57:39) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: exit()
(skl) BillsMacBookPro:~ billtubbs$ 
```

Since I am using jupyter notebooks this is a problem as the jupyter notebooks are also using Python 2.

**Comment by realdoug** [comment]
I ran into this and the simple fix was: ```  conda install -c anaconda ipython ```

Calling ```ipython``` at the command line is going to first look in the bin folder for your conda environment but if ipython isn't found it will fall back to ```/usr/local/bin``` or whatever is in your path.

**Comment by rama100** [comment]
> I ran into this and the simple fix was: ` conda install -c anaconda ipython`
> 
> Calling `ipython` at the command line is going to first look in the bin folder for your conda environment but if ipython isn't found it will fall back to `/usr/local/bin` or whatever is in your path.

This fixed it! Thanks.

**Comment by thinkjrs** [comment]
Same issue as @tritemio and fixed with `hash -r`. It appears that my hash table was stale. Thanks for the suggestion @takluyver!

**Comment by gustavosaume** [comment]
I was having the same issue and while debugging I realizes that my conda install was returning this error 
```
WARNING conda.core.envs_manager:register_env(46): Unable to register environment. Path not writable or missing.
```
First, I fixed that following the comments in https://github.com/conda/conda/issues/7267 and then I retried launching jupyter and it worked. Hopefully this helps other peeps. ✌️

**Comment by YuxuanXie** [comment]
> I ran into this and the simple fix was: ` conda install -c anaconda ipython`
> 
> Calling `ipython` at the command line is going to first look in the bin folder for your conda environment but if ipython isn't found it will fall back to `/usr/local/bin` or whatever is in your path.

works for me! thx!

**Comment by zzeitt** [comment]
> Try `which ipython` to see where it's finding it. You can also always start it with a particular Python by runing `python -m IPython` (this is a good general tip - most Python tools now offer a `python -m` way to launch them).

And this is a way that does not require modifying the current environment. Thanks for the hint!
