### ISSUE TITLE
can not display image from base 64 anymore (v6.2.1)

### ISSUE THREAD

**Issue by hainm** [ipython/ipython#10982]
hi,

below are attach files to reproduce the issue.

- OK with v5.3

<img width="1122" alt="screen shot 2018-01-15 at 5 21 13 pm" src="https://user-images.githubusercontent.com/4451957/34964194-5bb7a71a-fa1a-11e7-99c2-fc508eb6bebe.png">

- NOT ok with v6.2.1

<img width="1168" alt="screen shot 2018-01-15 at 5 21 16 pm" src="https://user-images.githubusercontent.com/4451957/34964205-678fba78-fa1a-11e7-9ff4-ff48544d8cf8.png">

The base64 string is from here: 
[fig.txt](https://github.com/ipython/ipython/files/1633140/fig.txt)

thanks.

PS: Of course I've been trying to follow the error traceback by reading the file in 'rb' mode but that won't help either.

<img width="1138" alt="screen shot 2018-01-15 at 5 36 23 pm" src="https://user-images.githubusercontent.com/4451957/34964265-b5a92816-fa1a-11e7-8e1e-1d760a0b559e.png">

**Comment by hainm** [comment]
is this intentional design or a bug?

**Comment by takluyver** [comment]
I think it was an accident that it accepted base64 data before - if you're passing data to the Image class, it's always been intended that you pass bytes with the raw image data (i.e. not base64 encoded). It probably 'broke' when the implementation was cleaned up a bit in #10739.

**Comment by hainm** [comment]
I see. thanks.
