### ISSUE TITLE
IPython doing case-insensitive completion

### ISSUE THREAD

**Issue by gabriellima** [ipython/ipython#10988]
Ipython is doing case-insensitive completion when using Jedi.

If I do `%config Completion.use_jedi = False` I "temporaly" fix this issue. 
Or permanently fix it updating ipython_config.py

May be related to #10969 

![image](https://user-images.githubusercontent.com/487779/35187162-7c67a4de-fe06-11e7-8bde-070fc0342142.png)

Environment:
```
Python 3.5.1
Ipython 6.2.1
ipykernel 4.8.0
jedi 0.11.1
```

**Comment by takluyver** [comment]
@Carreau is this something we can configure through Jedi? It seems to be hitting a few people (also #10728).

**Comment by Carreau** [comment]
There seem to be a `settings.case_insensitive_completion = True` when grepping through the source code. So it can probably be set.

**Comment by cottrell** [comment]
I might PR this. 

https://github.com/cottrell/ipython/commit/c07e32e1f996966e1322b679f6734816cfae567b

**Comment by palxex** [comment]
...what should I do if I WANT case insensitive completion? For macOS and Windows user that's better, since the filesystem is case-insensitive too.
I think its better introduce a option that configureable in ipython-settings.py, in order to control it.

**Comment by MrMino** [comment]
If someone wants case-insensitive completion, see https://github.com/ipython/ipython/issues/10728#issuecomment-921419106.

The case insensitivity for `%cd` magic has been started within #11850, but it's probably something that is going to (if not already has been) superseeded by Jedi's filename completion.
