### ISSUE TITLE
have a floating cell to execute some common commands

### ISSUE THREAD

**Issue by youkaichao** [ipython/ipython#10997]
e.g. when I'm using matplotlib.pyplot, sometimes I have to switch between two figure sizes. Then I have to open  a new cell, write `plt.rcParams["figure.figsize"] = (10.0, 10.0)`, run it, and then delete the cell. 

I think we can have a floating cell at the left side or at the right side, so that when we have to execute some common commands, we donot need to create a new cell, run it and delete it.

Thanks a lot!

**Comment by apetresc** [comment]
It sounds like you just want the [scratchpad extension](https://github.com/minrk/nbextension-scratchpad).

**Comment by youkaichao** [comment]
awesome!
thanks a lot!
