### ISSUE TITLE
HTML output of links within <i></i> is broken

### ISSUE THREAD

**Issue by moxplayer** [ipython/ipython#10991]
Hey, 

I tried to export an HTML file within the italics environment like this:

**\<i\>Text in italics [link](#resource anchor within notebook) Text in italics \<\/i\>**

which ended up not being a link. A workaround was:

**\<i\>Text in italics\</i\> [link](#resource anchor within notebook) \<i\>Text in italics\</i\>**

Moreover, when setting an anchor like this:

\<a id = 'ID'\> \</a\>, it would not always compile correctly in the HTML file, where adding an italics environment solved the issue:

**<i\>\<a id = 'ID'\> \</a\>\</i\>**

There are not problems of this kind in the ipynb file.

System Info:

 'ipython_version': '5.1.0',
 'os_name': 'nt',
 'platform': 'Windows-10-10.0.16299-SP0',
 'sys_platform': 'win32',
 'sys_version': '3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, '
                '11:57:41) [MSC v.1900 64 bit (AMD64)]'

**Comment by takluyver** [comment]
Technically, nbconvert (which does the HTML export) is doing the right thing according to the spec, but it doesn't match what the live notebook does. Here are the issues about it:

https://github.com/jupyter/nbconvert/issues/45
https://github.com/jupyter/nbconvert/issues/622

**Comment by takluyver** [comment]
Closing in favour of the issues I linked to on other repos.
