### ISSUE TITLE
Broken behaviour with np.dot on IPython but not in Python shell

### ISSUE THREAD

**Issue by johncoxon** [ipython/ipython#11007]
I'm seeing weird behaviour on two MacBooks Pro running IPython compared with my colleague's MacBook Pro running IPython and compared with my own machines running Python.

On my first Mac, running High Sierra 10.13.3, IPython 5.3.0, numpy 1.11.0, and Python 2.7.13, installed using Anaconda:
```
In [2]: P01 = np.array([-13.73046875, -10.4140625 ,  18.88452148], dtype=np.float32)
In [3]: P02 = np.array([-17.63671875,  13.19140625,  18.57519531], dtype=np.float32)
In [4]: P03 = np.array([  3.30859375,   1.1015625 ,  30.3034668 ], dtype=np.float32)
In [5]: np.dot(P02, np.cross(P01,P03))
Out[5]: 0.0
```

On my second Mac, running High Sierra 10.13.3, IPython 5.4.1, numpy 1.13.3, and Python 2.7.14, installed using Anaconda:
```
In [1]: P01 = np.array([-13.73046875, -10.4140625 ,  18.88452148], dtype=np.float32)
In [2]: P02 = np.array([-17.63671875,  13.19140625,  18.57519531], dtype=np.float32)
In [3]: P03 = np.array([  3.30859375,   1.1015625 ,  30.3034668 ], dtype=np.float32)
In [4]: np.dot(P02, np.cross(P01,P03))
Out[4]: 0.0
```

On my colleague's Mac, running High Sierra 10.13.3, IPython 5.4.1, numpy 1.13.1, and Python 2.7.13, installed **not** using Anaconda:
```
In [8]: P01 = np.array([-13.73046875, -10.4140625 ,  18.88452148], dtype=np.float32)
In [9]: P02 = np.array([-17.63671875,  13.19140625,  18.57519531], dtype=np.float32)
In [10]: P03 = np.array([  3.30859375,   1.1015625 ,  30.3034668 ], dtype=np.float32)
In [12]: np.dot(P02, np.cross(P01,P03))
Out[12]: 12604.703
```

On my Mac, running High Sierra 10.13.3, **not using IPython**, numpy 1.13.1, and Python 2.7.14, installed using Anaconda:
```
>>> P01 = np.array([-13.73046875, -10.4140625 ,  18.88452148], dtype=np.float32)
>>> P02 = np.array([-17.63671875,  13.19140625,  18.57519531], dtype=np.float32)
>>> P03 = np.array([  3.30859375,   1.1015625 ,  30.3034668 ], dtype=np.float32)
>>> np.dot(P02, np.cross(P01,P03))
12604.703
```

I have checked that `np.__path__` and `np.__config__.show()` are the same in my IPython and Python interactive shells; they are. My colleague can get `np.dot` to work as expected (the `12604` result) on every machine he's tried. How do I go about debugging this? What might be happening?

I should note that `np.dot` works fine on both of my machines (the top two examples) if I don't force the arrays to be `float32`:
```
In [2]: P01 = np.array([-13.73046875, -10.4140625 ,  18.88452148])
In [3]: P02 = np.array([-17.63671875,  13.19140625,  18.57519531])
In [4]: P03 = np.array([  3.30859375,   1.1015625 ,  30.3034668 ])
In [5]: np.dot(P02, np.cross(P01,P03))
Out[5]: 12604.703743014355
```

[I have also posted this on numpy's issue tracker as issue 10584](https://github.com/numpy/numpy/issues/10584).

**Comment by takluyver** [comment]
We'll let the investigation happen on the numpy issue unless some problem with IPython is identified.

**Comment by takluyver** [comment]
Numpy reckoned it might be an MKL issue. Closing here because - while IPython might affect it - I don't think it can be a bug in IPython.

**Comment by jiangzhongshi** [comment]
My machine return 0 for the following command.
```
ipython -c "import numpy as np;f=np.ones(2,dtype=np.float32);print(f.dot(f))"
```
