### ISSUE TITLE
no date time output when using jupyter notebook

### ISSUE THREAD

**Issue by youkaichao** [ipython/ipython#11000]
the code is 

```
import logging
logging.basicConfig(format='%(asctime)s:%(message)s', level=logging.INFO)
logging.info('is when this event was logged.')
```

when i run the code with python, it works well, the output is 
`2018-02-05 21:53:25,087:is when this event was logged.`
However, when i run the code in jupyter notebook, the output is 
`INFO:root:is when this event was logged.`

the time is gone!

I'm using IPython 5.1.0,  Python 2.7.13, Ubuntu 14.04.5 LTS.

**Comment by takluyver** [comment]
It's logging with the time for me. Try updating IPython and IPykernel.

**Comment by youkaichao** [comment]
@takluyver 
It's working in IPython 5.3.0.
Thanks!
