### ISSUE TITLE
Problem mixing multi-line comments and console-style inputs.

### ISSUE THREAD

**Issue by rsokl** [ipython/ipython#11017]
IPython 6.2.1, Python 3.6.3

There seems to be a problem with mix-and-match style code blocks that incorporate multiline comments mixed with console-style inputs

```python
# 1
>>> "yo"
'yo'
```

versus

```python
# 1
# 2
>>> "yo"
  File "<ipython-input-29-41bcffd77fef>", line 3
    >>> "yo"
     ^
SyntaxError: invalid syntax
```

Is this known/intentional behavior? My desire is to be able [to provide documentation](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/VectorizedOperations.html#Basic-Mathematical-Operations-Using-Arrays) like:
```python
# talking about code sometimes
# requires multiple lines
>>> x = 1 
```
and for the user be able to copy/paste the entire code block into IPython/Jupyter.

**Comment by davidmascharka** [comment]
I can replicate this with Python 3.6.4, IPython 6.2.1 and Jupyter 4.4.0.

**Comment by takluyver** [comment]
It only strips the prompts (`>>>`) if they appear in the first two lines. The idea is that you can easily copy from a console and paste into IPython - when you do that, at least the second line will always include the prompt.

Otherwise, don't include the prompt.

**Comment by rsokl** [comment]
Would there be any disadvantage to looking beyond two lines to strip a prompt? Clearly removing the prompt gets rid of the syntax error, but it defeats purpose of writing a code snippet like: 

```python
# shape-(3, 1, 2) broadcast-multiply with
# shape-(3, 1) produces shape-(3, 3, 2)
>>> x * y
array([[[ 0,  0],
        [ 0,  1],
        [ 0, -1]],

       [[ 0,  0],
        [ 2,  3],
        [-2, -3]],

       [[ 0,  0],
        [ 4,  5],
        [-4, -5]]])
```
which must distinguish the input and output in a console environment. In my mind, permitting more than two lines would nicely accommodate a rather natural style of providing documentation for a console-style code snippet.

**Comment by takluyver** [comment]
Greater likelihood of incorrectly stripping things that look like a prompt but aren't

```python
# For example
a = """
>>> look at me <<<
"""
```

**Comment by rsokl** [comment]
Ah. Of course. Yeah that would be a nightmare. Thanks for your time.
