### ISSUE TITLE
ipython option to ignore quit()

### ISSUE THREAD

**Issue by Tagar** [ipython/ipython#11010]
Is there is a way to make ipython ignore quit() ?

We have some users who incidentally put quit() (or copy-paste it without verifying in their Apache Zeppelin notebooks and this makes ipython backend process exit, leaving "pyspark interpreter" hanging.. 

This might have to be solved on Apache Zeppelin IPython side, but I wonder if there is a way to force ipython process not simply quit on accidents like this, or on some sort of exceptions.

**Comment by ivanov** [comment]
Hi @Tagar -  you can do this by running something like `def quit():pass` at the beginning.  There are various ways to run something at the beginning of an ipython session, depending on what you're using.

**Comment by Tagar** [comment]
thank you @ivanov
