### ISSUE TITLE
IPython 6.2.1 'ls' locks the terminal after running python script (OSX and Ubuntu)

### ISSUE THREAD

**Issue by chrisgmorton** [ipython/ipython#11012]
I'm not observing this with other OS commands such as 'pwd'. This issue is observed on both Ubuntu 16.04 and on MacOSX 10.13.2. My code is quite involved and I'm not sure what the interaction is. If you have a suggestion on likely cause I can try to simplify to provide a reproducible test case.

**Comment by ivanov** [comment]
Hi @chrisgmorton - sorry you're having trouble. A couple of question to help us figure out what might be happening:

So are you able to run all other commands after running your script, with the exception of `ls` - is that right? How are you running your script - just with the `%run` magic, or some other way? Does your script by chance create a variable in the namespace with the name `ls` - in other words, does `type(ls)` raise a NameError, or does it return something?

**Comment by chrisgmorton** [comment]
Hi Paul, thanks for the follow-up. I am able to run other imported functions from my package, following execution completion. I also get a correct result from 'pwd'. The script is run by importing my created package and a wrapper script that creates objects and executes methods. I am not using %run magic. Performing type(ls) raises an NameError so 'ls' is not redefined in the namespace.

**Comment by chrisgmorton** [comment]
`ls` is pointing to `/bin/ls` and file count is 31 in my case so this likely eliminates the simple issues.

I dug in a little and looked to see if I could isolate an offending call that was causing 'ls' to lock the terminal. I followed execution deep down into the sparse matrix code of my application and it looks like calls into linear and sparse linear algebra code causes the `ls` lock even though execution completes successfully and the application exits gracefully.

When I replaced calls to `numpy.linalg.norm()` with `scipy.linalg.norm()` this stopped the terminal lock-up of 'ls' after script completion. Unfortunately uncommenting out the call to `scipy.sparse.linalg.gmres()` again caused the terminal lock-up with 'ls' after script completion.

I'm using NumPy 1.13.1 and SciPy 0.19.1 built with the gnu 7 compilers and Intel Math Kernel Library.

**Comment by ivanov** [comment]
I'm a bit baffled.. is there no difference in behavior with `!ls` ?

**Comment by chrisgmorton** [comment]
There is no difference in behavior with `!ls`. I will try create a reproducible test case for you.

**Comment by chrisgmorton** [comment]
`Python 3.6.4 (default, Jan 21 2018, 20:39:54) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: ls
Desktop/               Music/                 bin/
Documents/             Nolo Documents Backup/ tmp/
Downloads/             Pictures/              usr/
Dropbox/               Public/                work@
Library/               Sites/
Movies/                atest.sh*

In [2]: import numpy as np

In [3]: np.__version__
Out[3]: '1.13.1'

In [4]: from numpy import linalg

In [5]: x=np.arange(10000)

In [6]: x
Out[6]: array([   0,    1,    2, ..., 9997, 9998, 9999])

In [7]: linalg.norm(x)
Out[7]: 577306.96773900103

In [8]: ls
`

**Comment by ivanov** [comment]
Your test case doesn't reproduce the behavior for me - but i'm on numpy 1.14.1 and without MKL.

One last thought - our `pwd` uses python's `os.getcwd()` under the hood, I wonder if the problem is with anything that tries to shell out. Does `!pwd` or `!echo 'hi'` also stall after the call to linalg?

**Comment by chrisgmorton** [comment]
Interestingly, pwd shows the correct output but !pwd locks. Also !echo 'hi' locks.

**Comment by ivanov** [comment]
ok - so it seems calling python functions work, but shelling out does not - at  least it's  nothing special about `ls` - does `os.system` also lock up the way `!` does?  Say `os.system("pwd")`, for example?

And can you try this in just a plain python shell - I suspect this isn't IPython related, but it's numpy leaving the system in this unhappy state.

**Comment by chrisgmorton** [comment]
os.system("pwd") does not lock up and shows the correct output as does os.system("ls"). As you might expect, this correct behavior is also shown in a plain python shell.

**Comment by takluyver** [comment]
The behaviour of `!` depends on whether you're using IPython in the terminal or as a Jupyter kernel.

In the terminal, it calls:

```python
subprocess.call('ls', shell=True, executable=os.environ.get('SHELL'))
```

If you can still reproduce the error, does running that command produce the same behaviour? Can you check if the SHELL environment variable is being changed?

(From what you've said above, I think you're using terminal IPython. If you're using it through Jupyter, then `!` commands are more complicated - it involves tricking the subprocess into thinking that it's running in a terminal.)

**Comment by chrisgmorton** [comment]
I can still reproduce the error.

Executing the above python code in an IPython terminal and then importing os and subprocess and executing:

`
os.environ.get('SHELL')
`

gives '/bin/bash'.

Executing,

`
subprocess.call('ls', shell=True, executable=os.environ.get('SHELL'))
`

hangs the terminal. Ctrl C does not even force an exit.

This seems to be specific to Intel's Math Kernel Library. If I were to hazard a guess, I would say this is related to MKL's multithreading execution and exit. When I use a smaller vector size (1000 instead of 10000) in the test case above, the error does not show up. MKL likely decides not to use multiple threads when the problem size is small enough that multithreading has no practical advantage.

This will very likely show up for all distributions that use MKL with NumPy and SciPy such as Anaconda. Calls to SciPy's sparse.linalg.lmgres() also cause the hang. Importantly for those digging in further, replacing Numpy's norm() with Scipy's linalg.norm() stops the hang in my test case. I still have the issue with sparse.linalg.lmgres() through and I am assuming (possibly wrongly) that the root causes are one and the same.

**Comment by takluyver** [comment]
Your guess sounds reasonable. Try playing around with the `subprocess` call to see if you can narrow down what situations it fails in.

**Comment by chrisgmorton** [comment]
I'm unable to narrow down further. Trying subprocess.run('ls'), subprocess.run('ls', check=True), subprocess.Popen('ls') all just cause the hang.

**Comment by chrisgmorton** [comment]
I have found a workaround for this issues which is to set the environment variable, `KMP_INIT_AT_FOLK=FLASE`. This issue relates to problems with Intel's MKL multithreading. See numpy/numpy#11734, issues and workarounds.

**Comment by chrisgmorton** [comment]
The route cause of this issue is Intel's MKL library and can resolved either by using `KMP_INIT_AT_FORK=FALSE` or using the  Intel TBB threading layer (see numpy/numpy#11734 for more details.)
