### ISSUE TITLE
option to disable .display() removing multiple whitespace

### ISSUE THREAD

**Issue by h-vetinari** [ipython/ipython#11022]
I've spent an hour rooting through documentation and source code, but I cannot find an option to _disable_ the fact that `display_html` automatically replaces multiples spaces with a single space (actually, I want to set a `pd.DataFrame`, and I need to illustrate precisely the difference between multiple and single whitespace).

It seems the call somehow ends up `InteractiveShell.instance().display_formatter.format` and its cell magic, and I had to give up the trail there, as it was getting increasingly unlikely that I could control this behaviour externally.

For most cases it's reasonable to remove multiple spaces, but as a design principle (IMO), if you mutate _the content_ of a user's input, you should at least provide the option to disable that mutation.

**Comment by takluyver** [comment]
I don't think we change it. Browsers collapse adjacent whitespace when displaying HTML. I think this is actually part of the official HTML specification.

If you want to use multiple spaces without them collapsing, you can use `&nbsp;` (non-breaking space), or control it using CSS (https://www.w3schools.com/cssref/pr_text_white-space.asp).

**Comment by h-vetinari** [comment]
Sorry for the late reply.

The issue is that - while it may be part of the HTML specs - it's being used for displaying `pd.DataFrame` in ipython, and there it might be essential to not change multiple spaces.

**Comment by takluyver** [comment]
If there's a problem with how pandas dataframes display, you probably need to open an issue on pandas - the package generates the HTML, IPython just passes it on to the browser.

**Comment by rsclafani** [comment]
Stumbled on this issue looking for a solution. The workaround I came up with is to execute the following in the notebook.
```
from IPython.core.display import display, HTML
display(HTML("<style>.rendered_html td { white-space: pre; }</style>"))
```
A global alternative would be to add the corresponding CSS to your ipython/jupyter custom profile.
