### ISSUE TITLE
Wrong suggestion for Python 3 missing paraentheses

### ISSUE THREAD

**Issue by ritiek** [ipython/ipython#11020]
IPython 6.2.0.dev (b65d977c8c5f936fe35ddd96eb28a8707828f8c3)
Python 3.6.4

Not a big deal but IPython gives an incorrect fix for *SyntaxError* when printing items coming from tuples/lists:

```python
In [3]: for x in (1,2,3):
   ...:     print x
  File "<ipython-input-3-b66a0b350f37>", line 2
    print x
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int x)?
```

> Did you mean print(**int** x)?

It should be just `print(x)`, removing the `int` part.

**Comment by takluyver** [comment]
That error message comes from Python itself, not from us. It looks like this might be the relevant bug:

https://bugs.python.org/issue32028

**Comment by ritiek** [comment]
IMO then it gets even weirder because my Python interpreter gives correct suggestion:
```
$ python3
```
```python
Python 3.6.4 (default, Feb 23 2018, 12:59:10)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> for x in (1,2,3):
...     print x
  File "<stdin>", line 2
    print x
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(x)?
```

where as IPython3:
```
$ ipython3
```
```python
Python 3.6.4 (default, Feb 23 2018, 12:59:10)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.0.dev -- An enhanced Interactive Python. Type '?' for help.

In [1]: for x in (1,2,3):
   ...:     print x
  File "<ipython-input-1-b66a0b350f37>", line 2
    print x
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int x)?
```

---

> It looks like this might be the relevant bug:
>
> https://bugs.python.org/issue32028

However, for some reason `print "%d" % 2` and `print 123` gives correct suggestion in my both Python and IPython interpreter.

**Comment by takluyver** [comment]
I see the bug in a plain Python shell as well:

```
Python 3.6.4 (default, Feb  8 2018, 14:42:51) 
[GCC 7.3.1 20180130 (Red Hat 7.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> for x in (1,2,3):
...     print x
  File "<stdin>", line 2
    print x
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int x)?
```

**Comment by manisha27** [comment]
f=open("/Downloads/Python_Primer/Humpty.txt")

rhyme=f.read()

f.close()

print rhyme
  File "<ipython-input-5-272e63b31269>", line 1
    print rhyme
              ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by manisha27** [comment]
f=open("/Users/manishatripathi/Downloads/CQF_Python_Primer/Humpty.txt")

    rhyme=f.read()

    f.close()

    print rhyme
      File "<ipython-input-5-272e63b31269>", line 1
        print rhyme
              ^
    SyntaxError: Missing parentheses in call to 'print' 

What is this error about?

**Comment by manisha27** [comment]
f=open("/Downloads/Python_Primer/Humpty.txt")

    rhyme=f.read()

    f.close()

    print rhyme
      File "<ipython-input-5-272e63b31269>", line 1
        print rhyme
              ^
    SyntaxError: Missing parentheses in call to 'print' 

What is this error about? Thanks!
