### ISSUE TITLE
imp.reload() does not work, but ipython autoreload does well

### ISSUE THREAD

**Issue by Justsoos** [ipython/ipython#11024]
two problem:
**first, might be bug of python??**
my python ver: `Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32`
my ipython ver:`6.2.1 `

I tried to change the model source code and then imp.reload() them both in python and ipython shell, nothing changed. I have to quit python or ipython shell and re-run to reload the model.

but after set autoload in profile of ipython, worked !!
```
c.InteractiveShellApp.exec_lines = ['%autoreload 2']
c.InteractiveShellApp.extensions = ['autoreload']
```

**second question, there three profile of ipython, should I delete some of them?**
I installed ipython from pip3 install jupyter, and then I found there are two ipython_config.py files belong to:
`Python36\Lib\site-packages\jupyter_core\tests\dotipython\profile_default`
`Python36\Lib\site-packages\jupyter_core\tests\dotipython_empty\profile_default`
it might be created by jupyter??
and the third one is made by `ipython profile create`, in ~\.ipython

but before I created the last one, I changed the content of `Python36\Lib\site-packages\jupyter_core\tests\dotipython_empty\profile_default\ipython_config.py`
it also served effective... so made me confused, how to set the unique profile ?

**Comment by takluyver** [comment]
- `imp.reload()` has to be given a module object, and only reloads one module at a time, whereas autoreload finds any modules which you have changed and reloads them.
- The profiles in `jupyter_core/tests` are part of the tests for the jupyter_core package. They are not used outside the tests, and you can safely ignore them.

**Comment by Justsoos** [comment]
- @takluyver  thx~, yes, I did use imp.reload(model), but python and ipython shell did not work. seems bugs of python, but autoload settings of ipython always worked... do not know why
- and I changed the ipython_config.py in `jupyter_core/tests` with `c.StoreMagics.autorestore = True`, it still take effect to ipython shell... maybe I should delete them.

**Comment by takluyver** [comment]
Closing as I don't think any of this indicates bugs with IPython.
