### ISSUE TITLE
asyncio will be running by default with tornado 5

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#11030]
When tornado 5 is released, which is scheduled to be this month, the tornado ioloop will run on asyncio by default. For the most part, this is nice because asyncio will always be running (#9166), but it's also tricky because simple cells like this that assume asyncio isn't running will stop working:

```python
loop = asyncio.get_event_loop()
# will fail because loop is already running:
loop.run_until_complete(asyncio.sleep(1))
```

Without something like #10390, there won't be an easy way that I can see for users to run asyncio code in IPython, other than putting them in a background thread where they can run it in an eventloop:

```python
aio_pool = ThreadPoolExecutor(1)

def init_loop():
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    return loop

aio_loop = aio_pool.submit(init_loop).result()

async def mycoro():
    await asyncio.sleep(1)
    return 5

result = aio_pool.submit(lambda : aio_loop.run_until_complete(mycoro())).result()
```

and #10390 still needs to handle the fact that asyncio will be running, which I don't think it does right now.

**Comment by minrk** [comment]
Here's a quick hack to provide an `%%asyncio` magic running async functions in the aio_thread:

```python
import asyncio

from concurrent.futures import ThreadPoolExecutor
import textwrap

aio_pool = ThreadPoolExecutor(1)

def init_loop():
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    return loop

aio_loop = aio_pool.submit(init_loop).result()

async def mycoro():
    await asyncio.sleep(1)
    return 5

result = aio_pool.submit(lambda : aio_loop.run_until_complete(mycoro())).result()

ip = get_ipython()
def asyncio_magic(line, cell):
    async_cell = "async def __async_f():\n%s" % textwrap.indent(cell, '    ')
    exec(async_cell, ip.user_ns)
    f = ip.user_ns['__async_f']
    
    result = aio_pool.submit(lambda : aio_loop.run_until_complete(f())).result()

ip.register_magic_function(asyncio_magic, magic_kind='cell', magic_name='asyncio')
```

**Comment by fortuna** [comment]
It would be great if this was made easier.

I was able to at least find a simpler workaround:
```python
async def do_stuff():
    await asyncio.sleep(1)
    print("Done")

asyncio.run_coroutine_threadsafe(do_stuff(), asyncio.get_event_loop())
```

**Comment by fortuna** [comment]
Here is an alternative to above.

One time setup:
```python
from concurrent.futures import ThreadPoolExecutor
import asyncio
LOOP = asyncio.new_event_loop()
ThreadPoolExecutor().submit(LOOP.run_forever)
```

Whenever you need async:
```python
asyncio.run_coroutine_threadsafe(coro, LOOP).result()
```

**Comment by Carreau** [comment]
We now have asyncio reply closing.

**Comment by fm75** [comment]
Excellent! Is this in a release?

**Comment by Carreau** [comment]
Yes, see https://ipython.readthedocs.io/en/stable/whatsnew/version7.html#ipython-7-0-0

You can just await: 
```
In [1]: import asyncio

In [2]: await asyncio.sleep(1)

In [3]:
```

And it works.

**Comment by fm75** [comment]
Indeed! Awesome. Just testing in the-littlest-jupyterhub that I set up this week.
Thank you.
