### ISSUE TITLE
display of wide table in HTML no longer has scroll bar

### ISSUE THREAD

**Issue by tomweber-sas** [ipython/ipython#11033]
Hey, I've been tracking down a customer problem with my package, saspy. I'm returning HTML5 results that contain a table of data that's wider than the width of the window in jupyter. This has always worked just fine; has a scroll bar and each column is separate without overlap of the column names or data.
I just upgraded to anaconda 3.6; python 2.6.4, ipython 6.2.1. Now I'm getting the same broken behavior my customer reported. The table now renders without the scrollbar and the column names are overlapped and unreadable. The table is squished into the fixed width of the jupyter window.
You can see this in my issue number 97: https://github.com/sassoftware/saspy/issues/97
I had been at an earlier version with python3.5 and ipython 5.3.0 (and earlier version before that as well). Never saw this problem in any previous version, so it seems to be a problem with this release.
Thanks!
Tom

**Comment by takluyver** [comment]
This is probably related to the [notebook package](https://github.com/jupyter/notebook), which contains the CSS affecting output.

**Comment by takluyver** [comment]
See also https://github.com/jupyter/notebook/issues/2209

**Comment by tomweber-sas** [comment]
@takluyver Thanks for pointing me to the right place! I've asked them about this on that issue.
Appreciate it getting back to me quickly.
Thanks,
Tom
