### ISSUE TITLE
No way to access current cell from Javascript when displaying HTML

### ISSUE THREAD

**Issue by EtienneDesticourt** [ipython/ipython#11037]
Hi,  

When creating a Javascript DisplayObject (from IPython.core) an element variable is defined that allows the Javascript code to modify the cell's output. But when displaying an HTML DisplayObject there seems to be no way to access the current cell from the Javascript code contained within the HTML.

For context I'm trying to propagate errors from a js library loaded in an HTML page. I tried raising an exception with Jupyter.notebook.kernel.execute but it didn't interrupt the cell's code nor did it display the exception so now I'm trying to just display Jupyter's python exception template from js but I can't figure out a way to do it.

**Comment by takluyver** [comment]
This would probably belong on https://github.com/jupyter/notebook , but I don't think there's anything we can do about it from Jupyter/IPython. I don't think you can control the context Javascript will run in when you add it to the page as part of some HTML.

One option for you might be to include in your HTML an empty div with a unique ID, and use that to display errors. Or you might just let the errors go to the Javascript console in the browser; that's where we generally expect to see Javascript errors reported.
