### ISSUE TITLE
The markdown file converted from Jupyter Notebook using nbconvert can't display png image file in GitHub Page

### ISSUE THREAD

**Issue by qiandongmin** [ipython/ipython#11048]
In my repisitory/_posts/ folder, I have this markdown file, which is converted from Jupyter Notebook using nbconvert. Inside this markdown tile, I have the following line:

```
![png](/static/911-Calls-Data-Capstone-Project_26_1.png)
```

Under my respository folder, I also h ave folder /static/, and there is 911-Calls-Data-Capstone-Project_26_1.png inside.  I can see the png image display properly in the github Edit File and Preview Changes window. However, the png file is not displaying on the GitHub page.

Anyone can help me with this problem? I have tried everything I can.

**Comment by takluyver** [comment]
I don't think this is related to IPython, sorry.
