### ISSUE TITLE
Make the crash handler tell users to provide more information

### ISSUE THREAD

**Issue by slel** [ipython/ipython#11042]
Currently the crash handler provides a crash log and tells users to send it
to developers. It would be useful to also tell users to provide information
about their operating system and how they installed the application.

**Comment by jdemeyer** [comment]
+1. Somehow the existence of the crash log makes users think that they do not have to provide any extra information. We often get bug reports in Sage containing literally only the crash log.

**Comment by slel** [comment]
Pull request #11043 aims to solve this issue by suggesting users
to include some more information when sending a crash report.

**Comment by takluyver** [comment]
Closed by #11043.
