### ISSUE TITLE
IO loop error

### ISSUE THREAD

**Issue by rbajaj999** [ipython/ipython#11055]
I am getting the following error whenever I try to launch jupyter using command line ( not using anaconda). Please suggest a solution. 

File "/usr/local/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/Library/Python/2.7/site-packages/notebook/notebookapp.py", line 45, in <module>
    ioloop.install()
  File "/Library/Python/2.7/site-packages/zmq/eventloop/ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'

I have already tried to update the zmq package but it doesnt seem to help. The issue exists in both python2 and 3 enviornment. Will appreciate any help in this regard.

**Comment by takluyver** [comment]
There should be a line after that which says what the actual error is.

What version of zmq do you have (`import zmq; zmq.__version__`)?

**Comment by rbajaj999** [comment]
@takluyver  thanks for pointing out. I have updated my comment with the actual error. 

I am using the following pzmq 17.0.0 

below is pip freeze from my terminal

ppnope==0.1.0
bleach==2.1.3
decorator==4.2.1
entrypoints==0.2.3
html5lib==1.0.1
ipykernel==4.8.2
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==7.1.2
jedi==0.11.1
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
MarkupSafe==1.0
mistune==0.8.3
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.4.0
pandocfilters==1.4.2
parso==0.1.1
pexpect==4.4.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
Pygments==2.2.0
python-dateutil==2.6.1
pyzmq==17.0.0
qtconsole==4.3.1
Send2Trash==1.5.0
simplegeneric==0.8.1
six==1.11.0
terminado==0.8.1
testpath==0.3.1
tornado==4.5.3
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.1.4

**Comment by minrk** [comment]
This error means that pyzmq 17 is *not* used (`IOLoop.initialized` [does not occur](https://github.com/zeromq/pyzmq/blob/v17.0.0/zmq/eventloop/ioloop.py) in pyzmq 17). If pip thinks you have pyzmq 17, you might try uninstalling it and installing it again, and double-check where pyzmq is importing from (`zmq.__file__`).

**Comment by takluyver** [comment]
Closing because this isn't part of IPython; feel free to keep using the comments to debug it.
