### ISSUE TITLE
SyntaxError: f-string expression part cannot include a backslash

### ISSUE THREAD

**Issue by Paddy3118** [ipython/ipython#11050]
I am using Jupyter Notebook 5.4.0 via Anaconda.

A code cell of:
```
l = [x**.5 for x in range(1, 11)]
print(f"floats: [{\", \".join(f\"{x:.3f}\" for x in l)}]")
```
gives an output error of "SyntaxError: f-string expression part cannot include a backslash"
The code was developed and works in python 3.6.0a3 though?

The context was [this](http://paddy3118.blogspot.co.uk/2018/03/what-f-in-f.html) short blog post.

Thanks.

PS:

{'commit_hash': 'ca5443062',
 'commit_source': 'installation',
 'default_encoding': 'cp1252',
 'ipython_path': 'C:\\Users\\Paddy3118\\Anaconda3\\lib\\site-packages\\IPython',
 'ipython_version': '6.2.1',
 'os_name': 'nt',
 'platform': 'Windows-10-10.0.16299-SP0',
 'sys_executable': 'C:\\Users\\Paddy3118\\Anaconda3\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, '
                '10:22:32) [MSC v.1900 64 bit (AMD64)]'}

**Comment by takluyver** [comment]
I get the same error putting that code into a plain Python shell. I think that's the risk you take if you develop something using an alpha version of Python - things are allowed to change from an alpha to a final release.

**Comment by ericvsmith** [comment]
This was indeed a late change to Python 3.6, shortly before the second beta, if memory serves me. See https://bugs.python.org/issue27921.

My intention is to some day relax this condition, so as to at least allow `\r`, `\t`, `\n`, etc. But it's not a straightforward problem, and depends on how people do (or don't) want to modify the lexer and parser to understand f-strings.

I think this bug can be closed, as it's not an issue with ipython.

**Comment by takluyver** [comment]
Thanks for those details. :-)
