### ISSUE TITLE
license please?

### ISSUE THREAD

**Issue by XenoAmess** [ipython/ipython#11058]
Thanks for making such a useful and beautiful tool.
I didn't find license in the files.So,where is it?
I wanna fork this and try to make an ijava or something.
If there is still no liscence,then please add it.

**Comment by takluyver** [comment]
It's here: https://github.com/ipython/ipython/blob/master/COPYING.rst

There are a couple of Java kernels already, one of them even called IJava. I haven't tried either of them, though. See the kernels list: https://github.com/jupyter/jupyter/wiki/Jupyter-kernels
