### ISSUE TITLE
Bug arising from %run combined with importing sklearn

### ISSUE THREAD

**Issue by Tahnan** [ipython/ipython#11057]
Hi there--apologies if this has been reported before, but "run" is sort of a hard thing to search for.  I didn't *see* anything like this, at least...

I'm using ipython 6.2.1 (commit_hash: `ca5443062`, commit_source: `installation`) with Python 3.4.3 (`3.4.3 (default, Nov 28 2017, 16:41:13) \n[GCC 4.8.4]`) on Ubuntu 14.04 ("trusty").  I also have scikit-learn installed (nothing unusual, installed via pip, version `0.19.1`).

If, in ipython, I `import sklearn`, nothing unusual happens.  Everything proceeds as expected.

*If*, however, I import it via `%run`--that is, if I use `%run` to run a file whose contents are nothing but `import sklearn`, or if I import it indirectly by running a file that imports something that imports something that, somewhere down the line, imports something from sklearn--then I get the following error the *first* time I do anything that raises an exception (the example here uses an AssertionError via `assert False`, but analogous things happen with, e.g., a NameError or a ZeroDivisionError):

```
$ ipython
Python 3.4.3 (default, Nov 28 2017, 16:41:13) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: with open('temp.py') as f:
   ...:     print(f.read())
   ...:     
import sklearn


In [2]: %run temp.py

In [3]: assert False
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/home/lnathan/code/suez-env/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-a871fdc9ebee>", line 1, in <module>
    assert False
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lnathan/code/suez-env/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 1828, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lnathan/code/suez-env/lib/python3.4/site-packages/IPython/core/ultratb.py", line 1090, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/home/lnathan/code/suez-env/lib/python3.4/site-packages/IPython/core/ultratb.py", line 311, in wrapped
    return f(*args, **kwargs)
  File "/home/lnathan/code/suez-env/lib/python3.4/site-packages/IPython/core/ultratb.py", line 345, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.4/inspect.py", line 1338, in getinnerframes
    framelist.append((tb.tb_frame,) + getframeinfo(tb, context))
  File "/usr/lib/python3.4/inspect.py", line 1298, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/usr/lib/python3.4/inspect.py", line 583, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/usr/lib/python3.4/inspect.py", line 629, in getmodule
    os.path.realpath(f)] = module.__name__
AttributeError: 'module' object has no attribute '__name__'
---------------------------------------------------------------------------
```

Subsequent exceptions display normally.

I traced this as deep into sklearn as I could (well, OK, as deep as I could until I realized it was after 5pm on a Friday and my energy isn't boundless), and it seems to be the result of something in `sklearn.utils.fixes`.  That module is the first thing in the import chain in sklearn that imports anything from `inspect`.  Our best speculation, then, is that the interaction between what ipython does with `inspect` and what sklearn does with `inspect` is clashing in some way.

**Comment by teeberg** [comment]
I'm also having this problem and am currently googling around and crawling through this repo's issues. Looks like this has also been reported in https://github.com/ipython/ipython/issues/9978

**Comment by Tahnan** [comment]
Aha!  Thank you for seeing that other report--as I said, I did try to search, but it's *really hard* to search for bugs with %run.

**Comment by Carreau** [comment]
That seem to be a bug in Python itself. On more recent version of Python, this does not appear to crash for me. As said in linked issue:

> From the traceback, it looks like it might even be an issue with Python's own inspect library, which assumes that modules have a __name__ attribute. We do already go to some lengths to work around inspect issues, but I'd rather not pile on more monkeypatches.

Closing as duplicated.
