### ISSUE TITLE
Add text to Audio display object?

### ISSUE THREAD

**Issue by thisisjl** [ipython/ipython#11074]
Hi, in my notebook I am printing a list of Audio display objects and I would like to have a title for each one of them. Therefore, I would like to know if it is possible to add some text to an Audio display object. Or if it is possible to embed the Audio object in a table, so the cell next to the audio object will contain the text.

At the moment I am using the following code, but I am sure there are better ways to do it:

```python
def title_audio(filename=None, url=None, text=None, seconds=30, fs=16000):
    tmpl = """
    <table style="width:100%">
    <tr>
        <td>
            {title}
        </td>
        <th>
            <audio controls>
                    <source src="data:audio/x-m4v;base64,{data}" type="audio/wav">
                </audio>
        </th>
    </tr>
    """
    if filename is not None:
        wav_bin = open(filename, "rb").read()
    elif url is not None:
        u = urlopen(url)
        wav_bin = u.read(int(np.ceil(seconds * fs)))

    if text is None:
        text = ''

    if six.PY3:
        b = base64.encodebytes(wav_bin).decode('utf-8')
    else:
        b = base64.encodestring(wav_bin)
    out = tmpl.format(data=b, title=text)

    return HTML(out)
```

Thanks

**Comment by takluyver** [comment]
I don't think there's currently any better way to do this than assembling the HTML yourself.

**Comment by thisisjl** [comment]
okay, thank you for your response.
