### ISSUE TITLE
How can I display output when calling ipd.Markdown() from a function?

### ISSUE THREAD

**Issue by dmolesUC3** [ipython/ipython#11077]
In my JupyterLab notebook, if I write

```python
ipd.Markdown('hello I am plain `ipd.Markdown()` output')
```

I get, as expected:

> hello I am plain `ipd.Markdown()` output

But if I write:

```python
def display_md(md):
    ipd.Markdown(md)
display_md('hello I am `display_md()` output')
```

I get nothing.

Clearly, `ipd.Markdown()` is missing some important context in the second case. Is there some way I can provide that? This is a trivial example, but I have more complex Markdown-generating code that I'd like to be able to call and display in one (module) function, without having to write a function that generates the Markdown as a string and then explicitly call `ipd.Markdown()` on the result.

**Comment by dmolesUC3** [comment]
I misunderstood how `Markdown` works and how the result was getting displayed. Changing my function to either

```python
def display_md(md):
  ipd.display(ipd.Markdown(md))
```

or

```python
def to_markdown_obj(md):
  return ipd.Markdown(md)
```

gets me the output I wanted.

**Comment by takluyver** [comment]
We often say that `display()` is the rich content equivalent of `print()`. An expression at the end of a cell gets displayed automatically, but if you want to display something from other code, call the `display()` function. `Markdown()` constructs an object that can be displayed, but it doesn't do the displaying.
