### ISSUE TITLE
File autocompletion gets buried in python nonsense

### ISSUE THREAD

**Issue by memeplex** [ipython/ipython#11088]
Just that, pressing tab after a path should only return completions for the filesystem, without including the current python workspace. Otherwise, it's pretty unusable except that you already know the name (or a prefix of the name) of the file you are interested in.

**Comment by takluyver** [comment]
What version of IPython are you on? We've been trying to improve this in recent releases, so please upgrade if possible.

**Comment by memeplex** [comment]
I was in 6.2.1, now I upgraded to 6.3.1 and works like a charm. Thanks!
