### ISSUE TITLE
pastebin magic does not work: github requires authentication to create gists

### ISSUE THREAD

**Issue by nonZero** [ipython/ipython#11082]
Github now [requires authentication](https://developer.github.com/v3/gists/#authentication) to create gists:

> You can read public gists anonymously, but you must be signed into GitHub to create gists.

`%pastebin` does not work anymore and returns 401:

    HTTPError: HTTP Error 401: Unauthorized

**Comment by takluyver** [comment]
Oh, that's frustrating. I'm not sure we want to deal with OAuth inside IPython. Maybe it should use another service?

**Comment by daniilhayrapetyan** [comment]
Have the same issue on ipython version 5.8.0.
