### ISSUE TITLE
ipython giving error and not showing the run option

### ISSUE THREAD

**Issue by Flock1** [ipython/ipython#11090]
Hi,

I am currently using anaconda in an environment and I haven't been able to run the notebook. I try to kill the servers but I keep getting that message:
![screenshot from 2018-04-12 09-45-59](https://user-images.githubusercontent.com/15093420/38656172-6f63d9fe-3e36-11e8-9837-dbf82ac6e3ee.png)

I tried an alternative, that is to install jupyter notebook through pip3, but I don't know why Ananconda is messing up. Please let me know what I should be doing.

**Comment by takluyver** [comment]
Those messages don't look like errors. Can you use the 'copy text' button to get all the output it's showing and paste it in here? Maybe there's an error further down.

**Comment by Flock1** [comment]
This is the message:
`[I 16:06:51.195 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 16:06:51.580 NotebookApp] JupyterLab beta preview extension loaded from /home/sarvagya/anaconda3/lib/python3.6/site-packages/jupyterlab
[I 16:06:51.580 NotebookApp] JupyterLab application directory is /home/sarvagya/anaconda3/share/jupyter/lab
[I 16:06:51.584 NotebookApp] Serving notebooks from local directory: /home/sarvagya
[I 16:06:51.584 NotebookApp] 0 active kernels
[I 16:06:51.584 NotebookApp] The Jupyter Notebook is running at:
[I 16:06:51.584 NotebookApp] http://localhost:8888/?token=ce7482fad006d5fdbca3fc8ffe2a232cf39beff50fee3055
[I 16:06:51.584 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:06:51.585 NotebookApp] 

Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8888/?token=ce7482fad006d5fdbca3fc8ffe2a232cf39beff50fee3055
[I 16:06:51.874 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[5866:5905:0412/160651.932995:ERROR:browser_gpu_channel_host_factory.cc(120)] Failed to launch GPU process.
`

**Comment by takluyver** [comment]
The last line is an error, but it's a Google Chrome error, not our error. See jupyter/notebook#2836.

**Comment by Flock1** [comment]
Hi. Thanks. I am now facing a new problem. I installed jupyter notebook and tensorflow GPU in a conda environment. Now, when I try to import tensorflow, it gives the error that no tensorflow module is present. Can you help me with this?

**Comment by takluyver** [comment]
It sounds like you're trying an import in two different installations of Python, or two different environments. Check `sys.executable` to see which Python and environment you're running in, and `sys.path` to see where it looks to import modules.

Python packages must be installed separately for each copy of Python you use, and if you are using virtualenvs or conda envs, packages must be installed into each environment where you need them. Either the package is not installed in one, or a different version of the package is installed.

To install packages to a particular Python installation or environment using pip, you can run it like this:

```shell
path/to/python -m pip install ...
# Replace path/to/python with the path of the Python executable (sys.executable)
```

If you are using conda environments, you can install packages from conda like this:

```shell
source activate myenv  # On Windows, just 'activate myenv' (no 'source')
conda install ...
```

For more detail, see [this blog post](http://takluyver.github.io/posts/i-cant-import-it.html).

[ This is a saved reply because I answer similar questions often - sorry if it doesn't exactly fit your case ]

**Comment by Flock1** [comment]
One weird thing happening with my conda environment is, it's creating a whole different folder like .conda where it's creating the environment. I'm guessing that's the problem. Can you help me with this?

**Comment by takluyver** [comment]
I think that's normal if you've installed Anaconda systemwide (so the Anaconda installation is not user-writable).

**Comment by Flock1** [comment]
So how do I install it in anaconda folder instead of some folder like .conda?

**Comment by takluyver** [comment]
If it's creating environments in `.conda`, that should be fine - so long as it can find the environment when you `source activate my_env` (replace my_env with whatever you called your environment).

**Comment by Flock1** [comment]
It does. It finds the env. The only problem is, python libraries don't work, specially tensorlfow gpu. When run it through anaconda navigator, non-gpu tensorflow works, but with jupyter notebook, no tensorflow works. 

I have installed tensorflow using pip and conda in the env but nothing works.

**Comment by takluyver** [comment]
Your kernel in the notebook is probably running in a different environment, then. Use `jupyter kernelspec list` to find where the kernelspecs are (these tell Jupyter about different kernels). If there's one ending in something like `.../kernels/python3`, the easiest thing is usually to delete it, so Jupyter will fall back to running the kernel in the same Python as you used to launch Jupyter.

**Comment by Flock1** [comment]
Hmmm. This is new. I've not tried this. I'll try that and will get back

**Comment by Flock1** [comment]
Great. This helped me import tensorflow. Now, one more small issue. I have a GPU and I installed tensorflow GPU through conda in the environment. It's not accessing the GPU. Can you help me with this? I think this will be the final issue

**Comment by takluyver** [comment]
Sorry, you'll need to ask Tensorflow about that - I can't help.

**Comment by Flock1** [comment]
Thanks for the help.
