### ISSUE TITLE
What‘s reason of this error?

### ISSUE THREAD

**Issue by nzh19970106** [ipython/ipython#11091]
![2018-04-12 22-50-21](https://user-images.githubusercontent.com/24224167/38685216-f10e9b8e-3ea3-11e8-84f7-022e4af04927.png)

I think all of my configuration is correct.But it failed. Each time when I run, this error will occur. When I use my partner's computer, it also failed with the same error.

**Comment by takluyver** [comment]
I'm not sure, but the `HINT` at the top of the screenshot suggests that this might be something to ask Theano about.

**Comment by takluyver** [comment]
Closing because this doesn't look like a bug in IPython - there's some problem with the code you're trying to run inside IPython.
