### ISSUE TITLE
spaCy similarity measure does not work in IPython 6.3.1

### ISSUE THREAD

**Issue by hadils** [ipython/ipython#11097]
## Your Environment

* Operating System: Mac OS X 10.13.4
* Python Version Used:  3.6.3
* spaCy Version Used:  2.10
* Environment Information: 
IPython 6.3.1
```Info about spaCy

    spaCy version      2.0.10         
    Location           /Users/hadilsabbagh/anaconda3/lib/python3.6/site-packages/spacy
    Platform           Darwin-17.5.0-x86_64-i386-64bit
    Python version     3.6.3          
    Models             en_core_web_lg, en
```

I  tested the example code for token similarity in Jupyter:
```tokens = nlp(u'dog cat banana')

for token1 in tokens:
    for token2 in tokens:
        print(token1.similarity(token2))
```

and got these results:
```1.0
2.30727e-21
-7.82874e+17
2.30727e-21
1.0
-8.24222e+17
0.0
-0.0446812
1.0
```

instead of:

```1.0
0.801686
0.243276
0.801686
1.0
0.281544
0.243276
0.281544
1.0
```

**Comment by takluyver** [comment]
I think you'll need to ask spacy about that, at least at first. Jupyter doesn't understand enough about the code you're running to be the direct cause of a problem like that.

**Comment by takluyver** [comment]
Follow up with spacy: https://github.com/explosion/spaCy/issues/2225
