### ISSUE TITLE
Create a magic to execute block before/after/around every computation

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipython#11104]
It would be great to have a magic that could execute a block of code after every execution, or before every execution, or perhaps just a magic that executes every computation in a specific `with` context.

Some examples of using this:

* an easy variable explorer that is updated after every execution 
* easily set up debugging-like watches in a console (print the value of certain variables after every computation
* watch certain variables, perhaps even using rich display into an ipywidget output widget
* make *sure* that some invariants are true before or after every execution

**Comment by takluyver** [comment]
You can hook things up to the `pre_execute` and `post_execute` events:

http://ipython.readthedocs.io/en/stable/config/callbacks.html

I wouldn't make magics for these at present - they're not used frequently enough to need a briefer syntax, and it would probably need some way to remove things added without a function object.

**Comment by jasongrout** [comment]
Perfect! Closing this issue, then.
