### ISSUE TITLE
timeit not running setup code

### ISSUE THREAD

**Issue by sho-87** [ipython/ipython#11105]
I have tried the following in a notebook cell:

```
%%timeit firstlist = [x for x in 'abcdefghijklmnopqrstuvwxyz']
firstlist.pop(25)
```

But I'm getting an index error, as if the setup code has not been run: `IndexError: pop index out of range`

Am I using cell mode setup code incorrectly?

**Comment by takluyver** [comment]
Timeit does something like this:

```python
(setup_code)
start = time()
for n in range(10000):
    (timed_code)
duration = (time() - start) / 10000
```

Can you see how this will go wrong with your code? :-)

**Comment by takluyver** [comment]
The purpose of that loop is to make the timing more accurate. There's some unavoidable overhead in timing, so you want the thing being timed to last long enough that it swamps the timing overhead. We actually step the loop variable up until it takes at least 2 seconds to run.

There is a second, outer loop that does what you are thinking of - take multiple readings and take an average. So when you get a result from %%timeit, it gives you mean and standard deviation. (This is controversial, there's an argument that the best time is more interesting than the mean.

You can control the two loops with the options `-n` (inner loop) and `-r` (outer loop, 'repetitions'). I always have to look up which way they go. So `%%timeit -n1` runs the inner loop just once, so your timed code always follows your setup code.

However, popping from a list is too fast to get an accurate result like that. You need to get creative. E.g. time making a list and popping from it, time making a list, and subtract.

**Comment by sho-87** [comment]
I see. any pitfalls to always using `-n1 -r100000`, besides overall slower timing runs as the setup code is being run more often?

**Comment by takluyver** [comment]
That's what I was talking about - it will give you very inaccurate timings for anything that runs quickly. E.g. here's the difference with using `-n1` on a simple example on my computer:

```
In [1]: %%timeit a = 1
   ...: a + 3
   ...: 
25 ns ± 1.29 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [2]: %%timeit -n1 a = 1
   ...: a + 3
   ...: 
264 ns ± 186 ns per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
