### ISSUE TITLE
%loadpy inconsistent with "run all" in notebook

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#1110]
Already made an allusion to it in #977,
but when using loadpy, the result is appended in the next cell, which is annoying when using "run all" or sharing notebook.

Moreover when you want to 'fix' it, you start thinking "did I changed the cell content ?, do I have to remove `%loadpy` or the next cell ?", I know that there is `%run` which works on many cases, but I'm 'running all' notebooks more and more often and I though it might append to a lot more users when released.

Expected behaviour could be :
-  override current corresponding line of the cell with loaded file, why not by prepending `# loaded through %loadpy filename`, not the all cell because it can be multiline
- comment the `%loadpy` instruction and append the file in the next cell (the easier ?)
- ideally generate a `file cell`, bound to the real file... ( one can dream )

**Comment by ivanov** [comment]
Hey gang, I'm going through old issues and it seems to me that it makes sense to close this one. `%loadpy` was renamed to `%load` a while ago, and in the notebook it replaces the current cell as of https://github.com/ipython/ipython/pull/6994 - so all of this stuff is done! Go team!

Happy hacking! :bowtie:
