### ISSUE TITLE
6.4 and 5.7 release 

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#11117]
I'll attempt to do to small releases tomorrow; 5.7 and 6.4.
They only have a couple of commits so it should be pretty strait-forward. 
This is to make sure everybody is ok with that (@rgbkrk , @takluyver ?)

And a list of todo-items. 

- [x] What's new 5.7 
  - [x] master (https://github.com/ipython/ipython/pull/11118)
  - [x] backport to 5.x (https://github.com/ipython/ipython/pull/11120)
  - [x] backport to 6.x (https://github.com/ipython/ipython/pull/11124)

- [x] What's new 6.4 
  - [x] master (https://github.com/ipython/ipython/pull/11119)
  - [x] backport to 6.x (https://github.com/ipython/ipython/pull/11126)

- [x] Create milestones
  - [x] 6.5 
  - [x] 5.8
- [x] Upload on PyPI: 
  - [x] 5.7 
  - [x] 6.4
- [x] Close previous milestones.
- [x] Conda forge 
  - [x] 5.7 (https://github.com/conda-forge/ipython-feedstock/pull/46)
  - [x] 6.4 (https://github.com/conda-forge/ipython-feedstock/pull/47)

Announce likely unnecessary.

```
$ shasum dist/*
7a8362315763fcf1aee76549687c4930827bd18f  dist/ipython-5.7.0-py2-none-any.whl
0d81e31263f57fb782b3afc54d76d2b2d06312ab  dist/ipython-5.7.0-py3-none-any.whl
42db6500a2f5a72776fe1176355e640472376522  dist/ipython-5.7.0.tar.gz

$shasum -a256 dist/*
707d1bbfc81e41e39ead1012af931bec6f80357b87e520af352e539cf5961dc0  dist/ipython-5.7.0-py2-none-any.whl
fc0464e68f9c65cd8c453474b4175432cc29ecb6c83775baedf6dbfcee9275ab  dist/ipython-5.7.0-py3-none-any.whl
8db43a7fb7619037c98626613ff08d03dda9d5d12c84814a4504c78c0da8323c  dist/ipython-5.7.0.tar.gz
```

```
$ shasum dist/*
e951fd3e262290a6ad7cc18f0e611ec8b7049249  dist/ipython-6.4.0-py3-none-any.whl
3ccb589771767e4584ebf52fe59c77339974f293  dist/ipython-6.4.0.tar.gz
$ shasum -a 256 dist/*
a0c96853549b246991046f32d19db7140f5b1a644cc31f0dc1edc86713b7676f  dist/ipython-6.4.0-py3-none-any.whl
eca537aa61592aca2fef4adea12af8e42f5c335004dfa80c78caf80e8b525e5c  dist/ipython-6.4.0.tar.gz
```

**Comment by takluyver** [comment]
:+1: Sounds like a good plan. Let me know if I can help. I'm also hoping to cut notebook 5.5 today or tomorrow.

**Comment by Carreau** [comment]
Ok, a bit late to do the release, doing that now.

**Comment by takluyver** [comment]
The conda-forge PRs were merged, so closing this.
