### ISSUE TITLE
Can I run a script and stop as I need to debug it?

### ISSUE THREAD

**Issue by mttbx** [ipython/ipython#11115]
Hi,
   Is there any work around?

**Comment by takluyver** [comment]
See the [%debug magic](http://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-debug) and the `-d` option for the [%run magic](http://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-run).

**Comment by mttbx** [comment]
I mean the program is running without exception, and when I hit some keys, it can stop and let me debug.

**Comment by mttbx** [comment]
thanks
