### ISSUE TITLE
code executes without error in ipython but not in normal python console!

### ISSUE THREAD

**Issue by Khalilsqu** [ipython/ipython#11122]
Hi, wich you are doing all well

I created some codes originally in Jupiter notebook and I can run them with successful outputs. The same scripts files run without errors as well in spyder ide since it uses ipython console to execute its scripts files.

The problem is when I execute the same script in normal python console using either VSC or sublime 3, I do not get the same output. 

The scripts read some data and I modify them visually using matplotlib interactive event handling and picking routines.  The output data are retrieved correctly when using ipython or spyder but not normal python console.

Do you have any idea why I am getting this behavior. Does ipython kernel uses a different matplotlib backend than normal python console?

Platform: windows 10
python: anaconda: python 3.6.5

**Comment by takluyver** [comment]
You can choose which backend you use; IPython adds an 'inline' backend which makes plots show up in the notebook. But that doesn't have any event handling, so you're probably not using that. Otherwise, it should be using your default matplotlib backend.

**Comment by Khalilsqu** [comment]
@takluyver  Thank you for your replay, Really appreciate it.

 I can use notebook backend to show plots in the notebook and make interactive event handling. I also can show the figure in jupyter notebook or either spyder in a separate window. 

Does the matplotlib backend has any effect on the data format of numpy arrays after modifying them with matplotlib event picking routines. I am not quite familiar  what exactly backend is!?. Cannot find a reason why my scripts run without errors while using jupyter or spyder but never works with VSC or sublime3.

**Comment by takluyver** [comment]
I think it shouldn't affect the format of the array, but it's possible that something works a bit differently in the notebook backend. You'd probably have to ask the matplotlib developers.

**Comment by Khalilsqu** [comment]
@takluyver Thank you for you time, I will investigate further. I appreciate your help. 

regards
