### ISSUE TITLE
No such directory

### ISSUE THREAD

**Issue by kelvinwop** [ipython/ipython#11138]
![image](https://user-images.githubusercontent.com/30770221/40092227-d9100322-5881-11e8-9224-34aa58721cbb.png)

It is worth noting that the directory mentioned is not the directory I am in:
`http://localhost:8888/tree/OneDrive/Documents/Jupyter%20Notebooks` is the url
`/OneDrive/Documents/Jupyter%%20Notebooks` in the prompt

Additionally anaconda prompt error:  `404 POST /api/contents/OneDrive/Documents/Jupyter%2520Notebooks (::1) 22.06ms referer=http://localhost:8888/tree/OneDrive/Documents/Jupyter%20Notebooks`

the dummy %2520 thing
![image](https://user-images.githubusercontent.com/30770221/40092304-42bbbe1a-5882-11e8-983e-086b8e1a45b7.png)

seems like an error parsing the path
¯\\\_(ツ)\_/¯

**Comment by kelvinwop** [comment]
Additional information:

As I suspect, I can create a new file if the folder does not have a space in it.

Hilariously, I created a notebook in the folder with a space when I first launched jupyter. This leads me to believe that upon reopening the directory causes some sort of change that makes this sort of thing happen.

OS: 
![image](https://user-images.githubusercontent.com/30770221/40092406-d983cfea-5882-11e8-8ec9-99ffb4cd20cd.png)

**Comment by Carreau** [comment]
That is strange, 

Can you try updating the notebook package in anaconda and re-try ? The followin should do the trick:

```
conda upgrade notebook
```

the `%-thing` is indead weird, `%20` is Space, so `%%20` in the prompt should not happened.

Note that this is not an IPython issue but a https://github.com/jupyter/notebook one, you may find more informations there. 

Is `OneDrive` a synchronized folder ? If so can you try on a non-synchronised folder ?

**Comment by kelvinwop** [comment]
Oh yeah, it worked in `tree/OneDrive/Documents` but not in `tree/OneDrive/Documents/Jupyter%20Notebooks`

**Comment by abhishekbajpayee** [comment]
@kelvinwop did you end up figuring this out? I recently ran into the exact same issue too.

**Comment by kelvinwop** [comment]
I think I ended up just removing spaces from the folders

**Comment by BryceHaley** [comment]
I had this issue just now. Not sure why it popped up today but Carreau's advice of running 

`conda upgrade notebook`

fixed it.
