### ISSUE TITLE
.ipy: Exit status from missing ! executable

### ISSUE THREAD

**Issue by techtonik** [ipython/ipython#11144]
Is it possible to read exit status from command in `.ipy` script for error reporting?
```
#!/usr/bin/env ipython

res = !mediainfo
```
From this output I can only see `SList` object with text about missing command that is too specific for underlying shell to parse. Is it possible to store exit status there somehow?

**Comment by takluyver** [comment]
It sticks a variable `_exit_code` in the namespace.

**Comment by techtonik** [comment]
Is that documented somewhere?

**Comment by techtonik** [comment]
@takluyver and it doesn't work
```
~ ipython runnypy.ipy
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-7431c5cc9ed3> in <module>()
      2 
      3 res = get_ipython().getoutput(u'mediainfo')
----> 4 print(_exit_code)
      5 

NameError: name '_exit_code' is not defined
```

`runnypy.ipy`:
```
#!/usr/bin/env ipython

res = !mediainfo
print(_exit_code)
```

**Comment by takluyver** [comment]
Looks like it's only for `!foo`, not `res = !foo`.

I'd suggest switching to a more pythonic way of running the command, like [subprocess.run()](https://docs.python.org/3/library/subprocess.html#subprocess.run).

**Comment by techtonik** [comment]
@takluyver yep, `!mediainfo` works in script context too.
