### ISSUE TITLE
Drop 3.4 ?

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#11157]
With Min's recent resurrection of async REPL in https://github.com/ipython/ipykernel/pull/323 and https://github.com/ipython/ipython/pull/11155 I'm wondering if it would be a good idea to drop 3.4

3.7 is out soon, so we would be supporting still 3 minor Python versions.

**Comment by minrk** [comment]
3.3 is EOL, so it seems appropriate to drop 3.3 in order to make dealing with async stuff more manageable.

**Comment by Carreau** [comment]
Sorry I meant 3.4 I mistyped.

**Comment by minrk** [comment]
Ah. I think it might be a little premature to drop 3.4 support for IPython itself, but let's see how it goes with `@gen.coroutine` and `yield from`.

**Comment by MrMino** [comment]
We no longer support 3.4.
