### ISSUE TITLE
i can't see codes in jupyter notebook

### ISSUE THREAD

**Issue by omar170** [ipython/ipython#11150]
![default](https://user-images.githubusercontent.com/39484358/40302433-c0e084e6-5cf7-11e8-80fd-adf0c01e9494.PNG)

**Comment by takluyver** [comment]
If your browser language is set to Arabic or Hebrew, we currently trigger right-to-left layout automatically. You can toggle it in the command palette (Ctrl-Shift-F, then search for rtl), but you'll have to do it each time.

@samarsultan we've had a number of issues opened about this. I guess a lot of people who speak Arabic/Hebrew are used to interfaces written in English being displayed left-to-right? Is it worth disabling RTL by default, at least until there are translations for these languages?

**Comment by omar170** [comment]
it fixed 

thank you
