### ISSUE TITLE
Ipython crashes for "foo = function?" for any foo and function, whereas "function?" works fine.

### ISSUE THREAD

**Issue by oscartackstrom** [ipython/ipython#11152]
The following crashes:
> In [1]: a = min?
> Docstring:
> min(iterable, *[, default=obj, key=func]) -> value
> min(arg1, arg2, *args, *[, key=func]) -> value
> 
> With a single iterable argument, return its smallest item. The
> default keyword-only argument specifies an object to return if
> the provided iterable is empty.
> With two or more arguments, return the smallest argument.
> Type:      builtin_function_or_method
> 
> In [2]: a = min?                                                                                                       
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 658, in launch_instance
>     app.start()
>   File "/usr/lib/python3/dist-packages/IPython/terminal/ipapp.py", line 348, in start
>     self.shell.mainloop()
>   File "/usr/lib/python3/dist-packages/IPython/terminal/interactiveshell.py", line 440, in mainloop
>     self.interact()
>   File "/usr/lib/python3/dist-packages/IPython/terminal/interactiveshell.py", line 423, in interact
>     code = self.prompt_for_code()
>   File "/usr/lib/python3/dist-packages/IPython/terminal/interactiveshell.py", line 333, in prompt_for_code
>     pre_run=self.pre_prompt, reset_current_buffer=True)
>   File "/usr/lib/python3/dist-packages/prompt_toolkit/interface.py", line 408, in run
>     self._pre_run(pre_run)
>   File "/usr/lib/python3/dist-packages/prompt_toolkit/interface.py", line 383, in _pre_run
>     pre_run()
>   File "/usr/lib/python3/dist-packages/IPython/terminal/interactiveshell.py", line 410, in pre_prompt
>     self.pt_cli.application.buffer.text = cast_unicode_py2(self.rl_next_input)
>   File "/usr/lib/python3/dist-packages/prompt_toolkit/buffer.py", line 372, in text
>     assert self.cursor_position <= len(value)
> AssertionError

whereas this works:
> In [1]: min?

**Comment by Carreau** [comment]
Which version of prompt_toolkit ? This was a common but should have been fixed now.

**Comment by takluyver** [comment]
It looks like you've got ipython through apt, going by the paths. We don't
recommend that, because the apt packages are almost always out of date, and
we can't update them ourselves. It's best to install it with pip or conda,
either of which can get you a recent version.
