### ISSUE TITLE
Can I capture rich outputs in plain python sessions ?

### ISSUE THREAD

**Issue by mwouts** [ipython/ipython#11163]
I would like to capture rich outputs (images, javascript, etc). For this I know I can use IPython.utils.capture. It works well inside jupyter notebooks. Should it also work in plain python ?

For now the script below says
* `Output #1 has data types text/plain (43b), image/png (3294b)` when executed in a jupyter notebook
* `No output captured` when run in a python interactive shell (and the plot is displayed instead of being captured)

Could you please indicate how I could change the script below to get it to work with plain python ? Thanks

```
from IPython.utils import capture

def describe_capture(cap):
    if len(cap.outputs)==0:
        print('No output captured')
    else:
        for i, o in enumerate(cap.outputs):
            types = ['{} ({}b)'.format(t, len(content)) for t, content in o.data.items()]            
            print('Output #{} has data types {}'.format(i+1, ', '.join(types)))

import pandas as pd
import matplotlib.pyplot as plt

with capture.capture_output() as cap:
    df = pd.DataFrame({'a':[1,2,3], 'b':[5,4,6]})
    df.plot(kind='bar')
    plt.show()
    
describe_capture(cap)
```

**Comment by takluyver** [comment]
It's not really intended to work in a plain Python environment,  because Python doesn't really have any concept of rich output by itself. You'd have to dig into the code to figure out how rich output capture works, how the inline backend for matplotlib works, and enable them both.

**Comment by mwouts** [comment]
Ok thanks, I see. I did some research, and I learnt that changing the backend to jupyter's one is done with
```
import matplotlib
matplotlib.use('module://ipykernel.pylab.backend_inline')
```
Then the above script (in plain python) does capture something, but only... the text representation of the plot, which is not very useful yet. I guess that's what you meant when you said that I would have to enable the rich output capture as well (any further clue is welcome !)

Finally, I quoted matplotlib, but I am actually interested in intercepting rich displays of images and pdf (and also javascript, json, etc), not only matplotlib plots. Say, for instance:
```
from IPython.utils import capture
from IPython.display import Image, display

with capture.capture_output() as cap:
    display(Image(filename='image.png'))
```
or even
```
from IPython.utils import capture
import plotly

with capture.capture_output() as cap:
    plotly.offline.iplot([plotly.graph_objs.Bar(y=[2,1,3])])
```
In this setting, capture works both in jupyter and ipython terminal (already better than the matplotlib example), but not in the plain python terminal. Do you expect the capture would be easier to configure in one of these examples ?

**Comment by takluyver** [comment]
Here's the code that captures rich outputs:

https://github.com/ipython/ipython/blob/2284ccfeed23cb6f83a2103f7e485bd9b9d10812/IPython/utils/capture.py#L155-L160

I think the `display()` function also assumes that it's run inside IPython, and gets a reference to the IPython shell object. But that would be the place to start digging.

**Comment by takluyver** [comment]
You might be able to make it work by instantiating an InteractiveShell object so that this machinery thinks it's inside IPython. But instantiating an InteractiveShell may do a bunch of other stuff that you don't want.

**Comment by mwouts** [comment]
Thanks @takluyver. That was very helpful. Indeed the capture relies on the shell, obtained with `get_ipython`, which is `None` unless I execute:
```
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell().instance()
```
With this, the capture of rich outputs created with `display` work in plain python. I have [tested](https://github.com/mwouts/notebooks/blob/master/reticulate%20and%20capture.Rmd) it with png images, plotly javascript and json rich outputs. For matplotlib plots however I do get the side effects you  mentioned, probably because mpl does not rely exclusively on rich outputs. Anyway I think I got sufficient coverage for now, so I'm closing this issue. Thank you a lot !

**Comment by YahavFes** [comment]
@mwouts 
I encountered in similar problem, and I would like to get some help:
I have python file that has the function foo().
```
def foo():
  from IPython.utils import io
  with io.capture_output() as captured:
     display(Javascript('element.text(IPython.notebook.get_selected_index())'))
  print(captured.stdout)
```
And I call this function from jupyter notebook cell.
my goal is to capture the stdout in a python's variable.
The problem is that captured.stdout remains empty (although if I execute the display command outside the captured scope I see the correct output in the jupyter notebook cell).
I tried execute the interactiveShell that we suggested above, but It didn't help.

**Comment by mwouts** [comment]
Hello @YahavFes , I have used `capture` rather than `io`, and I don't know about `stdout` in that context. Still I gave a try to your example, and the capture does capture the javascript snippet - but not the result of its execution, which I think is what you wanted. 

![image](https://user-images.githubusercontent.com/29915202/60215981-29b18a80-9869-11e9-8486-5972989fb117.png)

I am not an expert on this, but I think that if you want to make Python aware of the result of a computation done in Javascript, then you could send it back to Python from the Javascript side by using something like `kernel.execute`, like [here](https://jakevdp.github.io/blog/2013/06/01/ipython-notebook-javascript-python-communication/).
