### ISSUE TITLE
IPython shell Unicode display problem looking for help

### ISSUE THREAD

**Issue by zhenjiwang16** [ipython/ipython#11165]
hi all,
I met a chinese character display problem at the beginning use IPython for pandas lib. 
Python 2.7.14rc1 (v2.7.14rc1:c707893, Aug 26 2017, 23:59:08)
IPython 5.7.0 -- An enhanced Interactive Python.
----------------------------------------
In [1]: from pandas import Series
In [2]: data = {1:u"硬卧", 2:u"软卧"}
In [3]: s1 = Series(data)
In [4]: s1
Out[4]:
1    Ӳ��
2    ����
dtype: object
-----------------------------------------
I tried some solutions without solving：
1、this will not happen in IPython notebook and windows shell and otherIDE;
2、write the code: # --*-- coding:utf-8 --*--

**Comment by takluyver** [comment]
Please use Python 3 if at all possible - unicode handling is one of the main improvements from Python 2 to 3. Python 2 is reaching its end of official support in a couple more years, and I'm not interested in trying to fix py2+unicode bugs.

**Comment by zhenjiwang16** [comment]
Thank you for the Official statement, This problem has troubled me all day。
