### ISSUE TITLE
Incompatibility with prompt-toolkit 2.0

### ISSUE THREAD

**Issue by utkonos** [ipython/ipython#11179]
The newest version of prompt-toolkit, 2.x is not compatible with version 1.x. This is a problem with IPython/terminal/interactiveshell.py line 22's imports no longer work.

There is info about upgrading code to 2.x: https://python-prompt-toolkit.readthedocs.io/en/stable/pages/upgrading.html

Here is the current traceback from this problem (reported during Jupyter kernel loading).

https://gist.github.com/utkonos/1f844cfb86e914d82624bb5e196d69d2

**Comment by takluyver** [comment]
See #11177

**Comment by Carreau** [comment]
Closing as #11177 was merged.
