### ISSUE TITLE
IPython 6.4.0 hangs up the whole system when timing simple collections.deque insertion

### ISSUE THREAD

**Issue by RomanPerekhrest** [ipython/ipython#11187]
IPython 6.4.0 hangs up  the whole system for hour(s) when timing simple `collections.deque` insertion operation.
Crucial history:

```
In [189]: l = list(range(1000000))

In [190]: import collections

In [191]: q = collections.deque(range(1000000))

In [192]: %timeit l.insert(0, 0.1)
1.53 ms ± 34.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [193]: %timeit q.appendleft(0.1)
The slowest run took 152.92 times longer than the fastest. This could mean that an intermediate result is being cached.
3.24 µs ± 6.99 µs per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```
Input line `193` can take for hour(s) to perform.

-----

Technical details:

```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.
```

OS:
```
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```
`lshw` info:

```
     *-memory
          description: System memory
          physical id: 1
          size: 2248MiB
     *-cpu
          product: Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz
          vendor: Intel Corp.
          physical id: 2
          bus info: cpu@0
          width: 64 bits
```

**Comment by takluyver** [comment]
Have you tried it using the Python [timeit module](https://docs.python.org/3/library/timeit.html) directly?  Have you monitored memory use as it does this? `7 runs, 10000000 loops each` means you're adding 70 million elements to the deque, which is probably enough to fill up your memory.

Because `list.insert()` is slower, it runs that fewer times, so it won't take up as much memory.

**Comment by takluyver** [comment]
The starting size of the deque doesn't make much difference - it's all the things that are being added to it while doing the timing. Maybe you want to use a deque with maxlen set? `q = collections.deque(range(100), maxlen=100)` This will limit the size, so every time you add something to it, something is dropped from the other end.

**Comment by RomanPerekhrest** [comment]
Exactly, that's the crucial param for such deque case. Missed that parameter. Thanks.
