### ISSUE TITLE
refusing to set env var with whitespace

### ISSUE THREAD

**Issue by evan-burke** [ipython/ipython#11184]
I'm attempting to use the %env magic command to set an environment variable value to a Windows path which contains spaces, e.g.:

`%env var GOOGLE_APPLICATION_CREDENTIALS="C:/Folder Name/gcp_creds.json"
`

This generates an error due to the the whitespace, presumably from here: 
https://github.com/ipython/ipython/blob/master/IPython/core/magics/osm.py#L427

I see from the comments that this appears to be a sanity check, but in my case the whitespace is entirely intended (and works fine when setting using os.environ['NAME'] = value). 

As the workaround is fairly easy, I'm not too worried about a fix, but thought I'd bring it to your attention anyway in case this scenario is common. 

Thanks for all your work on ipython!

**Comment by Carreau** [comment]
Thanks, we likely need to detect proper quoting.

**Comment by takluyver** [comment]
N.B. You shouldn't put the `var` in there. Does it work like this?

```
%env GOOGLE_APPLICATION_CREDENTIALS="C:/Folder Name/gcp_creds.json"
```

**Comment by evan-burke** [comment]
Ah thanks, good catch, sorry about that. Dropping the 'var' resolves the whitespace error. 

I am seeing that the %env command requires the value to be unquoted, otherwise quotes are included in the value - so these two commands are equivalent: 
`%env GOOGLE_APPLICATION_CREDENTIALS=C:/Folder Name/gcp_creds.json`
`os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = "C:/Folder Name/gcp_creds.json"`

The former doesn't match usual quoting behavior in Python, which tripped me up, and I could see that affecting others as well. Stripping enclosing quotes if present is an easy thing to do, but I'm not sure if there are existing use cases which would be broken by that - thoughts?

**Comment by Carreau** [comment]
> Stripping enclosing quotes if present is an easy thing to do, but I'm not sure if there are existing use cases which would be broken by that - thoughts?

If the functionality was new, I would say yes, but it has been around for a long time, and there are more chances to break use code now if we change the actual behavior. SO I would leave it as is.

**Comment by evan-burke** [comment]
Makes sense. Thanks!
