### ISSUE TITLE
Script (e.g. Bash) magics doesn't have an error on status code

### ISSUE THREAD

**Issue by MSeal** [ipython/ipython#11198]
I ran into a use-case where I wanted to call a small bash script magic in a notebook, but couldn't halt execution easily based on exit status.

======= Cell 1 =======
```
%%bash
not_a_valid_command
```

======= Cell 2 =======
```
print("I don't want to run this if the bash command didn't return status code 0")
```

It seems like the [script magics](https://ipython.readthedocs.io/en/stable/interactive/magics.html) and the [code](https://github.com/ipython/ipython/blob/ec3d1a11bf26a0962cb2cf55ba263b12ac023183/IPython/core/magics/script.py#L63) don't have any options to inform the subprocess to error on non-zero status code. This would be nice to be configurable and/or defaulted.

**Comment by MSeal** [comment]
I've been having a lot of feedback from other users at my company who get frustrated that this isn't the default behavior (both for `%%script` and `!` patterns). For example `!pip install -U package-that-does-not-exist` will not halt execution, but this is a common pattern that cannot assume success to continue execution.

How disruptive would it be if we changed the default behavior to raise an error for nonzero exit codes by default?

**Comment by MSeal** [comment]
@Carreau thoughts on this topic?

**Comment by Carreau** [comment]
Thanks for pinging me. 
I think that make sens for consistency. It would be relatively easy to add a configuration option to change the behavior. 

Would that be ok only for the next major version ? 

Note that it should be relatively easy to backport as a custom package/extension for IPYthon, where you can just overwrite magics, if you want to have it on earlier versions.

**Comment by MSeal** [comment]
Ok let me see if I can make a PR to change the default behavior to make use of this for the 7.0 milestone.
