### ISSUE TITLE
Magic functions with a number inside brackets incorrect

### ISSUE THREAD

**Issue by colinc719** [ipython/ipython#11195]
When running a magic function that has an argument within brackets, it will remove the brackets.  For instance:

```
In [1]: def return_arg(arg):
            return arg

In [2]: %time return_arg('{8}')
CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.2 µs
Out[2]: '8'
```
instead of the expected output of
```
'{8}'
```
Having something other than a number within the brackets appears to work correctly:

```
In [3]: %time return_arg('{a8}')
CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.44 µs
Out[3]: '{a8}'
```
I'm running ipython version 6.4.0 and readline version 6.2-2.

**Comment by takluyver** [comment]
Magics have a kind of string formatting applied so that you can interpolate Python variables into the arguments. Not really needed for `%time`, but it applies to all magics.

To type literal `{}`, double them up, like `{{8}}`.

**Comment by Carreau** [comment]
Closing as behaving as expected. 
Thanks.
