### ISSUE TITLE
filterwarnings('error') disables tab completition

### ISSUE THREAD

**Issue by Teagum** [ipython/ipython#11196]
Setting `warnings.filterwarnings('error')` disables tab completition in Jupyter notebook. Resetting `warnings.filterwarnings('default')` reenables tab completition.

I am running:
▶ jupyter --version
4.4.0

▶ jupyter notebook --version
5.2.1

▶ ipython --version
6.4.0

The kernel issus the following error after pressing [TAB] if `warnings.filterwarnings('error')` is set:

> [IPKernelApp] ERROR | Exception in message handler:
> Traceback (most recent call last):
>   File "/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
>     handler(stream, idents, msg)
>   File "/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 434, in complete_request
>     matches = self.do_complete(code, cursor_pos)
>   File "/usr/local/anaconda3/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 257, in do_complete
>     txt, matches = self.shell.complete('', line, line_cursor)
>   File "/usr/local/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2032, in complete
>     return self.Completer.complete(text, line, cursor_pos)
>   File "/usr/local/anaconda3/lib/python3.6/site-packages/IPython/core/completer.py", line 1943, in complete
>     PendingDeprecationWarning)
> PendingDeprecationWarning: `Completer.complete` is pending deprecation since IPython 6.0 and will be replaced by `Completer.completions`.

**Comment by Carreau** [comment]
Yes, when you turn warning into errors, things emitting warnings will raise errors.
So any IPython functionality that use deprecated functionality will stop working. You need to use more advance warning filtering techniques for example add the following to make sure critical functionality still work:

```
warnings.filterwarnings('ignore', message='.*Completer.complete.*',
                            category=PendingDeprecationWarning, module='.*')
```

Closing as this work as expected.
