### ISSUE TITLE
Error in documentation for `ipython` %%timeit magic

### ISSUE THREAD

**Issue by alphaCTzo7G** [ipython/ipython#11193]
It seems there is a error in the `%%timeit` magic function. The default value of `-r<R>` is set to 3, while the actual value is 7: https://github.com/ipython/ipython/blob/ec3d1a11bf26a0962cb2cf55ba263b12ac023183/IPython/core/magics/execution.py#L968

The actual value as shown on this line: https://github.com/ipython/ipython/blob/ec3d1a11bf26a0962cb2cf55ba263b12ac023183/IPython/core/magics/execution.py#L1021

is 7. 

When I run `%timeit -n1 print(1)`, it prints out 1, 7 times not 3.

I created a PR here: https://github.com/ipython/ipython/pull/11192

**Comment by MrMino** [comment]
The aforementioned PR has been merged in 7.0 - closing.
