### ISSUE TITLE
IPython3lexer misses f-string prefixes

### ISSUE THREAD

**Issue by t-makaro** [ipython/ipython#11203]
'u','b','r','rb','br' (and their capitalized variants) are parsed by the IPython 3 lexer as ```Token.Literal.String.Affix```.

'f','rf','fr' (and their capitalized variants) are parsed as ```Token.Name```.

To reproduce:
```
from IPython.lib.lexer import IPython3lexer
lexer = IPython3lexer()

code1 = 'f"str"'
code2 = 'r"str"'
print(list(lexer.get_tokens(code1)))
print(list(lexer.get_tokens(code2)))
```
code2 tokenizes fine, but code 1 tokenizes wrongly.

**Comment by t-makaro** [comment]
I believe this is a pygments issue, so I opened it there. https://bitbucket.org/birkenfeld/pygments-main/issues/1452/python-36-f-string-prefix-not-recognized

**Comment by takluyver** [comment]
I think you're right, so I'll close this issue.

Unfortunately I think @birkenfeld is a bit overwhelmed on pygments maintenance; there are a lot of PRs and not many recent commits. Maintaining lexers for every language out there is a pretty herculean task. I don't know if there's some way we can help him out with that.

**Comment by t-makaro** [comment]
That's a shame. I've been trying to work on a pygments theme that matches jupyter notebook for syntax highlighting, but there are lots of limitations in the python lexer that I'm encountering. Particularly the lack of information regarding operators. I really need an ```Operator.Assignment``` token for things like ```=, +=, /=…``` since the notebook doesn't highlight these operators as it does for others.

**Comment by takluyver** [comment]
Pygments lets you [define your own lexers](http://pygments.org/docs/lexerdevelopment/) - that may be the easiest way to do what you want. You could start by copying the existing Python lexer (preserving the license from pygments alongside it, of course) and modify that.

**Comment by t-makaro** [comment]
Well, I'd need the IPython lexer to use the modified python lexer.  I know that I need to write a new preprocessor for nbconvert to use the pygments style; I'd also need to get nbconvert to use the new lexer.
