### ISSUE TITLE
Python 3 + Django = UnicodeError

### ISSUE THREAD

**Issue by im-n1** [ipython/ipython#11208]
I keep getting unicode error on each Django model I want to print out - or even set of models.

I use Python 3.6 and Ipython 6.4.0
Here my result:

![image](https://user-images.githubusercontent.com/198654/42036805-ebf0710c-7ae6-11e8-93c3-f420e2c6edef.png)

Using plain Python 3 interpreter everything works.

**Comment by Carreau** [comment]
Can you dove a copy-past-able full example ?

**Comment by grafa** [comment]
I guess you can rewrite the first line of my screenshot.
Also It doesn't matter which model from Django I use.

**Comment by takluyver** [comment]
That's not much help for reproducing it if we don't have a Django project handy and don't use Django regularly.

But in this case, I suspect the Django model is irrelevant. You can probably get the same error with `print('\xe1')`. Something in your environment is telling Python that the terminal only supports ascii, and so it can't print any character apart from ASCII.

**Comment by grafa** [comment]
Unfortunately I can't share the whole project but I can definitely try the print when I get to pc.

Maybe I should also mention I use Docker, so the whole py dev inc. the project sits inside docker container while I run something like `docker run -it bash`. Maybe it helps.

I will follow any steps you guys suggest. Not as good as share the project but I guess we can break it down.

**Comment by takluyver** [comment]
I would guess the locale is not set inside the docker container - try running `locale` in bash to check. You probably want the values to look something like `cs_CZ.UTF-8`.

**Comment by grafa** [comment]
Yup, the `print('\xe1')` snippet also thrown the excetpion.

```
root@1a9a67dd80ef:/# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

I guess that's bad, right? :)

**Comment by takluyver** [comment]
In Python, check those environment variables, along with `sys.stdout.encoding` and `locale.getpreferredencoding()`.

**Comment by grafa** [comment]
```
In [4]: sys.stdout.encoding
Out[4]: 'ANSI_X3.4-1968'

In [5]: import locale

In [6]: locale.getpreferredencoding()
Out[6]: 'ANSI_X3.4-1968'
```

**Comment by methane** [comment]
Use `PYTHONIOENCODING=utf_8`.
From Python 3.7, PEP 538 will help you.

**Comment by methane** [comment]
```
root@5111eb5cdf7e:/# locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
```

Your LANG environment variable is bad.  Your system don't have `en_US.UTF-8` locale.
You can list what locale you can use by `locale -a | grep -i utf`

**Comment by MrMino** [comment]
Given the plethora of good answers above, I'm considering this issue solved. If it's not - don't hesitate to ping us, we'll reopen.
