### ISSUE TITLE
custom.js mathjax macros not working on file open

### ISSUE THREAD

**Issue by waynemystir** [ipython/ipython#11205]
I have added custom.js to ~./jupyter/custom. And here's the beginning of the mathjax config section of my custom.js file:

MathJax.Hub.Config({
    "tex2jax": {
        inlineMath: [ ["$","$"], ["\\(","\\)"] ],
        displayMath: [ ["$$","$$"], ["\\[","\\]"] ],
        processEscapes: true,
    },  
    "displayAlign": "center",
    "extensions": ["tex2jax.js","TeX/AMSmath.js","TeX/AMSsymbols.js","TeX/color.js","TeX/cancel.js"],
    "TeX": {
        Macros: {
            wes: "\\blacksquare",
            qes: "\\frac{1}{8}",
            qd: "\\quad",
            dq: "\\quad\\quad",
            norm: ["{\\lvert#1\\rvert}", 1], 

When I open a notebook that uses these macros, the notebook doesn't appear to recognize these macros:

<img width="1044" alt="screen shot 2018-06-25 at 1 56 49 pm" src="https://user-images.githubusercontent.com/2120096/41867341-dfe72530-7880-11e8-8c30-2bbe1e03d26d.png">

But when I refresh the page, the macros are usually recognized and presented as expected. Is there something I can do to get Notebook to recognize the Mathjax macros when a file is opened?

**Comment by takluyver** [comment]
Closing in favour of https://github.com/jupyter/notebook/issues/3715
