### ISSUE TITLE
IPython.utils.signatures backport for Python 2 is deprecated in IPython 6, which only supports Python 3

### ISSUE THREAD

**Issue by jakirkham** [ipython/ipython#11206]
Getting a `DeprecationWarning` in `ipython`, which appears to be issued by `ipython`. Points to [this line]( https://github.com/ipython/ipython/blob/6.4.0/IPython/lib/pretty.py#L91 ) as problematic. Warning included below. Should add this showed up when running under Python 3.

```python
/opt/conda3/lib/python3.6/site-packages/IPython/lib/pretty.py:91: DeprecationWarning: IPython.utils.signatures backport for Python 2 is deprecated in IPython 6, which only supports Python 3
  from IPython.utils.signatures import signature
```

**Comment by Carreau** [comment]
Thanks ! Making that as easy for a first issue if anyone would like to contribute.

**Comment by pulkitmaloo** [comment]
I'd like to help with this issue. Can you explain in more detail what needs to be done?

**Comment by jakirkham** [comment]
My guess is that this `import` would be replaced with [`import`ing the relevant `inspect` function]( https://github.com/ipython/ipython/blob/6.4.0/IPython/utils/signatures.py#L11 ).
