### ISSUE TITLE
IPython 6.1.0 can't get cell content on for pre_run_cell event

### ISSUE THREAD

**Issue by alanbraz** [ipython/ipython#11213]
Running...

```
def pre_run_cell(self, info):
        print('Cell code: "%s"' % info.raw_cell)
```

I am getting `missing 1 required positional argument: 'info'` in a notebook with v6.1.0 of IPython while works fine running the same code using v6.4.0

Any idea to help?

**Comment by takluyver** [comment]
The argument was only added in version 6.3: https://github.com/ipython/ipython/pull/10795
