### ISSUE TITLE
magic command '%run' works `.py` file as a script or a model?

### ISSUE THREAD

**Issue by kenanai** [ipython/ipython#11225]
I have a question about the `%run` command in IPython.
This is an example.
a test python file `registration.py`

```Python
registry = []

def register(func):
    print('running register(%s)' % func)
    registry.append(func)
    return func

@register
def f1():
    print('running f1()')

@register
def f2():
    print('running f2()')

def main():
    print('running main()')
    print('registry ->', registry)
    f1()
    f2()

if __name__ == '__mian__':
    main()
```
Ok, then I use `%run` in ipython and I find the output is 
```
In [4]: %run registration.py
running register(<function f1 at 0x00000219CCC6BF28>)
running register(<function f2 at 0x00000219CCC6BEA0>)
```
and this result may not i want because when i use `import registration` I find they are samed.
```
In [5]: import registration
running register(<function f1 at 0x00000219CC5EBD90>)
running register(<function f2 at 0x00000219CCBD99D8>)
```
So if the `%run` run a python file not as a script but import it as a model.
And we know just run this file like a script the function `main()` will be called.

**Comment by takluyver** [comment]
`if __name__ == '__mian__':` - you've misspelled `__main__`, which might be causing confusion.

`%run` is kind of inbetween; it runs the module in its own namespace, but tells it that it is `__main__`. Then when it finishes running, it copies the variables into your interactive namespace.

**Comment by kenanai** [comment]
Sorry, I had a spelling mistake `__main__`. I changed this mistake and get my result. 

That is to say, in the IPython session environment, all files can be executed as a script by the `%run` command, and the variables in the file will then be imported into the current namespace. That is, for a module file, the effect that I use `%run` commands to this file  is the same as `from module import *` unless the file defines  main function (`if __name__  == '__main__': `), and the main function will be executed in this case.

OK, may be I understand that. Thank you for your help.
