### ISSUE TITLE
Syntax error from debug command with multiline function call

### ISSUE THREAD

**Issue by abramclark** [ipython/ipython#11223]
```$ ipython
Python 3.6.4 (default, Dec 27 2017, 20:19:53)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: def foo(a): print(a)

In [2]: foo(
   ...:   10
   ...: )
10

In [3]: debug foo(
   ...:   10
   ...: )
  File "<ipython-input-3-83f764d45ad3>", line 1
    debug foo(
            ^
SyntaxError: invalid syntax
```
This might be trickier than the `debug print('foo bar')` issue, but shouldn't the special command parsing in this case simply remove the first word then parse the remainder as Python?

**Comment by Carreau** [comment]
Hi there, thanks for you bug report. 

`debug` is a magic, and magics apply on strings not necessarily python code. There is then nothing smart about trying to debug multi line statement. 

In _some_ case we manage to detect that bare statement are magic, but we recommend to always use `%debug` (single line), or `%%debug` all cells.

In your `In[3]` the IPython parser cannot figure out that debug is a magic, and even though would apply it only to the line on which debug is. That is to say:

```
get_ipython().magic('debug', 'foo(')
    10
)
```

Which is invalid syntax.

You can force the evaluation of a multiline magic with `%%`

```
In [3]: %%debug
   ...: foo(
   ...:    10
   ...: )
```

With `%%debug` on its own line. Which  will work.

**Comment by Carreau** [comment]
Closing, but feel free to reopen (or ask for reopening)
