### ISSUE TITLE
 MAC os import Proxies Exception

### ISSUE THREAD

**Issue by WangWenQiang** [ipython/ipython#11239]
from Proxies import Proxies
Proxies(Version=1.6)
ipython(Version=6.4.0)
MAC OS

Exception && exit

detail:
```
versions/3.6.1/lib/python3.6/selectors.py", line 539, in register
    kev = select.kevent(key.fd, select.KQ_FILTER_READ,
AttributeError: module 'select' has no attribute 'kevent'
```

**Comment by Carreau** [comment]
Yes, this seem to be an issue with the proxies library, 

> why not catch errors like this, it makes me feel not so good about breakdown when the error happened

We could catch the error, but then do what ? We already prevent IPython to crash and exit, and display the error, there is not much more we can do.

Closing as there is likely nothing to do on our side, but we can reopen if necessary.
