### ISSUE TITLE
ipython --quick throws a segmentation fault

### ISSUE THREAD

**Issue by aweinstein** [ipython/ipython#11230]
Running `ipython --quick` throws a segmentation fault:
```
$ ipython --quick
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.
Segmentation fault
```
I'm running IPython 3.6.4, from a fresh Anaconda 5.2.0 installation, in a Linux Mint 18.1 machine.

**Comment by aweinstein** [comment]
I installed anaconda from scratch, and I don't get the segmentation fault anymore. 

But now I get `QApplication: invalid style override passed, ignoring it.` after running either `%matplotlib qt5` or `import matplotlib.pyplot as plt`.

**Comment by Carreau** [comment]
The segfault cannot come from IPython itself. Seeing that you see Qt Error message it is likely related to another library. matplotlib ? Do you have any specific IPython/Matplotlib configuration ?

**Comment by Carreau** [comment]
Up to you, let us know if you need any further help to debug.
