### ISSUE TITLE
Uncaught exception in ZMQStream callback - ValueError: signal only works in main thread

### ISSUE THREAD

**Issue by louwers** [ipython/ipython#11258]
```
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "/usr/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "/usr/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

After installing the newest versions of all Jupyter's dependencies, the notebook server crashes with multiple times this message whenever I try to run anything. Running 5.3.0 so it might be fixed as of now.

Edit: #11026 looks somewhat similar.

**Comment by Carreau** [comment]
That is most likely relevant to https://github.com/ipython/ipykernel, let's see if we can migrate it there. 

@meeseeksdev migrate to ipython/ipykernel

**Comment by Carreau** [comment]
@meeseeksdev migrate to ipython/ipykernel

**Comment by femiaiyeku** [comment]
Upgrading ipykernel worked for me
conda upgrade ipykernel

**Comment by n8vm** [comment]
I am still having this issue with the latest version of IPython. 

I mentioned it in the thread mentioned by @meeseeksdev[bot] , but just for visibility: 

I'm running into the same error message when trying to run an ipython kernel in a separate thread from the main thread. Once I receive that error message, I am unable to use ipython from jupyter.

If I surround the code in the pre_handler_hook and post_handler_hook of kernelbase.py, as well as the self.init_signal() in kernelapp.py file with a try catch, I'm able to use IPython within jupyter again and everything seems to work, although exceptions are just being caught in that case. I'm using the latest version of ipykernel, which I just cloned from github.

**Comment by csr818** [comment]
> Upgrading ipykernel worked for me conda upgrade ipykernel

actually work,thank you!
