### ISSUE TITLE
make cell outputs fully visible

### ISSUE THREAD

**Issue by bicepjai** [ipython/ipython#11264]
I notice the print statements are getting hidden at the start of the cell output, how to solve this issue ?

<img width="538" alt="screen shot 2018-08-13 at 5 34 27 pm" src="https://user-images.githubusercontent.com/806375/44065389-303f9b1a-9f1f-11e8-8d0e-67104d2fcf17.png">

**Comment by gustavoefeiche** [comment]
Could you please describe ipython version and the platform you are using?

**Comment by Carreau** [comment]
It also seem like you are using a custom environment. The theme does not look like the classic notebook, and you may have extension. 

You should also likely ask this question on Jupyter/notebook repository and not on IPython itself.

Closign but feel free to comment if re opening is nedded.
