### ISSUE TITLE
IPython>=6.5 (w/ prompt_toolkit>2) breaks all current versions of jupyter_console

### ISSUE THREAD

**Issue by mpacer** [ipython/ipython#11261]
Jupyter console's latest version as of today does not support prompt toolkit > 2. 

https://github.com/jupyter/jupyter_console/blob/master/setup.py#L82

```
    'prompt_toolkit>=1.0.0,<2.0.0',
```

I'm not sure what is involved upgrading to a newer edition of prompt_toolkit, but we will likely need to do that in order to fix this problem between jupyter_console and ipython.

**Comment by mpacer** [comment]
@Carreau @takluyver @jonathanslenders I feel like you all might have some insight here.

**Comment by Carreau** [comment]
It is a known issue  (https://github.com/jupyter/jupyter_console/issues/158), and there is a PR fixing it (https://github.com/jupyter/jupyter_console/pull/161) there just need to be people reviewing and helping with that, then we likely need to release a mojor version as it will be incompatible API.

I'm going to close as this is unrelated to IPython and above issues already track this.
