### ISSUE TITLE
Python 3.4 Maze Game code has problem

### ISSUE THREAD

**Issue by smoky-stu** [ipython/ipython#11260]
# Set the background color
        arcade.set_background_color(arcade.color.AMAZON)

        # Set the viewport boundaries
        # These numbers set where we have 'scrolled' to.
        self.view_left = 0
        self.view_bottom = 0
        print(f"Total wall blocks: {len(self.wall_list)}")

    def on_draw(self):
        """
        Render the screen.
        """
Invalid syntax comes up each time it is run. This is starting to bug me, as I can usually fix these problems for my students but not this one. This is the code that comes up as invalid syntax: 
 print(f"Total wall blocks: {len(self.wall_list)}")

**Comment by dhirschfeld** [comment]
I don't think this has anything to do with **i**python but it looks like your indentation is incorrect plus `**print(f"Total wall blocks: {len(self.wall_list)}")**` is not valid python - you should get rid of the asterisks. If you were intending to comment that line the comment character is `#`

**Comment by smoky-stu** [comment]
Those ** are meant to be Bold with the editor used on this site. Indentation is correct, first thing checked.

**Comment by takluyver** [comment]
f-strings (`f"Total wall...`) are new in Python 3.6; you can't use them in 3.4.

**Comment by smoky-stu** [comment]
Thank you, appreciate that answer. School is supposed to be implementing an update through the system some time in the future to 3.6.
