### ISSUE TITLE
Toolbar not appearing in Jupyter Notebooks 

### ISSUE THREAD

**Issue by jezlax** [ipython/ipython#11275]
Hello, 
I updated Jupyter recently and the tool bar has disappeared when in a python notebook. 

The following did not resolve it ran into an issue not being able to uninstall scandir
!pip install --upgrade --force-reinstall jupyter 

screenshot below, any help is welcome. thanks

![image](https://user-images.githubusercontent.com/10966945/44858752-ed54d400-ac2f-11e8-9612-5b3272a337e3.png)

**Comment by Carreau** [comment]
You are using a custom theme. IIRC this custom theme hides the toolbar. Please see with the theme author. 

THis is also a question for Jupyter/notebook, not IPython/IPython. 

Closing, feel free to ask to reopen if necessary.
