### ISSUE TITLE
set_custom_completer seems to be a no-op

### ISSUE THREAD

**Issue by atavory** [ipython/ipython#11272]
In [interactive_shell.py](https://github.com/ipython/ipython/blob/a2685d78f2403f84e6cb915ae11a4f6033ccc5f6/IPython/core/interactiveshell.py#L2034), `set_custom_completer` does

    self.Completer.matchers.insert(pos,newcomp)

Looking at the source code of IPCompleter, though, [matchers](https://github.com/ipython/ipython/blob/eed56ba34aa3856b5726d60eedfe60a17e1c26c5/IPython/core/completer.py#L1114) seems to be a property returning an ephemeral list, so the insert is a no-op.

To reproduce:

    import IPython

    def foo(*args, **kwargs):
        pass

    print(len(IPython.get_ipython().Completer.matchers))
    IPython.get_ipython().set_custom_completer(foo, 0)
    print(len(IPython.get_ipython().Completer.matchers))

This should print the same number twice (in my version, 5, 5)

**Comment by atavory** [comment]
Thanks!

I really like your

> 
> An alternate version of this is to allow custom matches to come either before or after the other matchers, but never be interpolated between them.
> 

in your second suggestion, FWIW.  

If needed, I'd be happy to submit a pull request for it.

**Comment by Madhu94** [comment]
This is still an issue, isn't it? Shalll I submit a PR?

**Comment by pganssle** [comment]
@Madhu94 I can reproduce with the latest version, so it looks like it hasn't been solved yet, so I suggest making a PR.

**Comment by ngoldbaum** [comment]
Looks like this is still an issue. Let's see if Paul's suggestion still works :)
