### ISSUE TITLE
Strings with spaces are not parsed correctly for shell execution in ipython

### ISSUE THREAD

**Issue by parthi2929** [ipython/ipython#11284]
Hi

I tried running a shell command as below in ipython notebook, but its not working. This is because the file name with spaces is not completely taken instead it gets chopped with space as delimiter, which thus naturally results in file not found error. 

Commands:  
```
source_file = "../../24. Confidence Intervals.ipynb"
import ntpath
tex_file = ntpath.basename(sourcefile).split('.ipynb')[0] + ".tex"
print(tex_file)
!pdflatex.exe -synctex=1 -interaction=nonstopmode -output-directory 1 "$tex_file"
```

Output:  
```
24. Confidence Intervals.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6730 64-bit)
entering extended mode
! I can't find file `24.'.
<*> 24. 
        Confidence Intervals.tex
Please type another input file name
! Emergency stop.
<*> 24. 
        Confidence Intervals.tex
!  ==> Fatal error occurred, no output PDF file produced!
```

Kindly help. I tried different methods by escaping space, but also didnot work. I tried on different commands but they also face same issue. 

OS: Windows 10
Python 3.6.4 (via anaconda)
Jupyter: 5.4.0

**Comment by Carreau** [comment]
`!` almost only call Popen with `shell=True`. Any underlying behavior is due to Popen. Try escaping the quotes.

Closing but feel free to keep commenting.
