### ISSUE TITLE
ipython autoreload does not work with class new methods

### ISSUE THREAD

**Issue by oscar6echo** [ipython/ipython#11281]
As described in this googlegroup jupyter thread [Hybrid dev Jupyter + VS Code & IPython magic autoreload](https://groups.google.com/forum/#!msg/jupyter/heWQ2ce04MI/xsZYe5GvAgAJ;context-place=forum/jupyter), and then later discussed with @Carreau at JCon, this [ipython-autoreload-explo](https://github.com/oscar6echo/ipython-autoreload-explo) repo gives an example, and maybe a fix ?

If you run the [test-magic-autoreload notebook](https://github.com/oscar6echo/ipython-autoreload-explo/blob/master/test-magic-autoreload.ipynb) with the standard `%autoreload 2` the [cube](https://github.com/oscar6echo/ipython-autoreload-explo/blob/9ce4faf9a1d132de281e4a98a71c23d65a797411/mypackage/myfile.py#L15) and [power](https://github.com/oscar6echo/ipython-autoreload-explo/blob/9ce4faf9a1d132de281e4a98a71c23d65a797411/mypackage/myfile.py#L19) function of [MyClass](https://github.com/oscar6echo/ipython-autoreload-explo/blob/9ce4faf9a1d132de281e4a98a71c23d65a797411/mypackage/myfile.py#L4), when uncommented still cannot be accessed.

If you run the same [test-magic-autoreload notebook](https://github.com/oscar6echo/ipython-autoreload-explo/blob/master/test-magic-autoreload.ipynb)  with `%myautoreload 2` then they are available.

The myautoreload magic is essentially the standard [autoreload](https://github.com/ipython/ipython/blob/master/IPython/extensions/autoreload.py), with a short [fix](https://github.com/oscar6echo/ipython-autoreload-explo/blob/9ce4faf9a1d132de281e4a98a71c23d65a797411/magics/myautoreload.py#L298).

Would you accept a PR ?

To give some context, the autoreload magic is particularly useful when a notebook producer prototypes in the notebook, because it's convenient, and then gradually moves the code to a properly organised package edited in a full fledged IDE. This package typically contains classes that start lean and grow.

**Comment by Carreau** [comment]
Apologies, I'm travelling and brain not functionning well while awake yet.
If it fix a usecase I'd say send a PR i'll try to get it in for 7.0 thtat I want to do (at least a beta) for end of semptember.

**Comment by oscar6echo** [comment]
Done.  
Please see PR #11283.

**Comment by Carreau** [comment]
CLosed by #11283.
