### ISSUE TITLE
%%writefile can't handle white space in file path/filename

### ISSUE THREAD

**Issue by mortang2410** [ipython/ipython#11309]
It is as the title suggests. In ipython, I have tried

`%%writefile  "test out.txt"`
`%%writefile  'test out.txt'`
`%%writefile  test out.txt`
`%%writefile  test\ out.txt`

and none gives me the expected behavior. The first one leads to creating a file literally named "test out.txt"  (yes, with quotes). The third one just leads to 

>  unrecognized arguments: out.txt

Is this a bug or am I just missing something obvious? Using IPython 6.5.0 with Python 3.6.5.

**Comment by Carreau** [comment]
This is probably a bug, it shouldn't be too hard to fix, it will just take some tim to figure out exactly how to parse the line. 

Here is where the [code of writefile is](https://github.com/ipython/ipython/blob/032cc8c92986762204a801eed36c57822b4a6345/IPython/core/magics/osm.py#L763-L791).

THe parsing is based on argparse.

**Comment by hongshaoyang** [comment]
I've written a simple workaround in #11330, please take a look.

**Comment by devadityasingh** [comment]
Yes
