### ISSUE TITLE
IPython 7.0.1 is incompatible with jupyter-console

### ISSUE THREAD

**Issue by neerajprad** [ipython/ipython#11335]
```bash
pip install ipython jupyter-console
``` 

complains about the incompatibility in `prompt-toolkit`. 

```
ipython 7.0.1 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.
```

Downgrading the version to `7.00rc1` gets around this issue.

**Comment by Carreau** [comment]
Yes, this is [tracked](https://github.com/jupyter/jupyter_console/issues/158) on the `jupyter_console` repository. 7.0.0rc1 have the same issue, you can't have it and jupyter_console installed and have both working.

Closing as it is tracked somewhere else.
