### ISSUE TITLE
Async error: event loop already running

### ISSUE THREAD

**Issue by davidbrochart** [ipython/ipython#11338]
Not sure this is an IPython issue because it happens only in a Jupyter Notebook, but the following code gives a `RuntimeError: This event loop is already running` (IPython 7.0.1, Python 3.7.0, notebook server 5.7.0). No problem with IPython 7.0.1, Python 3.6.3, notebook server 5.3.1.

```python
import asyncio

async def foo():
    await asyncio.sleep(1)
    print('done')

loop = asyncio.get_event_loop()

loop.run_until_complete(foo())
```

**Comment by Carreau** [comment]
Yes, is is documented in the what's new and [auto-async documentation](https://ipython.readthedocs.io/en/stable/interactive/autoawait.html#using-autoawait-in-a-notebook-ipykernel) with pointer to workarounds. 

Thanks for testing IPython 7.0 !

**Comment by davidbrochart** [comment]
The recommended way is to use [nest_asyncio](https://github.com/erdewit/nest_asyncio), but [in my case](https://github.com/erdewit/nest_asyncio/issues/3) it doesn't work (yet).
Is there a way to just disable Autoawait?

**Comment by Carreau** [comment]
> Is there a way to just disable Autoawait?

Yes, `%autoawait off` but your issue is unrelated to autoawait, it is due to the fact that tornato 5 use asyncio as its main eventloop. 

So far there is no solutions but to downgrade  `tornado` (and `ipykernel` ?) , see early in [this thread](https://github.com/jupyter/notebook/issues/3397#issuecomment-376803076) for example.

**Comment by HWiese1980** [comment]
Almost two years later, what's the status here?

**Comment by davidbrochart** [comment]
Having this a the beginning of your notebook should fix this issue:
```python
import nest_asyncio
nest_asyncio.apply()
```
