### ISSUE TITLE
Problem to use ipython token tranformoration facility as a way to alias python reserved words

### ISSUE THREAD

**Issue by psychoslave** [ipython/ipython#11342]
I'm trying to complete my [suggestion to use ipython tranformoration facilities as a way to locolalize python reserved words](https://stackoverflow.com/questions/17489603/defining-aliases-for-keywords-in-python/52568553#answer-52568553).

So far I came with the following code:

```python
from IPython.core.inputtransformer import TokenInputTransformer
@TokenInputTransformer.wrap
def f(tokens): 
    for n, token in enumerate(tokens):
         if token == 'si':
             tokens[n] = 'if'
    return tokens

from IPython import get_ipython
ip = get_ipython()
ip.input_splitter.python_line_transforms.append(f())

si True:
  prints 'Oui!'
```

Which fails with a syntax error. I would welcome any suggestion to fix the code and more broadly, solve the stated problem.

Further reading:

- https://ipython.org/ipython-doc/3/config/inputtransforms.html#token-based-transformers
- https://github.com/takluyver/ipython/blob/96b86fb221893f13ba26644098edc4a20cdc0669/docs/source/config/inputtransforms.rst
- https://github.com/ipython/ipython/issues/10893

**Comment by jesswright** [comment]
The top comment to that problem stated why "si" cannot be used as a reserved word. It's hard-coded into the language, sorry.

**Comment by jesswright** [comment]
Also, you are not inputting anything into the defined function you tried to call.

**Comment by takluyver** [comment]
The input transformation machinery all changed in 7.0; there were known problems with token transformers in the previous API (#10893) and I doubt anyone has the time to go back and fix it.

The new (7.0) API is now documented here:
https://ipython.readthedocs.io/en/stable/config/inputtransforms.html

The new API does not expose token-based transformers as a public API - we're using them internally, but the API felt too fragile to encourage other people to rely on. If you want to figure them out by reading code and write some of your own, feel free to, but future versions of IPython may well break it.

**Comment by psychoslave** [comment]
Thank you @takluyver for your feedback. Sad news to see it won't be a perenial solution to investigate and and propose for such a purpose of internationalization, but good to know where roads can lead.

Cheers
