### ISSUE TITLE
How to config jupyter/IPython so that I can get newline by hitting "Enter" instead of executing codes immediately?

### ISSUE THREAD

**Issue by ssfjhh** [ipython/ipython#11349]
For example, I input the codes below in IPython:
```python
for i in 'abc':
    print(i)|#| is a cursor.
```
In previous versions(I don't know the exact versions),  I can get a newline by hitting "Enter" once, and I can execute the inputed codes by hitting "Enter" twice. That is exactly what I want.
But now the codes is executed immediately with hitting "Enter" once. When I want to get a newline I have to hit "ctrl+Enter", and there is no auto-indentation.
How to config jupyter/IPython so that IPython behaves as usual.

**Comment by mmunozm** [comment]
I came here for the same reason. Same problem.
It's been already reported in https://github.com/ipython/ipython/issues/11334

**Comment by ssfjhh** [comment]
> I came here for the same reason. Same problem.
> It's been already reported in #11334
> 
> Edit: Use Ctrl+O to add new lines until it gets resolved.

I cannot get new line by `Ctrl+O` while `Ctrl+Enter` is OK.

**Comment by ozancaglayan** [comment]
Based on the release notes, this is (will be) fixed in version 7.1.

**Comment by Carreau** [comment]
7.1 released. Closing.
