### ISSUE TITLE
IPython directive parser broken for functions

### ISSUE THREAD

**Issue by TomAugspurger** [ipython/ipython#11362]
On IPython master, it seems like the `..ipython:: python` sphinx directive has trouble parsing function definitions

Some setup:

The `index.rst`

```rst
# file: index.html
Welcome to test's documentation!
================================

.. ipython:: python

   def f(x):
       x = 2
       return x

   f(2)


Testing
```

and the conf.py

```python
# file: conf.py
project = 'test'
copyright = '2018, tom'
author = 'tom'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''

extensions = [
    'IPython.sphinxext.ipython_directive',
    'IPython.sphinxext.ipython_console_highlighting',
]

source_suffix = '.rst'
master_doc = 'index'
```

To build

```
$ sphinx-build -M html . _build
Running Sphinx v1.8.1
making output directory...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build/html.
```

![screen shot 2018-10-04 at 8 52 45 am](https://user-images.githubusercontent.com/1312546/46478570-e41cd100-c7b2-11e8-93b5-dd52b16a2364.png)

Haven't done any debugging yet. Will take a look later.

**Comment by TomAugspurger** [comment]
In `process_block`

```
(Pdb) pp data
(None, 'def f(x):\n    x = 2\n    return x', '')
(Pdb) self.process_input(data, input_prompt, lineno)
(['In [1]: def f(x):', '   ...:     x = 2', '   ...:     return x', '   ...: ', '  File "<ipython-input-2-50e9b99ff1e2>", line 1\n    return x\n            ^\nSyntaxError: \'return\' outside function\n\n'], ['def f(x):', '    x = 2', '    return x', ''], '  File "<ipython-input-2-50e9b99ff1e2>", line 1\n    return x\n            ^\nSyntaxError: \'return\' outside function\n\n', False, None, None, None)
```

So something in `process_input` in going awry.

**Comment by dsblank** [comment]
Maybe a hint: it thinks the error is in line 1. Maybe the newlines are being removed?

**Comment by TomAugspurger** [comment]
I haven't dug further, but it seems like the use of `InteractiveShell.check_complete` is the issue. On 6.x and 7.x this is true

```python
In [1]: from IPython import InteractiveShell

In [2]: shell = InteractiveShell()

In [3]: shell.check_complete("def f(x):    x = 2")
Out[3]: ('complete', '')
```

On 6.x `splitter = self.IP.input_splitter` was used in `process_input_line` to see if there should be more lines coming.

**Comment by TomAugspurger** [comment]
> Maybe a hint: it thinks the error is in line 1. Maybe the newlines are being removed?

The error being line 1 was correct, though I think it's because lines aren't being joined properly.

FYI, I've stopped debugging this for now, in the hope that someone will more familiar with this bit of code will instantly know what's wrong. Though I think the pandas and matplotlib devs should be expected to share the maintenance burden since we're the main users :)

**Comment by adamklein** [comment]
I am seeing perhaps the same issue in the sphinx extension. My code is failing to process multiple lines such as:

```
.. ipython::

   In [1]: @decorated_func
      ...: def my_func():
      ...:     return pd.DataFrame(index=pd.date_range('20050101', '20050110', freq='D'))

   In [2]: n = my_func()
```

with sphinx-build I get

```
>>>-------------------------------------------------------------------------
Exception in .../docs/cookbook.rst at block ending on line 46
Specify :okexcept: as an option in the ipython:: block to suppress this message
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-e7d2bcb4e770> in <module>
----> 1 n = my_func()

NameError: name 'my_func' is not defined
<<<-------------------------------------------------------------------------
```
Does this sound like the same issue?

**Comment by Carreau** [comment]
closed by #11402

**Comment by thequackdaddy** [comment]
Could this be re-opened? 

I am working on this again and I think the issue still exists when you have classes?

sphinx seems to work fine with ipython 7.2 on [this](https://github.com/statsmodels/statsmodels/blob/master/docs/source/contrasts.rst) file, but only if I remove the class `Simple` (and all the instances thereof). 

Thus, I think there might be problem with classes. Not sure how to provide a minimal example, sadly.

**Comment by thequackdaddy** [comment]
Ok I have done some investigation of this... 

I think the real problem is here:

https://github.com/ipython/ipython/blob/4f901de17aff2132365fc3741fc5b4b8a9a98dc6/IPython/sphinxext/ipython_directive.py#L800-L852

Bottom line is that we have some very simple logic that basically:
* Creates "breaks" after every line that starts with a "@" (used because `@savefig` is some pseudo decorator that saves figures as files.)
* Creates "breaks" after every line that starts with a "#".
* Inside functions--but nothing else--checks to see if the function has a return statement. Once found, it exits the function. 

My main criticism is that if you have a class, it doesn't try to go to the end of the class. If you have multiple functions, it will likely "break" after the first function. Additionally, python already has a pretty good `ast.parse` function, and we are basically ignoring it. 

I wrote a quick PR to address some of my concerns. I notice there's no real unit testing, so that's likely my next challenge.
