### ISSUE TITLE
trade deprecated time.clock for time.perf_counter

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#11375]
We still have some calls to `time.clock`, which is deprecated. We should switch all such calls to `time.perf_counter`, which is available in all supported Python versions.

**Comment by victor-eds** [comment]
I'll take a look

**Comment by ammarmallik** [comment]
Done with it. Please review this: [Pull Request](https://github.com/ipython/ipython/pull/11376)

**Comment by Carreau** [comment]
closed in #11376

**Comment by Carreau** [comment]
Thanks, nice work.
