### ISSUE TITLE
Jupyter Notebook Output Problem

### ISSUE THREAD

**Issue by damlaalkan** [ipython/ipython#11383]
Hey I am new in Jupyter Notebook. In kernel R, my first line is giving the output but then it stops working. After first line every line gives nothing as output. Then when I change the first line input, the output of first line  disappears again. Please help me.

**Comment by damlaalkan** [comment]
Hello, firstly thank you for your quick response. Before you wrote, I did conda uninstall r-base so even the first line is not working right now but prompt saying In[*] always.  Now it is like that:


![image](https://user-images.githubusercontent.com/28626390/46748309-f4a1df80-ccbb-11e8-84c5-8fa1c4bf95e0.png)


But before it was giving output of first line as 4 but for the second and the other lines nothing was appeared as output. What do you recommend for me?

**Comment by Carreau** [comment]
So you can see two things : `In[*]` and in the upper right corner `R (black dot)`. 

The black dot and the `*` mean the notebook believe the kernel is busy (or unresponsive), this can happen if : 1)  R is doing a long running computation. 
2) there is a bug/crash

In your taskbar, one of the latest icon is "Anaconda Prompt" or something like that. 
Click on it and see if there is an error.

**Comment by damlaalkan** [comment]
Thank you but I deleted everything download again by following https://irkernel.github.io/installation/

**Comment by damlaalkan** [comment]
Thank you so much for your help but I deleted everything, R and Anaconda, and installed again by following https://irkernel.github.io/installation/. Now it works perfectly.

**Comment by Carreau** [comment]
Thanks, closing. 

@meeseeksdev[bot] close
