### ISSUE TITLE
Clean and update the documentation of the sphinx directive.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#11410]
@choldgraf made many good comments about the documentation of the sphinx directing in  ipython/ipython#11402

Cleaning the documentation, and moving most of the basic content into the module docstring, and include it with `.. automodule` would be good, then passing through the file and fixing the english/pharasing, plus reducing the size of the page woudl be good.

Leavin that as an "easy" issue for anyone willing to contribute.

**Comment by LucianaMarques** [comment]
Hi @Carreau , I'd like to give it a try, I believe I could do some good contribution on documentation. 

Just to make sure, there's no one handling this right now, right?

**Comment by Carreau** [comment]
> there's no one handling this right now, right?

No I don't think anyone is doing that. Thanks for taking the time to help much appreciated.

**Comment by choldgraf** [comment]
go @LucianaMarques !!! 🎉

**Comment by LucianaMarques** [comment]
Thank you @Carreau and @choldgraf, I'll come back with a pull request soon.

**Comment by LucianaMarques** [comment]
Hi guys, just to let you know, I added a few questions on the pull request mentioned by @Carreau , once I got these doubts figured out I'll open a pull request.

**Comment by LucianaMarques** [comment]
Hey, my pull request is [here](https://github.com/ipython/ipython/pull/11427)! 

I wanted to discuss some things, please take a look. Thanks!

**Comment by Carreau** [comment]
Tip, when you want to link to a pull-request you can also just add `#11427` (render as #11427), or to do it across repositories `ipython/ipython#11427` (render as ipython/ipython#11427)

**Comment by willingc** [comment]
@Carreau @LucianaMarques Now that the PR is merged, I'm going to close this. Thanks!
