### ISSUE TITLE
`ls` magic alias to `ls -F --color`

### ISSUE THREAD

**Issue by liushapku** [ipython/ipython#11431]
I have many different profiles used in linux. I use one profile when my terminal does not support any color.
Is there any option to control the `ls` aliases so that it uses `ls -F` instead of `ls -F --color`?

I already used `c.InteractiveShell.colors = 'NoColor'` but it does not affect the `ls` alias

**Comment by Carreau** [comment]
`ls` is also an alias in IPython, you can redefine it interactively to just `ls` with

```
In [1]: alias ls ls
```

use `hist -t ` to see the equivalent Python code:
```
In [2]: hist -t
get_ipython().run_line_magic('alias', 'ls ls')
get_ipython().run_line_magic('hist', '-t')
```

Place the equivalent code into `~/.ipython/profile_default/startup/alias.py` (choose the nname you like) with any other logic you like, like looking at the `$TERM` env or `infocmp` to know whether color is supported or not.

Does that fits your need ? 

If so feel free to close the issue.

**Comment by liushapku** [comment]
@Carreau Yes. This solves my problem. Thank you.

But don't you think it better to set the alias in `core.alias` according to `c.InteractiveShell.colors`? If it is 'NoColor', the `--color` should be remove in defining the aliases.

**Comment by Carreau** [comment]
Sure, but that would require someone to code it. Most if not all of the
work is volunteer, so it's mostly 'if someone implement it'.

**Comment by liushapku** [comment]
I have a workaround that is to change `AliasManger.init_aliases` in `IPython/core/alias.py` to

    def init_aliases(self):
        # Load default & user aliases
        for name, cmd in self.default_aliases + self.user_aliases:
            if cmd.startswith('ls') and self.shell.colors == 'NoColor':
                cmd = cmd.replace(' --color', '')
            self.soft_define_alias(name, cmd)

Do you think this an acceptable solution? If yes I can submit the pull request.

I don't quite understand what is a `Configurable` and what does `List(default_aliases()).tag(config=True)` imply. Why should the `default_aliases` be a class data member instead of instance data member? If it is an instance data member, we can easily let the function `default_aliases()` take a parameter `nocolor` and when it is `False` do not set `--color` in the aliases for `ls`.

**Comment by Carreau** [comment]
> Do you think this an acceptable solution? If yes I can submit the pull request.

Yes, that sounds good. 

> I don't quite understand what is a `Configurable` and what does `List(default_aliases()).tag(config=True)` imply. Why should the `default_aliases` be a class data member instead of instance data member?

Don't worry about that, it's the metaclass magic that  allow `c.AliasManger.default_aliases.append(...)/.prepend(...)` to work in the configuration file, and `--AliasManger.default_aliases=...` to work similarly as a command line argument. 

You  can tread `default_aliases` as a instance attribute which is of type list for all purposes.

**Comment by liushapku** [comment]
Get it. Thanks for explanation. I will take some time to digest the details of the configuration system.

Let me create an pull request for this change first.

**Comment by liushapku** [comment]
Do I need to consider the order of the initialization of the `colors` property and the `alias` properties?
Will the configuration system automatically fix the dependence?

**Comment by Carreau** [comment]
> Do I need to consider the order of the initialization of the `colors` property and the `alias` properties?
> Will the configuration system automatically fix the dependence?

As far as I can tell in your case you can just assumes the `default_aliases`  and `user_aliases`  are set once `super(AliasManager, self).__init__(shell=shell, **kwargs)` is called. The property are eventfull so we could link things up, but the way you did it in #11446 sounds good !

**Comment by liushapku** [comment]
Thanks for the explanation!
