### ISSUE TITLE
iPython 7.0.1 no longer allows multiple lines in blocks

### ISSUE THREAD

**Issue by truenicoco** [ipython/ipython#11442]
With the 6.x series I had to type enter twice to actually run several statements inside a block, which was really convenient. Since 7.0.1, it is executed immediately, allowing only one line inside a block, which is pretty sad. Is this the new intended behaviour?

Illustration:

```
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: for i in range(8):
   ...:     print(i)
   ...:     
0
1
[...]
```

against:

```
Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: for i in range(8): 
   ...:     print(i)                                                                                                                                         
0
1
[...]
```

**Comment by ozancaglayan** [comment]
Yes exactly but I think for me it "sometimes" works. But for other times it justs interprets earlier than it should. Very annoying.

This is ipython 7.0.1 on Python 3.7, using anaconda.

**Comment by truenicoco** [comment]
I did search but didn't found a previous report. Sorry, maintainers!
