### ISSUE TITLE
merge the two IPython directive pages

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#11444]
see https://ipython.readthedocs.io/en/latest/sphinxext.html
and https://ipython.readthedocs.io/en/latest/development/ipython_directive.html

Move all likely in the first link as it already exists in 7.0 doc.

**Comment by LucianaMarques** [comment]
Hey @Carreau , I'd like to give this a try!

Just to make it clear, I just have to merge both docs into only one (the first one) and delete the second one?

**Comment by Carreau** [comment]
> Just to make it clear, I just have to merge both docs into only one (the first one) and delete the second one?

Yes, that sounds good ! You've been doing some good work, so now you can likely start to make your own decision, or challenge ours !
