### ISSUE TITLE
Terminal title should be disabled when using IPython in a pipeline

### ISSUE THREAD

**Issue by kbd** [ipython/ipython#11482]
This came up recently here: https://github.com/sharkdp/bat/issues/403

Here's an example of how IPython prints control characters even when used in a pipeline:

```
/$ ipython -c "import os; print(os.isatty(1))"
True

/$ ipython -c "import os; print(os.isatty(1))" | gcat -A
^[]0;IPython: /^GFalse$
```

It would be good if IPython checked `isatty` (as shown above) to not add terminal title control characters if `ipython` is being used in a pipeline.

To be clear, this isn't just a convenience feature, as it can actually cause unexpected behavior when used in a pipeline. For example, one would expect that a `grep` for the letter `o` in the output of "False" above would return false:

```
/$ ipython -c "import os; print(os.isatty(1))" | grep o
01;31mon: /False
```

But it returns a match! Running the same command using stock Python correctly returns nothing (and 1 return code):

```
/$ python3 -c "import os; print(os.isatty(1))" | grep o
/$:1
```

**Comment by Carreau** [comment]
That seem reasonable to me. Do you want to send a PR ? The code setting the terminal title is likely in `IPython/terminal/interactiveshell.py`.

**Comment by kbd** [comment]
> That seem reasonable to me.

Great!

> Do you want to send a PR ?

Ok will do! FYI I won't be able to get to it before the weekend.

**Comment by Carreau** [comment]
> Ok will do! FYI I won't be able to get to it before the weekend.

No problem, large majority on the work in this repo is done on Nights and Week-end.
