### ISSUE TITLE
Release 7.1.1 has not been tagged

### ISSUE THREAD

**Issue by jamesw966** [ipython/ipython#11480]
Release 7.1.1 does not have a tag on GitHub. This is making things a bit difficult for the OSS registration tools I'm using.

**Comment by Carreau** [comment]
Apologies for that, it is now tagged and should point to 59a7834d26f553c62b35e767b8fc0482187f7218 which should be signed by me. 

Feel free to close the issue once it works.

Which tools are you using if I may ask ? Do you want me to ping you on new releases ?

**Comment by jamesw966** [comment]
Oh, it's just an internal Microsoft tool. Thanks very much for tagging!
