### ISSUE TITLE
Why not have %pip do the right thing?

### ISSUE THREAD

**Issue by dsblank** [ipython/ipython#11481]
On the page:

https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-pip

it says:

```
Intercept usage of pip in IPython and direct user to run command outside of IPython.
```

But why? Couldn't it be this: .... (deleted hacky code) how about this:

https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/

**Comment by Carreau** [comment]
Thanks for the question.  It's because "the right thing" is not always super obvious.

I did write https://pypi.org/project/pip_magic/ which does it, but one of the problem is how to make it work in the notebook. 
If pip ask for input then there is no way to "press" Y or N so the user process get stuck. It also let the user in a state where they believe that using pip from within IPython of Notebook "works". While it may work for installing missing modules it will not work for updating and a couple of other case. So we've settle on just giving an advice message. 

I'll be happy to experiment with other method but we're afraid it would be more disruptive than anything else

**Comment by dsblank** [comment]
Instructing users how to install and/or upgrade is really painful in IPython (including notebook, lab, console, and otherwise). Of course, pip is painful in Python generally. But we could do a lot to make this much better. "pip" is a Python package, so we can import it, and decide what the right thing to do is. Or, even better, detect whether we are in anaconda and decide what the best course of action would be for a given package, complete with questions for the user.

I think a general "%install" magic would help so much in this space. But first, we need to understand the issue with pip. And, if it can't handle 100% of cases, that's fine too. We just need to give a message, and maybe point to a URL with more details.

Here is the start of an IPython Package Manifesto:

1. We need to recognize that packages are hard to install/upgrade in Jupyter because it is not clear what version of Python is running nor how to get to that environment from the shell. We need to recognize that this is a big, important problem.
2. We can get all of the information we need from the running environment to install/upgrade in anaconda and/or pip
3. We can make suggestions for the anaconda and pip Python libraries to make it better integrated with Jupyter/IPython. We don't have to solve this completely from one end.
4. We can put a layer over these APIs to make it much easier to manage the majority of packages. It could even: "I'm going to update the following package. Select Yes to continue." Can also handle `--upgrade-strategy` appropriately.
5. Should be a standard part of IPython/Jupyter (eventually). Doesn't have to start out that way, but should have the support of the entire organization.
6. Could handle all of the different packages/activations in the Jupyter/IPython universe, and even know what needs to be done next (restart Jupyter, restart kernel, etc).
7. We can solve this problem.

**Comment by Carreau** [comment]
While I agree with most of that, and have tried to see what can be done upstream I've been blocked at several steps. : 

> "pip" is a Python package, so we can import it. 

No, not reliably. It is meant to be used as a CLI and rely on global internal state. So you __need__ to shell out to it. Upstream is not willing to make an API, and more inclined to make your life harder if you try as an API. 

Same for conda. 

Without this first steps it becomes really hard. We can try sure. but it requires a lot of dev work. 

I think it is a deeper problem, that most core-python people are not data scientist and we regularly hit snag where Python is not developed to be that friendly to REPL. Heck we even have to do contortions to allow users to write multi-line code blocks which is not supported by the CPython API. 

You are a core dev, and I'm happy for you to push that. If you make PRs and want friendlier pip integration I'll push in your direction. But the above ar mostly me trying to transfer the experience of last time I tried. 

... Maybe the conda folks could be re-convinced.  I would also love o have a gui package manager that hook into conda as a notebook/lab plugin.

**Comment by dsblank** [comment]
Thank you Santa, I mean @jakevdp ! I think we can close this.

**Comment by Carreau** [comment]
I'll try to release on the 25th :-)
