### ISSUE TITLE
Non-breakable space \xA0 converted to "&" when pasting into IPython

### ISSUE THREAD

**Issue by zakora** [ipython/ipython#11490]
**Steps to reproduce:**
1. Copy a non-breakable space into the clipboard
2. Paste the non-breakable space into the IPython console
3. The pasted character is shown as `&` in IPython console
Expected: The pasted character should be the non-breakable space.

**Example:**
![screencap](https://user-images.githubusercontent.com/106620/48313373-d5001e80-e5bb-11e8-9903-d26fd47c7447.gif)
[Video](https://github.com/ipython/ipython/files/2569344/remux.zip)

**System information:**
```
>  python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': '59a7834d2',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/tmp/venv/lib/python3.6/site-packages/IPython',
 'ipython_version': '7.1.1',
 'os_name': 'posix',
 'platform': 'Linux-4.18.17-200.fc28.x86_64-x86_64-with-fedora-28-Twenty_Eight',
 'sys_executable': '/tmp/venv/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.6.6 (default, Jul 19 2018, 14:25:17) \n'
                '[GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]'}
```

**Comment by zakora** [comment]
This bug doesn't happen when starting IPython with `env IPY_TEST_SIMPLE_PROMPT=1 ipython`.

**Comment by zakora** [comment]
This bug was fixed in https://github.com/prompt-toolkit/python-prompt-toolkit/commit/7db93560cb1f10c96f4a22816774da63e67e467e .
Waiting on a release of prompt_toolkit that brings this commit, then IPython will be able to get the fix.
Keeping this issue open for now, will close when the fix is propagated to IPython.

**Comment by Carreau** [comment]
Thanks for investigating and reporting back.

**Comment by zakora** [comment]
prompt_toolkit made releases with the fix, IPython got the fix, closing.
