### ISSUE TITLE
Permission to listen on port 8888 denied - Jupyter Notebook issue

### ISSUE THREAD

**Issue by madmanmadani** [ipython/ipython#11500]
I've been having issues getting on Jupyter Notebook again, used it in the past on this same machine but I am having problems with ports being denied and 0 active kernels. 

I constantly get "permission to listen on port 8888 denied" , I've checked to make sure I don't have any other notebooks open / instances running. I've followed a lot of the existing threads out there, but nothing has helped to resolve this. Can someone please help? I am running on Windows 10

**Comment by Carreau** [comment]
This is a question for jupyter/notebook, not ipython/ipython. 

In general if permission is `denied` it is different than something already listening. It mean that your user has not enough permission, or that an antivirus/firewall is restricting access. 

Closing for now as this is unrelated to IPython, but feel free to keep commenting.
