### ISSUE TITLE
all_completions returns nothing (simple fix suggested)

### ISSUE THREAD

**Issue by memeplex** [ipython/ipython#11541]
The `Completer.all_completions` method, which emacs python.el and elpy mode use, is returning nothing defined in the current scope. For example:

```
In [87]: xxx = 2

In [91]: get_ipython().Completer.all_completions('x')
Out[91]: ['%xdel', '%xmode']

In [92]: get_ipython().Completer.all_completions('xx')
Out[92]: []
```
Internally it's using jedi but discarding jedi completions. Now, `all_completions` calls the deprecated `complete` instead of `completions`. A simple change fixes both the usage of a deprecated method and a bug:

```
In [127]: list(map(lambda c: c.text, get_ipython().Completer.completions('x', len('x'))))
Out[127]: ['xxx', '%xdel', '%xmode']
```

Why not redefining `all_completions` like that? At least the following is working for me inside an emacs inferior python session:

```
get_ipython().Completer.all_completions = lambda t: map(lambda c: c.text, get_ipython().Completer.completions(t, len(t)))
```

**Comment by memeplex** [comment]
I realized the `map` is slightly more complicated because of a mismatch between what is returned and what emacs expects:

```
lambda c: t + c.text if t.endswith(".") else c.text
```

This way `xx -> xxx` but `argparse. -> argparse.ArgumentError`.

**Comment by memeplex** [comment]
Sorry, this one seems to be the right fix: `lambda c: t[:t.rfind(".") + 1] + c.text`

**Comment by memeplex** [comment]
@Carreau would you consider adding this to the next milestone? It's easy to fix and it's really critical for emacs users. Thanks!

**Comment by Carreau** [comment]
Sure, sending a PR would help. I'm way behind on working on IPython.

**Comment by memeplex** [comment]
@Carreau check the PR above, please.

**Comment by memeplex** [comment]
Can we close this? The fix has already been merged.
