### ISSUE TITLE
Can the IPython directive use warnings for errors?

### ISSUE THREAD

**Issue by TomAugspurger** [ipython/ipython#11547]
Pandas would like to have a workflow where

1. the documentation build always completes to the end, even if there are warnings
2. the CI fails if there are any warnings.

For regular sphinx things, this works with a combination of `-W error --keep-going`, which fails the job at the end of the build if there were any warnings.

This doesn't work with exceptions in IPython blocks. Here's a small example

```
Welcome to test's documentation!
================================

.. ipython:: python

   2 + 'a'

The rest of the biuld

.. ipython:: python

   2 + 2
```

And the relevant IPytyhon conf setting is `ipython_warning_is_error = False`.

When I run

```
sphinx-build -W --keep-going "." _build/
```

The entire document is built, but the exit code is `0`, when I'd like it to be `1`.

I *hope* this is just because exceptions in IPython blocks are printed to stdout. On some basic testing, it looks like using `sphinx.util.logging` and `logger.warning` rather than `sys.stdout.write` will satisfy my needs.

Are the IPython devs open to changing from `sys.stdout.write` to `logger.warning` for this?

cc @tacaswell, and idea if this change would break matplotlib at all?

**Comment by Carreau** [comment]
That seem to be reasonable to me. Feel free to send a pull request. 

@LucianaMarques might also want to take a shot at it ?

**Comment by TomAugspurger** [comment]
Sure, let me know if you have any questions.

I pushed my example to https://github.com/TomAugspurger/sphinx-test and am
building with `sphinx-build -W --keep-going "." _build/`.
Ideally that would exit with a non-zero exit code.

**Comment by LucianaMarques** [comment]
@TomAugspurger thank you for the explanation, I will take a loot at it and get back here.

**Comment by LucianaMarques** [comment]
@Carreau could you assign this to me, please?

**Comment by Carreau** [comment]
> Could you assign this to me, please?

I don't think I can assign to people that do not have commit rights. Just leaving a comment saying you want to work on it is enough.

**Comment by tacaswell** [comment]
Matplotlib also wants to fail CI if there are any errors in the docs.

**Comment by tacaswell** [comment]
Which is to say I am :+1: on this change.
