### ISSUE TITLE
Can not pass parameters to standalone .ipy scripts

### ISSUE THREAD

**Issue by techtonik** [ipython/ipython#11548]
It is impossible to create standalone .ipy scripts that accept parameters:

    $ cat <<EOF > script.ipy
    #!/usr/bin/env ipython3
    import sys
    print(sys.argv)
    EOF
    $ chmod +x script.ipy
    $ ./script.ipy --force
    ...
    [TerminalIPythonApp] CRITICAL | Bad config encountered during initialization:
    [TerminalIPythonApp] CRITICAL | Unrecognized flag: '--force'

Passing params to .ipy script is only possible when executing `ipython3` with explicit `--` delimiter:

    $ ipython3 script.ipy -- --force
    ['/home/techtonik/script.ipy', '--force']

The solution is to detect when .ipy script is specified and stop processing parameters after the filename.

**Comment by techtonik** [comment]
For command line `ipython3` processing starts by invoking this function:

https://github.com/ipython/ipython/blob/e9f3be2fbf425920e747ecf3a34d6dbbd511b3d5/IPython/terminal/ipapp.py#L376

which through inheritance `TerminalIPythonApp <-- IPython.core.application.BaseIPythonApplication <-- traitlets.config.application.Application` ends up in another repo:

https://github.com/ipython/traitlets/blob/d07d70d81e82f655ac36841415721d5246876538/traitlets/config/application.py#L824

**Comment by techtonik** [comment]
I can not trace which methods are called in which order up and down of the inheritance tree above:

https://github.com/ipython/traitlets/blob/d07d70d81e82f655ac36841415721d5246876538/traitlets/config/application.py#L829-L831

There are some docs https://traitlets.readthedocs.io/en/stable/config.html but I don't see how to alter `--` processing.

**Comment by techtonik** [comment]
Found the place:

https://github.com/ipython/ipython/blob/e9f3be2fbf425920e747ecf3a34d6dbbd511b3d5/IPython/terminal/ipapp.py#L289

**Comment by takluyver** [comment]
Is it a big hardship to use the extra `--`? `.ipy` scripts aren't widely used, as far as we know, but they linger on in the codebase to bring up odd problems like this. I'm reluctant to add special cases for handling them.

**Comment by techtonik** [comment]
> Is it a big hardship to use the extra --?

Yes. They can not be used in shebang, which means you can not have executable `.ipy` script:
```
$ cat xxx.ipy 
#!/usr/bin/env ipython3 --

!echo "XXX"
$ ipython3 xxx.ipy 
XXX
$ chmod +x xxx.ipy 
$ ./xxx.ipy 
/usr/bin/env: ‘ipython3 --’: No such file or directory
$ /usr/bin/env ipython3 --version
5.5.0
```

`.ipy` script popularity is a cause and effect problem. Without command line arguments they are less useful than plain `.py` or `.sh`.

**Comment by takluyver** [comment]
If that was the only issue, we'd have had a lot more people trying to fix it before now.

Regardless of that issue, I wouldn't recommend anyone use .ipy scripts. In fact, I'd go so far as to say: *please* don't use .ipy scripts for new code, and if you have existing code in them, consider it technical debt which you should try to clear up. Write Python scripts, or shell scripts, or xonsh scripts instead.

The IPython syntax is poorly specified; you're writing in a language with no proper grammar or parser. That means it's tricky for any static analysis tools to work with, which can be enormously useful even for dynamic languages like Python. It also means it's entirely implementation-defined, and we can and do change the implementation significantly from one version to another. We try to preserve compatibility, but there are no guarantees, and I'm sure there are gaps in the test suite. If we found a way to preserve 90% of the functionality with 10% of the complexity,  we may well go for it, especially if that made it easier to do something else which was more interesting at the time. The IPython syntax is convenient for interactive use, but it's not something to rely on in a script.

**Comment by techtonik** [comment]
:disappointed:

**Comment by techtonik** [comment]
I accept with that disclaimer. Is it possible to merge the fix now? )

**Comment by techtonik** [comment]
I am not using it for anything serious. See this for example. https://github.com/rirror/rirror.github.io/blob/master/01genkeys.ipy

I could use `bash`, but I am unable to write any bash `if` with file check or `for` offline without stackoverflow, so for me this is a good productivity boost. For a proper automation I will of course replace all instructions with subprocess.something.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.
It's been a while, here, @techtonik, but I agree with @takluyver that adding `--` manually is not to onerous. I think there are ways to route around the issue of not being able to use ipython in a shebang, such as creating another executable shell script that does this wrapping for you.

Thanks everyone and happy hacking! :bowtie:
