### ISSUE TITLE
Enhancement Suggestion: IPDB Runcall Magic

### ISSUE THREAD

**Issue by aa1371** [ipython/ipython#11555]
One of the most common debugging tools that I use is `ipdb.runcall`. So much so that I have use a custom magic to make it more convenient. The current implementation looks like this:

```python
import ipdb
from IPython.core.magic import register_line_magic
from IPython import get_ipython

@register_line_magic
def runcall(line):
    locals().update(get_ipython().user_ns)
    result = eval('ipdb.runcall(' + line.replace('(', ',', 1).replace(',)', ')'))
    return result

del register_line_magic
```

The usage looks like this:

```python
>>> def func(a=0, b=0):
...    c = a + b
...    d = b * c
...    return a - d
>>> %runcall func(b=2)
>>> x = %runcall func(3, 4)
>>> y = %runcall func()
```

I'm sure there is probably a better way to implement this, but either way I think that this would be a very valuable default magic to add.

**Comment by Carreau** [comment]
Thanks for the proposal. 
What I would suggest is to package your magic, and put it on PyPI. 

It's relatively easy, look at [flit](https://flit.readthedocs.io/en/latest/) to do that for example. 

Once its matures and is quite stable, we can consider including it. 

There are many advantages to packaging, in particular you are not limited by us if you need a modification to the magic, and you can make it available to users of older version of IPython. 

How does that sound ?

**Comment by ArtinSarraf** [comment]
Sounds good. I’ll try it out, thanks.
