### ISSUE TITLE
Weird regexp ['*']

### ISSUE THREAD

**Issue by dimaqq** [ipython/ipython#11559]
osm.py:828 `if re.match(r'[\'*\']|["*"]', args.filename):`

This regexp is odd, it's equivalent to `args.filename.startswith(("*", "'", '"'))` .
I can't quite imagine what was meant, perhaps "is the filename quoted?", i.e. `^('.*')|(".*")$` ?

https://lgtm.com/projects/g/ipython/ipython/snapshot/6baca094fcd8573aa8e8a75507b961c5af0aadd8/files/IPython/core/magics/osm.py?sort=name&dir=ASC&mode=heatmap#x4444122602069ae7:1

**Comment by takluyver** [comment]
Yes, I think you're right about what was meant. See PR #11330. Do you want to make a PR to fix it? And add another test?

**Comment by Carreau** [comment]
closed by #11600
