### ISSUE TITLE
Typo in completer module's docummentation and suggestions

### ISSUE THREAD

**Issue by LucianaMarques** [ipython/ipython#11554]
I'm currently working on issue #11449 and therefore I'm reading a lot about [the completer module](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.completer.html#module-IPython.core.completer). 

I found a small typo in this excerpt:

> We welcome any feedback on these new API, and we also encourage you to try this module in debug mode (start IPython with --Completer.debug=True) in order to have extra logging information is jedi is crashing, or if current IPython completer pending deprecations are returning results not yet handled by jedi

I believe that the correct is "... in order to have extra loggin information _**if**_ jedi is crashing ... "

I also wanted to give some suggestions on how to rewrite some paragraphs of this part of the docs. 

May I submit a PR on this type with other suggestions?

Thank you

**Comment by Carreau** [comment]
Sure, feel free to send PRs for anything you like. You don't have to ask for permission first.

**Comment by LucianaMarques** [comment]
Ok, I'm working on this and will submit a PR soon.

**Comment by LucianaMarques** [comment]
I fixed this in #11583
