### ISSUE TITLE
screenshot of a web page using Python

### ISSUE THREAD

**Issue by PallaviBodepudi** [ipython/ipython#11560]
Can someone help me with taking a screenshot of web page(eg: https://www.google.com/) using python?

**Comment by Carreau** [comment]
Hi @PallaviBodepudi 

Thanks for your question. Just to let you know that this is not a general Python to ask questions about learning Python, but more specifically about the development of the IPython software. I would suggest trying for example https://www.reddit.com/r/learnpython/ if you are starting with Python. 

To take a screenshot I would though advise to google for "Python and Selenium", Selenium will help you to control what is known as a headless web-browser. 

I'm going to close the issue as there no actionable item from my side, but feel free to keep commenting.
