### ISSUE TITLE
Python `contextvars` don't persist across cells in notebook

### ISSUE THREAD

**Issue by saulshanabrook** [ipython/ipython#11565]
Python 3.7 added a new [`contextvars`](https://docs.python.org/3/library/contextvars.html) package to "manage, store, and access context-local state".

However, if I set a `ContextVar` in one cell and then try to get it in another, it isn't persisted:

![](https://files.gitter.im/jupyter/jupyter/CLar/Screen-Shot-2019-01-16-at-4.36.18-PM.png)

This may be an antipattern (not sure if there is a good use case to set a variable across many cells) and I worked around it by setting `default`, [as recommended](https://www.python.org/dev/peps/pep-0567/#converting-code-that-uses-threading-local). However it is surprising and is different than how `ipython` works.

**Comment by takluyver** [comment]
@Carreau is this related to the async stuff?

**Comment by njsmith** [comment]
That's weird. ContextVars are like thread-locals until someone explicitly calls `Context.run`... is the kernel single-threaded? Does it use `Context.run`? Is some other lib calling it?

**Comment by Carreau** [comment]
In the notebook it's probably running the tornado eventloop... maybe @minrk  knows ?

**Comment by njsmith** [comment]
I believe tornado on py3 uses the asyncio loop by default, and if you're on py 3.7 then asyncio will automatically use different contexts for different tasks. And probably each cell execution counts as a different task as far as tornado/aio is concerned.

Sounds like the kernel should be explicitly holding a `Context` object and reusing it for each cell execution, instead of letting tornado/aio set the `Context` implicitly.

**Comment by minrk** [comment]
Thanks @njsmith! That sounds like a pointer in the right direction. Each execution is indeed an independent coroutine submission. I'm not quite sure if the fix for this will belong in core ipython, ipykernel, or both. Hopefully just ipython.

**Comment by vangheem** [comment]
Also, related to this. It seems like context vars are not correctly propagated when initializing or calling code that get/sets vars in differently in async functions.

Here is some code to display the problem:

```
from IPython.terminal.embed import InteractiveShellEmbed
from traitlets.config.loader import Config

import contextvars

cvar = contextvars.ContextVar('foo')


def run():
    cvar.set('bar')

    def foo():
        cvar.set('foofunc')

    async def afoo():
        cvar.set('afoofunc')

    ipshell = InteractiveShellEmbed(config=Config())
    ipshell()


if __name__ == '__main__':
    run()
```


Here is in ipython prompt:

```
In [1]: cvar.get()
Out[1]: 'bar'

In [2]: foo()

In [3]: cvar.get()
Out[3]: 'foofunc'

In [4]: await afoo()

In [6]: cvar.get() == 'afoofunc'
Out[6]: False
```

**Comment by JarnoRFB** [comment]
I recently had a package that was build with `contextvars` that suddenly broke in jupyter notebooks. It would be great if this issue could be somehow addressed, as it might become a real problem if more packages start to rely on `contextvars` and simply break unexpectedly when used within ipython/jupyter.

Two observations that I made are:
1. The problem does not occur, when `Run all cells` is used.
2. The problem also does not seem to occur when Python 3.6 and the backport of `contextvars` is used, but that might well be related to what @njsmith described above.

**Comment by mdickinson** [comment]
This produces surprising results when changing the `decimal` precision (or other aspects of the decimal context) in notebooks, since `decimal` now uses a PEP 567 context variable for the decimal context.

Related: https://github.com/ipython/ipykernel/issues/494, https://github.com/jupyter/notebook/issues/5260

**Comment by SylvainCorlay** [comment]
Note:
This does not impact IPython, or the xeus-python kernel.
