### ISSUE TITLE
SQLite Warning Message

### ISSUE THREAD

**Issue by kstone001** [ipython/ipython#11577]
When I run a python program, I get the message -- warn "IPython History requires SQLite, your history will not be saved".  How do I correct this message?

**Comment by Carreau** [comment]
You need to install [sqlite](https://www.sqlite.org/index.html) usually it comes with Python, you likely want to reinstall, or install another version of Python. I suggest using https://anaconda.org/ for example.

**Comment by ArrivalR8** [comment]
Anaconda 2020.07  sqlite 3.32.3  Python 3.8.3

Error thrown @ IPython startup.  Yet sqlite is present and %hist works.

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\history.py:226: UserWarning: IPython History requires SQLite, your history will not be saved
  warn("IPython History requires SQLite, your history will not be saved")

Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [9]: !conda list -f anaconda
# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
anaconda                  2020.07                  py38_0

In [10]: !conda list -f sqlite
# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
sqlite                    3.32.3               h2a8f88b_0

**Comment by Kojoley** [comment]
This warning was removed in https://github.com/ipython/ipython/pull/12092
