### ISSUE TITLE
testing ipython documentation

### ISSUE THREAD

**Issue by stas00** [ipython/ipython#11573]
I tried to run the test suite manually as suggested to help sort out my PR https://github.com/ipython/ipython/pull/11572, but there is nowhere a word at how to do it, at least I couldn't find any.

Through digging I found I could get the tests running with:

```
cd ipython
pip install -e ".[test]"
mkdir results
cd results
iptest
```
Simply replicated `appveyor.yml`

To run groups of tests, e.g. core:

```
iptest core
```

but I can't figure out how to run an individual test, e.g. How do I run: `core.tests.test_iplib.doctest_tb_verbose` which is failing? If there is one of course - rerunning the whole group is quite inefficient, especially if several tests fail and I need to the see the logs for one of them.

Can this information on how to run tests please be added to CONTRIBUTING.md?

Also it looks like the doc here is outdated: https://github.com/ipython/ipython/blob/320d21bf56804541b27deb488871e488eb96929f/IPython/testing/iptest.py

> 2. With the regular nose syntax, like `iptest -vvs IPython`.  In this form
>   the script simply calls nose, but with special command line flags and
>   plugins loaded.

which doesn't work. `iptest: error: unrecognized arguments: -vvs`

Thanks.

**Comment by Carreau** [comment]
From the top of my head, you should be able to give `fully.qualified.name.of.the.test.module[:which_test_in_it]`

```
iptest IPython.core.tests.test_iplib:doctest_tb_verbose
```

I believe for convenience when you want to run a full test suite from a module you can also give the "path" (ie qualified named with `.` replace with `/`. I use it like so:

```
cd ~; iptest IPython/core/tests/test_iplib.py ; cd -
```

Which make it relatively convenient for tab completion, so the argument is not really a "path" and `.py` is stripped.

We could probably indeed add that to Contributing.md. 

@meeseeksdev tag "good first issue"

**Comment by stas00** [comment]
> iptest IPython.core.tests.test_iplib:doctest_tb_verbose

That worked. Thank you!

> We could probably indeed add that to Contributing.md.

Thank you!
