### ISSUE TITLE
adding %%skip magic

### ISSUE THREAD

**Issue by stas00** [ipython/ipython#11582]
Often it makes the coding more efficient when one is able to turn off multiple cells off. There are various workarounds at the moment, but they all have issues, the main one is that they require that each cell needs to be manually tweaked to turn it on/off. We need  a programmatic solution.

I like the %%skip magic implementation here, since you can control many cells at once by changing a value of a single variable anywhere in the notebook. https://stackoverflow.com/a/43584169/9201239

Can this be added to the ipython core? 

Quoting the SO answer:
---------------------------
You can create your own skip magic with the help of a custom kernel extension.

**skip_kernel_extension.py**

    def skip(line, cell=None):
        '''Skips execution of the current line/cell if line evaluates to True.'''
        if eval(line):
            return
            
        get_ipython().ex(cell)
        
    def load_ipython_extension(shell):
        '''Registers the skip magic when the extension loads.'''
        shell.register_magic_function(skip, 'line_cell')
    
    def unload_ipython_extension(shell):
        '''Unregisters the skip magic when the extension unloads.'''
        del shell.magics_manager.magics['cell']['skip']

Load the extension in your notebook:

    %load_ext skip_kernel_extension

Run the skip magic command in the cells you want to skip:

    %%skip True  #skips cell
    %%skip False #won't skip

You can use a variable to decide if a cell should be skipped by using $:

    should_skip = True
    %%skip $should_skip

---------------------------

So now I can have:
```
cell1: skip_a = False
       skip_b = True 
cell2: %%skip $skip_a
cell3: %%skip $skip_a
cell4: %%skip $skip_b
cell5: 
cell6: %%skip $skip_b
```

An even more flexible version would be able to define ranges of cells, so that we have a function-like scope:

```
cell1: skip_a = False
       skip_b = True 
cell2: %%skip -begin $skip_a
cell3: %%skip -end
cell4: %%skip -begin $skip_b
cell5: 
cell6: %%skip -end
```

Here cell5 gets skipped, since it's included in the scope defined by cell4 and cell6.

So now only 2 cells per group will need to be modified. 

So the proposed syntax is:

```
# skip current cell if True
%%skip True/False

# start a range of cells to skip if True
%%skip -begin True/False

# finish the range of cells to skip
%%skip -end 
```

But perhaps starting with just a basic version would be great.

The known manual workarounds are:
- comment out code of each cell
- switch to raw cell type
- %%cache magic https://github.com/rossant/ipycache
- freeze extension

**Comment by Carreau** [comment]
is there any reason to not use Python code for that: 

```
if variablename:
    # your code
```

Will likely have the same effect without requiring any IPython specific magic.

**Comment by stas00** [comment]
That would be yet another workaround, indeed - thank you for mentioning it. And it would require editing every cell in question, plus re-indenting each of them. and if you wanted to remove the skip conditional you again need to re-edit+re-indent all cells.

Now imagine 10 cells in a row that you could scope with just 2 entries and no re-indentation required, and just 2 steps to remove it should you want to undo it down the road.

```
cell1: skip_a = False
cell2: %%skip -begin $skip_a
cell3: 
[...]
cellN: %%skip -end
```
I guess the advanced proposed part of this feature is sort of emulating a function scope across multiple cells.

Perhaps it should be called %scope then? and one could then turn it on off? Just thinking aloud.

**Comment by stas00** [comment]
Another really cool approach would be able to enabled/disable all cells belonging to a heading, that would make things even easier for the user and it would allow for nested features, so one could disable just a sub-heading, or a all of subheadings belonging to a parent heading, but that I guess would belong to jupyter notebook, since I don't think ipython even has a concept of headings.

**Comment by Carreau** [comment]
> I guess the advanced proposed part of this feature is sort of emulating a function scope across multiple cells.



> Another really cool approach would be able to enabled/disable all cells belonging to a heading, that would make things even easier for the user and it would allow for nested features, so one could disable just a sub-heading, or a all of subheadings belonging to a parent heading, but that I guess would belong to jupyter notebook, since I don't think ipython even has a concept of headings.

the issue is that the backend/kernel does not know the ordering of cells, you have to mark each cell independently anyway. This looks more like an issue for the frontend, when you want to mark some cells with tags and execute only a subset of the tags. This is likely not something you want to kernel to know about. 

The tag approach will also work regardless of the language. 

This discussion come regularly and last time it was brought up people starting to ask for loop cell, goto cell... etc. I think if you really start to have that need, then you should start thinking about moving things into a library and using proper language constructs. Magics are convenience function but most of the time they are _just_ thin wrappers around things that Python already allows you to do. We really don't want to adventure too far into replicating the capabilities of Python.

**Comment by stas00** [comment]
> the issue is that the backend/kernel does not know the ordering of cells, you have to mark each cell independently anyway. 

OK, I guess this indeed would be better fitting into the jupyter notebook. Except, I don't feel inspired to even propose it there, since every issue I posted there so far has been ignored.

Thank you for the useful feedback, @Carreau.

**Comment by Salmck** [comment]
Errors will be occured when there are other magic commands after the %%skip line because function ipython.ex can not run magic commands successfully. Maybe replacing `get_ipython().ex(cell)` with  `get_ipython().run_cell(cell)` can fix the problem.
