### ISSUE TITLE
python seems operate ok but no outputs

### ISSUE THREAD

**Issue by xiaotianlangxing** [ipython/ipython#11586]
![image](https://user-images.githubusercontent.com/47234206/52100360-2bf11f00-2612-11e9-81f3-31b9d3aaa3cb.png)

import requests
from bs4 import BeautifulSoup
res=requests.get('https://news.sina.com.cn/china/')
res.encoding='utf-8'
soup=BeautifulSoup(res.text, 'html.parser')

I don't understand why there are no outputs? Is there anything wrong with cells?

**Comment by Carreau** [comment]
> I don't understand why there are no outputs? Is there anything wrong with cells?

No, there is just nothing to show. 

The first cell does not print (or return) anything. The last statement is an assignment, `soup=...` Ipython does not display the value of the last assignment. 

See the difference between finishing a cell with a value or an assignment: 

```
In [5]: 1
Out[5]: 1

In [6]: a=1

In [7]:
```

Nothing get printed when you assign to a. 

If you want to see `a` you'll have to put it alone on a line: 

```
In [12]: a=1
    ...: a
Out[12]: 1
```

second cell, `soup.select('.feed-card-item')` is an empty list:
```
In [1]: import requests
   ...: from bs4 import BeautifulSoup
   ...: res=requests.get('https://news.sina.com.cn/china/')
   ...: res.encoding='utf-8'
   ...: soup=BeautifulSoup(res.text, 'html.parser')

In [2]: soup.select('.feed-card-item')
Out[2]: []
```
I manually check the page, there is 0 `'.feed-card-item`
So you are looping over 0 items and thus printing none. 
Note that what you are getting with Beautifulsoup may differ from what you have in your browser if you need to log-in.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
