### ISSUE TITLE
IPython broken on 3.8-dev, due to changes to ast.Module

### ISSUE THREAD

**Issue by njsmith** [ipython/ipython#11590]
In [bpo-35766](https://bugs.python.org/issue35766), Guido merged the "typed_ast" code that mypy used to maintain back into main CPython parser. This means that starting in 3.8, the regular ast module will contain information on type comments and `type: ignore` comments.

The `type: ignore` comments are stored in a list on the `ast.Module` object. This list is now *mandatory*. That means that this code is broken:

https://github.com/ipython/ipython/blob/512d47340c09d184e20811ca46aaa2f862bcbafe/IPython/core/interactiveshell.py#L3191-L3192

So is this:

https://github.com/ipython/ipython/blob/512d47340c09d184e20811ca46aaa2f862bcbafe/IPython/core/interactiveshell.py#L3199-L3200

[BTW, why does one of those say `'cell_name'` and the other says `cell_name`? Seems like one of those must be wrong... CC: @Carreau]

When you create a `Module` like this and try to `compile` it, then you get:

```
  TypeError: required field "type_ignores" missing from Module
```

On 3.8+, to create a `Module` object you have to instead write `ast.Module(nodelist, [])`.

I filed a bug on python ([bpo-35894](https://bugs.python.org/issue35894)), and Guido responded that the details of the AST like this aren't considered stable API, so he considers this a bug for IPython to fix, not a regression on CPython. So, now I'm filing a bug here instead :-).

The full changes [are here](https://github.com/python/cpython/pull/11645/files), and [AFAICT this line](https://github.com/python/cpython/pull/11645/files#diff-4d06871e531085389da207d32d01a005R6) is the one that's breaking IPython.

**Comment by Carreau** [comment]
Closed by #11593

**Comment by Carreau** [comment]
Hi there, You seem to run IPython on Python 3.8; do you mind trying #11713 that tried to make use of the new 3.8b1 (not out yet) top-level await ?

**Comment by njsmith** [comment]
I just run it in ci, I don't have a local build handy.
