### ISSUE TITLE
Problem with indentation in the `run_cell` method

### ISSUE THREAD

**Issue by grumpfou** [ipython/ipython#11594]
Hi,

When using the InteractiveShell method `run_cell`, there is a problem when the string to execute begins with a line that contains only 4 spaces. It then does not handle properly  the indentations of the subsequent loops.
![image](https://user-images.githubusercontent.com/3619520/52297665-21969400-2936-11e9-800e-95262a98436d.png)

Tested on JupyterNotebook, JupyterLab and the Ipython interactive shell in the terminal.

Config:
- jupyter --version 4.4.0
- ipython --version 7.0.1
- python3 --version Python 3.6.7
- Ubuntu 18.04.1 LTS

**Comment by Carreau** [comment]
Yes, the IPython machinery is attempting to detect leading indent and remove them. This is to handle text that might be copy-pasted from other source (like the web) that may include leading indent. 

It will also automatically strip leading `>>>`, `...`, `... :` and `In [x]` prompt.

**Comment by rgson** [comment]
How about trimming based on the line with the least amount of leading whitespace? Or at least ignoring whitespace-only lines? Seems like that would be less error-prone.

**Comment by Carreau** [comment]
There are a lot of historical reason for the current behavior; one of them is that often when copy-pasting from the web the first line does not have the same amount of whitespace than the others. So looking at the line with the least WS may not work. 

I believe it make sens to ignore the first line if it's only whitespace – ignoring all line with only WS may work as well. I'd be happy to look at a PR that does that.

**Comment by rgson** [comment]
@Carreau PR submitted.

I am able to run the example provided by @grumpfou without errors after the proposed change.

I refrained from removing all blank lines due to the increased complexity of handling e.g. multi-line strings containing blank lines. It shouldn't be necessary, anyway.
