### ISSUE TITLE
Interactive shell does not complete members for property values

### ISSUE THREAD

**Issue by vmalloc** [ipython/ipython#11609]
Trying to import this code into IPython:

```python
class Container:

    @property
    def member(self):
        return Member()


class Member:
    def foo(self):
        pass

    def bar(self):
        pass
```
And then performing:

```
In[1]: from example import Container
In[2]: c = Container()
In[3]: c.member.<TAB>
```
The above does not offer completions for methods of `member`. This used to work on previous versions (e.g. 7.1.1) but broke at 7.2.0. Is this intentional? If so, is there a configuration that changes this back to the old behavior?

We rely on the introspection of properties and descriptors to achieve many goals in our projects, including API discoverability and other features.

Thanks in advance!

**Comment by letalvoj** [comment]
It does not work for pandas either (I do not think that column access is implemented as a property). Surprisingly `<SHIFT>+<TAB>` works. See the following example:

```
>>> df = pd.Series([1,4,3],name='col').to_frame()
>>> df.col.#<SHIFT>+<TAB> doc pops up :)
>>> df.col.#<TAB> nothing pops up :(
```

the kernel knows, that `col` is a Series and also it knows it's value. Yet the `<TAB>` completion does not work, yet it apparently could.

**Comment by letalvoj** [comment]
OK, the issue in my case was that I was using a [latest jupyterlab docker image](https://github.com/jupyter/docker-stacks/tree/master/scipy-notebook), which has jedi on by default. When I set 
```python
%config Completer.use_jedi = False
```
the issue is gone.

**Comment by flying-sheep** [comment]
I think that’s related to davidhalter/jedi#1299: Basically it’s impossible to correctly infer the type of properties without executing them. However, I think it should be possible to statically infer the types of properties that don’t have branching code and always return the same type.

**Comment by MrMino** [comment]
It's most likely something specific to Jedi. Anyhow, it's no longer reproducible on 8.2:

![image](https://user-images.githubusercontent.com/6691643/160299439-77e5e5d8-4620-49f7-b936-778136b95bac.png)

If anyone is still running to this issue, please ping us here - we'll reopen.
