### ISSUE TITLE
ipython.org/news.html page is outdated

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [ipython/ipython#11611]
As of 2019.02.20 11:51 a.m. GMT, the page https://ipython.org/news.html shows 7.2.0 as the latest release.
IPython 7.3.0 was released two days ago (2019.02.18).

Consider adding a reminder to update this page to your release process document https://ipython.readthedocs.io/en/stable/coredev/index.html#ipython-release-process

**Comment by Carreau** [comment]
Yes it is listed in the tasks to finish relasing 7.3 in #11571 

> Consider adding a reminder to update this page to your release process document https://ipython.readthedocs.io/en/stable/coredev/index.html#ipython-release-process

It is already point 10.  

Help to do that is welcomed, even more this time for a dumb reason I've cut my right index cooking and typing is still literally painful. So I'm slow and don't have much time outside of $DAYJOB to do all these small tasks :-)

**Comment by Carreau** [comment]
Closed by https://github.com/ipython/ipython-website/pull/144 , Thanks @Vlad-Shcherbina !
