### ISSUE TITLE
Function arguments autocompletion

### ISSUE THREAD

**Issue by martinRenou** [ipython/ipython#11624]
Say I have a function like that:
```Python
from ipywidgets import FloatSlider

def foo(**kwargs):
    # Do some stuff...
    return FloatSlider(**kwargs)
```

I would like to trick IPython into thinking that my `foo` function has some keyword arguments (Relevant `FloatSlider` traits: `value`, `min`, `max`, etc.). I tried something like:
```Python
foo.__code__.co_varnames = ('value', 'min', 'max')
```
But Python complains `AttributeError: readonly attribute`, and I'm scared I would break the function anyway.

Does anyone has an idea on how to achieve that cleanly?

**Comment by Carreau** [comment]
Assign to `__signature__` maybe ? You might be able to either give it a string, or a signature object on recent enough Python ?

**Comment by martinRenou** [comment]
Thanks a lot for your answer! I did not know you could change the `__signature__` of the function

This is madness...
```Python
from inspect import signature, Parameter

def foo(**kwargs):
    return FloatSlider(**kwargs)

foo.__signature__ = signature(foo).replace(parameters=[
    Parameter(name='min', kind=Parameter.KEYWORD_ONLY), 
    Parameter(name='max', kind=Parameter.KEYWORD_ONLY)
])
```

It does the trick, ipython will autocomplete `min` and `max` arguments. I'm not sure I would put it in my code though. Not really feeling confident about it.

The thing is that changing the signature does not change the way it is called by Python. Meaning that this code:
```Python
def foo(x, y): 
     print("Hello")

foo.__signature__ = signature(foo).replace(parameters=[
    Parameter(name='x', kind=Parameter.POSITIONAL_OR_KEYWORD), 
    Parameter(name='name', kind=Parameter.POSITIONAL_OR_KEYWORD)
])

foo(name=4, x=5)
```
leads to `TypeError: foo() got an unexpected keyword argument 'name'`

So I guess changing the signature is only safe if the function was originally taking `*args, **kwargs` as arguments.

**Comment by maartenbreddels** [comment]
This can be really useful for widgets right?

**Comment by martinRenou** [comment]
Definitely :)

**Comment by Carreau** [comment]
If you ever ends up writing a decorator that automate some of this stuff it would be helpful for matplotlib . I would love a 

```
@extra_kwargs_are_passed_to(pyplot.axis)
def plot(...)
```

>  I'm not sure I would put it in my code though. Not really feeling confident about it.

`__signature__` is made to be overwritten for decorators, and other function-modifying-object. 
Stdlib decrators like [`@wraps`](https://docs.python.org/3/library/functools.html#functools.wraps) make use of it to expose the original function signature. So yes it's purely decorative :-) 

It's also useful for c-defined function that cant' be inspected. So please use heavily :-)

**Comment by maartenbreddels** [comment]
```python
import traitlets
class Test(traitlets.HasTraits):
    a = traitlets.Int(1)
    min = traitlets.Int()
    widget = traitlets.Instance(object)
    value = traitlets.Unicode()

from inspect import signature, Parameter, Signature

def create_parameter(cls, name):
    trait = getattr(cls, name)
    if trait.default_value == traitlets.Undefined:
        default = Parameter.empty
    else:
        default = trait.default_value
    return Parameter(name=name, kind=Parameter.KEYWORD_ONLY, default=default)

def fix_signature(cls):
    cls.__init__.__signature__ = cls.__signature__ = signature(cls).replace(parameters=
    [
        create_parameter(cls, trait_name)
        for trait_name in cls.class_trait_names()
        if not trait_name.startswith('_')
    ]
)
fix_signature(Test)
```
If I do `Test(val<tab>` it will not autocomplete :(
it seems wraps actually sets __wrapped__
IPython 7.2.0

**Comment by maartenbreddels** [comment]
FYI, the same behaviour with wraps, using tab you see the arguments in the popup window/help, but tab completion does not work.

**Comment by btel** [comment]
@maartenbreddels it's interesting to see how attrs solved this problem:

https://github.com/python-attrs/attrs/blob/4fe28966e88b9b85c9c2df77ffb34f70175c4492/src/attr/_make.py#L1651

I think it's something that could be implemented in traitlets. Also it might help to catch constructor arguments that were not defined.

**Comment by martinRenou** [comment]
> If I do Test(val<tab> it will not autocomplete :(

Assigning to `__signature__` only works for ipython=7.1.1. I guess it's because for this version jedi was not used. And jedi [does not take into account the `__signature__`](https://github.com/davidhalter/jedi/issues/1058)
