### ISSUE TITLE
[Travis CI] Error for Python 3.7 in Linux

### ISSUE THREAD

**Issue by LucianaMarques** [ipython/ipython#11620]
Hi there,

I submitted PR #11617 and it's not passing on Travis. The following message error appears:
```

Warning, treated as error:
/home/travis/build/ipython/ipython/docs/source/whatsnew/development.rst:45:Unexpected indentation.
Makefile:66: recipe for target 'html' failed
make: *** [html] Error 2
make: Leaving directory '/home/travis/build/ipython/ipython/docs'
The command "if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  pip install -r docs/requirements.txt
  python tools/fixup_whats_new_pr.py
  make -C docs/ html SPHINXOPTS="-W"
fi
" exited with 2.
```

I'm not understanding what's happening here. All the other tests are passing, and I'm not sure how to test .rst files, but I'm not getting why it's complaining about Python 3.7 exactly... 

Thank you

**Comment by Carreau** [comment]
The critical line is the follwoing: 
```
/home/travis/build/ipython/ipython/docs/source/whatsnew/development.rst:45:Unexpected indentation.
```

I've fixed it for you. RST is a bit tricky with indentation.

**Comment by LucianaMarques** [comment]
> The critical line is the follwoing:
> 
> ```
> /home/travis/build/ipython/ipython/docs/source/whatsnew/development.rst:45:Unexpected indentation.
> ```
> 
> I've fixed it for you. RST is a bit tricky with indentation.

Ooops! Thanks! :)

**Comment by Carreau** [comment]
Fixed and merged :-) Thanks.
