### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by gpotter2** [ipython/ipython#11623]
Hi!
I'm a maintainer of [secdev/scapy](https://github.com/secdev/scapy), and was wondering how IPython managed to make such beautiful executables (especially on Windows)

We're under a GPLv2 license which is fairly permissive. Are we allowed to copy/paste some content of, let's say, https://github.com/ipython/ipython/blob/master/setupbase.py, if we credit IPython, add the License header and link to it ?

Thanks !

**Comment by gpotter2** [comment]
We’ve ended up dropping distutils. That way we don’t use any IPython code

**Comment by Carreau** [comment]
Hi, Sorry for not responding to this. Happy you got it to work, and if ever you need to take some code from IPython, yes feel free it's BSD licensed. 

Thanks !
