### ISSUE TITLE
output not showing on Jupyter while pressing shift+enter

### ISSUE THREAD

**Issue by hriday535** [ipython/ipython#11637]
Team,

Below code on text file not showing output of a blank figure after pressing shift+enter on Jupyter , please let me know

import numpy as np
import matplotlib.pyplot as plt

def main():
    
    # a blank figure
    
    fig=plot.figure()
    plot.show()

On jupyter while putting in cell   %run w.py , and pressing shift+enter, it took to only next cell instead of output of a blank figure

please advise : )

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.

**Comment by hriday535** [comment]
Thnx Matthias Bussonnier, i am new to github, i am not sure how to open the issue in the right repository, please advise

**Comment by Carreau** [comment]
> i am new to github, i am not sure how to open the issue in the right repository, please advise

No problem, If you are unsure,  I would suggest opening an issue on our forum: https://discourse.jupyter.org/ and sign-in using GitHub (you may need to disable add blocker to see the "login with GitHub" button., then you can re-enable).

I've also edited  your above comment to have proper syntax highlighting; feel free to click to `edit` to see how I modified it. 

from what I can see you are creating a function called `main` but never calling it via `main()`; so I would not be surprised that nothing shows. 

You may want to take a step back and go to forums about learning Python (https://www.reddit.com/r/learnpython/) for example. There are also some good resources on youtube if you prefer videos.
