### ISSUE TITLE
interrupting during post_execute handler crashes kernel process

### ISSUE THREAD

**Issue by jsnydes** [ipython/ipython#11630]
repro in normal usage:
1) https://mybinder.org/v2/gh/ipython/ipython-in-depth/master?filepath=binder/Index.ipynb AKA try.jupyter.org

2) add and run the following cell:
```
%matplotlib inline
!wget http://mlr.cs.umass.edu/ml/machine-learning-databases/adult/adult.data
import pandas as pd
train = pd.read_csv("adult.data")
train.apply(pd.value_counts).plot(kind='bar', subplots=True)
```

3) this will hang for a good long while. Interrupt execution (i, i) and then, while the matplotlib post_execute handler is still running, interrupt again (you have a few seconds here, but not much longer)

expected result:
no matplotlib output, cell execution completes with original KeyboardInterrupt traceback displayed

actual result:
kernel crashes

minimal repro:
1) try.jupyter.org as above
2) add and run the following cell:
```
def raiser():
  raise KeyboardInterrupt
import IPython
ev = IPython.get_ipython().events
ev.register('post_execute', raiser)
```
IIUC the cause of this is `except Exception` located here:
https://github.com/ipython/ipython/blob/a2685d78f2403f84e6cb915ae11a4f6033ccc5f6/IPython/core/events.py#L89
this could be `except BaseException` or, if too scary, `except (Exception, KeyboardInterrupt)`

sys_info:
{'commit_hash': '523ed2fe5',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/srv/conda/lib/python3.6/site-packages/IPython',
 'ipython_version': '7.2.0',
 'os_name': 'posix',
 'platform': 'Linux-4.14.65+-x86_64-with-debian-buster-sid',
 'sys_executable': '/srv/conda/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.6.7 | packaged by conda-forge | (default, Nov 21 2018, '
                '02:32:25) \n'
                '[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]'}

**Comment by gpotter2** [comment]
Could be closed.

**Comment by jsnydes** [comment]
thanks :)
