### ISSUE TITLE
jupyter notebook not running my code

### ISSUE THREAD

**Issue by Sabby2337** [ipython/ipython#11635]
hi everyone .I have just started using python 3 and is not able to get output when i run the code and i am getting new empty cells everytime i am hitting
![screenshot 18](https://user-images.githubusercontent.com/37585343/53936632-84fc1900-40d0-11e9-8339-95765531d72a.png)
![screenshot 18](https://user-images.githubusercontent.com/37585343/53936636-8af1fa00-40d0-11e9-8020-7cd755dcf5e8.png)

 run .Please help me in solving this issue

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
