### ISSUE TITLE
Print generator as lists

### ISSUE THREAD

**Issue by mathieulongtin** [ipython/ipython#11645]
In IPython, every time a function returns an iterator, it just prints something like this:
```
In [48]: Path("/tmp").glob("*.txt")
Out[48]: <generator object Path.glob at 0x7f7d7dd351b0>
```
So then, you have to do this:
```
In [54]: list(_)
Out[54]:
[PosixPath('/tmp/abc.txt'),
 PosixPath('/tmp/def.txt'),
...
```

Shouldn't the pretty printer expand the content of the generator when that's what's returned by the command? That's usually what I want. Now I have to litter my IPython sessions with `list(...)`.

**Comment by Carreau** [comment]
Well, a generator can: 
1) be infinite
2) exhaust itself once iterated over. 

So printing it as a list cannot be the default option, as in many case it would break. If a generator want to have a nice repr, it needs to implement it explicitely. 


Example of breaking a generator by printing it: 

```
In [1]: gen  = (i for i in range(10))

In [2]: gen
Out[2]: <generator object <genexpr> at 0x1083d9db0>

In [3]: list(gen)
Out[3]: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]: next(gen)
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-4-6e72e47198db> in <module>
----> 1 next(gen)

StopIteration:
```

Closing as I don't beelive we can do anything, but feel free to comment and we can reopen.

**Comment by mathieulongtin** [comment]
1. When pretty printing a long list, IPython will truncate it, it could do the same for generators
2. When calling a function that returns a generator without assigning to a variable, it's already kind of exhausted. Sure it's in `_`, but it's not that useful.

We do it such as printing a variable, prints the <generator... thing
```
In [1]: gen  = (i for i in range(10))

In [2]: gen
Out[2]: <generator object <genexpr> at 0x1083d9db0>
```
But this prints the result:
```
In [1]: (i for i in range(10))
Out[1]: [0,1,2,3,4,5,6,7,8,9]
```

Or as an option. I'm just annoyed at constantly having to do `list(_)`, especially for things that used to return a list but now return a generator in Python 3+.

**Comment by tacaswell** [comment]
```python
In [1]: gen  = (i for i in itertools.count())
```

This can not be truncated as we can never reach the end of it to decide where to truncate it!

```python
In [1]: gen  = (i for i in range(10))                                                                                                                                                                                                                                                                

In [2]: list(gen)                                                                                                                                                                                                                                                                                    
Out[2]: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]: list(gen)                                                                                                                                                                                                                                                                                    
Out[3]: []

In [4]:     
```

I slightly different look at @Carreau 's example.  Printing the generator mutates it!

**Comment by mathieulongtin** [comment]
Why do you need to reach the end to decide to truncate it? Read enough to fill the screen and stop there.

**Comment by Carreau** [comment]
That because in most cases for arrays the middle is truncated. You usually want to know the length to decide where to truncate. We could iterate only on a few but again this still raises above problem about exhausting iterators. I disagree that assignment to _ is useless anyway, as you proved you used it in list. Generators also represent sometime large computation (dask for example). Lazyness is on purpose and peaking at the first element could have arbitrary side effects.

If you want to register a display hook that does this you can do it without changing IPython source. But it will not be the default.

History the completed was trying to be smart about looking in generators and it was more trouble than anything, even sometime triggering external API call which broke some prod system. So we're going to be really careful about this if ever done.

**Comment by mathieulongtin** [comment]
Display hook? That sounds good. Thanks for the tip.
