### ISSUE TITLE
Does ipython support a feature of scroll past end?

### ISSUE THREAD

**Issue by ghost** [ipython/ipython#11655]
Allow the ipython to be scrolled past the end of last line.

Considering of visual facts, typing at bottom of ipython feel not comfortable.

**Comment by Carreau** [comment]
I'm not quite sure what you are requesting. Most of the terminal handling is not done by IPython itself, so I doubt this is something that IPython can fix or implement.

**Comment by yiran7324** [comment]
My problem is that most of the terminal like things can only scroll to the last line without any space, so if the terminal get to the bottom of our screen, working seems to be not comfortable watching the bottom. Put more space beyond the last line, that is what I am requesting. ^_^

**Comment by MrMino** [comment]
For this to work, IPython would have to start as a full-screen application (the same way e.g. vim does). I don't think this is something that would ever happen. This request is better suited as something for your terminal emulator to implement, not IPython.
