### ISSUE TITLE
Blank screen on Chrome, Edge and IE.

### ISSUE THREAD

**Issue by INT-ZC** [ipython/ipython#11652]
In the console, it first returns 302 errors like:
`[I 18:45:24.226 NotebookApp] 302 GET /tree? (::1) 1.00ms`
And after a while, it shows tons of 404. 
![image](https://user-images.githubusercontent.com/28757366/54588909-5ab73d80-4a78-11e9-9f7e-efc679613ac0.png)

And in the broswer, there are serveral js errors:
![image](https://user-images.githubusercontent.com/28757366/54589128-e5983800-4a78-11e9-8a34-3cc7b240c8da.png)

**Comment by INT-ZC** [comment]
Tried to use WSL (Debian) for jupyter notebook and failed again.
`[W 19:55:49.327 NotebookApp] 404 GET /static/components/preact-compat/preact-compat.min.js.map (127.0.0.1) 2.40ms referer=None`

**Comment by Carreau** [comment]
If you are on windows, I bet something messed-up your registry and associated `text/plain` with javascript file. And/or, your anti-virus is acting up. 

Side note, this repository is just for IPython, not the notebook, and we are trying to organize request-for-help vs code issues in proper channels to ensure you everyone get proper response in time. You may want to ask for help [on discourse](https://discourse.jupyter.org). You may also find more relevant information in https://github.com/jupyter/notebook

**Comment by redhermes** [comment]
I am getting the same result blank screen with 404 errors on Windows 10

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.

**Comment by redhermes** [comment]
For anybody else that falls into this, it's actually a bug in jupyter, see:  
https://github.com/jupyter/notebook/issues/4467
