### ISSUE TITLE
No release notes for 5.8

### ISSUE THREAD

**Issue by asmeurer** [ipython/ipython#11661]
There are no release notes for 5.8 listed at https://github.com/ipython/ipython/blob/master/docs/source/whatsnew/version5.rst. At the very least it should have a heading for 5.8 so that it is clear that it exists. I know this is an old release, but it's the last one that supports Python 2, which is why I care about it.

**Comment by Carreau** [comment]
Its is probably only on the 5.x branch: 

https://github.com/ipython/ipython/blob/5.x/docs/source/whatsnew/version5.rst

> IPython 5.8.0
> Update inspecting function/methods for future-proofing. #11139 

I'll update on master.
