### ISSUE TITLE
The __del__ is not called in time when __repr__ is called.

### ISSUE THREAD

**Issue by blackball** [ipython/ipython#11668]
The issue could be reproduced by: 

```python
class Obj:
    def __init__(self):
        print("__init__")
    def __repr__(self):
        return "__repr__"
    def __del__(self):
        print("__del__")

# In IPython Shell
[1] a = Obj()
__init__
[2] a = None
__del__
[3] a = Obj()
__init__ 
[4] a
__repr__
[5] a = None
[6] # __del__ is not called 
```

At [4], when the IPython called a.__repr__ the object could not be called in time, but at when the shell exits. This built-in python shell has the same issue, but I would like to know the reason and if possible, how could I make the object deconstructed when it's assigned to None or deleted by del function. 

Thanks!

**Comment by Carreau** [comment]
I can see a couple of reasons; I would have to dig into which ones exactly cause that. 

There is a shadow namespace for history, You can access it in the REPL via: 

```
ip = get_ipython()
ip.user_global_ns  # there are a couple others. 
```

There is likely a reference around. 

This is what amoung other powers `_`, `__` and `___` that allow you to access previous result if you forgot to assign.

**Comment by blackball** [comment]
Thanks for your reply. Now I know the reason, but is there a way to explicitly release the object from ipython ?

**Comment by blackball** [comment]
Since this is not an issue of ipython. close.
