### ISSUE TITLE
How to determine if zeromq channel is active?

### ISSUE THREAD

**Issue by MSeal** [ipython/ipython#11694]
I had a use-case with https://github.com/nteract/scrapbook/issues/42 where detecting if the code executing doesn't have a zeromq channel established should maybe emit a warning or error. I don't need to know if there is a notebook associated, but just knowing that the execution context is inside a kernel is sufficient since non-notebook kernel clients could be possible.

**Comment by Carreau** [comment]
I'm quite unsure, I guess that would be a question for @minrk once back from leave.

**Comment by MSeal** [comment]
I think, maybe `hasattr(get_ipython(), "kernel")` does the trick based on reading the codebase, but I'm not positive this is set in all situations.

**Comment by minrk** [comment]
`get_ipython().kernel` is indeed the correct and official check for this. Use `getattr(get_ipython(), 'kernel', None)`, though. `hasattr` is close, but it would be more robust to check if it's defined and None.

Here's a snippet style used in some packages for detecting 1. am I in IPython, and 2. if so, is it a Jupyter kernel without unnecessary imports that is as light as possible when called not from an IPython environment:


```python
in_ipython = False
in_ipython_kernel = False

# if IPython hasn't been imported, there's nothing to check
if 'IPython' in sys.modules:
    from IPython import get_ipython
    ip = get_ipython()
    in_ipython = ip is not None

if in_ipython:
    in_ipython_kernel = getattr(ip, 'kernel', None) is not None
```

**Comment by MSeal** [comment]
Thanks @minrk
