### ISSUE TITLE
Where to manipulate display.audio view

### ISSUE THREAD

**Issue by ThetomekK** [ipython/ipython#11696]
Hi all,

Could anyone give me kindly a hint, where the display.audio view can be manipulated? 

Thanks

**Comment by ThetomekK** [comment]
Hi there,

I got it, it's within the audio tag.

**Comment by ThetomekK** [comment]
Please close, this issue isn't worth staying marked open, thx

**Comment by Carreau** [comment]
You may want to look at the ipywidget package for more advance Audio display. 

Closing, thanks.
