### ISSUE TITLE
curicreate包

### ISSUE THREAD

**Issue by guoyufengfeng** [ipython/ipython#11697]
jupyter notebook里面导入curicreate这个包出错

**Comment by Carreau** [comment]
You will need to give a longer explanation, like or example the error message. 

您需要提供解释，例如错误消息或示例。

This is also the wrong repository you may want to ask on jupyter/notebook or on our discourse forum. (https://discourse.jupyter.org/)

这也是您可能想要在jupyter / notebook或我们的论坛上询问的错误存储库。(https://discourse.jupyter.org/)
