### ISSUE TITLE
function arguments autocompletion does not look correct

### ISSUE THREAD

**Issue by stphnlyd** [ipython/ipython#11692]
See this screenshot.

![tab_completion_problem](https://user-images.githubusercontent.com/20906652/56223345-24350880-60a0-11e9-92fd-3c08c61c9a96.png)

**Comment by Carreau** [comment]
I see what you mean,it is a really good question,  but with the dynamic nature of python the completer can't figure everything out. And take the following (contrived) example: 

```
$ ipython
Python 3.7.1 (default, Dec 14 2018, 13:28:58)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0.dev -- An enhanced Interactive Python. Type '?' for help.

In [1]: class FA:
   ...:     def __abs__(self):
   ...:         return 'myfile.csv'

In [2]: abs(FA())
Out[2]: 'myfile.csv'

In [3]: import pandas as pd

In [4]: pd.read_csv(abs(FA())
```

It totally works. Now what you wish are heuristics, as human most likely the first argument you want is a filename. We would love to see that, and if you want to contribute we'll be happy to get your contributions. 

As this is not a "bug" per se, I'm going to close, but feel free to keep commenting, and send Pull requests to improve the completer code !

**Comment by stphnlyd** [comment]
But if you compare it with some older version of ipython, like with 5.8.0 the arguments are shown correctly. 

![图片](https://user-images.githubusercontent.com/20906652/56423824-6d739b00-62e0-11e9-85b3-2fd09681a76e.png)

**Comment by GBpauloh** [comment]
I can confirm (and sadly feel the same pain) @stphnlyd's issue.

In my case, I'm using

```
Python          3.7.3
IPython         7.7.0
jedi            0.15.1
parso           0.5.1
prompt_toolkit  2.0.9
```

**Comment by paulochf** [comment]
I can confirm (and sadly feel the same pain) @stphnlyd's issue.

In my case, I'm using

```
Python          3.7.3
IPython         7.7.0
jedi            0.15.1
parso           0.5.1
prompt_toolkit  2.0.9
```
