### ISSUE TITLE
Cannot install Ipython 7.x

### ISSUE THREAD

**Issue by bharadwajth** [ipython/ipython#11710]
I'm on `ipython` version 5.8.0. I've been trying to upgrade it but am unsuccessful. My `pip` version is 19.1. Even when I uninstall and install it again, I land only on ipython 5.8.0.

What am I missing?

![Screen Shot 2019-05-05 at 2 59 03 PM](https://user-images.githubusercontent.com/8296827/57200212-6090b180-6f46-11e9-8ff4-0400fc7941e3.png)

**Comment by Carreau** [comment]
You are running Python 2.7; Ipython 6+ do not support Python 2.7. 
Written in yellow at the top of your screen. 

Upgrade your Python; or stay with IPython 5.x. 

Closing as there is nothing we can do, but feel free to keep commenting. 

Thanks
