### ISSUE TITLE
Arrow printed twice for autocall

### ISSUE THREAD

**Issue by asmeurer** [ipython/ipython#11714]
```py
In [1]: %autocall
Automatic calling is: Smart

In [2]: print 1
------> print(1)
------> print(1)
1
```

The `------> print(1)` line should only be displayed once.

**Comment by asmeurer** [comment]
The problem is that cell transformers are called twice. Once in `should_run_async` https://github.com/ipython/ipython/blob/f14271fe2b0f9627f64848466de944befc7c29c9/IPython/core/interactiveshell.py#L2901 and once in `run_cell_async` https://github.com/ipython/ipython/blob/f14271fe2b0f9627f64848466de944befc7c29c9/IPython/core/interactiveshell.py#L2967. 

This is an issue for all cell transformers, not just autocall. It means that any input transformer will be run twice, which is an issue if it has side effects (such as printing stuff to the terminal) 

I don't know a whole lot about the code, but it seems to me that the transforms shouldn't be run in `should_run_async`. The comment there implies that it is done so that that exceptions are shown before execution. Won't this happen from the call in `run_cell_async` as well? 

It seems this was added in https://github.com/ipython/ipython/commit/64e14897ee532b995a8eaf40829cc380dc453ca3.

CC @minrk @takluyver

**Comment by Carreau** [comment]
The right way is tricky; we might have to break some public API and ass a flag in many of those to know wether some code is async or not. 

I'm working on  patch to CPython that should mitigate that by adding a flag to `compile()` that allows top-level await, and mark the code_object with `CO_COROUTINE`, with this on 3.8 the `should_run_async` _should_ not be called anymore.

**Comment by asmeurer** [comment]
Is it not possible to transform the cell before calling `should_run_async`, and keeping the transformed code from there on out?

**Comment by Carreau** [comment]
Sure, but we need to know later on wether the code need to run in the `exec` or `async_exec` path, 
and for that either we need to carry around a flag that tell us wether the code is async or not, – or recompute the value. 

We went to for recompute the value to not change the signature of all the functions in the stack.

**Comment by asmeurer** [comment]
The transformers are also called here https://github.com/ipython/ipython/blob/380db0d7241372f9c12d5d5aaaa8e7e4c70575d5/IPython/core/inputtransformer2.py#L623

**Comment by Carreau** [comment]
See also https://github.com/ipython/ipython/pull/12456
