### ISSUE TITLE
Tab completion of paths in string closes the string

### ISSUE THREAD

**Issue by asmeurer** [ipython/ipython#1172]
Say I have a file `mydir/myfile.txt` in the current directory.  If I want to open this file, I will do `open('myd<TAB>`, but this types (assuming there is nothing else starting with `myd`, `open('mydir/'`.  Do you see what it did there? It closed the string.  

It does this for all path completions in strings.  As soon as it hits the end of a directory, it closes the string. This is, as you can imagine, very annoying if you're trying to complete to a fairly nested file.

I don't mind closing the string when it hits the end of the path, by the way (though there should perhaps be an option to turn it off, as it too could be annoying in certain situations).

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.
Now that we use prompt_toolkit, the readline limitations no longer apply - and I think the default behavior does not close filename quotes.

Thanks everyone and happy hacking! :bowtie:
