### ISSUE TITLE
Pygments version error for python 3.4.x

### ISSUE THREAD

**Issue by ihorss** [ipython/ipython#11725]
> IPython 6.x requires Python version 3.3 and  above.

But now I've got next error for python 3.4.3:
`ERROR: Pygments requires Python '>=2.7, !=3.0.*, !=3.1.*,   !=3.2.*, !=3.3.*, !=3.4.*' but the running Python is 3.4.3`

So after last Pygment release (that don't support python 3.4 due to [Pygment  setup.py](https://bitbucket.org/birkenfeld/pygments-main/src/default/setup.py)) ipython can`t be installed on python 3.4.x becouse there is no specified version for Pygment in your requirements in setyp.py 

> install_requires = [
    'setuptools>=18.5',
    'jedi>=0.10',
    'decorator',
    'pickleshare',
    'traitlets>=4.2',
    'prompt_toolkit>=2.0.0,<2.1.0',
    'pygments',
    'backcall',
]

**Comment by Carreau** [comment]
I'm confused, 

I don't see the issue; you can install IPython without the latest pygments; 
I just installed a perfectly working version of IPython in a fresh Python 3.4 install, and it pulled pygments 2.3.1: 

```
$ conda create -n 3.4 python=3.4 pip
...
$ conda activate 3.4
...
$ pip install ipython
...
$ ipython
Python 3.4.5 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:47:57)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pygments

In [2]: pygments.__version__
Out[2]: '2.3.1'
```

Do you by any chance hav an old version of pip ?

**Comment by nouiz** [comment]
I got this problem too. I have the feeling that some of pygments packages aren't well done. For example for me it installed a version that isn,t compatible with my version of python. I downgraded pygment to 2.1.3 and it fixed this error. Just in case other people search for this error, downgrading pygment fixed it for me.

https://github.com/Theano/Theano/pull/6717
