### ISSUE TITLE
ipython does not color underscore in numerals

### ISSUE THREAD

**Issue by ssantichaivekin** [ipython/ipython#11739]
In Python, underscores are ignored when placed inside numerals. For example, `1_000_000` is just the same as `1000000`. Underscore in numerals should be treated as part of the numeral in syntax hilighting, but that doesn't happen in ipython, as shown below.

<img width="146" alt="Screen Shot 2019-05-19 at 2 38 21 PM" src="https://user-images.githubusercontent.com/19219105/57979176-175f5800-7a44-11e9-8e00-fc965a817fda.png">

**Comment by Carreau** [comment]
That's likely an upstream pygments issue; the code to highlight is not in IPython itself.

**Comment by jmansilla** [comment]
It's working for me (now at least)
 
<img width="168" alt="Screen Shot 2019-06-22 at 10 49 46" src="https://user-images.githubusercontent.com/488675/59964773-93cdd680-94db-11e9-9b48-791d99395b13.png">

**Comment by MrMino** [comment]
This is not reproducible on current versions of IPython. Should anyone run into this problem again - don't hesitate to ping us here, we'll reopen the issue.
