### ISSUE TITLE
Consider applying black to the user-code in the REPL CLI

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#11735]
See https://github.com/ipython/ipython/pull/11734 and https://twitter.com/Mbussonn/status/1128841958711889920 

- flag/option to turn on and of. 
  - Opt-in or opt-out ? 
- Apply only when pressing enter at the end of the buffer (?)
- should we mark black as dependency at install time ? 
  - still want to function properly w/o black installed.

**Comment by drunkwcodes** [comment]
* Opt-in in v7.
* Before dumping the history of several executions.
* Yes but it shouldn't.

**Comment by boyuan12** [comment]
Can I try to work on this issue?

**Comment by Carreau** [comment]
> Can I try to work on this issue?

Yes, but you might want to check I believe there is now the option `--TerminalInteractiveShell.autoformatter='black'` tha might already do some reformatting.

**Comment by MrMino** [comment]
I believe this is _in_, since #11734 was merged.

@Carreau Is there anything else left to do here?

**Comment by Carreau** [comment]
I think just making it enabled by default in one of the major next versions would be the next step. But we can also close.

**Comment by Carreau** [comment]
Now it's the default.
