### ISSUE TITLE
Code syntax highlighting in JupyterLab

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipython#11747]
https://github.com/jupyterlab/jupyterlab/issues/6376 pointed out that IPython is hard-coding Jupyter Notebook css classes in its output of syntax-highlighted code blocks. It should be pretty easy to also add JupyterLab's css class so that these blocks also work in JupyterLab.

The discussion on https://github.com/jupyterlab/jupyterlab/issues/6376 points out what class to add and where to add it. @bensteers said he'd try to put in a PR here.

**Comment by Benjamin-Lee** [comment]
Waiting on this with bated breath!

**Comment by Notgnoshi** [comment]
Here's a temporary workaround for anyone who needs a fix in the meantime.

```python
import IPython

def display_source(code) -> IPython.display.Code:
    def _jupyterlab_repr_html_(self):
        from pygments import highlight
        from pygments.formatters import HtmlFormatter

        fmt = HtmlFormatter()
        style = "<style>{}\n{}</style>".format(
            fmt.get_style_defs(".output_html"), fmt.get_style_defs(".jp-RenderedHTML")
        )
        return style + highlight(self.data, self._get_lexer(), fmt)

    # Replace _repr_html_ with our own version that adds the 'jp-RenderedHTML' class
    # in addition to 'output_html'.
    IPython.display.Code._repr_html_ = _jupyterlab_repr_html_
    return IPython.display.Code(data=code, language="python3")
```

**Comment by MrMino** [comment]
Is this still relevant? I cannot reproduce this in JupyterLab anymore.

**Comment by krassowski** [comment]
@MrMino Yes, It is still relevant. I can reproduce it in latest JupyterLab with IPython 7.29.0 and 7.30.0 with the example given in https://github.com/jupyterlab/jupyterlab/issues/8734#issuecomment-981764906 and with your test case from https://github.com/ipython/ipython/pull/13131#issuecomment-924500790:

```python
IPython.display.Code("""def all_the_colors():\n    return 123\n""", language='python')
```

![Screenshot from 2021-11-29 16-46-24](https://user-images.githubusercontent.com/5832902/143908533-1bee00f1-92fb-4e25-9dd7-ddc8489904cf.png)

**Comment by pnsvk** [comment]
> ```python
> ```python
>     return IPython.display.Code(data=code, language="python3")
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
>       
> ```

the snippet by @Notgnoshi works like a charm.. in case someone needed a quick-fix to get along.

**Comment by MattAlp** [comment]
Very excited for when this is fixed :)

**Comment by DonJayamanne** [comment]
For those interested in this issue, i've made a proposal for returning a custom mime type.
I believe that would help front ends better handle syntax highlighting for this scenario.
See here https://github.com/ipython/ipython/issues/13795

**Comment by westurner** [comment]
Why does pygments inline all of those style declarations?

I went to fix a few pygments syntax highlighting things with Ctrl-Shift-I for inspect element ( because jlab traps right click), and noticed that e.g. strings have `<span style="color:rgb(175,0,0)">` instead of `<span class="pyg-str">`? Is there a browser performance reason to inline all of those styles?

- [ ] create a pygments issue
- https://github.com/timkpaine/jupyterlab_miami_nights/issues/71
