### ISSUE TITLE
cleanup >3.5 conditional.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#11749]
We still have some code to handle pre-3.5 Python; 
It is not supported anymore so can be removed.

**Comment by gdhameeja** [comment]
If open, I'd like to work on this.

**Comment by kd2718** [comment]
Does this still need to be done? Is there an example of cleanup code you can show to point in the right direction?

**Comment by kd2718** [comment]
@Carreau looks like [this](https://github.com/ipython/ipython/blob/a9a72474c49d9c0a90ace5ee332ddd9d490b1a98/IPython/core/interactiveshell.py#L2261) is the kind of code you want cleaned up?

**Comment by Carreau** [comment]
Sorry I missed these comments; Yes that was the kind of things to simplify. This one has been done. There are a few other; I've opened #11954 and #11955 for example. 

Thanks.
