### ISSUE TITLE
Speedup slow timeit test

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#11751]
The test `test_timeit_arguments` take way too long, running just this test takes 10s:

```
$ cd ; iptest IPython.core.tests.test_magic:test_timeit_arguments ; cd -

Test group: IPython.core.tests.test_magic:test_timeit_arguments
.
----------------------------------------------------------------------
Ran 1 test in 9.534s

OK

______________________________________________________________________
Test suite completed for system with the following information:
[...SNIP...]
Status: OK (1 test groups). Took 10.077s.
```

The reasons is that we _actually_ try to time the operation instead of just making sure it's valid syntax. Simply adding `-n1 -r1` to the test should speed up the test greatly. 

A patch for this issue would be something like

```diff
@ IPython/core/tests/test_magic.py:1168 @ def test_time_no_var_expand():
 def test_timeit_arguments():
     "Test valid timeit arguments, should not cause SyntaxError (GH #1269)"
     if sys.version_info < (3,7):
-        _ip.magic("timeit ('#')")
+        _ip.magic("timeit -n1 -r1 ('#')")
     else:
```

Help welcome to fix this issue.

**Comment by LucianaMarques** [comment]
I did some testing on my machine and tests are taking longer actually ( > 15s) even after the modifications. I guess I could send the PR but I'm not sure this will solve the problem.
