### ISSUE TITLE
Image.display should take os.PathLike

### ISSUE THREAD

**Issue by alok** [ipython/ipython#11758]
Most of that module takes a `filename=...` argument but fails if the filename is `pathlib.Path`. This could be abstracted over like `FileLink` does.

**Comment by Carreau** [comment]
That seem reasonable; do you want to attempt a PR?

**Comment by alok** [comment]
Sure thing. Do I only have to change https://github.com/ipython/ipython/blob/master/IPython/core/display.py?

**Comment by Carreau** [comment]
> Sure thing. Do I only have to change https://github.com/ipython/ipython/blob/master/IPython/core/display.py

Likely yes, I had a quick look and it seem you will only have to touch "Image","DisplayObject" and "_find_ext".

**Comment by Carreau** [comment]
closed by #11764  thanks !
