### ISSUE TITLE
Change number of autocomplete results displayed

### ISSUE THREAD

**Issue by mlucool** [ipython/ipython#11757]
Hi,

Is there a way to change the number of autocomplete results displayed? For example, I'd like to see 5 rows of results, instead of 4 as there is now:
![image](https://user-images.githubusercontent.com/1813603/58505604-52a40a00-815b-11e9-8e3e-fa47fe7f6563.png)

I tried looking in the code and could not see where the number of rows is determined or if this is settable.
 
I am using:
Python 3.7.3
IPython 7.3.0

Thanks!

**Comment by LucianaMarques** [comment]
@Carreau could this be considered a feature request? :)

**Comment by ngoldbaum** [comment]
I think to get this to work, `prompt_toolkit` would first need to expose this as an option for the completion interface. IPython would then need to expose that option as a configuration variable.

**Comment by Carreau** [comment]
I believe this is the `TerminalInteractiveShell.space_for_menu` option, it is not   directly related to completions as it also affect backward search.
