### ISSUE TITLE
Error while opening jupiter notebook

### ISSUE THREAD

**Issue by Prasanna-530** [ipython/ipython#11763]
(base) C:\Users\Prasu>jupyter notebook
[W 10:28:19.134 NotebookApp] Permission to listen on port 8888 denied
[W 10:28:19.134 NotebookApp] Permission to listen on port 8889 denied
[W 10:28:19.134 NotebookApp] Permission to listen on port 8890 denied
[W 10:28:19.134 NotebookApp] Permission to listen on port 8891 denied
[W 10:28:19.134 NotebookApp] Permission to listen on port 8892 denied
[W 10:28:19.134 NotebookApp] Permission to listen on port 8891 denied
[W 10:28:19.134 NotebookApp] Permission to listen on port 8787 denied
[W 10:28:19.134 NotebookApp] Permission to listen on port 8806 denied
[W 10:28:19.144 NotebookApp] Permission to listen on port 8832 denied
[W 10:28:19.144 NotebookApp] Permission to listen on port 8985 denied
[W 10:28:19.144 NotebookApp] Permission to listen on port 8854 denied
[W 10:28:19.144 NotebookApp] Permission to listen on port 8848 denied
[W 10:28:19.144 NotebookApp] Permission to listen on port 8798 denied
[W 10:28:19.144 NotebookApp] Permission to listen on port 8961 denied
[W 10:28:19.144 NotebookApp] Permission to listen on port 8964 denied
[W 10:28:19.144 NotebookApp] Permission to listen on port 8841 denied
[W 10:28:19.144 NotebookApp] Permission to listen on port 8869 denied
[W 10:28:19.144 NotebookApp] Permission to listen on port 8862 denied
[W 10:28:19.144 NotebookApp] Permission to listen on port 8932 denied
[W 10:28:19.144 NotebookApp] Permission to listen on port 8958 denied
[W 10:28:19.144 NotebookApp] Permission to listen on port 8812 denied
[W 10:28:19.144 NotebookApp] Permission to listen on port 8803 denied
[W 10:28:19.144 NotebookApp] Permission to listen on port 8789 denied
[W 10:28:19.154 NotebookApp] Permission to listen on port 8880 denied
[W 10:28:19.154 NotebookApp] Permission to listen on port 8875 denied
[W 10:28:19.154 NotebookApp] Permission to listen on port 8980 denied
[W 10:28:19.154 NotebookApp] Permission to listen on port 8855 denied
[W 10:28:19.154 NotebookApp] Permission to listen on port 8820 denied
[W 10:28:19.154 NotebookApp] Permission to listen on port 8904 denied
[W 10:28:19.154 NotebookApp] Permission to listen on port 8923 denied
[W 10:28:19.154 NotebookApp] Permission to listen on port 8986 denied
[W 10:28:19.154 NotebookApp] Permission to listen on port 8835 denied
[W 10:28:19.154 NotebookApp] Permission to listen on port 8874 denied
[W 10:28:19.154 NotebookApp] Permission to listen on port 8840 denied
[W 10:28:19.154 NotebookApp] Permission to listen on port 8794 denied
[W 10:28:19.164 NotebookApp] Permission to listen on port 8842 denied
[W 10:28:19.164 NotebookApp] Permission to listen on port 8977 denied
[W 10:28:19.164 NotebookApp] Permission to listen on port 8807 denied
[W 10:28:19.164 NotebookApp] Permission to listen on port 8902 denied
[W 10:28:19.164 NotebookApp] Permission to listen on port 8931 denied
[W 10:28:19.164 NotebookApp] Permission to listen on port 8915 denied
[W 10:28:19.164 NotebookApp] Permission to listen on port 8853 denied
[W 10:28:19.164 NotebookApp] Permission to listen on port 8928 denied
[W 10:28:19.164 NotebookApp] Permission to listen on port 8930 denied
[W 10:28:19.164 NotebookApp] Permission to listen on port 8856 denied
[W 10:28:19.164 NotebookApp] Permission to listen on port 8932 denied
[W 10:28:19.164 NotebookApp] Permission to listen on port 8796 denied
[W 10:28:19.164 NotebookApp] Permission to listen on port 8922 denied
[W 10:28:19.174 NotebookApp] Permission to listen on port 8795 denied
[W 10:28:19.174 NotebookApp] Permission to listen on port 8786 denied
[W 10:28:19.174 NotebookApp] Permission to listen on port 8979 denied
[C 10:28:19.174 NotebookApp] ERROR: the notebook server could not be started bec
ause no available port could be found.

Not able to open jupyter notebook. If its because of antivirus, what to do in such a case? 
Nothing seems to work in anaconda app on my desktop, if i try to create any file, its throwing error.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
