### ISSUE TITLE
Missing keyboard shortcuts documentation after v6.5.0

### ISSUE THREAD

**Issue by DavidAntliff** [ipython/ipython#11797]
It looks like something went wrong with the keyboard shortcuts documentation generation after version 6.5.0:

Here in v6.5.0, the full list of shortcuts is documented:
https://ipython.readthedocs.io/en/6.5.0/config/shortcuts/index.html

In the next version, and **all newer versions** (to current 7.5.0), it's missing almost all of them:
https://ipython.readthedocs.io/en/7.1.0/config/shortcuts/index.html

**Comment by Carreau** [comment]
That's likely because we change version of prompt_toolkit, and should figure out how to get the default bindings to appear on this page.

**Comment by farisachugthai** [comment]
I'd imagine:

[./ipython/docs/autogen_shortcuts.py](../ipython/blob/master/docs/autogen_shortcuts.py)

is the relevant code if that helps at all.

**Comment by MrMino** [comment]
This is still very much relevant in 8.x stream.
