### ISSUE TITLE
Road to 8.0.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#11816]
This is a meta issue to track the road to IPython 8.0
It is there to track the potential large changes and discuss them.

I'll try to keep this top comment edited to reflect the status of the thread.

**Comment by Carreau** [comment]
Suggestions

1) use black on all the things and have a bot/ci that autoformat pull-requests. IE not _fail_ on improperly formatted code to not annoy user. The main question is: do we run black at once on the full codebase ?

2) Drop Nose, test using Pytest. It's still a bit annoying as we are so far stuck on pytest 3, and moving to pytest 4 or 5 will be a significant effort. Some test still only run w/ nose (doctests) and need to be migrated.

3) Completer refactor... this can be a lot of work and is a change of API.

**Comment by gpotter2** [comment]
I'd like to have "Resolve the issues with the completer" on the roadmap.
see https://github.com/ipython/ipython/pull/11804

**Comment by Carreau** [comment]
Yes, that would be a good idea as well.

**Comment by terrdavis** [comment]
Suggestions:
* Remove [deprecated](https://github.com/ipython/ipython/blob/4842416da03f3cc04897bd8731e851c2f0c0e734/IPython/core/debugger.py#L247) [color_scheme](https://github.com/ipython/ipython/blob/4842416da03f3cc04897bd8731e851c2f0c0e734/IPython/core/debugger.py#L221) argument in `core.debugger`.
* Remove other deprecated items (esp. those deprecated before ipython5).
* Remove python 2 specific imports. I found `reprlib`, `winreg`, and `tkinter` with a search for `py 2`.

**Comment by terrdavis** [comment]
> Suggestions
>
>1. use black on all the things and have a bot/ci that autoformat pull-requests. IE not fail on improperly formatted code to not annoy user. The main question is: do we run black at once on the full codebase ?
>...

[Yes](https://twitter.com/llanga/status/1163767833706323970)
It appears that it's possible to specify commits to be ignored by git blame by pointing `blame.ignoreRevsFile` to a file with the commit hashes corresponding to formatting commits.

**Comment by Carreau** [comment]
> * Remove python 2 specific imports.

That does not need to wait for 8.0 if they are 2.x only.


> It appears that it's possible to specify commits to be ignored by git blame by pointing `blame.ignoreRevsFile` to a file with the commit hashes corresponding to formatting commits.

I saw that it's new in git 2.23; I haven't found the default name for this ignore file; it would be nice for users to not have to explicitly configure git; so if you find how to do that; it would be nice.

**Comment by terrdavis** [comment]
I recently implemented a variant of the idea in my previous post:
* Put the revs to ignore in `.git-blame-ignore-revs` (see [this post](https://public-inbox.org/git/c34159af-f97e-82b3-e2a1-04adae5c10ac@google.com) for rationale on the name, and confirmation that there's no default file name).
```
# When making commits that are strictly formatting/style changes, add the
# commit hash here, so git blame can ignore the change.
# see docs for more details:
# https://git-scm.com/docs/git-config#Documentation/git-config.txt-blameignoreRevsFile

<full commit hash>  # initial black-format
<full commit hash>  # rename something internal
```
* Create a batch script (and corresponding shell script) `configure-git-blame-ignore-revs.bat` containing:
```batch
rem other config options for blame are markUnblamables and markIgnoredLines.
rem see docs for more details:
rem https://git-scm.com/docs/git-config#Documentation/git-config.txt-blameignoreRevsFile

git config blame.ignoreRevsFile .git-blame-ignore-revs
git config --get blame.ignoreRevsFile
```
* Explain in developer docs.

**Comment by Carreau** [comment]
I'm more and more convinced that this would be helpful.
If you want to send a pull-request that add these scripts in tools and update the readme that would be nice. At least we can focus the discussion in there; and once we run black on something we can decide to update this file. I'm guessing we can also likely look at the version of IPython; and if its `.dev`; ask user to run specific commands.

**Comment by Carreau** [comment]
Master is now going to be IPython 8.0. no target date yet, but API changes are now game.

**Comment by Carreau** [comment]
There is now a signed 8.0.0a1 tag, and I tried to release it, but there was some issues with the new setup.cfg and a few other changes. 
So the tag will likely not match  what 8.0.0a1 will be.

**Comment by Carreau** [comment]
```
Check the shasum for SOURCE_DATE_EPOCH=1640537471
$ shasum -a 256 dist/*
9a08b46fc4b90b2159c8b2d3c2ea32f5bf6f98e3ed5256b62ac91b2f76ebc362  dist/ipython-8.0.0b1-py3-none-any.whl
e49fb9a52bf13076930fdf484506567070f4afae1e050064b882dfef866458a8  dist/ipython-8.0.0b1.tar.gz
```

**Comment by bollwyvl** [comment]
Huzzah! I'll work on a conda-forge PR when next on keyboard.

**Comment by frenzymadness** [comment]
Hi there. Is there any schedule for IPython 8? I'm testing the beta 1 in Fedora with all dependant packages (more than 30) and it looks good to me so far. Only one problem has been uncovered in nbclient but I've already prepared a fix for that, see https://github.com/jupyter/nbclient/pull/190

**Comment by Carreau** [comment]
Probably some time next week or the week after, I'm mostly trying to find the time to write a blog post on jupyter.org and https://labs.quansight.org/ and find some time. 

I'm also in the middle of trying to find a new flat so that also affect my timeline in a bit of an unexpected way.

**Comment by frenzymadness** [comment]
Thanks for the info. I was just curious about how much the current tested status will diverge before the final release. In the next few weeks is more than fine.

Wish you good luck finding the flat you want.

**Comment by Carreau** [comment]
There was just one change for RC yesterday. Hopefully nothing but docs will
change now.
