### ISSUE TITLE
IPython 7.6 problem with %%time

### ISSUE THREAD

**Issue by jamesmyatt** [ipython/ipython#11811]
In IPython 7.6, the `%%time` magic is messing with the workspace. Looks like the last variable is never assigned in the workspace. This is a pretty serious error.

IPython 7.5.0 worked fine, so I assume it's related to https://github.com/ipython/ipython/pull/11716/. Also works fine when there's exactly one statement inside the cell.

```
In [1]:
%%time
a = 1
b = 2
c = 3
```

Wall time: 0 ns

```
In [2]:
a, b, c
```

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-6fd489e9d195> in <module>
----> 1 a, b, c

NameError: name 'c' is not defined
```

**Comment by Carreau** [comment]
Thanks for the report (this an previous issue), 
I'll try to get a fix and a minor release soon.

**Comment by Carreau** [comment]
Do you mind trying #11812 ? If it fixes it; I'll try to make a release before Friday.

**Comment by Carreau** [comment]
7.6.1 should now be released with a fix.

**Comment by jamesmyatt** [comment]
Thanks. It's working fine now.
