### ISSUE TITLE
Configure matplotlib backend - documentations inconsistencies

### ISSUE THREAD

**Issue by thrasibule** [ipython/ipython#11818]
I'm trying to change the matplotlib backend from the default (qt5) to gtk3. In the ipython_config.py file generated in the default profile, the option seems to be called ``InteractiveShellApp.matplotlib``, but setting it there seems to have no effect. However if I launch ipython with ipython --matplotlib 'gtk3', this works.

Looking further at the [reference](https://ipython.readthedocs.io/en/stable/interactive/reference.html) section of the docs, it mentions that running ``ipython --matplotlib qt`` is equivalent to setting the ``TerminalIPythonApp.matplotlib`` option. I tried to change it in the ipython_config.py file and it works indeed.

It seems to me that both the docs and the auto generated ipython_config.py file needs to be updated to reflect the correct option name?

**Comment by Carreau** [comment]
The documentation seem to be correct; the configuration system of IPython is just a bit complicated. 

configuration option can take precedence, and are of the form `c.ClassName.attribute=Value` inconfig files, or `--ClassName.attribute=Value` on the CLI.

The terminal Client  `$ ipython` is a `TerminalIPythonApp`, which is a subclass `InteractiveShellApp`, thus both `c.InteractiveShellApp.matplotlib=`, and `c.TerminalIPythonApp.matplotlib=` should work, but the more specific one will likely take precedence.  `--matplotlib` is just an alias; for convenience. 

`$ ipython --InteractiveShellApp.matplotlib=qt` works for me, so it is correct, `ipython --TerminalIPythonApp.matplotlib=qt` as well. 

There is a small difference between `InteractiveShellApp.matplotlib` and `TerminalIPythonApp.matplotlib`, as the former one will _also_ affect ipython kernels in Jupyter, while the later one will only affect CLI. 

My guess is you have the matplotlib options set somewhere else (and it takes precedence); or you have a typo (and IPython does not complain about typos, asany config option is potentially valid).

**Comment by thrasibule** [comment]
Thanks for the explanation that's very helpful. I tried on a fresh profile that I call ``test``
So if I do: ``ipython --profile=test --InteractiveShellApp.matplotlib=gtk3``, it works indeed. But if I uncomment ``c.InteractiveShellApp.matplotlib`` and set it to gtk in ipython_config.py it doesn't do anything (but setting ``c.TerminalIPythonApp.matplotlib=gtk`` works however. So there must be some non obvious precedence rule.

**Comment by Carreau** [comment]
That is really strange, Idid the same (with qt, I don't have GTK), and
setting c.InteractiveShellApp.matplotlib='qt'  ipython_config.py did setup
matplotlib backend for me.
Do you have any other machine where you can try this ?

**Comment by thrasibule** [comment]
Figured it out. I actually had an ``ipython_config.py`` lying around in my $HOME directory which seems to have higher precedence than the config file in .ipython/profile_test but less precedence than cli settings... Sorry about the noise.
