### ISSUE TITLE
AttributeError: module 'matplotlib' has no attribute 'interactive'

### ISSUE THREAD

**Issue by alessioarena** [ipython/ipython#11821]
Using the Ipython magic `%matplotlib widget` in jupyter lab causes the following error:

> ~\miniconda3_64\lib\site-packages\IPython\core\pylabtools.py in activate_matplotlib(backend)
>     304 
>     305     import matplotlib
> --> 306     matplotlib.interactive(True)
>     307 
>     308     # Matplotlib had a bug where even switch_backend could not force
> 
> AttributeError: module 'matplotlib' has no attribute 'interactive'

I am running the following module versions (I pasted only the ones I think are relevant):

```
ipykernel                 5.1.1            py36h39e3cac_0    conda-forge
ipympl                    0.2.1                 py36_1002    conda-forge
ipython                   7.1.1                    pypi_0    pypi
jupyter_client            5.3.1                      py_0    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_server            0.0.5                    py36_0    conda-forge
jupyterlab                1.0.1                    py36_0    conda-forge
jupyterlab_server         1.0.0                      py_1    conda-forge
matplotlib                3.0.1                    pypi_0    pypi
matplotlib-base           3.1.1            py36h2852a4a_0    conda-forge
```

Everything has been updated and upgraded using `conda` and the conda-forge channel to get the `jupyterlab => 1.0.0` version
I have `nodejs` and the `jupyter-matplotlib` extension freshly installed, but that should not matter at that point I think.

Please let me know if you need additional system info or tests done on this bug

**Comment by Carreau** [comment]
```
> matplotlib                3.0.1                    pypi_0    pypi
```

Please update matplotlib to latest stable, or install it from conda instalead of PyPI. You may need to `pip uninstall matplotlib`

Try `from matplotlib import interactive` from a python shell to se if that works.

**Comment by alessioarena** [comment]
Yes, I noticed that and I fixed the issue by installing everything using pip from a clean environment.
However, I believe that conda/conda_forge are currently breaking dependencies particularly if you are after Jupyterlab>= 1.0.0, matplotlib>=3.1 , geopandas and the latest ipywidgets.

For the moment I'm happy to mark this as closed

**Comment by tacaswell** [comment]
```
matplotlib                3.0.1                    pypi_0    pypi
matplotlib-base           3.1.1            py36h2852a4a_0    conda-forge
```

This is an exciting version missmatch!  conda-forge (and maybe defaults?) have started to spilt matplotlib into two parts: 'matplotlib-core' which is the actual code and 'matplotlib' which depends on 'matplotlib-core' and Qt.  This is so you can install matplotlib without installing all of Qt (which is nice for headless systems).  The problem is likely that you are seeing files that are from a mix of versions.

**Comment by Carreau** [comment]
Tom, I gave you triage rights here in case you need to label/close matplotlib related issues on this repo. 
I don't _expect_ you to do it of course; just giving you the ability to do so. 

@alessioarena happy that it works now !
