### ISSUE TITLE
Allow cell in cell magics to use f-string interpolation

### ISSUE THREAD

**Issue by jseabold** [ipython/ipython#11826]
It looks like it might just not be written, but is there a reason not to do variable expansion on the cell in the same way you do the line in line and cell magics?

It looks like I'd just need to add the variable expansion also for the cell [here](https://github.com/ipython/ipython/blob/5073312daa51b62aceb06626cf265d2da1836c7a/IPython/core/interactiveshell.py#L2342).

**Comment by Carreau** [comment]
Cells magics post-date line magics, and we decided to no try to modify the values passed to a cell magic, so that magics implementors could decide wether or not to try-to do expansion. 

DO you have an example of what you are trying to achieve ?

**Comment by jseabold** [comment]
Make something like this work

```%%sql_query {DATABASE_URI}

{SQL_STATEMENT}
```

In addition to this which does work

```%sql_query {DATABASE_URI} {SQL_STATEMENT}```

**Comment by Carreau** [comment]
That should be pretty straitforward: 

```python
from IPython.core.magic import Magics, magics_class, cell_magic
@magics_class
class SQL(Magics):

    @cell_magic
    def sql_query(self, line='', cell=''):
        print(cell.format(**self.shell.user_ns))

ip = get_ipython()
ip.register_magics(SQL)
```
```
>>> QUERY='MYQUERRY'
>>> %%sql_query a
... {QUERY}
MYQUERRY

```

The reason we don't do it by default, is that you may not always want to expand  `{...}`, it's easy to opt-in, but would be hard to opt-out from.

**Comment by jseabold** [comment]
Yeah, that makes sense. I was looking at the stateful magics for this, but then I read the code linked above. Isn't that what the [`MAGIC_NO_VAR_EXPAND_ATTR`](https://github.com/ipython/ipython/blob/5073312daa51b62aceb06626cf265d2da1836c7a/IPython/core/interactiveshell.py#L2347) is intended to do? I was just wondering whether it's an accident of history that it's used for lines and not cells.

**Comment by Carreau** [comment]
No, making it the default for line was a mistake (good choice at the time, but annoying later –  magics pre-dates decorators and used to used to start with @...), but backward-compatibility is what it is. 

So it is indeed not expanding in cell body is on purpose.
