### ISSUE TITLE
My Jupyter notebook looks different to others and "Tabs" key doesn't bring up a list. 

### ISSUE THREAD

**Issue by henri-kt** [ipython/ipython#11828]
Hello, 

I recently installed "Jupyter notebook" via anaconda, but my notebook looks different from those in tutorials online. I also can't seem to get the "Tab" button to bring up the dropdown list for " .islower, .isupper, .istitle, etc.." 

Any ideas on how to get around this?

Thanks in advance

<img width="1274" alt="Screenshot 2019-07-17 at 13 52 55" src="https://user-images.githubusercontent.com/52918621/61377008-3c344800-a89a-11e9-8aa6-d2b8ec270312.png">

**Comment by alexmojaki** [comment]
You are using JupyterLab, the successor to notebooks. That's meant to be a good thing.

I don't know the answer to your question, but there's some discussion about it here: https://github.com/jupyterlab/jupyterlab/issues/4487

**Comment by Carreau** [comment]
If you want to open "classic" notebook from within lab, try "help > open classic notebook".

**Comment by Carreau** [comment]
Thanks @alexmojaki for the response.

**Comment by henri-kt** [comment]
Thank you for your reply. Much appreciated.

**Comment by sepehr86-y** [comment]
how we can make is upper?????????????????

**Comment by kevintcaron** [comment]
> Hello,
> 
> I recently installed "Jupyter notebook" via anaconda, but my notebook looks different from those in tutorials online. I also can't seem to get the "Tab" button to bring up the dropdown list for " .islower, .isupper, .istitle, etc.."
> 
> Any ideas on how to get around this?
> 
> Thanks in advance
> 
> <img alt="Screenshot 2019-07-17 at 13 52 55" width="1274" src="https://user-images.githubusercontent.com/52918621/61377008-3c344800-a89a-11e9-8aa6-d2b8ec270312.png">

did you ever resolve this? I don't see any option for classic anywhere.
