### ISSUE TITLE
Change command that will be putted in history

### ISSUE THREAD

**Issue by voronind** [ipython/ipython#11824]
Can I define magic command that will be change own value in history?
For example
```python
>>> a = 1
>>> %mymagic    # after that last command in history is "%mymagic a = 1" for example
```

**Comment by Carreau** [comment]
I don't believe there is an easy way. History is meant to store history as is.

But maybe if you tell me _why_ you want that; we can find a workaround

**Comment by voronind** [comment]
```python
>>> some + expression
>>> %magic _       # do magic with last expression
```
I want that last command was `%magic some + expression` for quicker editing expression

**Comment by Carreau** [comment]
I don't see an easy way to do this beyond doing `up arrow` `Home` and typing `%magic`; you might want to poke around at `ip = get_ipython()` and `ip.history_manager`

**Comment by voronind** [comment]
Thank you very much for answer
