### ISSUE TITLE
Keep async event loop alive between cells

### ISSUE THREAD

**Issue by mehaase** [ipython/ipython#11829]
The `%autoawait` magic is amazing! It works very smoothly with asyncio and I've had a great time using it.

When it comes to Trio, however, the current integration is pretty limited, because Trio has a notion of _structured concurrency_, which means that all concurrent tasks must belong to a specific parent (called a "nursery" in Trio parlance). Therefore, if an object needs to run any tasks (e.g. a connection object that needs a background task to read incoming network data), that object's lifetime is bound to a nursery, and a nursery's lifetime is bound to the block of a context manager. The effect is that any object that needs to spawn a long-lived Trio task can only be used within a single cell.

Here's an example:

![trio example in jupyter notebooke](https://aws1.discourse-cdn.com/free1/uploads/trio/original/1X/0316414c7c7dba62147ac35908a07e6b6c34c462.png)

If I execute the second cell here, it will hang for a long time. Even though the `connect_websocket_url()` returns relatively quickly, the `async with` block will stay open as long as the connection's background task is running, i.e. as long as the connection itself is open.

On [the prototype async REPL issue](https://github.com/ipython/ipython/pull/11265#issuecomment-414944336), @njsmith mentioned the following:

> But we need to eventually reach a point of keeping the same loop alive over multiple cells, if we want this to be really useful.

I couldn't find any open issues tracking this idea to keep an event loop open between cells, so I'm opening this issue. I'm not sure how this would work in general, but for Trio specifically we probably want to call `trio.run()` once, run each cell as a task on this single Trio loop, and expose a global nursery object for launching background tasks that keep executing even when a cell isn't currently running.

I can contribute some time to helping out with this. I poked around some of the PRs and source code, but I'm not very familiar with IPython's internals, so I figure the best place to start is to brainstorm with those of you who understand the issues better than me.

**Comment by Carreau** [comment]
Thanks for opening this issue, and for the kind words ! 

There are actually two sides of this issue: 
   - in [ipykernel](https://github.com/ipython/ipykernel) tornado is running, so we likely need to swap the eventloop, or integrate both. 
   - In  terminal IPython we need to make [this](https://github.com/ipython/ipython/pull/11347)  work. 

I personally don't have enough time to goo deep the rabbit hole on these, but will do my best to help anyone with the motivation to do so.

**Comment by mehaase** [comment]
I started to look into this today, just trying to get familiar with how async is implemented and plan out some possible approaches. Over on the Trio Discourse, you said:

>  the kernel when using a notebook has a persistent running eventloop (tornado), I think it might be easier to just swap that for trio at startup to get native trio features.

I'm trying to understand the mechanics behind this idea. The two things I don't understand are:

1. The tornado event loop is started when the kernel starts. So would need to be specific by the user *before* starting the kernel? If the user runs `%autoawait trio` magic, then it's already too late by that point to pick which event loop to use?
2. ZMQ has integration with Tornado already, but not with trio, so if we switched the event loops, it seems like it would take a lot of work to continue using ZMQ (i.e. using ZMQ synchronously and running it in a separate thread?).

If you can provide guidance on these topics, it would be very helpful.

**Comment by dhirschfeld** [comment]
I ran into this problem with `autoawait` and `trio`:
https://gitter.im/python-trio/general?at=5f9b7c657cac87158f75a65e

...and @oremanj came with with a very cool solution using trio's new *guest mode*. Just linking here in case it can get integrated into IPython itself:
https://gist.github.com/oremanj/ab55690b866c84724a7c0cb120a08ef8

**Comment by njsmith** [comment]
Note that the gist there solves the problem of integrating trio with ipython similar to how asyncio is currently integrated with ipython, i.e. you have a single loop and do the equivalent of `run_until_complete` on each cell, and then while ipython is accepting input then none of the background tasks run.

For notebook integration, a similar solution could be used to run trio on top of the kernel's native asyncio loop, but the details would be different.

**Comment by mehaase** [comment]
FYI @dhirschfeld there is support for long-lived trio loop in this PR: https://github.com/ipython/ipython/pull/12097

It doesn’t use guest mode, though. (I don’t think guest mode existed when we created that PR.)
