### ISSUE TITLE
breakpoint debugger with tab expansion

### ISSUE THREAD

**Issue by nschloe** [ipython/ipython#11830]
There a multiple ways for breakpoint-debugging in Python, the most canonical one being [`breakpoint()`](https://www.python.org/dev/peps/pep-0553/) (from Python 3.7).
```python
def add(a, b):
    out = a + b
    breakpoint()
    return out / 2

val = add(4, 6)
# FIXME why isn't this 10?!
```
This gives you a simple console. Being used to IPython, I however would love to have an IPython console _with tab expansion_. I know there is [a debugger](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.debugger.html)
```python
from IPython.core.debugger import set_trace  
set_trace()
```
but it doesn't seem have tab expansion. Is there sometime I forgot to load here?

**Comment by Carreau** [comment]
I don't think tab completion was ever implemented for the debugger at least not into IPython. 

I would suggest to look at https://pypi.org/project/ipdb/ which does it though. 

Would that be what you are looking for ?

**Comment by nschloe** [comment]
Yup, thank you!
