### ISSUE TITLE
Jupyter.org Website Re-Design Effort.

### ISSUE THREAD

**Issue by tgeorgeux** [ipython/ipython#11839]
I wanted to make sure everybody is aware of the work being done on the Jupuyter.org re-design and has a chance to get involved if they wish. 

Please see the discourse post about the design:
https://discourse.jupyter.org/t/wip-re-design-of-jupyter-org-website/691/57

Also, we'd love input on the technical implementation:
https://github.com/jupyter/jupyter.github.io/issues/347

Thank you!

**Comment by MrMino** [comment]
This project has ended in December 2019. If anyone would like to get involved with improving the jupyter.org website, please go to http://github.com/Jupyter/jupyter.github.io.
