### ISSUE TITLE
?,?? command is not available

### ISSUE THREAD

**Issue by selfcs** [ipython/ipython#11843]
My OS is **Ubuntu 16.04** 。

python version is **Python 3.6.5 |Anaconda custom (64-bit)| (default, Apr 29 2018, 16:14:56)**。

ipython version is  **7.2.0**

but `?`,`??` is not available

![image](https://user-images.githubusercontent.com/49665472/62602539-98810980-b926-11e9-8c09-e8069dab6ba5.png)

**Comment by Carreau** [comment]
Remove the `()`; it is  a weird quirk, but as you see in the error message it less you

```Object `pd.read_csv()` not found.```

Not 

```Object `pd.read_csv` not found.```
