### ISSUE TITLE
ipython autocomplete does not work for module sys

### ISSUE THREAD

**Issue by laoshaw** [ipython/ipython#11847]
IPython 7.7.0, `import sys, sys.<TAB>` produces nothing, other modules are fine, is this a known bug?

**Comment by Carreau** [comment]
I believe this is now fixed in the latest jedi that was released a couple of hours ago. It does work for me (it can take a couple of seconds the first time to index everything).

**Comment by laoshaw** [comment]
confirmed, updated to jedi to 0.15.0 from 0.14.0 fixed this problem.
