### ISSUE TITLE
core.Pdb should accept skip argument

### ISSUE THREAD

**Issue by terrdavis** [ipython/ipython#11851]
The `skip` parameter (python 3.1+) is available in `pdb.Pdb` , but for some reason it's not included in IPython's debugger.  
The only other constructor parameters that aren't included are `nosigint` (3.2+),  and `readrc` (3.6+).

I have two proposals for the missing parameters:
1. Since IPython 7+ supports python 3.4+, add `skip` and `nosigint` to the signature.
OR
2. Pass `kwargs` through, automatically supporting python 3.6 fully.

I checked in the master branch and this change has not been made.

Annotated code snippet:
```python 
# IPython 7.5.0
# IPython.core.debugger
# snip
from pdb import Pdb as OldPdb
# snip
class Pdb(OldPdb):
    """Modified Pdb class, does not load readline.

    for a standalone version that uses prompt_toolkit, see
    `IPython.terminal.debugger.TerminalPdb` and
    `IPython.terminal.debugger.set_trace()`
    """

    def __init__(self, color_scheme=None, completekey=None,
                 stdin=None, stdout=None, context=5):  # add `skip=None`  or `**kwargs` here!

        # Parent constructor:
        try:
            self.context = int(context)
            if self.context <= 0:
                raise ValueError("Context must be a positive integer")
        except (TypeError, ValueError):
                raise ValueError("Context must be a positive integer")

        OldPdb.__init__(self, completekey, stdin, stdout)  # pass in `skip` or **kwargs here!
# snip
```
Links to annotated lines:
https://github.com/ipython/ipython/blob/fe0b87c2d05c172b064c54da1d3ae33d028f3ef5/IPython/core/debugger.py#L222
https://github.com/ipython/ipython/blob/fe0b87c2d05c172b064c54da1d3ae33d028f3ef5/IPython/core/debugger.py#L232
[pdb docs](https://docs.python.org/3/library/pdb.html#pdb.Pdb):
> class pdb.Pdb(completekey='tab', stdin=None, stdout=None, skip=None, nosigint=False, readrc=True)
> Pdb is the debugger class.
> 
>...
> 
> The skip argument, if given, must be an iterable of glob-style module name patterns. The debugger will not step into frames that originate in a module that matches one of these patterns.
>...
> New in version 3.1: The skip argument.
> 
> New in version 3.2: The nosigint argument. Previously, a SIGINT handler was never set by Pdb.
> 
> Changed in version 3.6: The readrc argument.

**Comment by Carreau** [comment]
As per [NEP29 (still in discussion)](https://github.com/numpy/numpy/pull/14086), I'm tempted to drop support for 3.5, (we've already dropped support for 3.4 already). 

So I'm open to accept a PR that is compatible 3.6+ only.  
One disadvantage of the `**kwarg` approach is that it does not allow you find the potential args that you can pass to the function when completing; though for PDB; i'm not sure it's super relevant. 

You seem to know what you are talking about, so feel free to send a PR; I might not get to it soon.

**Comment by terrdavis** [comment]
Would it be a reasonable compromise to inherit docstrings (primarily for class and constructor) so upstream API changes don't need to be discussed/manually incorporated?  
This is also relevant for `IPython.terminal.debugger.TerminalPdb`, which uses `*args, **kwargs` for its constructor signature.

**Comment by terrdavis** [comment]
I'm working on this now...
