### ISSUE TITLE
regarding aggressive debugging

### ISSUE THREAD

**Issue by vainaijr** [ipython/ipython#11861]
in the current state, I need to add set_trace after every function that I want to trace, how to do it automatically, so that I write set_trace once at the beginning of the notebook, and it is able to look inside functions that are called later.

how to use set_trace without writing it again and again, below every function / class / method?

**Comment by MrMino** [comment]
If you want to make this easier for yourself, you could look into [`breakpoint()`](https://peps.python.org/pep-0553/). Overall, the machinery of the debugger depends on the fact that it is called from within the frame that it is debugging. I don't think we have any good way of automating this.
