### ISSUE TITLE
Connecting to an existing kernel on a remote server while using spyder on my local machine

### ISSUE THREAD

**Issue by cerodell** [ipython/ipython#11879]
I'm having an issue connecting to an existing kernel on a remote server while using spyder on my local machine.

I am running spyder 3.3.6, I have installed miniconda and spyder-kernels on the remote server.

I launch `python -m spyder_kernels.console` on the remote server

Then on my local machine running spyder, I go the "gear" tab in the iPython console and click "connect to an existing kernel".

I check the "This is a remote kernel (VIA SSH)"
Type in hostname and password...then nothing..... won't connect.

Where am I going wrong?

Thank you in advance for your help!!!!!!!

**Comment by Rafiqul10** [comment]
i can help u sir,please download teamviewer, then send me mai

**Comment by ccordoba12** [comment]
@cerodell, you also need to install the `paramiko` package for that to work.
