### ISSUE TITLE
"Assertion failed: Connection reset by peer": what could I do about it?

### ISSUE THREAD

**Issue by maajdl** [ipython/ipython#11873]
Hello,

I am unable to use JupyterLab for more that a few hours. The same for JupyterNotebook.
Below is a copy of the console screen when the crash occurs as well as the Windows logs.
I have this problem since a long time, and I have re-installed Anaconda3 at least 4 times without resolving the issue.
I have seen that I am not alone wih this problem, but I know many people who do not have this problem.

Would you have a suggestion about how to look for the cause and find a practical solution?

Thanks

Michel

==============================================================
[I 23:26:08.445 LabApp] JupyterLab extension loaded from C:\Users\myasus\Anaconda3\lib\site-packages\jupyterlab
[I 23:26:08.445 LabApp] JupyterLab application directory is C:\Users\myasus\Anaconda3\share\jupyter\lab
[I 23:26:08.445 LabApp] Serving notebooks from local directory: C:\Users\myasus\Documents\_Work\Jupyter notebooks
[I 23:26:08.445 LabApp] The Jupyter Notebook is running at:
[I 23:26:08.445 LabApp] http://localhost:8888/?token=080bc3d02831103d726de11e1d1ada48197df38b4e55e25c
[I 23:26:08.445 LabApp]  or http://127.0.0.1:8888/?token=080bc3d02831103d726de11e1d1ada48197df38b4e55e25c
[I 23:26:08.445 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 23:26:08.507 LabApp]
    To access the notebook, open this file in a browser:
        file:///C:/Users/myasus/AppData/Roaming/jupyter/runtime/nbserver-6468-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=080bc3d02831103d726de11e1d1ada48197df38b4e55e25c
     or http://127.0.0.1:8888/?token=080bc3d02831103d726de11e1d1ada48197df38b4e55e25c
[I 23:26:11.255 LabApp] Build is up to date
[I 23:26:11.588 LabApp] New terminal with automatic name: 1
TermSocket.open: 1
TermSocket.open: Opened 1
[I 23:26:14.235 LabApp] Kernel started: 5e0d118d-6f3d-40c1-8b3e-40d58b4071d0
[I 23:26:17.504 LabApp] Adapting from protocol version 5.1 (kernel 5e0d118d-6f3d-40c1-8b3e-40d58b4071d0) to 5.3 (client).
[I 23:26:17.504 LabApp] Adapting from protocol version 5.1 (kernel 5e0d118d-6f3d-40c1-8b3e-40d58b4071d0) to 5.3 (client).
[W 23:26:20.123 LabApp] Got events for closed stream None
2019-09-01 23:26:40.726003: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow
 binary was not compiled to use: AVX2
2019-09-01 23:26:40.735857: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcu
da.dll
2019-09-01 23:26:40.967865: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce GTX 980M major: 5 minor: 2 memoryClockRate(GHz): 1.1265
pciBusID: 0000:01:00.0
2019-09-01 23:26:40.974296: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically li
nked, skip dlopen check.
2019-09-01 23:26:40.981406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-09-01 23:26:44.220150: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strengt
h 1 edge matrix:
2019-09-01 23:26:44.228235: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0
2019-09-01 23:26:44.232446: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
2019-09-01 23:26:44.245595: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/repli
ca:0/task:0/device:GPU:0 with 3236 MB memory) -> physical GPU (device: 0, name: GeForce GTX 980M, pci bus id: 0000:01:00.0, compute
capability: 5.2)
Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1549025594292\work\src\signaler.cpp:371)
Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1549025594292\work\src\signaler.cpp:371)
Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1549025594292\work\src\signaler.cpp:371)
Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1549025594292\work\src\signaler.cpp:371)
Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1549025594292\work\src\signaler.cpp:192)
Assertion failed: Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1549025594292\work\src\signaler.cpp:Connection re
set by peer [371)
10054] (C:\ci\zeromq_1549025594292\work\src\signaler.cpp:371)
Exception in callback BaseAsyncIOLoop._handle_events(1656, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(1656, 1)>
Traceback (most recent call last):
  File "C:\Users\myasus\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\myasus\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 138, in _handle_events
    handler_func(fileobj, events)
  File "C:\Users\myasus\Anaconda3\lib\site-packages\terminado\management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "C:\Users\myasus\Anaconda3\lib\site-packages\winpty\ptyprocess.py", line 189, in read
    data = self.fileobj.recv(size)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1549025594292\work\src\signaler.cpp:371)

==============================================================
Windows log,  Logged: 2019-09-02 02:11:23

Faulting application name: python.exe, version: 3.7.3150.1013, time stamp: 0x5cc0c771
Faulting module name: KERNELBASE.dll, version: 6.3.9600.19425, time stamp: 0x5d26b6e9
Exception code: 0x40000015
Fault offset: 0x000000000000908c
Faulting process ID: 0x1944
Faulting application start time: 0x01d5610bdda68fe4
Faulting application path: C:\Users\myasus\Anaconda3\python.exe
Faulting module path: C:\WINDOWS\system32\KERNELBASE.dll
Report ID: 31cb60c2-cd16-11e9-828b-5cc5d446f6c1
Faulting package full name: 
Faulting package-relative application ID: 

==============================================================
Windows log,  Logged: 2019-09-02 02:11:23

Faulting application name: python.exe, version: 3.7.3150.1013, time stamp: 0x5cc0c771
Faulting module name: KERNELBASE.dll, version: 6.3.9600.19425, time stamp: 0x5d26b6e9
Exception code: 0x40000015
Fault offset: 0x000000000000908c
Faulting process ID: 0xca0
Faulting application start time: 0x01d5610be11811c9
Faulting application path: C:\Users\myasus\Anaconda3\python.exe
Faulting module path: C:\WINDOWS\system32\KERNELBASE.dll
Report ID: 326286f1-cd16-11e9-828b-5cc5d446f6c1
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.
