### ISSUE TITLE
weird behaviour when using argument parser

### ISSUE THREAD

**Issue by vainaijr** [ipython/ipython#11871]
doing 
`args = parser.parse_args()`
gives error, changing it to
`args = parser.parse_args('')`
works fine

**Comment by Carreau** [comment]
Not quite sure if this related to ipython or not, please give a longer explanation of what you are doing. At least how you create `parser`.

**Comment by vainaijr** [comment]
recreated it here
https://colab.research.google.com/drive/1iNk-BA-BhkxmACtwhc8udWWQbCt9BTJY

**Comment by Carreau** [comment]
default behavior from `parse_arg` if you pass nothing is to look in `sys.argv`.
Sys `argv` contain the argument used to start the kernel.

So make sens, nothing weird there.

Closing.
