### ISSUE TITLE
ipython 7.8.0 error in Spyder IDE

### ISSUE THREAD

**Issue by GNSharmaa** [ipython/ipython#11887]
I have recently upgrade ipython 7.6 to 7.8 using piupgrade module. Everything went fine, but after upgrade when i restarted spyder it opened normally but ipython console shows following error. Please help!!
![Screenshot (27)](https://user-images.githubusercontent.com/55408142/64982912-ec472100-d8dc-11e9-93af-a2c21399793d.png)

**Comment by LucianaMarques** [comment]
Hi @GNSharmaa ,

Can you please copy here the traceback message instead of only leaving the image? It would be nicer to read it :)

Can you also please check whether there isn't any updates for Spyder as well?

**Comment by ccordoba12** [comment]
This problem occurs because you don't have write permissions in the last directory shown in your screenshot.

So this is not a problem with Spyder nor IPython. To fix it you need to fix those write permissions.

**Comment by GNSharmaa** [comment]
> Hi @GNSharmaa ,
> 
> Can you please copy here the traceback message instead of only leaving the image? It would be nicer to read it :)
> 
> Can you also please check whether there isn't any updates for Spyder as well?

Here is the message:
Traceback (most recent call last):
File "c:\python37\lib\site‑packages\spyder\plugins\ipythonconsole\plugin.py", line 1153, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle, **kwargs)
File "c:\python37\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "c:\python37\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "c:\python37\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "c:\python37\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "c:\python37\lib\site‑packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\PRACHI\\AppData\\Roaming\\jupyter\\runtime\\kernel‑c448e2a12b3f.json'

I just updated Spyder to 4.0.0.b5 and ipython to 7.8.0.
Also i didn't touched any files of python or spyder. I don't know how to grant permission. Please help me!

**Comment by ccordoba12** [comment]
You need to go this directory

C:\Users\PRACHI\AppData\Roaming\jupyter\runtime

with the Windows file explorer, do a right click on it and look for an option to change its permissions (I don't remember exactly where that's located because I don't use Windows but you can google for it).

**Comment by GNSharmaa** [comment]
> You need to go this directory
> 
> C:\Users\PRACHI\AppData\Roaming\jupyter\runtime
> 
> with the Windows file explorer, do a right click on it and look for an option to change its permissions (I don't remember exactly where that's located because I don't use Windows but you can google for it).

i checked the folder. Permissions are fine but issue is same. Please help!

**Comment by ndeeds** [comment]
I have this exact same issue after upgrading to spyder 3.3.3. Something changed in the way that permissions are being handled on the json file that is getting written to 

C:\Users\ndeeds.INTERA\AppData\Roaming\jupyter\runtime

I completely opened up permissions in the "runtime" folder:

![image](https://user-images.githubusercontent.com/16090529/65552567-59187780-deea-11e9-89ab-c89441e1d392.png)

And yet I still get this error when launching a kernel:

![image](https://user-images.githubusercontent.com/16090529/65552630-85cc8f00-deea-11e9-995f-2ccbac8723fa.png)

**Comment by ndeeds** [comment]
Commenting out this block solves the problem for me. Maybe it's something about my particular system, but I don't know why it popped up after the upgrade.

![image](https://user-images.githubusercontent.com/16090529/65553792-47849f00-deed-11e9-8964-b7da97905b9f.png)

**Comment by ccordoba12** [comment]
This was a problem introduced in the latest  version of jupyter_client, sorry for the confusion.

**Comment by ndeeds** [comment]
> This was a problem introduced in the latest version of jupyter_client, sorry for the confusion.

No worries, thanks for the heads up.

**Comment by GNSharmaa** [comment]
> This was a problem introduced in the latest version of jupyter_client, sorry for the confusion.

Does that mean problem is in jupyter itself?? If yes should i downgrade?

**Comment by ccordoba12** [comment]
The latest version of the jupyter_client package should have fixed this.

**Comment by GNSharmaa** [comment]
> The latest version of the jupyter_client package should have fixed this.

Latest jupyter_client version is 5.3.3 which is already installed, yet the problem persists

**Comment by ccordoba12** [comment]
Ok, please install the pywin32 package and try again.

**Comment by raphaelquast** [comment]
... I've just wanted to join this discussion since I'm running into the exact same problem (with a completely fresh and fully updated miniconda installation) so this is definitely not fixed in the latest versions!

uncommenting lines `93-100` in `connect.py` as suggested above also solves the problem for me!
however, this has to be done for each environment individually which can be quite annoying...

**Comment by GNSharmaa** [comment]
I don't know how, but issue has been fixed now, even without downgrading and i m still at ipython 7.8.0. Thanks to all of you for help!!

**Comment by olaitao2** [comment]
Hello, the solution that worked for me when I encountered this problem was to right click and select "Run as administrator" when selecting the Jupyter/Spyder application shortcut.
