### ISSUE TITLE
Julia kernel shows different format of output when running on desktop

### ISSUE THREAD

**Issue by lichenhao608** [ipython/ipython#11906]
I am using Julia 1.2.0 and the PrettyTables package.

The output of the table shows weird when I run it on my desktop.
![image](https://user-images.githubusercontent.com/23352637/66460119-22cf1200-ea2b-11e9-91e5-13ad43cdf5f1.png)

However, when I run it on my laptop, the format the table is perfect and shows similar to the sample image on https://github.com/ronisbr/PrettyTables.jl that the columns are perfectly aligned
![image](https://github.com/ronisbr/PrettyTables.jl/blob/master/docs/src/assets/welcome_figure.png?raw=true)

I have tried to reinstall Julia, the package, and Jupyter. None of them works. Can anyone help me with that?

**Comment by Carreau** [comment]
Hi @lichenhao608 I think you have better chances on a Julia community of the IJulia repository. 
Jupyter mostly defer all of that to Julia;

**Comment by MrMino** [comment]
I second this suggestion: this is all very specific to the Julia Kernel, and not something we can deal with here.
