### ISSUE TITLE
Restore terminal title after exiting IPython

### ISSUE THREAD

**Issue by pasenor** [ipython/ipython#11909]
IPython sets the terminal title to `IPython: {cwd}`, which is cool, but after exiting the shell, on xterm the original title is not restored. It can be fixed by [saving and then restoring the original title](https://stackoverflow.com/a/20048874/2166825):

    sys.stdout.write('\033[22;0t')  # Save title on stack
    sys.stdout.write('\033[23;0t')  # Restore title from stack

**Comment by MrMino** [comment]
Fixed within #11910.
