### ISSUE TITLE
Ipython have some bugs while deal with multiprocess program.

### ISSUE THREAD

**Issue by rnLIKEm** [ipython/ipython#11929]
this is the code below:
```
# coding:utf-8
from multiprocessing import Process

def foo():
    print('hello')

if __name__ == '__main__':
    p = Process(target=foo, )
    p.start()
    p.join()
    print('End')

```
I run this script twice get some exception
see:
![image](https://user-images.githubusercontent.com/52340898/67635552-91eda700-f903-11e9-9b60-245b7297d309.png)

![image](https://user-images.githubusercontent.com/52340898/67635563-a467e080-f903-11e9-9e49-212c35762f53.png)

**Comment by Carreau** [comment]
from the traceback it looks like an issue in the multiprocessing module; so this migt need a fix upstream in Python.  We can try to have a workaround in IPython but regardless a properfix upstream woudl be nice.

**Comment by rnLIKEm** [comment]
thanks for you anwser
