### ISSUE TITLE
Keyboard shortcuts not working (again)

### ISSUE THREAD

**Issue by gegnew** [ipython/ipython#11944]
7.9.0 seems to have broken keyboard some keyboard shortcuts (or I'm really missing something). Similar issue at #11405 . The 'jk' shortcut works just fine for me on 7.6.1, but I not on 7.9.

**Comment by augustogoulart** [comment]
@gegnew thanks for reporting it. Can you please provide more details about your system?

**Comment by gegnew** [comment]
```
System:    Host: eva Kernel: 4.19.81-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.2.0
Desktop: KDE Plasma 5.17.2 tk: Qt 5.13.1 wm: i3 4.17.1 dm: SDDM Distro: Manjaro Linux 
Machine:   Type: Desktop Mobo: ASUSTeK model: PRIME B450M-A v: Rev X.0x serial: <filter> UEFI: American Megatrends v: 1823 
CPU:       Topology: 6-Core model: AMD Ryzen 5 3600 bits: 64 type: MT MCP arch: Zen
```

It's perfectly possible that I've configured something wrong, but I can't figure out what it would be. The other example ("The Spanish Inquisition" mapped to Ctrl-N) works just fine. Any ideas of what I could poke at to investigate?

**Comment by Carreau** [comment]
I don't see anything between 7.8.0 and 7.9.0 that should break shortcut.

How comfortable are you installing from git ? If you are it would be good if you can do a `git bisect` to find which revision broke the shortcuts.

**Comment by gegnew** [comment]
Yeah,  actually, it works fine. I forgot that I needed to set the ` TerminalInteractiveShell.editing_mode` to 'vi'. Since the example in the documentation is for mapping 'jk' to vi mode, perhaps that section should contain a reminder about this setting in your IPython config?

Sorry it took a bit to get back to troubleshooting this.
