### ISSUE TITLE
Simplification of logic since Python 3.5 removal.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#11955]
Since #11953 was merged a couple of extra simplification can be done:

See in particular  this comments. 

 - https://github.com/ipython/ipython/pull/11953/files#r348243309

The value `DICT_IS_ORDERED` in `IPython/lib/pretty.py` is always `True`; any code that reply on it can be simplified; and the value should be documented for future removal.

This is a good issue for a first time contributor.

**Comment by whiskeyjack-dev** [comment]
I'll take a crack at this.

**Comment by jamescooke** [comment]
It looks like this is done and should be closed.

**Comment by mijiturka** [comment]
Going by CONTRIBUTING.md it's now possible for everyone to close an issue:
@meeseeksdev close
