### ISSUE TITLE
Cleanup some codepath after 3.6 removal.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#11954]
Since #11953 was merged a couple of extra simplification can be done:

See in particular  these comments. 

 - https://github.com/ipython/ipython/pull/11953/files#r348244312

The value `async_safe` in `IPython/core/tests/test_async_helpers.py` is now a constant, 

The codepath relying on those constants can be simplified. In particular I believe a boolean expression can be removed.

This is a good issue for a first time contributor.

#12637 moved us closer to the goal. `val_should_fail` can likely be removed in favor simply `should_fail`, `async_safe` will then be unused and could be removed.

**Comment by yhiraki** [comment]
Tests pass if `val_should_fail` is always `should_fail` . Is this correct behavior?
I changed [test_async_helpers.py#L217-L218](https://github.com/kousikmitra/ipython/blob/747cdeb276ec8c88ad646b809882c11bd63543e9/IPython/core/tests/test_async_helpers.py#L217-L218) to below:

```
val_should_fail = should_fail
```
