### ISSUE TITLE
Error While reading the CSV in Jupyter Notebook via Pandas

### ISSUE THREAD

**Issue by dhirupadhyay** [ipython/ipython#11969]
HI Techies,
I am new to python and pandas, i am trying to import a structured csv file in jupyter notebook by using conventional code .i.e

```
import pandas as pd
df=pd.read_csv("Datasets/Border_Crossing_Entry_Data")
df.head(5)
```

but every time i am getting the below error, please help me since i am supposed to submit my assignment 

```
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-11-33127abc1814> in <module>
      1 import pandas as pd
----> 2 df=pd.read_csv("Datasets/Border_Crossing_Entry_Data")
      3 df.head(5)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    683         )
    684 
--> 685         return _read(filepath_or_buffer, kwds)
    686 
    687     parser_f.__name__ = name

C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
    455 
    456     # Create the parser.
--> 457     parser = TextFileReader(fp_or_buf, **kwds)
    458 
    459     if chunksize or iterator:

C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py in __init__(self, f, engine, **kwds)
    893             self.options["has_index_names"] = kwds["has_index_names"]
    894 
--> 895         self._make_engine(self.engine)
    896 
    897     def close(self):

C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py in _make_engine(self, engine)
   1133     def _make_engine(self, engine="c"):
   1134         if engine == "c":
-> 1135             self._engine = CParserWrapper(self.f, **self.options)
   1136         else:
   1137             if engine == "python":

C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py in __init__(self, src, **kwds)
   1915         kwds["usecols"] = self.usecols
   1916 
-> 1917         self._reader = parsers.TextReader(src, **kwds)
   1918         self.unnamed_cols = self._reader.unnamed_cols
   1919 

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] File b'Datasets/Border_Crossing_Entry_Data' does not exist: b'Datasets/Border_Crossing_Entry_Data'`
```

**Comment by Carreau** [comment]
Hi, 

Please check your file path, and current working directory.
In IPython you should be able to use `ls` and `cwd`

from what you wrote I see two issues:

```
df=pd.read_csv("Datasets/Border_Crossing_Entry_Data")
```


1) You didn't add the file extensions to filename,
2) you seem to be on windows. The file separator is `\` not `/`. (you may have to double it and use `"Datasets\\Border_Crossing_Entry_Data.csv"`.

This is more a generic Python question than a Jupyter/IPython issue, so closing.

**Comment by mohdqadeer** [comment]
pd.read_csv('customer_churn.csv')
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-6-95d69fe7548d> in <module>
----> 1 pd.read_csv('customer_churn.csv')

C:\Anaconda\lib\site-packages\pandas\io\parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    674         )
    675 
--> 676         return _read(filepath_or_buffer, kwds)
    677 
    678     parser_f.__name__ = name

C:\Anaconda\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
    446 
    447     # Create the parser.
--> 448     parser = TextFileReader(fp_or_buf, **kwds)
    449 
    450     if chunksize or iterator:

C:\Anaconda\lib\site-packages\pandas\io\parsers.py in __init__(self, f, engine, **kwds)
    878             self.options["has_index_names"] = kwds["has_index_names"]
    879 
--> 880         self._make_engine(self.engine)
    881 
    882     def close(self):

C:\Anaconda\lib\site-packages\pandas\io\parsers.py in _make_engine(self, engine)
   1112     def _make_engine(self, engine="c"):
   1113         if engine == "c":
-> 1114             self._engine = CParserWrapper(self.f, **self.options)
   1115         else:
   1116             if engine == "python":

C:\Anaconda\lib\site-packages\pandas\io\parsers.py in __init__(self, src, **kwds)
   1889         kwds["usecols"] = self.usecols
   1890 
-> 1891         self._reader = parsers.TextReader(src, **kwds)
   1892         self.unnamed_cols = self._reader.unnamed_cols
   1893 

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] File customer_churn.csv does not exist: 'customer_churn.csv'

**Comment by nagarajungh** [comment]
Hi @dhirupadhyay please let me know how do you resolve the issue, i am having same issue

here is my issue


---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-8-84b7ff6b45f1> in <module>
      4 import os
      5 # Constructing data frame
----> 6 df = pd.read_csv(r'C:\Users\99666\Desktop\Capstone\Data-Collisions.csv')
      7 print ('Data read into a pandas dataframe!')
      8 df.head(3)

/opt/conda/envs/Python36/lib/python3.6/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    700                     skip_blank_lines=skip_blank_lines)
    701 
--> 702         return _read(filepath_or_buffer, kwds)
    703 
    704     parser_f.__name__ = name

/opt/conda/envs/Python36/lib/python3.6/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    427 
    428     # Create the parser.
--> 429     parser = TextFileReader(filepath_or_buffer, **kwds)
    430 
    431     if chunksize or iterator:

/opt/conda/envs/Python36/lib/python3.6/site-packages/pandas/io/parsers.py in __init__(self, f, engine, **kwds)
    893             self.options['has_index_names'] = kwds['has_index_names']
    894 
--> 895         self._make_engine(self.engine)
    896 
    897     def close(self):

/opt/conda/envs/Python36/lib/python3.6/site-packages/pandas/io/parsers.py in _make_engine(self, engine)
   1120     def _make_engine(self, engine='c'):
   1121         if engine == 'c':
-> 1122             self._engine = CParserWrapper(self.f, **self.options)
   1123         else:
   1124             if engine == 'python':

/opt/conda/envs/Python36/lib/python3.6/site-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   1851         kwds['usecols'] = self.usecols
   1852 
-> 1853         self._reader = parsers.TextReader(src, **kwds)
   1854         self.unnamed_cols = self._reader.unnamed_cols
   1855 

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] File b'C:\\Users\\99666\\Desktop\\Capstone\\Data-Collisions.csv' does not exist: b'C:\\Users\\99666\\Desktop\\Capstone\\Data-Collisions.csv'

**Comment by Shrinjoymaiti** [comment]
![Screenshot (43)](https://user-images.githubusercontent.com/69680372/93005920-cf870d00-f573-11ea-9067-28e393c8097b.png)
I'm facing same issues. Help me please.

**Comment by AungSoeLin** [comment]
> HI Techies,
> I am new to python and pandas, i am trying to import a structured csv file in jupyter notebook by using conventional code .i.e
> 
> ```
> import pandas as pd
> df=pd.read_csv("Datasets/Border_Crossing_Entry_Data")
> df.head(5)
> ```
> 
> but every time i am getting the below error, please help me since i am supposed to submit my assignment
> 
> ```
> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-11-33127abc1814> in <module>
>       1 import pandas as pd
> ----> 2 df=pd.read_csv("Datasets/Border_Crossing_Entry_Data")
>       3 df.head(5)
> 
> C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
>     683         )
>     684 
> --> 685         return _read(filepath_or_buffer, kwds)
>     686 
>     687     parser_f.__name__ = name
> 
> C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
>     455 
>     456     # Create the parser.
> --> 457     parser = TextFileReader(fp_or_buf, **kwds)
>     458 
>     459     if chunksize or iterator:
> 
> C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py in __init__(self, f, engine, **kwds)
>     893             self.options["has_index_names"] = kwds["has_index_names"]
>     894 
> --> 895         self._make_engine(self.engine)
>     896 
>     897     def close(self):
> 
> C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py in _make_engine(self, engine)
>    1133     def _make_engine(self, engine="c"):
>    1134         if engine == "c":
> -> 1135             self._engine = CParserWrapper(self.f, **self.options)
>    1136         else:
>    1137             if engine == "python":
> 
> C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py in __init__(self, src, **kwds)
>    1915         kwds["usecols"] = self.usecols
>    1916 
> -> 1917         self._reader = parsers.TextReader(src, **kwds)
>    1918         self.unnamed_cols = self._reader.unnamed_cols
>    1919 
> 
> pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()
> 
> pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()
> 
> FileNotFoundError: [Errno 2] File b'Datasets/Border_Crossing_Entry_Data' does not exist: b'Datasets/Border_Crossing_Entry_Data'`
> ```

having this error,  for bottle.csv



NameError                                 Traceback (most recent call last)
<ipython-input-3-c11f5912ec0f> in <module>
----> 1 bottle['T_degC'] = pd.to_numeric(bottle['T_degC'], errors='coerce') #convert variable to numeric

NameError: name 'bottle' is not defined

**Comment by Harshavardhanteja7** [comment]
Even I got the Same Error Saying Permission denied

**Comment by Shobhit195-byte** [comment]
I have also got the same error.
Kindly help me resolve the issue.

**import pandas as pd
df = pd.read_csv('AAPL.csv')
df.head()**


FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-b88eb1e5a444> in <module>
      1 import pandas as pd
----> 2 df = pd.read_csv('AAPL.csv')
      3 df.head()

~\anaconda3\lib\site-packages\pandas\io\parsers.py in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    684     )
    685 
--> 686     return _read(filepath_or_buffer, kwds)
    687 
    688 

~\anaconda3\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
    450 
    451     # Create the parser.
--> 452     parser = TextFileReader(fp_or_buf, **kwds)
    453 
    454     if chunksize or iterator:

~\anaconda3\lib\site-packages\pandas\io\parsers.py in __init__(self, f, engine, **kwds)
    944             self.options["has_index_names"] = kwds["has_index_names"]
    945 
--> 946         self._make_engine(self.engine)
    947 
    948     def close(self):

~\anaconda3\lib\site-packages\pandas\io\parsers.py in _make_engine(self, engine)
   1176     def _make_engine(self, engine="c"):
   1177         if engine == "c":
-> 1178             self._engine = CParserWrapper(self.f, **self.options)
   1179         else:
   1180             if engine == "python":

~\anaconda3\lib\site-packages\pandas\io\parsers.py in __init__(self, src, **kwds)
   2006         kwds["usecols"] = self.usecols
   2007 
-> 2008         self._reader = parsers.TextReader(src, **kwds)
   2009         self.unnamed_cols = self._reader.unnamed_cols
   2010 

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] No such file or directory: 'AAPL.csv'

**Comment by Carreau** [comment]
Apologies, but this is a bug tracker, and as much as we do our best to help users, these are not Jupyter/IPython bugs.

Please use commands like `ls`, `dir`, `pwd` and make sure the file exists where you are trying to read from it. 
Also please read error message,  you do not have the same errors. 

Some are FileNotFound, some are NameError.

locking issue and marking recent comments os off-topic.
