### ISSUE TITLE
IPython 7.10 does not work with matplotlib in Python 3.8

### ISSUE THREAD

**Issue by albireox** [ipython/ipython#11974]
With the latest IPython 7.10 and running Python 3.8, when I import `from matplotlib import pyplot as plt`, the import works but the prompt becomes unusable (invisible characters, Ctrl-C/D does not work). Alternatively, if I add that line to the initial imports in my `ipython_config.py`, I get the error

```
Task was destroyed but it is pending!
task: <Task pending name='Task-1' coro=<History._start_loading() running at /Users/albireo/.pyenv/versions/3.8.0/Python.framework/Versions/3.8/lib/python3.8/site-packages/prompt_toolkit/history.py:40>>
/Users/albireo/.pyenv/versions/3.8.0/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py:633: RuntimeWarning: coroutine 'History._start_loading' was never awaited
  self._ready.clear()
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<History._start_loading() running at /Users/albireo/.pyenv/versions/3.8.0/Python.framework/Versions/3.8/lib/python3.8/site-packages/prompt_toolkit/history.py:40>>
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<History._start_loading() running at /Users/albireo/.pyenv/versions/3.8.0/Python.framework/Versions/3.8/lib/python3.8/site-packages/prompt_toolkit/history.py:40>>
```

but then it seems matplotlib works.

**Comment by Carreau** [comment]
Try to downgrade prompt toolkit to 2.x.

**Comment by albireox** [comment]
Yes, that fixes it.

**Comment by Carreau** [comment]
Great ! You can also apply #11973 locally and run from prompt toolkit master.

**Comment by mrzzheng** [comment]
Same here on Python 3.7.5..  #11973 doesn't work, importing matplotlib.pyplot still makes input prompts to disappear.

**Comment by pylang** [comment]
On a related note, should `travis.yml` be updated to test on Python 3.8 and 3.9-dev?

**Comment by Carreau** [comment]
> On a related note, should `travis.yml` be updated to test on Python 3.8 and 3.9-dev?

We do test on 3.8-dev and nightly. We could switch to 3.8 (non dev), 3.9-dev and nightly but I'm not sure it is worth it yet.

**Comment by Carreau** [comment]
I'm going to assume #11973 fixed it. Let us know if that's not the case. I'm going to release a 7.10.1 that should have some  those fixes.
