### ISSUE TITLE
review usage of py3compat.u_format

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#11987]
py3compat.u_format use to help formatting string between python 2 and python 3 by doing:

```
py3compat.u_format('{u}"a string"')  -> u"a string" # py 2
py3compat.u_format('{u}"a string"')  -> "a string" # py 3
```

my guess is now it is useless and can just be removed. 

- check every place where it is used:
  - if input have no '{u}', remove the function call. 
  - if Input have a `{u}`, look at how to update it and potentially inline (or not) the `u""`.

**Comment by kousikmitra** [comment]
@Carreau can I work on this? or is it closed?

**Comment by mijiturka** [comment]
u_format has been completely removed with PR #12259
@meeseeksdev close
