### ISSUE TITLE
IPython ignore chained exception when using %xmode plain

### ISSUE THREAD

**Issue by impact27** [ipython/ipython#11995]
IPython ignores chained exception when using`%xmode plain`:
ipython:
```python
In [2]: %xmode plain                                                                                 
Exception reporting mode: Plain

In [3]: try: 
   ...:     v = {}['a'] 
   ...: except KeyError as e: 
   ...:     raise ValueError('failed') from e 
   ...:                                                                                              
Traceback (most recent call last):
  File "<ipython-input-3-944ebf5453bb>", line 4, in <module>
    raise ValueError('failed') from e
ValueError: failed
```
python:
```python
>>> try:
...     v = {}['a']
... except KeyError as e:
...     raise ValueError('failed') from e
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
KeyError: 'a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
ValueError: failed
```

**Comment by Carreau** [comment]
Hum, that appear to be on purpose; and it's not going to be an easy change.

**Comment by impact27** [comment]
> Hum, that appear to be on purpose; and it's not going to be an easy change.

I am not sure what the rationale of this being on purpose is. Why shouldn't `'Plain'` follow https://www.python.org/dev/peps/pep-3134/? I can understang e.g. for `'Minimal'`.

**Comment by Carreau** [comment]
I'm not sure, this is pretty old code, but `Plain` appear to go through a path that only print the last exception.

I agree with you that there does not appear to be any reason not to print the chain, I'm just saying that the current code appear to have been implemented in a way that assume it would not have to do it.

**Comment by impact27** [comment]
Ok, I opened a PR that could solve it: https://github.com/ipython/ipython/pull/11999
