### ISSUE TITLE
ipython's pdb 7.10 cannot be (directly?) used as pytest's pdb

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#12005]
The debugger of IPython<7.10 can be used as pytest's pdb by passing `--pdb --pdbcls=IPython.terminal.debugger:TerminalPdb` to pytest (e.g. create a single failing test and run it with `pytest --pdb --pdbcls=IPython.terminal.debugger:TerminalPdb`).
With ipython 7.10 (and pytest 5.3.1) this fails with
```
<elided>
  File ".../python3.8/site-packages/_pytest/debugging.py", line 243, in _init_pdb
    _pdb = cls._import_pdb_cls(capman)(**kwargs)
  File ".../python3.8/site-packages/IPython/terminal/debugger.py", line 30, in __init__
    self.pt_init()
  File ".../python3.8/site-packages/IPython/terminal/debugger.py", line 69, in pt_init
    options['inputhook'] = self.inputhook
AttributeError: 'PytestPdbWrapper' object has no attribute 'inputhook'
```

**Comment by Carreau** [comment]
Yeah that's my fault. Should be fixed on master. I'll try to release a 7.10.2 soon.

**Comment by anntzer** [comment]
Thanks!
