### ISSUE TITLE
IPython/utils/py3compat.py unused `annotate` function. 

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#12011]
The function `annotate` is a relic of Python 2 compatibility time. 

we should : 
1) check if it is used, remove usage if any
2) remove the function once it is unused.

**Comment by takuya1981** [comment]
I checked that there is no reference to annotate () from this package.

**Comment by takuya1981** [comment]
Oh, build failed..
In python 3.6 for Mac, it shows that Error: Checksum for Cask 'python-framework-36' does not match.
SHA256 hash value for python-3.6.8-macosx10.6.pkg is 3c5fd87a231eca3ee138b0cdc2be6517a7ca428304d41901a86b51c6a22b910c, and the value I calculated is same as Actual not Expected.

**Comment by BitLegion** [comment]
#12061

**Comment by mijiturka** [comment]
This has made it into master with PR #12052
@meeseeksdev close
