### ISSUE TITLE
Ipdb and Flask No longer work together

### ISSUE THREAD

**Issue by jchang10** [ipython/ipython#12019]
I wanted to mention this here. I can't be the only that uses flask and ipdb together. Using "import ipdb;ipdb.set_trace()" has worked well in flask apps for the longest time up until a recent update. I tracked it down to ipython. v7.9.0 works but v7.10.0 does not. :(

Just wanted someone to be aware. Is it possible to get an explanation of what might have caused this? Wondering if there might be a workaround possibly? For now, downgrading to v7.9.0 works for now. Just would be nice to know if I have to look for another solution in the future.

It now gives this error when hitting the breakpoint:
```
File "/.venv/lib/python3.7/site-packages/IPython/terminal/debugger.py", line 97, in cmdloop
    line = self.pt_app.prompt() # reset_current_buffer=True)
  File "/.venv/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 986, in prompt
    return self.app.run()
  File "/.venv/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 788, in run
   return get_event_loop().run_until_complete(self.run_async(pre_run=pre_run))
  File "/usr/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-3'.
```
Reproducing this error can be done with the simplest flask app:
```
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    import ipdb;ipdb.set_trace()
    return 'Hello, World!'
```

Thanks!

**Comment by rishikant42** [comment]
@jchang10 I don't think this issue is specific to flask framework. I have faced the same issue in Django as well. Thanks.

**Comment by LucianaMarques** [comment]
Thanks for the feedback! I occasionally contribute to IPython and I'll be taking a look at this.

**Comment by Carreau** [comment]
Can you try v7.10.1 and Master ? We are aware on some issues with asyncio and ipdb and both 7.10.1 and master have a few extra fixes.

**Comment by jchang10** [comment]
@Carreau Yes, sorry, I should have mentioned earlier. Same behavior with v7.10.1.

**Comment by karolyi** [comment]
+1 with django and `IPython.embed()`

**Comment by Carreau** [comment]
Please try master and/or 7.10.x branch from github. They both fix a bug with ipdb and have not been release yet.

**Comment by jchang10** [comment]
Hi. Same exact output as above in original post. I ran the following:
$ pip install --upgrade git+git://github.com/ipython/ipython@master
$ pip show ipython
Name: ipython
Version: 7.11.0.dev0

In addition, I tried the below. Same result again.
$ pip install --upgrade git+git://github.com/ipython/ipython@7.10.x
$ pip show ipython
Name: ipython
Version: 7.10.1

**Comment by shifr** [comment]
Same here with 7.10.1. Rollback to 7.9.0 helps

**Comment by aspratyush** [comment]
Even just `ipdb` itself seems to be causing issues with 7.10*.
```
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import ipdb                                                                                                                                                                                                

In [2]: ipdb.set_trace()                                                                                                                                                                                           
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-823a13fd69ba> in <module>
----> 1 ipdb.set_trace()

~/workspace/venv-tf2py3.6/lib/python3.6/site-packages/ipdb/__main__.py in set_trace(frame, context)
     65     if frame is None:
     66         frame = sys._getframe().f_back
---> 67     p = _init_pdb(context).set_trace(frame)
     68     if p and hasattr(p, 'shell'):
     69         p.shell.restore_sys_module_state()

~/workspace/venv-tf2py3.6/lib/python3.6/site-packages/ipdb/__main__.py in _init_pdb(context, commands)
     46 def _init_pdb(context=3, commands=[]):
     47     try:
---> 48         p = debugger_cls(context=context)
     49     except TypeError:
     50         p = debugger_cls()

~/workspace/venv-tf2py3.6/lib/python3.6/site-packages/IPython/terminal/debugger.py in __init__(self, *args, **kwargs)
     28         Pdb.__init__(self, *args, **kwargs)
     29         self._ptcomp = None
---> 30         self.pt_init()
     31 
     32     def pt_init(self):

~/workspace/venv-tf2py3.6/lib/python3.6/site-packages/IPython/terminal/debugger.py in pt_init(self)
     67 
     68         if not PTK3:
---> 69             options['inputhook'] = self.inputhook
     70         self.pt_app = PromptSession(**options)
     71 

AttributeError: 'TerminalPdb' object has no attribute 'inputhook'
```

Resolves upon downgrading ipython to 7.9.

**Comment by zgoda** [comment]
I believe original issue is related to prompt-toolkit while @aspratyush comment relates to ipython itself. Forcing downgrade of prompt-toolkit to a version below 3 with ipython 7.10.x results in `AttributeError: 'TerminalPdb' object has no attribute 'inputhook'`.

**Comment by Carreau** [comment]
Please stop testing and posting that  IPython `7.10.0` or `7.10.1` are affected – it is not the same issue as the one reported ;   I am also aware of it and #12008 will fix the specific error about `self.inputhook`.

**Comment by Carreau** [comment]
@jchang10 thanks for testing on master; there was some change in asyncio with prompt toolkit 3, I though that #12001 might have fixed it but it may need some fixes in prompt_tookit as well.

I believe that downgrading to prompt_toolkit 2 should work for now. 

@jonathanslenders you seem to have more understanding of eventloops that I have. Does that seem like something obvious to fix, or already fixed ?

**Comment by jonathanslenders** [comment]
Hi @Carreau, thanks for pinging me.
I totally forgot to do the same fix I recently did to terminal/interactiveshell.py
Not sure whether I've time today, but if not I push a fix tomorrow.

**Comment by jonathanslenders** [comment]
@jchang10 : Can you check whether this PR: https://github.com/ipython/ipython/pull/12028 solves you issue?

**Comment by jchang10** [comment]
Yes, great. That did it! Thanks again!
