### ISSUE TITLE
IPython/utils/py3compat.py unused _print_statement_sub.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#12010]
function `_print_statement_sub` seem unused in code base. 

One should check if this is actually the case, and remove it if necessary.

**Comment by mijiturka** [comment]
This has made it into master with PR #12076
@meeseeksdev close
(Sorry if I'm not supposed to close issues as a brand-new user but going by CONTRIBUTING.md)

**Comment by Carreau** [comment]
> (Sorry if I'm not supposed to close issues as a brand-new user but going by CONTRIBUTING.md)

No that's good ! thanks !
