### ISSUE TITLE
raise ImportError('Please upgrade your TensorFlow installation to v1.12.*.')

### ISSUE THREAD

**Issue by HegiRaket** [ipython/ipython#12042]
I followed a youtube tutorial called 'Train an Object Detection Classifier Using TensorFlow (GPU) on Windows 10'
Onestep is starting the following code in JUPYTER:

> import numpy as np
> import os
> import six.moves.urllib as urllib
> import sys
> import tarfile
> import tensorflow as tf
> import zipfile
> 
> from distutils.version import StrictVersion
> from collections import defaultdict
> from io import StringIO
> from matplotlib import pyplot as plt
> from PIL import Image
> 
> # This is needed since the notebook is stored in the object_detection folder.
> sys.path.append("..")
> from object_detection.utils import ops as utils_ops

But I received the follwoing error message:

> if StrictVersion(tf.__version__) < StrictVersion('1.12.0'):
>   raise ImportError('Please upgrade your TensorFlow installation to v1.12.*.')

After this error I made an TENSORFLOW upgrade. Now I use Tensorflow 2.0
But after upgrading I received the very same error message.

So I made a full ANACONDA upgrade but I still receive the same error message. I have no more ideas.

PLEASE HELP ME

**Comment by Carreau** [comment]
Hi, 

This is the bug tracker for IPython; not a general help forum. If you are a beginner with Python and following a tutorial please you the help forums at your disposal; or reach to general community like https://www.reddit.com/r/learnpython/
