### ISSUE TITLE
Running iptest on macOs HighSierra raises  ModuleNotFoundError: No module named 'traitlets'

### ISSUE THREAD

**Issue by augustogoulart** [ipython/ipython#12050]
I'm trying to run IPython's test suite locally on macOs HighSierra with python 3, but after following the[ recommended steps](https://ipython.readthedocs.io/en/latest/install/install.html#installing-the-development-version) I'm getting the error below:
```
Traceback (most recent call last):
  File "/usr/local/bin/iptest", line 4, in <module>
    from IPython.testing.iptestcontroller import main
  File "/usr/local/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
  File "/usr/local/lib/python3.7/site-packages/IPython/core/application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
ModuleNotFoundError: No module named 'traitlets'
```

However, traitlets was indeed installed:
```
$ pip install -e .[test]
```

```
$ pip freeze | grep traitlets
traitlets==4.3.3
```

Currently, I don't have machines other macOs's and Windows’s, so determining whether or not this is a setup error would help me tremendously. I've considered building a Debian VM, but let's see if I can make this work for macOs first.

Thanks!

**Comment by augustogoulart** [comment]
In case somebody gets to experience the same problem, this how I solved it:

Inside `/usr/local/bin`, find and remove all the instances of `iptest` and `ipython`:

<img width="404" alt="Screen Shot 2019-12-22 at 13 35 16" src="https://user-images.githubusercontent.com/13952931/71324646-05ed9b00-24c0-11ea-909d-8ebdd23aae96.png">

Create a virtual environment for installing the testing dependencies, like:
```
$ python3 -m venv .ipython-venv

$ source .ipython-venv/bin/activate
```

Install the testing dependencies:

```
$ pip install -e .[test
```

Run `iptest` from the outside of ipython's directory:

```
$ iptest
```

Test suite should complete successfully:

```
Test suite completed for system with the following information:
IPython version: 7.11.0.dev
IPython commit : 285e6a440 (repository)
IPython package: ~/Workspace/ipython/IPython
Python version : 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27) [Clang 6.0 (clang-600.0.57)]
sys.executable : ~/Workspace/.ipython-venv/bin/python3
Platform       : macOS-10.13.6-x86_64-i386-64bit

Tools and libraries available at test time:
   pygments sqlite3

Tools and libraries NOT available at test time:
   matplotlib

Status: OK (7 test groups). Took 41.132s.
```

**Comment by LaurianoElmiroDuarte** [comment]
It does not work
