### ISSUE TITLE
ipython causes kernel panic in MacOS when shutting down the computer

### ISSUE THREAD

**Issue by snail123815** [ipython/ipython#12083]
With my limited knowledge, I cannot tell if it is a bug in ipython or MacOS
My system info:
```
{'commit_hash': 'e508b6e4d',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python3.7/site-packages/IPython',
 'ipython_version': '7.10.1',
 'os_name': 'posix',
 'platform': 'Darwin-19.2.0-x86_64-i386-64bit',
 'sys_executable': '/usr/local/opt/python/bin/python3.7',
 'sys_platform': 'darwin',
 'sys_version': '3.7.6 (default, Dec 30 2019, 19:38:26) \n'
                '[Clang 11.0.0 (clang-1100.0.33.16)]'}
```
Recently I found that every time I do restart or shutdown, there will be a kernel panic. Then an multilingual error message will show and restart normally. When logged in, system will report a kernel panic event.

Symptom: 
System stuck at a stage that it seems to have shut down all apps, showing only a wall paper and a spinning wait icon.

After a series of test, I can reproduce this symptom: 

Steps to reproduce:

1. Start the system
2. Open Terminal
3. Run `ipython` and `exit()`
4. Select to restart or shutdown machine

Running only python3 won't cause the problem.

MacOS version: 19C57

Part of the panic info:
```
      Kernel Extensions in backtrace:
         com.apple.driver.watchdog(1.0)[EFAA17B9-A62C-30B7-9602-0BB5282EDDD6]@0xffffff7f8e645000->0xffffff7f8e64dfff
         com.apple.driver.AppleSMC(3.1.9)[CA7CACA5-58A6-3E59-9F67-2422183AB544]@0xffffff7f8e64e000->0xffffff7f8e66cfff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[3467C105-9354-3BD2-85F3-E5AEF94BD275]@0xffffff7f8e63c000
            dependency: com.apple.driver.watchdog(1)[EFAA17B9-A62C-30B7-9602-0BB5282EDDD6]@0xffffff7f8e645000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[1286D5E5-A6A1-3C44-A244-04C068903DB2]@0xffffff7f8df2f000
 ```
Full info:
[kernel_panic.txt](https://github.com/ipython/ipython/files/4047575/kernel_panic.txt)

**Comment by Carreau** [comment]
Wow, that will be tough.  IPython does not directly use compiled code so there is no reason that it's IPython itself; but more one of its dependencies. I'll try to find which one could cause this.

**Comment by snail123815** [comment]
Well, I don't know if other people still have this issue. But I think one of the recent macOS 10.15.5 update solved the issue. None of its dependencies will cause problem now.
