### ISSUE TITLE
Shortening Tab Completion

### ISSUE THREAD

**Issue by mlucool** [ipython/ipython#12088]
Hi,

When tab completing it would helpful if there was a way to not repeat the part that is already typed.  For example, `aa.bb.cc.dd.xx<TAB>`, the popup would not repeat the `aa.bb.cc.dd.` While I would be a fan of this by default, it may make sense to make this opt in/out.

**Comment by Carreau** [comment]
Yes it make sens; I believe the completion logic already allows fo what is show and what is going to be completed to be different. So it's a matter of finding the right spot and writing the logic. 

There is one possibility which is to remove common prefix, though there are some corner case like `mpl<tab>` with suggest both `matplotlib` and `%matplotlib` so there will be no common prefix. In the case where things are already typed we need some heuristics like if you typed `mat` you do not want the completion to be only `plotlib`; as in your example we could try to remove non ambiguous part after splitting  dots.

There is a question of wether we do that as part of the completer logic or part of the UI logic.
In Terminal IPython there is already in `IPython/terminal/ptutils.py` the following: 

```
def _elide(string, *, min_elide=30):
    """
    If a string is long enough, and has at least 3 dots,
    replace the middle part with ellipses.

    If a string naming a file is long enough, and has at least 3 slashes,
    replace the middle part with ellipses.

    If three consecutive dots, or two consecutive dots are encountered these are
    replaced by the equivalents HORIZONTAL ELLIPSIS or TWO DOT LEADER unicode
    equivalents
    """
```

This function is used in a context (same file line 128) where we do have the surrounding text (at least for IPython console) so it should not be too invasive to do this change.

**Comment by ngoldbaum** [comment]
I think I'd like to try my hand at this, starting with Matthias' suggestions.

**Comment by ngoldbaum** [comment]
Actually, hmm, I'm a little confused - isn't this how it works already? See this screenshot:

![Screenshot from 2020-02-13 16-09-39](https://user-images.githubusercontent.com/3126246/74486884-53acd100-4e7b-11ea-806c-a9407606ca09.png)

**Comment by ngoldbaum** [comment]
Ah, I was able to reproduce this using `prompt_toolkit 1.0.5` and `IPython 5.8.0`. @mlucool is the fact that this behavior no longer occurs with the latest versions of IPython and prompt_toolkit sufficient to close this issue or do you need the fix backported?

**Comment by Carreau** [comment]
If you find that it's fixed in master and 7.x feel free to close. 

We do accept minimal PRs against 5.x but we don't promise release and to work on it. 
That is to say if it's a minimally trivial  non-invasive change that obviously help we merge and can do a release.

Otherwise we focus on master(dev) and 7.x for stable. PRs that as marked as 7.x will automatically get backported by our bot on merge.

**Comment by ngoldbaum** [comment]
I'll check with 7.x but I don't have permissions to close issues it seems. BTW if you'd like to give me triage access that would be cool :)

**Comment by Carreau** [comment]
I should have sent you invite to triage team. I'll recheck.

**Comment by ngoldbaum** [comment]
Yeah, It doesn't happen in IPython 7.x either, this should be good to close.

**Comment by mlucool** [comment]
Yes, this is fixed in ipython 7.x when used with prompt_toolkit 3.x. Closing.
