### ISSUE TITLE
if statement or function EOF error

### ISSUE THREAD

**Issue by solocazzimiei** [ipython/ipython#12096]
Hi,
I'm new on Spyder 3.3.6.
When run a selection of code (F9) in correspondence of any if statement or function assignment  the Console return an EOF error like above shown. How can be solved ? 
```
def titolo_w(titolo):
  File "<ipython-input-780-5f591f155d80>", line 1
    def titolo_w(titolo):
                         ^
SyntaxError: unexpected EOF while parsing
```
or 
```
if y_in > 1 :
  File "<ipython-input-781-f087a9bd4bba>", line 1
    if y_in > 1 :
                 ^
SyntaxError: unexpected EOF while parsing 
```

**Comment by Carreau** [comment]
This is the tracker for IPython, not spyder, you may want to try https://github.com/spyder-ide/spyder

My wild guess is that you are not selecting enough code and the snippet you are executing is actually invalid.
