### ISSUE TITLE
unable to have jupyter run cells

### ISSUE THREAD

**Issue by jeeves990** [ipython/ipython#12100]
Seems like a recurring problem. Very frustrating.

ran **python -m ipykernel --log-level DEBUG**

and got this output. Please help with interpretation.

  File "C:\Users\FBA_S\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
[IPKernelApp] Cleaning up sockets
[IPKernelApp] Closing shell channel
[IPKernelApp] Closing control channel
[IPKernelApp] Closing stdin channel
[IPKernelApp] Terminating zmq context

**Comment by MrMino** [comment]
If anyone is still running into this issue: please share the code with which this can be reproduced. Otherwise we are unable to help.

I'm going to close this for now, but if this is still relevant to anyone, and you have a reproducible example of this issue - share it, and we'll reopen.
