### ISSUE TITLE
ERROR:root:Internal Python error in the inspect module

### ISSUE THREAD

**Issue by isayasfeyera** [ipython/ipython#12112]
```
Traceback (most recent call last):
  packages\tensorflow_core\core\framework\tensor_shape_pb2.py", line 112, in <module>
    '__module__' : 'tensorflow.core.framework.tensor_shape_pb2'
TypeError: expected bytes, Descriptor found
```

**Comment by Carreau** [comment]
THis appear to be a tensorflow error, not an IPython one; also knowing which code you run or what you did to get this error would be helpful to understand. Without this, there is not much I can do.

**Comment by MrMino** [comment]
Right now there's nothing in this report that would indicate this to be a problem related to IPython. If someone disagrees - please ping us here and provide more information, we'll reopen the issue.
