### ISSUE TITLE
ipython 7.12.0 tab completion doesn't work with numpy and scipy, but with matplotlib

### ISSUE THREAD

**Issue by Kadelka** [ipython/ipython#12121]
The ipython-shell:
Python 3.8.1 (default, Jan  9 2020, 22:55:38) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.

import readline
readline.parse_and_bind('tab: complete')

import numpy
numpy.__v tab completes to numpy.__version__
similar for numpy._anything, but
numpy.lin tab should complete to numpy.linspace(, but doesn't
ipython works fine with eg. matplotlib and other modules.

**Comment by Carreau** [comment]
Try to upgrade jedi; if jedi crashes you will not get any completions.

**Comment by Kadelka** [comment]
Just upgrades jedi. Completion now seems to be o.k. Thank you.

**Comment by david-mandelman** [comment]
I am experiencing the same problem - autocomplete works with pandas and seaborn, but NOT numpy. I'm using latest Jedi version 0.14.1. in fact, I updated all pkgs with conda in late April, 2020, so everything up-to-date:
numpy 1.18.1
Jupiter 1.0.0

**Comment by Kadelka** [comment]
My jedi-version is 0.16.0. With conda it is 0.15.1. Maybe your upgrade is not complete.

**Comment by david-mandelman** [comment]
Interesting. Thanks, I’ll look into it and see if I can upgrade

-David
--
David Mandelman
Staff Scientist, R&D
Clinical Next-Generation Sequencing
Life Sciences Solutions

Thermo Fisher Scientific
5781 Van Allen Wy | Carlsbad, CA  92008
Tel: +1 (760) 476-7052

**Comment by david-mandelman** [comment]
I'm trying: conda install jedi=0.15.1
but conda seems stuck at Solving environment. Should I get the Jedi pkg directly from Jedi site?

**Comment by david-mandelman** [comment]
OK, performed full conda update and now have Jedi 0.15.2, but numpy still NOT autocompleting. Frustrating. Any suggestions?

**Comment by Kadelka** [comment]
I think you sould address @Carreau directly. I'm only a user.

**Comment by Carreau** [comment]
Latest jedi on conda-forge is 0.17 (https://github.com/conda-forge/jedi-feedstock/pull/30/files) though you have to use `-c conda-forge` when upgrading all.

Which Python version are you on ? It might be that you are on an older one which does not have newer packages. 

Avoid old version of Jedi, the latest IPython will not be compatible with them.

You can use conda-export and pip-freeze if you want to see version of all your packages.

**Comment by david-mandelman** [comment]
Python 3.7.7.  So I’m using jedi 0.15.2 and I also installed nbextensions with autocomplete feature. Now Numpy is autocompleting for me. In fact, a context-sensitive menu pops up offering the library methods as they are typed, not bad. Thanks for the help.


I tried updating with : conda update -c conda-forge --update-all , but that offered jedi 0.15.2 which I already have so I figured I’ll stop troubleshooting for now since I have the functionality I was looking for. Thanks for all the help.


-David
--
David Mandelman
Staff Scientist, R&D
Clinical Next-Generation Sequencing
Life Sciences Solutions

Thermo Fisher Scientific
5781 Van Allen Wy | Carlsbad, CA  92008
Tel: +1 (760) 476-7052

**Comment by prasunsrivastava** [comment]
d Hi @Carreau . I am also facing the same issue. To reproduce the issue, I created a minimal conda environment with only `Numpy` and `IPython`. Below are the packages installed in the environment:
<pre># Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
backcall                  0.2.0                      py_0  
blas                      1.0                         mkl  
ca-certificates           2020.6.24                     0  
certifi                   2020.6.20                py38_0  
decorator                 4.4.2                      py_0  
intel-openmp              2020.1                      217  
ipython                   7.16.1           py38h5ca1d4c_0  
ipython_genutils          0.2.0                    py38_0  
jedi                      0.17.0                   py38_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
mkl                       2020.1                      217  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.1.0            py38h23d657b_0  
mkl_random                1.1.1            py38h0573a6f_0  
ncurses                   6.2                  he6710b0_1  
numpy                     1.19.1           py38hbc911f0_0  
numpy-base                1.19.1           py38hfa32c7d_0  
openssl                   1.1.1g               h7b6447c_0  
parso                     0.8.0                      py_0  
pexpect                   4.8.0                    py38_0  
pickleshare               0.7.5                 py38_1000  
pip                       20.2.2                   py38_0  
prompt-toolkit            3.0.5                      py_0  
ptyprocess                0.6.0                    py38_0  
pygments                  2.6.1                      py_0  
python                    3.8.5                hcff3b4d_0  
readline                  8.0                  h7b6447c_0  
setuptools                49.2.0                   py38_0  
six                       1.15.0                     py_0  
sqlite                    3.32.3               h62c20be_0  
tk                        8.6.10               hbc83047_0  
traitlets                 4.3.3                    py38_0  
wcwidth                   0.2.5                      py_0  
wheel                     0.34.2                   py38_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
</pre>
I am running Python 3.8.5 with conda 4.8.2 on Ubuntu 20.04 LTS. 

Also, I tried checking the results fro the `Completer` object and found that it works for some of the modules and not for others. Below is an example where it shows an empty list for `Numpy` whereas it provides values for `sys`.
```
In [1]: import IPython                                                                                                                                                                                     

In [2]: import numpy as np                                                                                                                                                                                 

In [3]: import sys                                                                                                                                                                                         

In [4]: ipy = IPython.get_ipython()                                                                                                                                                                        

In [5]: ipy.Completer.all_completions('np.')                                                                                                                                                               
Out[5]: []

In [6]: ipy.Completer.all_completions('sys.')                                                                                                                                                              
Out[6]: 
['sys.abiflags',
 'sys.addaudithook',
 'sys.api_version',
 'sys.argv',
 'sys.audit',
 'sys.base_exec_prefix',
 'sys.base_prefix',
 'sys.breakpointhook',
 'sys.builtin_module_names',
 'sys.byteorder',
 'sys.call_tracing',
 'sys.callstats',
 'sys.copyright',
 'sys.displayhook',
 'sys.dont_write_bytecode',
 'sys.exc_info',
 'sys.excepthook',
 'sys.exec_prefix',
 'sys.executable',
 'sys.exit',
 'sys.flags',
 'sys.float_info',
 'sys.float_repr_style',
 'sys.get_asyncgen_hooks',
 'sys.get_coroutine_origin_tracking_depth',
 'sys.getallocatedblocks',
 'sys.getcheckinterval',
 'sys.getdefaultencoding',
 'sys.getdlopenflags',
 'sys.getfilesystemencodeerrors',
 'sys.getfilesystemencoding',
 'sys.getprofile',
 'sys.getrecursionlimit',
 'sys.getrefcount',
 'sys.getsizeof',
 'sys.getswitchinterval',
 'sys.gettrace',
 'sys.hash_info',
 'sys.hexversion',
 'sys.implementation',
 'sys.int_info',
 'sys.intern',
 'sys.is_finalizing',
 'sys.maxsize',
 'sys.maxunicode',
 'sys.meta_path',
 'sys.modules',
 'sys.path',
 'sys.path_hooks',
 'sys.path_importer_cache',
 'sys.platform',
 'sys.prefix',
 'sys.ps1',
 'sys.ps2',
 'sys.ps3',
 'sys.pycache_prefix',
 'sys.set_asyncgen_hooks',
 'sys.set_coroutine_origin_tracking_depth',
 'sys.setcheckinterval',
 'sys.setdlopenflags',
 'sys.setprofile',
 'sys.setrecursionlimit',
 'sys.setswitchinterval',
 'sys.settrace',
 'sys.stderr',
 'sys.stdin',
 'sys.stdout',
 'sys.thread_info',
 'sys.unraisablehook',
 'sys.version',
 'sys.version_info',
 'sys.warnoptions']

```

@david-mandelman Are you using specific nbextension for the autocomplete? I tried doing the same and did not get the autocomplete suggestions. I turned on hinterland, and it still can not perform the auto-completions.

Any help from the community will be much appreciated. 

Thanks

**Comment by tsokar** [comment]
Hi, I am experiencing the same issue on "stock" ipython/python/numpy in Manjaro and archlinux.
I followed the test proposed by @prasunsrivastava and get the same behaviour.
Any hint ?

Thanks !

**Comment by tsokar** [comment]
@Carreau : I tested with jedi git  v0.17.2 r141.216f976f and completion works again with numpy.
Thanks a lot !
Just a question, what (in your opinion) changed in jedi 0.17.2 vs 0.17.0 that may lead to the issue ?

T.

**Comment by Carreau** [comment]
I don't know, I just know that when david wake patch releases it's often for critical bugs. I also know that 0.17.0 had bugs as many software (spyder for example) explicitly exclude it.

**Comment by jjstickel** [comment]
I figure out how to run ipython with `--IPCompleter.debug=True`. I get this

```
In [1]: np.araOops Jedi has crashed, please report a bug with the following:
   ...: """
   ...: '/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/num
   ...: py/__init__.py'
   ...: s"""
```
Not a lot of information. FWIW, you can disable use of jedi with the option ` --IPCompleter.use_jedi=False`, and auto-completion works again.

**Comment by mdruiter** [comment]
I had accidentally installed parso 0.8.0, which jedi 0.17.2 didn't like. I reinstalled jedi, which downgraded parso to 0.7.1, and now it works again!

**Comment by imavo** [comment]
Using ipython 7.19.0 with Python 3.8.5 on ubuntu 20.04.

Tab completion causes crash with module subprocess.

The parso verison is 0.8.1 (makes no difference if downgraded to 0.7.1, same crash).

The jedi verison ist 0.18.0.

Using `ipython --IPCompleter.use_jedi=False`  lets tab completion work for this module.

Using `ipython --IPComplete.debug

Traceback (most recent call last):
  File "/home/xxx04/pyenv1/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 113, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/home/xxx04/pyenv1/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 129, in _get_completions
    for c in completions:
  File "/home/xxx04/pyenv1/lib/python3.8/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/home/xxx04/pyenv1/lib/python3.8/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/home/xxx04/pyenv1/lib/python3.8/site-packages/IPython/core/completer.py", line 1861, in _completions
    matched_text, matches, matches_origin, jedi_matches = self._complete(
  File "/home/xxx04/pyenv1/lib/python3.8/site-packages/IPython/core/completer.py", line 2029, in _complete
    completions = self._jedi_matches(
  File "/home/xxx04/pyenv1/lib/python3.8/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches
    interpreter = jedi.Interpreter(
  File "/home/xxx04/pyenv1/lib/python3.8/site-packages/jedi/api/__init__.py", line 725, in __init__
    super().__init__(code, environment=environment,
TypeError: __init__() got an unexpected keyword argument 'column'

**Comment by Carreau** [comment]
#12793 fixes it.
