### ISSUE TITLE
https://localhost:9999无法链接，求解！🙏

### ISSUE THREAD

**Issue by nova679** [ipython/ipython#12138]
```
from http.server import HTTPServer, BaseHTTPRequestHandler

class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
      self.send_response(200)
      self.send_header('content_type','text/plain;charset=utf-8')
      self.end_header()

      self.wfile.write("Helle everyone, I am Willam, I am a AI serer~ And this is a page of:".encode()+self.path[1:].encode())

if __name__ == '__main__':
    server_address=('',9999)    
    httpd=HTTPServer(server_address,Handler) 
    httpd.serve_forever()
```

**Comment by Carreau** [comment]
I'm not sure I understand your problem.

If you are trying to run this from within Jupyter then:
  1. this is not the right repo, this is for IPython.
  2. you cannot do that as Jupyter is a server itself.

You want to put this in a python file and from a terminal use `python yourfile.py`.

I'm closing as there is not much to do, but feel free to still comment.
