### ISSUE TITLE
displaying latex \neq does not work

### ISSUE THREAD

**Issue by gokhansolak** [ipython/ipython#12133]
I am using the Jupyter notebook on Ubuntu 16.04. I get an error when I want to display the "not equal" (\neq) symbol in python code, while "greater or equal" (\geq) works fine, as follows:

![image](https://user-images.githubusercontent.com/6887994/74612734-0f7e3280-5100-11ea-8fbe-c5c5a779d7b0.png)

[File to reproduce the problem](https://gist.github.com/gokhansolak/8ea060fb22bd266f0eb03b032d4fc37b)

Version info:
```
jupyter core     : 4.6.2
jupyter-notebook : 6.0.3
qtconsole        : not installed
ipython          : 6.2.1
ipykernel        : 4.8.2
jupyter client   : 5.3.4
jupyter lab      : 1.2.6
nbconvert        : 5.6.1
ipywidgets       : not installed
nbformat         : 5.0.4
traitlets        : 4.3.2
```

**Comment by Carreau** [comment]
`\n` is a new line in Python. If you want to actually have a backslash and an n in a string you need to :
1) use rawstring. 
2) escape the backslashes:

```
Latex('$$\\neq$$')
```

and 
```
Latex(r'$$\neq$$')
```

Will both work. Closing as there is nothing we can do, and it is expected python behavior.

Note that you should do the same with `\\geq` as `\g` is invalid escape sequence. You will find the same issue with anything that starts with `\t`, `\r`, `\a`...
