### ISSUE TITLE
Adding a two column view to the notebook. 

### ISSUE THREAD

**Issue by Tillsten** [ipython/ipython#1214]
I think would be nice to have an optional two column view of the notebook:
Left column would be the input cells and right column the output of the cell,
the height of both cells is the same.

**Comment by tangyouze** [comment]
I think ipython notebook is now called jupyter? May I know if this feature is implemented or not?

**Comment by takluyver** [comment]
> I think ipython notebook is now called jupyter?

Yep!

> May I know if this feature is implemented or not?

It's not.

**Comment by tangyouze** [comment]
So what I should do is open a new issue in https://github.com/jupyter/notebook and fork that repo 
 and send PR to that repo?

**Comment by takluyver** [comment]
Yep, that's the relevant repo. I don't know if it would be easier to do it in Jupyterlab, the new new interface, though.

Closing here since it's certainly no longer an IPython issue.
