### ISSUE TITLE
ipython 5 won't install on python 2.7

### ISSUE THREAD

**Issue by daggaz** [ipython/ipython#12173]
The latest release (2.6.x) of the pygments dependency is python >=3.5 only.

As the pygment version is unbounded by ipython, this breaks the installation of ipython 5.9.0 on python 2.7 (this is last version supporting python 2).

If you wish to maintain the support of ipython on python 2.7, then you need to pin pygments to <2.6.

**Comment by Carreau** [comment]
Fixed in 5.x I'll release 5.10 soon.
