### ISSUE TITLE
Ctrl-C doesn't work to clear a line of input when using wx

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#122]
In previous versions of IPython, you could use Ctrl-C to clear a line of input.  This no longer works if GUI event loop integration is running with wx or qt.  This is because of how the wx and qt inputhooks handle KeyboardInterrupt.  But, this does work in Tk, which means it is possible to fix this issue.  We need to investigate and fix.

**Comment by Carreau** [comment]
That should be fixed now that we use PTK. 

Thanks all, please reopen an issue if needed.
