### ISSUE TITLE
Suggest %pip or %conda when user types !pip or !conda

### ISSUE THREAD

**Issue by mdeff** [ipython/ipython#12204]
To guide users towards doing things right, could we suggest they use the magics instead of the shell invocations? Possibly with a short explanation why. Was also mentioned in <https://github.com/ipython/ipython/pull/11524#issuecomment-444875270>.

**Comment by angulartist** [comment]
Hello, I'd like to work on this

As a beginner, can you give me a hint on how I can catch these !commands ?

**Comment by Inception95** [comment]
Hi, if this issue is still open, can I work on it?

**Comment by ashwinvis** [comment]
For completeness, we could also warn when `!cd` is executed.
