### ISSUE TITLE
Move display classes (JavaScript, HTML...) under IPython.lib.display

### ISSUE THREAD

**Issue by martinRenou** [ipython/ipython#12223]
Following our discussion @Carreau.

In xeus-python, we monkey-patch the `IPython.core.display` module in order to plug the base display functions to the xeus display logic.

Our problem is that there are lots of classes in this module that we don't actually need to monkey patch:
`'DisplayObject', 'TextDisplayObject', 'Pretty', 'HTML', 'Markdown', 'Math', 'Latex', 'SVG', 'ProgressBar', 'JSON', 'GeoJSON', 'Javascript', 'Image', 'set_matplotlib_formats',
'set_matplotlib_close' and 'Video'`. 

We only need to monkey-patch `'display', 'display_pretty', 'display_html', 'display_markdown', 'display_svg', 'display_png', 'display_jpeg', 'display_latex', 'display_json', 'display_javascript', 'display_pdf', 'clear_output', 'publish_display_data' and 'update_display'`

I am wondering if we could move all the classes that we don't need to monkey-patch from `IPython.core.display` to `IPython.lib.display`.

I can come up with a PR myself, I just need the green light from you. I guess this would be a backward-incompatible change (if people are importing from `IPython.core.display`, but not if they import from `IPython.display`).

**Comment by Carreau** [comment]
I think that would be fine, we can change API in 8.0. 

we could also do it in 7.x with aliases the IPython.core.display that import from lib. 


Just to understand you do replace IPython.core.display completely so you want it to be as minimal as possible right ?

**Comment by martinRenou** [comment]
> Just to understand you do replace IPython.core.display completely so you want it to be as minimal as possible right ?

Exactly. The only approach we found was to monkey-patch this module (this one and the Comms implementation for ipywidgets support). Simply because lots of Notebooks/libraries import the display function.

**Comment by Carreau** [comment]
Marked as easy and help wanted. I have no objections, we can re expose for now  in core with a module `__getattribute__` or `__getattr__` to raise a deprecation warning.

**Comment by martinRenou** [comment]
> we could also do it in 7.x with aliases the IPython.core.display that import from lib

I'm afraid this won't be possible (at least I suppose). Because `lib` already imports `core.display`.

**Comment by ivanov** [comment]
Hi @martinRenou  and @Carreau ! Drive-by comment here, but I'm worried about how much stuff is being moved in #12239 that will unnecessarily break imports for folks unless imports continue to work from both .core.display and .lib.display under the proposed changes.

Would an alternative plan to extract the targets of the monkey-patching into their own module that both core.display and lib.display import also work here? I think that would satisfy the xeus-python monkeypatching and keep the import paths the same.

**Comment by martinRenou** [comment]
> I'm worried about how much stuff is being moved in #12239 that will unnecessarily break imports 

I agree and am willing to make things backwards-compatible. What I did is just a draft for now.

**Comment by ivanov** [comment]
> What could we call this module? `IPython.core.displaycore`?

If you write it you get to name it ;) and that seems fine to me. If you want more suggestions, maybe something like `display_protocol`, `display_functions`, or `display_implementation`, or shortened versions of those - `display_proto`, `display_funcs`, `display_impl`, or dropping the underscore, if you like.

**Comment by Carreau** [comment]
we can move most of it into IPython/lib/display.py and import it into core. There might be a circular import but I don't think that will be the case, and even though it should not be a problem. Another module is fine with me as well.

**Comment by martinRenou** [comment]
> There might be a circular import but I don't think that will be the case

I am actually not sure I understand how we won't have a circular import.

**Comment by farisachugthai** [comment]
> > There might be a circular import but I don't think that will be the case
> 
> I am actually not sure I understand how we won't have a circular import.

Hi guys! Sorry to just jump in here but if you move `DisplayObject` and `TextDisplayObject` from IPython.core.display to lib, then you can also get rid of the import statement in lib to import core.

As a result, only core would be importing lib, you move all your classes out of the way and there shouldn't be a circular import problem.

**Comment by Carreau** [comment]
The objects have been moved, and circular imports is not a problem anyway, 

Closing unless objections in which case we can reopen.
