### ISSUE TITLE
Autoreload slow

### ISSUE THREAD

**Issue by jacquespeeters** [ipython/ipython#12224]
I'm running into issue really similar to the one described here.
https://github.com/ipython/ipython/issues/11817
When I'm working on large DataFrame, 

My python version is the following
```
Python 3.7.0 (default, Jul 27 2018, 16:07:23) 
[GCC 6.3.0 20170516] on linux
```
And the result of `pip freeze | grep 'jupyter\|ipy'`

```
ipykernel==5.2.0
ipython==7.13.0
ipython-genutils==0.2.0
jupyter-client==6.1.2
jupyter-core==4.6.3
```

**Comment by Carreau** [comment]
Hum, can you share your dataframe or even something that would generate a similar Df that produce the same issue ?

**Comment by MrMino** [comment]
Given lack of response, I'm going to assume this is no longer relevant to you. If you still run into this issue, please provide something that will let us reproduce this issue - we'll reopen it.
