### ISSUE TITLE
Can we use subplots on IPython.display

### ISSUE THREAD

**Issue by Eshan-Agarwal** [ipython/ipython#12228]
I am using below code snippet to display GIF on `.ipynb` but it display all GIF in vertically one after other I tried of subplots using `matplotlib` but it's not working, Is it possible to use subplots on `IPython.display.Image`.

```py
with open('sample.gif','rb') as f:
      display(Image(data=f.read(),format="png",width=width,height=height))
```

**Comment by Carreau** [comment]
I would have a look at ipywidgets for that, they seem to have pretty extensible layout. 

https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html

**Comment by Eshan-Agarwal** [comment]
@Carreau  Thanks for reply, I have some 5 GIF and I want to display all of them in grid in .ipynb through python script, I don't get anything from link given by you, can you please point out where exactly I am mistaking?

**Comment by Carreau** [comment]
Well it's not an IPython issue. IPython does mostly execution and provide hooks.

Especially if it's an issue with colab, colab tend to not implement all of jupyter usual feature. So of it's problematic with colab I won't be able to help much.

**Comment by Eshan-Agarwal** [comment]
Thank for your help, I will look on their.
