### ISSUE TITLE
AttributeError: 'TerminalPdb' object has no attribute 'inputhook'

### ISSUE THREAD

**Issue by waleedhammam** [ipython/ipython#12233]
on windows

Python 3.8.0, ipython 7.10.1

when I try to import ipdb

![image](https://user-images.githubusercontent.com/10658229/79108421-92c1aa80-7d76-11ea-8cae-ed5d54f62d39.png)

**Comment by Carreau** [comment]
> Python 3.8.0, ipython 7.10.1

Can you please try a more recent version of IPython ? and which version of prompt toolkit ?

**Comment by waleedhammam** [comment]
I updated to `prompt-toolkit==3.0.5` and `prompt-toolkit==3.0.5` and worked ok, Thanks!
