### ISSUE TITLE
jupyter notebook unable to download .tex or .pdf: nbconvert failed: Pandoc wasn't found...

### ISSUE THREAD

**Issue by mmcoello** [ipython/ipython#12238]
Hello!

I am new to jupyter notebook, python, and linux, and do not know much of anything about bash or start up files. 

I am having the following error when I am trying to download a .tex or .pdf of my jupyter notebook .ipynb file. 

```
500 : Internal Server Error
The error was:

nbconvert failed: Pandoc wasn't found.
Please check that pandoc is installed:
http://pandoc.org/installing.html
```

I am running jupyter notebook on linux. I downloaded and unzipped the pandoc file but got stuck there. I also added pandoc to my environmental file along with nbconverter. I also installed texlive but dont know what to do/if it worked.

I found this [post on github](https://github.com/ipython/ipython/issues/5005) where someone had the same issue and fixed it but I do not understand what it means to and how to set a path variable. I have a start up file but am scared to mess with it. 
Does the path variable need to be specific for jupyter notebook outputs?!?

Please help!

Thank you!

-m

**Comment by Carreau** [comment]
Hi there, 

Thanks for your question. As a first note this is IPython, not jupyter notebook, the difference is complicated, so let's gloss over it. That being said you might find more help in https://discourse.jupyter.org/, and on the github.com/jupyter/notebook. 

1) Are you using conda ? If you are using conda than you should be able to "conda install pandoc", it will be wayyyy easier. 

2) This might be a bit long but bear with me. 

When you type a command in bash, like "jupyter", or "python" or "pandoc", linux need to know where to "search" for things. What linux will do is search in the variable "$PATH".

for example here is my PATH:

```
$ echo $PATH
/Users/bussonniermatthias/miniconda3/bin:/Users/bussonniermatthias/miniconda3/condabin:/Users/bussonniermatthias/.local/bin:/usr/local/sbin:/Users/bussonniermatthias/.idris2/bin:/Users/bussonniermatthias/bin:/Users/bussonniermatthias/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/usr/local/opt/fzf/bin
```

It will search in each of these folder _in order_, and stop on the first where it finds the command you asked. 

To change "PATH" temporarily you can just in a bash prompt do `PATH=...`, but that tends to mess things up if you just "set" it.

```
$ PATH=123
-bash: id: command not found
```

Oh no, i've messed up my path... but it's ok, I can just close my terminal and reopen. What is better is to append, or prepend to path depending of wether you want things to have high (prepend), or low (append) precedence. if you are not sure append is always safer. 

```
$ PATH=$PATH:/new/path
$ echo $PATH
/Users/bussonniermatthias/miniconda3/bin:/Users/bussonniermatthias/miniconda3/condabin:/Users/bussonniermatthias/.local/bin:/usr/local/sbin:/Users/bussonniermatthias/.idris2/bin:/Users/bussonniermatthias/bin:/Users/bussonniermatthias/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/usr/local/opt/fzf/bin:/new/path
```

Note the lack of space around equal, and when you assign you use no `$`, but the "value of PATH` have a $. 

Once you have played allong enough and want to have `$PATH` always be the new value, you can edit your ~/.bashrc, or ~/.bash_profile or well it depends on your distribution and add a line with 
```
PATH=$PATH:/the/right/thing
```

You will even probably have in this file already some stuff, for example I have that added by conda :

```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/bussonniermatthias/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/bussonniermatthias/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/bussonniermatthias/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/bussonniermatthias/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```

You might need to restart your jupyter notebook server for things to work, but if PATH is set correctly, and in bash you get something along:

```
 $ pandoc --version
pandoc 2.9.2
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2
Default user data directory: /Users/bussonniermatthias/.local/share/pandoc or /Users/bussonniermatthias/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

Then all is fine. 

Side notes: if you are on linux you like can `apt install pandoc` (one almost never download and install a an app by downloading it manually on linux). 

If you wonder "where" a command like pandoc, jupyter, python is on linux, you can use `which`, to tell you where things are:

```
 ~[master ✗] $ which pandoc
/Users/bussonniermatthias/miniconda3/bin/pandoc
 ~[master ✗] $ which jupyter
/Users/bussonniermatthias/miniconda3/bin/jupyter
 ~[master ✗] $ which ls
/bin/ls
 ~[master ✗] $ which which
/usr/bin/which
 ~[master ✗] $ which -a python
/Users/bussonniermatthias/miniconda3/bin/python
/usr/local/bin/python
/usr/bin/python
 ~[master ✗] $
```

This might help you to figure things out better, if not we can try to dig in more details.

**Comment by mmcoello** [comment]
Hello Carreau!

Thanks so much for the information. It was pretty helpful, I still have a lot more to learn. 

I am still not quite sure what I should be changing. 

Here is some more information I think could be helpful.
I am a graduate student working on my advisers server in seashell (I am told?). I am using miniconda downloaded on my own special area (?) of the server and I am using jupyter that is on the entire server for everyone... pardon my lack of proper lingo... but I have a hunch since maybe this could be the root of the issue?


``[coello@great ~]$ which python
/home/sbarc/students/coello/miniconda3/bin/python
[coello@great ~]$ which jupyter
/usr/local/bin/jupyter''

**Comment by Carreau** [comment]
> seashell

I think you mean [c-shell](https://en.wikipedia.org/wiki/C_shell), I'm not too familiar with it, but linux shells are usually relatively similar. 

Try the following:

```
$ which pandoc
/Users/bussonniermatthias/miniconda3/bin/pandoc
```

Does it find it ?

As you can see mine is in miniconda as well.

If you are using a global jupyter then you _may_ need to ask your advisor to install pandoc. Though you _can_ use nbconvert via the command line in which case you do not need to ask that to your advisor:

1) Make sure you have pandoc install in miniconda, and `nbconvert` as well:

```
$ which jupyter-nbconvert
/Users/bussonniermatthias/miniconda3/bin/jupyter-nbconvert
```

If not you can use `conda install pandoc nbconvert` to install them

2) now you can use the following to create a PDF:

```
$ jupyter nbconvert --to=pdf mynb.ipynb
```
Which should output:
```
[NbConvertApp] Converting notebook mynb.ipynb to pdf
[NbConvertApp] Writing 20420 bytes to ./notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running xelatex 3 times: ['xelatex', './notebook.tex', '-quiet']
[NbConvertApp] Running bibtex 1 time: ['bibtex', './notebook']
[NbConvertApp] WARNING | bibtex had problems, most likely because there were no citations
[NbConvertApp] PDF successfully created
[NbConvertApp] Writing 5768 bytes to mynb.pdf
```

(you can use --to=latex if you only want the.text file)

It's not in the Graphical user interface but should still work. Then you can download the `.tex`/`.pdf`

**Comment by mmcoello** [comment]
Hi Again,

Yes I do mean C-shell. Good to know.

Thank you so much for all the help.

I have been trying this on the command line also and run into issues when converting into a pdf. But it actually worked for a latex document so that is great.

Here is the error I get when I try for the pdf.

`(general) [coello@great ~]$ jupyter nbconvert --to=pdf 288lc_hw1.ipynb
[NbConvertApp] Converting notebook 288lc_hw1.ipynb to pdf
[NbConvertApp] Writing 86154 bytes to ./notebook.tex
[NbConvertApp] Building PDF
Traceback (most recent call last):
  File "/home/sbarc/students/coello/miniconda3/envs/general/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/home/sbarc/students/coello/miniconda3/envs/general/lib/python3.7/site-packages/jupyter_core/application.py", line270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/sbarc/students/coello/miniconda3/envs/general/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/sbarc/students/coello/miniconda3/envs/general/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "/home/sbarc/students/coello/miniconda3/envs/general/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/sbarc/students/coello/miniconda3/envs/general/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/sbarc/students/coello/miniconda3/envs/general/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/sbarc/students/coello/miniconda3/envs/general/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/sbarc/students/coello/miniconda3/envs/general/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/sbarc/students/coello/miniconda3/envs/general/lib/python3.7/site-packages/nbconvert/exporters/pdf.py", line 185, in from_notebook_node
    self.run_latex(tex_file)
  File "/home/sbarc/students/coello/miniconda3/envs/general/lib/python3.7/site-packages/nbconvert/exporters/pdf.py", line 156, in run_latex
    self.latex_count, log_error, raise_on_failure)
  File "/home/sbarc/students/coello/miniconda3/envs/general/lib/python3.7/site-packages/nbconvert/exporters/pdf.py", line 114, in run_command
    "at {link}.".format(formatter=command_list[0], link=link))
OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.`

I have the package texlive-core in my activate environment general.

Thanks again! Your insight has been very helpful!

**Comment by mmcoello** [comment]
This issue has not been resolved but it has been figured out. Jupyter is generating newer tex code than what the operating system CentOS-7 package installs of texlive (Based on TeX Live 2013) support. Thanks for all the help Carreau!

**Comment by arunyashla** [comment]
Convert Jupyter Notebook (.ipynb) to Python (.py) using Terminal
You can convert one or multiple Jupyter notebooks using the nbconvert package. First, install the ‘nbconvert’ and ‘jupyter’ libraries. So, install these packages using the command prompt or terminal by typing the following commands:

Execute and install below packages using command prompt:

> pip install jupyter

> pip install nbconvert
