### ISSUE TITLE
eval of a list comprehension returns a coroutine in 3.9

### ISSUE THREAD

**Issue by Erotemic** [ipython/ipython#12268]
I'm not sure this is an IPython bug, but it occurs in IPython but not in a regular Python prompt. This also only occurs in Python 3.9 (current version is 3.9.0a5). This was tested with IPython 7.13.0.

The test case that I'm using is evaluating a list comprehension. In Python 3.8 in any environment I've tried, if I run:

```python
print(eval('[i for i in range(3)]'))
```
I get 

```
[0, 1, 2]
```

However, in IPython using Python 3.9 if I run:

```python
print(eval('[i for i in range(3)]'))
```

I get

```
<coroutine object <module> at 0x7efed0a6a340>
<ipython-input-1-d9f23b1bef4d>:1: RuntimeWarning: coroutine '<module>' was never awaited
  print(eval('[i for i in range(3)]'))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

However, If I use the normal Python prompt or the command line:

`python -c "print(eval('[i for i in range(3)]', {}))"` It works. 

Note that `ipython -c "print(eval('[i for i in range(3)]'))"` produces the same coroutine output. 

The reason I'm not sure if this is an IPython bug or not is that I also encounter the issue in [xdoctest](https://github.com/Erotemic/xdoctest)  (where I've currently hacked in a workaround that checks if eval returned a coroutine to prevent if from occurring). But perhaps its a problem in both IPython and xdoctest? I'm really not sure, I'm looking for any reference on what's changed in 3.9 that might have caused this issue but I don't really see anything. 

EDIT:

I found a case where it occurs in Python 3.9 itself (caused by setting compile flags), so perhaps this is a Python issue and not an IPython issue. 

```
python -c "print(eval(compile('[i for i in range(3)]', mode='eval', filename='foo', flags=221184, dont_inherit=True), {}))"
```

**Comment by Erotemic** [comment]
I'm closing this, I'm pretty certain this is a Python issue and not an IPython issue.

**Comment by tacaswell** [comment]
Likely the same as https://github.com/ipython/ipython/issues/12216 which I have not gotten to reporting upstream yet.
