### ISSUE TITLE
test_embed_svg_url needs internet connection

### ISSUE THREAD

**Issue by frenzymadness** [ipython/ipython#12281]
Hello.

[This part](https://github.com/ipython/ipython/blob/master/IPython/core/tests/test_display.py#L109) of the test_embed_svg_url needs internet connection to download the SVG image from Wiki. But some build systems have internet connection disabled on purpose so this will fail.

It would be nice to have some decorator to skip tests like this when no internet connection is available. What do you think about it?

**Comment by Carreau** [comment]
Oh.... thanks. 

Yes we can do that, or my guess is SVG `url=` might also accept `file://` url and we can point to a local one.

**Comment by Inception95** [comment]
Hi, can I help with this question?

**Comment by Carreau** [comment]
Yes, feel free to send a PR. I even see that the test is also mocked, so we can just remove the external test. 

That would be deleting lines 109 to 112 of linked file.
