### ISSUE TITLE
Any idea why IPython.get_ipython() is returning None?

### ISSUE THREAD

**Issue by kirankotari** [ipython/ipython#12334]
```
Traceback (most recent call last):
  File "/Users/kkotari/.pyenv/versions/3.7.4/bin/ipycli", line 8, in <module>
    sys.exit(run())
  File "/Users/kkotari/.pyenv/versions/3.7.4/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipycli/ipycli.py", line 8, in run
    IPython.get_ipython().define_macro('var', """a=10
AttributeError: 'NoneType' object has no attribute 'define_macro'
```
[Repo](https://github.com/kirankotari/ipycli)

I was trying to create a python package where the scripts needs to run on IPython. Is there any special settings to create such a package. 

ipython --version
7.14.0

Thanks in advance.

**Comment by Carreau** [comment]
Yes, 

`get_ipython()` only return an IPython instance if there is one. That is to say it can be used to determine whether or not you are running inside "IPython", I put IPython between quotes as it could be ipykernel or something else. 

If you want to create an instance if there are none, you need to call `.instance()` on the class you want (typically TerminalInteractiveShell() at the CLI). 

What you can do is then simply to name your script with the `.ipy` extension and run them with `ipython <yourscripts>` and we'll try to detect magics and other things.

**Comment by kirankotari** [comment]
@Carreau Thanks, Finally I understood where I need to instantiate
```python
import IPython as ipy
from IPython.terminal.interactiveshell import TerminalInteractiveShell

shell = TerminalInteractiveShell.instance()
shell.define_macro('foo', """a,b=10,20""")
ipy.embed(display_banner=False)
```

**Comment by msacs09** [comment]
I have a requirement to start a service once the packages installed by calling command tabpy and I used below and I get error. `NoneType' object has no attribute 'system`. This same command can be executed without any issues manually in jupyter notebook by taping `!tabpy` manually .As such is there any other way we can call such commands from python script

```
from IPython import get_ipython
get_ipython().system('tabpy')
```
**error**
```
File "Tabpy_startup.py", line 8, in <module>
get_ipython().system('tabpy')
AttributeError: 'NoneType' object has no attribute 'system'
```

**Comment by Carreau** [comment]
> As such is there any other way we can call such commands from python script

Rename your script to `.ipy` and use `ipython yourscript.ipy`
use proper `os.system`, or better `subprocess` to really run a subprocess.

**Comment by msacs09** [comment]
@Carreau thank you. Sadly still doesn’t work. The script doesn’t work.  But when I run manually it does work in Jupiter notebook

**Comment by Sarah-2021-scu** [comment]
I am trying to execute a python script which has been converted from jupyter notebook. The error I get is as follows:
Traceback (most recent call last):

  File "test_score1.py", line 112, in <module>
    get_ipython().run_cell_magic(u'time', u'', u"qfile = '/data/oms/data/interim/kim2014/Fetal_Testis_Gel_Velos_27_f27.mgf'\nq = mgf.read(qfile, convert_arrays=1, read_charges=True, \n             dtype={'m/z array': np.float32, 'intensity array': np.float32, 'charge array': np.uint8})")
AttributeError: 'NoneType' object has no attribute 'run_cell_magic'

I tried renaming the script to .ipy as well but it doesn't work.

**Comment by Carreau** [comment]
> The error I get is as follows:
> Traceback (most recent call last):

As you probably correctly guessed, this is because `get_ipython()` only forwas from within IPython sessions. 



>   File "/data/oms/sarah/my_ann_solo/test_score1.py", line 20
>     def verify_extension(supported_extensions: List[str], filename: str) -> None:
>                                                                                                                        ^
> SyntaxError: invalid syntax

Can you check if IPython is not installed for Python 2 ? Or to be more sure to run IPython from Python 3, you can do:

```
/path/to/python3 -m IPython test_score1.py
```

If this still does not work, can you open a separate issues, with possibly the content of your files so that we can investigate ?

Thanks.

**Comment by Sarah-2021-scu** [comment]
Thank you for your solution. I was timing the cell in my notebook which was causing the error. On changing that the command is working fine. However I am experiencing another error of "free(): invalid pointer
Aborted (core dumped)" after execution. I guess valgrind can generate a report of the analysis but I need to have sudo permission for building the same. I am trying to do it with the build. 

Thanks in advance.

**Comment by Carreau** [comment]
Any memory error like that are really unlikely to happen because of
IPython/Python.

Timing with magics is really just a thin wrapper around  python's timeit
module so you should be able to time in pure python as well, though you
will need to put your code in strings literals.
