### ISSUE TITLE
Bug: define_macro & embed doesn't work as expected inside a method vs __main__

### ISSUE THREAD

**Issue by kirankotari** [ipython/ipython#12333]
If I have a macro inside a function doesn't work as expected, the same is working fine on `__main__` condition. Why? 

Define Macro in function throws an error..!
```
import IPython as ipy
from IPython.terminal.interactiveshell import TerminalInteractiveShell

def run():
    shell = TerminalInteractiveShell.instance()
    shell.define_macro('foo', """a,b=10,20""")
    ipy.embed(display_banner=False)

if __name__ == "__main__":
    run()
```
```
⋊> ~/c/i/i/ipycli on master ⨯ ipython test
In [1]: foo
Out[1]: IPython.macro.Macro('a,b=10,20\n')
In [2]: a,b
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-3-2fbdd1b4fa70> in <module>
----> 1 a,b
NameError: name 'a' is not defined
```

Define Macro in __main__ works fine..!
```
import IPython as ipy
from IPython.terminal.interactiveshell import TerminalInteractiveShell

if __name__ == "__main__":
    shell = TerminalInteractiveShell.instance()
    shell.define_macro('foo', """a,b=10,20""")
    ipy.embed(display_banner=False)
```
```
⋊> ~/c/i/i/ipycli on master ⨯ ipython test
In [1]: foo
In [2]: a,b
Out[2]: (10, 20)
```

IPython version 7.14.0
OS: macOS Catalina
Terminal: iTerm2  version 3.3.9

**Comment by kirankotari** [comment]
@all any updates why this is happening?

**Comment by Carreau** [comment]
Sorry I didn't had a chance to look at it yet, I haven't touched macro in forever. 

I'm not surprised it does nto work from within a function if it's inspecting frames ,but I'm unsure.

**Comment by Carreau** [comment]
I don't understand what you are asking and how your examples are working. You seem to be omitting some informations.

```
if __name__ == '__main__':
    IPython.get_ipython().define_macro('var', """a=10
b=20""")
```

This will fail  with IPython undefined. Please provide the whole file

```
$ ipython test
```

This will not give you a prompt. You need the `-i` flag.

```
Your new variables are a=10, b=20
```

Where is the code that does that ? 

If you provide approximative examples, or have done modification you are not telling me about it's going to be tough to understand.

**Comment by kirankotari** [comment]
@Carreau Sample Repo link [Repo link](https://github.com/kirankotari/ipycli/blob/master/ipycli/ipycli.ipy)
[Repo Link](https://github.com/kirankotari/ncs_pycli)

**Comment by kirankotari** [comment]
Got the solution, after defining the I need assign manually when I am calling the embed from function
`x, y = shell.user_ns['x'], shell.user_ns['y']` before `ipy.embed(display_banner=False)`
