### ISSUE TITLE
How does one capture the prompt string?

### ISSUE THREAD

**Issue by ChemGuy88** [ipython/ipython#12382]
Hello!

How do I get the string that forms the input prompt in IPython? I need that string so I can take its length. I'm trying to find the width of my terminal window. I get a partial answer from `shutil.get_terminal_size()`, but that doesn't acount for the 10 or so spaces used by the prompt, e.g., `Input [1]: `.

I have posted this on StackOverflow, if you're curious about the [application](https://stackoverflow.com/q/62309792/5478086).

**Comment by Carreau** [comment]
You seem to be maybe confusing pritting and returning ? If you print it won't be preceded by the Out prompt.

```
In [1]: 'abc'
Out[1]: 'abc'

In [2]: print('abc')
abc
```

If you really need, here is how to get the ipython instance, the template for both in and out prompt, and the prompt number:

```
In [3]: ip = get_ipython()

In [4]: ip.prompt_in1
Out[4]: 'In [\\#]: '

In [5]: ip.prompt_out
Out[5]: 'Out[\\#]: '

In [6]: ip.execution_count
Out[6]: 6
```

With that you should be able to compute what you requested.

**Comment by ChemGuy88** [comment]
Thank you! This does answer my question.
