### ISSUE TITLE
Implement a configuration UI and backend for the notebook

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#1238]
There are a variety of things in the notebook that should be configurable.  The notebook dashboard should allow users to configure all of their notebooks and that configuration information should be persisted to the server and recalled when notebooks are loaded.

Once we have created this, we should review the notebook to see what items should be made configurable.

**Comment by Carreau** [comment]
Backend now exist, UI no, but won't make it for 3.0, target as 4.0

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
