### ISSUE TITLE
Google Colab cells still running after various crashes occured

### ISSUE THREAD

**Issue by Zador-Pataki** [ipython/ipython#12390]
Hi, I am trying to make prediction for a deep learning example but I am running into repetitive  issues.

In some cases the browser becomes "unresponcive" and I am inclined to leave the page, which results in all outputs of the cells disappearing, but the cell being executed continues to execute.

In anohter case all of my chrome browsers crash... when I then return to my notebook it enters a runtime state of "busy" where gain the cell is apparently executing and yet again I see no outputs. 

Now if there was a way to go around this that would be great however I doubt it. What I really want to know is: is my code really still being executed? In other words will the prediction of my code still find themselves in my target folders?

Thanks

**Comment by Carreau** [comment]
Closing this is an issue with Colab which is a google product.
