### ISSUE TITLE
XML display similar to JSON display

### ISSUE THREAD

**Issue by samuelsinayoko** [ipython/ipython#12415]
I'm working with XML and JSON files and I love the interactive IPython.display.JSON. 
I'd love to have something similar for XML files. I've looked at the code for `IPython.display.JSON`
https://github.com/ipython/ipython/blob/master/IPython/core/display.py#L546
but I don't really see where to start. 
Happy to try and have a go is someone can point me in the right direction.

**Comment by Carreau** [comment]
Which is the target representation you want ? I'm going to assume most likely HTML right ? 

So you want to look in here:

https://ipython.readthedocs.io/en/stable/config/integrating.html#rich-display

Here is an example doing highlighting but not collapsing:



```
from pygments import highlight
from pygments.lexers import XmlLexer
from pygments.formatters import HtmlFormatter

class XML:
    
    
    def __init__(self, data):
        self.data = data
        
    def _repr_html_(self):
        return highlight(self.data, XmlLexer(), HtmlFormatter(noclasses=True))

XML('''<note>
<to>Tove</to>
<from>Jani</from>
<heading>Reminder</heading>
<body>Don't forget me this weekend!</body>
</note>''')
```

<img width="594" alt="Screen Shot 2020-07-01 at 18 15 51" src="https://user-images.githubusercontent.com/335567/86305612-eea60d80-bbc6-11ea-99aa-9813c4eec890.png">

**Comment by samuelsinayoko** [comment]
Yes I was thinking of targeting the HTML representation. I guess I’d need some JavaScript to cover the folding part, any pointers for how to approach this?

**Comment by Carreau** [comment]
Hum, I haven't touch JS in a while. 

you can try https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details for a non-JS based approach.

You can try to look at tree libraries like https://github.com/QuantStack/ipytree you might be able to see how to use those to make a tree.

**Comment by samuelsinayoko** [comment]
That’s super helpful thanks. Wasn’t aware of details, should be enough to get me going.

**Comment by Carreau** [comment]
No problem, closing here but you should still be able to comments, if that's not enough and you get stuck feel free to ask.
