### ISSUE TITLE
SyntaxWarning when ipython is launched

### ISSUE THREAD

**Issue by fortin** [ipython/ipython#12423]
On a new install of IPython via Homebrew with Python 3.8.3 on macOS 10.15.5, I get the following error when I run `ipython`:

```
/usr/local/Cellar/ipython/7.15.0/libexec/vendor/lib/python3.8/site-packages/traitlets/config/loader.py:795: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(key) is 1:
/usr/local/Cellar/ipython/7.15.0/libexec/vendor/lib/python3.8/site-packages/traitlets/config/loader.py:804: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(key) is 1:
```

Is this a bug or is there something wrong with my installation? Thanks.

**Comment by Carreau** [comment]
That's just a warning, so it's fine. And that's in traitlets, not IPython. It is fixed in traitlets master.
