### ISSUE TITLE
IPython 5.10 doesn't work on Python 3.8

### ISSUE THREAD

**Issue by bmw** [ipython/ipython#12432]
When using IPython 5.10 on Python 3.8, I am unable to import modules in the interactive shell. The output is:
```
In [1]: import os
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/my/homebrew/path/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/codeop.py in __call__(self, source, filename, symbol)
    134 
    135     def __call__(self, source, filename, symbol):
--> 136         codeob = compile(source, filename, symbol, self.flags, 1)
    137         for feature in _features:
    138             if codeob.co_flags & feature.compiler_flag:

TypeError: required field "type_ignores" missing from Module
```
I think this is the same problem as https://github.com/ipython/ipython/issues/11590, however, it was never fixed in the 5.x series.

Is this something you all would be willing to fix? My use case is I'm maintaining a project that still supports Python 2.7 so we have IPython pinned to 5.10, but this doesn't work with newer versions of Python.

**Comment by Carreau** [comment]
If you send PRs to the 5.x branch I'm happy to merge them and do source releases, 
you probably can do conditional versions but that might not even be necessary.

If users have pip>9, you do not need to pin, IPython 6+ will (should?) not install on Python 2, as  it is properly tagged with `setuptools_extra_args['python_requires'] = '>=3.3'` and pip will only consider IPython up to 5.x.

At least that works for me on a fresh 2.7 env; with a loose requirement in IPython, I still get only the latest compatible one.

<img width="532" alt="Screen Shot 2020-07-23 at 16 42 50" src="https://user-images.githubusercontent.com/335567/88348944-9795e300-cd03-11ea-81ef-b2ec3a1e2637.png">

**Comment by bmw** [comment]
Thanks for the response and suggested workarounds!

I ended up just taking more steps in my project towards dropping Python 2 support which is probably better anyway.

I'm satisfied here, so you're welcome to close this issue if you want.

**Comment by tacaswell** [comment]
Not sure on the scope of your projects, but https://numpy.org/neps/nep-0029-deprecation_policy.html may be a good starting point for making support window decisions.

**Comment by Carreau** [comment]
@bmw great, let us know if you need any help, have a look at https://python3statement.org/practicalities/ as well for some tips. 

@tacaswell you changed your avatar ? How am I supposed to recognize you ? 

Closing but feel free to ask questions.
