### ISSUE TITLE
I'm getting this error message while using Jupiter notebook, Just started learning Python. Can someone help me out ? --------------------------------------------------------------------------- TypeError                                 Traceback (most recent call last) <ipython-input-36-6edacf022ee7> in <module> ----> 1 my_dog = Dog(breed='cat')  TypeError: Dog() takes no arguments

### ISSUE THREAD

**Issue by dreamchaserami** [ipython/ipython#12441]

**Comment by dreamchaserami** [comment]
<img width="1119" alt="Screen Shot 2020-07-14 at 5 36 42 PM" src="https://user-images.githubusercontent.com/64211001/87483182-afc97c00-c5f8-11ea-83f4-559db0521b46.png">

**Comment by trifle** [comment]
@dreamchaserami Your init method lacks underscores. It's two: `__init__(…)`, not one: `_init(…)`.

**Comment by Carreau** [comment]
thanks @trifle for responding ! @dreamchaserami this is a bug tracker, so it might not be the best place to find help ! Hope you are enjoying Python; closing as there is not much to address here, but you can keep up with the discussion.
