### ISSUE TITLE
Feature Request:  %history -g limit to last n sessions

### ISSUE THREAD

**Issue by DanielGoldfarb** [ipython/ipython#12451]
- presently `hist -g` globs ***all*** sessions.
- `hist -g -l <n>` can limit the glob to the last `n` lines of each session,
- but as far as I can tell there is no way to simply grep the last `n` sessions, nor to grep only the range specified.

I would like to be able to do either or both of:

`hist ~4/1-~0/10 -g <pattern>`  to search between line 1 four session ago, until the present session line 10, or

`hist -g <pattern> -s <n>` to limit the -g search to the last `n` sessions (instead of just the last `n` lines of each session).

If somewhere can point me to the code that handles `hist -g <pattern> -l <n>` then I think I will be able to contribute this change myself.  Thanks.  --Daniel

**Comment by Carreau** [comment]
History magic is defined here:

https://github.com/ipython/ipython/blob/624a95c10b5e3fe6067686ad5e10bbd5fd665f8f/IPython/core/magics/history.py

Pattern and limit handling go into the history manger there:

https://github.com/ipython/ipython/blob/624a95c10b5e3fe6067686ad5e10bbd5fd665f8f/IPython/core/magics/history.py#L170-L189

Default history will get queries into SQL/SQlite there:

https://github.com/ipython/ipython/blob/624a95c10b5e3fe6067686ad5e10bbd5fd665f8f/IPython/core/history.py#L347-L386

I haven't looked at the code in a while, but I also thing that `~x` should mean all of session x by default. Let me know if you need more quidance.

**Comment by DanielGoldfarb** [comment]
Many thanks!  I glanced through the code and it appears fairly straight forward.  I hope to have some time to start playing with it next week sometime.   Again, thank you.

**Comment by Carreau** [comment]
> Many thanks! I glanced through the code and it appears fairly straight forward. I hope to have some time to start playing with it next week. Again, thank you.

No, thank you for the request and the proposal to contribute !

**Comment by DanielGoldfarb** [comment]
@Carreau -  What can I do to get PR #12854 looked at/merged ?   Thanks. --Daniel

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. @DanielGoldfarb 's #12854 was merged to provide this feature. 

Thanks everyone and happy hacking! :bowtie:
