### ISSUE TITLE
Closing window of iTerm2 with running ipython instance leaves spin loop python 3.8 process.

### ISSUE THREAD

**Issue by hardkrash** [ipython/ipython#12469]
When closing the terminal window running ipython 7.15.0 and 7.16.1 from an iTerm2 window with python 3.8.1 python.org framework install on macOS 10.15.4 will leave a stuck python3.8 process at 100% CPU load.

This does not occur with OS X Terminal so it may be an iTerm2 issue.
But with the destruction of the window, leaves a stuck process consuming a processor.

Are there any tips to gather information to assist in debugging this issue?

**Comment by Carreau** [comment]
Iterm2 does that on purpose, you can "undo" closing a window. See that in iterm2 prefs.
