### ISSUE TITLE
What is the key timeout of ipython?

### ISSUE THREAD

**Issue by SleepyBag** [ipython/ipython#12468]
I am using ipython with vim mode. In general, it works well. 

But when I press esc and another key like 'b' quickly, it will take it as alt-b. 

In most other terminal applications, there would be a setting item named keytimeout, which control for how long time it would be expecting the next character after entering esc. So I wonder if ipython has a similar setting? I tried to seek for it in online documentation but found nothing. Thank you!

**Comment by Carreau** [comment]
I believe that we can't do that because of the terminal mode. It only possible if we take over the full terminal screen which prompt toolkit does not.

Of anything this is a prompt toolkit question.

**Comment by SleepyBag** [comment]
I understand. Thank you for your kindly reply!
