### ISSUE TITLE
Problem with ipython installation

### ISSUE THREAD

**Issue by MuslimBeibytuly** [ipython/ipython#12489]
ERROR: Could not find a version that satisfies the requirement ipython==7.17.0 (from -r src/requirements.txt (line 22)) (from versions: 0.10, 0.10.1, 0.10.2, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.13.2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 4.0.0b1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0rc1, 4.1.0rc2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 5.0.0b1, 5.0.0b2, 5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.4.0, 5.4.1, 5.5.0, 5.6.0, 5.7.0, 5.8.0, 5.9.0, 5.10.0, 6.0.0rc1, 6.0.0, 6.1.0, 6.2.0, 6.2.1, 6.3.0, 6.3.1, 6.4.0, 6.5.0, 7.0.0b1, 7.0.0rc1, 7.0.0, 7.0.1, 7.1.0, 7.1.1, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.6.1, 7.7.0, 7.8.0, 7.9.0, 7.10.0, 7.10.1, 7.10.2, 7.11.0, 7.11.1, 7.12.0, 7.13.0, 7.14.0, 7.15.0, 7.16.0, 7.16.1)
ERROR: No matching distribution found for ipython==7.17.0 (from -r src/requirements.txt (line 22))
Python 3.6.7, Ubuntu 18.04

**Comment by sximba** [comment]
I also ran into this issue. My dev environment and production environment are using different python versions. ipython 7.17+ only installs on python 3.7+

**Comment by Carreau** [comment]
Please report upstream to pip who recently added a dependency resolver. 
Also please include where src/requirements.txt is from.

**Comment by Carreau** [comment]
> Python 3.6.7

Also IPython 7.17 is not compatible with Python 3.6.
