### ISSUE TITLE
No matching distribution found for ipython==7.17.0 in Python 3.6 

### ISSUE THREAD

**Issue by amrishparmar** [ipython/ipython#12509]
OS: macOS 10.15
Python: 3.6

To replicate:
- Use a Python 3.6 environment
```
(python3.6) ➜  ~  pip install ipython==7.17.0
ERROR: Could not find a version that satisfies the requirement ipython==7.17.0 (from versions: 0.10, 0.10.1, 0.10.2, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.13.2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 4.0.0b1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0rc1, 4.1.0rc2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 5.0.0b1, 5.0.0b2, 5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.4.0, 5.4.1, 5.5.0, 5.6.0, 5.7.0, 5.8.0, 5.9.0, 5.10.0, 6.0.0rc1, 6.0.0, 6.1.0, 6.2.0, 6.2.1, 6.3.0, 6.3.1, 6.4.0, 6.5.0, 7.0.0b1, 7.0.0rc1, 7.0.0, 7.0.1, 7.1.0, 7.1.1, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.6.1, 7.7.0, 7.8.0, 7.9.0, 7.10.0, 7.10.1, 7.10.2, 7.11.0, 7.11.1, 7.12.0, 7.13.0, 7.14.0, 7.15.0, 7.16.0, 7.16.1)
ERROR: No matching distribution found for ipython==7.17.0
```

I also see the exact same result in a Debian Docker Python 3.6 image.

Works fine under Python 3.7/3.8

**Comment by Carreau** [comment]
Yes. On purpose and documented.

https://ipython.readthedocs.io/en/latest/whatsnew/version7.html

> PR #12410 finally remove support for 3.6, while the codebase is still technically compatible; IPython will not install on Python 3.6.

https://discourse.jupyter.org/t/release-of-ipython-7-17/5449

> IPython will not install on Python 3.6 anymore (unless you force it to), and it is not guaranteed to work.


setup.py

>     error = """
IPython 7.17+ supports Python 3.7 and above, following NEP 29.
When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
Python 3.3 and 3.4 were supported up to IPython 6.x.
Python 3.5 was supported with IPython 7.0 to 7.9.
Python 3.6 was supported with IPython up to 7.16.

Readme:

> Starting with IPython 7.10, IPython follows NEP 29

...
