### ISSUE TITLE
Pathlib, Pathlib everywhere.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#12515]
There are many places where we could make use of Pathlib. 

Look for any places that uses `with open(...)` and ask yourself:

- is the argument a string ? 
- would it make sens to make it a `Path()`, 
- how far upstream in the code can I make it a Path.

Don't try to bite more than you can chew (or more than I can review), try to fix 1 place at a time.

**Comment by Carreau** [comment]
for example see https://github.com/ipython/ipython/pull/12512

**Comment by Inception95** [comment]
Hi @Carreau, if no one is working on /core/page.py for using Pathlib, can I take this part?

**Comment by Carreau** [comment]
> Hi @Carreau, if no one is working on /core/page.py for using Pathlib, can I take this part?

Sure, please. Thanks.

**Comment by barhenkro** [comment]
Hi, I would like to work on core/interactiveshell.py and add there more use of Pathlib.
Can I help with that?

**Comment by OdinTech3** [comment]
Hey @Carreau can I take on testing/iptestcontroller.py and core/magics/execution.py ?

**Comment by arindam9999** [comment]
Hi, I would like to work on ipython/IPython/core/completer.py  and change string to Path.
Can I help with that?

**Comment by MrMino** [comment]
Might also be of use: https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module

There are many places other than `with open()` that might use pathlib treatment:

```diff
-    conda_history = os.path.join(sys.prefix, 'conda-meta', 'history')
-    return os.path.exists(conda_history)
+    return Path(sys.prefix, 'conda-meta', 'history').exists()
```

**Comment by OdinTech3** [comment]
That's a good point.

**Comment by MrMino** [comment]
> Might also be of use: https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module
> 
> There are many places other than `with open()` that might use pathlib treatment:
> 
> ```diff
> -    conda_history = os.path.join(sys.prefix, 'conda-meta', 'history')
> -    return os.path.exists(conda_history)
> +    return Path(sys.prefix, 'conda-meta', 'history').exists()
> ```


Although some of them might be less trivial and more error prone, especially when they're interpreted as text. For example, when returning a `PosixPath` object breaks code in the scope above because it is being `' '.join()`-ed with other shell arguments.

**Comment by sumagnadas** [comment]
I searched for the functions in the whole project and i found many of them. Should i consider replacing all of them with Pathlib alternatives or what files should i consider not replacing the functions in?

Sorry if i couldn't make you understand what i want to say.

**Comment by davbrito** [comment]
I'm working on `paths.py` and I found the following line in several functions:

> ```python
> assert isinstance(ipdir, str)
> ```

One of such assertions gives a message saying `"all path manipulation should be str(unicode), but are not."`.

Should I delete such lines so the move to pathlib can work?

**Comment by sumagnadas** [comment]
Yea some places are not working because of that.

> I'm working on `paths.py` and I found the following line in several functions:
> 
> > ```python
> > assert isinstance(ipdir, str)
> > ```
> 
> One of such assertions gives a message saying `"all path manipulation should be str(unicode), but are not."`.
> 
> Should I delete such lines so the move to pathlib can work?

**Comment by Carreau** [comment]
Hi everyone, I'm trying to review all the PRs, there are many tacking this issues, be careful some of you are sending changes for which there are already other PRs opened.

**Comment by sumagnadas** [comment]
Why is this closed now?

**Comment by ashwinvis** [comment]
@meeseeksdev open

**Comment by squarebat** [comment]
I am new to open source contribution and would love to work on this issue. After I am done with my changes, what would be the easiest way to test the code before I create a PR?

**Comment by davbrito** [comment]
> I am new to open source contribution and would love to work on this issue. After I am done with my changes, what would be the easiest way to test the code before I create a PR?

Hello @squarebat 
You should do this:
- Install the testing dependencies this by running this command in the root of the repo:

```
$ pip3 install -e .[test]
```
- Then execute the tests with
```
$ iptest
```

**Comment by squarebat** [comment]
I want to work on the ```test_run.py``` file. However, I'm having trouble resolving some errors in that file. The two main errors are

-  ```undefined variable get_ipython``` (This one is resolved by adding an import but that seems wrong)

-  ```undefined variable _ip``` : In some functions ```_ip``` is initialized as ```_ip = get_ipython()``` hence defining it, but in other functions it not initialized, hence causing error. 

I have set up my environment using ```pip install .```
I just wanted to know if I made a mistake while setting up the environment, or if there is a bug in the ```test_run.py``` file.

**Comment by davbrito** [comment]
> I have set up my environment using `pip install `

You have to use `pip install -e .[test]`

The `-e` means that you Install it in editable mode.

**Comment by Joe-Sin7h** [comment]
Hello! This is my first time contributing to an open source project , I would like to work on this issue .
can i get assigned ?

**Comment by ThisIsMatin** [comment]
Hi @Carreau, may I work on /core/logger.py to use Pathlib? (If no one is working on this file)

**Comment by nitin-pandita** [comment]
Hey, I would love to work on this issue, as a beginner in Open source I think I can make it work. Thank you

**Comment by HmbleCreator** [comment]
Hey, I would love to work on this issue can you assign it to me ?

**Comment by kevin1kevin1k** [comment]
I am also willing to work on this, possibly on different set of files.

**Comment by Carreau** [comment]
Closing this issue, 

In general this is open source, we can't/won't assign people to it; if you want to work on something you are free to do so; You can comment that you are planning on doing X/Y/Z to avoid people doing duplicate work,  you can also submit draft/incomplete PRs to show that you are working on it. 

But keep in mind that  in general maintainer will tend to just ignore those comments as too many people say "I will do X" and never do it. 



Even if closed, if you believe some files may make use of better libraries like pathlib, feel free to do so, but please keep your PRs _small_.
