### ISSUE TITLE
Coconut kernels not working

### ISSUE THREAD

**Issue by regr4** [ipython/ipython#12533]
Hi, I was trying to get the [Coconut](https://github.com/evhub/coconut) kernel to work with jupyter and ipython, but when I try to run anything, I get the following error message:

    ----------------------------------------------------------
    TypeError                Traceback (most recent call last)
    /usr/local/lib/python3.8/site-packages/IPython/core/async_helpers.py in _pseudo_sync_runner(coro)
     66     """
     67     try:
    ---> 68         coro.send(None)
     69     except StopIteration as exc:
     70         return exc.value

    /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/coroutines.py in coro(*args, **kw)
    122         @functools.wraps(func)
    123         def coro(*args, **kw):
    --> 124             res = func(*args, **kw)
    125             if (base_futures.isfuture(res) or inspect.isgenerator(res) or
    126                     isinstance(res, CoroWrapper)):

    TypeError: run_cell_async() got an unexpected keyword argument 'transformed_cell'

This happens in Jupyter notebooks, in Jupyterlab and in the ipython repl.

I originally opened an issue [here](https://github.com/evhub/coconut/issues/551#issue-690423739), but got told it was probably a problem with ipython

What I've tried so far:
- removing and reinstalling the coconut kernels
- uninstalling [coconut](https://pypi.org/project/coconut/) and installing [coconut-develop](https://pypi.org/project/coconut-develop/) and its kernels
- searching through the github issues for the same problem.
- upgrading jupyter and all its dependencies to the latest version

my OS is macOS Catalina, 10.15.6. I have python 3.8 installed via homebrew.

The output from `jupyter --version` is:
    jupyter core : 4.6.3
    jupyter-notebook : 6.1.3
    qtconsole : 4.7.6
    ipython : 7.18.1
    ipykernel : 5.3.4
    jupyter client : 6.1.7
    jupyter lab : 2.2.6
    nbconvert : 5.6.1
    ipywidgets : 7.5.1
    nbformat : 5.0.7
    traitlets : 5.0.0

The output from `IPython.sys_info()` is:
{'commit_hash': 'e78905a3c',
'commit_source': 'installation',
'default_encoding': 'utf-8',
'ipython_path': '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython',
'ipython_version': '7.14.0',
'os_name': 'posix',
'platform': 'macOS-10.15.6-x86_64-i386-64bit',
'sys_executable': '/usr/local/bin/python3',
'sys_platform': 'darwin',
'sys_version': '3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) \n'
                '[Clang 6.0 (clang-600.0.57)]'}

(also, thanks for ipython, it's great!)

**Comment by xxdavid** [comment]
Hey, I had the same problem as you do (and also macOS Catalina, Python 3.8 from brew). For me, the issue was resolved by downgrading coconut to 1.4.0 (with `pip install --force-reinstall coconut==1.4.0`). I tried all the newer versions too (1.4.1, 1.4.2 and 1.4.3) but it seems it's broken since 1.4.1.

For record:
```
$ jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : 4.7.7
ipython          : 7.18.1
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.8
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 5.0.4
```

Thank you for making coconut! Tell me if there's anything I can do to fix this bug in newer versions.

**Comment by ruivieira** [comment]
This is still happening with Jupyter Lab 2.2.8.

```
$ coconut -v
Coconut: Version 1.4.3 [Ernest Scribbler] running on Python 3.8.5
```

macOS 10.15.6.

`IPython.sys_info()`:

```
"{'commit_hash': '95d2b79a2',
   'commit_source': 'installation',
   'default_encoding': 'utf-8',
   'ipython_path': '/Users/ruivieira/Library/Caches/pypoetry/virtualenvs/python-experiments-book-gQP3g2TK-py3.8/lib/python3.8/site-packages/IPython',
   'ipython_version': '7.18.1',
   'os_name': 'posix',
   'platform': 'macOS-10.15.6-x86_64-i386-64bit',
   'sys_executable': '/Users/ruivieira/Library/Caches/pypoetry/virtualenvs/python-experiments-book-gQP3g2TK-py3.8/bin/python',
   'sys_platform': 'darwin',
   'sys_version': '3.8.5 (default, Oct  8 2020, 11:52:34) [Clang 10.0.1 ]'
}"
```

**Comment by ruivieira** [comment]
FYI this is fixed in Coconut (https://github.com/evhub/coconut/issues/551)
