### ISSUE TITLE
Changelog for 7.18.1

### ISSUE THREAD

**Issue by frenzymadness** [ipython/ipython#12531]
Hello.

Could please somebody add a documentation about what happened in 7.18.1? For example, the changelog for 7.18 says that the minimum version of jedi is now 0.16 but it's not true for 7.18.1.

I'd like to contribute but I don't understand the situation.

Thank you.

**Comment by hroncok** [comment]
See also https://github.com/ipython/ipython/compare/7.18.0...7.18.1

**Comment by frenzymadness** [comment]
I did check the diff but some explanation about the changes would be handy. For example, why the version of jedi was reverted?

**Comment by MrMino** [comment]
Probably because of issues with the PR that updated the requirement line. The code that was updated has been reverted, so the change in requirements was no longer needed.
