### ISSUE TITLE
ImportError: cannot import name 'Image' from 'IPython.display'

### ISSUE THREAD

**Issue by gunstonej** [ipython/ipython#12561]
i'm getting some strange behaviour - 

i'm testing a xeus-python environment, 

in a jupyterlab notebook, if i type
` from IPython.display import display, JSON, Markdown, HTML, display_pdf, clear_output`

i get no issues, but:
` from IPython.display import Image`

returns
> ---------------------------------------------------------------------------
>ImportError                               Traceback (most recent call last)
>In  [15]:
>Line 1:     from IPython.display import Image
>
>ImportError: cannot import name 'Image' from 'IPython.display' (C:\Users\j.gunstone\Miniconda3\envs\jupyterlab-debugger\lib\site-packages\IPython\display.py)

in any other environment importing Image as shown works with no issue.

here is a explicit spec file of my environment
[jupyterlab-debugger.txt](https://github.com/ipython/ipython/files/5282554/jupyterlab-debugger.txt)

**Comment by miguelcard** [comment]
I have the same issue, seems only to be happening in jupyter lab, not in my jupyter notebook (even using the same enviroment)

**Comment by miguelcard** [comment]
@gunstonej Could you solve the issue somehow?

**Comment by miguelcard** [comment]
I noticed it wasn't working with the xpython kernel I normally use for debugging but once you change the kernel to Python3 it should work, at least it did for me, hopefully that still helps :)

**Comment by gunstonej** [comment]
@miguelcard - sorry for the delay. opened the issue in xeus-python and closed here.

**Comment by VivekMishra96** [comment]
ImportError: cannot import name 'render_site' from 'IPYNB_RENDERER.site' (C:\Users\acer\Desktop\IPYNB_renderer\src\IPYNB_RENDERER\site.py)


I am getting this error could you just help me out
