### ISSUE TITLE
IPython Crashes when Executing Command

### ISSUE THREAD

**Issue by Carrey904** [ipython/ipython#12590]
When I execute a command in IPython, it returns the result of the command but with an error. Later IPython exits. This seems to happen randomly on different terminals.
```
C:\Users\14116>ipython
Python 3.8.3rc1 (tags/v3.8.3rc1:802eb67, Apr 29 2020, 21:39:14) [MSC v.1924 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: 1
Out[1]: 1

In [2]: 2
Out[2]: 2

Traceback (most recent call last):
  File "c:\program files\python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001919E39C930> still has pending operation at deallocation, the process may crash
In [3]:
C:\Users\14116>
```
OS: `Windows 10`
Python Version: `3.8.3`
IPython Version: `7.18.1`

**Comment by JubilantJerry** [comment]
This is also happening on my system.
OS: Windows 10
Python: 3.10.6
IPython: 8.5.0
Asyncio: 3.4.3

I run IPython inside a virtual environment using Mambaforge, i.e. Miniconda.

The workaround I use at the moment is to open the `__init__.py` file in the `site-packages/IPython` directory, and add the following lines somewhere during the execution of the file:
```
import asyncio
import platform
if platform.system() == 'Windows':
   asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

From what I can tell, IPython doesn't play well with the default event loop policy of asyncio used on Windows (`asyncio.windows_events.WindowsProactorEventLoopPolicy` it seems). I'm not sure why this may be the case, but if there is no fix to use the other policy IPython will need a special case handling for Windows to set the event loop policy to something it supports.

**Comment by JubilantJerry** [comment]
Is there no update on this? As of version 8.9, this problem is still happening!

**Comment by JubilantJerry** [comment]
Before this can be closed, shouldn't there be an explanation? Are bugs no longer considered bugs?
