### ISSUE TITLE
Problem with tests test_get_ipython_dir_* when using pathlib

### ISSUE THREAD

**Issue by davbrito** [ipython/ipython#12651]
I am having problem passing this test:

> https://github.com/ipython/ipython/blob/3c2c1857268fba1833b324d8b4e4ce53b0220b83/IPython/core/tests/test_paths.py#L57-L69

And others similar.

The problem is this line: `patch('os.name', "posix")`. Because pathlib thinks it is running into a unix system then tries to use `PosixPath`.
Therefore it gets this error:

> ```
> ======================================================================
> ERROR: test_get_ipython_dir_2, Testcase to see if we can call get_ipython_dir without Exceptions.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "C:\Users\David\Envs\ipy\lib\site-packages\nose\case.py", line 198, in runTest
>     self.test(*self.arg)
>   File "c:\users\david\proyectos\ipython\IPython\core\tests\test_paths.py", line 67, in test_get_ipython_dir_2
>     ipdir = paths.get_ipython_dir()
>   File "c:\users\david\proyectos\ipython\IPython\paths.py", line 45, in get_ipython_dir
>     ipdir = Path(home_dir, ipdir_def)
>   File "c:\python\python38\lib\pathlib.py", line 1035, in __new__
>     raise NotImplementedError("cannot instantiate %r on your system"
> NotImplementedError: cannot instantiate 'PosixPath' on your system
> ```

@Carreau what should I do?

_Originally posted by @davbrito in https://github.com/ipython/ipython/pull/12650#issuecomment-712481472_

**Comment by davbrito** [comment]
> @meeseeksdev tag help wanted

**Comment by davbrito** [comment]
@meeseeksdev tag help wanted

**Comment by davbrito** [comment]
@meeseeksdev tag testing

**Comment by MrMino** [comment]
Patching `os.name` into posix is not a good idea IMO, especially since builtins depend on it.

**Comment by davbrito** [comment]
> Patching `os.name` into `posix` is not a good idea IMO, especially since builtins depend on its value.

Why do they do it in those tests? Is there any justification for that?
