### ISSUE TITLE
Jedi completion crashed

### ISSUE THREAD

**Issue by arache** [ipython/ipython#12705]
Hi there,

The auto completion can't do the job for some of my modules.
After setting following in my notebook, I got jedi crashed issue.

what I did in my notebook:
```
%config Completer.use_jedi = True
%config Completer.debug = True

```
Then i got this:
```
Oops Jedi has crashed, please report a bug with the following:
"""
Type __wrapped__ is neither a data type nor a request type
s"""
```
Sorry I can't get any more logs there.

packages:
ipython                  7.16.1
jupyterlab               2.1.5
notebook                 6.0.3
jedi                     0.17.2

Please let me know if any more information is required.

**Comment by marrowsuck** [comment]
Just stumbled upon this. I'm on python-3.9.0, ipyhon-7.19.0, jedi-0.17.2.
On my desktop completion is broken. Laptop works fine though (same packages).
Completion works again with the most recent git checkout from jedi -- 69750b9b.

**Comment by MrMino** [comment]
I think this has been fixed already. If not, please ping us and we'll reopen the issue
