### ISSUE TITLE
assertion error

### ISSUE THREAD

**Issue by ErickSalgado1** [ipython/ipython#12709]
so I am currently working on a school assignment but I think that my code is correct here as I am getting half of the grade correct but for the other half I get this error. I'm supposed to learn how to use classes in python.
Traceback (most recent call last):

  File "/root/sandbox6eca5c65/nt-test-3846a2cb.py", line 9, in <module>
    assert(motorcycleOne.speed == 65.0)
AssertionError

As I understand it the code the teacher used to test my code is this.

motorcycleOne = Motorcycle(90.0, 65.0, True)
motorcycleTwo = Motorcycle(85.0, 60.0, False)

motorcycleOne.accelerate(30.0)
motorcycleTwo.accelerate(20.0)

assert(motorcycleOne.speed == 65.0)
assert(motorcycleTwo.speed == 80.0)

assert(motorcycleOne.sidecar)
assert(not motorcycleTwo.sidecar)

the code that I made is for the assignment is here.

class Motorcycle:
    accelerate = 0.0
    def __init__ (self, maximumSpeed, currentSpeed, sidecar):
        self.maximumSpeed = maximumSpeed
        self.currentSpeed = currentSpeed
        self.sidecar = sidecar;
    def accelerate(self, accelerate):
        self.accelerate = accelerate
        if self.currentSpeed + self.accelerate > self.maximumSpeed:
            return print("This motorcycle cannot go that fast");
    def speed(self):
        if self.currentSpeed + self.accelerate < self.maximumSpeed:
            self.currentSpeed = self.currentSpeed + self.accelerate;
        return self.currentSpeed;
 
I do not expect to get the correct answer, but if you tell me if my code is wrong or is the code my teacher put up to blame?

**Comment by MrMino** [comment]
These kinds of questions would be better suited for StackOverflow. On this issue tracker we discuss issues specific to IPython. This seems to be general Python programming question.
