### ISSUE TITLE
ERROR:root:Internal Python error in the inspect module

### ISSUE THREAD

**Issue by Sanjeev273** [ipython/ipython#12725]
Hi smilei team members,

I have the following issue in Track-particles diagnostics when plotting the data but Particle ordering finishing successfully.
![error](https://user-images.githubusercontent.com/67734147/101881335-44d99c80-3bba-11eb-9627-02f754d139d9.JPG)
![error2](https://user-images.githubusercontent.com/67734147/101881351-4b681400-3bba-11eb-9342-9127c7512205.JPG)

Here is the output data file for simulation.
[activebeamdumping.sge.o1565740.txt](https://github.com/ipython/ipython/files/5678032/activebeamdumping.sge.o1565740.txt)
can anyone help me to solve it ?

**Comment by Carreau** [comment]
Hi there, 

I believe you may have the wrong repository, this is the issue tracker for IPython; you might be looking for https://github.com/SmileiPIC

You also likely want to provide all your code in a form that can be copy pasted for the smiley team to help you. 

Thanks,

**Comment by Sanjeev273** [comment]
> 
> 
> Hi there,
> 
> I believe you may have the wrong repository, this is the issue tracker for IPython; you might be looking for https://github.com/SmileiPIC
> 
> You also likely want to provide all your code in a form that can be copy pasted for the smiley team to help you.
> 
> Thanks,
Hi Carreau, 

Here is my Smilei script: 

#### Namelist for laser wakefield acceleration, external injection of an electron bunch defined profile: Active beam dumping
import numpy as np
from numpy import vectorize, real
import cmath
import math
l0 = 2.0*math.pi         # laser wavelength [in code units]
t0 = l0                  # optical cycle
Lsimx = 160.*l0          # length of the simulation box in x
Lsimy = 50.*l0           # length of the simulation box in y
Tsim = 67423.*t0            # duration of the simulation
resx = 4.               # nb of cells in one laser wavelength
resy = 2.
rest = resx/0.4          # nb of timesteps in one optical cycle 
dt = 0.19 #t0/rest
nx = 80.*4                # number of cells along x-axis
ny = 50.*2
npatch_x = 32           # number of patches along x-axis

# Plasma plateau density
n0 = 0.0017

# Laser parameters
laser_fwhm = 98.   #  (98/c_over_omega0 = 12.5 um )
omega = 1.
a0 = 1.
focus_laser = 3.*laser_fwhm
center_laser=3.*laser_fwhm
waist = 30. #94.26


# Bunch parameters
bunch_sigma_x = 10.6                                          # bunch longitudinal rms size
bunch_sigma_r = 4.                                          # bunch transverse rms size (cylindrical symmetry)
center_bunch = 215.                                          # bunch at 0.5*lambdap behind the laser (ok a little more because of relativistic elongation of plasma
alpha = 0.001
gamma= 1000.                                              # relativistic lorentz factor
beta = math.sqrt(1.-1/gamma**2)
relative_energy_spread = 0.01
electron_mass_eV = 0.511e6
norm_emittance_m = 1.e-6 # transverse normalized emittance


# Auxiliary physical quantities
lambda0 = 0.8e-6               # laser wavelength, m
c=299792458                    # lightspeed, m/s
omega0 = 2*math.pi*c/lambda0   # laser frequency
eps0=8.854187e-12              # Vacuum permittivity, F/m
e=1.60217646e-19               # Elementary charge, C
me=9.10938215e-31              # Electron mass, kg
ncrit = eps0*omega0**2*me/e**2 # Plasma critical number density [m-3]
normalized_species_charge = -1 # For electrons


# normalized density of a cylindrical bunch
def nbunch_(x):
        profile_x = math.exp(-(x-center_bunch)**2/2./bunch_sigma_x**2)
        #profile_r = math.exp(-((y-Main.grid_length[1]/2.)**2+(z-Main.grid_length[2]/2.)**2)/2./bunch_sigma_r**2)
        profile = alpha*n0*profile_x
        
        if (((x-center_bunch)**2/(4.*bunch_sigma_x)**2 ) < 1. ):
            return profile
        else:
            return 0.
            


Main(
    geometry = "1Dcartesian",
    
    interpolation_order = 2,

    timestep = dt,
    simulation_time = Tsim,

    cell_length  = [l0/resx],
    grid_length = [ Lsimx],

    number_of_patches = [npatch_x],
    
    clrw = nx/npatch_x,
    #clrw = 1,

    solve_relativistic_poisson = True,
    
    EM_boundary_conditions = [ ["silver-muller"] ],
    
    solve_poisson = False,
    print_every = 100,

    random_seed = smilei_mpi_rank
)

MovingWindow(
    time_start = 500.,
    velocity_x = 0.9997
)


LoadBalancing(
    initial_balance = False,
    every = 20,
    cell_load = 1.,
    frozen_particle_load = 0.1
)


Species( 
    name = "electronbunch",
    position_initialization = "regular",
    momentum_initialization = "maxwell-juettner",
    relativistic_field_initialization = True,
    particles_per_cell = 100,
    c_part_max = 1.0,
    mass = 1.0,
    charge = -1.0,
    charge_density = nbunch_,       # comment when importing numpy particles
    mean_velocity = [beta, 0.0, 0.0], # corresponds to Lorentz factor gamma = 200
    temperature = [electron_mass_eV*beta**2*beta*gamma*relative_energy_spread**2], # comment when importing numpy particles
    pusher = "boris",    
    time_frozen = 250.,    # bunch starts moving when laser peak is at 180.c/omega0 of distance, 1.25*lamdap of the plasma wave 
    boundary_conditions = [
    	["remove", "remove"],
    	
    ],
)


Species(
    name = "electron",
    position_initialization = "regular",
    momentum_initialization = "cold",
    particles_per_cell = 100,
    c_part_max = 1.0,
    ponderomotive_dynamics = True,
    mass = 1.0,
    charge = -1.0,
    charge_density = n0, #polygonal(xpoints=[focus_laser+20,focus_laser+30.,15000.,15100.],xvalues=[0.,n0,n0,0.]),
    mean_velocity = [0.0, 0.0, 0.0],
    temperature = [0.0, 0.0, 0.0],
    pusher = "ponderomotive_boris",
    time_frozen = 0.,
    boundary_conditions = [
       ["remove", "remove"],
       
    ],
)

Species(
    name = "proton",
    position_initialization = "regular",
    momentum_initialization = "cold",
    particles_per_cell = 100,
    c_part_max = 1.0,
    ponderomotive_dynamics = True,
    mass = 1836.,
    charge = 1.0,
    charge_density = n0, # polygonal(xpoints=[focus_laser+20,focus_laser+30.,15000.,15100.],xvalues=[0.,n0,n0,0.]),
    mean_velocity = [0.0, 0.0, 0.0],
    temperature = [0.0, 0.0, 0.0],
    pusher = "ponderomotive_boris",
    time_frozen = 0.0,
    boundary_conditions = [
       ["remove", "remove"],
      
    ],
)





# We build a gaussian laser from scratch instead of using LaserGaussian3D
# The goal is to test the space_time_profile attribute

focus = [focus_laser]
waist = 30.
time_envelope = tgaussian(center=center_laser, fwhm=laser_fwhm)
ellipticity = 0
    
def space_time_envelope(x,t):
        polarization_amplitude_factor = 1/math.sqrt(1.+ellipticity**2)
        return (a0*omega*polarization_amplitude_factor)*complex( vectorize(time_envelope)(t) )

LaserEnvelope(
        omega = omega,
        envelope_profile = space_time_envelope,
        envelope_solver = 'explicit',
        Envelope_boundary_conditions = [["reflective"]],
        polarization_phi =0,
        ellipticity = ellipticity
        
)

#LaserEnvelopePlanar1D(
#    omega = omega,
#    a0              = 1.,     
#    time_envelope   = tgaussian(center=center_laser, fwhm=laser_fwhm),
#    envelope_solver = 'explicit',
#     Envelope_boundary_conditions = [ ["reflective", "reflective"],
#     ],
#)

Checkpoints(
    dump_step = 0,
    dump_minutes = 0.0,
    exit_after_dump = False,
)

list_fields = ["Ex","Ey","Ez","Bx","By","Bz","Rho_electron", "Rho_electronbunch", "Jx","Jy","Jz","Env_A_abs","Env_E_abs","Env_Ex_abs"] #all fields

DiagFields(
    every = 100,
    fields = list_fields
)


DiagScalar(every = 10, vars=['Utot','Ukin', 'Uelm','Ukin_electron', 'Ukin_electronbunch', 'EyMax','EyMaxCell'])

DiagParticleBinning(
	deposited_quantity = "weight",
	every = 100,
	species = ["electron"],
	axes = [
		["x", 0, Main.grid_length[0], nx],
		["ekin", -1, 2., 100]
	]
)

DiagParticleBinning(
	deposited_quantity = "weight_ekin",
	every = 100,
	species = ["electron"],
	axes = [
		["moving_x", 0, Main.grid_length[0], nx],
		["ekin", -1, 2., 100]
	]
)

def my_filter(particles):
    return np.sqrt(particles.px**2 + particles.py**2 + particles.pz**2) > 20*me*c
    
DiagTrackParticles(
    species = "electronbunch",
    every = 100,
    filter = my_filter,
    attributes = ["x", "px", "Ex", "py", "Ey"] 
)

DiagPerformances (
         every = 100
         
)
