### ISSUE TITLE
Improving recursive Pdb

### ISSUE THREAD

**Issue by wesm** [ipython/ipython#1273]
I haven't started looking at it yet, but I'm really suffering a lot from how weak Pdb becomes in recursive mode (`debug stmt`) on Linux at least (readline navigation stops working, etc.) and I'm wondering how hard it would be to IPython-enhance the recursive debugger? Once my suffering increases enough I will do something about it myself but before I go digging I just wanted to check if I'm wasting my time or if there are any low hanging fruit there

**Comment by segevfiner** [comment]
This is still an issue in IPython 5 and probably 6, i.e. it still happens with prompt-toolkit based IPython.
