### ISSUE TITLE
Documentation formatting is inconsistent

### ISSUE THREAD

**Issue by fabianegli** [ipython/ipython#12762]
There are some docstrings that are not consistently formatted and sometimes result in a supposedly unexpected format in the ipython.readthedocs.io

An example:

https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-env

    %env
    -----
    
    Get, set, or list environment variables.
        
    Usage:
        
    %env: lists all environment variables/values %env var: get value for var %env var val: set
    value for var %env var=val: set value for var %env var=$val: set value for var, using python 
    expansion if possible

https://github.com/ipython/ipython/blob/223e783c447a773a497809646ca0d874ea10ceeb/IPython/core/magics/osm.py#L434-L449

For this case it would probably be best to use [field lists](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#field-lists).

It might pay off to do a systematic review of the docstring formatting.

**Comment by MrMino** [comment]
Thanks for reporting this; sorry for a late response. Looks like someone forgot to RST-ize the docstring. PRs welcome.

**Comment by boyuan12** [comment]
Can I try to work on this issue?

**Comment by MrMino** [comment]
@boyuan12 sure, go for it. If you have any questions - don't hesitate to @me & ask here.

**Comment by boyuan12** [comment]
@MrMino So do I just change the example that Fabian provided using a field list?

**Comment by MrMino** [comment]
@boyuan12 If you make it look better - sure, that is a valid contribution.

You can check out [`docs/README.rst`](https://github.com/ipython/ipython/blob/master/docs/README.rst) for a guide on how to generate the docs locally.

**Comment by boyuan12** [comment]
@MrMino @fabianegli, here's my PR: ipython/ipython#12926. Please check.
