### ISSUE TITLE
Katana ssl error

### ISSUE THREAD

**Issue by ericivancarlos** [ipython/ipython#12775]
[Exception]([SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:727))

does any one know this error?

katana details

Core     [ 1.0.0.1, Build: 0069 ]
                Date     [ 25/12/16:14/03/17    ]
                Banner   [          WAR         ]
                Modules     [ 37 ] Tools [ 2 ]

**Comment by MrMino** [comment]
Hi there. Is your issue about IPython?

If it is - please provide a way to reproduce it (what code triggers your issue) and some additional information: IPython version, Python version, etc.

If not - I'm afraid this is not the right place to ask this question.

Closing this for now, but don't hesitate to ping me if you think this should be reopened.
