### ISSUE TITLE
document tuning IPython.parallel

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#1277]
The parallel docs fall short in a number of ways, largely due to being a straight translation of the old IPython.kernel docs.

My [scipy tutorial](http://minrk.github.com/scipy-tutorial-2011) is a bit more complete in some areas, but one thing particularly lacking is performance tuning.

The principal knobs for tuning IPython.parallel are:

* TaskScheduler.scheme
* TaskScheduler.hwm
* HubFactory.db_class
* use of References to avoid data movement
* message serialization
* setting up inter-engine communication

And the typical workload characteristics that are important to how you would tune IPython are:

* task atomicity/dependency
* data movement
* task heterogeneity

**Comment by willingc** [comment]
@Carreau This one can be closed as parallel is a separate project. If you grant me privileges, I would be happy to triage and close doc issues. And wow, you are doing an awesome job of closing issues.

**Comment by Carreau** [comment]
> @Carreau This one can be closed as parallel is a separate project. If you grant me privileges, I would be happy to triage and close doc issues. And wow, you are doing an awesome job of closing issues.

Don't feel like you have to, you have a lot on your plate already ! And you are doing an awesome job !
