### ISSUE TITLE
Display doesn't show correct widget when called from external source

### ISSUE THREAD

**Issue by mojivalipour** [ipython/ipython#12771]
If I use the following code directly in a jupyter notebook cell, then the output perfectly will: 
![image](https://user-images.githubusercontent.com/59541910/104674211-41519d80-56b1-11eb-9477-65e15f335bee.png)
But if I wrap this very same code in a file and use the magic to run it, then the output will be just the class of that widget: 
![image](https://user-images.githubusercontent.com/59541910/104674334-752cc300-56b1-11eb-9ee2-26c580420e20.png)

```
from IPython.display import display, clear_output
from ipywidgets import widgets, Button, HBox
likeButton = Button(Description='Like')
disLikeButton= Button(Description='Hate')
display(HBox([likeButton,disLikeButton]))
```

I wondered if there is any solution to use the second approach and still have the first outcome?

**Comment by MrMino** [comment]
When you type `!command` into a cell, the kernel process fires up your command in a subprocess, just as you would do in a terminal. That `display` from your script - its output doesn't even get to the kernel process if you run it this way, its in a separate Python process.

`!` is meant to run terminal commands. If you want to run a python script from inside a cell, use the [`%run`](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-run) magic:

```py
%run test.py
```
