### ISSUE TITLE
NoneType' object has no attribute 'system

### ISSUE THREAD

**Issue by msacs09** [ipython/ipython#12829]
I have a requirement to start a service once the packages installed by calling command tabpy and I used below and I get error. NoneType' object has no attribute 'system. This same command can be executed without any issues manually in jupyter notebook by taping `!tabpy `manually .As such is there any other way we can call such commands from python script

```
from IPython import get_ipython
get_ipython().system('tabpy')
```

**error**

File "Tabpy_startup.py", line 8, in <module>
get_ipython().system('tabpy')
AttributeError: 'NoneType' object has no attribute 'system'

Also tried this 

```
import subprocess
start_tabpy = subprocess.run("tabpy")
print("Service started: %d" % start_tabpy.returncode)
```

**Comment by MrMino** [comment]
You are not running an IPython shell, that's why `get_ipython()` returns `None`.

Do you have to use `IPython` class to run a process? Why can't you use the `subprocess` module?

**Comment by MrMino** [comment]
Given the lack of response, I'm going to assume this is no longer relevant for you. If that's not the case, please ping us here with the relevant information, and we'll reopen.
