### ISSUE TITLE
Ipython 7.20 `1 is 1` or `"a" is "a"` never returns bug

### ISSUE THREAD

**Issue by RJTK** [ipython/ipython#12822]
This seems like a pretty trivial bug but in Ipython 7.20 and Python 3.8.5 typing in something like `1 is 1` or `"a" is "a"` in the Ipython shell will cause it to essentially freeze up -- you can hold down the return key and keep getting nothing but `...` as if it's expecting a new line.

![ipython_bug](https://user-images.githubusercontent.com/6856593/108305505-1fe44580-7178-11eb-8545-d5ef3af36c4a.png)

This is still present in the most recent commit at the time 5da6784b690b085bd9cde88e08ab4e2def9f65ff
![ipython_bug8](https://user-images.githubusercontent.com/6856593/108306413-1065fc00-717a-11eb-95dc-c1b3279742b4.png)

**Comment by MrMino** [comment]
Seems to work for me, although on different python version:
![image](https://user-images.githubusercontent.com/6691643/108345655-d24ef380-71de-11eb-8b0c-1d55e19e167e.png)

Could you please try to reproduce it inside a virtualenv and show us the output of `pip freeze`

**Comment by RJTK** [comment]
et voila

![ipy_bug](https://user-images.githubusercontent.com/6856593/108451511-f3daca00-7234-11eb-9db6-b65bf9d79c89.png)

**Comment by MrMino** [comment]
You could've shared the freeze textually mate, so people don't have to use OCR on your screenshot to replicate...

**Comment by RJTK** [comment]
Sorry, I had in my head that I should include an image demonstrating the bug.  It's the default installation I got with `conda create -python=3.8` and `pip install ipython`:

```
backcall==0.2.0
certifi==2020.12.5
decorator==4.4.2
ipython==7.20.0
ipython-genutils==0.2.0
jedi==0.18.0
parso==0.8.1
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.16
ptyprocess==0.7.0
Pygments==2.8.0
traitlets==5.0.5
wcwidth==0.2.5
```

**Comment by MrMino** [comment]
Ok, so I managed to reproduce it. Seems to be connected to the python version: it is bugged in 3.8.5 but works correctly in 3.8.6. Intuition tells me it is probably related to some kind of a bug in the `ast` module, and there are entries related to that [in the 3.8.6 changenote](https://docs.python.org/release/3.8.6/whatsnew/changelog.html#changelog).

I guess you should update to 3.8.6?

![image](https://user-images.githubusercontent.com/6691643/108526238-2cc87c80-72d1-11eb-9e73-8b8e490d2815.png)

**Comment by RJTK** [comment]
Gotcha -- since it's not an IPython bug there's no problem here.

**Comment by Carreau** [comment]
Good find @MrMino ! Thanks !
