### ISSUE TITLE
Custom magic best practice: import vs. load_ext

### ISSUE THREAD

**Issue by jayqi** [ipython/ipython#12838]
Hello, I'm developing a Python package which implements a custom magic with the `@register_line_cell_magic` decorator.

Something I found unclear when reading the [documentation](https://ipython.readthedocs.io/en/stable/config/custommagics.html) is whether my magic should be loaded as an extension or not. The initial example on that page that uses the decorator registers the magic on module import, so then a user who runs `import my_module` would have the magic available. 

However, later examples that use the `Magics` class-based approach instead register the magic in `load_ipython_extension`, which to my understanding requires the user to use `%load_ext my_module` to make the magic available.

I'm not seeing discussion on which is the recommended way of registering magics, especially since it appears they lead to a different entrypoint for a user. Is there a standard or best practice recommended for which approach to use? 

One thing I noticed is that the import approach throws a `NameError` when the module is loaded outside of an IPython kernel, which is straightforward to work around with a try-except.

**Comment by Carreau** [comment]
Personally i think that the explicit registration in `load_ext` is better; in particular if your magics might have side effect, or be slow to load; 

The decorators are convenient when working interactively and defining a magic just in current notebook. 
Other things to take into account is whether your magic would overwrite and existing one (or be overridden by someone else), in which case you may want to have them only registered with load_ext and not import. 

In general , explicit is better than implicit; but you can use your better  judgment.
