### ISSUE TITLE
paste into ipython stop working with vi mode

### ISSUE THREAD

**Issue by pinggit** [ipython/ipython#12841]
this works well:

```
[ins] In [46]: In [41]: s = 'Abc Def Ghi'
[ins] In [47]:
```

this does not work.
```
[ins] In [44]: [ins] In [41]: s = 'Abc Def Ghi'                       
          ...:                 
          ...:                                                        
  File "<ipython-input-44-0af6a6a3f6c4>", line 1
    [ins] In [41]: s = 'Abc Def Ghi'
          ^
SyntaxError: invalid syntax
```

is it possible to configure ipython to also accept transcript under vi mode?

**Comment by pinggit** [comment]
It seems like related to this setting:

`c.TerminalInteractiveShell.autoindent = False`

I changed to True, and it works...

**Comment by MrMino** [comment]
Nice catch. I was pondering whether it's a bug - it seems like an omission of sorts - but I'm not sure if you are supposed to select text while in the insert mode. As a Vim user, It feels weird to me to go into insert mode then start to select text by mouse and copy it.

Then again insert mode is the default, and the nav mode has its own prompt too, smarter pasting shouldn't be hard to implement for either.

**Comment by pinggit** [comment]
@MrMino just one comment, I'm not select text by mouse and copy...
I'm running ipython inside of a vim8 terminal, in a vertial pane. And my workflow with vim is to test things in ipython vim pane, escape vim terminal insert (and back to normal mode), then copy the ipython test result into my editing buffer, and paste them back into ipython vim terminal whenever I need to re-run them. works like a charm.
This paste issue in ipython vi mode kind of break it - I have to clean the test result (removing vi mode style prompts chars) before I can re-run them...

**Comment by MrMino** [comment]
@pinggit I don't think there's a need to make this configurable - `[ins] In [123]:` is not a valid syntax, so in the interest of UX the interpreter might as well ignore it by default, the same way `In [123]` would be.
