### ISSUE TITLE
ipdb crashed on parsing a valid pyproject.toml file

### ISSUE THREAD

**Issue by dazza-codes** [ipython/ipython#12853]
The pyproject.toml file must be valid because poetry parses and manages the file just fine.  ipdb objects to any closing brace on a new line as the only character on that line.

The following error was raised by simply importing ipdb and calling ipdb.set_trace()

```
Traceback (most recent call last):
  File "./notebooks/csg_random_poi.py", line 32, in <module>
    ipdb.set_trace()
  File "/opt/conda/envs/gis/lib/python3.7/site-packages/ipdb/__main__.py", line 75, in set_trace
    p = _init_pdb(context).set_trace(frame)
  File "/opt/conda/envs/gis/lib/python3.7/site-packages/ipdb/__main__.py", line 52, in _init_pdb
    context = os.getenv("IPDB_CONTEXT_SIZE", get_context_from_config())
  File "/opt/conda/envs/gis/lib/python3.7/site-packages/ipdb/__main__.py", line 82, in get_context_from_config
    parser = get_config()
  File "/opt/conda/envs/gis/lib/python3.7/site-packages/ipdb/__main__.py", line 174, in get_config
    read_func(f)
  File "/opt/conda/envs/gis/lib/python3.7/configparser.py", line 717, in read_file
    self._read(f, source)
  File "/opt/conda/envs/gis/lib/python3.7/configparser.py", line 1110, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: '/home/joe/src/gis/pyproject.toml'
	[line 17]: ']\n'
	[line 24]: ']\n'
	[line 175]: ']\n'
	[line 181]: ']\n'
	[line 186]: ']\n'
	[line 193]: ']\n'
	[line 216]: ']\n'
	[line 227]: ']\n'
	[line 236]: ']\n'

If you suspect this is an IPython 7.21.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

```

**Comment by bollwyvl** [comment]
I don't believe we support any `pyproject.toml` parsing for config... `configparser` handles old-school `.cfg ` and `.ini`. how is it configured to even look in that file?

**Comment by MrMino** [comment]
@dazza-codes have you by chance set `IPDB_CONFIG` to `pyproject.toml` in your environment? That's not supported.

**Comment by MrMino** [comment]
@bollwyvl this is done by `ipdb`, i.e. the wrapping code, not by IPython.

**Comment by MrMino** [comment]
@dazza-codes @bollwyvl I should've check before commenting. Indeed, on paper ipdb support for pyptoject.toml was added in 0.13.5 (9 days ago), but actually working only since 0.13.6 (2 days ago).

Anyways - update Ipdb, it should work.

**Comment by MrMino** [comment]
Hi @dazza-codes. I'll close this issue, as it's not related to IPython itself. If the update to 0.13.6 didn't fix your problem, please file an issue in [gotcha/ipdb](https://github.com/gotcha/ipdb).
