### ISSUE TITLE
IPython does not show colors when called with embed()

### ISSUE THREAD

**Issue by klieret** [ipython/ipython#12850]
I use the following snippet to drop to an interactive IPython CLI from my code:

```python
from IPython import embed

# do some things

embed()
```

But no syntax highlighting or any other color shows up.

If, in contrast, I start ipython simply with

```
ipython3
```

Then colors show up as expected.

How can I get colors/syntax highlighting when embedding IPython like this?
 
Systems tested

* `IPython==7.21.0` +  `python3==3.7.5`
* `IPython==7.13.0` + `python3==3.6.9`
* `IPython==7.16.1` + `python3==3.6.9`

**Note**: Also asked this on [SO](https://stackoverflow.com/questions/66474372/ipython-shell-via-embed-not-showing-colors/)

**Comment by aetasoul** [comment]
You have the wrong link for Stackoverflow.

Check [this](https://github.com/ipython/ipython/issues/11523)

**Comment by klieret** [comment]
Thanks a lot! I somehow didn't find this old issue :)

**Comment by Carreau** [comment]
Thanks @aetasoul  for helping with the resolution.
