### ISSUE TITLE
Bug: extra closing ) does not trigger SyntaxError

### ISSUE THREAD

**Issue by aroberge** [ipython/ipython#12859]
Consider the following:
```
> ipython
IPython 7.21.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: print('hello'))
   ...:
   ...:
```
The extra `)` should have resulted in a `SyntaxError`; instead, more input is apparently expected. This problem is present in earlier versions of IPython as well.

**Comment by MrMino** [comment]
I'm trying very hard to think of a reason for this, and so far the only thing that I can see is that this makes it possible to move the cursor to the line above and fix the code. Not sure if that's intended reason behind it, to me it's more irritating than functional.

I would PR this if I were able to find the code that is responsible for it, but so far I cannot.

**Comment by MrMino** [comment]
Found it - [`make_tokens_by_line()`](https://github.com/ipython/ipython/blob/master/IPython/core/inputtransformer2.py#L469) does not care if parenthesis depth sinks below 0:

```
            elif token.string in {')', ']', '}'}:
                if parenlev > 0:
                    parenlev -= 1
```

This is one of these cases where it's half explicit half not, and so difficult for me to interpret. @Carreau shouldn't cases where `parenlev <= 0` lead to an error?
