### ISSUE TITLE
I can't insert an image in Jupyter Notebook using ![]("image.jpg") code

### ISSUE THREAD

**Issue by Wobbly10** [ipython/ipython#12857]
The following error pops up: '[]' is not recognized as an internal or external command,
operable program or batch file.
 
![image](https://user-images.githubusercontent.com/71792788/110943459-3e95c080-8361-11eb-8a48-b2b42347b845.png)

**Comment by MrMino** [comment]
You need to change the cell type to Markdown first:

![image](https://user-images.githubusercontent.com/6691643/111573979-e240ff80-87ab-11eb-9a56-b42d8e60877e.png)

**Comment by MrMino** [comment]
Hi @Wobbly10. I'll close this issue for now, but if you need further help - don't hesitate to reach out here & ping me.
