### ISSUE TITLE
ipython's reaction to ctrl-c when reverse-searching history

### ISSUE THREAD

**Issue by segasai** [ipython/ipython#1286]
Hi, 

I've noticed a relatively minor bug with reverse searching the history in ipython, but it can be quite annoying. 

```python
In [1]: print 'aaaa'
aaaa

In [2]:  # Now pressing Ctrl-r  to search for aaa
(reverse-i-search)`aa': print 'aaaa'  
#Now I cancel the search by pressing Ctrl-C
KeyboardInterrupt

In [2]:     
```

So what I get is the empty command line -- which is perfectly fine, but the problem if I press enter now the command from the history still is going to be executed... 
I checked and this definitely doesn't happen in the same situation with e.g. bash's readline.

  Sergey

**Comment by tacaswell** [comment]
Also see https://bugs.python.org/issue24266 which has a patch to fix this behavior.

**Comment by tacaswell** [comment]
Also see https://github.com/ludwigschwardt/python-gnureadline/pull/47 

Building that branch will give you a `gnureadline` (which IPython prefers) which correctly deals with this case.

**Comment by minrk** [comment]
@tacaswell that's super great. Closing here as the fix is on its way upstream.

**Comment by Evidlo** [comment]
I'm still having this issue on ipython 3.2.1
