### ISSUE TITLE
(i)pdb _runscript leads to KeyError: '_oh'

### ISSUE THREAD

**Issue by jdtsmith** [ipython/ipython#12883]
When I run `ipdb` or `pdb` in iPython (v7.22.0) using `_runscript` (as, e.g. [elpy-shell](https://github.com/jorgenschaefer/elpy) does), after exiting the (i)pdb sub-console, any self-printing command leads to:

```python
ipdb> q

In [23]: x
Out[23]: ---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/code/python/scraps/test_edb.py in <module>
----> 1 x

/usr/local/Cellar/ipython/7.22.0/libexec/lib/python3.9/site-packages/IPython/core/displayhook.py in __call__(self, result)
    261             self.write_output_prompt()
    262             format_dict, md_dict = self.compute_format_data(result)
--> 263             self.update_user_ns(result)
    264             self.fill_exec_result(result)
    265             if format_dict:

/usr/local/Cellar/ipython/7.22.0/libexec/lib/python3.9/site-packages/IPython/core/displayhook.py in update_user_ns(self, result)
    199 
    200         # Avoid recursive reference when displaying _oh/Out
--> 201         if self.cache_size and result is not self.shell.user_ns['_oh']:
    202             if len(self.shell.user_ns['_oh']) >= self.cache_size and self.do_full_cache:
    203                 self.cull_cache()

KeyError: '_oh'
```

**Comment by MrMino** [comment]
Could you please provide the code on which this can be reproduced (i.e. how are you calling `_runscript`)?

**Comment by jdtsmith** [comment]
```python
In [2]: from IPython.core.debugger import Pdb as __pdb
In [3]: __pdb(context=1)._runscript('/Users/jdsmith/code/python/scraps/test_edb.py')
ipdb> q
```
It seems (i)pdb updates `locals` but does not reset them on quit!

**Comment by MrMino** [comment]
Actually, `_runscript` comes from the builtin `pdb.Pdb` class. It is used in `pdb.main()` function. I'm not sure if you're supposed to use it the way you are using it - if I'd want to run a script in ipdb I would've just typed the following in the console:

```
ipdb /path/to/script.py
```

I don't know if there are any supported ways of running script debuging in the IPython console, but given that `_runscript` comes from a builtin module, and it starts with a leading underscore, I doubt it's one of them.

**Comment by jdtsmith** [comment]
Right, but this is how `elpy` runs and debugs scripts.  In fact `ipdb` [does the same thing](https://github.com/gotcha/ipdb/blob/6694611c9417a9afc28c86f5ffe546d4397c95a7/ipdb/__main__.py#L301) in its main loop.  Maybe I'll ask over there.

**Comment by MrMino** [comment]
@jdtsmith as much as I'd like to help and PR a fix for this, the code of it resides inside stdlib, not this package, so there isn't much we can do here :disappointed:.

**Comment by jdtsmith** [comment]
Thanks.  I have sense found that `%run -d` does much of what I want, and does preserve the locals and restore them when ipdb finishes.  I'm not sure how `%run` accomplishes that, but glad to have discovered.

**Comment by MrMino** [comment]
@jdtsmith I've literally just stumbled upon that too :). BTW. you can view the source of a magic (and for that matter, any other function / class, if you substitute `%run`) in IPython by issuing

```
%run??
```
