### ISSUE TITLE
get_ipython().complete gives different completions than [Tab]

### ISSUE THREAD

**Issue by jdtsmith** [ipython/ipython#12887]
I'm working on improving the link between Emacs's python-shell mode and iPython's excellent completions.  Right now python.el is using some very simple logic to figure out what small "piece" of a pending input line to complete, then using `get_ipython().Completer.all_complete` o that piece and parsing the results.  It's fairly basic at parsing the original text to complete, so Emacs misses many useful completions.  iPython is much smarter about context.  What I'd like to do is feed an entire _line_ to `Completer` and let it figure out what it wants to complete, just as it would in the terminal.  But I need to know _what_ iPython actually determined was the relevant completion text within that line.

I see `get_ipython.complete()` should be close to what I need.  Consider (in IPython 7.22.0):

```python
In [10]: testing = 42
In [11]: test = 12
In [21]: print(42 + tes[Tab]
                         test           test_numpy.py 
                         testing        test_numpy.py~
```

but 

```python
In [12]: l="print(42 + tes"
In [13]: get_ipython().complete(None, l, len(l))
Out[13]: ('tes', ['test', 'test_numpy.py', 'test_numpy.py~'])
```

I.e. it omits some completions (e.g. `testing`, in this case).  Also, Jedi-based completions don't seem to be included:

```python
In [55]: test2=[3,5,'str']
In [56]: test2[-1].ca
                      capitalize()
                      casefold()  
                      .cache/     
In [56]: l='test2[-1].ca'
In [57]: get_ipython().complete(None, l, len(l))
Out[57]: ('.ca', ['.cache/'])
```

In fact even the simple example from the `complete` docs doesn't work as expected:

```python
In [74]: x='hello'
In [75]: get_ipython().complete('x.l')
Out[75]: ('x.l', [])
```

Is there some configuration issue which could lead to `_ip.complete` not returning the same results as `[Tab]` does?  Thanks for iPython.

**Comment by jdtsmith** [comment]
Update: I see a simple `get_ipython.complete()` is closer to what I need:

```
In [50]: get_ipython().complete(None, l, len(l))
Out[50]: ('tes', ['test', 'test_numpy.py', 'test_numpy.py~'])
```

but it omits some completions (e.g. `testing`, in this case).  Also, Jedi-based completions don't seem to be included:

```python
In [55]: test2=[3,5,'str']

In [56]: test2[-1].ca
                      capitalize()
                      casefold()  
                      .cache/     

In [56]: l='test2[-1].ca'

In [57]: get_ipython().complete(None, l, len(l))
Out[57]: ('.ca', ['.cache/'])
```

**Comment by jdtsmith** [comment]
Oddly, I discovered that if I set `ip.Completer.use_jedi = False`, it does correctly complete 'x.l' and "print(42 + tes".  The final (Jedi-based) completion doesn't work no matter the setting of `use_jedi`.  So somehow the `jedi` capability in `ip.Completer` is both not working in `ip.complete` _and_ preventing other forms of completion from working correctly.

PS: Dict completion in longer lines (`12 + d[Tab]`) doesn't work even using Tab, the dict must be at the input line beginning.

**Comment by jdtsmith** [comment]
OK, I now see that `[Tab]` internally uses the new _provisional_ completion framework and the `Completion` objects.  I managed to get all the completions that `[Tab]` sees with:

```python
with provisionalcompleter():
         print('\n'.join([f"{x.text}: [{x.start}:{x.end}] {x._origin}"
                          for x in ip.Completer.completions(l,len(l))
                          if x.text.startswith(l[x.start:x.end])]))
```

But this is obviously not a stable API.  Perhaps the documentation could be updated to indicate iPython command-based completion is in transition, and the old system doesn't provide all completions, and the new system is not yet stabilized.

**Comment by MrMino** [comment]
> Perhaps the documentation could be updated to indicate iPython command-based completion is in transition

[I think it already does mention it..?](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.completer.html#experimental:~:text=The%20APIs%20attached%20to%20this%20new,use%20in%20an%20provisionalcompleter%20context%20manager.) I'm not up to date with this part of the docs though, so I might be wrong here.

**Comment by jdtsmith** [comment]
Thanks.  I think saying something about [complete](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.completer.html#IPython.core.completer.IPCompleter.complete) being an outdated interface that does not provide the same set of matches that `[Tab]` does would be very helpful.  It's awkward because the new API isn't yet official or recommended, and old API isn't as capable.  Thanks.
