### ISSUE TITLE
Double-dash becomes en-dash in docs for "cd" magic

### ISSUE THREAD

**Issue by wjandrea** [ipython/ipython#12885]
The double-dash in [this line][line] gets rendered as an en-dash (Unicode U+2013) in [the docs][docs] for the `cd` magic.

I don't know how to fix it, sorry, otherwise I'd submit a pull request :frowning_face: 

  [line]: https://github.com/ipython/ipython/blob/86d24741188b0cedd78ab080d498e775ed0e5272/IPython/core/magics/osm.py#L317
  [docs]: https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-cd

**Comment by MrMino** [comment]
Hi @wjandrea! Thanks for bringing it to our attention - I just PRed a fix. Your links to the code made this a lot easier - keep it up.
