### ISSUE TITLE
Traitlets dropping support for python 3.6 causes install issue with pip.

### ISSUE THREAD

**Issue by dfrank8** [ipython/ipython#12890]
We are using `ipython 7.16.0` and `python 3.6.1`:

`traitlets` dropped support for python 3.6. iPython has the requirement is `traitlets >=4.2`. This causes anyone using python 3.6 to be unable to install iPython using pip.

Locking `traitlets` at `traitlets==4.3.3` in `requirements.txt` fixes the problem. It seems as though iPython should lock the `traitlets` dependency in these earlier versions.

```python
Collecting traitlets>=4.2 (from ipython==7.16.1->-r requirements.txt (line 65))
  Downloading https://files.pythonhosted.org/packages/f6/7d/3ecb0ebd0ce8dcdfa7bd47ab85c1d4a521e6770ef283d0824f5804994dfe/traitlets-5.0.5-py3-none-any.whl (100kB)
traitlets requires Python '>=3.7' but the running Python is 3.6.1
You are using pip version 9.0.1, however version 21.0.1 is available.
```

It's strange that this issue is only occurring now, since traitlets' most recent version was released in October 2020.

**Comment by MrMino** [comment]
Strange. [Python 9.0.1 already has the `python_requires` functionality](https://pip.pypa.io/en/stable/news/#id531:~:text=Implementation%20of%20pep%2D503%20data%2Drequires%2Dpython.%20When%20this,version%20that%20doesn%E2%80%99t%20satisfy%20the%20requirement.), and traitlets 5.0.5 have `data-requires-python="&gt;=3.7` specified in the index. This should not happen.

I cannot reproduce your issue. I'm using a virtual environment with python 3.6.1 installed from pyenv, and `pip==9.0.1`, and it works as intended:

```
> pip install IPython --no-cache
Collecting IPython
  Downloading https://files.pythonhosted.org/packages/23/6a/210816c943c9aeeb29e4e18a298f14bf0e118fe222a23e13bfcc2d41b0a4/ipython-7.16.1-py3-none-any.whl (785kB)
...
Collecting traitlets>=4.2 (from IPython)
  Downloading https://files.pythonhosted.org/packages/ca/ab/872a23e29cec3cf2594af7e857f18b687ad21039c1f9b922fac5b9b142d5/traitlets-4.3.3-py2.py3-none-any.whl (75kB)
...
Installing collected packages: pickleshare, parso, jedi, decorator, ipython-genutils, six, traitlets, wcwidth, prompt-toolkit, backcall, pygments, ptyprocess, pexpect, IPython
Successfully installed IPython-7.16.1 backcall-0.2.0 decorator-5.0.5 ipython-genutils-0.2.0 jedi-0.18.0 parso-0.8.2 pexpect-4.8.0 pickleshare-0.7.5 prompt-toolkit-3.0.18 ptyprocess-0.7.0 pygments-2.8.1 six-1.15.0
traitlets-4.3.3 wcwidth-0.2.5
```

What command have you used to install IPython?

**Comment by dfrank8** [comment]
@MrMino we are using a fairly simple Docker container, and installing from requirements.txt.

```Docker
FROM python:3.6
ADD . /opt/app
WORKDIR /opt/app
RUN pip install -r requirements.txt
...
```

I just simplified requirements.txt to just be:
```
ipython==7.16.0
ipython-genutils==0.2.0
```
and re-run the docker build and it's working now 😕  I'm confused now.

I also just re-tried our GitLab CI/CD pipeline (where the error originally occurred) with the "fix" reverted out, and it's working again. So I guess it was temporary? I appreciate your diligence and testing (and the library you help maintain!)

Feel free to close.

**Comment by MrMino** [comment]
@dfrank8 Alright, thanks. Feel free to reach out here if it comes up again.
