### ISSUE TITLE
IPython crashes inconsistently when dealing with `pathlib`

### ISSUE THREAD

**Issue by michaelwooley** [ipython/ipython#12899]
I've just run into an error with `pathlib` using the ipython cli that causes a crash. Unfortunately, I'm also finding that it can be somewhat difficult to write a set of commands to consistently reproduce the error.

Here is the [**debug output**](https://github.com/ipython/ipython/files/6282902/err1.txt) from using option `%config Application.verbose_crash=True`. This report came from a session where I only entered the three commands listed in the code example below.

Here is a sequence of commands that _sometimes_ leads to a crash:

```python
import pathlib
p = pathlib.Path("a.mp3") # Made-up filename (haven't checked if this matters or not)

# Error in next line (sometimes)
p?

# One time the above went okay but this line fails:
dir(p)
```

In another instance, I did not get an error on line 3. However, on the next command I did `dir(p)`, which led to a crash. Unfortunately, I didn't have the verbose crash setting activated.

I wish I could be more helpful at this point. Let me know if there's anything I can do to help (or fix).

**Configuration**

```
➜  temp python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': '2486838d9',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/michael/.pyenv/versions/3.6.12/lib/python3.6/site-packages/IPython',
 'ipython_version': '7.16.1',
 'os_name': 'posix',
 'platform': 'Linux-5.9.16-1-MANJARO-x86_64-with-arch-Manjaro-Linux',
 'sys_executable': '/home/michael/.pyenv/versions/3.6.12/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.6.12 (default, Jan  4 2021, 11:03:02) \n[GCC 10.2.0]'}
```

**Comment by Carreau** [comment]
Oh, that look like a jedi-related issue, and this is likely causing a first exception when you press tab, that bubble when you press enter later. You likely want to pin to an older version of Jedi.

Alternatively you are on 3.6, if you can I would also recommend updating if possible to get the newer IPython and newwer jedi that should work together.

**Comment by michaelwooley** [comment]
Okay, thanks, good to know. It is just something that popped up. Feel free to re-open if you think that this needs to be addressed more.
