### ISSUE TITLE
Error when putting non string values into vars

### ISSUE THREAD

**Issue by tetelevm** [ipython/ipython#12905]
Hi!
This is a bug not only in IPython, but in every other interpreter I've seen. And while the documentation says about this bug that there are no guarantees about the case that causes it, that's no reason not to fix it.
An error is caused when `vars`, `locals` or `globals` contains a non string value and then autocomplete is called. Example:
```
In [1]: vars()[123] = 123
In [2]: a<Tab>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/completer.py", line 2056, in _complete
    for m in matcher(text)])
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/completer.py", line 1283, in magic_matches
    global_matches = self.global_matches(bare_text)
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/completer.py", line 676, in global_matches
    if word[:n] == text and word != "__builtins__":
TypeError: 'int' object is not subscriptable

If you suspect this is an IPython 7.22.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org
You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.
Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```
The reason for the bug is that neither putting nor working with the variable dictionary checks or converts keys to string form. Again, this bug is definitely present in CPython, Jython and MicroPython (although their code is written a little differently), and I am currently planning to create an issue in the first two as well.

**Comment by MrMino** [comment]
I don't think you're supposed to use `vars()`, `locals()` or `.__dict__` with non-str keys. These dictionaries map variable / field _names_ to their values. Having variable name of type `int` is meaningless.

FTR this works as expected:

```
In [3]: vars()['aaaaa'] = 123

In [4]: aaaaa
Out[4]: 123
```

Why would you want to add a non-str key there?

**Comment by Carreau** [comment]
> Why would you want to add a non-str key there?

It's common to mark frames objects in a way that can't conflict with user-defined variables – you can usually can use string that are invalid identifiers and it's sufficient, but some people use object; but i've seen it.

Trio uses invalid identifier for  Keyboard interrupt protection searchfor ki_protection_enabled.

But yes it's likely going to break everything to not use strings.

**Comment by MrMino** [comment]
Given the lack of response, and the issue itself not being specific to IPython, I'm going to assume it's no longer relevant to you. Should you need any further help on this matter, please don't hesitate to ping us here - we'll reopen.
