### ISSUE TITLE
input not accepted with "1 is True"

### ISSUE THREAD

**Issue by kundor** [ipython/ipython#12901]
Typing `1 is True`, the prompt continues waiting for input, and there doesn't seem to be a way to get the interpreter to accept the statement.
```
In [1]: 1 is True 
   ...:  
   ...:    
```
I noticed this in IPython 7.13.0 with Python 3.8.5. I then upgraded to IPython 7.22.0 and the problem is still present.
The same occurs with variants such as `1 is None`, `None is 2`, `False is 0`, etc.
Also with literal strings such as `'a' is 'a'`.

**Comment by MrMino** [comment]
Looks like a duplicate of #12822.

If you're using Python 3.8.0-3.8.5, update to 3.8.6, it should fix this issue. Otherwise please ping me here, I'll reopen.
