### ISSUE TITLE
Fail on Big Sur M1 Mac

### ISSUE THREAD

**Issue by RandallShanePhD** [ipython/ipython#12914]

**Comment by MrMino** [comment]
Umm... @RandallShanePhD, could you please add some logs / information about the IPython version?

**Comment by Carreau** [comment]
Also make sure you are on the latest version; there were some M1 fixes in Feb or March IIRC.

**Comment by RandallShanePhD** [comment]
Thanks - had the latest version but it has stopped after the recent Big Sur update.  I'll close this - thank you again!!
