### ISSUE TITLE
Jupyter Notebook won't print anything or show output from a loop

### ISSUE THREAD

**Issue by eugeniomca** [ipython/ipython#12944]
Jupyter Notebook is not showing any output or printing anything. Everything seems to be running perfectly, Kernel seems to be connected and [working.
![Captura](https://user-images.githubusercontent.com/83718872/117172294-49813600-ad91-11eb-9891-108b559fdc83.JPG)

**Comment by MrMino** [comment]
I gather from the fact that you closed it that the issue is fixed. If it's not, don't hesitate to reopen it.
