### ISSUE TITLE
IPython prints a "permission denied" warning when $IPYTHONDIR doesn't exist

### ISSUE THREAD

**Issue by paper42** [ipython/ipython#12951]
```
%: export IPYTHONDIR=~/.local/var/ipython/
%: ipython3
/usr/lib/python3.9/site-packages/IPython/paths.py:66: UserWarning: IPython parent '/home/user/.local/var' is not a writable location, using a temp directory.
  warn("IPython parent '{0}' is not a writable location,"
Python 3.9.4 (default, Apr  5 2021, 00:48:45) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.23.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]:
```

`mkdir ~/.local/var` fixes this issue, could ipython do it automatically before it prints this warning?

``` 
%: python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': 'a0c0411c4',
 'commit_source': 'installation',
 'default_encoding': 'utf-8',
 'ipython_path': '/usr/lib/python3.9/site-packages/IPython',
 'ipython_version': '7.23.0',
 'os_name': 'posix',
 'platform': 'Linux-5.11.18_1-x86_64-with-glibc2.32',
 'sys_executable': '/usr/bin/python3',
 'sys_platform': 'linux',
 'sys_version': '3.9.4 (default, Apr  5 2021, 00:48:45) \n'
                '[GCC 10.2.1 20201203]'}
```

**Comment by ivanov** [comment]
> could ipython do it automatically before it prints this warning?

Theoretically speaking, yes, it could. However, the issue could be that a user might also accidentally introduce a typoe to their IPYTHONDIR directory, or have it pointing to something that needs to get mounted, but hasn't been, so I think the current behavior is acceptable and desirable, in that we do no want to second guess what should happen, and we are already pretty explicit about what it happening and the remedy you propose is _one_ reasonable approach, but not the only one that could possibly make sense.

**Comment by MrMino** [comment]
https://zen-of-python.info/in-the-face-of-ambiguity-refuse-the-temptation-to-guess.html

**Comment by ivanov** [comment]
Thank you for your report, @paper42. Hopefully the explanation of why we don't do this makes sense, so  I'm going to go ahead and close this issue
Happy hacking! :bowtie:
