### ISSUE TITLE
zmqerror

### ISSUE THREAD

**Issue by lijieyuan** [ipython/ipython#12976]
jupyterlab running by docker. When new create notebook .ipynb  first  ;   the kernel status  connect to unkown to disconnected;
![jupyter1](https://user-images.githubusercontent.com/23073445/118074640-ede22880-b3e0-11eb-97df-e269bb304c1a.jpg)
jupyerlab 3.0.0
ipython 7.16.1
jupyter-client 6.1.12

thanks

**Comment by MrMino** [comment]
Please update your Python / IPython versions and let us know if the problem persists.

**Comment by Carreau** [comment]
Thanks @MrMino for triaging.

I believe this is now tracked in https://github.com/ipython/ipykernel/issues/676, so closing here.
