### ISSUE TITLE
%%time magic does not stop execution on error

### ISSUE THREAD

**Issue by BrenBarn** [ipython/ipython#12971]
If in a Jupyter notebook I have a cell that uses the `%%time` magic, and I queue up that cell and some subsequent cells to run (by hitting Shift-Enter several times), and the `%%time` cell raises an exception, execution is not stopped as usual but continues on to the later cells that were queued to run.

For instance try making a cell with

```
%%time
import time
time.sleep(3)
1/0
```

And then add a cell after it with something like `print("oops")`.  Go back to the first cell and hit Shift+Enter twice.  The first cell's output shows a zero division exception, but the second cell still runs.

I'm not sure if this is a Jupyter issue or IPython issue, but I posted it here because it seems to be very similar to this old issue: https://github.com/ipython/ipython/issues/7100 (although that predates the Jupyter/IPython split).

**Comment by MSeal** [comment]
Late context: Generally speaking magics _should_ be raising exceptions to halt further commands (or cells) when their internals fail. I'd consider it an implementation gap with the magic if it defaults to run-after exception without explicitly allowing it. With the `%%time` magic you can setup the code to catch expected exceptions already so adding a flag to the command isn't super necessary if behavior is changed imo.

**Comment by zmbc** [comment]
@Carreau can you provide some context on why this is not planned to be fixed?

> I can see how someone would actually like to time a generation of particular exceptions in a notebook.

This could be achieved by a try-except _within_ the timed cell, so it's not clear to me why having `%time` itself do this is necessary.
