### ISSUE TITLE
timing differs from windows and linux

### ISSUE THREAD

**Issue by Barry1** [ipython/ipython#12983]
If running a jupyter cell with the following code
```python
%%time
import time
time.sleep(100)
```
on linux the result whos WAll=100seconds and zero usage (of course). That detail is based on the function `clock2` within `timing.py` as far as I can see.
On windows [time.perf_counter](https://docs.python.org/3/library/time.html#time.perf_counter) is used - which also measures times of sleeping. I recommend to use [time.process_time](https://docs.python.org/3/library/time.html#time.process_time) to have a more comparable situation.
If we switch, we can also change the output to show now only WALL on Windows. I'll try to submit a fix. (or idea for that)

**Comment by Carreau** [comment]
Thanks for the report and the fix, I'll try to take care of it soon.

**Comment by Barry1** [comment]
> Thanks for the report and the fix, I'll try to take care of it soon.

Thank you @Carreau - I just realized that I had some struggle with `darker` and how to place `whatsnew/pr` - now fixed. Please activate the check. Best regards.
