### ISSUE TITLE
Sphinx rendering bug for IPython.core.interactiveshell.InteractiveShell.set_custom_exc

### ISSUE THREAD

**Issue by eric-wieser** [ipython/ipython#12981]
The docs for [`IPython.core.interactiveshell.InteractiveShell.set_custom_exc`](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.interactiveshell.html#IPython.core.interactiveshell.InteractiveShell.set_custom_exc) have horribly mangled a warning message into a list of arguments. I can't work out at a glance why this is happening; it might be a `sphinx.ext.napoleon` bug, or a sphinx misconfiguration somewhere.

![image](https://user-images.githubusercontent.com/425260/118260619-711b8100-b4aa-11eb-9436-c0af4a028dd1.png)

**Comment by MrMino** [comment]
This looks terrible! Thank you for reporting it.

**Comment by prius** [comment]
This is fixed already in the most recent version.

![Selection_306](https://user-images.githubusercontent.com/1616237/131831376-33a22e57-0fa3-4d42-af3c-e55044a9b7d7.png)

**Comment by prius** [comment]
Hmm, I've just built the doc locally from master branch and got what you see on the screenshot... Then I need a way to reproduce that, I guess.

**Comment by prius** [comment]
Yes, it is still broken on 7.x branch, but is okay on master.

Do you want it to be fixed in 7.x as well?
