### ISSUE TITLE
Separate cursor for each cell

### ISSUE THREAD

**Issue by rishavtraining** [ipython/ipython#12985]
Once the cell is executed the cursor doesn't moves to a new cell. If I click in the new cell another cursor appears, every cell has a cursor of it's own. I have to click couple of times in the cell to write code and have tried reinstalling but there is no change. Please help me fix this issue.
![cursor](https://user-images.githubusercontent.com/65455921/118823201-6c096800-b8d6-11eb-8726-a28f6aeb5725.png)

**Comment by Carreau** [comment]
please report this to https://github.com/jupyter/notebook, the code for the notebook is there and they will have a better idea of what can be happening. 

I would also try: 
- another browser
- private browsing widow w/o extensions.
