### ISSUE TITLE
TransformerManager().transform_cell misses part of cell

### ISSUE THREAD

**Issue by MarcoGorelli** [ipython/ipython#12988]
Example:
```python
>>> src = ("""\
... # foo
... a = b??
... """)
>>> from IPython.core.inputtransformer2 import TransformerManager
>>> TransformerManager().transform_cell(src)
"# foo\nget_ipython().run_line_magic('pinfo2', 'b')\n"
```

I would have expected something like what `IPythonInputSplitter` would have returned:
```python
>>> IPythonInputSplitter().transform_cell(src)
"# foo\nget_ipython().set_next_input('a = b');get_ipython().run_line_magic('pinfo2', 'b')\n"
```

Diagnostics:
```python
>>> import IPython
>>> IPython.__version__
'7.23.1'
>>> import sys
>>> sys.version_info
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
```

**Comment by Carreau** [comment]
I'm not sure why the `set_next_input()`? Can you expand on your reasoning ?

**Comment by MarcoGorelli** [comment]
Simply because that's what's returned if there's no comment:
```
In [18]: TransformerManager().transform_cell("a=b??")
Out[18]: "get_ipython().set_next_input('a=b');get_ipython().run_line_magic('pinfo2', 'b')\n"

In [19]: TransformerManager().transform_cell("# foo\na=b??")
Out[19]: "# foo\nget_ipython().run_line_magic('pinfo2', 'b')\n"

```

**Comment by Carreau** [comment]
Ah, sorry I misunderstood the question I will re-read more carefully.

**Comment by Carreau** [comment]
I believe this is on purpose, in the terminal you can't edit your previous cell, so we attempt to use set_next_input for the user to keep typing, while in a notebook or other editable frontend, there does not seem to be a need to do so as the user may remove the `?`.  We could do like `load` and replace the content of the current cell, demo of `?` is common enough that it would be extremely surprising.

**Comment by MarcoGorelli** [comment]
OK, thanks for explaining!
