### ISSUE TITLE
Cannot import 'ipdb', even when running in 'ipython'

### ISSUE THREAD

**Issue by zachriggle** [ipython/ipython#12982]
I have `ipython` installed, and it works fine -- but for whatever reason, I'm unable to import `ipdb`.  I'm not sure how to further troubleshoot this.

```
$ python3 -m pip -q install ipython

$ ipython3 --profile=none
Python 3.8.9 (default, May 11 2021, 02:10:31)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.23.1 -- An enhanced Interactive Python. Type '?' for help.

IPython profile: none

In [1]: import ipdb
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-5aecdc9391ac> in <module>
----> 1 import ipdb

ModuleNotFoundError: No module named 'ipdb'
```

**Comment by ivanov** [comment]
Hi @zachriggle , sorry you're having trouble. 

If you are you intending to use the `ipdb> `  prompt mode that ships with IPython, the magic command to do that is `%debug`. For example, if you do

```ipython
In [8]: def foo():
   ...:     x = "hi"
   ...:     1/0
   ...:

In [9]: foo()
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-9-c19b6d9633cf> in <module>
----> 1 foo()

<ipython-input-8-efbc92504b5f> in foo()
      1 def foo():
      2     x = "hi"
----> 3     1/0
      4

ZeroDivisionError: division by zero
```

All is not lost, you can enter the postmortem debugger, inspect the stack, look at variables and run expressions.

```
In [10]: %debug
> <ipython-input-8-efbc92504b5f>(3)foo()
      1 def foo():
      2     x = "hi"
----> 3     1/0
      4

ipdb> x.capitalize()  #tab completion works here
'Hi'
```
`%debug` also has a way of setting breakpoints. Type `debug?` in IPython to read the documentation for details.

But maybe you were intending to use https://github.com/gotcha/ipdb ? In that case, that's a separate project that does not come pre-installed with ipython, so try adding `ipdb` to your pip install command.

**Comment by MrMino** [comment]
You need to `pip install ipdb` first in order to get IPython PDB implementation as a separate module / command.

**Comment by zachriggle** [comment]
I thought ipdb came as part of ipython.  Apparently not?

**Comment by MrMino** [comment]
@zachriggle no, ipdb is a separate project: https://github.com/gotcha/ipdb

**Comment by ivanov** [comment]
> I thought ipdb came as part of ipython. Apparently not?

not as an importable module. As I wrote [above](https://github.com/ipython/ipython/issues/12982#issuecomment-841762844), you can get to the debugging mode in ipython, which does have a leading `ipdb> ` prompt - that's part of IPython - but not `import ipdb` - that's a separate project.

I'm going to go ahead and close this, since this is not an IPython issue.

Happy hacking! :bowtie:
