### ISSUE TITLE
RFE: move from distutils to setuptools (& `setup.py build_sphinx`)

### ISSUE THREAD

**Issue by kloczek** [ipython/ipython#13014]
```console
[tkloczko@barrel ipython-7.24.1]$ grep distutils setup.py
# BEFORE importing distutils, remove MANIFEST. distutils doesn't properly
from distutils.core import setup
# custom distutils commands
from distutils.command.sdist import sdist
```
Looks like ipython is still using `distutils` and by this it does not support `setup.py build_sphinx`:
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
/usr/lib64/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'build_sphinx'
```
It would be good to move to setuptools.

**Comment by Carreau** [comment]
Thanks, we are aware, and we also likely want to move to declarative setup in a  pyproject.toml for example, as well as get rid of our dependency on nose.

**Comment by tirkarthi** [comment]
distutils is also deprecated from Python 3.10 : https://www.python.org/dev/peps/pep-0632/

**Comment by kloczek** [comment]
> distutils is also deprecated from Python 3.10 : https://www.python.org/dev/peps/pep-0632/

Good point. I just added note in my ticket against `flit` to not generate settup.py with `import distutils` becasue oof that PEP.

**Comment by pradyunsg** [comment]
My two cents: it would be a good idea to move to flit, since IPython is a pure-Python project and doesn't need most of the additional capabilities afforded by setuptools.

**Comment by bollwyvl** [comment]
The one exception being the [man pages, delivered via `data_files`](https://github.com/ipython/ipython/blob/0e4d6390b2174fb1b352a082b72ad387ae696e87/setupbase.py#L159). This is the _one_ case [flit has considered supporting](https://github.com/takluyver/flit/issues/358) but it _SURE WOULD BE NICE_ if it just supported the actual feature, with whatever caveats, that still made it work for the rest of the jupyter stack...

**Comment by Carreau** [comment]
Yes, +1 to have purely declarative setup. I ❤️ flit as well.

**Comment by kloczek** [comment]
`flit` at the moment is nothing more than just archiver which can generate .whl file with necessary checksums inside.
https://github.com/takluyver/flit/issues/429

`flit` cannot handle actual build of the module when it is necessary to build DSO or cannot handle building documentation like setuptools<>sphinx integration does https://www.sphinx-doc.org/en/master/usage/advanced/setuptools.html
Only from that point of view I would recommend to stick with pure pep515 (settup.cfg/project.toml + stub setrtup.py consisting from 'from setuptools import setup; setup()') but with `setuptools` backend.
`flit` additionally autogenerates setup.py with imported `distutils` which is already on the road to be deprecated https://www.python.org/dev/peps/pep-0632/

**Comment by MrMino** [comment]
AFAICT `distutils` is no longer used. That said, integration with sphinx is still not there, so I'm leaving this issue open for that.

**Comment by kloczek** [comment]
I no longer see that distutils is used in latest 8.3.0 .
I think that this ticket can be closed.

Thx.

**Comment by Carreau** [comment]
thanks.
