### ISSUE TITLE
Python cannot find Ipython?

### ISSUE THREAD

**Issue by sahild11** [ipython/ipython#13025]
Does this make sense?

Environment:
```
└─(22:35:09)──> python3 -V                                                                                                                              ──(Sun,Jun20)─┘
Python 3.9.5
└─(22:35:14)──> ipython -V                                                                                                                              ──(Sun,Jun20)─┘
7.24.1

```
<img width="851" alt="Screen Shot 2021-06-20 at 10 33 05 PM" src="https://user-images.githubusercontent.com/23486231/122703583-8f963a00-d217-11eb-8441-2309b887ca00.png">

**Comment by MrMino** [comment]
@sahild11 the package name is `ipython`, the command is `ipython`, but the module name itself is `IPython` - with the two first letters capitalized.

**Comment by MrMino** [comment]
@sahild11 the package name is `ipython`, the command is `ipython`, but the module name itself is `IPython` - with the two first letters capitalized.

Closing this, but if you have further questions related to this - you can ping me here.

**Comment by sahild11** [comment]
@MrMino Thanks!
