### ISSUE TITLE
module 'neural_renderer' has no attribute 'rasterize_face_index_map_and_weight_map'

### ISSUE THREAD

**Issue by Fly-Pluche** [ipython/ipython#13023]
when I try to train the Liquid Warp GAN ,the bug happened. 
![image](https://user-images.githubusercontent.com/73021377/122346433-86893c80-cf7b-11eb-8df6-a43fbe7738a2.png)

**Comment by MrMino** [comment]
Um, what makes you think it is a bug in IPython? There's nothing in these tracebacks that makes it look like one.

**Comment by Fly-Pluche** [comment]
You're right, but the mistake bothered me so much and I couldn't find a solution that I went to the doctor in a hurry.
Now,The bug was somehow solved even though I didn't do anything.Thank you.
