### ISSUE TITLE
Licensing issue with Stackoverflow's CC-BY-SA License

### ISSUE THREAD

**Issue by uptickmetachu** [ipython/ipython#13039]
Hi, thank you for this amazing tool!

We have recently been FOSS audited and this package was flagged with potential licensing issues. 

Code copied/distributed and/or adapted from [Stackoverflow requires](https://stackoverflow.com/help/licensing):
1. attribution and
2. **licensing under the same license as the original ([CCA-BY-SA-3.0](https://creativecommons.org/licenses/by-sa/3.0/) or [CCA-BY-SA-4.0](https://creativecommons.org/licenses/by-sa/4.0/)).** 
This repositories BSD-3 License is not compatible with CCA-BY-SA.

The code that is causing issue:
https://github.com/ipython/ipython/blob/a2c2a2dcec36224c7dca561efcf9ed9e5c514c3c/IPython/utils/text.py#L408

Consider changing the implementation of the function such that the attribution isn't required.

**Comment by Carreau** [comment]
> 2\. licensing under the same license as the original ([CCA-BY-SA-3.0](https://creativecommons.org/licenses/by-sa/3.0/) or [CCA-BY-SA-4.0](https://creativecommons.org/licenses/by-sa/4.0/)).

Original post if pre 2011 so will be CC-BY-SA-2.5 (also you have extra A in CCA).
The effect is still the same though IIUC.

**Comment by MrMino** [comment]
TBH I don't find this code necessary. If I understand it correctly, the part required is finding the common _prefix_, not the common substring, so this is unnecessarily quadratical.

I'll refactor it and post a PR today.

**Comment by Carreau** [comment]
Actually this is used in only one place, and to find the longest common prefix that only contain whitespace and `>`. So it can be replaced by something much faster and simpler.

**Comment by Carreau** [comment]
Ha, simultaneous comments :-)

**Comment by uptickmetachu** [comment]
Thank you for your quick replies! Sorry about the typo in the original post.

**Comment by MrMino** [comment]
Fixed in #13041.

**Comment by MrMino** [comment]
@uptickmetachu FYI 7.26 which fixed this issue has been released today.

**Comment by uptickmetachu** [comment]
Thank you very much much!
