### ISSUE TITLE
7.25.0 : Alias is broken on some Linux distros

### ISSUE THREAD

**Issue by Stig124** [ipython/ipython#13035]
Hello,

Installed Ipython on RHEL 8, but faced a command-not-found, then discovered that the alias is set to :

```bash
ipython='python -c '\''import IPython; IPython.terminal.ipapp.launch_new_instance()'\'
```

The `python` executable is not a thing any more on a lot of linux distro, having been phased out by the EOL of Python 2 (notably Debian-based distros are the exceptions), putting the alias to `python3` would guarantee that the alias work in every system that is near up-to-date

**Comment by MrMino** [comment]
Hi @Stig124, you have installed IPython using `dnf` (or whatever is the equivalent for RHEL thesedays), right? What command have you used exactly?

**Comment by Stig124** [comment]
`pip3 install --user ipython`, I never use dnf for python @MrMino

**Comment by bollwyvl** [comment]
Right, sounds pretty downstream. In the `pip` and `conda` versions, setuptools [`entry_points`](https://github.com/ipython/ipython/blob/7.25.0/setup.py#L246) are used, which generally seem to work wherever, once they work for anything...

**Comment by MrMino** [comment]
Ah, right, sorry, I had a memory of someone trying to package IPython into RPM here, I thought its connected.

@Stig124 what's your version of `setuptools`?

**Comment by Stig124** [comment]
`50.3.2` @MrMino 

```
Name: setuptools
Version: 50.3.2
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /usr/lib/python3.9/site-packages
Requires: 
Required-by: pipenv, ipython
```

**Comment by Stig124** [comment]
Oops, nevermind, `57.0.0` is now installed, will reinstall and retry

**Comment by Stig124** [comment]
> Right, sounds pretty downstream. In the `pip` and `conda` versions, setuptools [`entry_points`](https://github.com/ipython/ipython/blob/7.25.0/setup.py#L246) are used, which generally seem to work wherever, once they work for anything...

`L246` has nothing to do with the alias setup at first glance, what I find weird is that the `ipython` executable is the alias :
```
ipython='python -c '\''import IPython; IPython.terminal.ipapp.launch_new_instance()'\'
```

But `ipython3` is 

```python
- cat ~/.local/bin/ipython3
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from IPython import start_ipython
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(start_ipython())
```

*Found a bug there though, the usage of `#!/usr/bin/python3` is problematic in venvs, will report it separatly*

**Comment by MrMino** [comment]
Sorry, not `setuptools`, I meant `pip` - could you please show the output of `pip -V`? 

Also, I forgot to ask - do you happen to know where this alias is defined on your machine? Normally `pip` would install IPython as an executable script into `/usr/bin` or `~/.local/bin` (for `--user` install, not sure what's the location on RHEL, you can look it up with `import site; print(site.USER_BASE)`).

---

I've just installed IPython on RHEL8 Docker UBI (`registry.access.redhat.com/ubi8/python-38`), and what the install does is it puts a shell script (generated via `setuptools` entry-points machinery) into `/opt/app-root/bin/ipython`, with the following contents:

```py
#!/opt/app-root/bin/python3.8                                       
# -*- coding: utf-8 -*-                                             
import re                                                           
import sys                                                          
from IPython import start_ipython                                   
if __name__ == '__main__':                                          
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(start_ipython())                                       
```

I erroneously assumed that RHEL is somehow different in how entrypoints work, but from UBI pov - it seems not.

**Comment by Stig124** [comment]
Oh, I'm really sorry for raising that issue, this alias is set by oh my zsh, the other issue (#13036) is independent for that
