### ISSUE TITLE
ipython3 script is totally different from ipython alias

### ISSUE THREAD

**Issue by Stig124** [ipython/ipython#13036]
Found that quirk while trying to figure out #13035
`ipython3` is 
```python
- cat ~/.local/bin/ipython3
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from IPython import start_ipython
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(start_ipython())
```

The usage of `#!/usr/bin/python3` is problematic in venvs, as it will not use site-packages from the venv it's. It's even acknowledged by the program with this
```
UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
  warn("Attempting to work in a virtualenv. If you encounter problems, please "
```

But if you're running `ipython`, there is no such thing as it will soak up the venv and work fine (except with the alias of course):

```
ipython='python -c '\''import IPython; IPython.terminal.ipapp.launch_new_instance()'\'
	~/.local/share/virtualenvs/py-4bWyypbJ/bin/python
```

Would love to fix that but that will take a while before I figure out where that script is generated

**Comment by MrMino** [comment]
Are you sure you are looking at the right exec script? If you create a venv and install ipython in it, the venv's `bin/` directory will get populated with `ipython` and `ipython3` scripts, which will both start, correctly, with a shebang akin to this:

```
#!/home/mrmino/.virtualenvs/tmp-bd506c8573674be/bin/python
```

It's just that your shell does not rehash its commands after you add something executable to `PATH`, so the `ipython3` command will still point to the script outside of the venv.

To alleviate it you can either re-activate your venv, use `rehash` command in zsh, or `hash -d` in bash.

**Comment by Carreau** [comment]
I believe the script is not generated by IPython but setuptools/distutils.

Quick search found something similar in `easy_install.py in class ScriptWriter:`

```
    template = textwrap.dedent(r"""
        # EASY-INSTALL-ENTRY-SCRIPT: %(spec)r,%(group)r,%(name)r
        __requires__ = %(spec)r
        import re
        import sys
        from pkg_resources import load_entry_point

        if __name__ == '__main__':
            sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
            sys.exit(
                load_entry_point(%(spec)r, %(group)r, %(name)r)()
            )
    """).lstrip()
```

Might have changed a bit.

We really need to move away from setup.py and use a `pyproject.toml` which is declarative at some point.

**Comment by MrMino** [comment]
@Carreau yeah, it's generated when you declare an entry point, then the proper `#!`-shebangs are set on installation. Should we even have the `ipython3` command anymore? Maybe let's remove it for 8.0?

OP is probably confusing his `~/.local/bin/ipython3` with the `.../bin/ipython3` in his venv, cause after installation his `ipython3` command still points to the script from `~/.local`.

**Comment by MrMino** [comment]
I'm going to close this, as the issue with `ipython3` shebang isn't really an IPython bug - even if it was the case that the shebangs are borked, the code that generates them is outside of this codebase.

Let's rather discuss removing `ipython3` in #13040.
