### ISSUE TITLE
Remove `ipython3` command

### ISSUE THREAD

**Issue by MrMino** [ipython/ipython#13040]
Given that IPython no longer supports Python 2, and we're approaching the next major release, I would like to propose to remove the `ipython3` entrypoint/command in IPython 8.0.

Is there anyone against this?

**Comment by bollwyvl** [comment]
There are [4m results](https://github.com/search?q=ipython3&type=code) for `ipython3` on GH...

**Comment by MrMino** [comment]
@bollwyvl from a cursory look the majority of them are the identifiers signifying the kernel name, not the command itself - or am I missing something here?

I thought the relevant results are the "shell" ones only, i.e. https://github.com/search?l=Shell&q=ipython3&type=Code

**Comment by MrMino** [comment]
Ugh... Notebooks aside, looks like I underestimated the amount of code that does `os.system('ipython3')` or similar.

Now I'm not sure if it's a sensible price to pay for the minuscule simplification it would bring.
