### ISSUE TITLE
Build warning

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#13075]
```
$ ./setup.py sdist --formats=gztar
/Users/bussonniermatthias/miniconda3/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)
running sdist
```

This seem new...

**Comment by bollwyvl** [comment]
what's yer versions of `pip`, `setuptools`, `wheel`, etc?

**Comment by Carreau** [comment]
pip 21.1.3 from /Users/bussonniermatthias/miniconda3/lib/python3.8/site-packages/pip (python 3.8)
setuptools '50.3.2'

I doubt wheel is needed as this was triggered during the sdist.

I think that might be an artifact of us still using distutils in some places.

**Comment by MrMino** [comment]
I think this is no longer relevant - I cannot find any mentions of distutils anywhere in the tree anymore, and the warning is gone too.
