### ISSUE TITLE
Numfocus Small Developper Grant to tackle removing nose and IPython 8.0

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#13108]
I open this issue as a central point to coordinate, track progress and for transparency.

I'm going to submit a numfocus Small Developpement Grant hoping to subcontract someone to tackle the most critical issues to get IPython 8.0 through the door.  The critical points are
  - [x] Remove any dependency and mention of nose. Indeed this is impeding packaging on linux, and on Python 3.10.
  - [ ] Making sure 8.0 (or at least the 8.x branch) is a future proof with respect to changes in Python 3.10/3.11. 
  - [ ] This would mean that 8.x would become the new stable branch and that 7.x would not get any more releases except critical ones. 
  - [ ] We might break a couple of APIs as this would be a major version.
  - [ ] This might need some changes on IPykernel as well as it imports some of the testing facilities of IPython that rely on nose.

Below is what was submitted (and accepted), it's done via a form, for simplicity so this attempt to reproduce the questions of the forms.

<details>
SUBMIT BY SEPT 3rd (Friday of next week).

**Name of Submitter:**
**Email:**
**Proposal Title:** IPython maintenance and future proofing
Two Sentence Summary: Work is required to ensure the compatibility of IPython and IPykernel with the upcoming Python 3.10 and 3.11 releases and migrate the test suite from nose to pytest.  In addition, this work, along with two years of accumulated bug fixes and enhancements, will be release as IPython 8.0 and next version of IPykernel

**Description of Proposal:This question is required. No more than 750 words (4,500 characters max).**

We propose three main tasks:
- Ensure that IPython is compatible and warning free with Python 3.9, 3.10, and 3.11
- Migrate the test suite from nose to pytest
- Complete the release process for IPython 8.0

Critical maintenance work is needed to ensure IPython and IPykernel are fully compatible and warning free with Python 3.9 and the upcoming Python 3.10 and 3.11 releases. Python 3.9 and future versions of Python have deprecated or moved several parts of the standard library that IPython and IPykernel rely on and work is needed to mitigate these changes.  This work will need to be done on the master branch that will become the new stable (8.x series), and relieve maintainer from tedious backporting of critical bugfixes by making the 8.x branch.  In addition, we will work toward dropping support for older versions of Python or other dependencies.

The second task is to migrate the testing framework used from nose to pytest.  IPython’s use of nose pre-dates the existence of pytest, however pytest is now the standard testing framework and nose is no longer an active project.  While the frameworks are largely compatible, IPython maintains several custom extensions and a custom test runner that will need to be ported to pytest, re-implemented, or replaced with equivalent pytest functionality.  We expect this task to consume a majority of the effort.

The final task is to release IPython 8.0 and a minor version of IPkernel.  The stable branch of IPython (7.x) diverged from the main branch about 18 month ago. In addition to the work proposed in this grant, significant work has been merged to the master/main branch, but has not been released.

If time/funds remain, we would devote the remaining effort to improving and automating the release process which currently has a number of manual steps. 

** Benefit to Project/Community:This question is required.
No more than 400 words (2,500 characters max)**

IPython and IPykernel are fundamental tools used daily by a vast majority of users in the Scientific Python Ecosystem, it is essential that they are compatible with the latest versions of CPython.

A number of new  features are currently only available on the master branch and the user base would gain from having them released. 

Migrating from nose to pytest is critical for the continued health and quality of IPython.  Having a functioning test harness is a cornerstone of the project’s quality assurance and it is no longer tenable to rely on an inactive project.  Because nose is no longer maintained upstream, there is no guarantee it will remain compatible with all future versions of Python and a number of distributions have dropped the packaging as nose. This will simplify packaging IPython for downstream maintainers who have requested nose no longer be a dependency of IPython.   Additionally, by migrating to the standard test framework, also used by numpy, scipy, Matplotlib, and pandas, makes it more likely that new contributors will already be familiar with it which may improve onboarding of new contributors.

A new major release will reduce the burden on the IPython maintainers as the stable and master branch have diverged significantly which makes backporting difficult and occasionally extremely time-consuming. 

**Amount Requested:This question is required. **
$4800

**Brief Budget Justification: (Please include hours and/or pay rates)This question is required. **

Contractor : 50hrs @ 80$/hr [implementation] 
Matthias Bussonnier: 10hrs @ 80 [code review, project management, release]

We have identified Nikita Kniazev (https://github.com/Kojoley) as a candidate do to the work

**Timeline of Deliverables:This question is required. **
Please include specific timelines showing when you will achieve the proposed work.

We expect work speed to be limited by two factors : 
  - limited by IPython Maintainers availabilities to review or merge Pull-Requests, 
  - Release and adoption of Python 3.10 (planned for october 4th 2021).  General availability of a new Python version is often associated with a number of bugs reported, and change in CI. It also takes conda forge some time to Package Python 3.10 and make it available to end users. 

We’d also like to stay in line with NEP 29  which suggests stopping support for Python 3.7 at the end of 2021.

Due to the limitation on existing IPython Maintainers for review and merging, we expect this work to be carried out on a part-time basis over 2 months. 

Mid-October 2021 to Mid November
  - Port current nose ipdoctest plugin to pytest
  - Fix or temporary disable/document failing or disappeared tests
  - Replace nose utils usage in tests
Mid-November to Mid December: 
  - Remove nose plugin and nose dependency
  - Release Beta version of IPython 8.0 
  - Fix deprecation warnings and compatibility issues
  - Try to fix test discovery or try alternative approaches to implement ipdoctests plugin for pytest
End of December 2021/Early 2022:
  - Release a final version of IPyhon 8.0 / Last release of IPyhon 7.x

</details>

I'll keep updating this issue with news.

**Comment by sgaist** [comment]
Hi,

I would like to give a hand with the nose cleanup for the HacktoberFest.

**Comment by Carreau** [comment]
Apologies, I missed your message. Yes feel free to do so, no need to ask for authorisation first.

**Comment by Carreau** [comment]
As a side note, the grant has been approved, we hope to start the work soon.

**Comment by sgaist** [comment]
That's good news !

By the way, it seems that a good deal of the job was done in #12840. Shall that one serve as base to build on ?

**Comment by Carreau** [comment]
#12840 is on the 7.x branch and there are (too many?) conflicts to resolve, I think it might get faster to just redo on 8.0, as I don't think we want to backport that work.

**Comment by Carreau** [comment]
We've started to set a contract with @Kojoley, you will see them working on this issue and everything related.

**Comment by prachetasolutions** [comment]
Remove any dependency and mention of nose. Indeed this is impeding packaging on linux, and on Python 3.10.

**Comment by jarrodmillman** [comment]
Should this be closed?

**Comment by Carreau** [comment]
Yes. THanks.

**Comment by jasongrout** [comment]
> Yes. THanks.

Right now this issue is also pinned. Should it be unpinned as well?

**Comment by Carreau** [comment]
@MrMino just unpinned. Thanks !
