### ISSUE TITLE
Improper path comparison of virtualenv directories

### ISSUE THREAD

**Issue by MrMino** [ipython/ipython#13124]
Minor, non-breaking issue found during review of #13094.

If path of the active virtualenv is a substring of another virtualenv, IPython started from the second one will not fire up any warning.

Example:

```
virtualenv aaa
virtualenv aaaa
. aaaa/bin/activate
python -m pip install ipython
. aaa/bin/activate
aaaa/bin/ipython
```

Expected behavior after executing `aaaa/bin/ipython`: the following warning message is printed:

```
/home/mrmino/r/ipython/AAA/lib/python3.9/site-packages/IPython/core/interactiveshell.py:958: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv
.
```

It is not shown on `master` nor `7.x`. The root cause is the following condition in `IPython.core.interactiveshell`:

https://github.com/ipython/ipython/blob/3e2c48a0aaf251b06acbf717b462bc4e7fec8cd6/IPython/core/interactiveshell.py#L936-L938

Prefix-wise check of strings with `in` is of course not adequate here. It also covers up the logic from `pathlib.Path` related to case sensitivity. Removing `fspath` from this code and using proper parent relationships from `pathlib.Path` to perform these checks would alleviate the need to use `sys.platform` branches in this method.

**Comment by Mithil467** [comment]
I'll love to try and fix this issue! I am looking into it.
