### ISSUE TITLE
Better suppor for print escaped code

### ISSUE THREAD

**Issue by sylvain-bougnoux** [ipython/ipython#13135]
**[Feature request]**
Currently some [escape code](https://en.wikipedia.org/wiki/ANSI_escape_code), eg color, are properly interpreted by print. But not all. It is confusing. Maybe not all can be done ?

I am particularly interested by "erase line", ie "\x1b[2K" that currently does nothing.

For instance
`print('Hello','\x1b[2K\rBye')`
Should print 'Bye' and not 'Byelo'.
(of course adding end spaces does the job but it is an example).

**Comment by MrMino** [comment]
ANSII escape sequences are interpreted by the terminal emulator (e.g. `gnome-terminal`), not the shell running inside it (`ipython` or `zsh` or `bash`).

Is there anything specific wrt. IPython you wish to see improved here?

**Comment by sylvain-bougnoux** [comment]
Sorry I got confused, you are right, my example works in a python or ipython shell directly on windows (windows terminal); but does not on spyder. I don't know which embedding they use (terminal emulator), I will fill a bug report there. Thanks.

**Comment by sylvain-bougnoux** [comment]
Actually it does not work in `jupyter qtconsole`, I guess it is the 'guilty'. I will report there.

**Comment by MrMino** [comment]
No problem.
