### ISSUE TITLE
IPython crash when use showtraceback with exception_only=True

### ISSUE THREAD

**Issue by MiklosTacs** [ipython/ipython#13152]
Used IPython version: 7.20.0-py38hd4e2768_1

len(None) is called in the iPython code.

The following exception was raised:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 1103, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "C:\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "C:\Anaconda3\lib\inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
And when this exception is caught in IPython.core.ultratb.VerboseTB.get_records, the return value is None:

def get_records(self, etb, number_of_lines_of_context, tb_offset):
    try:
        # Try the default getinnerframes and Alex's: Alex's fixes some
        # problems, but it generates empty tracebacks for console errors
        # (5 blanks lines) where none should be returned.
        return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
    except UnicodeDecodeError:
        # This can occur if a file's encoding magic comment is wrong.
        # I can't see a way to recover without duplicating a bunch of code
        # from the stdlib traceback module. --TK
        error('\nUnicodeDecodeError while processing traceback.\n')
        return None
    **except:
        # FIXME: I've been getting many crash reports from python 2.3
        # users, traceable to inspect.py.  If I can find a small test-case
        # to reproduce this, I should either write a better workaround or
        # file a bug report against inspect (if that's the real problem).
        # So far, I haven't been able to find an isolated example to
        # reproduce the problem.
        inspect_error()
        traceback.print_exc(file=self.ostream)
        info('\nUnfortunately, your original traceback can not be constructed.\n')
        return None**
But the next operation with return value that it is called len() in IPython.core.ultratb.find_recursion, and this causes an exception and IPython crash.

I cannot prove code which helps to reproduce the bug because of my company policy other hand special HW (SWHIL) is also necessary.

**Comment by MrMino** [comment]
Duplicate of #12831.
