### ISSUE TITLE
Provisional Completer API Thoughts

### ISSUE THREAD

**Issue by jdtsmith** [ipython/ipython#13155]
I've been using the provisional completion API for an Emacs mode targeting inferior-iPython.  The docs mention interest in feedback on the API, so I thought to open an issue to discuss.  Some thoughts and suggestions:

- The current provisional API was put in place 5 years ago.  Are there any plans to change it in the near term?  If not, perhaps the provisional context requirement should be dropped, and the docs should no longer indicate the functionality as experimental.  After all, `[Tab]` has been providing these completions for 5 years, so they are pretty well vetted!
- It's very useful that the completion API provides the bounds of the string which it is completing.  What would also be very helpful is to also get the bounds of the full expression iPython + jedi are evaluating for the completion itself.  For example, in `x.y[0].z[Tab]` IPCompleter will indicate `z` as the completion text to alter, but presumably iPython knows that it's evaluating an entire expression `x.y[0].z___`.  This would be very useful for users of the API that want to query functions for docstrings, etc. during completion. 

Thanks for iPython.

**Comment by krassowski** [comment]
@meeseeksdev tag tab-completion
