### ISSUE TITLE
Traceback File "...", line x, so you can click on it in terminals to go to statement 

### ISSUE THREAD

**Issue by gertcuykens** [ipython/ipython#13169]
When using Python you can click on the File line in vscode terminal to go to statement 
```
Traceback (most recent call last):
  File "/Users/gert/Desktop/py/./tutorial.py", line 4, in <module>
```
When using IPython the line number is displayed in such a way you can't parse it
```
ValueError                                Traceback (most recent call last)
~/Desktop/py/tutorial.py in <module>
```
Suggest to keep the default  File "...", line x, syntax

related to https://github.com/ipython/ipython/issues/7998

**Comment by vidartf** [comment]
I think this was closed in https://github.com/ipython/ipython/pull/13417 ?
