### ISSUE TITLE
ctrl-c/ctrl-break hangs interactive python input from win7 64-bit qtconsole

### ISSUE THREAD

**Issue by mwiebe** [ipython/ipython#1322]
This is probably related to #514, but is unrelated to shell commands. In #481, @cboos mentions a context where ctrl-C hangs, this might be related to that as well. I'm running from the latest master.

If I don't hit ctrl-break, things are normal:

```
In [1]: raw_input("test: ")

test: testing!
Out[1]: u'testing!'

In [2]: 
```

but, if I do hit ctrl-break, it freezes:

```
In [2]: raw_input("test: ")

test: can still edit here, but enter doesn't work after hitting ctrl-C
    [at this point, only the 'restart kernel' command works]
```

**Comment by Carreau** [comment]
I'm going to attempt migrating this using the bot I'm writing. Sorry for the noise if it does not work, I've tested extensively on test repos, and it works, but one never know.

@Meeseeksdev[bot] migrate to jupyter/qtconsole

**Comment by Carreau** [comment]
It seem to work :-) I'm now happy. Though it is hardcoded to respond only to a couple of users in a couple of repositories.
