### ISSUE TITLE
Matplotlib-3.5.0 won't allow anymore "orientation" parameter in savefig

### ISSUE THREAD

**Issue by stonebig** [ipython/ipython#13241]
playing with seaborn/Matplotlib on Jupyter Notebook I get this error:
![image](https://user-images.githubusercontent.com/4312421/139597622-77a4cc17-e6ff-4fdf-ad1c-443d653bb180.png)

this erroneous parameter may apparently come from "%matplotlib inline"

https://gitter.im/matplotlib/matplotlib?at=617ee0f12197144e849af0ab

**Comment by stonebig** [comment]
simpler example, without seaborn:

````
%matplotlib inline
````

````
import matplotlib.pyplot as plt
import numpy as np

# Data for plotting
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)

fig, ax = plt.subplots()
ax.plot(t, s)
plt.show()
````
![image](https://user-images.githubusercontent.com/4312421/139603515-fb4ddd8a-91c8-4f5f-a354-5a34bf1884fb.png)

**Comment by ianhi** [comment]
I think this may be a setting in your rcparams perhaps? I think the inline backend is now managed in https://github.com/ipython/matplotlib-inline but there doesn't seem to be any usage of `orientation` there

**Comment by stonebig** [comment]
trying with matplotlib-master of october 30th , I don't have the expected breakage, so the problem may have resolved itself somehow.
