### ISSUE TITLE
p_venv.parts[1] - IndexError: tuple index out of range

### ISSUE THREAD

**Issue by acamso** [ipython/ipython#13268]
I just updated IPython to the newest version 7.29 - worked fine in 7.26. I also tried the 7.30.0.dev branch with the same result. Reverting back to 7.26 worked.

**Traceback**
```
File "/home/*****/.venv/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 524, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/home/*****/.venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 645, in __init__
    self.init_virtualenv()                                                                                                              
  File "/home/*****/.venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 924, in init_virtualenv 
    if p_venv.parts[1] == "cygdrive":
IndexError: tuple index out of range
```

**Comment by Carreau** [comment]
Hum, that was introduced as part of #13153.

Out of curiosity, I guess you are not using venv ? Or are you?
And what is the value of `os.environ["VIRTUAL_ENV"]`, `Path(os.environ["VIRTUAL_ENV"])`,

**Comment by AlexChalk** [comment]
@Carreau I've also seen this error. I have `export VIRTUAL_ENV="./result"`, so no 1-index:
```
>>> from pathlib import Path
>>> foo = Path("./result")
>>> foo.parts
('result',)
```

**Comment by GigiusB** [comment]
I have same issue.
I am managing my virtualenv with poetry using "virtualenvs.in-project = true" 
This means my `p_venv == ".venv" `

A possible quick workaround could be checking first for the length of p_venv ?

**Comment by saltlightscript** [comment]
Also having this issue when using a one barrelled VIRTUAL_ENV
My usecase is that on windows on MinGW when I generate virtualenv it incorrectly adds the VIRTUAL_ENV path to the cwd so I change it to 'venv' to make that work, and therefor this issue happens due to ipython not checking for list length first

**Comment by minusf** [comment]
just ran into this when having `VIRTUAL_ENV=./venv`

this bit is indeed not very defensively coded and it seems strange we have to suffer for cygwin :D 

```diff
-       if p_venv.parts[1] == "cygdrive":
+       if "cygdrive" in p_venv.parts:
            drive_name = p_venv.parts[2]
            p_venv = (drive_name + ":/") / Path(*p_venv.parts[3:])
```

**Comment by Carreau** [comment]
There was a PR last week to try to improve things, feel free to send a PR.

I believe #14440 should fix this, so closing. Feel free to open another issue if more issues arise.
