### ISSUE TITLE
Remove pre-3.8 codepath.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#13316]
Once https://github.com/ipython/ipython/pull/13315 is merged the master branch will not support 3.7 anymore, this gives opportunities to remove all the pre-3.8 codepath.

If you like to contribute, find 1 block of code that is execute only before python 3.8 (look for sys.version_info in the code base), 
and simplify it. 

It may be more than just deleting code, as you might be then able to cleanup imports, or simplify more logics.

**Comment by Carreau** [comment]
https://app.codecov.io/gh/ipython/ipython/compare/13315/changes might be a good way to see code that can potentially be removed.

**Comment by GalBr** [comment]
@Carreau Should I continue working on this issue or should we save it for newer people?

**Comment by Carreau** [comment]
> @Carreau Should I continue working on this issue or should we save it for newer people?

Up to you, depend how comfortable you are around the code base. It's a good way to get started maybe try to remove the conditional code and try to understand/simplify/improved nearby code ?
