### ISSUE TITLE
Notebooks on MacOS Monterey do not all use the proper .zshrc or .bash_profile

### ISSUE THREAD

**Issue by RawbRAwbRawb** [ipython/ipython#13413]
All:

On MacOs 12.1 and using Jupyterlabs / Python 3.9:

Trying to print out LaTeX formatted Notebook and keep getting the usual "Pandoc not found"

I edited both .bash_profile and .zshrc to add a path to Pandoc and the latter got me to the following.

On the terminal  within JupyterLabs>"which pandoc" returns correct path.
<img width="539" alt="Screen Shot 2021-12-21 at 10 47 30 AM" src="https://user-images.githubusercontent.com/96495333/146982401-8fed037d-6364-49a3-8fca-1e4593c8e0c1.png">

Just like is does in the normal terminal

But ...
Within a notebook within jupyter:
<img width="515" alt="Screen Shot 2021-12-21 at 10 49 08 AM" src="https://user-images.githubusercontent.com/96495333/146982618-26f473f9-adea-4101-a7e2-04c4166f601d.png">

So it seems that a terminal opens with one .rc file but the notebooks open with another?

you will notice that /usr/local is missing in the "!echo $path" command.

Adding this at the top of the file (path add) into the command line is a fine solution, but doesn't seem to work either.
--> I suspect THAT is a permissions problem.

<img width="512" alt="Screen Shot 2021-12-21 at 10 54 21 AM" src="https://user-images.githubusercontent.com/96495333/146983185-17bdd6a2-bdcd-4a63-b081-78cde1b13865.png">

You notice that the PATH doesn't change.

On edit *********  added in system console outputs to show path is proper

<img width="557" alt="Screen Shot 2021-12-21 at 11 08 12 AM" src="https://user-images.githubusercontent.com/96495333/146984678-6dcc60d1-9682-405f-99fc-24c554699a54.png">

**Comment by Carreau** [comment]
That is likely an issue for jupyter/notebook, not for IPython itself, as there is no code here related to starting a kernel.

**Comment by RawbRAwbRawb** [comment]
Ok, thanks. Reposted there.
