### ISSUE TITLE
`%%capture` writes `stderr`  to `stdout`

### ISSUE THREAD

**Issue by pya** [ipython/ipython#13425]
I expected the exception  to be written to `stderr` but `%%capture`  seems to write it to  `stdout`:

```
$ ipython
Python 3.10.1 | packaged by conda-forge | (main, Dec 22 2021, 01:39:14) [Clang 11.1.0 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.30.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %%capture cap
   ...: print('Hello')
   ...: 1 / 0
   ...: 
   ...: 

In [2]: cap.stderr
Out[2]: ''

In [3]: print(cap.stdout)
Hello
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-5-c7d63a990d8c> in <module>
      1 print('Hello')
----> 2 1 / 0
      3 

ZeroDivisionError: division by zero
```

This may lead to this problem in JupyterLab
https://github.com/jupyterlab/jupyterlab/issues/11775

**Comment by krassowski** [comment]
To my understanding the exception is not written to either stderr or stdout - it is raised and aborts the execution flow, so `%%capture` magic cannot capture anything printed out after it occurred.

The capturing of stderr works fine in principle:

![Screenshot from 2022-01-01 12-20-02](https://user-images.githubusercontent.com/5832902/147850453-fae1774f-425d-42ba-9755-a30e82c54c5c.png)

**Comment by pya** [comment]
Thanks for your answer. Looks like I misunderstood the concept how `%%capture` works. My use case is writing with JupyterBook. I would like to  "clean" the exception from absolute paths and re-raise it with a nicer looking text (for my teaching purposes). I do have a work around. Since I process the `*.ipynb` JSON anyway before building with JupyterBook, I just clean it there. Alternatively, I could write my own cell magic, using a `try`- `except` and using the  `%%capture` functionality in the way you explain.

**Comment by Carreau** [comment]
Sorry for being late to the party. 
The easiest way would be to switch the exception shower of IPython:

```python
ip = get_ipython()

def my_show_tb(exc_tuple=None, filename=None, tb_offset=None,
                      exception_only=False, running_compiled_code=False):
    print(ip._get_exc_info(exc_tuple))

ip.showtraceback = my_show_tb
```

```python
In[x]: raise ValueError
(<class 'ValueError'>, ValueError(), <traceback object at 0x1048a7180>)
```

Note that it should already remove absolute path and elide home to `~`, i'm happy to get patches that simplify more.

If you have your own tb handler and want to put it in `ultratb.py`, i'm also happy to make new modes beyond `plain`, `context` and `verbose`. 

If you want a "tutorial", or "teaching" mode, it can be added.
