### ISSUE TITLE
Multi-line edit executes too early with await

### ISSUE THREAD

**Issue by cdeil** [ipython/ipython#13424]
I was trying to type this example in IPython:
```
from prefect.client import OrionClient

async with OrionClient() as client:
    deployment = await client.read_deployment_by_name("Addition Machine/my-first-deployment")
    flow_run = await client.create_flow_run_from_deployment(deployment)
```
However, typing ENTER after the first line with an `await` statement stops the multi-line edit too soon and executes the code:
```
In [16]: async with OrionClient() as client:
    ...:     deployment = await client.read_deployment_by_name("Addition Machine/my-first-deployment")

In [17]:
```

I think this is a general bug with `await`, the same bug happens with any other example, e.g.
```
In [17]: with open():
    ...:     spam = await Thing()
```

@minrk  - related to #13348 ?

**Comment by minrk** [comment]
I don't think it's related to #13348, which has to do with _running_ async code. This would be in the `check_complete` check of the input transformer, which considers invalid syntax to be 'complete' so it shows you a syntax error immediately. A top-level `await` is not valid Python syntax, but IPython manages this during execution by wrapping it in a coroutine. The same wrap doesn't occur in the input-transform check, however, so there's a disconnect between what code is _actually_ run vs what is evaluated for completeness/syntax validity.
