### ISSUE TITLE
Improvement of  `core.magic_arguments` example

### ISSUE THREAD

**Issue by kolibril13** [ipython/ipython#13431]
Currently, there is only a [very raw example](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.magic_arguments.html?highlight=%40magic_arguments.argumen#module-IPython.core.magic_arguments
) of using `magic_arguments` with custom cell magic.
Therefore, I have the idea to add a second, more fleshed out example that might help people to easier understand and use cell magic arguments: 
![image](https://user-images.githubusercontent.com/44469195/148220767-d59ad4ca-e713-434a-8241-c212580fba6b.png)
Here is the code:
```py
from IPython.core import magic_arguments
from IPython.core.magic import register_cell_magic


@magic_arguments.magic_arguments()
@magic_arguments.argument(
    "--option",
    help=("Add an option here"),
)
@magic_arguments.argument(
    "--style",
    default=None,
    help=("Add some style arguments"),
)
@register_cell_magic
def my_cell_magic(line, cell):
    """Cool cell magic"""
    args = magic_arguments.parse_argstring(my_cell_magic, line)
    print(args.style)
    print(args.option)
```

**Comment by Carreau** [comment]
Sure, do you want to send a PR ?

**Comment by kolibril13** [comment]
Yes, here it is: #13433

**Comment by Carreau** [comment]
You don't need to close issues when sending PRs, merging the PR automatically closes the linked issue.

**Comment by kolibril13** [comment]
Okay!
