### ISSUE TITLE
Autocomplete crashes ipython

### ISSUE THREAD

**Issue by FalcoGer** [ipython/ipython#13430]
I'm running ipython from the ubuntu software repositories package `python3-ipython` for 20.04, currently version `7.19.0` with python version `3.8.10`.
```text
uname -a
Linux <myhostname> 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
Whenever I try to autocomplete, the terminal window scrolls down as if to make room for the selection box, but nothing shows up there. Nothing gets autocompleted and nothing else happens.
When I then manually complete the command and hit enter, ipython crashes.
Backtrace and crashreport are attached. Importing sys doesn't solve the issue either.
[Crash_report_ipython.txt](https://github.com/ipython/ipython/files/7814279/Crash_report_ipython.txt)

**Comment by FalcoGer** [comment]
installed it with pip3, now it works.

**Comment by Carreau** [comment]
Yes, it looks like you have (had) a quite old version of IPython as the latest IPython is 7.31, and that was indeed a fixed bug. 

Closing.
