### ISSUE TITLE
IPython 8.0: built in aliases issue warnings: You executed the system command !ls

### ISSUE THREAD

**Issue by mario-grgic** [ipython/ipython#13449]
Starting with IPython 8 built in aliases `ll`, `ldir`, `lf`, `lx` etc issue warnings:

```
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/IPython/core/interactiveshell.py:2373: UserWarning: You executed the system command !ls which may not work as expected. Try the IPython magic %ls instead.
  warnings.warn(
```

**Comment by sabjohnso** [comment]
e0c24607cb40bc4d2cc6f7859526db9a857ee51c Added `cd` and `ls` to the list of system commands to warn that there are equivalent magics.  It included logic to check that the commands did not come from expanded aliases.  However, the logic is not correct and the warnings are being issued for expanded aliases.
