### ISSUE TITLE
Promblem with prompt-toolkit 3.0.24, ipython 7.31.0, and python 3.7

### ISSUE THREAD

**Issue by DManowitz** [ipython/ipython#13444]
I have an environment with python 3.7, ipython 7.31.0, and prompt-toolkit (and prompt_toolkit) 3.0.24.  When I try to run ipython, I get this error:
ModuleNotFoundError: No module named 'prompt_toolkit.enums'

Downgrading prompt-toolkit and prompt_toolkit to 3.0.4 appears to have fixed the issue.

However, in an environment with python 3.8, ipython 7.31.0, and prompt-toolkit 3.0.24, I get no error.

**Comment by MrMino** [comment]
I cannot reproduce this. Are you sure you are actually running ipython from your currently active environment? Try to refresh the shell caches: `hash -d` in bash / `rehash` in zsh, and rerun ipython
