### ISSUE TITLE
IPython-8 warns about virtualenv created by pyenv

### ISSUE THREAD

**Issue by verdimrc** [ipython/ipython#13457]
Hi, is there a way to disable the virtualenv warning?

I use pyenv, and every time IPython-8.0 starts from a virtual environment that's based on pyenv's miniconda, it shows this warning:

```bash
# Activate virtualenv via 'pyenv activate my_project_env' or 'pyenv activate my_base_python_env/envs/my_project_env'.
...

# Then, start ipython (installed in that virtual env).
$ ipython
/Users/xxx/.pyenv/versions/rubix-mds/lib/python3.9/site-packages/IPython/core/interactiveshell.py:802: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
  warn(
Python 3.9.7 (default, Sep 16 2021, 08:50:36) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sys
   ...: 
   ...: sys.executable
Out[1]: '/Users/xxx/.pyenv/versions/rubix-mds/bin/python'

In [2]: import os
   ...: 
   ...: os.environ["VIRTUAL_ENV"]
Out[2]: '/Users/xxx/.pyenv/versions/miniconda3-latest/envs/rubix-mds'
```

This only happens for virtualenv based on another pyenv's miniconda3-latest. No warning shown with virtualenv based on another pyenv's "python version".

```bash
$HOME
`-- versions
    |-- miniconda3-latest
    |   `-- envs
    |       `-- rubix-mds
    `-- rubix-mds -> $HOME/.pyenv/versions/miniconda3-latest/envs/rubix-mds
```

I'd like to know if there's a way to silent this particular warning?

Thank you.

**Comment by Carreau** [comment]
Hum, I would have to try, but see if you can use `warnings.filterwarnings` in one of the [startup files](https://ipython.readthedocs.io/en/stable/interactive/tutorial.html?highlight=startup#startup-files).

I'f not we can add a flag/config option to silence it.

**Comment by luca-drf** [comment]
I have the same problem as @verdimrc. Note that the IPython that is executed is actually installed in the virtualenv. I started noticing this problem with IPython 7.28.0.

**Comment by cbrnr** [comment]
+1 for a config option to silence this warning. I'm using IPython via pipx, precisely because I didn't want to install it in every venv.

**Comment by MrMino** [comment]
If you get this warning then you are _not_ running IPython from the active virtualenv.

Lots of people get confused by this, when they don't realize that their shells cache `PATH` resolution. Right after you install IPython in the virtualenv, the command `ipython` may still point to the installation from outside of your venv.

I have doubts whether adding an option to suppress this warning, thereby adding another moving part to the whole setup, will actually help.

**Comment by cbrnr** [comment]
I don't want to install IPython in every venv, that's why I run the one from my main env. Because this applies to many projects I'm using, I'd appreciate an option to disable the warning.

**Comment by MrMino** [comment]
I'm not sure how healthy it is to do that, but I guess we can add it for that usecase.

I would still like to advise people against doing it this way. There be dragons.

**Comment by cbrnr** [comment]
Of course, the default is still to issue the warning. But people can silence it if they want.
