### ISSUE TITLE
IPython 8.0 requires pre-release dependency

### ISSUE THREAD

**Issue by pehala** [ipython/ipython#13454]
With the release of IPython 8.0 it is now dependent on `black`, which has all releases on pypi marked as pre-release, that means, e.g. you cannot install IPython 8.0 with pipenv without enabling pre-release dependencies even tho IPython is not pre-release.

**Comment by n1ngu** [comment]
Per the documentation I would still expect the black requirement to be optional

https://ipython.readthedocs.io/en/stable/whatsnew/version8.html#auto-formatting-with-black-in-the-cli

Not that this can happen after black is required in the setup.cfg after df3248f00a60859ed07f81e87531856b30891396

**Comment by lpsinger** [comment]
:+1: black is not a runtime dependency of IPython, so it shouldn't be in `install_requires`. Black is only needed for development. It should be in extras.

**Comment by n1ngu** [comment]
For a possible workaround, explicitly state a black pre-release as a requirement in your Pipfile. This
```
[packages]
black = "==21.12b0"
ipython = "*"
```
installs just fine. (but it is cumbersome and hard to maintain, etc, so better wait for ipython 8.1)

Also, this does not affect recent pipenv versions so maybe update the very pipenv if you can afford it.

**Comment by renzon** [comment]
As a workafound I prefered seting Ipython to < 8. There is not good reason in sending black to production.

**Comment by n1ngu** [comment]
> There is not good reason in sending black to production.

Sorry if this goes offtopic, but:

@renzon if you are deploying an application that relies on IPython, this is specifically a very good reason to send black alongside it! If you weren't already or even if IPython-8.1 won't have a hard requirement on black, I'd suggest to consider installing it to unlock extra IPython features for your application.

If your app does not use IPython in production... then you would have no reason to send *IPython* to production at all. Black is not the issue, so I'd suggest to sort out your production vs development requirements (`pipenv install --dev ipython` given that you are attending this issue)

**Comment by JelleZijlstra** [comment]
FYI we're planning to release a non-beta version of Black by the end of the month.

**Comment by Carreau** [comment]
Closing, black has been removed as hard dependency , and it's stable now.
