### ISSUE TITLE
Unknown variable ip

### ISSUE THREAD

**Issue by mcepl** [ipython/ipython#13460]
https://github.com/ipython/ipython/blob/c0abea7a6dfe52c1f74c9d0387d4accadba7cc14/IPython/core/tests/test_oinspect.py#L120

Where is this `ip` variable coming from? (And there is a way more of them in this file)

**Comment by daredevil82** [comment]
https://github.com/ipython/ipython/blob/c0abea7a6dfe52c1f74c9d0387d4accadba7cc14/IPython/conftest.py#L69

You can see in conftest

**Comment by mcepl** [comment]
OK, if it is correct, then I just got lost in ugliness of pytest.
