### ISSUE TITLE
r followed by quote auto-matches with closing quote regardless of context

### ISSUE THREAD

**Issue by RobinFiveWords** [ipython/ipython#13479]
In 8.0.0 typing any of the following...
```
r'
r"
R'
R"
```
...seems to duplicate that quote character regardless of where it is typed. For example, type this...
```
In[1]: pqrst
```
...then move the cursor back between the r and s and type one double-quote, and it will add a second resulting in this:
```
In[1]: pqr""st
```

Behavior seems to be unaffected by turning on TerminalInteractiveShell.auto_match or setting TerminalInteractiveShell.autoformatter = None.

(edit) More generally, any quoted string ending in R has an extra quote character auto-inserted that then needs to be deleted.

I imagine this is driven by /terminal/shortcuts.py lines 183-191. When I comment out these lines, it behaves as I would expect, even when turning on auto_match. Why are raw strings considered a special case forcing auto-match rather than letting lines 142-150 dictate how it behaves based on the user's auto_match choice?

**Comment by Carreau** [comment]
This should be fixed, let's try to keep comments in #13465 is it is not.
