### ISSUE TITLE
Highlighting within traceback/errors in Jupyter Notebook after IPython 8.0.0

### ISSUE THREAD

**Issue by omasoud** [ipython/ipython#13476]
Not sure if this belongs here or in https://github.com/jupyter/notebook. I'm logging it here since it seems to correlate with `ipython` 7.31.0 -> 8.0.0 

With `notebook` 6.4.7 + `ipython` 7.3.1:

![image](https://user-images.githubusercontent.com/16273458/149837913-81e4317f-2c7f-4cc2-b63c-da661daded65.png)

With `notebook` 6.4.7 + `ipython` 8.0.0:

![image](https://user-images.githubusercontent.com/16273458/149837968-2a50d617-ff21-4af3-b6a0-3e21105ddab5.png)

So new highlighting within the traceback shows up, which is nice. But it doesn't seem to have good visibility in a dark mode.
(Darkness achieved via `!jt -t monokai` from [`jupyterthemes`](https://github.com/dunovank/jupyter-themes).

Where is the color control happening? And is there a way to disable this particular highlighting altogether?

Thanks in advance for your response.

**Comment by Carreau** [comment]
You might be able to make it better by tweaking the value of `@ansiyellow`

https://github.com/dunovank/jupyter-themes/blob/889b9f06c24dbb8d86af902cb5e0d2630c741892/jupyterthemes/styles/monokai.less#L142

It is not yet configurable on the IPython side.

**Comment by omasoud** [comment]
Thanks! That gave me a good direction. Here is what I had to do:
- Added to `Lib\site-packages\jupyterthemes\layout\codemirror.less`:
```css
    span.ansiyellow-bg,
    .ansi-yellow-bg {
        color: @ansiyellow-bg;
    }
```
        
- Added to `Lib\site-packages\jupyterthemes\styles\monokai.less`:
```css
    @ansiyellow-bg:         #524412;
```
Then ran `!jt -t monokai` to update.

Result:
![image](https://user-images.githubusercontent.com/16273458/150019308-fc508773-2197-40f0-9ce5-75c2e9006616.png)
