### ISSUE TITLE
Autoimport Custom Magics

### ISSUE THREAD

**Issue by mlucool** [ipython/ipython#13493]
To use a custom magic, you first need to run `%load_ext module.path` or configure IPython to autoload an extension. The former requires you not to just remember the magic you want to use, but also where it's from exactly. It also requires an extra LOC. The latter sounds great, but if you have an extension that is slow to load or you want to sometimes update the PATH before using that custom magic, then you can't use this method.

To solve this, I propose adding a magic mapper which IPython can use to determine where to load_ext if the magic is not already loaded. Doing this in the standard `ipython_config` allows for both sitewide defaults as well as user customizations.

While maybe not the best API this is what I mean:
```
c.MagicMapper.extend({
   'foo': 'myext.foo',
   'bar': 'myext.foo',
   'baz': 'anotherext'
})
```

Now in a notebook, if I run `%%foo` instead of ``UsageError: Cell magic `%%foo` not found.``, IPython first tries `%load_ext myext.foo`.

What do you think?

**Comment by Carreau** [comment]
See #13506 

Will be release at end of month.
