### ISSUE TITLE
Is tab supposed to work in the ultratb prompt ?

### ISSUE THREAD

**Issue by chapmanjacobd** [ipython/ipython#13495]
I really love ultratb and I probably overuse it (instead of logging and running I often raise)

When I press tab I get a tab char inserted into the ipdb REPL.

Is tab supposed to work in ultratb or does tab completion require `prompt_toolkit`? Maybe it is not working on my machine or maybe it is working as it is supposed to--not sure. 

If it is not supposed to work would it make sense to supply TerminalPdb instead of debugger.Pdb ? Maybe that could be exposed as a kwargs option...

```
Python 3.9.10 (main, Jan 17 2022, 00:00:00) 
import IPython
@>>> IPython.version_info
(8, 0, 1, '')

kitty 0.21.2 created by Kovid Goyal
fish, version 3.3.1
```

**Comment by Carreau** [comment]
So I'm not quite sure what you are asking, not how you are using it, but for me:

```
In [1]: import ipdb
   ...:
   ...: ipdb.set_trace()
--Call--
> /Users/bussonniermatthias/dev/ipython/IPython/core/displayhook.py(252)__call__()
    251
--> 252     def __call__(self, result=None):
    253         """Printing with history cache management.

ipdb> imp<tab> # complete to import
```

It does need prompt toolkit though I believe. 

<img width="273" alt="Screen Shot 2022-01-28 at 20 57 17" src="https://user-images.githubusercontent.com/335567/151613083-f6736dd0-c801-44e1-8b9c-997e546ca37a.png">

**Comment by chapmanjacobd** [comment]
ah I use it like this

```
sys.excepthook = ultratb.FormattedTB(
    mode="Verbose" if args.verbose > 0 else "Context", color_scheme="Neutral", call_pdb=1
)
```

**Comment by chapmanjacobd** [comment]
oh maybe this will work

```
from IPython.terminal.debugger import TerminalPdb

sys.excepthook = ultratb.FormattedTB(
                    mode="Verbose" if args.verbose > 0 else "Context",
                    color_scheme="Neutral",
                    call_pdb=1,
                    debugger_cls=TerminalPdb,
                )
```

**Comment by chapmanjacobd** [comment]
I also get an IndentationError immediately after pressing enter

```
@ipdb> for key, value in extra_dict.items():    
*** IndentationError: expected an indented block
```

so maybe part of it is a configuration error or maybe a limitation of pdb

**Comment by Carreau** [comment]
It's a bug. You can patch locally:


```
class TBTools(colorable.Colorable):
    """Basic tools used by all traceback printer classes."""

    # Number of frames to skip when reporting tracebacks
    tb_offset = 0

    def __init__(self, color_scheme='NoColor', call_pdb=False, ostream=None, parent=None, config=None):
        # Whether to call the interactive pdb debugger after printing
        ...
-        if call_pdb:
-            self.pdb = debugger.Pdb()
-        else:
-            self.pdb = None
+        self.pdb = None

```

And then using 


```
sys.excepthook = ultratb.AutoFormattedTB(
    mode="Verbose",
    color_scheme="Neutral",
    call_pdb=1,
    debugger_cls=TerminalPdb,
)
```

Works for me. 

I need to look into a proper fix, and see if it has other effects, or you can try to send a PR.

**Comment by chapmanjacobd** [comment]
this seems to fix it but I'm not sure if it is the best solution. https://github.com/ipython/ipython/pull/13498

I think this does not fix it for ListTB (? never used that)

is self.debugger_cls available in TBTools? maybe something like this would be better ?

```
class TBTools(colorable.Colorable):
		 ...
        if call_pdb and not self.debugger_cls:
            self.pdb = debugger.Pdb()
        else:
            self.pdb = None
```

**Comment by chapmanjacobd** [comment]
Here is a quick way to test it out

```
python -c "import sys;from IPython.core import ultratb;from IPython.terminal.debugger import TerminalPdb;sys.excepthook=ultratb.FormattedTB(mode='Context',color_scheme='Neutral',call_pdb=1,debugger_cls=TerminalPdb);raise"
```
