### ISSUE TITLE
Auto-complete hinted suggestions using the END key

### ISSUE THREAD

**Issue by FFY00** [ipython/ipython#13492]
Sorry if this is duplicated and has been implemented already, but I did search the issue tracker and did not find anything mentioning it.

The auto-complete hints in the new version are awesome, however I find myself trying to apply them by pressing the END key, just like I do in the fish shell, and IPython does not seem to have that keybind enabled by default.

Would it be possible to consider adding this to the default keybinds? Several other auto-completion systems do the same, so I don't think I am the only user that would be benefit from this change. I think it would make the defaults slightly better :blush: 

Thank you!

**Comment by Carreau** [comment]
Yes, that is a good idea, I thought about it at some point, configure which keys allow to validate hinted suggestion, and also allow other sources of hinted suggestions. I'm not sure I'll have the time to do that soon, so it will likely need someone to contribute it.
