### ISSUE TITLE
ValueError while using DeepLabCut

### ISSUE THREAD

**Issue by bncullins** [ipython/ipython#13490]
I came across this issue in DeepLabCut after analyzing and attempting to convert to tracklets in the GUI:

![AnalyzedANDConvertToTrackletsError_1-25-22](https://user-images.githubusercontent.com/98359924/151044960-b9bcc6bc-fd6c-4bc0-ae82-3d5e3a9c4180.png)

I'm using Windows 10 Pro, ipython 7.30.1. Thank you and please let me know if I can provide any other information.

**Comment by Carreau** [comment]
That looks like a problem in DeepLabCut, not with IPython itself, you'll have to see with them. 
Thanks.
