### ISSUE TITLE
disable whatever is expanding / autoindenting my code in my shell history

### ISSUE THREAD

**Issue by clandestinenetworks** [ipython/ipython#13496]
how do I turn this off so it doesn't auto indent my history like that?
![Screenshot_20220128_114154](https://user-images.githubusercontent.com/93053093/151611111-22366200-96b3-4051-abb0-08022ab41526.png)

pisses me off that I even have to ask :/

**Comment by Carreau** [comment]
```
$ ipython --help-all 
...
--autoindent
    Turn on autoindenting.
    Equivalent to: [--InteractiveShell.autoindent=True]
--no-autoindent
    Turn off autoindenting.
    Equivalent to: [--InteractiveShell.autoindent=False]
..
--InteractiveShell.autoindent=<Bool>
    Autoindent IPython code entered interactively.
    Default: True
```

You can also make an effort and read the last few issues/pr, and changelog.
