### ISSUE TITLE
In debug (IPdb) mode within Spyder, calling `!n` in IPython 8.0.1 at the end of a file opens spydercustomize.py rather than exiting IPdb

### ISSUE THREAD

**Issue by juliangilbey** [ipython/ipython#13507]
I've been working on getting Spyder 5.x into Debian.  At the moment, the Spyder maintainers are pinning Spyder to version 7.x, but the Debian IPython maintainer is ready to upgrade to version 8.0.1.  I'm therefore testing Spyder 5.2.2 with IPython 8.0.1 to see if there are any significant issues, which presumably there ought not to be.  But one of the Spyder tests fails, and it is clear what has changed (and probably "gone wrong") between IPython 7.31.1 and IPython 8.0.1, but I have no idea how to fix it, I'm afraid.

The failing Spyder test is `spyder/app/tests/test_mainwindow.py::test_c_and_n_pdb_commands` (which you can find at https://github.com/spyder-ide/spyder/blob/84e199395fdb0fe9d2fc1ba148c44cfe42cbafec/spyder/app/tests/test_mainwindow.py#L1783), and I will now describe the behaviour with IPython 7.31.1 and IPython 8.0.1.  It seems easy to reproduce in Spyder 5.2.2.

This test starts by loading the following file:
```python
# %% first Code Cell's name
a = 10
"Hello"

# In[23]
li = [1, 2, 3]

# <codecell> Third Code Cell\'s name
import numpy as np
arr = np.array(li)

#%% Fourth Code/ Cell's % name\
s = """Z:\\escape\\test\\string\n"""
a
```
It then does the following in the script window and IPython console:
* Start the debugger.  The prompt moves to line 2 of the file (`a = 10`), and the IPython window shows (in colour):
```
In [1]: debugfile('/tmp/script.py', wdir='/tmp')
> /tmp/script.py(2)<module>()
      1 # %% first Code Cell's name
----> 2 a = 10
      3 "Hello"
      4 
      5 # In[23]
```
* Set a breakpoint at line 6
* Enter `!c` in the IPython window.  The prompt moves to line 6.
* Enter `!n` 5 times.  After the 5th time, the line `a` has been executed and both IPython 7.31.1 and IPython 8.0.1 show:
```
IPdb [6]: !n
--Return--
None
> /tmp/script.py(14)<module>()
     10 arr = np.array(li)
     11 
     12 #%% Fourth Code/ Cell's % name\
     13 s = """Z:\\escape\\test\\string\n"""
---> 14 a
```
* Enter `!n` one more time. We now get divergent behaviour.  The expected result is that of IPython 7.31.1, with the debugger exiting:
```
IPdb [7]: !n

In [2]: 
```
* However, with IPython 8.0.1, the file `(spydercustomize.py)` is opened within the Spyder editing windows area, and the IPython terminal shows the following:
```
IPdb [7]: !n
> /usr/lib/python3/dist-packages/spyder_kernels/customize/spydercustomize.py(481)exec_code()
    479             # We ignore the call to exec
    480             ipython_shell.showtraceback(tb_offset=1)
--> 481     __tracebackhide__ = "__pdb_exit__"
    482 
    483 
```

This is clearly not the intended behaviour.

Best wishes, Julian

**Comment by Carreau** [comment]
Thanks, i'll see if I can reproduce and track it down.

**Comment by juliangilbey** [comment]
With Spyder 5.3.0, the test works perfectly, so it does not seem to be a problem in IPython.  Sorry for the noise!  Closing this issue now.
Best wishes, Julian
