### ISSUE TITLE
Pin to pytest<7

### ISSUE THREAD

**Issue by rhshadrach** [ipython/ipython#13512]
Just installed for development via the docs `pip install -e '.[test]'`. This got me pytest 7, and trying to run the tests failed. I noticed `Collecting pytest<7` on the CI, and downgrading to pytest 6 fixed.

**Comment by Carreau** [comment]
let see if #13516 fixes it.

**Comment by MrMino** [comment]
I'm confused. How does v7 fails for you, @rhshadrach? I've just done `pip install -e '.[test]'; pytest`: it installed pytest 7.1.0 and passed all of the tests.

**Comment by rhshadrach** [comment]
@MrMino #13523 was merged shortly after I raised this issue. Note that #13523 also removed the pinning in #13516. So I think this can be closed now (for a variety of reasons!).
