### ISSUE TITLE
Console bug adds an extra quote on macOS Monterey

### ISSUE THREAD

**Issue by alternativebug** [ipython/ipython#13530]
I'm experiencing what seems to be a bug which adds an additional single quote. Here's what happens when I only write `x['odor']`, it becomes `x['odor']'`:

[![console][1]][1]

At first I thought I'm making a mistake but when it repeated multiple times in the same minute, by looking further I noticed an extra `'` being added. I don't know why this is happening besides, I want to change the default quote view from double to single quotes which for some reason changed in the following versions:

* macOS Monterey `12.2.1`
* ipython `8.0.1` installed using brew.

  [1]: https://i.stack.imgur.com/7rUlx.gif

**Comment by gimmemabrewski** [comment]
I see this issue has been closed but I am still having the exact same issue on Arch Linux. I'm all up to date as far as I know (just updated and the issue persists). iPython is installed through the main Arch repos.
iPython info when running...
```
Python 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.1.0 -- An enhanced Interactive Python. Type '?' for help.
```
I also have disabled this setting
```
c.TerminalInteractiveShell.auto_match = False
```
in `$HOME/.ipython/profile_default/ipython_config.py` but it didn't make a difference. If this gets reopened I'd be glad to offer any info that might help!

**Comment by unsignedrant** [comment]
@Carreau Why is the issue closed?
