### ISSUE TITLE
Kernel interrupt doesn't work

### ISSUE THREAD

**Issue by lucianadelcastillo** [ipython/ipython#13536]
When I try to interrupt the kernel, it doesn't work, you morons, have you got how much time I lost because of your silly bugs? How hard can it be to interrupt the bloody thing?

**Comment by bollwyvl** [comment]
This might be a little hard to track down without further information about your context, such as:

- which version of (I)Python 
- what operating system
- what your kernel was doing at the time

However, as with [matplotlib](https://github.com/matplotlib/matplotlib/issues/22252), derogatory remarks against the volunteer contributors and maintainers of this software are not welcome here.
