### ISSUE TITLE
Error while saving file: abc.ipynb database or disk is full.

### ISSUE THREAD

**Issue by abhaydd22** [ipython/ipython#13533]
Hello, 

I am facing an issue while writing a code in jupyter notebook in windows os. Error message shown in title is an issue. I have 70 GB of free space in my C: Drive still this issue persist. Could anyone please help me to resolve this, I have gone through multiple threads but none provided correct answer. I have tried renaming history.sqlite also but that doesn't help. I am badly stuck from last two days. Thanks in Advance

**Comment by Carreau** [comment]
I don't think that history.sqlite, it is likely a database of Jupyter notebook itself. 

Do you have the full error message with traceback ? 

At least there is no reason for history to be triggered on notebook save.

run `jupyter --data-dir`, to see the folder for Jupyter data files and look for a `nbsignatures.db` in there. Jupyter likely have a problem writing to _that_ file.

Note that this is likely not an IPython issue at all, it will be an issue for jupyter/notebook or maybe even jupyter/nbformat
