### ISSUE TITLE
v8 Errors: input line numbers missing

### ISSUE THREAD

**Issue by jdtsmith** [ipython/ipython#13541]
I quite like the new (v8) simple format for syntax and other compile errors from Input, like `Input In [25]`.  But compared to the old (v7) error header with pseudo-files (e.g. `File "<ipython-input-6-9e0b5ab16b5e>", line 4`), the line number has gone missing.  There are tools which parse iPython's errors which will be missing this line information.  This is also particularly problematic for syntax/indentation errors in `Plain` style with multi-line input:

```
In [25]: if True:
    ...:     same_var = 1
    ...: else:
    ...:    same_var = 2
    ...:     same_var = 1
    ...:     same_var = 1
  Input In [25]
    same_var = 1
    ^
IndentationError: unexpected indent
```

I think `Input In [25], line 5` would be perfect, or, for consistency with the file version, `Input In [25]:5`.

**Comment by MrMino** [comment]
@jdtsmith Nice. I don't think anyone would have any issue with adding this, could you please turn it into a PR?

**Comment by jdtsmith** [comment]
Thanks, see #13560.

**Comment by MrMino** [comment]
Seems like this has been fixed in 8.1.0 with #13535. My apologies go to @jdtsmith for not checking this properly and wasting their time on this.

**Comment by jdtsmith** [comment]
No worries.  But in fact #13535 only adds line information for run errors like ZeroDivisionError, not Syntax/Indentation Errors, and related.  See #13560. (And it gives me incorrect line numbers too).

**Comment by MrMino** [comment]
You're right. Some of my brain cells might be off today :smile:. Back to PR it is.

Let's reopen this issue though and link the PR, then it will get closed automatically on merge.

**Comment by jdtsmith** [comment]
Hi @MrMino, just checking on the status of this issue.  I have tooling standing by to learn the final decision on restoring line numbers for input blocks across the board.  Thanks.

**Comment by jdtsmith** [comment]
In case you haven't checked in on PR #13560 recently, I got confirmation that the <cell line...> stuff was no longer needed and can be reverted.  I also went ahead a just pushed the small change changing "Input cell" -> "Cell" for a short and consistent layout. Let me know if you see anything else needed in #13560 before it could be merged.
