### ISSUE TITLE
sqlite3.dll missing when installing in a venv on Windows

### ISSUE THREAD

**Issue by waszil** [ipython/ipython#13564]
If I install ipython with pip into a virtual environment created with `python -m venv`, when starting ipython, it will fail because it does not find sqlite3:

I'm using Anaconda3, and created the venv like this:

```
C:\>my_project>conda activate
(base) C:\>my_project>python -m venv venv
(base) C:\>my_project>conda deactivate
C:\>my_project>.\venv\Scripts\activate
(venv) C:\>my_project>python -m pip install ipython
(venv) C:\my_project>ipython
Traceback (most recent call last):
  File "c:\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\my_project\venv\Scripts\ipython.exe\__main__.py", line 4, in <module>
  File "C:\my_project\venv\lib\site-packages\IPython\__init__.py", line 52, in <module>
    from .terminal.embed import embed
  File "C:\my_project\venv\lib\site-packages\IPython\terminal\embed.py", line 15, in <module>
    from IPython.core.interactiveshell import DummyMod, InteractiveShell
  File "C:\my_project\venv\lib\site-packages\IPython\core\interactiveshell.py", line 73, in <module>
    from IPython.core.history import HistoryManager
  File "C:\my_project\venv\lib\site-packages\IPython\core\history.py", line 11, in <module>
    import sqlite3
  File "c:\Anaconda3\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "c:\Anaconda3\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed while importing _sqlite3: The specified module could not be found.
```

It is fixed by manually copying the sqlite3.dll from the main python installation (.../Library/bin/sqlite3.dll) into the virtualenv: .../venc/Scripts/sqlite3.dll

I don't know if it should be managed by venv itself as a part of the standard library, or it should be performed by ipython when its installing.

**Comment by bollwyvl** [comment]
Mixing and matching parts of virtual env techniques probably won't work. The activation part (of either of them) ensure that python and lower-level native files are all locateable. So `deactivate`ing your conda env means your `python` might not be able to find everything provided by conda.

My recommendation, especially on windows: If you're using conda... just use conda until you have to support something not on conda-forge, and you'll save yourself mountains of problems.

```bat
conda activate
conda create -c conda-forge venv python ipython
conda activate venv
ipython
```

If you _really_ want to use pip to get everything _except_ `pip` and `python` (and `sqlite` and `tk`...)

```bat
conda activate
conda create venv python pip
conda activate venv
python -m pip install ipython
ipython
```

Once you start mixing them, though: you never _quite_ know what you're going to get, as there is less metadata coordination between the two systems than you might hope after a decade.

At any rate, this probably isn't an ipython problem (plain `python -c 'import sqlite3'` wouldn't work either), and would encourage you to close this one out!

**Comment by waszil** [comment]
Ok, I see, thank you.
