### ISSUE TITLE
'IPython.utils.io' has no attribute 'IOStream'

### ISSUE THREAD

**Issue by UniqASL** [ipython/ipython#13576]
Hi,

I'm using Python 3.9.10 with the last version of IPython (8.1.1) and I get the following error:

> IPython could not be loaded: module 'IPython.utils.io' has no attribute 'IOStream'

When downgrading IPython to 7.32.0 the error disappears and IPython loads properly. Any idea on this issue?

Thanks in advance.

**Comment by MrMino** [comment]
Hi @UniqASL 

Is this error happening during startup? Which operating system are you using?

Please provide the full console output of it, including the whole traceback.

**Comment by UniqASL** [comment]
Hi @MrMino 

Thanks for the reply.

Yes the error occurs when starting a new python shell in Pyzo 4.12.0. My OS is Windows 10.

This is the entire output of the console:

> Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:22:07) on Windows (64 bits).
This is the Pyzo interpreter with integrated event loop for PYQT5.
IPython could not be loaded: module 'IPython.utils.io' has no attribute 'IOStream'
Type 'help' for help, type '?' for a list of *magic* commands.

**Comment by MrMino** [comment]
@UniqASL could you please try to open IPython via cmd and check whether it throws an exception there too? If it does, please attach the whole traceback here.

**Comment by UniqASL** [comment]
@MrMino, running IPython in cmd actually works. No error there. Does the error comes from Pyzo then?

**Comment by Carreau** [comment]
IOStream has been deprecated since IPython 6 (2017), this is a problem with pyzo  (https://github.com/pyzo/pyzo) that still uses them: https://github.com/pyzo/pyzo/blob/18a7d905764dfe6145a5eed12ad3ec0976390905/pyzo/pyzokernel/interpreter.py#L597-L599

Nothing we can do here, you will need to ask to pyzo.

**Comment by UniqASL** [comment]
Ok, thanks a lot for the assistance!
