### ISSUE TITLE
Add Cell ID for Events

### ISSUE THREAD

**Issue by mlucool** [ipython/ipython#13579]
Given the [cell-id JEP](https://jupyter.org/enhancement-proposals/62-cell-id/cell-id.html), it would be helpful to get the cell id in the relevant [IPython event](https://ipython.readthedocs.io/en/stable/config/callbacks.html) callbacks.

As an example use case, I have a `post_run_cell` callback that I want to only take an action when it's called the first time it sees a given cell.

Is this possible? Any reason not to?

**Comment by Carreau** [comment]
Hum I'm not even sure the cell id are currently sent to the kernel I'll check.

**Comment by bollwyvl** [comment]
We've been relying on them down stream for a while:

https://github.com/robots-from-jupyter/robotkernel/blob/master/src/robotkernel/kernel.py#L204

**Comment by Carreau** [comment]
With #13600 and ipython/ipykernel#886 it should be take care of. Will be released at end of month in ipython 8.3
