### ISSUE TITLE
"from IPython.display import update_display" Issue

### ISSUE THREAD

**Issue by spf255** [ipython/ipython#13578]
I have been running a script that calls the `IPython.display` `update_display` function through the `pycaret` library. This works fine when I'm running the script in a Cloudera Data Science Workbench (CDSW) Jupyter session. I now want to schedule this script as a CDSW job, but when I try to run this in a command line session in CDSW (using the same libraries), I receive the error that I can't import the `update_display` function. Any ideas why this doesn't work?

`from pycaret.anomaly import *`

Results:
```
ImportError: cannot import name 'update_display'
ImportError                               Traceback (most recent call last)
in engine
----> 1 from pycaret.anomaly import *

/home/cdsw/.local/lib/python3.6/site-packages/pycaret/anomaly.py in <module>()
      9 import warnings
     10 from pycaret.internal.logging import get_logger
---> 11 from pycaret.internal.Display import Display, is_in_colab, enable_colab
     12 import pandas as pd
     13 import numpy as np

/home/cdsw/.local/lib/python3.6/site-packages/pycaret/internal/Display.py in <module>()
      7 import ipywidgets as ipw
      8 from IPython import get_ipython
----> 9 from IPython.display import display, HTML, clear_output, update_display
     10 from typing import Optional, List, Dict, Any
     11 from pycaret.utils import enable_colab

ImportError: cannot import name 'update_display'
```

**Comment by Carreau** [comment]
check the version of IPython 
something like 


```
import IPython
IPython.version_info
```

it may be you don't have the same version of IPython

**Comment by spf255** [comment]
Thanks, @Carreau!

After digging, I found that it's using `IPython` (v. 7.16.3) in this directory when working in Jupyter Notebook:

`/home/cdsw/.local/lib/python3.6/site-packages/IPython/`

And it's using `IPython` (v. 5.1.0) in this directory when working in the command line:

`/var/lib/cdsw/python3-engine-deps/lib/python3.6/site-packages/IPython/`

Since these are being called from the `pycaret` library, I'll have to request our CDSW administrator to update the default package.
