### ISSUE TITLE
%paste + history

### ISSUE THREAD

**Issue by mlucool** [ipython/ipython#13585]
From a user point of view, it seem like `%paste` should not store itself in IPython's history, but instead store the text that was pasted. It seems unlikely that a user will want to use history to get to paste again over get to the thing that was pasted.

![ipython-paste](https://user-images.githubusercontent.com/1813603/157872550-0ea6043c-c844-4e5e-b499-9cfe3e0c5ea9.gif)

**Comment by Carreau** [comment]
That looks reasonable.

It seem like prompt_toolkit is keeping it's own history of what have been typed, so there might be multiple fixes needed.

**Comment by haridsv** [comment]
Shouldn't this be configurable? I for one liked the prior behavior. I mosty paste long arbitrary code that has no relevance for future uses but now having to deal with the issue of seeing this text in the history, besides recalling older items by going through such multiline items is painful as both up arrow and Ctrl+P go line by line when it is multiline items.

**Comment by haridsv** [comment]
BTW, I find it extremely hard to navigate through history once a long multiline entry gets in. On Mac with iTerm, PageUp and PageDown work against the iTerm buffer and Ctrl+Up and Ctrl+Down are used by mission control by default, so the only shortcuts usable by default are Ctrl+P and Ctrl+N and these also go the previous/next line when there are multiple lines so it becomes extremely tedious to use them to navigate. I have for now disabled the mission control shortcuts so that I can use Ctrl+Up and Ctrl+Down for navigating the history.

**Comment by Carreau** [comment]
> On Mac with iTerm, PageUp and PageDown work against the iTerm buffer

For me Fn-Up/Down (which are I guess PgUp/PgDown) navigate history, and Fn-Ctrl-Up/Down control the iterm buffer.

**Comment by haridsv** [comment]
> For me Fn-Up/Down (which are I guess PgUp/PgDown) navigate history, and Fn-Ctrl-Up/Down control the iterm buffer.

For the later set does nothing and I don't think I ever tweaked these shortcuts in iTerm2.

**Comment by javidcf** [comment]
Please consider making this a configurable option. I did find the previous behaviour far more convenient. I frequently experiment with an open IPython console pasting different variations of a piece of code time and again - before I could just repeat the last command, now I have to write `%paste` again and again. Also, as has been mentioned, traversing a history with multi-line entries is slow as, at least in my current Windows setup, it can only be navigated line by line.

**Comment by victorbs** [comment]
Yes. I would really appreciate if this was a configurable option. Having %paste in my history was very useful to me.

**Comment by Carreau** [comment]
Feel free to send a PR.
