### ISSUE TITLE
Lite Youtube Embed

### ISSUE THREAD

**Issue by psychemedia** [ipython/ipython#13583]
Via @simonw, I note https://github.com/paulirish/lite-youtube-embed , a web component that improves performance for loading and rendering Youtube videos.

The current `YouTubeVideo` class just seems to use an IFrame, so this approach might improve performance albeit at the cost of adding a dependency.

https://github.com/ipython/ipython/blob/9065df747f265f02502866869f329c1ccdf9e58d/IPython/lib/display.py#L301

**Comment by MrMino** [comment]
I personally am against adding a dependency like this to the IPython itself. If someone needs this then it can be created as a separate package (e.g. using something akin to [`ipywidgets`](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Custom.html)).

From what I can tell, adding this dependency would be complicated and difficult to maintain.
