### ISSUE TITLE
Too many calls to __getitem__ in dict subclass

### ISSUE THREAD

**Issue by nixjdm** [ipython/ipython#13597]
I think I have a bug in ipython (but not totally sure) where if you subclass `dict` and have `__getitem__` return an instance of the subclass, then this class's `__getitem__` method is called too many times. This can be seen with the following code's prints. Note, the actual return value is correct. It seems like the extra time `__getitem__` is false-called, that result is thrown away.

This code is a crude/incomplete way to get deep items out of a dict by passing in a list of keys to traverse, via a subclass. The code that gives the extra prints specifically returns an instance of the subclass. I tried to strip this down to just what would reproduce the issue, so it's a bit wonky on its own, but does reproduce the possible bug.

Note this is definitely seems to be an interaction with subclassing the builtin `dict`, since we don't see the behavior if we subclass`UserDict`, **_but_**, the code shows the expected prints with the normal python repl, which makes me think this is really a bug in ipython.

Since the extra prints appear, I'd also trust the results of things like `%time` less.

See this example in ipython. Note 

- [1] subclasses dict, and doesn't return an instance of the subclass. No issue.
- [2] subclasses dict, and returns an instance of the subclass. Extra print.
- [3] subclasses UserDict, and returns an instance of the subclass. No issue.

```
$ ipython
Python 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.1.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import operator
   ...: from functools import reduce
   ...: class Test(dict):
   ...:     def __getitem__(self, key):
   ...:         print("!", key)
   ...:         if isinstance(key, str):
   ...:             return super().__getitem__(key)
   ...:         return reduce(operator.getitem, key, self)
   ...: dct = {'a': {'b': {"c": "d"}}}
   ...: Test(dct)['a', 'b']
! ('a', 'b')
! a
Out[1]: {'c': 'd'}

In [2]: import operator
   ...: from functools import reduce
   ...: class Test(dict):
   ...:     def __getitem__(self, key):
   ...:         print("!", key)
   ...:         if isinstance(key, str):
   ...:             return super().__getitem__(key)
   ...:         return Test(reduce(operator.getitem, key, self))
   ...: dct = {'a': {'b': {"c": "d"}}}
   ...: Test(dct)['a', 'b']
! ('a', 'b')
! a
Out[2]: ! c
{'c': 'd'}

In [3]: import operator
   ...: from functools import reduce
   ...: from collections import UserDict
   ...: class Test(UserDict):
   ...:     def __getitem__(self, key):
   ...:         print("!", key)
   ...:         if isinstance(key, str):
   ...:             return super().__getitem__(key)
   ...:         return Test(reduce(operator.getitem, key, self))
   ...: dct = {'a': {'b': {"c": "d"}}}
   ...: Test(dct)['a', 'b']
! ('a', 'b')
! a
Out[3]: {'c': 'd'}
```

And in the normal python repl, showing no extra prints anywhere, the suspect code:

```
$ python
Python 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import operator
>>> from functools import reduce
>>> class Test(dict):
...     def __getitem__(self, key):
...         print("!", key)
...         if isinstance(key, str):
...             return super().__getitem__(key)
...         return reduce(operator.getitem, key, self)
... 
>>> dct = {'a': {'b': {"c": "d"}}}
>>> Test(dct)['a', 'b']
! ('a', 'b')
! a
{'c': 'd'}
>>> class Test(dict):
...     def __getitem__(self, key):
...         print("!", key)
...         if isinstance(key, str):
...             return super().__getitem__(key)
...         return Test(reduce(operator.getitem, key, self))
... 
>>> Test(dct)['a', 'b']
! ('a', 'b')
! a
{'c': 'd'}
>>>
```

**Comment by MrMino** [comment]
The extra print comes from IPython's pretty-printer fetching the keys of a dict it tries to show in the output. It uses `__getitem__` directly instead of using `dict.__repr__`, but overall the amount of dictionary lookups is the same, it's just that with the default `__repr__` the lookup is done in C code.

![image](https://user-images.githubusercontent.com/6691643/161645478-afc4fd5b-3950-4ab9-8552-d76dba286eec.png)

You can easily see where the calls come from by using a debugger in your `__getitem__`:
```
import operator
from functools import reduce
class Test(dict):
    def __getitem__(self, key):
        import pdb; pdb.set_trace()
        if isinstance(key, str):
            return super().__getitem__(key)
        return Test(reduce(operator.getitem, key, self))
dct = {'a': {'b': {"c": "d"}}}
Test(dct)['a', 'b']
```
