### ISSUE TITLE
Hi. I think the issue is still existing. On my side I manage to reproduce the issue with click library. The minimal code snippet is below.

### ISSUE THREAD

**Issue by andrijana-lebesgue** [ipython/ipython#13609]
Having the same issue as below
(_Originally posted by @swan001 in https://github.com/ipython/ipython/issues/12831#issuecomment-981716440_)

Hi. I think the issue is still existing. On my side I manage to reproduce the issue with click library. The minimal code snippet is below.

```python
import click

@click.command()
@click.option('--nb_files', type=int, help='number of files to load')
def execute_job(nb_files):
    print('hello world', nb_files)
    return nb_files

if __name__ == '__main__':
    execute_job()
```

Then executed in IPython with the following argugments:
```shell
--nb_files 20
```
I encounter the issue with IPython version 7.22.0 , on Databricks platform using a "Python" job (actions with them are also ongoing).

Should we create a different issue for this one in case this is specific to click? Let me know. Thanks.

**Comment by MrMino** [comment]
We can reopen the other issue. I didn't see it because of all of the notifications I get from all of the different projects, you might want to @MrMino me in the future.
