### ISSUE TITLE
Incorrect input code cell line number

### ISSUE THREAD

**Issue by jdtsmith** [ipython/ipython#13608]
PR #13535 implemented line numbers in the <module> name for multi-line input, as a workaround for a debugpy issue with Python 3.10.  It does not function correctly with iPython 8.1.1, always mentioning line 1 no matter what line the error occurred on:

```python
In [1]: if True:
   ...:     x=1
   ...:     y=2
   ...:     z=1/0
   ...: 
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
Input In [1], in <cell line: 1>()
      2 x=1
      3 y=2
----> 4 z=1/0

ZeroDivisionError: division by zero
```

In addition, PR #13560 restores line numbers for all tracebacks, including syntax errors etc. (that do not pass the compilation stage).  This would make the line numbers listed in the `<cell line: 123>` superfluous, even if correct.

**Comment by jdtsmith** [comment]
Closing as this will be rendered irrelevant once #13560 is merged.

**Comment by SneshaAP** [comment]
ValueError                                Traceback (most recent call last)
[<ipython-input-83-e4e7ade8fa45>](https://localhost:8080/#) in <cell line: 1>()
----> 1 assess_model(model=LogisticRegression())

7 frames
[/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py](https://localhost:8080/#) in __array__(self, dtype, copy)
   2151     ) -> np.ndarray:
   2152         values = self._values
-> 2153         arr = np.asarray(values, dtype=dtype)
   2154         if (
   2155             astype_is_view(values.dtype, arr.dtype)

ValueError: could not convert string to float: 'D00-ENG'
