### ISSUE TITLE
Transformer for `pinfo` line magic incorrectly sets next input when the line contains parentheses

### ISSUE THREAD

**Issue by krassowski** [ipython/ipython#13602]
In JupyterLab we experience an annoyance with pinfo magic which results in some expressions creating a new cell instead of providing help (https://github.com/jupyterlab/jupyterlab/issues/12269). The following example creates extra cells:

```python
sum([1]).denominator?
```

or:

```
y = lambda x: int?
```

While the direct call to `pinfo` line magic, or to underlying `_inspect` method does not have such an effect:

```python
?sum([1]).denominator
```

```python
%pinfo sum([1]).denominator
```

```python
ipython._inspect('pinfo', 'sum([1]).denominator?')
```

```python
get_ipython().run_line_magic('pinfo', 'sum([1]).denominator?')
```

![extra-cells](https://user-images.githubusercontent.com/5832902/159914796-e8b05f77-c368-4df4-b665-226dbd8ebaaa.gif)

This was narrowed down to a special construct in the input transformer which for some reason wants to set next input in case if the `?` is placed mid-command:

https://github.com/ipython/ipython/blob/0c5563497fe94a8a24ec88912433959908f2506e/IPython/core/inputtransformer.py#L196-L210

identically in transformer2:

https://github.com/ipython/ipython/blob/0c5563497fe94a8a24ec88912433959908f2506e/IPython/core/inputtransformer2.py#L328-L342

This code existed like that since 2012 when it was introduced during magics and splitter refactoring in https://github.com/ipython/ipython/commit/3f192dc6a1873b0d2e5345fc475ffab0fa403466. Interestingly the commit is titled `Remove next_input nonsense in magic calls (but keep functionality).`.

Now, the `set_next_input` will only get introduced if `next_input` is given which gets decided in `help_end` utility:

https://github.com/ipython/ipython/blob/0c5563497fe94a8a24ec88912433959908f2506e/IPython/core/inputtransformer.py#L342-L355

which also happens in transformer2:

https://github.com/ipython/ipython/blob/0c5563497fe94a8a24ec88912433959908f2506e/IPython/core/inputtransformer2.py#L468-L487

What follows:
- I do not see any use-case for the `next_input` to be ever returned. Can we remove it, or am I missing something?
- regardless, the regular expression `_help_end_re` disallows parentheses, only allows strings like `\w+(\.\w+)*` thus it thinks (possibly incorrectly) that it should set the next input to `sum([1]).denominator`; in more detail, the `_help_end_re.search` does not capture the `sum([])` part, and only captures `denominator?` which is different from `line.strip()` therefore `line.rstrip('?')` is assigned as `next_input`. Can we modify the regular expression to allow for parens, brackets and others?
- in `inputtransformer2` a syntax error will be raised when we try to use `DataFrame()?` or `data['key']?, however I would very much like to be able to get help for those as well; this might also require a slight change in the `_ofind` method to allow evaluation of code for pinfo magics (around here https://github.com/ipython/ipython/blob/47ccec77b41b010091ec18a20ff7d2bedcc674da/IPython/core/interactiveshell.py#L1525-L1527 where exception for other magics is already present)

**Comment by Carreau** [comment]
I think the reason for set_next_input is/was for the terminal as you can't (couldn't) easily edit your previous entry for multiline (which is now untrue for prompt toolkit. So I thik we can remove set_next_input.
