### ISSUE TITLE
ModuleNotFoundError: No module named 'IPython.lib.kernel'

### ISSUE THREAD

**Issue by yanone** [ipython/ipython#13610]
I'm trying to run the [wx app example](https://github.com/ipython/ipykernel/blob/main/examples/embedding/ipkernel_wxapp.py) from `ipykernel` that opens a `qtconsole`.

[This line](https://github.com/ipython/ipykernel/blob/fc51ba4cccbc3b56323f9fc75f0ba631916812d9/examples/embedding/internal_ipkernel.py#L7) causes a `ModuleNotFoundError`, and indeed, I cannot find such code in _IPython/lib_ myself. What happened to it? Did it move? Did it disappear?

I'm posting this here instead of _ipykernel_ because the import points to it.
Many thanks.

**Comment by MrMino** [comment]
That line is 11 years old.

![image](https://user-images.githubusercontent.com/6691643/160643281-30c80bc8-f180-4244-9382-42e7df950152.png)

Difficult to tell what happened to this callable, the string `connect_qtconsole` is not in the current tree.

**Comment by MrMino** [comment]
I'm going to assume that this will fix it. Otherwise please report an issue in the ipykernel tracker.
