### ISSUE TITLE
Using SQL Magics not able to connect to database

### ISSUE THREAD

**Issue by Kajalagg98** [ipython/ipython#13632]
When using the ipython module to connect to Oracle database, i.e.,

# loads the SQL magic extensions
%load_ext sql
# Connect to Oracle
%sql oracle+cx_oracle://username:password@host:port/?service_name=service

I am getting the following error:
__init__() got an unexpected keyword argument 'bind'
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

The format I am using is correct because the same format is working in a standalone sample (without use of sql magic).

**Comment by MrMino** [comment]
Please file this issue in `ipython-sql` issue tracker: https://github.com/catherinedevlin/ipython-sql
