### ISSUE TITLE
add warning about Enum in autoreload caveats

### ISSUE THREAD

**Issue by ethanfurman** [ipython/ipython#13651]
The warnings at

    https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html

do not mention the issues with reloading modules with enums:

- `Enum` and `Flag` are compared by identity (`is`, even if `==` is used (similarly to `None`))
- reloading a module, or importing the same module by a different name, creates new enums (look the same, but are not the same)

**Comment by Abdullium** [comment]
Wanna assign this to me 
i'll fix it

**Comment by sreenath-tm** [comment]
I'm interested in contributing to this issue, so before I start working it, would you mind sparing your time explaining what the fix will be like and pointing me to some resources to get started.
