### ISSUE TITLE
`auto_match` slow and hogs CPU in some cases

### ISSUE THREAD

**Issue by infokiller** [ipython/ipython#13654]
To reproduce in IPython 8.2, paste `function_with_long_nameeee('arg`, and add the closing quotes at the end.
The slowness increases when the prefix is longer (in this case dominated by the function name `function_with_long_nameeee`), so if you don't notice it, try increasing it).

## Steps to reproduce with docker

1. Build the image and start a container:

```sh
build_oci_img() {
  docker build "$@" - <<EOF
  FROM python:3.8-slim
  RUN pip install ipython==8.2
EOF
}

build_oci_img
docker run --rm --interactive --tty "$(build_oci_img -q)" ipython -i -c 'get_ipython().auto_match = True'

```

2. Paste `function_with_long_nameeee('arg` and then type another `'` (single quote)

**Comment by infokiller** [comment]
Just tested 8.3 and I see the same behavior

**Comment by MrMino** [comment]
Oh my, the lag. It hurts.

For anyone reproducing: make sure to `get_ipython().auto_match = True` first.

**Comment by infokiller** [comment]
Thanks, I can confirm this is fixed with the following modification to the original steps:

```sh
build_oci_img() {
  docker build "$@" - <<EOF
  FROM python:3.8-slim
  RUN apt-get update -y && apt-get install -y git
  RUN pip install git+https://github.com/ipython/ipython.git
  RUN ipython --version
EOF
}

build_oci_img
docker run --rm --interactive --tty "$(build_oci_img -q)" ipython -i -c 'get_ipython().auto_match = True'
```
