### ISSUE TITLE
Wait for an async function in IPython

### ISSUE THREAD

**Issue by mlucool** [ipython/ipython#13670]
Hi,

The following works in python, but not IPython due to "This event loop is already running":
```
import asyncio

class Foo:
    def bar(self):
        loop = asyncio.get_event_loop()
        # I want this to wait as long as it needs to and return 2
        val = loop.run_until_complete(self.baz())
        return val

    async def baz(self):
        await asyncio.sleep(0.1)
        return 2


print(Foo().bar())
```

Is this possible to do in IPython? On a high level, I want to hide that some code is async by internally forcing it to be sync to the caller in IPython (the caller in my real use case is `_ipython_display_` which can't await for content AFAIK).

**Comment by MrMino** [comment]
I don't think this is possible without turning many UI features of IPython off, or using separate event loop in a separate thread. IPython is built on prompt-toolkit which runs on asyncio.

But why do you need to run an event loop from within that class? Event loops are (as of writing this at least) global for each thread. Doing this from a class that isn't your main component is a bad practice design-wise.

You might want to look at [`asyncio.get_running_loop()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_running_loop) instead.

**Comment by mlucool** [comment]
Replacing `get_event_loop` with [get_running_loop()](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_running_loop) or [asyncio.new_event_loop()](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_running_loop) leads to `RuntimeError: This event loop is already running` and  `RuntimeError: Cannot run the event loop while another loop is running`.


Maybe I should ask a more general question here - if I have an async function, how can I use it in `_ipython_display_`?

**Comment by MrMino** [comment]
Scratch that, I have a memory of IPython running prompt-toolkit via asyncio, but that's not always true, or I might've mistaken it with something. I might need to brush up on that part of the codebase.

In any case, if you have an event loop object, you can add coroutines to it using [`loop.call_soon(...)`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.call_soon) and other scheduling subroutines.

**Comment by MrMino** [comment]
I'm going to assume that the above fixes the issue you had. If not - let me know - I'll reopen the issue.

**Comment by Carreau** [comment]
You can try to use https://pypi.org/project/nest-asyncio/, but yes, the nesting of eventloop because ipykernel uses  asyncio is in general a problem.
