### ISSUE TITLE
can't import locust in ipython

### ISSUE THREAD

**Issue by adaaaaaa** [ipython/ipython#13676]
ipython:8.3.0
ipykernel:6.13.0
python:3.10.4

**Comment by bollwyvl** [comment]
This would require a much clearer description of the problem, and probably your goals: having used [locust](https://github.com/locustio/locust) some, it relies on gevent, and is therefore not compatible with the asyncio-style event loop used in ipython, and is unlikely to be fixable. This is mirrored by the duplicate post over here: https://github.com/locustio/locust/issues/2098
