### ISSUE TITLE
supposed typo in function symbol name

### ISSUE THREAD

**Issue by AlexanderStohr** [ipython/ipython#13703]
https://github.com/ipython/ipython/blob/f20e3b80393a1a5909a050cb7bb9cbce9e044827/IPython/core/tests/test_displayhook.py#L31
and also line 44

Did you mean...
overbite,
overrate,
override,
overripe,
overwrite

**Comment by roansong** [comment]
That does look like it should be 

```python
def test_underscore_no_overwrite_user(): 
```

**Comment by MrMino** [comment]
If anyone would like to test out making PRs - feel free to fix that typo :).
