### ISSUE TITLE
Suggestion: 'undeprecate' extensions

### ISSUE THREAD

**Issue by DemonikGH** [ipython/ipython#13722]
I can't think of a single reason why it is deprecated. Python package management is really bad to rely on pip, packing small personal customization extensions is a massive overkill and can lead to potential pip conflicts in the future and publishing it is a horrendous waste of time (and might not even be possible in some cases). Extensions folder was perfect for very simple personal extensions and now using it constantly shows warnings that can't be disabled. Startup scripts aren't a good alternative because they clutter globals space and trying to do something without putting anything into globals leads to extremely ugly code in startup scripts.

**Comment by Carreau** [comment]
I think it's pretty easy even locally to create/install a package without publishing it.
For example using https://flit.pypa.io/en/latest/. You don't even have to use pip for that. 

We'll try to do better with the docs, and better deprecation with `install_ext`

**Comment by Carreau** [comment]
Thanks you for reminding me to remove `install_ext` and the ability to load extensions from `~/.ipython/extensions` this will be taken care of by #13744. It will also remove the part of the documentation that mention this folder.


I invite you to re-read the documentation carefully, in particular the "and can be placed anywhere you’d normally import from" section. I will remind you of [PYTHONPATH](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH) and suggest `export PYTHONPATH=PYTHONPATH:~/.ipython/extensions`.

You should really learn about to python package management. It is for sure not perfect, but you seem to have not really looked at it in a long time.
