### ISSUE TITLE
Improving dict autocomplete

### ISSUE THREAD

**Issue by mlucool** [ipython/ipython#13735]
We have found the dict autocomplete to show too many option at times. As an example, given this:
```
$ ls
a-dir-name  a-file
$ ipython
```

The following is appears:
![image](https://user-images.githubusercontent.com/1813603/185985402-5e2b2aa4-68c2-4c99-826b-b3cd9539c8c9.png)

Here you can see a number of things are suggested that are not helpful including:
1. Files
2. Magics

This is made much worse by something like [pyflyby](https://github.com/deshaw/pyflyby) where all possible imports that start with `a` are also listed.

Ideas:
1. Only show valid keys of the dict (when possible)
2. Sort to show dict keys first and all other options after

**Comment by krassowski** [comment]
This is similar to a previous request to only show magics after `%` (https://github.com/ipython/ipython/issues/12959) which was solved by a simple check for `%` prefix in https://github.com/ipython/ipython/pull/13483. I was recently thinking about adding more capabilities to matchers in backward compatible way (https://github.com/ipython/ipython/issues/12820).

On high level, the solution can be implemented by (expanding upon ideas proposed above):
1. adding a method to check whether all other matchers should be suppressed. If two or more matchers say "suppress all other matchers", then we could take the union of completions from those.
2. adding `priority`/`rank` to each matcher or each completion item to be used for sorting (or `sort_text` if following LSP; this appears sub-optimal though and we can always convert to `sortText` downstream from a numeric rank)

**Comment by krassowski** [comment]
On implementation level, approach (A):

(1) Suppressing can be performed as a matcher-level function. Matcher would start to resemble a proper class with methods (not just a function). We could introduce this while maintaining backward-compatibility by adding an optional `should_suppress_others` method via a decorator. The new `Matcher` could be typed as follows:

```python
class LegacyMatcher(Protocol):
    __call__: Callable[[str], list[str]]


class MatcherSupressionProtocol(Protocol):
    should_suppress_others: Callable[[str], bool]


Matcher = Union[LegacyMatcher, MatcherSupressionProtocol]
```

(2) Currently sorting is governed by hard-coded [`completions_sorting_key`](https://github.com/ipython/ipython/blob/7f51a0332edd0c675c2d314ca3e62df7ef041281/IPython/core/completer.py#L304-L333); it would be difficult to recognise a dictionary key using this existing approach alone.

Matcher-level priority/rank could be a solution if it took the request text in and return a number depending on situation (here answering "how likely it seems that we are in a dict"):

```python
class MatcherPrioritySystemDynamic(Protocol):
    priority: Callable[[str], float]

Matcher = Union[LegacyMatcher, MatcherSupressionProtocol, MatcherPrioritySystemDynamic]
```

**Comment by krassowski** [comment]
Completion-level priority/rank would enable more granular control for matcher developers and could expand the API proposed in my [earlier comment](https://github.com/ipython/ipython/issues/12820#issuecomment-1222788271):

```python
class SimpleCompletion(NamedTuple):
    text: str
    origin: Optional[str]
    type: Optional[str]
    priority: Optional[float]
    

class LegacyMatcher(Protocol):
     __call__: Callable[[str], Union[list[str], list[SimpleCompletion]]]
```

However, what follows from my comment above is an observation that the information about priority and suppression is context-specific; therefore, maybe we should reconsider...

**Approach (B)**: matchers are just simple functions, but return an extensible structure with metadata. In this scenario matchers would be comply with following typing:

```python
class MatchingResult(TypedDict):
    matches: list[SimpleCompletion]
    suppress_others: NotRequired[bool]
    priority: NotRequired[float]

LegacyMatcher = Callable[[str], list[str]]
NewMatcher = Callable[[str], MatchingResult]   # TODO: find better code name
Matcher = Union[LegacyMatcher, NewMatcher]
```

> Using `TypedDict` + `NotRequired`, or `Protocol` corresponds to implementation which will require duck typing or key checking respectively but will allow us to add more properties in the future without breaking compatibility.

**Comment by mlucool** [comment]
@krassowski, thanks for the work here. A few pieces of feedback:
1. This does not handle dicts with depth > 1:
![image](https://user-images.githubusercontent.com/1813603/200403509-d8711cc3-faad-4559-8135-374689c1148e.png)

2. As a nice to have, when you select a value, it should complete the `"]` as well so that I can just push enter:
![image](https://user-images.githubusercontent.com/1813603/200403743-abcc47a3-fbb9-40c3-9e24-e158119756f7.png)
