### ISSUE TITLE
display.HTML() data parameter does not accept bytes

### ISSUE THREAD

**Issue by eyaler** [ipython/ipython#13770]
docs say that data passed to display.HTML can be bytes but this breaks with:
```
[/usr/local/lib/python3.7/dist-packages/IPython/core/display.py](https://localhost:8080/#) in warn()
    696             prefix = data[:10].lower()
    697             suffix = data[-10:].lower()
--> 698             return prefix.startswith("<iframe ") and suffix.endswith("</iframe>")
    699 
    700         if warn():

TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by ChandanChainani** [comment]
@eyaler please can you share the steps to reproduce the bug

**Comment by eyaler** [comment]
@ChandanChainani 
```
from IPython.display import HTML
HTML('works')
HTML(b'crashes')
```

**Comment by ChandanChainani** [comment]
@eyaler It seem the document is incorrect because `TextDisplayObject` class add a check to only allow string type which can be checked [here](https://github.com/ipython/ipython/blob/dc08a337f568ce179a88b83fdcf6ebb4158dfdb5/IPython/core/display.py#L393-L395)
