### ISSUE TITLE
Support for question mark (?) for objects part of list

### ISSUE THREAD

**Issue by nishikantparmariam** [ipython/ipython#13780]
**Consider this reproducer** 

```python
class B:
    
    @property
    def foo(self):
        """
        Documentation for Foo
        """
        return self._foo
    
    @foo.setter
    def foo(self, v):
        self._foo = v
        
    def some_method(self):
        """
        Documentation for some method
        """
        pass

class A:
    
    def __init__(self):
        self.b = [B(), B()]
        
a = A()

```
Now doing 

```python
a.b[0].some_method?
```
or
```python
a.b[1].foo?
```

Does not seem show docstring, instead it says `Object ``Foo`` not found` 

**Context**

We are developing a Python library (class) that holds objects in a list. The objects have methods and properties defined on them which does not seem to show help as per the above snippet. It would be really useful if users can quickly access documentation.

In general, the object on which property or method is requested may be present in `dict` e.g.  `a.b['key'].foo?` or it may be coming from a function `a().foo?` - in these cases as well we get the same error. Though if only simple list case works, it would suffice for us.

We are aware that this works - 

```python
temp = a.b[0]
temp.foo?
```
It would be great if it works without needing to put into a variable first.

**Relevant Code Sections**
https://github.com/ipython/ipython/blob/ae0dfcd9d4fb221f0278f07b022f9837b0e51e67/IPython/core/magics/basic.py#L298-L303
https://github.com/ipython/ipython/blob/57eaa12cb50c9a95213b9e155032e400b9424871/IPython/core/interactiveshell.py#L1532-L1544

Open for suggestions / workarounds!

**Comment by Carreau** [comment]
That should be doable, though we try to avoid poking at things that might trigger side effects, like getindex. 

We have to consider also that `?` is not an operator and need to do some code transform on the code when it is still in a string for to make `?` works. That is to say 

```
temp.foo?
```

Get actually transformed into:

```
%pinfo temp.foo
```

Which itself get transformed into `get_ipython().run_line_magic('pinfo', 'temp.foo')`

And that will likely not support arbitrary python expressions

The code transform and modifying `_ofind` you pointed to to support `[]` with literal should not be too hard, but extending for arbitrary python expression would be much quite a bit more difficult (and dangerous/surprising) as now `?` could execute arbitrary methods.
