### ISSUE TITLE
if self.quitting: raise BdbQuit bdb.BdbQuit

### ISSUE THREAD

**Issue by zoetu** [ipython/ipython#13794]

**Comment by space624** [comment]
Hello ,How did you solve it.

**Comment by zoetu** [comment]
> Hello ,How did you solve it.

No, i haven't.

**Comment by space624** [comment]
Thank you I solved it. After starting the child process, the main process will crash, so we need to set join(1) and hibernate for 1 second. The specific reason has not been found
