### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Hemanthkumarvajjala** [ipython/ipython#13792]
linear_model=smf.ols('pf~rd+as+ms',data=data_50,return_type='dataframe').fit()

Traceback (most recent call last):

  File ~\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3369 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Input In [62] in <cell line: 1>
    linear_model=smf.ols('pf~rd+as+ms',data=data_50,return_type='dataframe').fit()

  File ~\anaconda3\lib\site-packages\statsmodels\base\model.py:200 in from_formula
    tmp = handle_formula_data(data, None, formula, depth=eval_env,

  File ~\anaconda3\lib\site-packages\statsmodels\formula\formulatools.py:63 in handle_formula_data
    result = dmatrices(formula, Y, depth, return_type='dataframe',

  File ~\anaconda3\lib\site-packages\patsy\highlevel.py:309 in dmatrices
    (lhs, rhs) = _do_highlevel_design(formula_like, data, eval_env,

  File ~\anaconda3\lib\site-packages\patsy\highlevel.py:164 in _do_highlevel_design
    design_infos = _try_incr_builders(formula_like, data_iter_maker, eval_env,

  File ~\anaconda3\lib\site-packages\patsy\highlevel.py:66 in _try_incr_builders
    return design_matrix_builders([formula_like.lhs_termlist,

  File ~\anaconda3\lib\site-packages\patsy\build.py:689 in design_matrix_builders
    factor_states = _factors_memorize(all_factors, data_iter_maker, eval_env)

  File ~\anaconda3\lib\site-packages\patsy\build.py:354 in _factors_memorize
    which_pass = factor.memorize_passes_needed(state, eval_env)

  File ~\anaconda3\lib\site-packages\patsy\eval.py:474 in memorize_passes_needed
    subset_names = [name for name in ast_names(self.code)

  File ~\anaconda3\lib\site-packages\patsy\eval.py:474 in <listcomp>
    subset_names = [name for name in ast_names(self.code)

  File ~\anaconda3\lib\site-packages\patsy\eval.py:105 in ast_names
    for node in ast.walk(ast.parse(code)):

  File ~\anaconda3\lib\ast.py:50 in parse
    return compile(source, filename, mode, flags,

  File <unknown>:1
    as
    ^
SyntaxError: invalid syntax

**Comment by Hemanthkumarvajjala** [comment]
Could any one help

**Comment by bollwyvl** [comment]
This looks like a problem in your patsy formula construction, and probably not related to ipython, per se. Have a look at the [patsy documentation](https://patsy.readthedocs.io/en/latest/formulas.html#the-formula-language) and try building your formula up one token at a time.
