### ISSUE TITLE
8.6 completion API and IPCompleter.matchers

### ISSUE THREAD

**Issue by jdtsmith** [ipython/ipython#13826]
Hi @krassowski, I'm not entirely sure if this is a regression, but in the new 8.6 Completion API, the following method of "editing" the dynamically-generated matchers list no longer functions as before:

```python
ip=IPython.get_ipython()

class IPCompleterLight(IPCompleter):
    """A completer without files or (when in pdb) magics."""
    @property
    def matchers(self): #remove file matches
        matchers=super().matchers
        if self.file_matches in matchers:
            matchers.remove(self.file_matches)
        if self._ipb_inPdb and self.magic_matches in matchers:
            matchers.remove(self.magic_matches)
        return(matchers)

completer = ip.Completer
completer.__class__ = IPCompleterLight
```

Before 8.6, this worked to remove file matches and disable magic matches while PDB is active (which, BTW, I would suggest should be done by default; in case you are wondering, the `_ipb_inPdb` boolean gets set externally in my package).  After 8.6 this code no longer works; perhaps `matchers` is being consulted early and the matcher list cached?  However, there appears to be a better way using `disable_matchers` with the new API, so I've switched to that without problem.  

I also noticed that that the matcher names changed from e.g. `file_matches` to `file_matcher` so perhaps it's a more superficial issue.

One other minor comment: it took me some time to figure out what format `disable_matchers` wants, since the matcher _identifier_ is mentioned but never really explained.  A short example in the docstring or docs would be helpful.  E.g. my mode does its own file completion, so:

```python
completer.disable_matchers = ['IPCompleter.file_matcher']  # class name essential
```

**Comment by krassowski** [comment]
@meseeksdev tag tab-completion

**Comment by krassowski** [comment]
@meeseeksDev tag tab-completion

**Comment by krassowski** [comment]
> I also noticed that that the matcher names changed from e.g. `file_matches` to `file_matcher` so perhaps it's a more superficial issue.

Looking at the example, this seems to relevant to the issue you see. The matcher list does not contain `self.file_matches` nor `self.magic_matches` and longer, so when you check:

```python
if self.file_matches in matchers:
    matchers.remove(self.file_matches)
if self._ipb_inPdb and self.magic_matches in matchers:
    matchers.remove(self.magic_matches)
```

the code never enters either of the conditions. It might be hard to catch indeed. The decision to keep `_matches` functions as they were and define new `_matcher` wrappers was intended to preserve the backwards compatibility as much as possible. Does the following work?

```python
if self.file_matcher in matchers:
    matchers.remove(self.file_matcher)
if self._ipb_inPdb and self.magic_matcher in matchers:
    matchers.remove(self.magic_matcher)
```

> One other minor comment: it took me some time to figure out what format `disable_matchers` wants,

Thank you for pointing this out, I opened #13827.

**Comment by jdtsmith** [comment]
> Does the following work?

Thanks.  Yes, this does work. The issue is it's harder to support pre 8.6 and 8.6 now, since the names of the default matchers have changed.  I could look for either flavor, but `disable_matchers` is more straightforward if I simply require >=8.6.  

BTW, the `provisionalcompleter` requirement is unsettling, since the API (v1 anyway) has been in place for >6 years.  Is there a plan for the completion API to _graduate_ from provisional status any time soon?  The hope is not to have to futz with the completion code when new versions appear.

I appreciate your work.  New completions working well.

**Comment by krassowski** [comment]
> Is there a plan for the completion API to graduate from provisional status any time soon?

That's my hope.
