### ISSUE TITLE
Enable Read The Docs PR integration?

### ISSUE THREAD

**Issue by krassowski** [ipython/ipython#13828]
Could we enable the [RTD PR integration](https://docs.readthedocs.io/en/stable/pull-requests.html)? This would make it easier to preview and review the documentation changes.

**Comment by krassowski** [comment]
@Carreau?

**Comment by krassowski** [comment]
This would make reviewing changes to documentation easier. It requires [4 clicks in RTD dashboard](https://docs.readthedocs.io/en/stable/pull-requests.html#configuration).

**Comment by krassowski** [comment]
This would also help catching typos, as those corrected in https://github.com/ipython/ipython/pull/13918

**Comment by bollwyvl** [comment]
+1 to per-PR requests.

> reviewing changes 

Also, beyond just docs, we could relatively humorously offer a jupyterlite site with the package-as-built, as we have done for `ipywidgets`. 

If the "fat" JS console isn't what we want, a positive signal here might put me over the edge for offering a minimal [terminal](https://github.com/jupyterlite/jupyterlite/issues/717) app based on `xtermjs`, which might be a nice experience for folks, if we can figure out how to trick out all the prompts properly (though it would probably still require all the `await` stuff).

> catching typos

I've been applying `hunspell` on some docs sites, and maintain `hunspell` and `hunspell-en` on `conda-forge`. It takes a bit to stand up (_what's an `IPython`?_), and ideally some DOM-based rules to avoid things like autodoc method names, but can be worth it. I generally run it _after_ a docs site is built, against the generated HTML. One can also add an HTML report to the built PR site, and disable the feature on a non-PR build... but sometimes that doesn't make it clear exactly _where_ the unknown word came from.

There is also [`vale`](https://github.com/errata-ai/vale) which i haven't used yet, but presumably could also get built.

One downside is I haven't been able to get the above toolchain to run on windows, but if it's mostly run on CI, that might not be a big deal if it's easy to get to the report out of RTD: indeed, setting up the `pull-request-opened` GitHub Action to link to both the top of the docs site, a lite demo, and any reports, could be solid.

**Comment by Carreau** [comment]
RTD should be re-enabled (if was some time ago, but it broke, so I had to fix it). Happy to have any other docs improvement you wish.

**Comment by bollwyvl** [comment]
RTD reviews are coming up.

I will open a separate issue for the in-browser demo.
