### ISSUE TITLE
Cannot find Changelog / Release notes

### ISSUE THREAD

**Issue by cfra** [ipython/ipython#13824]
Going through the documentation and the repository, I cannot find any changelog/release notes.

Would be great if some reference to their location that is more obvious could be added.

**Comment by krassowski** [comment]
Is https://ipython.readthedocs.io/en/stable/whatsnew/index.html helpful, or are you looking for a more detailed log?

**Comment by cfra** [comment]
Thank you very much, this is more or less what I had been looking for. :+1:

My mental search algorithm was looking for someting like `CHANGELOG` or `RELEASES` or `HISTORY` in both the root directory of the repository and in the last third of the documentations table of contents, so I missed this entry at the second position. :see_no_evil:
