### ISSUE TITLE
"paste -q" cause "session number not unique" error, while "paste" does not

### ISSUE THREAD

**Issue by jackyspy** [ipython/ipython#13835]
Since IPython 8.2, `paste -q` will cause an error `ERROR! Session/line number was not unique in database. History Logging moved to new session xxx`, but `paste` WITHOUT `-q` will NOT. 
Tested with IPython *8.6*, same error ocurred.
I cannot find out what's the problem.

![image](https://user-images.githubusercontent.com/1861185/202857496-db73880b-ee13-4c38-8ac7-0b9f68adc705.png)

**Comment by daducci** [comment]
Same problem here, using IPython 8.7.0
