### ISSUE TITLE
Jedi speed/results/crashing depend on current directory

### ISSUE THREAD

**Issue by jdtsmith** [ipython/ipython#13866]
It would appear that part of Jedi's slowness is related to it _crawling the entire current directory tree_.

For a simple test, I use completions of `astropy.units`, which is part of a substantial package.  Depending on what directory you start from, `_jedi_matches`:

1. Returns results in a about a second (shallow/light directories)
2. Returns same results in 20-30 seconds (deeper/heavier directories)
3. Crashes (very deep/heavy directory like `~/`)

Note this is for the original completion calculation, _not_ the lazy and timeout-guarded type recovery.  So the timeout does not apply.  Jedi version 0.18.2 (though same behavior in 0.18.1).

```python
In [1]: import astropy.units as u
In [2]: x = 5 * u.MJy/u.sr
In [3]: get_ipython().Completer.debug=True
In [19]: cd code    # heavy directory
<snip>
In [20]: %time list(get_ipython().Completer._jedi_matches(7,0,'x.unit.'))
CPU times: user 19.3 s, sys: 3.84 s, total: 23.1 s
Wall time: 23.7 s
Out[20]: 
[<Completion: aliases>,
 <Completion: bases>,
 <Completion: cgs>,
 <Completion: compose>,
 <Completion: decompose>,
 <Completion: EquivalentUnitsList>,
 <Completion: find_equivalent_units>,
 <Completion: in_units>,
 <Completion: is_equivalent>,
 <Completion: is_unity>,
 <Completion: name>,
 <Completion: names>,
 <Completion: physical_type>,
 <Completion: powers>,
 <Completion: scale>,
 <Completion: si>,
 <Completion: to>,
 <Completion: to_string>,
 <Completion: to_system>]

In [21]: cd ~    # Very heavy directory
<snip>
In [22]: %time list(get_ipython().Completer._jedi_matches(7,0,'x.unit.'))
CPU times: user 545 ms, sys: 274 ms, total: 820 ms
Wall time: 861 ms

Out[22]: [<Fake completion object jedi has crashed>]
In [23]: cd code/python/test/  #light directory, just a few files and no subdirs
<snip>
In [24]: %time list(get_ipython().Completer._jedi_matches(7,0,'x.unit.'))
CPU times: user 963 ms, sys: 33.7 ms, total: 997 ms
Wall time: 1.03 s
Out[24]: 
[<Completion: aliases>,
 <Completion: bases>,
 <Completion: cgs>,
 <Completion: compose>,
 <Completion: decompose>,
 <Completion: EquivalentUnitsList>,
 <Completion: find_equivalent_units>,
 <Completion: in_units>,
 <Completion: is_equivalent>,
 <Completion: is_unity>,
 <Completion: name>,
 <Completion: names>,
 <Completion: physical_type>,
 <Completion: powers>,
 <Completion: scale>,
 <Completion: si>,
 <Completion: to>,
 <Completion: to_string>,
 <Completion: to_system>]
```

**Comment by davidhalter** [comment]
I guess we could introduce an option in Jedi to avoid static analysis and only use runtime information. But that would obviously come at the cost of stuff like `foo[0]` not being able to complete.

I'm also a bit confused why it does that much analysis when using only `x.unit.`, which is something that can usually be understood with a simple `dir()` call. So I feel like this is a Jedi issue and should probably be opened there as well.

**Comment by jdtsmith** [comment]
Yeah that confused me too.  Presumably Jedi already knows the type of the object, so it's not clear why it's doing such a deep dive.  I'll open this over at Jedi and link here.

**Comment by davidhalter** [comment]
Jedi 0.19.0 is released and should fix this issue. Can be closed. See also https://github.com/davidhalter/jedi/issues/1899.

**Comment by jdtsmith** [comment]
Great, I can confirm that jedi 0.19 fixes this problem with astropy.units completion.  Thanks for your work on this.
