### ISSUE TITLE
Problems with the new auto suggestion keybindings in #13888

### ISSUE THREAD

**Issue by infmagic2047** [ipython/ipython#13901]
I'm using a git build of IPython and found two problems with autosuggestion related to #13888.

1. In Vi mode, when there is a suggestion displayed, `escape` will only discard the suggestion, but will not enter the Vi normal mode like it usually does. I find it more reasonable if both actions are performed.
2. If I type some words so a suggestion pops up, and then press `left` followed by `right`, there will be one spurious character from the suggestion inserted at the wrong position.

Example (using `|` to indicate cursor position)
```
("123" is the suggestion)
In [1]: a=|123

(after pressing left, the suggestion disappears)
In [1]: a|=

(after pressing right, an extra character 1 is inserted)
In [1]: a1|=
```

**Comment by Carreau** [comment]
Thanks for testing and the quick bug report ! We'll try to fix that quickly.

**Comment by Carreau** [comment]
I would appreciate if you could try #13902 and let me know if you find issues with it.
