### ISSUE TITLE
jedi crashing on plt.[Tab]

### ISSUE THREAD

**Issue by jdtsmith** [ipython/ipython#13912]
In iPython 8.8.0, Jedi is crashing like:

```python
In [1]: import matplotlib.pyplot as plt
In [2]: plt.Oops Jedi has crashed, please report a bug with the following:
   ...: """
   ...: Ran out of input
   ...: s"""
```

MPL v3.6.3, Jedi v0.18.2

**Comment by krassowski** [comment]
I could not reproduce this on the `main` branch with matplotlib 3.6.3 and jedi 0.18.2 (nor 0.18.1, not matplotlib 3.5.1) on Ubuntu using Python 3.9.5. Could you provide more details on your setup?

**Comment by jdtsmith** [comment]
Just updated to iPython 8.9.0 and the crash persists.    This is on MacOS 12.6:

```
% python3 -m IPython --Completer.debug=True                                                                             
Python 3.10.8 (main, Oct 13 2022, 10:17:43) [Clang 14.0.0 (clang-1400.0.29.102)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.9.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import matplotlib.pyplot as plt

In [2]: plt.plot
             Oops Jedi has crashed, please report a ...
             --jedi/ipython--                          
```

**Comment by jdtsmith** [comment]
OK, well, without any changes in version of MPL, iPython, or Jedi whatsoever, this has stopped crashing.  Perhaps some elusive change in environment vars. Will keep an eye out for recurrence.

**Comment by jdtsmith** [comment]
Well, spoke too soon.  Same exact version.  Let me know if there's further debug info that could be helpful.  See also #13866.  

![image](https://user-images.githubusercontent.com/93749/217660900-5bd5c285-524b-4981-aae0-a388b447d9a9.png)

**Comment by jdtsmith** [comment]
OK I just reinstalled matplotlib (same exact version) and Jedi no longer crashes.  Closing again; will re-open if it recurs.
