### ISSUE TITLE
How to disable the "improvements" to the history up/arrow in the REPL in 8.9.0?

### ISSUE THREAD

**Issue by cottrell** [ipython/ipython#13924]
https://ipython.readthedocs.io/en/stable/whatsnew/version8.html

It seems like now when you type
```python
blah = 123
this = 'that'
```

and then type `b<up arrow` it no longer takes you to the correct line.

Is there some way to achieve same behaviour as before?

It sounds like the improvements are good except anything that touches the user interface.

up should mean up.
enter should mean enter.

Any changes to user interface must be on an opt-in basis.

**Comment by cottrell** [comment]
#13888

**Comment by krassowski** [comment]
Dear @cottrell thank you for the feedback. The workaround to disable the added keybindings is described in https://github.com/ipython/ipython/issues/13878#issuecomment-1409237629 (and comments below). As mentioned in that thread I am working on making this customizable. Should we close this issue to consolidate the discussion in https://github.com/ipython/ipython/issues/13878?

I am sorry that this causes interruptions to the workflow, and I genuinely did not intend for this to be released without the other piece of the work which is making shortcuts customisable (including allowing user to easily decide between the current and previous behaviour).

**Comment by krassowski** [comment]
Close this one to consolidate the discussion in https://github.com/ipython/ipython/issues/13878, in particular please see https://github.com/ipython/ipython/issues/13878#issuecomment-1418296718?
