### ISSUE TITLE
History search / tab completion does not behave as expected.

### ISSUE THREAD

**Issue by aanastasiou** [ipython/ipython#13938]
Hello

I am on ipython 8.9.0, using python 3.11.0. This is a fresh install on a completely clean Ubuntu 22.04, using pyenv as the virtual environment manager. This is a setup that I have used elsewhere without (until now) any need for additional setings.
On (all of) my systems, I always set bash's history navigation to work in [this way](https://stackoverflow.com/questions/3535192/matlab-like-command-history-retrieval-in-unix-command-line) and the same works within ipython without any extra settings.

With the configuration mentioned above, when I start ipython and try to navigate in history, the search works but instead of bringing back the whole line, marking it as "active", it brings back the rest of the line but shaded. For example:

![image](https://user-images.githubusercontent.com/1336337/217814794-ca2e32b7-924a-400d-9433-e7e9bce9e9ba.png)

To "activate" that line, I have to press "End"...which is a bit annoying.

But perhaps more importrantly, tab completion does not work. So, as I stand there looking at that line, taping "Tab" will not make the rest of the line "active" (in the way I described hapenning with the "End" key)

Any ideas what might be going on here? 
(I don't remember if I had the libreadline-dev package installed when I install python 3.11 using pyenv, could this be a factor in this?)

**Comment by csm10495** [comment]
I'm also hitting this on ipython 8.9.0, but for me its on python 3.10.0 and on Mac.

**Comment by csm10495** [comment]
Here is a tiny video showing the issue:
I type "import" then hit tab, instead of completing the recent line, it goes into... guessing?

Uploading Screen Recording 2023-02-09 at 4.53.45 PM.mov…

**Comment by Carreau** [comment]
@csm10495 do you get correct behavior when downgrading to say 8.8.0 ? I think @aanastasiou bug is different. 

@aanastasiou Can you try 8.10 that was released today and may fix some issue with autosuggestions ? Also https://github.com/ipython/ipython/pull/13928 shoudl soon help you to configure keybindings and may help.

**Comment by krassowski** [comment]
> Previous versions would have tab-completed to import click

@csm10495 I see exact same behaviour as on your recording in IPython 7.30. If you wish to see module/package options in the completer add a space after `import ` and before pressing <kbd>tab</kbd>

> But perhaps more importrantly, tab completion does not work. So, as I stand there looking at that line, taping "Tab" will not make the rest of the line "active" (in the way I described hapenning with the "End" key)

@aanastasiou  this is not unexpected in a sense. While there are applications that use <kbd>Tab</kbd> to complete autosuggestions (e.g. MS Word), doing this in IPython would conflict with the standard completer, and that is why we use <kbd>Esc</kbd> (and <kbd>right</kbd>, and <kbd>ctrl</kbd> + <kbd>right</kbd>, etc) - all of this is documented. Ans as we just saw in https://github.com/ipython/ipython/issues/13878 even small changes to default keybinding result in users inundating the issue tracker with (more or less constructive) complaints.

> (I don't remember if I had the libreadline-dev package installed when I install python 3.11 using pyenv, could this be a factor in this?)

No.

**Comment by csm10495** [comment]
I must be confusing myself. The behavior change has to do with the right key not autocompleting anymore.

**Comment by csm10495** [comment]
I guess my issue is described in the release notes: https://ipython.readthedocs.io/en/stable/whatsnew/version8.html

.. kind of disappointed that defaults changed but I guess it is what it is.

**Comment by aanastasiou** [comment]
@Carreau , it did not, but thank you :)

@krassowski, there is no point in me adding to the overall crankiness around this subject :) I will only say however that this has now become a two steps action when previously it was just a straightforward up/down selection.

Can I please ask if at least it is possible to configure iPython to behave like it used to with the new system?

**Comment by krassowski** [comment]
I will only say however that this has now become a two steps action when previously it was just a straightforward up/down selection.
> 
> Can I please ask if at least it is possible to configure iPython to behave like it used to with the new system?

Please see https://github.com/ipython/ipython/issues/13878#issuecomment-1418296718
Your feedback is appreciated!

**Comment by cottrell** [comment]
Rollback will be coming I think. The most interesting thing here is to ponder what is going on at D.E. Shaw that they find use for single character auto-completions. So incredibly terse branching system? Perhaps they are typing in DNA sequences?

**Comment by Carreau** [comment]
Please avoid derogatory comments (implicit or explicit) on other users in general. You may not have meant it, but I think some people can take offense at something like this that looks strongly like sarcasm.

There are many use case for partial completion. I recently had private requests from high-energy physics where filename contain parameters, and thus it makes sens to be partially complete names. I myself would have been using similar things in biophysics during my PhD. Though I originally went for longest common prefix, I can see how this can be not enough. 

There is also a number of use-case where you have dynamic objects that mirror an API in another language, and not all properties are known, in which case you might want to complete shorter sequence than full tokens.


In general as there is usually a release each month I'm not that conservative with defaults, as it is in general impossible to make users discover new features if they are not enabled by default. So we are likely going to iterate on the keybinding, and with the recent work of @krassowski those will be configurable.

**Comment by krassowski** [comment]
I am preparing a PR to document the current behaviour and how to customise it. In the meantime, @aanastasiou @csm10495 would you have an opinion on https://github.com/ipython/ipython/issues/13987 which would add another way to dismiss autosuggestions? Please leave :+1: or :-1: over there :)

**Comment by cottrell** [comment]
I would suggest for all successful projects with large number of users, that changes to defaults should should follow the typical deprecation pattern: warn first for a while (several versions) and tell users how to "act now you are at risk!" kind of thing. I think scipy and pandas follows this kind of approach.

Having a splash warning in the REPL could also be a good way of advertising new REPL features without too much risk or cost to humans on any side of this.

**Comment by krassowski** [comment]
I think that all the questions here were answered. Since there is another issue tracking documentation of user-facing changes to auto-suggestions (https://github.com/ipython/ipython/issues/13979) I will close this issue. Thank you for your contribution to the discussion!

@cottrell I do agree with your suggestion on having a more proactive way of warning users about upcoming changes (in addition to existing practice of opening issues for discussion long before any changes are submitted as PRs and then released). Generating warnings on runtime is arguably a bit easier for APIs where you can just emit a DeprecationWarning (as in pandas) than for UX changes as in IPython.

**Comment by cottrell** [comment]
what is the status on this and when it will be fixed?
