### ISSUE TITLE
`%matplotlib` not working properly with matplotlib 3.7.0 and later

### ISSUE THREAD

**Issue by dnicolodi** [ipython/ipython#13977]
The IPython mainloop integration with matplotlib as initiated with the `%matplotlib` magic does not work as expected.

Using the %matplotlib IPython magic to install the main loop integration and setting interactive mode for matplotlib, and the %run magic to run a script that creates some figures and calls matplotlib.pyplot.show(), the script execution does not terminate until the displayed figures are closed. Once all the figures are closed, the script terminates, but another empty figure pops up.

Using matplotlib 3.6.3, the script is executed and terminates leaving the possibility to interact with the figures.

The issue is due to the hook installed by running `%matplotlib` to run the script invoked with `%run`:  https://github.com/ipython/ipython/blob/e35dbb4e3828d643d7ffd58747350d7c90134706/IPython/core/pylabtools.py#L198-L226

Most likely, something in matplotlib 3.7.0 changed and that code does not work as intended anymore.

If I don't run `%matplotlib` and just invoke `import matplotlib.pyplot as plt; plt.ion()` instead, the issue is not reproduced.

This is the same issue as described in https://github.com/matplotlib/matplotlib/issues/25485 I think the issue is in IPython

**Comment by tacaswell** [comment]
I think this is a collaborative bug and we should probably fix it on the Matplotlib side.  There is some deep coupling and basically private API usage of the other side on both sides, but mpl does not expose public API for the thing than IPython needs here and hacks are now over a decade old so we should fix them.

**Comment by tacaswell** [comment]
Fixed by @dnicolodi on the Matplotlib side via https://github.com/matplotlib/matplotlib/pull/25496
