### ISSUE TITLE
Auto suggestions cannot be completed when in the middle of multi-line input

### ISSUE THREAD

**Issue by lukelbd** [ipython/ipython#13970]
Completing an ipython 8 [autosuggestion](https://ipython.readthedocs.io/en/stable/whatsnew/version8.html#autosuggestions) by pressing `ctrl-f` or `ctrl-e` works perfectly for code on the final line of multi-line input (the following two screenshots show before and after pressing `ctrl-f` or `ctrl-e`):

<img width="357" alt="Screenshot 2023-03-12 at 14 09 48" src="https://user-images.githubusercontent.com/19657652/224570634-fb856132-4b73-46b4-bdf0-576f9601633f.png">

<img width="363" alt="Screenshot 2023-03-12 at 14 10 00" src="https://user-images.githubusercontent.com/19657652/224570647-40ccf5c1-00d6-4d5e-b965-691ca12ffe51.png">

However pressing `ctrl-f` or `ctrl-e` fails when trying to complete the suggestion in the middle of multi-line input -- instead, the only thing that works is holding down right arrow until the suggestion is completed:

<img width="361" alt="Screenshot 2023-03-12 at 14 11 27" src="https://user-images.githubusercontent.com/19657652/224570743-37756db5-989a-46d4-8447-bb23649d7309.png">

Note this problem persists across different terminals (apple Terminal and iTerm2) and after disabling custom `bashrc` and `inputrc`. Is there any way suggestions can be completed with one keystroke in the middle of multi-line input?

**Comment by krassowski** [comment]
Thank you for the report, I can reproduce it. Here are two workarounds for now:
- you can use <kbd>End</kbd>
- you can update to 8.11 where <kbd>right</kbd> was changed back to complete full line (whereas <kbd>ctrl</kbd> + <kbd>right</kbd> completes token-by-token and <kbd>alt</kbd> + <kbd>right</kbd> completes character-by- character).

**Comment by lukelbd** [comment]
Thanks for the quick response. Unfortunately I tried hitting <kbd>Right</kbd> in ipython 8.11 and it doesn't work (<kbd>Ctrl</kbd>+<kbd>Right</kbd> and <kbd>Alt</kbd>+<kbd>Right</kbd> also don't work)... so now there seems to be no way to complete a middle line.

**Comment by krassowski** [comment]
This is not strictly related to this bug, but I just wanted to ask if you happen to have an opinion on https://github.com/ipython/ipython/issues/13987? Please leave :+1: or :-1:  over there if you do - thank you :)
