### ISSUE TITLE
Proposal: Use `AutoSuggestFromHistory` by default

### ISSUE THREAD

**Issue by oscarbenjamin** [ipython/ipython#13993]
(Sorry this ended up being a bit of an essay :). There are a number of related issues and I wanted to be clear exactly what this one is about.)

This is a proposal to make the default configuration for up/down completion be as given by this configuration:
```python
%config TerminalInteractiveShell.autosuggestions_provider = 'AutoSuggestFromHistory'
```
Essentially this restores the behaviour of `up/down` for navigating to history with search that was changed in gh-13888 (IPython 8.9.0). This refers to when typing a partial match of a previously entered command and pushing `up` to retrieve that previously entered command without needing to push `right` to complete and run the command.

This follows from the discussion in gh-13878 (It was suggested in https://github.com/ipython/ipython/issues/13878#issuecomment-1484060390 to open a new issue). This is also referring to the same problem as gh-13979.

This proposal is at least partially an alternative to gh-13987.

A useful and longstanding IPython feature is the ability to rerun previous commands and to search for them by typing some letters and pushing `up`. For example you might enter these commands:
```python
In [2]: result = sum([1, 3)]  # typed this wrong

In [3]: result = sum([1, 3, 4, 6, 7, 78])

In [4]: a = -result

In [5]: b = a + a

In [6]: long_list = [1, 2, 3, 4]
   ...: print(sum(long_list))
10
```
Now if you want to rerun `In [3]` IPython provides a number of ways to retrieve that command. One quick way of retrieving it is to type the first letter(s) of the command e.g. `r` and then push `up` which before gh-13888 would complete the line ready to push enter and rerun that command:
```python
In [7]: result = sum([1, 3, 4, 6, 7, 78])# cursor at end of line
```
If there are multiple matches then pressing up repeatedly will list them in reverse history order. This behaviour is consistent with other REPLs such as Julia, Matlab etc.

The change in gh-13888 means that pressing up no longer invokes the "history buffer" and instead uses the "suggestion buffer". This brings a number of behavioural changes that mean that searching with `up` requires different keypresses and is now inconsistent with other REPLs having this feature as well as a little less convenient (in my opinion!) to use. I have tried this behaviour for over a month now to see if I could get used to it but am now convinced the previous behaviour is a better default and this proposal is to restore that.

The differences between how the history buffer and the suggestion buffer work are as follows:

1. With the suggestion buffer the most recently matched command is displayed automatically without needing to press `up` but it is not completed and so pressing right is needed to run the command. This means that where previously you would type `r up enter` you should now type `r right enter` to rerun the line shown above. To find a match that is not the most recent you should push `r up... right enter` rather than previously `r up... enter`.
2. If searching for the most recent command the old way using `r up enter` (which is still the way used in other REPLs) then the search will not find the most recent command but the *second* most recent command and if enter is pressed then it will run without completing which will be an error. Completing that line with `right enter` is also incorrect for example it would run the incorrectly typed `In [2]` above (I couldn't possibly count how many times I've done this!).
3. With the history buffer it is possible to rerun a multiline code block such as `In [6]` above using `l up enter`. With the suggestion buffer suggestions are only given for one line at a time meaning that it is necessary to search for and run each line separately e.g. for `In [6]` above the keypresses would be `l right enter p right enter`.
4. With the history buffer as soon as you see a search result that is what you were looking for `enter` will rerun it whereas with the suggestion buffer `right enter` is needed after confirming that the correct command is shown.
5. The suggestion buffer offers the possibility to partially complete from the previous command using `ctrl+right`. For example typing `l ctrl+right` will complete `long_list = ` meaning that multiple `ctrl-right` can be used to reconstruct part of the command and then it is possible to type something different for the remainder of the command.

Apart from the case of multiline blocks it is possible to get out of suggestion mode in a few ways:

1. Pressing escape and waiting 2 seconds turns the suggestion buffer off. At that point up/down will use the history buffer as before.
2. Pressing right will complete the line leaving it in a state where you can press enter or edit the line and then press enter. This is similar to what the history buffer does except that it is not possible from here to press up/down to navigate to alternate commands.
3. It is proposed in gh-13987 that the `delete` key could be used to disable the suggestion buffer as `escape` does except without the 2 second delay.

The proposal here is essentially that pressing `up` will immediately disable the suggestion buffer and move to the history buffer restoring previous behaviour for searching with `up/down`.

I have listed a number of differences from having `up/down` use the suggestion buffer rather than the history buffer. While some of them might seem like small differences rather than necessarily being disadvantageous it is important to note that they are differences relative to IPython's previous behaviour and also relative to other systems that have the same feature. The change behaviour also means that navigating like `r up` behaves very differently from just navigating with `up` whereas previously these behaved the same except for the restriction to only navigate through matching commands. Consistency across different UIs is inherently advantageous for anyone who needs to learn and use those multiple UIs.

Also the small differences do stack up when something is heavily used. For example I regularly type `r up enter` pausing only (if at all) before the `enter` to confirm that it is the right command or whether I need to push `up` more times to get that command. When I do this the speed at which I type `r up` is too fast to look at any suggestion. Now though I need to type `r`, look at the faintly coloured suggestion, and then decide whether to push `up` or `right`. That small decision that needs to be made and the involvement of one extra key causes an unavoidable slowdown/frustration every time I do this.

The only advantage as far as I can tell of having suggestion mode rather than history mode is the possibility of using `ctrl+right` for partial completion. I have tried to use this but it is just never useful for what I want to do when searching with `up`. Basically there are two possibilities for what I am trying to do:

1. Rerun a previous command exactly as it was.
2. Search for the previous command but then edit it and run a modified version of that command.

The partial completion is only potentially useful in case 2 but actually it is not a good fit there and so I always use `right` and then edit the line before running it. The reason partial completion is not useful here is because you have a line like this:
```python
In [1]: result = function(arg1, 2*arg2, arg3, arg4)
```
Say you want to rerun this line but using `3*arg2` instead of `2*arg2`. I would do this by pressing `r up` which previously would complete the whole line (now `r up right` is needed). Then you can use e.g. arrow keys to navigate to the `2` and change it to a `3` and then hit `enter`. With the suggestion buffer and partial completion you would type `r` and then `ctrl+right` 3 times to complete `result = function(args1, `. Now you don't want to complete the `2` so you type `3` but then the suggestion buffer has no suggestions any more because your line doesn't match the history: you will have to type `*arg2, arg3, arg4)` manually.

Also perhaps this should be a separate issue but on my Mac laptop ctrl+right is the key combination for switching between different fullscreen applications so it actually doesn't work for completing suggestions in IPython at all.

**Comment by krassowski** [comment]
Thank you for writing up a clear and comprehensive proposal.

I would recommend anyone interested to leave a reaction (:+1: or :-1: ) to keep the comments section focused.

As for `ctrl` + `right` (token-by-token acceptance of suggestions) not working on Mac let's continue discussion in a separate issue (is there an alternative Mac-specific keybinding that you would propose? you can try different options by assigning a [custom shortcut](https://ipython.readthedocs.io/en/stable/config/options/terminal.html#configtrait-TerminalInteractiveShell.shortcuts)).

**Comment by krassowski** [comment]
Here is a counter-proposal (keeping the substance the same, but differing on technical level): what if we the restore old <kbd>up</kbd> for switching history buffer and rebind the current auto-suggestion switching to <kbd>ctrl</kbd> + <kbd>up</kbd> (same for <kbd>down</kbd>/<kbd>ctrl</kbd> + <kbd>down</kbd> respectively)?

**Comment by oscarbenjamin** [comment]
As of the latest release it seems that the previous behaviour is restored so that a single press of `up` recovers the most recent matching command including all lines if it was a multiline command. I have only just installed this so I haven't tested it much but it seems that the up/down history searching now works the way that I wanted it to.

I am not sure exactly what has changed but I guess it is gh-14026. Perhaps this issue is not needed any more.

**Comment by RuRo** [comment]
@oscarbenjamin it seems that 8.14.0 restored the default up/down navigation, but instead broke the ctrl+up/down navigation.

For example, consider the following inputs:

```python
In [1]: a = [
   ...:     "this is",
   ...:     "a list",
   ...: ]

In [2]: a = """
   ...: this is a
   ...: multiline string
   ...: """

In [3]: a =
```

In `ipython<8.9` you could press `ctrl+up ctrl+up` to get the list.

In `ipython==8.14.0`  it seems that `ctrl+up` cycles through the "ghost" autocompletions, so `ctrl+up ctrl+up` cycles between the fake `"""` and `[` postfixes. `up ctrl+up` doesn't work either, because `ctrl+up` just moves the cursor up one line instead of selecting the previous cell.

**Comment by oscarbenjamin** [comment]
> it seems that 8.14.0 restored the default up/down navigation, but instead broke the ctrl+up/down navigation.

I see what you mean. I guess that a new issue should be opened for that though and this one should still be closed.

**Comment by krassowski** [comment]
Closing as per above, I opened https://github.com/ipython/ipython/issues/14112 for the other issue. Thank you!
