### ISSUE TITLE
Right arrow broken in 8.12.1

### ISSUE THREAD

**Issue by Dapid** [ipython/ipython#14051]
The -> arrow doesn't work. When I press the <- arrow to go back and edit the current command, Ipython ignores it.

I don't think my explanation is very clear, so here is an example. If I type:

```
In [1]: print(A
```
And realise I forgot to open the quotes, I go back,

```
In [1]: print("|A
```
Now I am stuck, and cannot "hop" over A. I can keep moving backwards, though. Pressing `end` does work.
 
I have replicated it in an empty virtualenv under both Python 3.9 and 3.10.  The problem disappears downgrading to Ipython 8.12.0.
I am using Fedora Linux, with Qterminal 1.1.0.

**Comment by Nicholas-Mitchell** [comment]
Tested the hotfix myself by manually patching my installation `ipython==8.13.0` -- it works again :)   Thanks @krassowski

**Comment by 2sn** [comment]
How can this recent change to auto-completion relative to earlier versions be entirely disabled and reverted to the earlier behavior?  I find it practically unusable.  I just want to see previous commands with the up arrow, filtering by what it is at the beginning of the line.  As it used to be.  No right arrow "feature".

**Comment by Nicholas-Mitchell** [comment]
You can create configurations (and even different profiles) for ipython.
Have a look at the docs for how to get started:
https://ipython.readthedocs.io/en/stable/config/intro.html


To turn off the auto suggestions, it should be as simple as adding this
setting inside am ipython config:
`c.TerminalInteractiveShell.autosuggestions_provider = None`

**Comment by krassowski** [comment]
# Workaround

Start IPython with override for the problematic shortcut:

```python
ipython --TerminalInteractiveShell.shortcuts "{'command':'IPython:auto_suggest.resume_hinting', 'new_keys': []}"
```

Or If you do not have control over startup sequence, execute:

```python
%config TerminalInteractiveShell.shortcuts = [{"command": "IPython:auto_suggest.resume_hinting", "new_keys": []}]
```

or add it to your configuration in general.

**Comment by 2sn** [comment]
For me, it also work to set
```
c.TerminalInteractiveShell.shortcuts = [{"command": "IPython:auto_suggest.resume_hinting", "new_keys": []}]
```
in the IPython config file (`~/.ipython/profile_default/ipython_config.py`)

**Comment by 2sn** [comment]
With just the "hot fix" the right button seems to be still broken in the IPython debugger called from within IPython using `%debug`.

**Comment by Nasjoe** [comment]
Same here with IPython 8.13.1 inside a Django Shell with shell_plus from django-extensions.

**Comment by theXYZT** [comment]
I am getting the same problem in IPython 8.13.1 (on Windows, using the conda-forge package, and Python 3.11.3)

**Comment by namoshizun** [comment]
Same here with Python 3.11.3 + IPython 8.13.1, on MacOS

**Comment by ThiefMaster** [comment]
A bugfix release would be great :)

**Comment by Carreau** [comment]
yes.

**Comment by ThiefMaster** [comment]
In almost all projects - this one likely included - an issue being closed just means that it has been fixed in a dev version, not that there's already a fixed release.
