### ISSUE TITLE
Question about plotting on IPython terminal

### ISSUE THREAD

**Issue by manmartgarc** [ipython/ipython#14061]
Hello,

This is not a bug report, but rather a question.

I use a IPython terminal over SSH (using VSCode) most of the time. Sometimes I need to generate quick plots to check on some things. This works fine when I am working on my local machine, but when I am running over SSH there's no new window that is created when I call `plt.plot()`. I checked out a couple of guides that tell us to use X11 to handle this, but I remember there being a way to generate the plots within the IPython terminal itself and not in a new window. Is this setting still available?

Thank you in advance for any feedback.

**Comment by bollwyvl** [comment]
Perhaps https://github.com/jonathf/matplotlib-sixel ?

**Comment by jdtsmith** [comment]
There's also [imgcat](https://github.com/wookayin/python-imgcat).  You'll need a terminal which can speak these protocols.
