### ISSUE TITLE
Add %mamba magic to install packages in current kernel

### ISSUE THREAD

**Issue by dshean** [ipython/ipython#14075]
If you wish, you could define a `%mamba` magic similarly to how `%pip` and `%conda` are defined in #11524

_Originally posted by @jakevdp in https://github.com/ipython/ipython/issues/9517#issuecomment-848985175_

**Comment by dshean** [comment]
This issue continues to come up for hub deployments with more complex environments.  Just wanted to resurface a feature request for a %mamba magic.

**Comment by lizeidsness** [comment]
I wondered that too.  This worked as a workaround:
````
%alias mamba conda
%mamba env list
````

**Comment by fecet** [comment]
A mamba magic would be great but what's the problem of just using `!mamba`?

**Comment by mjkanji** [comment]
> A mamba magic would be great but what's the problem of just using `!mamba`?

[According to the creator of IPython](https://github.com/jupyterlab/jupyterlab-desktop/issues/234#issuecomment-928484514), directly calling the shell can result in unexpected behaviour with respect to which environment the packages are actually installed in. And see [this SO post](https://stackoverflow.com/questions/70602866/is-there-an-advantage-of-using-over-in-jupyter-when-the-same-command-exi/70604999#70604999) with more links/details.

**Comment by fecet** [comment]
> > A mamba magic would be great but what's the problem of just using `!mamba`?
> 
> [According to the creator of IPython](https://github.com/jupyterlab/jupyterlab-desktop/issues/234#issuecomment-928484514), directly calling the shell can result in unexpected behaviour with respect to which environment the packages are actually installed in. And see [this SO post](https://stackoverflow.com/questions/70602866/is-there-an-advantage-of-using-over-in-jupyter-when-the-same-command-exi/70604999#70604999) with more links/details.

I think this was caused by the PATH environment is according to that one you open notebook instead of kernel, but that can be configured by kernelspec like, I have a snippet for that:

```bash
    python -m ipykernel install --user --name $CONDA_DEFAULT_ENV --display-name "Python $(python-version) ($CONDA_DEFAULT_ENV)"
    json_file="$HOME/.local/share/jupyter/kernels/$CONDA_DEFAULT_ENV/kernel.json"
    # jq '. + {env: {PATH: env.PATH}}' $json_file > $json_file
    cat <<< $(jq '. + {env: {PATH: env.PATH}}' $json_file) > $json_file
```

I would like to crate a PR add mamba magic but I doubt whether it will be accepted because there is a simple workaround.

**Comment by dshean** [comment]
OK!  I think there is still value in a PR for `%mamba`, which is simpler than the workaround you mention.  The average new jupyter/ipython user won't understand nuances here.

**Comment by dshean** [comment]
Thanks @lizeidsness, though I'm not sure https://github.com/ipython/ipython/issues/14075#issuecomment-1654167248 solves the underlying issue, as this should just run conda, not mamba, which offers improved performance over conda, esp for more complex environments.

**Comment by mjkanji** [comment]
While we are considering this, it would also be great to have support for a `%micromamba` magic, which a potentially _ever faster_ implementation of `mamba`, that's also independent of `conda` (i.e., you don't need conda installed at all).

I do realize, though, that at some point, you just have to say no to these requests. Not to mention, the folks behind `mamba` and `micromamba` are now making _yet another_ package manager called `pixi`: \[[ 1](https://prefix.dev/) \]\[ [2](https://github.com/prefix-dev/pixi) \]

**Comment by lizeidsness** [comment]
> Thanks @lizeidsness, though I'm not sure [#14075 (comment)](https://github.com/ipython/ipython/issues/14075#issuecomment-1654167248) solves the underlying issue, as this should just run conda, not mamba, which offers improved performance over conda, esp for more complex environments.

Noted - but was meant as a temporary workaround until it was maybe implemented.
