### ISSUE TITLE
How do you view .ipynb file?

### ISSUE THREAD

**Issue by danielkrajnik** [ipython/ipython#14087]
Does ipython have any way to simply print .ipynb as a human-readable text?

Can't believe I'm asking this...

**Comment by dneise** [comment]
Hi @danielkrajnik I am not an ipython developer, but stumbled over your question. I hope my answer might help you.

I think the tool you might be looking for is [`nbconvert`](https://pypi.org/project/nbconvert/) it is able to convert ipynb files into various formats, even text-only formats like markdown or rst, or even just plain old python.

**Comment by dneise** [comment]
Ah nice, so I guess we can close this?

**Comment by cohml** [comment]
Just paste the path in here and view it locally, no need to install anything: https://nbviewer.org/
