### ISSUE TITLE
display javascript always print an empty line

### ISSUE THREAD

**Issue by Kefan-pauline** [ipython/ipython#14122]
Hi all,

I am creating a chatbot UI within jupyter notebook using ipywidets and ipython. 

In order to create the streaming effect, I used `display(Javascript(js_code))`. 

However, each call of this will print an empty line below the modified HTML section. Here is an example of output, I would like to delete the space under `Bot`:

![image](https://github.com/ipython/ipython/assets/62143886/16f1bbc5-4242-405f-86e8-8debd2622092)

Code for reproduce:
```
import ipywidgets as widgets
from IPython.display import display, HTML, Markdown, Javascript
import time

# Define the style for the bot message
bot_style = 'background-color: #add1af; padding: 5px; border-radius: 5px; float: left; clear: both;'

output_widget = widgets.Output()
display(output_widget)

user_input = 'Python code to create scatter plot.'
with output_widget:
    user_message_html = f'<div style="background-color: #cce5ff; padding: 5px; border-radius: 5px; float: right; clear: both;">User: {user_input}</div>'
    display(Markdown(user_message_html))
    
# Initial bot message without content
bot_id = 'bot-message'
bot = f'<div id="{bot_id}" style="{bot_style}">Bot: </div>'
with output_widget:
    display(Markdown(bot))

# Function to update messages from the generator
def update_messages(message):
    js_code = f'''
    const botMessage = document.getElementById("{bot_id}");
    botMessage.innerHTML = "Bot: {message}";
    '''
    display(Javascript(js_code))

messages = [' Sure! Here is ',
 ' Sure! Here is an ',
 ' Sure! Here is an example ',
 ' Sure! Here is an example of ',
 ' Sure! Here is an example of how ',
 ' Sure! Here is an example of how to do it',
 ' Sure! Here is an example of how to do it in Python.']
# Call the update_messages function to start message updates
for message in messages:
    update_messages(message)
    time.sleep(0.1)
```

Is there anyway to delete the empty lines created by  `display(Javascript(js_code))`? Maybe I should modify my js_code, or pass some parameters to the display/Javascript function?

Thanks in advance!

---
**Update:**
It turns out that these empty lines are `<IPython.core.display.Javascript object>`, here is the cell output after I restarted the kernel.
```
Output()
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
<IPython.core.display.Javascript object>
```

**Comment by artquest** [comment]
Hi!
Did you find the solution? I have a similar case: empty lines generated on every `display(HTML('<script>...</script>'))`. The problem is I have this line in a loop with hundreds of iterations. So I have hundreds of empty lines in my output.

**Comment by artquest** [comment]
Found it, you need to use the update function of the display handle like this:
`dh = display(HTML('<script>...</script>'), display_id=True)`
and later:
`dh.update(Javascript('...'))`
In this case you have only one empty line. Original answer is [here](https://stackoverflow.com/a/57096808/868860).
