### ISSUE TITLE
Please revert #14190 as it breaks jupyter/qtconsole 

### ISSUE THREAD

**Issue by Czaki** [ipython/ipython#14227]
The #14190 was merged without any deprecation and packages `jupyter/qtconsole` is broke now because of this line:
https://github.com/jupyter/qtconsole/blob/2accd52e7af226bc857a89099260e55c5740efe1/qtconsole/jupyter_widget.py#L17

This change break also upstream package like [`napari`](https://github.com/napari/napari).

It will be really nice if you could revert this change add deprecation warnings, make small release, and provide upstream packages time to fix it before final removal.

**Comment by Carreau** [comment]
reverted by https://github.com/ipython/ipython/pull/14228
