### ISSUE TITLE
Using autoreload magic fails with the latest version

### ISSUE THREAD

**Issue by DonJayamanne** [ipython/ipython#14230]
* Create a notebook with two cells
* First cell with the following code
```
%load_ext autoreload
%autoreload 2
```
* Second cell with
```
print(1234)
```

Upon running the second cell, the following error is displayed
```
Error in callback <bound method AutoreloadMagics.pre_run_cell of <IPython.extensions.autoreload.AutoreloadMagics object at 0x106796e90>> (for pre_run_cell):
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: AutoreloadMagics.pre_run_cell() takes 1 positional argument but 2 were given
```

Downgrading to 8.16.1 fixes this

**Comment by krassowski** [comment]
From a quick look the event manager callback code was modified by #14216. There may be some functionality that needs to be restoring in handling callbacks there.

**Comment by Carreau** [comment]
I'm astonished this was not found by tests.

**Comment by sachinjoshi199007** [comment]
This is impacting our team, what is the ETA for resolving the issue.

**Comment by Carreau** [comment]
> This is impacting our team, what is the ETA for resolving the issue.

This is an open source project maintained mostly from volunteer time. I'll do my best but it will take some time. I might get breakfast and shower and wake up a bit before doing a new release to not botch one more thing.

**Comment by sachinjoshi199007** [comment]
> > This is impacting our team, what is the ETA for resolving the issue.
> 
> This is an open source project maintained mostly from volunteer time. I'll do my best but it will take some time. I might get breakfast and shower and wake up a bit before doing a new release to not botch one more thing.

Thanks for your prompt response @Carreau i understand that it is an open source project and really appreciate the work that your and other members of the community are doing. Reason i asked for the ETA is to know whether we should plan for downgrading or wait out for the next release with the fix.

**Comment by Carreau** [comment]
I should be out in a couple of minutes/hours.

**Comment by Carreau** [comment]
Can some of you try main, to make sure all is right, I'll release in a few hours regardless, but having someone try for a bit would help.

Note that I've also pinned pytest-asyncio that had a release a few hours ago that break IPython CI.

**Comment by pmav99** [comment]
It seems to have been fixed:
```
$ pip install --quiet --force ipython==8.17.1 
$ ipython
Python 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.17.1 -- An enhanced Interactive Python. Type '?' for help.

[ins] In [1]: %load_ext autoreload
         ...: %autoreload 2
         ...: 

[ins] In [2]: 1 + 1
Error in callback <bound method AutoreloadMagics.pre_run_cell of <IPython.extensions.autoreload.AutoreloadMagics object at 0x7fbf8e218c10>> (for pre_run_cell):
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: AutoreloadMagics.pre_run_cell() takes 1 positional argument but 2 were given
Out[2]: 2
```
while with main:
``` 
$ pip install --quiet --force 'git+https://github.com/ipython/ipython.git'
$ ipython
Python 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.18.0.dev -- An enhanced Interactive Python. Type '?' for help.

[ins] In [1]: %load_ext autoreload
         ...: %autoreload 2

[ins] In [2]: 1 + 1
Out[2]: 2
```

**Comment by georgedeath** [comment]
Yep, all fixed in notebooks.

**Comment by iloveitaly** [comment]
Fixed for me too!
