### ISSUE TITLE
search not working in docs

### ISSUE THREAD

**Issue by rootsmusic** [ipython/ipython#14264]
In [readthedocs](https://ipython.readthedocs.io/en/stable/), the search tool loads a searching page but can't complete the process.  No error message.

**Comment by kwsp** [comment]
I've already debugged this issue with a [different project](https://github.com/pydicom/pydicom/issues/1965), but the gist is that the docs are built with `sphinx_rtd_theme`. They still rely on jQuery to load `searchindex.js`, while the Sphinx project removed their dependency on jQuery in 2022 and by default load `searchindex.js` with vanilla JS. A very simple patch could make search work again, but [`spinx_rtd_theme` needs to fix this upstream](https://github.com/readthedocs/sphinx_rtd_theme/issues/1546).

**Comment by astrojuanlu** [comment]
Please try https://github.com/ipython/ipython/pull/14346
