### ISSUE TITLE
Functions cannot appear in nbextensions in Jupyter Notebook

### ISSUE THREAD

**Issue by Jady2022** [ipython/ipython#14308]
**Hi, I am new to python and jupyter notebook, I just used these codes to make the nbextension bar appear:**

`#directly check for the package using:`
`conda list jupyter_nbextensions_configurator`
`#Install it using`
`pip install jupyter_nbextensions_configurator`
`#enable it`
`jupyter nbextensions_configurator enable --user`

 **but it did not show any clickable function, and it said as below:**

varInspector/main
This nbextension is enabled in the notebook json config, but doesn't provide a yaml file to tell us how to configure it. You can still enable or disable it from here, though.

section: notebook
require path: varInspector/main
compatibility: ?.x

**--------------------------**

jupyter-js-widgets/extension
This nbextension is enabled in the notebook json config, but doesn't provide a yaml file to tell us how to configure it. You can still enable or disable it from here, though.

section: notebook
require path: jupyter-js-widgets/extension
compatibility: ?.x

**---------------**

Nbextensions dashboard tab
An nbextension that renders the nbextensions configurator interface as a dashboard tab.

section: tree
require path: nbextensions_configurator/tree_tab/main
compatibility: 4.x, 5.x
/nbextensions/nbextensions_configurator/tree_tab/readme.md
Dashboard Tab for jupyter_nbextensions_configurator
The jupyter_nbextensions_configurator jupyter server extension provides user interfaces for configuring which nbextensions are enabled (load automatically for every notebook), and for editing nbextension options (see its [readme](http://localhost:8888/nbextensions/nbextensions_configurator/readme.md)).

In addition to the main standalone configurator page, this nbextension adds the configurator UI as a tab on the main jupyter dashboard (file browser, or tree) page:

configurator UI in a dashboard tab

**--------------------
 can anyone tell me what should I do next?**

**Comment by krassowski** [comment]
This is not the best repository to ask questions about Jupyter Notebook. IPython repository does not host the Notebook code anymore (https://blog.jupyter.org/the-big-split-9d7b88a031a7). It is worth noting that `jupyter_nbextensions_configurator` is a legacy approach for Notebook <7 and if you are new to Jupyter Notebook, I would recommend that you start from a fresh installation of Notebook 7 (https://blog.jupyter.org/announcing-jupyter-notebook-7-8d6d66126dcf) which includes an improved extension and configuration system. For future, the correct place to report issues in notebook is: https://github.com/jupyter/notebook and for general questions to the community: https://discourse.jupyter.org/
