### ISSUE TITLE
Magic does not work well with ```ast_transformers```/```inspect```

### ISSUE THREAD

**Issue by knyazer** [ipython/ipython#14328]
There is a possible problem with IPython magics: if while registering magic, one modifies the ```ast_transformers``` field of the current shell, for example by adding a new transformer, this leads to the incorrect value of ```co_lineno``` (being always zero, while the real value should be the first line number of the requested function) when trying to use ```inspect``` on any functions. A possible reason is that something confusing cell-level ```co_lineno``` with function-level one. Since it is quite hard to explain the problem coherently, here is a link to a [colab with a reproduction](https://colab.research.google.com/drive/1TIsTRovnDS78e2TUdtKPICAeqVF1Bb0G?usp=sharing#scrollTo=Mfl6NEyOgZC7)

The issue originally appeared [here](https://github.com/patrick-kidger/jaxtyping/issues/160), you might find it useful to quickly look through the discussion there.

I have spent a bit of time trying to figure out what is wrong, but seemingly it requires a too-deep dive into the code. I am happy to help with fixing the issue, so I would appreciate it if you could give me some pointers.

**Comment by knyazer** [comment]
@meeseeksdev tag notebook

**Comment by Carreau** [comment]
I'll try to have a look, but I'm not too surprised, this is pretty brittle APIs and transforms.
