### ISSUE TITLE
Github action workflows do not pass even on main branch

### ISSUE THREAD

**Issue by s-kai273** [ipython/ipython#14338]
when pushing any branch, some github action workflows would run to check code styles, passing tests and others.
but some of them currently fail even on main branch....
I categorize them as below.

- Python package / formatting
- Run tests / test

can anyone help to fix it?

**Comment by s-kai273** [comment]
and I did reformat codes and created draft [PR](https://github.com/ipython/ipython/pull/14332/files).
on this PR, Python package / formatting issue is fixed.

on the reformatting process, I found that the results of reformatting is defferent depending on darker version.
to pass the format workflow, must use `darker==1.5.1` and `black==22.10.0` same to the ones used in workflow.
but it is not written any documents maybe.
I suggest to note it on [code-style part](https://github.com/ipython/ipython/blob/3d02f18733c0bbf062e8852fdc417609fbf29e51/CONTRIBUTING.md#code-style) of CONTRIBUTING.md.

how do you think??

**Comment by krassowski** [comment]
> workflows do not pass even on main branch

To be fair the only failing test is on Python `3.13-dev` which is not unexpected as that Python version has not been released and may contain breaking changes.

> found that the results of reformatting are defferent depending on darker version. to pass the format workflow, must use darker==1.5.1 

Well specifically, you need to use `darker -r 60625f241f298b5039cb2debc365db38aa7bb522` as described in https://github.com/ipython/ipython/blob/3d02f18733c0bbf062e8852fdc417609fbf29e51/CONTRIBUTING.md#code-style. I think this is not ideal but it is documented.

**Comment by s-kai273** [comment]
@krassowski 
thank you for your replying.

> the only failing test is on Python 3.13-dev which is not unexpected

OK, I got it.

> you need to use darker -r 60625f241f298b5039cb2debc365db38aa7bb522 as described

if you use the latest version of darker (now 1.7.2), the result is different from `darker==1.5.1` and `black==22.10.0` even executing `darker -r 60625f241f298b5039cb2debc365db38aa7bb522`.
that is why, I think the description is not enough.

I guess the reason of the reformatting workflow failure is based on it, because there is no change on format using the latest version of darker.
