### ISSUE TITLE
please undeprecate %sc

### ISSUE THREAD

**Issue by tavin** [ipython/ipython#14394]
I refer to https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-sc.

Please remove the deprecation of `%sc`. It does not actually have an equivalent replacement. The object returned by `var = !` does not stringify to the output of the shell command. Rather it stringifies to a python list representation of the split lines. By stringify I mean using `str()` or passing to a yaml/json parser etc. The behavior of `var = !` may be useful/desirable in certain cases, but `%sc` works better in other cases.

Of course every time `var = !` is used, it could be followed by `var = var.nlstr`, but imo `%sc` is better than extra boilerplate. One liners that require two lines... just aren't one liners anymore :)

**Comment by Carreau** [comment]
It's been deprecated 12 years ago, it's likely to not be removed soon. It is a fairly straitforward magic, so if you need or it ever gets removed, it should be simple enough for someone else to move it to a new package or even just defin it in their config file if needs be. 

I'm not going to un-deprecate it after more than 10 years, and if it gets removed one day, then I think it's ok. I don't think we should worry about it. 

Closing as I don't believe i'll un-deprecate.
