### ISSUE TITLE
Infinite redirects on http://nbviewer.ipython.org/

### ISSUE THREAD

**Issue by gitcnd** [ipython/ipython#14415]
Won't load anything:

```

# curl -i https://nbviewer.ipython.org/ -L
HTTP/2 301 
date: Mon, 22 Apr 2024 10:50:05 GMT
content-length: 0
location: https://nbviewer.ipython.org/
retry-after: 0
accept-ranges: bytes
via: 1.1 varnish
x-served-by: cache-sjc10036-SJC
x-cache: HIT
x-cache-hits: 0
x-timer: S1713783005.018870,VS0,VE0
strict-transport-security: max-age=300
alt-svc: h3=":443"; ma=86400
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=NlrAj283b4%2BoQaZeANVUltbYruBVIP0PiYVs5Bz7xUgiYBCHiyTd1p75zsIfnp1iJ12%2FXZWP0iJAmWME7Vaf5fzWOx2ig%2FirI6kcgb%2Bgg6r%2BE9rqj2zqQOnonCzj6j1hQJViNiNptIguSlNY0L6QLMocoQ%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 87850d054c29aab5-SJC

HTTP/2 301 
date: Mon, 22 Apr 2024 10:50:05 GMT
content-length: 0
location: https://nbviewer.ipython.org/
retry-after: 0
accept-ranges: bytes
via: 1.1 varnish
x-served-by: cache-sjc1000096-SJC
x-cache: HIT
x-cache-hits: 0
x-timer: S1713783005.029737,VS0,VE0
strict-transport-security: max-age=300
alt-svc: h3=":443"; ma=86400
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=mASfweSpqJUDfrdB%2FZM52NY%2BwLG15lNBCj7jsF3w3Bi4OlmVG4D0FmhXQgc7QQ3D44v6QpbSgWGZzOULcDwuAtfAR2E5ebJTrP%2FH%2BpEn%2F54zxCSZ0M0YWE4Z4yDWHqFZP1%2F5nAZQah4L7KJ1zTN54qmrWw%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 87850d056c43aab5-SJC

HTTP/2 301 
date: Mon, 22 Apr 2024 10:50:05 GMT
content-length: 0
location: https://nbviewer.ipython.org/
retry-after: 0
accept-ranges: bytes
via: 1.1 varnish
x-served-by: cache-sjc10072-SJC
x-cache: HIT
x-cache-hits: 0
x-timer: S1713783005.040583,VS0,VE0
strict-transport-security: max-age=300
alt-svc: h3=":443"; ma=86400
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=hyyutTXT24o1QNBJ%2FCiX2Xsf%2FyRuV2yeGCXYZ3Asyih%2FPJlafMSaPnT5LH5Fuge10SXS3IjDvKYUcGdc6T7q3eZ5GO7%2B7bvBftq0skV%2B0nK4cecwRgkecIXupngHh%2BauMceDab1JVbSMxZFcWV36SayY0Q%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 87850d057c52aab5-SJC

HTTP/2 301 
date: Mon, 22 Apr 2024 10:50:05 GMT
content-length: 0
location: https://nbviewer.ipython.org/
retry-after: 0
accept-ranges: bytes
via: 1.1 varnish
x-served-by: cache-sjc1000121-SJC
x-cache: HIT
x-cache-hits: 0
x-timer: S1713783005.050465,VS0,VE0
strict-transport-security: max-age=300
alt-svc: h3=":443"; ma=86400
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=lZVe70QT92bzoLUULXWaoOsc54vs%2FWlqioT%2FdUQc0LzA2qQnW9ky%2FPd2TrtR7oIznaMK9jokOXidhGhxcweVNb2IT9HFmHD%2FPqCeesWYG5BjXBES1T5iibgn0EM8aSWu6Gxm5d4qmpa%2BPjU%2FNVf1PoKaAQ%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 87850d058c64aab5-SJC

HTTP/2 301 
date: Mon, 22 Apr 2024 10:50:05 GMT
content-length: 0
location: https://nbviewer.ipython.org/
retry-after: 0
accept-ranges: bytes
via: 1.1 varnish
x-served-by: cache-sjc10048-SJC
x-cache: HIT
x-cache-hits: 0
x-timer: S1713783005.061156,VS0,VE0
strict-transport-security: max-age=300
alt-svc: h3=":443"; ma=86400
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=sJvTOPnJsnkaLuzZgsPHhi2HbU9j1trsf9IxKuHl5gxTG8MynmzH8ttX6URhTqusWYXPC6RArMBP6q4rDd3rekSC6EIHf079getRxkJWpc9LRYmG2%2FtZP29QhAgI89FtqtbCgo%2Bi2PwCHVV21qsNi5qg2g%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 87850d059c6caab5-SJC

```

**Comment by Carreau** [comment]
I'm opened an issue with the Jupyter executive council.

**Comment by Zsailer** [comment]
@Carreau and @gitcnd are you still seeing this issue? 

The redirect works for me.

**Comment by Carreau** [comment]
i fixed it. thanks

**Comment by gitcnd** [comment]
I doubt that redirecting  https://nbviewer.ipython.org/  to  https://nbviewer.org/  was the purpose of that URL?    ipython was in there for a reason.

**Comment by krassowski** [comment]
> I doubt that redirecting https://nbviewer.ipython.org/ to https://nbviewer.org/ was the purpose of that URL? ipython was in there for a reason.

What do you mean by that?

**Comment by Carreau** [comment]
No the various URL are there for legacy reasons, it was serving the same things by the same backend.

[Nbviewer pre-dates the name jupyter](https://github.com/carreau/gistpynb), some people insisted at some point to run that on ipython/jupyter subdomains but it's a security concern (same reason github pages is on github.io and not .com, readthedocs  pages are on readthedocs.io while the admin interfaces are on .org) as js is user controlled. So any nbviewer-like services should always be on it's own subdomain.

I've enabled url rewriting so cloudflare will do a proper url permanent redirect.

(nbviewer.jupyter.org has the same behavior).

**Comment by gitcnd** [comment]
I thought my point was obvious?  nbviewer can do all sorts of things, but if anyone puts "ipython" in the URL, they're not interested in the other things - they're wanting the python one... more specifically - all the millions of websites/tutorials/etc all over the web using that URL are expecting it goes to the thing they meant - a viewer for ipython notebooks, not something different (a generic viewer for anything)

Just saying... it's a pet-peeve of mine when people move things around and break all the backlinks in the process...  the security aspect of the move is fine of course.

**Comment by Carreau** [comment]
Can you point me to any link I broke ? I spent multiple hours reading cloudflare docs to make sure url are properly re-written ... but maybe I missed something ? Like this link properly works, and as far as I can tell you really need to pay attention to see the url was changed.


https://nbviewer.ipython.org/github/ipython/ipython/blob/6.x/examples/IPython%20Kernel/Index.ipynb

nbviewer.org, nbviewer.ipython.org and nbviewer.jupyter.org were just aliases for the same thing, not even different deployment _literally the same server and application_, so there is no difference in what they do. Literally none.

Also technically IPython notebook have not been a think anymore for 9 years now, we still understand the name but it's generally not cool to use a deadname.
