### ISSUE TITLE
Jupyter NoteBook\ ipynb file not showing In and Out words 

### ISSUE THREAD

**Issue by Singaram-117** [ipython/ipython#14431]
I'm having a problem with jupyter notebook, it's  not showing the "In" and "Out" terms while executing the code.

![Screenshot 2024-05-04 233448](https://github.com/ipython/ipython/assets/110803245/fee472bb-c163-4f97-ad7b-2c316f167387)

**Comment by Carreau** [comment]
Please see with the [Jupyter/notebook](https://github.com/jupyter/notebook) team

**Comment by Singaram-117** [comment]
anyway thanks for the support i found alternate solution by installing the previous version of the jupyter notebook <6.7
