### ISSUE TITLE
Released PyPI versions have tags missing from repo

### ISSUE THREAD

**Issue by wimglenn** [ipython/ipython#14433]
There maybe some others, I didn't check, but 8.16.1 was the one I was looking for:

https://pypi.org/project/ipython/8.16.1/

```
$ git checkout 8.16.1
error: pathspec '8.16.1' did not match any file(s) known to git
```

Where can I find [tags](https://github.com/ipython/ipython/tags) for the PyPI releases?

**Comment by Carreau** [comment]
8.16.1 should be a2af83ddfda76f7a84a0b32700a4259596bc4683, i'll fix the tag.

**Comment by Carreau** [comment]
tags pushed.

**Comment by wimglenn** [comment]
@Carreau  Thank you.
