### ISSUE TITLE
memory leakage with matplotlib

### ISSUE THREAD

**Issue by SpaceWalker162** [ipython/ipython#14446]
Running the following code in ipython causes memory leakage. The same thing occurs for both Agg and QtAgg.

```
import numpy as np
import matplotlib.pyplot as plt
import gc

for i in range(5):
    fig = plt.figure(num=1, clear=True)
    ax = fig.add_subplot()
    ax.plot(np.arange(10**7))
gc.collect()
```

Runing the same code in python does not lead to memory leakage.

python version 3.8.19
ipython version 8.12.2
matplotlib version 3.7.2

**Comment by Carreau** [comment]
Latest stable is IPython 8.24, ipython version 8.12.2 was released more than a year ago, and we don't support either Python  3.8 or 3.9. 

I can't reproduce locally (i'm assuming the np.array leaks from your code). 

So I'm going to close, feel free to reopen if you can reproduce on more recent.
