### ISSUE TITLE
Lazy Load a Variable

### ISSUE THREAD

**Issue by mlucool** [ipython/ipython#14452]
Similar to lazy loading magics, we'd find it useful if we could lazy load variables. That is, users want to do something like as soon as they start IPython (no imports/code needed):
```
o.fn1().fn2()
```
Here they know what `o` means to them and they use it all the time and know it means:
```
from foo import Bar
from baz import qux

o = Bar(qux)
```

So ideally in IPython startup they can define variable -> imports + code to be evaluated the first time they try to access this global.

**Comment by Carreau** [comment]
Would you expect foo, Bar, baz and qux to be in final namespace ?

**Comment by mlucool** [comment]
>Would you expect foo, Bar, baz and qux to be in final namespace ?

No

**Comment by Carreau** [comment]
Closed by https://github.com/deshaw/pyflyby/pull/345
