### ISSUE TITLE
The autoreload module is not an IPython extension.

### ISSUE THREAD

**Issue by PauAltur** [ipython/ipython#14462]
I am getting a ```The autoreload module is not an IPython extension.``` message when running 
```python
%load_ext autoreload
```
Trying to run ```%autoreload 2``` after that results in ```UsageError: Line magic function `%autoreload` not found.```

After seeing issue number [12115](https://github.com/ipython/ipython/issues/12115) I performed the check stated there:
```python
import autoreload
autoreload??
```
and my output is
```
Type:        module
String form: <module 'autoreload' from 'path_to_workdir\\venv\\lib\\site-packages\\autoreload\\__init__.py'>
File:        [path_to_workdir\venv\lib\site-packages\autoreload\__init__.py
Docstring:   <no docstring>
```
which seems like it points to the autoreload module. Any help would be appreciated thanks.

Further context:
```
python: 3.8.3 from pyenv-win in venv virtual environment
ipython: 8.12.3
autoreload: 0.1.2

os: win-11
```

**Comment by Carreau** [comment]
You have the autoreload package installed that conflict with the extension, you can try to use the full path the IPython autorelod extension:

```
In[1]: %load_ext IPython.extensions.autoreload
```
