### ISSUE TITLE
Completion in indented lines incorrectly strips the prefix when jedi is disabled

### ISSUE THREAD

**Issue by krassowski** [ipython/ipython#14470]
Completion in indented lines incorrectly strips the prefix when jedi is disabled.

Originally reported in Notebook (https://github.com/jupyter/notebook/issues/7397) then JupyterLab (https://github.com/jupyterlab/jupyterlab/issues/16522), but narrowed down to IPython 8.8 / 8.11; https://github.com/ipython/ipython/pull/13943 fixed a related issue but did not cover this one.

**Comment by Carreau** [comment]
bisected to https://github.com/ipython/ipython/pull/13943

**Comment by Carreau** [comment]
So It was trading one issue for another.

**Comment by ccordoba12** [comment]
FYI, we're also affected by this in Spyder because we disable Jedi support by default (until recently it had serious performance issues).

**Comment by krassowski** [comment]
@ccordoba12 would be great if you have time to confirm if https://github.com/ipython/ipython/pull/14474 helps (and does not introduce regressions elsewhere)
