### ISSUE TITLE
[Duplicate] %run ignores -n switch when running .ipynb files

### ISSUE THREAD

**Issue by BlazingInferno1221** [ipython/ipython#14487]
I am duplicating the following issue because it seems to be old enough that it's been buried by all the other issues and since it appears that it may be an easy fix, at least according to the post and comments: https://github.com/ipython/ipython/issues/10967#issue-285547595

**Comment by ivanov** [comment]
Hi @BlazingInferno1221, Please don't duplicate issues, we have too many open as it is.  If the fix is easy, please submit a pull request. Thanks!
