### ISSUE TITLE
Only create the `README_STARTUP` file the first time the `startup_dir` is created

### ISSUE THREAD

**Issue by jamesbeith** [ipython/ipython#14496]
Every time I start IPython the following file is created, regardless of whether I've previously deleted it.

```
.ipython/profile_default/startup/README
```

This can be seen here as part of the `check_startup_dir()` method.

https://github.com/ipython/ipython/blob/1ec91ebf328bdf3450130de4b4604c79dc1e19d9/IPython/core/profiledir.py#L120-L121

Could we make the copying of the `readme` file into `startup_dir` conditional, only if the `startup_dir` has been created? This would mean if I delete the file (but not the dir) it won't come back again each time I start IPython.

The reason (albeit small) is because I often search for "README" in my IDE and now I have two results coming up, one of which isn't relevant to the project (the IPython one).

I'm happy to put a PR together for this if you're open to the idea?

Thanks

**Comment by Carreau** [comment]
Oh, yeah, make complete sens. 

I was looking at the file logic so end up making a PR https://github.com/ipython/ipython/pull/14497, I would appreciate your review on it. 

For small update like that, feel free to directly send a PR if it's not too  much work.
