### ISSUE TITLE
Ruff as formatter

### ISSUE THREAD

**Issue by joellidin** [ipython/ipython#14532]
Hello, I am just wondering if it is possible to use `ruff` as a formatter? I could not find any issues or documentation on it. I saw there is the possibility for `black` but I would prefer `ruff` if it is possible.

**Comment by ChandanChainani** [comment]
@joellidin 

[`ipython`](https://github.com/ipython/ipython) only support [`black`](https://github.com/psf/black) and [`yapf`](https://github.com/google/yapf) which can be supplied using ` --TerminalInteractiveShell.autoformatter="yapf"` flag to [`ipython`](https://github.com/ipython/ipython) or through `profile` as shown [here](https://github.com/ipython/ipython/blob/03646ad130c7670893fcd094071df085749d6b56/IPython/terminal/interactiveshell.py#L281C76-L281C80)

If you want to use [`ruff`](https://github.com/astral-sh/ruff) you can follow below steps to manually add [`ruff`](https://github.com/astral-sh/ruff) for formatting to [`ipython`](https://github.com/ipython/ipython)

1. create `profile` for [`ipython`](https://github.com/ipython/ipython)
    ```
    ipython profile create
    ```
2. edit `~/.ipython/python_default/ipython_config.py` and add below lines at the bottom of the file
```
import subprocess
from IPython.terminal.interactiveshell import TerminalInteractiveShell

class MyTerminalInteractiveShell(TerminalInteractiveShell):
    def _set_formatter(self, formatter):
        def ruff_reformat_handler(text_before_cursor):
            cmd = f"printf {repr(text_before_cursor)} | ruff format --stdin-filename 'tmp.py' -"
            p = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)            
            lines = p.stdout.readlines()
            if len(lines) > 0 and lines[0].startswith(b"warning:"):
                lines = lines[2:]
            retval = p.wait()
            return b"".join(lines).decode()

        self.reformat_handler = ruff_reformat_handler

c.TerminalIPythonApp.interactive_shell_class = MyTerminalInteractiveShell
```
3. Start [`ipython`](https://github.com/ipython/ipython) and it will use `ruff` for formatting the input code block

**Note:** The above code is only tested for few examples eg: `1 +   2` and `if 1    ==2:    print("hi")`
