### ISSUE TITLE
IPCompleter doesn't work inside tuples/arrays

### ISSUE THREAD

**Issue by divyansshhh** [ipython/ipython#14585]
Consider the following snippet - 

```python
y = "abc"
x = (1, y.<tab>
```

This doesn't return any autocomplete suggestions. This is fixed by enabling `jedi` but can we look into fixing this for the IPCompleter?

This is reproducible on both ipython v8.22.0 and v8.28.0

**Comment by krassowski** [comment]
The case of unclosed parenthesis is already handled, but this case is not. Briefly the relevant code is:

https://github.com/ipython/ipython/blob/d7eebae444b6cf5e8d184591766cf64764e31773/IPython/core/completer.py#L1144-L1150

and then in evaluation we use naive approach of trimming on the left side if there is a syntax error - unless there is not.

https://github.com/ipython/ipython/blob/d7eebae444b6cf5e8d184591766cf64764e31773/IPython/core/completer.py#L1221-L1228

I think that the problem might be that `1, y` is a valid Python expression which evaluates to a tuple (assuming that `y` is defined).

Partial parsing of Python is not easy in the general case. We could possibly consider some heuristics for closing parenthesis for tuples and lists and after guarded evaluation extract the relevant part.

To spell it out we cannot just split on space as in general case it could be `x = (1, a[" "].y.`

**Comment by krassowski** [comment]
Indeed, `<tab>` returns results corresponding to methods available on a tuple:

![Image](https://github.com/user-attachments/assets/70b24a69-5086-4d6d-89f5-336b2ce8240d)

![Image](https://github.com/user-attachments/assets/168b83ee-709b-42fb-b91c-2ff7cdbb7660)

**Comment by krassowski** [comment]
Some more related cases:
- `x = (1, a[" "].y.`
- `x = [1, y.`
- `x = {1, y.`

```
x = (
   1, y.
```

**Comment by mlucool** [comment]
FWIW we turned off jedi because it had historically been too slow, so using Jedi as a solution is unlikely to be ideal (unless its much faster than it used to be)

**Comment by mlucool** [comment]
The following is also a fix
```
ip = get_ipython()
ip.Completer.python_matcher = ip.Completer.python_matches
```

**Comment by Carreau** [comment]
> FWIW we turned off jedi because it had historically been too slow, so using Jedi as a solution is unlikely to be ideal (unless its much faster than it used to be)

I think it's _computing the completions_ that is slow with jedi – because of all the inference and need to access libraries code; Jedi (and its dependency, parso), also offer the ability to simply parse incomplete Python code – which should be much faster – I'm suggesting using only the parsing to extract the current expression the cursor is in.

@krassowski pointed out that a disadvantage is jedi/parso need a new release on every new Python version because of Python syntax changes so that may be a better reason to not use it.

**Comment by krassowski** [comment]
I think restoring the previous behaviour by adding back the attempt to evaluate:

```
# Another option, seems to work great. Catches things like ''.<tab>
m = re.match(r"(\S+(\.\w+)*)\.(\w*)$", text)
```

prior to:

```
m2 = re.match(r"(.+)\.(\w*)$", self.line_buffer)
```

would be a sensible solution improving the current situation. In the edge cases like `x = (1, a[" "].y.<tab>` it does not matter as it does not work right now either. However, we should be careful not to brake `a[" "].y.<tab>`, so maybe it needs two checks? Definitely it needs more tests.
