### ISSUE TITLE
%edit and file locks

### ISSUE THREAD

**Issue by cashfields** [ipython/ipython#14583]
When using the ipython command %edit there is a difficulty if an editor is already opened.

If using NOTEPAD ipython can open multiple documents , no problems.
If another editor is used and is already opened , it appears that a file lock prevents the editor from opening the temp file.
If another editor is used and is not currently opened , then the %edit temp file can be edited,

   
If the configuration file "C:\Users\cash_\.ipython\profile_default\ipython_config.py" is modified to us another editor there can be issues. See below lines.

Starts around line 650:
```
 -Set the editor used by IPython (default to $EDITOR/vi/notepad).
 -Default: 'notepad'
 c.TerminalInteractiveShell.editor = 'notepad'
 -c.TerminalInteractiveShell.editor = 'C:\KEDITW16\KEDITW32.EXE'
 -c.TerminalInteractiveShell.editor = 'notepad++.exe'
 -c.TerminalInteractiveShell.editor = 'C:\Users\cash_\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Notepad++.lnk'
```

With admin rights , I have difficulty getting to the file , must elevate my privilege.  Big file lock. 
 
There are error messages from each editor that it can not open the file - a second file - the temp file.

Please see attached PDF docs with screen prints. One file for each editor ( notepad , KEDIT , NP++ ) with good and bad scenarios.  Showing 'test text' returned to ipython with good examples , if not already opened. 

My big guess is you need to create the temp file and grant rights to 'Everyone'.

==============================

Current python version is:
3.11.8

In [1]: import IPython

In [2]: IPython.__version__
Out[2]: '8.29.0'

OS Name	Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045

==============================[python will     edit if editor is open 0 notepad.pdf](https://github.com/user-attachments/files/17784370/python.will.edit.if.editor.is.open.0.notepad.pdf)
[python will not edit if editor is open 1 kedit.pdf](https://github.com/user-attachments/files/17784369/python.will.not.edit.if.editor.is.open.1.kedit.pdf)
[python will not edit if editor is open 2 notepad++.pdf](https://github.com/user-attachments/files/17784368/python.will.not.edit.if.editor.is.open.2.notepad%2B%2B.pdf)

**Comment by Carreau** [comment]
You likely want to use notepad++ (or whatever other editor) in "blocking mode"; for example  https://stackoverflow.com/questions/24521631/does-notepad-have-a-blocking-mode

**Comment by cashfields** [comment]
That will work just fine. Thank you. Can close issue.
