### ISSUE TITLE
Mispelling "custom" in 8.30 Whats new section

### ISSUE THREAD

**Issue by danieltomasz** [ipython/ipython#14592]
Is "cutom", should be "custom" https://arc.net/l/quote/iomrtdrt, also in the line below "custo" should be fixed

**Comment by Carreau** [comment]
Thanks, I've sent a PR. Why a link minifier though ? Wondering if I'm missing something.
Can I update to link directly to the offending page ?

**Comment by danieltomasz** [comment]
@Carreau link to specific location o page, created and supported by my browser (Arc)

**Comment by Carreau** [comment]
No worries, I've left your link and added a new one for archival.
