### ISSUE TITLE
qtconsole drag target?

### ISSUE THREAD

**Issue by CRP** [ipython/ipython#1488]
Having recently switched from IPython on osx terminal to qtconsole, I miss the "drag a file from finder to get full path in terminal" feature. Is something along these lines planned? More generally is some kind of drag and drop from/to qtconsole planned?

Thanks

**Comment by Carreau** [comment]
Above mentioned PR seem to implement the requested feature, and for me it works with current QtCOnsole.

I'm thus closing this. 
Please reopen if needed, preferably open a new issue on the jupyter/qtconsole repository. 

Thanks.
