### ISSUE TITLE
foo?? not using object_info_request in ipythonqt frontend

### ISSUE THREAD

**Issue by rkern** [ipython/ipython#157]
Per the message spec, foo?? magic should be invoking an object_info_request (or at least something like an object_info_reply). Instead, it gets an execute_reply with paged text. When integrating a frontend into a larger application with its own editors, it would be ideal to open the relevant file at the correct line instead of paging it. The information in the object_info_reply is necessary for that. It's not clear to me how this should be integrated since the frontend is not responsible for parsing the typed-in text to determine whether to send an execute_request or an object_info_request. Perhaps the message spec should be flexible in determining what kind of reply is appropriate for the execute_request. Alternately, the frontend can be made to handle at least the ? and ?? syntax (they're simple enough and distinct enough to make that reasonable).

Incidentally, object_info_reply requires an additional "start_line_number: int" entry to allow a consumer to locate the appropriate line in the file.

**Comment by Carreau** [comment]
Closing as this is a QtConsole bug. 

Thanks.
