### ISSUE TITLE
Add undo (ctrl-Z) for cut/copy/paste/delete in the notebook

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#1582]
Currently, when performing cell level actions such as cut/copy/paste, there is not way of undoing the actions.  This makes it very easy to loose work.  We need to build a framework, UI and keyboard shortcut that makes it possible to undo these actions.

**Comment by nealmcb** [comment]
Yes - I think this is important.  The IPython 2.0 modal notebook interface makes this more likely, and makes it very easy to merge cells also (e.g. hitting shift-m instead of ctrl-m-whatever).

**Comment by adelriosantiago** [comment]
Undo works but the shortcut Ctrl-Z, Cmd-Z is not. Is this still on the roadmap?

**Comment by hmswaffles** [comment]
On a mac, Cmd-z and Cmd-Shift-z do the same thing for the editing of text inside of a cell. Please update this to work like users expect.

**Comment by liamlindy** [comment]
Has anyone had success recently with the undo commands? I am unable to use them at all

**Comment by iVictory2004** [comment]
Opened in 2012, still same issue ocurring, guess I'll just stick to notepad thenn))

**Comment by csaroff** [comment]
I'd like to just throw in my support for undoing things other than delete.

There's been a number of times where I've accidentally pasted a bunch of cells and it was surprisingly time-consuming to suss out which cells were just pasted in and delete them.
