### ISSUE TITLE
Notebook command line parameters not checked

### ISSUE THREAD

**Issue by matthew-brett** [ipython/ipython#1639]
I just noticed that these command lines:

<pre>
$ ipython notebook unlikely
$ ipython notebook unlikely=impossible
$ ipython notebook --pylab=impossible
</pre>

all pass without remark, but this:

```
$ ipython notebook --unlikely=impossible
```

gives:

<pre>
WARNING: Unrecognized alias: 'unlikely', it will probably have no effect.
[NotebookApp] Using existing profile dir: u'/Users/mb312/.ipython/profile_default'
</pre>

Fernando commented on the list (in answer to my question whether this behavior is intended):

> Yes, I think so, though I'm not sure how fixable it is, Min will have
> a better idea: the problem is that the command-line handling captures
> flags and then has to pass that information 'downstream' to all
> components that make up an application, but it doesn't know in advance
> what all the valid flags are from 'below'.  But definitely file it so
> we have a focused place to document/discuss this...

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. I'm not sure how long ago this was fixed (I think quite a while) but here's how IPython 5.1.0 behaves:

```
$ ipython notebook unlikely
[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook` in the future
[C 14:25:30.810 NotebookApp] No such file or directory: /Users/pi/code/ipython/unlikely
14:25@ipython(master)$ ipython notebook unlikely=impossible
[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook` in the future
[C 14:25:33.016 NotebookApp] No such file or directory: /Users/pi/code/ipython/unlikely=impossible
```

Happy hacking! :bowtie:
