### ISSUE TITLE
Allow notebooks to be saved/loaded from GitHub

### ISSUE THREAD

**Issue by stefanv** [ipython/ipython#1648]
This issue is for tracking information pertaining to exporting an IPython notebook to GitHub Gist or regular repositories.

The main blocker so far was OAuth: we could not generate a single (publicly visible) token for all IPython users, since abuse of that token would cause problems.  However, GitHub now provides a way to generate custom tokens, solving this problem:

http://developer.github.com/v3/oauth/#oauth-authorizations-api

**Comment by yuvipanda** [comment]
Related: https://github.com/elaine84/jupyter-synchronized-folders/pull/2
