### ISSUE TITLE
ipython.el silently activates indent-tabs-mode

### ISSUE THREAD

**Issue by lebedov** [ipython/ipython#1744]
It appears that including ```(require 'ipython)``` in one's .emacs file causes indent-tabs-mode to be set in python-mode buffers regardless of whether one unsets it elsewhere in .emacs (e.g., via python-mode-hook). I've observed this behavior with GNU emacs 23.3, python-mode 6.0.7, and the version of ipython.el included with ipython 0.12.1. Is this expected? In accordance with PEP 8, it is desirable to keep indent-tabs-mode off to avoid mixing tabs and spaces.

**Comment by minrk** [comment]
ipython.el is gone
