### ISSUE TITLE
Client.queue_status info gets confused by retried tasks

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#1801]
The Hub doesn't get notified of tasks that fail on an engine but are awaiting resubmission, so it thinks the task is perpetually pending on the engine on which it failed.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
