### ISSUE TITLE
columnize uses terminal columns in zmq kernel

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#1958]
This is pretty irrational, because the likely widths of terminal windows, qt consoles, and notebooks vary pretty widely.

I imagine most people have their ~80 character terminal windows, so you get a pretty sensible value in the notebook and elsewhere.

I, on the other hand, use a full-width drop-down (TotalTerminal née Visor), so my default terminal window is 270 columns wide, and quite a bit wider than my browser window or qt consoles.

The point being that the launching terminal should be totally ignored in the zmq kernel, and a sensible default used instead (I presume ~80-100 characters).

**Comment by QGB** [comment]
import IPython.utils.text as ut

**Comment by QGB** [comment]
In [8]: IPython.utils.text.compute_item_matrix([1,2,3],row_first=False, separator_size=2,displaywidth=80)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-52f7213bbfc3> in <module>
----> 1 IPython.utils.text.compute_item_matrix([1,2,3],row_first=False, separator_size=2,displaywidth=80)

C:\QGB\Anaconda3\lib\site-packages\IPython\utils\text.py in compute_item_matrix(items, row_first, empty, *args, **kwargs)
    700         Out[5]: True
    701     """
--> 702     info = _find_optimal(list(map(len, items)), row_first, *args, **kwargs)
    703     nrow, ncol = info['max_rows'], info['num_columns']
    704     if row_first:

TypeError: object of type 'int' has no len()
