### ISSUE TITLE
Add an 'ignore exceptions' mode to run commands in notebook

### ISSUE THREAD

**Issue by fperez** [ipython/ipython#1977]
I've been finding myself with notebooks where I do want to keep an exception at a certain point (typically for demo/illustration purposes), but those prove to be really annoying to re-run whole.  One can use 'run all' up to the exception, but from there onwards the only solution is to run them cell-by-cell.

I think it would make sense to have an 'ignore exceptions' toggle in the menu so users can choose to run things simply ignoring any cell that causes an exception.

We also will eventually want more fine-grained 'run' controls, such as 'run from here' and 'run until here', but that's for another issue.

**Comment by dlukes** [comment]
What's the status on this? :) I know there's a [workaround extension for the classic notebook](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/runtools), and as @takluyver points out [here](https://github.com/ipython/ipython/pull/4993#issuecomment-369552684),

> Since notebook 5.1 (PR jupyter/notebook#2549), you can also tag a cell with raises-exception to indicate that an exception is expected; then execution will continue through that cell.

So effectively, the behavior *can* be achieved with stock Jupyter Notebook, although it takes a while to figure it out. As for the new JupyterLab interface, these features are also being discussed on its own issue tracker (https://github.com/jupyterlab/jupyterlab/issues/4496, https://github.com/jupyterlab/jupyterlab/issues/2412). Does this mean this issue can be closed?
