### ISSUE TITLE
Cannot restart kernels with running subprocesses on Windows

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#1995]
If a Kernel has a subprocess, then the ports are not immediately freed at shutdown, so the restarted kernel fails to bind.

To reproduce:

``` python
from subprocess import Popen
p = Popen(['sleep', '12345'])
```

in any kernel-using frontend (qt, nb, etc.), then attempt to restart the kernel.  The restarted kernel will encounter a bunch of 'Address in use' errors.  Restarting again after a few seconds, and it's fine (no need to wait for the whole 12345 s, a few seems to suffice).

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
