### ISSUE TITLE
fix autoscroll on Firefox

### ISSUE THREAD

**Issue by juliantaylor** [ipython/ipython#2041]
# update: retitling to describe current state

auto-scroll is super buggy in Firefox (like everything else), so it was disabled for 0.13. This Issue is open for re-enabling autoscroll of long output in Firefox if we can figure out how to make it not suck.
# Original description

since the notebook puts long outputs into a scrollable subcell it scrolls down to the end of the page on each shift+enter even when it should only scroll the following cell.

to reproduce ubuntu 12.04 daily build standard browser (ff 13 I think):
put make three cells containing this:
for i in range(500):
    print i

execute them and then reexecute the first one, it then scrolls right down to the end of the page while I expect to land at the second one.

**Comment by ebellm** [comment]
I see the expected behavior (scrolls to subsequent input) on FF 39 on a Mac--can we determine when the bug was fixed and re-enable autoscrolling for Firefox?
