### ISSUE TITLE
Add a utility method to pretty printer for common Class(a, b, c=d) style output

### ISSUE THREAD

**Issue by njsmith** [ipython/ipython#2137]
It'd be nice if common boring _repr_pretty_ methods could just be written like:

```
def _repr_pretty_(self, p, cycle):
    assert not cycle
    p.pretty_constructor(self, [self.a, self.b], [("c", self.c)])
```

Something like this (extracted from the patsy source): https://gist.github.com/3113186

**Comment by eric-wieser** [comment]
Now that 3.6 is the minimum supported version, I wonder if we can simplify that spelling to
```python
p.pretty_invocation(type(self).__qualname__, self.a, self.b, c=self.c)
```
