### ISSUE TITLE
keyboard shortcuts for Print View and Run All

### ISSUE THREAD

**Issue by tmbdev** [ipython/ipython#2228]
I'm using Notebook 0.13. Could you add keyboard shortcuts for 

- Print View
- Run All

They don't seem to be there right now.  Run All and Restart probably also should have buttons.

**Comment by bridge29** [comment]
I am also a fan of "start over" button.  I would love it also to be a two-button press shortcut. Thanks!

**Comment by srodriguex** [comment]
A "run all" shortcut would be very helpful, indeed.

**Comment by InbarItay** [comment]
Agreed

**Comment by nathanielatom** [comment]
+1 for "start over" button and two-button keyboard shortcut.

**Comment by Carreau** [comment]
> +1 for "start over" button and two-button keyboard shortcut.

Which is the extension we did 2 weeks ago at [scipy tutorial](https://github.com/jupyter/scipy-advanced-tutorial/blob/master/Part1/04-notebook-extensions.md#new-keyboard-shortcut-) 

000, to kill kernel, clear all, restart and run all.

**Comment by oleiade** [comment]
+1 for run all

**Comment by snowch** [comment]
+1 for run all

**Comment by damianavila** [comment]
Restart & Run all hit master here: https://github.com/jupyter/notebook/pull/400

I guess we can close here...

**Comment by kevin1kevin1k** [comment]
+1 for run all!

**Comment by takluyver** [comment]
If you want to test notebook 5.0 (`pip install --upgrade --pre notebook`), there's a shortcut editor you can try in the help menu.

**Comment by sytelus** [comment]
+1 for run all

**Comment by armant** [comment]
+1 for run all

**Comment by fensterheim** [comment]
+1 for run all

**Comment by peakBreaker** [comment]
+1 for run all

**Comment by po0ya** [comment]
+1 for run all

**Comment by vanderlin** [comment]
+1 for run all
