### ISSUE TITLE
[notebook] Remove target="_blank" from notebook links on dashboard page

### ISSUE THREAD

**Issue by inducer** [ipython/ipython#2320]
Three reasons to do this:
- Users already have control over what they want, by choosing between middle vs left click. This takes that control away.
- If #2319 (emacs/vim keybings) gets done, then according to [Chrome's policy](http://code.google.com/p/chromium/issues/detail?id=84332) the window would need to stay in App mode to be able to receive otherwise browser-reserved keys like C-n and C-p. `target="_blank"` pops the tab out of App mode, which is inconvenient.
- There's no state on the dashboard page that a user might destroy by navigating away.

A consequent change to this is that "File > Close" and "File > Close and halt" should likely return a user to the dashboard.

**Comment by NickATC** [comment]
This is a good time frist issue... is this still a WIP??
