### ISSUE TITLE
R documentation in Python

### ISSUE THREAD

**Issue by lgautier** [ipython/ipython#2375]
R objects in packages are documented in R "help" pages. It would be convenient to have those easily accessible from
ipython.

Rpy2 starts providing an automagic building of Python docstrings from the R documentation with the upcoming release 2.3.0.
May be some of it could be used.

To install the upcoming 2.3.0:

``` bash
hg clone https://bitbucket.org/lgautier/rpy2
cd rpy2
hg update version_2.3.x
python setup.py install
```

Then in ipython:

``` python
# builds docstrings for all R packages imported; not terribly fast at the moment
import rpy2.interactive as r
# query the doc for "zapsmall", in the R package "base"
?r.packages.base.zapsmall
```

**Comment by lesley2958** [comment]
is this still nothing that wants to be changed?

**Comment by takluyver** [comment]
If the docstring is available as `obj.__doc__` on the object,  then I think this *should* just work without needing anything to be changed. I may have overlooked something, though.

**Comment by lgautier** [comment]
I forgot to update this. Rpy2's `importr` is making R objects dynamically fetch the R doc when the docstring is accessed, and it does work.
