### ISSUE TITLE
mobile browsers and the htmlnotebook

### ISSUE THREAD

**Issue by dalcacer** [ipython/ipython#2454]
Hi there, I managed to launch ipython at a host and tried to access the htmlnotebook using an android-tablet.

First of all the overall experience is charming, though some points could maybe be optimized for mobile devices (in future?).

I ran into one specific problem:
Existing markdown or heading cells can't be edited by touching/clicking them.
A first solution could be an edit-shortcut. (I finally managed to edit a cell by selecting it and hitting `ctrl+y` followed by `ctrl+m`.)

Raw/code-cells just work fine. I think they aren't "rendered" yet, so the browser identifies them as a **text-input-field**, so clicking/touching those invokes the keyboard.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
