### ISSUE TITLE
automatic indent fails after EOF

### ISSUE THREAD

**Issue by doda** [ipython/ipython#2465]
```python
In [1]: for bla in bla:
   ...:     <- cursor here

In [1]:  <press Ctrl+d>
Do you really want to exit ([y]/n)? n

In [1]: for bla in bla:
   ...: <- cursor here
```

**Comment by takluyver** [comment]
I can't currently reproduce this - pressing Ctrl-D when the line is non-empty removes the character under the cursor, or does nothing if the cursor is at the end of the line. Anyone else?

**Comment by doda** [comment]
It seems indeed that pressing Ctrl-D while indented does not work anymore ... bug fixed! :)

**Comment by doda** [comment]
@doda
