### ISSUE TITLE
Ctrl-C in ipdb kills QtConsole on Windows

### ISSUE THREAD

**Issue by dhirschfeld** [ipython/ipython#2472]
As detailed on the user list (http://mail.scipy.org/pipermail/ipython-user/2012-October/011274.html) pressing Ctrl-C in ipdb will cause the QtConsole to hang. Tested on Windows 32bit Python with latest IPython.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
