### ISSUE TITLE
All commands in Qt console Magic menu should not be immediatelly executed

### ISSUE THREAD

**Issue by klonuo** [ipython/ipython#2565]
Some commands from Magic menu require additional parameter, to be able to run. 
IPython Qt console already appends question mark on some of them (nice workaround/feature), but not on all.
For example running anything but `%load_ext?` from Extension submenu seems useless, also with other magics like `%run`, `%tb`, ...

**Comment by Carreau** [comment]
closing that, now that QtConsole is its own repo.
