### ISSUE TITLE
Decide how to document JavaScript

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#2567]
I suggest using jsdoc 3

http://usejsdoc.org/

**Comment by Carreau** [comment]
I think once we are in typescript we will use typedocs. There are some issues that with current structure where all appears global.

**Comment by ellisonbg** [comment]
Yeah, one of the main reasons I am so supportive of transitioning to
typescript is that typedoc is so nice.

On Wed, Jun 10, 2015 at 10:46 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> I think once we are in typescript we will use typedocs. There are some
> issues that with current structure where all appears global.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/2567#issuecomment-110849532>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. The [notebook](https://github.com/jupyter/notebook) is no longer  a part of this repository, and from my understanding is no longer  being actively developed, and [JupyterLab docs](https://jupyterlab.github.io/jupyterlab/) adopted conventions inherited from TypeDoc in the TypeScript world. Thanks everyone for participating!

Happy hacking! :bowtie:
