### ISSUE TITLE
For multi-line input end key goes to end of line instead of end of input

### ISSUE THREAD

**Issue by khughitt** [ipython/ipython#2594]
In the regular version of IPython the home key goes to the beginning of input and the end key goes to the end of the input.

In qtconsole (1.7.0b2) the home key works, but the end key only goes to the end of the line -- to get to the end of the input you have to hit "end", "right-arrow", "end", "right-arrow", etc.
## System info:

Arch Linux 64-bit
IPython 1.7.0b2, run with "qtconsole --colors=linux --pylab"

**Comment by dashesy** [comment]
I use PgUp/PgDn go to previous lines/multilines in history, but cannot find any way to go to the beginning/end of a multiline.

**Comment by markmark1** [comment]
Did some one figure this out?
is there a way to goto end of multiline ipython input or beginning of multiline python input please? thanks in advance

**Comment by MrMino** [comment]
As far as I can tell this is already in `7.x`, via <kbd>Ctrl</kbd>+<kbd>Home</kbd> and <kbd>Ctrl</kbd>+<kbd>End</kbd>.

I don't know where exactly it was implemented (prompt-toolkit?), but I'm going to close this anyway. If anyone disagrees - please ping me.

**Comment by markmark1** [comment]
There is no home or end button in Mac keyboard so how do you do it in Mac
  
  
  
    
  

  
  
>

**Comment by MrMino** [comment]
@markmark1 I don't have a mac, so I can't be sure, but have you tried <kbd>Ctrl</kbd> + <kbd>Fn</kbd> + <kbd>←</kbd> / <kbd>→</kbd>?

Google is your friend here, these shortcuts seem to be the same as for every other text editing program :).

**Comment by markmark1** [comment]
Will try ctrl Ctrl + Fn + ← / →
Blazej as advised
