### ISSUE TITLE
ipython fails under IronPython 2.7.3

### ISSUE THREAD

**Issue by kent37** [ipython/ipython#2666]
Trying to run ipython 0.13.1 under IronPython 2.7.3 on Windows 7-64 I found a few problems and (fewer) workarounds.

IPython\utils\process.py line 24 change to use the correct process module

```
 - if sys.platform == 'win32':
 + if sys.platform == 'win32' or sys.platform == 'cli':
```

IPython\core\prompts.py line 142 - os.path.realpath raises ValueError with bogus path:

```
 - HOME = os.path.realpath(HOME)
 + if sys.platform != 'cli':
 +     HOME = os.path.realpath(HOME)
```

IPython\core\interactiveshell.py line 1044 this code

```
        user_module = types.ModuleType("__main__",
            doc="Automatically created module for IPython interactive environment")
```

raises
SystemError: Unsupported param dictionary type: IronPython.Runtime.PythonDictionary
I don't have a fix for this one, it seems to be an IronPython bug (http://ironpython.codeplex.com/workitem/33173)

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. IPython 0.13.1 is super old at this point and the next version of IPython will not support Python 2.x at all.

Happy hacking! :bowtie:
