### ISSUE TITLE
Notebook including other notebook

### ISSUE THREAD

**Issue by lrem** [ipython/ipython#2677]
I would love to see a way for notebooks to include other notebooks. By include I mean literally running the other one as if it was part of the current one: the same kernel, the same namespace.

In my, but I believe many other people's, use case the notebook often serves to keep well typeset (LaTeX) formulas next to their Python implementation and visualization. Now, I often want to run this on multiple sets of input parameters, keeping each set as a separate notebook for further tweaking. This means duplicating the formulas code between multiple notebooks, what further implies a lot of manual and error prone work with keeping them in sync. The other option - making them actual modules kept in plain _.py_ is also not good, as I lose the _well typeset formulas next to code_ niceness of notebooks.

Bonus points if print view would actually show the cells of the included notebooks.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. Min added support for `%run somenotebook.ipynb` back in November of 2013 with #4452 - thanks, Min! Running notebooks via `%run` has seen additional improvements since then.

Happy hacking! :bowtie:

**Comment by lrem** [comment]
I've tried it and it Just Works™. Thanks!
