### ISSUE TITLE
pluggable authentication

### ISSUE THREAD

**Issue by shreddd** [ipython/ipython#2770]
I was wondering if there were any plans for supporting pluggable authentication in the notebook. 

I looked at the code and it doesn't seem too hard to support alternate forms of authentication (eg. LDAP) by making callouts from ipython.lib.security.passwd_check. If there is any interest I can probably get this working. Also - any coding/style guidelines that I should follow would be appreciated

Thanks
-Shreyas

**Comment by pelson** [comment]
I think this can now be closed thanks to the addition of #6977.

**Comment by minrk** [comment]
@pelson thanks for catching it.
