### ISSUE TITLE
Adding record-and-playback to IPython Notebook for teaching

### ISSUE THREAD

**Issue by gvwilson** [ipython/ipython#2832]
[Software Carpentry](http://software-carpentry.org) is moving its Python lessons (and eventually other content as well) over to the IPython Notebook. As part of that, we would like to replace our video screencasts with something that replays a Notebook session in the browser, in sync with an audio voiceover.  We want to do this because:
1. People can't pause a video, then copy and paste its text, because there is no text: there are just pixels arranged to look like letters.
2. For the same reason, the code in videos is invisible to search engines.
3. We also can't diff and merge videos in version control the way we can diff and merge source code and Notebooks.
4. And video is inherently less adaptable to new platforms (e.g., tablets and smart phones) than first-class content that's rendered in the best way for whatever device the user has.

In the long run, we'd like users to be able to:
1. Press "Play".
2. Watch the Notebook reconstruct itself in sync with a voiceover.
3. Press "Pause".
4. Do some experimenting (e.g., fill in a short exercise, play with parameters for graphs, etc.).
5. Press "Reset" to put things back the way they were.
6. Press "Play" again to continue with the "main line" of the presentation.

Implementing this kind of "what if?" will be difficult, because we'd have to clone and restore the state of the back-end engine, but a "replay only" tool would still be very useful: at least as useful as our existing screencasts.  From discussion with Brian Granger, Min RK, and Bobby Richter (of Mozilla), it looks like "replay only" could be done as a plugin without any changes to the Notebook itself:
1. [Popcorn.js](http://popcornjs.org/) and a little bit of custom Javascript can be used to synchronize a soundtrack (e.g., an MP3 voiceover) with updates to the Notebook's cells.
2. The Notebook now allows per-cell metadata, so timing information (e.g., when to start displaying this cell and how long to take filling it in) can be embedded without format changes.

The workflow we envision is:
1. Author spends minutes, hours, or days incrementally building up the notebook.
2. Author puts notebook in "mark time" mode.
3. Author records audio her favorite desktop tool while clicking "next" in the notebook to insert time marks into metadata.
4. Author saves audio and inserts URL into notebook.
5. Time passes.
6. Audience opens notebook in browser (either local or web copy---audio file may be local or web as well).
7. Audience presses "Play".
8. Notebook incrementally reconstructs itself in sync with voiceover.
9. Audience can use "Rewind", "Fast Forward", "Pause", "Go To Cell" (jumps the audio) or "Go To Time" (jumps the notebook) at will.

Please add comments on this ticket if you have suggestions or design ideas, or want to help build, test, and use this widget.

**Comment by gvwilson** [comment]
Presume this is stale?

**Comment by Carreau** [comment]
We can migrate to the new repo. With the current refactoring in progress, this will be **much** easier to do in 6month or so. We have a meeting this Friday to discuss about how to store/transmit application state, so I'll mention that explicitly.

**Comment by gvwilson** [comment]
Gracias,
Greg

**Comment by lrq3000** [comment]
Great news! This feature would be amazing and I know for sure I would use it extensively! :100:
