### ISSUE TITLE
can't reconnect an open notebook if the server crashes

### ISSUE THREAD

**Issue by drevicko** [ipython/ipython#2867]
If you are working on a notebook and for whatever reason the server or the crashes, there doesn't appear to be any way to reconnect once the server comes back to life. Unless I'm missing something, the result is that anything written since your last save must be copy/pasted into the last saved copy (or given up as lost..).

This is related to #1378 (autosave), #2553 (robustness against client failures) and similar to #2667 (can't save if accidentally deleted), though it seemed to me a somewhat different issue, so I've given it a separate ticket..

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
