### ISSUE TITLE
Colon hash (:#) in string forces input to wait

### ISSUE THREAD

**Issue by rgbkrk** [ipython/ipython#2913]
Entering a string with a colon immediately followed by a pound sign forces the input to wait. This issue does not affect ipython notebook (bug only seen in the console/qtconsole).

Example:

``` python
In [41]: ":#"
   ....:     
Out[41]: ':#'

In [42]: ':#'
   ....:     
Out[42]: ':#'
```

**Comment by rgbkrk** [comment]
Wanted to see if this was maybe fixed by #8505, no go:

```
In [1]: "this is my test :# "
   ...:
Out[1]: 'this is my test :# '
```

**Comment by takluyver** [comment]
No, those might appear similar, but they're handled by completely separate
parts of the code.

**Comment by rgbkrk** [comment]
You know, I never left commentary about _how_ I ran into this bug (which still exists). I was writing regular expressions at the time (with non-matching groups IIRC).

**Comment by rgbkrk** [comment]
Note that this applies when there are spaces between the colon and the hash:

```
In [5]: ':      #'
      :
Out[5]: ':      #'
```

**Comment by rgbkrk** [comment]
No way, you can't have fixed the first bug I ever reported to ipython. It's my favorite bug.

**Comment by Carreau** [comment]
> No way, you can't have fixed the first bug I ever reported to ipython. It's my favorite bug.

We can add a flag for you to restore it :-)  We're so happy you opened bugs and contributed ! And thanks for still sticking around !

**Comment by takluyver** [comment]
No we can't, I removed the old code that was causing the issue. ;-)

I've been meaning to get round to it for ages, and someone else reporting the same bug today provided the impetus.

**Comment by willingc** [comment]
For @rgbkrk: :ant: :ant: :ant: :spider: :spider: 🕸 :bee: :bee: :beetle: :beetle: To keep you from getting lonely :smile:

**Comment by Carreau** [comment]
> No we can't, I removed the old code that was causing the issue

We can still have a subpackage `rgbkrk.py` and match on the machine login right ?
We should do if for fperez anyway. 

> 🐜 🐜 🐜    🐝 🐝 🐞 🐞

BUGS FOR THE BUG GOD, BEES FOR THE BEE QUEEN

**Comment by rgbkrk** [comment]
Thank you for the extra bugs @willingc!

**Comment by takluyver** [comment]
Thank you for subscribing to bug facts, your source of exciting information about bugs!

I can now reveal that none of the creatures depicted so far are true bugs (order Hemiptera). Here is a true bug (a shield bug, to be more specific):

![shield bug](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Acanthasoma_hamorrhoidale_adult.jpg/320px-Acanthasoma_hamorrhoidale_adult.jpg)

**Comment by jasongrout** [comment]
I'm really glad we have a team with such a variety of backgrounds!

**Comment by rgbkrk** [comment]
🐛 ?

**Comment by Carreau** [comment]
See [this documentaty about ants](https://www.youtube.com/watch?v=9jtU9BbReQk)[1].

Thanks ants. 

1: full source  https://vimeo.com/62218296
