### ISSUE TITLE
Problems with the less based style.min.css

### ISSUE THREAD

**Issue by damianavila** [ipython/ipython#3012]
Using reveal ipython powered slideshows, if I want to get a pdf, I have problems with the following line in style.min.css:

```
@media print{*{text-shadow:none !important;color:#000 !important;background:transparent !important;box-shadow:none !important;} a,a:visited{text-decoration:underline;} a[href]:after{content:" (" attr(href) ")";} abbr[title]:after{content:" (" attr(title) ")";} .ir a:after,a[href^="javascript:"]:after,a[href^="#"]:after{content:"";} pre,blockquote{border:1px solid #999;page-break-inside:avoid;} thead{display:table-header-group;} tr,img{page-break-inside:avoid;} img{max-width:100% !important;} @page {margin:0.5cm;}p,h2,h3{orphans:3;widows:3;} h2,h3{page-break-after:avoid;}}.clearfix{*zoom:1;}.clearfix:before,.clearfix:after{display:table;content:"";line-height:0;}
```

[link](https://github.com/ipython/ipython/blob/master/IPython/frontend/html/notebook/static/css/style.min.css#L20) to the code: 

In particular with this one: 
`color:#000 !important;`
because it is making all the code black, losing all the pigment coloring...
and because is marked as `!important` I can not overwriting later with css.

It is necessary to get this color property to black? I don't think so... ;-)

Cheers.

Damián.

ping @Carreau because you work with this style ;-)

**Comment by ellisonbg** [comment]
@damianavila should we keep this targeted to 3.0? Any update on this issue?

**Comment by damianavila** [comment]
Let target to 4.0... I will submit the request upstream... if I get a quick answer, we can do the changes before 3.0 but I don't know if it is a realistic timeframe, so better change it to 4.0

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
