### ISSUE TITLE
further decouple javascript modules

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#3057]
We've done an okay job with decoupling the javascript, but it hasn't actually been tested in the wild.  I wrote two examples today, which suggest that there is still some cleaning up to do (will post them later, after some cleanup).

The first was a page with a single kernel and single code cell, and the second was a page that used nothing but kernel.js.
- CodeCell brings in way too many dependencies non-optionally - tooltip, completer, config, celltoolbar
- The Kernel object still has one dangling reference to the notebook in start_kernel, which should be removed.
- almost none of our Tornado handlers are reusable outside IPython - they depend on the WebApp having an ipython_app attribute, read_only, and are actually tied to our url scheme and specific attributes only defined in MappingKernelManager.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
