### ISSUE TITLE
Download a notebook as JSON from browser if server is dead

### ISSUE THREAD

**Issue by ivanov** [ipython/ipython#3086]
It would be nice to have a javascript-based save functionality.

One use case is related to #3085 -- a user can open a notebook that she  doesn't have permission to save, run it, modify it in her browser, but then not have anyway to save this new notebook, since save currently roundtrips through the server.

Another use case is the server crashed, or you were disconnected, but you have some intermediate state that you want to preserve.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
