### ISSUE TITLE
Equivalents of dbup, dbdown and dbstack in Embedded IPython sessions

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [ipython/ipython#3096]
Do IPython embedded shells have support for moving up or down through the [**call stack**](http://en.wikipedia.org/wiki/Call_stack)? (i.e. something like [`dbup`](http://www.mathworks.com/help/matlab/ref/dbup.html) or [`dbdown`](http://www.mathworks.com/help/matlab/ref/dbdown.html) in MATLAB).

What about the ability to just inspecting it? (i.e. seeing the list of calls from the top level to the context in which the shell was started). This would be similar to [`dbstack`](http://www.mathworks.com/help/matlab/ref/dbstack.html) in MATLAB.

**Comment by MrMino** [comment]
This is covered by the `traceback` module & `inspect.stack()` in Python.
