### ISSUE TITLE
Variable inspector in notebook

### ISSUE THREAD

**Issue by elyase** [ipython/ipython#3193]
It would be nice to have some sort of quick variable inspector. What I have in mind would be something like a tooltip/popup, (similar to the one which displays the function signature when tabbing inside a function) which activates when the mouse goes over the variable and some modifier key(for example Alt(Windows)/ ⌥(Option) on Mac) is being pressed. As soon as the mouse leaves the area over the var it goes away. Screenshot:

![variable_inspect](https://f.cloud.github.com/assets/1175888/393043/30f9635e-a78d-11e2-939c-ac44df4d16f6.png)

**Comment by mcaffini** [comment]
Does anyone want to explore in this direction? (@elyase?)
I started coding a variable inspector widget last week and I have a few ideas.

**Comment by elyase** [comment]
sure! I was also thinking about this recently.

**Comment by mcaffini** [comment]
I started from the widget linked by @herr-biber and I'm working on a color code for major types (spyder-like to be easier). It would be nice to toggle on/off the variable inspector with a button on the toolbar (maybe later).
