### ISSUE TITLE
Saving current execution state like Matlab does with .mat

### ISSUE THREAD

**Issue by nipunbatra** [ipython/ipython#3271]
Many times, when a lot of data processing is done in a notebook, after reopening all the data crunching needs to be done again. How about saving the way Matlab allows to save .mat

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one as a duplicate of #112 and #1035. It's worth noting that anyone who seeks this functionality should look at [dill](https://pypi.python.org/pypi/dill), which has functions for `dump_session()` and `load_session()`.

Happy hacking! :bowtie:
