### ISSUE TITLE
Notebook - Add RTL (Right-To-Left) Support

### ISSUE THREAD

**Issue by amitkot** [ipython/ipython#3278]
Currently, it is hard to prepare a notebook that is written in a right-to-left language (Hebrew, in my case, but also Arabic and Farsi), as the text is always formatted in a  left-to-right manner.

The way this is implemented in Gmail is that according to the first letter of each line, the line is automatically LTR or RTL.

If this is implemented, the IPython Notebook will become a viable method for preparing python documentation and training material in Arabic, Farsi and Hebrew.

**Comment by gnestor** [comment]
This was implemented in the notebook: https://github.com/jupyter/notebook/pull/2357
