### ISSUE TITLE
strange behavior in Kernel+Py3

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#3289]
@ganwell has brought up an interesting issue.

With the following trivial `example.c`:

``` c
// example.c
#include <Python.h>

int example(void);
int example(void) {
    PyRun_SimpleString("print('hello')");
    return 0;
}
```

It can be called from Python with:

``` python
# example.py
import ctypes
example_so = ctypes.PyDLL("./example.so")
example_so.example()
```

Interestingly, if this code is executed via `%run example.py`, it works as expected.  However, the same code executed in the _same_ interactive session, it gets this weird error, as if the namespace is entirely empty:

``` python
$> ipython3 console
In [1]: run example.py
hello

In [2]: example_so.example()
Out[2]: 0
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<string> in <module>()

NameError: name 'print' is not defined
```

Even more peculiar, this does not affect terminal IPython, so it is a behavior specific to the kernel:

``` python
$> ipython3
In [1]: run example.py
hello

In [2]: example_so.example()
hello
Out[2]: 0
```

So this is a behavior unique to Python 3, using the kernel, and running interactively and _not_ via `%run`.

A complete example can be found [here](https://github.com/ganwell/ctypes-example).

**Comment by ganwell** [comment]
@minrk This should probably be closed, as it was strange quirk and ages ago.
