### ISSUE TITLE
IPEP18: Text Editor for the Notebook

### ISSUE THREAD

**Issue by ghost** [ipython/ipython#3324]
On Brian's advice, I'm opening [this IPEP](https://github.com/ipython/ipython/wiki/IPEP18:-Text-Editor-for-the-Notebook), along with another regarding a HTML terminal, and will close IPEP7.

IPEP7 proposed 'Notebook subclients' in general, which don't seem useful beyond having an editor and terminal.

**Comment by ivanov** [comment]
I am closing this, the IPEP was deferred, but we now have a text editor in the notebook and in jupyterlab.
