### ISSUE TITLE
BPython interface in IPython

### ISSUE THREAD

**Issue by alexbw** [ipython/ipython#3339]
I've seen some buzz awhile back about taking the nice completion and doc-string features of BPython and porting them to IPython. The BPython shell is incredibly nice to work with, and was curious if there's any plans or history behind a port?

**Comment by ivanov** [comment]
For what its worth, this is what [bipython](https://github.com/ivanov/bipython) did, while it was working, so if anyone wants to roll up their sleeves, that could be a useful starting point. 

Between bipython and the [python prompt toolkit](https://python-prompt-toolkit.readthedocs.io/en/latest/) now being using in IPython, I think we can close this issue.
