### ISSUE TITLE
wishlist/enh: better handling of AutoMagic with call parens (quit() and exit() ought not NameError, at least)

### ISSUE THREAD

**Issue by dwf** [ipython/ipython#342]
Related to #337, people coming from generations-old IPython might still be tempted to type quit() and be miffed to find out it doesn't exist anymore. Ideally these two should probably 'just work', or the error should at least be something more sensible than a NameError.

In general trying to use automagic with call () parens should probably not NameError, but rather direct the user to %magic. I've been looking at InteractiveShell for a way to do this generally but I'm not sure there is a good one. Seems like catching a NameError in run_code is the way to go but we're already several levels down the call stack from being able to inspect the raw code to see if it is a magic gone wrong.

**Comment by takluyver** [comment]
`exit()` and `quit()` now seem to work fine.
