### ISSUE TITLE
stderr missing in IPython + Emacs + WinXP

### ISSUE THREAD

**Issue by ipython** [ipython/ipython#35]
Original Launchpad bug 237204: https://bugs.launchpad.net/ipython/+bug/237204
Reported by: jietang86 (Jie Tang).

WinXP Pro SP2
Emacs 22.1
ipython.el 
python-mode.el 

stderr doesn't show up when using IPython with ipython.el inside Emacs.

e.g.:

In [2]: from sys import stderr,stdout

In [3]: stdout.write('\nfoo\n')

foo

In [4]: stderr.write('\nbar\n')

In [5]:

It seems like sys.stderr has some buffering issues; if I flush the stream using stderr.flush() after writing to it the text displays.

In [6]: stderr.flush()

bar

In [7]:

As a workaround I added calls to

Term.cout.flush()
Term.cerr.flush()

right before IPython's "In[]" input prompt is displayed (around line 1675 in iplib.py)

**Comment by minrk** [comment]
ipython.el is no more
