### ISSUE TITLE
Add visual indication that cell has been edited and is now 'locked' in Qt Console

### ISSUE THREAD

**Issue by fperez** [ipython/ipython#358]
Once a cell has been edited, it would be nice to visually mark it somehow (faint change of color background or thin line above it) so the user knows the content has changed and the behavior is now different.  Especially because if they have 'cell locking' on, they'll need to override the arrow key at the edge of an edited cell to get out of it, so providing a visual cue would be good.

**Comment by Carreau** [comment]
Closing as a QtConsole issue.
