### ISSUE TITLE
Alerts when loading large notebooks in Firefox

### ISSUE THREAD

**Issue by ghost** [ipython/ipython#3637]
I noticed that very large Ipython notebooks have issues loading in Firefox. Try to reproduce this issue using <a href="https://github.com/ogrisel/parallel_ml_tutorial/blob/master/solutions/03%20-%20Text%20Feature%20Extraction%20for%20Classification%20and%20Clustering.ipynb">this notebook</a> or <a href="https://github.com/ogrisel/parallel_ml_tutorial/blob/master/solutions/04%20-%20Large%20Scale%20Text%20Classification%20for%20Sentiment%20Analysis.ipynb">this one</a>, although I have seen similar behavior in several large notebooks. These are some alerts that I usually get:

> A script on this page may be busy, or it may have stopped responding. You can >stop the script now, or you can continue to see if the script will complete.
> Script: http://127.0.0.1:8888/static/components/jquery/jquery.min.js:5
> 
> A script on this page may be busy, or it may have stopped responding. You can >stop the script now, or you can continue to see if the script will complete.
> Script: http://127.0.0.1:8888/static/components/jquery-ui/ui/minified/jquery-ui.min.js:7
> 
> A script on this page may be busy, or it may have stopped responding. You can >stop the script now, or you can continue to see if the script will complete.
> Script: http://127.0.0.1:8888/static/components/codemirror/lib/codemirror.js:1003

After clicking on "Continue" the loading resumes as usual.

I'm running Ipython 1.0 dev and Firefox 22 in Linux Mint 15. Google Chrome frequently loads the notebooks without major issues. I have seen the "The following pages have become unresponsive" dialog but this is rare.

**Comment by cknoll** [comment]
I can confirm this behavior with IPython version 2.3.1. I get the alert on by notebook PC, but not on my desktop PC (which has much more computing power).

While a clean solution seems to be planned for 3.0 (wishlist), does anybody know an immediate workaround (e.g. change some firefox config)?
