### ISSUE TITLE
? should look at __signature__

### ISSUE THREAD

**Issue by asmeurer** [ipython/ipython#3678]
I was watching http://pyvideo.org/video/1716/python-3-metaprogramming (intersting talk btw) and it was mentioned that Python 3 has this new feature `__signature__`, which lets you redefine what the signature of an object should be, which is used by things like inspect.signature. It is pointed out that `help` doesn't support this, but it would be great if IPython's `?` does. I checked however, and it doesn't (this is Python 3):

```py
In [2]: import inspect

In [3]: from inspect import Signature, Parameter

In [4]: a = Signature([Parameter('test', Parameter.POSITIONAL_OR_KEYWORD)])

In [5]: class Test:
    __signature__ = a
   ...:

In [11]: print(inspect.signature(Test))
(test)

In [12]: Test?
Type:       type
String Form:<class '__main__.Test'>
Docstring:  <no docstring>

In [18]: def f(*args):
   ....:     pass
   ....:

In [20]: f?
Type:       function
String Form:<function f at 0x1026ac0e0>
File:       /Users/aaronmeurer/Documents/ipython/<ipython-input-18-446f067045b6>
Definition: f(*args)
Docstring:  <no docstring>

In [21]: f.__signature__ = a

In [22]: f?
Type:       function
String Form:<function f at 0x1026ac0e0>
File:       /Users/aaronmeurer/Documents/ipython/<ipython-input-18-446f067045b6>
Definition: f(*args)
Docstring:  <no docstring>

In [24]: print(inspect.signature(f))
(test)
```

**Comment by Carreau** [comment]
works for function now : 

```
n [9]: f?
Signature: f(*args)
Docstring: <no docstring>
File:      ~/dev/notebook/notebook/static/notebook/<ipython-input-8-19c7cd79bebe>
Type:      function

In [10]: f.__signature__ = a

In [11]: f?
Signature: f(test)
Docstring: <no docstring>
File:      ~/dev/notebook/notebook/static/notebook/<ipython-input-8-19c7cd79bebe>
Type:      function
```
Not Class.

**Comment by asmeurer** [comment]
`inspect.signature` reads this directly. Any reason IPython couldn't just use that (in Python 3, of course)?

**Comment by minrk** [comment]
@asmeurer I believe we do call `inspect.signature` on Python 3, but if I read the logic correctly, we do it on `Class.__init__` in order to get a handle on the callable (for Python 2). Since we've adopted (and backported) signatures, I think we can skip grabbing `__init__`, and it should Just Work™

**Comment by minrk** [comment]
#9335 should remove the reaching into `obj.__init__`, and fix this.
