### ISSUE TITLE
Need for modern formatting of docstrings in inline `help(something)` and in separate `something?` window

### ISSUE THREAD

**Issue by dpsanders** [ipython/ipython#3687]
With the styling of the Notebook being in general so sleek and modern, and more so with upcoming CSS mods, there is one aspect of the look and feel that is almost stuck in a terminal in the 80s: the formatting of docstrings, both inline with `help(something)` and in the separate pop-out window that appears when doing `something?`

I have often felt that this makes it intimidating for new -- and not so new -- users to actually plunge in to understanding the function, with the various options being overwhelming.

And yet that are already solutions available: see the beautiful rendered docstrings in the `Spyder` editor, for example. I believe that they use `numpydoc` style, as in the `numpy` documentation, e.g. [here](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html#numpy.arange)

I realise that it is getting late (!) for 1.0, but I believe it would be a major enhancement.

Along the same lines, I suggest that the pop-out help viewer be moved from the bottom to the right, since there is always more horizontal wasted space available than vertical screen estate.

**Comment by jmansour** [comment]
another +1 for this. 

likely for any time soon?

**Comment by anntzer** [comment]
FWIW, simple handling of rst to html conversion can be implemented as in the `_parse_doc` and `_itertext_ansi` functions at https://github.com/evanunderscore/defopt/blob/master/defopt.py#L285 and https://github.com/evanunderscore/defopt/blob/master/defopt.py#L342.

**Comment by mbakker7** [comment]
Is there any update on this feature request? Has this maybe been implemented in the new Jupyter Notebooks that have been developed together with the Jupyter Lab?

**Comment by PhysRex** [comment]
Any update on this?

**Comment by Carreau** [comment]
> Any update on this?

No public one. I have thoughts and prototypes through the years, and there is the `c.InteractiveShell.sphinxify_docstring=True` option, but it does not work well.

I think I know how to solve it, but it's more than a week-end hack that will need some significant commitment.

**Comment by mbakker7** [comment]
Any thoughts on how we can get this feature request to the forefront of development? It would sure be a great addition.

**Comment by Carreau** [comment]
I'm working on that – the toughest part is finding funding. Expressing your interest here and saying for which projects and what desires you have for such a feature can help.

**Comment by twiecki** [comment]
+1 on this being an amazing feature, especially for building NBs that demonstrate API of a package. I would like to just do `help(MyClass)` and have it rendered well.

**Comment by mbakker7** [comment]
Is this something we could get funded in a Documentation grant? Maybe even Google Summer of Code or something like that? It has to do with making the documentation readable after we put so much effort in putting in the equations and such.

**Comment by Carreau** [comment]
I believe @stefanv and Jarrod Millman might be working on such a grant;  yes funding would be great, and I'm interested in helping with writing such a grant and I am trying to find a way to get some of my time funded next year if possible.

I doubt summer of code would be a good fit, maybe, but I think the challenging part is getting someone senior enough with time; to at least sketch the large part. GSOC is better suited for project with a narrow scope; and this – despite its apparent simplicity – is not.

**Comment by ivirshup** [comment]
I have a suggestion which is a bit of a different approach, but should be easier to implement and give the most flexibility around documentation writing and display to library authors.

What if I could easily open a new window or tab to the rendered api docs for a given function or object? That is, something like: `docs(np.linspace)` would open a [webpage to the docs](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)?

## Some advantages

### Relativley easy to implement

`ipython`/ `jupyter` doesn't need to know how to render the docs for any specific project. All it needs to do is open a link. This could even be as simple as having a link to the relevant doc page be included in the current help view.

### It will display right

This means library authors can use whatever custom extensions or doc generation systems they want without worrying that jupyter won't be able to render it correctly. If I use something like the `matplotlib` extension to have inline plot examples, these will still be viewable by the user. I don't see how an `ipython` based rendering system could do this reliably.

## Potential issues

The main difficulty I see will be getting a link to the doc page. I think this is solvable.

One approach would be to get the sphinx object inventory for a project like `intersphinx` does. This should work for a lot of python projects. I think this works as a fallback option, but has a number of downsides. It requires people use sphinx, and it requires the intersphinx mappings always work.

As an alternative, there could be an API for library authors to provide links to the documentation, similar to how `__getitem__` tab completion is handled. That is, a package could provide a function like `pkg._doc_address(pkg.obj)` which would return the url for relevant object. This has the advantage of being customizable. It's not dependent on authors using sphinx or any particular markup. It also makes it the author's responsibility to do things like link to the correct version of the docs.

There are also issues of 1) rendered doc pages not being available or 2) for the right version. I think solving 1) depends on how a link is accessed or displayed and 2) can be delegated to library authors.

**Comment by sambarluc** [comment]
> I have a suggestion which is a bit of a different approach, but should be easier to implement and give the most flexibility around documentation writing and display to library authors.
> 
> What if I could easily open a new window or tab to the rendered api docs for a given function or object? That is, something like: `docs(np.linspace)` would open a [webpage to the docs](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)?

I like this. As a side note, this is the same approach as the `fish` shell. In that case, I think that maintaining the links db is much easier, as they all come from the same source, but overall it's a perfectly fine system, which I tend to prefer nowadays to "classical" man pages.

Note however that it also implies some extra complication when working on a remote machine, e.g. over `ssh`.

**Comment by ivirshup** [comment]
Some work in going into this over at https://github.com/jupyter/papyri/issues/1
