### ISSUE TITLE
Add tab completion for `%config`

### ISSUE THREAD

**Issue by dpsanders** [ipython/ipython#3706]
Tab completion should be added for options for `%config`.

**Comment by tomowind** [comment]
@ellisonbg This seems fixed in master.

**Comment by takluyver** [comment]
Are you sure? If this was fixed, I'd expect to be able to tab complete things like:

```
%config Intera<tab>   -> InteractiveShell
%config InteractiveShell.<tab>   -> configurable attributes

**Comment by tomowind** [comment]
Sorry, I thought it was about autocompleting "%config" itself, not additional parameters. :)
