### ISSUE TITLE
ipython notebook - help window position

### ISSUE THREAD

**Issue by Tooblippe** [ipython/ipython#3711]
1. Currently the help window in the ipython notebook is at the bottom of the page. Is it possible to have this as a split window to the right of notebook (or the option to have it there).
2.  Making the help window disappear with the "Ctrl m - q" shortcut would also make it more in line with the REPL experience

**Comment by ivanov** [comment]
Hi @Tooblippe, thank you for your suggestion. I'm going through and closing old issues where it makes sense, and I think it makes sense to close this one. 

[JupyterLab](/jupyterlab/jupyterlab) moved a model where help output is displayed inline, with the additional functionality that outputs can be dragged out to their own vertical or horizontal panel, which is similar to the functionality you were seeking.

Happy hacking! :bowtie:
