### ISSUE TITLE
Allow output to be placed horizontally next to input cell

### ISSUE THREAD

**Issue by dpsanders** [ipython/ipython#3717]
Allowing, as an option, the output to be placed horizontally to the right of the input cell would make lots of workflows much more agile. 

As with #3711, most people have much more horizontal space available / wasted than vertical space. This should be taken advantage of more effectively. Having the output there would be an excellent way to do so. Indeed, this could even be considered as a default option.

**Comment by ivanov** [comment]
Hi David, thank you for your suggestion. I'm going through and closing old issues where it makes sense, and I think it makes sense to close this one.  This feature is available in [JupyterLab](/jupyterlab/jupyterlab).

Happy hacking! :bowtie:
