### ISSUE TITLE
ANSI escapes in nbconvert

### ISSUE THREAD

**Issue by ivanov** [ipython/ipython#3727]
These were added in 1.0, and nbconvert likely doesn't handle them properly at the moment. 

There's an example notebook under examples/tests/ANSI%2520Test.ipynb

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
