### ISSUE TITLE
connection files should contain serialization info

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#3832]
The parallel connection files already have pack/unpack keys. These should be included in regular kernel connection files.  Perhaps as a part of the next unification of parallel and regular kernel config / apps.

**Comment by dmanikowski-reef** [comment]
Hi guys, is this issue still valid?

**Comment by takluyver** [comment]
IMO we should simply declare that the protocol requires JSON packing (making this issue obsolete). This is what everyone uses anyway, except maybe the parallel machinery, which is a special case.

I don't think the advantages of any alternative serialisation format are worth the added complexity of making it switchable in different clients and kernels.
