### ISSUE TITLE
Additional "ghost" character in interactive terminal

### ISSUE THREAD

**Issue by eteq** [ipython/ipython#395]
When I use the latest master ipython, there seems to be an extra "ghost" character after the end of the input buffer.  If I scroll exactly to the last character in the current input buffer, and then scroll one (or any number, actually) character to the right, any input I type doesn't appear (although the cursor doesn't move) - the only thing I can do is scroll a character left or backspace, and although the cursor doesn't move, all of a sudden I'm back to the normal situation at the end of the line.

This happens on OS X 10.6 with 32-bit EPD, but *not* on Ubuntu 10.04 (haven't tried 10.10).  Let me know if any other debug info would be helpful.

**Comment by Carreau** [comment]
This is 4 years old, and with all the frontend refactor and usage of prompt_toolkit. 

Closing, 

Please reopen an issue if needed. 

Thanks.
