### ISSUE TITLE
need special exceptions for nbconvert stages

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#3950]
We should define exception classes in nbconvert that indicate stage failure (transform, post, etc.) distinct from a crash, so that the nbconvert app can show sensible errors rather than crash reports, and exit with a nonzero status code.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
