### ISSUE TITLE
Stale browser cache when serving local /files/

### ISSUE THREAD

**Issue by mcburton** [ipython/ipython#4004]
When serving up a local file through the Notebook webserver, if the file gets modified the version in the browser cache gets stale. In some cases it is difficult to force the browser to refresh those files. The current cache headers served up by the Notebook are  
 
An example from Fernando: Loading up image files served via /files/ but also changing those images on disk. The image files changes could only be detected by restarting the Notebook. 

Another example: I was writing JSON files to disk via the %%writefile magic and then loading them in in D3.js in a separate HTML file being served by the Notebook. I had to open the JSON files directly and shift-refresh to update the browser cache.  

I am not super familiar with the IPython codebase, but it looks like lines 322-330 in https://github.com/ipython/ipython/blob/master/IPython/html/base/handlers.py#L322 are the relevant place to tweak the server-side cache control. 

Possible solution, although I don't know the larger ramification, would be to set the headers `Expire` to `0`, `Cache-Control` to `max-age=0`, and `Cache-Control` to `private`

**Comment by minrk** [comment]
/files/ URLs should no longer be cached.
