### ISSUE TITLE
Feature request: Drop to shell at a given line of input file.

### ISSUE THREAD

**Issue by bashseb** [ipython/ipython#403]
Since python is interpreted line by line, shouldn't this be fairly easy to implement?

I thought this might be possible and posted this question on stackoverflow: http://stackoverflow.com/questions/5801906/ipython-pylab-debugging-can-i-stop-the-execution-at-a-specific-line-and-drop-in

Basically, I'm asking for a way to drop to the ipython shell before reaching the end of the code in order to inspect and test my code at the specific sub-routine. I prefer not to use the debugger:

E.g. stop at line 423 in bar.py

```
 ipython -pylab --stop-at bar.py:423 foo.py
```

or, stop at a subroutine name in bar.py

```
 ipython -pylab --stop-at bar.py:subroutine-name foo.py
```

thank you

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. An implementation of the proposed functionality was provided, but we are not going to add this as a command-line argument feature for IPython.

Another way to do this if you are able to edit the code in question is to add `import IPython; IPython.embed()` wherever you would like to instantiate IPython.

Thanks everyone and happy hacking! :bowtie:
