### ISSUE TITLE
Include keyboard shortcuts in notebook menus, button tooltips, and link titles

### ISSUE THREAD

**Issue by westurner** [ipython/ipython#4055]
It would be even easier to learn [IPython notebook](https://en.wikipedia.org/wiki/IPython#Notebook) [keyboard shortcuts](https://en.wikipedia.org/wiki/Keyboard_shortcut) if the keyboard shortcuts were displayed in menu menus, button tooltips, and link titles.
- https://github.com/ipython/ipython/blob/master/IPython/html/templates/notebook.html
- https://github.com/ipython/ipython/blob/master/IPython/html/static/notebook/less/quickhelp.less
- https://github.com/ipython/ipython/blob/master/IPython/html/static/notebook/less/tooltip.less
- https://github.com/ipython/ipython/blob/master/IPython/html/static/notebook/js/quickhelp.js
- https://github.com/ipython/ipython/blob/master/IPython/html/static/notebook/js/notebook.js#L139 (`document.keyDown`)

See Also:
- [KeyboardJS](https://github.com/RobertWHurst/KeyboardJS), [keymaster](https://github.com/madrobby/keymaster), 
- https://github.com/ipython/ipython/issues/977#issuecomment-2693113

**Comment by krassowski** [comment]
This appears to have been implemented in both Notebook (which now lives in a separate repository) and JupyterLab. Closing as completed.

**Comment by westurner** [comment]
JupyterLab also has a "Command palette" https://jupyterlab.readthedocs.io/en/stable/user/commands.html

- [ ] DOC: docs/: Keyboard Shortcuts;
  -  howto modify
     - e.g. how to fix:
       Split Cell doesn't work on a Chromebook because `Ctrl--` adjusts font size
       - `Ctrl-M -` is the emacs-style split Cell shortcut (which e.g. Colab has ootb)
     - How to add a shortcut for "Restart & Run all" && "Run all cells here and below"

> The command palette can be accessed from the View menu or using the keyboard shortcut Command/Ctrl Shift C.

Not CtrlP (like CtrlP.vim and now VScode), but Ctrl-Shift-C for the JupyterLab Command Palette (which makes it easy to search for keyboard shortcuts by command name) 

https://jupyterlab.readthedocs.io/en/stable/search.html?q=Keyboard&check_keywords=yes&area=default
