### ISSUE TITLE
don't instantiate CodeMirror for each cell at load

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#4169]
This is very expensive, and the primary limiting factor for loading notebooks with many cells.  Instantiating CodeMirror on first edit of a cell will help load performance a great deal.

We should do this after @ellisonbg's modal PR, since that will add a 'first edit' event to code cells, which doesn't really exist right now.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.

**Comment by williamstein** [comment]
For what it is worth, I tried to implement this approach with CoCalc Jupyter, but eventually gave up (for now), due to it requiring re-implementing too much of CodeMirror.  It’s a huge can of worms.

**Comment by jasongrout** [comment]
Thanks for sharing your experience, @williamstein. @blink1073 also tried implementing this in JupyterLab, and gave up after working on it for a while for similar reasons - it's a huge can of worms.
