### ISSUE TITLE
nbconverted latex fails to compile on notebook with Unicode characters

### ISSUE THREAD

**Issue by Keno** [ipython/ipython#4244]
Consider the following IJulia notebook: http://nbviewer.ipython.org/6646942.
Trying to convert this to PDF via latex results in the error:

```
(/usr/local/texlive/2013/texmf-dist/tex/latex/ucs/data/uni-1.def)
! Undefined control sequence.
\u-default-295 #1->\texthbar

l.271 \PY{err}{ħ}
                   \PY{o}{=} \PY{l+m+mf}{1.05457} \PY{o}{*} \PY{l+m+mf}{10.0...
```

Another issue is a somewhat ugly red box arround unicode characters in the HTML-converted version, but I suppose that problem lies in the syntax highlighter. 

OS is Mac OS 10.8. Latex distribution is MacTex. 

Refs https://github.com/JuliaLang/IJulia.jl/issues/75

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
