### ISSUE TITLE
Support for custom authentication in Tornado handlers

### ISSUE THREAD

**Issue by sychan** [ipython/ipython#4262]
I'm working on adding authentication support to IPython and after looking at the code, it looks like it is easy enough to do if you are willing to either:
   1) Fork the code
   2) Monkeypatch the request handlers

   Neither of these are very appealing (though I would much rather monkeypatch then fork). Are there any other options that could be implemented? I'm sure that other people are interested in this as well especially now that Docker is a viable means provisioning per user notebooks.

   What I am trying to do specifically is to add an HTTP Authorization header to each request that contains an authentication token, and have the handlers verify the validity of the token before servicing the request. Its easy to do and a common approach. I actually need access to the token for backend web service requests. I can override the front end HTML templates and have already modified the javascript to add the headers to the ajax requests, but I am blocked on the backend.

   An alternative might be to setup configurable handlers for /login and /logout and have the front end register the authentication token with the login handler and receive a secure session cookie that references the . Code on the backend such as notebook handlers would have to have access to the session object to authenticate the user for access to data.

   What do people think?
   Steve

**Comment by ellisonbg** [comment]
@minrk this is an older issue on notebook auth. Is it still relevant?

**Comment by minrk** [comment]
@ellisonbg this should be addressed now
