### ISSUE TITLE
Displayed matplotlib figures get grey background since 1.0

### ISSUE THREAD

**Issue by jorisvandenbossche** [ipython/ipython#4307]
If you display matplotlib figures with `display(fig)` or just by returning `fig` (so without the inline backend enabled), these figures have a grey background color in the border (as the figures also have in the seperate matplotlib figure window when interactive plotting is on) since 1.0. 
See eg:
- With IPython 1.0: http://nbviewer.ipython.org/5868420/ipython-figure-grey-background.ipynb
- With IPython 0.13 (white background): http://nbviewer.ipython.org/5868420/ipython-figure-grey-background-0.13.ipynb

Is this a deliberate change? I think the previous white background was better for in the notebook. 
You can change this manually if you set in the beginning of each notebook: `matplotlib.rcParams['figure.facecolor'] = 'w'`

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.

**Comment by jorisvandenbossche** [comment]
BTW, this issue is solved with matplotlib 2.0, where the figure background is no longer grey by default. 
So fine to have this closed!

**Comment by Carreau** [comment]
> BTW, this issue is solved with matplotlib 2.0, where the figure background is no longer grey by default.
> So fine to have this closed!

Sweet ! Thanks for noticing and taking the time to write a message !
