### ISSUE TITLE
Markdown formatter

### ISSUE THREAD

**Issue by minad** [ipython/ipython#4329]
Would it make sense to add a markdown formatter and _repr_markdown_ to directly support markdown output for some mimetype text/x-markdown?

**Comment by JanSchulz** [comment]
Is there any news on this issue? I'm currently building a knitr clone (https://github.com/JanSchulz/knitpy) with the ipython infrastructure (mainly kernels and the display framework) and the lack of a proper way to get markdown formatted tables starts to bite me: including html formatted tables in documents which should be converted to html is fine, but converting html tables to docx does not work.

It would be nice if IPython could take the lead and define a `_repr_mimetype(mimetype)` or similar mechanism and also include a default output type in the kernels (so instead of using html one could define that markdown should be tried first)

**Comment by Carreau** [comment]
```
from IPython.display import Markdown
Markdown??
###
class Markdown(TextDisplayObject):

    def _repr_markdown_(self):
        return self.data
```
??

So closing this issue ?

Table are another problem as are not standard markdown. Don't know if they are supported.

**Comment by JanSchulz** [comment]
I know that I can add user code to send something via the display framework. IMO this bugreport is about a generic way to get markdown from any object, similar to the way you get html from any object now.

```python
df = pd.DataFrame(...)
df
```
would result in markdown instead of html in the "execute_result" message.

**Comment by takluyver** [comment]
It's up to the class what output formats it supports. You get html from a
dataframe because it has a _repr_html_ method. IPython doesn't decide what
output formats different objects have.

**Comment by JanSchulz** [comment]
OK, I dug into the thing here to see what's working already:

`IPython.core.formatters` already implements `_repr_markdown_` as the way to get markdown format, so it seems that the original issue is already done. 

This is alos advertised in the usage (from `IPython.core.usage`)
> Python objects can simply be passed to these functions and the appropriate
> representations will be displayed in the console as long as the objects know
> how to compute those representations. The easiest way of teaching objects how
> to format themselves in various representations is to define special methods
> such as: ``_repr_html_``, ``_repr_svg_`` and ``_repr_png_``. [...]

On the other hand we have the second comment above form @Carreau, which states that '_repr_whatever_` should not be the way it should work.

**Comment by minrk** [comment]
We also planned, but ran out of time to design and implement for 3.0, a mechanism for arbitrary mime-types without `_repr_foo_`, since that's not a pattern that can be extended to all mime-types.

Something along the lines of:

```python
def _repr_mimetypes_(self):
    return {
        'application/postscript' : self._to_eps,
        'text/x-fortran': self._to_fortran_for_some_reason,
    }
```

**Comment by JanSchulz** [comment]
as "get all mimetypes" is IMO pretty uncommon outside of ipythons display system, I would vote for 

```
def _repr_mimetype_(self, mimetype):
   if not mimetype in suported_mimetype:
       return None
   else:
       formatter = suported_mimetype[mimetype]
       return formatter()
```

**Comment by Carreau** [comment]
> as "get all mimetypes" is IMO pretty uncommon outside of IPythons display system

For All object of IPython  all mimetypes are computed. All mimetypes are supported and store in notebook format. It is **the point** of IPython display system.

**Comment by JanSchulz** [comment]
I'm not sure how far `_repr_html_` is used outside of IPythons display system and whether you want to take such consideration into account at all, but `_repr_html_` is the de facto way "to get the html representation of the object". If something else than IPython wanted to use this interface, it's no problem, but a `_repr_mimetypes_()` would be strange for any other case than sending such a dict over the kernel-wire.
