### ISSUE TITLE
Multiple kernels and variable passing between them

### ISSUE THREAD

**Issue by minad** [ipython/ipython#4386]
Some magic functions could be implemented in a language agnostic way. For example there are the %script commands to call other programs. If somebody implements a Julia/Ruby/R kernel they have to reimplement the whole magic functionality. Could it be possible that IPython somehow routes the cells to different kernels or intercepts the evaluation?

**Comment by BoPeng** [comment]
Hi, Carreau,

I found this issue because of a need to execute R code from my SoS kernel (http://github.com/BoPeng/SOS). Instead of communicating with rpy2 etc and re-inventing all the wheels, I thought it would be nice to keep an instance of an IR kernel and communicate with it. Something like

```
    def do_execute(self, code, silent, store_history=True, user_expressions=None,
                   allow_stdin=False):
         # ...
         if self.R_mode:
              if self.r_kernel is None:
                    self.r_kernel = ??start_IR_kernel()
              return self.r_kernel.do_execute(code, silent, store_history, user_expressions, allow_stdin)
```

I understand your reservation on this multi-kernel thing back in the ipython age, but has the evolution of jupyter made it possible? Are you aware of any project that implements similar ideas?

**Comment by BoPeng** [comment]
After a bit more reading, it seems that this is completely doable, and the following code seems to be working

```
from jupyter_client import manager
KM, KC = manager.start_new_kernel(startup_timeout=60, name='ir')
msg=KC.execute('1+1')
res = KC.iopub_channel.get_msg(block=True, timeout=1)
```

**Comment by takluyver** [comment]
Yep, that's an easy way to start any other kernel. The limitation is that the sub-kernels don't share variables or anything with your main kernel (or each other). You can use the filesystem to share data, or come up with some way to exchange data between processes (like the beaker notebook does).

**Comment by ivanov** [comment]
I am going through a round of cleaning up old stalled issues, and this one cropped up and the discussion seems to have died down. The summary that I gather is that ipython/jupyter will not be supporting multiple kernels for a single notebook with variables being passed around between them, so I am closing this issue.

**Comment by Carreau** [comment]
Thanks @ivanov for the help in cleaning up issues. 

For cross language integration you can see (for example) a blog post I wrote about that:

http://carreau.github.io/posts/23-Cross-Language-Integration.html

Where R, Rust, C, Fortran, Julia talk to each other.

**Comment by BoPeng** [comment]
Well, a new [SoS](https://github.com/BoPeng/SOS) (Script of Scripts) kernel supports multiple kernels using magics `%use` (switch to another kernel) and `%with` (use another kernel for current cell), and limited exchange of data using magics `%get` (get variable from sos dict) and `%put` (put variables to sos dict). Data exchange is currently limited to the python and `ir` (R) kernels but can certainly be extended later.

Note that SoS is a workflow system so although the sos kernel can be used similar to a Python 3 kernel, using SoS directives such as `input:` and `output:` provides additional features such as preview of output files.
