### ISSUE TITLE
%%px and %px commands take long time to run, outputing nothing

### ISSUE THREAD

**Issue by carlding** [ipython/ipython#4395]
I'm a newbie to ipython parallel computing. I have installed ipython 1.1.0 on both controller and 3 engines, and all engines can register themselves on the controller.

I can get correct engine list after executing the following code on the controller:
from IPython.parallel import Client
rc = Client(profile='myprofile')
rc.ids
[3, 4, 5]

However, when I execute the following code:
%%px
import os
import socket
print("This is running in process with pid {0} on host '{1}'.".format(os.getpid(), socket.gethostname()))

there is no output at all, and the code takes around 20 seconds to run. I have turned on the debug information on the engine side using the option --log-level=DEBUG. It seems that all the engines have received the requests.

Please enlighten me how I can solve this problem. Thanks.

**Comment by Carreau** [comment]
Closing as inactive.
