### ISSUE TITLE
Notebooks don't detect kernel shutdown

### ISSUE THREAD

**Issue by ivanov** [ipython/ipython#4429]
Right now, if you have a notebook open, whose kernel was shutdown, that notebook's javascript does not know that the kernel was shutdown.

**Comment by ellisonbg** [comment]
Hmmm, we should look into this and see if it is still an issue...

**Comment by minrk** [comment]
This is still an issue. I think we can bump it past 3.0.

**Comment by ellisonbg** [comment]
OK bumping to 4.0
