### ISSUE TITLE
BdbQuit exception when quitting ipdb

### ISSUE THREAD

**Issue by xuyuan** [ipython/ipython#4474]
Since version 1.1.0, I have problem when quitting ipdb
# system info:

``` python
import IPython; print(IPython.sys_info())
```

{'codename': 'Work in Progress',
 'commit_hash': '1afe8a5',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python2.7/dist-packages/IPython',
 'ipython_version': '2.0.0-dev',
 'os_name': 'posix',
 'platform': 'Linux-3.8.0-33-generic-x86_64-with-Ubuntu-13.04-raring',
 'sys_executable': '/usr/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.4 (default, Sep 26 2013, 03:20:26) \n[GCC 4.7.3]'}
# minimal reproducible case:

``` python
run -d scripts/ipython_win_post_install.py
```

**\* Blank or comment
**\* Blank or comment
**\* Blank or comment
**\* Blank or comment
NOTE: Enter 'c' at the ipdb>  prompt to continue execution.

> /home/xu/soft/python/ipython/scripts/ipython_win_post_install.py(6)<module>()
>       5 
> ----> 6 """
>       7 

``` python
ipdb> q
```

ERROR: An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (127, 72))

ERROR: An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (127, 72))

---

BdbQuit                                   Traceback (most recent call last)
/usr/local/lib/python2.7/dist-packages/IPython/utils/py3compat.pyc in execfile(fname, *where)
    212             else:
    213                 filename = fname
--> 214             builtin_mod.execfile(filename, *where)
    215 
    216 # Parts below taken from six:

/home/xu/soft/python/ipython/scripts/ipython_win_post_install.py in <module>()
      4 http://docs.python.org/2/distutils/builtdist.html#the-postinstallation-script
      5 
----> 6 """
      7 
      8 from **future** import print_function

/home/xu/soft/python/ipython/scripts/ipython_win_post_install.py in <module>()
      4 http://docs.python.org/2/distutils/builtdist.html#the-postinstallation-script
      5 
----> 6 """
      7 
      8 from **future** import print_function

/usr/lib/python2.7/bdb.pyc in trace_dispatch(self, frame, event, arg)
     47             return # None
     48         if event == 'line':
---> 49             return self.dispatch_line(frame)
     50         if event == 'call':
     51             return self.dispatch_call(frame, arg)

/usr/lib/python2.7/bdb.pyc in dispatch_line(self, frame)
     66         if self.stop_here(frame) or self.break_here(frame):
     67             self.user_line(frame)
---> 68             if self.quitting: raise BdbQuit
     69         return self.trace_dispatch
     70 

BdbQuit:

**Comment by user202729** [comment]
For what it's worth, if one want to debug something and want to print out the traceback of `BdbQuit` object, it's possible to explicitly catch it at the top level and reraise something else, or `traceback.print_exc()`.

A possibly useful feature may be, if the user code contain just `raise BdbQuit`, warn the user of this behavior.
