### ISSUE TITLE
Notebook takes 30 sec to load

### ISSUE THREAD

**Issue by jankatins** [ipython/ipython#4484]
I've a notebook which takes 30 sec to load. It has a few plots in it and is quite long, but I've other notebooks which also have plots and are "long" (or at least have lots of output) and they load much faster. 

I have also yesterday switched to a newer ipython version from git and my feeling is that this long loading times are only since I updated (no hard data, but I never noticed long loads before when I opened this notebook. Unfortunately, I've deleted my last installer/git references, so I can't say how old the last version was. Probably 1-2 month old) 

The notebook can be found here: https://www.dropbox.com/s/fy461tnic67vdth/Testen.ipynb
or nbviewer: http://nbviewer.ipython.org/urls/dl.dropboxusercontent.com/s/fy461tnic67vdth/Testen.ipynb?dl=1&token_hash=AAFnIscbA5TMyRhDMA9r3Bru38bwviKaQUIeHMwP7EyesQ

If you have any suggestions how do debug such issues (chromes "inspect element" seems to suggest that it's not network latency: all GET/POSTs are within ms), I would be happy to help!

[Note: this notebook is my "debugging and testing" Notebook, so all kind of stuff is in there, which probably does not make much sense and probably does not run...]

**Comment by dlukes** [comment]
This is still the case in both the classic notebook and JupyterLab (I have a notebook with no plots, just a lot of small cells). Maybe this issue should be moved to https://github.com/jupyter/notebook and/or https://github.com/jupyterlab/jupyterlab, now that these are projects separate from IPython?
