### ISSUE TITLE
Output for semicolon-terminated lines with comments

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#4525]
cf https://github.com/JuliaLang/IJulia.jl/issues/109

The output of a semicolon-terminated line with comment is not suppressed in IPython.

```
b = 1
b; # foo
```
give `Out[13]: 1`
```
b = 1
b;
```
does not.

Havent found such and issue on our tracker.

 @takluyver you are the best with the input machinery and coroutines; Thoughts ?

(Because of the comment @stevengj in sus-cited issue, marking as prio-high, but won't  mind if priority decreased later, or not fixed)

**Comment by xflr6** [comment]
#9228 adapts the semicolon detection to address the remaining prolematic cases.
