### ISSUE TITLE
move some part of banner1 to banner2

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#4556]
Especially with non-python kernel part of banner are irrelevant (and confusing?)
and are not profile-configurable (at least in console) as are pre-profile loading: 

Example :

```
Python 2.7.5 (default, Sep 12 2013, 13:55:48)
Type "copyright", "credits" or "license" for more information.

IPython 2.0.0-dev -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

IPython profile: julia

banner2:this is s julia kernel julia
Starting kernel event loops
```

Still the IPython version is relevant for the frontend and might help debug.

**Comment by ellisonbg** [comment]
Honestly, I think we should get rid of most of the banner. Folks have gotten used to using the notebook without all of this stuff. I think we could simplify the banner to something super minimal that just shows the name of the kernel.

**Comment by damianavila** [comment]
> Honestly, I think we should get rid of most of the banner. Folks have gotten used to using the notebook without all of this stuff. I think we could simplify the banner to something super minimal that just shows the name of the kernel.

I agree... a minimal reference... maybe one line is enough...

**Comment by Achifaifa** [comment]
I actually did exactly this (before realising I could set display_banner to false) last week. How's this?

IPython 2.0.0-dev (Python 2.7.5) -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

Removing the hints or the 'enhanced interactive python' is also trivial, so whatever you like the most.

**Comment by jzf2101** [comment]
@takluyver @Carreau Is this ready to close based on #9912 ?

**Comment by takluyver** [comment]
Yes, it looks like we've consolidated and basically got rid of banner2.
