### ISSUE TITLE
IronPython support

### ISSUE THREAD

**Issue by ksachdeva** [ipython/ipython#4557]
Hi,

I was trying using IPython with IronPython and one of main bug I encountered (from IPython side) was that in IPython\utils\process.py you use sys.platform == 'win32' where it is should be sys.platform == 'win32' or sys.platform == 'cli' (and also a check to see that we are not on mono) to make it work on windows platform using IronPython

Regards
Kapil

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. IronPython support was updated by @dsblank in #5055 (Thanks Doug!).

Happy hacking! :bowtie:
