### ISSUE TITLE
Deadlock due to readline

### ISSUE THREAD

**Issue by abrasive** [ipython/ipython#4857]
Hello lovely developers,
readline <=6.2 calls malloc() from inside its SIGWINCH handler. This is naughty since it's not reentrant - if the signal comes during a malloc() call, as it frequently does under tiling window managers with GUI windows open, the process deadlocks (under Linux glibc; some other systems get corrupted heaps instead).

This is not your fault, and it is corrected in readline-6.3rc1 as far as my testing goes. There's also no way to work around it given the limited python readline interface, other than to ignore SIGWINCH after readline initialises.

Given the number of deployed systems with readline <=6.2 (all of them), and the potential for data loss (I've had many sessions die this way, and lost some serious work today), I would request that you either:
- put in a warning for old readline users that this may happen, or
- disable SIGWINCH if an old readline is detected (and presumably notify the user)

This is not specific to GUI eventloops, it just happens to be particularly easy to trigger under a tiling WM where the terminal and GUI windows are simultaneously resized on a frequent basis.

Thanks for all the great work!
- James

**Comment by ivanov** [comment]
Hey there @abrasive, thank you for filing this report, it's too bad we didn't end up acting on it back when you filed it, given how much information you provided. I'm going through old issues and it seems to me that it makes sense to close this one, as we have moved away from using readline, and now use prompt_toolkit instead.

Happy hacking! :bowtie:
