### ISSUE TITLE
tab completing matplotlib

### ISSUE THREAD

**Issue by moorepants** [ipython/ipython#4877]
Now that there is `%matplotlib` magic, I miss being able to tab complete on matplotlib.

```
In [2]: import matplotlib

In [3]: matplo
%matplotlib  matplotlib   

In [3]: matplot
%matplotlib  matplotlib   

In [3]: matplotl
%matplotlib  matplotlib   

In [3]: matplotli
%matplotlib  matplotlib   

In [3]: matplotlib
%matplotlib  matplotlib   

```

Should magics try to tab complete if you happen to have a variable in the name space that is the same name as a magic?

**Comment by evectant** [comment]
@Carreau I can submit a PR for this, but I see that `test_completer:test_magic_completion_order` pins down that behavior specifically:
```python
# After the import, there should be two options, ordered like this:
text, matches = c.complete('mat')
nt.assert_equal(matches, ["matplotlib", "%matplotlib"])
```

**Comment by Carreau** [comment]
I don't think it is still that much of an issue with prompt-toolkit. We can change the test if we have a better behavior, they are not fixed in stone. 

![mpl](https://cloud.githubusercontent.com/assets/335567/25962242/d1e59558-3631-11e7-87f2-5a8773890c53.gif)

But PR welcome of course.

**Comment by srinivasreddy** [comment]
Safely closed? @carreau

**Comment by takluyver** [comment]
Yup, thanks
