### ISSUE TITLE
Need multiple undo delete cell in new notebook

### ISSUE THREAD

**Issue by fonnesbeck** [ipython/ipython#4924]
The IPython 2.0 modal notebook interface makes it very easy to delete cells accidentally relative to the 1.x interface; I do it pretty regularly. Hence, I think its very important to be able to undelete more than just the last deleted cell.

**Comment by ggventurini** [comment]
Please consider this, it's still an issue in IPython 3 / Jupyter -- I just inadvertently deleted my work holding down by mistake the 'x' key. :/

**Comment by anriseth** [comment]
Seconded

**Comment by Carreau** [comment]
migrated to jupyter/notebook#712
