### ISSUE TITLE
auto-completion should not work when asking exit confirmation after ctrl-D

### ISSUE THREAD

**Issue by moreandres** [ipython/ipython#4968]
When I hit ctrl-D to end a session and I got a confirmation request, the auto-completion (moving up or down) shows things from my previous commands inside the ipython shell. I think it should not do that.

amore@ubuntu:/tmp/ipython$ python -m IPython
Python 2.7.3 (default, Sep 26 2013, 20:03:06)
Type "copyright", "credits" or "license" for more information.

IPython 2.0.0-dev -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: str='string'

In [2]:
Do you really want to exit ([y]/n)? str='string'
Do you really want to exit ([y]/n)? y

**Comment by fperez** [comment]
On master we are now using the prompt_toolkit implementation, which doesn't have this problem any more. Closing for now, reopen if necessary...
