### ISSUE TITLE
Comm code is not run in the same context as notebook code

### ISSUE THREAD

**Issue by jdfreder** [ipython/ipython#5006]
Discovered because of #4983 

Things like tracebacks are not getting displayed in the notebook.  There is a lot of logic in the zmq shell stuff that doesn't get ran for comm msgs...

**Comment by jdfreder** [comment]
Reopening, this is still a problem, see ipython/ipywidgets#44

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
