### ISSUE TITLE
make Qt console key bindings configurable

### ISSUE THREAD

**Issue by mspacek** [ipython/ipython#502]
From discussion in #496, I think I'd like to take a crack at making the qt console key bindings configurable. Of course, if anyone else wants to do it, that would be great too!

Fernando wrote:

> It seems to me the right way to do this is to wait for #492 to get merged (almost ready).  At that point, the Qt console will have a proper config file support, and it will be much easier to experiment.  

> This is, for example, the format used by LyX:
<pre>
\bind "C-e" "line-end"
\bind "C-a" "line-begin"
\bind "C-d" "char-delete-forward"
\bind "C-i" "font-emph"
\bind "C-S-t" "buffer-update pdf2"
</pre>

> which follows how Emacs describes keybindings as well.

> I don't think the `\bind` syntax looks particularly nice, but the key descriptions seem fine, and it's just a matter for us of sorting out how to describe actions.

**Comment by Carreau** [comment]
This has been open for 4 years and the qtconsole has been moved to it's own repository. 
I would suggest moving the issue there to get slightly more visibility. 

I'm going to close this one for now, as it is buried deep beneath thousands of others, but feel free to reopen if needed. 

Thanks.
