### ISSUE TITLE
Group multiple cells together as one unit using shift button

### ISSUE THREAD

**Issue by ArcTanSusan** [ipython/ipython#5180]
Wishlist feature request on the UI: I want to be able to group multiple cells (of any type) together using the shift button and then move the group altogether up or down as one unit when I press the up/down arrow.

**Comment by naught101** [comment]
It'd be great if grouped cells could be collapsed together, as per https://github.com/ipython/ipython/issues/7923

**Comment by JoeCodeswell** [comment]
+1

**Comment by asifm** [comment]
I think this issue should be closed. Multi-cells selection is possible since Jupyter 4.1. https://blog.jupyter.org/2016/01/08/notebook-4-1-release/

After selecting multiple cells as described below, you can press `X` to cut the cells or `C` to copy. Then move to the cell below which you want to see the cut/copied cells and press `V`. 

>Multi-cell selection is an often requested feature. The new version of the notebook includes the ability to select multiple cells and perform commands on them. Not all cell commands can be performed on multiple cells yet, but the basic API exists and can be used for extensions.

>To select a contiguous block of cells while in command mode, press Shift-J or Shift-K (also Shift-Down or Shift-Up) to extend and shrink the selection. Or you can hold Shift and left click on a cell to select a range of cell. The selected cells can be visually distinguished from the unselected ones by their soft blue background.

>Many cell commands operate now on the selected cells. For example, merging cells (Shift-M) used to merge current with the cell below it. It still does that for a single selected cell, but now it also merges all selected cells together.

**Comment by takluyver** [comment]
Yep, multi cell selection is now possible. We hope to add ways to select cells based on headings, but I think this can be closed now.
