### ISSUE TITLE
Change cache handling to First-in First-out

### ISSUE THREAD

**Issue by pchanial** [ipython/ipython#5249]
The long warning that is issued when the cache limit is exceeded (if I set it to 5, for instance) was disrupting my work flow:

```
WARNING: Output cache limit (currently 5 entries) hit.
Flushing cache and resetting history counter...
The only history variables available will be _,__,___ and _1
with the current result.
```

If I explicitly set the cache size to be a given number I expect it not to be greater than that, so I felt this warning was useless to me.

Then I realized that IPython cache system flushes entirely the cache when the limit is reached, instead of removing the oldest entries (FIFO), which is a more expected method to cache data.

**Comment by blackmagic02881** [comment]
this issue was fixed already. here is the related commit.
commit 1f09dea1486145364608de5ce959bef3653c2681
Author: Min RK <benjaminrk@gmail.com>
Date:   Thu Nov 13 15:47:09 2014 -0800

    cull 20% when display hook is full

    instead of 100%

**Comment by ellisonbg** [comment]
Closing this one as fixed.
