### ISSUE TITLE
every cell erroniously repeated

### ISSUE THREAD

**Issue by niallrobinson** [ipython/ipython#5315]
The text in every cell in my notebook has been repeated. It just runs on from the previous line with no new line. I'm afraid that I can't reproduce the bug - sorry I can't be more helpful. Has anyone seen this before?

**Comment by Carreau** [comment]
Do you still have this ?

**Comment by Carreau** [comment]
I'm going to close this one for inactivity

**Comment by niallrobinson** [comment]
haven't seen it in ages - happy for it to be closed
