### ISSUE TITLE
Allow to select multiple in select widgets

### ISSUE THREAD

**Issue by dawehner** [ipython/ipython#5327]
It would be kinda helpful for some usecases to be able to configure a SelectWidget to have multiple selections instead of just one

Maybe something like this could work
```
def helper(a):
    print a

interact(helper, a=SelectWidget(values = ['a', 'b', 'c'], multiple=True))
```

Thank you in advance
PS: is there any reason to append tags to new issues?

**Comment by bollwyvl** [comment]
Fixed by #6890!

Here's the [new API](http://nbviewer.ipython.org/github/ipython/ipython/blob/8cd71d912654c02d2d3678bb3501caad4b924de8/examples/Interactive%20Widgets/Widget%20List.ipynb#Selection-widgets)!

**Comment by bobbysan** [comment]
Selecting multiple items using the SelectMultiple widget does not work in some cases for me. If the selected options are highlighted using only the mouse (and are contiguous) it works fine. If selecting only apples and bananas (using Shift and Ctrl) in the example below it does not work. It will highlight/select the last item clicked. Please advise. Thanks.

```python
w = widgets.SelectMultiple(
    description="Fruits",
    options=['Apples', 'Oranges', 'Pears', 'Grapes', 'Peaches', 'Bananas'])
display(w)
```

My setup:
ipython-verson: 3.1.0-dev & 3.0.0 (tried both)
platform: windows 7

**Comment by bollwyvl** [comment]
Confirmed.

It is actually, really briefly, correct, but then the super `change`
handler fires and clobbers the new, correct value.

**Comment by jdfreder** [comment]
I'll copy this over to an issue so we can track it.
