### ISSUE TITLE
HTML cells with javascript get incorrect mouse position, shifted by presence of other cells.

### ISSUE THREAD

**Issue by jdavidheiser** [ipython/ipython#5338]
I noticed an odd mouse positioning bug today, and spent a LOT of time trying to track this particular one down, initially believing the bug to be on my end.

The issue I'm seeing can be demonstrated by loading the following ipynb file, which includes HTML / javascript output of a graphing command.  If you mouseover the generated graph, a descriptive popup will appear.

In a normal interactive IPython notebook, the mouseover popup will be shifted, and the amount of shift depends on the size of the cells above the graph.

By comparison, when viewed using nbviewer, the popup is positioned correctly.

https://gist.github.com/jdavidheiser/dcc11d85448ebf862521
http://nbviewer.ipython.org/gist/anonymous/dcc11d85448ebf862521

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
