### ISSUE TITLE
%edit session mangling terminal output

### ISSUE THREAD

**Issue by jayboyd** [ipython/ipython#5344]
This seems to be some interaction between emacs and ipython, but I've found that if I ever do a Ctrl-G (emacs for quit current command), the screen gets completely hosed with random text from both the emacs session and the ipython shell, and only some characters input are received, forcing me to do a Ctrl-D to kill ipython, after which my terminal shell has normal output but does not correctly take input so I have to kill it as well. 

ipython 1.2.1, OS X 10.9.2, python 2.7.5

**Comment by ivanov** [comment]
Thank you for your report, @jayboyd, I'm going through old issues and going to close this one due to inactivity. Hopefully this got sorted out for you.

Happy hacking! :bowtie:
