### ISSUE TITLE
Widgets lacking  __doc__?

### ISSUE THREAD

**Issue by yarikoptic** [ipython/ipython#5381]
Might be just a problem with my installation of ipython (from yesterdays c2ab228):

Checked ```widgets.FloatSliderWidget?``` and got only

```
Type:            MetaHasTraits
String form:     <class 'IPython.html.widgets.widget_float.FloatSliderWidget'>
File:            /usr/lib/python2.7/dist-packages/IPython2X/IPython/html/widgets/widget_float.py
Init definition: widgets.FloatSliderWidget(self, *pargs, **kwargs)
Docstring:       <no docstring>
Init docstring:  Constructor
```

So it seems that none of the traits docs were used to populate a sensible __doc__?

**Comment by amcdawes** [comment]
I think this is resolved. I wasn't able to find any widgets without docstrings. The particular function raised in this issue `widgets.FloatSlider` was resolved by commit 22fe3a683dc27c42546e48abf1fdaa119b8d223a
