### ISSUE TITLE
Restore shell profile

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#547]
The 'pysh' (aka 'sh') profile does nothing in 0.11 beyond redraw the prompt in a more bash-y way.  None of the actually useful bits described in the interactive/shell doc have been updated to the new APIs.

This functionality should be restored.

**Comment by ivanov** [comment]
Hi there, I'm going through cleaning up old issues and I see that https://github.com/ipython/ipython/pull/6838 was closed in 2014 (see that issue for the rationale) so I'm going to close this as well.  

Happy hacking! :bowtie:
