### ISSUE TITLE
Custom notebook keyboard shortcuts inconsistiencies

### ISSUE THREAD

**Issue by juhasch** [ipython/ipython#5542]
The example notebook describes how keyboard shortcuts can be customized in the IPython Notebook 2:
http://nbviewer.ipython.org/github/ipython/ipython/blob/2.x/examples/Notebook/User%20Interface.ipynb

There are some issues with this:
 * `display_command_shortcuts()` and `display_edit_shortcuts()` doesn't work anymore.
* defining your own shortcut can lead to strange effects if you use `+` instead of  `-` to combine shortcut keys. In the example notebook, the key combinatons like `Ctrl+s` are somtimes decribed using `+` or `-`.

Now if you do
```javascript
%%javascript
IPython.keyboard_manager.edit_shortcuts.add_shortcut('Alt+r', {
    help : 'run cell',
    help_index : 'zz',
    handler : function (event) {
        IPython.notebook.execute_cell();
        return false;
    }}
);
```
instead of 
```javascript
%%javascript
IPython.keyboard_manager.edit_shortcuts.add_shortcut('Alt-r', {
    help : 'run cell',
    help_index : 'zz',
    handler : function (event) {
        IPython.notebook.execute_cell();
        return false;
    }}
);
```
unrelated keys like `#`or `^` are starting to do strange things in edit mode.

**Comment by minrk** [comment]
This notebook has been moved to the [ipython-in-depth tutorial](https://github.com/ipython/ipython-in-depth/blob/master/examples/Notebook/Custom%20Keyboard%20Shortcuts.ipynb), and the examples there appear to be up to date for 3.0.
