### ISSUE TITLE
Notebook: convert URL to link fails when delayed

### ISSUE THREAD

**Issue by ymost** [ipython/ipython#5544]
Consider the following snippet in a notebook:
```python
for i in range(10):
    time.sleep(0.2)
    print('http://www.google.com/')
```

Only the first 2 output lines are converted into links, but when the ```sleep``` method is commented out, all 10 output lines are converted into links.

IPython version: 1.1.0
Python version: 2.7.6
OS: Windows 8.1 64bit

**Comment by abeguerra** [comment]
In OutputArea.prototype.append_stream there are two code paths for rendering output. 

In code path A - have at least one output to consider
```
// latest output was in the same stream, 
// so append directly into its pre tag
// escape ANSI & HTML specials:
```
OutputArea.append_text() is called which includes a call to utils.autoLinkUrls(). utils.autoLinkUrls() wraps the appropriate HTML around a URL. 

In code path B - 
```
// If we got here, attach a new div
```
the call to utils.autoLinkUrls() is not made and the URL is not wrapped with appropriate HTML.

I propose the addition of a call to utils.autoLinkUrls() in code path B to ensure hyperlinks are rendered correctly.

When URL rendering was added in commit below utils.autoLinkUrls() was not added to code path B
https://github.com/ipython/ipython/commit/b4ab213a87a3a77e9d95009542d75dde1b2dc3bc
https://github.com/ipython/ipython/blob/b4ab213a87a3a77e9d95009542d75dde1b2dc3bc/IPython/frontend/html/notebook/static/js/outputarea.js
