### ISSUE TITLE
Secured IPython Notebook server "login loop" with Chrome on redhat (local network)

### ISSUE THREAD

**Issue by sjobeek** [ipython/ipython#5572]
While attempting to set up an IPython Notebook server running on a redhat linux machine at work to access over the corporate network, I ran into a strange login loop issue when attempting to access the server with Chrome. 

I could reach the login page successfully with both chrome and firefox, however with chrome inputting the correct password directed me immediately back to the same login page (with no "password incorrect" prompt), regardless of the specific URL requested (root, /tree, etc).  Inputting an incorrect password behaved as expected (displaying "Invalid password"). 

With Firefox, the same setup/server works properly, redirecting to /tree after a successful login.  The terminal output of the server is identical when using firefox or chrome.

IE 11 completely fails to work at all (blank white display instead of login page)

I am running with a fresh, fully updated Anaconda install (new OpenSSL patches and all, plus ipython 2.0), and a self-signed certificate.  I am working on a user account without root access. Linux version is Red Hat Enterprise Linux Workstation release 6.5

My notebook profile is very basic: 

```
#Notebook config
c = get_config()
c.NotebookApp.certfile = u'/homes/sjoberge/lnx/certificates/mycert.pem'
c.NotebookApp.ip = '*'
c.NotebookApp.open_browser = False
c.NotebookApp.password = u'sha1:ebeb049...'
c.NotebookApp.port = 8889
```

Terminal output (login with firefox works, then login with chrome fails)

```
[sjoberge@lnxpefeks ~]$ ipython notebook --profile=limoserver
2014-04-09 16:28:21.542 [NotebookApp] Using existing profile dir: u'/homes/sjoberge/lnx/.ipython/profile_limoserver'
2014-04-09 16:28:21.578 [NotebookApp] Using MathJax from CDN: https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js
2014-04-09 16:28:21.615 [NotebookApp] Serving notebooks from local directory: /homes/sjoberge/lnx
2014-04-09 16:28:21.615 [NotebookApp] 0 active kernels
2014-04-09 16:28:21.615 [NotebookApp] The IPython Notebook is running at: https://[all ip addresses on your system]:8889/
2014-04-09 16:28:21.616 [NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
2014-04-09 16:28:32.279 [tornado.general] WARNING | Invalid cookie signature 'ZGNlNzMxOGMtN2E3NC00Mzg3LWI4ZGItMjQ4MGU5NTdhNGNm|1397085389|66216e234e643586a4cc82ffed042901e062b9bb'
2014-04-09 16:28:32.280 [tornado.access] 302 GET / (15.234.221.12) 2.11ms
2014-04-09 16:28:35.630 [tornado.access] 302 POST /login?next=%2F (15.234.221.12) 1.13ms
2014-04-09 16:28:35.697 [tornado.access] 302 GET / (15.234.221.12) 0.75ms
2014-04-09 16:28:49.436 [tornado.access] 302 GET / (15.234.221.12) 1.73ms
2014-04-09 16:28:52.788 [tornado.access] 302 POST /login?next=%2F (15.234.221.12) 1.00ms
2014-04-09 16:28:52.794 [tornado.access] 302 GET / (15.234.221.12) 0.87ms

```

No idea what's going on here, but maybe just a bug of some sort with Chrome?

**Comment by ellisonbg** [comment]
We will have to dig into this...unless you have already resolved the issue?

**Comment by sjobeek** [comment]
Ooh wow this is is from quite a while ago.  Let's see if I can remember how this was resolved...


If I remember properly, the same server was accessible from chrome on my co-worker's computers.  Completely uninstalling Chrome and re-installing it did temporarily fix this issue, however I seem to remember it coming back once or twice. 

I don't believe I was ever able to pinpoint the exact cause.

**Comment by minrk** [comment]
If this can't be reproduced now, let's call it resolved until someone can encounter it with master. There's a very good chance this is fixed by various login changes that have happened in the last several months.

**Comment by rschulzUK** [comment]
Am experiencing this problem without SSL and with Firefox 37.0.1, while Chrome 42.0.2311.90 works fine. I do not know how to debug this properly, but below is some log output that may give a hint?

More version info: IPython 3.1.0, Python 2.7.9 (part of Anaconda 2.2.0)

Loop with Firefox:
[I 13:47:01.926 NotebookApp] 302 GET / (xxx.xxx.xxx.xxx) 0.54ms
[I 13:47:01.947 NotebookApp] 302 GET /tree (xxx.xxx.xxx.xxx) 0.79ms
[I 13:47:25.137 NotebookApp] 302 POST /login?next=%2Ftree (xxx.xxx.xxx.xxx) 1.36ms
[I 13:47:25.160 NotebookApp] 302 GET /tree (xxx.xxx.xxx.xxx) 0.75ms

Firefox JS console output:
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More] <unknown>
Password fields present in a form with an insecure (http://) form action. This is a security risk that allows user login credentials to be stolen.[Learn More] <unknown>
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead

Non-loop with Chrome:
[I 13:45:41.112 NotebookApp] 302 GET / (xxx.xxx.xxx.xxx) 0.92ms
[I 13:45:41.136 NotebookApp] 302 GET /tree (xxx.xxx.xxx.xxx) 1.20ms
[I 13:46:07.838 NotebookApp] 302 POST /login?next=%2Ftree (xxx.xxx.xxx.xxx) 1.52ms

Chrome JS console output:
Resource interpreted as Font but transferred with MIME type text/html: "http://xxx.xxx.xxx.xxx:8888/static/components/font-awesome/fonts/fontawesome-webfont.woff2?v=4.3.0".
underscore-min.map:1 GET http://xxx.xxx.xxx.xxx:8888/static/components/underscore/underscore-min.map 404 (Not Found)

**Comment by npyoung** [comment]
Having this problem as well with 3.1.0 in Chrome. Clearing recent cookies and cached data fixes it immediately.

**Comment by Dalar** [comment]
I have the same problem with Chrome version 52.0 and newest Jupyter version. Should I create an issue in https://github.com/jupyter/notebook/issues ?

**Comment by willingc** [comment]
@Dalar Does clearing cookies and cached data fix this as it did here https://github.com/ipython/ipython/issues/5572#issuecomment-97538805

**Comment by Dalar** [comment]
@willingc Yes, but the problem resumes quite often. After every update at least.

**Comment by dannykwells** [comment]
@willingc did anything ever come of this? Running into the same issue, unclear cause. Any help avoiding (beyond simply clear cookies etc. often) would be great.

**Comment by willingc** [comment]
Hi @dannykwells,

Would you be able to share some additional information about your deployment? I'm not sure that what you are seeing is the same as the others as I believe that the original issue was resolved. Let's see if @takluyver and @carreau have any insights. Could you share what version of IPython you are using or if you are using Jupyter Notebook? Thanks!

**Comment by takluyver** [comment]
Anyone seeing this: is it possible that your browser is configured to reject all cookies? That might cause the symptoms described.

**Comment by endertekin** [comment]
I am having the same exact issue running jupyter notebook 1.0 on chrome 65.0. It's an endless login loop, and the console output just shows:
```
[I 13:45:09.426 NotebookApp] http://localhost:8888/
[I 13:45:09.426 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 13:45:09.710 NotebookApp] 302 GET /tree (::1) 2.99ms
[I 13:45:14.467 NotebookApp] 302 POST /login?next=%2Ftree (::1) 2.37ms
[I 13:45:14.477 NotebookApp] 302 GET /tree (::1) 0.70ms
[W 13:45:23.634 NotebookApp] 401 POST /login?next=%2Ftree (::1) 1.55ms referer=http://localhost:8888/login?next=%2Ftree
[I 13:45:26.480 NotebookApp] 302 POST /login?next=%2Ftree (::1) 1.24ms
[I 13:45:26.487 NotebookApp] 302 GET /tree (::1) 0.90ms
[I 13:47:51.359 NotebookApp] 302 GET / (::1) 2.35ms
[I 13:47:51.371 NotebookApp] 302 GET /tree? (::1) 1.07ms
[I 13:47:54.975 NotebookApp] 302 POST /login?next=%2Ftree%3F (::1) 1.23ms
[I 13:47:54.982 NotebookApp] 302 GET /tree? (::1) 0.97ms
[I 13:48:19.409 NotebookApp] 302 GET / (::1) 0.82ms
[I 13:48:19.416 NotebookApp] 302 GET /tree? (::1) 0.90ms
```
I don't have this issue with Safari.  If I use a token instead of a password, I can get to the tree (via the url only, entering the token in the password prompt has the same issue), but it doesn't show any files. I have verified in the site security settings that cookies are being set and accepted.

**Comment by willingc** [comment]
Ping @gnestor @takluyver

**Comment by Random-Word** [comment]
Seeing the same issue as endertekin on Chrome 63:

`[I 14:06:43.843 NotebookApp] 302 GET /tree (127.0.0.1) 1.35ms
[20375:20416:0419/140643.865910:ERROR:browser_gpu_channel_host_factory.cc(107)] Failed to launch GPU process.
Created new window in existing browser session.
[I 14:06:46.993 NotebookApp] 302 POST /login?next=%2Ftree (127.0.0.1) 3.42ms
[I 14:06:47.005 NotebookApp] 302 GET /tree (127.0.0.1) 3.36ms
[I 14:06:53.894 NotebookApp] 302 POST /login?next=%2Ftree (127.0.0.1) 3.26ms
[I 14:06:53.904 NotebookApp] 302 GET /tree (127.0.0.1) 3.32ms
[I 14:07:03.569 NotebookApp] Malformed HTTP message from 127.0.0.1: Malformed HTTP headers: '\n\x01\x00\x00w\n\n'
[I 14:07:03.569 NotebookApp] Malformed HTTP message from 127.0.0.1: Malformed HTTP headers: '\n\x01\x00\x00wêê\x00\x00ÿ\x01\x00\x01\x00\x00\x00\x00\x0e\x00\x0c\x00\x00\tloca'
[I 14:07:34.902 NotebookApp] 302 POST /login?next=%2Ftree (127.0.0.1) 1.23ms
[I 14:07:34.906 NotebookApp] 302 GET /tree (127.0.0.1) 0.77ms
[I 14:10:01.235 NotebookApp] 302 POST /login?next=%2Ftree (127.0.0.1) 3.17ms
[I 14:10:01.244 NotebookApp] 302 GET /tree (127.0.0.1) 2.35ms
[I 14:10:02.118 NotebookApp] 302 POST /login?next=%2Ftree (127.0.0.1) 0.86ms
[I 14:10:02.121 NotebookApp] 302 GET /tree (127.0.0.1) 0.79ms
[I 14:10:02.968 NotebookApp] 302 POST /login?next=%2Ftree (127.0.0.1) 1.01ms
[I 14:10:02.970 NotebookApp] 302 GET /tree (127.0.0.1) 0.80ms
`

**Comment by takluyver** [comment]
I'll reopen this, but I don't think we understand what's going on. How it's meant to work is that `/login` redirects you to `/tree` when you are authenticated, and `/tree` redirects you to login when you're not authenticated.

**Comment by takluyver** [comment]
Actually, I just realised this is issue is on IPython. The relevant repository for this is now [jupyter/notebook](https://github.com/jupyter/notebook). So please open an issue there with the information and a link to this thread.

**Comment by onietosi** [comment]
I am facing the same issue. Clearing cookies seems to work, but has any issue been opened on [jupyter/notebook](https://github.com/jupyter/notebook)?
