### ISSUE TITLE
Interactivity with media has high latency on Safari@OSX

### ISSUE THREAD

**Issue by michaelaye** [ipython/ipython#5575]
Trying out the interactivity examples for Beat Frequencies and Image Processing, I noticed that on Safari@OSX (Mavericks all updates) the latency between using the widget and updated media is unbearably large, in the order of 5 seconds until the audio player is re-displayed and between 5 and 10 seconds until an image is shown with an updated value of RGB using the sliders.
Here's my system data:
MBP Retina 2012
Safari 7.0.3
Mavericks 10.9.2
IPython: 2.0.0 (5c3a5f18e)

Note that on Chrome the examples work smoothly.

**Comment by minrk** [comment]
The examples appear to run at several Hz for me. Can we close this one as mysteriously fixed? Or do you still see this issue, @michaelaye?

rMBP 2013
Safari 8.0.2
OS X 10.10.1
IPython master (25d6433b8c48ae7c3082870648bec7e22866616d)

**Comment by michaelaye** [comment]
Not really for me. Maybe the solved things in Safari 8?

See my screencast here: https://dl.dropboxusercontent.com/u/139035/beat_frequencies_widget_slowness.mov

rMBP 2012
Safari 7.1.2
OS X 10.9.5
IPython master Jan 14 (7e15d0696)

**Comment by minrk** [comment]
My guess is it's a performance bug in Safari 7, which isn't really something we can do anything about.

**Comment by parente** [comment]
FWIW, performance seems fine in Safari 8 on Yosemite:

https://dl.dropboxusercontent.com/u/264241/Safari%20-%20Beat%20Frequencies.mov
