### ISSUE TITLE
Completion broken for 1/math.s<tab> and %d<tab>

### ISSUE THREAD

**Issue by lebigot** [ipython/ipython#5577]
Completion is severely limited in my IPython 2.0 terminal shell. For example, `1/math.s<tab>` and `%d<tab>` both fail (instead of proposing `math.sin`, etc. and `%doctest…` etc.).

After removing both my `.pystartup` and `.ipython/`, the `%d<tab>` completion started working again. The `1/math.s<tab>` no-completion problem is still there, though…

**Comment by Carreau** [comment]
`1/math.s<tab>` should be fixed by #10182

**Comment by Carreau** [comment]
closed by #10182
