### ISSUE TITLE
[Wishlist] Setting: On an exception, allow user to edit problematic line; ipython reattempts evaluation from that point on without having to rerun all of the code

### ISSUE THREAD

**Issue by chironex** [ipython/ipython#559]
I don't know if this feature already exists, but if it doesn't, it would be nice. Nobody likes having to go back and run 4 minutes of code after ipython breaks down over an easily-fixed error. It would be nice to enable an option that, when enabled, causes ipython to pause upon hitting a broken line of code, and then allows you to edit that line in your favorite text editor. You would then go back to ipython and tell it to try to continue running your code, reevaluating the line that it originally failed at, without losing any data you had computed up to that point.

Note that there's some behavior that would need to be defined (I.E., what happens if you add lines before the line that caused the exception while editing your failed code?).

**Comment by Carreau** [comment]
I'm going to close this as the notebook is now a thing, and @rkern is right: `"fix-and-continue" ` is not possible. 

Feel free to open a new issue if you want this to be looked at again. 

Thanks !
