### ISSUE TITLE
Files that have a newline in their filename

### ISSUE THREAD

**Issue by tibi-p** [ipython/ipython#5601]
Presuming that a file with a newline in its filename makes its way on my filesystem, shouldn't !ls be able to detect that? Currently it returns two separate entries, e.g. "abc\ndef" => "abc" and "def".

**Comment by remram44** [comment]
This looks like an ls issue. On my machine, it shows something like this:
```
abc?def
other_file
```
I don't think this concerns IPython so it should be closed.

**Comment by minrk** [comment]
@remram44 thanks!
