### ISSUE TITLE
Help reference missing some shortcuts

### ISSUE THREAD

**Issue by jhamrick** [ipython/ipython#5607]
We (@olgabot and @Carreau) realized that the help reference doesn't include all keyboard shortcuts, like `Shift-Tab` to show the function help. I found this file:

https://github.com/ipython/ipython/blob/master/IPython/html/static/notebook/js/quickhelp.js

which looks like it includes help for these shortcuts, but for whatever reason I guess they're not showing up.

**Comment by drocco007** [comment]
The shortcut referenced in the original issue is in the most recent help; are there any that are currently missing?

**Comment by Carreau** [comment]
Most should be auto generated, so I would just test and see. Shift tab might still be missing.

**Comment by takluyver** [comment]
Shift tab is there. I think we can close this now, and open new issues if we find specific things missing.
