### ISSUE TITLE
Document interact/interactive

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#5637]
tagging as sprint-friendy / quickfix

@jhamrick and I are working on that.

**Comment by ellisonbg** [comment]
Just to clarify this issue, we need to add a good *docstring* to these functions.

**Comment by tbittner** [comment]
How does this look as docstring for the "interact" function?

https://github.com/tbittner/ipython/compare/document-interact-5637

I can add some doc for "interactive", too.

**Comment by ellisonbg** [comment]
Thanks! One bit of terminology that we are using for the other argumets is "widget abbreviation" = they are abbreviate ways of specifying which widget to use for that argument.

**Comment by tbittner** [comment]
Ok, updated the doc and added doc for "interactive" function.

Pull request submitted at https://github.com/ipython/ipython/pull/7525

**Comment by takluyver** [comment]
And merged #7525
