### ISSUE TITLE
Horizontal scrollbar of cell output overlaps subsequent cell

### ISSUE THREAD

**Issue by florian-wagner** [ipython/ipython#5695]
Hey guys,

in Chromium on Arch Linux I noticed, that the horizontal scrollbar of a cell output overlaps the input area of the subsequent cell.

![image](https://cloud.githubusercontent.com/assets/2799008/2765037/e253c64e-ca1e-11e3-92bf-a934c573c27b.png)

Cheers
Florian

**Comment by rossant** [comment]
Same problem on latest Chrome on Ubuntu 14.04: impossible to scroll horizontally...

![image](https://cloud.githubusercontent.com/assets/1942359/5696182/b50112d4-99c4-11e4-9c6b-0d3d1057c0e4.png)

It works in Firefox, but there's a display problem instead:

![image](https://cloud.githubusercontent.com/assets/1942359/5696192/f05b31de-99c4-11e4-8528-97367e67343b.png)
