### ISSUE TITLE
nbconvert to PDF error

### ISSUE THREAD

**Issue by gibiansky** [ipython/ipython#5722]
Hey there,

I'm getting the following error upon using nbconvert with `--post PDF`:

```
! LaTeX Error: Command \ttfamily invalid in math mode.
```

Compiling myself with `pdflatex` works fine. Also, specifying `--post pdflatex` no longer works (which i assume is purposeful).

Any ideas why I get that error? PDF compilation fails afterwards. Note that I am using the `\mathbb{C}` command, but I can't think of why else `ttfamily` would be in math mode or why it would be a problem.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
