### ISSUE TITLE
multicell cut-copy-paste UI/UX feedback

### ISSUE THREAD

**Issue by ivanov** [ipython/ipython#5746]
Opening this issue to collect feedback on my prototype for multi-cell cut-copy-paste.

You can grab the code which is an extension for now: [NB-CCCP](https://github.com/ivanov/nb-cccp)

```sh
cd $(ipython locate)/nbextensions
git clone https://github.com/ivanov/nb-cccp
echo "require(['nbextensions/nb-cccp'], function (copy_paste) {
    copy_paste.load_ipython_extension();
    console.log('copy_paste extension loaded');
    });" >> $(ipython locate profile)/static/custom/custom.js
```

The README file of that repo has further instructions for how to use it.

**Comment by IanHawke** [comment]
I've just update to Jupyter notebook 3.0 (through conda, using python 3.4.2) and this extension stopped the notebook from working correctly (it is the only extension I had running; removing the profile/static/custom/custom.js file made the notebook work fine). Is that expected?

**Comment by takluyver** [comment]
It's not exactly expected, but it's not especially surprising either - quite a lot has changed in the JS between 2.x and 3.x. Hopefully we'll get round to building multi-cell selection into the notebook before too much longer, so it won't need to be an extension.

**Comment by trendelkampschroer** [comment]
Hi,

I like this feature a lot. Could it be extended to also allow /cut/copy/paste of multiple cells between different notebooks?

**Comment by ellisonbg** [comment]
We are working on allowing multiple notebooks on a single browser tab. Then
it will be pretty easy to add that feature (and yes, we too would like to
have it!)

On Wed, Nov 11, 2015 at 4:53 AM, Benjamin Trendelkamp-Schroer <
notifications@github.com> wrote:

> Hi,
>
> I like this feature a lot. Could it be extended to also allow
> /cut/copy/paste of multiple cells between different notebooks?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/5746#issuecomment-155719221>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by amueller** [comment]
stupid question but wouldn't it be possible to allow copy and paste using the system clipboard?
Then there is no issue with doing it between browsers.

Something like https://www.lucidchart.com/techblog/2014/12/02/definitive-guide-copying-pasting-javascript/

**Comment by minrk** [comment]
@amueller I think doing it with the clipboard is probably what we should do next, if we can get it to work. Thanks for the link!

**Comment by amueller** [comment]
I imagine it will be non-trivial but I'm sure you can rock it :)

**Comment by palbarede** [comment]
I installed NB-CCCP and I do see the 3 new blue buttons and the counter displaying 0 but just like 
cmgerber on Apr 29, 2014
I cannot select more than one cell and even if I select one cell the counter does not display 1.

I do not understand how to select multiple cells with NB-CCCP.

Server Information:

You are using Jupyter notebook.

The version of the notebook server is 4.0.6 and is running on:

Python 3.5.1 |Anaconda 2.4.1 (x86_64)| (default, Dec  7 2015, 11:24:55) 
[GCC 4.2.1 (Apple Inc. build 5577)]

Current Kernel Information:

Python 3.5.1 |Anaconda 2.4.1 (x86_64)| (default, Dec  7 2015, 11:24:55) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
%guiref   -> A brief reference about the graphical user interface.

**Comment by Carreau** [comment]
> I installed NB-CCCP and I do see the 3 new blue buttons and the counter displaying 0 but just like 
> cmgerber on Apr 29, 2014

Please see notebook 4.1 which was [released a few days ago](https://blog.jupyter.org/2016/01/08/notebook-4-1-release/) and have multiple selection & copy/cut/past baked in.

Closing this issue.

**Comment by palbarede** [comment]
Yes it works thanks.
