### ISSUE TITLE
ipython nbconvert fails with certain markdown cells

### ISSUE THREAD

**Issue by willzfarmer** [ipython/ipython#5757]
When using

    ipython nbconvert --to latex --post pdf myfile.ipynb

with a LaTeX and Markdown cell the build fails when pdflatex attempts to compile, citing

    Paragraph ended before \@sect was complete

Debugging the generated LaTeX file yields the error occurring from document structure like the following.

    ...
    \section{name}
    \paragraph{text text text}
    more text

A simple fix in this case is to simply not wrap the generated cell in a \paragraph.

Note, this issue is similar to #4946, however that issue was resolving a different problem (I think).

Edit: Note, as far as I can tell this only occurs with Heading 4 cells.

**Comment by Carreau** [comment]
Closing as inactive.
