### ISSUE TITLE
WX Eventloop not working in Emacs

### ISSUE THREAD

**Issue by bergtholdt** [ipython/ipython#577]
I use the current EPD 7.1.1 distribution which comes with IPython 0.11rc1 on Windows-7 x64. 

I use python-mode with ipython.el (from current git) when working in Emacs. Previously, i.e. with IPython 0.10 and the old thread-based event handling I could start IPython with

ipython.bat -pylab

i.e. I have this:
(setq ipython-command "ipython.bat")
(setq py-python-command-args (cons "-pylab" py-python-command-args))

which would activate wx event-loop. with 0.11. I use this

ipython.bat --pylab gui=wx pylab=wx

(setq py-python-command-args (cons "--pylab" (cons "gui=wx" (cons "pylab=wx" py-python-command-args))))

which works, but matplotlib figures and enthought traits based apps do not process events any more. I.e. if I 

plot([1,2,3,4])

the figure window pops up, but stays empty and the title says "Figure 1 (Not Responding)". The IPython prompt in Emacs is responsive and I can even start more (non responding) figures issuing

figure()

When I run the same on a plain console everything works fine. Issuing a "show()" does nothing.
In a shell or eshell within emacs it also does not work.

I investigated a little to debug and put a print into:

IPython/lib/inputhookwx.py
144ff:
            while not stdin_ready():
                while evtloop.Pending():
                    print "_1"

On a standard console once I issue the plot([1,2,3,4]) I get several "_1" printed on the console. Inside Emacs I get nothing. I also put a print right at the start of  inputhook_wx3(). It never gets outputted in Emacs so it seems inputhook_wx3 is never called.

I also tried pylab=tk. This plots some more content in the figure (the buttons), but stays unresponsive as well.

I hope this gives enough hints to somebody to solve this issue and give me my development environment back.

**Comment by minrk** [comment]
IPython no longer ships ipython.el
