### ISSUE TITLE
Disable IPython keyboard manager for toolbar

### ISSUE THREAD

**Issue by juhasch** [ipython/ipython#5829]
The keyboard manager handles all keydown events of the current document. This prevents adding a text input field in the toolbar and typing in something.

Now I can register with the keyboard manager to prevent this from happening as @ellisonbg pointed out in https://github.com/ipython/ipython/pull/5825.

Wouldn't it be useful to register the whole menubar by default, i.e. add a
`IPython.keyboard_manager.register_events($('#menubar-container'));` 
as standard ?

**Comment by ellisonbg** [comment]
Talked about this at the dev meeting. Let's try this out and see how the user experience is.

**Comment by minrk** [comment]
#7439
