### ISSUE TITLE
Splitting cell, and continuous selection

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#5860]
When splitting cell with ctrl+- the new cell start to behave has if shift was pressed when moving the cursor(not for other actions), where only pressing arrow key will make/extend/selection. 

Minor annoyance and only does it 4 times over 5 but pretty reproductible on my setup.

**Comment by Carreau** [comment]
I haven't seen this while in a while. Did you @ellisonbg ?

**Comment by ellisonbg** [comment]
I have'nt seen this recently. We could close it for now and reopen if it shows up again.
