### ISSUE TITLE
Edit magic fails on filepaths containing spaces. 

### ISSUE THREAD

**Issue by nitetrain8** [ipython/ipython#5918]
Ipython version- 2.1.0
OS- windows 7 64 bit
Python- version 3.4.1

When using edit magic to edit a file containing spaces, the code for the "%edit" magic automatically quotes filenames containing spaces on line 661 of Ipython/core/magics/code.py. When the filename is sent executed using the terminal's safe_execfile function, it is expanded to the full path on line 2520 of Ipython/core/interactiveshell.py. If the filename is quoted at this time, then os.path.abspath incorrectly expands the filename to $curdir/'$filepath'. 

To reproduce:

with open("C:/de bug/dbg.py", 'w') as f:
    pass

%edit "C:/de bug/dbg.py"

After continuing by closing the file/pressing enter, an error indicating incorrect filepath used by the interactive shell will be thrown.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

I'm not sure how long ago this was fixed, but I just verified that both quoted and escaped version work for files with spaces in their path. I do not believe this was a windows-only issue (I tested on a Debian). 

```
Python 3.8.9 (default, Jun 14 2021, 23:59:48)
Type 'copyright', 'credits' or 'license' for more information

In [1]: %edit "path with spaces/test"
done. Executing edited code...

In [2]: %edit path\ with\ spaces/test
done. Executing edited code...
```



Thanks everyone and happy hacking! :bowtie:
