### ISSUE TITLE
Can not rename notebook to upper case

### ISSUE THREAD

**Issue by squarel** [ipython/ipython#5919]
![image](https://cloud.githubusercontent.com/assets/886306/3111206/58d6a2fe-e6ae-11e3-9f7b-e0bdb2417b88.png)
I try to rename my notebook from 'tree' to 'Tree' but failed. 
The code to check if the new path of notebook exists or not is using os.path.isfile(), this method is case insensitive.
![image](https://cloud.githubusercontent.com/assets/886306/3111254/0948124e-e6af-11e3-957a-49a7ab868d96.png)

**Comment by davidlowryduda** [comment]
This seems like more of an OS X thing than an ipython thing. Can this issue be closed, or is there a desired change of behavior?
