### ISSUE TITLE
Setting insert cell default type?

### ISSUE THREAD

**Issue by fonnesbeck** [ipython/ipython#5952]
Is is possible to set a global default for the cell type when a new cell is inserted above or below another cell? It seems that there was a recent change that copies the type of the cell that is currently selected when a new cell is created. I find this frustrating because I end up creating Markdown cells way more frequently than I would do naturally, and have to go in and manually change the type. Markdown constitutes < 10% of the cells in any given notebook I create, so I want to create code cells by default. Is there a way of specifying this?

**Comment by joelostblom** [comment]
If anyone else is looking for this in JupyterLab, you can go to `Settings -> Advanced Settings manager -> Notebook` and then add the following in "User Preferences":

```json
{
    "defaultCell": "markdown"
}
```

There is also a [suggestion here for how to achieve this in the classic notebook](https://stackoverflow.com/questions/40382454/jupyter-notebook-new-cell-type-default/64229826#64229826), so maybe this issue can be closed?

**Comment by hughperkins** [comment]
You can search for `main.min.js`, inside your pyenv site-settings, open this file, then search for `default_cell_type`, and change it from `code` to `markdown`. This works, though it's hardly accessible/intuitive. (source https://stackoverflow.com/a/40933932/212731 , plus I tested this, and it worked ok for me in june 2023, using jupyter 1.0.0, jupyter_client 8.2.0

```
$ pip freeze | grep jupyter
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.6.3
jupyter_client==8.2.0
jupyter_core==5.3.0
jupyter_server==2.6.0
jupyter_server_terminals==0.4.4
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.7
```
