### ISSUE TITLE
scrollbar overflow output_subarea

### ISSUE THREAD

**Issue by kimdwkimdw** [ipython/ipython#5967]
```
python -c "import IPython; print(IPython.sys_info())"
----
{'commit_hash': '781830f',
 'commit_source': 'repository',
 'default_encoding': 'cp949',
 'ipython_path': 'MYLOCALPATH\\ipython\\IPython',
 'ipython_version': '3.0.0-dev',
 'os_name': 'nt',
 'platform': 'Windows-8-6.2.9200',
 'sys_executable': 'MYLOCALPATH\\Scripts\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '2.7.7 (default, Jun  1 2014, 14:21:57) [MSC v.1500 64 bit (AMD64)]'}
```

relevant package: pandas, numpy (latest)
## and latest chrome browser(35.0.1916.114 m)

![ipython-table-bug](https://cloud.githubusercontent.com/assets/386070/3231350/ecfeca3c-f0aa-11e3-8082-278d6f86adc9.png)

The scrollbar below the text "5 rows x 21 columns" overflow parent div element.
It should be inside parent div.
I want to scroll x-axis, but it didn't work because child div element bigger than parent div element.

I found this bug both versions 2.1 and 3.0-dev.

The test case of this bug can be like below

>  `assertTrue($(".output_subarea:last").height() > $(".output_subarea:last > div").height())`

**Comment by ellisonbg** [comment]
I have seen this too, but it may be fixed in master. We need to verify/fix before 3.0.

**Comment by parente** [comment]
Can confirm the overflow bug still exists in master a7a2090 on Chrome 39.0.2171.95 and Safari 8.1 on Mac. It appears to be the influence of the max-height after hiding then showing the cell output. If I remove those styles, the cell overflow corrects itself. Putting them back has no negative effect until the next hide.

I'll keep looking and submit a pull request with the LESS fix from @joelkim and the one for the hiding too if I can figure it out.

**Comment by ellisonbg** [comment]
Thanks for the confirmation!

On Fri, Jan 16, 2015 at 12:01 PM, Peter Parente <notifications@github.com>
wrote:

> Can confirm the overflow bug still exists in master a7a2090
> <https://github.com/ipython/ipython/commit/a7a20903043052107f03283c0de2cdf939c587bd>
> on Chrome 39.0.2171.95 and Safari 8.1 on Mac. It appears to be the
> influence of the max-height after hiding then showing the cell output. If I
> remove those styles, the cell overflow corrects itself. Putting them back
> has no negative effect until the next hide.
>
> I'll keep looking and submit a pull request with the LESS fix from
> @joelkim <https://github.com/joelkim> and the one for the hiding too if I
> can figure it out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/5967#issuecomment-70313250>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
Can anyone provide a *complete* example that reproduces the problem? I think the fix in #7489 isn't going to work, but I can't explore other options, and I've never been able to reproduce this. Scrollbars sit happily inside the div, as far as I can tell.

**Comment by parente** [comment]
Notebook and steps to reproduce:

1.Grab http://nbviewer.ipython.org/gist/parente/c8fc38c7bf2b3ace9e7d
2. (Mac only) Switch "Show scroll bars" in System Preferences -> General to "Always". (It doesn't manifest when scroll bar autohide is turned on.)
3. Open the notebook.
4. Double click to hide the output of `df.head()`.
5. Double click to show the output of `df.head()` again.

Upon showing the output of that cell again, I always wind up with the scrollbar overflow as shown below. It also rarely renders in this state when the notebook first opens as well.

![overflow](https://cloud.githubusercontent.com/assets/153745/5885758/d12a20e8-a344-11e4-8f06-c24fbcb2c03d.png)

**Comment by minrk** [comment]
Thanks for the example, that works, and clarifies that it's definitely a browser bug. I'll continue feedback in the PR.

**Comment by kimdwkimdw** [comment]
Finally resolved?!

**Comment by kimdwkimdw** [comment]
When I report this problem, I thought it was bug of chrome.

**Comment by minrk** [comment]
@kimdwkimdw this is a browser bug, but it is not resolved. #7489 mitigates the problem a bit.
