### ISSUE TITLE
Allow to embed local videos using html5

### ISSUE THREAD

**Issue by dawehner** [ipython/ipython#5987]
As shown in http://nbviewer.ipython.org/github/ipython/ipython/blob/1.x/examples/notebooks/Part%205%20-%20Rich%20Display%20System.ipynb you can embed videos into ipython not only using Youtube or Vimeo but also local files.

Is there a reason why there is no simple way of an Video display which allows you to pass in the filepath?

**Comment by mpenkov** [comment]
This looks like an easy starting issue, so I'll start working on it and send a PR during the week.

**Comment by mpenkov** [comment]
It looks like #5992 got merged, so perhaps this issue should be marked as completed?

**Comment by Carreau** [comment]
Sure, thanks. 

You should be able to close it by mentioning our helper bot as follow:

@meeseeksdev[bot] close
