### ISSUE TITLE
IPython Parallel: ZMQError: Too many open files 

### ISSUE THREAD

**Issue by shaunpatel** [ipython/ipython#6039]
I am using ipython parallel to run a distributed job on a 12-core machine (mac pro). After ~10 hours, I receive the following error:

```
/usr/local/lib/python2.7/dist-packages/zmq/sugar/context.pyc in socket(self, socket_type)
    135         if self.closed:
    136             raise ZMQError(ENOTSUP)
--> 137         s = self._socket_class(self, socket_type)
    138         for opt, value in self.sockopts.items():
    139             try:

/usr/local/lib/python2.7/dist-packages/zmq/backend/cython/socket.so in zmq.backend.cython.socket.Socket.__cinit__ (zmq/backend/cython/socket.c:2481)()

ZMQError: Too many open files
```

I thought it might be a memory management issue on the individual kernels so I run this code after each iteration of the loop. Although it helped, it doesn't solve the problem.

```
# CLEAR CACHE
def clearCache(rc, dview):

    rc.purge_results('all')
    rc.results.clear()
    rc.metadata.clear()
    dview.results.clear()
    rc.history = []
    dview.history = []
```

I should also mention, I am running this code with runipy.
Any suggestions?

**Comment by OliverEvans96** [comment]
Is there a way to globally access the Client object created in the current process without creating a new one or passing the old one around?
