### ISSUE TITLE
Race condition in notebook tab-completion

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#6043]
Type e.g. `from IPython.parallel import C`, then hit tab followed by `l` in very quick succession (you may need to try this a few times to see the issue). You get the possible completions for `C` at that point, but the cell already contains the `l`. When you select one of the completions, it is inserted before the `l`, e.g. `Client` -> `Clientl`.

This is probably because the l is inserted between requesting completions and receiving the reply. Ideally in this case, keys pressed between those events would have the same effect as typing after the completion list appears. @minrk suggested that adding a sleep in the completion machinery would make it easier to test this.

This is low priority, but I wanted to record the issue.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
