### ISSUE TITLE
Unclear error message when trying to load notebook that isn't even valid JSON

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#6052]
wget an nbviewer notebook URL (instead of the actual notebook URL), resulting in an HTML file with a .ipynb extension.

Opening it in the notebook in master results in a dialog box headed "Error loading notebook", with the text "Bad request". I think we should do a better job of the error message in this case.

(Bug report originally described how we failed to open a renderable notebook, but then I worked out what I had done)

**Comment by minrk** [comment]
I get this error now:

![screen shot 2015-01-13 at 15 24 39](https://cloud.githubusercontent.com/assets/151929/5731448/55c33390-9b38-11e4-8d6b-90505f7cb283.PNG)

so I think this can be closed.
