### ISSUE TITLE
nbconvert - ReST .. code:: directive

### ISSUE THREAD

**Issue by trendelkampschroer** [ipython/ipython#6100]
Hi,

I have encountered a problem when converting .ipynb files to .rst. Code cells are marked using the ".. code:: python" directive.

Using sphinx to build html using the .rst files generated via nbconvert fails with the following error.

ERROR: Unknown directive type "code".

.. code:: python

In the sphinx-docs I have found ".. code-block:: python" directive instead. 

Is this a bug of nbconvert or am I using an outdated version of sphinx.

I am glad for any suggestions.

Thanks,

Ben

**Comment by sontek** [comment]
Just tried with latest sphinx and it is now accepting `.. code::` so this can probably be closed
