### ISSUE TITLE
Update widgets across several open notebook windows

### ISSUE THREAD

**Issue by bbirand** [ipython/ipython#6111]
Hi,

(I looked around quite a bit for this as I feel it must be asked somewhere, but couldn't find anything.)

It seems like when there are multiple windows that open the same notebook, only the last one gets the control. So if I have a widget, and I programmatically update its value, only one of the notebooks gets the "update" signal to redraw the widget. It would be really cool if widgets in several notebooks could be connected together, so that if I move the slider in one browser, it moves on the other screen.

It seems like sending some of the signals to multiple notebooks should be possible with the Pub/Sub ZeroMQ sockets. I'm sure there are many complications to get this to work. But, out of curiosity, has this been considered?

Thanks!

**Comment by ellisonbg** [comment]
This is known to not fully work today. In the future it may, but there are tons of low-level arch details we would have to work out first.

**Comment by bbirand** [comment]
I thought this type of widget behavior was being considered for IPython 3. Is this not right, then?

**Comment by ellisonbg** [comment]
Not for 3.0. It is going to take a while (at least a year) to get all of the pieces into place.
