### ISSUE TITLE
Possible bug - Notebook stack trace creates 3 html links when an HTML link is present in the code

### ISSUE THREAD

**Issue by schodge** [ipython/ipython#6121]
**Reproduce**: Download this notebook: http://nbviewer.ipython.org/github/ggventurini/python-deltasigma/blob/master/examples/dsdemo1.ipynb

Execute the last cell without installing `version_information.py`:

```
#%install_ext http://raw.github.com/jrjohansson/version_information/master/version_information.py
%load_ext version_information
%reload_ext version_information

%version_information numpy, scipy, matplotlib, deltasigma
```

You should then get an error.

```

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-11-d8cbdebb1719> in <module>()
      1 #%install_ext http://raw.github.com/jrjohansson/version_information/master/version_information.py>
----> 2 get_ipython().magic(u'load_ext version_information')
      3 get_ipython().magic(u'reload_ext version_information')
      4 
      5 get_ipython().magic(u'version_information numpy, scipy, matplotlib, deltasigma')

<cutting a bunch out for space reasons>

ImportError: No module named version_information
```

**BUG**: The stack trace has three separate links when displayed.  The first, on line 1, goes to `http://raw.github.com/jrjohansson/version_information/master/version_information.py%3C/span` - it starts on the `http://` and ends on the `>`, inclusive.  Then on line 2, `----> 2 get_ipython().` is also a link to the same URL.  Lastly, a third and final link starts on `magic(u'load_ext version information')` and continues all the way through the entire rest of the stack trace, again to the same URL.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
