### ISSUE TITLE
"-datetime.timedelt" not completed

### ISSUE THREAD

**Issue by lebigot** [ipython/ipython#6140]
After the necessary `import datetime`, completing `-datetime.timedelt` with TAB does not work. Doing the same with `datetime.timedelt` works as expected.

Python 2.7.8 (default, Jul 13 2014, 17:11:32) 
IPython 2.1.0

**Comment by Carreau** [comment]
This will be fixed by #10182

**Comment by Carreau** [comment]
closed by #10182
