### ISSUE TITLE
Kernel selection UI

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#6217]
Extra things to do on top of #6126 : 

  - [x] Changing kernel is destructive, pop a  confirmation ? 
  - [x] Decide the final place of kernel selector
  - [x] Show kernels logo/favicons 
  - [x] Load `kernel/custom.js`,`kernel/custom.css`
  - [x] what about custom `/static/` overwrite like Julia and tooltip ?
  - [x] automatically deal with notebook with `language` metadata field ?

**Comment by ellisonbg** [comment]
I think the kernel selection UI stuff is being tracked in other more specific issues. Closing this meta-issue.
