### ISSUE TITLE
kernelspec/customjs

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#6231]
Thought about kernelspec custom js:

We cannot have it run on load, and I think we should require a module to be defines.
With specific function we guaranty to call.

Indeed kernel like Julia do monkey-patch IPython stuff (like tooltip), and do attach action to events. By switching kernel you need to un-patch and/or detach events, 

I propose to require the `kspec/customjs` module and call a `load/unload` methods on it. 

I propose the load method/function to return a `state` object and the unload to get this `state` object as argument. Otherwise this would require the patching/unpatching to be statefull which might prevent different kernels in using the same extensions.

I believe that would also be usefull for @gibiansky seeing that IHaskell has quite a few custom js/css to inject.

(Next step is to register this kernelspec/custom css/js on nbviewer)

Pinging @takluyver that has worked a lot on kernelspec and @dsblank that seem super active on js-side with calico.

Thought ?

**Comment by ellisonbg** [comment]
I know we have decided something wrt to custom.js in the kernelspec, just don't remember what it was. I think we were pushing back on it a bit to really understand what the needs were. Can I close this issue?

**Comment by Carreau** [comment]
If custom.js is present (actuallt kernel.js) load it but prevent future kernel switch without reload.
