### ISSUE TITLE
Ctrl-C not clearing prompt in terminal (with EPD?)

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#625]
As reported by EPD users on the mailing list, Ctrl-C no longer works to clear a prompt in the terminal. One user has apparently tried this with a newer checkout from git, but sees the same problem. This has affected one Linux and one Windows user, but I can't replicate it on Linux.

Expected behaviour:

<pre>
In [1]: cd something_wrong<Ctrl-C>
KeyboardInterrupt
In [1]:
</pre>

N.B. It seems Ctrl-C does still work to interrupt running commands.

**Comment by Carreau** [comment]
With this issue being 5 years old, the lack of activity, and all the recent refactor I'll assume this is either fixed, or need a new issue to be reopened. 

Thanks all, and closing to try to keep issue list small. 

Thanks !
