### ISSUE TITLE
%debug magic "up" fails to pass through generator stack

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#6251]
Consider the following example "pdbtest.py":

```
def f(x):
    raise Exception

gen = (f(x) for x in [0])

for x in gen:
    pass
```

If I run this with `python -i pdbtest.py`, when the exception is thrown I can go up the stack all the way to the module-level with pdb:

```
Traceback (most recent call last):
  File "pdbtest.py", line 6, in <module>
    for x in gen:
  File "pdbtest.py", line 4, in <genexpr>
    gen = (f(x) for x in [0])
  File "pdbtest.py", line 2, in f
    raise Exception
Exception
>>> import pdb; pdb.pm()
> /home/antony/tests/pdbtest.py(2)f()
-> raise Exception
(Pdb) u
> /home/antony/tests/pdbtest.py(4)<genexpr>()
-> gen = (f(x) for x in [0])
(Pdb) u
> /home/antony/tests/pdbtest.py(6)<module>()
-> for x in gen:
(Pdb) u
*** Oldest frame
(Pdb) 
>>> 
```

However, if I try to do the same with ipython's %debug magic, I cannot go beyond the generator frame -- which is particularly annoying when you think the actual bug happens earlier:

```
In [1]: %debug
> /path/to/pdbtest.py(2)f()
      1 def f(x):
----> 2     raise Exception
      3 

ipdb> u
> /path/to/pdbtest.py(4)<genexpr>()
      3 
----> 4 gen = (f(x) for x in [0])
      5 

ipdb> u
*** Oldest frame
ipdb>
```

This happens with ipython 2.1.0 and python 3.4.

**Comment by fredcallaway** [comment]
Not sure how much this will do but... *bump*

**Comment by xapple** [comment]
It's a pretty serious bug for a debugger not to be able to travel up the call stack... astonishing that is untouched since it appeared in 2012.

**Comment by abukaj** [comment]
It also affects Python 3.6 (both IPython 6.4.0 and Jupyter Notebook with IPython 5.3.0).

**Comment by xeor** [comment]
This have suddenly started happening to me as well, in the last couple of weeks. Been using ipython and the debugger magic method for many years.. Never had this problem.
I'm not using the notebook.

Python 3.6.3
IPython 6.4.0

**Comment by Carreau** [comment]
See #11266
