### ISSUE TITLE
%PDB magic and <C-C> hang ipython when attached to kernel

### ISSUE THREAD

**Issue by ocehugo** [ipython/ipython#6272]
Hi, this is such an annoying bug. How to reproduce:

1. Start a kernel
2. Start a console ipython with the kernel in 1.
3. write a simple wrong source code test.py:
for i in range(1):
    print i
4. %pdb in ipython to turn on pdb
5. call test.py from ipython
6. pdb will show on the print line of test.py
7. hit ctrl+c and the kernel hangs forever with the error msg:
ERROR: Cannot interrupt kernels we didn't start.
8. No way to turn back unless closing the kernel (ctrl+\ ), losing all environment.

ipython 2.1.0
python 3.3.5

**Comment by languitar** [comment]
This still seems to exist and I constantly struggle with it. Is there any way to at least get the prompt back even if the kernel cannot be interrupted?
