### ISSUE TITLE
Wish tab completion was sorted by class

### ISSUE THREAD

**Issue by ipython** [ipython/ipython#63]
Original Launchpad bug 319620: https://bugs.launchpad.net/ipython/+bug/319620
Reported by: dholth (Daniel Holth).

Tab completion is hard to use when objects have many methods. It would be nice if IPython could group tab completion possibilities by the class or subclass they were defined in, most-specific-class first.

**Comment by Carreau** [comment]
I'm going to close this as this is really old, and we'll likely take care of that when updating our completer. API. 

Thanks !
