### ISSUE TITLE
Make it much more user friendly to install notebook extensions

### ISSUE THREAD

**Issue by jankatins** [ipython/ipython#6327]
Currently installing nb extensions like toc or python-code-in-markdown is hard, at least if it doesn't work at first try (up to now it never worked at first try :-( )

It would be much nicer if 
- there would be a central repository, like an "ipython extension store" which would list all plugins, including a possibility to submit new ones and submitting one for every major version
- this repository had a "download extension" feature, which would download all required files, install it to the right location and instruct the notebook to load the extension without any other user intervention
- ipython itself had some UI to enable/disable them

**Comment by ellisonbg** [comment]
@takluyver @minrk do you think our current nbextensions capabilities allow us to close this one?

**Comment by takluyver** [comment]
We have not remotely addressed this.

**Comment by dsblank** [comment]
I think that this would be a good project for the Jupyter community at large to develop. I imagine that we could create an API that would be easy to implement across different kernels, and satisfy a number of package-like things.

**Comment by takluyver** [comment]
There are two separate but related pieces. This issue is focussed on pure client side notebook extensions, which would be installed independently of kernels. Let's not conflate that with kernel extensions which need to provide some frontend code as well.

**Comment by ellisonbg** [comment]
Some of this will get resolved with the repo splitting that will require us to figure out how to manage the JS code for widgets outside the notebook core. Targeting this to 4.0.

**Comment by ResidentMario** [comment]
Wanted to know what the progress on this has been, and what this might look like in the [next-gen push](http://blog.jupyter.org/2016/07/14/jupyter-lab-alpha/). Is [`jupyter_nbextensions_configurator`](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator) it?
