### ISSUE TITLE
Output Scrollbar Overlaps Next Cell

### ISSUE THREAD

**Issue by jgoad** [ipython/ipython#6330]
This looks a lot like a similar bug reported in February. The horizontal scroll bar of an output overlaps the next cell so I can't scroll over to see output in the far right columns of a pandas dataframe.

**Comment by ellisonbg** [comment]
I used to see this, but don't any longer. Has this been fixed. @Carreau @jdfreder

**Comment by Carreau** [comment]
IIRC John fixed it.
