### ISSUE TITLE
keycodes.down used for showing tooltips?

### ISSUE THREAD

**Issue by gibiansky** [ipython/ipython#6334]
Hey all!

Quick question about JS in codecell.js (line 205ish):

https://github.com/ipython/ipython/blob/9a0ef7371060d61415f02526caaa3916a6083d28/IPython/html/static/notebook/js/codecell.js#L205

Why are tooltips shown on 'keycodes.down'? They are _actually_ shown on `(`. However, for some reason, pressing `(` yields keycode 40 (which is the down arrow). However pressing the down arrow doesn't _also_ trigger the tooltip.

This is problematic because for IHaskell I need to override this so that tooltips are shown on space, instead of on paren. However, if I override `keycodes.down`, other things break (namely, you have to press spacebar to go down in tab completion lists!)

I am very confused and this seems like a bug / hack. What's going on?

**Comment by ellisonbg** [comment]
We may also want to think about moving away from the `(` trigger for tooltips altogether.

**Comment by Carreau** [comment]
> We may also want to think about moving away from the ( trigger for tooltips altogether.

People are asking for tooltip/completion on more keypress not less.

**Comment by ellisonbg** [comment]
But the reason they are asking for more is that our existing one is broken.

I think all actions should basically have one solid default that we provide
that can work with all kernels.

On Sun, Jan 11, 2015 at 3:20 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> We may also want to think about moving away from the ( trigger for
> tooltips altogether.
>
> People are asking for tooltip/completion on more keypress not less.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/6334#issuecomment-69490992>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
We are a bit puzzled about this. In master, the tooltip is not triggered by `(` at all (it works with shift+tab). For now we are going to close this unless there is another subtle aspect of the bug.
