### ISSUE TITLE
Feasilibity of widgets/layout for mimicking this

### ISSUE THREAD

**Issue by hugadams** [ipython/ipython#6336]
Hello, 

**I wanted to post this to the mailing list but have been having trouble all week.  I obtained permission to post here.  If preferred to go on the mailing list, can someone with access post it, and I'll remove this thread?  Sorry**

We are developing a spectroscopy library and want to put in some interactive plots/utilities to make the software a bit more approachable to novices.  I'd really like to build the entire interactive plotting interface through the notebook's new widget system.  My reasoning is as follows: 
  
   - All static plots are already matplotlib-based, so we wouldn't have to write a seperate plotting api 
   - Notebooks are inherently browser-ready, so sharing plots would be great 
         - Is it likely that static nbviewer will eventually support widgets?  Since the data is required, I figured not... 
   - Our tutorials are already in notebooks, so we'd like to be consistent. 

I've watched all the videos I can find from the widgets, and think I'm fine with the Python end; however, am finding it hard to come by lots of information on controlling the layout of the widgets.  I know it's mostly done in javascript, and I think the most complex view we will have will look something like this: 

https://sites.google.com/site/shigemorita/home/2dshige

How much time would you estimate a javascript novice ought to spend on getting something like that in the notebook?  Can anyone share tutorials for the layout portion of the widget API?  Any information is helpful.  Lastly, does anyone have any hacky ideas of how to bury the source code so that the widgets merely display, rather than the user copy/pasting the widget source into a cell?   

Thanks

**Comment by Carreau** [comment]
Closing to clean up the list of stale issues, and as this is mostly doable, and will simple with things like flexx, or IBM reworking on widgets/dashboard. 

Thanks.
