### ISSUE TITLE
Nbconvert and Math in Markdown Cells

### ISSUE THREAD

**Issue by juhasch** [ipython/ipython#6339]
I have two markdown cells in a notebook:
`$  P_{a} + P_{a} $`
`Text $  P_{a} + P_{a} $`

The first cell gets translated to math, but not the second one:
![latex](https://cloud.githubusercontent.com/assets/2445216/3995244/2c9561a8-2925-11e4-8a73-4e997e5f6030.png)

I am using Python 2.7 + latest IPython master on Windows.

**Comment by ellisonbg** [comment]
Hmm, I can't reproduce this on master. Can you retry with latest master? Can others try to confirm? How do you have MathJax installed. Version?

**Comment by juhasch** [comment]
Works now as expected. Closing.

**Comment by ellisonbg** [comment]
Thanks!
