### ISSUE TITLE
Directory history not saved

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#634]
As reported by Jon on the mailing list.

Directory history (`_dh`) was saved and reloaded from disk in earlier versions.  I can't actually find the code that saves it, although I think it went into the pickleshare database. We should work out what's best to do.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. Five years later, I'd say the answer to @takluyver's question is "no" - at least that's what we went with.

Also worth noting that the command line to enable this is `--StoreMagics.autorestore=True`  - I think there was a rename of StoreMagic --> StoreMagics in a rewrite of plugins/magics stuff in late May 2012.

Thanks everyone and happy hacking! :bowtie:
