### ISSUE TITLE
[UI enhancement] Support "--no-banner" flag in qtconsole

### ISSUE THREAD

**Issue by kini** [ipython/ipython#6343]
Since `ipython qtconsole` displays the same banner as `ipython console`, it would seem to make sense for `ipython qtconsole` to accept a `--no-banner` flag, just as `ipython console` already does, which would make it not display the banner.

**Comment by ccordoba12** [comment]
This is already fixed, so it should be closed

**Comment by Carreau** [comment]
> This is already fixed, so it should be closed

Thanks !
