### ISSUE TITLE
How can I let nbconvert to support unicode for Latex, e.g. Chinese? 

### ISSUE THREAD

**Issue by wegamekinglc** [ipython/ipython#6356]
Currently when I run nbconvert to convert a *.ipynb file to latex, it works fine when only english words are included. However if there is some Chines characters in that file, the output tex file can't be recognized by latex or ctex...

**Comment by jiamo** [comment]
I also find this problem. Windows8.1 python3.4.1 with pandoc 1.13.2 , ipython 2.2.0  installed.   Here is  the tex:  http://pastebin.ubuntu.com/9661229/

**Comment by jiamo** [comment]
There is only one line in the notebook:# 1.1 几何 . And the error message is like:
! Emergency stop.
 ...

l.225     \section{1.1 几何}
                              \label{ux51e0ux4f55}
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on "1 Geometry of Curves.log".

[NbConvertApp] Removing temporary LaTeX files

**Comment by ellisonbg** [comment]
@Carreau isn't the solution of this to run a pdf converter that supports unicode chars. Our default of pdflatex doesn't. The user would have to set a config var to use something like xetex I think. Do others remember the details of this?

**Comment by Carreau** [comment]
We might want to have a look at https://github.com/JelteF/PyLaTeX also. 
I'm fine with switching pdflatex to xelatex or other.

**Comment by ellisonbg** [comment]
I think we should keep our default to pdflatex, but i was thinking the user
could use the ipython configuration system to try xetex.

On Mon, Jan 12, 2015 at 12:25 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> We might want to have a look at https://github.com/JelteF/PyLaTeX also.
> I'm fine with switching pdflatex to xelatex or other.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/6356#issuecomment-69639277>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by mlgill** [comment]
I realize this is an old discussion, but for the benefit of others who find this thread, there is a configuration setting in `ipython_nbconvert_config.py` for swtiching from `pdflatex` to `xetex`:

```c.PDFPostProcessor.latex_command = [u'xetex', u'{filename}']```

I'm using IPython version 3.1.0.

**Comment by Carreau** [comment]
Closing as last message apparently give a solution.
