### ISSUE TITLE
better message on failed saved (e.g. disk full error)

### ISSUE THREAD

**Issue by ivanov** [ipython/ipython#6364]
I brought this up in #6269, on a failed notebook save, the user sees is a cryptic orange "Bad Request" message.
![2014-08-26-143303_182x34_scrot](https://cloud.githubusercontent.com/assets/118211/4052455/c303691a-2d6b-11e4-8539-d66d077184d1.png)

To create a disk full scenario under Linux:
```shell
sudo mkdir /mnt/tiny
sudo mount -t tmpfs -o size=20k tmpfs /mnt/tiny
```
and start a notebook server in /mnt/tiny.

then in a notebook `!dd if=/dev/zero of=bigfile`

**Comment by minrk** [comment]
These messages are better in 3.0.
