### ISSUE TITLE
Find a way to show smth to user when JS fails.

### ISSUE THREAD

**Issue by GaelVaroquaux** [ipython/ipython#6365]
Hi IPython devs,

Sorry for being dense, but after a good hour of fighting, I cannot install IPython 2.x on Ubuntu 14.04. The installation works, but the notebooks don't render, and I believe this is for lack of the different javascript files in the install. Below, I am attaching the logs from both pip, and the server:

**pip log**

<pre>
$ pip install --user --upgrade ipython\[notebook\]
Downloading/unpacking ipython[notebook] from https://pypi.python.org/packages/2.7/i/ipython/ipython-2.2.0-py27-none-any.whl#md5=1503523a69baec078487d862c3d9415b
  Downloading ipython-2.2.0-py27-none-any.whl (2.8MB): 2.8MB downloaded
Downloading/unpacking jinja2 from https://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.7.3.tar.gz#md5=b9dffd2f3b43d673802fe857c8445b1a (from ipython[notebook])
  Downloading Jinja2-2.7.3.tar.gz (378kB): 378kB downloaded
  Running setup.py (path:/tmp/pip_build_varoquau/jinja2/setup.py) egg_info for package jinja2
    
    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
Requirement already up-to-date: pyzmq>=2.1.11 in /home/varoquau/.local/lib/python2.7/site-packages (from ipython[notebook])
Requirement already up-to-date: tornado>=3.1 in /home/varoquau/.local/lib/python2.7/site-packages (from ipython[notebook])
Downloading/unpacking markupsafe from https://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.23.tar.gz#md5=f5ab3deee4c37cd6a922fb81e730da6e (from jinja2->ipython[notebook])
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py (path:/tmp/pip_build_varoquau/markupsafe/setup.py) egg_info for package markupsafe
    
Requirement already up-to-date: certifi in /home/varoquau/.local/lib/python2.7/site-packages (from tornado>=3.1->ipython[notebook])
Requirement already up-to-date: backports.ssl-match-hostname in /home/varoquau/.local/lib/python2.7/site-packages (from tornado>=3.1->ipython[notebook])
Installing collected packages: ipython, jinja2, markupsafe
  Running setup.py install for jinja2
    
    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
  Running setup.py install for markupsafe
    
    building 'markupsafe._speedups' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c markupsafe/_speedups.c -o build/temp.linux-x86_64-2.7/markupsafe/_speedups.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/markupsafe/_speedups.o -o build/lib.linux-x86_64-2.7/markupsafe/_speedups.so
Successfully installed ipython jinja2 markupsafe
Cleaning up...
resting ~/dev/scikit-image $ pip install --user --upgrade ipython\[all\]     
Downloading/unpacking ipython[all] from https://pypi.python.org/packages/2.7/i/ipython/ipython-2.2.0-py27-none-any.whl#md5=1503523a69baec078487d862c3d9415b
  Downloading ipython-2.2.0-py27-none-any.whl (2.8MB): 2.8MB downloaded
Requirement already up-to-date: pyzmq>=2.1.11 in /home/varoquau/.local/lib/python2.7/site-packages (from ipython[all])
Downloading/unpacking nose>=0.10.1 from https://pypi.python.org/packages/source/n/nose/nose-1.3.4.tar.gz#md5=6ed7169887580ddc9a8e16048d38274d (from ipython[all])
  Downloading nose-1.3.4.tar.gz (277kB): 277kB downloaded
  Running setup.py (path:/tmp/pip_build_varoquau/nose/setup.py) egg_info for package nose
    
    no previously-included directories found matching 'doc/.build'
Requirement already up-to-date: tornado>=3.1 in /home/varoquau/.local/lib/python2.7/site-packages (from ipython[all])
Downloading/unpacking Sphinx>=1.1 from https://pypi.python.org/packages/2.7/S/Sphinx/Sphinx-1.2.2-py27-none-any.whl#md5=aa3dccfcf8dd6394b25c61fc1a15fba8 (from ipython[all])
  Downloading Sphinx-1.2.2-py27-none-any.whl (1.1MB): 1.1MB downloaded
Requirement already up-to-date: pygments in /usr/lib/python2.7/dist-packages (from ipython[all])
Downloading/unpacking numpydoc (from ipython[all])
  Downloading numpydoc-0.5.tar.gz
  Running setup.py (path:/tmp/pip_build_varoquau/numpydoc/setup.py) egg_info for package numpydoc
    
Requirement already up-to-date: jinja2 in /home/varoquau/.local/lib/python2.7/site-packages (from ipython[all])
Requirement already up-to-date: certifi in /home/varoquau/.local/lib/python2.7/site-packages (from tornado>=3.1->ipython[all])
Requirement already up-to-date: backports.ssl-match-hostname in /home/varoquau/.local/lib/python2.7/site-packages (from tornado>=3.1->ipython[all])
Downloading/unpacking docutils>=0.7 from https://pypi.python.org/packages/source/d/docutils/docutils-0.12.tar.gz#md5=4622263b62c5c771c03502afa3157768 (from Sphinx>=1.1->ipython[all])
  Downloading docutils-0.12.tar.gz (1.6MB): 1.6MB downloaded
  Running setup.py (path:/tmp/pip_build_varoquau/docutils/setup.py) egg_info for package docutils
    
    warning: no files found matching 'MANIFEST'
    warning: no files found matching '*' under directory 'extras'
    warning: no previously-included files matching '.cvsignore' found under directory '*'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    warning: no previously-included files matching '*~' found under directory '*'
    warning: no previously-included files matching '.DS_Store' found under directory '*'
Requirement already up-to-date: markupsafe in /home/varoquau/.local/lib/python2.7/site-packages (from jinja2->ipython[all])
Installing collected packages: ipython, nose, Sphinx, numpydoc, docutils
  Running setup.py install for nose
    
    no previously-included directories found matching 'doc/.build'
    Installing nosetests script to /home/varoquau/.local/bin
    Installing nosetests-2.7 script to /home/varoquau/.local/bin
  Found existing installation: Sphinx 1.2b1dev-20130726
    Uninstalling Sphinx:
      Successfully uninstalled Sphinx
  Running setup.py install for numpydoc
    
  Running setup.py install for docutils
    changing mode of build/scripts-2.7/rst2html.py from 644 to 755
    changing mode of build/scripts-2.7/rst2s5.py from 644 to 755
    changing mode of build/scripts-2.7/rst2latex.py from 644 to 755
    changing mode of build/scripts-2.7/rst2xetex.py from 644 to 755
    changing mode of build/scripts-2.7/rst2man.py from 644 to 755
    changing mode of build/scripts-2.7/rst2xml.py from 644 to 755
    changing mode of build/scripts-2.7/rst2pseudoxml.py from 644 to 755
    changing mode of build/scripts-2.7/rstpep2html.py from 644 to 755
    changing mode of build/scripts-2.7/rst2odt.py from 644 to 755
    changing mode of build/scripts-2.7/rst2odt_prepstyles.py from 644 to 755
    
    warning: no files found matching 'MANIFEST'
    warning: no files found matching '*' under directory 'extras'
    warning: no previously-included files matching '.cvsignore' found under directory '*'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    warning: no previously-included files matching '*~' found under directory '*'
    warning: no previously-included files matching '.DS_Store' found under directory '*'
    changing mode of /home/varoquau/.local/bin/rst2odt.py to 755
    changing mode of /home/varoquau/.local/bin/rst2xml.py to 755
    changing mode of /home/varoquau/.local/bin/rst2html.py to 755
    changing mode of /home/varoquau/.local/bin/rst2odt_prepstyles.py to 755
    changing mode of /home/varoquau/.local/bin/rst2latex.py to 755
    changing mode of /home/varoquau/.local/bin/rst2man.py to 755
    changing mode of /home/varoquau/.local/bin/rst2xetex.py to 755
    changing mode of /home/varoquau/.local/bin/rstpep2html.py to 755
    changing mode of /home/varoquau/.local/bin/rst2pseudoxml.py to 755
    changing mode of /home/varoquau/.local/bin/rst2s5.py to 755
Successfully installed ipython nose Sphinx numpydoc docutils
Cleaning up...
</pre>

**IPython notebook log**

<pre>
$ ipython notebook    [master] [12:36]
2014-08-27 12:36:44.100 [NotebookApp] Using existing profile dir: u'/home/varoquau/.ipython/profile_default'
2014-08-27 12:36:44.104 [NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
2014-08-27 12:36:44.116 [NotebookApp] The port 8888 is already in use, trying another random port.
2014-08-27 12:36:44.117 [NotebookApp] Serving notebooks from local directory: /home/varoquau/tmp/skimage-tutorials/lectures
2014-08-27 12:36:44.117 [NotebookApp] 0 active kernels 
2014-08-27 12:36:44.117 [NotebookApp] The IPython Notebook is running at: http://localhost:8889/
2014-08-27 12:36:44.117 [NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Created new window in existing browser session.
[14963:15004:0827/123644:ERROR:nss_util.cc(853)] After loading Root Certs, loaded==false: NSS error code: -8018
WARNING:tornado.access:404 GET /static/jqueryui.js (127.0.0.1) 0.85ms referer=http://localhost:8889/notebooks/00_images_are_arrays.ipynb
</pre>

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
