### ISSUE TITLE
Message spec shim doesn't add user_variables on first request

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#6383]
If I start a Julia kernel, the terminal shows 'adapting kernel to 4.0', but the first execution request doesn't get `user_variables` added, causing Julia to throw an error (@stevengj is working around this). Any subsequent requests get user_variables added OK by the adapter, and execute without a problem, so it looks like the adapter just isn't acting on the first execute_request for some reason.

**Comment by minrk** [comment]
This is fixed, now that opening the channels waits for the initial kernel_info_reply
