### ISSUE TITLE
ipython.parallel in wsgi app

### ISSUE THREAD

**Issue by bsdis** [ipython/ipython#6386]
When importing IPython.parallel in a script running as a wsgi service, an error occurs:

[Sat Aug 30 21:36:52.586183 2014] [:error] [pid 7469] [remote 10.252.230.165:51802] mod_wsgi (pid=7469): Target WSGI script '/home/opta/www/env/pyramid.wsgi' cannot be loaded as Python module.
[Sat Aug 30 21:36:52.586274 2014] [:error] [pid 7469] [remote 10.252.230.165:51802] mod_wsgi (pid=7469): Exception occurred processing WSGI script '/home/opta/www/env/pyramid.wsgi'.
[Sat Aug 30 21:36:52.586316 2014] [:error] [pid 7469] [remote 10.252.230.165:51802] Traceback (most recent call last):
[Sat Aug 30 21:36:52.586338 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]   File "/home/opta/www/env/pyramid.wsgi", line 4, in <module>
[Sat Aug 30 21:36:52.586493 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]     application = get_app(ini_path, 'main')
[Sat Aug 30 21:36:52.586510 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]   File "/home/opta/www/env/lib/python3.3/site-packages/pyramid/paster.py", line 31, in get_app
[Sat Aug 30 21:36:52.586672 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]     global_conf=options)
[Sat Aug 30 21:36:52.586689 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]   File "/home/opta/www/env/lib/python3.3/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Sat Aug 30 21:36:52.586988 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]     return loadobj(APP, uri, name=name, *_kw)
[Sat Aug 30 21:36:52.587005 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]   File "/home/opta/www/env/lib/python3.3/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
[Sat Aug 30 21:36:52.587044 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]     return context.create()
[Sat Aug 30 21:36:52.587060 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]   File "/home/opta/www/env/lib/python3.3/site-packages/paste/deploy/loadwsgi.py", line 710, in create
[Sat Aug 30 21:36:52.587086 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]     return self.object_type.invoke(self)
[Sat Aug 30 21:36:52.587100 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]   File "/home/opta/www/env/lib/python3.3/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
[Sat Aug 30 21:36:52.587126 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]     return fix_call(context.object, context.global_conf, *_context.local_conf)
[Sat Aug 30 21:36:52.587140 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]   File "/home/opta/www/env/lib/python3.3/site-packages/paste/deploy/util.py", line 55, in fix_call
[Sat Aug 30 21:36:52.587167 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]     val = callable(_args, *_kw)
[Sat Aug 30 21:36:52.587181 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]   File "/home/opta/www/env/zebra/zebra/**init**.py", line 13, in main
[Sat Aug 30 21:36:52.587207 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]     config.scan()
[Sat Aug 30 21:36:52.587221 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]   File "/home/opta/www/env/lib/python3.3/site-packages/pyramid/config/**init**.py", line 930, in scan
[Sat Aug 30 21:36:52.587248 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]     ignore=ignore)
[Sat Aug 30 21:36:52.587263 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]   File "/home/opta/www/env/lib/python3.3/site-packages/venusian/**init**.py", line 205, in scan
[Sat Aug 30 21:36:52.587289 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]     **import**(modname)
[Sat Aug 30 21:36:52.587303 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]   File "/home/opta/www/env/zebra/zebra/views.py", line 3, in <module>
[Sat Aug 30 21:36:52.587417 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]     import IPython#.parallel
[Sat Aug 30 21:36:52.587434 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]   File "/home/opta/www/env/lib/python3.3/site-packages/IPython/**init**.py", line 48, in <module>
[Sat Aug 30 21:36:52.587610 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]     from .core.application import Application
[Sat Aug 30 21:36:52.587646 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]   File "/home/opta/www/env/lib/python3.3/site-packages/IPython/core/application.py", line 40, in <module>
[Sat Aug 30 21:36:52.587877 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]     from IPython.core import release, crashhandler
[Sat Aug 30 21:36:52.587894 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]   File "/home/opta/www/env/lib/python3.3/site-packages/IPython/core/crashhandler.py", line 28, in <module>
[Sat Aug 30 21:36:52.588064 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]     from IPython.core import ultratb
[Sat Aug 30 21:36:52.588081 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]   File "/home/opta/www/env/lib/python3.3/site-packages/IPython/core/ultratb.py", line 110, in <module>
[Sat Aug 30 21:36:52.588539 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]     from IPython.core import debugger
[Sat Aug 30 21:36:52.588556 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]   File "/home/opta/www/env/lib/python3.3/site-packages/IPython/core/debugger.py", line 36, in <module>
[Sat Aug 30 21:36:52.588823 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]     from IPython.utils import coloransi, io, py3compat
[Sat Aug 30 21:36:52.588840 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]   File "/home/opta/www/env/lib/python3.3/site-packages/IPython/utils/io.py", line 86, in <module>
[Sat Aug 30 21:36:52.589036 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]     stdout = IOStream(sys.stdout, fallback=devnull)
[Sat Aug 30 21:36:52.589053 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]   File "/home/opta/www/env/lib/python3.3/site-packages/IPython/utils/io.py", line 45, in **init**
[Sat Aug 30 21:36:52.589081 2014] [:error] [pid 7469] [remote 10.252.230.165:51802]     setattr(self, meth, getattr(stream, meth))
[Sat Aug 30 21:36:52.589112 2014] [:error] [pid 7469] [remote 10.252.230.165:51802] AttributeError: 'mod_wsgi.Log' object has no attribute 'name'

It seems ipython tries to redirect stdout but fails to do so. 
A quick and dirty workaround i did was in
IPython/utils/io.py
to change line 45 from

```
    for meth in filter(clone, dir(stream)):
         setattr(self, meth, getattr(stream, meth))
```

to

```
    for meth in filter(clone, dir(stream)):
        try:
            setattr(self, meth, getattr(stream, meth))
        except AttributeError:
            pass
```

Is it possible to fix this in a nicer way?

**Comment by cjwelborn** [comment]
@Carreau, @ellisonbg  This bug hit me in my django app. It's only reproducible when the mod_wsgi app is running. I'm not doing anything with `parallel`. It was triggered by `pygments.get_all_lexers()`, since IPython was installed recently, it tried to load the IPython lexer and caused this. I have a traceback (I was gathering a list of lexer names/aliases from pygments when it errored):

**IPython version:** `5.1.0`

```
File "/home/cj/scripts/welbornprod/wp_site/wp_main/utilities/highlighter.py" in <listcomp>
  35. LEXERNAMES = [lexer_[1] for lexer_ in lexers.get_all_lexers()]

File "/usr/lib/python3/dist-packages/pygments/lexers/__init__.py" in get_all_lexers
  53.     for lexer in find_plugin_lexers():

File "/usr/lib/python3/dist-packages/pygments/plugin.py" in find_plugin_lexers
  53.         yield entrypoint.load()

File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py" in load
  2249.         return self.resolve()

File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py" in resolve
  2255.         module = __import__(self.module_name, fromlist=['__name__'], level=0)

File "/usr/local/lib/python3.5/dist-packages/IPython/__init__.py" in <module>
  49. from .terminal.embed import embed

File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/embed.py" in <module>
  16. from IPython.core.interactiveshell import DummyMod, InteractiveShell

File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py" in <module>
  62. from IPython.utils import io

File "/usr/local/lib/python3.5/dist-packages/IPython/utils/io.py" in <module>
  93.     stdout = IOStream(sys.stdout, fallback=devnull)

File "/usr/local/lib/python3.5/dist-packages/IPython/utils/io.py" in __init__
  42.             setattr(self, meth, getattr(stream, meth))

Exception Type: AttributeError at /misc/xtools
Exception Value: 'mod_wsgi.Log' object has no attribute 'name'
```

I haven't dug into the ipython source, but can we forget about the `name` in case of this error? I'd like to get my little project up and going, so I'll hack it in if I need to.

Thanks,
-Chris

**Comment by takluyver** [comment]
It's trying to get `sys.stdout.name`, which must mean that `dir(sys.stdout)` has returned a list including `'name'`. So that sounds like something is broken in mod_wsgi.

**Comment by cjwelborn** [comment]
`getattr` can fail in many ways even when the attributes come from `dir`. I've seen it quite a few times, though I can probably provide some proof when I get back home. There is a 6 character fix that can be applied here (`getattr(stream, meth, None)`). That's why I was asking if `name` was absolutely required, because with this little change it would be skipped over. Maybe `mod_wsgi` is in the wrong here, but I don't see a problem with fixing a small edge case.

**Comment by takluyver** [comment]
Fair enough. Want to make a pull request?

**Comment by cjwelborn** [comment]
Yes, I'll get it done this evening (I'm on central time). Thanks 😀

**Comment by cjwelborn** [comment]
@takluyver Will PR #10191 work for you? All tests passed, plus [one extra test I added](https://github.com/ipython/ipython/pull/10191/files#diff-0416844b97da9db849967eb6d82ebe0aR71) for this specific edge case.

**Comment by GrahamDumpleton** [comment]
From memory ``dir()`` returns name because what ``dir()`` is being run on is actually a wrapper/proxy. When you access ``name``, the wrapper/proxy actually then tries to access the real file like object which is wraps and if that doesn't have it, and it is permitted not to have it, then the lookup fails. The problem is arguably in the way the wrapper/proxy is implemented, but transparent proxies that properly reflect the wrapped object is hard.

Code using the file object associated with ``sys.stdin``, ``sys.stdout`` and ``sys.stderr``, which doesn't accomodate that certain attributes are optional has come up before with mod_wsgi. Main case I can remember is the ``isatty()`` method, which is not supposed to be implemented if the file like object is not associated with a real file, but code out there does assume it always exists. In that case an implementation of ``isatty()`` was added which returned ``False`` to avoid the problem.

So no big deal for me to also add a ``name`` attribute to the mod_wsgi ``Log`` object as no doubt this will come up again.
