### ISSUE TITLE
TypeError: 'unicode' does not have the buffer interface (error printing traceback)

### ISSUE THREAD

**Issue by dholth** [ipython/ipython#6397]
When using Pyramid's `pshell` with Python 2.7.5 and IPython 2.0.2 (IPython is the underlying shell implementation if available), certain tracebacks error out in traceback.py's `_print()` function with the cryptic message `'unicode' does not have the buffer interface`.

What's happening here is that `file` is `io.BytesIO()` while `line.strip()` is unicode. I've fixed it by editing traceback.py to include `line.strip.encode('utf-8')`.

If it is in fact IPython setting file to `io.BytesIO()` then it would be better if IPython could do something to make this "just work" instead of having to edit Python's standard library.

```
python2.7/traceback.py(25)print_list()
     24         if line:
---> 25             _print(file, '    %s' % line.strip())
     26 

python2.7/traceback.pyc in _print(file, str, terminator)
     11 
     12 def _print(file, str='', terminator='\n'):
---> 13     file.write(str+terminator)
     14 
     15 

TypeError: 'unicode' does not have the buffer interface
```

**Comment by Carreau** [comment]
Closing as inactive.
