### ISSUE TITLE
offer a sphinx built as download

### ISSUE THREAD

**Issue by ipython** [ipython/ipython#64]
Original Launchpad bug 420123: https://bugs.launchpad.net/ipython/+bug/420123
Reported by: timmie (Tim).

It would be good to have the Sphinx docs for download or offline reading at:
http://ipython.scipy.org/moin/Download

This could be offered for the latest stable release.

Thanks.

**Comment by Carreau** [comment]
With all the readthedocs builds and the future work we will make for documentation, I'm closing this as stale. 

Please reopen an new issue if needed. 

Thanks !
