### ISSUE TITLE
Latex tab completions leave extra backslash in terminal console

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#6442]
In `ipython console`:

```
\alp<TAB> -> \\alpha
\alpha<TAB> -> \α
```

In both cases, there's a backslash left over that shouldn't be there. It works in the notebook and the Qt console.

**Comment by minrk** [comment]
This appears to be fixed.

**Comment by takluyver** [comment]
I can still reproduce the failure.

**Comment by minrk** [comment]
My mistake. Bug does not affect greedy completion, only `greedy=False`.

**Comment by minrk** [comment]
should be fixed by #7497
