### ISSUE TITLE
several bugs in ipython nbconvert --to latex

### ISSUE THREAD

**Issue by schlichtanders** [ipython/ipython#6466]
I found a whole bunch of bugs in the conversion from the ipython notebook to the latex representation - compared to the html version - and created a minimized test-case.

I mailed this bug-report recently under the same header to the ipython-dev mailing list. This is now the corresponding issue.
The test notebook and its html and latex translation are now on https://gist.github.com/schlichtanders/e108ed0be80108178af2 (pdfs versions not included)

As I now understand how to circumvent the gaps, I can use the latex conversion perfectly, but nevertheless I think those bugs deserve to be fixed.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
