### ISSUE TITLE
IPython Notebook RadioButtonsWidget value cannot be string representation of an integer.

### ISSUE THREAD

**Issue by davidhsmith** [ipython/ipython#6469]
A simple example:

```
def f(a, b):
  print (a,b)

b = widgets.ToggleButtonsWidget(description='kVpe:', values=[' -3', ' 0', u'3'], value=' 0')
b.on_trait_change(f, 'value')
display(b)
```
This works fine in an IPython cell and the user can click the first or second button.  However, clicking the third button, labeled '3', results in a stack trace followed by the following message:

  TraitError: The 'value_name' trait of a ToggleButtonsWidget instance must be a unicode string, but a value of 3 <type 'int'> was specified.

Note that the first two (working) buttons contain a space in front of the number.  Lacking this space, the third button issues the TraitError exception.

I am using IPython Notebook version 2.2.
(Pardon my limited experience with github markdown).

**Comment by minrk** [comment]
This is fixed in master
