### ISSUE TITLE
%%cython magic module caching behavior confusing

### ISSUE THREAD

**Issue by vallis** [ipython/ipython#6507]
The %%cython magic builds an importable module with name derived from the hash of the cell. If the hash does not change, the cell code is not recompiled.

However, this creates a confusing problem when compilation fails because, say, the path of a required library was not given correctly as an argument to %%cython. Changing the %%cython arguments and running the cell again does not recompile the module, so the failure persists.

The solution would be to derive the hash from the entire cell, including the first line.

**Comment by ellisonbg** [comment]
Looks resolved, closing.
