### ISSUE TITLE
Force a variable to sync immediately?

### ISSUE THREAD

**Issue by lavery3** [ipython/ipython#6508]
I'm working on a custom widget, and the model needs to know the size of the browser window. I created the model, which doesn't yet do anything, thus:

```
class ROIMultiPointWidget(widgets.DOMWidget):
    _view_name = Unicode('ROIMultiPointWidgetView', sync=True)
    imageWidth = Float(sync=True)
    imageHeight = Float(sync=True)
    imageURL = Unicode(sync=True)
    width = Integer(sync=True)
    height = Integer(sync=True)
    windowWidth = Integer(sync=True)
    windowHeight = Integer(sync=True)

    def __init__(self, image=None):
        super(widgets.DOMWidget, self).__init__()
        self.msg_throttle = 0
        self.imageWidth, self.imageHeight = image.size
        self.send_state()
```

On the JS side, I have:

```
define(["widgets/js/widget",
    "components/raphael/raphael"],
function(WidgetManager, Raphael) {

var ROIMultiPointWidgetView = IPython.DOMWidgetView.extend({
    initialize: function() {
    console.log('initialize');
    ROIMultiPointWidgetView.__super__.initialize.apply(this, arguments);
    var w = Math.max(document.documentElement.clientWidth,
             window.innerWidth || 0);
    var h = Math.max(document.documentElement.clientHeight,
             window.innerHeight || 0);
    this.windowWidth = w;
    this.windowHeight = h;
    this.model.msg_throttle = 0;
    this.model.set('windowWidth', w);
    this.model.set('windowHeight', h);
    this.touch();
    },
...
```

followed by other stuff.

This doesn't work as I intended. In particular, right after creation of a new widget, it's windowWidth and windowHeight traitlets are zero. If I fool around in the browser to create traffic between the frontend and the kernel, the values propagate to the ROIMultiPointWidget, but I can't figure out a way to make this happen programmatically. 

Is there a way to force an update? Comments like "Your whole strategy is wrong -- you should be doing is this way: ..." would also be welcome.

Thanks.

**Comment by ellisonbg** [comment]
@jdfreder can you comment on this one?

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
