### ISSUE TITLE
formailize allowed backward-compatible nbformat changes

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#6519]
Now that #6045 introduces notebook validation, we should define what sort of backward-compatible changes are allowed in the notebook format that qualify for a minor revision. In 3.x-series, we defined it loosely as new properties that were safely ignored (metadata was added in various places, under this rule). The current validation supports this by skipping any `additionalProperties: false` validations for notebooks from the future. Other possible backward-compatible changes we could allow:

- new output types
- new cell types

These would need to be handled in the code (mainly javascript) by loading the unrecognized output or cell with a simple placeholder. It need not be editable, just indicate that there's something there that the UI doesn't understand.

We don't need to have this all done before merging #6045, but we should have a pretty formal idea of what sort of extensions we allow before our next backward-incompatible nbformat change (hopefully a very long time from now).

**Comment by ellisonbg** [comment]
What is the status of this issue @minrk ?

**Comment by takluyver** [comment]
@minrk I seem to remember that you addressed this. Can it be closed?

**Comment by minrk** [comment]
I think the only thing missing is expressing it in the nbformat docs. The code should all be done.
