### ISSUE TITLE
Use with eventlet caused a crash

### ISSUE THREAD

**Issue by boothead** [ipython/ipython#652]
The problem came when pressing Ctrl-D to exit. My money is on something to do with eventlet patching the the threading library. 

The crash report is attached.

thanks,
Ben

**Comment by ivanov** [comment]
Hey ya'll, I'm going through old issues and it seems to me that it makes sense to close this one. Min mentioned this being a duplicate of #207, which was closed by #876 - so this issue should be fixed. Thanks everyone!

Happy hacking! :bowtie:
