### ISSUE TITLE
Same widget does not update all interact. 

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#6534]
Cf [Stackoverflow](https://stackoverflow.com/questions/25945543/can-values-from-ipython-widgets-propagate-to-other-cells/25992790#25992790) 

having the same widget (say a Checkbox) shared by 2 interact, the value of the checkbox is updated across cell, but the interactived' function not call. Ex:

![capture d ecran 2014-09-24 a 08 30 40](https://cloud.githubusercontent.com/assets/335567/4384325/e7c2de98-43b4-11e4-9264-74546270de13.png)

I clicked on first checkbox, second was highligted, but value did not changed from True to False.

**Comment by ellisonbg** [comment]
@jdfreder can you have a look at this?

**Comment by ellisonbg** [comment]
If two cells have exactly the same overall widget hierarchy displayed, then I think this behavior makes sense. But it is entirely possible that a single widget will appear in multiple cells that have completely different overall widget hierarchies. I think the old behavior might make sense. IIRC this was a deliberate choice that we made early on, but @jdfreder will (hopefully) remember more. 

We also need to check to see how this interplays with the output widget.

**Comment by minrk** [comment]
ok, that sounds much too complicated to be appropriate for 3.0. I think we should table this, and mark as 4.0.

**Comment by ellisonbg** [comment]
OK sounds good.

On Thu, Jan 15, 2015 at 2:45 PM, Min RK <notifications@github.com> wrote:

> ok, that sounds much too complicated to be appropriate for 3.0. I think we
> should table this, and mark as 4.0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/6534#issuecomment-70177052>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
If interact used an output widget context manager to wrap the output and included that output in the Box widget that all of the other interact controls are in, I don't think you'd see this problem.  I think what's happening here is that the output is only getting routed to the active cell (as designed).

**Comment by ellisonbg** [comment]
+1 on making this for 4.0.

**Comment by jasongrout** [comment]
+1 to having stdout/stderr by default only going to the cell the action happened on, but explicitly capturing output in an output widget would display the output everywhere there was the output widget view.  In other words, +1 to @jdfreder's comment, if I understood him correctly.

**Comment by jdfreder** [comment]
I still think the right solution for this is to use OutputWidgets, but that'll have to wait until we figure out how that will be persisted in or alongside notebooks.

**Comment by jdfreder** [comment]
Moved to ipython/ipywidgets#163
