### ISSUE TITLE
[Optionally] Trigger a webhook when server starts

### ISSUE THREAD

**Issue by rgbkrk** [ipython/ipython#6567]
When a notebook server comes online, have it hit a webhook to let another server know when it has started. This would be used by JupyterHub and tmpnb.

Possible client arguments:

```
ipython notebook --callback-url="https://127.0.0.1:9999/api/webhooks/29fa19098ec7"
```

**Comment by ellisonbg** [comment]
Marked as 4.0, but feel free to retarget to 3.0 if you need it ASAP.

**Comment by rgbkrk** [comment]
Nope, just a convenience that Min and I noted for Docker related spawning (for JupyterHub and tmpnb). Not high on the priority list.

**Comment by rgbkrk** [comment]
Closing since this belongs in jupyter/notebook.
