### ISSUE TITLE
browser cache madness

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#6576]
I spent a bit of time investigating our caching issue, in part because the move to require.js has made the situation much worse in everyday use. It is complicated, because it affects regular users and those of us who live on master quite differently. I haven't found a good solution, and I don't really believe there is one. There are, however, several mediocre solutions, which benefit different use cases to different degrees.

## Summary of the situation:

- Cache-control can prevent browsers from requesting a URL if it has been seen before.
- ETag + 304 prevents browsers from redownloading content they already have,
  even if they are requesting the same URL again.
- tornado adds a URL parameter based on the hash of the file
  when you use `static_url(...)` in a template.
- By default, tornado only does this once per file for the lifetime of the server,
  so even refreshing a page will get the cached version,
  though restarting the server should reliably clear the cache for the file
- When we switched to require.js, the URLs for most things no longer include
  the hash, so caching has fallen back to browser default behavior (cache survives across server restarts, even when it shouldn't)

### Disable browser cache, rely on 304

This is by far the simplest to implement, and easiest to get right every time. Simply set the cache headers so that static files aren't cached. The browser will make a request for every static file every time, but *content* will be cached. The big downside is that this has a noticeable impact on page load time for notebooks, which load a very large number of javscript files. If we used minified (or just concatenated) javascript with `r.js`, it would reduce the number of javascript requests to one, which would make this more feasible. Which brings us to...

### use minified javascript per-page

This would be best for stable-release users, because it would be the simplest, most reliable, and most efficient. It would also probably be the worst for day-to-day developers, because it would mean a build step when working on javascript. If we don't track the compiled result, it would also mean a nodejs build step is required just to install from master.

### use tornado `static_url` for everything loaded by require

`require` doesn't *need* to omit the tornado hash param. Unfortunately, the only way I see to get it to work is to include a URL entry in require config for every single javascript file in `static`. But since tornado caches the hashes only once, walking the tree only needs to happen one time in the server's lifetime. This one is a bit weird and gross, but it has the easiest to understand behavior: files will be cached for the lifetime of the server, and restarting the server will clear the cache of any files that changed. Any files that didn't change will continue to be cached.

## Summary

That's not all of the solutions, just the ones that I have thought about and tried locally. I'm assuming that minifying/concatenating javascript isn't going to fly, because it's too annoying for developers and users on master. So I would current lean toward using `static_url` to compute hashed URLs for `require`d files. We can also consider having different behavior for development installs (e.g. never cache, rely on 304), which has load-time consequences, but easy update benefits. This could also be governed by a flag, instead of checking the install type.

**Comment by Carreau** [comment]
@minrk can this one be considered closes now ? As we did the solution that you said would not fly?
