### ISSUE TITLE
AttributeError: 'QtInProcessShellChannel' object has no attribute '_handle_kernel_info_reply'

### ISSUE THREAD

**Issue by mfitzp** [ipython/ipython#6578]
The `QtInProcessShellChannel` attempts to forward kernel info messages using a callback `_handle_kernel_info_reply` which does not exist (`kernel_mixins.py:77`)

        if msg_type == 'kernel_info_reply':
            self._handle_kernel_info_reply(msg)

Looking at the class definition above I think the fix would be:

        if msg_type == 'kernel_info_reply':
            self.kernel_info_reply.emit(msg)

**Comment by ellisonbg** [comment]
@takluyver can this one be closed?

**Comment by takluyver** [comment]
Yes, I think so.
