### ISSUE TITLE
WidgetManager has no attribute register_widget_view

### ISSUE THREAD

**Issue by gabrielelanaro** [ipython/ipython#6610]
Hi! I'm using last version of IPython and I'm trying to make custom widgets to work. I'm having problems with the Javascript here:

    require(["widgets/js/widget"], function(WidgetManager){
        
        // Define the DatePickerView
        var DatePickerView = IPython.DOMWidgetView.extend({
            render: function(){ this.$el.text('Hello World!'); },
        });
        
        // Register the DatePickerView with the widget manager.
        WidgetManager.register_widget_view('DatePickerView', DatePickerView);
    });

The problem is that the WidgetManager is not actually the WidgetManager as defined in widgets/js/manager, rather it is an object whose attributes are:

    Object {WidgetModel: function, WidgetView: function, DOMWidgetView: function}

What can the problem be?

Specific Commit:
https://github.com/ipython/ipython/commit/31b050655fe24be0d7ee3b3dd4db58d33f6fa39a

**Comment by jacksonloper** [comment]
I think the question you're really asking is "Where on earth is the API for the IPython javascript library?!!?!"  I, too, have been wondering about this.  Bizarrely, I think the answer is: there isn't one.  

But the answer you're looking for is:

require(["widgets/js/widget", "widgets/js/manager"], function(widget, manager){
    
    var HelloView = widget.DOMWidgetView.extend({
        
        // Render the view.
        render: function(){ 
            this.$el.text('Hello World!'); 
        },
    });
    
    manager.WidgetManager.register_widget_view('HelloView', HelloView);
});

**Comment by minrk** [comment]
We are working on docs for the js. One reason we haven't felt a lot of pressure to do that is that there are currently *zero* stable public APIs in the IPython javascript, so absolutely everything is in a state of "use at your own risk, and assume it will break on next release".

**Comment by parente** [comment]
In running through all the tutorials for issue #7350, I hit this problem too in the `examples/Interactive Widgets/Date Picker Widget.ipynb`. Should the tutorial get fixed or ditched if the API is unstable?
