### ISSUE TITLE
Nbconvert and Unicode highlighing

### ISSUE THREAD

**Issue by juhasch** [ipython/ipython#6618]
If I have unicode variable names in a Python 3 notebook, and use `nbconvert` to convert the notebook to HTML, I get error markers from syntax highlighting:
![pylexer](https://cloud.githubusercontent.com/assets/2445216/4515160/35357c40-4bac-11e4-90ed-9455d79f7bf0.png)
Now if I replace `IPythonLexer()` with `IPython3Lexer()` in `highlight.py`, `nbconvert` shows the expected behavior:
![py3lexer](https://cloud.githubusercontent.com/assets/2445216/4515161/37dc8dda-4bac-11e4-99ad-57490e33dfb9.png)

I suspect it would be possible to modify `basic.tpl` to send the codemirror mode name and version to `highlight.py` to select the correct lexer ?

**Comment by takluyver** [comment]
This now appears to work - if you write a notebook with Python 3, it uses the IPython3 lexer and doesn't draw red boxes around non-ascii characters. Closing.
