### ISSUE TITLE
Need a way to import from python script.

### ISSUE THREAD

**Issue by rvraghav93** [ipython/ipython#6628]
Using `ipython notebook --script` saves a copy of the IPython notebook as a python script with the metadata of the cells ( I feel so ) preserved as comments.

I suggest that there should be a way to convert back to ipython notebook given this python script.

Use cases : 

* Direct operations / Modifications to the python script could be done as a whole file and restored back to the notebook.

* Certain tools like `autopep8` operate only on a python script. Hence the `.ipynb ---> .py  --autopep8--> .py ----> .ipynb` should become feasible once this feature is included.

Also I need a small clarification ... When downloaded as a python file ( using the File --> Download as ) the contents are different compared to the python script generated using `ipython notebook --script`. Why is that so ? Only the latter seems to preserve the metadata in a disambiguous manner. The former method does not ( the commented metadata could as well be a regular comment )

**Comment by btel** [comment]
@minrk is there a way to convert python .py script *into* notebook. I think this was the request in this issue. Round-tripping is not strictly necessary, but it would be nice feature anyway (running PEP8 checkers being one example and easy diffing/merging another),
