### ISSUE TITLE
Ghosts of interact past?

### ISSUE THREAD

**Issue by ahhsia** [ipython/ipython#6636]
I  get an every increasing set of plots from a single interact cell in the notebook when running a SelectWidget and changing the plot function.

Originally, I was using subplot instead of just plot because I was attempting to get 2 different types graphs to change simultaneously with the interactive widgets. So, while the test case below doesn't really need subplot, it is the simplest testcase I have that showcases the odd behavior.

If I run this:
<pre><code>    w1= widgets.SelectWidget(values=[4,5,6], value=4) </code></pre> 

<pre><code>
   @interact(a = w1)
    def viewer(a):
        fig,ax=plt.subplots()
        #ax.plot(range(a))
        ax.plot(range(a+1))
 </code></pre> 
And then go back and change the ax.plot command,(e.g. reverse the commenting on the ax.plot commands shown here), rerun the cell and select a new value, I will end up with 2 figures.
The more times I change the plot command, the longer the chain of figures I will end up with.

![ghost](https://cloud.githubusercontent.com/assets/2042495/4534573/4df428e2-4da7-11e4-9c75-81a133339d52.png)

**Comment by ellisonbg** [comment]
@jdfreder can you comment on this one and set an appropriate milestone?

**Comment by takluyver** [comment]
@jdfreder this was milestoned for 4.0, though I think that might have been just to get you to look at it. Can you have a look and, if you think something needs to be done, make an issue on ipywidgets and close this one.

**Comment by jdfreder** [comment]
I can confirm this.
