### ISSUE TITLE
Allow widgets to provide frontend code

### ISSUE THREAD

**Issue by jgosmann** [ipython/ipython#6696]
To use widget the front end code has to be loaded by either executing it in an IPython notebook cell or a call to `display(Javascript(code))`. As a widget won't work without it's front end code, I would like to see a way to store the front end code (or the path to it) in the widget's class and have IPython automatically load it (ideally this will happen only the first time the widget is instantiated in a notebook).

**Comment by jasongrout** [comment]
@ellisonbg, @takluyver: this should probably be closed since #6494 was merged.

**Comment by takluyver** [comment]
Thanks for the reminder.
