### ISSUE TITLE
trait_names and __getattr__ in third-party modules, like RPC libs

### ISSUE THREAD

**Issue by katyukha** [ipython/ipython#6698]
Hello!

Take for example RPC library, like my [OpenERP Proxy (v0.4)](https://github.com/katyukha/openerp-proxy), that uses __getattr__ to get remote method proxy in a way like ```service.my_cool_remote_method()```, and when I type ```service.<tab>``` in IPython, I got ```service.trait_names()``` remote method called. This also applicable for any object that returns something for any *getattr* request.

The code which do this is in file https://github.com/ipython/ipython/blob/master/IPython/utils/dir2.py:

```python
    # for objects with Enthought's traits, add trait_names() list
    # for PyCrust-style, add _getAttributeNames() magic method list
    for attr in ('trait_names', '_getAttributeNames'):
        try:
            func = getattr(obj, attr)
            if callable(func):
                words |= set(func())
        except:
            # TypeError: obj is class not instance
            pass
```

Is it posible to use something like ```isinstance(obj, HasTraits)``` to check if object have method ```trait_names```?

Google search for this problem points me to [[IPython-user] That trait_names attribute bit me!](http://mail.scipy.org/pipermail/ipython-user/2008-December/006087.html)

 **To reproduce**:

1. run *IPython* shell
2. run ```%edit``` and insert next code in editor

    ```python
    class Test(object):
        def __getattr__(self, name):
            if not name.startswith('_'):    # exclude private methods
                def method_proxy(*args, **kwargs):
                    sargs = ', '.join(args)
                    skwargs = ', '.join(('%s=%s' % (k, v) for k, v in kwargs.items()))
                    print "\n- call to method '%s(%s)'" % (name, ', '.join([i for i in (sargs, skwargs) if i]))
                    return False
                return method_proxy
            raise AttributeError("Test object has not attribute '%s'" % name)
    ```
3. type in IPython shell

    ```
        In [29]: t = Test()
        In [30]: t.<tab>
        - call to method 'trait_names()'
    ```
    Notice printed line *- call to method 'trait_names()'*

IPython version:

```
$ ipython --version
2.1.0
```

**Comment by takluyver** [comment]
We've also considered checking for an attribute like `_this_should_never_really_exist_on_an_object_` - if it seems to exist, then we can assume that the object is a proxy of some kind that's using `__getattr__` to pretend it has all attributes.

**Comment by katyukha** [comment]
Seems to be fixed)
