### ISSUE TITLE
Reset matplotlib 1.4 style of inline figures in the notebook

### ISSUE THREAD

**Issue by Juanlu001** [ipython/ipython#6707]
When using matplotlib 1.4 in the notebook and manually set a style:

```
%matplotlib inline
import matplotlib.pyplot as plt
# ---
plt.style.use('bmh')  # say
```

I cannot get back to the previous appearance. I tried `plt.rcdefaults()` as suggested in matplotlib/matplotlib#2236 but IPython makes its own changes to those, so I get a uglier figure. Perhaps it should be better to provide these settings as an `ipynb` style?

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
