### ISSUE TITLE
Newcommands and conversion to LaTeX

### ISSUE THREAD

**Issue by ycopin** [ipython/ipython#6722]
Hi, 

I can introduce LaTeX-style new commands (or similar stuff) in the notebook, and they are properly handled by mathjax in the nbviewer. See e.g. [this example](http://nbviewer.ipython.org/urls/dl.dropbox.com/s/s5o4ao6t62q4npj/Intrinsic%20dispersion.ipynb), where the `newcommand`s are included in the 1st markdown cell):

``` latex
$
\renewcommand{\d}{\mathrm{d}}
\renewcommand{\v}[1]{\boldsymbol{#1}} % Vector
\renewcommand{\m}[1]{\mathsf{#1}} % Matrix
\DeclareMathOperator{\Var}{Var}
\DeclareMathOperator{\Cov}{Cov}
\DeclareMathOperator{\argmin}{argmin}
$
```

However, when exporting to LaTeX (`ipython nbconvert --to latex Intrinsic\ dispersion.ipynb --post pdf`), this generates the invalid LaTeX escaped code:

``` latex
\$
\renewcommand{\d}{\mathrm{d}}
\renewcommand{\v}{[}1{]}\{\boldsymbol{#1}\} \% Vector
\renewcommand{\m}{[}1{]}\{\mathsf{#1}\} \% Matrix
\DeclareMathOperator{\Var}{Var} \DeclareMathOperator{\Cov}{Cov}
\DeclareMathOperator{\argmin}{argmin} \$
```

Just editing the LaTeX file to copy the initial commands in the preamble makes it perfectly functional. 

Is there a way to circumvent this bug?

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.

**Comment by ycopin** [comment]
Do you mean it should be transferred to Jupyter? Do you have an idea of which part specifically? (nbconvert?)

**Comment by Carreau** [comment]
Yes,  jupyter/nbconvert seem like the right place to migrate. Let me see if the automigration works

@meeseeksdev migrate to jupyter/nbconvert

**Comment by Carreau** [comment]
Hum.. app crashed. I'll have to fix the bot.
