### ISSUE TITLE
Kernel Adapter python specific.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#6741]
Kernel Adapter message spec v4/v5 use python tokenize to convert from 5.0 to 4.0, especially to get token as curent cursor position. The tokenizing assume that the underlying language is Python. In particular the tokenizer will choke on chars that are not valid in python. EG, `!` (Julia) and probably `$` in R and Haskell. This lead to impossibility to inspect things like `push!` (Julia) and get tooltip, even if use select the token to inspect and press shift-tab. 

In IPython 2.x is was customizable through `custom.js`, but nothind can be done in 3.0 unless fully implementing message-spec v5.

**Comment by ellisonbg** [comment]
@Carreau and @minrk is there anything for 3.0 we need to do for this?

**Comment by minrk** [comment]
I don't think there's anything for us to do here. Tokenization happens in the kernel, it's no longer the responsibility of the frontend. There are downsides to this (frontend config can't influence tokenization), but this doesn't really have anything to do with the adapter.

**Comment by Carreau** [comment]
Fair enough. Closing.
