### ISSUE TITLE
Confirm before overwriting notebook file when on-disk file has changed

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipython#6750]
Currently, it seems that when a save is requested by the notebook, it blindly overwrites the current version on disk, which can cause all sorts of pain if the notebook happens to be open by two different browser tabs or windows.

@minrk suggested that the notebook be aware of the last modified time of the file, and before saving, the notebook asks what the last modified time on the file is.  If the file has been modified since we knew about it, confirm with the user that we really do want to overwrite the file.  +1 to Min's suggestion.

**Comment by ellisonbg** [comment]
I think the real answer is to just build the real time collaboration stuff. That will complete address this issue and not complicate the content manager. We are seeing how the contents manager will interplay with the real time stuff and I think it is important to keep this type of state/lock out of the contents manager. It just doesn't belong there.

**Comment by minrk** [comment]
We don't need any state/lock for this. We can compare last_modified with the value from when the file was opened/last saved, and prompt to confirm if it's changed.
