### ISSUE TITLE
Move language info out of kernelspec?

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#6776]
I've noticed recently that kernelspecs at present are a combination of two very different kinds of information: how to start a given kernel, and how to treat code written in the language of that kernelspec. So far this isn't a practical problem, but it is a bit of a code smell, and if we're going to rethink it, we really need to do it before release.

The three options I'm considering are:

1. Leave everything as is.
2. Leave the language info in the kernelspec, but move it into a sub dictionary, and store it separately in notebook metadata - kernelspec in nb metadata would just contain name and display name, and language_info would be a separate top level key.
3. Move language info to the kernel info request, so kernelspecs really just describe how to start a kernel: the frontend asks the kernel for all info about its language. Metadata storage would be as 2. This feels more correct, but it would also be more disruptive. This would mean that, when creating a new notebook, highlighting would briefly be wrong until the kernel came up. Existing notebooks would not suffer, because the language info would be in metadata.

Ping kernel authors @stevengj, @gibiansky, @blink1073, @dsblank, and @ellisonbg who has been thinking about delayed kernel start.

**Comment by ellisonbg** [comment]
@takluyver can this one be closed?
