### ISSUE TITLE
In notebook %%writefile writes spurious % at the end of file

### ISSUE THREAD

**Issue by xanderhsia** [ipython/ipython#6786]
When I use %%writefile in a notebook cell (version 2.3), the file it writes always ends with a % character that is not typed in the cell
Example:

```
%%file test.net
a
```

and go to the command line and do a cat, I get

```
> cat test.txt
a%
```

If I do the same thing from a terminal ipython session there is no % at the end of the file

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
