### ISSUE TITLE
Sporadic failure in JS tests

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#6790]
I see this periodically in the JS tests on Travis:

```
FAIL ws_closed_ok: kernel_busy.Kernel was triggered
# type: assertEquals
# subject: "kernel_idle.Kernel"
# expected: "kernel_busy.Kernel"
FAIL ws_closed_ok: kernel_idle.Kernel was triggered
# type: assertEquals
# subject: "kernel_busy.Kernel"
# expected: "kernel_idle.Kernel"
```

It looks like it's a simple race condition, where the messages aren't always being processed in the order it expects. Rerunning the tests usually makes it pass, but it fails often enough to be annoying.

**Comment by ellisonbg** [comment]
Have we been seeing race conditions in the JS tests recently? Is this still relevant?

**Comment by minrk** [comment]
It seems to come and go. I haven't seen it in a bit, though.

**Comment by krassowski** [comment]
Closing as it appears that this test is no longer in IPython repository. Please reopen if I misunderstood.
