### ISSUE TITLE
Cannot browse pdb/ipdb history in qtconsole

### ISSUE THREAD

**Issue by rabbitmcrabbit** [ipython/ipython#682]
If I turn %pdb on and generate an Exception, or if I execute pdb.set_trace(), so that I'm at a (pdb) or ipdb> shell, then I do not appear to have access to a history of recent commands -- i.e. I cannot retrieve previous commands from within pdb or from the python session prior to launching pdb. Likewise, after exiting the pdb session and returning to the main prompt, history only contains commands entered outside of pdb.

This is only the case within the qtconsole -- a terminal ipython session has a contiguous history across the main session and any pdb subsessions.

**Comment by chaoflow** [comment]
+1 for history within ipdb, ideally isolated from history within IPython. The things I do in IPython are not really related to those in ipdb.

**Comment by ned2** [comment]
@pwaller is right, this is a limitation of ipdb in general, and one that has been frustrating me ever since I started using ipdb.

**Comment by Carreau** [comment]
Hi, 

The qtconsole has been moved to https://github.com/jupyter/qtconsole, so it shoudl likely be moved therefor the qtconsole part. 

This will allow us to keep the number of IPython issues smaller and focussed on IPython. As currently there is an extremely high number of opened issues , it make it really hard to find if a problem is actually known, or going to be worked one. 

The issue of debugger is a more general issue on the Jupyter Project and we are aware of that. 
I'm not sure this issue in particular reflect nicely what the state is, and leaving it open will just incite people to +1, while there likely be no work directly on that. 

Feel free to reopen if need, for the time being I'm going to close this. But a fresh issue that lay out nicely all the moving pieces and requirement would be prefered. 

Thanks.

**Comment by mattphillipsphd** [comment]
+1 for history, it blows my mind that I have to retype a line in the debugger any time I want to re-run a command or a similar one.  My lowly cygwin terminal can handle this much...
