### ISSUE TITLE
Edit notebook metadata gets awkward with large metadata

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#6833]
For cite2c, I'm storing citation info in notebook metadata, which is the sort of thing we're encouraging extension authors to do. However, the 'edit notebook metadata' dialog quickly starts looking rather broken in this kind of case.

Easy: Fix the codemirror instance to behave sensibly with larger amounts of text (at present it just expands horizontally and vertically to fit the contents).

Harder: Integrate something like [jsoneditor](https://github.com/josdejong/jsoneditor/) for dealing with the JSON structure instead of JSON text.

**Comment by ellisonbg** [comment]
Yeah, we probably want to have the CM editor use a fixed size with scroll bars.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
