### ISSUE TITLE
Make notebooks accessible to people with disabilities

### ISSUE THREAD

**Issue by dr-leo** [ipython/ipython#6845]
Working with notebooks with screen-reading software such as 
- NVDA: http://www.nvda-project.org, or
- jaws: www.freedomsci.com

is an uphill battle: Buttons are unlabled, text areas are not spoken to name but a few areas where improvement is needed.

While I am not an expert on accessibility, I understand that much can be achieved by 
- labling elements such as buttons and check boxes, and
- making use of the accessibility-related features of frameworks such as Bootstrap, e.g. through the sr-only attribute.

For further details on accessibility standards see

http://www.w3.org/WAI/

**Comment by dr-leo** [comment]
Having looked at the following resources,

http://www.w3.org/WAI/eval/Overview.html
http://www.w3.org/WAI/ER/tools/
http://www.w3.org/WAI/users/involving.html
http://www.uiaccess.com/accessucd/ut_plan.html#recruiting

Three incremental steps appear useful to make notebooks more accessible:

1. Select and run some of the automatic evaluation tools on some representative notebooks
2. Address the most salient accessibility issues unearthed by these tools 
3. involve users with relevant disabilities, e.g., through college programs and ask them for comments. Given the growing significance of IPython in research context there might be a chance of having some institution conduct a field study

On 1.: The easiest starting-point would be some editible notebooks online as test candidates. There should be a webapp providing this. Any hint? - Or can someone set up a test environment offline?

Leo

**Comment by minrk** [comment]
That sounds great. I'm not sure what you mean by editable, but we can use https://try.jupyter.org or other hosted deployments for this kind of thing.

**Comment by rsmith31415** [comment]
A few easy changes:

![screenshot from 2015-04-23 23 14 58](https://cloud.githubusercontent.com/assets/599274/7312333/9c48af8c-ea0e-11e4-8a50-cfec5dcdfbbc.png)

1. The `select` elements need to have labels:

![screenshot from 2015-04-23 23 15 48](https://cloud.githubusercontent.com/assets/599274/7312362/c789cf6e-ea0e-11e4-8f26-77b10c158043.png)

2. The text in the menus needs to have better contrast:

![screenshot from 2015-04-23 23 17 11](https://cloud.githubusercontent.com/assets/599274/7312371/f5016614-ea0e-11e4-8db1-7f18a08a2be3.png)

3. When navigating using the tab key, when we reach a cell in the notebook, the focus goes to that cell immediately and is not possible to go to other cells.

4. Explicit use of tabindex. The default is working okay but I remember it is not possible to navigate through modals.

This stuff is really really important particularly if you're receiving funding from agencies that require accessibility in software. It wouldn't be a bad idea to talk to a lawyer about this.

**Comment by dr-leo** [comment]
Great!

Once committed, I am happy to test it and write up a short section for
the docs from an eyes-free perspective. - So far I have been using but
the text console.

Leo
Am 24.04.2015 um 06:32 schrieb rsmith31415:

**Comment by vamsijkrishna** [comment]
This is important to enable people with visual impairment work on the environment. I personally know couple of brilliant people with low vision facing issues with their work. Thank you for opening this up. Happy to contribute in any which way possible.

**Comment by dr-leo** [comment]
Hi,

I opened this issue. Unfortunately I lack the time and knowledge to
contribute code. In an earlier comment I tried to set out some
incremental steps with links to resources which might help others find a
good starting-point. Being visually impaired/blind myself I would be
happy to test and give feedback though.
 
Thanks and good luck!

Leo


Am 07.09.2016 um 17:45 schrieb Vamsi:

**Comment by takluyver** [comment]
Closing in favour of issues on jupyter/notebook . Meta issues:

- https://github.com/jupyter/notebook/issues/180
- https://github.com/jupyter/notebook/issues/1801

More specific issues:

- https://github.com/jupyter/notebook/issues/3217
- https://github.com/jupyter/notebook/issues/3218
- https://github.com/jupyter/notebook/issues/3218
- https://github.com/jupyter/notebook/issues/3226
- https://github.com/jupyter/notebook/issues/3400
