### ISSUE TITLE
cell outputs suppressed after importing certain libraries in virtualenv

### ISSUE THREAD

**Issue by JohnGriffiths** [ipython/ipython#6853]
I frequently am encountering the problem that cell outputs to console operation type commands like `ls` and `print` are suppressed after doing imports from [this library](https://github.com/the-virtual-brain/tvb-library) such as

    from tvb.simulator.lab import *

This seems to only happen when running inside a virtualenv (which is set up using [this script](https://github.com/the-virtual-brain/tvb-pack/blob/master/scripts/mkenv.sh)). Hyperlink navigation also seems to not work. 

Is this a common problem?

**Comment by ellisonbg** [comment]
I would bet $20 that this is something that the underlying library is going. Marking as no action and closing, but feel free to reopen if you can verify that this is an ipython issue.
