### ISSUE TITLE
Exceptions thrown in cell with multiline strings

### ISSUE THREAD

**Issue by akimd** [ipython/ipython#6864]
It seems that when an exception is raised from a cell with a multiline string, we get a code-red error.

Try:

```
raise Exception(r'''foo
''')
```

It will report:

```
ERROR: An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (1, 0))

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-15-8d28bd905cfc> in <module>()
      1 raise Exception(r'''foo
----> 2 ''')

Exception: foo
```

The first three lines are worrying for the casual user.

**Comment by akvadrako** [comment]
I'm still seeing this in a current version of iPython. The following cell in a python 3 notebook generates an error whenever an exception is thrown:

```py
print(arg="""
""")
```

gives me:

```
ERROR:root:An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (1, 0))
```

However adding a comment avoids the error. This works:

```py
print(arg="""
""")
# """
```

**Comment by craigcitro** [comment]
So I ran into this today and dug a little; the issue here is that the way `ultratb.py` is using the `tokenize` module doesn't play nicely with multiline `"""` strings. In particular, when using a multiline string as an argument, the error is reported at the *last* line, whereas it's the *first* line for (say) a `\`-continued `"` string.

I would be happy to send a PR to squelch the error in this particular case, unless there are objections.

**Comment by craigcitro** [comment]
Ah, and on thinking about this a little more, the reason that single-line strings work well has nothing to do with Python, and everything to do with this snippet:
https://github.com/ipython/ipython/blob/f35cf047006e1398816c697fee19c28de77d9f1d/IPython/core/inputtransformer.py#L173-L191
One side-effect of this line is that `\`-continued strings are assembled before execution, meaning that `ultratb` won't mistakenly start parsing from the **end** of such a string.

**Comment by takluyver** [comment]
Thanks @craigcitro for investigating. I think it's fine to silence the error in ultratb.
