### ISSUE TITLE
Inconsistent repr when error raised in it

### ISSUE THREAD

**Issue by dashesy** [ipython/ipython#6867]
With iPython QtConsole, if an error is raised inside `__repr__` only printing the object will actually raise, simply evaluating the object will force the error to a string. I see this after upgrading from IPython 1.0.0 to IPython 2.3.0, it was consistent in 1.0.0

```python
class boz(object):
    def __repr__(self):
        raise ValueError('test')

gg = boz()
```

```
In [0]: gg
Out[11]: <repr(<__main__.boz at 0x46f2e50>) failed: ValueError: test>

In[1]: print gg
ValueError                                Traceback (most recent call last)
----> 1 print gg
...
```

**Comment by ellisonbg** [comment]
@dashesy can you confirm this is resolved in master?

**Comment by dashesy** [comment]
I just tried with 3.0.0-dev and it is fixed there

**Comment by ellisonbg** [comment]
Thanks! Closing.

**Comment by damianavila** [comment]
you forgot to actually close it :wink:
