### ISSUE TITLE
Notebook freezes if attempting to execute cell subsequent %matplotlib magic before finished

### ISSUE THREAD

**Issue by mborysow** [ipython/ipython#6889]
First off, I love the work you guys have been doing with IPython, it is truly amazing and I use it every day.  With that out of that way, here is my first bug report:

This has been a minor annoyance for me for a while now.  At the top of all of my notebooks I tend to have either %matplotlib inline or %matplotlib qt.  If I spam shift-enter to execute multiple cells and I try to execute any cells after this IPython magic (fast enough that it hasn't finished working), then the notebook hangs.  Since it's common for me to restart the kernel and work my way back through it, I end up running into this a lot.  It also took me a long time to figure out exactly why my notebook would do this sometimes.

I've seen it occur on versions of IPython 2.0 through 2.2 at least, though I think it was present in earlier 1.x series.  I can only confirm that this happens on Linux, through an miniconda install.  Seen on Fedora 20 and RHEL 6.5.  Very repeatable.

What other information would be most helpful to you in diagnosing this?  I'm not at work at the moment so I'm sure I'm leaving out specifics of what I mean by 'hangs.'  I will update this further on Monday morning.

Best Regards,
Michael Borysow

**Comment by ellisonbg** [comment]
Closing as duplicate.
