### ISSUE TITLE
Standard method to install other kernels into system-wide directory

### ISSUE THREAD

**Issue by dsblank** [ipython/ipython#6907]
Currently, examples for installing kernels install into a user's kernel directory. For example, see @takluyver's bash_kernel installer:

https://github.com/takluyver/bash_kernel/blob/master/setup.py

However, it would be convenient if there were also a standardized option to install into one of the IPython's system folders. This request is to come up with a standard option for kernel's setup.py that would install into one of IPython's system-wide folders. Something like:

https://gist.github.com/dsblank/390f25bdb9e5585fa976

In this example, setup.py takes a `--system` flag and installs the kernel files into the first folder on the IPython kernel system search path.

Whatever it is, it should be able to work with `pip` and other standard install tools. (There isn't anything for IPython team to do here, except to facilitate the discussion among kernel developers.)

**Comment by ellisonbg** [comment]
@minrk and @takluyver what is the status of this one? Tagging for 3.0, but feel free to change it.

**Comment by minrk** [comment]
I think it's resolved (`ip kernelspec install` puts things in /usr/local/share/jupyter/kernels).

**Comment by ellisonbg** [comment]
OK closing...
