### ISSUE TITLE
Overriding X-Frame-Options improperly disables any X-Frame-Options

### ISSUE THREAD

**Issue by rgbkrk** [ipython/ipython#6918]
Noticed this when deploying a setup and testing on the wrong domain I configured it for.

Example output from the Chrome console:

```
Invalid 'X-Frame-Options' header encountered when loading 'https://example.org/user-dafskljf/notebooks/Untitled.ipynb': 'ALLOW FROM example.com' is not a recognized directive. The header will be ignored.
```

Noting that the embedding still worked, I tried this on another domain. Now all domains are allowed. By default, if the header is not overridden, iframe embedding is disallowed. With a `X-Frame-Options` setting  in `tornado_options` though, if the syntax is wrong it allows it on *all* domains.

Originally I, @rgbkrk, was the one to introduce this into IPython within the last few months. I'm a bit sad to see I didn't handle it right. Note that this is related to #6862, in that we should be using CSP instead of X-Frame-Options.

**Comment by ellisonbg** [comment]
@rgbkrk are there changes we need to make for 3.0? Can you pick a milestone for this?

**Comment by rgbkrk** [comment]
Now that we've switched over to using CSP instead of X-Frame, this is closed. IFrame embedded was handled with #7016.
