### ISSUE TITLE
consider adding links to contents models

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#6941]
**Not for 3.0**

We do a lot of URL constructing in javascript, and often introduce bugs because we compute the same or similar URLs in many different places.  The GitHub APIs avoid the need for consumers to compute URLs by including most common URLs for an entity in the model itself. We might consider following suit.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
