### ISSUE TITLE
Dashboard in notebook should be labeled "Dashboard"

### ISSUE THREAD

**Issue by dsblank** [ipython/ipython#6995]
When working with students, it is useful to be able to refer to what you call the "dashboard" (the view with Notebooks, Running, Terminals, and Clusters tabs). However, there is no indication that this is the dashboard. That makes it very confusing to attempt to refer to it.

Would it be possible to label this view somewhere as the "Dashboard"? Even in the `<title>` would be somewhat useful. An "IP[y] Notebook Dashboard" graphic would be nice.

**Comment by minrk** [comment]
@ellisonbg what do you think about this one? We have lots of available space in the header. I'm ambivalent about putting 'Dashboard' in there. I don't think it's especially common to have a title on equivalent pages.

**Comment by ellisonbg** [comment]
I don't think we should put "Dashboard" in the header. Fine changing the <title> in <head>

**Comment by minrk** [comment]
@ellisonbg incomplete comment?

**Comment by ellisonbg** [comment]
Oh weird, the last sentence was:

Fine changing the <title> in the <head>

**Comment by takluyver** [comment]
HTML tags need to be wrapped in backticks, otherwise it tries to parse them.

**Comment by ellisonbg** [comment]
Ahh thanks

On Thu, Jan 15, 2015 at 10:27 AM, Thomas Kluyver <notifications@github.com>
wrote:

> HTML tags need to be wrapped in backticks, otherwise it tries to parse
> them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/6995#issuecomment-70135082>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
Add dashboard to title in #7480.

**Comment by dsblank** [comment]
Thanks! That should help a bit in referring to this page.

**Comment by takluyver** [comment]
We decided not to do this in today's dev meeting.

We're not quite sure what to call this page in user-facing contexts. I might refer to it as the 'File list' - even though that's not strictly accurate, that's the most obvious feature of it, and most users will probably understand what that means.
