### ISSUE TITLE
Make terminals more discoverable

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7019]
I would propose not to completly disable the terminal tab if 'not terminals_availlable' as otherwise nobody 
will know it exist. 
Either make it gray unclickable, or fill the content of the tab with a message that to use terminal in notebook you need to install terminado blah blah blaha

**Comment by ellisonbg** [comment]
This is still an issue, but we are getting rid of the terminals tab so the issue won't be focused around the terminals tab. Instead, the relevant UI elements are:

* The Terminal option in the New drop down in the dashboard.
* The Terminal panel in the Running tab.

We definitely want to have a good UI treatment of these things when the terminal won't work (such as always on windows).

**Comment by ellisonbg** [comment]
I should mention that this one is important for the usability on Windows. Also, it is an opportunity for us to poke Microsoft about better native terminal support. Maybe a button that Windows users can click to send an email to pleasefixthis@microsoft.com.
