### ISSUE TITLE
Improve CodeMirror usage to improve LaTeX display in Notebook Cells

### ISSUE THREAD

**Issue by benrbray** [ipython/ipython#7052]
Please see the [relevant discussion in the CodeMirror repository](https://github.com/codemirror/CodeMirror/issues/2942).
### The Problem

This is a simple enhancement request.

In Markdown, underscores toggle italics, but in LaTeX they also serve to indicate subscripts. Unfortunately, while editing with CodeMirror, underscores used in LaTeX mode sometimes cause italics to be toggled in the edit view.

Steps to reproduce:
1) Start editing a markdown cell.
2) Type the following: $$a_{n+1} = 2a_{n} + b$$
3) The text will display as a_**_{n+1} = 2a_**_{n}+b` where the characters in bold here have been italicized in the editor.

Non-example:
1) The following renders correctly in a Markdown cell: $$a_n = 2a_n+b$$
### The Solution

Wherever `CodeMirror` is used in the code for a Markdown cell in an IPython Notebook, it should be initialized using the [multiplexer mode](http://codemirror.net/doc/manual.html#addon_multiplex) in order to switch between rendering Markdown and rendering LaTeX between $ and $$ symbols.  See the link above for relevant discussion and an example.  

I would add this myself, but I am unfamiliar with the repository and it seems like a relatively quick fix.  If no one is willing, I would appreciate being pointed to the correct location in the repository to make the change.

Thanks!

**Comment by drocco007** [comment]
@takluyver confirmed this still occurs with a fresh checkout.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
