### ISSUE TITLE
Dead kernels in docker IPython notebook server

### ISSUE THREAD

**Issue by iiSeymour** [ipython/ipython#7062]
Running the notebook server inside a Docker container results in all notebooks producing the following pop ups:

> Kernel Restarting
> 
> The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened.

Followed by:

> Dead Kernel
> 
> The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened.

The host OS is Ubuntu 12.04.5 LTS and the Docker version 1.0.1. The installed _(container)_ IPython version is 2.3.1. My Dockerfile ends with:

```
EXPOSE 8888
CMD ["ipython", "notebook", "--config", "/config.py"]
```

The only change I have made to the config file is `c.NotebookApp.ip = u'*'` and  container is run with:

```
docker run -d -p 8001:8888 -v "${PWD}"/ipython_notebook_config.py:/config.py notebook
```

Any ideas what could be causing this or how to diagnose it?

**Comment by teramind** [comment]
I have the same problem.

**Comment by ericchiang** [comment]
Are there any updates on what's causing this?

I'm trying to get a Jupyter notebook working in an Ubuntu 14.04 container (host machine is also Ubuntu 14.04) and I'm getting this error every time.

Neither shell form or psuedo-exec are working for me when using the remote API. Every combination of installing/running as root/non-root it still producing the error.

**Comment by sphinxligustri** [comment]
I'm running ubuntu 14.04 x64 and had a similar issue trying to run the Jupyter Notebook docker image from [Docker Jumpstart by Andrew Odewahn](http://odewahn.github.io/docker-jumpstart/ipython-notebook.html). 

Thanks to **soerendip42**, for pointing me in the right direction:
> It does not crash when starting docker with an interactive shell and start the notebook from there!

The Docker image doesn't start the notebook correctly when I run the following command (again from [Docker Jumpstart by Andrew Odewahn](http://odewahn.github.io/docker-jumpstart/ipython-notebook.html))
```
docker run -it           \
   -p 8888:8888          \
   -v $(pwd):/usr/data   \
   -w /usr/data          \
   ipython/scipystack    \
   ipython notebook --ip=0.0.0.0 --no-browser
```

Actiing on **soerendip42**'s comment, I altered it slightly to specify the use of ```sh -c``` (now it works om my computer (tm)):
```
docker run -it           \
   -p 8888:8888          \
   -v $(pwd):/usr/data   \
   -w /usr/data          \
   ipython/scipystack    \
   sh -c "ipython notebook --ip=0.0.0.0 --no-browser"
```

At some time, before the rewrite, I got the following message in the browser. Unfortunately, I don't recall the specific circumstances.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/base/handlers.py", line 365, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/services/sessions/handlers.py", line 50, in post
    model = sm.get_session(path=path)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/services/sessions/sessionmanager.py", line 139, in get_session
    return self.row_to_model(row)
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/services/sessions/sessionmanager.py", line 178, in row_to_model
    raise KeyError
KeyError
```

**Comment by rsdenijs** [comment]
Same problem on Debian Wheezy

Workaround: 

sudo docker run -p 8888:8888  -i -t ipython/ipython /bin/bash

And inside the container:
ipython notebook --no-browser --ip=0.0.0.0

**Comment by pikeas** [comment]
Exact same problem and solution as @sphinxligustri:

`docker run -p 8888:8888 --rm <ipython image> sh -c "ipython notebook --ip=*"` -> no crash
`docker run -p 8888:8888 --rm <ipython image> ipython notebook --ip=*` -> crash

Adding `--debug` doesn't provide any additional insight.

This issue is tagged `needs-info` - what additional information can we provide to help resolve this?

**Comment by jakirkham** [comment]
Same problem. Tried all the solutions here including @sphinxligustri; however, none worked except the wrapper script idea. Used a script like this:

    #!/bin/bash

    ipython notebook --no-browser --ip=*

**Comment by davecahill** [comment]
+1 @jakirkham - your approach is the only one which worked for me.

**Comment by jcalazan** [comment]
+1 Running into this issue as well on Ubuntu 14.4.

Doing `docker-compose run --service-ports service_name bash` then running the service in the shell works fine as others have noted.

**Comment by logston** [comment]
+1 @pikeas 

```
sudo docker run -d -P <image> sh -c "jupyter notebook --notebook-dir=<my notebook dir>"
```

worked for me

**Comment by penolove** [comment]
+1 @jakirkham 
- your approach is the only one which worked for me,too.

**Comment by mrocklin** [comment]
I'm getting something similar to this issue without using docker, even with using the solution provided above.  I get the dialog as above, plus the following log printout.

```
[W 15:32:32.555 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 15:32:32.555 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 15:32:32.556 NotebookApp] The port 8888 is already in use, trying another random port.
[I 15:32:32.562 NotebookApp] Serving notebooks from local directory: /home/mrocklin/workspace/dask-examples
[I 15:32:32.562 NotebookApp] 0 active kernels 
[I 15:32:32.562 NotebookApp] The IPython Notebook is running at: http://[all ip addresses on your system]:8889/
[I 15:32:32.562 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 15:32:54.601 NotebookApp] 302 GET / (127.0.0.1) 0.75ms
[I 15:32:57.759 NotebookApp] Creating new notebook in 
[I 15:32:58.822 NotebookApp] Kernel started: 7cba51a1-0e41-47d7-b6a0-9568ef3a9da4
[I 15:33:01.818 NotebookApp] KernelRestarter: restarting kernel (1/5)
[W 15:33:08.867 NotebookApp] Timeout waiting for kernel_info reply from 7cba51a1-0e41-47d7-b6a0-9568ef3a9da4
[I 15:33:10.826 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 7cba51a1-0e41-47d7-b6a0-9568ef3a9da4 restarted
[I 15:33:13.835 NotebookApp] KernelRestarter: restarting kernel (2/5)
```

**Comment by solomatov** [comment]
I have the same problem.

**Comment by thewtex** [comment]
@mrocklin @solomatov Two notebooks will not be able to use the same port:

```
[I 15:32:32.556 NotebookApp] The port 8888 is already in use, trying another random port.
```

**Comment by mrocklin** [comment]
Previously I received this error after freshly booting up my system.  This issue actually triggered me to completely reinstall Anaconda, which did resolve the problem.

**Comment by hupili** [comment]
Same here starting iPython notebook via docker-compose. Solved by this comment: https://github.com/ipython/ipython/issues/7062#issuecomment-102451972

In short, in my `docker-compose.yml`, I changed from `command: ipython notebook --ip 0.0.0.0` to `command: sh -c 'ipython notebook --ip 0.0.0.0'`

**Comment by ezeakeal-ps** [comment]
Hi all, I hope this is useful to someone

I had a similar issue with Jupyter not connecting to the kernel.
Running via Django extensions: `/python manage.py shell_plus --notebook`
I saw "python kernels fail to start" and I tried almost everything listed.
We are running the notebook inside of Docker

In the end, I ran the same command via supervisord, and for some reason it worked.
```[program:jupyter]
command=/opt/conda/bin/python manage.py shell_plus --notebook --settings=settings.jupyter
directory=/opt/jupyter
stopasgroup=true
autostart=true
startsecs=1
startretries=1
logfile_backups=0
stdout_logfile=/data/logs/jupyter.out
stderr_logfile=/data/logs/jupyter.err
```

The settings file had no bearing on the output here..

**Comment by ahxxm** [comment]
[a wrapper](https://github.com/ahxxm/base/commit/54ddf5bfb43a68d4e14b04cacd1ed4280c65018a) works for me.. no idea about rationale though

**Comment by jakirkham** [comment]
This is probably some child reaping issue. While using `bash` or `supervisord` kind of work, neither are intended for this use case. The best thing I have seen thus far is [tini]( https://github.com/krallin/tini/ ), which just works nicely at solving this problem.

**Comment by ahxxm** [comment]
tini seems to be used by official ipython notebook images, but those Dockerfile result in huge images with more than 20 layers...

**Comment by cavaunpeu** [comment]
Simply add `sh -c` in front of my Jupyter notebook launch command worked for me. E.g.

`docker run -w /tmp/notebooks -v $(pwd)/notebooks:/tmp/notebooks --rm -p 127.0.0.1:8888:8888 $DOCKER_IMAGE sh -c 'jupyter notebook --ip=0.0.0.0 --no-browser --notebook-dir=/tmp/notebooks'`

**Comment by norela** [comment]
Same problem here. However, adding working with sh -c didn't work for me.
`docker run --rm -ti -v ~/Dockervolume:/hostdir container sh -c 'jupyter notebook --config=/tmp/config.py'`
Still results in kernels not starting. Though they are when starting them interactively.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
