### ISSUE TITLE
%run magic on ipynb continues after a cell has an exception

### ISSUE THREAD

**Issue by drevicko** [ipython/ipython#7100]
When you run an .ipynb file with the %run magic, and a cell generates an exception, the remaining cells continue to run. This can have unexpected outcomes as subsequent cells typically rely on results from the cell that generated the exception. It is also inconsistent with the behaviour of 'run all' when viewing a notebook and with the behaviour when running a .py file (probably .ipy also..).

It would be good at least to have the option to halt when an exception is thrown, but ihmo it'd probably be best to simply stop execution of the remaining cells if an exception is thrown.

I'm working on ipython 2.0.0 (the tag in the repo with that name) as I need the --script functionality (which at last check had been disabled in the head version), so apologies if this is resolved in the head version.

For the record, this is related to #4452

**Comment by ellisonbg** [comment]
I think the right solution is to run all cells at the same time, not one by one.

**Comment by drevicko** [comment]
Would reporting the line number of an exception be tricky in that case? If they were all run together, would the reported line number refer to the concatenation of the contents of all cells? 
The ideal would be to report something to indicate which cell, and the line number within the cell.

**Comment by minrk** [comment]
run_cell reports success or failure, so it's easy enough to halt on exception, we just weren't doing it. #7471
