### ISSUE TITLE
ipcluster on windows doesn't work with MPI launcher

### ISSUE THREAD

**Issue by krcools** [ipython/ipython#7110]
In ipython 2.0:

```
ipcluster start -n 4 --engines=MPIEngineSetLauncher
```

fails to launch a cluster. Using the `--debug` flag revealed that the issue is an ill formed command line for launching the engines. The command line includes the `--cluster-id` flag, but no argument to it (by default). As a workaround I use the cluster name `cluster`. It would be good however, if also void cluster-id's were valid.

The issue is not present when local clusters are launched.

**Comment by ellisonbg** [comment]
Can you give the details of your MPI installation?

**Comment by krcools** [comment]
Hi,

I am using the 64 bit version of MSMPI. Seems to work fine outside of
ipython.

best regards
kristof

On Sun, Jan 11, 2015 at 11:23 PM, Brian E. Granger <notifications@github.com

**Comment by myhlivecom** [comment]
I met the same problem as krcools.
A workaround by me is:
- Give a string to cluster_id, e.g., c.BaseParallelApplication.cluster_id = 'cid' in ipengine_config.py.
- Start Client with cluster_id, e.g., c = Client(profile='mpi', cluster_id='cid').

My environment is:
- Windows 10 64-bit
- Microsoft MPI v7 (Version 7.0.12437.6)
- Anaconda 3 4.0.0 64-bit
- ipython 5.0.0
- ipyparallel 5.1.0
- mpi4py 2.0.0

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
