### ISSUE TITLE
Nbconvert: Latex to PDF conversion fails on notebooks with unicode

### ISSUE THREAD

**Issue by re4lfl0w** [ipython/ipython#7150]
- I found [similary issue](https://github.com/ipython/ipython/issues/4539/). but this article ipython 2.0 solved problem.
- But I have a problem.
- How do I config option?
- ipython: 2.3.0
- python: 2.7.6

> $ ipython nbconvert Web_Hacking1.ipynb  --to latex --post pdf --debug

[NbConvertApp] Config changed:
[NbConvertApp] {'NbConvertApp': {'export_format': u'latex', 'log_level': 10, 'postprocessor_class': u'pdf'}}
[NbConvertApp] IPYTHONDIR set to: /Users/re4lfl0w/.ipython
[NbConvertApp] Using existing profile dir: u'/Users/re4lfl0w/.ipython/profile_default'
[NbConvertApp] Searching path [u'/Users/re4lfl0w/Documents/ipython/qna/web_hacking', u'/Users/re4lfl0w/.ipython/profile_default'] for config files
[NbConvertApp] Attempting to load config file: ipython_config.py
[NbConvertApp] Loaded config file: /Users/re4lfl0w/.ipython/profile_default/ipython_config.py
[NbConvertApp] Attempting to load config file: ipython_nbconvert_config.py
[NbConvertApp] Loaded config file: /Users/re4lfl0w/.ipython/profile_default/ipython_nbconvert_config.py
[NbConvertApp] Converting notebook Web_Hacking1.ipynb to latex
[NbConvertApp] Support files will be in Web_Hacking1_files/
[NbConvertApp] Applying preprocessor: coalesce_streams
[NbConvertApp] Applying preprocessor: SVG2PDFPreprocessor
[NbConvertApp] Applying preprocessor: ExtractOutputPreprocessor
[NbConvertApp] Applying preprocessor: LatexPreprocessor
[NbConvertApp] Applying preprocessor: HighlightMagicsPreprocessor
[NbConvertApp] Attempting to load template article.tplx
[NbConvertApp] Loaded template article.tplx
[NbConvertApp] Writing 22027 bytes to Web_Hacking1.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running pdflatex 3 times: [u'pdflatex', u'Web_Hacking1.tex']
[NbConvertApp] CRITICAL | pdflatex failed: [u'pdflatex', u'Web_Hacking1.tex']
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./Web_Hacking1.tex
LaTeX2e <2014/05/01>
Babel <3.9k> and hyphenation patterns for 78 languages loaded.
(/usr/local/texlive/2014/texmf-dist/tex/latex/base/article.cls
Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
(/usr/local/texlive/2014/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2014/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/latexconfig/graphics.cfg)
(/usr/local/texlive/2014/texmf-dist/tex/latex/pdftex-def/pdftex.def
(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))
(/usr/local/texlive/2014/texmf-dist/tex/latex/adjustbox/adjustbox.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/local/texlive/2014/texmf-dist/tex/generic/xkeyval/xkeyval.tex))
(/usr/local/texlive/2014/texmf-dist/tex/latex/adjustbox/adjcalc.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/adjustbox/trimclip.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/collectbox/collectbox.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/adjustbox/tc-pdftex.def))
(/usr/local/texlive/2014/texmf-dist/tex/latex/ifoddpage/ifoddpage.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/varwidth/varwidth.sty))
(/usr/local/texlive/2014/texmf-dist/tex/latex/graphics/color.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/latexconfig/color.cfg))
(/usr/local/texlive/2014/texmf-dist/tex/latex/tools/enumerate.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/local/texlive/2014/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
(/usr/local/texlive/2014/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/local/texlive/2014/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/local/texlive/2014/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/local/texlive/2014/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(/usr/local/texlive/2014/texmf-dist/tex/latex/ucs/ucs.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/ucs/data/uni-global.def))
(/usr/local/texlive/2014/texmf-dist/tex/latex/base/inputenc.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/ucs/utf8x.def))
(/usr/local/texlive/2014/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix
<2008/02/07> (tvz))
(/usr/local/texlive/2014/texmf-dist/tex/latex/oberdiek/grffile.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty))
(/usr/local/texlive/2014/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
(/usr/local/texlive/2014/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/local/texlive/2014/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(/usr/local/texlive/2014/texmf-dist/tex/latex/url/url.sty))

Package hyperref Message: Driver (autodetected): hpdftex.

(/usr/local/texlive/2014/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/local/texlive/2014/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/usr/local/texlive/2014/texmf-dist/tex/latex/tools/longtable.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/booktabs/booktabs.sty)
No file Web_Hacking1.aux.
(/usr/local/texlive/2014/texmf-dist/tex/context/base/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/local/texlive/2014/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/usr/local/texlive/2014/texmf-dist/tex/latex/oberdiek/grfext.sty)
(/usr/local/texlive/2014/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex

Package geometry Warning: The marginal notes overrun the paper.
     Add 3.73001pt and more to the right margin.

*geometry* verbose mode - [ preamble ] result:
* driver: pdftex
* paper: <default>
* layout: <same size as paper>
* layoutoffset:(h,v)=(0.0pt,0.0pt)
* modes:
* h-part:(L,W,R)=(72.26999pt, 469.75502pt, 72.26999pt)
* v-part:(T,H,B)=(72.26999pt, 650.43001pt, 72.26999pt)
* \paperwidth=614.295pt
* \paperheight=794.96999pt
* \textwidth=469.75502pt
* \textheight=650.43001pt
* \oddsidemargin=0.0pt
* \evensidemargin=0.0pt
* \topmargin=-37.0pt
* \headheight=12.0pt
* \headsep=25.0pt
* \topskip=10.0pt
* \footskip=30.0pt
* \marginparwidth=65.0pt
* \marginparsep=11.0pt
* \columnsep=10.0pt
* \skip\footins=9.0pt plus 4.0pt minus 2.0pt
* \hoffset=0.0pt
* \voffset=0.0pt
* \mag=1000
* \@twocolumnfalse
* \@twosidefalse
* \@mparswitchfalse
* \@reversemarginfalse
* (1in=72.27pt=25.4mm, 1cm=28.453pt)

(/usr/local/texlive/2014/texmf-dist/tex/latex/ucs/ucsencs.def)
(/usr/local/texlive/2014/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
(/usr/local/texlive/2014/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/usr/local/texlive/2014/texmf-dist/tex/latex/amsfonts/umsb.fd)

LaTeX Warning: No \author given.

(/usr/local/texlive/2014/texmf-dist/tex/latex/ucs/data/uni-198.def)
(/usr/local/texlive/2014/texmf-dist/tex/latex/ucs/data/uninames.dat)
(/usr/local/texlive/2014/texmf-dist/tex/latex/ucs/data/uni-198.def)

! Package ucs Error: Unknown Unicode character 50937 = U+C6F9,
(ucs)                possibly declared in uni-198.def.
(ucs)                Type H to see if it is available with options.

See the ucs package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.227 정리}
             \label{uxc6f9-uxd574uxd0b9-uxac15uxc758-uxc815uxb9ac}
?
! Emergency stop.
 ...

l.227 정리}
             \label{uxc6f9-uxd574uxd0b9-uxac15uxc758-uxc815uxb9ac}
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on Web_Hacking1.log.

[NbConvertApp] Removing temporary LaTeX files

**Comment by xmduhan** [comment]
I have the same problem.

**Comment by xmduhan** [comment]
I think I find the answer.

Ipython default user "pdflatex" cmd. But pdflatex is not support unicode,and there is a "xelatex" cmd can be used instead.You can install it with 'sudo apt-get install texlive-xetex' on ubuntu system.

When it finished,vi ~/.ipython/profile_nbserver/ipython_nbconvert_config.py,set c.PDFPostProcessor.latex_command =  [u'xelatex', u'{filename}']. 

Then use cmd:' 
ipython nbconvert Web_Hacking1.ipynb --to latex --post PDF  --config  ~/.ipython/profile_nbserver/ipython_nbconvert_config.py '. 

I hope it work for you! :-)

**Comment by re4lfl0w** [comment]
Thank you @xmduhan .
I fixed the problem.
But I have a new problem

![image](https://cloud.githubusercontent.com/assets/6144782/5704329/c249f7a4-9ab3-11e4-8dde-b66a3cf73450.png)

Do you see that?
latex layout is very ugly.
How do I make same layout as HTML version?

**Comment by xmduhan** [comment]
I am not sure about it, right now. 
Maybe you need to learn defining a converting template.
Or Maybe you can try to convert notebook file to a html file first, then use a others tools to convert html file to a pdf.
