### ISSUE TITLE
Always add reveal prefix when using nbconvert --to slides

### ISSUE THREAD

**Issue by twiecki** [ipython/ipython#7197]
When trying to upload my slides I always get tripped up that they don't show up correctly. The solution, as pointed out by @damian_avila is to add: `--reveal-prefix "http://cdn.jsdelivr.net/reveal.js/2.5.0"`. I wonder if this option should not be executed by default when running nbconvert to output slides.

**Comment by spookylukey** [comment]
Perhaps relevant to this, and also warrants it's own issue: reveal.js-3.0.0 is now the latest release, and it doesn't work at all with IPython Notebook slides. You get:

    ReferenceError: Reveal is not defined

**Comment by damianavila** [comment]
>Perhaps relevant to this, and also warrants it's own issue: reveal.js-3.0.0 is now the latest release, and it doesn't work at all with IPython Notebook slides. 

Plaining to update to reveal.js 3.0.0 soon... thanks for the report, I will take ASAP.

**Comment by knedlsepp** [comment]
I'm bascially having the same issue. @damianavila: What do you suggest doing when I want to display the exported slides on an offline computer without an ipython installation?

**Comment by knedlsepp** [comment]
Oh, nevermind. With the help of the above comments, I just figured: Downloading a pre 3.0.0 reveal.js to the same folder and exporting the notebook with --reveal-prefix does the trick.

**Comment by charlesdguthrie** [comment]
I need to print lecture notes with the slides, which is something introduced in Reveal v3.2.0.  Is there anything I can do to make it compatible with ipython, even if it means manually modifying the html?

**Comment by takluyver** [comment]
nbconvert master now uses Reveal 3.1, so I'd expect it to work with 3.2 as well.

**Comment by charlesdguthrie** [comment]
It turns out my nbconvert version was out of date

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
