### ISSUE TITLE
Offline fallback display mode for IFrames

### ISSUE THREAD

**Issue by chriddyp** [ipython/ipython#7220]
Hi all! Chris here, from [Plotly](https://plot.ly/)

In IPython notebooks, we display Plotly graphs as iFrames. Here is an example:

```HTML
<iframe src="https://plot.ly/~chris/1638.embed"></iframe>
```

I'd love to be able to load a cached image of the Plotly graph and then replace the image with the iFrame once it loads or keep the image if was a connection error in loading the iFrame.

If JavaScript was enabled, I would do something like this:

```HTML
%%HTML
<img id="static-image" src="data:image/png;base64,iVBORw0KGgoAAAAN......ElFTkSuQmCC">

<iframe id="plotly-graph" scrolling="no" 
    style="border:none; display:none;"seamless="seamless" 
    src="https://plot.ly/~chris/1638.embed" 
    height="525" width="100%">
</iframe>

<script type="text/javascript">
$(document).ready(function () {
    $('#plotly-graph').on('load', (function () {
        $('#static-image').hide();
        $('#plotly-graph').show();
    }));
});
</script>
```

Thoughts:
- This JS doesn't need to interact with anything outside of its output cell. I thought about dynamically injecting the `IFrame`, `<img>`, and the `<script>` into another `IFrame` with `doc.write()`:

```HTML
%%HTML
<iframe id="PlotContainer" src="about:blank"></iframe>

<!-- JS that inserts content into an IFrame - needs to be executed only once, on IFrame creation -->
<script type="text/javascript">
var doc = document.getElementById('FileFrame').contentWindow.document;
doc.open();
doc.write('<html><head><title></title></head><body>');

doc.write('<img id="static-image" src="data:image/png;base64,iVBORw0KGgoAAAAN...>')
doc.write('<iframe id="plotly-graph" style="display:none; src="https://plot.ly/~chris/1638.embed"></iframe>')

<!-- Arbitrary JS, but executed in a safe IFrame -->
doc.write('<script type="text/javascript">');
doc.write('$(document).ready(function () {');
doc.write("    $('#plotly-graph').on('load', (function () {");
doc.write("        $('#static-image').hide();");
doc.write("        $('#plotly-graph').show();");
doc.write("    }));");
doc.write("});");
</script>
```

 but found that injecting `<script>`s into IFrames was also not allowed. Should this be allowed? Are  `<script>`s that run inside `<iframe>`s that load from `src` safer than `<script>`s injected into `IFrames`?

- Another solution might be exposing an API to this (optional) behaviour through the `IPython.display.IFrame` class?

Any other ideas? Big thanks!

**Comment by ellisonbg** [comment]
Just add a `_repr_png_` to the object and the png will be saved in the notebook and can be used in offline contexts.

**Comment by ellisonbg** [comment]
Ohh, looks like you are already doing that.

**Comment by ellisonbg** [comment]
I don't think we are going to make any changes to dynamically switch output types based on various dynamic state. adding @fperez to this.
