### ISSUE TITLE
Terminal shutdown button doesn't work in dashboard

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#7230]
If I open a terminal and then try to shut it down by clicking the red Shutdown button in the dashboard, nothing happens.

**Comment by minrk** [comment]
From here, it shuts down and disappears from the list immediately, and without errors. This is terminado 0.3.1, Python 3.4, OS X 10.10.

**Comment by ellisonbg** [comment]
Retested with master, cleared cache. Terminado is up to date. Only
different is that I am running Python 2.7. Still fails.

@jdfreder observes the same problem...

On Wed, Jan 14, 2015 at 1:52 PM, Min RK <notifications@github.com> wrote:

> From here, it shuts down and disappears from the list immediately, and
> without errors. This is terminado 0.3.1, Python 3.4, OS X 10.10.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/7230#issuecomment-69999315>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
Maybe it's Python 2, I haven't run the server in Python 2 for quite a while.

**Comment by ellisonbg** [comment]
Yeah! Probably good for some of us to keep doing that.

On Thu, Jan 15, 2015 at 2:41 PM, Min RK <notifications@github.com> wrote:

> Maybe it's Python 2, I haven't run the server in Python 2 for quite a
> while.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/7230#issuecomment-70176485>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
> Yeah! Probably good for some of us to keep doing that. 

Until we drop support for running the server under Python 2. We're doing that for 4.0, right :)

**Comment by ellisonbg** [comment]
I tend to be an advocate for breaking things, so it sounds good to me :)

On Thu, Jan 15, 2015 at 2:45 PM, Min RK <notifications@github.com> wrote:

> Yeah! Probably good for some of us to keep doing that.
>
> Until we drop support for running the server under Python 2. We're doing
> that for 4.0, right :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/7230#issuecomment-70177170>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by rgbkrk** [comment]
Works on my cloud.

**Comment by ellisonbg** [comment]
"yeah too bad for you that your Datsun is slow and doesn't run well, my
Ferrari works fine" ;-)

On Thu, Jan 15, 2015 at 7:03 PM, Kyle Kelley <notifications@github.com>
wrote:

> Works on my cloud.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/7230#issuecomment-70201888>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by rgbkrk** [comment]
Figured I should try a new take on "works on my machine". :wink: tmpnb.org also runs on Python 3, hence the difference (I tried it out when I saw this issue).

**Comment by ellisonbg** [comment]
I was just kidding you ;-) Some people don't observe the issue on Python 2
as well.

On Fri, Jan 16, 2015 at 12:05 PM, Kyle Kelley <notifications@github.com>
wrote:

> Figured I should try a new take on "works on my machine". [image: :wink:]
> tmpnb.org also runs on Python 3, hence the difference (I tried it out
> when I saw this issue).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/7230#issuecomment-70313810>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
It appears unrelated to Python version, something about the OS or terminal setup is setting signal handlers for the subprocesses on some machines and not others. It appears to be happening entirely outside Python's purview.

**Comment by jdfreder** [comment]
> Yeah! Probably good for some of us to keep doing that.

I'm still running 2.0 on most machines I use...  IIRC one of the Python security/signing libraries I use doesn't support 3 & Windows yet.

**Comment by amcdawes** [comment]
#7491 appears to solve this for me. Running zsh was the source of the original issue as it ignores SIGTERM

**Comment by minrk** [comment]
closed by #7491
