### ISSUE TITLE
Dangerous visual hierarchy in dashboard

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#7233]
Right now the "Duplicate" and "Delete" buttons in the dashboard are "merged" into one uber-button that suggests (visual hierarchy) that suggests that they are logically related. However, given that duplication and deletion do the opposite type of things (create vs. destroy) I think it is dangerous to have them so close visually.

A second, but related issue is that the "Shutdown" button is red (indicating danger) but the "Delete" button is white (no danger), even though "Delete" is the most dangerous action of all. If anything the "Shutdown" button should be orange and the "Delete" button should be red.

Eventually we will get rid of the per item buttons, but for 3.0 I think we should at least make them two separate non-merged buttons in the UI to reflect that they don't go together.

I have already almost deleted notebook accidentally because of these issues.

**Comment by Carreau** [comment]
This is now done.
