### ISSUE TITLE
Reconsider the "Terminals" dashboard tab

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#7234]
With my proposal to simplify the "New" button in the dashboard in #7231 it becomes possible to further simplify the dashboard:

* Include "Terminal" in the "New" dropdown to allow a user to create a new *anything* from that single dropdown.
* Get rid of the "Terminals" tab entirely.
* List the running terminals in the "Running" tab.

This provides the same exact UI for all notebooks, text files and terminals.

**Comment by payne92** [comment]
Strong +1

I had the same thought as Brian when I was previewing 3.0:  "new" should let me make a new "anything".

**Comment by ellisonbg** [comment]
Resolved by #7271
