### ISSUE TITLE
Use left text-align in rendered html

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#7239]
It is difficult for the eye to track long lines of text. Usually the recommendation is to use shorter line lengths, but given the other design constraints of the notebook and modern (wide) monitors, that is not always possible. Right now the issue is compounded by the notebook's usage of fill justify (`text-align: justify`).

I proposed using `text-align: left` to give a mild ragged edge to large block of rendered markdown text to help guide the eye in the vertical direction.

**Comment by takluyver** [comment]
Done by #7445.
