### ISSUE TITLE
Enh: utils.traitslets: add getter and setter handlers to allow property-like behavior

### ISSUE THREAD

**Issue by dr-leo** [ipython/ipython#7269]
Enthought.traits support this feature. I find it useful and would like to see it in IPython's traitlets module for use in custom applications. Or is this feature already there?

I am afraid I lack the knowledge to send a PR for this. And unless otherse need it there is little chance of seeing property traits implemented any time soon. 

Leo

**Comment by ellisonbg** [comment]
We have definitely given up on full traitlets compatibility.

**Comment by dr-leo** [comment]
While this enhancement proposal never aimed at full compatibility with Enthought traits, there seems to be no support for this new feature. I therefore close this issue.

**Comment by stefanoborini** [comment]
I actually would need this feature as well.
