### ISSUE TITLE
code fails to produce a figure in inline mode (but works in Qt4Agg backend)

### ISSUE THREAD

**Issue by eyurtsev** [ipython/ipython#7276]
The following code fails to produce a figure if using inline mode, but works fine on the Qt4Agg backend.

The problem appears when setting the xscale to log.

```python
%pylab inline
from matplotlib.patches import Arrow, ConnectionPatch

# This figure does not show up (even if xlimits are specified)
figure()
ax = gca()
xy1 = (0, 0) # non-positive starting coordinate
xy2 = (1, 1)
con = ConnectionPatch(xyA=xy1, xyB=xy2, coordsA="data", coordsB="data",
                      axesA=ax, axesB=ax)

ax.add_artist(con)
xscale('log')
```

I get the following message:

/usr/local/lib/python2.7/dist-packages/IPython/core/formatters.py:239: FormatterWarning: Exception in image/png formatter: width and height must each be below 32768
  FormatterWarning,

Also see for reference: https://github.com/matplotlib/matplotlib/issues/3932

**Comment by minrk** [comment]
For figures where bbox_inches='tight' causes problems like this, You can disable it with

```python
c.InlineBackend.print_figure_kwargs = {}
```

in your ipython_config.py
