### ISSUE TITLE
interact with custom widget not triggered

### ISSUE THREAD

**Issue by updiversity** [ipython/ipython#7277]
Hi,

from the suggestion of @rossant , I tried to get an excel-like grid editor for pandas dataframe. 
http://nbviewer.ipython.org/github/ipython/ipython/blob/2.x/examples/Interactive%20Widgets/Widget%20Events.ipynb

As i am running on ipython 3.0.0, I had to do some changes, and at the end I decided to rewrite to python part (HandsonTableWidget & HandsonDataFrame) in order to use the "interact" function with my custom widget.

My widget function looks like this:

from __future__ import print_function
from IPython.html import widgets # Widget definitions
from IPython.html.widgets import interact, interactive, fixed, interact_manual
from IPython.display import display # Used to display widgets in the notebook
from IPython.utils.traitlets import Any,Unicode,List,Dict # Used to declare attributes of our widget

import StringIO
import pandas as pd

class DataFrameTableWidget(widgets.DOMWidget):

    _view_name = Unicode('HandsonTableView', sync=True)
    dataframe = Unicode(sync=True)
    settings = Dict(sync=True)
    description = Unicode(sync=True)
    
    def __init__(self, df, *pargs, **kwargs):
        widgets.DOMWidget.__init__(self, *pargs, **kwargs)
        self.value = df
        self.on_trait_change(self._on_data_changed, 'dataframe')
        self.on_displayed(self._on_df_displayed)

    def _on_df_displayed(self, e):
        # DataFrame ==> Widget (upon initialization only)
        json = self.value.to_json(orient='values')
        self.dataframe = json
        
    def _on_data_changed(self, e, val):
        # Widget ==> DataFrame (called every time the user
        # changes a value in the graphical widget)
        buf = StringIO.StringIO(val)
        self.value = pd.read_json(buf, orient='values')
        
    def show(self):
        display(self)

The function i want to run through "interact" is just this one:
def g(x):
    print(x)

The interact function is called in this way:
i=interact(g,x=DataFrameTableWidget(df))
where df is a simple panda dataframe (no sub-indexes)

I shows successfully the grid editor, but when I edit a value in a cell, then the variable x is not updated.

I raised the issue here because when I decided to use the function "interact_manual", then it works great. The x variable was correctly updated and the output of the print was changing.

Is it a bug ?

**Comment by ellisonbg** [comment]
No this isn't a bug. In order to work with interact, a custom widget must have a traited `value` attribute that has a simple scalar type. That is by design. What you probably want is to use the `fixed` function in the `widgets` module:

```
interact(myfunc, df=fixed(mydata), ...)
```

Fixed will pass the df to the function as a raw DataFrame each time and you can do what ever you want. 

But honestly, interact is probably not the right thing to use for complex composite data such as a `DataFrame`.
