### ISSUE TITLE
feature request: simple exceptions

### ISSUE THREAD

**Issue by ipython** [ipython/ipython#73]
Original Launchpad bug 367427: https://bugs.launchpad.net/ipython/+bug/367427
Reported by: culler (Marc Culler).

There are cases where python tracebacks are completely useless to users, such as when they refer to code in a cython file which the user does not have.  In these cases the traceback is just a distracting pile of useless text that fills up your terminal.  It would be nice to have the option of disabling the printing of tracebacks.

REQUEST: please add another xmode value: Simple which reports the exception type and its value, but suppresses the traceback.

- Marc Culler

**Comment by Carreau** [comment]
This issue is 1/2 a decade old, and there is few chance of anyone working on that. 
I'm going to close it to try to reduce the number of opened issue in the issue tracker. 

Please open a new issue is needed. 

Thanks !
