### ISSUE TITLE
handling of html comments is inconsistent

### ISSUE THREAD

**Issue by pmfeldman** [ipython/ipython#7304]
When a cell contains only an html comment, setting the cell format to "markdown" causes the cell contents to become invisible, as expected. If, however, the cell contains other html content in front of the comment, as in the example below, the comment remains visible:

```
<hr style="height:2px">
<!--
import numpy as np
-->
```

**Comment by minrk** [comment]
Doesn't appear to affect master. May have been fixed by upgrading marked.js.
