### ISSUE TITLE
Unicode char broken  in notebook ?

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7305]
Combining char are not over the previous char.
![capture d ecran 2014-12-24 a 10 37 58](https://cloud.githubusercontent.com/assets/335567/5547389/26e78d4e-8b59-11e4-93e5-76948147bc38.png)

**Comment by ellisonbg** [comment]
Combining chars have always worked fine on a Mac, but I know that Fernando said that absolutely look horrible on Linux.

**Comment by ellisonbg** [comment]
![screen shot 2015-01-11 at 2 41 31 pm](https://cloud.githubusercontent.com/assets/27600/5697219/f6880a8e-999f-11e4-90cb-c21a9595b7e4.png)

**Comment by ellisonbg** [comment]
I am going to close as this is not anything we can do something about.
