### ISSUE TITLE
Create a notebook for testing nbconvert

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#7309]
We need to put together a notebook that illustrates the main things that we expect nbconvert to handle. The most important target is the HTML output. Some of these things include:

* At least one example of all output types.
* A good sample of Markdown.
* Links to files located on the web.
* Relative/absolute links to files co-located with the notebook
* Relative/aboslute links to other notebooks co-located with the notebook.

**Comment by minrk** [comment]
Isn't this closed by #7385, even though it moved to another repo?

**Comment by rgbkrk** [comment]
Addressed in https://github.com/ipython/nbconvert-examples/pull/9.

**Comment by jdfreder** [comment]
@minrk I guess  ipython/nbconvert-examples#9 really addresses this.  This issue should be in that repo, not ipython's.  I'll close it here.
