### ISSUE TITLE
atomic write umask

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7317]
Reported on gitter.im/ipython/ipython by @bigzachattack 

Sadly no one was on the chat at that time, too busy with a big bearded men 
dressed in red trying to smuggle things in our houses through the cheminee. 

```
I noticed today working in master, that any new notebook I create or copy has permissions
0o600 and ignores my umask. In IPython.utils.io.atomic_writing() uses mkstemp() to create
a temporary file for the atomic write. According to the python docs, mkstemp creates
files as 0o600.

After the write succeeds to the tmp file, _copy_metadata is called to copy the metadata
from the original file to destination file. It will throw an exception if there is no
source file. Thus when the notebook is copied into the notebook dir, it has
permissions 0o600.

Is this desired behavior, temporary, or a bug? I work in an environment where are default
permissions are 0o660 to allow for users to easily share information, so defaulting new
notebooks to 0o600 seriously inhibits this ability.
```

**Comment by bigzachattack** [comment]
Here are couple of ideas to get the permissions right:

Idea 1

> handle, path = tempfile.mkstemp()
> umask = os.umask(777)
> os.umask(umask) <<< Not sure if you need to set the umask back
> mode = (0o777 & ~umask) <<< I think this is how you translate umask to mode
> os.chmod(path, mode)

Idea 2

* Use tempfile.mkdtemp() and create empty file instead of tempfile.mkstemp()
* Delete the directory and file on cleanup

**Comment by minrk** [comment]
I implemented Option 2. in #7469.
