### ISSUE TITLE
Add legend for symbol icons for control chars in keyboard shortcuts

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#7322]
When did the keyboard shortcuts for control chars become symbols? 

I am pretty strongly -1 on that as none of those symbols are on users keyboards and are far from universally recognized. Some of them I don't even know what they are, or have to think carefully about what they might be.

Also, using upper case letters is confusing as some users will think they need to use shift for those.

![screen shot 2014-12-26 at 4 45 49 pm](https://cloud.githubusercontent.com/assets/27600/5560010/ba81e2f4-8d1e-11e4-8e79-ebf607de7f00.png)

**Comment by ellisonbg** [comment]
We talked about this in a dev meeting:

* Use `esc` everywhere instead of the silly clock.
* Put a legend at the top.
* For other OS use a different legend of single letters.

**Comment by ellisonbg** [comment]
@Carreau ok this one is back to waiting for author :) let us know if you want someone else to pick it up.

**Comment by amcdawes** [comment]
I'm happy to take a shot at this, stop me if it's already done.

**Comment by Carreau** [comment]
> @Carreau ok this one is back to waiting for author :) let us know if you want someone else to pick it up.

Well, [Technically (xkcd link)](http://xkcd.com/1475/) author is you @ellisonbg :-P this is an issue you opeened, not a PR;

@amcdawes Please go ahead and submit even an unfinished PR if you like. I'm busy finishing up a few legal stuff in france, but might also take a shot at it if I make a break in administrative paper :-)

**Comment by amcdawes** [comment]
@ellisonbg can you explain more about what you mean by "For other OS use a different legend of single letters." On MacOS, PR #7521 adds a legend that pairs the symbols with names for mac keys, I'm not sure what would be comparable on another OS. Ctrl, Shift, Alt are usually how the keys are labelled, and how the shortcuts are listed in the quickhelp dialog.

**Comment by Carreau** [comment]
> For other OS use a different legend of single letters."

At some poiint we want shortcut in menu. Obviously, `Ctrl-Alt-Shift-M` is too long for menu, but if we asssume C==Ctrl, Alt ==M == Meta , Shift == S, we could write it `CMS-M` (shift could be keept as arrow), but C==Ctrl, and M==Meta (S sometime == Super == windows key on linux) are common.

**Comment by takluyver** [comment]
I've never seen shortcuts written like `CMS-M`. I do sometimes see `C-` for Ctrl, but even that is unusual (mainly used by diehard Emacs fans). Even in menus, it's normal to write out `Ctrl` and `Shift`. E.g. this is from Pycharm:

![screenshot from 2015-01-22 09 16 53](https://cloud.githubusercontent.com/assets/327925/5860667/c621cca6-a217-11e4-88f6-3e59c0b0795c.png)

**Comment by takluyver** [comment]
And you'd be surprised what you can fit into a menu - other Pycharm menu entries include `Ctrl+Alt+Shift+F8` and `Ctrl+Alt+Close Bracket`.

**Comment by minrk** [comment]
Most menus expand to fit their content. The shortcut just needs to go inside the `a` tag to avoid wrapping

**Comment by ellisonbg** [comment]
I do think it is a good idea to not let menus get very wide though.

On Thu, Jan 22, 2015 at 12:55 PM, Min RK <notifications@github.com> wrote:

> Most menus expand to fit their content. The shortcut just needs to go
> inside the a tag to avoid wrapping
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/7322#issuecomment-71096733>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
