### ISSUE TITLE
too many classes in Qt

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#7325]
We have too many classes and subclasses in the qtconsole code. Right now, we have:

RichIPythonWidget inherits from IPythonWidget inherits from FrontendWidget inherits from (HistoryConsoleWidget, BaseFrontendMixin) inherits from ConsoleWidget, and RichIPythonWidget is the only class we actually use. None of the intermediate classes serve any use.

I think a lot of this is abstraction for abstraction's sake, and we can get rid of most or all of these classes, leaving the one and only real final IPythonWidget as the implementation of all of these things, especially the BaseFrontendMixin, which is a Mixin only mixed into one class.  The ConsoleWidget makes a certain amount of sense, since it contains a lot of generic logic, but I think at least, BaseFrontendMixin, FrontendWidget, IPythonWidget, and RichIPythonWidget should probably be consolidated into a single class.

**Comment by Carreau** [comment]
Migrated to jupyter/qtconsole#89
