### ISSUE TITLE
Error loading notebook

### ISSUE THREAD

**Issue by juhasch** [ipython/ipython#7328]
Using Firefox I get an error with the following message when loading some notebooks:
`TypeError: ks is undefined`

The javascript log output is:
```
TypeError: ks is undefined
var new_mode_url = 'kernelspecs/'+ks.name+'/kernel';
``` 
in Lines 2093 and also 2100 of `notebook.js`.

This is with current master using Anaconda and Firefox (tested with Linux and Windows).
Example notebook: https://gist.github.com/juhasch/67e38a443ce220d7247c

**Comment by twiecki** [comment]
I have the same problem.

**Comment by twiecki** [comment]
This still occurs with most recent master for me (at least using the jupyterhub docker container). Can we reopen?

**Comment by minrk** [comment]
We can reopen as we investigate #7420, but I just want to be clear that this does not appear to affect:

- IPython master (2ce594fa834dc5897be753bede5ba5df45423b5b)
- Firefox 34.0.5
- OS X 10.10.1

**Comment by twiecki** [comment]
I'm on linux FWIW.

**Comment by minrk** [comment]
It's working here on Linux as well. Baffled, but we'll dig into it. Maybe it's a bug that only affects German IP addresses :)

**Comment by takluyver** [comment]
Can one of you post the error details that you're seeing with current master? The code has changed and the line causing the original error is no longer there.

**Comment by juhasch** [comment]
Happens using Firefox for Windows, Linux and Mac (tested just now). This is the notebook:
```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.4.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
```

**Comment by takluyver** [comment]
I don't see a failure on Firefox for Linux with that notebook. Can you post the error you're now seeing, because the original error was in code that no longer appears to exist.

**Comment by juhasch** [comment]
New install of  current IPython master + Anaconda + Python 3.4.1

![firebug](https://cloud.githubusercontent.com/assets/2445216/5709667/11cf206e-9a9c-11e4-8469-e7e9138ddb60.png)

![screenshot](https://cloud.githubusercontent.com/assets/2445216/5709669/15df60f6-9a9c-11e4-9839-d228c2641806.png)

**Comment by takluyver** [comment]
Ah, I think I understand it. I suspect that the error is occurring when the notebook is loaded before the JS finishes retrieving the list of kernelspecs. `Notebook.fromJSON` calls `KernelSelector.change_kernel`, but it doesn't know the kernelspec name yet.

**Comment by minrk** [comment]
#7432 should hopefully synchronize that race
