### ISSUE TITLE
pdflatex chokes on SymPy's unicode char 9472

### ISSUE THREAD

**Issue by haraldschilly** [ipython/ipython#7333]
SymPy uses the character 9472 for the fraction bar. pdflatex doesn't know what to do, and I had to fix the `base.tplx` file's `package` block with these definitions. Maybe there is a better way, but I at least it does work for me. To reproduce in the notebook:

``` python
from sympy.abc import x
sy.pprint((1+x) / (1-x))
```

and then 

```
ipython nbconvert --to latex ...
```

my fix in the `base.tplx`:
(two changes: one in the `ucs` line and the `DeclareUnicodeCharacter`)

```
\usepackage{ucs} % Extended unicode (utf-8) support
\usepackage[utf8x]{inputenc} % Allow utf-8 characters in the tex document
% this is needed for sympy's 2D ascii art fractions
\DeclareUnicodeCharacter{9472}{-}
```

My setup:

```
$ python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': '1c0eb68',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/opt/canopy/env/User/lib/python2.7/site-packages/IPython',
 'ipython_version': '2.3.1',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-43-generic-x86_64-with-debian-jessie-sid',
 'sys_executable': '/home/opt/canopy/env/User/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.6 | 64-bit | (default, Sep 15 2014, 17:36:10) \n[GCC 4.1.2 20080704 (Red Hat 4.1.2-54)]'}
```

and 

```
$ pdflatex --version
pdfTeX 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian)
```

**Comment by ellisonbg** [comment]
Why are you not using full latex support that sympy has? It would not use any such unicode chars and would work fine with the latex output of nbconvert.

But we should fix this bug.

**Comment by ellisonbg** [comment]
I am targeting this as 4.0, but if you (or anyone else) wanted to get it into 3.0, it could if completed soon.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
