### ISSUE TITLE
Super new to networking-ipython enviroment

### ISSUE THREAD

**Issue by thereisnocarmensandiego** [ipython/ipython#7335]
about that super, well...super ultra new...at least is optimistic...

back to the topic, I installed python 2.7 and I just went to a nanodegree class on udacity(free publicity) and I picked the nanodegree on 'Data Science'. That nanodegree teaches the fundamentals about Data Science, which I am interested, so I went and I found that I needed the NumPy and the Matplotlib to run the graphics and get some mathematical implementations done, but since I am new to all this, I can't make nor the NumPy nor the Matplotlib to work with the Python, so I installed the Anaconda, which gives me the programs mentioned, all neat and installed, so I thought, since I can't use the Ipython notebook, due to a kind of problem.

possible problems, since I been looking for answers or guidance, i think are that:

-I can't use the Ipython notebook because there is some-kind of firewall that stops the notebook, but I disabled the windows firewall and still nothing works.

-when I use the Ipython shell and try to use the Matplotlib, the shell answers with a fatal error:

C:\PATH\...
_ext.c:186:20: fatal error: sys/un.h: no such file or directory
compilation terminated.
-----------------------------
AttributeError
<ipython-input-20-exadecimalnumber>

Solution:

I think I dont have the Matplotlib correctly installed, but that's the other problem, I dont know where to installed, or how to installed, or if there is another problem...

so, I gonna continue searching, 

hope my engrish is ok, and my question is understood....

regards,

'thereisnocarmensandiego'

**Comment by ymost** [comment]
+1
Having the same issu

**Comment by takluyver** [comment]
Closing as this is old and it's not clear what was going wrong. Feel free to keep using comments for troubleshooting.
