### ISSUE TITLE
Kernelspec, hmac-scheme.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7337]
Trying to get Ihaskell to work I saw that the signature_scheme of session cannot be set by each kernel independently. I haskell use no signature (which I know is not good,  but that's not the point), but with the multi-user kernel that forces to deactivate the signature globally. 

Should we allow a per-kernel config, or say to kernel they just have to use hmac-sha256, 
if sha-256 has suddently a vulnerability and we change, that mean that all kernels have to adapt super fast, or get incompatible, or we deactivate signature. 

Thoughts ?

**Comment by ellisonbg** [comment]
Hmm, shouldn't we pick the scheme globally and refuse to talk to kernels that don't respect it. I think we want to push back on kernel authors that make different choices for no really good reason. Or is there a good reason the IHaskel kernel can't use the default (or any) scheme. Does this really need to be per-kernel configurable?

**Comment by minrk** [comment]
I don't think there should be any per-kernel *config* for this. But we may want to allow kernels to specify what schemes they do support. Even if we refuse to talk to them, we could do it more gracefully than failure to authenticate messages if we knew beforehand that the current scheme is not supported.

At this point, I don't think this needs to be addressed for 3.0.

**Comment by Carreau** [comment]
> Hmm, shouldn't we pick the scheme globally and refuse to talk to kernels that don't respect it. I think we want to push back on kernel authors that make different choices for no really good reason.

I'm mostly thinking of what if we change ? Let's say one of the ex Kyle's employers had a backdoor in sha256 we use and we switch to (for demonstration purpose) blowfish. This will immediately make all old kernels incompatible. 

I think in the long term a list of supported scheme make sens, even if we deprecate it.

I would definitively consider that a bug in a kernel if it does not use auth, but by installing IHaskell, 
I made all my kernel not-signing messages which is definitively bad. And I had no warning about that. 
Again not totally Jupyter-side fault, but as we only have a global configurable, kernels that are being installed have no choice but to modify user global config. 

I don't expect that was done by Andrew on purpose, but just that it was st to no sign at the beginning of project development and then "just forgotten".

A per-kernel hint that show a (unconfigurable) warning that kernel communication are unsecure make sens to me.

**Comment by ellisonbg** [comment]
Bumping to 4.0.

I like the idea of @minrk

**Comment by gibiansky** [comment]
@Carreau 

IHaskell will support HMAC-SHA256 in the near future, once it supports IPython 3.0. 

> I would definitively consider that a bug in a kernel if it does not use auth, but by installing IHaskell, 
I made all my kernel not-signing messages which is definitively bad. And I had no warning about that. 
Again not totally Jupyter-side fault, but as we only have a global configurable, kernels that are being installed have no choice but to modify user global config.

I don't think that is actually the case -- at least, it should not have been. IHaskell has always used it's own `profile_haskell` profile, which was used for Haskell and only haskell, so authentication for the other kernels should not have been affected.

Also, I am not sure -- should kernels implement anything besides `hmac-sha256`? (The documentation leaves open the possibility of other signing schemes, but it is slightly unclear whether kernels *may* support other schemes or *should* support other schemes, and if so, what schemes they should support.)

**Comment by minrk** [comment]
> should kernels implement anything besides hmac-sha256

According to the spec, they should officially expose the gamut of basic hmac+hash algorithms available from whatever crypto library you are using (commonly md5, sha256, sha512, etc.). In practice, I will be surprised if anything other than sha256 is actually used, so if that's all you feel like supporting, I would expect to be fine for the indefinite future. I would at least check the value in the connection file and throw an informative error.

If we do come up with a reason to move away from sha256, I think we will need to implement something like what's described here - a way for kernelspecs to describe what schemes their kernels support.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
