### ISSUE TITLE
All included example notebooks should work with python2.

### ISSUE THREAD

**Issue by fperez** [ipython/ipython#7350]
We should ensure all notebooks we ship work with python2.  We shouldn't make py3 a requirement yet (and shouldn't have a mix of py2 and py3 notebooks in the docs). We can make them py2/3 compatible with appropriate `__future__` imports, but shouldn't mandate py3 being installed.

I ran into the issue with `examples/Interactive Widgets/Using Interact.ipynb`, but there are others:

```
(master)amirbar[examples]> grep '"name": "python3"' */*ipynb
Interactive Widgets/Using Interact.ipynb:   "name": "python3"
Notebook/Notebook Basics.ipynb:   "name": "python3"
Notebook/Running Code.ipynb:   "name": "python3"
```

**Comment by damianavila** [comment]
>For instance, I have several Python kernels at this point, but any notebook I write with any of them should be loadable by someone with any Python kernel.

:+1:

**Comment by ellisonbg** [comment]
The only thing we can't do with `__future__` is annotations that are used in widgets.

**Comment by jakevdp** [comment]
Was trying to start on this, but got an error.

- I installed IPython from master in Python 2.7 and in Python 3.4, and started a notebook server in each
- I opened ``examples/Embedding/Index.ipynb`` from the Python 2.7 server, ran it, and saved the result.
- I opened the same notebook from the Python 3.4 server, and got the following:
```
Notebook failed to load

The error was:
TypeError: Cannot read property 'name' of undefined
See the error console for details.
```

Here's the console output:
```
Default extension for cell metadata editing loaded.
:8890/static/notebook/js/celltoolbarpresets/rawcell.js?v=20150113104537:82 Raw Cell Format toolbar preset loaded.
:8890/static/notebook/js/celltoolbarpresets/slideshow.js?v=20150113104537:43 Slideshow extension for metadata editing loaded.
:8890/static/notebook/js/kernelselector.js?v=20150113104537:142 spec python2 undefined
:8890/static/notebook/js/notebook.js?v=20150113104537:2102 Notebook failed to load from JSON: TypeError: Cannot read property 'name' of undefined
http://localhost:8890/api/sessions Failed to load resource: the server responded with a status of 501 (Not Implemented)
:8890/static/base/js/utils.js?v=20150113104537:594 Object
:8890/static/base/js/utils.js?v=20150113104537:596 API request failed (501): The 'python2' kernel is not available. Please pick another suitable kernel instead, or install that kernel.
:8890/static/services/sessions/session.js?v=20150113104537:52 Session: kernel_dead (null)
```

**Comment by jakevdp** [comment]
Actually, this looks like it's been reported in #7349

**Comment by jakevdp** [comment]
> any notebook I write with any of them should be loadable by someone with any Python kernel.

+1 on this, by the way.

**Comment by parente** [comment]
If it would help, I'm willing to run all of the notebooks in `examples/` as they appear after fresh checkout to see if they all work in Python 2 out of the box (beyond the kernel picking problem reported above). Is that work within the scope of this item?

**Comment by takluyver** [comment]
I think the main issue is the kernel picking problem, I doubt we've written any example code that is Python 3 specific (apart from the function annotation example which is deliberately so). That said, I'm sure manual checking of our example material would turn up some things that need correcting, so if you've got time, that would be welcome.

**Comment by parente** [comment]
Went through `IPython Kernel` and `Interactive Widgets` testing for Py2 issues so far. I found only one compat issue:

In Widget List.ipynb, the first dropdown example fails in Python 2 (`The 'value_name' trait of a Dropdown instance must be a unicode string, but a value of 1 <type 'int'> was specified.`) There's no text indicating that this is a Python 3 only example. The second dropdown example using a `str:int` dict works.

I did see a few other broken things along the way. I'll open those in a separate issue.

**Comment by franktoffel** [comment]
I've found a small problem while running the following notebook in tmpnb.org 

ipython_examples/Interactive Widgets/Lorenz Differential Equations.ipynb
 ```
In [4]:
....
File "<ipython-input-4-8bc116cc499d>", line 12
    def lorenz_deriv((x, y, z), t0, sigma=sigma, beta=beta, rho=rho):
                     ^
SyntaxError: invalid syntax
```
However, this only happens when using Python 3 (kernel by default). If I change it to Python 2, then there is no problem at all.

I am not sure whether this is a bug or just a problem with the code. I managed to avoid the error by parsing the vector as a list and then unpacking the values of x,y,z. I can send a PR but I don't find the original IPYNB in the repo, just the HTML one.

**Comment by rgbkrk** [comment]
@franktoffel Looks like [this notebook](https://github.com/ipython/ipython/blob/master/examples/Interactive%20Widgets/Lorenz%20Differential%20Equations.ipynb).

**Comment by jenshnielsen** [comment]
Tuples as input arguments have been removed in python2 so it is no surprise that this doesn't work 

http://legacy.python.org/dev/peps/pep-3113/

**Comment by franktoffel** [comment]
@rgbkrk that was I thought but I can't open it in my computer.

```
Error loading notebook
Unreadable Notebook: C:\Users\franktoffel\Documents\IPython Notebooks\Lorenz Differential Equations.ipynb Unsupported nbformat version 4
```
I know that I can directly edit the raw but I wasn't sure whether this is the original file or one being generated from other source [(something related to this issue)](https://github.com/ipython/ipython/issues/6052#issuecomment-47274260).

**Comment by takluyver** [comment]
Thanks for the heads up, I'll fix it.

The notebooks in master currently require IPython master to open them, because we've changed the notebook version format. We will make a 2.4 release that can read nbformat 4 notebooks.

**Comment by takluyver** [comment]
Now that #7454 is merged, I think we only need to open and save all the example notebooks so that their metadata is updated, then they will open in a Python 2 or 3 kernel, and we can close this issue.

**Comment by minrk** [comment]
The kernelspec metadata is added to all the examples in 3.0b1
