### ISSUE TITLE
nbagg shows no image

### ISSUE THREAD

**Issue by beojan** [ipython/ipython#7351]
When using the nbagg backend, the interactive widgets appear, but the plot itself does not, and the message
`[IPKernelApp] ERROR | No such comm: c795df2a293345a1ae3237c0f203d6d3`
is printed to the terminal.

**Comment by tacaswell** [comment]
@takluyver @minrk Something changed between 2.3.1 and the master branch which has really broken `nbagg`.  

We should get this figured out before ipython 3.0.  Mpl have a 1.4.3 planed for ~end of the month anyway so if fixes are needed on the mpl we can get that out in parallel.

**Comment by tacaswell** [comment]
It looks like there has been a lot of work done on the logic of registering/unregistering comms, so I suspect something got broken in that process, but I don't understand the code well enough to be sure.

**Comment by minrk** [comment]
Yup, we'll dig into this to see if we can figure out what's gone wrong. Some code got cleaned up in creating comms, but I don't think any breakage was intentional, so there's a good chance there's a bug on our side.

**Comment by tacaswell** [comment]
@minrk Any update on this?

**Comment by minrk** [comment]
Sorry, I'll try to dig into it some more.

**Comment by minrk** [comment]
Looks like it wasn't comm changes, but output changes that caused the problem. Opaque Promise failure messages just made it *look* like a comm failure, since it was an error in the comm_open callback. Should be fixedc by matplotlib/matplotlib#4002.

Sorry it took so long for me to get around to it.

**Comment by tacaswell** [comment]
@minrk fixed this on the mpl side, please close

**Comment by minrk** [comment]
Thanks!
