### ISSUE TITLE
'Dive into Python' book website

### ISSUE THREAD

**Issue by billtubbs** [ipython/ipython#7356]
This is not a bug, but I noticed that this website that is suggested as a link on the iPython homepage is no longer running.

iPython page URL:
http://ipython.org/ipython-doc/stable/interactive/tutorial.html

Link:
http://diveintopython.org/toc/index.html

Sounds like this tutorial/book is no longer available: "the author has pulled down all copies".

See here for a cloned copy:
http://www.diveintopython.net

**Comment by Carreau** [comment]
Thanks for the report, will take a look at broken link on website, there seem to be quite q few broken link. 

And BTW, the website code is here: https://github.com/ipython/ipython-website

**Comment by tacaswell** [comment]
@Carreau mpl has started to build the docs on travis and use a linkchecker to make sure they do not rot: https://github.com/matplotlib/matplotlib/blob/ab549acc3a546c03b2fce1a5a156df4c2a60d6cd/.travis.yml#L61

**Comment by Carreau** [comment]
Thanks, I was considering that. 
Sadly right now there are ~100 links with issues (I'm slowly fixing them).

Also side question but I can RTFD, how do you insure Travis push only master and not PR? (Or do you still deploy by hand)

Envoyé de mon iPhone

**Comment by tacaswell** [comment]
We are still deploying the docs by hand (there is a PR to auto-deploy, but it isn't finished yet).  The way that travis deals with the secret keys is you upload them via an encrypted ENV and travis only decrypts on branch builds (not PR bulids) due to the obvious security hole so it more-or-less takes care of it's self.

**Comment by rgbkrk** [comment]
This is actually fixed in master (http://ipython.org/ipython-doc/stable/interactive/tutorial.html), but in the original link above, http://ipython.org/ipython-doc/1/interactive/tutorial.html, the link is wrong. `/2/` is fine as well.

**Comment by rgbkrk** [comment]
Perhaps we just need it backported for old documentation which search engines will continue to cache and display?

**Comment by Carreau** [comment]
Closing as we will probably not fix old docs.
