### ISSUE TITLE
File Management UI supports creation of directories, but not their deletion

### ISSUE THREAD

**Issue by ssanderson** [ipython/ipython#7364]
On multiple occasions I've accidentally clicked the Folder option in the new dropdown for creating notebooks, causing me to create an "Untitled Folder" directory that I now can't delete... :crying_cat_face: .

**Comment by ssanderson** [comment]
I imagine other people have noticed this, but I couldn't find an open issue for it, and it seemed worth tracking.

**Comment by dsblank** [comment]
+1 (for creating a way to delete them). And for deleting files too.

**Comment by minrk** [comment]
I'm guessing making a complete filesystem manager and navigator is going to be unavoidable.

**Comment by ssanderson** [comment]
I'd actually be fine with removing the directory creator TBH, but I think that if you allow creation you have to allow deletion, or else you end up with a whole bunch of directories you can't do anything about easily.

**Comment by minrk** [comment]
That's definitely true. Personally, I would be for removal of the ability to create directories from the dashboard, but it's a reasonable thing to want, so we can go both ways. I agree that it should at least be symmetrical, whichever way we go.

**Comment by damianavila** [comment]
>I'm guessing making a complete filesystem manager and navigator is going to be unavoidable.

Yep... at least a very basic one... but minimally featured.

>Personally, I would be for removal of the ability to create directories from the dashboard, but it's a reasonable thing to want, so we can go both ways. I agree that it should at least be symmetrical, whichever way we go.

mmm... not sure about the ability removal... I agree in the symmetrical thing, of course, but I think I am +0.5 on allowing deletion of directories...

**Comment by Carreau** [comment]
What about rename to nothing delete?

Envoyé de mon iPhone

**Comment by ellisonbg** [comment]
This will be fixed by #7300
