### ISSUE TITLE
Clicking on menu actions in the notebook makes it jump to the beginning

### ISSUE THREAD

**Issue by ccordoba12** [ipython/ipython#7367]
Fox example, if you click on `Insert > Insert Cell Above` or `View > Toggle Header`, the notebook jumps immediately to the beginning. It seems the same happens with all actions (although I haven't tried them all).

I'm using 3.0.0-dev, revision 4b40dd4

**Edit**: I tried it in Firefox 33 and Chrome 34

**Comment by mathieu1** [comment]
The same happens by clicking any action associated with tooltips (shift+tab) i.e. "show the current docstring in pager", "grow the tooltip vertically" and close.

**Comment by ccordoba12** [comment]
Hey @takluyver could you confirm this one? I think it's an ugly regression you should address before 3.0 is released :-)

**Comment by takluyver** [comment]
Confirmed. @jdfreder , I think you're most familiar with scroll behaviour. Can you have a look, or ping someone else to look at it?
