### ISSUE TITLE
Edit Cell Metadata doesn't work

### ISSUE THREAD

**Issue by juhasch** [ipython/ipython#7370]
System:
- current master
- Anaconda Python 3.4
- Chrome
- Windows 7 in a Virtualbox

When trying to edit metadata I get a grayed out display and can't edit anything:
![edit-medadata](https://cloud.githubusercontent.com/assets/2445216/5607168/a76cad2e-944f-11e4-9747-09c453c4d9e8.png)

**Comment by minrk** [comment]
Looks like our CSS was out of date. Should be fixed by #7376
