### ISSUE TITLE
WrappedError when saving notebook

### ISSUE THREAD

**Issue by juhasch** [ipython/ipython#7371]
When trying to save a notebook I get the following error in the follwing message in the Javascript console:
![error-saving](https://cloud.githubusercontent.com/assets/2445216/5607177/35f1893e-9450-11e4-9421-fcd7a50e0022.png)

System:
- current master
- Anaconda Python 3
- Virtualbox Windows 7
- Chrome

**Comment by minrk** [comment]
@juhasch can you expand the stack in the WrappedError?

**Comment by minrk** [comment]
Nevermind, I can reproduce it.

**Comment by minrk** [comment]
should be fixed by #7373

**Comment by juhasch** [comment]
Thanks for the quick fix!
