### ISSUE TITLE
No encoding declared on Python output of nbconvert

### ISSUE THREAD

**Issue by guy4261** [ipython/ipython#7378]
I run *ipython nbconvert my_notebook.ipynb --to python* and what I get is a Python file which can't run due to the following error:
```Python
SyntaxError: Non-ASCII character '\xd7' in file my_notebook.py on line 212, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

One of my cells output contains a non-ascii character, and when I add the encoding comment to the first line of my script:
```Python
# -*- coding: UTF-8 -*-
```

the script is usable again.

However, IPython nbconvert does not include a command line flag that allows me to do either of the following two options:
* Supply an encoding string that will be use in the *coding:* comment to the first line,
* Convert to Python code without the cells output.

Any solution will be appreciated.

BTW, I also didn't find a way to make Python run a .py script using a command-line specified encoding... But that's another deal.

**Comment by Carreau** [comment]
I think utf8 by default would be fine. I don't think we should support other encoding. It there is really a request for it, we can rethink about it. 

Do you want to submit a PR that add the encoding comment to python export ?

**Comment by damianavila** [comment]
>I think utf8 by default would be fine

:+1:

**Comment by takluyver** [comment]
The Python template already has a coding template, so I'm not sure how this occurred:

https://github.com/ipython/ipython/blob/master/IPython/nbconvert/templates/python.tpl#L4

**Comment by damianavila** [comment]
>The Python template already has a coding comment, so I'm not sure how this occurred:

oppsss... you are right...

**Comment by minrk** [comment]
@guy4261 what version of IPython are you using? Do you have a custom template or any other nbconvert-related config?

**Comment by minrk** [comment]
I opened #7383, which adds tests that verify that this does not affect master, at least.
