### ISSUE TITLE
threadsafe widgets

### ISSUE THREAD

**Issue by jacksonloper** [ipython/ipython#7411]
All widgets share the same iopub_socket, so this code breaks:

```
import IPython.display
from IPython.html import widgets
import threading
from numpy.random import randint

isw1=widgets.IntSlider()
IPython.display.display(isw1)

isw2=widgets.IntSlider()
IPython.display.display(isw2)

def randoset(wid,N):
    for i in range(N):
        wid.value=randint(0,50)

t1=threading.Thread(target=randoset,args=[isw1,100])
t2=threading.Thread(target=randoset,args=[isw2,100])
t1.start()
t2.start()
```

Does this matter?  Probably.  There could be valid use-cases for multithreaded widgets which display results obtained by polling external resources, e.g. widgets which keep track of EC2 instances, widgets which monitor IPython.parallel workerbees, etc.

Hoping @minrk, @ellisonbg, @jdfreder, or @fperez may weigh in on our options!

**Comment by ellisonbg** [comment]
@minrk had the idea to tie into the tornado event loop rather than using a mutex. This is a much better idea.

**Comment by minrk** [comment]
Marking as 4.0

**Comment by jdfreder** [comment]
> e.g. widgets which keep track of EC2 instances

Yeah @ellisonbg, @jgoad, and I just ran into this type of problem with a Crazyflie.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
