### ISSUE TITLE
User interface tour broken.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7418]
Don't start at all;  raise as undefined not a function deep in bootstrap.

**Comment by minrk** [comment]
@Carreau what page is failing, and what exact commit, browser, etc.? Everything looks fine, here.

**Comment by Carreau** [comment]
4d67561570b1d1f30fd8c8640af703533daa9ff7, (merge modal-modal) notebook page > help menu, User interface tour, do nothing, private browsing windows agressive refresh, git status clean, submodule updated. 
Chrome 40; OS X 10.8.

```
...
Kernel: kernel_ready (a0e78cff-ea2d-4d09-81b0-922e9fd5070a)
tour.js:145 let's start the tour
tour.js:131 tour started
bootstrap-tour.min.js:19 Bootstrap Tour 'tour' | Show the orphan step 1. Orphans option is true.
bootstrap.min.js:6 Uncaught TypeError: undefined is not a function

(anonymous function)    bootstrap.min.js:6
x.extend.each           jquery.min.js:4
x.fn.x.each             jquery.min.js:4
b                       bootstrap.min.js:6
c._showPopover          bootstrap-tour.min.js:19
(anonymous function)    bootstrap-tour.min.js:19
c._scrollIntoView       bootstrap-tour.min.js:19
c.showStep.ended.c      bootstrap-tour.min.js:19
c._callOnPromiseDone    bootstrap-tour.min.js:19
c.showStep              bootstrap-tour.min.js:19
c._callOnPromiseDone    bootstrap-tour.min.js:19
c.start                 bootstrap-tour.min.js:19
NotebookTour.start      tour.js:147
(anonymous function)    menubar.js:288
x.event.dispatch        jquery.min.js:5
x.event.add.y.handle    jquery.min.js:5
```

Dropping on last call I saw a `data[option]()` where `option` is a object, and `data` has string keys, so `data[option]` is indeed undefined. Seem to be a bootstrap plugin (popover) which is not defined as far as I can tell.

**Comment by mathieu1** [comment]
For me (on OS X 10.10 / Chrome / current master) `Help > User Interface Tour` does nothing. The error thrown in the JS console is 
![jserror](https://cloud.githubusercontent.com/assets/7703352/5696874/b6db6850-99df-11e4-96c3-3c3a0c753a5d.png)

(sorry for the stupid screenshot but pasting from the JS console is worse)

**Comment by minrk** [comment]
Sorry, I read it as "User interface broken", I completely missed the "tour" part.

**Comment by jhamrick** [comment]
This is the offending commit: 43a0e469fd3cdc2aebd4843e223538c530e45632, according to git-bisect. Looking at what changed in components, my guess is that it was the upgrade to bootstrap 3.3 that broke this, but I will investigate further.

**Comment by jhamrick** [comment]
I believe the error is occuring here in bootstrap-tour.js:

https://github.com/ipython/ipython-components/blob/master/bootstrap-tour/build/js/bootstrap-tour.js#L482

And then later down in the trace, here in bootstrap.js:

https://github.com/ipython/ipython-components/blob/master/bootstrap/js/bootstrap.js#L1689

I'm not sure that provides all that much insight, though.

I also tried updating to the most recent version of the bootstrap tour (we're on 0.9.0, the most recent is 0.10.1), but that didn't seem to fix it, unfortunately.

**Comment by jhamrick** [comment]
Aha, it is a bug in bootstrap-tour itself: https://github.com/sorich87/bootstrap-tour/issues/356 I'll try the fix suggested there and see if it works.

**Comment by jhamrick** [comment]
That fix kind of seems to work, but leaves the tour broken in other ways (for example, controlling it with the arrow keys seems to break it) -- I'm not sure if that's because the version of bootstrap-tour is too old, or if it's interfering with IPython keybindings, or what. I can't debug more tonight, but maybe this is enough for someone else to run with.

**Comment by jhamrick** [comment]
I will try to take another stab at fixing this as I would ideally like to have this feature before my class releases the first problem set. Not 100% sure if I will have time, but I will try!

**Comment by jhamrick** [comment]
Well, it seems like after upgrading to the newer version of the bootstrap tour, the `backdrop` option is broken, looks like this:

![image](https://cloud.githubusercontent.com/assets/83444/5827937/d8c1027e-a0b3-11e4-8249-a7928a6ea6b3.png)

I can try to debug this further, though am pretty stumped so far. Or, the easier option is just to not use the backdrop.

**Comment by jhamrick** [comment]
Oops, this should probably be reopened until #7515 is merged.
