### ISSUE TITLE
Mouse wheel shouldn't make code cells scroll

### ISSUE THREAD

**Issue by rossant** [ipython/ipython#7419]
If you turn the mouse wheel down while hovering over a code cell, the contents of the code cell scroll, hiding the first line of the cell. Tested in latest Chrome and Firefox on Ubuntu 14.04.

**Comment by mathieu1** [comment]
Duplicate of #7395, fix in the pipes apparently :)

**Comment by rossant** [comment]
Right, missed that... Closing!
