### ISSUE TITLE
Notebook Help is IPython kernel specific

### ISSUE THREAD

**Issue by dsblank** [ipython/ipython#7424]
Now that kernels can display their own help, the standard help menu should contain links to items that are kernel-agnostic. The two standard help menu items, `Notebook help` and `Markdown help` are two good categories for general use:

![screenshot from 2015-01-12 07 05 16](https://cloud.githubusercontent.com/assets/168568/5702594/04c07124-9a2a-11e4-926d-2363a67cd7bb.png)

However, the `Notebook help` points to a page (http://nbviewer.ipython.org/github/ipython/ipython/blob/2.x/examples/Index.ipynb) that is full of IPython-specific items on magics, widgets, parallel code, etc. 

Suggest pointing to a new page that only describes the Notebook frontend without any kernel-specific details. 

(The `Markdown help` is not a good introduction to Markdown, but I'll make a separate issue for that.)

**Comment by ellisonbg** [comment]
The documentation in master has a much better separation of the python and general stuff. At the same time, it is likely that we will continue to *demonstrate* the features of the notebook (such as widgets, output, etc.) using Python code.

This is where the notebook help link should point:

http://nbviewer.ipython.org/github/ipython/ipython/blob/master/examples/Notebook/Index.ipynb

This is where the kernelspec help for python should point for the (notebook part) of the python kernel docs:

http://nbviewer.ipython.org/github/ipython/ipython/blob/master/examples/IPython%20Kernel/Index.ipynb
