### ISSUE TITLE
Markdown help page could be more useful

### ISSUE THREAD

**Issue by dsblank** [ipython/ipython#7428]
The Markdown help for all kernels is currently a link to:

https://help.github.com/articles/github-flavored-markdown/

This is GitHub specific, and has advanced details and terms that may not be an appropriate link to send first-time users to. Also, as it is GitHub specific, there is no additional information about where to go for more/better help (eg, mailing list, stackoverflow, videos, additional links, etc).

Suggest that Jupyter provide a more gentle introduction to Markdown, perhaps at least using:

https://help.github.com/articles/markdown-basics/

or taking parts of our Users Manual from our local install of Jupyterhub from a few months ago and creating a Jupter-specific page:

http://jupyter.cs.brynmawr.edu/hub/dblank/public/Jupyter%20Notebook%20Users%20Manual.ipynb

**Comment by takluyver** [comment]
I think when we put that link in, it was a general overview of GFM, and Github then reorganised things to make it a description of how GFM differs from regular Markdown.

PR coming up.

**Comment by takluyver** [comment]
See #7429
