### ISSUE TITLE
Links/References within resource responses in API

### ISSUE THREAD

**Issue by rgbkrk** [ipython/ipython#7437]
For all of the API resources, provide references to the resources in a navigable way. E.g. when getting the `/api/kernels` endpoint, have the full link to the kernel resources:

```
[{"name": "python2",
  "id": "61d5d2e2-f1eb-4489-b0f7-5c652b888517",
  "href": "/basepath/api/kernels/61d5d2e2-f1eb-4489-b0f7-5c652b888517"
  }]
```

Not sure if they should be relative or absolute. We probably have to assume they're relative in the default case for users that have a local installation (and no idea what domain they run on), whereas if we had a service that ends up doing any amount of redirection, we might want the full URL:

```
[{"name": "python2",
  "id": "61d5d2e2-f1eb-4489-b0f7-5c652b888517",
  "href": "https://try01.jupyter.org/basepath/api/kernels/61d5d2e2-f1eb-4489-b0f7-5c652b888517"
  }]
```

There isn't a standard for this per se, but I've been reading several resources:
- [Haters gonna HATEOS](http://timelessrepo.com/haters-gonna-hateoas)
- [HAL - Hypertext Application Language](http://stateless.co/hal_specification.html)
- [JSON Linking](https://www.mnot.net/blog/2011/11/25/linking_in_json)

It would be really useful for @odewahn / @oreillymedia as well as anyone providing [just the kernels](https://github.com/rgbkrk/kernels-service).

**Comment by minrk** [comment]
From gitter: I think we should do this, but we might hold it until after 3.0. It would be really nice to reduce the amount of URL composition we do in Javascript, but I don't think we should do *that* refactor for 3.0, so I would either:

A. add the links to the REST API in 3.0, but don't use them in Javascript, yet
B. add the links to the REST API and start using them in Javascript for 4.0

Since we are trying to do our best to start cutting off proposals for 3.0, I would go with B unless the benefit is really substantial.

**Comment by rgbkrk** [comment]
I'm happy to start implementing the links to the REST API for 3.0 and not use them in JavaScript yet, at least as an exploration on how we do it. There isn't one golden standard for linking but thus far, I'm liking the [HAL Spec](http://tools.ietf.org/html/draft-kelly-json-hal-06) the most.

Didn't mention it above but [GitHub's API uses `*_url` for the keys](https://developer.github.com/v3/gists/#response).

**Comment by rgbkrk** [comment]
Oops, meant to say that if I start and it doesn't make it into 3.0 in time, that's also cool too and just becomes option B. :wink:

**Comment by takluyver** [comment]
Milestoned 4.0 for now.

**Comment by rgbkrk** [comment]
Closing since this belongs in jupyter/notebook.
