### ISSUE TITLE
Code cell shrinking

### ISSUE THREAD

**Issue by mathieu1** [ipython/ipython#7447]
I've been experiencing a bug for some days now using notebooks from current master, but I can't pinpoint an exact procedure to reproduce it. All is fine for a while, then seemingly randomly, the notebook gets into a state in which clicking every "normal" code cell will "shrink" it a bit. 
![cell-shrinking](https://cloud.githubusercontent.com/assets/7703352/5736379/71d85482-9bd5-11e4-929e-a734c2fdcfa5.gif)
Nothing to be seen in the JS console. Everything gets back to normal after refreshing the notebook (for a while at least). On current master / OS X 10.10 / Chrome.

**Comment by Carreau** [comment]
Gosh...

Could it be since https://github.com/ipython/ipython/pull/7414 ?

**Comment by mathieu1** [comment]
I *think* I've had this issue for a week or so, so I don't think the Codemirror update made things worse. But then again, I'm not quite sure of when I first had this.

**Comment by Carreau** [comment]
so a week or so might have been https://github.com/ipython/ipython/pull/7347 , which is known to have introduce issues. Pondering revert to 4.8.

**Comment by mathieu1** [comment]
Maybe... Anything I can do when this happens again (pretty sure it will) to debug / find out how to reproduce?

**Comment by Carreau** [comment]
Yeah, you could try to open web-inspector of your browser, and try to figure out why the cell have the wrong height. But it require some experience dealing with web stuff.  You can also go to IPython/html/static/components and for install codemirror 4.8 with bower to see if the bug still appear.

**Comment by mathieu1** [comment]
Happened again, but the problem disappears when opening the JS console, maybe this only happens for certain browser width.

Found out this possibly related width-dependant code cell growing issue:
![cell-growing](https://cloud.githubusercontent.com/assets/7703352/5777892/cba88672-9d96-11e4-861d-2a0465396d98.gif)

**Comment by mathieu1** [comment]
I guess I'll keep listing weirdness I encounter here, as this all seems like Codemirror issues to me (let me know if you think it is unrelated and if I should open a separate issue). 
Weirdness 3 : tooltips within certain cells are systematically fetching the documentation for some object on the line below (don't know how to reproduce, but not fixed after refresh, will see if I can get an example notebook)
![tooltip](https://cloud.githubusercontent.com/assets/7703352/5792687/d0ccde60-9f25-11e4-85da-ca6f320ffc50.png)

**Comment by minrk** [comment]
I'll bet CodeMirror *really* hates that you can't just ask a browser if/where scrollbars are drawn. There seem to be new scrollbar-related bugs every single update. And they are usually browser dependant.

**Comment by jdfreder** [comment]
> Weirdness 3 : tooltips within certain cells are systematically fetching the documentation for some object on the line below (don't know how to reproduce, but not fixed after refresh, will see if I can get an example notebook)

This is probably a bug in our tooltip code, not Codemirror.

**Comment by mathieu1** [comment]
BTW, haven't seen any of this for a while... Feel free to close or milestone beyond 3.0

A minor annoyance I'm seeing on OSX / Chrome is that I can't scroll quite enough to the right in code cells, I'm never sure whether there is more code to the right...
![line-end](https://cloud.githubusercontent.com/assets/7703352/6128602/8db32ade-b137-11e4-889d-f8103a3d120a.gif)

**Comment by minrk** [comment]
Thanks, @mathieu1

**Comment by doomsplayer** [comment]
save issue on my macbook/chrome
