### ISSUE TITLE
Trailing whitespace when paste a word to notebook

### ISSUE THREAD

**Issue by dalguji** [ipython/ipython#7448]
When I copy a word and paste it into iPython notebook, I see a whitespace is followed after the pasted word. For instance, when I double-click on a word 'apple' on a normal web page and paste it into iPython notebook, 'apple ' is actually pasted.

This issue consistently happens especially when I copy a word from web browsers by double-click, while copying by drag does not cause it.

I am using iPython 2.3.1 on OSX Yosemite and I think I have been seeing this issue at earlier versions. I was wondering if it's a known issue and planed to be fixed.

**Comment by Carreau** [comment]
Upstream bug, I will repo upstream.

**Comment by Carreau** [comment]
Actually webkit "Feature". works in any text area, and no short term plan to give an option to deactivate. 
So unfortunately, nothing we can do technically, and not enough political power to have webkit considering an option.

Sadly closing as nothing we can do :_(

**Comment by Carreau** [comment]
Might e able to do something with clipboardAPI at some point in future, so reopenning with a bit of hope.
