### ISSUE TITLE
enhancement: facilitate highlighting specific lines of code in markdown

### ISSUE THREAD

**Issue by jason-s** [ipython/ipython#7449]
I'm working on a slide show using IPython and would like to highlight some specific lines of code, like the ones shown in these blog posts:
- http://zpao.com/posts/adding-line-highlights-to-markdown-code-fences/
- http://en.support.wordpress.com/code/posting-source-code/

![code-line-highlight](https://cloud.githubusercontent.com/assets/738893/5739397/62651a04-9bb6-11e4-9f07-e46fca60746a.png)

or this:  (doesn't seem to work in IPython or in nbconvert-exported ipython)
http://sebastianraschka.com/Articles/2014_markdown_syntax_color.html

Is there any way to add this feature to IPython?

**Comment by Carreau** [comment]
Probably not in core, but with [an extension](https://github.com/ipython-contrib/IPython-notebook-extensions/) it is liketly to be possible. 

Live slideshow ? Or exported with nbconvert ? In live notebook have a look at wether [codemirror](http://codemirror.net/) support line styling. You probably want to play with ["gutters markers"](http://codemirror.net/demo/marker.html) to decide which line should be highlighted.

Is @jhamrick using something similar for classes ?

**Comment by jason-s** [comment]
I don't need live, just exported with nbconvert.
