### ISSUE TITLE
Dashboard grey out unreadable notebooks and files.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7451]
Assuming a notebook is chomd 000, it shoudl not be clickable on dashbord. 

Yes it has  few chances to happen on filesystem backend, but it is common in Google drive, where you app have limitted access.

**Comment by minrk** [comment]
Maybe they should just be excluded from the drive listing.

**Comment by ellisonbg** [comment]
I think that for now excluding these from the content manager listing makes the most sense. An unreadable file is really useless of the notebook UI.
