### ISSUE TITLE
Enable tab completion and tooltips to be triggered on regular expressions

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#7467]
There are many kernels for which it woudl be useful to trigger tab completion and tooltips on various regular expressions. We think this would be useful to think about in the future.

**Comment by dsblank** [comment]
MetaKernel handles generic language completion and help through regular expressions:

https://github.com/Calysto/metakernel/blob/master/metakernel/_metakernel.py#L19

**Comment by Carreau** [comment]
I think Brian miss-described the issue. 

The question is that lots of user and kernels authors want to trigger info-request and completion request not only on tab, but on other keypress (most often requested are space, and dot) 
We don't care about the regular expression to match token as in any case the all cell (and sometime even more) would be sent to the kernel for completion/inspection. 

But we need a way to configure that in the frontend (here probably notebook)

**Comment by dsblank** [comment]
Ah, that would be useful. Although it might still involve a regular expression: when dot is the keypress, "1." should not trigger the function whereas "object." should. Except in a language like Ruby, where you can call methods on a number. I guess the kernel could be triggered, but not respond... but it could generate a lot of extra communication, which could be limited by use of a regular expression.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
