### ISSUE TITLE
Focus stays on toolbar buttons after action

### ISSUE THREAD

**Issue by mathieu1** [ipython/ipython#7475]
I ran into the following:
Step 1 : delete a cell (click the cut button)
Step 2 : run a few cells with shift + enter a bunch of times
Ooops, many cells just got cut!

Much more harmless, but might be useful for debugging: the copy button also keep focus, and so do the cell-up (cell-down) buttons when activated on the top (bottom) cell.

By the way, mistakenly cutting more than one cell happens regardless of this issue (human error). Am I correct in thinking that in such a situation, the only thing that can be done currently is to shutdown the notebook before it auto-saves (or not rely on auto-saves but checkpoints instead)?

**Comment by Carreau** [comment]
Ouh, nasty. #7476 should take care of that.

> By the way, mistakenly cutting more than one cell happens regardless of this issue (human error). Am I correct in thinking that in such a situation, the only thing that can be done currently is to shutdown the notebook before it auto-saves (or not rely on auto-saves but checkpoints instead)?

You could disable autosave, or rely on checkpoint, yes. 
There have been attempt at undo history:

https://github.com/ipython/ipython/pull/6779
