### ISSUE TITLE
Save notebooks with terminal newline (option)

### ISSUE THREAD

**Issue by jakirkham** [ipython/ipython#7478]
Maybe this feature already exists and I don't know it, in which case please clue me in.

It would be nice to save iPython notebooks with a newline before EOF. As whitespace isn't significant in JSON, this should remain valid JSON.

If there is some other reason that this shouldn't be standard, could we at least have an option perhaps in ~/.ipython somewhere?

Thanks.

**Comment by minrk** [comment]
@jakirkham done in #7479

**Comment by jakirkham** [comment]
@minrk thank you.
