### ISSUE TITLE
Links to header cells hide the cell under the menu

### ISSUE THREAD

**Issue by mathieu1** [ipython/ipython#7484]
Here's what things look like before and after clicking on link in the header cell.

![before-after](https://cloud.githubusercontent.com/assets/7703352/5774443/2eca7f68-9d6e-11e4-8c9f-944b16a0cd4d.png)

**Comment by minrk** [comment]
Yeah, some changes to how the header and notebook are on the page have really messed with the notebook scrolling a lot. Ping @jdfreder for any ideas.

**Comment by Carreau** [comment]
http://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header

or alike should do the trick.

**Comment by ellisonbg** [comment]
Confirming this bug.

**Comment by minrk** [comment]
In reading about fixed headers and scrolling, we have to put manual invisible negative-margin, positive padding elements on all anchors (what the @Carreau's link suggests, and roughly every resource I have found on the matter)

That proposal would also have to be applied to all user elements with IDs. *Every* element with an ID would need such a spacer, not just our own headers. I do not think that is reasonable.

To me, this means we made a mistake in switching to a fixed header, and the notebook should go back into a statically positioned div, rather than sitting and floating in the body.

**Comment by ellisonbg** [comment]
OUCH

Let's put this on the agenda for Th. The benefits of the approach in master
are significant (pager cleanup, notebooks are now printable, scrolling
performance much better, etc.). It is a really non-trivial cost to go back.
Hmmmm...

On Tue, Jan 20, 2015 at 4:42 PM, Min RK <notifications@github.com> wrote:

> In reading about fixed headers and scrolling, we have to put manual
> invisible negative-margin, positive padding elements on all anchors (what
> the @Carreau <https://github.com/Carreau>'s link suggests, and roughly
> every resource I have found on the matter)
>
> That proposal would also have to be applied to all user elements with IDs.
> *Every* element with an ID would need such a spacer, not just our own
> headers. I do not think that is reasonable.
>
> To me, this means we made a mistake in switching to a fixed header, and
> the notebook should go back into a statically positioned div, rather than
> sitting and floating in the body.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/7484#issuecomment-70764338>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
I have difficulty believing that it's impossible to have a header and content, where the header is taken into account when scrolling elements on the page. But consensus seems to be that a fixed header is *not* the way to accomplish that, which is maddening.

**Comment by minrk** [comment]
I opened #7517, which removes the fixed header but appears to behave otherwise the same. No idea what catastrophic consequences it may have that I haven't noticed yet, though. Every layout change seems to have one or two.
