### ISSUE TITLE
%load in qtconsole places cursor in the wrong place

### ISSUE THREAD

**Issue by lgretton** [ipython/ipython#7485]
When using qtconsole and %load to load a Python program the program will not execute once loaded

It seems that the cursor is being placed on the line after that of the program's last line instead of at the end of the last line. If the cursor is moved back and return is entered, the program will execute.

ipython 2.3.1, Qt 4.8.6, PyQt 4.11.3, Python 2.7.9, Scientific Linux 6.4 (64-bit).

**Comment by takluyver** [comment]
#7487 should fix this.
