### ISSUE TITLE
Protect modal body from untrusted HTML

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7486]
`IPython.dialog.modal({'body':"<script>alert('bar')</script>"})` does what you expect. 

Which is annoying as `load_notebook_error` get the message from the rejected promise, whose `error.message` might be remote from some weird unexpected things. 

proposal: 

in our dialog implementation, use a `unsafe_body` key when we know the body come from a trusted source and contain html. Use it if necessary,  and sanitize/escape otherwise.

**Comment by minrk** [comment]
I agree that we should escape html from untrusted sources, but I disagree that we should use an 'unsafe_body' key, since we would always set it to true, which defeats its purpose. We should just be wary of html from untrusted sources. The load_notebook_error message does come from a trusted source, so it's not an example of a problem.

**Comment by Carreau** [comment]
> The load_notebook_error message does come from a trusted source, so it's not an example of a problem

On jupyterdrive I am not completely certain it comes from a trusted source. (Agreed this is paranoia)

I think I miss expressed myself with unsafe_body:

Imho :
`modal({ body: '<script>alert('foo')</script>'})` should show `<script>alert('foo')</script>` and `modal({ unsafe_body: '<script>alert('foo')</script>'})` should execute the js, or whatever name we give it. 

unsafe usage  of modal should be explicit, safety should be default.

**Comment by minrk** [comment]
Every single case we have right now would use unsafe_body, so I'm not sure how that helps.

**Comment by jdfreder** [comment]
I think it's completely fine for this helper function to accept HTML.  I think wherever you're uncertain if the content is safe or not (you mention jupyterdrive) you should sanitize it before passing it into the dialog method.

**Comment by minrk** [comment]
Absolutely. There's no way dialog should stop accepting HTML. I've retitled the issue, since I don't think @Carreau is proposing that.

**Comment by Carreau** [comment]
Sorry for confusing title. 
I ment that if the function receive text it should not be considered trusted and turned into html.

**Comment by takluyver** [comment]
This was addressed by #7493.
