### ISSUE TITLE
Markdown output is not sanitized by nbconvert

### ISSUE THREAD

**Issue by ssanderson** [ipython/ipython#7488]
In the live notebook, Markdown output is always sanitized before being displayed to the user. However, the static html produced by nbconvert is unsanitized.  This isn't an XSS vulnerability per se, since the rest of the rendered static html is also allowed to have javascript, but It seems odd that markdown renders differently in the different context.

It would also be nice if it were easy to configure nbconvert to spit out escaped markdown.

**Comment by minrk** [comment]
What do you mean by "spit out escaped markdown"?

You can set the display_priority config to exclude markdown altogether. Since sanitization happens in js, I'm not sure how we can add sanitization to nbconvert without including a massive js library.

**Comment by ssanderson** [comment]
By "spit out escaped markdown", I mean "render markdown with the same escaping/sanitization semantics as are applied with the live notebook".  

A more fancy version of this would be something like adding an HTMLExporter option to configure a whitelist of tags to render as HTML, with any other being removed and/or escaped.  (If this route were considered the issue probably wouldn't be Markdown-specific so much as it would be about making it possible to configure the escaping behavior of nbconvert). I've had some success playing with [Bleach](https://pypi.python.org/pypi/bleach) locally to accomplish this.  I can probably make this work with my own local subclass of `HTMLExporter`, but I suspect that other people might benefit from having this be configurable in the default distribution.

**Comment by minrk** [comment]
We should probably consider adding Bleach in the future. Marking as 4.0.

**Comment by ssanderson** [comment]
@minrk it turns out it's actually really straightforward to do this nicely with an nbconvert Preprocessor.  Would you guys be interested in a PR to add it to the existing preprocessor library?

**Comment by Carreau** [comment]
> @minrk it turns out it's actually really straightforward to do this nicely with an nbconvert Preprocessor. Would you guys be interested in a PR to add it to the existing preprocessor library?

Sure, we can always review it, even if it it not merged, at least it is reviewed and easy to make standalone.

**Comment by minrk** [comment]
I think it makes sense, but we can review it after we get 3.0 out the door.

**Comment by ssanderson** [comment]
Proposal for this lives at #7595

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
