### ISSUE TITLE
nbformat v2 notebook with missing 'stream' key in stream outputs

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#7490]
@stefanv just sent me an nbformat 2 notebook which was missing the 'stream' keys in stream outputs, and failed to open in current master because of this.

@minrk , can you remember if that was ever a valid option in the notebook format? If so, we should support it. If not, we can write it off as having been saved by some broken development version of IPython.

**Comment by minrk** [comment]
It has never been valid, but it can be fixed easily enough, so might as well handle it.

**Comment by stefanv** [comment]
Thank you!
