### ISSUE TITLE
PDF generation from notebook fails if euro symbol (€) is present

### ISSUE THREAD

**Issue by jthiem** [ipython/ipython#7511]
Hi, I found that if the euro currency symbol is in the markup of a Notebook, "Download as PDF" and `ipython nbconvert --to=pdf` fail, since LaTeX doesn't know `\euro`. The LaTeX headers need an appropriate `\usepackage`, perhaps `\usepackage{eurosym}` (which works but some users find ugly).

**Comment by takluyver** [comment]
Not being a LaTeX user, it constantly amazes me that people still put up with nonsense like this. You really need a package to write €?

**Comment by Carreau** [comment]
> You really need a package to write €?

Sadly yes cause fonts used might not have it. 

You are lucky £££££
