### ISSUE TITLE
Dashboard/notebook list is sluggish

### ISSUE THREAD

**Issue by jhamrick** [ipython/ipython#7518]
Loading the dashboard/notebook list is fairly sluggish. This isn't too noticeable on a local connection, but to a remote server, it can be pretty obvious -- in my use case, after launching the dashboard from JupyterHub, I sometimes have to wait 5-6 seconds at a blank screen before anything shows up, with no indication of loading:

![image](https://cloud.githubusercontent.com/assets/83444/5831094/1dd384be-a0e0-11e4-9d4a-455d7c91a8da.png)

The problem appears to be loading of all the javascript files. This could potentially be resolved by minifying and concatenating the javascript (see also issue #6576 and PR #6580). An interim solution could be to at least display something (e.g. the jupyter logo and a "Loading, please wait..." message), just to let the user know that something is happening, while the rest of the javascript is loading.

**Comment by minrk** [comment]
Since the notebook javascript is now minified/concatenated, I'm going to close this. I realize there's still room to improve, but we can open new issues on the notebook repo for that.
