### ISSUE TITLE
Unicode characters inside code cells in IPython notebook

### ISSUE THREAD

**Issue by juliohm** [ipython/ipython#7519]
I'm using IPython notebooks with the Julia profile. Code can contain unicode characters and these are incorrectly highlighted after the HTML document is generated (see figure):

![incorrect unicode](http://i.imgur.com/DDUQ8ae.png)

**Comment by Carreau** [comment]
I think the issue has been reported recently. 
the [pygments](http://pygments.org/) highlighter need to be updated.
We use pygments definition as is any update to julia syntax or highlighting problem is likely to 
comme from there.

**Comment by Carreau** [comment]
Oh, and issues has even been openned upstream : https://bitbucket.org/birkenfeld/pygments-main/issue/1074/square-boxes-around-unicode-characters-in

**Comment by juliohm** [comment]
They are still working on this issue?

**Comment by juliohm** [comment]
This is still an issue in Jupyter 4.0.6.
