### ISSUE TITLE
IPython alias for "nbconvert --ExecutePreprocessor.enabled=True" [Wishlist]

### ISSUE THREAD

**Issue by chrish42** [ipython/ipython#7524]
I've been waiting for a way to run IPython notebooks on the command-line, so I was happy to see that this feature landed in what is to become IPython 3.0. However, given the current proposed way of invoking this:

    ipython nbconvert InputNotebook --ExecutePreprocessor.enabled=True --to notebook --output Executed

I can see myself forgetting and looking this up multiple times. Given that this is a really useful feature, it'd be nice if there was a much shorter and easier to remember way of invoking this. Maybe a `nbrun` or `nbexec` alias for `nbconvert --ExecutePreprocessor.enabled=True`? I think that would go a long way towards making this feature easier to discover and invoke. Thanks.

**Comment by takluyver** [comment]
You can replace `--ExecutePreprocessor.enabled=True` with `--execute`. I think we should leave shorter aliases up to individual users for the time being.

**Comment by minrk** [comment]
I think `--execute` satisfies this condition. Adding your own `alias nbrun="ipython nbconvert --execute"` to `[shell]rc` should be sufficient if you use it a lot (I have `alias nbc="ipython nbconvert"`).
