### ISSUE TITLE
Misc permissions edge cases

### ISSUE THREAD

**Issue by jhamrick** [ipython/ipython#7527]
Playing around with some permissions things, I have discovered a few more edge cases:

* Currently, if you try to delete a file, create a new folder, or duplicate a file, but don't have permission, it fails silently from the dashboard, though it appears to be handled correctly on the backend, e.g.

```
[W 21:39:21.046 SingleUserNotebookApp] delete /Problem Set 0/0 - Index.ipynb
[W 21:39:21.046 SingleUserNotebookApp] Permission denied: Problem Set 0/0 - Index.ipynb
```

* If you try to create a new file but don't have write permission on the directory, just it opens a new, blank tab. Again, relevant log messages show up suggesting it's being handled properly on the back end.

* If the directory is `chmod -w` but the user does have write permission to the *file*, IPython still complains that the file is read only.

**Comment by takluyver** [comment]
Thanks. I think the third one is because our atomic saving needs to be able to create new files in the directory (it does save & rename).

**Comment by jhamrick** [comment]
Ah, that makes sense. That's probably ok, then.

**Comment by takluyver** [comment]
@minrk I think you're most familiar with this stuff - is there something reasonable we can do about the first two cases?

**Comment by minrk** [comment]
I opened #7620, which should address the ones we can address. Looks like it was a few missing `catch-> show error` bits.
