### ISSUE TITLE
Notebook Help links don't work

### ISSUE THREAD

**Issue by dsblank** [ipython/ipython#7532]
In current master, none of the Help links in the Help menu that open URLs are working. For example, clicking on menu -> Help -> Markdown doesn't go to URL (nothing happens).

I'm on Chrome on Linux.

**Comment by Carreau** [comment]
Gosh. 
I submitted two fixes.

**Comment by dsblank** [comment]
Thanks! Thanks! :) 

Is HTML 5 a requirement for IPython notebook?

**Comment by Carreau** [comment]
```
<!DOCTYPE HTML>
<html>
```

So I would say yes. The question is how much of Html5 is supported by a browser, 
and how much needs IPython. http://caniuse.com/ is of help. 

Roughtly http://caniuse.com/#feat=websockets is a good starting point, 
and beyond 2 older version of a browser that does not support a feature, we start considering dropping support for these (exception of IE I suppose).
