### ISSUE TITLE
Codemirror 4.12 out.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7543]
We should probably update.

**Comment by Carreau** [comment]
Marking to 4.0 as some people are afraid of updates.

**Comment by damianavila** [comment]
:+1:

**Comment by minrk** [comment]
It was just a question. If there are known issues this fixes for us, that's fine, but if there aren't, I probably wouldn't bother this close to release.

**Comment by Carreau** [comment]
Superseeded by #7841
