### ISSUE TITLE
Displaying a widget using displayhook produces misaligned Out[N] prompt

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#7545]
![screenshot from 2015-01-22 16 56 44](https://cloud.githubusercontent.com/assets/327925/5867960/bd98d2d8-a257-11e4-8599-e0e331664f9b.png)

This doesn't look right. @jdfreder, can you investigate?

**Comment by minrk** [comment]
The out prompt is in the right place, but it shouldn't be drawn since there isn't actually any output.

**Comment by minrk** [comment]
Should be fixed by #7560
