### ISSUE TITLE
Code cells can end up wider than the white 'page' background

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#7546]
Made my window a bit narrower, and this happened:

![screenshot from 2015-01-22 16 59 52](https://cloud.githubusercontent.com/assets/327925/5867987/2c41751e-a258-11e4-8421-9c55544657ee.png)

**Comment by minrk** [comment]
This is a Firefox-specific bug (in Firefox, I think) where cells grow in width to match their content, ignoring the `overflow: hidden` css. The bug has been around a very long time, I think, but it's made more noticeable now that we don't have an edge-to-edge background anymore.

**Comment by damianavila** [comment]
>This is a Firefox-specific bug (in Firefox, I think) where cells grow in width to match their content, ignoring the overflow: hidden css. The bug has been around a very long time, I think, but it's made more noticeable now that we don't have an edge-to-edge background anymore.

Yes, I faced this problem with my extensions too since a long time ago... we can try to detect if we are in firefox and force the `max-width` of the Codemirror instance... how does it sound?

**Comment by minrk** [comment]
It might work. There are a lot of different values to pick for that max-width, though, as the size changes.

**Comment by damianavila** [comment]
>It might work. There are a lot of different values to pick for that max-width, though, as the size changes.

What sizes do you suggest?

**Comment by minrk** [comment]
> What sizes do you suggest?

I can't really suggest sizes, since it varies, depending on the width of the page. We would need to measure the width of the parent element, and set the max again on every window resize.

**Comment by takluyver** [comment]
I thought there was already a set of fixed sizes that it switches between automatically based on some CSS query. Can the cell be hooked into that?

**Comment by minrk** [comment]
@takluyver yes, it can. It just needs to remeasure all the elements around it, because it's the container that's resized on transition, and the cell fills the available size. If we add media queries) to the cell, we would need to make sure it measures the padding and margins of prompts, etc. at every level correctly. Plus, for continuously varied widths (screen < 768px, I believe), it would still need to measure and reset max-width on every window resize.
