### ISSUE TITLE
Header scroll out of page.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7550]
https://github.com/ipython/ipython/pull/7517 has the nice side effect that header scroll out of page.

**Comment by Carreau** [comment]
Gosh, id does it on half on my page and not the other half.... and only sometime after I click a header...

**Comment by minrk** [comment]
Every page looks correct to me. Can you be more specific? Maybe cache issue?

**Comment by Carreau** [comment]
Hum, seem to appear only with dev tools open, and adding border to everything, looks like actually the parent div oh `<html>` is scrolling. Which is impossible, unless it is a chrome UI bug that use a single html container for Page+Dev tools.

Closing as non-IPython bug then.

**Comment by minrk** [comment]
Thanks. Scared me for a bit, there.

**Comment by Carreau** [comment]
Me to.

Envoyé de mon iPhone
