### ISSUE TITLE
Editor notification

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7569]
I think we should add the notification area (at least for save) on the Editor. 
Maybe also a dirty indicator.

**Comment by damianavila** [comment]
>I think we should add the notification area (at least for save) on the Editor. 
Maybe also a dirty indicator.

Yep, probably...

**Comment by takluyver** [comment]
The notification area is already there. I added it specifically for file
saved notifications. It looks like the event that the notification widget
listens for has fallen out of sync with the event fired on save. A very
easy fix for anyone at their computer.
