### ISSUE TITLE
setting bbox_inches in print_figure_kwargs seems to have no effect

### ISSUE THREAD

**Issue by matthias-k** [ipython/ipython#7574]
Hi,

I need to create some figures for a paper, where I manually control the position of the legend. I noticed that the position of the legend depends on whether `bbox_inches='tight'` was used in savefig. Therefore I wanted to deactivate the tight layout in ipythons matplotlib interface to see the final figure in the notebook. It appeared to me that the InlineBackend from `IPython.kernel.zmq.pylab.config` is the right place to do so, however the figure still has no margin.

Here is a minimal working example

    # This will show the figure as tight
    f = plt.figure()
    f.add_axes([0.3, 0.3, 0.4, 0.4])

    # Set the default value of bbox_inches to None
    from IPython.kernel.zmq.pylab.config import InlineBackend
    ib = InlineBackend.instance()
    ib.print_figure_kwargs.update({'bbox_inches': None})

    # Now the notebook should show the figure with quite some margin,
    # but the result is the same as above
    f = plt.figure()
    f.add_axes([0.3, 0.3, 0.4, 0.4])

Best,
  Matthias

**Comment by minrk** [comment]
Many config values cannot be reliably changed after everything is initialized. That config value would have the desired effect if you had called it prior to `%matplotlib inline`. If you call `IPython.display.set_matplotlib_formats('png')` again, after changing the value, the config should propagate.

**Comment by matthias-k** [comment]
Great, that worked! Thankyou for your help!
