### ISSUE TITLE
Horizontal scroll not working

### ISSUE THREAD

**Issue by damianavila** [ipython/ipython#7582]
In Chrome Versión 39.0.2171.65 Ubuntu 14.04 (64-bit), hscroll is hidden no matter what...

![2015-01-25-130202_1366x768_scrot](https://cloud.githubusercontent.com/assets/1640669/5892076/64e9a76a-a492-11e4-84dd-d5ffd982e676.png)

I think it is related with this hack: https://github.com/ipython/ipython/blob/master/IPython/html/static/notebook/less/codemirror.less#L53-L58

**Comment by minrk** [comment]
Closed by #7583
