### ISSUE TITLE
Race problem in terminado prevents first shell prompt from being shown in terminal 

### ISSUE THREAD

**Issue by payne92** [ipython/ipython#7584]
In the Web notebook, in a terminal window, the first shell prompt is not shown (on my system).  The underlying problem is a race condition in terminado.  

See this open issue there:  https://github.com/takluyver/terminado/issues/4

I'm filing this here because we'll need a dependency version bump in IPython to catch the newer version of terminado (when the underlying issue is fixed).

**Comment by takluyver** [comment]
I just released the fix in terminado 0.4.

I don't think this needs a dependency version bump in IPython - IPython isn't incompatible with the previous release.

**Comment by payne92** [comment]
Understood.  If the problem is reported as an IPython problem (which it will likely be), we can refer folks here.

To fix this problem, upgrade to the latest version of terminado.

**Comment by takluyver** [comment]
Yep. I'm optimistic that we won't get many reports, though, because anyone installing from today onwards will get terminado 0.4 (we use `>=` rules for dependencies, we don't pin to specific versions unless we know there's a problem with later versions).
