### ISSUE TITLE
Get rid of scroll within scroll on text editor page

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#7589]
Right now both the page and code mirror area scroll on the text editor page. Scroll within scroll is a really awkward experience that we would not use unless we absolutely have to. In this case, the CM instance should scroll, but not the page.

**Comment by minrk** [comment]
This is a result of the CodeMirror div getting the wrong size by measuring the wrong elements. Should be fixed by #7593

**Comment by ellisonbg** [comment]
Thanks!

On Sun, Jan 25, 2015 at 10:40 PM, Min RK <notifications@github.com> wrote:

> This is a result of the CodeMirror div getting the wrong size by measuring
> the wrong elements. Should be fixed by #7593
> <https://github.com/ipython/ipython/pull/7593>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/7589#issuecomment-71419885>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
