### ISSUE TITLE
Lost shadow between toolbar and main notebook

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#7590]
Up to recently, there used to be a shadow at the bottom of the toolbar on the main notebook page that made it clear that the notebook slid under it. Now that shadow is gone and it is difficult to distinguish between the toolbar and notebook area (see below).

**Comment by ellisonbg** [comment]
![screen shot 2015-01-25 at 3 48 36 pm](https://cloud.githubusercontent.com/assets/27600/5893887/e331edc8-a4a9-11e4-8c00-b6dfdfa04ad1.png)

**Comment by minrk** [comment]
Fixed by #7597
