### ISSUE TITLE
Numbers in notebook cells are duplicated, incorrect

### ISSUE THREAD

**Issue by parente** [ipython/ipython#7591]
The input cell number in the UI is wrong. The `In` list of inputs kernel side is correct.

![numbers](https://cloud.githubusercontent.com/assets/153745/5894827/d3664e42-a4dc-11e4-8a22-3b4f03b6a3f5.gif)

**Comment by takluyver** [comment]
I thought we ignored attempts to execute an empty cell, so it wouldn't add a prompt number at all, but I guess not.

**Comment by minrk** [comment]
#7598 ignores empty cells in the notebook, like IPython does in run_cell.
