### ISSUE TITLE
Allow distinction between notebook directory and home directory page.

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#7607]
I think it is important to make sure that it is easy for users of a multiuser JupyterHub deployment to share notebooks. Some of the requirements:

* They can navigate up to the /home directory to see the dirs of all users. This means that the single user notebook dir would be /home.
* But have the default dashboard view be their own home directory, rather than the possibly massive /home.

To address this I propose that we add a new config variable in the single user notebook that sets the default path that is used for the dashboard in the single user server.

**Comment by dsblank** [comment]
What do you mean "share notebooks"? Do you mean: allow users to be able to open someone else's notebook for running/editing? This might might be useful for collaborative editing, but currently that sounds very dangerous.

Currently, we require users to:

* download and upload notebooks to use them; or
* use a "Copy" function that copies it into their own Incoming directory

Here is a browse of shared notebooks in Public with copy/download links (for copy, user must be logged in):

http://jupyter.cs.brynmawr.edu/hub/dblank/public/

Here is a rendered view, with Download link:

http://jupyter.cs.brynmawr.edu/hub/dblank/public/CS110%20Intro%20to%20Computing/2015/Notes/Jan26.ipynb

**Comment by ellisonbg** [comment]
A basic deployment of jupyterhub allows users to set unix permissions on
files to allow others use them:

* Open, read and run but not write
* Of full read, run, write access.

This just works out of the box and is the default simple way of sharing
content that we should support (even if many users don't enable it by
setting permissions on their files). I like the idea of the "Make a Copy"
of a read only notebook making that copy in a sort of incoming directory.
How did you implement that?



On Tue, Jan 27, 2015 at 8:42 AM, Doug Blank <notifications@github.com>
wrote:

> What do you mean "share notebooks"? Do you mean: allow users to be able to
> open someone else's notebook for running/editing? This might might be
> useful for collaborative editing, but currently that sounds very dangerous.
>
> Currently, we require users to:
>
>    - download and upload notebooks to use them; or
>    - use a "Copy" function that copies it into their own Incoming
>    directory
>
> Here is a browse of shared notebooks in Public with copy/download links
> (for copy, user must be logged in):
>
> http://jupyter.cs.brynmawr.edu/hub/dblank/public/
>
> Here is a rendered view, with Download link:
>
>
> http://jupyter.cs.brynmawr.edu/hub/dblank/public/CS110%20Intro%20to%20Computing/2015/Notes/Jan26.ipynb
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/7607#issuecomment-71680549>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
Also, I love the idea of a public folder that knows how to nbconvert
notebooks to static. How are you doing that?

On Tue, Jan 27, 2015 at 8:57 AM, Brian Granger <ellisonbg@gmail.com> wrote:

> A basic deployment of jupyterhub allows users to set unix permissions on
> files to allow others use them:
>
> * Open, read and run but not write
> * Of full read, run, write access.
>
> This just works out of the box and is the default simple way of sharing
> content that we should support (even if many users don't enable it by
> setting permissions on their files). I like the idea of the "Make a Copy"
> of a read only notebook making that copy in a sort of incoming directory.
> How did you implement that?
>
>
>
> On Tue, Jan 27, 2015 at 8:42 AM, Doug Blank <notifications@github.com>
> wrote:
>
>> What do you mean "share notebooks"? Do you mean: allow users to be able
>> to open someone else's notebook for running/editing? This might might be
>> useful for collaborative editing, but currently that sounds very dangerous.
>>
>> Currently, we require users to:
>>
>>    - download and upload notebooks to use them; or
>>    - use a "Copy" function that copies it into their own Incoming
>>    directory
>>
>> Here is a browse of shared notebooks in Public with copy/download links
>> (for copy, user must be logged in):
>>
>> http://jupyter.cs.brynmawr.edu/hub/dblank/public/
>>
>> Here is a rendered view, with Download link:
>>
>>
>> http://jupyter.cs.brynmawr.edu/hub/dblank/public/CS110%20Intro%20to%20Computing/2015/Notes/Jan26.ipynb
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ipython/ipython/issues/7607#issuecomment-71680549>.
>>
>
>
>
> --
> Brian E. Granger
> Cal Poly State University, San Luis Obispo
> @ellisonbg on Twitter and GitHub
> bgranger@calpoly.edu and ellisonbg@gmail.com
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by dsblank** [comment]
Both are seat-of-my-pants hacks at the moment:

https://github.com/dsblank/jupyter.brynmawr/blob/master/jupyterhub/publichandler.py

This is embarrassing code... but the main take-away I think is the functionality. Briefly:

* when you "Publish", it copies your notebook into your Public folder (creates it if necessary), and sets proper permissions. This is an even larger hack [1] where the javascript sends the kernel Python code to execute, using callbacks to confirm and show URL of nbconvert-view of notebook (via PublicHandler)
* PublicHandler will list files in directory, show HTML, images, and render ipynb files (with header)
* Make a copy will do similar as Publish, but copies other's notebooks into an Incoming folder. 

Next, I'm working on:

* browsing others' "published" notebooks
* a "Submit" button for turning in homework

This is all prototype code to be suggestive to a developer of *what* we want, but not *how* it should be done.

[1] - https://bitbucket.org/ipre/calico/src/master/notebooks/nbextensions/calico-publish.js

**Comment by minrk** [comment]
@ellisonbg how do you propose implementing the default path, in terms of URLs? Would `/tree/` redirect to `/tree/default/path/`? That would make listing the root directory impossible. Would `/` redirect to `/default/path/`? Would the logo link go to default or home?

I think using the default path for the logo and `/` (not `/tree/`) links should work.

**Comment by minrk** [comment]
default_url was already present, and used for the `/` redirect. In #7608, I use the same URL for the logo link. I think that should cover this one.

**Comment by takluyver** [comment]
@ellisonbg this got closed by Min's fix. Let us know if you think of anything more that should be done with this.

**Comment by ellisonbg** [comment]
Sounds like it, but let me do a few tests before closing this...

On Tue, Jan 27, 2015 at 12:10 PM, Thomas Kluyver <notifications@github.com>
wrote:

> @ellisonbg <https://github.com/ellisonbg> this got closed by Min's fix.
> Let us know if you think of anything more that should be done with this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/7607#issuecomment-71718725>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by takluyver** [comment]
It already got closed - reopen it if you think something else is needed.

**Comment by ellisonbg** [comment]
OK, sounds good.

On Tue, Jan 27, 2015 at 4:34 PM, Thomas Kluyver <notifications@github.com>
wrote:

> It already got closed - reopen it if you think something else is needed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/7607#issuecomment-71759209>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
