### ISSUE TITLE
Firefox: bad rendering of items in "Help" menu

### ISSUE THREAD

**Issue by kmike** [ipython/ipython#7612]
External links in Help menu don't render correctly for me in Firefox 35.0.1, OS X 10.10.1, IPython master:

![help](https://cloud.githubusercontent.com/assets/107893/5933751/b6a2a358-a6e6-11e4-87fc-396f98cbf6b4.png)

In Chrome they look fine (icons and captions are aligned):
![help2](https://cloud.githubusercontent.com/assets/107893/5933782/27fabd74-a6e7-11e4-9302-568b239c541c.png)

**Comment by minrk** [comment]
Should be fixed by #7618
