### ISSUE TITLE
Click on logo does not redirect to `/tree`.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7615]
Probably since https://github.com/ipython/ipython/pull/7608 , href is now `href=""`, so no way to get from notebook to dashboard...

**Comment by Carreau** [comment]
Hum, seem to heisenbug, disapear when I add some `pdb.set_traces()` to follow the `default_url`.

**Comment by minrk** [comment]
After pulling #7608, you would need to have restarted the server to get default_url to propagate. Confirmed that this isn't the case.

**Comment by Carreau** [comment]
Indeed, actually testing on the server I restarted, and not on the one which is running on a  tab I forgot which was still running fix the issues :-P
