### ISSUE TITLE
Assigning sys.stdout to a file and prompt issues? 

### ISSUE THREAD

**Issue by pik** [ipython/ipython#7621]
i.e.  `In [3]: sys.stdout = open('outlog.txt', 'w')`
I've only tested this with ipython and ipython2 on my laptop - so I don't know if it's installation specific.

**Comment by takluyver** [comment]
Are you waiting to see a new prompt? It's probably getting written to the file. If you redirect stdout, it will be pretty hard to use IPython.

**Comment by pik** [comment]
So I take it this has to do with the way IPython is creating new prompts? And is it a fixable behaviour? One can of course use `contextlib.redirect_stdout` - but often with interactive shell it's convenient to to just set sys.stdout.

**Comment by takluyver** [comment]
It's not really fixable, if I'm understanding the issue correctly. IPython uses stdout to talk to you. If you send stdout somewhere else, you won't see what IPython is saying.

**Comment by pik** [comment]
It also redirects the entire prompt i.e. for `print('ipython')`  - this is `outlog.txt`
 ^A^[[0;32m^BIn [^A^[[1;32m^B414^A^[[0;32m^B]: ^A^[[0m^Bipython

**Comment by pik** [comment]
I'm going to close, since the solution appears to be to simply use `redirect_stdout` in all cases.

**Comment by takluyver** [comment]
Yes - prompts aren't something special at that level, they get written to stdout along with your output.
