### ISSUE TITLE
CodeMirror hscrollbar blocks the pointer events

### ISSUE THREAD

**Issue by ckald** [ipython/ipython#7623]
(Originally reported in Jupyterhub repo and redirected here)

Hello,

Currently there is a bug in a Jupyterhub markup that makes it very annoying to edit long single-line cells. I encounter it in Chrome 39 (OSX). MirrorCode horizontal scrollbar element hangs in front of the cell with `min-height: 18px` and captures all pointer events. To move the cursor around the cell, I have to use a small slit at the very top.

![Proofpic](https://www.dropbox.com/s/ysnw70npgzsjk9e/Screenshot%202015-01-28%2021.47.50.png?dl=1)

Seems that removing the `min-height` attribute should fix the problem

**Comment by takluyver** [comment]
This looks similar to #5885, which was also tracked as codemirror/CodeMirror#2562. #5890 was supposed to mitigate it. @minrk , is it possible that it got re-broken somehow?

**Comment by ckald** [comment]
In my case the scrollbar is a transparent block, unlike #5885

**Comment by ckald** [comment]
Basically, this is the code I see in the devtools:

```html
<div class="CodeMirror-hscrollbar" not-content="true" style="min-height: 18px; display: block; right: 0px; left: 0px;">
    <div style="height: 100%; min-height: 1px; width: 1153.9873046875px;"></div>
</div>
```

The inner block is rendered with `height: 1px`

**Comment by minrk** [comment]
Didn't somebody revert #5890 recently? Maybe we need to put it back.

**Comment by takluyver** [comment]
Aha, yes, #7583 took it out in order to fix the lack of scrollbars when they should be there, reported as #7582. Pinging @damianavila

Aren't browsers fun?

**Comment by damianavila** [comment]
wow... this is very weird... I can not replicate the behaviour from @ckald 
I am also in Chrome 39... but in Linux...

**Comment by minrk** [comment]
Since the scrollbar is no longer hidden, I don't think this affects master. @ckald can you double check with latest master?

**Comment by minrk** [comment]
@jdfreder just ran into this. What browser, OS, window dimensions, and cell contents?

**Comment by jdfreder** [comment]
```
window.outerHeight
592
window.outerWidth
888
navigator.userAgent
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36"
```

Code cell width: 633px
Longest line width: 918px

**Comment by minrk** [comment]
@jdfreder so it's Chrome, and you have lines that exceed the width of the code cell, and you don't see a scrollbar? I see a scrollbar on the cell when I try to reproduce what you describe.

Can you reproduce it in incognito with `IPYTHONDIR=/tmp/ipython ipython notebook --port=8765`, so there's no config and no cache?

**Comment by ckald** [comment]
Scrollbars in Chrome usually are visible only when you need them. Native scrollbar behaves normally while the HTML element is not needed at all. I've just updated IPython and Jupyterhub on my instance and the problem persists

**Comment by minrk** [comment]
@ckald the screenshot shows a cell with text overflowing, which should be drawing a scrollbar, and, as far as I can tell, does on current IPython and Chrome. Can you post the output of `print(IPython.sys_info())`?

**Comment by ckald** [comment]
In my Chrome the scrollbar always fades out after a second of inactivity. But I think this has nothing to do with this HTML scrollbar that is creating problems. It should just not be there at all

{'commit_hash': '4abc89a',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/var/www/jupyter/env/lib/python3.4/site-packages/IPython',
 'ipython_version': '3.0.0-dev',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-32-generic-i686-with-Ubuntu-14.04-trusty',
 'sys_executable': '/var/www/jupyter/env/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.4.0 (default, Apr 11 2014, 13:05:18) \n[GCC 4.8.2]'}

**Comment by minrk** [comment]
> In my Chrome the scrollbar always fades out after a second of inactivity

Aha! This is the key. You have the "show scrollbar only when scrolling" behavior enabled, and I don't. If I turn that on, I can reproduce it.

This is either a problem in CodeMirror, or perhaps some of our own CSS getting in its way. Here's [more info](http://marijnhaverbeke.nl/blog/a-pathological-scrolling-model.html) on the shenanigans CodeMirror has to get up to for scrollbars to work properly. It is a frequent source of headaches.

**Comment by ckald** [comment]
Didn't know that one can disable this. Anyhow, see the issue text – you need only to remove the "min-height" declaration to fix this bug. Looks like it is added from the JS

**Comment by minrk** [comment]
> you need only to remove the "min-height" declaration to fix this bug

Since that causes the scrollbar to never show, it's trading one bug for a different one. The "dead area" appears to be a known issue in CodeMirror (codemirror/CodeMirror#811). It may still be preferable to apply another hack to trade one incorrect behavior for a less problematic incorrect behavior. I'll look into applying it in the right conditions.

**Comment by jdfreder** [comment]
> and you don't see a scrollbar? I see a scrollbar on the cell when I try to reproduce what you describe.

I don't see the scrollbar because it's OSX's magic hide&show when needed 'feature'.

**Comment by minrk** [comment]
#7660 should reverse the tradeoff CodeMirror has chosen (get click events, lose scrollbar).
