### ISSUE TITLE
Make read-only clearer.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7629]
Not to annoy user, I suggest a warning on first edit.

I got surprised using google drive where the file was read-only a few time. 
Especially since autosaved is disabled in read-only, so you don't especially notice that you might 
loose work.

**Comment by minrk** [comment]
ping @ellisonbg for ideas of more aggressive UI for indicating read-only.

**Comment by jhamrick** [comment]
:+1: I have noticed this as well with my class as we provide a read-only version of the assignments for them. I feel like just having a persistent notification that it's read-only would be good -- not too in your face, but always there so it's always easy to tell that it's read-only.

**Comment by jdfreder** [comment]
We could overlay ![screen shot 2015-02-04 at 3 13 12 pm](https://cloud.githubusercontent.com/assets/3292874/6051820/5dd993b8-ac80-11e4-93c6-25420e03573d.png) with a red ![screen shot 2015-02-04 at 3 14 52 pm](https://cloud.githubusercontent.com/assets/3292874/6051849/9465a412-ac80-11e4-8309-b2fd30a6b791.png) and stick it in the notification area. http://fortawesome.github.io/Font-Awesome/examples/#stacked

It could either show continuously, or for a 5-10s duration after a save attempt.
