### ISSUE TITLE
Select none/all in dashboard

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#7637]
I think most UIs where you can select multiple things (files, emails, etc.) provide some way to quickly select everything, or possibly everything visible, and even more importantly, to empty the selection without having to click again on each selected item. We should consider this for the file list in the dashboard.

We could also have ways to select e.g. all notebooks, all running notebooks, etc., but I think that's less important. GMail has UI for selecting groups that we could <s>shamelessly copy</s> be inspired by:

![gmail_selecting](https://cloud.githubusercontent.com/assets/327925/5980378/b6774eea-a864-11e4-894e-323c6818e580.png)

**Comment by jdfreder** [comment]
Since you entered this on Saturday I'm guessing it's not too late for an MVP?
