### ISSUE TITLE
Ctrl+C does not break and clear the current line when typing

### ISSUE THREAD

**Issue by ndunsworth** [ipython/ipython#7639]
Often times I will start typing a command in a IPython shell and instead of hitting backspace a bunch of times to clear the text I'll just hit ctrl+c to clear and get a new line.

Somewhere in the 2.x series this no longer happens.  When I hit ctrl+c a KeyboardInterrupt happens but I must manually hit "Enter" for "KeyboardInterrupt" to appear in the shell and a new line create.

I'm running mint 17 which if I installed IPython through synap it would install 1.2.1 which behaves as I would expect.

**Comment by takluyver** [comment]
I don't think I've ever seen that. It couldn't be due to some change in your terminal emulator or your shell? i.e. you can still get the expected behaviour running 1.x in the same environment?

We're just getting ready to release 3.0 beta 1 - it would be good if you can test that and see if the problem is fixed.

**Comment by ndunsworth** [comment]
I dont believe it is the shell, I have 1.2.1 and 2.x installed on the same Mint system and only 2.x produces the issue.  So yes 1.2.1 works fine in the same terminal that 2.x does not.

I just downloaded the latest checkout of the 3.x branch and the issue still persists.

**Comment by ndunsworth** [comment]
Ok so I've dug around a bit and believe I've discovered whats causing the issue.

Our machines have a PYTHONSTARTUP file which imports some basic modules often used.  It appears that pyqt is causing the issue to happen because of a Qt.QtGui.QApplication(sys.argv) call which was being executed in a rogue startup script.

Weird that 1.2 series didnt seem to mind while 2.x+ did.

Apologies for the false alarm, I'll def make sure to dbl check that PYTHONSTARTUP is unset when hunting these sort of issues down.

**Comment by takluyver** [comment]
Ah, that makes sense. I think we didn't respect $PYTHONSTARTUP until 2.x, and we got a few bug reports about odd behaviours when we started running it. Thanks for tracking down the problem.
