### ISSUE TITLE
Wrapper kernel syntax highlighting and notebook validation failing on 3.0.0-b1

### ISSUE THREAD

**Issue by lstagner** [ipython/ipython#7640]
I have come across a few issues when using a  [wrapper kernel](https://github.com/lstagner/idl_kernel) for idl.

First of all syntax highlighting is no longer working. 

Secondly I get the following error when I try to save my notebook
![idl_kernel_save_failure](https://cloud.githubusercontent.com/assets/4305891/5985319/67f4f034-a895-11e4-9c83-3faeec52d95f.png)

Everything was working fine about a month ago. 

The problem seems to be that the language_info metadata is no longer being placed in the notebook.
![language_info_metadata](https://cloud.githubusercontent.com/assets/4305891/5985364/f42b0dcc-a895-11e4-8e9d-09251d2c2009.png)

**Comment by minrk** [comment]
@lstagner what is the IPython commit version? I think this is something that was fixed recently.

    python -c 'import IPython; print(IPython.sys_info())'

**Comment by lstagner** [comment]
I am using the 3.0.0-b1 pre-release
```
{'commit_hash': u'ee6223a',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python2.7/dist-packages/IPython',
 'ipython_version': '3.0.0-b1',
 'os_name': 'posix',
 'platform': 'Linux-3.11-2-amd64-x86_64-with-LinuxMint-1-debian',
 'sys_executable': '/usr/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.5+ (default, Sep 17 2013, 15:31:50) \n[GCC 4.8.1]'}
```

**Comment by minrk** [comment]
@lstagner and did you just create this notebook, or had you created it a while ago?

**Comment by lstagner** [comment]
Just created

**Comment by minrk** [comment]
@lstagner ok, can you run this script?

```python
import json
from IPython.kernel import KernelManager
km = KernelManager(kernel_name='IDL')
km.start_kernel()
kc = km.client()
kc.kernel_info()
msg = kc.get_shell_msg()
print(json.dumps(msg['content'], indent=2))
```

**Comment by lstagner** [comment]
Here you go
```
In [1]: import json

In [2]: from IPython.kernel import KernelManager

In [3]: km = KernelManager(kernel_name='IDL')

In [4]: km.start_kernel()

In [5]: kc = km.client()

In [6]: kc.kernel_info()
[IPKernelApp] WARNING | No default profile found, history unavailable
Out[6]: 'ff956c63-c529-43c9-99a6-cbad77e595ee'

In [7]: msg = kc.get_shell_msg()

In [8]: print(json.dumps(msg['content'], indent=2))
{
  "language_info": {}, 
  "implementation": "IDL_kernel", 
  "implementation_version": "0.2", 
  "protocol_version": "5.0", 
  "banner": "GDL - GNU Data Language, Version 0.9.4\n", 
  "help_links": []
}

In [9]:
```

**Comment by minrk** [comment]
ok, then the kernel is providing an invalid kernel_info reply, and the validation is rightly complaining. language_info must have at least the 'name' and 'version' fields filled.

**Comment by lstagner** [comment]
This is the [language_info](https://github.com/lstagner/idl_kernel/blob/master/idl_kernel.py#L39) the wrapper kernel should be using

**Comment by minrk** [comment]
scratch that - only the name is absolutely necessary for the content to be valid.

**Comment by minrk** [comment]
Hm, I installed your wrapper kernel, and it showed the correct language_info. Do you perhaps have multiple versions of the kernel installed? Can you add some debug statements to your kernel, to pinpoint what's going on?

**Comment by lstagner** [comment]
Yes that was the issue. I had a different version locally installed at it was defaulting to that. It's all fine now.
