### ISSUE TITLE
early test on windows (winpython) of IPython3.0beta0

### ISSUE THREAD

**Issue by stonebig** [ipython/ipython#7648]
Hi,

Here my remarks:
- doing `pip install --pre ipython[all]' , tornado felt the need to install itself (but was already installed)
- the new behaviour `The Dashboard now lists all files, not just notebooks and directories` is a bad surprise, can you pinpoint me to the rational of this decision ? 
- the first images of my test notebook were not showing up in the notebook, but aside (not inlined ?)
- I miss the IRkernel necessary packages in windows binary form on CRAN

**Comment by takluyver** [comment]
1. Maybe it installed a newer version?
2. IPython may be used in situations where it's the only interface you have to that machine - e.g. if a teacher runs notebooks on a server for their students using Jupyterhub. For that reason, you can now edit text files in the web interface as well. Why was this a nasty surprise? Directories and notebooks should be sorted at the top of the list, so we didn't expect it to be a problem.
3. Could be a caching issue - press Ctrl-F5 a few times to refresh, or try in a different browser.
4. There are people working on it. See takluyver/IRkernel#54.

**Comment by stonebig** [comment]
1. no, but no kitten were armed in the process, just a curiosity as the rest was OK
2. it's a bad (not nasty) surprise because my default notebook is opening in a directory full of 'other things', so my insides are now exposed. I understand the rational. But hey, you mean Terminado ? does it work on windows ?
3. oke, I forgot about this kind of bugs when changing winpython versions. I will retry. thanks

**Comment by takluyver** [comment]
We've added both terminals (using Terminado) and a basic text editor based on Codemirror. The text editor should work on any platform, terminals require something Unix-y.

> no kitten were armed in the process

![](http://ball-pythons.net/gallery/files/1/8/5/8/armed_kitty.jpg)

**Comment by stonebig** [comment]
(oups! harmed kitten fight back)
In the behaviour of today, i can indeed edit what I see, but the <Newline> didn't work on the saved file.
I get , editing with notepad:
````
@echo offpython "%~dp0\..\Tools\Scripts\2to3.py" %*rem test
````
copy/ pasting on github is giving me back <Newlines>
````
@echo off
python "%~dp0\..\Tools\Scripts\2to3.py" %*
rem test
````

==> There is a <CR> or a <LF> missing for windows ?

**Comment by takluyver** [comment]
Oh, we're probably saving with Unix newlines everywhere. Almost every editor should display that correctly, even on Windows, but notepad is, naturally, an exception.

I can't decide whether or not that's something we should fix. @minrk?

**Comment by minrk** [comment]
I think we are using LF everywhere. That seems like the right behavior, these days.

**Comment by stonebig** [comment]
ok, my simple test in . bat `echo "Hello World"<LF>pause" did work.

only point remaining seems to be:

- the first images of my test notebook were not showing up in the notebook, but aside (not inlined ?)

I still have the problem with a cleared cach.
Is it still correct to use `ipython notebook --matplotlib=inline` ?

**Comment by stonebig** [comment]
another sudden strange issue:
- I lost the end of my notebook

It didn't happen yesterday on first tries. It may have happened when I tried with a second browser.
I can always have done a bad manipulation, though.

**Comment by stonebig** [comment]
`6.` I get a 
````
:0: FutureWarning: IPython widgets are experimental and may change in the future.
````

on this
````
# scikit image an Notebook interactivity
# Import matplotlib (plotting), skimage (image processing) and interact (user interfaces)
# This enables their use in the Notebook.
%matplotlib inline
from matplotlib import pyplot as plt

from skimage import data
from skimage.feature import blob_doh
from skimage.color import rgb2gray

from IPython.html.widgets import interact, fixed

# Extract the first 500px square of the Hubble Deep Field.
image = data.hubble_deep_field()[0:500, 0:500]
image_gray = rgb2gray(image)

def plot_blobs(max_sigma=30, threshold=0.1, gray=False):
    """
    Plot the image and the blobs that have been found.
    """
    blobs = blob_doh(image_gray, max_sigma=max_sigma, threshold=threshold)
    
    fig, ax = plt.subplots(figsize=(6,6))
    ax.set_title('Galaxies in the Hubble Deep Field')
    
    if gray:
        ax.imshow(image_gray, interpolation='nearest', cmap='gray_r')
        circle_color = 'red'
    else:
        ax.imshow(image, interpolation='nearest')
        circle_color = 'yellow'
    for blob in blobs:
        y, x, r = blob
        c = plt.Circle((x, y), r, color=circle_color, linewidth=2, fill=False)
        ax.add_patch(c)

# Use interact to explore the galaxy detection algorithm.
interact(plot_blobs, max_sigma=(10, 40, 2), threshold=(0.005, 0.02, 0.001));
````

how should it be rewrite ? is there a link ?

**Comment by takluyver** [comment]
Getting images inline: I see what you mean now. No, `--matplotlib` no longer works with the notebook (you should get a warning message about it in the terminal). Use `%matplotlib inline` within the notebook instead. We changed this because it was too easy to create notebooks assuming that the server was started with `--matplotlib` or `--pylab`, which didn't work as expected when other people ran them. Also, as you note, it's meaningless for non-IPython kernels.

UTF-8 BOM: It's not common practice to put a BOM before UTF-8 encoded text. Again, any decent editor should handle files without it correctly, but notepad won't. I don't think we'd consider changing what we do there.

Exe files: We show all files. There's no reliable way to tell what's text and what isn't without reading every single file, so we don't try to guess, we just show them all.

Lost the end of a notebook: Not sure how that could happen. If you find a way to reproduce it, definitely file a bug.

Warning about widgets: There's nothing to change at the moment, it's just a note of caution because we're still thinking about the design of widgets, so the API may well change a lot in the next couple of releases.

**Comment by stonebig** [comment]
ok, thanks for these explanations. I'll adapt to these changes.

I will open another issue if I can reproduce the notebook loss.

**Comment by stonebig** [comment]
I still don't understand if the old widget described in `6.` should still work as before (as it doesn't at the moment)

**Comment by stonebig** [comment]
interactivity is back to working with IPython3.0.rc1
