### ISSUE TITLE
[shift + tab] shortcut for tooltip is not working on 3.0.0-b1 [Notebook]

### ISSUE THREAD

**Issue by kikocorreoso** [ipython/ipython#7654]
Hi.

I tried to get the usual 'help tooltip' using [shift + tab] shortcut and it is not working on the 3.0.0-b1 version. If i press the shortcut some times it opens the pager (as expected) but the tooltip is not shown.

I tested that on:
<table><tbody><tr><th>Software</th><th>Version</th></tr><tr><td>Python</td><td>3.4.0 64bit [GCC 4.8.2]</td></tr><tr><td>IPython</td><td>3.0.0-b1</td></tr><tr><td>OS</td><td>Linux 3.13.0 24 generic x86_64 with LinuxMint 17 qiana</td></tr><tr><td colspan="2">Sun Feb 01 12:32:24 2015 CET</td></tr></tbody></table>

Tested on:
* FF 35.0.1
* Chrome Version 40.0.2214.93 (64-bit)

In the JS consoles I don't see any errors.

Thanks for the hard work.

**Comment by Carreau** [comment]
Hum tooltip should definitively appear, maybe not in the right position, but I guess #7655 should fix that.
Can you try with it, and/or make sure your browser cache is flushed ? (Or try in an incognito window to be sure)

**Comment by kikocorreoso** [comment]
Thanks, guys.

I think it is working fine now.
