### ISSUE TITLE
Traitlets: allow_none default value for trait types

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipython#7670]
For a number of trait types the default value for `allow_none` is `True`, such as `Enum`, `Dict`, `List`, `Instance`. 

It probably makes sense for `Type`, but as explicit is often better than implicit, could be interesting to change this before traitlets are separated out.

This would be a divergence with respect to the `traits` library though. (still I think that given the popularity of IPython, traitlets are much more used).

**Comment by takluyver** [comment]
I think I'd expect to have to specify it for Enum, at least. Less sure about the others.

I think we now consider traitlets to be an API based on traits, not a drop in replacement for traits.

**Comment by minrk** [comment]
I'd expect to have to specify it for just about anything other than Instance.

**Comment by ssanderson** [comment]
:+1: for `allow_none=False` everywhere possible.
