### ISSUE TITLE
Feature: Dict traitlet klass attribute for values

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipython#7671]
Just like `List`, `Dict` traitlet type could have an optional `klass` attribute, that would be a traitlet instance enforcing validation of values of the dict.

**Comment by takluyver** [comment]
What about the keys? E.g. to be acceptable for JSON, keys must be strings.

**Comment by SylvainCorlay** [comment]
Good point. 
Although that would require the `key_type` (or whatever we name it) to be specified for every widget attribute which might be a bit verbose. Or is there an elegant way to make it so that every traitlet such that `sync=True` has its keys validated.

**Comment by takluyver** [comment]
Maybe it's cleaner to do it as a separate traitlet type JSONableDict. Or
maybe validating that keys are strings is superfluous - getting that wrong
is not a common failure mode, I think.

**Comment by SylvainCorlay** [comment]
Yeah, especially since there are other reasons why something would not be jsonable.
