### ISSUE TITLE
Selection widget reverse lookup with numpy arrays

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipython#7673]
With selection widgets, a reverse lookup occurs when setting a new value to check whether the new valid is among the available options. This lookup uses the `==` operator, which is overloaded for numpy.array. 

We should give the possibility to the user to provide his own comparison predicate on construction of the selection widgets.

**Comment by minrk** [comment]
We use equality to trigger change events on traitelts, don't we? Doesn't this need to be fixed at the lowest traitlets level as well?

**Comment by minrk** [comment]
Apparently the equality check has been removed in underlying traitlets (which treats all numpy arrays as unequal, even identical ones).
