### ISSUE TITLE
cpaste magic error with logging history

### ISSUE THREAD

**Issue by tlmaloney** [ipython/ipython#7676]
I am having a similar problem to issue #2412 upgrading from ipython==2.1.0 to ipython==2.3.1. Here is [my setup](https://gist.github.com/tlmaloney/ba7663022678da201808), I have just one startup script that logs. And [here is the error](https://gist.github.com/tlmaloney/1cb609c12ee864166c42) I'm getting. If I remove the `05_log.py` file from the startup folder, I get no errors when using `%cpaste`.

**Comment by takluyver** [comment]
I can reproduce this with master, will work on a fix.

**Comment by takluyver** [comment]
#7678 should fix this.
