### ISSUE TITLE
DropDown widget getting cut off

### ISSUE THREAD

**Issue by desilinguist** [ipython/ipython#7677]
I am playing around with the widgets in iPython 3.0.0b1 and found that the DropDown widget gets cutoff if there aren't a sufficient number of cells underneath the cell that's displaying the widget. It's better explained using the two images attached. As you can see, in the first image, the dropdown menu is cut-off without showing all of the options. In the second image -- where another cell has been added below the current cell -- the drop down shows one more option but still gets cut off. 

For a drop down with 10-15 options, this seems like a less than ideal way to get the DropDown widget to display all its options. Isn't there a way to set the `overflow-y` property or something to get it to scroll instead?

![img1](https://cloud.githubusercontent.com/assets/161680/6029407/6cb84ac2-abbe-11e4-8117-1563fd567756.png)

![img2](https://cloud.githubusercontent.com/assets/161680/6029408/6cbb249a-abbe-11e4-9335-b9659cc9d8d5.png)

**Comment by aneeshvartakavi** [comment]
I'm facing a similar issue when the dropdown is cut off the end of the notebook (see attached screenshot). I've worked around this in the past by adding empty cells below this, but I currently have a list of 300 options and I'm trying to find a better fix. I'm running IPython Notebook 3.2.1.

![screen shot 2015-07-17 at 3 51 27 pm](https://cloud.githubusercontent.com/assets/4122476/8758691/c581a352-2c9b-11e5-9962-d6f7363b1990.png)

**Comment by jdfreder** [comment]
Hmmm, this is probably another, similar but different bug.  Unless it's a bootstrap problem.  Either way, if you could open an issue in http://github.com/ipython/ipywidgets , that would be great.

**Comment by aneeshvartakavi** [comment]
Done! For reference, https://github.com/ipython/ipywidgets/issues/94
