### ISSUE TITLE
Need for template notebook format for *IPython examples*  and *nbextension examples* 

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipython#7682]
IPython itself and typical nbextensions come with a folder of example notebooks, that are generally part of the corresponding GIT repository.

I think that there is a need for a mechanism to expose the example notebooks to the main dashboard, in such a way that opening an example notebook would first make a copy in the current folder and open that copy. 

This would help exposing new users with features, and prevent example notebooks to be modified in place. Besides, these notebooks can then be considered as doctests, since their output would not be easily modified.

**Comment by jdfreder** [comment]
I agree, this would be useful.

**Comment by SylvainCorlay** [comment]
https://github.com/jupyter/notebook/issues/332
