### ISSUE TITLE
Object '%color_info' not found!

### ISSUE THREAD

**Issue by edonyM** [ipython/ipython#7691]
I installed IPython in my Fedora21 yesterday. For a better visualization, I try syntax highlighting in my terminal console (not qtconsole). The configurations are as follows.
```py
c = get_config()
c.InteractiveShellApp.gui = 'gtk'
c.InteractiveShellApp.pylab = 'gtk'
c.TerminalIPythonApp.gui = 'gtk'
c.TerminalInteractiveShell.autoedit_syntax = True
c.TerminalInteractiveShell.color_info = True
c.TerminalInteractiveShell.colors = 'Linux'
c.TerminalInteractiveShell.autoindent = True
c.PromptManager.color_scheme = 'Linux'
```
Bad things happened. 

```py
Python 2.7.8 (default, Nov 10 2014, 08:19:18) 
Type "copyright", "credits" or "license" for more information.

IPython 2.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: %color_info
ERROR: Line magic function `%color_info` not found.

In [2]: %color_info?
Object `%color_info` not found.
```
I am not sure if my configuration is correct or my understanding about syntax highlighting in ipython is right.

**Comment by takluyver** [comment]
IPython doesn't do syntax highlighting in the terminal - you need to take control of the terminal at a lower level than we do to highlight input like that. If you want that, try [bpython](http://bpython-interpreter.org/), or [bipython](http://bipython.org/) to combine that with the goodness of IPython.

There isn't a `%color_info` magic - for some reason, our help output says that there is. We'll remove it from the help.
