### ISSUE TITLE
Reconnecting error messages with master(-ish)

### ISSUE THREAD

**Issue by michaelaye** [ipython/ipython#7697]
Version: ee6223ab74eb

My situation is that I set up a remote notebook on a server that I only can reach when in a VPN. Now, my Wifi is shaky for some reason, that's possibly how my VPN get's shaky.
So I needed to close my notebook after a VPN reconnect and the dashboard still reported it as 'running'. When I clicked on the 'running' notebook, I got this error in the console:

```python
RunTimeError: Method not supported by Web Sockets
```

Full error log here:
https://gist.github.com/23ed2e252897d96804a5

Working on OSX 10.9.5 using conda and Python 3.4

**Comment by minrk** [comment]
@michaelaye what tornado version?

**Comment by michaelaye** [comment]
I just updated today, so I can't be 100% sure, but if I had the previous `conda` version, then it was 4.0.2.

**Comment by minrk** [comment]
This should be doubly fixed by #7768

**Comment by michaelaye** [comment]
We have a proverb in German.The approximate translation would be:Doubly sewn holds better. ;) Thanks.
