### ISSUE TITLE
move %%magic highlight magic in IPython/separate codemirror mode

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7699]
The code in `cell.js` that deals with changing the highlighting when the cell starts with a magic has a few issues : 
1. It is applied on non-ipython kernels.
2. the logic is not triggered on notebook load. 

A reasonable option is to move this logic into a **real** IPython mode. 
As the magic syntax is probably use by @dsblank metakernel, it would be nice to have also a meta mode that allow to integrate it with other things beyond IPython mode.

Marking as 4.0 and sprint-friendly.

**Comment by dsblank** [comment]
There are a few popular kernels that use metakernel (matlab, octave, scheme, processing, etc.) and many others that use the % magic (metacommand) syntax. It would be great to be able to have that syntax highlighting when desired.

**Comment by minrk** [comment]
@rgbkrk you can add to `CodeCell.options_default.highlight_modes`:

```javascript
require(['notebook/js/codecell'], function (codecell) {
  codecell.CodeCell.options_default.highlight_modes['magic_sql'] = {
    reg: ["^%%sql"]
  };
});
```

<img width="870" alt="screen shot 2017-04-04 at 12 49 28" src="https://cloud.githubusercontent.com/assets/151929/24653207/2b2cdfb4-1935-11e7-9dc7-a1b85512967a.png">

Not sure of the best way to do it with an extension or some such would be.

**Comment by rgbkrk** [comment]
Thanks @minrk!

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
