### ISSUE TITLE
Issue appeared when updating  openssl to 1.0.2

### ISSUE THREAD

**Issue by davidtrem** [ipython/ipython#7702]
Might be the risk of living on the edge, but I would like to point this issue anyway.
For some reason websocket connection to the kernel failed after updating openssl to 1.0.2
on my Mac (openssl from macports). I'm using the latest ipython head.
Downgrading openssl to 1.0.1k version have fixed this issue for the time being.

**Comment by minrk** [comment]
@davidtrem thanks for bringing it up, though it's almost certainly not something for IPython to do anything about. Are you also using macports for Python? You may need to recompile Python after upgrading a library that it links to.

**Comment by Carreau** [comment]
Hi, 

This issue has been quiet for almost 2 years, and I don't think there is anything we can do. It has been marked as no-action, and I'm going to close it to attempt to reduce the number of opened issue. Feel free to reopen if needed. 

Thanks.
