### ISSUE TITLE
Tooltip appears in wrong place in Ipython 3 (beta)

### ISSUE THREAD

**Issue by rsmith31415** [ipython/ipython#7710]
I'm testing Ipython (3.0.0b1) and noticed that the tooltip appears in the wrong place:

![screenshot from 2015-02-07 18 07 20](https://cloud.githubusercontent.com/assets/599274/6094553/a0346e56-aef4-11e4-9bc9-37b7165cc3f9.png)

![screenshot from 2015-02-07 18 06 47](https://cloud.githubusercontent.com/assets/599274/6094557/aa4deeda-aef4-11e4-8dfc-2da3e552a20a.png)

In order to reproduce this issue, follow these steps:

1. Open a new notebook
2. Import any package and run that cell
3. In the same cell, add another line of code and press `shift + tab` to trigger the tooltip. 
4. The tooltip appears a few pixels above the correct place.
5. Now, create a few empty cells until reaching the bottom of the page.
6. Repeat 3, but this time, the tooltip appears a few pixels below the correct place.

This issue doesn't occur in Ipython 2. I tested in Firefox (35.0.1) and Chrome 40.0.2214.111 (64-bit) in Ubuntu 14.10.

**Comment by minrk** [comment]
Thanks for testing the beta. I believe this should be fixed by #7655. Can you check if it behaves correctly in master?

**Comment by rsmith31415** [comment]
Yes, it behaves as it should. Thanks!

By the way, it seems that the configuration files are being used across conda environments. I had another environment with a couple of kernels and those kernels were available to the new environment I created to test this in master.

**Comment by takluyver** [comment]
I think the kernels thing is as expected. Kernels are not installed inside an env unless you explicitly put them in env/share/jupyter/kernels/. The idea is that you will be able to use a kernel that runs inside an env without having to start the server in that env.

**Comment by rsmith31415** [comment]
Right. That's okay, but I was thinking that might produce errors hard to debug because I don't think it is only sharing kernels but also extensions. For example, I installed vimception a few weeks ago in Ipython 2 and now I also have a not working option to start vimception in Ipython 3.

**Comment by takluyver** [comment]
Yes, all of your IPython config lives outside of environments. I think this is fairly standard for applications. You can test with blank config by setting $IPYTHONDIR to a temporary directory.

**Comment by rsmith31415** [comment]
Nice tip. I tested it but I don't have that environmental variable and is still sharing the same configuration. Maybe something like `--ipython-dir`?

**Comment by takluyver** [comment]
If you don't have $IPYTHONDIR set, it defaults to `~/.ipython`, which is your usual config. Setting it to a temporary directory overrides it to give you blank config.

I think `--ipython-dir` works as well.

**Comment by rsmith31415** [comment]
Great. Thanks!
