### ISSUE TITLE
Weird TypeError: 'NoneType' object is not callable!

### ISSUE THREAD

**Issue by edonyM** [ipython/ipython#7711]
I try to use qt console, type command line in terminal `ipython qtconsole --profile=edony`. It works very well, but when I try to import all in numpy.
```py
In [5]: from numpy import *
In [6]: for tmp in arange(0,1,0.1):
     ...:         x = tmp**2
     ...:         print x
Out[2]: 
0
0.01
0.04
...
```

 > The numpy works normally. But when I checked about the terminal, something weird happened that I am not sure if it is a bug or something else.

```py
edony:~ edony$ ipython qtconsole --profile=edony
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/IPython/qt/console/frontend_widget.py", line 60, in highlightBlock
    super(FrontendHighlighter, self).highlightBlock(string)
  File "/usr/local/lib/python2.7/site-packages/IPython/qt/console/pygments_highlighter.py", line 115, in highlightBlock
    for token, text in self._lexer.get_tokens(string):
  File "/usr/local/lib/python2.7/site-packages/pygments/lexer.py", line 192, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "/usr/local/lib/python2.7/site-packages/IPython/qt/console/pygments_highlighter.py", line 30, in get_tokens_unprocessed
    for item in action(self, m):
TypeError: 'NoneType' object is not callable

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

```
This error loops about 13 times and my system is OSX10.10.2 and my IPython version is 2.4.0.

**Comment by takluyver** [comment]
For now, downgrade pygments to <2. I thought we back ported that fix for
2.4, but I guess not.

**Comment by minrk** [comment]
Weird, I thought we backported that, too. We can do 2.4.1 with it shortly.

**Comment by jdfreder** [comment]
Hmmm, we don't have a 2.x or backport milestone.  Just 1.3...

**Comment by takluyver** [comment]
We decided not to bother opening a new 2.5 milestone after we cut 2.4.

PR #6878, which fixed this, was milestoned for 2.4, but I think we forgot to check the milestone before we made the release. There are several others here that I think got missed:

https://github.com/ipython/ipython/pulls?q=is%3Apr+milestone%3A2.4+is%3Aclosed

**Comment by jdfreder** [comment]
I can't figure out how to modify the milestones, otherwise I would have removed 1.3.  Is there a reason it still exists?

**Comment by minrk** [comment]
I deleted the 1.3 milestone and opened 2.4.1, which we can cut once we figure out the remaining pygments-2/pyqt-5 issues.
