### ISSUE TITLE
Enhancement: Load virtualenv within IPython notebook

### ISSUE THREAD

**Issue by cjermain** [ipython/ipython#7715]
**Enhancement:**
Load virtual environment directly within IPython using a new magic keyword, which restarts the Kernel within that virtual environment

```
%virtualenv ~/path/to/activate
```

**Background:**
Virtual environments are critical for separating the system Python environment from a specific development environment. Although in the regular IPython terminal, users can easily exit the terminal and then start up their environment, this is not always the case within the IPython Notebook.

**Example use cases:**
1) The associate virtual environment that is required can be _explicitly_ defined in the notebook, which is useful when distributing a `pip` requirements.txt file that is expected to be used.
2) When using [nbopen](https://github.com/takluyver/nbopen) to automatically launch IPython Notebook servers, virtual environments could be selected on the fly after the notebook had already been running.

Comments? Suggestions?

**Comment by Carreau** [comment]
I'm not really sure all tha make sens. 

first, this would be a magic, and I'm not really sure a kernel can restart itself as another process in a reliable manner. And any way if this is done as a magic, it shoudl probably be better as a separate package. If you need some extra abstraction in IPython do do it, then we can discuss adding them.

Also the description seem like it fits well the notion of multiple kernels and the dropdown we have now in IPython 3, so I really doubt the magic would be usefull. 

So while @jdfreder tags this as wishlist, I would be inclined to say that this is covered by kernels and close.

**Comment by takluyver** [comment]
I'm inclined to agree with @Carreau - I don't think this makes sense. Both technically and in terms of the interface - specifying a path to a virtualenv won't work when someone runs the notebook on another computer. Also, there are multiple efforts in this space (virtualenvs, conda, hashdist), and we should let them explore different approaches.

You might be interested in talking to @ahmadia, who is working on ideas for recreating an appropriate hashdist environment to run a notebook in.

Closing for now, we can reopen if people disagree.

**Comment by ahmadia** [comment]
@cjermain - There's some groundwork in https://github.com/ahmadia/thisworks and I can dig out an example notebook if you're interested.  Thanks for the ping @takluyver

**Comment by cjermain** [comment]
That makes sense. Thanks for the feedback.

@ahmadia - I will check out HashDist in more detail.

**Comment by jdjoode** [comment]
It would definitely make sense to be able to specify the virtualenv in a notebook. I have notebooks spread all over my different projects. It is easier to have them together in one folder and to be able to specify the virtualenv on top.

Compare it to %matplotlib inline...

**Comment by Carreau** [comment]
you can install many kernelspec with differents "names" so you could get a dropdown to start kernels from within many venvs.

**Comment by jdjoode** [comment]
@Carreau Oh that is new to me. Do you have a link to the docs? Or is google my best shot?

**Comment by ahmadia** [comment]
@jdjoode - Just remember that the kernels need to be compatible with the front-end.  If you pick a kernel with a different API, it won't work.  It's a cool technique though and is compatible with both conda and HashDist.

**Comment by Carreau** [comment]
I'm not sure we have docs for that (yet), and how recent this is, but if you do `<PathToPython> -m IPython kernelspec install-self --name MyVenvPython` you should get a kernel name `MyVenvPython`.

You can also create the kernelspec by hand, it in not too complicated, Just duplicate an existing one and edit the `kernel.json`

**Comment by jdjoode** [comment]
Thanks!
