### ISSUE TITLE
Control+J in Notebook on Firefox on Windows

### ISSUE THREAD

**Issue by dsblank** [ipython/ipython#7716]
Student report: "I wish the that notebook didn't use Control+J in the notebook on Firefox on Windows to move cells. Firefox uses that for..." something else. 

Just providing feedback on 3.0.0-beta from the classroom.

**Comment by jdfreder** [comment]
Do you have any alternatives to suggest?  IIRC, ctrl-shift-up/down, or something similar, moves text up and down in some Windows programs.

@ellisonbg design.

**Comment by dsblank** [comment]
I will ask her.

**Comment by takluyver** [comment]
Designing shortcuts in browsers is extremely annoying. Almost everything with modifier keys is already used for something else, and detecting most of the keys is tricky with different browsers and different keyboard layouts. I think all we can safely do is the letters with or without shift.

In this case, we reserved shift+j/k for extending the selection when we make it possible to select more than one cell. So ctrl+j/k was the logical choice for moving a cell. I'm still not convinced that moving a cell (swapping it with the one above or below) makes sense as opposed to cutting and pasting it, but I was outvoted on that.

**Comment by jdfreder** [comment]
@takluyver has a good point.  I don't remember voting on the issue, but I think cutting/pasting the cell is more natural to me.  Maybe disabling the move up/down altogether would be the best solution.

**Comment by jdfreder** [comment]
Although, we probably want an undo stack for that.

**Comment by dsblank** [comment]
I don't think that move up/down needs a shortcut in any event. Maybe the first quick fix for this issue is to remove the shortcuts key bindings for move up/move down.

Also +1 to cut/paste cells. And those key bindings are ready for use here for exactly this kind of purpose.

**Comment by Carreau** [comment]
Ctrl+J seem to be open download dialog (Cmd+J on mac) 
I think the moving cell is more usefull than copy past.
But thanks for the feedback. 


Shift+J is for now availlble as it has effect only on edit mode, and moving cell only on command mode. 

Though I  can see Shift+J for selecting multiple cells later.

**Comment by jdfreder** [comment]
Added to tomorrow's agenda.

**Comment by dsblank** [comment]
Student suggestion: "Is ctrl+up an option? Or ctrl+shift+up?"

**Comment by takluyver** [comment]
IIRC, arrow keys are something that we can't detect reliably across browsers and keyboard locales, which is partly why we bind j & k in the first place. Also, @minrk said that on OS X those shortcuts do window manager things.

We discussed this this morning and came to the conclusion that we should just remove Ctrl-J and Ctrl-K from the shortcuts. People who like them can easily add them back with a bit of custom js.
