### ISSUE TITLE
Caret disappears after escaping tooltip

### ISSUE THREAD

**Issue by rsmith31415** [ipython/ipython#7723]
There is a small glitch after triggering a tooltip  in which pressing Esc to dismiss the tooltip also escapes the caret that was placed after the written text. Example:

1. Write in a cell the word "map", then press `Shift + Tab` (a tooltip will appear and the caret remains)
2. Press `Esc` ( tooltip disappears and also the caret after the word "map") 
3. Now we are in "command mode".

Ipython 2 didn't have this behavior and intuitively makes sense to press  `Esc` to remove the tooltip and return to the text.

This is happening in the master branch using Chrome (40.0.2214.111) and Firefox (35.0.1).

**Comment by mathieu1** [comment]
Looks like undesired behavior to me. I certainly wouldn't want 'Esc' to go to command mode on closing the tab-completion list (which it thankfully doesn't). Proposed a fix in #7728
