### ISSUE TITLE
Long text overflows in Firefox

### ISSUE THREAD

**Issue by rsmith31415** [ipython/ipython#7724]
I'm sure this has been reported before but I can't find the exact same issue.

When you write a very long text in a cell in the Ipython Notebook  (3 dev and 2.3.1) in Firefox (Firefox 35.0.1 in Ubuntu 14.10), this happens:

![screenshot from 2015-02-09 22 14 01](https://cloud.githubusercontent.com/assets/599274/6121475/76c015a0-b0a9-11e4-81b1-2a27db9c3f5d.png)

In Chrome, it works as it should:

![screenshot from 2015-02-09 22 12 08](https://cloud.githubusercontent.com/assets/599274/6121478/855a0b34-b0a9-11e4-8228-7313e1bc398e.png)

This is similar to the output given by rossant in the issue #5695, although in that case, it is the output that overflows.

**Comment by minrk** [comment]
Weird, I'm sure this has been reported as well. It's been a known issue for years, now, and it's a bug in Firefox that prevents the content from obeying its CSS overflow property.

**Comment by takluyver** [comment]
Yep, I reported it as #7546. Closing as duplicate.

**Comment by rsmith31415** [comment]
Are you sure this is a Firefox bug? Did anyone report it already? 

I tried to set the div with class `inner_cell` to `overflow: hidden;` and that fixed it. I did the same in Chrome and didn't see any difference at all.

![screenshot from 2015-02-10 17 10 16](https://cloud.githubusercontent.com/assets/599274/6138550/bc5f9ba0-b147-11e4-8080-f8bccc0e9fc8.png)

**Comment by takluyver** [comment]
Just tried the same on my machine: it correctly hides the extra content, but doesn't show the scrollbar. `overflow-x: scroll` shows scrollbars on every cell.

I think the `overflow-x: hidden` behaviour is better than the current one in Firefox, and it doesn't appear to have any adverse effect in Chrome. @minrk, @jdfreder , do you see any reason that we shouldn't set `overflow-x: hidden` on `div.inner_cell`?

**Comment by rsmith31415** [comment]
Did you click on the cell after you made the change? After clicking, the horizontal scrollbar appears.

**Comment by minrk** [comment]
@rsmith31415 that doesn't appear to be the case for me, and it would be quite surprising for an `overflow-x: hidden` to result in a visible scrollbar, since it's specifically telling the browser not to show one.

**Comment by rsmith31415** [comment]
@minrk Are you testing in Ipython 3, right? I was testing in Ipython 2.3.1. Maybe there was a change in Ipython 3 that is breaking this fix. I think the idea is to add `overflow: hidden;` to the parent of the element to prevent the text from exceeding its container but allowing its children to create scrollbars.

**Comment by takluyver** [comment]
I do see the scrollbar appear after clicking on the cell. I bet it's actually appearing on some inner element, possibly due to something Codemirror is doing.

**Comment by rsmith31415** [comment]
I tested this in Ipython 3 and adding or removing something in the cell is needed. After that, the scrollbars appears:

![screenshot from 2015-02-10 17 47 57](https://cloud.githubusercontent.com/assets/599274/6139080/30155cd8-b14d-11e4-97f6-b01a2f92ef54.png)

I think Codemirror is adding CSS styling via Javascript. That might be the reason why the vertical scrollbar is hidden by default.

**Comment by minrk** [comment]
@rsmith31415 it's a bug because the inner_cell shouldn't be overflowing at all. The inner CodeMirror element should be the one fixing its width and scrolling, which it does on other browsers (it can also be backward - maybe we are relying on buggy behavior in other browsers, where FF is the only one doing it right). It probably makes sense to set `overflow-x` to `hidden` or `auto` on div.inner_cell as a workaround. It doesn't fix the behavior, since it's still wrong (scrolling the wrong element), but it's a reasonable mitigation.

**Comment by takluyver** [comment]
Do you (@rsmith31415) want to open a PR for it?

**Comment by rsmith31415** [comment]
@minrk Certainly this shouldn't be happening. I think Firefox is causing the issue and maybe CodeMirror is not helping by changing things on the fly. It would be nice to isolate this issue in a simple example (without CodeMirror) to understand better what is happening. Keep in mind that  `overflow: auto;` depends on the user agent according to Mozilla's [documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow), so we have to careful there.

@takluyver I think it is better if you or minrk make a pull request for this since you guys have a much better understanding of the code base and this can be tricky.

Does anyone is able to test this workaround on Windows? 

By the way, I just noticed you don't support IE (that is a relief).

**Comment by minrk** [comment]
@rsmith31415 no worries, I'll open a PR applying this CSS on Firefox.

**Comment by takluyver** [comment]
ah, I was just about to do so as well. I'll let you do it, since you're more familiar with CSS.

**Comment by minrk** [comment]
#7734
