### ISSUE TITLE
error in function defintion not shown

### ISSUE THREAD

**Issue by JanSchulz** [ipython/ipython#7731]
A cell with this (note the missing comma) will not raise an error when run:

```
def fix( a, b c):
    pass
```

I would expect that some kind of "not valid python" error is raised.

This is ipython master as of b29264c

**Comment by takluyver** [comment]
I see a syntax error as expected. If you've just upgraded, you may have JS caching issues. Hit Ctrl-F5 a few times, or open it in another browser.

**Comment by minrk** [comment]
Since that's IPython from a couple of weeks ago, this is probably #7624, which is fixed in master.

**Comment by JanSchulz** [comment]
Yep, seems to be fixed by the latest master. Sorry, should have checked that.
