### ISSUE TITLE
ES6 and other build tools

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7735]
Meta issue to consider ES6, and other build tools for javascript.
- http://6to5.org/  seem to be use by atom which have a `"use 6to5"` similar to `"use strict"`.

**Comment by takluyver** [comment]
You know, if we dropped support for everything besides Firefox until they all caught up, we could start using default function arguments and `function (foo, ...args)` today, with no polyfill. :wink: 

Or if we only supported IE technical preview with experimental features enabled, we could start using ES6 classes.

Source: http://kangax.github.io/compat-table/es6/
