### ISSUE TITLE
Getting PID of ipython notebook server started with POpen gives wrong PID

### ISSUE THREAD

**Issue by mangecoeur** [ipython/ipython#7738]
The ipython notebook make life difficult for you if you want to open it as a subprocess from another script because the PID of the process != the PID of the process (as checked with `ps`). This is true using POpen as well as nodejs child_process. A browse of StackOverflow suggests that not using `shell=True` should prevent this - this is wrong, as you will see if you run the example below (no shell arg needed).

Example in python(3):

```python
import subprocess
args = ['ipython', 'notebook', '--no-browser']
with subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT) as proc:
    print(proc.pid)
```

The PID will be 1 less than the PID of the actual server. (i.e. real PID = returned pid +1).

You need to know the PID if you then want to read the server info from the `~/.ipython/profile_default/securty/nbserver-<pid>.json` file. It's frustrating because there's no way to ask the process directly to give you that information (port, security, etc) that you need for embedding.

**Comment by takluyver** [comment]
I can't replicate this on Linux - the PIDs are exactly what they appear as. No idea what could be causing the issue.

**Comment by mangecoeur** [comment]
I'm seeing this on OSX with ipython 2.3. It seems if I use the dev version (Ipython3) I don't get the same issue...

**Comment by takluyver** [comment]
I've just checked with the current 2.x branch, which was just released as 2.4.1, and it's still working as I expect.

**Comment by mangecoeur** [comment]
It does seem to be working fine on 2.4.1 for me also, installed via pip. I'm wondering if it's a result of using the anaconda python dist version of 2.3...

**Comment by takluyver** [comment]
It's possible that Anaconda's `ipython` is a wrapper script that does something else and then launches IPython as a subprocess.

**Comment by Carreau** [comment]
> It's possible that Anaconda's ipython is a wrapper script that does something else and then launches IPython as a subprocess.

[Probably, ](https://github.com/conda/conda-recipes/blob/master/ipython-notebook/ipython_mac.command) that would explain the +1 difference.

**Comment by minrk** [comment]
Closing, as @Carreau pointed out that it's anaconda's wrapper that's launching the subprocess.
