### ISSUE TITLE
Notebook: Long delay before closing/server stop on Windows

### ISSUE THREAD

**Issue by s9w** [ipython/ipython#7741]
I'm on Windows with ipython 2.4.0

The console says "Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).". But doing so takes over a minute on my machine to actually exit! Just measured and it was 102 seconds.

It's faster to just kill python.exe. Which is ugly and can't be the expected behavior. This is not new for me, but I couldn't find related issues, so what's up with that?

**Comment by takluyver** [comment]
If you have a lot of kernels running with a lot of things in memory, it might take a while to clean them all up, but 100 seconds seems extreme. How many kernels did it need to shut down?

If the problem is with a large number of kernels, it should be much better in IPython 3. IPython 2 sends a shutdown message to each kernel and waited for it to exit before moving on to the next. IPython 3 asks all the kernels to shut down and then waits for them (#5764).

**Comment by s9w** [comment]
Only one, and a fast machine - that's the thing!

**Comment by takluyver** [comment]
And is this the case even if you haven't run anything in that kernel?

@minrk, any ideas? I know how much you enjoy debugging process issues on Windows ;-)

**Comment by s9w** [comment]
Yes, even with "ipython notebook" and immediately closing after.

**Comment by takluyver** [comment]
If you do that, it should have *no* kernels to shut down, which is even more mystifying. A kernel is only started when you click open a notebook file.

**Comment by minrk** [comment]
The inner loop is actually uninterruptible on Windows. It will catch the interrupt the first time an event is processed, so if your browser is open it should exit promptly. We can add a no-op callback at 5-10 second intervals to put an upper limit on the delay.

**Comment by takluyver** [comment]
We should probably add that callback.

Perhaps we should also use the tornado asyncio wrapper on Windows when it's available. I would expect that that is not uninterruptible.

**Comment by minrk** [comment]
> Perhaps we should also use the tornado asyncio wrapper on Windows

I don't think we can. It would need to use the same uninterruptible zmq poll as the inner loop. Plus, tornado can only be used with the SelectorEventLoop. It is not compatible with the Proactor one that may have better behavior.

**Comment by takluyver** [comment]
@s9w If you have time, can you give #7748 a try?

**Comment by s9w** [comment]
Yes, that works! Thanks

**Comment by Carreau** [comment]
> Yes, that works! Thanks

Great, merging #7748 then
