### ISSUE TITLE
how do I convert a "pure" Ijulia notebook v3 in a notebook v4 'Julia' ?

### ISSUE THREAD

**Issue by stonebig** [ipython/ipython#7742]
Hi,
I'm on ipython3.0b1, with kernels python3 and Julia.
I want to play with this notebook "ijulia-made":
http://nbviewer.ipython.org/github/JuliaLang/Interact.jl/blob/master/doc/notebooks/02-Widgets%20Overview.ipynb

But I don't see how to pre-convert it in "v04" 'Julia' with the Ipython GUI....
 
==> it opens in Python3 kernel ... shame.

(it doesn't seem to work if I copy/paste by hand, maybe Ijulia interact is not compatible with Ipython3)

**Comment by takluyver** [comment]
Open it and go to the kernel menu, and select the Julia kernel. That should
change the kernel, the highlighting, and the notebook metadata.

**Comment by stonebig** [comment]
aouh ! so simple. thanks !

**Comment by stonebig** [comment]
still, i'm worried Julia 'Interact' module doesn't work anymore. Could you have a look on the given notebook ?

**Comment by Carreau** [comment]
Julia notebooks do have `language=julia` in their metadata. I thought we were migrating that ?

**Comment by takluyver** [comment]
It should be easy to write a script to do so, but I don't think we have done that.

@stonebig widgets may have changed quite a bit, possibly IJulia will need to update things for that to work. @jdfreder should be able to give more info.

**Comment by Carreau** [comment]
> It should be easy to write a script to do so, but I don't think we have done that.

I was thinking it was either in JS, or in Nbformat.
We could maybe use the dialog when there is no kernelspec matching to prompt for a kernel ?

**Comment by jdfreder** [comment]
> @jdfreder should be able to give more info.

https://github.com/ipython/ipython/wiki/IPython-3.0-comm-and-widget-migration-document

**Comment by Carreau** [comment]
Can you try #7747 for automatically recognizing Julia notebooks ?

**Comment by minrk** [comment]
closed by #7747
