### ISSUE TITLE
right click in notebook jumps to the first cell

### ISSUE THREAD

**Issue by JanSchulz** [ipython/ipython#7745]
In a long notebook scroll down and then use a right click -> The notebook scrolls to the first cell. It doesn't matter if the cell is highlighted (via left click) or not.

This is a ipython notebook from master this morning.

[I kind of expect to find the "run all cells above" command under a right click... #6313]

**Comment by Carreau** [comment]
Hum.. can't seem to reproduce whereever I right click. 
Can you give a bit more info on OS, browser, version of IPython ?

**Comment by takluyver** [comment]
And hit refresh a few times in case it's a JS caching issue.

**Comment by JanSchulz** [comment]
Win7, chrome latest, conda environment (installed dependencies via `conda install ipython-notebook` and then removed ipython(ipython-notebook) again), installed ipython from a local git checkout of master via `python setup.py develop`. Installed all of the rest of the requirements via pip until ipython notebook worked. 

My local `~\.ipython` was just cleaned (removed `nbextensions` directory and my profile_default\static\custom\ dir). Deleted cached data in chrome. Restarted the notebook server and loaded the notebook and reloaded it a few times to make sure. 

It still happens :-(

**Comment by JanSchulz** [comment]
Ok, found a way to find the problem: https://developer.chrome.com/devtools/docs/javascript-debugging#pause-on-next-statement -> activate the mouse -> contextmenu breakpoint

The scrolling happend in line 3609 in codemirror.js: `cm.display.input.focus();`. I couldn't step into that function, so no idea whats happening here :-(

**Comment by JanSchulz** [comment]
Ok, with the latest ipython notebook from today (0889b336e3a1412c7a83e79b4d7d4106a43ed388) this doesn't happen anymore. Thanks!

**Comment by Carreau** [comment]
Great, closing then !
