### ISSUE TITLE
stupid question about using IJulia natively 

### ISSUE THREAD

**Issue by stonebig** [ipython/ipython#7749]
as we can't use `%matplotlib inline`
how do we do to have a graphic `inline` when trying the native example ?
````
using PyCall
@pyimport matplotlib.pyplot as plt
@pyimport numpy as np
# Note how we mix numpy and julia:
t = linspace(0, 2*pi, 1000); # use the julia linspace
s = sin(3 * t + 4 * np.cos(2 * t)); # use the numpy cosine and julia sine

fig = plt.gcf()  # **** WATCH THIS VARIABLE ****
plt.plot(t, s, color="red", linewidth=2.0, linestyle="--")
plt.show()
````

**Comment by Carreau** [comment]
The way matplotlib inline figures works is really specific to matplotlib and IPython where we have some specific hook to render things inline. I don't know if/wether it can work across the Python-Julia fence, put it's probably a non-trivial piece of work. Having matplotlib patched to without IPython having knowledge of matplotlib would be great, and would probably simplify the things. 

On pure julia kernels, when the object returned is a Fig Object you can always a hook that gets its PNG repr and display it using the standard julia `show(::mime, object)` way.

**Comment by rsmith31415** [comment]
@stonebig You can't use `%matplotlib inline` but it is not needed. If  you want to plot inline simply use `PyPlot` (sample code taken from [IJulia Preview](http://nbviewer.ipython.org/url/jdj.mit.edu/~stevenj/IJulia%20Preview.ipynb)):

![screenshot from 2015-02-11 16 57 55](https://cloud.githubusercontent.com/assets/599274/6158363/2b0349ea-b20f-11e4-8a5b-8bd4d77d2d2b.png)

If your purpose is to combine calls from Python and Julia, load `PyPlot` before `PyCall` and use matplotlib as you did: 

![screenshot from 2015-02-11 17 01 43](https://cloud.githubusercontent.com/assets/599274/6158409/b1aa53e4-b20f-11e4-9ce3-a70f7331cd98.png)

**Comment by stonebig** [comment]
ah, Excellent !  Thank you  @rsmith31415 
My purpose was to not ship Gadfly with Winpython, as it's too big, but still be able to show eye-candy.

By the way, I didn't find a similar example for mandelbrot (in Ijulia+Pyplot). Do you have one ?

**Comment by rsmith31415** [comment]
@stonebig  Take a look [here](http://nbviewer.ipython.org/gist/macd/128ca830e8f3819985a2)

**Comment by stonebig** [comment]
Thanks again, I really didn't know how to search in the Julia world, loosing hours.
By any chance, do you know how to do a little smaller output images ?

**Comment by rsmith31415** [comment]
You can ask all these questions in StackOverflow because I think, this is off-topic.

    using PyPlot
    using PyCall
    @pyimport matplotlib.pyplot as plt
    plt.subplots(figsize=(3,3))
    plt.plot([1,2,3,4,5],[2,3,4,5,6])
