### ISSUE TITLE
Missing feature to navigate to parent directory

### ISSUE THREAD

**Issue by rsmith31415** [ipython/ipython#7751]
There was a very useful feature that allowed you to navigate folders using a link to move to the parent directory. However, this feature is missing in the latest versions of the Ipython notebook (3 and 2.3.1)

Actually, [this](https://github.com/ipython/ipython/pull/7681) recent issue shows several images in which there is a folder followed by two dots:

![image from #7681](https://cloud.githubusercontent.com/assets/7703352/6042140/bec6bc62-ac82-11e4-9446-d70122b871fa.png)

Why am I not seeing that in the master branch?

UPDATE:

It seems that the folder followed by dots does appear after clicking on a directory, but I'd like to able to navigate parent folders with respect to the location in which `ipython notebook` is called.

**Comment by Carreau** [comment]
I'd like to able to navigate parent folders with respect to the location in which ipython notebook is called.

No that won't be possible for security issues. You could start the notebook in `/` but have the default dashboard be something else. But by design navigating up `--notebook-dir` (default to `.`) and going into folders that start with `.` is not possible.

**Comment by rsmith31415** [comment]
Good to know. Thanks!

**Comment by kammeyer** [comment]
What's the security issue here?  The python interpreter is not sandboxed, and so once inside a notebook, the entire filesystem is accessible, even to the extent of os.system("ipython notebook --notebook-dir /")

**Comment by Carreau** [comment]
The kernel might not be python, nor on the same machine than the server, nor do you need a running kernel to use server API(s).


Envoyé de mon iPhone

**Comment by zbeekman** [comment]
So can I have a link in an index.ipynb that points to the folder containing this file? If so how?

**Comment by Carreau** [comment]
> So can I have a link in an index.ipynb that points to the folder containing this file? If so how?

In a markdown cell:

```
[current dir](.)
```

**Comment by zbeekman** [comment]
Cheers!
