### ISSUE TITLE
`Ctrl-a` keybinding should go to term.js terminal

### ISSUE THREAD

**Issue by fperez** [ipython/ipython#7753]
The `C-a` keybinding is the standard bash 'go to start of line' keybinding.  I don't know how easy it is to make sure we redirect it so the terminal (in the notebook environment) sees it. I suspect it's being captured by the browser as 'select all'.

I'm flagging this as 3.0 as I think it's a big usability issue. BUT, if it's hard to do, let's punt and retarget for later. I only think we should fix now if the fix is very straightforward.

ps - we probably should have a label for the notebook terminal component.  Not sure what we want to name it (same for the notebook editor)

**Comment by minrk** [comment]
I looked into this a while ago, and thought it was a bug in term.js we couldn't work around. Apparently it's an optional behavior that we can just turn off. Should be fixed by #7754.
