### ISSUE TITLE
Dropdowns in cell toolbar - styling wrong

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#7758]
The text of the selected option is half hidden. This only affects the cell toolbars - the dropdowns in the main toolbar look OK.

![slide_type_dropdown](https://cloud.githubusercontent.com/assets/327925/6159877/c2715168-b210-11e4-9180-96b80ff325f2.png)

Firefox & Linux

**Comment by rsmith31415** [comment]
It is also happening in Chrome. The `select` element seems to have a bit of extra padding (5px). A reduction of 3px seems to work in Firefox and Chrome:

![screenshot from 2015-02-11 21 06 38](https://cloud.githubusercontent.com/assets/599274/6161132/0a5a8686-b232-11e4-8e58-557b9a21c49a.png)

![screenshot from 2015-02-11 21 09 01](https://cloud.githubusercontent.com/assets/599274/6161145/3b67557e-b232-11e4-99b6-7937022b7439.png)

By the way, there are a lot styles being overridden in that section of the page and mixing pixels with ems is going to cause some issues.

**Comment by takluyver** [comment]
Thanks for digging into it. I expect Min will make a PR before I get to my
computer.
