### ISSUE TITLE
More useful presentation of inspection info

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#7759]
When you first summon a tooltip on a function, before you hit shift-tab enough times to expand it, the signature is far enough down to be out of view. Instead you see type, repr and path to its module, none of which are especially useful.

This is a reminder to myself to re-evaluate the presentation of this information, re-order it and possibly eliminate some fields. I've been meaning to do this for years.

**Comment by Carreau** [comment]
@stefanv would be pleased as he said tooltip was not heigh enough.
