### ISSUE TITLE
Parameterized traitlets and default value validation

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipython#7760]
When using a List traitlet with validated elements, the default value of the elements is validated, like in this example:

```Python
from IPython.utils.traitlets import *

class Bar():
    pass

class Foo(HasTraits):
    bars = List(Instance(Bar, allow_none=False))

foo = Foo()
```
which yields a `TraitError` because the default value, None, is invalid. 

A fix would be to do `bars = List(Instance(Bar, tuple(), allow_none=False))`, i.e. to create a  default value. But somehow, I think that there should not be a need to instantiate a default value that is never going to be used!

@minrk should the default value be validated when the traitlet is to be used in a "template" trait like List?

**Comment by SylvainCorlay** [comment]
Btw, it seems that this validation was not happening until `IPython 2.2`.

**Comment by minrk** [comment]
Hm,  it seems like the default value shouldn't be generated at all, but there may be too many things going on right now for me to have an accurate picture in my head. I will try to think about this more carefully in the morning. Thanks for catching it.

**Comment by SylvainCorlay** [comment]
OK, this was introduced in f68b176, where the `instance_init` of the child trait was added in the `instance_ init` of the container.

**Comment by ssanderson** [comment]
I'd assume that the right thing here would be for the default value of `List(Instance, ...)` to just be an empty list, right?

**Comment by SylvainCorlay** [comment]
It is. I am talking about the default value of Instance.
