### ISSUE TITLE
No HTML Title in Print Preview

### ISSUE THREAD

**Issue by tingtron** [ipython/ipython#7761]
IPython v 2.2.0.
In Notebook web interface, selecting **File / Print Preview** shows page:
  `.../nbconvert/html/<File Name>.ipynb?download=false`
However, the HTML **title** of the page is "Notebook".
Expected: title "*File Name*"

Compare: when the same output is obtained from command line:
   `ipython nbconvert <File Name>.ipynb`
the resulting HTML has correct title: "*File Name*".

**The cause:**
The IPython handler (`IPython/html/nbconvert/handlers.py`) fails to pass 
   `resources['metadata']['name'] = notebook_name`
when calling `exporter.from_notebook_node`

Compare method `Exporter.from_filename` in
   `IPython\nbconvert\exporters\exporter.py`

**Comment by takluyver** [comment]
If it's a simple fix, please do open a PR for it. Thanks!

**Comment by takluyver** [comment]
This is working correctly in master - we're just approaching 3.0, and we're not planning any more 2.x releases, so I'm actually going to close this.

**Comment by tingtron** [comment]
I should've checked the latest master. It's been addressed for #7360. Thank you!
