### ISSUE TITLE
No indication when connection is closed cleanly

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#7767]
If the server-side closes the websocket connection cleanly (without errors), there is no indication in the notebook UI that the connection has been lost. This is because there's a check in the event handler for whether it was an error, and does nothing, if not.

This can be reproduced by adding a `self.close` in the websocket handler that fires some time after the connection is estabished.

Marking as 3.1

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
