### ISSUE TITLE
Trait default values are validated even when not ever used

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipython#7769]
```Python
from IPython.utils.traitlets import *

class Foo(HasTraits):
    bar = Type(allow_none=False)

foo = Foo(bar=int)
```
yields `The 'bar' trait of a Foo instance must be a subclass of object, but a value of type 'NoneType' (i.e. None) was specified.`

The default value is validated while it is not needed.

**Comment by SylvainCorlay** [comment]
Unlike the similar #7760, this has been here all along and is really part of how traitlets work since the beginning. 

Is it a bug or a feature?

**Comment by minrk** [comment]
This has bothered me for a while - that default values are computed even when unused. I think it's a bug, but it's been around since day 1.

**Comment by takluyver** [comment]
I thought we fixed that? It used to calculate the default value when you set another value, so that `_foo_changed` callbacks could be passed the 'previous' value, but I changed that in #7041.

**Comment by takluyver** [comment]
Ah, I guess that was only dynamically generated default values.

**Comment by SylvainCorlay** [comment]
@takluyver, yes I was looking into the code of #7041.
