### ISSUE TITLE
running remote https nbserver with master

### ISSUE THREAD

**Issue by michaelaye** [ipython/ipython#7772]
I'm trying to run notebooks via a remote VPN'ed nbserver on my iPad. The dashboard starts fine, the notebook loads fine as well, but th connection to the kernl fails.
I see several SSL related errors in the terminal, could this be from the self-signed certificate? Somehow I thought in that case I would not even reach the dashboard, that it jus blocks the connection to the kernel is new to me.
Version: Master
Sorry for the incomplete log, I don't have a computer right now, all I could do is this screenshot with the iPad. Also I can't seem to scroll up in my SSH app.

![image](https://cloud.githubusercontent.com/assets/69774/6181860/fcf3562e-b2f6-11e4-8e26-9d5a31adce40.jpg)

**Comment by Carreau** [comment]
I agree that you should not have reached the Dashboard. Unless it id due to websockets that are openned only on non-dashboard pages.

**Comment by Carreau** [comment]
Can you still reproduce this ? Or do we close ?

**Comment by michaelaye** [comment]
Not happening currently, so closing.

**Comment by Carreau** [comment]
Thanks !
