### ISSUE TITLE
User manager(roles control) in ipython notebook

### ISSUE THREAD

**Issue by Anne623** [ipython/ipython#7773]
Hi, All, I use ipython notebook with public server, set password for server. 

Otherwise,  I want to new a user(need password) for ipython notebook server which login page can input user name. each user has owner notebook, Dose IPython notebook support this? Like user manager, or roles control.

**Comment by minrk** [comment]
The notebook server is a single-user application. You may be interested in [JupyterHub](https://github.com/jupyter/jupyterhub), which allows a multi-user deployment of notebook servers.
