### ISSUE TITLE
Alias mpl nbagg 

### ISSUE THREAD

**Issue by tacaswell** [ipython/ipython#7774]
Talking to @danielballan today he pointed out that nbagg, while accurate and making lots of sense to mpl developers, is not the clearest our most user friendly name.  

Would it make sense to provide an alias in the mpl related ipython magic to a more suitable name? Would it be possible to get that alias in for 3.0 at this late date?

**Comment by takluyver** [comment]
Possibly. Any thoughts on what to call it?

**Comment by Carreau** [comment]
`%matplotlib notebook` ?

**Comment by danielballan** [comment]
+1 for  `%matplotlib notebook`

**Comment by minrk** [comment]
Since we have `qt` for `QtAgg`, it makes sense to me for `notebook` to be `nbagg` (`nb` would be a bit terse, I think). Any objections? @fperez or @ellisonbg?

**Comment by fperez** [comment]
+1 on `notebook`. This is small enough that it's OK this late in the game: b/c I suspect it will get broad usage and 3.x will be a long-lived series, I'd rather have it in now.

**Comment by minrk** [comment]
I just saw that nbagg support was included in 2.4. Should we keep `nbagg` as an alias for compatibility, backport `notebook` to 2.4.2, just switch to `notebook`, or something else? 2.4 has been out for two weeks.

**Comment by ellisonbg** [comment]
+1

**Comment by takluyver** [comment]
I'd leave nbagg for compatibility and just add notebook as an alias.

**Comment by minrk** [comment]
Sounds good.

**Comment by minrk** [comment]
#7778

**Comment by tacaswell** [comment]
Thanks!
