### ISSUE TITLE
vim mode while typing on IPython - ipyrc | ipy_user_conf.py?

### ISSUE THREAD

**Issue by arnaldorusso** [ipython/ipython#7775]
Hi,
Is there any configuration of ipyrc to ignore some keys?
When I'm inside ipython console, if I type <esc> key it disappear every sentence that I have wrote.
How can I disable this behavior?
If *vim-mode* is a feature, I could not find in the web. Is there any *vim mode* inside ipython console?
I use a lot the vim-ipython, but almost the time, when I have connected my vim with ipython console, I go through the ipython console to check something and many mistakes I do: including jjjjj, kkkk, or even deleting after pressing <esc> key.
Thanks again for all IPython dev team! It's really awesome to use IPython daily!

**Comment by Carreau** [comment]
I dont' think we have any specific keybinding.
IPython terminal just use readline, so if you have any readline configuration then you should look there.

What OS/terminal emulator ?

**Comment by arnaldorusso** [comment]
Hi @Carreau Thanks for reply.
How should I set any *readline* configuration?

I'm using Debian/bash terminal

**Comment by minrk** [comment]
readline is configured with [inputrc](https://www.gnu.org/software/bash/manual/html_node/Readline-Init-File.html).
