### ISSUE TITLE
In-notebook terminal rendering of certain whole-screen applications (like mc) is broken.

### ISSUE THREAD

**Issue by fperez** [ipython/ipython#7782]
This is related to #7242, but not quite fixed by that PR...

On Chrome on Linux, if I set the Consolas font to being my monospaced font, when running mc (Midnight Commander) in the in-notebook terminal, the computation of the column width must be wrong, b/c the page misrenders:

![image](https://cloud.githubusercontent.com/assets/57394/6197637/d26ca638-b39d-11e4-8445-12a68b919157.png)

This is even more evident when an error box is drawn:

![image](https://cloud.githubusercontent.com/assets/57394/6197640/db82257c-b39d-11e4-85df-2279bee71cf8.png)

Checking the value of `Terminal.brokenBold` in the JS Console returns `true` with Consolas. Yet, the fix in #7242 isn't helping here.

For reference, switching to another monospaced font, such as DejaVu Sans Mono, fixes the problem. So at least there's a workaround.

But even if the bug is in Consolas, it would be nice if we could make it work correctly (if viable).  Regular terminal emulators don't exhibit this behavior.  In as much as possible, we want our terminal to match a 'real' terminal 100%.

Marking this for 3.1, as it's fairly obscure and there's an easy workaround for now.

**Comment by takluyver** [comment]
I guess 'real' terminal emulators draw each character at a calculated position. As @Carreau mentioned on gitter, doing that in termjs would involve wrapping each character in its own div.

Shouldn't we file this against term.js? It seems like setting a bad precedent to file bugs in termjs on IPython.

**Comment by fperez** [comment]
Certainly! I wasn't completely sure where the bug lied, which is why I filed it here. 

You understand the details better (having actually worked with term.js). Feel free to close it here and reopen it on term.js.  That way it's documented for us, even if we can't actually do anything about it.

**Comment by takluyver** [comment]
As far as I'm concerned, all the rendering and interaction with the terminal is done by term.js. We just put it on a page with a bit of CSS, and pass messages between it and a websocket.

**Comment by fperez** [comment]
Reported as chjj/term.js#60, closing here.
