### ISSUE TITLE
kernels.js warning.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7783]
Not sure if we did, but I don't think we flag the kernels that have a kernel.js and prevent further switching.
We said we should.

Marking as 3.1 but should at least be in docs.

**Comment by minrk** [comment]
I think we just log a warning at this point. If I recall correctly, we said we would force refresh on kernel change after loading kernel.js.

**Comment by minrk** [comment]
#8203 implements the behavior we had discussed.
