### ISSUE TITLE
Notebooks do not display on Chrome/OSX

### ISSUE THREAD

**Issue by cel4** [ipython/ipython#7785]
I am having issues when trying to open notebooks on my mac. When clicking on any notebook file, instead of showing the notebook the tab just stays completely blank.

This issue seems to be introduced by commit https://github.com/ipython/ipython/commit/2907e85670558fabd76d58b75e960181e3d9daea:

**Comment by minrk** [comment]
This is likely a case of bad cache javascript, and clearing the cache and/or loading in an incognito window should work. Are you using master or the beta or release candidate? How did you install IPython?

**Comment by cel4** [comment]
I see this issue in both Chrome and Safari. Using incognito mode in Chrome does not seem to fix it.

I installed directly via `pip install <path/to/local/checkout>`. Master works fine right before commit https://github.com/ipython/ipython/commit/2907e85670558fabd76d58b75e960181e3d9daea. After that commit, it seems broken.

**Comment by Carreau** [comment]
You probably haven't updated submodules in the checkout then.
The JavaScript is this too old.

Python setup.py submodule, and reinstall.
Envoyé de mon iPhone

**Comment by cel4** [comment]
Argh, totally forgot about  updating the submodule. This was indeed the problem. Thanks!

**Comment by minrk** [comment]
@cel4 I don't suppose you still have the output of the install that didn't work? I think there are supposed to be checks to prevent installation when the submodule state is wrong.

**Comment by cel4** [comment]
@minrk, no unfortunately I did not. However I do not remember seeing any hints pointing to the outdated submodule. It could very well be that I did not read all the messages carefully though.
