### ISSUE TITLE
Incorrect kernel reported on new install

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#7786]
I helped someone install the 3.0 beta under python 2 lat week. When he opened a v3 notebook and it was updated, it worked fine, but the name of the kernel was "Kernel" rather than Python 2.

**Comment by takluyver** [comment]
I think that's what it says when it starts, so if it keeps saying 'Kernel', that means it's failing to update it once the kernel starts.

I take it you didn't get a chance to check the JS console?

**Comment by minrk** [comment]
Pretty sure this is a duplicate of #7645, and fixed by #7650, in which case it should be fixed in the RC. Can you check?

**Comment by ellisonbg** [comment]
Looks like this did fix it. Thanks!
