### ISSUE TITLE
Consider putting command/edit keyboard shortcuts in tabs

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#7787]
Right now the keyboard shortcut dialog scrolls. It may make more sense to put the command/edit mode shortcuts in tabs to reduce the vertical space.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
