### ISSUE TITLE
Move dashboard buttons to the L side of the table

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#7788]
Right now there can be a huge distance between the left of the notebook dashboard (where there are checkboxes) and the right, where there are the buttons. It might improve the usability to have the buttons on the left side (where the download text is).

**Comment by rsmith31415** [comment]
In that case, why not reduce the size of the div that contains all the files and folders. Something like this:

![screenshot from 2015-02-14 18 33 50](https://cloud.githubusercontent.com/assets/599274/6201581/12355154-b478-11e4-8612-895cef0c558b.png)

![screenshot from 2015-02-14 18 33 37](https://cloud.githubusercontent.com/assets/599274/6201582/19329cdc-b478-11e4-95e8-bd7d70f407df.png)

In this way, there is not much empty space on the right.

This reminds me Github interface:

![screenshot from 2015-02-14 18 34 54](https://cloud.githubusercontent.com/assets/599274/6201585/3d8a3446-b478-11e4-9342-038e43d72d00.png)

**Comment by ellisonbg** [comment]
We have talked about some more significant changes to the dashboard, but
are trying to get there through small incremental changes.

On Sat, Feb 14, 2015 at 4:39 PM, rsmith31415 <notifications@github.com>
wrote:

> In that case, why not reduce the size of the div that contains all the
> files and folders. Something like this:
>
> [image: screenshot from 2015-02-14 18 33 50]
> <https://cloud.githubusercontent.com/assets/599274/6201581/12355154-b478-11e4-8612-895cef0c558b.png>
>
> [image: screenshot from 2015-02-14 18 33 37]
> <https://cloud.githubusercontent.com/assets/599274/6201582/19329cdc-b478-11e4-95e8-bd7d70f407df.png>
>
> In this way, there is not much empty space on the right.
>
> This reminds me Github interface:
>
> [image: screenshot from 2015-02-14 18 34 54]
> <https://cloud.githubusercontent.com/assets/599274/6201585/3d8a3446-b478-11e4-9342-038e43d72d00.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/7788#issuecomment-74398651>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by rsmith31415** [comment]
Is there an issue where I can read about those proposed changes?

**Comment by ellisonbg** [comment]
Unfortunately, we don't have it written down anywhere. But most of the ideas were very much inspired by GitHub.

**Comment by mathieu1** [comment]
A related suggestion : replace the long text "To import a notebook, drag ... or **click here**" by a simple `import notebook` button, along with a tooltip and/or mention in the doc that importing a notebook also works by dragging.

**Comment by ellisonbg** [comment]
+1

**Comment by dsblank** [comment]
@mathieu1 Your suggestion regarding the importing by dropping is a good one. Three points:

1. Currently, the "click here" doesn't look like something you can click: no mouse change when mouse over.
2. You can upload any type of file, not just notebooks. 
3. "import" may not be the correct word; maybe "upload" is better

So, a button that says "Upload" and mouse over that says "Drag and drop files to upload, or click button to select them".
