### ISSUE TITLE
Empty running tab tables should only have a grey header

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#7789]
When the "Running" tab tables have no entries, the entire table is grey. Only the table header should be grey - the area that has the "There are no...." should have the standard white bg.

![screen shot 2015-02-15 at 11 03 44 am](https://cloud.githubusercontent.com/assets/27600/6204508/8d10a4c0-b502-11e4-9eea-6bce0ad6592c.png)

**Comment by parente** [comment]
I submitted a pull request with the background fix. The PR has a screenshot for review.

**Comment by minrk** [comment]
closed by #7791
