### ISSUE TITLE
Selected Keyboard Shortcuts in Chrome not working

### ISSUE THREAD

**Issue by igauravsehrawat** [ipython/ipython#7792]
Ctrl + m + t  - doesn't work instead opens new tab
Ctrl + m + n - doesn't work instead open window .

OS version: Ubuntu 14.04
Chrome : 38.0.2125.122

Possible Solution: ipython might have to change the shortcuts for these .

Thanks
Cheers

**Comment by Carreau** [comment]
`Ctrl + m + t` an `Ctrl + m + n` are not shortcut used by IPython notebook.
What are you trying to acchieve ?

**Comment by igauravsehrawat** [comment]
@Carreau 
Version: 1.2.1

![ipython-keyboard-shortcuts](https://cloud.githubusercontent.com/assets/3696327/6207774/65effb96-b5d1-11e4-8271-01220b60165e.png)

**Comment by takluyver** [comment]
Note that it's not `Ctrl+m+t`, it's `Ctrl+m`, then t.

In newer versions of IPython, we changed to a different scheme for keyboard shortcuts. We're not doing any more 1.x releases, so I'm closing this issue.

**Comment by igauravsehrawat** [comment]
@takluyver thanks. Mistaken myself. 

Cheers
