### ISSUE TITLE
single quotes inside backquotes in .md block breaks pdflatex

### ISSUE THREAD

**Issue by michaelaye** [ipython/ipython#7793]
Version: 7c9205cbba3a7e15c1e4f61d9db4786a77a87a56 (master as of 5 mins ago)

In a notebook markdown cell, this one breaks pdflatex:

``` markdown
Accessing `df['SCAN OLA TIME']`
```

Using double quotes is okay:

``` markdown
Accessing `df["SCAN OLA TIME"]`
```

Error:

``` latex
! Undefined control sequence.
    <argument> df\_orig{[}\textquotesingle
                                           {}SCAN\ OLA\ TIME\textquotesingle {}{]}
    l.867 ...le{}SCAN\ OLA\ TIME\textquotesingle{}{]}}

    ?
    ! Emergency stop.
```

**Comment by michaelaye** [comment]
The question is of course if this is an upstream problem, or if the notebook should replace single quotes with double quotes for user convenience?

**Comment by minrk** [comment]
It may be a missing package. We have a static copy of the pandoc latex preamble to load packages, but pandoc's preamble can actually change. Perhaps there's a way that we can extract the pandoc package preamble at generation time, rather than carrying a static copy that can get stale.

**Comment by heplesser** [comment]
`\textquotesingle` is defined in package `textcomp`, adding `\usepackage{textcomp}` to the template (or for now to the generated tex file) has fixed this for me.

**Comment by srdawes** [comment]
Is there any chance of fixing this issue? IPython Notebook doesn't seem to output a tex file when it crashes with a 500 Server error and there seems to be no template anywhere to edit. 

Can you describe your workaround in more detail @heplesser?

**Comment by heplesser** [comment]
@srdawes I first convert the notebook to LaTeX (`ipython nbconvert --to latex mynotes.ipynb`), then edit the generated TeX file (`mynotes.tex`) with a text editor and add `\usepackage{textcomp}` to the header section of the file, and finally create the PDF by running `pdflatex mynotes`, usually two or three times to get all references right.

**Comment by srdawes** [comment]
Fantastic! Thanks so much @heplesser. That worked.  It would be good if this package were added to the default template though as the process of producing the pdf has gone from one anyone using LaTeX can use to one only people comfortable with working with command windows can attempt.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.

**Comment by heplesser** [comment]
The problem does not longer exist in nbconvert 5.2.1, so no need to re-open this elsewhere.
