### ISSUE TITLE
TypeError:CodeMirror undefined

### ISSUE THREAD

**Issue by kain88-de** [ipython/ipython#7796]
I'm trying to use the [codefolding](https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/Codefolding) extension with Ipython 3.0.0-rc1. 

I copied the codefolding extension to  '/nbextensions/codefolding' and and load it in custom.js with

```Javascript
$([IPython.events])/on('app_initialized.NotebookApp', function() {
require(['/nbextensions/codefolding/codefolding/js'])
});
```

The extension is not loaded with the current RC and looking into the web console I can see error messages like this.

```TypeError: CodeMirror is undefined    foldcode.js:73```

This error is in a file of CodeMirror shipped with IPython.  I'm not sure if this is a problem with the CodeMirror version shipped in the RC or how IPython includes it.

I'm using Firefox 31.4.0

**Comment by juhasch** [comment]
Please make sure you use the latest version of the extension:
https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/usability/codefolding

**Comment by minrk** [comment]
bugs in extensions should be reported in the extension's repo.
