### ISSUE TITLE
load balanced map_async does not give back prompt

### ISSUE THREAD

**Issue by michaelaye** [ipython/ipython#7799]
Using 7c9205cbba3a7e15c1e4f61d9db4786a77a87a56 on a miniconda Python 2.7 I don't get back the prompt with this line:

```python
result = lview.map_async(process_image_name, image_names)
```

The code that is executed is this:

```python
def do_blotches(p4img):
    reduced = clustering.perform_dbscan(p4img.get_blotches())
    if reduced is None:
        return None
    series = [blotch.data for blotch in reduced]
    df = pd.DataFrame(series)
    df['image_id'] = p4img.imgid
    return df

def do_fans(p4img):
    reduced = clustering.perform_dbscan(p4img.get_fans(), fans=True)
    if reduced is None:
        return None
    series = [fan.data for fan in reduced]
    df = pd.DataFrame(series)
    df['image_id'] = p4img.imgid
    return df
    
def process_image_name(image_name):
    dirname = pjoin(HOME, 'data/planet4/reduced')
    blotchfname = pjoin(dirname, image_name+'_reduced_blotches.hdf')
    fanfname = pjoin(dirname, image_name+'_reduced_fans.hdf')
    if os.path.exists(blotchfname) and\
            os.path.exists(fanfname):
        return image_name
    data = pd.read_hdf(dbfile, 'df', where="image_name="+image_name)
    img_ids = data.image_id.unique()
    print("Found {} unique P4 image_ids.".format(img_ids.shape[0]))
    blotches = []
    fans = []
    for img_id in img_ids:
        p4img = markings.ImageID(img_id)
        blotches.append(do_blotches(p4img))
        fans.append(do_fans(p4img))
    blotches = pd.concat(blotches, ignore_index=True)
    blotches.to_hdf(blotchfname, 'df')
    fans = pd.concat(fans, ignore_index=True)
    fans.to_hdf(fanfname, 'df')
    return image_name
```

Could this be a be a Py2.x issue? With Py3.x this usually works for me. Although I noticed that it could take several seconds if the iterator given to the function would entail a long list. Maybe this is the efficiency difference between using lists and iterators? Even so this list of `image_names` is only between 200 and 300 items long.

**Comment by minrk** [comment]
Something is definitely misbehaving if this isn't returning quite promptly.

image_names is a plain list of strings? Are these functions defined in a module that's importable on the client and engines, or interactively? What OS?

**Comment by minrk** [comment]
Are you using dill?

**Comment by michaelaye** [comment]
* it's just a list of file path strings
* no, these functions were only defined in the notebook and I pushed the 2 sub functions to the engines using `dview.push({'do_fans':do_fans,'do_blotches':do_blotches})`
* OS: OSX 10.10.2
* not using dill

**Comment by minrk** [comment]
How many engines?

**Comment by michaelaye** [comment]
Only used 3 or 4 engines on a 4+4 machine (4 real, 4 virtual).

**Comment by minrk** [comment]
Hm, when I run it locally (with 300 fake image names that don't exist), it returns immediately. I'm not sure what could be causing the hang. Can you set `client.debug = True` and try again? Does it trigger only for large enough lists? Do you see it with just one filename?

**Comment by michaelaye** [comment]
Ok, will do, but am on different project right now. Possibly until tomorrow I can rerun.

**Comment by minrk** [comment]
No rush, thanks for debugging.

**Comment by michaelaye** [comment]
i think we can close it. i called the map_async with a pandas Series and had a bug where I forgot to call unique() on the Series. That resulting in a list the size of over 100k elements.
