### ISSUE TITLE
load balancing map_async has increasing memory consumption

### ISSUE THREAD

**Issue by michaelaye** [ipython/ipython#7800]
This is the same code running as in #7799, using a miniconda Python2.7 and version 7c9205cbba3a7e15c1e4f61d9db4786a77a87a56.

The sub-functions return pandas data frames, are they maybe being cached in some IPython cache for 'previous variable access'?
The increasing memory consumption is not so bad at first, but after 30 mins of running or so, it's at 100 MB per minute or so, and that despite the fact that the end-resulting HDF files that I write out are only each approx 1 MB of size.

Can I run IPython parallelism without the IPython cache somehow to check if that is the reason? I would be surprised if sclearn.clustering itself has a memory leak, but it's of course not impossible.

Here's the code, for reference:

``` python
def do_blotches(p4img):
    reduced = clustering.perform_dbscan(p4img.get_blotches())
    if reduced is None:
        return None
    series = [blotch.data for blotch in reduced]
    df = pd.DataFrame(series)
    df['image_id'] = p4img.imgid
    return df

def do_fans(p4img):
    reduced = clustering.perform_dbscan(p4img.get_fans(), fans=True)
    if reduced is None:
        return None
    series = [fan.data for fan in reduced]
    df = pd.DataFrame(series)
    df['image_id'] = p4img.imgid
    return df

def process_image_name(image_name):
    dirname = pjoin(HOME, 'data/planet4/reduced')
    blotchfname = pjoin(dirname, image_name+'_reduced_blotches.hdf')
    fanfname = pjoin(dirname, image_name+'_reduced_fans.hdf')
    if os.path.exists(blotchfname) and\
            os.path.exists(fanfname):
        return image_name
    data = pd.read_hdf(dbfile, 'df', where="image_name="+image_name)
    img_ids = data.image_id.unique()
    print("Found {} unique P4 image_ids.".format(img_ids.shape[0]))
    blotches = []
    fans = []
    for img_id in img_ids:
        p4img = markings.ImageID(img_id)
        blotches.append(do_blotches(p4img))
        fans.append(do_fans(p4img))
    blotches = pd.concat(blotches, ignore_index=True)
    blotches.to_hdf(blotchfname, 'df')
    fans = pd.concat(fans, ignore_index=True)
    fans.to_hdf(fanfname, 'df')
    return image_name
```

**Comment by michaelaye** [comment]
I tried to use

```python
from IPython import InteractiveShell
InteractiveShell.cache_size = 0
```
inside the notebook but it does not seem to change anything. Do I have to put this into the notebook_config to be working?

**Comment by takluyver** [comment]
That will only affect the kernel you're interacting with, so if something's being cached inside the parallel machinery, I wouldn't expect that to make a difference. Hopefully Min will be able to provide more information about it.

**Comment by michaelaye** [comment]
Aha, so that sounds like putting it to the config file should be better than, because that is being used by each engine, I believe?

**Comment by minrk** [comment]
There is a client-side cache. You can clear it with `Client.purge_local_results`

**Comment by minrk** [comment]
There should also be an improvement in this behavior in 3.0, where results should be popped out of the cache on retrieval (#5784).

**Comment by michaelaye** [comment]
But I was using https://github.com/ipython/ipython/commit/7c9205cbba3a7e15c1e4f61d9db4786a77a87a56 so this should have been in, no?

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
