### ISSUE TITLE
Change from 2.7 to 3.4 kernel throws error in console

### ISSUE THREAD

**Issue by michaelaye** [ipython/ipython#7802]
I reported this some weeks ago in the help-gitter, but it still happens so I thought I report it here.

I had a notebook that I was running on Py2.7 (using 7c9205cbba3a7e15c1e4f61d9db4786a77a87a56) and I wanted to try it on Py3.4 to see if I have the same memory problems.
When launching the notebook the console throws this error, about not finding `python2` (I use conda environments to switch).

```bash
[E 16:33:24.544 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/IPython/html/base/handlers.py", line 365, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/IPython/html/services/sessions/handlers.py", line 53, in post
        model = sm.create_session(path=path, kernel_name=kernel_name)
      File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/IPython/html/services/sessions/sessionmanager.py", line 66, in create_session
        kernel_name=kernel_name)
      File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/IPython/html/services/kernels/kernelmanager.py", line 84, in start_kernel
        kernel_name=kernel_name, **kwargs)
      File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/IPython/kernel/multikernelmanager.py", line 112, in start_kernel
        km.start_kernel(**kwargs)
      File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/IPython/kernel/manager.py", line 240, in start_kernel
        **kw)
      File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/IPython/kernel/manager.py", line 189, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/IPython/kernel/launcher.py", line 213, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/Users/klay6683/miniconda3/lib/python3.4/subprocess.py", line 858, in __init__
        restore_signals, start_new_session)
      File "/Users/klay6683/miniconda3/lib/python3.4/subprocess.py", line 1456, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'python2'
[E 16:33:24.598 NotebookApp] {
      "Accept-Encoding": "gzip, deflate",
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Accept-Language": "en-us",
      "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
      "Origin": "http://localhost:8888",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Content-Length": "86",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18",
      "X-Requested-With": "XMLHttpRequest",
      "Referer": "http://localhost:8888/notebooks/catalog%20production.ipynb"
    }
[E 16:33:24.598 NotebookApp] 500 POST /api/sessions (::1) 75.21ms referer=http://localhost:8888/notebooks/catalog%20production.ipynb
```

Despite the errors I  can change the kernel with the menu point "Kernel->Change Kernel", but have to close the notebook and start it again before it works.

**Comment by takluyver** [comment]
Can you show the contents of the relevant `kernel.json` files that you're switching between? And just to confirm, you're switching *from* Python 2 *to* Python 3 when you get that traceback? I'm a bit surprised that it's trying to launch `python2` if you switched to Python 3.

**Comment by michaelaye** [comment]
So the procedure is:
* run a py2.7 notebook
* don't like something, save notebook
* close notebook, kill ipython notebook
* switch to py34 environment
* start a new python notebook
* launch the previously saved notebook
* that's when above error appears.

Where do I find these different kernel.jsons ?

**Comment by takluyver** [comment]
Ah, I see, you're starting a new notebook server in a different environment, not switching the kernel within the notebook.

Are there any folders in `~/.ipython/kernels`? If so, each one should have a kernel.json in it.

**Comment by michaelaye** [comment]
Only one subfolder called 'python2' and here is its kernel.json:

```json
$ less kernel.json
{
 "display_name": "Python 2",
 "language": "python",
 "argv": [
  "python2",
  "-c",
  "from IPython.kernel.zmq.kernelapp import main; main()",
  "-f",
  "{connection_file}"
 ],
 "codemirror_mode": {
  "version": 2,
  "name": "python"
 }
}
```

**Comment by takluyver** [comment]
OK, I see what's happening. When you save the notebook, it records in the metadata that it is associated with a Python 2 kernel, so when you open it, it will try to start a Python 2 kernel for it. This much is as is intended.

Where it's going wrong is that kernel.json file - I guess it was created by an earlier commit of IPython. It tries to launch `python2`, which isn't in your $PATH in the Python 3 conda env. The kernel.json files we now create specify a full `/path/to/env/bin/python` to avoid this problem. If you delete the `python2` subfolder, it should fix that.

Then if you want to use the new kernel switching mechanism to test your notebook without having to restart the server, run `ipython kernelspec install-self` in the environment where you're *not* going to run the server (e.g. run that command in the Python 2 env, and then run `ipython notebook` in the Python 3 env). That will create a new kernel.json which should work better.
