### ISSUE TITLE
Order of execution: python interleaved with JS

### ISSUE THREAD

**Issue by jakobgager** [ipython/ipython#7804]
Is there a way to get of the javascript call executed before or interleaved with the python code? 
E.g. to get the notebook name one could use the approach shown in [this example](http://nbviewer.ipython.org/github/ipython/ipython/blob/master/examples/Interactive%20Widgets/Export%20As%20%28nbconvert%29.ipynb). But if you put everything within one method (or cell) like
```python
def getNotebookName():
    from IPython.display import Javascript, display
    from IPython.html import widgets
    notebook_name = widgets.TextWidget()
    js = """var model = IPython.notebook.kernel.widget_manager.get_model('{model_id}');
         model.set('value', IPython.notebook.notebook_name);
         model.save();""".format(model_id=notebook_name.model_id)
    display(Javascript(data=js))
    return notebook_name.value
```
it doesn't work due to the order of execution (I guess).

**Comment by takluyver** [comment]
The JS code can run at the same time as the Python code, but the kernel won't process the update to the widget object until it finishes executing your code, AIUI. I don't think there's any good way round that.

Have a look at Jon's jsobject library for more details about this: https://github.com/jdfreder/ipython-jsobject

**Comment by jakobgager** [comment]
Thanks for the hint. I somehow expected something like this. :confused:
