### ISSUE TITLE
Old versions not available in pypi, e.g. for python 2.6 or 3.2

### ISSUE THREAD

**Issue by diimdeep** [ipython/ipython#7812]
It's stated that
*If you need to use Python 2.6 or 3.2, you can find IPython 1.0 [here](http://archive.ipython.org/release/)*

Why such versions not available in https://pypi.python.org/pypi/ipython ?

**Comment by takluyver** [comment]
https://pypi.python.org/pypi/ipython/1.2.1

PyPI hides older versions by default, but they are still there.

**Comment by diimdeep** [comment]
@takluyver  nice, thanks.
