### ISSUE TITLE
Strange characters prevent notebook opening

### ISSUE THREAD

**Issue by dsblank** [ipython/ipython#7813]
Had a user today (using master code from about 2 weeks ago) that couldn't get a notebook to render:
```
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1332, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/publichandler.py", line 44, in get
        nb_json = nbformat.read(fp, as_version=4)
      File "/usr/local/lib/python3.4/dist-packages/IPython/nbformat/__init__.py", line 133, in read
        return reads(fp.read(), as_version, **kwargs)
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1766: ordinal not in range(128)
```
It turned out that the notebook had a weird comma-like character that was probably copy-pasted from Word. 

Isn't there a way to read the file, in a given encoding, and replace/ignore such errors? Suggest we do that in `IPython/nbformat/__init__.py` at line 133.

**Comment by takluyver** [comment]
That definitely shouldn't be happening - you should be able to use any character in the notebook.

**Comment by takluyver** [comment]
Wait, I'm confused - the error is coming from jupyterhub, in a module called `publichandler`. That module is not there in the repo, no other code in jupyterhub appears to use nbformat, and I'm puzzled as to why jupyterhub would be rendering a notebook at all - I thought it just started instances of `ipython notebook` to do all that?

**Comment by dsblank** [comment]
The stack trace does have publichandler in it, but the error is in nbformat. Or am I not opening the file correctly?

**Comment by minrk** [comment]
I think this is actually a bug in your extensions to jupyterhub, not in nbformat.

**Comment by takluyver** [comment]
Make sure that you're opening the file like `open(path, encoding='utf-8')`.

If you don't pass an encoding, the default is platform & locale dependent, and for services on Unix servers, that often means it's ASCII. This platform dependent default is probably my least favourite thing about Python.

Oh, I see Min found a simpler fix.

**Comment by minrk** [comment]
@dsblank I opened a PR against your jupyter.brunmawr repo. If you pass a file-like to nbformat.read, it must be unicode-aware, as returned by `io.open('path', encoding='utf-8')`.

**Comment by dsblank** [comment]
Thanks! Especially since this was my bug :( And double-thanks for the fix! And triple-thanks for the speed at which you did this!
