### ISSUE TITLE
Inspect requests inside a function call should be smarter about what they inspect.

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#7816]
Previously, `func(a, b, <shift-tab>` would give information on `func`, now it gives information on `b`, which is not especially helpful.

This is because we removed logic from the frontend to make it more language agnostic, and we have not yet reimplemented that on the frontend. For 3.1, we should make it at least as smart as 2.x was. The quicky and dirty approach would be a regex; the proper way is tokenising the code.

Ping @mwaskom who brought this up on the mailing list.

**Comment by mwaskom** [comment]
Thanks! I don't actually know how to *use* any of these packages, so I rely on what IPython tells me they'll do :)

Should note here too that the help also seems to be displaying the __repr__ for, at least, pandas DataFrames slightly differently in 3.0.rc1, which yields a help popup that is garbled and hides the important bits.

**Comment by takluyver** [comment]
The dataframe reprs sounds like a separate thing - can you file an issue for it? Preferably with screenshots? Thanks.

**Comment by mwaskom** [comment]
Done: #7817 

More related to this issue:

While implementing a smarter inspector, it would be *great* if it would work across line breaks. I'm constantly getting bitten by trying to do

```python
complex_function(some_arg, another_arg, data_frame.some_transformation(),
                 a_kwarg=a_value, <shift-TAB>
```
And having it not work.

This did not work on the 2.x series either, AFAICT, but if the inspector is going to be reimplemented it would be awesome if it could be added.

**Comment by takluyver** [comment]
If there's smart, tokenising logic to determine what you're inspecting, there's no reason it shouldn't handle multiple lines. Making it smart enough for that might not be a 3.1 thing, though.

**Comment by minrk** [comment]
#7819 might be an improvement on this one
