### ISSUE TITLE
Method help popovers have become less useful in IPython 3.0.rc1

### ISSUE THREAD

**Issue by mwaskom** [ipython/ipython#7817]
Forking from #7816 

I've noticed that the help popover (i.e., what you get when you hit shit-TAB in side the text of a function call) now has a lot of information that is not very useful to the task of finding out the function signature for a method.

I've particularly noticed this for Pandas Dataframes, though I assume the issue is more general than that. It's particularly annoying with DataFrames because the textual `__repr__` looks really bad, especially for large frames. (And also because I can never remember how to use their methods).

Here's an example of what we used to get:

![screenshot 2015-02-19 10 38 29](https://cloud.githubusercontent.com/assets/315810/6273369/dc816412-b823-11e4-8a8b-e0aeea040d93.png)

And here's what we get now:

![screenshot 2015-02-19 10 37 44](https://cloud.githubusercontent.com/assets/315810/6273378/e5146200-b823-11e4-86ad-070859bd5e80.png)

(I should note that putting together this issue caused me to note how much more attractive I find the 3.0/Jupyter styling. Well done!)

**Comment by takluyver** [comment]
Aha, yes, this was another part of the reorganisation to make the frontend more language agnostic. Previously, the tooltip got a bunch of semi-semantic but quite Python specific info, and that was formatted by JS code. Now it gets text back from the kernel and displays it as is, so what you see is the same as when you do `tips.groupby?`.

I've also noticed that this information is not brilliant for tooltip presentation - see issue #7759 for some reorganisation I want to do.

I also have a more ambitious plan with @ccordoba12 to adapt some code from Spyder to render a nicer HTML presentation of docstrings.

**Comment by rsmith31415** [comment]
@takluyver 

>I also have a more ambitious plan with @ccordoba12 to adapt some code from Spyder to render a nicer HTML presentation of docstrings.

Do you mean to render the markdown as HTML inside the tooltip? If that is correct, it would be great to see LaTeX rendering via MathJax.

**Comment by takluyver** [comment]
I do mean rendering as HTML inside tooltips, but there's not currently any markdown involved. I think that MathJax rendering should *just work* in that situation.

**Comment by rsmith31415** [comment]
Oh, right. I think it is reST, not markdown. 

I remember that you have to tell MathJax to target a certain element to dynamically render the math. In any case, that is excellent.

**Comment by takluyver** [comment]
I thought it just looked for text in `$foo$`, but maybe we do that and put it in some element for mathjax to find.

**Comment by rsmith31415** [comment]
Yes, I'm guessing that's the way you're doing it (it is called [inline configuration](http://docs.mathjax.org/en/latest/dynamic.html))

**Comment by Zulko** [comment]
I second this issue, in my opinion it was nicer when we had function definition and docstring directly on alt+tab. I raised the concern on reddit and apparently other people agree (see [here](http://www.reddit.com/r/Python/comments/2xfw0i/ipython_30_released/cozua95)). Would it be possible to put the "Definition" and "Docstring" fields at the top ?

**Comment by takluyver** [comment]
Yep, that's exactly what I plan to do. I will work on it today, since this seems to be a concern for a lot of people.

**Comment by adrn** [comment]
:+1: -- FWIW this is enough to keep me from updating...
