### ISSUE TITLE
Issue while installing NewTurtle in Python notebook

### ISSUE THREAD

**Issue by Damor16** [ipython/ipython#7820]
Hello everybody, 

I am fairly new to the community and to Python itself. I am having issues with installing turtle edition to Ipython notebook. i am tried installing both, NewTurtle and PAC turtle version available for python notebook. 

I get the following error 

2015-02-19 21:45:01.119 [NotebookApp] Using existing profile dir: u'/Users/RD15/.ipython/profile_default'
2015-02-19 21:45:01.123 [NotebookApp] Using MathJax from CDN: http://cdn.mathjax.org/mathjax/latest/MathJax.js
2015-02-19 21:45:01.368 [NotebookApp] Serving notebooks from local directory: /Users/RD15/Downloads/PACattack-master
2015-02-19 21:45:01.368 [NotebookApp] 0 active kernels 
2015-02-19 21:45:01.368 [NotebookApp] The IPython Notebook is running at: http://127.0.0.1:8888/
2015-02-19 21:45:01.368 [NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
ERROR:tornado.general:Could not open static file ''
WARNING:tornado.access:404 GET /static/components/jquery-ui/themes/smoothness/jquery-ui.min.css (127.0.0.1) 1.45ms referer=http://127.0.0.1:8888/tree user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18
WARNING:tornado.access:404 GET /static/components/requirejs/require.js (127.0.0.1) 0.49ms referer=http://127.0.0.1:8888/tree user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18
WARNING:tornado.access:404 GET /static/components/jquery/jquery.min.js (127.0.0.1) 0.55ms referer=http://127.0.0.1:8888/tree user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18
WARNING:tornado.access:404 GET /static/components/bootstrap/bootstrap/js/bootstrap.min.js (127.0.0.1) 0.49ms referer=http://127.0.0.1:8888/tree user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18
WARNING:tornado.access:404 GET /static/components/jquery-ui/ui/minified/jquery-ui.min.js (127.0.0.1) 0.41ms referer=http://127.0.0.1:8888/tree user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18

I am quite not sure what is the problem, as i tried to follow instruction as mentioned in the author page. 

thank you

**Comment by takluyver** [comment]
I have developed a notebook turtle widget from the PACattack code, which you can find here: https://github.com/takluyver/mobilechelonian/

I wouldn't recommend trying to use the code from either of the original projects - they were both based on an older copy of the IPython code.

**Comment by Damor16** [comment]
Thank you takluyver for the help. Sorry, I am just a beginner, how do I install it the extension?

thank you

**Comment by takluyver** [comment]
I've just put a new release up on PyPI; you should be able to do `pip install mobilechelonian`.

It needs IPython 3, which we're just about to release.
