### ISSUE TITLE
support mimebundles

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#7824]
msgspec 5 uses mimebundles in a few new places (pager, inspect_reply), but the mimebundle code in OutputArea still needs to be pulled out in order to be re-used in these places. The new mime-bundle areas only handle text/plain as of 3.0.

**Comment by flying-sheep** [comment]
shouldn’t this be moved to the notebook repo?

**Comment by minrk** [comment]
Migrated to jupyter/notebook#1135

**Comment by minrk** [comment]
Indeed it should.
