### ISSUE TITLE
nbconvert --to slides --post server reveal.js redirection not working

### ISSUE THREAD

**Issue by lmarti** [ipython/ipython#7829]
I am using ipython nbconvert to serve my notebooks as slides locally.

When I run ipython nbconvert --to slides --post serve my-notebook.ipynb the slides are not rendered correctly.

I have noticed in the log that a redirection is added to serve reveal.js:

`[NbConvertApp] Redirecting reveal.js requests to https://cdn.jsdelivr.net/reveal.js/2.5.0`

but https://cdn.jsdelivr.net/reveal.js/2.5.0 returns a 403 error. 

I have noticed that in the most recent version the file ipython/IPython/nbconvert/postprocessors/serve.py has the url updated to point to https://cdn.jsdelivr.net/reveal.js/2.6.2 -- this new url also returns a 403 error. 

---
Environment details:

python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': '1c0eb68',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/lm/anaconda/lib/python3.4/site-packages/IPython',
 'ipython_version': '2.3.1',
 'os_name': 'posix',
 'platform': 'Darwin-14.1.0-x86_64-i386-64bit',
 'sys_executable': '/Users/lm/anaconda/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.4.2 |Anaconda 2.1.0 (x86_64)| (default, Oct 21 2014, '
                '17:42:20) \n'
                '[GCC 4.2.1 (Apple Inc. build 5577)]'}

**Comment by damianavila** [comment]
Can you test if `ipython nbconvert your_slides.ipynb --to slides --post serve --reveal-prefix "http://cdn.jsdelivr.net/reveal.js/2.5.0" is working for you? I am suspecting on a failure in the redirection...

**Comment by damianavila** [comment]
ok... I think I know what the problem is... when we use `http://` the thing is working but not when you use the secured one, I mean `https://`...
@minrk @rgbkrk is there something we can do the the ServePostProcessor implementation to accept secure http?
As a quick workaround we can change the default url to `http` if necessary...
BTW, this probably need to be inside 3.0, if not the `--post serve` option is not working by default.

**Comment by lmarti** [comment]
The command you suggested works for me. I think I was not using any https stuff.

**Comment by takluyver** [comment]
This appears to be working for me with the https URL we use by default in master. Why would redirecting to an https URL be a problem?

**Comment by damianavila** [comment]
This was not working the other day, let me check again... maybe a `jsdeliv` issue?

**Comment by lmarti** [comment]
The situation is the same on my side.

**Comment by damianavila** [comment]
OK, this is not working for me in master... I have this in the JS console:

```
 Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://127.0.0.1:8000/reveal.js/css/reveal.css".
test_slides.slides.html:19 Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://127.0.0.1:8000/reveal.js/css/theme/simple.css".
test_slides.slides.html:13675 Resource interpreted as Script but transferred with MIME type text/html: "http://127.0.0.1:8000/reveal.js/lib/js/head.min.js".
test_slides.slides.html:13677 Resource interpreted as Script but transferred with MIME type text/html: "http://127.0.0.1:8000/reveal.js/js/reveal.js".
test_slides.slides.html:13682 Uncaught ReferenceError: Reveal is not defined
test_slides.slides.html:13722 Uncaught ReferenceError: Reveal is not defined
```

The funny thing is that downgrading tornado to 3.2, I can get it working...

**Comment by minrk** [comment]
I know what the issue is, I'll have a PR with some fixes shortly. The proxy request is failing due to a missing package, and we are ignoring the error.

**Comment by minrk** [comment]
#7850

**Comment by hongshanguo** [comment]
I was having a huge amount of trouble in dealing with this, but thankfully the Feb 21 comment worked finely for me... Honestly, I don't believe this bug is fixed. ;D

**Comment by damianavila** [comment]
AFAIK, the `certifi` issue was solved in the conda package, so right now it does not have to be an issue anymore, and if you don't have `certifi` installed, then #7850 will help... obviously, this is not working for previous versions, but 3.0 has the fix, it is solved there ;-)

**Comment by btabibian** [comment]
For some reason I am having this problem again and only thing I get on JS console in chrome is following error:

Uncaught ReferenceError: Reveal is not defined

I can open the presentation on Firefox but not on Chrome or Safari.

**Comment by damianavila** [comment]
Can you tell me exactly what commands you used to make the slides? Can you also try cleaning your browser cache and reload it again? Thanks.

**Comment by btabibian** [comment]
Thanks for the suggestion, cleaning the cache worked!! Any idea why this might happen?

**Comment by damianavila** [comment]
The browsers are pretty aggressive caching js... so if you work with a previous version and it was cached you will have problem. I always use the browser in incognito mode and with the dev tools opened, then you can make a hard relaod to be sure you are not hitting an old js...

**Comment by btabibian** [comment]
Thanks for your very helpful answer. I was on the verge of panicking :-)
