### ISSUE TITLE
commenting in Magics lines causes UsageError

### ISSUE THREAD

**Issue by interrogator** [ipython/ipython#7840]
When putting comments on lines containing Magics, you get a UsageError:

> In [24]: %matplotlib inline # a comment
> UsageError: unrecognized arguments: # a comment

Not a big deal, but likely an easy fix, too!

**Comment by Carreau** [comment]
Magics are not python syntax, so `#something` is **not** a comment.

The way magic work is that everything after the magics is a string, lets say with a have a magic `%hexcolor`  treating `#` as comment would prevent `%hexcolor #FAEDF8` to work.

**Comment by Carreau** [comment]
Still thanks for the heads up, the reason not to parse comments in magics might not be obvious I must admit. We could fix the matplotlib magic itself, but that would lead to some inconsistencies also.

**Comment by interrogator** [comment]
No worries, it just came up when I was demoing to students who were also new to Python, so I thought I'd let you know. Also, syntax highlighting in IPython treats it as a comment, so that added a bit to the confusion.

**Comment by takluyver** [comment]
It's not really clear cut - technically, we don't specify anything about
the syntax of the line after a line magic, but in most contexts, #comments
would make sense. I think it comes up rarely enough that it's not work
complicating the parser to handle it, though. You can always put a comment
on the line before.

**Comment by interrogator** [comment]
I agree, and as I said before, it's trivial. That said, if they aren't comments, they shouldn't be highlighted as comments. Moreover, if things after a hash aren't greyed out, people would realise pretty quickly that those things aren't being parsed as comments. Two bird with one stone!

Thanks, by the way, for your fantastic work!

**Comment by Carreau** [comment]
> That said, if they aren't comments, they shouldn't be highlighted as comments. Moreover, if things after a hash aren't greyed out, people would realise pretty quickly that those things aren't being parsed as comments. 

Thats easier.

**Comment by takluyver** [comment]
@Carreau it looks like you reopened this to change the highlighting of `%magic` lines in the notebook. Do you still want to do that? Do you want to retitle this, or close it and reopen on jupyter/notebook ?

**Comment by Carreau** [comment]
Assigning to myself to decide what to do at a time when brain can do brain functions more reliably.

**Comment by Carreau** [comment]
Hi, 

This issue has been quiet for almost a year, and I don't think there is anything we can do – it shoudl be fixed in the notebook frontend if anything not here. It has been marked as no-action, and I'm going to close it to attempt to reduce the number of opened issue. Feel free to reopen if needed. 

Thanks.
