### ISSUE TITLE
Widget Placement.ipynb does not exist

### ISSUE THREAD

**Issue by grelston** [ipython/ipython#7844]
Reading through the [Index notebook](https://github.com/ipython/ipython/blob/master/examples/Interactive%20Widgets/Index.ipynb) for [examples/Interactive Widgets/](https://github.com/ipython/ipython/tree/master/examples/Interactive%20Widgets) I discovered that [Widget Placement.ipynb](https://github.com/ipython/ipython/blob/master/examples/Interactive%20Widgets/Index.ipynb#L45) does not exist. This is for master, commit [e8dddcc1a9](https://github.com/ipython/ipython/commit/e8dddcc1a92759af1f59447cbee6edb5ba6f896d).

**Comment by takluyver** [comment]
Thanks for the report.
