### ISSUE TITLE
Using `??` on a class instance with two definitions in a file shows the source to the first definition, instead of the actual definition in use

### ISSUE THREAD

**Issue by tankorsmash** [ipython/ipython#7847]
#temp.py
    class Foo(object):
    	def bar(self):
    		pass
    
    class Foo(object):
    	def bar(self):
    		print "output"

in iPython:

    In [1]: import temp
    In [2]: foo = temp.Foo()
    In [3]: foo.bar()
      output
    In [4]: foo?
      Type:       Foo
      String Form:<temp.Foo object at 0x17a5f50>
      File:       /home/user/temp.py
      Source:
      class Foo(object):
				def bar(self):
						pass

IPython 0.13.2 and Python 2.7.3 reports that the first definition of Foo is the one being used, but it's the second one being instantiated

**Comment by takluyver** [comment]
0.13 is not supported any more - we're about to release 3.0. Can you try
with a more recent version?

**Comment by tankorsmash** [comment]
Oh wow, that explains that. I'm on Ubuntu 12.04. I'm sure it'd be resolved.

**Comment by tankorsmash** [comment]
In [6]: foo.bar??
Type:        instancemethod
String form: <bound method Foo.bar of <temp.Foo object at 0x210f2d0>>
File:        /home/user/temp.py
Definition:  foo.bar()
Source:
        def bar(self):
                print "output"

Can confirm IPython 3.0.0-rc1 has it fixed

**Comment by takluyver** [comment]
Thanks @tankorsmash
