### ISSUE TITLE
Contents Manager does not get passed config ?

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7849]
I can't seem to have my custom contents manager receive a config.

In sessionmanager we seem to have `contents_manager = Instance('IPython.html.services.contents.manager.ContentsManager', args=())` but nowhere is it passed parent or config. Is that normal ?

**Comment by Carreau** [comment]
actually it seams that because SessionManager does not have constructor, so when you passs it aroung in notebook_app it is not set.

**Comment by minrk** [comment]
These objects are constructed in `NotebookApp.init_configurables`, so that default init in session_manager shouldn't ever be used. `parent` is passed. If config weren't passed, then you wouldn't be able to specify the notebook_dir, and that's not true. What config are you trying to pass?

**Comment by Carreau** [comment]
Yeah, they are contructed there, but we do : 

```
 self.session_manager = self.session_manager_class(
            parent=self,
            log=self.log,
            kernel_manager=self.kernel_manager,
            contents_manager=self.contents_manager,
        )
```

Though, sessionmanager has no `__init__` to it, so as far as I can tell it reconstruct new ones without passing config or parents. 

I'm mostly trying to get a custom manager with custom config, and that does not work.

Even this config : 

```
{
  "nbformat": 1,
  "NotebookApp": {
    "tornado_settings": {
      "contents_js_source": "nbextensions/gdrive/mixed-contents"
    }
  },
  "ContentsManager":{
      "filesystem_scheme": [
            {
                "root":"HD",
                "contents":"IPython.html.services.contents.filemanager.FileContentsManager"
            },
            {
                "root": "gdrive",
                "contents": "jupyterdrive.clientsidenbmanager.ClientSideContentsManager"
            }
        ]
  }

}
```

yield this log (with extra print statement):

```
Contents ::  () {'log': ..., 'parent': <IPython.html.notebookapp.NotebookApp object at 0x102a8a320>}
Contents.config ::  {..., 'ContentsManager': {....}}
=================
Contents ::  () {}
Contents.config ::  {}
````
`(){}` being `*args, **kwargs`
Which show that we are creating 2 instances one of them without configs.

**Comment by takluyver** [comment]
> Though, sessionmanager has no __init__ to it,

HasTraits objects take keyword arguments to the constructor and set the traitlet attributes from those. Configurable objects additionally deal with `parent`. So it shouldn't need an explicit `__init__`.

**Comment by Carreau** [comment]
Hum, when would these contents without config be created then ? Should I just ignore them ?

**Comment by Carreau** [comment]
> Hum, when would these contents without config be created then ? Should I just ignore them ?

Should I just suppose that my custom content manager might get instanciated without config at some point and would be instanciated ok at a later point ?

**Comment by takluyver** [comment]
Which one is it using? I think we should fix it so it's only instantiated once, but if the copy with the config is getting used, it's not so urgent.

I would guess that it's an ordering thing that something is referencing `self.contents_manager` before it gets set, and traitlets generates the default value.

**Comment by minrk** [comment]
> when would these contents without config be created then ?

probably created by the default_value generator, and never used. The default value stuff is really annoying.

> Should I just ignore them ?

yes

What's your class's name? `ContentsManager` doesn't have a `filesystem_scheme` trait. You need to use *your* class's name.

**Comment by Carreau** [comment]
> probably created by the default_value generator, and never used. The default value stuff is really annoying.

Ah, that could be it.

> What's your class's name? ContentsManager doesn't have a filesystem_scheme trait. You need to use your class's name.

Yes, but mine derive from it, so using `ContentsManager` does work too. 

I am failing early in mine  if config is not given, and did the same in my for of IPython to check if it was true with default `ContentsManager` (Hence the key) 

Not failing early seem to work, but it was very unintuitive that you could not be passed the config.
That prevent to raise an exception telling the user "Hey you should configure me".

**Comment by minrk** [comment]
We should just get rid of the `args=()` in SessionManager that causes it to be instantiated.

**Comment by minrk** [comment]
#7855

**Comment by takluyver** [comment]
Ah, that's what it is. I was digging through code trying to work out what used contents_manager before it ought to. I missed that passing any args causes instantiation.
