### ISSUE TITLE
Stronger password hash algorithms for IPython notebook

### ISSUE THREAD

**Issue by luanthe** [ipython/ipython#7863]
The documentation for `IPython.lib.security.passwd()` says that the hash algorithm can be specified using:

```
    algorithm : str
        Hashing algorithm to use (e.g, 'sha1' or any argument supported
        by :func:`hashlib.new`).
```

However, the algorithms supported by `hashlib` (md5, sha1, sha2 variants) are not recommended for password hashing, see:

http://krebsonsecurity.com/2012/06/how-companies-can-beef-up-password-security/
http://security.stackexchange.com/questions/211/how-to-securely-hash-passwords
http://security.blogoverflow.com/2013/09/about-secure-password-hashing/

It would be better to allow the use of stronger password hashing algorithms, perhaps by including something like https://pythonhosted.org/passlib/

**Comment by Carreau** [comment]
Yes, we are aware that password should be stored as blowfish, or other "slow" algorithm. 
The question is how do you tell IPython which library to use for which scheme ?
passlib or cryptography ?

We are not either storing thousand of user password, and in multi-user context, Jupyterhub use pluggable auth, so this will most likely be more secure.

There are also probably more security things that could be better designed like PFS, and  ciphers we accept. 

I suppose a PR that add the possibility to do that would be accepted, but I doubt passwd encryption is the weaker place in the security chain.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
