### ISSUE TITLE
fail to start ipcontroller : AssertionError main

### ISSUE THREAD

**Issue by razygon** [ipython/ipython#7866]
I have updated ipython from 1.1 to 2.4.1, and then I can't start the ipcontroller (previously it worked well).
System: windows 8
python: 2.7 win32

I use `ipython profile create --parallel --profile=myprofile` to create my own profile
and start with
`ipcontroller --profile=myprofile --ip=*`

the error:

```
  File "C:\Python27\lib\multiprocessing\forking.py", line 380, in main
  File "C:\Python27\lib\multiprocessing\forking.py", line 380, in main
  File "C:\Python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\lib\multiprocessing\forking.py", line 488, in prepare

  File "C:\Python27\lib\multiprocessing\forking.py", line 488, in prepare
    prepare(preparation_data)
  File "C:\Python27\lib\multiprocessing\forking.py", line 488, in prepare
    assert main_name not in sys.modules, main_name
AssertionError    : assert main_name not in sys.modules, main_name
: ssertionError_main__
_ssert main_name not in sys.modules, main_name
_main__AssertionError
: __main__
```

I tried to do sth to forking.py, but failed, anybody can help with the problem?

**Comment by takluyver** [comment]
@minrk I've milestoned this for 3.0 because I think we should at least check it out - feel free to retarget it.

**Comment by minrk** [comment]
Looking into it.

**Comment by minrk** [comment]
@razygon how did you install Python? What shell are you using to launch ipcontroller? How did you install IPython?

I'm using Python 2.7 and IPython 2.4.1 via conda on windows 8, and ipcontroller starts just fine, here.

**Comment by razygon** [comment]
@minrk I installed via pip and python is also the default version. I tried conda, and the error is solved. Thank you very much!
I guess if using parallel conda should be involved,  right?

**Comment by razygon** [comment]
hi, actually I found there is one more reason that the engines can't connect with the controller.
The *location* in engine.json is not my physical address, but a virtual adapter's address.
I changed the file:
![image](https://cloud.githubusercontent.com/assets/3334564/6387661/bcb4bf20-bdc9-11e4-9622-e62897cd57fc.png)
 if not location:
       if public_ips():
            location = public_ips()[**-1**] ->location = public_ips()[**0**]  #line 228

maybe this is not a common issue, but only on my machine. In case sb. have the same problem, so I write it down.

**Comment by senyai** [comment]
Hint: running `python -m IPython.parallel.apps.ipcontrollerapp` instead of `ipcontroller.exe` is working okay.

**Comment by minrk** [comment]
@senyai yikes, that suggests that setuptools is somehow involved in the problem. I don't like that one bit.

**Comment by beebeed** [comment]
Hi, I am encountering similar problems - is there any suggested work around?

**Comment by ivanov** [comment]
Greetings! I'm going through old issues and it seems to me that it makes sense to close this one, since the original reporter was able to resolve the issue, and there was also a suggested workaround proposed by another user. Please open a new issue and mention this one (#7866) if you have a similar problem.
