### ISSUE TITLE
Notebook validation failing on seemingly valid notebooks

### ISSUE THREAD

**Issue by abeguerra** [ipython/ipython#7869]
The notebook validation for the notebook linked below is failing. The error I see is:

Notebook Validation failed: [] is not of type u'object'

I am running notebook server version 3.0.0-b1-16f4598

Notebooks which are failing validation:
1. https://raw.githubusercontent.com/ipython-books/cookbook-code/master/notebooks/chapter01_basic/01_notebook.ipynb
2. https://raw.githubusercontent.com/ipython-books/cookbook-code/master/notebooks/chapter01_basic/02_pandas.ipynb

The notebooks are from this repo (https://github.com/ipython-books/cookbook-code/tree/master/notebooks/chapter01_basic) and seem like valid notebooks to me. I see no problem in the notebook cells and am even able to run the cells.

Is this a bug? What is the expected behavior?

**Comment by Carreau** [comment]
> 1. https://raw.githubusercontent.com/ipython-books/cookbook-code/master/notebooks/chapter01_basic/01_notebook.ipynb

The metadata of the first cell is a list, metadata should be dict.

@rossant are these generated with ipymd ?

**Comment by abeguerra** [comment]
Should there be a way for me to recover from this? Because the notebook gets converted to v4 format but I cannot save it.

**Comment by Carreau** [comment]
You should be able to save it with the new format. Do you get the error on save or load ?

**Comment by abeguerra** [comment]
I get the above error on load. I get the following error on save:
Unexpected error while saving file: 02_pandas.ipynb pop() takes at most 1 argument (2 given)

**Comment by rossant** [comment]
> are these generated with ipymd ?

No they aren't. I think I used a custom process to convert them so I'm not really surprised they are not completely valid. :(

I'll try to update all notebooks to nbformat v4 soon.

**Comment by Carreau** [comment]
Just changing `"metadata" : []` to `"metadata" : {}`  should work. Though if you use normal IPython, I'm curious on how you got these.

We should probably try to handle that in a more reliable way. 

Also if you have custom code to generate notebook, v3 and v4 validator should be importable to check automatically.

**Comment by abeguerra** [comment]
I'm using normal Jupyter and I got the notebook in from the notebooks dir from the command line with the mv command.

**Comment by parente** [comment]
I've run into this too. I understand it's difficult (probably impossible) for nbconvert to fix an invalid notebook that I've moved into the notebooks directory. But it would be nice for the UI to warn me that, in addition to the notebook being invalid, I will not be able to save my changes (whereas, right now, I can make edits and only find out that I can't actually save them when I press Cmd-S).

I think I saw in a separate case where the notebook's kernel is not found, that when the user clicks "Continue with no kernel", the notebook is placed in a read-only. Can we do that here for invalid notebooks?

**Comment by rossant** [comment]
@abeguerra @Carreau @parente I've started to fix and convert all cookbook notebooks to IPython 3/nbformat v4. Feel free to test the [pull request](https://github.com/ipython-books/cookbook-code/pull/16)!

**Comment by rossant** [comment]
Sorry about the metadata problem; it was probably a bug in my homemade notebook transformation process. IPython 2.0 never told me that the notebooks were invalid, whereas IPython 3.0 did, so I only discovered the problem now. The PR above fixes the problem and updates all notebooks to v4.

**Comment by Carreau** [comment]
No problem, we had kind-of a schema in 2.0, but the format and our code was not designed with the schema so we were not enforcing validation. 

Note that invalid notebook that load should work on 3.0 and can be save. You case is just really special in that `list.pop` can take only 1 arg in python, while dict can take 2. 

So you are bitten by the combinaison of upgrading, being bad format, and the specific case of your metadata being a list, so I doubt this is worth fixing that. It would require some hairy heuristic in `IPython/nbformat/v4/rwbase.py` that would work for this specific case but not in others.

I'm going to close, but will be happy to reopen if we see problem like that a lot.

**Comment by Carreau** [comment]
Note: if fix needed : 
``` 
IPython/nbformat/v4/rwbase.py", line 69, in strip_transient
        cell.metadata.pop('trusted', None)
TypeError: pop() takes at most 1 argument (2 given)
```

Because metadata is in this case a list and not a dict.

**Comment by rossant** [comment]
Agreed, I don't think there's anything to fix in IPython (unless someone else has a similar problem with other notebooks). My PR in `cookbook-code` should solve the problem for good, as long as the book readers update their git repo.
