### ISSUE TITLE
Holding the space bar to scroll down the document doesn't work.

### ISSUE THREAD

**Issue by jdfreder** [ipython/ipython#7873]
Tapping the space bar works, holding it for an extending period of time behaves strangely.  This is a side effect of using smooth scrolling.  We need to complete the existing scroll and then execute the next scroll.

When I start moving my cursor again, I have stopped holding the space bar:

![kbscrollbug](https://cloud.githubusercontent.com/assets/3292874/6382661/5ad3d702-bcff-11e4-9076-0a5dd1cf12d8.gif)

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
