### ISSUE TITLE
Making stdin optional when creating new kernels

### ISSUE THREAD

**Issue by jhamrick** [ipython/ipython#7880]
It would be useful for the `ExecutePreprocessor` (and other things that want to automatically run notebooks on the fly) to be able to easily disable `stdin` -- otherwise, if there is something like a call to `input`, it causes the preprocessor to just hang and eventually time out. I think this would just involve adding a new kwarg to this function: https://github.com/ipython/ipython/blob/master/IPython/kernel/manager.py#L417 and then calling `kc.start_channels(stdin=stdin)`, where `stdin` is whatever value that was passed in (True by default).

Questions:
1. Is there some other way to do this that I missed?
2. If not, does this change sound ok? If so, I'll go ahead and make a PR for it and add an option to disable stdin to the `ExecutePreprocessor` as well.

**Comment by Carreau** [comment]
Hum, I think there is already a way to tell kernels that stdin is not implemented.

**Comment by Carreau** [comment]
stdin -> raw input. , but I guess that what you are encountering.

**Comment by jhamrick** [comment]
Yeah, `raw_input` or `input`, depending on the version of python :)

**Comment by takluyver** [comment]
KernelClient has an `allow_stdin` attribute, and the `execute` method has a similarly named parameter. Setting either to False *should* suffice, though I don't know if we've checked that recently.

**Comment by jhamrick** [comment]
Aha, I missed the argument to `execute` somehow. I'll play around with that and see if it works.
