### ISSUE TITLE
Horse in tab completion.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7887]
In notebook.

```
object.__dict__.__.<tab><delay1><c><delay2><tab>
```

will complete to `copy` `copyopy` `<someting else weird>` depending on the value of `<delay1>` and `<delay2>` especially reproducible if `<delay1>` ~1s and  `<delay2>` ~ (fast enough but not too much).

Discover trying to fix #4777 that might be related.

**Comment by takluyver** [comment]
Should this have been closed by #7889, or is there still some issue?

**Comment by takluyver** [comment]
@Carreau shouldn't this have been closed by #7889?

**Comment by Carreau** [comment]
Oh, yes, it should I guess github does not parse the AND.
