### ISSUE TITLE
"Download as"  menu is lonely and would like a markdown entry.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#7890]
He only got py, html, rst, pdf, ipynb.

Markdown would be a nice addition.

**Comment by minrk** [comment]
This list should really be auto-populated, it seems.

**Comment by Carreau** [comment]
> This list should really be auto-populated, it seems.

It was decided that no IIRC. So it is manually curated. I think the reason was TeX would be useless in menu, plus a few other things I suppose.

**Comment by takluyver** [comment]
Yeah, I think auto populating UI is likely to end up making it less user friendly, because we're not thinking about UI when we're adding to the API.

**Comment by takluyver** [comment]
Fixed by #7893
