### ISSUE TITLE
TypeError: 'module' object is not callable (3.0.0rc1)

### ISSUE THREAD

**Issue by bmcfee** [ipython/ipython#7894]
I've been hitting this with the 3.0.0.rc1 distribution from pypi:

```
WARNING:root:kernel d99b582b-7874-4ca3-a9df-18a4e4b0d319 restarted
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 45, in <module>
    from .config.loader import Config
  File "/usr/local/lib/python2.7/dist-packages/IPython/config/__init__.py", line 6, in <module>
    from .application import *
  File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 65, in <module>
    @decorator
TypeError: 'module' object is not callable
```

Not all of my notebooks trigger this bug, but once it happens, nothing works from that point onwards.  I haven't found any specific common feature to the notebooks that do trigger this, but I'm not sure how exactly to look.  I'm happy to help debug, however possible.

(PS: I looked through the current open and recently closed issues, and didn't see anything that looked like this; apologies if it's already reported/fixed.)

**Comment by Carreau** [comment]
What is the content of CWD of the notebook you try to open ?

**Comment by bmcfee** [comment]
> What is the content of CWD of the notebook you try to open ?

(Assuming CWD = current working directory?)

It's a folder full of ipynb's and their corresponding .py exports.  Here's the [gist](https://gist.github.com/bmcfee/4dcf902785e4c754e901).

Should I be looking for something specific?

**Comment by Carreau** [comment]
> (Assuming CWD = current working directory?)

Yes, sorry. 

any thing that carry the name of a potential python module. like `path.py` `decorator.py` ...Etc. Try moving `cache.py` (and possibly `decorators hack.py`) away, I have issues seeing how `decorators hack` could be imported as decorator. But it seem like something is imported as decorator instead of the right one. 

You can try to shove a `print(decorator.__file__)` just before the line that crash to get a hint I guess.

**Comment by bmcfee** [comment]
Aha!  Sorry, I was mistaken ; this was running from a separate folder which does include a `decorator.py` (derived from `decorator.ipynb`).  I guess this is an instance of pebkac then?

Removing that file seems to have corrected the issue so far.

**Comment by bmcfee** [comment]
Side note: this never happened with 2.3/2.4, but I guess something changed in how cwd is handled.

My previous config had set `c.FileNotebookManager.notebook_dir` to the top-level directory (which does not include that file); it seems like 3 is ignoring this directive though.

Either way, I think I can work around it/fix my broken setup.  Thanks, and sorry for the inconvenience!

**Comment by minrk** [comment]
it's `FileContentsManager.root_dir` now, instead of `FileNotebookManager.notebook_dir`.
