### ISSUE TITLE
IPython Notebook behind apache proxy

### ISSUE THREAD

**Issue by franga2000** [ipython/ipython#7898]
Hi, I'm trying to run iPython Notebook behind an Apache2 proxy and I'm having trouble with WebSockets.

I'd like to have the notebook accessible from <domain>/python/.

Using a few tutorials and the apache wiki, I managed to write this VirtualHosts file:
````python
# Trying to proxy WS requests
ProxyPass /python/api/kernels ws://127.0.0.1:8888/python/api/kernels
ProxyPassReverse /python/api/kernels ws://127.0.0.1:8888/python/api/kernels

# Proxy HTTP requests
ProxyPass /python http://127.0.0.1:8888/python
ProxyPassReverse /python http://127.0.0.1:8888/python
ProxyRequests On

# Spoof headers only if the URL contains "/python/" (I have other stuff on this VHost)
<If "%{QUERY_STRING} =~ /python/">
   Header set Host "http://127.0.0.1:8888/python"
   Header set Origin "http://127.0.0.1:8888/python"

   RequestHeader set Host "http://127.0.0.1:8888/python"
   RequestHeader set Origin "http://127.0.0.1:8888/python"
</If>
```
Here's my notebook profile config:
```python
c = get_config()

c.NotebookApp.ip = '127.0.0.1'
c.NotebookApp.open_browser = False
c.NotebookApp.port = 8888

c.NotebookApp.base_url = '/python/'
c.NotebookApp.tornado_settings = {'static_url_prefix':'/python/static/'}
c.NotebookApp.allow_origin='http://127.0.0.1:8888/python'
c.NotebookApp.notebook_dir = '/home/franga2000/iPython/'
```
I'm getting this error in the NB console (also for /stdin and /iopub:
```
WARNING:tornado.access:400 GET /python/api/kernels/f2d21678-4fef-4cb4-996f-dcee954b54ca/shell (127.0.0.1) 0.44ms referer=None
```
I'm using Apache 2.4.7 on Ubuntu 14.04. Also, the notebook is runing in a virtualenv (doubt its relevant).

What am I doing wrong?

**Comment by Carreau** [comment]
This is just a warning, so I guess it should be fine. 
(sidenote, you should run over https)

Did you had a look at https://github.com/ipython/ipython/issues/5525/ ? (might have changed a bit)

Also ask on Mailing list for wider audience.

**Comment by franga2000** [comment]
It is a warning, but it's returning `HTTP 400` anyways. WebSockets aren't connecting so the app can't communicate with the kernel. Everything else works fine, I just can't execute any code.

I'm planning on using SSL, but I haven't started on that since I can't even get a normal connection to work.

I read #5525 but in the end everyone switched to nginx (can't do) and the solution was never posted.

**Comment by rgbkrk** [comment]
I think your allowed origin should be without the path. That is, instead of

```
c.NotebookApp.allow_origin='http://127.0.0.1:8888/python'
```

It should read

```
c.NotebookApp.allow_origin='http://127.0.0.1:8888'
```

The Origin header is sent by the browser to indicate where a request *origin*ated from. This can be munged by Apache (I definitely don't know Apache though).

**Comment by franga2000** [comment]
I changed the `allow_origin` and the apache header spoofer to `127.0.0.1:8080` and I still get the same errors. Debug mode isn't helpful either

**Comment by cabhishek** [comment]
@franga2000 Did you ever find a workaround? I'm having similar issues running IPython with apache httpd as reverse proxy.

**Comment by franga2000** [comment]
@cabhishek Here's what worked for me: http://stackoverflow.com/a/28819231/1906127

**Comment by Carreau** [comment]
Closing as there is a solution on SO post.
