### ISSUE TITLE
nbconvert heading numbering different in 3.0

### ISSUE THREAD

**Issue by rlabbe** [ipython/ipython#7909]
I have a very large notebook, but I have reduced the problem to a small demo. I am using notebook to generate a book in PDF format, and use the headings to specify chapters, sections, and so on. I.e. 

```
#Chapter 1 
text
##section 1
text
#Chapter 2
txt
```

and so on. I wrote a custom book.tplx file to generate a PDF from the notebook in the style that I want. The notebook is in IPython 3.0 format.

In IPython 3.0 I get this as my table of contents

0.1 Chapter 1
0.1.1 Section 1
0.2 Chapter 2 

In 2.4 I get (by this I mean I run IPython 2.4 on the same IPython 3.0 notebook)

1 Chapter 1
1.1 Section 1
2 Chapter 2

A second difference is that in IPython 3.0 all of the content for both chapters end up on one page, whereas in 2.4 it correctly starts a new page for each chapter (not suprising since 3.0 doesn't seem to recognize that the chapter has changed).

There are other differences, but all I believe due to the fact that IPython 3.0 does not recognize header 1 (#sometext) cells as chapters.

It probably isn't clear from the comments, but it is the behavior of IPython 2.4 that I want.

My commands are:

```
2.4: ipython nbconvert --to latex --post PDF --template book notebook.ipynb
3.0: ipython nbconvert --to PDF --template book notebook.ipynb
```

notebook.ipynb:

```
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Chapter 1"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "hi there"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Section 1"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "more text"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Chapter 2"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "text"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.4.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
```

book.tplx:

```
% Default to the notebook output style
((* if not cell_style is defined *))
    ((* set cell_style = 'style_ipython.tplx' *))
((* endif *))

% Inherit from the specified cell style.
((* extends cell_style *))


((* block docclass *))
\documentclass{book}
\setcounter{chapter}{0}
((* endblock docclass *))

((* block preamble *))
((* endblock preamble *))

((* block title *))
\title{test}
\date{}
((* endblock title *))

((* block abstract *))
\tableofcontents
((* endblock abstract *))

% Define block headings
% Note: latex will only number headings that aren't starred 
% (i.e. \subsection , but not \subsection* )

((* block h1 -*))\chapter((* endblock h1 -*))
((* block h2 -*))\section((* endblock h2 -*))
((* block h3 -*))\subsection((* endblock h3 -*))
((* block h4 -*))\subsubsection((* endblock h4 -*))
((* block h5 -*))\paragraph((* endblock h5 -*))
((* block h6 -*))\subparagraph((* endblock h6 -*))
```

**Comment by rlabbe** [comment]
PDF output in 3.0
![image](https://cloud.githubusercontent.com/assets/5308143/6428680/37c30140-bf5f-11e4-90cf-b3e75865a254.png)

PDF output in 2.4 (using the same IPython 3.0 notebook)
![image](https://cloud.githubusercontent.com/assets/5308143/6428684/50e2491a-bf5f-11e4-8797-3cfe373a3efe.png)

**Comment by minrk** [comment]
Heading cells are removed in 3.x, so all headings are handled via pandoc in markdown2latex. The h1, h2 blocks have no effect anymore. You can influence pandoc's handling of headings, though. It looks like to get what you want, you need only pass the `--chapters` flag to pandoc, which you can do by modifying the `markdowncell` part of the template:

```
((* block markdowncell scoped *))
    ((( cell.source | citation2latex | strip_files_prefix | markdown2latex(extra_args=["--chapters"]) )))
((* endblock markdowncell *))
```

The only difference between that and the block in the base template is the `extra_args=["--chapters"]` bit.

I've uploaded a [complete template](https://gist.github.com/minrk/a78c52034187e725d4df) that appears to achieve what you are after.

**Comment by rlabbe** [comment]
I tried that template and it works in 3.x, thank you. 

So it appears that if/when I switch to 3.0 people on 2.4 can still view the notebooks, but cannot generate PDFs in 2.4. That seems to be by design, so I'll close this. Thanks again for the prompt response.
