### ISSUE TITLE
merge Cell.options_default and Cell.config_defaults

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#7910]
These are two structs that really serve the same purpose, but we didn't finish replacing the old options_default with the new config stuff. This means some customization needs to be in custom.js via options_default, and others via calls to the new config js api. There is no overlap of the things configurable via each mechanism, which is super confusing.

**Comment by minrk** [comment]
I'd like to fix this for 3.1, but I don't know how to do that without breaking options_default, so marking for 4.0.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
