### ISSUE TITLE
Unrecognized flag: '--ext' when using IPython 3.0 + django_extensions 1.5 and Django 1.6

### ISSUE THREAD

**Issue by pebreo** [ipython/ipython#7913]
Hello! I am starting with:

`$ python  manage.py shell_plus --notebook`

and getting:

```
[C 22:39:28.216 NotebookApp] Bad config encountered during initialization:
[C 22:39:28.216 NotebookApp] Unrecognized flag: '--ext'
```

I am using **IPython v3.0 + Django 1.6 + django-extensions 1.5**.

I did a python manage.py shell_plus and I got `True` when I ran this command.

```
$ python manage.py shell_plus
from django.conf import settings; 'django_extensions' in settings.INSTALLED_APPS
```

Finally, IPython/Jupyter works as expected when I run `ipython notebook`.

Here is my `pip freeze` output:

```
Django==1.6
Jinja2==2.7.3
MarkupSafe==0.23
PyYAML==3.11
Pygments==2.0.2
backports.ssl-match-hostname==3.4.0.2
binaryornot==0.3.0
certifi==14.05.14
cookiecutter==0.9.1
django-extensions==1.5.0
gnureadline==6.3.3
ipython==3.0.0
jsonschema==2.4.0
mistune==0.5
mock==1.0.1
ptyprocess==0.4
pyzmq==14.5.0
six==1.9.0
terminado==0.5
tornado==4.1
wsgiref==0.1.2
```

**Comment by Carreau** [comment]
I guess that's a Django that pass some `--ext` flag somewhere ? So I would open an issue on Django relevant project. Otherwise I think it's fine if the flag it just ignored by IPython you should be safe.

**Comment by minrk** [comment]
Is the result different for IPython 2.4, and everything else the same?

**Comment by pebreo** [comment]
It works fine in IPython 2.4, no errors there.

**Comment by minrk** [comment]
I found the issue. The `shell_plus` code is trying to tell the IPython kernel to load an extension by passing an argument on the command-line to the notebook server. IPython 2 allowed specifying arguments to the IPython *kernel* at the notebook command-line. IPython 3, as part of the language-agnostic kernel starting changes, no longer relays the notebook's CLI arguments to the kernel.
