### ISSUE TITLE
Import Button in Notebook

### ISSUE THREAD

**Issue by ardhipoetra** [ipython/ipython#7916]
I found the design of importing notebook in tree view is kind of not intuitive. We have to 'click' the 'bolded' text, instead of link (usually underlined), or button. Is this intentional?

If that's not, I propose to add one button beside the "new" button. It should look like this : 
![screenshot](https://cloud.githubusercontent.com/assets/2739025/6432779/fbd2ed9e-c05d-11e4-847f-0f81f6e2bbc9.png)

**Comment by Carreau** [comment]
Does the drag and drop not work ? The click to import is just here as a fallback for when the drag does not work;

**Comment by mathieu1** [comment]
This has also been discussed in #7788 and a candidate `upload` button proposed in #7805

**Comment by Carreau** [comment]
CLosing as we now have an upload button.
