### ISSUE TITLE
Automatic parenthesis/brackets don't work in IPython 3 notebook

### ISSUE THREAD

**Issue by aflyax** [ipython/ipython#7919]
It used to be that typing open parenthesis or bracket would create a set of an open and a closed parentheses/brackets. Also if you selected some text and then typed the open parenthesis/bracket, that text would now be surrounded by parentheses/brackets. This feature is missing/not working in IPython 3 notebook.

**Comment by mathieu1** [comment]
This is discussed in #7896

**Comment by minrk** [comment]
closed by #7926

**Comment by naught101** [comment]
How can you turn this off? the custom.js solution floating around on stackoverflow no longer works. Also, How can you turn off autoclosing of quotes?
