### ISSUE TITLE
Allow to import existing .py or sphinx .rst into a new (or existing) notebook

### ISSUE THREAD

**Issue by yarikoptic** [ipython/ipython#792]
Now there seems to be no easy way to import existing simple code snippets into a notebook.

Ideally there should be an import button, which given a URI to file or to url would import it into the notebook.

For .py files it should treat independent multiline strings as a markup blocks, and based on indentation/empty lines separate code into  code blocks

For .rst/.txt files assume Sphinx formatting and extract inlined code into code blocks while leaving the rest as markup blocks

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. For a while now we've had both `Upload` button in the Notebook Dashboard, as well as `%load` magic inside a notebook, both of which are now able to handle arbitrary files. 

Thanks everyone and happy hacking! :bowtie:
