### ISSUE TITLE
Blank Notebook, no errors, it just doesn't run

### ISSUE THREAD

**Issue by ZachDischner** [ipython/ipython#7925]
After updating iPython, my notebooks will no longer render. Debug messages show no errors, but any notebooks are just blank. iPython runs just fine, and the notebook intro/nav page pulls up correctly, but not any new/existing notebooks. 

When I try to run a notebook and view "Running" from the nav page, it says "There are no notebooks running"

Here are the logs with debug turned on
![screen shot 2015-03-02 at 9 57 22 am](https://cloud.githubusercontent.com/assets/1893326/6445645/906fde08-c0c2-11e4-9691-f909183c78ae.png)

![screen shot 2015-03-02 at 9 54 14 am](https://cloud.githubusercontent.com/assets/1893326/6445596/2788f550-c0c2-11e4-9b0a-fe13b6dbbffb.png)

![screen shot 2015-03-02 at 9 53 08 am](https://cloud.githubusercontent.com/assets/1893326/6445577/0ac4c1ec-c0c2-11e4-8f12-1a689ca5f355.png)
![screen shot 2015-03-02 at 9 53 03 am](https://cloud.githubusercontent.com/assets/1893326/6445581/101430a6-c0c2-11e4-9e48-e553e06647c4.png)

**Comment by Carreau** [comment]
can you force-refresh the page (this look like stale javascript), and see the javascript console of the browser ?

**Comment by ZachDischner** [comment]
Force refresh does nothing, but the console does show a bunch of JS errors (shoulda checked that first)
![screen shot 2015-03-02 at 10 58 05 am](https://cloud.githubusercontent.com/assets/1893326/6446891/5dc091ec-c0cb-11e4-86b0-4e352456e5f2.png)

**Comment by Carreau** [comment]
o_O how did you update ? 
This look like you are missing some js dependencies.

**Comment by ZachDischner** [comment]
I have a clone of the ipython repo, just did a `git pull origin master`,`git submodule update`.

**Comment by ZachDischner** [comment]
I'm also using the Anaconda Python distribution, and tried a conda update, no change

**Comment by Carreau** [comment]
Was this resolved ?

**Comment by ZachDischner** [comment]
I can’t remember what the resolution was, I think I had an issue with multiple pythons or something. Regardless, after enough updates and reinstalls my iPython works now (thank gods!)

Thanks,

Zach

**Comment by Carreau** [comment]
Ok, great, thanks. Closing !
