### ISSUE TITLE
find an invalid link to pythonxy in the links.txt

### ISSUE THREAD

**Issue by mashenjun** [ipython/ipython#7928]
Hi, 
I found the links to the pythonxy is wrong. It jumps to a irrelevant company. I thinks the right address should be https://code.google.com/p/pythonxy/. I have make a [PR](https://github.com/ipython/ipython/pull/7927) about this.
Thanks

**Comment by mashenjun** [comment]
fix spelling mistake

**Comment by takluyver** [comment]
Fixed by #7927.

For the record, if you've made a PR, there's no need to make an issue about it as well.
