### ISSUE TITLE
Color Themes?

### ISSUE THREAD

**Issue by jackmaney** [ipython/ipython#7931]
I love IPython, but light color themes in editors/IDEs strain my eyes and make them hurt. I've been making do with the themes [from this site](https://github.com/nsonnad/base16-ipython-notebook), but [the CSS breaks on IPython 3.0](https://github.com/nsonnad/base16-ipython-notebook/issues/4). 

Could easily-configurable color themes please be a feature to put on the backlog? And by "easily-configurable", I don't mean fiddling with SCSS/LESS/CSS, etc, but a menu option that brings up a modal screen with a drop-down list of at least a few light theme and dark theme choices (solarized light and solarized dark should probably be included, since they're popular) that get applied (via JavaScript) upon selection.

Thank you for your time.

**Comment by Carreau** [comment]
This is something I tried to tackle in ipython/ipython#7008 but which is still work in progress. 
One of the issues is that the alternative themes quickly get out of sync if nobody uses them. 
So unless someone want to fiddle with css/less to maintain the themes, there are few chances of having themes out of the box. 

Note that with previous linked PR, it would be only a matter of defining values of color/variable, not technically fiddling with css. 

The JS dropdown is almost trivial and was one of the first [extension](https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/styling/css_selector) I [wrote](http://carreau.github.io/posts/02-css-selector.html), but is useless without an actual maintained theme.

**Comment by thmosqueiro** [comment]
@Carreau just out of curiosity: does the css keeps changing a lot from version to version, or the hardest part is actually to maintain (keep updating) the dropdown to select themes?

**Comment by Carreau** [comment]
Depends.  if you live on master, I would expect a few breakage from weeks to weeks but relatively minimal. The hard part is to have a tool that rebuild the css automatically. I suppose ~80-90% of changes people want in themes are values of [variable](https://github.com/ipython/ipython/blob/master/IPython/html/static/notebook/less/variables.less). So should almost never break. 

The rest will mostly be sending changes to main css to make theming easier. 

So if I had to put number, I would say a couple of days to make a good automatic css build tool (you have a starting point above), then probably a couple of hours per week, if you are living on master.

**Comment by thmosqueiro** [comment]
I see. Thanks for the answer!

Apart from the CSS rebuilder (I'm reading the [other thread](https://github.com/ipython/ipython/pull/7008)), I wonder if we had a button like "Import theme", maybe this would at least make it easier for people to use custom "themes" (like packages with css/less/etc). I know today it's a matter of copying this to the right profile folder, but this could actually encourage people to create and share their own themes, couldn't it? And, then, instead of maintaining 4 themes like in your extension, we could try to maintain only a light and a dark theme (changing only colors).

Does that make any sense? I know this is not a priority tho.

**Comment by Carreau** [comment]
Yes, people are interested in themes. And I suppose a few themes availlable on nbviewer wouldn't hurt either. From the top of my head I know that these group people have themes : Plot.ly, Cameron Davidson Pilon fro Bayesian methods for hacker, Lorena Barbara for Aero Python, Damian Avila.

So there si an interest. 

I suppose a "Theme" repo can be separated from IPython core anyway and leave it up to the community. 

So if someone comme along and send the relevant patch that have minimal overhead for developpement, the patches will probably be accepted.

**Comment by thmosqueiro** [comment]
Agreed. I'll check if I can do it myself.

**Comment by rgbkrk** [comment]
Doesn't @damianavila have a dark theme?

**Comment by rsmith31415** [comment]
>I suppose a "Theme" repo can be separated from IPython core anyway and leave it up to the community.

That's an excellent idea.

**Comment by jackmaney** [comment]
:+1: for prettymuch anything that would make theming IPython easier.

**Comment by thmosqueiro** [comment]
If I'm interested in contributing with this, who should I talk to?

**Comment by Carreau** [comment]
Yes he does have a theme, but AFAIK he does not build it form IPython one, which make it difficult to "maintain" in the long run. 

@thmosqueiro you can pretty much just open PRs here with code that add a theme builder. 

Feel free to fork my https://github.com/ipython/ipython/pull/7008 I was not able to figure out how to get min.maps and some other files useful for debugging working. 

The way I see it woking is `build_theme --in <themefile> --out <outfile>` and basically that's it. + extension to load theme for now.

**Comment by thmosqueiro** [comment]
Okay, earlier today I've seen what you did in #7008.

**Comment by damianavila** [comment]
>Doesn't @damianavila have a dark theme?

I have one... but I have to make some updated to make compatible with 3.0
Right now I am using the white one...

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
