### ISSUE TITLE
Add kernelspec remove command

### ISSUE THREAD

**Issue by gibiansky** [ipython/ipython#7934]
When a new version of IHaskell is installed, the user may want to reinstall the kernelspec. I was hoping to offer this behind a `IHaskell install` command, that would install or reinstall the kernelspec as necessary.

However, right now, `ipython kernelspec install` crashes if the kernel already exists, and offers no way to remove a kernel, so there is no way to reinstall a kernel without doing path-specific manipulations, which is what I assume `ipython kernelspec install` was created to avoid.

Is the addition of a `ipython kernelspec remove` or `ipython kernelspec reinstall` command feasible and/or a good idea? I would use it, I believe, but I do not know what the ultimate goal with the ipython command line interface is.

**Comment by takluyver** [comment]
Install does have a --replace flag.

On 2 Mar 2015 19:55, "Andrew Gibiansky" <notifications@github.com> wrote:
>
> When a new version of IHaskell is installed, the user may want to
reinstall the kernelspec. I was hoping to offer this behind a IHaskell
install command, that would install or reinstall the kernelspec as
necessary.
>
> However, right now, ipython kernelspec install crashes if the kernel
already exists, and offers no way to remove a kernel, so there is no way to
reinstall a kernel without doing path-specific manipulations, which is what
I assume ipython kernelspec install was created to avoid.
>
> Is the addition of a ipython kernelspec remove or ipython kernelspec
reinstall command feasible and/or a good idea? I would use it, I believe,
but I do not know what the ultimate goal with the ipython command line
interface is.

**Comment by gibiansky** [comment]
Indeed there is! I looked around for it but didn't find it, but it's right there in `ipython kernelspec install --help`. Sorry!

**Comment by Carreau** [comment]
Does a `remove` make also sens ?

**Comment by gibiansky** [comment]
Logically I think it does but I don't really need one. That said users may want to remove kernels, if only to clean up the elements of their menu bar (e.g. if someone uninstalls Haskell from their system, they want IHaskell gone most likely)

**Comment by takluyver** [comment]
I think remove probably makes sense.

**Comment by takluyver** [comment]
`jupyter kernelspec remove` now exists.
