### ISSUE TITLE
Ipython3.0 notebook - customized profile not loaded

### ISSUE THREAD

**Issue by Aezio** [ipython/ipython#7942]
Hi, not sure this is a bug or a problem with my configuration.
After the upgrade from ipy2.4 to ipy3.0 (with conda) my old work profile is not correctly loaded (basically I have the default settings), if I use the –debug option apparently looks good:

```
[D 09:04:36.657 NotebookApp] {
  'InteractiveShellApp': {'exec_lines': ['import numpy as np', 'import scipy as sc', 'import pandas as pd', 'import quantities as pq', 'import GP', 'import matplotlib.pyplot as plt', '%load_ext autoreload', '%matplotlib inline', '%matplotlib nbagg']},
  'NotebookApp': {'log_level': 10, 'profile': 'work', 'browser': 'chrome'},
  'InlineBackend': {'rc': {'savefig.dpi': 72, 'figure.figsize': (14, 8.0), 'figure.facecolor': (1, 1, 1, 0), 'font.size': 16, 'figure.subplot.bottom': 0.125, 'figure.edgecolor': (1, 1, 1, 0), 'legend.fontsize': 16, 'axes.grid': True, 'lines.linewidth': 1.5}}
}
```

but if I try to use numpy, for example, I get a NameError, the library is not imported 

OS: Win7 64bit  - Python 3.4.1 using conda

Thank you for the great tool and the help

**Comment by takluyver** [comment]
Are those settings in your `ipython_notebook_config.py` file? The notebook config no longer affects the kernel, so you'll need to move them to `ipython_kernel_config.py`.

**Comment by takluyver** [comment]
(but the `NotebookApp` config should still be in `ipython_notebook_config.py`)

**Comment by Aezio** [comment]
Hi , yes, these settings are part of the ipython_notebook_config.py

I can't see any ipython_kernel_config.py in my work profile folder (only ipython_config.py, ipython_notebook_config.py, ipython_qtconsole_config.py and ipython_nbconvert_config.py).
Should I create a new profile and dump there (in the new ipython_kernel_config.py) my configuration?

**Comment by Aezio** [comment]
OK, partially solved.
I have created a new profile and copied my old ```ipython_notebook_config.py``` in the profile folder and edited the new ```ipython_kernel_config.py```. The namespace is correctly populated but my default matplotlib configuration doesn't:

(from ```ipython_notebook_config.py```)
```c.InlineBackend.rc = {'font.size': 16, 'figure.figsize': (14, 8.0), 
                      'figure.facecolor': (1, 1, 1, 0), 'savefig.dpi': 72,
                      'figure.subplot.bottom': 0.125, 'figure.edgecolor': (1, 1, 1, 0),
                      'lines.linewidth' : 1.5, 'legend.fontsize' : 16,
                      'axes.grid' : True}```

**Comment by takluyver** [comment]
> (from ipython_notebook_config.py)

That should be in `ipython_kernel_config.py` as well.

**Comment by Aezio** [comment]
Now it works, I copied the whole  ```InlineBackend configuration``` section to ```ipython_kernel_config.py```. Many thaks fro your help!
