### ISSUE TITLE
IPython 3.0 notebook - tooltip does not show

### ISSUE THREAD

**Issue by klonuo** [ipython/ipython#7944]
Hi,

congratulations on the new release. Notebook looks great. Qt Console starts instantly, unlike in previous versions (at least for me on Windows).

The issue: when I type opening bracket for some function, in the previous version tooltip would show after some small delay, but now nothing happens. Tested on Chrome, FF and IE11.

I would guess there is some new setting I have to enable?

**Comment by takluyver** [comment]
Sorry about this - a few features have been slightly degraded as we've worked on making the frontends more language agnostic. Popping up a tooltip after a `(` is not the right thing for all languages, and we haven't yet worked out a satisfactorily good way of configuring it. So for now, you need to press shift-tab to bring up the tooltip.

**Comment by klonuo** [comment]
Nice. That's even better, I just didn't know the shortcut, as I tried with Tab.
Thanks
