### ISSUE TITLE
Matplotlib widget opens in background

### ISSUE THREAD

**Issue by klonuo** [ipython/ipython#7945]
In previous IPython 2.x with, i.e. executing this in qt console:

```python
import matplotlib.pyplot as plt
plt.plot([1, 3, 2])
```
the focus from IPython console would be lost elsewhere, so user needed to click inside console to regain focus.

In IPython 3 it seems different - the focus is still in console (as it obviously should) but when calling `plt.show()` matplotlib widget is opened in background. Same applies to notebook.

**Comment by tacaswell** [comment]
I assume this is the qt backend?

Did you also update matplotlib recently?

**Comment by klonuo** [comment]
Indeed this happened with qt4 backand and matplotlib 1.4.0 with python 2.7
However same happens with tkagg in same environment, and same happens with matplotlib 1.4.3 on IPython 3 with Python 3.4

**Comment by tacaswell** [comment]
There are too many pronouns for me to clearly understand your message (I am
not sure which behavior 'this' is).

**Comment by klonuo** [comment]
When I execute `plt.show()` matplotlib window pops in background regardless which backend is used or if use matplotlib 1.4.0 or latest 1.4.3.

**Comment by klonuo** [comment]
Further explanation...

```python
>>> import matplotlib.pyplot as plt
>>> plt.plot([1,4,3])
[<matplotlib.lines.Line2D object at 0x04FC3450>]
>>> plt.show()
```

This code block works as expected in Python interpreter.
In IPython 2 after executing `plt.plot()` we'd loose focus from IPython "interepreter".
In IPython 3 focus remains in IPython 3 "interpreter", but executing `plt.show()` opens the plot in background.

Using something like `%matplotlib` or `%pylab` solves the problem, but the point here is that IPython mangles the focus from the expected behavior.

**Comment by takluyver** [comment]
Closing as probably not an IPython bug - we don't control window focus, as far as I know. Feel free to continue using comments to debug.
