### ISSUE TITLE
After clicking on the "Save"  in toolbar the focus does not return to notebook

### ISSUE THREAD

**Issue by udibr** [ipython/ipython#7963]
As a result you need to click back on one of the cells in the notebook to continue editting.
This wasnt the case in ipython 2x. Also this does not happen if I click on another button in the toolbar or if I use File->Save and checkpoint from the menu.

**Comment by takluyver** [comment]
I can reproduce this. The save button appears to be grabbing the focus.

**Comment by takluyver** [comment]
@Carreau , I started looking into this, and I suspect it's the actions refactor that broke it. Can you take a look?

**Comment by Carreau** [comment]
Sure will do. 
It's probably just a `return false` on the right place.

**Comment by Carreau** [comment]
cf #7981 that should fix it.
