### ISSUE TITLE
IPython 3.0 makes matplotlib axes facecolor transparent

### ISSUE THREAD

**Issue by mwaskom** [ipython/ipython#7964]
```python
import seaborn
orig_kws = seaborn.axes_style()

%matplotlib inline
with_mpl_kws = seaborn.axes_style()

{k: {"orig": v, "with_mpl": with_mpl_kws[k]} for k, v in orig_kws.items() if v != with_mpl_kws[k]}
```
```python
{'axes.facecolor': {'orig': '#EAEAF2', 'with_mpl': (1, 1, 1, 0)}}
```

See https://github.com/mwaskom/seaborn/issues/460 for resulting confusion.

Is this intentional?

**Comment by minrk** [comment]
It's intentional, but maybe not a good idea. If I recall, it was @Carreau that made the change. Is that right?

**Comment by mwaskom** [comment]
I think the basic idea makes sense to facilitate using inline plots when the has a non-white background style, but imo it should be an option controlled by a paramter to %matplotlib, if such a thing is possible, and not the default behavior.

**Comment by millejoh** [comment]
Note that with transparent plots if you are using anything but a white background in emacs-ipython-notebook the plots are almost unreadable. Agree that there should be an option in the call to %matplotlib that can control this.

**Comment by mwaskom** [comment]
I could also probably address the "dark notebook background" usecase on the seaborn end with an "inverse" or similarly named style that has transparent axes facecolors and white supporting plot elements...

**Comment by wrobstory** [comment]
Looking at http://nbviewer.ipython.org/github/wrobstory/pydatasv2014/blob/master/Up%20and%20Down%20PyData%202014.ipynb

It appears that all I did was 
```python
import seaborn as sb
sb.set(rc={'text.color': axis_color, 'axes.labelcolor': axis_color})
```
Where axis_color was some white-ish thing.

**Comment by mwaskom** [comment]
Yeah, I am talking about adding a seaborn style that would automatically make plots look something like the vincent plots in that notebook.

But anyway, that's an orthogonal question to what IPython should do by default with `%matplotlib`.

**Comment by Carreau** [comment]
We should probably switch to matplotlib themes in general. Not custom solutions.

**Comment by minrk** [comment]
I started working on the switch to a theme, but just ran out of time before 3.0. I still think that's a good idea, and should make changing things easiest in the most matplotlib-y way.

**Comment by jorisvandenbossche** [comment]
I also ran into this problem of having completely white figures now due to importing seaborn before `%matplotlib inline`

The related PR is #6064

**Comment by tacaswell** [comment]
attn @tonysyu

**Comment by bjonen** [comment]
I guess this is related. When copy pasting inline figures to an external program (e.g. Powerpoint), there is now a black background around the figure.

**Comment by mwaskom** [comment]
In general I think you should avoid copy pasting figures directly from the notebook into presentations. Independent of the parameter settings discussed here, IPython also lowers the DPI of figures in notebook output. This helps keep the size of the notebook down, but it can also degrade text and other smaller figure elements. I think you might find that you get crisper output if you save the figures using matplotlib and then import the resulting files into your presentations.

**Comment by bjonen** [comment]
Agreed, for publications or important presentations it is better to save the figure to file. 

But for quick and dirty presentations, I find it extremely useful to just be able to copy/paste the results from the notebook. One great thing about the notebook is that one doesn't have to come up with figure names and output directories anymore. Plus, others who only have access to the html version, can select figures to extract and add to presentations.

**Comment by tacaswell** [comment]
If you are using mpl 1.4.3 you can use `%matplotlib notebook` (you have to use `%matplotlib nbagg` in IP2) which will get you an interactive figure.  By default the 's' key is bound to save which will open a new window with a normal DPI version of the figure.

**Comment by mwaskom** [comment]
Any progress on this, or at least the possibility of dropping back to the pre 3.0 default behavior in lieu of a full style system implementation? I have noticed this confusing a lot of people as it's really unclear why plots suddenly look different.

**Comment by zonca** [comment]
I also got affected by this, I often work on remote IPython Notebook and right-click to save pngs. Transparent background is annoying, unfortunately setting `facecolor` in `matplotlibrc` does not work either: http://stackoverflow.com/questions/29571179/set-ipython-notebook-inline-plots-background-not-transparent

**Comment by ellisonbg** [comment]
@Carreau why did we change this? Have we reverted the change in 3.1? If we haven't fixed this in 3.1, let's do that for 3.2.

**Comment by Carreau** [comment]
This has been introduced by #6064 (3.0), which closes #5727 (3.0), which itself re-fix  what #4608 (2.x) was doing. 

I can revert the first one, but that will re-open #5727 but that still does not fix global issues that we should be using a matplotlib theme I guess.

**Comment by Carreau** [comment]
See #8336

**Comment by fperez** [comment]
+1 to reverting to pre-3.0 behavior. Will merge #8336
