### ISSUE TITLE
ExecutePreprocessor should run from the notebook's directory

### ISSUE THREAD

**Issue by jhamrick** [ipython/ipython#7967]
If you run `nbconvert` from the command line with the `--execute` flag, but are not in the same directory as the notebook, then the notebook won't run successfully if it depends on external files because the kernel will have been started in the cwd rather than the notebook's directory. So probably `ExecutePreprocessor` should chdir to the notebook's directory first, then chdir back to the original directory.

I'll make a PR for this later today.

**Comment by takluyver** [comment]
It shouldn't need to actually chdir, I think - just launch the kernel with the right working directory.
