### ISSUE TITLE
Large images overflowing in notebook

### ISSUE THREAD

**Issue by ghost** [ipython/ipython#7968]
I think this bug is part of #7701 (which is currently closed):

Very simple example (in Chrome 40.0.2214.115):

Insert a large image in markdown: `![image.jpg "Optional title")`:

![screenshot from 2015-03-04 14 24 48](https://cloud.githubusercontent.com/assets/599274/6492571/41a30d4a-c27a-11e4-83e6-7a8196d3d0e9.png)

![screenshot from 2015-03-04 14 25 27](https://cloud.githubusercontent.com/assets/599274/6492582/593df6e0-c27a-11e4-8bf8-1873c426f488.png)

Now using:

```
from IPython.display import Image
Image(filename='img_test/image.jpg')
```

![screenshot from 2015-03-04 14 27 27](https://cloud.githubusercontent.com/assets/599274/6492635/addd5ef2-c27a-11e4-81d9-6ac9ced17936.png)

In Firefox (36.0):

With Markdown (works great):

![screenshot from 2015-03-04 14 29 04](https://cloud.githubusercontent.com/assets/599274/6492671/eaf42d0c-c27a-11e4-965d-360b97d1bac2.png)

And with `Image` (overflows):

![screenshot from 2015-03-04 14 29 24](https://cloud.githubusercontent.com/assets/599274/6492686/faafb2f2-c27a-11e4-8f3a-1de98202e7e6.png)

**Comment by takluyver** [comment]
Yes, we 'fixed' it in #7721, but it wasn't fully fixed, and some people preferred the older behaviour. So it was reverted in #7818.

**Comment by rsmith31415** [comment]
Right, but it seemed odd that the previous issue remained closed.

I think the resize handler is actually [this](https://github.com/ipython/ipython/blob/b09f7cf936e6397dd02d27a27a6f9668aeb8db7a/IPython/html/static/base/js/page.js):

    Page.prototype._resize_site = function() {
            // Update the site's size.
            $('div#site').height(window.innerHeight - $('#header').height());
         };


which is used here:

    Page.prototype.bind_events = function () {
            // resize site on:
            // - window resize
            // - header change
            // - page load
            var _handle_resize = $.proxy(this._resize_site, this);
            
            $(window).resize(_handle_resize);

            // On document ready, resize codemirror.
            $(document).ready(_handle_resize);
            events.on('resize-header.Page', _handle_resize);
        };

If that is the thing @jdfreder was describing, I don't think it is needed. It is much better to use responsive design for everything.

**Comment by rsmith31415** [comment]
I think now I understand what is the purpose of the resize handler. It is changing the height of the `#site` element to obtain the effect of a sticky header. I commented the `_resize_site` method in `/IPython/html/static/base/js/page.js`:

     Page.prototype._resize_site = function() {
         // Update the site's size.
         //$('div#site').height(window.innerHeight - $('#header').height());
          };

and then I added `position: fixed;` and `width: 100%` to the `#header` in `/IPython/html/static/style/style.min.css`:

     #header {
       /* Initially hidden to prevent FLOUC */
       display: none;
       background-color: #ffffff;
       /* Display over codemirror */
       position: fixed;
       width: 100%;
       z-index: 100;
      }

and included a `top-margin` in `#site` and a couple of media queries to keep the margin between `#header` and `#site`:

    #site {
      width: 100%;
      display: none;
      box-sizing: border-box;
      -moz-box-sizing: border-box;
      -webkit-box-sizing: border-box;
      overflow: auto;
      margin-top: 9em;
    }

    @media screen and (-webkit-min-device-pixel-ratio:0) and (max-width: 651px) {
          #site {
              margin-top: 11em;
            }
        }

    @media (max-width: 646px) {
        @-moz-document url-prefix() {
            #site {
                margin-top: 11em;
            }
        }
    }

The first media query targets webkit browsers and the second targets Firefox. In this particular case, Firefox and Chrome seem to measure width differently. However, in general, that shouldn't be case. As a workaround, I had to use two media queries. I tested in Chrome 41.0.2272.76 and Firefox 36 on Ubuntu and works okay. Maybe this can be helpful to fix the original issue.
