### ISSUE TITLE
Unusual white space at bottom of notebook

### ISSUE THREAD

**Issue by williamgilpin** [ipython/ipython#7969]
When I open locally-hosted notebooks, a strange gray bar appears at the bottom. It cuts off anything beneath it, so it takes up screen real estate. The issue occurs on both Chrome (my default) and Safari (which I never use and I would expect to have default settings). 

![screen shot 2015-03-04 at 4 12 31 pm](https://cloud.githubusercontent.com/assets/8154246/6496531/dff759b0-c289-11e4-9b26-e3b27498bbef.png)

In the second screenshot, I've used the Chrome "inspect element" tool to verify that the browser doesn't see some sort of independent object sitting there:

![screen shot 2015-03-04 at 4 14 24 pm](https://cloud.githubusercontent.com/assets/8154246/6496535/f2a53820-c289-11e4-903e-e2a021db9b93.png)

I'm running the latest version of iPython on Yosemite with Python 3 code. Thank you!

**Comment by rsmith31415** [comment]
Is there a header (with logo, toolbar and menu) in your page? Your HTML indicates (`<div id="header" style="display: none;">...</div>`) that your header is hidden and that the calculation of the height of  `#site` is responsible for the large gray area at the bottom.

**Comment by williamgilpin** [comment]
You're correct, I realized that a long time ago I put some "hide header" code into my custom.js. I just dug up the file and commented out the lines, and now the header is back and the issue has been resolved. Thank you.

**Comment by minrk** [comment]
Thanks for figuring this out.

**Comment by rsmith31415** [comment]
@williamgilpin If you need more space for your code, you can use "Toggle Header" and "Toggle Toolbar" in the View menu.

@minrk No problem.

**Comment by williamgilpin** [comment]
@rsmith31415 That's a good suggestion and one I do sometimes use. Ideally I'd like to hide it by default when I open a new notebook, but it's really not a big deal. Also thanks @minrk, the new Jupyter looks really fantastic.

**Comment by takluyver** [comment]
Now that we have frontend config, we could make toggling the header and
toolbar sticky, so the next time you open a notebook, they're in the state
you last had them.

**Comment by Carreau** [comment]
> Now that we have frontend config, we could make toggling the header and
> toolbar sticky, so the next time you open a notebook, they're in the state
> you last had them.

But is it a per notebook ? Or per server config ? :-P

**Comment by takluyver** [comment]
I think per installation (I.e. the obvious way to use frontend config) is
fine. The UI is not part of a particular notebook, and while you might want
to associate that change with a notebook, I think that would be more likely
to confuse users.
