### ISSUE TITLE
Dashboard: Remove hook after shutdown action performed

### ISSUE THREAD

**Issue by michaelaye** [ipython/ipython#7970]
It is slightly annoying that the selection hook stays after I shut down a running notebook via the dashboard. Version: a7fe535e4620 (3.0.0rc1)

**Comment by Carreau** [comment]
Tagging as UX/UI, Also known as @ellisonbg .

**Comment by ellisonbg** [comment]
thanks will have a look...

On Thu, Mar 19, 2015 at 9:28 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> Tagging as UX/UI, Also known as @ellisonbg <https://github.com/ellisonbg>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/7970#issuecomment-83841381>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.

**Comment by michaelaye** [comment]
At the time the issues were opened this was the correct repo to open the issue in. Wouldn't it be more correct to copy these issues over to the notebook repo?

**Comment by Carreau** [comment]
> At the time the issues were opened this was the correct repo to open the issue in. Wouldn't it be more correct to copy these issues over to the notebook repo?

Yes, though there is a large number of opened issues and some of them are duplicates. So while it would be nice I think the number of issues that would need to be migrated is small. It's also uncertain wether this should be notebook or lab or something else.

The migration bot is also broken – I should work on that, and a close issue can still be migrated reopened. So Far IPython was above 1k opened issue and having an open issue here let people believe it would worked on while the people mostly involved in notebook/lab do not look at issues here so leaving open is that wrong kind of signal.
