### ISSUE TITLE
matplotlib inline cannot display unicode characters

### ISSUE THREAD

**Issue by netheril96** [ipython/ipython#7976]
When using the inline matplotlib backend, it does not display unicode characters properly. Here is a screenshot of that result

![inline](https://cloud.githubusercontent.com/assets/836839/6500794/53f43c4a-c34b-11e4-8171-ba65eb8bd03e.png)

The code to produce it is 

```python
import numpy
%matplotlib inline
import matplotlib.pyplot as plt
plt.plot(numpy.linspace(0, 1, 1000), numpy.random.randn(1000))
plt.title(u'测试样例→☞😄😡')
```

As contrast, here is the output of native (MacOSX) backend:

![native](https://cloud.githubusercontent.com/assets/836839/6500800/6482a51a-c34b-11e4-805d-15f8ebf8e1d1.png)

**Comment by jenshnielsen** [comment]
Does saving a figure (with plt.savefig"('name.png') ) actually work. I think this is likely to be a Matplotlib issue rather than an IPython bug. The inline backend essentially works by saving a figure as png.

**Comment by netheril96** [comment]
@jenshnielsen 

The png file also doesn't work while jpeg works. It is indeed a bug in `matplotlib` itself.
