### ISSUE TITLE
custom.js not loaded

### ISSUE THREAD

**Issue by HyperionAnalytics** [ipython/ipython#7984]
I have a simple custom.js file in default profile. It is not working in ipython v.3.0.0 Works fine in v.2.4.1

```javascript
if (IPython.CodeCell) {
    IPython.CodeCell.options_default.cm_config.autoCloseBrackets = false;
    IPython.CodeCell.options_default.cm_config.lineNumbers = true;
    IPython.CodeCell.options_default.cm_config.cursorBlinkRate = 100;
}
```

**Comment by Carreau** [comment]
Can you give full custom.js ? you might need to require something to get a handle to `IPython.CodeCell`

**Comment by HyperionAnalytics** [comment]
What you see above is the full custom.js. In default custom.js, in the comments, it says: "Classes and functions are available at load time and may be accessed plainly:".

**Comment by takluyver** [comment]
I think @minrk noted the other day that custom.js is now getting loaded significantly earlier than it used to. That comment in the default custom.js may well be wrong at present, though I'm not sure whether we'll change the code or the comment.

**Comment by HyperionAnalytics** [comment]
OK, following MB's hint, this seem to work:

```javascript
require([
 'base/js/namespace',
 'base/js/events'
], function(IPython, events) {
    events.on('app_initialized.NotebookApp', function(){
    IPython.CodeCell.options_default.cm_config.autoCloseBrackets = true;
    IPython.CodeCell.options_default.cm_config.lineNumbers = true;
    IPython.CodeCell.options_default.cm_config.cursorBlinkRate = 100;
    });
});
```

I'm not sure if this is the intended way of doing it. Whatever you do, please inform users of proper ways of customizing notebooks.

**Comment by Carreau** [comment]
The problem is that our config system for frontend is still in motion. If we configure it too much, people will rely on it. I changed the wording a bit in #7992
