### ISSUE TITLE
Allow text on toolbar buttons

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#7985]
Toolbar buttons are currently icon-only, which gets confusing as extensions add buttons to the toolbar and try to use the limited set of icons available in Font Awesome.

The add_buttons_group() API should take an additional optional `button_text` key for a very short (usually one word) string to show on the button. icon-only, text-only and icon+text buttons should be allowed.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
