### ISSUE TITLE
Document how to make kernels available in notebooks

### ISSUE THREAD

**Issue by onesandzeroes** [ipython/ipython#7988]
After seeing the new kernel-switching feature in the release notes for v3.0, it took me quite some time to figure out how to make use of it. As far as I can tell the easiest way to make the Python 2 and 3 kernels available through the notebook's menu is to run:

```bash
ipython2 kernelspec install-self --user
```

for both `ipython2` and `ipython3`. Should this be documented somewhere (e.g. the main notebook page in the docs), or is this still considered a bit of an experimental feature without a set public API?

**Comment by minrk** [comment]
Not an experimental feature, we just haven't figured out how/where best to write docs for the IPython kernel. It should go somewhere, probably as an example in the `kernelspec` doc? Maybe on the more detailed install page?

**Comment by JanSchulz** [comment]
My vote would got to including a new headline after http://ipython.org/ipython-doc/dev/notebook/notebook.html#configuring-the-ipython-notebook
```
## Installing new kernels

Running the notebook makes the current python installation available as a kernel. Other python installations (different python versions, virtualenv or conda environments) can be installed as kernels be following these steps:
* make sure that ipython is run with the desired python installation (e.g. activate the environment) 
* make sure that ipython is installed 
* run once `ipython kernelspec install-self --user` (or `ipython2 ...` or `ipython3 ...`)

Kernels for other languages can be found _here_. They usually come with instruction what to run to make the kernel available in the notebook.

The user installed kernel spec files are in ~/.ipython/kernels. 
```

**Comment by Carreau** [comment]
Please feel free to send a PR.

**Comment by JanSchulz** [comment]
as #8020 is merged, this issue can probably be closed.

**Comment by minrk** [comment]
Indeed, thanks.
