### ISSUE TITLE
Portability of IPython running from USB - IPython 3.0

### ISSUE THREAD

**Issue by duytrung** [ipython/ipython#7989]
Hi all,
I install python and IPython, its dependencies on my computer. After that, I copied the whole directory into my USB flash. I tried to work with my IPython on USB in the workplace. However, the computer there assigned a different drive path other than default, e.g. "C:\Python". Therefore, I changed directory to my USB Python Scripts folder, e.g. Z:\Python\Scripts and run this: "ipython notebook" it didn't really work. Let say, the result is "C:\Python\python.exe" ".....scripts\path\...".

How to fix this problem, to run Ipython in a portable manner in the future releases no matter what path of python located?

Great thanks!

**Comment by Carreau** [comment]
Have a look at https://github.com/winpython/winpython 

But IPython notebook itself have complex dependencies, and is not made to work in a portable manner.
