### ISSUE TITLE
Consider always installing with setuptools

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#7994]
Bear with me.

With the increase in popularity and dependency count of `ipython[notebook]`, we should consider `python setup.py install` requiring setuptools. The reason being if IPython is *not* installed with setuptools, `ipython[notebook]` and other extras are undefined. This means that other packages can never depend on any IPython extra, because they might be impossible to install (cf jupyter/jupyterhub#181). The simplest example of this is IPython installed with `conda install ipython-notebook`. All dependencies are present, but because setuptools wasn't invoked, a dependency on `ipython[notebook]` cannot resolve. For that specific case, I can ask Continuum to use `pip install .` for the IPython package instead of `setup.py install`, but I think it's a general issue.

I think this is a temporary problem, because the Big Split™ will make `jupyter-notebook` (or whatever) a regular package that can be required. That being the case, I think we should consider this for 3.1 or not at all.

**Comment by takluyver** [comment]
Given that we've held out this long, I hope we can hold out to 4.0, where
we shouldn't need any extra dependency groups.

**Comment by minrk** [comment]
okay, then I think we should make it clear that *no downstream projects* should depend on `ipython[anything]`.
