### ISSUE TITLE
Making a copy of an open notebook only copies (auto)saved changes

### ISSUE THREAD

**Issue by mathieu1** [ipython/ipython#8001]
`File > Make a copy...` merely makes a copy of the notebook file **in its current (auto)saved state**. This is particularly troublesome when autosave is enabled: from the user standpoint, making a copy results in a copy of the notebook *at some random point in time in the last x minutes* (and this will often go unnoticed, looking like it includes the latest changes).

I would definitely expect `Make a copy...` to include all latest change (otherwise I would go in the dashboard and duplicate the notebook).

A possible way to remove any ambiguity would be a `File > Save as...` dialog (although the exact behavior with respect to Save or Save+Checkpoint would remain a bit unclear). To make it closest to `Make a copy...` one could optionally
- make the default file name being the usual `....-CopyN.ipynb`
- include both a `Save` button and a `Save and Open` button

A minor side issue : the `File` menu does not close in the original notebook upon making a copy.

*Edit:* I'd be happy to open a PR for this if there is a clean and cheap way of reusing current code, but I haven't quite found how to do that yet, and I'd rather leave this to someone else if tweaking the save mechanism is required.

**Comment by dsblank** [comment]
BTW, this issue also occurs with other nbextensions, such as our "Publish" and "Submit"...  should be a general API call that is recommended to do before doing any of these functions (maybe there is, but just need to be aware of it).

(That File menu minor issue should be made as a separate issue... I find that annoying too)

**Comment by minrk** [comment]
I don't understand the expectation that copying a notebook would copy changes that haven't been made yet. The server has no idea that the user has changes that haven't been saved.

**Comment by minrk** [comment]
I misunderstood a bit. I think triggering save on copy should cover this, just like we do when you try to download a notebook.

**Comment by minrk** [comment]
Fixed by #8006
