### ISSUE TITLE
shift-tab function help unusable in jupyter notebook

### ISSUE THREAD

**Issue by jkokorian** [ipython/ipython#8003]
Previously when I would press shift-tab in the IPython notebook, I would get a nice dropdown with the function signature and a short description. Pressing shift-tab again would show the complete docstring and some additional info.

In the new jupyter notebook however, when I press shift-tab, I get the following:

    Type:        function
    String form: <function test at 0x000000002B44A978>
    File:        d:\jkokorian\my documents\_delft\phd\journal\2015-03-04 pm13.tri4-c measurements\2015-03-04 endurance measurement\<ipython-input-30-aa82faa501ff>

Which is information that I really never care about. Can it be changed back to the original behavior? The current implementation makes the shift-tab function completely unusable.

**Comment by takluyver** [comment]
Already fixed in master for 3.1. On my tablet now, or I'd look up the PR number.

**Comment by jkokorian** [comment]
Awesome!

**Comment by takluyver** [comment]
PR was #7903.
