### ISSUE TITLE
Automatically export a notebook as a script upon saving

### ISSUE THREAD

**Issue by drorata** [ipython/ipython#8009]
In earlier versions it was possible to run `ipython notebook --script`; this assured that upon saving of the notebook a script copy (`.py`) will be exported as well. This could be very helpful when trying to put a [notebook under version control](http://stackoverflow.com/a/25765194/671013).

According to the [release announcement](http://ipython.org/ipython-doc/3/whatsnew/version3.html) this option is deprecated. However, the alternative suggested does not handle this automatically. What is the proper way to mimic the previous behavior using 3.x? Is there some configuration that can be done? Something like: `c.FileNotebookManager.save_script = True`?

**Comment by minrk** [comment]
You can use `FileContentsManager.post_save_hook` to define a function that fires after every save, which can call `nbconvert --to script [filename]` on notebooks.

**Comment by drorata** [comment]
@minrk Thanks! I forgot to mention that I saw this docstring, but it was too cryptic for me. Can you please provide a full "tutorial"? How do I use this hook? How do I pass the current notebook to `nbconvert`?

**Comment by minrk** [comment]
@drorata yup, sorry for being short, we're in a meeting. Here is an example (in `ipython_notebook_config.py`):

```python
import os
from subprocess import check_call

def post_save(model, os_path, contents_manager):
    """post-save hook for converting notebooks to .py scripts"""
    if model['type'] != 'notebook':
        return # only do this for notebooks
    d, fname = os.path.split(os_path)
    check_call(['ipython', 'nbconvert', '--to', 'script', fname], cwd=d)

c.FileContentsManager.post_save_hook = post_save
```

That's the simple version for exporting files to scripts on save. It's more efficient but more complex to avoid instantiating an nbconvert process by using an Exporter locally.

**Comment by drorata** [comment]
Thanks! Seems to do the trick. 

BTW: What's the right way to do the opposite? Import a script (that was exported using `nbconvert`) into a notebook?

**Comment by minrk** [comment]
> What's the right way to do the opposite?

There isn't one. The closest we have now is making a new notebook, and loading the script into a cell with `%load script.py`.

**Comment by drorata** [comment]
I guess this, and indeed I saw, this issue is discussed often. The solution you propose is rather limited, since it puts all the cells into a single one. :-1: 

Thanks anyway!

**Comment by watsonix** [comment]
@minrk, thanks for making this little hook! super useful.

**Comment by masnick** [comment]
In case anyone is trying to get [this code](https://github.com/ipython/ipython/issues/8009#issuecomment-78154448) to run, it's missing `c = get_config()`.

As far as I can tell, it works fine on both Python 2 and Python 3.

To figure out which folder to save the `ipython_notebook_config.py` file in, run `ipython locate profile default`.

**Comment by Teodormz** [comment]
For us this is actually less convenient than having --script command. I have a team of people, every one runs their own installation of Anaconda on their machines (similarly to as if you have your own installation of Eclipse, VS, compilers, etc.: very reasonable).
Asking them to add the lines to ```ipython_notebook_config.py``` is more burdensome than asking them to run notebooks with --script command by default. Also, not all the notebooks need to be converted to .py, the ones which aren't shared are good the way they are.

Do you have a simpler solution? Can you not deprecated --script option please?

**Comment by mobiusdumpling** [comment]
**Update:** This solution is broken in iPython version 4, because of "The Big Split" of Jupyter from iPython. To adjust this solution to version 4, use the command `jupyter notebook --generate-config` to create a config file. The command `jupyter --config-dir` finds out which directory contains the config files. And the code snippet given by @minrk should be added to the file named `jupyter_notebook_config.py`. The rest works as before.

**Comment by gothug** [comment]
So, isn't there any way to import the notebook from .py file back into multiple cells (not single one) as it was when I exported it with nbconvert?

Thanks.

**Comment by drevicko** [comment]
Note that, though there is an option `c.NotebookManager.save_script = True` suggested in `jupyter_notebook_config.py`, this doesn't work (at least in Jupyter 4.0.6). You need to add Min's scirpt from above.

**Comment by chaltik** [comment]
Please note that at least under Anaconda distribution for window the above script does not work. The line ` check_call(['jupyter','nbconvert', '--to', 'script', fname], cwd=d)
`
should be replaced with
 ` check_call(['jupyter-nbconvert', '--to', 'script', fname], cwd=d)
`

**Comment by minrk** [comment]
@chaltik that is not quite accurate. If `jupyter nbconvert` does not work, then something is wrong with the environment. The `jupyter-nbconvert` string should not be hardcoded, instead the subcommand should be used.

**Comment by gsauthof** [comment]
@watsonix `--to python` and `--to script` are equivalent. Apparently, `--to script` was introduced as language-agnostic alias for `--to python`.

**Comment by takluyver** [comment]
They're equivalent for notebooks written in Python. For notebooks in other languages, `--to python` might get things wrong (e.g. Python style `# comments` don't work in all languages)

**Comment by eddy-ojb** [comment]
Hello,

I have followed minrk's instructions but am struggling to get this to work with Jupyter on Windows and get the following error. Is anyone able to guide me as it is a bit too cryptic for me.

TypeError: Item in ``from list'' must be str, not unicode
[E 13:03:57.362 NotebookApp] Post-save hook failed on C:\Users\edward\OneDrive\01_Data_Science\test.ipynb
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda2\lib\site-packages\notebook\services\contents\filemanager.py", line 115, in run_post_save_hook
        self.post_save_hook(os_path=os_path, model=model, contents_manager=self)
      File "C:\Users\edward\.jupyter\jupyter_notebook_config.py", line 34, in post_save
        check_call(['jupyter', 'nbconvert', '--to', 'script', fname], cwd=d)
      File "C:\ProgramData\Anaconda2\lib\subprocess.py", line 186, in check_call
        raise CalledProcessError(retcode, cmd)
    CalledProcessError: Command '['jupyter', 'nbconvert', '--to', 'script', 'test.ipynb']' returned non-zero exit status

Where is providing the unicode string? How do I provide a string it can interpret?

My versions of jupyter are as follows:

jupyter                   1.0.0                    py27_3
jupyter-contrib-core      0.3.0                     <pip>
jupyter-highlight-selected-word 0.0.10                    <pip>
jupyter-latex-envs        1.3.8.2                   <pip>
jupyter-nbextensions-configurator 0.2.4                     <pip>
jupyter_client            4.4.0                    py27_0
jupyter_console           5.0.0                    py27_0
jupyter_core              4.2.1                    py27_0
notebook                  4.3.1                    py27_1

Best regards

Ed

**Comment by takluyver** [comment]
What about the version of nbconvert? Is there a traceback before that error message? This sounds similar to jupyter/nbconvert#362 and [this SO question](http://stackoverflow.com/questions/38723801/typeerror-when-executing-jupyter-nbconvert).

**Comment by eddy-ojb** [comment]
Thank you very much takluyver!

I put this in 'jupyter_nbconvert_config.json'

{
  "Exporter": {
    "template_path": [
      ".",
      "c:\\users\\edward\\.jupyter\\jupyter_contrib_nbextensions\\src\\jupyter_contrib_nbextensions\\templates"
    ],
    "preprocessors": [
      r"jupyter_contrib_nbextensions.nbconvert_support.CodeFoldingPreprocessor",
      r"jupyter_contrib_nbextensions.nbconvert_support.PyMarkdownPreprocessor"
    ]
  },
  "version": 1
}

Cheers

Ed

**Comment by takluyver** [comment]
I'm not quite sure where the `r` fix came from - as far as I know, it's just making the config file invalid JSON, so nbconvert will ignore it. It's equivalent to removing that file.

I'm still interested in whether you're using the latest version of nbconvert, because I think that issue should already be fixed if you are.

**Comment by eddy-ojb** [comment]
The versions of nbconvert and nbformat are:

nbconvert                 4.2.0                    py27_0
nbformat                  4.2.0                    py27_0

**Comment by eddy-ojb** [comment]
Thanks. I updated to nbconvert 5.1.1 and it works without the "r".

**Comment by kambysese** [comment]
I've managed to get the hooks in this thread to work (somewhat) producing desired `.py` and `.html` files after a checkpoint. However, I am getting a `ValueError: No JSON object could be decoded` having to do with my nb config `.json` file that I don't really understand. Any ideas what I am doing wrong here?

I am working in a Py27 Anaconda virtual env with following packages:

> jupyter 1.0.0 
> jupyter_client 5.1.0
> jupyter_console 5.1.0
> jupyter_core 4.3.0
> nbconvert 5.2.1
> nbformat 4.4.0

My `jupyter_nbconvert_config.json` file looks like:
```
{
  "Exporter": {
    "template_path": [
      ".",
      "/home/ktavabi/.jupyter/templates"
    ],
    "preprocessors": [
      "jupyter_contrib_nbextensions.nbconvert_support.CodeFoldingPreprocessor",
      "jupyter_contrib_nbextensions.nbconvert_support.PyMarkdownPreprocessor"
    ]
  },
  "version": 1
}
```
I get the following error in the console:

> [NbConvertApp] ERROR | Exception while loading config file /home/ktavabi/.jupyter/jupyter_nbconvert_config.json
> Traceback (most recent call last):
>   File "/home/ktavabi/miniconda3/envs/andrea-anders/lib/python2.7/site-packages/traitlets/config/application.py", line 562, in _load_config_files
>     config = loader.load_config()
>   File "/home/ktavabi/miniconda3/envs/andrea-anders/lib/python2.7/site-packages/traitlets/config/loader.py", line 406, in load_config
>     dct = self._read_file_as_dict()
>   File "/home/ktavabi/miniconda3/envs/andrea-anders/lib/python2.7/site-packages/traitlets/config/loader.py", line 412, in _read_file_as_dict
>     return json.load(f)
>   File "/home/ktavabi/miniconda3/envs/andrea-anders/lib/python2.7/json/__init__.py", line 291, in load
>     **kw)
>   File "/home/ktavabi/miniconda3/envs/andrea-anders/lib/python2.7/json/__init__.py", line 339, in loads
>     return _default_decoder.decode(s)
>   File "/home/ktavabi/miniconda3/envs/andrea-anders/lib/python2.7/json/decoder.py", line 364, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/home/ktavabi/miniconda3/envs/andrea-anders/lib/python2.7/json/decoder.py", line 382, in raw_decode
>     raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded
