### ISSUE TITLE
input_area height problem of ipy3.0 notebook on older firefox (24.3)

### ISSUE THREAD

**Issue by stonefly** [ipython/ipython#8011]
The input_area height is not correct if less than two characters are typed.

The problem starts occuring from 3.0, and does not exist on newest firefox 35+.

![untitled](https://cloud.githubusercontent.com/assets/689302/6579416/0eed69be-c742-11e4-8678-2b898e1f4b5d.jpg)

**Comment by takluyver** [comment]
I doubt we're going to spend time fixing problems on unsupported older versions of browsers. Even as an ESR, Firefox 24 has been superseded now. Can you reproduce it on the current ESR (31)?

http://en.wikipedia.org/wiki/Firefox_release_history

**Comment by stonefly** [comment]
Hi, I cannot reproduce it on the current esr (31).

**Comment by takluyver** [comment]
Thanks for checking. Closing as I don't consider Firefox 24 a supported browser.
