### ISSUE TITLE
inspect_request breaks compatibility with emacs-ipython-notebook

### ISSUE THREAD

**Issue by millejoh** [ipython/ipython#8013]
While inspect_request is designed to be more generic and usable with a variety of kernels (i.e. not just IPython) I think Jupyter has taken a step back in functionality by having the IPython kernel return a string instead of structured JSON like with object_info_request in v4.0 of the kernel spec.

Is it possible to provide some sort of backward-compatible support for object_info_request as defined in v4.0 of the kernel spec? As it stands now the current implementation of inspect_request breaks emacs-ipython-notebooks tooltip functionality.

One thought would be to have IPython return text/json as the value for the data key as it did in the 2.x series.

**Comment by minrk** [comment]
We could return the structured data as JSON, but I don't think we should. How does emacs-ipython-notebook handle tooltips coming from Julia, Haskell, Ruby, and R? Structured introspection data isn't really sustainable in a language agnostic way. I would recommend emacs-ipython-notebooks tooltip handle the tooltip that the kernel has rendered, if at all possible.

**Comment by millejoh** [comment]
For now the goal with EIN is to be a super awesom REPL for IPython - along the lines of what SLIME aims to be for Common Lisp. I'll have to give some serious thought as to how that means as far as other languages are concerned.

Strings are a great data structure for hiding complexity - which is probably the right tradeoff for Jupyter since it aims to support a variety of languages, each with its own ways of doing object introspection. The disadvantage is additional work on the part of the client if we want to go any deeper than simply returning a function's docstring.

After giving this some more thought I think the right thing to do for ein is not depend on the messaging protocol to perform introspection and rather use Python's well-documented inspect module.

Thanks for taking the time to comment.
