### ISSUE TITLE
Markdown cell border overwrites text

### ISSUE THREAD

**Issue by rlabbe** [ipython/ipython#8014]
If you use css to format your notebook the black border tends to slightly overlap the text on the right hand side of the page. The overlap is on the order of 1/2 of a character, and only on the longest lines. Perhaps the css is 'bad'; I am not a web developer, but I know this is new behavior.

To duplicate: put the following in a code cell and execute it. Then, click on a paragraph of text and observe the bounding box. 

```
from IPython.core.display import HTML
HTML('https://raw.githubusercontent.com/plotly/python-user-guide/master/custom.css')
```

Note that I did not write that css file. This is the one I'm using, and it has the same results as the one above.

https://raw.githubusercontent.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/master/styles/custom2.css

environment: anaconda 64 bit, Python 3.4, IPython 3.0.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
