### ISSUE TITLE
Loading notebook causes runaway memory consumption in Chrome

### ISSUE THREAD

**Issue by dhermes** [ipython/ipython#8016]
This was a student's submission in Math 228B at Berkeley (I am the GSI / grader).

It is pegging 100% of CPU and failing to load:
![screen_shot_001](https://cloud.githubusercontent.com/assets/520669/6588024/52fe1c14-c749-11e4-84ec-cff0da344a10.png)

I have been trying to diagnose the issue but can't place it. For the student's privacy I am avoiding uploading the file, but would be happy to email to someone personally.

---

The notebook is in v3 format. I tested both in IPython 2.4.1 and IPython 3.0.

**Comment by Carreau** [comment]
Sure, mbussonnier(at)berkeley.edu or even security(at)ipython.org and ref the issue.

**Comment by dhermes** [comment]
Sent. Thanks for the quick ack.

**Comment by rgbkrk** [comment]
Nice, this notebook makes a tmpnb server slow to a crawl (but not the overall system - yay for resource limits).

**Comment by Carreau** [comment]
Too many stream output, 

I'm collapsing them, and sending back a working version.

-- 
M

**Comment by dhermes** [comment]
That's what I figured it was. It seems strange that such a notebook was able to be created.

**Comment by Carreau** [comment]
Le 10 mars 2015 à 17:37, Danny Hermes <notifications@github.com> a écrit :

> That's what I figured it was. It seems strange that such a notebook was able to be created.
> 

No, I think this is because Browser have just lots of dom nodes to be created at once. 
If you do it progressively should be fine. 

I send you a comprised stream version. 
This should not happened on IPython 3. 
-- 
M

**Comment by dhermes** [comment]
Thanks guys!

Feel free to close out if you don't think the rewrite should occur as in  `ipython nbconvert --to notebook` does.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.

**Comment by dhermes** [comment]
WFM, thanks for all you do @Carreau!
