### ISSUE TITLE
Tooltips in "User Interface Tour" are not working properly

### ISSUE THREAD

**Issue by rsmith31415** [ipython/ipython#8018]
There is a small issue in the User Interface Tour in master. The tooltip that points at Keyboard Shortcuts is not opening the menu.

![screenshot from 2015-03-11 01 02 51](https://cloud.githubusercontent.com/assets/599274/6591939/93397a24-c78c-11e4-8cfb-93917986f4af.png)

This only happens after clicking on the arrows to move to the next tooltip. If I use the keyboard, then it works as expected.

In "complex" notebooks, the Tour generates a double scrollbar because it positions the tooltip below the notebook. Usually, this occurs at step 7.

![screenshot from 2015-03-11 01 06 58](https://cloud.githubusercontent.com/assets/599274/6592004/6a190942-c78d-11e4-8fad-301a024ed19a.png)

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
