### ISSUE TITLE
"Keyboard Shortcuts" modal dialog is scrolling down automatically

### ISSUE THREAD

**Issue by rsmith31415** [ipython/ipython#8019]
When I open the Keyboard Shortcuts modal dialog, it scrolls down a bit without user interaction:

![output](https://cloud.githubusercontent.com/assets/599274/6605485/f9e0a112-c7f5-11e4-850f-dd2f474658b6.gif)

This occurs in Firefox 36 and Chrome 41.

**Comment by minrk** [comment]
I suspect this is because the close button is being focused. The inner content of the dialog should probably be scrolled.

**Comment by rsmith31415** [comment]
Good observation. I removed `focus()` here (in  `ipython/IPython/html/static/base/js/dialog.js`):


        modal.on("shown.bs.modal", function() {
            setTimeout(function() {
                footer.find("button").last(); // here was .focus()
                if (options.open) {
                    $.proxy(options.open, modal)();
                }
            }, 0);
        });

and that fixes it. 

Do you know what unintended consequences this change might have?

**Comment by Carreau** [comment]
Dialog is used in many places, and would make closing the dialog with keyboard in many cases difficult. 
notebook restart, kernel dead, error writing, basically everything that pop you a information message.

**Comment by rsmith31415** [comment]
That's what I thought. Is there any other solution? Maybe adding a parameter to the modal object to explicitly allow focus on the default option?
