### ISSUE TITLE
Where is the move cell below?

### ISSUE THREAD

**Issue by re4lfl0w** [ipython/ipython#8021]
I upgraded ipython 3.0

I confused shortcut.
Where is the move cell below and move cell above?

I investigate shortcult help menu I found combination about X + V.

Do you think X(cut selected cell) + V(paste cell below) more comportable than move cell below and move cell above?

I want to get move cell below and move cell above.
How about?
Thanks.

**Comment by Carreau** [comment]
You can configure the keyboard shortcut and/or toolbar. See example folder.

**Comment by Carreau** [comment]
Related : https://github.com/ipython/ipython/pull/7732
