### ISSUE TITLE
Updating a DropDown or SelectMultiple options (using a dict) is not reflected in the view 

### ISSUE THREAD

**Issue by bobbysan** [ipython/ipython#8022]
When updating the options attribute using a dict after the widget is created, the new options are not reflected in the view. Below are examples:

Works using a list:
```
options=['Apples', 'Oranges',]

w = widgets.SelectMultiple(
    description="Fruits",
    options=options)

options = ['Apples', 'Oranges', 'Pears'] 
w.options = options

display(w)
```

Doesn't work using a dict:
```
options = dict()
options['Apples'] = 'apples'
options['Oranges'] = 'oranges'

w = widgets.SelectMultiple(
    description="Fruits",
    options=options)

options['Pears'] = 'pears'
w.options = options

display(w)
```

List boxes (e.g. SelectMultiple) appear to have the same behavior. I think the view should be updated with the new options when the options attribute is modified using a dict.

**Comment by bollwyvl** [comment]
Looking into this along with #8012!

**Comment by bollwyvl** [comment]
Ah, this is somewhat insidious. So, you're not actually setting it to a new `dict`... if it was going to work at all, it would work as soon as you added the pears, not when you re-assigned it.

If you set `w.options` to something else altogether before setting it to your fruit options again, it will update. Or, tricks like `w.options = tuple(options.items())` would get around this.

Unfortunately, the traitlets are just [not quite ready](http://ipython.org/ipython-doc/dev/api/generated/IPython.utils.traitlets.html)  for the kind of behaviour you expect:
> We don’t support:
> - A full set of trait types. Most importantly, we don’t provide container traits (list, dict, tuple) that can trigger notifications if their contents change.
While this is no longer strictly true, as there are the [EventfulDict](http://ipython.org/ipython-doc/dev/api/generated/IPython.utils.traitlets.html#IPython.utils.traitlets.EventfulDict) and list types, they are not presently available in conjunction with Any (to my knowledge).

**Comment by bobbysan** [comment]
Insidious indeed. Thanks for explaining it. The trick mentioned is good work around.

One other tip: to display options in a particular order in the updated view (in my case alphanumerically) set `w.options = []` and then set `w.options` as desired. Otherwise the new options are just appended to the current ones in the view.
