### ISSUE TITLE
Multiple line Latex output of code cells rendering all on one line.

### ISSUE THREAD

**Issue by damontallen** [ipython/ipython#8026]
As an example this [notebook](http://nbviewer.ipython.org/urls/gist.github.com/damontallen/a2f86b6208ffae6f783f/raw/3b7335fef61d039aa41cdcd8aa520708879e31ee/adjustbox%20problem.ipynb) renders correctly in nbviewer and in the live notebook but when it is converted to Latex the cell output is forced to one line ([pdf output](https://copy.com/hME7bLbRzRryA8GH)).  I've traced the problem to the addition of adjustbox to equation output.  According to the documentation at ftp://ftp.dante.de/tex-archive/macros/latex/contrib/adjustbox/adjustbox.pdf (section 4.10, page 20) minipage must be used with adjustbox to allow for the use of linebreaks - "This allows for line breaks and footnotes in the adjustbox ."  

Adjustbox was implemented in PR  #5694 to limit equations to page width but instead of using "max width" it should be minipage (line 164 of IPython/nbconvert/templates/latex/base.tplx).  However there needs to be an additional addition of '\\' for ever newline in an equation's output and I don't know where that needs to be added.  This also changes the behaviour of the rendering of the equation from centered to left justified even when '$$' was used.  I don't know how to fix this.

**Comment by minrk** [comment]
Thanks for the detailed explanation. Hopefully we can find a fix. It might be that we should back off adjustbox if the new bug is worse than the prior one.

**Comment by Carreau** [comment]
Migrated to jupyter/nbconvert#204
