### ISSUE TITLE
OSX installation via brew

### ISSUE THREAD

**Issue by lunokhod** [ipython/ipython#8029]
Hi, 

This is just a request to have an ipython brew tap created so that it could be installed on osx via brew. given that OSX comes with a working python distribution, I would imagine that this wouldn't be too complicated....

Cheers,

**Comment by Carreau** [comment]
Brew does not want to deals with python install. You can create a tap yourself and or ask them to do it if you like. But I doubt any of us want to take the time to learn ruby and try to convince brew maintainer.
