### ISSUE TITLE
Non-deterministic tests in IPython.core.magic

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#8032]
While debugging other tests, @Carreau noticed that running `iptest IPython.core.magics` sometimes runs 9 tests, and sometimes 10.

**Comment by Carreau** [comment]
That seem to be doctests of functions that have no examples in doctests. So likely not important.
Still it might mean we find the wrong number of doctests here and there.

It also can go as low at 8 and as high as 11 tests for `iptest IPython.core.magics`.

**Comment by takluyver** [comment]
Fixed, we hope, by #10538.
