### ISSUE TITLE
ipython notebook --config doesn't work as ipython --config

### ISSUE THREAD

**Issue by jrellis** [ipython/ipython#8034]
```
{'commit_hash': u'f75fda4',
 'commit_source': 'installation',
 'default_encoding': 'cp437',
 'ipython_path': 'c:\\miniconda\\envs\\base\\lib\\site-packages\\IPython',
 'ipython_version': '3.0.0',
 'os_name': 'nt',
 'platform': 'Windows-7-6.1.7601-SP1',
 'sys_executable': 'c:\\miniconda\\envs\\base\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '2.7.9 |Continuum Analytics, Inc.| (default, Dec 18 2014, 16:57:52) [MSC v.1500 64 bit (AMD64)]'}
```

Create a config file, such as 'ipc.py' here:
```python
c = get_config()
c.InteractiveShellApp.exec_lines = [
  'import numpy as np',
  'import pandas as pd'
]
```

`ipython --config ipc.py` works as expected, doing the imports
`ipython notebook --config ipc.py` has no effect on the loaded kernels

Running with --debug shows the file loaded, but you never see the "Running code" lines.
```
[D 15:05:10.351 NotebookApp] Loaded config file: C:\Users\user\ipc.py
[D 15:05:10.354 NotebookApp] Config changed:
[D 15:05:10.354 NotebookApp] {'NotebookApp': {'log_level': 10, 'extra_config_file': u'ipc.py'}, 'InteractiveShellApp': {'exec_lin
es': ['import numpy as np', 'import pandas as pd']}}
```

**Comment by takluyver** [comment]
The notebook server no longer passes its config over to the kernels - kernels have to be configured with their own config files.

**Comment by jrellis** [comment]
What does the notebook --config option do then? Should it be removed? At least the help text should change as it is identical to the ipython --config help text. Also, does the functionality no longer exist to add an additional config file? All configuration must now be in the ipython_kernel_config.py?

**Comment by takluyver** [comment]
The notebook server is a separate application with its own config - the `--config` option still works for that.

I don't think it's possible to specify a config file for notebook kernels at the command line. This is part of the separation of the language independent parts of IPython, which will become Jupyter. You could use a custom kernelspec that has extra arguments for the kernel.
