### ISSUE TITLE
pip install ipython, Does not work in Ubuntu 14.04

### ISSUE THREAD

**Issue by ChrisDubeau** [ipython/ipython#8042]
When i Tried to install IPython into a Oracle VM VirtualBox that was running Ubuntu 14.04, which has Python installed on it i found that the instructions on http://ipython.org/install.html did not allow me to use IPython after calling "pip install ipython". It does work if i call it from within a forked copy of ipython off of GitHub.
![ipython error](https://cloud.githubusercontent.com/assets/10521003/6645254/8176ab5e-c980-11e4-9d42-c817412fccde.PNG)

**Comment by takluyver** [comment]
Is it possible that `pip` is installing with a different version of Python than the one you're running with `python`? Find where `pip` is with `which pip` and see what the first line (beginning with `#!`) is.

**Comment by ChrisDubeau** [comment]
It appears to be installing into the same version of python.
![error 2](https://cloud.githubusercontent.com/assets/10521003/6645595/81a2cb28-c983-11e4-97b6-8a99d04b89af.PNG)

**Comment by takluyver** [comment]
Do you have `$PYTHONPATH` set? Did `pip install ipython` definitely succeed?

**Comment by ChrisDubeau** [comment]
So it was $PYTHONPATH being incorrectly set. Thank you for the assistance

**Comment by yongqiangzhang1** [comment]
@ChrisDubeau , How to set $PYTHONPATH?

**Comment by carlsmith** [comment]
@yongqiangzhang1, `PYTHONPATH` is a *environment variable*. Environment variables belong to the shell (usually bash, unless you're on Windows). Programs like Python and IPython only reference these variables, so this isn't a good place to explain any of this stuff in detail. See this [StackOverflow question][1], and the relevant [Python docs][2] to learn more.

[1]: http://stackoverflow.com/questions/3402168/permanently-add-a-directory-to-pythonpath
[2]: https://docs.python.org/3/using/cmdline.html#environment-variables
