### ISSUE TITLE
Allow sections to be collapsed and expanded in the notebook

### ISSUE THREAD

**Issue by ccordoba12** [ipython/ipython#805]
I haven't seen this discussed or planned so I thought I should bring it to the table. By cell grouping I mean exactly what _Mathematica_ has: the possibility to group your cells in sections, subsections, etc, which let you easily move, evaluate and eliminate them.

I think one of the most important usability problems with the Sage notebook is the lack of this capability. That's why I don't use anymore but I've also seen on the Sage lists that a lot of people request it.

The only python notebook I know of that has this feature is [codenode](https://github.com/codenode/codenode), now a defunct project by the same guy who developed the Sage notebook. Maybe you can use some of its ideas to implement it here, since it is BSD licensed.

**Comment by drorata** [comment]
Is there any update on this front?

**Comment by mhooreman** [comment]
Hello,

I would find it very interesting. Is there any update on that?

Thanks a lot.

**Comment by pjc42** [comment]
in case you find this before you find the extension, this is now implemented at [nbextensions - collapsible_headings](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/collapsible_headings). seems to work great, many thanks to the contributors...

**Comment by Carreau** [comment]
@meeseeksdev[bot] migrate to jupyter/notebook
