### ISSUE TITLE
Vertical position problems in dashboard

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#8056]
There are a few vertical positioning issues with the checkboxes in the dashboard. First, the cb in the multiple-selector dropdown is too low:

![screen shot 2015-03-14 at 4 54 30 pm](https://cloud.githubusercontent.com/assets/27600/6653478/e9148034-ca6a-11e4-931f-ef0235f34f04.png)

The the count shown, it almost looks like the count integer is 1-2 px too high as well:

![screen shot 2015-03-14 at 4 54 40 pm](https://cloud.githubusercontent.com/assets/27600/6653479/eb74000c-ca6a-11e4-92ab-52db7659310d.png)

In the items, the checkbox is also low: 

![screen shot 2015-03-14 at 4 54 49 pm](https://cloud.githubusercontent.com/assets/27600/6653480/edabae7e-ca6a-11e4-94d6-9db65f3779de.png)

**Comment by takluyver** [comment]
Closed by #8058.
