### ISSUE TITLE
Multiple selector master checkbox has wrong logic

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#8057]
If you hand select a number of items in the dashboard and then use the master checkbox to deselect all of them, it does the opposite (it selects everything). The current behavior is backwards from other similar UIs (Gmail for example). To reproduce, put the dashboard in this state and click the top (master) checkbox:

![screen shot 2015-03-14 at 4 58 13 pm](https://cloud.githubusercontent.com/assets/27600/6653495/82a1623a-ca6b-11e4-9e9c-c254f2bba4fe.png)

Here is a summary of the desired behavior when the master checkbox is clicked:

* If none selected, select all.
* If all selected, deselect all.
* If some selected, deselect all

**Comment by Carreau** [comment]
The curent behavior is the os/browser "native" one. Asked behavior requires to reimplement the checkbox without using native one, or completly highjiking browser behavior. So can't do with current manpower.

**Comment by minrk** [comment]
Or try #8059
