### ISSUE TITLE
Keep current input cell at the top or in the middle of the screen

### ISSUE THREAD

**Issue by abalkin** [ipython/ipython#8061]
When you write a new notebook (as opposed to editing an existing one), the cell that you are editing is often the last cell of the notebook.  In the current UI, editing the last cell is inconvenient for several reasons:

1. It stays at the bottom of the screen.   There is no way to scroll it up the window leaving white space below.
1. Once you execute the code, it jumps up to create space for output and keeps jumping as you update your code based on what you see in the output.

I suggest the following to improve the situation:

1. Allow main window scrolling as long as the last input cell is fully visible.
1. Do not re-scroll on `Ctrl-Enter` even if the output shrinks. 
1. Provide keyboard shortcuts to bring the current cell to the middle, top or bottom of the window.

The second proposal is similar to Emacs' `recenter-top-bottom` function that is bound to `Ctrl-L` by default.   `Ctrl-L`  seems to be available in the notebook UI.

**Comment by takluyver** [comment]
Scrolling behaviour is one of those things that seems to be constantly not quite right.

> Ctrl-L seems to be available in the notebook UI.

Nope, on Linux (and probably Windows) it selects the URL so you can navigate to another address. Basically all Ctrl+something shortcuts are unavailable in browsers.

**Comment by abalkin** [comment]
> Ctrl+something shortcuts are unavailable in browsers.

I think that's true on Linux and Windows only.  On a mac browser shortcuts use "Option", 
![screen shot 2015-03-15 at 6 24 18 pm](https://cloud.githubusercontent.com/assets/535197/6658471/9382ede6-cb40-11e4-9c15-2a3b57a3e1f4.png) modifier.

**Comment by abalkin** [comment]
If we agree that "recenter-top-bottom" is a good action to have, I am sure we can find a key combination to bind this function to.  @takluyver, what do you think about the other two items on my list?

**Comment by takluyver** [comment]
I think your suggestions make sense, but I don't know how easy they are to implement.

I think we used to just add an area of blank space at the bottom of the notebook so there was room to scroll the last cell up. Has that been removed?

**Comment by abalkin** [comment]
> I think we used to just add an area of blank space at the bottom of the notebook

The current behavior (on a Mac) is such that once you have enough material to fill the browser window, the last cell cannot be scrolled up more than about 1 inch from the bottom.  It is likely that this was different in IPython 2 because this behavior if fairly annoying to me now and I don't recall being annoyed by this  in the past.

(I hope this is not browser specific, but I use a recent version of Chrome.)

**Comment by abalkin** [comment]
Hmm, it does look like there is an attempt to add resizable "end_space", but it does not work.

![screen shot 2015-03-15 at 7 11 33 pm](https://cloud.githubusercontent.com/assets/535197/6658687/387c9a44-cb47-11e4-8dac-2f7f38d2204f.png)

**Comment by rsmith31415** [comment]
@abalkin I believe that `.end_space` does work. It is used to add a bit of space at the bottom of the notebook in order to let the user scroll down to the last cell when activating the pager:

![screenshot from 2015-03-15 17 21 19](https://cloud.githubusercontent.com/assets/599274/6658708/bcb1fb16-cb37-11e4-8dc9-6664aca62334.png)

**Comment by abalkin** [comment]
@rsmith31415 - what if the pager is not activated?  Assuming "In [4]" is your last cell.  If you remove `PCA?` and close the pager, - can you move "In [4]" to the middle of the browser window leaving large white ( or grey) area below?

**Comment by rsmith31415** [comment]
@abalkin No. If I close the pager, the `.end_space` is reduced to `min-height: 100px;` but there is no much room to scroll down to put `ln [4]` in the middle of the page. You could increase the min-height to keep the last cell in the middle . Something like this:

![screenshot from 2015-03-15 17 33 33](https://cloud.githubusercontent.com/assets/599274/6658764/8679e642-cb39-11e4-862f-8a60aabd4557.png)

but I'm not sure I like that because it triggers the scrollbars when there is barely any content in the notebook.

**Comment by abalkin** [comment]
For me, `end_space` does not work for the pager either:

![screen shot 2015-03-15 at 7 35 06 pm](https://cloud.githubusercontent.com/assets/535197/6658773/a52daf86-cb4a-11e4-9a20-6fe8fd7773c4.png)

`Ctrl-Enter`

![screen shot 2015-03-15 at 7 35 41 pm](https://cloud.githubusercontent.com/assets/535197/6658772/a52cfb9a-cb4a-11e4-908a-b82c4b1797d1.png)

**Comment by rsmith31415** [comment]
Did you scroll down with your mouse over the notebook (not the pager)?

**Comment by abalkin** [comment]
Aha, yes when the pager is up, I can scroll the cells up to bring the last one above the help pager.

In this issue, I suggest that I should be able to scroll the cells up all the way until the last cell is at the top of the page.

**Comment by rsmith31415** [comment]
Sure, but that's the trick that `end_space` is accomplishing when the pager is activated. I guess it is possible to do what you want. The main problem I see is that there are already some problems with the scrolling, so it would be difficult to try to implement this without solving the other issues first.

**Comment by abalkin** [comment]
@rsmith31415 - can you reference the other scrolling issues here?

The implementation of this issue seems straightforward - just manipulate `min-height` of the `end_element` in the `document.onscroll` handler.

**Comment by Carreau** [comment]
Pro tip. Always replace  "Just" by the following. 
![http://star.psy.ohio-state.edu/coglab/Miracle.html](http://star.psy.ohio-state.edu/coglab/Pictures/miracle.gif)

**Comment by rsmith31415** [comment]
@abalkin 

I've noticed a couple of glitches in the last days. For example, after closing a modal, the scrollbar moves to the bottom and then returns to its original position and this happens somewhat randomly (if I remember correctly, only in Firefox.) Another one is that the pager changes which element is triggering the scrollbar (first the body and then the `#site` element). 

I suppose there are events that are changing a bit the behavior of the scrollbars.

**Comment by abalkin** [comment]
@Carreau - I hear you.  I hope a "work-in-progress" PR will do better than "Just".  See gh-8067.

The end-space manipulation is  in 8a971b6.  It almost works, but I don't think I've got the offset calculations quite right.   Also, I need to add logic to shrink end-space back when it is no longer needed. (Say after scroll to the top followed by recenter.)

Please let me know whether I am on the right track.

**Comment by abalkin** [comment]
It would also be nice to have a shortcut for "execute cell,  insert in place".  Unlike ⌥↩ "run cell, insert below" action which keeps executed cell at the same position and inserts new cell below it, the new action will place new cell where the old cell was by scrolling the notebook up.  I would use ⌘↩ as a shortcut for this action.
