### ISSUE TITLE
Styling the new flex box widget classes - width of IntText

### ISSUE THREAD

**Issue by patricksnape** [ipython/ipython#8064]
# Issue

Attempting to set the width of an `IntText` widget does not change the size of the parent flex box (div). This means that `IntText`  doesn't render properly within a flex layout.

**IPython 3.0**
**Python 2.7**
**All browsers**
# Reproduce

http://nbviewer.ipython.org/gist/patricksnape/ac985babaa9f4df0c7d7
# Details

It seems that `IntText` consists of a 'widget-hbox', which has 'widget-label' and 'text' as children. By changing the width of `IntText`, it seems like only the width of the 'text' is updated and not the one of the 'widget-hbox' object.
Consequently, it is impossible to control the width of the text area when it is part of a `FlexBox`.

Is this the expected behaviour of `IntText`? We weren't sure whether this is a bug or the desired behaviour. How should I change the width of `IntText` so that the width of its `HBox` is also changed?

This was also posted on the mailing list, so apologies if someone was working on a response to this.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
