### ISSUE TITLE
Notebook and console send different messages for completion

### ISSUE THREAD

**Issue by gibiansky** [ipython/ipython#8068]
Typing an identifier into the console and into the notebook, then pressing tab, yield different messages to be sent.

Is this purposeful? Am I misinterpreting the spec here?

Notebook sends:

```
{"text":"","line":".","block":null,"cursor_pos":1}
```

Console sends:

```
{"code":".","cursor_pos":1}
```

IPython version 3.0.0.

**Comment by Carreau** [comment]
Probably the console was not updated to new message spec, and adapter kicks-in.

**Comment by gibiansky** [comment]
Ah, I understand what was happening. I was specifying messaging protocol v4, and console was ignoring that, whereas notebook wasn't. So console was sending me v5 messages while notebook was sending me v4 messages.

I've gone ahead and just updated to using v5. So now both of them send the v5 messages.

This looks like a bug but I don't know how to fix it or whether it's worth fixing; I don't know if you intend to maintain compatibility with v4 kernels, but if you do, then this is a bug.

**Comment by gibiansky** [comment]
Of course, I now get an error 

```
[C 21:31:16.956 NotebookApp] Malformed message: ['<IDS|MSG>', 'ad1ba667a699a3488489b6a178a15d889a0f1c9b587ebb1157e3d176ffdfae4a', '{"username":"username","msg_type":"complete_reply","msg_id":"ab43c9a9-7554-4629-8be5-05fddd9cda42","session":"D8E41E0B8F4F461185EB69AB7E82EB67"}', '{"username":"username","msg_type":"complete_request","msg_id":"352643CB604943FBA420528196EB7CBC","session":"D8E41E0B8F4F461185EB69AB7E82EB67"}', '{}', '{"status":"ok","cursor_start":0,"matches":["putStrLn"],"cursor_end":7,"metadata":{}}']
    Traceback (most recent call last):
      File "/Users/silver/dev/homebrew/lib/python2.7/site-packages/IPython/html/base/zmqhandlers.py", line 181, in _on_zmq_reply
        msg = self._reserialize_reply(msg_list, channel=channel)
      File "/Users/silver/dev/homebrew/lib/python2.7/site-packages/IPython/html/base/zmqhandlers.py", line 162, in _reserialize_reply
        msg = self.session.deserialize(msg_list)
      File "/Users/silver/dev/homebrew/lib/python2.7/site-packages/IPython/kernel/zmq/session.py", line 848, in deserialize
        return adapt(message)
      File "/Users/silver/dev/homebrew/lib/python2.7/site-packages/IPython/kernel/adapter.py", line 367, in adapt
        return adapter(msg)
      File "/Users/silver/dev/homebrew/lib/python2.7/site-packages/IPython/kernel/adapter.py", line 70, in __call__
        return handler(msg)
      File "/Users/silver/dev/homebrew/lib/python2.7/site-packages/IPython/kernel/adapter.py", line 271, in complete_reply
        if content['matched_text']:
    KeyError: 'matched_text'
```

**Comment by gibiansky** [comment]
Why is `version = 4` in `adapter.py` line 363? It says:

```python
    if 'version' in header:
        from_version = int(header['version'].split('.')[0])
    else:
        # assume last version before adding the key to the header
        from_version = 4
```

Is this something that should be updated to `from_version = 5`?

**Comment by takluyver** [comment]
I don't think that needs updating. Version 5 messages should have the
msgspec version in the header - that code treats the message as v4 if it
doesn't say that it's a later version.

**Comment by gibiansky** [comment]
@takluyver Ah, okay. I interpreted the comment "assume last version before adding the key to the header" as "assume that this kernel conforms to whatever the latest messaging spec is".

**Comment by minrk** [comment]
There might be a problem in the console in the initial kernel_info request that is meant to set up the adaptation.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
