### ISSUE TITLE
kernel_ready.Kernel triggered twice when creating a new notebook

### ISSUE THREAD

**Issue by neilzimmerman** [ipython/ipython#8069]
Any time you a pushed directly into a new notebook, the 'kernel_ready.Kernel' is triggered twice from kernel.js. This usually happens when creating a new notebook or "making a copy" from within a running notebook.

**Comment by neilzimmerman** [comment]
This is happening because 'kernel_ready.Kernel' is triggered in kernel.js on line 960 when the new kernel is starting and on line 411 after connecting. Does it need to be triggered the first time? is it really ready if it is not yet connected?

**Comment by minrk** [comment]
The first one is probably triggered inappropriately.

**Comment by takluyver** [comment]
I still see the two trigger calls in the code, but I only get one kernel_ready event when I create a new notebook. Can someone dig into the code a bit?

**Comment by Carreau** [comment]
Need to be migrated to Notebook repo.

**Comment by minrk** [comment]
Migrated to jupyter/notebook#973
