### ISSUE TITLE
[Request] Add shortcut and/or icon for Cell -> Run all (notebook).

### ISSUE THREAD

**Issue by Ismael-VC** [ipython/ipython#8070]
Sometimes it's useful to use this sequence when editing at the notebook:

1. `Esc`, switch to command mode.  
2. `Ctr+00`, restart kernel
3. Select `Cell` -> `Run all`

It would be nice if the third step where a shortcut, I also thought about a shortcut for doing step 2 and 3 at the same time, what do you think?

Even without restarting the kernel a shortcut and/or icon for `Run all` would be very handy.

**Comment by Carreau** [comment]
This has been requested a few times in issues. You can configure it.
