### ISSUE TITLE
Convert from 3.0.0 to 2.x

### ISSUE THREAD

**Issue by dorneanu** [ipython/ipython#8075]
Hi,

is there a way how to convert an IPython Notebook (created with ipython version 3.0.0) to a previous version (say 2.2.0)? 

The problem is that I have a lot of notebooks written with IPython 2.2.0 and don't know how to convert them to the newer version. 

Thx in advance,

Victor

**Comment by takluyver** [comment]
Hi Victor,

On 18 March 2015 at 06:15, Victor Dorneanu <notifications@github.com> wrote:

> is there a way how to convert an IPython Notebook (created with ipython
> version 3.0.0) to a previous version (say 2.2.0)?
>
> The problem is that I have a lot of notebooks written with IPython 2.2.0
> and don't know how to convert them to the newer version.
>

There are a few ways to convert notebooks between different versions. If
you open an older notebook in IPython 3, it will update it and save in the
newer format (you'll see a message saying that this has happened).
Likewise, if you open a new format notebook (from IPython 3) in IPython
2.4, it will downgrade it to the older format. The format used didn't
change between 2.2 and 2.4.

If you want to explicitly convert notebooks at the command line, you can
use IPython 3 with a command like: ipython nbconvert --to notebook
--nbformat 3 MyNotebook.ipynb . IPython 2 uses nbformat 3, and IPython 3
uses nbformat 4.

Thomas

**Comment by davidedelvento** [comment]
Opening new files with the old notebook results in "Error loading notebook - Bad Request" errors which is really frustrating.
