### ISSUE TITLE
IPython notebook presentation mode

### ISSUE THREAD

**Issue by lunemec** [ipython/ipython#8076]
Hello,

I'm often using IPython notebook as a presentation tool for python programs, and I'm wondering if it could be extended with "presentation mode" where you'd have a cell as a slide (or similar) and you could go through them as you would in any other presentation.

Thank you,
Lukas

**Comment by takluyver** [comment]
Try https://github.com/damianavila/RISE ☺

**Comment by Carreau** [comment]
Or [this one](https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/slidemode), but less used and less maintained !
