### ISSUE TITLE
Run commands should be grouped together in help

### ISSUE THREAD

**Issue by abalkin** [ipython/ipython#8089]
In the command mode section, run commands are nicely grouped together:

![screen shot 2015-03-19 at 1 01 25 pm](https://cloud.githubusercontent.com/assets/535197/6735957/3e47f376-ce38-11e4-9f78-2ab41386880d.png)
 
but in the edit mode section they are not grouped and are not presented in the same order.

![screen shot 2015-03-19 at 1 00 42 pm](https://cloud.githubusercontent.com/assets/535197/6735971/5367ede2-ce38-11e4-9488-70de3b9a101b.png)

**Comment by ChrisDubeau** [comment]
I am looking to help with this project and wanted to see if i could fix this issue. With that in mind what section of the project would i find the relevant files that would need to be worked on?

**Comment by abalkin** [comment]
@ChrisDubeau - thanks for your interest in helping the project!

I have recently fixed some other issues in this area and if you look at gh-7809, you will see where the relevant code is.  The order of entries is controlled by the `help_index` attribute in  actions dictionary in IPython/html/static/notebook/js/actions.js.

**Comment by takluyver** [comment]
They are together when I view them, so there must be something varying here.

![screenshot from 2015-03-23 17 10 15](https://cloud.githubusercontent.com/assets/327925/6793308/cf23e0e0-d17f-11e4-8e96-3c39bdebb958.png)

**Comment by takluyver** [comment]
Aha, they're sorted together on Firefox, but not on Chromium.
