### ISSUE TITLE
Terminal (Terminado) only displays single line bash prompts. 

### ISSUE THREAD

**Issue by AGS-Knight** [ipython/ipython#8095]
When starting a new notebook, I noticed that if I choose `Terminal`, it only displays the first line of my bash prompt.  The next line of my prompt, which consists of a few characters (`----->`) is missing.  However, the browser terminal functions properly.  How does terminado and ipython interact in this instance?  Is there somewhere where I can modify the terminal settings?

**Comment by takluyver** [comment]
IPython and the terminal barely interact at all, and there aren't really any settings for it.

What is your prompt? I just tried with a simple multi-line prompt, and I can't replicate a problem. Is it only an issue the first time the prompt is printed, or every time?

**Comment by AGS-Knight** [comment]
This behavior occurs every time the prompt is printed.  
I hadn't yet tried a simple two line prompt, but this is the prompt I'm currently using:

```bash
.:[ user@hostname : 06:26:04 : ~/.ipython/nbextensions/ ]:.
---> 
```
Code:

```bash
bash_prompt_cmd() {
RTN=$?

smiley() {
    if [ $1 == 0 ] ; then
echo "--->"
    else
echo "--->"
       fi
    }
smileyc() {
    if [ $1 == 0 ] ; then
echo $GREEN
else
echo $RED
       fi
    }
 if [ $(tput colors) -gt 0 ] ; then
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
RST=$(tput op)
fi
smiley=$(smiley $RTN)
smileyc=$(smileyc $RTN)
    local CY="\[\033[1;36m\]" 
    local BL="\[\033[1;34m\]" 
    local WH="\[\033[1;37m\]"
    local YE="\[\033[1;33m\]"
    local GG="\[\033[38;5;66m\]"
    local BR="\[\e[1;33m\]"
    local RE="\[\033[1;31m\]" 
    local WHB="\[\033[1;37m\]"
    local PROMPT="${YE}$"
    [ $UID -eq "0" ] && PROMPT="${RE}#"
    local PROMPT_PWD=""
    local PS1_T1="\n$YE.:[ $GG`whoami`@`hostname` $YE: $GG\t $YE:$YE "
    local ps_len=$(( ${#PS1_T1} - 12 * 6 + 6 + 4 )) #Len adjust for colors, time and var
    local PS1_T2=" $YE]:.\n\[\$smileyc\]\$smiley\[$RST\] " 
    local startpos=""
    PROMPT_PWD="${PWD/#$HOME/~}"
    local overflow_prefix="..."
    local pwdlen=${#PROMPT_PWD}
    local maxpwdlen=$(( COLUMNS - ps_len ))
    # Sometimes COLUMNS isn't initiliased, if it isn't, fall back on 80
    [ $maxpwdlen -lt 0 ] && maxpwdlen=$(( 80 - ps_len )) 
    if [ $pwdlen -gt $maxpwdlen ] ; then
        startpos=$(( $pwdlen - maxpwdlen + ${#overflow_prefix} ))
        PROMPT_PWD="${overflow_prefix}${PROMPT_PWD:$startpos:$maxpwdlen}"
    fi      
    export PS1="${PS1_T1}${PROMPT_PWD}${PS1_T2}"
}
PROMPT_COMMAND=bash_prompt_cmd
```

**Comment by takluyver** [comment]
I sourced that code inside an IPython terminal, and I do see both lines of the prompt :-S

![screenshot from 2015-03-20 10 47 06](https://cloud.githubusercontent.com/assets/327925/6757484/aabd1a52-ceee-11e4-90df-1ec25c5e8f49.png)

**Comment by AGS-Knight** [comment]
Well that's strange -  I'll try to find out what's happening on my end.  Thanks for looking into this.

**Comment by takluyver** [comment]
Closing as it's not clear there was anything for us to do on this, and if there is, it's no longer part of the IPython repo, because things got split up.
