### ISSUE TITLE
ContentsManager.rename_file and ContentsManager.delete_file have confusing names

### ISSUE THREAD

**Issue by ssanderson** [ipython/ipython#8101]
ContentsManager has two abstract methods, `rename_file` and `delete_file`, that allow subclasses to define what it means to delete or rename an object.  It then implements a higher-level `delete` method that calls these implementation-specific methods and also ensures that checkpoints are kept in sync.  

This is unfortunate for two reasons:
1. The methods `delete_file` and `rename_file` are also expected to correctly apply to directories.  This is particularly confusing when the class also has plain `delete` and `rename` methods, which might lead one to assume naively that `delete/rename` should handle any path, and `delete/rename_file` should only be called on files.
2. It's easy for a subclass to accidentally implement `delete` and `rename` instead of `delete_file` and `rename_file`, which causes that class to incorrectly handle checkpoint synchronization. (I had precisely this bug in pgcontents.)

This issue is almost certainly of my own making, so I'm happy to fix it.  If it weren't using traitlets, the right fix for this would be to make `ContentsManager` a subclass of `ABCMeta` and make the expected overrides `abstractmethods`, so it's possible that the proper solution to this is to implement `AbstractHasTraits` with a compatible union of `MetaHasTraits` and `ABCMeta`.  (@llllllllll this sounds like your kind of project)

**Comment by minrk** [comment]
I don't like the sound of AbstractHasTraits. Maybe we should have made the higher level methods that you shouldn't override, but handlers call directly, the ones with less obvious names, e.g. `delete_object_and_checkpoint`, where `delete` just deletes the target.

**Comment by ssanderson** [comment]
> I don't like the sound of AbstractHasTraits.

Is your concern here about implementation complexity, or do you think the notion of an `AbstractHasTraits` doesn't seem useful?  It seems to me that the bug I ran into here, namely failing to override a method for which the superclass requires an override to function correctly, is precisely the problem that's addressed by ABCMeta by alerting you at construction time that your object isn't fulfilling the contract of its inheritance tree.

**Comment by ssanderson** [comment]
> Maybe we should have made the higher level methods that you shouldn't override, but handlers call directly, the ones with less obvious names, e.g. delete_object_and_checkpoint, where delete just deletes the target.

This probably would be better.  I guess the question now is whether it's worth the potential breakage to go back and rename these methods.

**Comment by minrk** [comment]
At this point, I'd like to avoid breaking things just to pick better names. If we do go with the name-change approach, I would probably pick entirely new names, so we can deprecate/preserve the existing ones.

However, an argument can be said that some ContentsManagers *should* override `delete`. For instance, if the checkpoints are actually in git, then it doesn't make sense to remove them on delete of a file. I think in general, most ContentsManagers are going to need to be aware of their CheckpointsManager.

Because of that, I think it *is* appropriate for a subclass to only implement delete, and not delete_file. So I'm not sure this is a case where ABC even solves the problem.

**Comment by ssanderson** [comment]
> Because of that, I think it is appropriate for a subclass to only implement delete, and not delete_file. So I'm not sure this is a case where ABC even solves the problem.

You can still override `delete` and "ignore" `delete_file` if the parent is an ABC; your class just has to explicitly re-implement `delete_file` with a no-op or somesuch.  But if you do that you're explicitly rejecting the default behavior, and you're running the risk that a future implementation of `ContentsManager` and/or the classes that use its interfaces will depend explicitly on `delete_file`.  So even if it's reasonable for *some* implementations to implement `delete` rather than `delete_file`, I'd argue that overriding the higher-level operation is "more dangerous", in the sense that you need to know a lot more about the implementation of your Checkpoints class and the `ContentsManager` base class to produce a correct subclass.  As a subclass implementer, I'd rather be warned and forced to write a bit of boilerplate to acknowledge that I'm doing the less safe thing.

**Comment by minrk** [comment]
Makes sense. I'm generally not a fan of ABCs (I think none of what we do with ABCs right now in IPython is useful to anyone in any way, but I also know we aren't doing it properly).

As long as it doesn't need more mixins, or producing something like AbstractHasTraits, then I'm okay with using ABCs to communicate the interface. Personally, though, I think documenting the interface (also not done) is all we should do.

**Comment by Carreau** [comment]
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.
