### ISSUE TITLE
`fig.canvas.draw()` does not redraw plots in notebook with nbagg backend in IPython 3

### ISSUE THREAD

**Issue by ketch** [ipython/ipython#8106]
In IPython 2, it was possible to have a plot that was updated interactively through a widget whose callback changed the plot data.  This could be done using the nbagg backend and `fig.canvas.draw()`; an example is here: http://nbviewer.ipython.org/github/jenshnielsen/netcdf-lesson/blob/master/Interactive%20plotting%20with%20nbagg.ipynb.

In IPython 3, that example does not work.  Only an empty plot and a slider widget are produced.

I have verified that the figure is being modified appropriately when the slider is moved; the problem is that the figure is never rendered.

**Comment by ketch** [comment]
See also relevant discussion at https://github.com/ipython/ipython/issues/7520.

**Comment by ketch** [comment]
This problem went away after I updated to matplotlib 1.4.3.

**Comment by takluyver** [comment]
Great, thanks for working it out.
