### ISSUE TITLE
`_log_format_changed()` missing 3 required positional arguments

### ISSUE THREAD

**Issue by jhamrick** [ipython/ipython#8110]
In `IPython.config.application`, the `_log_datefmt_changed` handler calls `_log_format_changed` but does not pass it the required arguments. My guess would be that this is the correct implementation:

```
def _log_datefmt_changed(self, name, old, new):
    self._log_format_changed(name, self.log_format, self.log_format)
```

However I am not really sure what the `name` parameter is for, so I might be wrong.

**Comment by takluyver** [comment]
I think the name should just be `'log_format'` - it's there so you can use one function as the changed callback for several different traitlets, IIRC.

**Comment by jhamrick** [comment]
Ok, cool. I'll make a PR then.

**Comment by takluyver** [comment]
Thanks!

The signature for traitlet changed callbacks is a bit odd, but we can't really change it. They can accept any of:

- No arguments
- `name`
- `name, new`
- `name, old, new`

I think most of the time, `new` is the only parameter actually used.
