### ISSUE TITLE
Can not run IPTEST due to folder name changed

### ISSUE THREAD

**Issue by duytrung** [ipython/ipython#8115]
Hi all,

I tried to run IPTEST, however, it failed due to folder name has changed. How to fix it anyway?
I renamed the folder to Python instead of PYX previously, for convenience in managing stuffs. All the other packages installed and updated well.

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\eep1>iptest
Fatal error in launcher: Unable to create process using '"C:\Pyx\python.exe"  "c:\Python\Scripts\iptest.exe" '

C:\Users\eep1>_
```

Thanks.

**Comment by minrk** [comment]
When you run Python, does `sys.executable` refer to the correct location? If not, you may need to reinstall Python. If it does, you may need only reinstall IPython.

**Comment by duytrung** [comment]
Hi minrk,

Here is the result, I found it pretty correct to the python path:

```
C:\Users\eep1>ipython
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 3.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import sys

In [2]: print(sys.executable)
c:\Python\python.exe

In [3]:

```

**Comment by minrk** [comment]
okay, then try uninstalling and reinstalling IPython:

    pip uninstall ipython
    pip install ipython

**Comment by Carreau** [comment]
Hi, 

This issue has been quiet for almost 2 years, and I don't think there is anything we can do. It has been marked as no-action, and I'm going to close it to attempt to reduce the number of opened issue. Feel free to reopen if needed. 

Thanks.
