### ISSUE TITLE
Option to download files in tree

### ISSUE THREAD

**Issue by loehndorf** [ipython/ipython#8118]
Before updating to v3 I often stored files as csv and downloaded them manually. This is not possible anymore, since the linked file now opens a text editor. Although this is a nice feature, I often do not want to open files, especially if they large. I propose to add "Download" in addition to "Duplicate" and "Rename" as another button that appears once a file gets selected.

**Comment by takluyver** [comment]
I think that makes sense. We've also been talking about selecting multiple files and downloading a zip of them.

**Comment by jdavidheiser** [comment]
I would just like to second this request.  The combination of the in-browser text editor, Terminado, and the notebooks themselves has led to Jupyter/IPython working about 80% as a pure-browser interface to an analytic environment, which is awesome.  In a corporate environment with a heavy cloud focus, this is a huge boon, and file download would really fill in the gaps.  The multiple-file zip download sounds great as well.

**Comment by ssanderson** [comment]
@takluyver @minrk we're looking at something like this as well.  I'm wondering if a good first step toward this would be making the file size available to the frontend as another field in the contents spec.  That way you at least have some advanced warning if you're about to crash your browser by reading 100MB into the DOM. See also https://github.com/jupyter/jupyter_notebook/issues/24.

**Comment by takluyver** [comment]
If we can agree on how and where to display file size in the dashboard, I think that would certainly make sense.

**Comment by minrk** [comment]
Adding file size to the model is an easy first step that we can do before deciding on UI. I know we want to add last_modified to the tree view as well. Adding the size makes as much sense, and we should probably do both at once, whenever that happens.
