### ISSUE TITLE
Double-click on displayed items causes cursor to return to cell input

### ISSUE THREAD

**Issue by dsblank** [ipython/ipython#8125]
I'm not sure what is happening nor why, but if you double-click some items that are displayed (like JavaScript or HTML buttons) the cursor will jump back to source.

To replicate (running latest Chrome/Chromium on Linux):

``` html
%%html
<canvas height="600"/>
<button>Press me</button>
```

then double-click the button. Cursor is positioned back in input cell. Only happens first time button is displayed (as if this is part of the hide-the-output-on-double-click-- now it thinks it is hidden). For example, double-clicking the button a second time won't cause cursor to go back to input. But rerun the cell again, and double-click takes cursor back to input.

The reason that this is problematic is that in running some simulations requires that you click a "Next" button. Clicking too fast is received as a double-click and jumps the screen way back to the source. This happens to me every day in lecture/demo.

**Comment by engheta** [comment]
This is a major nuisance. Does anyone have any insight into this?
