### ISSUE TITLE
Looking for Interviewees

### ISSUE THREAD

**Issue by LeninaCrowne** [ipython/ipython#8143]
Hello!
I’m currently working on my bachelor’s thesis in “leader emergence in open source software projects“. For my research I’m looking for interviewees, preferably 2 people per OSS project: one person with some sort of leadership role and one “normal” project member.
The interviews will take place via Skype over the next couple of weeks and last around half an hour.
Feel free to forward this request to anyone who might be interested and do not hesitate to contact me with any questions you might have.
Thank you so much for your help!
Greetings from Munich,
Katy
PS: My e-mail is katharina.ring@web.de

**Comment by Carreau** [comment]
Hi Katy, 

I would suggest for you to write to the mailing list IPython-dev(at)scipy.org you will have a broader audience. This is mostly the bug tracker, and half of the people you will be interested in are just too busy to look at all the issues, so they will not see that, but might on the ML. For our project in particular, 
the leadership is Fernando Perez (Benevolent Dictator For Life aka BDFL) and Brian Granger.

There are also a few other [Mailing list](http://www.scipy.org/scipylib/mailing-lists.html) for the scipy stack projects. 

I am going to close this as this is not technically a bug, but you can continue to comment on it. 

Thanks !
