### ISSUE TITLE
Alternative end of line keybindings

### ISSUE THREAD

**Issue by alvinwt** [ipython/ipython#8144]
I realized that certain models of laptops lack the *home* and *end* buttons keyboards. I would like to alternative key bindings to go to the end of line or beginning of line for such keyboards. Are there documentation to do this using javascript and relevant functions?

**Comment by Carreau** [comment]
Yes, keybindings for Codemirror ar configurable, see [codemirror manual](http://codemirror.net/doc/manual.html). You might need to tinker with IPython `custom.js` file to inject custom javascript.
