### ISSUE TITLE
Parallel IPython "apply" broken in current master

### ISSUE THREAD

**Issue by bergtholdt** [ipython/ipython#8145]
I just updated to current master and can't get the apply method to work. The issue can be reproduced by simply calling

```
client[0].apply_sync(os.getcwd)
```

on a Client object. Which causes this output:

    UnpicklingError                           
    Traceback (most recent call last)\\dephbgpflhmsc00\HPC_share2\bergtholdt\python\Python27\lib\site-packages\IPython\kernel\zmq\serialize.pyc in unpack_apply_message(bufs, g, copy)
        160     assert len(bufs) >= 2, "not enough buffers!"
        161     pf = buffer_to_bytes_py2(bufs.pop(0))
    --> 162     f = uncan(pickle.loads(pf), g)
        163     pinfo = buffer_to_bytes_py2(bufs.pop(0))
        164     info = pickle.loads(pinfo)
    UnpicklingError: invalid load key, '<'.

The version that I used earlier was 85b118a, about 4 month ago.

    {'commit_hash': u'befcaa9',
     'commit_source': 'installation',
     'default_encoding': 'cp850',
     'ipython_path': 'C:\\x64\\Python27\\lib\\site-packages\\IPython',
     'ipython_version': '4.0.0-dev',
     'os_name': 'nt',
     'platform': 'Windows-7-6.1.7601-SP1',
     'sys_executable': 'C:\\x64\\Python27\\python.exe',
     'sys_platform': 'win32',
     'sys_version': '2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]'}

**Comment by bergtholdt** [comment]
Seems that anything that pickles (apply, map, ...) won't work:

This executes:

    In [34]: client[0].execute('x = os.getcwd()')
    Out[34]: <AsyncResult: execute>

Result can be looked at via %px magic (returns just strings, I guess):

    In [35]: %px0 x
    Out[0:8]: '\\\\dephbgpflhmsc00\\HPC_share2\\bergtholdt\\python\\.ipython\\profile_hpc'

But not pulled:

    In [36]: client[0]['x']
    ---------------------------------------------------------------------------UnpicklingError                           Traceback (most recent call last)\\dephbgpflhmsc00\HPC_share2\bergtholdt\python\Python27\lib\site-packages\IPython\kernel\zmq\serialize.pyc in unpack_apply_message(bufs, g, copy)
        160     assert len(bufs) >= 2, "not enough buffers!"
        161     pf = buffer_to_bytes_py2(bufs.pop(0))
    --> 162     f = uncan(pickle.loads(pf), g)
        163     pinfo = buffer_to_bytes_py2(bufs.pop(0))
        164     info = pickle.loads(pinfo)
    UnpicklingError: invalid load key, '<'.

Pushing does not result in an error:

    In [37]: client[0]['x'] = 'test'

But does not work either:

    In [38]: px0 x
    Out[0:9]: '\\\\dephbgpflhmsc00\\HPC_share2\\bergtholdt\\python\\.ipython\\profile_hpc'

**Comment by takluyver** [comment]
We have seen this in tests as well, but we're completely unsure what's happening at present. It seems to be a Python 2 specific problem, but it's not OS specific (we've seen the same failure on Linux) and it's not introduced by a new Python release, since you're on 2.7.5.

**Comment by minrk** [comment]
Once I split out IPython parallel and started running the parallel tests on travis, I was able to track this down. It's caused by a recent change to use memoryviews, which were correctly handled on Python 3, but not Python 2.

**Comment by twiecki** [comment]
How can run IPython parallel with this patch applied?

**Comment by minrk** [comment]
If you are running current master of these repos, the patch should be applied. In the IPython parallel repo:

    pip install -r requirements.txt
    pip install -e .
