### ISSUE TITLE
Possible to make nbconvert.preprocessors.execute fail on error in cell?

### ISSUE THREAD

**Issue by audy** [ipython/ipython#8148]
I'm rendering notebooks from the command line using a make file. I want there to be some sort of error if there was an error in a cell in a notebook (that way I can automatically check that all of my notebooks still work after making changes to a shared function).

The command I'm using to render the notebooks is:

```sh
ipython nbconvert \
    --ClearOutputPreprocessor.enabled=True \
    --ExecutePreprocessor.enabled=True \
    --to=html \
    $input
```

This works fine but there is no error/warning if one of the cells in the notebook encountered an error. The exist status of `ipython` is 0.

Is there a way to get `ipython nbconvert` to exit with a non-zero exit status or otherwise print some kind of warning when an error is encountered in a cell?

**Comment by takluyver** [comment]
I don't think so at present, but it seems like a reasonable option if you'd like to add it. Wait a couple of weeks, though, because we're just reorganising the repository, so that code is going to move.

**Comment by takluyver** [comment]
#8286 is for the same thing. This one was first, but there's more discussion on the other, so closing this.
