### ISSUE TITLE
jupyter_qtconsole reenable icon.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#8152]
Just reminder.

**Comment by minrk** [comment]
@Carreau reminder time! We are close to ready to release the qtconsole and I have no idea what this means.

**Comment by Carreau** [comment]
Bah it's just a UI thing where the icon would not show in dialogs IIRC. Not sure I remember correctly.

**Comment by takluyver** [comment]
Closing this since we're not even sure what it means, and the qt console is no longer in this repo. If we find it again, let's file an issue in jupyter/qtconsole.
