### ISSUE TITLE
No toolbar in notebook

### ISSUE THREAD

**Issue by Tjorriemorrie** [ipython/ipython#8170]
I thought I'd give this a try, looks so good, but not fucking working:
````
pip install "ipython[notebook]"
````
pip freeze gives ipython==3.0.0
Running:
````
ipython notebook
````
runs and opens the browser correctly. But when creating a new file there is no toolbar
![screen shot 2015-03-27 at 14 50 45](https://cloud.githubusercontent.com/assets/1099093/6868033/c3fcc3c6-d490-11e4-9947-5928faf472a2.png)
:
You sure this is past beta?

**Comment by rsmith31415** [comment]
You opened a new "Text File". Instead, create a new notebook:

![screenshot from 2015-03-27 08 53 08](https://cloud.githubusercontent.com/assets/599274/6869990/ca7e0c1e-d45e-11e4-833b-441ad2ac03b3.png)

**Comment by minrk** [comment]
Text files don't have a toolbar associated with them. Only notebooks do. When you open a notebook (.ipynb), you will see a toolbar.
