### ISSUE TITLE
DropdownWidget at the end of page

### ISSUE THREAD

**Issue by taniki** [ipython/ipython#8171]
When the list is at the end of a page, there is no way to access items outside the window.

Some browser have a native behaviour allowing to access dropdown items with the keyboard but this is not the case with the UI framework used by ipython.

An easy workaround is to use `SelectWidget` instead.

![screenshot 2015-03-27 15 07 23](https://cloud.githubusercontent.com/assets/27315/6870108/1080ce96-d49a-11e4-93df-b6adb2d5ed40.png)

**Comment by takluyver** [comment]
See ipython/ipywidgets#94
