### ISSUE TITLE
Unintended scrolling/jumping on text selection

### ISSUE THREAD

**Issue by d10genes** [ipython/ipython#8173]
When I select text in a code cell where the text is around the middle of the page,
![screen shot 2015-03-27 at 3 09 21 pm](https://cloud.githubusercontent.com/assets/379413/6875367/4fa1966a-d494-11e4-861b-f12e676be265.png)

and then click on the selected text, the text jumps/scrolls to the bottom of the page.

![screen shot 2015-03-27 at 3 09 31 pm](https://cloud.githubusercontent.com/assets/379413/6875371/5aa25a18-d494-11e4-8768-8d4795e31606.png)

I thought it was some custom css or js, but after disabling that the problem appears to continue.

There seem to be other cases where this jumping occurs, but this is the only one I've figured out how to reproduce.

I assume this is unintented behavior?

It looks related to #3441 from over a year ago, but this occurs with the recent 4ad311ea.

**Comment by d10genes** [comment]
Looks possibly related to issue #8054 and PR #8191 (?)

**Comment by minrk** [comment]
It does indeed look related, and appears to be fixed by #8191.

**Comment by d10genes** [comment]
I'm still getting this jumping as of 719adcbf8 (unless big split installation issues are quietly failing to install from master? `pip freeze` in a new virtualenv shows `-e git+https://github.com/ipython/ipython.git@719adcbf8f7fbdcc47da5e91e9650533e5cb64c6#egg=ipython-master`).
