### ISSUE TITLE
[Enhancement Feature Request] - Functions Look-up button

### ISSUE THREAD

**Issue by duytrung** [ipython/ipython#8177]
Hi, 

I'm wondering whether is it OK to implement a feature that implement a list of available function that user can lookup in real-time. This is more an a function completion using Control+Space as in some IDEs or text editor. The features as described here:

+ A small button located at the "In [  ]:" to make it appears like this: In [  ] [Functions] that allows user to use hot key combination to display a list of categorized funtions.
or 

+ A double windowed panel appears in the in the right of the program showing which function we are currently accessing in the package and their documentation/usage.

Kind regards

**Comment by minrk** [comment]
This sounds like a good idea to build as a notebook extension. You can see examples of other notebook extensions [here](https://github.com/ipython-contrib/IPython-notebook-extensions).

**Comment by duytrung** [comment]
Thanks minrk for your reply,

What is the requirement for writing the extension, I only know the intermediate python, C/C++, for my own computing purpose. Do they require much javascript, html? I know those but not very used to them.

Please list out some prior knowledge requirements. I will consider some time to study and give contribute to the plug-in if possible. I found that this project is quite fantastic.

Thank you!

**Comment by Carreau** [comment]
Yes, you will mostly need some JS/HTML experience. Maybe some python to do
callback in the kernel to get the list of function. You can get some
inspiration on github/ipython-contrib
