### ISSUE TITLE
Make Shift-J and Shift-K move the current cell up or down in notebook

### ISSUE THREAD

**Issue by brandon-rhodes** [ipython/ipython#8183]
Apologies if my Google searches for this topic are incomplete and this is a repeat suggestion!

The Notebook used to have a very useful pair of keys in Command Mode for moving a cell up or down — I needed them just now, when I realized that this useful function that I just wrote could simplify even more code if it were moved further up in this notebook.

The previous keystrokes were probably removed because they conflicted with one or two very common browser operations, which is quite appropriate.

I would like to suggest Shift-J and Shift-K as their new command keys, which I think will fit in nicely with the current set of shortcuts, and make it easier to move a cell a few dozen positions up or down without having to select "move cell up" repeatedly from a menu, or attempt the far more dangerous operation of cut and paste, which if done incorrectly leaves you without the cell at all.

**Comment by takluyver** [comment]
We're saving shift-J and shift-K because we plan to implement a way to select a range of cells, and those are obvious key combinations to use for that.

Here are instructions on how to re-enable the old Ctrl-J/K shortcuts for your own use:

https://github.com/ipython/ipython/pull/7732#issuecomment-74519970

**Comment by Carreau** [comment]
I'm also slowly updating docs [here](http://carreau.gitbooks.io/jupyter-book/content/keyboardshortcut.html) PR welcomed.

**Comment by brandon-rhodes** [comment]
Thank you both, @takluyver and @Carreau, for the useful links and for giving me more context about the decision — Shift does have a long history as the select-and-drag key, so I do see the need to reserve it for that!
