### ISSUE TITLE
Non-ipynb file extensions in FileContentsManager

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#8185]
This issue has been opened to track this closed PR #7834. Feel free to reopen the PR is work starts up again.

**Comment by Carreau** [comment]
Hi, 

This issue has been quiet for almost 2 years, and I don't think there is anything we can do. It has been marked as no-action, and I'm going to close it to attempt to reduce the number of opened issue. Feel free to reopen if needed. 

Thanks.
