### ISSUE TITLE
Misc work on the Cluster tab and ipcluster

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#8189]
This issue was opened to track progress on this closed issue: #7874 

Feel free to reopen the PR when work restarted.

**Comment by Carreau** [comment]
Hi, 

This issue has been quiet for almost 2 years, and I don't think there is anything we can do. It has been marked as no-action, and I'm going to close it to attempt to reduce the number of opened issue. Feel free to reopen if needed. 

Thanks.
