### ISSUE TITLE
IndexError rendering traceback

### ISSUE THREAD

**Issue by akhmerov** [ipython/ipython#8205]
The following code causes an error (on Python 2 only) in IPython's traceback rendering in both in 3.0.0 and 2.4.0:

```python
In [1]: (0/0 for i in [1] if all(i for j in [])).next()
/usr/local/lib/python2.7/site-packages/IPython/core/ultratb.py in format_records(self, records)
    745             file = py3compat.cast_unicode(file, util_path.fs_encoding)
    746             link = tpl_link % file
--> 747             args, varargs, varkw, locals = inspect.getargvalues(frame)
    748 
    749             if func == '?':

/usr/local/lib/python2.7/inspect.pyc in getargvalues(frame)
    827     """'varargs' and 'varkw' are the names of the * and ** arguments or None.
    828     'locals' is the locals dictionary of the given frame."""
--> 829     args, varargs, varkw = getargs(frame.f_code)
    830     return ArgInfo(args, varargs, varkw, frame.f_locals)
    831 

/usr/local/lib/python2.7/inspect.pyc in getargs(co)
    789                                 remain[-1] = remain[-1] - 1
    790                             if not remain: break
--> 791             args[i] = stack[0]
    792 
    793     varargs = None

IndexError: list index out of range
```

Either of these two modifications correctly renders the `ZeroDivisionError`:

```python
(0/0 for i in [1] if all(True for j in [])).next()
[0/0 for i in [1] if all(i for j in [])]
```

**Comment by minrk** [comment]
Thanks for the report. FWIW, there doesn't appear to be a problem on Python 3.

**Comment by keryil** [comment]
Apparently some suspect this is a python issue, not specific to IPython. See https://github.com/ipython/ipython/issues/8293

**Comment by ssanderson** [comment]
The root cause of this is http://bugs.python.org/issue14611.  The supplied patch there fixes this for me.

**Comment by ssanderson** [comment]
See https://github.com/ipython/ipython/issues/8293#issuecomment-146368401 for the gory details.

**Comment by akhmerov** [comment]
Beautiful! So this issue should be closed, right?

**Comment by ssanderson** [comment]
I suppose it depends on whether the IPython folks want to provide a workaround for a bug in CPython.  There's already at least one patch for `inspect` in ultratb.  I've provided another one in https://github.com/ipython/ipython/pull/8882.

**Comment by ssanderson** [comment]
@akhmerov to be clear, the patch linked above in the CPython bugtracker hasn't been merged, and has been inactive since 2012.  I'm not sure why.

**Comment by akhmerov** [comment]
@ssanderson I understand; I actually meant closing the issue as not-ipython-problem (I only saw your commits after commenting). Monkey-patching the standard library seems also OK in this particular case though, especially since it's not the first monkey-patch.
