### ISSUE TITLE
IPython parallel results.get_dict() fails.

### ISSUE THREAD

**Issue by michaelaye** [ipython/ipython#8206]
This is from a load_balanced.map_async() run with 8 engines over 3170 filenames:

``` python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-81-e761d0f819f4> in <module>()
----> 1 results.get_dict()

/usr/local/python3/miniconda/lib/python3.4/site-packages/IPython/parallel/client/asyncresult.py in get_dict(self, timeout)
    185             if engine_id in rdict:
    186                 raise ValueError("Cannot build dict, %i jobs ran on engine #%i" % (
--> 187                     engine_ids.count(engine_id), engine_id)
    188                 )
    189             else:

ValueError: Cannot build dict, 399 jobs ran on engine #6
```

IPython: 3.0.0
Python: 3.4

$ python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': 'f75fda4',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/python3/miniconda/lib/python3.4/site-packages/IPython',
 'ipython_version': '3.0.0',
 'os_name': 'posix',
 'platform': 'Linux-2.6.32-431.11.2.el6.x86_64-x86_64-with-redhat-6.5-Santiago',
 'sys_executable': '/usr/local/python3/miniconda/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.4.3 |Continuum Analytics, Inc.| (default, Mar  6 2015, '
                '12:03:53) \n'
                '[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'}

**Comment by minrk** [comment]
That's right. `get_dict` turns the result of a DirectView into a dict of results keyed by engine ID. As the error message above attempts to communicate, this only works if each engine produced at most one result. It can't create that dict if one engine produced multiple results.

**Comment by michaelaye** [comment]
IIUC, a dict would then never possible from a lbview.map_async, right? But when someone is using an lbview, maybe a per_engine dictionary is anyway not wanted/required. But, could this not return simply a list per engine of the things done? Or a tuple with result and engine number, if one really wanted? `pandas` is so cool in dealing with lists of tuples that I usually do:

```python
def process_filename(filename):
    result = do_stuff(filename)
    return (filename, result)

results = lbview.map_async(process_filename, df.filename)
df = pd.DataFrame(results.result, columns=['filename','result']).merge(df, on='filename')
```
I was not in the need of having get_dict() working for me, just a bit confused about the thrown error. Maybe this error could be caught to inform the user instead of throwing the error? Or returns lists of results per engine?

**Comment by minrk** [comment]
> Maybe this error could be caught to inform the user instead of throwing the error?

Isn't that what the error does? If you try to do something that doesn't work, an error should be thrown. Hopefully an informative one. I will try to clarify the error message.

We could definitely make get_dict return lists per engine if any engine has created multiple results. I'm just not sure if it would be confusing for a single method to return a dict of lists sometimes, and dict of results others.

> Or a tuple with result and engine number, if one really wanted?

I'm not sure what you mean, here. Do you mean get_dict should return a dict of tuples? Or a new method that does `zip(engine_ids, results)`?

**Comment by michaelaye** [comment]
I was more 'shocked' that I get an error using a method that was 'on offer'. This is an interesting expectation change on my end over the years. 10 years ago I would totally expect that the user has to know when/how to use a method. But this days, with dynamic object manipulation depending on contents, I'm kinda expecting that a method on offer doesn't bark at me merely for using it, but instead friendly lets me know that it's of no use to me. Though I see that a thrown error can be much more useful in a bigger application, maybe my opinion on this is skewed from too much interactive working.

You could always return a dict of lists, with the lists having only 1 element. There are several packages out there that follow that paradigm.

Well, I'm not sure what I meant either with tuples. ;) I think I just cannot think in terms of actually being interested in the engine number when I was not interested in what goes where in the first place, having used a load-balanced view that even does not give me that control. So maybe one should rather question the existence of the method like this in a result object coming from a lbview.

**Comment by minrk** [comment]
@michaelaye but if it shows you a friendly message and returns None, execution will continue and you will see an error as soon as you try to use the dict that is either not a dict, or empty. I think it's better to have an error when the mistake was made, rather than at some time later because the return value doesn't make sense.

> You could always return a dict of lists, with the lists having only 1 element.

This defeats the purpose of `get_dict`, which is for mapping results to engine IDs. The use case that `get_dict` exists for is things like this:

```python
ar = rc[:].apply_async(lambda : MPI.get_rank())
mpi_ranks = ar.get_dict() # a mapping of IPython IDs to MPI ranks
```

Which is a common pattern for getting mappings of engine ID to MPI rank, PID, hostname, etc. The goal is that there are many things for which you want a *single* mapping of engine ID to a property of that engine, so it must be a result itself, not a list, to be useful.

> So maybe one should rather question the existence of the method like this in a result object coming from a lbview.

This seems the relevant point - AsyncResult is a single object that can represent results from a variety of contexts. Some operations only make sense in some contexts (e.g. get_dict). Does that mean there should be several different AsyncResult classes with the different methods? Perhaps.

**Comment by takluyver** [comment]
@minrk this is still open, but marked no action - do you want to do anything like breaking up different types of AsyncResult, or making the error message clearer?

**Comment by Carreau** [comment]
Hi, 

This issue has been quiet for almost 2 years, and I don't think there is anything we can do. It has been marked as no-action, and I'm going to close it to attempt to reduce the number of opened issue. Feel free to reopen if needed. 

Additionally ipyparallel is now its own package so the issue should likely be reopened there if needed.  

Thanks.
