### ISSUE TITLE
Memory leak: DOMWidget not collectable by gc

### ISSUE THREAD

**Issue by joe1gi** [ipython/ipython#8207]
A reference cycle is formed by `_validate_border` being defined inside `__init__` (adding self to its closure) and added to `self._trait_notifiers` via `on_trait_change`. Because it also has a `__del__` method, gc won't collect it.

This problem can be fixed by defining `_validate_border` outside `__init__` or outside the class. A better solution may be to remove `__del__` altogether, since it is never called in practice. To trigger `__del__`, one would have to remove the widget from `Widget.widgets` and break another reference cycle formed by `Widget.comm` and `Comm._msg_callback`.

As widgets and their comms naturally form cycles, the presence of `__del__` on Comm is similarly unhealthy. I think this `__del__` is also expendable, because only a user call to `CommManager.unregister_comm` can trigger it.

To reproduce: 
```
from IPython.html import widgets
from IPython.display import display
w = widgets.FloatText()
display(w)
w.close()
%xdel w
import gc
# widget appears in garbage only after it has been displayed
gc.collect()
print gc.garbage
# but always in the full object list
print [obj for obj in gc.get_objects() if type(obj).__name__ == 'FloatText']
del obj
```

`objgraph` output for reference:
![widget_ref_cycle](https://cloud.githubusercontent.com/assets/11727027/6913062/03757450-d7be-11e4-8fc9-39c199d92321.png)

**Comment by jdfreder** [comment]
Woah, I was unaware of this.  Thanks for the assignment @takluyver - I'm going to open a sister issue in ipywidgets so I can track this there.

**Comment by takluyver** [comment]
Thanks @jdfreder. Closing here since you have an ipywidgets issue to track it with.
