### ISSUE TITLE
All notebook hyperlinks are underlined

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#8219]
In previous version of the notebook all hyperlinks were blue, but not underlined. Now they are all underlined :( Was this a deliberate design change or accident? I prefer no underlines.

**Comment by Carreau** [comment]
I think accident.

**Comment by minrk** [comment]
I just checked, and they are underlined on 2.x and 1.x. I don't think this has changed since the beginning of the notebook.

**Comment by ellisonbg** [comment]
Mmmm, no way, I am positive this wasn't the case - it must be a browser
change...

On Wed, Apr 1, 2015 at 10:02 AM, Min RK <notifications@github.com> wrote:

> I just checked, and they are underlined on 2.x and 1.x. I don't think this
> has changed since the beginning of the notebook.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/8219#issuecomment-88548515>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
Hmm, found a screenshot from a while back where links were underlined...now
doubting my memory...but I could swear they weren't underlined

On Wed, Apr 1, 2015 at 10:13 AM, Brian Granger <ellisonbg@gmail.com> wrote:

> Mmmm, no way, I am positive this wasn't the case - it must be a browser
> change...
>
> On Wed, Apr 1, 2015 at 10:02 AM, Min RK <notifications@github.com> wrote:
>
>> I just checked, and they are underlined on 2.x and 1.x. I don't think
>> this has changed since the beginning of the notebook.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ipython/ipython/issues/8219#issuecomment-88548515>.
>>
>
>
>
> --
> Brian E. Granger
> Cal Poly State University, San Luis Obispo
> @ellisonbg on Twitter and GitHub
> bgranger@calpoly.edu and ellisonbg@gmail.com
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
Custom theme ? Slideshow ?

**Comment by Carreau** [comment]
Migrated to jupyter/notebook#977
