### ISSUE TITLE
Can't open notebook if directory contains a directory named "path"

### ISSUE THREAD

**Issue by mpharrigan** [ipython/ipython#8221]
Steps to reproduce:
 - Make a directory named `path` in a location of your choosing
 - Try to create a new notebook or open an existing one alongside the above directory:
```
  path/
  Untitled.ipynb
```

Observed behavior:
```
[I 19:19:20.352 NotebookApp] Kernel started: d751b2a6-b6bd-4753-8ef2-417e85a7e0bb
/home/harrigan/opt/miniconda3/bin/python3: Error while finding spec for 'IPython.kernel' (<class 'ImportError'>: cannot import name 'path')
[I 19:19:23.355 NotebookApp] KernelRestarter: restarting kernel (1/5)
/home/harrigan/opt/miniconda3/bin/python3: Error while finding spec for 'IPython.kernel' (<class 'ImportError'>: cannot import name 'path')
[I 19:19:26.360 NotebookApp] KernelRestarter: restarting kernel (2/5)
/home/harrigan/opt/miniconda3/bin/python3: Error while finding spec for 'IPython.kernel' (<class 'ImportError'>: cannot import name 'path')
[I 19:19:29.365 NotebookApp] KernelRestarter: restarting kernel (3/5)
/home/harrigan/opt/miniconda3/bin/python3: Error while finding spec for 'IPython.kernel' (<class 'ImportError'>: cannot import name 'path')
[W 19:19:30.376 NotebookApp] Timeout waiting for kernel_info reply from d751b2a6-b6bd-4753-8ef2-417e85a7e0bb
[I 19:19:32.369 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel d751b2a6-b6bd-4753-8ef2-417e85a7e0bb restarted
/home/harrigan/opt/miniconda3/bin/python3: Error while finding spec for 'IPython.kernel' (<class 'ImportError'>: cannot import name 'path')
[W 19:19:35.375 NotebookApp] KernelRestarter: restart failed
[W 19:19:35.376 NotebookApp] Kernel d751b2a6-b6bd-4753-8ef2-417e85a7e0bb died, removing from map.
```

Notebook reports "restarting kernel failed". This bug was not observed when I tried with `ipython kernel` and `ipython console --existing xxx`

Output of sys_info:
```
{'commit_hash': 'f75fda4',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/ssdhome/harrigan/opt/miniconda3/lib/python3.4/site-packages/IPython',
 'ipython_version': '3.0.0',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-48-generic-x86_64-with-debian-jessie-sid',
 'sys_executable': '/home/harrigan/opt/python/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.4.3 |Continuum Analytics, Inc.| (default, Mar  6 2015, '
                '12:03:53) \n'
                '[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'}
```

**Comment by minrk** [comment]
That's correct. IPython uses a package called [path](https://pypi.python.org/pypi/path.py). If there's a `path.py` in the CWD, `import path` will find the local file instead of the installed module. You would have a similar problem if you made a `random.py` or `IPython.py`.

**Comment by mpharrigan** [comment]
Is this really the desired behavior?

**Comment by mpharrigan** [comment]
Shouldn't it only try to import from the filesystem if `path/` contains an `__init__.py`?

**Comment by takluyver** [comment]
On Python 3, directories without an `__init__.py` now work as namespace packages. It will only find this if it can't find a regular `path` package at all, though, so installing [path.py](https://pypi.python.org/pypi/path.py) should make it work.

**Comment by mpharrigan** [comment]
Thanks, good to know. Maybe conda should include path as a dependency

**Comment by minrk** [comment]
IPython up through 3.0 ships a copy of some simple Python dependencies in IPython.external, which is the source of some of these problems. IPython 4.0 (current master) will do away with that, and express a regular dependency on these packages.
