### ISSUE TITLE
Startup file doesn't throw errors on IPython Notebook Start

### ISSUE THREAD

**Issue by bllchmbrs** [ipython/ipython#8241]
in startup scripts(for notebooks) I cannot raise errors or perform print statements. Because of this, there's no way to notify the user that pulling in the spark_home variable has some issue. You'll see what I've written in this gist:

https://gist.github.com/anabranch/a810391f3d1def45a0b3

It will never raise an error/print even by modifying the SPARK_HOME to make it fail.

**Comment by takluyver** [comment]
I think this is a notebook specific issue - it discards output that arrives before you execute a cell.
