### ISSUE TITLE
`pip install ipython` on windows did not install readline

### ISSUE THREAD

**Issue by bialix** [ipython/ipython#8246]
I'm using ipython for a very long time, but I don't update it very often, because even old versions just works for me. Maybe I missed something important. But.
Earlier, maybe year ago (in 2014) installing ipython via pip (on windows) also installed for me crucial part of ipython: readline library that makes experience with ipython so good, and why I really love ipython shell. But this is no more so good. Basic `pip install ipython` does not try to install readline nor pyreadline. I had big frustration, because it's not very obvious why tab completion and other goodies does not work anymore. In the 3.1.0 release I see there is small hint about pyreadline but it's not very obvious, when you're in rush. Why don't you put readline/pyreadline to the dependencies of your project? Why don't you suggest to run `pip install readline` or something like that automatically?
Even your page http://ipython.org/pyreadline.html does not try to help here.
I'm very disappointed about such lesser user experience, also keeping in mind I'm actually programmer who should understand everything better than regular users.
I just want to point your attention to this problem. Probably it could be solved easily by adding corresponding declaration to your setup.py or setup.cfg.

**Comment by bialix** [comment]
Also your readline page stated: The current stable release is 1.7.
I've executed `pip install pyreadline` and now I have pyreadline 2.0

**Comment by takluyver** [comment]
If you do `pip install ipython[terminal]`, it will get pyreadline too. I think we pulled it out of the default dependencies because it's not necessary for the notebook or the Qt console, and there are probably quite a few users on Windows who mainly use those.

**Comment by minrk** [comment]
I believe it was moved to `[terminal]` due to installation issues with pyreadline on some combinations of Windows and Python versions, preventing users of things like the notebook from being able to install due to a failure in a package that they won't use.

**Comment by minrk** [comment]
We should remove the ipython.org/pyreadline.html page, since we don't manage the pyreadline package anymore.

**Comment by bialix** [comment]
I don't think removing this page is good idea. When I don't have readline installed and run ipython I got message:

D:\work\Opensource\intelhex.bzr\intelhex>ipython
WARNING: Readline services not available or not loaded.
WARNING: Proper color support under MS Windows requires the pyreadline library.
You can find it at:
http://ipython.org/pyreadline.html

Defaulting color scheme to 'NoColor'
Python 3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 10:35:05) [MSC v.1600 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]:

So, actually that ipython itself who pointed me to that page url. Probably you can change explanation text on that page and maybe provide some updated instructions for users?

**Comment by bialix** [comment]
OK, it seems I missed that magic spell `pip install ipython[terminal]`. I was unfamiliar with such pip syntax. Now pip has installed everything correctly:

D:\work\Opensource\intelhex.bzr\intelhex>pip install "ipython[terminal]"
Collecting ipython[terminal]
  Using cached ipython-3.1.0-py3-none-any.whl
Collecting pyreadline>=2.0 (from ipython[terminal])
  Using cached pyreadline-2.0.zip
    package init file 'pyreadline\configuration\__init__.py' not found (or not a regular file)
Installing collected packages: pyreadline, ipython
  Running setup.py install for pyreadline
    package init file 'pyreadline\configuration\__init__.py' not found (or not a regular file)

Successfully installed ipython-3.1.0 pyreadline-2.0

**Comment by minrk** [comment]
By removing the page, I wouldn't make it 404, but redirect to more appropriate page, one that actually corresponds to the pyreadline project. That page is unmaintained, and inappropriate given IPython's current relationship with PyReadline.

**Comment by stonebig** [comment]
looking at pycon2015 lightning talks, I fell over pgcli, which is using this for windows.
https://github.com/jonathanslenders/python-prompt-toolkit 

could it be a solution to the currently poor situation of windows users regarding readline, terminado, ...?

**Comment by takluyver** [comment]
It could be an alternative to pyreadline, but I don't think there's a clear advantage to doing that - it's just exchanging one pure Python dependency for another. Maybe we should just live with installing the extra dependency even when you just want the notebook.

I don't think it can help with getting terminals in the web browser - that needs some lower level infrastructure.

**Comment by minrk** [comment]
@takluyver for the next release, I think that's going to happen anyway, since the IPython kernel depends on IPython, and IPython will probably install its terminal dependencies unconditionally.

**Comment by Carreau** [comment]
Hi, 

This issue has been quiet for almost 2 years, and I don't think there is anything we can do. It has been marked as no-action, and I'm going to close it to attempt to reduce the number of opened issue. Feel free to reopen if needed. 

IPython does not require readline anymore, it uses prompt_toolkit, and if you still want readline you can use rlipython frontend extension. 

Thanks.

**Comment by qris** [comment]
If you found this page because you're wondering why IPython readline support (multi-line editing) no longer works, you can install  [ptpython](https://github.com/prompt-toolkit/ptpython) and run `ptipython` to get it back.
