### ISSUE TITLE
Better support for pandas in nbconvert --to latex

### ISSUE THREAD

**Issue by lmarti** [ipython/ipython#8261]
When `nbconvert`ing a notebook to latex, pandas' DataFrames are rendered as raw (verbatim) text. pandas DataFrame has a `to_latex()` method that produces a better output.

**Comment by Carreau** [comment]
Pandas should implement a `_repr_latex_` special `_repr_*_`  so that rich latex output is handled by nbconvert. We don't special case libs in IPython.

**Comment by Carreau** [comment]
I guess you can do a PR:

```python
def _repr_latex_(self):
    return self.to_latex()
```

**Comment by lmarti** [comment]
Yes, I just tried that one and works.

**Comment by jorisvandenbossche** [comment]
@Carreau if pandas provides a `_repr_latex_`, is there still an easy way to still use the plain text repr in your latex output if you would prefer that?

**Comment by Carreau** [comment]
if you `print(df)` it shoudl use the text one. 
If globally on the all document when you convert, you just prefer the text, you can set the display_data_priority of text higher than LaTeX, to the conversion to PDF will use text if availlable. 

Doing it at conversion time, on per object/cell basis woudl need custom code.
