### ISSUE TITLE
NBExtensionApp add --activate --deactivate.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#8262]
Add option to activate and deactivate extensions using --activate and --deactivate flags.

Already implemented as a subclass in nbgrader by Jess, just need to be moved upstream at the right time.

Cf https://github.com/jupyter/nbgrader/pull/207

**Comment by Carreau** [comment]
Sorry I was opening this while still remembering to do it in the middle of another comment, description editted.

**Comment by minrk** [comment]
Great, thanks.

**Comment by damianavila** [comment]
Interesting... I like the idea of activation/deactivation...

**Comment by ptone** [comment]
See also:
https://ipython.hackpad.com/March-2015-Dev-Meeting-Cf6eyqe5Yqe#:h=Jupyter-extension-Packages
