### ISSUE TITLE
Comm messages aren't handled in ExecutePreprocessor

### ISSUE THREAD

**Issue by jhamrick** [ipython/ipython#8264]
The `ExecutePreprocessor` in nbconvert doesn't properly handle comm messages, resulting in a bunch of errors like this when using widgets or the `nbagg` matplotlib backend:

```
unhandled iopub msg: comm_open
unhandled iopub msg: comm_msg
unhandled iopub msg: comm_msg
...
```

The fix is pretty trivial; it just involves adding another if clause to the if statement that checks the message type:

```
elif msg_type.startswith('comm'):
    continue
```

I feel like this is something that should probably be fixed in 3.x, but since nbconvert has already been moved I'm not sure where I should submit the fix. Should I submit it against master, and whoever backports it will handle making the same changes on 3.x? Should I submit two PRs? Should I just wait until the split is done?

**Comment by minrk** [comment]
@jhamrick Backporting patches actually works fine across renames There's a bit in our backport script that gets in the way, but I've already applied a patch having commented that out, and it was okay.

**Comment by minrk** [comment]
After the code has actually left the repo, it will probably be a two PR process.

**Comment by jhamrick** [comment]
@minrk Ok, I'll submit a PR against master then and we'll see how that goes.
