### ISSUE TITLE
Error message about overwriting the notebook

### ISSUE THREAD

**Issue by tritemio** [ipython/ipython#8270]
Occasionally, usually with a long running notebook, I get a popup error message stating:

```
Notebook has changed since we opened it. Overwrite the changed file?
```

When I overwrite seems that I don't lose any information but the notebook folder is littered with folders with the same name of the notebook and a random suffix.

When the error happens this is printed on the terminal (this message is repeated a few times):

```
[W 11:18:08.438 NotebookApp] Permission denied: manta/manta NI timestamps multi-ch overflow to Photon-HDF5-Batch.ipynb
[W 11:18:08.440 NotebookApp] 403 PUT /api/contents/manta/manta%20NI%20timestamps%20multi-ch%20overflow%20to%20Photon-HDF5-Batch.ipynb (::1) 192.00ms referer=http://localhost:8888/notebooks/manta/manta%20NI%20timestamps%20multi-ch%20overflow%20to%20Photon-HDF5-Batch.ipynb
```

I'm using ipython 3 from anaconda on win x64.

**Comment by Carreau** [comment]
Do you have many tabs open on the same notebook ? These random names are to ensure atomic writing on notebooks (which fails). Is this a dropbox folder, or any other kind of folder with weird permissions ?

**Comment by tritemio** [comment]
I'm sure that the notebook is opened only in one tab when the error occurs. The folder is a normal windows folder that I use for my work and I never had permission errors with other programs or with ipython < 3. It happens to be inside a Dropbox folder, and I got the same error under a google drive folder. I'll try to see if I can get the error outside dropbox or gdrive folders.

**Comment by Carreau** [comment]
Ah, most likely the dropbox daemon is accessing/syncing the file while we try to save it.
Probably same thing that prevent latex from creating PDF when adobe have the PDF open.

**Comment by tritemio** [comment]
I hope ipython can handle this occurrence in a more robust way. BTW I never got this error in ipython 2, and I was always working under dropbox.

**Comment by minrk** [comment]
The tempfiles are a new behavior, and prevent data loss on failed writes. Something wonky is happening with the temp files. @Carreau might be on the right track that we are trying to delete the temp file while Dropbox is in the process of syncing it, which causes problems on Windows but won't on other platforms.

**Comment by takluyver** [comment]
Ugh, yes, the atomic writing is probably going to be nasty in synced folders if the sync daemon starts syncing before we get to rename the newly created file. Even on Unix-y systems, I think Dropbox's backup of files you delete might quickly get full of notebook saves. And I don't currently see a good way to fix that.

Gah. I wish OSs exposed a native way to write a file atomically, so we didn't have to do this rename trick.

**Comment by tritemio** [comment]
I see the underlying problem. I don't care if Dropbox backup history is littered with these temporary files. 

But having my work folder littered with temp files and the UI showing messages implying that I may loose some data is frightening.

**Comment by tritemio** [comment]
As a workaround you may try to rename the file again after X seconds. Or provide a configuration option to set the folder for temp files somewhere else, outside the synced folder.

I wonder how MS office solve this as they also use temp files whenever a document is open and there is no issue with sync folders.

**Comment by takluyver** [comment]
Saving files elsewhere could work, but you need to ensure it's on the same filesystem (otherwise you can't atomically move it, negating the benefits of atomic save). I don't know of a good cross platform way to ensure that other than putting it in the same folder, and it doesn't seem very nice to expect users to configure it themselves.

Renaming again after a few seconds doesn't really seem like a good idea. I think that's going to end up causing yet more problems, because you're no longer dealing with plain success/failure, instead you have these strange failed-but-might-succeed-soon states.

**Comment by minrk** [comment]
We could have a periodic 'cleanup temp files' sweep.

**Comment by minrk** [comment]
...or we could disable atomic save on Windows.

**Comment by tritemio** [comment]
If I understand correctly, when you save the notebook, you save to a new temp file to avoid to corrupt the original notebook. When the save completes you rename it in order to overwrite the old file and in this way you assure that the files on disk are never inconsistent/corrupted (because rename is atomic).

If this picture is correct, in order to do not loose data the rename must complete. 

When this error occurs, for some reasons, the notebook GUI shows several dialog asking to overwrite the file, so I have to click several times on overwrite until the notebook is finally saved. And the result is that a bunch of temp files are left in the folder. Would be possible to detect this situation and at least try to delete the old temp files once the save succeeds?

**Comment by Carreau** [comment]
Might be possible, but that would require making subsequent save aware of
each other, and I guess that dropbox will get a handle on temp files, and
we will actually get an error in trying to delete them while dropbox is
syncing.

**Comment by minrk** [comment]
@tritemio at the very least, we can definitely handle the failure better, yes.

**Comment by ebenolson** [comment]
I started seeing this on my git-tracked notebooks around the time of the switch to Jupyter.

**Comment by nealmcb** [comment]
I just ran across this error message for the first time, and I'm assuming it is because I did indeed have the notebook open in multiple tabs.  (Is there any way to help folks avoid that?)

To help people deal with it and distinguish dangerous situations from other causes, how about providing a bit more info?  E.g. show the timestamps and file sizes in question, or let the user see a diff of the notebooks, or perhaps provide a way to let them make the diff themselves, maybe by saving to a temp file and showing them the file names for copy/paste, or something else along those lines.

**Comment by scholer** [comment]
I have the same issue on a dropbox-synced folder. For now - as a short term fix - I'd really like to get a command-line switch to disable atomic save. That way, I can use that to avoid errors when running a server for notebooks in my dropbox (about half of them) and I can still have atomic save for the other half of my notebooks that are not in my dropbox.

**Comment by takluyver** [comment]
In jupyter/jupyter_notebook#45, I make it use names that Dropbox should ignore for the temporary files, which should improve matters.

If you need to patch it out in the meantime, you can find the relevant line here:

https://github.com/ipython/ipython/blob/rel-3.1.0/IPython/html/services/contents/fileio.py#L123

By replacing `self.atomic_writing()` with `open()`, you should get regular saving back.

**Comment by tritemio** [comment]
jupyter/notebook#67 may solve this issue, would be useful to backport to 3.x

**Comment by takluyver** [comment]
I think that's too big a change to backport. We rushed into backporting the original atomic save mechanism, and I now think we shouldn't have. The good news is that we're aiming to have 4.0  quite soon.

**Comment by takluyver** [comment]
Hopefully this is better now. If it still comes up, please open a new issue on jupyter/notebook.
