### ISSUE TITLE
Make OutputArea.display_order configurable (js)

### ISSUE THREAD

**Issue by flying-sheep** [ipython/ipython#8279]
Hi, i’d like to display PNGs for one notebook with many plots containing many points (and therefore bad performance when using SVG)

it would be nice to configure the display preference without limiting the formats available in the notebook JSON.

[here](https://github.com/ipython/ipython/blob/ff02638008de8c90ca5f177e559efa048a2557a0/IPython/html/static/notebook/js/outputarea.js#L941-L951) is the relevant (hardcoded) code.

**Comment by minrk** [comment]
You can change the notebook's display order in custom.js:

```javascript

require(['notebook/js/outputarea', function (oa) {
    oa.OutputArea.display_order = ['my', 'display', 'order'];
});
```

Changing the display preference in the live notebook doesn't affect what is stored in the notebook JSON at all.

But what you might actually be after is `IPython.display.set_matplotlib_formats('png')`, which sets the matplotlib figure format. You can switch between png, svg, and (depending on availability) jpg.

**Comment by flying-sheep** [comment]
thanks! a bit complicated though ;)

> Changing the display preference in the live notebook doesn't affect what is stored in the notebook JSON at all.

yeah, i know. my question didn’t mean that i thought it would, only that a workaround would be to set that order.

**Comment by flying-sheep** [comment]
this won’t cut it:

calling this changes the order for all newly rendered outtputs, but not existing ones.

so even when doing `display_html('<script>…</script>')` in the first cell, i still get SVGs displayed when re-loading the notebook.

**Comment by flying-sheep** [comment]
For the record, here’s how to modify this:

```javascript
display_javascript("""
require(['notebook/js/outputarea'], function (oa) {
	//remove png
	var i_png = oa.OutputArea.display_order.indexOf('image/png')
	oa.OutputArea.display_order.splice(i_png, 1)
	
	//insert png before svg
	var i_svg = oa.OutputArea.display_order.indexOf('image/svg+xml')
	oa.OutputArea.display_order.splice(i_svg, 0, 'image/png')
})
""")
````

**Comment by flying-sheep** [comment]
Moved to jupyter/notebook#1488

**Comment by Carreau** [comment]
Thanks for migrating that @flying-sheep !
