### ISSUE TITLE
ExecutePreprocessor should stop and propagate the error

### ISSUE THREAD

**Issue by tritemio** [ipython/ipython#8286]
`ExecutePreprocessor()` does not stop when it encounters an error on the notebook but pass to execute the following cells.

Ideally `ExecutePreprocessor().preprocess()` should stop the execution on error and propagate the exception raised in the notebook. Runipy with ipython 2.x used to work exactly in this way.

Here an example to reproduce the issue:

```
from IPython import nbformat
from IPython.nbconvert.preprocessors import ExecutePreprocessor

nb_name = 'notebook_with_error.ipynb'
nb = nbformat.read(nb_name, as_version=4)
ep = ExecutePreprocessor(timeout = 3600)
out = ep.preprocess(nb, {'metadata': {'path': nb_name_out}})
nbformat.write(nb, nb_name_out)
```

I would like to be able to use a scheme like the following to execute notebooks:

```
nb_name = 'notebook_with_error.ipynb'
nb = nbformat.read(nb_name, as_version=4)
ep = ExecutePreprocessor(timeout = 3600)
try:
    out = ep.preprocess(nb, {'metadata': {'path': nb_name_out}})
except Exception as e:
    msg = 'Error executing the notebook "%s".\n\n' % notebook_name
    print(msg)
    raise e
finally:
    nbformat.write(nb, nb_name_out)
    display(FileLink(nb_name_out))
```

**Comment by tritemio** [comment]
A temoporary workaround is monkey-patching `ExecutePreprocessor` like this:

```
from IPython.nbconvert.preprocessors import ExecutePreprocessor
from IPython.nbformat.v4 import output_from_msg

def preprocess_cell(self, cell, resources, cell_index):
    """
    Apply a transformation on each code cell. See base.py for details.
    """
    if cell.cell_type != 'code':
        return cell, resources

    outputs = self.run_cell(cell)
    cell.outputs = outputs

    for out in outputs:
        if out.output_type == 'error':
            self.log.error('Error executing the following cell:')
            self.log.error(str(cell.source))
            raise RuntimeError('Error executing the notebook.')

    return cell, resources

ExecutePreprocessor.preprocess_cell = preprocess_cell
```

**Comment by takluyver** [comment]
A few people have requested this, I think we've agreed that it should be a configurable option, but anyone wanting to implement it should probably hold off for the repo split.

**Comment by tritemio** [comment]
Is there any use case for the current behaviour?

**Comment by jhamrick** [comment]
Yes. For example, if you have a demo notebook that purposefully includes an exception, you still want to execute the cells below it. nbgrader makes use of the current behavior because we still want to grade students' solutions even if they have an error earlier in the notebook.

The current behavior should definitely not go away, so having it be a configurable option would be best.

**Comment by tritemio** [comment]
Ok, it makes sense. 

If you wish I can send a PR once the split if over and then move from there.

There will be another 3.2 release soon? I'm thinking what the best path for me right now if I want to support current ipython and be also as much "future proof" as I can. I have some analysis that is going into a paper and I don't want it to break in a few months from now.

**Comment by Carreau** [comment]
There shouldn't be another 3.x release before a month I guess.

**Comment by jhamrick** [comment]
My guess is that the most future-proof way to do it would be to check the outputs of the cells after the notebook has completely finished executing. That way, you'll always catch your errors now, and when the behavior does eventually change, the exception will just happen sooner.

**Comment by takluyver** [comment]
Nbconvert now stops and throws CellExecutionError by default when it sees an error.
