### ISSUE TITLE
Backport IPython.nbformat (read)

### ISSUE THREAD

**Issue by FRidh** [ipython/ipython#8295]
`IPython.nbformat` in IPython 3.x has functions to read and write notebooks and which take as argument the nbformat version the notebook should be converted to.

Could the functions in this module also be backported to 2.x? While they're trivial to implement this would make it easier for other code to support IPython 2.x and 3.x. A use case would be supporting IPython 2.x and 3.x and each nbformat version in Pelican liquid tags.

Or would you suggest waiting for [jupyter_nbformat](https://github.com/jupyter/jupyter_nbformat)?

**Comment by minrk** [comment]
There may not be another 2.x release, so I'm not sure what good backporting it to the 2.x branch will accomplish. But it's a reasonable idea.

**Comment by minrk** [comment]
There won't be another 2.x release with any new features.
