### ISSUE TITLE
ipython kernelspec install should install to sys.prefix

### ISSUE THREAD

**Issue by asmeurer** [ipython/ipython#8299]
`ipython kernelspec install` seems to install to `/usr/local`. It would be better if it installed to `sys.prefix` by default. This would make it play much nicer with conda environments (probably virtualenvs too).

On a related note, https://ipython.org/ipython-doc/dev/development/kernels.html#kernel-specs doesn't mention that prefix relative installs are possible.

**Comment by Carreau** [comment]
No I dont' think we should, and it has been dicussed in person and in [some issues](https://github.com/ipython/ipython/pull/7124). Kernelspec are not python specific, and it is not clear that installing in sys.prefix is the right thing to do. 

We can rediscuss again, but I doubt this will change.

**Comment by asmeurer** [comment]
This has nothing to do with being Python specific.

**Comment by minrk** [comment]
If we used sys.prefix, we'd need to be very careful and have quite a few special cases, because it has often the wrong value on OS X (/System/Library or /Library or /usr/local/Cellar) and debian (/usr), in all of which cases installs should go in /usr/local. It's also the wrong thing to use on Windows.

**Comment by takluyver** [comment]
When we've had this discussion previously, it has come round to 'maybe we should provide a flag to specify the target directory explicitly', followed by 'wait, that would just be an incredibly verbose spelling of `cp`'

**Comment by asmeurer** [comment]
Hmm, I have also seen sys.prefix be "wrong". I don't know why or how they do that. But assumedly systems that do change sys.prefix are doing so because they want things to be installed into that prefix instead of where Python really is. 

> When we've had this discussion previously, it has come round to 'maybe we should provide a flag to specify the target directory explicitly', followed by 'wait, that would just be an incredibly verbose spelling of cp'

You can't necessarily cp after installing, because you might not even have permissions to write /usr. And anyhow, I think to most people, what `ipython kernelspec install` actually does can be opaque. The fact that it's just `cp` is not clear at all. 

It also complicates things like https://github.com/IRkernel/IRkernel/blob/0b64531109e1ca10c1a19c164d72dd2246566f86/R/kernel.r#L248 (which is where this originates for me; in my recipe for IRKernel, I have to [use cp](https://github.com/conda/conda-recipes/blob/aca156081ba5d2a3a9f14e23c7e8f0f9a4bc9621/r-packages/r-irkernel/build.sh#L13)).

**Comment by takluyver** [comment]
Discussion continues in jupyter/jupyter_core#61 and jupyter/jupyter_core#75. Closing here.
