### ISSUE TITLE
Unwanted Slide Fragments Created

### ISSUE THREAD

**Issue by damontallen** [ipython/ipython#8304]
I haven't been able to locate another issue or PR that contains this problem so I cannot say how it showed up.  The problem is that once I show a fragment in a slide show ever cell after that in every other slide becomes a fragment if it wasn't a slide or sub-slide.  This [example notebook](http://nbviewer.ipython.org/format/slides/urls/gist.githubusercontent.com/damontallen/8362d0dd3d2e52c02a03/raw/bdf679253cdcda25f93126d8914b18068e342451/Untiltled.ipynb#/) only has one fragment in it but fragments appear on every slide after the first one.

I believe this showed up with 3.0 but it is still present in 3.1.

I do know it must be in nbconvert.

**Comment by takluyver** [comment]
Ping @damianavila

**Comment by damianavila** [comment]
OK, I will take a look :+1:

**Comment by damianavila** [comment]
pinging here to let you know I think I know the issue and I will try to come with a fix in the jupyter-nbconvert demo (then we can discuss there if we need a backport to 3.next, although probably we will need it).

**Comment by takluyver** [comment]
We are planning to make the 3.x -> 4.x cycle considerably shorter than usual - we'll pretty much be releasing 4.0 once we have the separate repositories sufficiently stabilised, I think. Backporting stuff to 3.x will be much more painful than usual, so it's in all of our interests to get 4.0 out soon.

**Comment by damianavila** [comment]
OK, sounds good :+1:

**Comment by takluyver** [comment]
See jupyter/jupyter_nbconvert#9
