### ISSUE TITLE
notebooks should save and restore view settings for header and toolbar

### ISSUE THREAD

**Issue by lstead** [ipython/ipython#8308]
Very annoying to have to reset view settings every time I open a notebook. Notebook should restore settings from previous saved session when loaded. 

Thanks

**Comment by wjjsun** [comment]
Actually, you can customize it. refer to [ipython notebook toolbar customize](http://stackoverflow.com/a/29851084/1914781)

**Comment by takluyver** [comment]
Just to check, are you referring to the hidden/visible state of the header and toolbar?

**Comment by lstead** [comment]
On 4/24/15 12:58 PM, Thomas Kluyver wrote:
>
> Just to check, are you referring to the hidden/visible state of the 
> header and toolbar?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ipython/ipython/issues/8308#issuecomment-95991992>.
>



yes, i wanted notebooks to open w/o showing the header & toolbar.

i'm using ipython to teach a class, so my laptop is projected. the
header & toolbar take up too much space, are kind of distracting,
and i never use the toolbar.

i just installed it and works perfectly!  there is a typo in the stack 
overflow
the 2nd piece of code, the thing i installed, goes in 'custom.js', not
'custom.css'

THANK YOU SO MUCH,

larry

**Comment by Carreau** [comment]
Comment on SO fixed.

**Comment by vovkkk** [comment]
Sometimes (usually right after starting server), I get message in Firefox console:

```
ReferenceError: $ is not defined custom.js:1:0
```

and header & toolbar are **not** being hidden. Later as I reopen notebook or open others all works fine, my custom.js:

```js
$([IPython.events]).on("app_initialized.NotebookApp", function () {
  $('div#header-container').hide();
  $('div#maintoolbar').hide();
});
```

Also, on SO it says `div#header` — it doesn’t work in 3.1.0, should be `div#header-container`

**Comment by Carreau** [comment]
Your custom.js is wrong. you need to `require()` of `define()` the module you use or you get a race condition. Don't trust what SO says, check the dates, and the version for which the answer is (here IPython 1.x))

**Comment by vovkkk** [comment]
> you need to require() of define() the module

i don’t speak in alien, following code seems to work, but who knows what may happen if it’s wrong, please let me know how it should be exactly

```js
require(["base/js/events"], function (events) {
$([IPython.events]).on("app_initialized.NotebookApp", function () {
  $('div#header-container').hide();
  $('div#maintoolbar').hide();
});
});
```

More recent topics are somewhat misleading as well, e.g. http://stackoverflow.com/questions/28876235/ipython-notebook-3-hide-headers-by-default

**Comment by Carreau** [comment]
Roughtly correct. 

```
require(["base/js/events"], function (events) {
events.on("app_initialized.NotebookApp", function () {
  $('div#header-container').hide();
  $('div#maintoolbar').hide();
});
});
```

`$([IPython.events])` -> `events` as you have a `function (events)`.

Javascript is ... let say "complicated", and the API is in motion, so we assume that any people that mess with javascript and custom.js know what they are doing and can keep-ip with dev. 

Hiding the elements like that might break the measurement on page height a bit so might have some layout issues. You should check how the menu item to hide things do it.

**Comment by vovkkk** [comment]
Thank you for clarification.

I use custom.js just because there is no settings to hide toolbar by default.
