### ISSUE TITLE
Argument to supress import warnings from pylab/matplotlib magic

### ISSUE THREAD

**Issue by npezolano** [ipython/ipython#8315]
Tracking this as an issue first to track changes / opinions.

I want to be able to remove the message ```Populating the interactive namespace from numpy and matplotlib``` produced by calling ```%pylab inline``` or ```%matplotlib inline```.

I want to add a simple flag to disable the message from this.

https://github.com/ipython/ipython/blob/master/IPython/core/magics/pylab.py#L146

**Comment by Carreau** [comment]
`%matplotlib inline` does not produce the warning (if it does it is a bug), pylab produce the warning because it is explicitely a bad habit we don't recommend to use and don't support. Nowhere in our docs should `pylab` be mentioned (except few edge cases).

So I doubt any way to remove the warning will be accepted, it will more go in the opposite direction.

**Comment by npezolano** [comment]
Ah sorry for the misconception, so the solution is to simply not use `%pylab inline` and add a call to `import matplotlib.pyplot as plt` in my case. Closing this.

**Comment by Carreau** [comment]
yeah, basically 

```
import numpy
import matplotlib
from matplotlib import pylab, mlab, pyplot
np = numpy
plt = pyplot

from IPython.core.pylabtools import figsize, getfigs

from pylab import *
from numpy import *
```

Here is my **personal** thought of why no pylab : http://carreau.github.io/posts/10-No-PyLab-Thanks.html

**Comment by aleeshajaganath** [comment]
I too had the same issue when i put "image_to_crop=plt.imread('__')" inside for loop. It got resolved when i removed from loop

**Comment by lemelinm** [comment]
But what about the message : «Populating the interactive namespace from numpy and matplotlib ». What does it mean?
