### ISSUE TITLE
Security issue:  Missing Secure Attribute in Encrypted Session (SSL) Cookie

### ISSUE THREAD

**Issue by dockter-84** [ipython/ipython#8325]
"IBM Security AppScan Standard" found that an encrypted session (SSL) is using a cookie without the "secure" attribute.

The following is from the "AppScan" report:

__Risk:__ It may be possible to steal user and session information (cookies) that was sent during an encrypted session.  This is because The web application sends non-secure cookies over SSL
   
Basically the only required attribute for the cookie is the "name" field. Common optional attributes are: "comment", "domain", "path", etc. The "secure" attribute must be set accordingly in order to prevent to cookie from being sent unencrypted.

RFC 2965 states:
"The Secure attribute (with no value) directs the user agent to use only (unspecified) secure means to contact the origin server whenever it sends back this cookie, to protect the confidentially and authenticity of the information in the
cookie."

For further reference please see the HTTP State Management Mechanism RFC 2965 at:  http://www.ietf.org/rfc/rfc2965.txt
and for "Best current practice" for use of HTTP State Management please see
http://tools.ietf.org/html/rfc2964

```html
GET /ipython/login?next=%2Fipython%2Ftree HTTP/1.1
Accept-Language: en-US
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Referer: https://appscanprod.stage1.mybluemix.net/ipython/tree
Host: appscanprod.stage1.mybluemix.net
User-Agent: Mozilla/5.0 (Windows NT 6.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/41.0.2272.118 Safari/537.36

HTTP/1.1 200 OK
X-Backside-Transport: OK OK
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Security-Policy: frame-ancestors 'self'; report-uri /ipython/api/security/csp-report;
Content-Type: text/html; charset=UTF-8
Date: Wed, 08 Apr 2015 06:30:41 GMT
Etag: "8c156d6c177bcd2148bf9c3c91e99e7ef715700e"
Server: nginx/1.6.2
X-Cf-Requestid: 1b2cb25a-99a3-4e2d-7b9a-6134f16ac4c1
X-Client-IP: 9.121.242.83
X-Global-Transaction-ID: 533871689
Set-Cookie: username-appscanprod-stage1-mybluemix-net=; expires=Tue, 08 Apr 2014 06:30:41 GMT;
Path=/
x-ua-compatible: IE=edge
```

### Possible fix

1. IPython needs to set "secure=True" when calling tornado's Request Handler.
      1. In ```/usr/local/lib/python2.7/dist-packages/IPython/html/auth/login.py```, change:
         1. From: ```self.set_secure_cookie(self.cookie_name, str(uuid.uuid4()))```
         1. To: ```self.set_secure_cookie(self.cookie_name, str(uuid.uuid4()), secure=True)```
1. References:
      1. [How to set the "secure" attribute of a secure cookie](https://groups.google.com/forum/#!topic/python-tornado/iP6j7VrCSEk)

**Comment by Carreau** [comment]
Hi, thanks for the report, we will have a look. 

For security vulnerability disclosure, in general you can contact `security@ipython.org` before posting a public description.

**Comment by ssanderson** [comment]
@Carreau since this is a potential security issue, should it be backported to 3.x?

**Comment by Carreau** [comment]
> @Carreau since this is a potential security issue, should it be backported to 3.x?

I'm not 100% sure, but that seem easy to backport.
