### ISSUE TITLE
grayed out scrollbars appearing for long text markdown

### ISSUE THREAD

**Issue by rlabbe** [ipython/ipython#8327]
Recently I've noticed that my notebooks are filled with inoperable scrollbars. Many of the cells have a grayed out scrollbar drawn beside it. All of the content is visible; scrolling is not required.  I've done some tests and with the same notebook they do not appear in IPython 3.0, but do appear with version 3.1.  This is in Chrome version 41, Windows 7 and Windows 8. I've not tested elsewhere.

I've pasted an example below which includes text and latex for a markdown cell. However, the same thing is happening with code output.

![image](https://cloud.githubusercontent.com/assets/5308143/7184278/5405f58e-e411-11e4-8757-4bb924f170b4.png)

This is the markdown for that cell

Now we are prepared to compute the covariance matrix. The *covariance* measures how much two random variables move in the same direction, and is defined as

$$ COV(x,y) = \frac{1}{N}\sum_{i=1}^N (x_i - \mu_x)(y_i - \mu_y)$$

If we compare this to the formula for the variance of a single variable we can see where this definition came from.

$$\sigma^2 = \frac{1}{N}\sum_{i=1}^N(x_i - \mu)^2$$

And indeed, the covariance of a variable with itself is just the variance of the variable, which we can trivially prove with

$$\begin{aligned}
COV(x,x) &= \frac{1}{N}\sum_{i=1}^N (x_i - \mu_x)(x_i - \mu_x) \\
&= \frac{1}{N}\sum_{i=1}^N (x_i - \mu_x)^2 \\
&= VAR(x)
\end{aligned}$$

Let's build some familiarity with this by calculating the covariance for the $\mathbf{x}$ from the beginning of this section.

$$\mathbf{x}_0 = \begin{bmatrix}1 \\8\\3\end{bmatrix},\ \  \mathbf{x}_1 = \begin{bmatrix}3\\7\\7\end{bmatrix}$$

We already know the mean is

$$\mu_x = \begin{bmatrix}2\\7.5\\5\end{bmatrix}$$

**Comment by koenvb** [comment]
Tried the code on Mac OS X 10.10.3 with 
* Safari Version 8.0.5 (10600.5.17) and 
* Chrome Version 42.0.2311.90 (64-bit)

With ipython 3.1.0 and python 3.4 
But no strange scrollbars

Could you share the notebook just for trying?
What happens in IE or firefox? Just to see if its a chrome issue or not?

**Comment by rsmith31415** [comment]
Tested in Chrome 42 in Linux and wasn't able to reproduce it. Can you tell what extensions you have installed?

**Comment by rlabbe** [comment]
I put the markdown above in as gist.
http://nbviewer.ipython.org/gist/rlabbe/50211d9302c06a9a9abd

gist is here
https://gist.github.com/rlabbe/50211d9302c06a9a9abd

I'm quite ignorant as to what nbviewer is doing, but I assume that using it isolates me from whatever extensions I have installed (the Calico spellchecker). When I view the gist on my computer via chrome and nbviewer, I see the scrollbar. If I view it in IE, I do **not** see it.

Windows 8.1
IPython 3.1.0
Python 3.4.3
Anaconda Installation
Chrome Version 42.0.2311.90 m
IE version 11.0.9600.17728


I went to my girlfriend's computer. She is not a developer and does not have Python or any sw stack installed. Similar results (visible in Chrome, not in firefox):
Windows 7
Firefox 37.0.1
Chrome 42.0.2311.90 m

**Comment by rsmith31415** [comment]
@rlabbe Now I can see the issue in IPython 3.1. This seems to have been fixed in master. Can you try that?

**Comment by rlabbe** [comment]
I'm somewhat reluctant to install master on this machine. I can try it on a virtual machine later. I will note that I believe the problem only happens when the last line in the cell is latex with a somewhat large matrix. For example, a cell ending with the following latex will have the scroll bar.

$$\mathbf{Q_c} = \begin{bmatrix}0&0&0\\0&0&0\\0&0&1\end{bmatrix} \Phi_s$$

**Comment by rsmith31415** [comment]
Yes, I forgot to describe that cause of this issue. Well, you can try later in master. Hopefully it has been fixed.

**Comment by minrk** [comment]
closing in favor of jupyter/notebook#735
