### ISSUE TITLE
Notebook: interactive matplotlib backend error

### ISSUE THREAD

**Issue by tritemio** [ipython/ipython#8332]
I'm getting instabilities when using an interactive backend like nbagg or qt in the ipython notebook on windows 7 x64 (Anaconda, python 2, ipython 3 or 3.1).

Sometimes the figure does not show up and after a 1-2 seconds a static version appears in the notebook output area.

At the same moment the log show 8 lines like this:

```
[IPKernelApp] ERROR | No such comm: b4b1eca358a04bec96bd8f82dc64e4ed
```

I'm not able to reproduce it systematically but it's quite frequent.

**Comment by tacaswell** [comment]
Smells like a race condition to me.

attn @pelson

**Comment by pelson** [comment]
The fact that the figure appears (statically) means that an image has been transferred via the comm.
@tritemio - do you get any other problems with the notebook? I'm wondering if the socket is being killed off or something - do you have any antivirus/network security software running?

**Comment by tritemio** [comment]
No other problems that I'm  aware of.  There is sophos av running.

**Comment by tritemio** [comment]
@pelson, sorry, the only anti-virus running on this machine is the built in MS Security Essential.

**Comment by jenshnielsen** [comment]
Which version of matplotlib? There was a bug with IPython 3.x and the notebook backend fixed in 1.4.3

**Comment by tritemio** [comment]
@jenshnielsen  I'm running the current matplotlib in Anaconda which is 1.4.3

**Comment by takluyver** [comment]
Closing for now as probably not an IPython bug. We can reopen (or open a new bug on one of the other repos) if there's something for us to do. Feel free to keep using these comments to debug.
