### ISSUE TITLE
No difference in behaviour between slide "-" and slide "Fragment" in notebook slides

### ISSUE THREAD

**Issue by toastmaker** [ipython/ipython#8335]
For many presentations, I used to have a slide with markdown (text, title, equations) and code producing a plot mixed on a single slide (using the first slide as markdown slide marked as type Slide and the second with the Python code marked as type "-". And they were concatenated in a single slide in a resulting presentation. It does not work anymore, now it operates exactly the same way like if the second part were a fragment. 

```
Cell type: Slide
Markdown: title, text

Cell type: -
Code: python code to produce a plot
```

Generates two a slide with the first content and you have to move to the next one to get the Python code to appear. In other words, it now behaves identically to:

```
Cell type: Slide
Markdown: title, text

Cell type: Fragment
Code: python code to produce a plot
```

In a slideshow, slides of the type "-" act exctly like the type "Fragment".
with a need to turn a page betweem slides. Is there a workround before a fix is given? (Anaconda distribution iPython 3.1.0)

**Comment by takluyver** [comment]
Ping @damianavila - was something else like this reported recently?

**Comment by damianavila** [comment]
Yes, this is the same as #8304. @takluyver can you close this one and also #8304 in favour of the issue raised in the `jupyter_nbconvert` repo?: https://github.com/jupyter/jupyter_nbconvert/issues/9 
Thanks.
