### ISSUE TITLE
No new line on input if terminal width is increased

### ISSUE THREAD

**Issue by alexrichert** [ipython/ipython#8338]
I am using ipython 2.3.0-1 (current version for Fedora 21), and run into the following problem. 
Suppose I type or paste the following 104 characters into an ipython prompt:

    In [1]: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrst
    uvwxyzabcdefghijklmnopqrstuvwxyz

where the new line after the letter "t" corresponds with a terminal of width 80 characters. However, if I increase the width of the terminal window at all (to, say, 81 characters):

    uvwxyzabcdefghijklmnopqrstuvwxyzyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrst

There is no new line, and my input so far gets obscured/overwritten (though it will still run the command as entered). It works fine if I resize the window back to 80 characters in width or less. If I start ipython in a larger terminal window (100 char instead of the typical 80), then once again, this problem only presents itself when the terminal window is enlarged width-wise, and goes away as soon as I re-shrink the window to the size it was when I started up ipython.

**Comment by takluyver** [comment]
I don't think IPython has that level of control over your terminal - we don't get keystroke-by-keystroke updates, and we don't handle SIGWINCH. So I suspect this is a bug in either your terminal emulator or readline.

**Comment by alexrichert** [comment]
Hm yes, it appears so, sorry about that. It's also happening in normal python and R, so it looks like I will be taking my bug reports elsewhere!

**Comment by takluyver** [comment]
No worries, good luck with getting it fixed!

**Comment by alexrichert** [comment]
Actually it looks like this is not really a bug, it's just something 
that only bash seems to have implemented a solution for by checking the 
terminal width after each keystroke. So this could be a feature request, 
but I have no idea how involved it would be to implement or what the 
drawbacks might be. A sort of workaround is to run "stty columns 10000" 
(or other large number) in the shell before opening python/R/whatever, 
except that there is subsequently no way to delete back to the previous 
line once a new line has been inserted...
