### ISSUE TITLE
Docs show inconsistent naming for config directories (/usr/share/*jupyter*/kernels vs ~/.*ipython*/kernels)

### ISSUE THREAD

**Issue by jaredly** [ipython/ipython#8349]
Do the docs need to be updated, or is the `~/.ipython` directory a carryover from the past that will be phased out?
![image](https://cloud.githubusercontent.com/assets/112170/7255271/6733a97e-e805-11e4-930a-a1c0abc76001.png)

https://ipython.org/ipython-doc/dev/development/kernels.html#kernel-specs

**Comment by minrk** [comment]
Those are the correct values for IPython 3. The user directory will move to a Jupyter location in 4.0.

**Comment by takluyver** [comment]
The docs will need to be updated. The user-specific location for this will be platform-dependent:

- Linux: `~/.local/share/jupyter/kernels` (or elsewhere if `$XDG_DATA_HOME` is set)
- OS X: `~/Library/Jupyter/kernels`
- Windows: `C:\Users\{username}\AppData\Roaming\kernels` (or elsewhere if `%APPDATA%` is set to something other than the default).

**Comment by jaredly** [comment]
cool, good to know
