### ISSUE TITLE
reload sys prevents new cell outputs

### ISSUE THREAD

**Issue by denfromufa** [ipython/ipython#8354]
import sys
reload(sys)
print 'no output is displayed'

**Comment by denfromufa** [comment]
the output goes to console instead of notebook

**Comment by takluyver** [comment]
`sys.stdout` is where print output is written to. Reloading sys presumably resets it to the default location. Why would you reload sys?

**Comment by denfromufa** [comment]
http://stackoverflow.com/questions/3828723

**Comment by takluyver** [comment]
As the answers to that question point out, using `sys.setdefaultencoding()` is not recommended. It's removed from sys normally for a reason. Python is flexible enough that you can do things that will break IPython, and this is one such thing.

**Comment by midnightradio** [comment]
I need both 'stdout' and 'setdefaultencoding' but the latter breaks the other. One possible workaround here is backing up the reference and restoring stdout after reload(sys).

```
import sys
default_stdout = sys.stdout
default_stderr = sys.stderr
reload(sys)
sys.stdout = default_stdout
sys.stderr = default_stderr
```

**Comment by jamesrkg** [comment]
Thanks @midnightradio - on behalf of all of us who like/need to break the rules occasionally!

**Comment by takluyver** [comment]
Closing as I don't think there's anything for us to fix here.

For future readers who may come across this: `sys.setdefaultencoding()` is probably not the right way to solve your problem, and it may well cause other problems.
