### ISSUE TITLE
IPython notebook stopped to work after IPython 3.1.0 upgrade

### ISSUE THREAD

**Issue by intscorpio** [ipython/ipython#8362]
Couldn't find any info about the issue on the Internet.

```
ipython notebook --profile=nbserver

[I 13:37:05.577 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
[W 13:37:05.586 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 13:37:05.586 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 13:37:05.588 NotebookApp] Serving notebooks from local directory: /home/kovalev
[I 13:37:05.588 NotebookApp] 0 active kernels 
[I 13:37:05.588 NotebookApp] The IPython Notebook is running at: http://[all ip addresses on your system]:8888/
[I 13:37:05.588 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 574, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 367, in start
    return self.subapp.start()
  File "/usr/local/lib/python2.7/dist-packages/IPython/html/notebookapp.py", line 1092, in start
    self.io_loop = ioloop.IOLoop.current()
AttributeError: type object 'IOLoop' has no attribute 'current'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True


sudo pip freeze

alabaster==0.7.3
apt-xapian-index==0.44
awscli==1.6.2
Babel==1.3
backports.ssl-match-hostname==3.4.0.2
bcdoc==0.12.2
boto==2.33.0
botocore==0.73.0
certifi==14.5.14
chardet==2.0.1
colorama==0.2.5
command-not-found==0.2.44
decorator==3.4.0
docutils==0.12
Fabric==1.3.2
gevent==0.13.6
GnuPGInterface==0.3.2
GraphLab-Create==1.3.0
greenlet==0.3.1
iotop==0.4.4
ipython==3.1.0
Jinja2==2.7.3
jmespath==0.5.0
jsonschema==2.4.0
language-selector==0.1
librato-metrics==0.4.9
lockfile==0.10.2
lorem-ipsum-generator==0.3
luigi==1.1.2
M2Crypto==0.21.1
MarkupSafe==0.23
mistune==0.5.1
mixpanel-py==3.1.1
msgpack-python==0.1.10
nltk==3.0.1
nose==1.3.6
numexpr==2.4
numpy==1.9.2
numpydoc==0.5
pandas==0.16.0
paramiko==1.7.7.1
prettytable==0.7.2
ptyprocess==0.4
pyasn1==0.1.7
pycrypto==2.4.1
pycurl==7.19.0
Pygments==2.0.2
pyOpenSSL==0.12
PyStemmer==1.3.0
python-apt===0.8.3ubuntu7.2
python-augeas==0.4.0
python-daemon===UNKNOWN
python-dateutil==2.4.2
python-debian===0.1.21ubuntu1
pytz==2015.2
PyYAML==3.10
pyzmq==14.5.0
requests==0.8.2
rsa==3.1.2
six==1.9.0
snowballstemmer==1.2.0
Sphinx==1.3.1
sphinx-rtd-theme==0.1.7
terminado==0.5
tornado==4.1
transliterate==1.7.3
ufw==0.31.1.post1
unattended-upgrades==0.1
virtualenv==12.1.1
xlrd==0.9.3
```

**Comment by minrk** [comment]
That sounds like there's an old version of pyzmq and/or tornado, but pip freeze suggests that both are up to date. What do you get from:

```python
import tornado
import zmq
print(tornado.version, tornado.__file__)
print(zmq.__version__, zmq.__file__)

from zmq.eventloop import ioloop
print(ioloop.IOLoop)
loop = ioloop.IOLoop.current()
```

?

**Comment by intscorpio** [comment]
Hi minrk,
thanks for a reply.
Here is an output:
In [3]: import tornado

In [4]: tornado.version_info
Out[4]: (4, 1, 0, 0)

In [5]: tornado.version
Out[5]: '4.1'

In [6]: import zmq

In [7]: zmq.__version__
Out[7]: '14.5.0'

In [8]: zmq.__file__
Out[8]: '/usr/local/lib/python2.7/dist-packages/zmq/__init__.pyc'

In [9]: from zmq.eventloop import ioloop

In [10]: ioloop.IOLoop
Out[10]: zmq.eventloop.ioloop.ZMQIOLoop

In [11]: loop = ioloop.IOLoop.current()

In [12]: loop
Out[12]: <tornado.platform.epoll.EPollIOLoop at 0x1a93d10>

It looks like everything is OK with tornado and zmq.

**Comment by minrk** [comment]
Hm, now that's tricky because that's the same code that's failing in your example. Could you humor me and uninstall pyzmq, tornado, and IPython, and then reinstall them?

**Comment by minrk** [comment]
Can you also check what you get from `cat $(which ipython)`? and `which -a ipython`?

**Comment by minrk** [comment]
and `echo $PYTHONPATH`

**Comment by intscorpio** [comment]
I have done exactly that. I completely reinstalled ipython and all its dependencies. And now it works. I don't have any idea what was wrong with previous installation as all commands outputs look the same.

Btw cat $(which ipython) gives me something like that 
�I����L���]���H��I��I���21�H���4��H��H�D$X�`H��$�H�hL�l$(H�T$0L�|$0H��H�L$ H��H�D$8�����<%����I�ԉEH��I�T$��L���l���J�<�����H��H�D$(����H��#AH�5�<1�H�xH�G�
���H�5�AH�=i<H���H��tH�H�1�1��"���1ɀz0L�bH�T$��L$����H�T$H�E1�L$A�4$@��Lc�B�D� Ek�

which -a python
/usr/bin/python

and
echo $PYTHONPATH
"empty output"

Still interested how to deal with such problems in future.

**Comment by minrk** [comment]
THe problem was that either tornado or pyzmq was too old, or *possibly* was only partially upgrade (unlikely). I'm not sure quite how it managed to get that way, but uninstalling and reinstalling components that are the wrong version is one way to fix such things.

**Comment by intscorpio** [comment]
Thank you, minrk!

**Comment by evvanderplas** [comment]
Thanks a bunch, this happened with my jupyter/ipython notebook as well. Reinstalling pyzmq (with conda) revived my notebook!
