### ISSUE TITLE
Creating new cell should move the cursor to that cell

### ISSUE THREAD

**Issue by dchandan** [ipython/ipython#8363]
Currently creating a new cell with the shortcuts does not automatically place the cursor in the new cell. One has to use the mouse to click on the new cell to bring the cursor to that cell. This feels like an interruption to a smooth shortcut based work-flow. Could this be fixed please?

**Comment by Carreau** [comment]
Creating a new cell does focus it for me, and enter make it enter edit mode.

Can you precise your IPython version and the shortcut you use?

**Comment by dchandan** [comment]
I a using version 3.1.0, browser Safari on Mac. But I only upgraded to 3.1.0 yesterday and was experiencing this issue with the previous 3.x builds too. I use the following shortcuts:
Ctrl + m, a
Ctrl + m, b
Ctrl + m, m
Ctrl + m, 1-6

**Comment by Carreau** [comment]
Please read the [notes]((http://ipython.org/ipython-doc/2/whatsnew/version2.0.html#modal-user-interface)) about the keyboard shortcut interface that have changed in 2.0 almost 1 and a half year ago . 

Ctrl+m is not used any more, and you are, as expected in command mode after entering one of theses shortcut, you do not need to use the mouse but just get back into edit mode.
