### ISSUE TITLE
nbformat.read sometimes gives image data as list of bytes?

### ISSUE THREAD

**Issue by arve0** [ipython/ipython#8369]
I get some strange behavior when testing [my code](/arve0/ipynbcompress) in tox, which is **not reproducible** every time.

This is my code:
```python
nb = read(filename, as_version=4)
outputs = [cell.get('outputs', []) for cell in nb['cells']]
# omit empty outputs
outputs = [o for o in outputs if len(o)]
# flatten
outputs = [o for lines in outputs for o in lines]
for output in outputs:
    data = output.get('data', {})
    if not data:
        continue
    keys = data.keys()
    for key in keys:
        if 'image' in key:
            string = ''.join(data[key])
```

On the last line, `data[key]` will be *bytes* or *str* -- failing or passing my test in tox. The time between passing/failing can be a couple of seconds, and I can not see any pattern. I should also add that [I copy notebooks to `tmpdir` with pytest](https://github.com/arve0/ipynbcompress/blob/master/test/test_compress.py#L15-16) before running any test, so notebooks should be the same (as also notebook file timestamp suggest).

Of course, I could just test if the data is list of bytes and convert it, but this seems like a bug somewhere. I have not looked into the code of `nbformat.read`, but guess it uses the `json` module, which states:

> The json module always produces str objects, not bytes objects.

So how is it even possible to get bytes objects when reading a json-file?

**Comment by arve0** [comment]
I should add:
- python 2.7 tests never fails
- my system is OS X 10.10.1

```
$ source .tox/py34/bin/activate
$ python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import IPython
>>> IPython.__version__
'3.1.0'
```

**Comment by arve0** [comment]
Linux is also affected:
- Failing: https://travis-ci.org/arve0/ipynbcompress/jobs/59704009
- Working: https://travis-ci.org/arve0/ipynbcompress/builds/59702747
- No diff in code between builds: https://github.com/arve0/ipynbcompress/commit/5995b57d0a2ac25b08403b8c3d787b6b60e66087

**Comment by arve0** [comment]
I've looked into [/jupyter/jupyter_nbformat](/jupyter/jupyter_nbformat), and it seems like the bug remains in `json.reads`: https://github.com/jupyter/jupyter_nbformat/blob/master/jupyter_nbformat/reader.py#L14

**Comment by arve0** [comment]
I got ahead of myself, more likely that the error resides in [v3.convert.upgrade_output](https://github.com/jupyter/jupyter_nbformat/blob/master/jupyter_nbformat/v4/convert.py#L156). Strange enough, there is [already a test for type bytes there](https://github.com/jupyter/jupyter_nbformat/blob/master/jupyter_nbformat/v4/convert.py#L183-185).

**Comment by arve0** [comment]
Iiik! The err was mine, [not decoding my encoded byte64 var](https://github.com/arve0/ipynbcompress/blob/5995b57d0a2ac25b08403b8c3d787b6b60e66087/ipynbcompress/ipynbcompress.py#L58).

Strange though, this should fail every time.

**Comment by arve0** [comment]
Ah! Pytest does not refresh the tmpdir between environments!

**Comment by Carreau** [comment]
Happy you solved it while we were sleeping!
