### ISSUE TITLE
Markdown rendering-no paragraphs

### ISSUE THREAD

**Issue by dartdog** [ipython/ipython#8370]
Markdown not rendering correctly (seems to me has been an issue for a while) Also does not render with Paragraphs in NB convert. 1st one is as entered
![rawmdinstall_extensions](https://cloud.githubusercontent.com/assets/87834/7305980/bf3dc85c-e9c7-11e4-98b7-3407a5f6a403.png)

This is as rendered:
![install_extensions](https://cloud.githubusercontent.com/assets/87834/7306017/ed93fc6c-e9c7-11e4-9bff-56b8b87338bb.png)

**Comment by minrk** [comment]
It is rendering it as a paragraph, otherwise the 'In short' would be on the same line as 'accuracy.' I guess you mean that we should have different styling for paragraph breaks?

**Comment by takluyver** [comment]
In the unrendered view, it looks like you're leaving a blank line between each line of the markdown? Is that the case? If so, it will be rendering each line as a new paragraph, which is probably not what you want.

**Comment by dartdog** [comment]
Doh!! removed the excess blank lines now I get the blank lines between Paragraphs as desired...

**Comment by dartdog** [comment]
However when rendered to Latex I get indented paragraphs with no blank line and there does not seem to be a way to get a blank line even with a manual <br>
