### ISSUE TITLE
IPython notebook and firefox interaction issue

### ISSUE THREAD

**Issue by MichaelWS** [ipython/ipython#8373]
I posted this on stackoverflow, but people do not seem able to help.

I have a pandas DataFrame with greater than 70 columns.
When I produce a calculation on it, firefox (on windows) has the the DataFrame printed in a greater space than the window is allotted for it and makes the scrollbar act in unexpected ways.   I would like the scrollbar to fit inside the ipython window allotted for it. Is there any clean way to handle this?  

It can be recreated in firefox using this code in an ipython notebook window.

```
df = pd.DataFrame(np.random.randn(100, 20))
df.tail()
```

**Comment by takluyver** [comment]
What version of IPython are you using? I think we changed how this behaves in IPython 3.

**Comment by MichaelWS** [comment]
ipython 3.0.0

**Comment by takluyver** [comment]
OK, so it's the new behaviour you're having a problem with. Can you post a screenshot of what you see, and describe what's wrong with it? I've just tried that code snippet in master (I don't think that code has changed much since 3.0) and it works roughly as I expect.

**Comment by MichaelWS** [comment]
Yes, I am having issues replicating my work environment. I will try to set up some vm's soon.

**Comment by tqa236** [comment]
Can we close this issue now?
