### ISSUE TITLE
Python conflict with Sublime Text - Trouble running IPython 3.0.0

### ISSUE THREAD

**Issue by duytrung** [ipython/ipython#8381]
I used Python 3 in Anaconda distribution. I tried running IPython from Sublime Text but it failed. Here is the message from the text editor:
```
"C:\Anaconda3\python.EXE: Module use of python33.dll conflicts with this version of Python.
IPython Console 3.0.0
ERROR: Kernel did not respond
```

Kind regards

Steve

**Comment by koenvb** [comment]
As your problems are mostly related to Sublime and SublREPL I would advise to get help in the https://github.com/wuub/SublimeREPL project. I assume they are in a better place to help you out with the link between Sublime and python/ipython

**Comment by takluyver** [comment]
Closing as it seems unlikely to be an IPython bug. Feel free to use the comments for troubleshooting.
