### ISSUE TITLE
nbconvert timeout on long computations

### ISSUE THREAD

**Issue by cstjean** [ipython/ipython#8382]
When running a long computation through `ipython nbconvert`, I will get a timeout ERROR. For instance, with the notebook containing just one cell:

`from time import sleep`
`sleep(120)`

Running it with 

`ipython nbconvert Testing_IPython.ipynb --ExecutePreprocessor.enabled=True --to html --output Executed --output Testing_IPython.html`

Yields:

`[NbConvertApp] ERROR | Timeout waiting for execute reply`
`[NbConvertApp] ERROR | failed to run cell: Empty()`
`[NbConvertApp] ERROR | from time import sleep`

It seems that the exception comes from [this line](https://gist.github.com/tritemio/58f327bc1f02af3fc464#file-ipython-executepreprocessor-mokey-patch-L34), @tritemio. Is there any way to manually set the timeout? The [documentation](http://ipython.org/ipython-doc/1/interactive/nbconvert.html) for nbconvert is out-of-date.

**Comment by takluyver** [comment]
The timeout is configurable. Set `c.ExecutePreprocessor.timeout` in the config file, or pass `--ExecutePreprocessor.timeout=180` at the command line.
