### ISSUE TITLE
notebook server - access to files on notebook side, upload menu in dashboard

### ISSUE THREAD

**Issue by denfromufa** [ipython/ipython#8383]
How can I access the files on notebook client side for use as data in the notebook computations, if the notebook server is located on remote machine? 

Right now I can only access the files on the notebook server side.

Is the only option to copy the files to remote server?

**Comment by denfromufa** [comment]
client and server side do not have common storage location

**Comment by takluyver** [comment]
Yes, all your code is running on the machine where the notebook server is. If they don't share a filesystem, then you will need to either copy the files to where the code runs, or run the server where the files are (technically you need to run the kernels there, but the easiest way to do that is to run the server there).

**Comment by denfromufa** [comment]
But it is possible to send files over sockets for built-in support in ipynb

**Comment by takluyver** [comment]
If you're running the notebook server on the remote machine, then the only communication with your local machine is the websockets your browser opens. And the browser doesn't have filesystem access.

**Comment by denfromufa** [comment]
Looks like this maybe the solution:

http://nbviewer.ipython.org/github/esss/ipython/blob/master/examples/Interactive%20Widgets/File%20Upload%20Widget.ipynb

**Comment by denfromufa** [comment]
https://github.com/ipython/traitlets/issues/12

**Comment by denfromufa** [comment]
How can I modify that widget example not to display the file in notebook but to save it on remote ipython server?

**Comment by takluyver** [comment]
It is transferring it to the kernel. Check `file_widget.value` after you've selected a file.

**Comment by denfromufa** [comment]
I was able to transfer text files, but binary did not go through correctly. Is there any way to transfer "raw" binary data using that widget?

**Comment by denfromufa** [comment]
Now I think it is better to include the file upload option right in the *dashboard*

**Comment by denfromufa** [comment]
I found that button! Closed!

**Comment by minrk** [comment]
The upload button should be the same on local IPython as on try.jupyter. What version of IPython are you using?

**Comment by denfromufa** [comment]
'3.0.0'

**Comment by denfromufa** [comment]
Ok, I got the upload button on latest version.
