### ISSUE TITLE
Reading docstring causes keyboard unresponsiveness

### ISSUE THREAD

**Issue by ozak** [ipython/ipython#8386]
Hi, 

since upgrading to IPython 3.1.0 I have noticed that getting help, i.e. reading the docstring for a method sometimes causes the keyboard to not work after exiting...at least for a while or until certain number of characters have been included (happened both using the qtconsole and notebook). E.g.

    import skimage.graph as graph
    graph.MCP?

Generated the issue at least twice...although not always. Any one else having the same issue?

**Comment by Carreau** [comment]
Haven't seen that... do you get any error message in the terminal, or in
the Notebook JS console ?

**Comment by ozak** [comment]
No errors. Even stranger is the fact that it is mostly the ``enter`` and ``delete`` keys. other keys seems to function. But it is only (I)Python related, since at the same time other apps have no issue. I am on a Mac OSX 10.9.5

**Comment by takluyver** [comment]
Can you still reproduce this? It's especially bizarre that you say you've seen it with both the notebook and the qtconsole - those have completely separate code for keyboard handling.

**Comment by ozak** [comment]
I think it still happens on the qtconsole...although it I am not 100% sure. Can't remember the last time it happened. What does happen a lot is that after output is displayed (say a large ``Pandas dataframe``, unless you push ``enter`` to jump to a new input cell, the first X number of characters do not get read and thus do not get executed or produces an error...even more, unless you input enough characters to produce an error and jump to a new input cell, ``enter`` does not work if you have started typing anything and ``delete`` does not delete.

Haven't noticed it in the notebook and can't remember having the latter problem there.

**Comment by takluyver** [comment]
OK. There are some odd bugs in the Qt console keyboard handling. I think some of them have been cleaned up, but I wouldn't be surprised if there are more. If there's a simple way to reproduce it, please file a bug on the jupyter/qtconsole repo.

**Comment by ozak** [comment]
Ok I can confirm this still happens on qtconsole. I was using Anconda's distribution 

            platform : linux-64
        conda version : 3.19.0
  conda-build version : 1.11.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /grid/software/anaconda/2.2.0  (read only)

I can provide the .condarc file if needed to create the same installation. I was working with ``IPython v3.0.0`` on ``Python 2.7.11``. The issue happened after requesting info about ``griddata``

    from scipy.interpolate import griddata
    griddata?

after pressing ``q`` to return to the cell I had the problem that neither ``del`` nor ``return`` worked. I had to write a lot of letters until it accepted the ``return`` obviously causing an error.  I tried to replicate by just importing and executing on my other computer, but it didn't reproduce the error there. It seems it is something random. I will keep you posted if I am able to find a replicable example.

**Comment by takluyver** [comment]
> I was working with IPython v3.0.0 on Python 2.7.11.

Make sure you've got the latest version of the qtconsole package (currently 4.1.1).

**Comment by ozak** [comment]
According to conda it has version `` QT 4.8.6-0`` and ``pyqt 4.11.3`` on the server. And I am sure the version on my laptop is even newer, since I usually  keep that one up to date.

**Comment by takluyver** [comment]
Not Qt, the qtconsole package that contains our code. `conda install qtconsole`.

**Comment by ozak** [comment]
That one seems to be dated...It seems it is not even installed (conda shows it as a new package to be installed? Is this new to IPython 4?). I will upgrade and let you know if I encounter this again.

**Comment by takluyver** [comment]
Yep, IPython 4 split up what used to be one big package into a lot of smaller ones. The parts that aren't specific to Python (including the Qt console) got renamed to *Jupyter*.

I'm going to close the issue here; if you still have problems with the new version of the Qt console, please file a new issue in the [jupyter/qtconsole repo](https://github.com/jupyter/qtconsole).
