### ISSUE TITLE
display files info in ipynb navigation panel

### ISSUE THREAD

**Issue by den-run-ai** [ipython/ipython#8391]
See description below

**Comment by minrk** [comment]
Vague titles with no description aren't the most helpful issues. Can you perhaps describe what you are asking for?

**Comment by denfromufa** [comment]
The notebook dashboard just displays the file names. But date modified,
size, and access status are very important like in Explorer.

**Comment by takluyver** [comment]
There's already issue #1547 for modified date. I'm sure we've talked before about adding size as well, though I can't find an issue specifically about that.

**Comment by denfromufa** [comment]
By access status I mean the file attributes such as read-only

**Comment by FluxIX** [comment]
I would like to see size and attributes/permissions (platform-dependent) assigned to the Notebook file.
