### ISSUE TITLE
requirements files for notebook

### ISSUE THREAD

**Issue by denfromufa** [ipython/ipython#8393]
Is there any way to generate requirements files for notebook based on imported/used modules and packages?

**Comment by takluyver** [comment]
We don't provide anything like that, but you could write a tool to do it if you want. The fiddly bit would be matching up import names to PyPI names (which are often the same, but they don't have to be).

**Comment by denfromufa** [comment]
Here are 2 packages that can do this for Python code:

https://github.com/bndr/pipreqs
https://github.com/alecthomas/importmagic

**Comment by jamesfe** [comment]
I was setting up my dev environment and there are a number of packages not listed in the requirements file, but necessary to develop ipython.  This includes requests and nose - should we add a requirements-tests.txt file?

**Comment by minrk** [comment]
@jamesfe we only used requirements.txt for *unreleased* dependencies. To install IPython and its testing dependencies use `pip install "ipython[test]"`

**Comment by takluyver** [comment]
@minrk can we now remove requirements.txt again? The only thing left in it is traitlets, and I don't think IPython requires an unreleased version of traitlets.

**Comment by minrk** [comment]
@takluyver yup, #9132.

Also closing here, as we have no plans to implement requirements inside the notebook, and even if we did this is no longer the repo for it.

**Comment by jamesfe** [comment]
Thanks!
