### ISSUE TITLE
e-mail after the cell finishes the code.

### ISSUE THREAD

**Issue by erogol** [ipython/ipython#8394]
I think this is very useful feature to consider. If you are doing large scale data processing or machine learning, many codes take very long times on your remote machine. Therefore, having such functionality is very useful from my view.

**Comment by takluyver** [comment]
I don't think it's something we'd consider in IPython itself, but you could write an extension to do it. Relevant bits of the docs:

http://ipython.org/ipython-doc/stable/config/extensions/index.html#writing-extensions
http://ipython.org/ipython-doc/stable/config/callbacks.html

The event you'd want is called 'post_run_cell'. And I guess you may also want to use 'pre_run_cell' to time how long it took.
