### ISSUE TITLE
nbconvert --to=script or python converts raw cells to python code (ie: are not commented)

### ISSUE THREAD

**Issue by drevicko** [ipython/ipython#8395]
Markup cells have "# " prepended to each line when converting to python code, but raw cells are added to the python file as is.

I believe the purpose of raw cells is to show raw text data, perhaps output from a bash command or something like that. The point is, nobody would put code into one unless they wanted the code to not execute, so raw cells need to be commented out or left out when converted to python code.

**Comment by Carreau** [comment]
As the [docs says](http://ipython.org/ipython-doc/1/interactive/notebook.html#raw-cells):

> When passed through nbconvert, raw cells arrive in the destination format unmodified. For example, this allows you to type full LaTeX into a raw cell, which will only be rendered by LaTeX after conversion by nbconvert.

If you want somethings special, use celltoolbar, and tag the cells, but the behavior is correct. 

Output from bash command or anything else is probably better:
 1) as a `1bash-command` in a code cell, 
 2) in trible backtick code block in markdown. 

But thanks for asking the question.

**Comment by takluyver** [comment]
To expand a bit on what Matthias said, you can indicate what mimetype a raw cell represents by selecting 'Raw cell format' from the cell toolbar dropdown. Then each raw cell will get a toolbar with a dropdown for the format. If you tag the cell as another format, it won't get included when you nbconvert to Python.

**Comment by drevicko** [comment]
Fair enough. Though it is a bit counter intuitive - when converting to python, you'd naively expect the running code to match the code that gets run in the notebook. 

Thanks for the quick feedback (:
And thanks for the tips on how one might hide them from the export :)
