### ISSUE TITLE
pandasql queries return None in IPython notebook

### ISSUE THREAD

**Issue by szeitlin** [ipython/ipython#8396]
![screen shot 2015-05-01 at 10 07 34 am](https://cloud.githubusercontent.com/assets/5185401/7433808/f39402e2-efe9-11e4-9220-4bed6ec93d6a.png)

python 2.7.9
ipython 3.1.0
pandas 0.16.0
pandasql 0.6.2
mac os 10.9.5
safari 7.1.5

Same data, same conda env, just python:

```
>>> df = pandas.read_csv("2014_ts_sorted_zoned.csv", index_col=0)

>>> small_df = df[['Lat', 'Long', 'DistanceMeters', 'zoned']]

>>> print small_df.shape
(12287, 4)

>>> small_df.head()
   Lat      Long  DistanceMeters                      zoned
0  37.7643 -122.4334          0.0000  2014-06-18 06:38:14-07:00
1  37.7643 -122.4334          0.0000  2014-06-18 06:38:14-07:00
2  37.7643 -122.4334          0.0000  2014-06-18 06:38:15-07:00
3  37.7643 -122.4334          0.0000  2014-06-18 06:38:15-07:00
4  37.3943 -122.0771       4744.3589  2014-06-18 07:46:29-07:00

>>> from pandasql import sqldf

>>> q = "SELECT * FROM small_df ORDER BY RANDOM() LIMIT 10;"

>>> print sqldf(q, locals())
   Lat      Long  DistanceMeters                      zoned
0  37.3775 -121.9688      15784.8389  2014-07-24 08:07:16-07:00
1  37.3894 -121.9687       2203.3044  2014-10-08 16:26:22-07:00
2  37.3859 -121.9690       2591.2532  2014-06-30 16:27:51-07:00
3  37.3776 -121.9858      13573.8545  2014-10-24 08:03:36-07:00
4  37.3774 -122.0021      12191.9785  2014-10-16 08:00:48-07:00
5  37.3857 -122.0386       8670.1475  2014-10-17 07:55:55-07:00
6  37.3901 -122.0639      12729.8311  2014-06-30 16:47:04-07:00
7  37.3860 -122.0480       7797.0029  2014-06-23 07:52:04-07:00
8  37.3741 -121.9716      15059.0332  2014-06-20 08:09:00-07:00
9  37.3747 -121.9690       3849.6147  2014-10-07 16:32:48-07:00
```

**Comment by Carreau** [comment]
That seem to work for me with same versions. Can you be sure to restart the kernel ? And provide a self contain from start to interpreter to bug version, there might be some other import that mess things up. 

Do you have any custom setup ? does it work if you start from a new profile ?

**Comment by szeitlin** [comment]
This was reproduced two days in a row. Second day was with a fresh kernel.

Don't understand your next request. What do you mean by "a self contain 
from start to interpreter to bug version" ?

Yes, it could be an incompatibility with some other package I was using, 
but I wasn't using anything strange. matplotlib, seaborn, pytz. 
Regardless, I need these things to play nicely together.

What would you consider a "custom setup"?

Why would I need a new profile? Do you mean, if I had a custom profile?



Matthias Bussonnier wrote:

**Comment by Carreau** [comment]
I dont get all the first statements you use, like I did not import pytz or seaborn, and could be affecting the display. By custom profile I ment some configuration of IPython, like startup script, or enabling greedy completer, that could make some bugs like that if ever you complete on interables.

**Comment by takluyver** [comment]
Is this still reproducible?

**Comment by Carreau** [comment]
Closing as this has been inactive for about a year. Feel free to reopen.
