### ISSUE TITLE
IPython do not produce output after a while when using SSH tunneling

### ISSUE THREAD

**Issue by hnykda** [ipython/ipython#8401]
Hello,

I am using IPython on my server on localhost. Then I use `ssh -N -f -L localhost:sourcePort:localhost:TargetPort username@serverdomain` to tunnel it on my client.

Code is running well and when I left notebook open on my client after running the code, it works. But when I run the code and then close the notebook on client (not halt or shutdown, just don't display it) and then reconnects after e.g. turning client PC down, output of notebook is still same as I left it, even though there should be some more produced by the code. I can see that the code is running, since it is e.g. writing to the output files and is eating CPU. And after it ends (which I can find out by the fact that it is not writing into output files), variables are OK and it is clear that code ran correctly. But output of that current part of code (which is in just one cell) is not shown. 

It is annoying when I e.g. need to create a lot of graphs and it take long time. I have to leave my client PC turn on just for displaying the notebook. Specially when I close my browser window by an accident. 

Here is a picture how it looks like when I close and open the window. The kernel is busy and code is running, but I don't see any output from the last cell and it had changed sign from running "[ \* ]" to empty "[ ]". You can see there is "(Starting)" in the page title. 

![2015-05-03-162141_1366x768_scrot](https://cloud.githubusercontent.com/assets/2741256/7445385/97547714-f1b0-11e4-9a8c-d6b7c093f07e.png)

I suspect that it somehow write changes in notebook just to memory connected to current window and when you close it, you lost everything since your last save. Is this correct? It would be better if the output would be somehow saved in connection to kernel.

I'm of course able to provide you with my configuration, but there is nothing uncommented in my config file except matplotlib backend, port and ip.

`Ipython 3.1.0`, `Python 3.4.3`. 

Thank you

**Comment by takluyver** [comment]
Yep, as you guessed, the output is currently only stored in the frontend, so if you close the notebook, there's nothing to store that output. We're planning to refactor that so that the server stores the notebook model, which will fix this, but it will take some time.

**Comment by kotrfa** [comment]
Thank you for an answer. Is this somewhere documented? I had to miss it. 

And thank you for your work also!

**Comment by takluyver** [comment]
In fact it is, though I confess I'm mildly surprised at that:

http://ipython.org/ipython-doc/3/interactive/reference.html#customizing-readline-behavior

**Comment by takluyver** [comment]
Sorry, got confused about which issue I was responding to. I don't know if we have explicitly documented this anywhere.

**Comment by kotrfa** [comment]
I would suggest to at least mention it somewhere. It was kind of hard to figure the problem myself.
