### ISSUE TITLE
long output is not tracked, need to scroll by hand

### ISSUE THREAD

**Issue by birnstiel** [ipython/ipython#8407]
More of a feature request: if I run a cell that produces lots and lots of output, ipython automatically toggles output scrolling (which is good), but to follow the progress, I constantly have to scroll down. I think it would be more natural if the focus would follow the last line of the long output, like a terminal window.

Here is an example:

```
print('Starting ...')
for i in range(1000): print(i)
print('... Done!')
```

**Comment by Carreau** [comment]
The scrolling is most likely a browser feature, and will be really hard to change.

**Comment by birnstiel** [comment]
well I don't know the internals, but whatever updates the `div` containing the output, could just call javascript:

    mydiv.scrollTop=mydiv.scrollHeight

[Here](https://jsfiddle.net/birnstiel/7mvh2tuc/3/embedded/result/) is an example: the button changes the content of the scrollable div, and then scrolls to the bottom of it.

**Comment by scruel** [comment]
the following code will do the trick as you described.

```
%%javascript

var div = $(".output_scroll").get(0)

function callJump() {
    setTimeout(jumpToBottom, 2000);
}

function jumpToBottom() {
    if(div.scrollTop != div.scrollHeight){
        div.scrollTop = div.scrollHeight;
        callJump();
    }
}
jumpToBottom();
```

**Comment by scruel** [comment]
Hi, the following code will do the trick as you described.
run it in any cell, and will apply to all output blocks.

```
%%javascript

window.scroll_flag = true
window.scroll_delay = 2000

function callScrollToBottom() {
    setTimeout(scrollToBottom, window.scroll_delay);
}

function scrollToBottom() {
    if (!window.scroll_flag) {
        callScrollToBottom();
        return;
    };
    $(".output_scroll").each(function() {
        $(this)[0].scrollTop = $(this)[0].scrollHeight;
    });
    callScrollToBottom();
}
scrollToBottom();

```

Moreover, prevent you want to disable it,
you can just execute the code `window.scroll_flag = flase` in browser console(F12).
or you can modify the delay of the operation to 3s by type code `window.scroll_dalay = 3000`.
