### ISSUE TITLE
Trying to execute "%matplotlib inline" as part of exec_lines is not working

### ISSUE THREAD

**Issue by ccordoba12** [ipython/ipython#8410]
For Spyder we're using

```python
c.InteractiveShellApp.exec_lines = ["%matplotlib inline"]
```

to start our kernels with the inline backend, but I just noticed that that's not working. However, it works for other backends (like qt or tk).

I also noticed that starting qtconsole like this

    ipython qtconsole --matplotlib inline

doesn't have any effect either.

It seems this problem has been present for a long time because I tried it in IPython 1.0 to no effect :-)

**Comment by takluyver** [comment]
I think this is because the frontend config is no longer passed through to the kernel. Probably the easiest solution is to add a kernelspec that will start the kernel with the config you want.

I also think we should make 'inline' the default backend when matplotlib is used in the kernel, but that effort has stalled a bit.

**Comment by damianavila** [comment]
But this should still work, in the `ipython_kernel_config.py`

```
c = get_config()
c.IPKernelApp.matplotlib = 'inline'
```

**Comment by takluyver** [comment]
I just saw that @ccordoba12 mentioned that it works with qt or tk, so it can't be that it's not getting the config at all. I'm not sure what could be going on there.

**Comment by ccordoba12** [comment]
@takluyver, yes, the problem is only with `inline`. The other backends work correctly.

I saw the issue about setting `inline` as the default but since it was moved to 4.0, I decided to open this one to see if you can fix it for 3.2 :-)

**Comment by takluyver** [comment]
Does `%matplotlib inline` work in the Spyder console after it has started?

**Comment by ccordoba12** [comment]
Yep

**Comment by takluyver** [comment]
Adding `c.InteractiveShellApp.exec_lines = ["%matplotlib inline"]` to my `ipython_kernel_config.py` works for me running `ipython qtconsole` on master, so I suspect it's to do with the way Spyder launches things. Double check that it's really taking effect with other backends, not just using mpl's default backend.

**Comment by ccordoba12** [comment]
Thanks Thomas, I'll check it out.

But what about

    ipython qtconsole --matplotlib inline

is it working for you too?

**Comment by takluyver** [comment]
It now needs to be written as `ipython qtconsole -- --matplotlib inline`, but if I do that, it works. If I try it without the extra `--`, it gives a big error message.

**Comment by ccordoba12** [comment]
Ok, I'll test things tomorrow and report back. Thanks a lot for the quick response :-)

**Comment by ccordoba12** [comment]
Ok, I tested things and now I understand what's happening:

1. After an IPython qtconsole started, I was running `%matplotlib` to verify the current mpl backend.
2. The result was always `agg` instead of `inline`, which made me think that `inline` was not set.
3. However, I see now that if I don't run `%matplotlib` I can generate inline plots without problems, which means there's no problem with `exec_lines` and `inline` :-)

This is a bit confusing because if I run `%matplotlib qt` and then `%matplotlib`, the result I get is `Qt4Agg`, not `agg`. And this is what I was expecting with `inline`!

So the problem (I think) is just a bit of an asymmetry in treating `inline` when running `%matplotlib` :-) Maybe this will be solved once (and if) you set `inline` as the default backend.

@takluyver, feel free to close this one if you think it's the right thing to do.

**Comment by takluyver** [comment]
Possibly from mpl's point of view, 'agg' is the actual backend - the thing that draws the plots. I'm not sure. But if the plots are actually appearing inline, I think this is OK.
