### ISSUE TITLE
IPython sends JSON HTTP POST with non-conforming content type application/x-www-form-urlencoded breaking WebOb HTTP proxying

### ISSUE THREAD

**Issue by miohtama** [ipython/ipython#8416]
The environment:

IPython 3.1.0
Chrome 43
Python 3.4
OS X

When IPython starts the session, it makes HTTP POST to the server with JSON payload as shown below using *application/x-www-form-urlencoded* content type.

![screen shot 2015-05-08 at 13 31 08](https://cloud.githubusercontent.com/assets/49922/7534925/3dea0bfe-f588-11e4-8f00-9be57c0d6f09.png)

Because *application/x-www-form-urlencoded* encoding separates fields with =-character a middle man proxy, WebOb based Python app in this case, may insert = character at the end of the payload, resulting to the invalid JSON. I am not sure if inserting = at the end is legit behavior or not, but I suspect it is done because it seems that Content-Length header is missing from this request as well (at least when the XmlHttpRequest request was initiated by Chrome). Maybe inserting = is a workaround for some other bug in some other software.

The following happens:

    [D 13:23:42.567 NotebookApp] Bad JSON: '{"notebook":{"path":"default.ipynb"},"kernel":{"id":null}}='
    [E 13:23:42.567 NotebookApp] Couldn't parse JSON
        Traceback (most recent call last):
          File "/Users/mikko/code/trees/venv/lib/python3.4/site-packages/IPython/html/base/handlers.py", line 263, in get_json_body
            model = json.loads(body)
          File "/opt/local/Library/Frameworks/Python.framework

Suggestion: If any HTTP POST's with JSON payload are made from IPython, they should use *application/json* content type instead of *application/x-www-form-urlencoded*. 

If somebody can point me to right direction I can make a patch for this.

Similar issue in another software has been reported here:

http://stackoverflow.com/a/10393222/315168

**Comment by takluyver** [comment]
jupyter/jupyter_notebook#72 should fix this
