### ISSUE TITLE
Jupyter (Unsaved Changes) -won't save

### ISSUE THREAD

**Issue by moritzmcgarrie** [ipython/ipython#8424]
Hi, install python 2.7 through macports and ipython notebook etc. save and checkpoint does not save, and "(unsaved changes)" always displayed.  I can't Rename a notebook either.  Any solution?

**Comment by koenvb** [comment]
Could it be your notebook is not writable? What are the file permissions?
(On mac check CMD + I for file permissions)

**Comment by moritzmcgarrie** [comment]
ls -l says "  drwx------+ 14  myname  staff      476 May 11 07:53 Desktop  "  etc
"Download as..." works okay and puts a file in my Downloads.
when I click the floppy disk symbol nothing happens and there are no messages in Terminal

**Comment by koenvb** [comment]
How do you start ipython? Does it provide you any error message in the
console you start ipython from?

On Mon, May 11, 2015 at 4:50 PM, moritzmcgarrie <notifications@github.com>
wrote:

> ls -l says " drwx------+ 14 myname staff 476 May 11 07:53 Desktop " etc
> "Download as..." works okay and puts a file in my Downloads.
> when I click the floppy disk symbol nothing happens and there are no
> messages in Terminal
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/8424#issuecomment-100788944>.
>



-- 
Koen van Besien

BE: +32 485 68 29 28
AU: +61 435613099

**Comment by moritzmcgarrie** [comment]
iMoritzs-MacBook-Pro:~ Moritz$ ipython notebook
[I 08:52:34.278 NotebookApp] Serving local MathJax from /Users/Moritz/.ipython/nbextensions/mathjax/MathJax.js at /nbextensions/mathjax/MathJax.js
[I 08:52:34.440 NotebookApp] Serving notebooks from local directory: /Users/Moritz
[I 08:52:34.440 NotebookApp] 0 active kernels 
[I 08:52:34.440 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 08:52:34.440 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation)

Then the latest version of firefox pops up with a window with http://localhost:8888/tree
and displays Jupyter.

I then select a .ipynb file and  terminal displays 
[W 08:54:11.523 NotebookApp] 404 GET /favicon.ico (192.168.1.6) 91.39ms referer=None
[W 08:54:11.524 NotebookApp] 404 GET /favicon.ico (192.168.1.6) 0.51ms referer=None
[I 08:54:20.489 NotebookApp] Kernel started: 188b30ad-24da-48d5-9591-a010a43d2b03

I type 2+2 and out[1]: is 4 and then I click the floppy disk symbol and nothing happens.

**Comment by moritzmcgarrie** [comment]
Temp solution.  Even with wifi off when hotspot shield is on http://www.hsselite.com/ , jupyter doesn't save. Temp solution is to switch off hotspot shield and all is fine.

**Comment by koenvb** [comment]
Can you just create a new notebook and see if that works?
Where is your notebook file residing? On your local desktop?

On Mon, May 11, 2015 at 4:56 PM, moritzmcgarrie <notifications@github.com>
wrote:

> iMoritzs-MacBook-Pro:~ Moritz$ ipython notebook
> [I 08:52:34.278 NotebookApp] Serving local MathJax from
> /Users/Moritz/.ipython/nbextensions/mathjax/MathJax.js at
> /nbextensions/mathjax/MathJax.js
> [I 08:52:34.440 NotebookApp] Serving notebooks from local directory:
> /Users/Moritz
> [I 08:52:34.440 NotebookApp] 0 active kernels
> [I 08:52:34.440 NotebookApp] The IPython Notebook is running at:
> http://localhost:8888/
> [I 08:52:34.440 NotebookApp] Use Control-C to stop this server and shut
> down all kernels (twice to skip confirmation)
>
> Then the latest version of firefox pops up with a window with
> http://localhost:8888/tree
> and displays Jupyter.
>
> I then select a .ipynb file and terminal displays
> [W 08:54:11.523 NotebookApp] 404 GET /favicon.ico (192.168.1.6) 91.39ms
> referer=None
> [W 08:54:11.524 NotebookApp] 404 GET /favicon.ico (192.168.1.6) 0.51ms
> referer=None
> [I 08:54:20.489 NotebookApp] Kernel started:
> 188b30ad-24da-48d5-9591-a010a43d2b03
>
> I type 2+2 and out[1]: is 4 and then I click the floppy disk symbol and
> nothing happens.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/8424#issuecomment-100789542>.
>



-- 
Koen van Besien

BE: +32 485 68 29 28
AU: +61 435613099

**Comment by moritzmcgarrie** [comment]
Switched on hotspot shield (its free, if you need to reproduce this for debugging etc) and created a notebook on my desktop.  2+2 etc and then tried to save it. Autosave failed.  switched off hotspot shield and pressed save and it worked.

**Comment by Carreau** [comment]
can you open the Javascript console in your browser and see if there is any browser errors. I guess it is hotspot shield that prevent some requests to be made. I would see in HS docs if you can whitelist IPython.

**Comment by moritzmcgarrie** [comment]
Ctrl+shift+J I try and save and 
GET 
http://localhost:8888/api/contents/Documents/Learn_Python/Data_from_Google.ipynb [HTTP/1.1 200 OK 4ms]
PUT 
http://localhost:8888/api/contents/Documents/Learn_Python/Data_from_Google.ipynb
But otherwise nothing out of the ordinary

**Comment by takluyver** [comment]
If you're still having this problem, please open a new issue on the jupyter/notebook repo.
