### ISSUE TITLE
Load more history into readline buffer at startup

### ISSUE THREAD

**Issue by aerusso** [ipython/ipython#8426]
I'm curious why, at startup in core/interactiveshell.py, the readline history is populated with a hard coded value of only 1000 (instead of, say, the configuration parameter history_length) history entries.

I've personally wished I had more history.

**Comment by takluyver** [comment]
I don't see any problem with making this configurable if you would like to make a PR. I probably wouldn't make it fill the readline history (10k entries by default), because I doubt most users want to go that far back, and it presumably has some cost in startup time.

**Comment by aerusso** [comment]
This is my first pull request, so please let me know if I've done something wrong.
