### ISSUE TITLE
Incorrect documentation for introspection

### ISSUE THREAD

**Issue by gibiansky** [ipython/ipython#8432]
The [documentation for `inspect_reply`](http://ipython.org/ipython-doc/dev/development/messaging.html#introspection) is lacking.

It seems that to get a tooltip to show up you need `found = True` in your JSON, while the documentation only mentions status. See `tooltip.js` line 267 (roughly, may have changed since 3.0): 
```javascript
        this._reply = reply;
        var content = reply.content;
        if (!content.found) {
            // object not found, nothing to show
            return;
        }
        // If 'found' is true, then actually show the tooltip
```

Either the documentation should specify that `found` is necessary, or the implementation should check for `status` and not `found`.

**Comment by gibiansky** [comment]
Looks like this was fixed in [this PR](https://github.com/ipython/ipython/pull/8408/files), and it's just a website update that needs to be done.

**Comment by takluyver** [comment]
I think we're waiting on rebuilding the docs until we've decided where the docs for different pieces will go after the split.

**Comment by Carreau** [comment]
This is now fixed and live on http://jupyter-client.readthedocs.io/en/latest/messaging.html
