### ISSUE TITLE
Build error on 4.0.0.dev0 using pip

### ISSUE THREAD

**Issue by fonnesbeck** [ipython/ipython#8436]
I'm running into a setuptools problem when installing IPython from master. Running

    pip install -U --no-deps git+git://github.com/ipython/ipython.git 

Yields [the following error](http://d.pr/n/x4eg) on OS X 10.10, and Python 3.4 (Homebrew).

**Comment by takluyver** [comment]
We've temporarily disabled installing from master because we're in the middle of splitting things up. It should still work if you use `pip install -e`

**Comment by minrk** [comment]
Installation from master works now.
