### ISSUE TITLE
[security] login next url not validated

### ISSUE THREAD

**Issue by bluesmoon** [ipython/ipython#8438]
On IPython, it looks like you can pass any URL as the value of `next` to the `/login` page, and you get redirected there after login.  An attacker could use this to launch a phishing attack against IPython users.

Suggested fix is to validate the `next` url before redirecting.

**Comment by rgbkrk** [comment]
Thanks for reporting this. Fixed in 4370a155cce639753fc2e82426e36c841a97d2d5.
