### ISSUE TITLE
backgroundjobs related magic functions are all missing

### ISSUE THREAD

**Issue by digitalsatori** [ipython/ipython#844]
sorry for the dumb question, but where are those magics:
%jobs,  %bg etc.

ipython  prompted Magic function 'xxx' not found whenever I type these magic phrase in ipython, and it seems really missing in the "core/magic.py" . I also found that nowhere in ipython actually refer to the lib/backgroundjobs.py where background jobs handling process defined.

**Comment by ahmadia** [comment]
This has been resolved with the new `script` [magic](https://ipython.org/ipython-doc/dev/interactive/magics.html), that provides a `--bg` flag.

Example:

%%script bash --bg --out script_out

sleep 10
echo hi!

**Comment by Carreau** [comment]
Thanks ! Closing then !

**Comment by Tagar** [comment]
It would be still great to have %bg back.. not just external script background execution.
We use ipython for Spark and some commands (like stats collection), may have to run for an hour,
but most of following cells not necessarily depend on its result. So it would be good to run 
any cell in background, not just external scripts. Thank you.

**Comment by madanh** [comment]
I have Monte-Carlo simulations that run for  around two hours, but may converge earlier. Useful conclusions and earlier convergence detection can be be done when running them in background and dumping intermediate results in a file.  A perfect job for %bg, so please reopen

**Comment by Carreau** [comment]
> I have Monte-Carlo simulations that run for around two hours, but may converge earlier. Useful conclusions and earlier convergence detection can be be done when running them in background and dumping intermediate results in a file. A perfect job for %bg, so please reopen

Magics do not have to be part of IPython to be available, you are free to publish a package on PyPI that exposes a `%bg` magic. Though from your use case, it seem like [ipyparallel](IPython/core/magics/script.py) and using Python Futures might be more appropriate.
