### ISSUE TITLE
Vispy Webgl example doesn't work on windows because of "symbolic link" is not an end-user right

### ISSUE THREAD

**Issue by stonebig** [ipython/ipython#8440]
Hi,

I fall on this issue: https://github.com/vispy/vispy/issues/907

Which comes down to the fact that end-users on windows are not permitted to create symlinks.

Which project should take care of this possibility ?

Is there a possiblity, for that kind of situation, that IPython doesn't need to do a symlink or can do a copy instead (in the Windows case) ?

**Comment by takluyver** [comment]
The `install_nbextension()` function has an optional `symlink=` parameter, and the docstring says you can't rely on it on Windows (it says that now, at least - it might not always have done). It looks like vispy is passing `symlink=True`. Possibly we should redesign that API to fall back on copying if symlinks aren't supported, but I think it's behaving as (currently) designed.

**Comment by stonebig** [comment]
So on current Ipython API, the issue resolution seems for vispy people.
It's a duplicated effort if extension packages have all to manage that subtility with their inner `Windows` knowledge and willingness, so a more `Windows sin` forgiving API would be nice.

**Comment by takluyver** [comment]
Filed jupyter/notebook#100 to discuss the API
