### ISSUE TITLE
IPython and Cron

### ISSUE THREAD

**Issue by borisRa** [ipython/ipython#8441]
Hi, I have simple IPython script that checks if some process is ON or OFF. If I run the script through shell it works !  BUT the same command through CRON doesn't. It seems that IPython through cron doesn't see the same environment !

This does work:

    /anaconda/bin/ipython /home/boris/projects_boris/RTB/RTB/RTB_Code/cron_check.py 

And the same command through CRON doesn't :-1: 

    * * * * * /anaconda/bin/ipython /home/boris/projects_boris/RTB/RTB/RTB_Code/cron_check.py 

cron_check.py:

```python
import os

result = os.popen("ps -Af").read()
result = result.count("log_handler.py")
print (result)

if (result == 0) :
                print("the len is 0")
```

Any suggestion will be greatly appreciated,
Boris

**Comment by Carreau** [comment]
Cron, in general, does not run with the same env, so I would look for cron related question, not IPython.

http://stackoverflow.com/questions/2229825/where-can-i-set-environment-variables-that-crontab-will-use

Also in your example, why use IPython and not pure python?
-- 
M

**Comment by minrk** [comment]
Since it's a pure Python script, I don't think it makes sense to run it with IPython. Still, the reason it's likely failing is to run a script without an interpreter, you need two things:

1. It must be executable (`chmod +x cron_check.py`)/
2. The first line must be a [shebang](http://en.wikipedia.org/wiki/Shebang_(Unix)#Purpose), specifying the interpreter, e.g. `#!/anaconda/bin/python`.

**Comment by borisRa** [comment]
This script is only an example, I have the same piece of logic that is being run as a part of a IPython program. And the script is running fine just doesn't recognize the processes. Have tried the shebang and chmod without any success.

**Comment by borisRa** [comment]
By the way the same launch with python works :
/anaconda/bin/python /home/boris/projects_boris/RTB/RTB/RTB_Code/cron_check.py 

And again with IPython it doesn't: 
/anaconda/bin/ipython /home/boris/projects_boris/RTB/RTB/RTB_Code/cron_check.py

**Comment by takluyver** [comment]
We don't really recommend you use IPython for something like cron jobs - it's designed for interactive use, so it's probably not going to be the right tool for automatic system stuff.

The example script you gave is just printing, so how would you tell if it ran in cron? The output would just be discarded, as I understand it.

**Comment by rgbkrk** [comment]
@borisRa What do your cron logs say?

```
grep CRON /var/log/syslog
```

(depending on distro, may be a different path).

**Comment by borisRa** [comment]
Actually in CRON I store the logs :

* * * * * /anaconda/bin/ipython /home/boris/projects_boris/RTB/RTB/RTB_Code/cron_check.py > /var/log/my_cron_logs.log 2>&1

And there can see the output. About "grep CRON /var/log/syslog" can see all the "cron_check.py"  triggers :

 (boris) CMD (/anaconda/bin/ipython /home/boris/projects_boris/RTB/RTB/RTB_Code/cron_check.py > /var/log/my_cron_logs 2>&1)
 CRON[8117]: (boris) CMD (/anaconda/bin/ipython /home/boris/projects_boris/RTB/RTB/RTB_Code/cron_check.py > /var/log/my_cron_logs.log 2>&1)
CRON[8267]: (boris) CMD (/anaconda/bin/ipython /home/boris/projects_boris/RTB/RTB/RTB_Code/cron_check.py > /var/log/my_cron_logs.log 2>&1)

**Comment by borisRa** [comment]
@takluyver tried to launch my IPython script through python and got Errors about module names didn't find :

```javascript
from XXX_Code import YYY_Adjust as BA
ImportError: No module named XXX_Code
```

This one worked  ( IPython ):
```javascript
/anaconda/bin/ipython /home/boris/projects_boris/RTB/RTB/RTB_Code/my_IPython_code.py
```
And with Python it doesn't (throws the error above): 
```javascript
/anaconda/bin/python /home/boris/projects_boris/RTB/RTB/RTB_Code/my_IPython_code.py
```

**Comment by takluyver** [comment]
I don't know what we'd do that might affect imports like that.
