### ISSUE TITLE
Disable smooth scroll

### ISSUE THREAD

**Issue by joelmo** [ipython/ipython#8443]
Ipython 3 seem to have some smooth-scrolling script enabled.

I think the browser should decide if smooth scrolling should be enabled. In chromium it's disabled by default but can be set in about://flags. I think firefox have this enabled by default but can also be turned off. Maybe this can be turned off in a user profile, but it would be better to just use the browsers preference for this.

**Comment by Carreau** [comment]
We don't enable smooth scrolling anywhere as far as I am aware. Do you want to describe what you are doing and how it behaves ?

**Comment by joelmo** [comment]
The experience when scrolling is not as nice as it was in ipython2, I didn't have this problem there. If I'm in a long document and scroll fast, using space or pgup/down the view tends to hook. In the video here can you see some smooth-scrolling is enabled? I'm running without browser plugins and in ipython I use some small css changes, I have also tested without them but I get same problem.

I recorded my screen so you can see what happens when I scroll fast.
 https://mega.nz/#!KdZEBDjZ!HGSJzdjWrSA5Wgr9Qt_q4nonEWHLrtVhtnLvWCwZg9s

**Comment by Carreau** [comment]
Hum, there is indeed thing bound to Space and shift space, but I can't find anything related to PgUp and PgDown. 

@jdfreder some help please ....

**Comment by jdfreder** [comment]
Definitely looks like the scroll manager is being invoked, but like @Carreau says, it just listens to `space` and `shift-space`.  Could you have your machine mapping page up&down to those keys?

Anyways, does the following code cell fix the problem for you?

```js
%%javascript
require(['notebook/js/scrollmanager'], function(sm) {
    var NoScrollManager = function(notebook, options) {
        sm.ScrollManager.apply(this, [notebook, options]);
    };
    NoScrollManager.prototype = Object.create(sm.ScrollManager.prototype);
    
    NoScrollManager.prototype.scroll_some = function(pages) {
        this.element.scrollTop(this.element.scrollTop() + pages * this.element.height());
    };
    
    IPython.notebook.scroll_manager = new NoScrollManager(IPython.notebook);
});
```

**Comment by joelmo** [comment]
PgUp/Down does nothing in the notebook, they usually scroll the page, but I rarely use those keys for scrolling.

Thanks, the above script works. I also tried `IPython.notebook.scroll_manager.animation_speed=0;` this also fixes the issue.

**Comment by jdfreder** [comment]
@joelmo ah yes, that would probably do it too.  I wasn't sure, so I wrote the above script which avoids jquery's animate altogether.
