### ISSUE TITLE
ipython notebook issue

### ISSUE THREAD

**Issue by 1520588207** [ipython/ipython#8445]
there is some problem with my ipython notebook:
The kernel has died, would you like to restart it? If you do not restart the kernel, you will be able to save the notebook, but running code will not work until the notebook is reopened.
and the terminal said ,there is no module named zmq.ipkernal.

**Comment by Carreau** [comment]
How did you install ? Can you copy-past the message exactly ? If you are not familiar with Python/IPython I would suggest **not** installing from github/master which is a bit complex right now.

**Comment by 1520588207** [comment]
![Uploading 捕获.PNG…]()
![Uploading 捕获2.PNG…]()

**Comment by 1520588207** [comment]
![default](https://cloud.githubusercontent.com/assets/11959482/7682565/81d8b6d2-fdab-11e4-9b21-5cd9e9af42bc.PNG)

![2](https://cloud.githubusercontent.com/assets/11959482/7682609/caa5dcd2-fdab-11e4-8a41-1f0486a28eb1.jpg)

**Comment by Carreau** [comment]
Woooow... what version of IPython is that ? it seem like a 2+ years old version. I would suggest to upgrade you are probably really out of date and hence why it does not work.

How did you install ?

**Comment by 1520588207** [comment]
thank you,i have install the latest version.it works.but there is another error,and why?
![default](https://cloud.githubusercontent.com/assets/11959482/7693975/7ab1ae0c-fe0c-11e4-84df-663915369edf.PNG)

**Comment by Carreau** [comment]
You are missing a space between `notebook` and `--pylab` and anyway pylab
is deprecated. don't use it.
