### ISSUE TITLE
Incorrect number of engines in Clusters-tab

### ISSUE THREAD

**Issue by hannorein** [ipython/ipython#8448]
The Clusters-tab in the IPython tree shows an incorrect number of engines for parallel computing clusters if the cluster is started using the `SSHEngineSetLauncher` launcher with multiples engines. For example, this cluster with 44 (running) engines:

```
c.SSHEngineSetLauncher.engines = {                                                                                                 
    'node1.utoronto.ca': 20,                                                                                            
    'node2.utoronto.ca': 24,                                                                                            
}
```

shows up on the Clusters-tab as only having 24 engines. I'm running version 3.1.0.

**Comment by minrk** [comment]
The SSHEngineSetLauncher you are using ignores the `n` argument that the clusters tab represents. I'll see if I can rearrange things in the launchers to make this easier. It probably won't be a 3.x thing, though.

**Comment by Carreau** [comment]
Has this been addressed  by ipp/9 ?

**Comment by minrk** [comment]
Not yet, no.
