### ISSUE TITLE
Issue with two versions of minus sign character

### ISSUE THREAD

**Issue by jkbrooks** [ipython/ipython#8455]
In ipython 3.1.0, I cannot use one minus sign character to make a subtraction.  See below:

```
In [212]: 4 – 5
  File "<ipython-input-212-memory-slot>", line 1
    4 – 5
      ^
SyntaxError: invalid syntax


In [213]: 4 - 5
Out[213]: -1
```

The top character was copied by hitting the minus key on my keyboard in Sublime Text 2.  The latter character comes from hitting the same key directly in iPython in the terminal.

**Comment by takluyver** [comment]
The character in the top example is U+2013, 'EN DASH'. The operator for subtraction in Python, and in almost all programming languages, is U+002D, 'HYPHEN-MINUS'. This should be what you get when you hit the dash key on the keyboard, but I know e.g. Word will autocorrect it to en dash depending on what other characters are around it. I'm surprised that Sublime seems to be doing that. But I don't think it's a bug in IPython - the top example really is invalid syntax. A code-oriented text editor should not be turning hyphen-minus into en dash.
