### ISSUE TITLE
User request for action for "Notebook changed" not clear

### ISSUE THREAD

**Issue by michaelaye** [ipython/ipython#8456]
When I run a remote notebook server and I am opening a running notebook a second time on a different browser I get this error message and request for action on the first instance:

    Notebook has changed since we opened it. Overwrite the changed file?

and I honestly don't understand with certainty what it means. Especially the 'changed since we opened it' is confusing, because sure it has changed since we opened it, because even in the first browser instance I already had worked on it. But I guess this refers to the changes that were put on the server by the 2nd browser instance of the same notebook?

I think my problem in understanding is the doubt on what 'changed file' means, caused by the lack of understanding if my local browser has something like a local copy or if everything happens on the remote server. Not knowing this means that 'changed file' could be both, either a local copy in the old status, or the remotely changed file with the updates from the second browser instance.

Do you see my dilemma?

**Comment by takluyver** [comment]
I think 'changed file' refers to the changes on disk saved by the other instance, and thus 'overwrite' will save the copy on the computer giving that message, obliterating the changes from the other copy.

I can see that it certainly could be clearer, though.

We're also intending to change the model. At present, each tab where you have the notebook open keeps its own copy of the notebook document. We want to have the model on the server, and synchronise changes between clients, in which case this wouldn't be an issue (or much less often, at least).

**Comment by michaelaye** [comment]
and I should base my current decision on which button to press on your "I think" ? ;)

**Comment by takluyver** [comment]
It's a fairly confident thought. ;-) But as I said, the wording could definitely be clearer. And ideally we'd avoid needing to show the message altogether.

**Comment by michaelaye** [comment]
Interestingly, Clicking both "Cancel" and the upper right close x on the dialog has no effect. So I am forced to Overwrite then?

**Comment by takluyver** [comment]
Overwrite, or reload the page to lose the local changes and preserve the
changes on disk. Another area where the UI is not very clear :-(

**Comment by michaelaye** [comment]
Thanks, the reload did it.

**Comment by Carreau** [comment]
see https://github.com/jupyter/notebook/pull/153

**Comment by brettbrocato** [comment]
This message sometimes pops up when there is only one copy of my notebook open.  Why would that happen?
