### ISSUE TITLE
ipython is crashed after update

### ISSUE THREAD

**Issue by Dongkyun-Kim** [ipython/ipython#8458]
When I type "ipython.exe" in terminal. 
![image](https://cloud.githubusercontent.com/assets/11627869/7766809/3199c6ac-00a8-11e5-873e-2277d360e16a.png)

After update via Anaconda Launcher, ipython is crashed. It can't run at all. And spyder too. Updated ipython version is 3.1.0.

**Comment by takluyver** [comment]
You might need to upgrade [path.py](https://pypi.python.org/pypi/path.py).
