### ISSUE TITLE
Stuff displayed with `display_html()` is missing from PDF export

### ISSUE THREAD

**Issue by nchammas** [ipython/ipython#8463]
I have some text and tables displayed using `display_html()` like this:

```python
from IPython.display import display_html
display_html("<h1>Hai</h1>", raw=True)
```

The output of these `display_html()` calls shows up fine in the notebook when I run it, but it's missing from the PDF export (which runs without error).

Here's what I'm running on:

```sh
$ python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': u'cbccb68',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python2.7/site-packages/IPython',
 'ipython_version': '3.1.0',
 'os_name': 'posix',
 'platform': 'Darwin-14.3.0-x86_64-i386-64bit',
 'sys_executable': '/usr/local/opt/python/bin/python2.7',
 'sys_platform': 'darwin',
 'sys_version': '2.7.9 (default, May  6 2015, 13:26:35) \n[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)]'}
```

```sh
$ pdflatex --version
pdfTeX 3.14159265-2.6-1.40.15 (TeX Live 2014)
kpathsea version 6.2.0
Copyright 2014 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Compiled with libpng 1.6.10; using libpng 1.6.10
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with xpdf version 3.03
```

**Comment by Carreau** [comment]
`display_html`  display HTML, Html is not converted to tex, you need to `display` and object that have a `__latex__` repr if you want to have any chance to get something on the PDF.

**Comment by JanSchulz** [comment]
just as a question: pandoc can convert html to whatever format, so why not let nbconvert convert individual messages (e.g. the data from the above display_html) to a specifc (in this case latex), if no direct usage/conversion is possible? I use this strategy in knitpy and thats the way I got pandas html tables displayed in pdfs.

**Comment by Carreau** [comment]
Because Pandoc cannot convert arbitrary html to arbitrary latex. And we
don't want "it works except when it does not".
