### ISSUE TITLE
AttributeError in notebook when quitting debugger

### ISSUE THREAD

**Issue by akhmerov** [ipython/ipython#8465]
To reproduce execute a cell:

```python
raise RuntimeError
```

followed by

```python
%debug
```

and typing `q`.

This results in an `AttributeError: 'NoneType' object has no attribute 'set_completer_delims'` raised in a deeply nested function call.

The error appears in 3.1.0 both Python 2.7.8 and 3.4.3 (I couldn't test with master since the installation isn't straightforward right now). The error appears in notebook and qtconsole, but not in the regular shell.

**Comment by takluyver** [comment]
Replicated in master, thanks.

**Comment by takluyver** [comment]
#8470 should fix it.
