### ISSUE TITLE
Starting terminal in current directory

### ISSUE THREAD

**Issue by peter-ch** [ipython/ipython#8467]
In the IPython notebook when I'm browsing the directory tree I often need to start a terminal in the directory I'm currently in, but it always starts from / when I'm root or /home/peter otherwise. Is that a bug or there is some way I can configure it?

**Comment by takluyver** [comment]
It's not exactly a bug, just a limitation of the way terminals are done at present.

**Comment by peter-ch** [comment]
I can try to patch the code myself to get this behavior. Just something quick and dirty that works. Is it easy?

**Comment by takluyver** [comment]
I don't think it is easy, unfortunately. IIRC, three separate parts of the
code would need changes. I'll try to look into this once we've got 4.0 out.

**Comment by Carreau** [comment]
@Meeseeksdev migrate to jupyter/notebook

**Comment by Carreau** [comment]
@Meeseeksdev migrate to jupyter/notebook
