### ISSUE TITLE
retina figures don't work in QtConsole

### ISSUE THREAD

**Issue by shadowleaves** [ipython/ipython#8468]
setting %config InlineBackend.figure_format='retina' or 'png2x' doesn't make inline plots up to retina's high resolution. in fact they make the plots worse than default (png). anyone knows why? I'm on latest ipython (3.1.0) and this issue has been always around since 2.x versions - it never got fixed.

InlineBackend.figure_format = 'png' (default)
![screen shot 2015-05-24 at 13 28 14](https://cloud.githubusercontent.com/assets/5053963/7788825/e29e0c08-0218-11e5-8542-6ac0082f17a5.png)

InlineBackend.figure_format = 'retina' or 'png2x'
![screen shot 2015-05-24 at 13 28 44](https://cloud.githubusercontent.com/assets/5053963/7788827/ea66242a-0218-11e5-99b9-fcf0691e0663.png)

**Comment by minrk** [comment]
Hm, I can't get the retina figures to misbehave. Can you perhaps share your IPython and matplotlib config files?

This is what my figures look like before/after `%config InlineBackend.figure_format='retina'`:

Before:

![screen shot 2015-05-24 at 12 08 49](https://cloud.githubusercontent.com/assets/151929/7789206/b66bcdba-020d-11e5-867a-272d453ea6dd.PNG)

After: 

![screen shot 2015-05-24 at 12 08 54](https://cloud.githubusercontent.com/assets/151929/7789209/bb9db10e-020d-11e5-9d4c-65bf257437a5.PNG)

**Comment by shadowleaves** [comment]
thanks for helping. here're my ipython settings:
$ cat ~/.ipython/profile_default/ipython_config.py 
c = get_config()

c.IPythonWidget.font_size = 11
c.IPythonWidget.font_family = 'Consolas'

and here's matplotlib setting (only one uncommented line):
$ cat ~/.matplotlib/matplotlibrc
.
.
.
backend      : MacOSX
.
.
.

**Comment by minrk** [comment]
Can you share a notebook where you've produced plots at both retina and non-retina res?

**Comment by shadowleaves** [comment]
the retina plotting in the ipython notebook is working fine. what wasn't working is the plotting in a qt-console terminal (started by $ ipython qtconsole --matplotlib inline).

![screen shot 2015-05-24 at 15 29 14](https://cloud.githubusercontent.com/assets/5053963/7789300/b12c92aa-0229-11e5-979a-2768a1c40a3c.png)

**Comment by shadowleaves** [comment]
hello minrk, could you please take a look at the issue again? as i said, the ipython notebook rendering on retina looks just fine. it's the ipython qtconsole terminal that has problem with retina rendering.

**Comment by minrk** [comment]
It's possible that Qt4 cannot display high-dpi graphics.

**Comment by minrk** [comment]
(i.e. that it does the downsample before the paint, rather than letting the OS do it)

**Comment by alexoliveira** [comment]
I'm having the same issue as above, I'm using Jupyter 4.0.6 and iPython 4.1.2.
Adding `%config InlineBackend.figure_format = 'retina'` at the top of my script doesn't change the graph display. I'm using `%matplotlib notebook`.

**Comment by minrk** [comment]
@alexoliveira The InlineBackend config only affects the inline backend (`%matplotlib inline`). `%matplotlib notebook` is a different backend altogether, and would need its own way to support high-resolution images. @tacaswell any support for double-dpi display in nbagg?

I'm closing this, since it's about the QtConsole, which is limited by Qt's own support of high-dpi display. If you use Qt5, QtConsole figures should work in high resolution.

**Comment by tacaswell** [comment]
There is code for handling retnia in nbagg.  I think it is in the 2.0.0b1 release, might be in 1.5.2rc1.

qt4 can not do high-dpi at all (but qt5 can).

**Comment by minrk** [comment]
Nice, does it do retina by default, or is there a switch to flip?

**Comment by tacaswell** [comment]
For nbagg, I think it introspects the browser and guesses (@jenshnielsen has done most of this work).  I am not sure about qt5.

**Comment by jenshnielsen** [comment]
Actually @mdboom did the work. Unfortunatly I don't think the notebook agg retina will make it into 2.0 but will be in the next release (2.1). We really have to fix the qt5agg backend. There is a PR for that that I have to revisit.

**Comment by jbwhit** [comment]
I'm getting a deprecation warning when using the snippet: 
```%config InlineBackend.figure_format='retina'```

Specifically: 

```/Users/jonathan/miniconda2/envs/newpy3/lib/python3.5/site-packages/ipykernel/pylab/config.py:87: DeprecationWarning: InlineBackend._figure_format_changed is deprecated: use @observe and @unobserve instead.
  def _figure_format_changed(self, name, old, new):
/Users/jonathan/miniconda2/envs/newpy3/lib/python3.5/site-packages/ipykernel/pylab/config.py:78: DeprecationWarning: InlineBackend._figure_formats_changed is deprecated: use @observe and @unobserve instead.
  def _figure_formats_changed(self, name, old, new):```

I'm not sure how I'd use the decorator in a magic. Any suggestions on what to do going forward?

My setup: 

Software	Version
Python	3.5.2 64bit [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)]
IPython	5.0.0
OS	Darwin 15.6.0 x86_64 i386 64bit
numpy	1.11.1
scipy	0.18.0
matplotlib	1.5.2
pandas	0.18.1
Tue Aug 09 12:00:55 2016 PDT

**Comment by takluyver** [comment]
Sorry about that; the deprecation warning is not for your use of the magic, it's for a function that's called by changing the config.

**Comment by JiechengZhao** [comment]
@asmeurer @minrk I have found a ticket https://github.com/ipython/ipython/issues/2234/ , which is similar with this one. Could you have a look at.
I also suffer low resolution result in qtconsole with Sympy in Mac.
