### ISSUE TITLE
Notebook download as PDF fails when remotely hosted images present

### ISSUE THREAD

**Issue by AnthonyHorton** [ipython/ipython#8471]
I have a notebook containing several remotely hosted images displayed using the markdown `![<alt-text>](<image url>)` syntax.  All display fine in the notebook but when I try to download as PDF I get the generic `nbconvert failed: PDF creating failed` error.  Looking in the terminal output I find that remote images are causing LaTeX file not found errors, e.g. `! Package pdftex.def Error: File``http://www.dunlap.utoronto.ca/wp-content/uploads/2013/05/Dragonfly_1080px_Oct-2014.jpg' not found.`  LaTeX doesn't support the use of remotely hosted images but nbconvert is passing the urls to LaTeX anyway, causing a fatal error in the conversion.

Obviously there is a workaround, manually download all the images and change all the urls to point to local files instead, and in most situations you should probably be doing that anyway.  Still, it would be nice if nbconvert checked for remote image links and either issued a more informative error message or downloaded a local copy of the linked image for LaTeX to use.

Output of `python -c "import IPython; print(IPython.sys_info())"`:

```
{'commit_hash': 'cbccb68',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/mnt/data/ajh/Documents/virtualenvs/sci-latest-python3.4.1/lib/python3.4/site-packages/IPython',
 'ipython_version': '3.1.0',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-51-generic-x86_64-with-debian-jessie-sid',
 'sys_executable': '/home/ajh/Documents/virtualenvs/sci-latest-python3.4.1/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.4.0 (default, Apr 11 2014, 13:08:40) \n[GCC 4.8.2]'}
```

**Comment by chuan92** [comment]
I don't know what how nbconvert use pandoc, but pandoc can convert a markdown file with remotely hosted images to pdf.

**Comment by Carreau** [comment]
We use pandoc to convert to TeX then pdflatex the .tex file.
I doubt pandoc "just" download the remote files for you.

If there is a way to ask pandoc the list of files, and get them back that
would be great.
PR welcomed.

**Comment by chuan92** [comment]
@Carreau You are right, pandoc dose a bit more than just pdflatex the .tex file. I wonder whether directly using pandoc to covert to pdf is a good choice?

**Comment by Carreau** [comment]
> @Carreau You are right, pandoc dose a bit more than just pdflatex the .tex file. I wonder whether directly using pandoc to covert to pdf is a good choice?

If you can figure out how to do that...

we use pandoc to convert bits of markdown, there are many pieces that do not go through pandoc, so I'm not sure how you would handle that.

**Comment by Carreau** [comment]
This should be migrated to jupyter/notebook.

**Comment by gabrielaraujof** [comment]
As temporary workaround, is there a way to convert to pdf using local image files?
