### ISSUE TITLE
nbconvert failed: command could not be found: pdflatex

### ISSUE THREAD

**Issue by robdempsey** [ipython/ipython#8473]
Hello

ipython --version  3.1.0

I am not sure if this is the correct place to post this. I have setup a notebook server and I am trying to download a notebook in pdf form in a chrome webbrowser.

I receive the following message 

500 : Internal Server Error
nbconvert failed: command could not be found: pdflatex

However if I run the same on the command line I get a successful conversion

ipython nbconvert --to pdf "Panda Demo.ipynb"
[NbConvertApp] Converting notebook Panda Demo.ipynb to pdf
[NbConvertApp] Writing 18537 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running pdflatex 3 times: ['pdflatex', 'notebook.tex']
[NbConvertApp] PDF successfully created
[NbConvertApp] Writing 51679 bytes to Panda Demo.pdf

the pdflatex is in everyones' path?

Any ideas?

Rob

**Comment by takluyver** [comment]
If you inspect `os.environ['PATH']` inside a notebook (kernels should inherit environment variables from the notebook server), is the directory containing pdflatex on there?

**Comment by robdempsey** [comment]
Thanks it gave me the idea.  Just in case someone else has the problem.  To survive a reboot I had used the following entry on the cron

@reboot /root/anaconda3/bin/ipython notebook --profile nbserver >> /tmp/notebook.log 2>&1

however this did not pick up my .bash_profile hence environment variables.  Move to a shell script

@reboot /home/user123/.ipython/startup_script.sh

with the contents below works

#!/bin/bash
. /etc/profile
. $HOME/.bash_profile
/root/anaconda3/bin/ipython notebook --profile nbserver >> /tmp/notebook.log 2>&1

**Comment by takluyver** [comment]
BTW, I think that if you set environment variables in `~/.profile` instead of `~/.bash_profile`, they will be set when you log in, instead of only when you run bash.

**Comment by Carreau** [comment]
On my system, `.profile` is loaded only if `.bash_profile` does not exist. So I have a `source .profile` in my `.bash_profile`. Just in case.

**Comment by takluyver** [comment]
I believe that on Linux, `.profile` is actually run when you log in, separate from whatever bash does with its confusing constellation of profile & rc files. I think I've read that that doesn't apply to Macs, though.

**Comment by praneethkumarpidugu** [comment]
1.Initially you need Pandoc
2.Convert the .ipynb to latex format
      ```$ipython nbconvert --to latex "Linear_regression_using_sample_data.ipynb" ```
3.Pandoc has a large version which takes 1 -2 hours for installation. Instead install this basic version from this link http://www.tug.org/mactex/morepackages.html
4.Restart the terminal for the changes to apply.
5.Execute the same path where you have performed step 2 
      ```$jupyter nbconvert NAME_OF_YOUR_FILE.ipynb --to pdf```
6.If you are have any issues with latxt install this additional packages:
     ```$sudo tlmgr install adjustbox
         $sudo tlmgr install collectbox
         $sudo tlmgr install ucs```
7.Repeat step 5
Note: I'm assuming you have basictex installed not the full version.
