### ISSUE TITLE
DeprecationWarnings should be visible by default in interactive usage

### ISSUE THREAD

**Issue by njsmith** [ipython/ipython#8478]
DeprecationWarning and PendingDeprecationWarning are invisible by default. The rationale for this is that they are only useful to people who are writing code, so they should not be shown to end-users who are merely running code.

If someone is typing stuff into the interactive REPL or a notebook, though, and the code they type uses some deprecated functionality, then we should actually show them this warning. We know that the author is sitting right there. And they're probably going to take whatever they tested interactively and move it into a more permanent form and ugh.

This problem is particularly acute for packages that are primarily used through the interactive prompt, like numpy. I'm really tired of getting bugs like this: numpy/numpy#5919

The solution is simple: when entering interactive mode, IPython should do something like:
```
warnings.filterwarnings("default", category=DeprecationWarning, module="__main__")
warnings.filterwarnings("default", category=PendingDeprecationWarning, module="__main__")
```
This means "for any `DeprecationWarning` or `PendingDeprecation` warning which is caused by code running in the module with name `"__main__"`, use the `"default"` handler (which means: display once per line of code that triggered it). (Confusingly, the default handler for these warning messages is not `"default"`, but `"ignore"`. So overriding the default with `"default"` produces a non-default outcome.)

**Comment by njsmith** [comment]
See also: https://bugs.python.org/issue24294

**Comment by Carreau** [comment]
We already reset the warning filter in IPython so +1.
We could then turn our shims modules into Dreprecation warning and not User warning also maybe.

**Comment by charris** [comment]
IIRC, the bug was introduced when Python made no DeprecationWarning the default in order to work around the mistake of backporting PyCapsule to 2.8 and raising DeprecationWarning for PyCObject.

**Comment by takluyver** [comment]
I think this makes sense. @njsmith , do you have time to do a PR?

**Comment by Carreau** [comment]
commiting and I push a PR.

**Comment by Carreau** [comment]
(no test yet though)

**Comment by minrk** [comment]
I hadn't thought of this, but it's a good idea. I don't think that there's any sensible argument against enabling it for `__main__`. I'm wondering if we should unhide deprecations across the board, though.

The discussion on [python-ideas](http://comments.gmane.org/gmane.comp.python.ideas/32191) is a bit depressing.

**Comment by Carreau** [comment]
if we enable it locally you get too many warning due to deprecation everywhere. Even on 3,4 you get loads of deprecation just because IPython  use `imp`

**Comment by takluyver** [comment]
But you should only be seeing warnings associated with `__main__`, right? So you shouldn't see all the warnings about our use of imp.

**Comment by njsmith** [comment]
@takluyver: Right, the PR #8480 currently only shows warnings associated with `__main__`. But @minrk suggested that maybe we should show all deprecation warnings, even those not associated with `__main__`.

It is true that warnings are *very* often attributed incorrectly. The default value for `stacklevel=` is always wrong, and in the special case whole-module deprecations it turns out that in Python 3 [it's not even possible to get right](https://bugs.python.org/issue24305) without some major shenanigans. Oops.

**Comment by Carreau** [comment]
I guess most of our imports will happen before we set up the warning filters, so our imports shouldn't be seen. 

Though with #8480, even if I install a filter on everything, a user's `import imp` does not trigger a warning on stderr, probably cause the filter is added too late.

**Comment by jorisvandenbossche** [comment]
an after-merge + 1 
This is one of the reasons we use FutureWarning in pandas instead of DeprecationWarning (although this has of course the disadvantage of also giving warnings from library code you use ..)

**Comment by njsmith** [comment]
@jorisvandenbossche: note that for this to work properly, you also have to make sure the DeprecationWarnings are correctly attributed, which I've noticed that a lot of pandas's aren't. Basically any time you call `warnings.warn` but don't pass in `stacklevel=`, then that's a bug.

**Comment by Carreau** [comment]
Should we propose to make stacklevel a mandatory argument in CPython3.6

**Comment by takluyver** [comment]
Make an optional argument compulsory *because* lots of existing code isn't using it? That doesn't sound like a great idea.

Maybe it should issue a warning if you don't pass stacklevel ;-)

**Comment by njsmith** [comment]
The backcompat issues are substantial, but you never know, might be worth a
try and see what people say. I probably wouldn't bring it up until a patch
was merged to cpython though, which could then be pointed to as motivation
for getting people to clean up their stacklevels.

**Comment by njsmith** [comment]
That does sound more likely to actually be merged :-).

**Comment by Carreau** [comment]
> The backcompat issues are substantial, but you never know, might be worth a
> try and see what people say. I probably wouldn't bring it up until a patch
> was merged to cpython though, which could then be pointed to as motivation
> for getting people to clean up their stacklevels.

I don't get this sentence. My brain is probably fried.

In which case a stacklevel of 1 is correct ? Is stacklevel of 2, The most usefull use value ? 
Or should we add a warning mode that do not raise, but actually print the full stacktrace so that you can manually inspect. 

Thoughts ?

**Comment by jorisvandenbossche** [comment]
@njsmith Yeah, I know you once posted a comment about that somewhere on a pandas issue, but never had the time to look at it. 
Do you know of some good explanations what the `stacklevel` argument exactly does? Because I don't find the docs (https://docs.python.org/2/library/warnings.html#warnings.warn) very helpful to grasp it fully.

**Comment by jorisvandenbossche** [comment]
@njsmith So actually it is probably rather simple: we need to use `stacklevel=2` everywhere, only in cases we have eg a helper function that does the deprecation call which is called in the deprecated function, you need to use `stacklevel=3`

**Comment by Carreau** [comment]
yep, basically. Little more complicated for warning on "import", but that's a Python bug. And if you use decorators, in which case you need to take into account the wrapper of the decorator.

**Comment by jorisvandenbossche** [comment]
yes, I was just testing the decorator case (we use this one: https://github.com/pydata/pandas/blob/master/pandas/util/decorators.py#L18), but surprisingly it seems that there the default is ok, and I don't need to specify `stacklevel=2`

**Comment by Carreau** [comment]
Yah I was thinking of

```
@dec fun():
   warn(staclevel=probably(3))
```
