### ISSUE TITLE
Don't import dreload by default. 

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#8485]
`core/builtin_trap.py`

```python
from IPython.lib import deepreload
if self.shell.deep_reload:
    self.auto_builtins['reload'] = deepreload.reload
else:
    self.auto_builtins['dreload']= deepreload.reload
```

Does it make sens to stop doing that by default ?

Warn message say it will be removed in 6.0.

**Comment by fperez** [comment]
+1 to removing this as a config option, people can just import it instead.
