### ISSUE TITLE
Terminal in Notebook does not respect allow_origin setting

### ISSUE THREAD

**Issue by rgbkrk** [ipython/ipython#8491]
The terminal websocket endpoint doesn't reflect the `allow_origin` setting.

**Comment by takluyver** [comment]
It looks like copying the `check_origin` method from `ZMQStreamHandler` to `TermSocket` should be what's needed.

**Comment by rgbkrk** [comment]
I _think_ it does now and beyond that this issue belongs in jupyter/notebook
