### ISSUE TITLE
variable substitution in a %%bash cells first line fails silently if one variable isn't defined

### ISSUE THREAD

**Issue by drevicko** [ipython/ipython#8492]
Variable substitution in the first line of `%%bash` cells doesn't happen if one of the variables isn't defined. Instead, the name of the variable with a "$" prepended is sent to bash. This is true even for variables in the list that ARE defined.

To demonstrate, say I have a cell like this:

    %%bash -s $a_variable $another_var
    echo $1 $2

If both variables are defined, `str(a_variable)` and `str(another_var)` are output by bash (since variables are substituted by their string representation). If, on the other hand, at least one of the variables isn't defined, bash outputs this:

    $a_variable $another_var

The bad part about it, is that there is no error, exception or anything to warn you that something's gone wrong.

**Comment by Carreau** [comment]
This is a know limitation of the system, There is no easy way to know wether or not you want to pass a litera; `$something` or expand. The only way is to try expanding, and if it fails fallback on the literal. If you have many `$vars` we cannot distinguish which one fails, so the all raw string get send  to bash. And as passing `$literal` without expansion is something that people want to do, we cannot error either. And this applies to all magics. 

There is a plan for magic to have opt-in to automatic variable expansion, but you can only guess what people want to do up to a certain point.

**Comment by takluyver** [comment]
I remembered that we silently fell back to passing literal `$foo`, though I'm a little surprised that as soon as one expression fails, we abandon trying to format any of them. I guess it's fairly rare that you'd actually want a mix of literal $foo and expanded Python expressions in one command, though.

**Comment by Carreau** [comment]
I remember digging through that code for some close but different reason, where it gives some weird but logical behavior in `${something}` vs `{something}`.. anyway. Keep in mind that we actually eval `$...` and if any raises we continue with the raw string. So that things like that are possible:

```
In [1]: class F:
   ...:     @property
   ...:     def bar(self):
   ...:         return 'yeah'
   ...:

In [2]: !echo {F().bar}
yeah
```

We don't dintinguish a NameError from any other excpetions:

```
    def var_expand(self, cmd, depth=0, formatter=DollarFormatter()):
        """Expand python variables in a string.

        The depth argument indicates how many frames above the caller should
        be walked to look for the local namespace where to expand variables.

        The global namespace for expansion is always the user's interactive
        namespace.
        """
        ns = self.user_ns.copy()
        try:
            frame = sys._getframe(depth+1)
        except ValueError:
            # This is thrown if there aren't that many frames on the stack,
            # e.g. if a script called run_line_magic() directly.
            pass
        else:
            ns.update(frame.f_locals)

        try:
            # We have to use .vformat() here, because 'self' is a valid and common
            # name, and expanding **ns for .format() would make it collide with
            # the 'self' argument of the method.
            cmd = formatter.vformat(cmd, args=[], kwargs=ns)
        except Exception:
            # if formatter couldn't format, just let it go untransformed
            pass
        return cmd
```

**Comment by drevicko** [comment]
Hmm.. Makes sense...

The current behaviour is certainly strange - something that works can be made to not work by adding a parameter. That strangeness is why I raised this issue: I'd forgotten to define the extra parameter (I'd written the code but forgotten to execute it, a common enough mistake I think). 

It was only through constructing an example for this issue that I realised what was going on.. I think that if the ok variables had passed through, and the undefined one appeared as `$variable_name` it would have been pretty obvious what was happening.

To do that, I guess a `DollarFormatter` is needed that doesn't raise an exception if it doesn't find a variable, and keeps parsing the remainder. Easy enough to do, but how would that behaviour fit with other uses of `DollarFormatter`?

**Comment by Carreau** [comment]
> Easy enough to do

![30](https://cloud.githubusercontent.com/assets/335567/7905369/467a4058-07cc-11e5-8ba0-37ef32948b48.jpg)

I doubt DollarFormatter is used in many places, and we can have another Class we use in this particular place.

**Comment by takluyver** [comment]
I've got a feeling this is the only place DollarFormatter is used. I'd be OK with changing it so a failure to format one parameter doesn't disrupt the others.

**Comment by Carreau** [comment]
> I've got a feeling this is the only place DollarFormatter is used

In IPython, [first result on github search](https://github.com/gems-uff/noworkflow/blob/2bdae510c86c7c58b5f98a0892a17ae876d1f07b/capture/noworkflow/now/ipython/magics/now_prolog.py) is someone else using it in a not-an-ipython-fork project.
