### ISSUE TITLE
matplot notebook - closing figure behaviour is inconsistent

### ISSUE THREAD

**Issue by mangecoeur** [ipython/ipython#8495]
Exactly when a figure is/isn't closed and when it will display seems quite inconsistent with the matplot `notebook` backend, depending on whether you put `close` in the same or in a different cell. If you create a figure then close it with the 'X' button, calling `plt.gcf()` in the next cell will return the figure image anyway just as if you hadn't closed it.

Likewise, if you do:

```python
%matplotlib notebook
f = plt.figure()
plt.plot([1,2,3], [1,2,3])
```

-> figure appears
--> new cell

```python
plt.close(f)
plt.gcf()
```

-> figure image appears (non interactive)

However if you group the commands in a single cell:

```python
%matplotlib notebook
f = plt.figure()
plt.plot([1,2,3], [1,2,3])
plt.close(f)
plt.gcf()
```

I see the figure widget controls but no image (and the layout is also somewhat broken - using Firefox). 

Calling `gcf()` in the next cell does not show any image. Sometimes you get the previously plotted image if you don't reset the backend by calling `%matplotlib notebook`.

If you are making many plots (e.g. in a loop) - you can't close figures as they are created because they don't appear, but if you don't close them you quickly hit 20 figures and start seeing the  'many figures open' warning. It also makes it more annoying if you want to always plot and close so that you don't accidentally start plotting on the current figure instead of creating a new one.

**Comment by jenshnielsen** [comment]
This is really a matplotlib issue since the notebook backend is implemented there. There are related issues in matplotlib such as https://github.com/matplotlib/matplotlib/issues/4281

**Comment by mangecoeur** [comment]
@jenshnielsen ok - I thought it might be an ipython issue because of the interactive widgets. Will look at matplotlib side.

**Comment by Carreau** [comment]
It might be a coupled issue. I would suggest  using the matplotlib oo way, `fig, ax = subplots()` so that you get a ref to the current axis and can access it around. It will avoid subtilities like that.

**Comment by takluyver** [comment]
Closing here as it's probably an mpl issue. We can reopen if it looks like there's something for IPython to fix.

**Comment by mangecoeur** [comment]
Also note: The oo interface may be preferred, but if you are using pandas or seaborn for plotting they basically work in a procedural way and you don't have control over that.

**Comment by mwaskom** [comment]
That's not quite accurate: http://stackoverflow.com/questions/23969619/plotting-with-seaborn-using-the-matplotlib-object-oriented-interface

Pandas plotting functions also can be directed to plot onto specific existing Axes, as well.
