### ISSUE TITLE
Safety of getpass.getpass() in a notebook

### ISSUE THREAD

**Issue by mikecroucher** [ipython/ipython#8496]
Say I do this

`foo( getpass.getpass() )`

and enter a password at the prompt. Are the results from getpass.getpass() stored anywhere in the ipynb file? I'm assuming that they are not but, since I'm about to put such a ipynb file on github, I thought it best to ask.

Cheers,
Mike

**Comment by Carreau** [comment]
if `foo` prints it, or return it and is the last statement of the cell it might. But then you would saw it in the notebook. 

Here is what is stored, you can see that only dots are store in the notebook itself. 
```
{
   "cell_type": "code",
   "source": [
    "import getpass\n",
    "getpass.getpass()\n",
    "pass"
   ],
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "········\n"
     ]
    }
   ]
  }
```
