### ISSUE TITLE
Trigger '?' resolution with the tab key

### ISSUE THREAD

**Issue by ipython** [ipython/ipython#85]
Original Launchpad bug 284006: https://bugs.launchpad.net/ipython/+bug/284006
Reported by: fdo.perez (Fernando Perez).

An oft requested feature is to have

`x?<TAB>`

actually provide the information without the person having to type

`x?<ENTER>`

The implementation is probably one that will work by directly printing out the information returned by '?' and returning an empty completion list and stopping the completion process, because the readline api by default wants a list.

**Comment by Carreau** [comment]
This is available in the notebook with Shift-Tab. There is a general consensus that completion and introspection should kind-of be merged, even in the terminal. 

I doubt this issue with be taken care of directly, and it is 1/2 a decade old, so I'm going to close it. 

Please open a new issue is needed. 

Thanks.
