### ISSUE TITLE
%%timeit raises KeyError with more than one execution

### ISSUE THREAD

**Issue by drevicko** [ipython/ipython#8508]
In an IPython notebook (ipython 3.1.0, Python 2.7.3 and 4.00-dev, Python 2.7.8, ipython updated just now), if I execute the following in a cell with `-n2` or greater, it produces a KeyError. However if I execute with `-n1` it works:

```
%%timeit -n2 foo=set((1,3,4))
foo.remove(4)
```
produces
```
... other stacktrace data ...

/mnt/local/python-virtual-environments/ipython-jupyter/local/lib/python2.7/site-packages/IPython/core/magics/execution.pyc in timeit(self, number)
    130         gc.disable()
    131         try:
--> 132             timing = self.inner(it, self.timer)
    133         finally:
    134             if gcold:

<magic-timeit> in inner(_it, _timer)

KeyError: 4
```
But if I limit it to one loop:
```
%%timeit -n1 foo=set((1,3,4))
foo.remove(4)

1 loops, best of 3: 0 ns per loop
```
even more confusing - this also works:
```
%%timeit -n2 foo=set((1,3,4))
if 4 in foo:
    foo.remove(4)

2 loops, best of 3: 954 ns per loop
```

**Comment by BMJHayward** [comment]
I'm on python 3.4.0, ipython 3.1.0, same results.
Also calling remove on the other elements; 1 and 3, throws the same error.
Using:
    foo=list((1,3,4)), foo.remove(3) throws value error.

I'm not sure this is a problem. On the second loop you're trying to remove something that isn't there. 
The timeit method doesn't recreate the object for every loop, so it probably _should_ raise an error when you try to remove something that isn't there.

**Comment by drevicko** [comment]
No, it gets re-initialised each attempt. Check out what happens if you do
```
if 4 in foo:
    foo.remove(4)
```
you can run that with `-n2`, at least with python 2.7

**Comment by jenshnielsen** [comment]
If you run that code it will only remove it in the first run. The next one will just check that its not there and do nothing.

**Comment by drevicko** [comment]
You're quite right, I was assuming it gets re-initialised, but doesn't. 

Just to be sure, I tried this:

```In [4]: %%timeit -n2 foo=set((1,2,3,4))
print foo
if 4 in foo:
  foo.remove(4)
   ...: 
set([1, 2, 3, 4])
set([1, 2, 3])
set([1, 2, 3, 4])
set([1, 2, 3])
set([1, 2, 3, 4])
set([1, 2, 3])
The slowest run took 7.34 times longer than the fastest. This could mean that an intermediate result is being cached 
2 loops, best of 3: 12.5 µs per loop
```

Which means it's hard to use %timeit to measure removing items from some collection, since `-n1 -r200` takes the best of 200, not the average or something like that. Oh well!

**Comment by takluyver** [comment]
There's a good reason it works like this - timing always involves some overhead, and for small operations like this, the overhead would dwarf what you're trying to time. So the operation is done many times to build up a significant overall time, and then it divides by the number of runs. The initialisation is outside this loop, because that's not what you're trying to time.

If you need to time something like this that's not immediately repeatable, time creating a set, then time creating it and removing an item from it, and take the difference.

**Comment by drevicko** [comment]
That's true, but I wonder if it would be kinder if timeit could do this for you when requested. The warning about 'intermediate results' could mention this option. I guess it's an edge use case, but whenever I hit this sort of confusion, I wonder how many others hit it also.

**Comment by Carreau** [comment]
If you really want to time something, then you better have to use the timeit module explicitely. The magic is indeed convenient, but is just a wrapper.
