### ISSUE TITLE
"This backport is for Python 2.7 only."

### ISSUE THREAD

**Issue by marmalodak** [ipython/ipython#8509]
Should I do something different to install ipython3?

    $ pip install 'ipython[all]>=3'
    Requirement already satisfied (use --upgrade to upgrade): ipython[all]>=3 in /mnt/myth/john/projects/jupyter/venv/ipython3-venv/lib/python3.4/site-packages
    Collecting mistune>=0.3.1 (from ipython[all]>=3)
      Using cached mistune-0.5.1-py2.py3-none-any.whl
    Collecting nose>=0.10.1 (from ipython[all]>=3)
      Using cached nose-1.3.7-py3-none-any.whl
    Collecting jinja2 (from ipython[all]>=3)
      Using cached Jinja2-2.7.3.tar.gz
    Collecting requests (from ipython[all]>=3)
      Using cached requests-2.7.0-py2.py3-none-any.whl
    Collecting tornado>=4.0 (from ipython[all]>=3)
      Using cached tornado-4.2.tar.gz
    Collecting terminado>=0.3.3 (from ipython[all]>=3)
      Using cached terminado-0.5.tar.gz
    Collecting pyzmq>=13 (from ipython[all]>=3)
      Using cached pyzmq-14.6.0.tar.gz
    Collecting jsonschema>=2.0 (from ipython[all]>=3)
      Using cached jsonschema-2.5.0-py2.py3-none-any.whl
    Collecting pygments (from ipython[all]>=3)
      Using cached Pygments-2.0.2-py3-none-any.whl
    Collecting numpydoc (from ipython[all]>=3)
      Using cached numpydoc-0.5.tar.gz
    Collecting Sphinx>=1.1 (from ipython[all]>=3)
      Using cached Sphinx-1.3.1-py2.py3-none-any.whl
    Collecting markupsafe (from jinja2->ipython[all]>=3)
      Downloading MarkupSafe-0.23.tar.gz
    Collecting ptyprocess (from terminado>=0.3.3->ipython[all]>=3)
      Using cached ptyprocess-0.5.tar.gz
    Collecting functools32 (from jsonschema>=2.0->ipython[all]>=3)
      Using cached functools32-3.2.3-1.tar.gz
        Complete output from command python setup.py egg_info:
        This backport is for Python 2.7 only.

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-12p_vfd_/functools32
    $ pip -V
    pip 7.0.3 from /mnt/myth/john/projects/jupyter/venv/ipython3-venv/lib64/python3.4/site-packages (python 3.4)

**Comment by takluyver** [comment]
Looks like there was an issue with jsonschema - Julian/jsonschema#228. They've fixed it in the short term by removing the wheel. You may need to clear pip's cached files before trying again.

**Comment by sigmavirus24** [comment]
pip's caching library should catch this. If it doesn't work without removing pip's cached files, you should file a bug at github.com/pypa/pip

**Comment by marmalodak** [comment]
Seems to be fixed.  Thanks for the quick response!
