### ISSUE TITLE
notebook file names have last six character truncated

### ISSUE THREAD

**Issue by gregcaporaso** [ipython/ipython#8510]
I've been experimenting with [ipymd](https://github.com/rossant/ipymd) and noticed that my file names are truncated when they are converted to notebook titles (see the image below). It looks like the notebook is assuming that the file extension will be ``.ipynb``, so truncating the last six characters when the title is generated. If the extension is not ``.ipynb`` but rather ``.md`` (as in my case), part of the name gets truncated too. For example, in my case ``getting-started.md`` becomes ``getting-star``. 

![screenshot 2015-06-05 09 37 03](https://cloud.githubusercontent.com/assets/192372/8010634/9c100e1a-0b66-11e5-8459-bc8f68c14a80.png)

**Comment by Carreau** [comment]
That's a jupyter/notebook bug, not an IPython one. [this line](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/notebook.js#L1755)  that you probably want to replace by `string.replace(/\.[^.]+$/, "")`. Though the assumption that the extension is `.ipynb` is baked on many places. 

Do you want to make an attempt at a PR ?

**Comment by rossant** [comment]
Yeah, I know about this bug, would love it if it could be fixed somehow. I fear that it's not a trivial fix but I may be wrong.

Might be related to #8185

**Comment by minrk** [comment]
Should be fixed by jupyter/notebook#135.

**Comment by Carreau** [comment]
I'm fine with removing the assumption as `.ipynb` in some places. It might be assumed in a few other places though.
