### ISSUE TITLE
Export IPython Notebook to Scientific Article Format

### ISSUE THREAD

**Issue by miltonlab** [ipython/ipython#8512]
Exists plans to create a plugin to generate a Article from templates as:
Abstract
Introduction
Experiment
Theory
Bibliography, etc....

**Comment by Carreau** [comment]
This is a https://github.com/jupyter/nbconvert issue. The core is really configurable, so it will most likely be a custom template, not bake into the core.

This probably go under the umbrella of https://github.com/ipython/ipython/issues/4119 (that shoudl be migrated to https://github.com/jupyter/nbconvert too)
