### ISSUE TITLE
How to stop the iPython notebook to run the command line, run only python code

### ISSUE THREAD

**Issue by nicky1108** [ipython/ipython#8514]
I am using iPython notebook build a online interactive teaching website, but I don't want users to run command line, any idea how to remove iPython notebook command line function? Is there any configuration or something? 

![img1](https://cloud.githubusercontent.com/assets/4279283/8039290/3e304e5e-0e3b-11e5-9479-d8b4f93ee147.png)

**Comment by takluyver** [comment]
Are you doing this for security, or to avoid confusing users?

If you want to avoid confusion, you can turn off automagics by setting `c.InteractiveShell.automagic = False` in a config file. This will prevent `ls` from working, but you'll still be able to achieve the same thing with `!ls`, or `os.system('ls')`, or `os.listdir()`.

If you want to restrict what users can do, that's much harder. The best bet is to run the kernel in some sort of container, and let users do whatever they want within the container.

**Comment by nicky1108** [comment]
thanks!
