### ISSUE TITLE
traitlets dependency

### ISSUE THREAD

**Issue by chebee7i** [ipython/ipython#8518]
Currently, it looks like it is necessary to install the version of traitlets from GitHub. `setup.py` does not do this, and an incorrect version is installed which results with:

`ImportError: No module named config.application`

This information is not mentioned it the `README.rst`. Should it be? I had to do: 

`pip install -r requirements.txt`

**Comment by Carreau** [comment]
Yep it normal it's a non released software version. We expect people that hack from master to follow the annouced for now, and it's explained on [our blog post](http://blog.jupyter.org/2015/04/15/the-big-split/).

Traitlets should be release soonish enough that we don't need to update the readme for that. Or it will become outdated.

Thanks for the question though.

**Comment by chebee7i** [comment]
Ahh thanks for the link. I haven't been following the blog :)
