### ISSUE TITLE
GenericCheckpointsMixin missing methods

### ISSUE THREAD

**Issue by KrishnaPG** [ipython/ipython#8522]
In the commit https://github.com/ipython/ipython/commit/82dcba3ba9ffa3ee3193602e2d5df3ef3c3de106 two new methods were introduced `get_notebook_checkpoint` and `get_file_checkpoint` but the definition of 
`GenericCheckpointsMixin` itself was not updated. 

It still has `get_checkpoint` method. Subclasses work now, but just thought of notifying it.

The file in question is: `ipython/IPython/html/services/contents/checkpoints.py` and the branch https://github.com/ipython/ipython/releases/tag/rel-3.1.0

**Comment by ssanderson** [comment]
https://github.com/ipython/ipython/pull/8524

**Comment by ssanderson** [comment]
@minrk it was easiest to PR this against the 3.x branch.  Since the main repo lives in jupyter/notebook, is there an easier way to forward-port this change other than plain-old copy/paste?

**Comment by minrk** [comment]
copy/paste is the simplest I have found. Sometimes building a patch and updating paths works, though.
