### ISSUE TITLE
exists() method for Checkpoints class

### ISSUE THREAD

**Issue by KrishnaPG** [ipython/ipython#8523]
Presently the [`Checkpoint`](https://github.com/ipython/ipython/blob/3.x/IPython/html/services/contents/checkpoints.py#L13) class has `list_checkpoints()` method that is being used to verify if a check point exist for a given file or not, such as [here](https://github.com/ipython/ipython/blame/3.x/IPython/html/services/contents/filemanager.py#L387):
````
                # One checkpoint should always exist for notebooks.
                if not self.checkpoints.list_checkpoints(path):
                    self.create_checkpoint(path)
````
In some scenarios listing all checkpoints is too costly affair when we are just interested in only checking the existence of atleast one.

Perhaps the `Checkpoint` class should have `checkpoint_exists_for(path)` kind of mechanism.

(PS: Not sure if this *issues* forum is right place for feature requests like this, my apologies if this is not.)

**Comment by takluyver** [comment]
Github issues are a fine place for feature requests. For future issues about the notebook, though, https://github.com/jupyter/notebook is the repository to file them against. It's OK to leave this one here, though.

**Comment by KrishnaPG** [comment]
Thanks for the clarification @takluyver . Will try to use jupyter moving forward.

**Comment by KrishnaPG** [comment]
Moved to [here](https://github.com/jupyter/notebook/issues/142). Hence closing this.
