### ISSUE TITLE
Code introspection with decorators feature request

### ISSUE THREAD

**Issue by jrellis** [ipython/ipython#8529]
When using ?? to get source code introspection on a decorated function, only the source of the decorator is included, which is seldom what someone would be looking for. What do people think about instead showing the source of the decorated function?

**Comment by Carreau** [comment]
That is not really something IPython could decide. Decorators are syntactic sugar for:

```
def fun():
    pass

fun = decorate(fun)
```

It is the responsibility of the decorator to move things around if desires, which `functools.wraps` does for docstring.

**Comment by jrellis** [comment]
IPython could get the code; for example by inspect.getsource on functional items of func_closure on the function. It seems reasonable to say that functools should take care of this rather than IPython, as it does for the docstring; other decorator libraries do. Still, IPython is extending python semantics here, so it might make sense for the IPython semantics to act in the most useful way for the user rather than be bound by choices in functools.

**Comment by ssanderson** [comment]
@jrellis if you use functools.wraps (https://docs.python.org/2/library/functools.html) in your decorator definition, IPython will find the docstring of your decorated function correctly.

```
from functools import wraps
def decorator_with_wraps(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        f(*args, **kwargs)
    return decorated

def decorator_no_wraps(f):

    def decorated(*args, **kwargs):
        f(*args, **kwargs)
    return decorated

[13]: 
@decorator_with_wraps
def f():
    "MY AWESOME DOCSTRING"
    pass

In [14]: f?
Signature: f(*args, **kwargs)
Docstring: MY AWESOME DOCSTRING
File:      ~/quantopian/qexec/zipline_repo/<ipython-input-11-9764957933ed>
Type:      function

[15]: 
@decorator_no_wraps
def f():
    "MY AWESOME DOCSTRING"
    pass

In [16]: f?
Signature: f(*args, **kwargs)
Docstring: <no docstring>
File:      ~/quantopian/qexec/zipline_repo/<ipython-input-12-905e59f6147e>
Type:      function

```

**Comment by ssanderson** [comment]
Oops, missed @Carreau's reference to `wraps` above...

**Comment by Carreau** [comment]
The thing to show is not alway obvious, it will be definitively painful in Python2. 

functools.wraps set `__wrapped__` in python 3 and show the wrapped function, 
and we already handle this case when decorator are used with python3 and functools wraps. 

```python
import functools
from functools import wraps

def dec(fun):
    @wraps(fun)
    def _wrap():fun()
    return _wrap

@dec
def orig():
    """orig docstring"""
    pass

orig??
# Signature: orig()
# Source:
# @dec
# def orig():
#     """orig docstring"""
#     pass
# File:      ~/<ipython-input-22-d4a101bc95e5>
# Type:      function
```

Doing it magically canot work in many cases like [here](https://github.com/Carreau/insupportable/blob/master/insupportable/insupportable.py#L245-L247) where you can use this function as a decorator, but actually what you are interested in is one of the parameters of the constructor of the class, while the actual thing you call when you call your original function is the `__call__` of this same class. I can rewrite the same in a similar manner where actually the original decorate function has closure function, which is perfectly fine. There is no way from the `??` caller perspective to guess what should be inspected if the writer of the decorator does not give a hint.

extreme oposite case.

```
def RaiseAtCall(fun)
   def r():
         raise ValueError('told you it was deprecated')
   return r

@RaiseAtCall
def too_old():
    pass
```
There is no closure to inspect, no handle on original function, nothing to guess. 

So best thing we can do is tell decorator writeers to 1) use python3 2) functools.wraps.
