### ISSUE TITLE
raw_input() text formatting

### ISSUE THREAD

**Issue by interrogator** [ipython/ipython#8532]
When using `raw_input()` in the Notebook, newlines aren't represented until after the user has entered something:

![screen shot 2015-06-12 at 10 09 51 pm](https://cloud.githubusercontent.com/assets/10471132/8131915/4180d4f8-1150-11e5-961d-b1a08bb400cb.png)

![screen shot 2015-06-12 at 10 10 03 pm](https://cloud.githubusercontent.com/assets/10471132/8131916/4180e86c-1150-11e5-8b56-753c0fa6ac0b.png)

This is different from IPython on the command line. Any ideas?

**Comment by Carreau** [comment]
is is most likely a jupyter/notebook issues.

**Comment by minrk** [comment]
closed by jupyter/notebook#182
