### ISSUE TITLE
Autobuild docs

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#8533]
RFTD, or travis + ghpages. 

marking as sprint friendly SciPy.

**Comment by souravsingh** [comment]
I would like to work on this issue.

**Comment by Carreau** [comment]
It seem to me that this already partially works as [the latest branch](http://ipython.readthedocs.org/en/latest/) seem to point to latest ipython commit. 

There might be part of the build that don't work maybe, not sure anymore why I openend that.

**Comment by Carreau** [comment]
jupyterhub and ipywidgets seem to not havedocs on readthedocs. You can try to set up these, if you like.

**Comment by minrk** [comment]
JupyterHub's using markdown docs on GitHub, so no readthedocs there, for now.

**Comment by Carreau** [comment]
My bad, readthedocs can use mkdocs, could it be useful ?

**Comment by Carreau** [comment]
Thanks to @willingc awesome work, awesome docs are building on RTD, so closing this.
