### ISSUE TITLE
readline show-mode-in-prompt not working

### ISSUE THREAD

**Issue by memeplex** [ipython/ipython#8539]
For people using vi mode with readline, this option is really convenient. It doesn't work quite right with ipython 3.1: the mode is shown in the line before the prompt and it's never updated. I've tested the option with bash, python and R shells and the behaviour is consistently as expected. I know there are issues upstream with readline, but I don't think this is one of those.

**Comment by takluyver** [comment]
Could it be a conflict with one of the [options we set in readline](https://github.com/ipython/ipython/blob/rel-3.1.0/IPython/core/interactiveshell.py#L399)?

**Comment by memeplex** [comment]
The problem is this line:

`separate_in = SeparateUnicode('\n', config=True)`

Changing it to the following makes the mode indicator work:

`separate_in = SeparateUnicode('', config=True)`

It's configurable so this would not classify as a bug after all, but maybe some short commentary in the documentation could be desirable.

**Comment by takluyver** [comment]
So it doesn't work if the prompt we pass to `raw_input` starts with a newline? That sounds like an issue with readline, or maybe with the Python bindings of readline.

I don't think it's worth trying to document tiny details like this - the more docs we have, the more they'll get out of date. If you want a more visible record of it than this issue, you can e.g. ask a Stackoverflow question and answer it yourself.

**Comment by memeplex** [comment]
Ok, I'm reporting this upstream. Let's see what Chet has to say.

**Comment by memeplex** [comment]
FYI (from Chet):

```
This is among several changes that have already been made for the next
version.  Among other things, the mode string is now placed at the
beginning of the last line of a multiline prompt.
```
