### ISSUE TITLE
nbconvert: download included graphics

### ISSUE THREAD

**Issue by MaxNoe** [ipython/ipython#8542]
If i have a notebook that includes internet graphics like this in a Markdown cell:
```
![Image](https://farm6.staticflickr.com/5561/14499025000_c58c919221_z.jpg)
```
I get an error when I try converting the file, because the image is not found.

Is it possible that nbconvert will try to download the file and then include it into the converted notebook, e.g. into a pdff?

**Comment by takluyver** [comment]
I think this is the same as #8471.
