### ISSUE TITLE
Pip installs 3.x only for python2 

### ISSUE THREAD

**Issue by xamvolagis** [ipython/ipython#8544]
After running 
```bash
sudo -H pip install ipython[all]
```
I am told that ipython 3.1.0 is being installed, and this works for python2 (that is, running 
```bash 
ipython2 --version
```
gives  3.1.0,
but running either ipython or ipython3 gives  me the 2.3.0 version, with python3.

Should I just install from github? 
Thanks

**Comment by ccordoba12** [comment]
You need to run

    sudo -H pip3 install ipython[all]

to update IPython in Python 3. Note the **3** at the end of `pip` above.

**Comment by xamvolagis** [comment]
Sorry, I forgot to mention that I have aliased pip3 as pip, so that is the command that I ran.

Just in case, I tried the same thing explicitly as pip3, to no avail.

**Comment by minrk** [comment]
The output of pip tells you where it's installing scripts. You can compare this with the output of `which -a ipython`. I'm guessing there's another location earlier on your PATH. You may also need to do `hash -r` to clear your shell's cache of paths.

**Comment by xamvolagis** [comment]
There is only one copy of ipython on my computer, I removed all versions, (I searched / for "*ipython*" and deleted everything) and reinstalled from pip, but the result is the same: ipython 3.1.0 for python2 but ipython 2.3.0 for python3.

By the way, ipython, ipython2, and ipython3 are placed in  /usr/local/bin by pip

**Comment by Carreau** [comment]
Would by any chance sudo discard the alias ? Try to explicitely use pip3.

**Comment by xamvolagis** [comment]
I tried that, same thing, and anyway, running 

```bash
pip3 list | grep ipython
```
Gives
````bash
ipython (3.1.0)
```
and 

in /usr/local/lib/python3.4 (which is where pip checks for requirements) I have the folder
ipython-3.1.0.dist-info/

**Comment by minrk** [comment]
> There is only one copy of ipython on my computer,

Forgive me, but if you are still getting two versions, this statement cannot be true. When you start the elusive IPython 2, what is `IPython.__file__`? I suspect that `easy-install.pth` is the likely culprit, as it so often is when the wrong package seems to be imported.

**Comment by xamvolagis** [comment]
I understand, I meant that there is only one file named "ipython".
Thanks, this helped me figure it out!

For python3 (ipython2), i got 
'/usr/lib/python3/dist-packages/IPython/__init__.py'

and for python2 (ipython3), I got 
'/usr/local/lib/python2.7/dist-packages/IPython/__init__.pyc'

It turns out, some python packages had been installed in /usr/local/lib, and others in /usr/lib. After deleting /usr/lib/python3/dist-packages/IPython, I can now run ipython3 as expected.

I don't really understand why some packages have been installed in one place and some in the other, I always install packages with sudo. I am also the only person who uses this computer, so it doesn't matter for me, and I use virtualenv's when I need something different. Do you know what I can do to fix/avoid this situation in the future?

Thanks again!

**Comment by minrk** [comment]
/usr/lib means it was installed with `apt-get`, not `pip`. I bet if you look in your various `easy-install.pth` files, you will see `/usr/lib/python3/dist-packages` somewhere in there. That  *definitely* should not be there, and you can edit the file and remove it.

**Comment by xamvolagis** [comment]
Oh, ok. In my 
```/usr/local/lib/python3.4/dist-packages/easy-install.pth```  file, I have both the ```/usr/lib/python3/dist-packages``` and ```/usr/local/lib/python3/dist-packages```, but in my ```/usr/local/lib/python2.7/dist-packages/easy-install.pth```, I have only ```/usr/lib/python2.7/dist-packages```

Should I remove the /usr/lib paths from both?
