### ISSUE TITLE
Ask confirmation when navigate away when kernel running

### ISSUE THREAD

**Issue by cancan101** [ipython/ipython#8546]
Right now this message pop ups if there are unsaved chnges when you try to navigate away on a Notebook:
![image](https://cloud.githubusercontent.com/assets/51059/8243667/1f6ca3a6-15e7-11e5-9bfd-dd42de0a4a02.png)

I suggest doing the same when the kernel is "busy" / running.

**Comment by flying-sheep** [comment]
This can be done via

```js
const CONFIRMATION = 'The Kernel is busy. are you sure you want to navigate away from this page?'
let kernel_busy = false

notebook.kernel.events.on('kernel_idle.Kernel', e => kernel_busy = false)
notebook.kernel.events.on('kernel_busy.Kernel', e => kernel_busy = true);

window.addEventListener("beforeunload", e => {
	if (!kernel_busy) return

	e.returnValue = CONFIRMATION
	return CONFIRMATION
})

**Comment by cancan101** [comment]
It would be cool if these snippets were under some sort of VCS / indexed so that users could find them. Ideally there would be a relatively simple method of turning them on / off.

**Comment by flying-sheep** [comment]
well, there are several semi-decentralized extension repositories as well, but as of now, i hope someone implements this one as default.

**Comment by Carreau** [comment]
Seem like you know how to do it. Pr welcomed.

Envoyé de mon iPhone

**Comment by flying-sheep** [comment]
sure. just tell me where to put it (as it’s [global](https://github.com/jupyter/notebook/blob/cc1f01d21e6c4e533e8b991f3bf7e6f49cdd9f03/notebook/static/notebook/js/notebook.js) behavior but [kernel](https://github.com/jupyter/notebook/blob/cc1f01d21e6c4e533e8b991f3bf7e6f49cdd9f03/notebook/static/services/kernels/kernel.js)-related)

**Comment by Carreau** [comment]
I guess a notebook.js is fine as a notebook will always have a kernel, but a kernel might not be in a notebook.

**Comment by flying-sheep** [comment]
OK. filed it against the current home of the notebook.
