### ISSUE TITLE
pyjsonrpc breaks ipython notebook

### ISSUE THREAD

**Issue by staticfloat** [ipython/ipython#8547]
Hello there, I'm not entirely sure whether this is an ipython thing or a `pyjsonrpc` thing, but I have noticed that after running `import pyjsonrpc`, IPython notebooks become dysfunctional.  Specifically, `print`ing values out to the notebook no longer works, although "returning" variables from notebook cells still prints out their values.

This has been observed on both Windows and Linux.  System configuration follows:

Linux:
```
The version of the notebook server is 3.1.0-cbccb68 and is running on:
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]
```

Windows:
```
The version of the notebook server is 3.0.0-f75fda4 and is running on:
Python 2.7.9 |Anaconda 2.2.0 (64-bit)| (default, Dec 18 2014, 16:57:52) [MSC v.1500 64 bit (AMD64)]
```

Both have `pyjsonrpc 0.0.2` installed.  Here is [an example notebook](https://gist.github.com/staticfloat/29bc2b45a7c07285d4b7) displaying the issue.

**Comment by minrk** [comment]
Importing pyjsonrpc triggers

```python
from gevent.monkey import patch_all; patch_all()
```

which is a *horrible* thing to do on import, since it reliably breaks roughly everything. I don't think there's anything for us to do in IPython to fix this.

**Comment by staticfloat** [comment]
Awesome.  Thanks for tracking that down, Min.  I'll just figure out a way to work around this dependency on my side.

**Comment by minrk** [comment]
I should note: gevent is probably producing warnings that patch_all is firing at a late enough point that it might not work properly, but those warnings are not getting to the notebook for the exact reason that they are trying to warn about.
