### ISSUE TITLE
can't install dev version?

### ISSUE THREAD

**Issue by karissa** [ipython/ipython#8549]
Following instructions on the readme:
```
No distributions at all found for notebook (from ipython==4.0.0-dev)
Storing debug log for failure in /Users/karissa/.pip/pip.log
ipython $ ipython notebook --version
-bash: /Users/karissa/anaconda/bin/ipython: No such file or directory
ipython $ which pip
/Users/karissa/anaconda/bin/pip
```

Is it because I have anaconda installed? I'm not in a conda environment.

**Comment by takluyver** [comment]
Installation is a bit complex while there are several unreleased packages which rely on one another, but if you run `pip install -r requirements.txt .` in the [notebook repo](https://github.com/jupyter/notebook), I think it should get all the pieces you need.

**Comment by Carreau** [comment]
Closing now that 4.x is out.
