### ISSUE TITLE
Python 2.7 Notebook Queue.join() kernel hanging

### ISSUE THREAD

**Issue by crispybacon** [ipython/ipython#8554]
From the Standard Library Reference:
https://docs.python.org/2/library/queue.html
Both the Queue.join() and calling Queue.get() on an empty Queue cause the kernel to hang.
The example code from the tutorial causes this condition.  

###Standard Library Example###

    def worker():
        while True:
            item = q.get()
            do_work(item)
            q.task_done()

    q = Queue()
    for i in range(num_worker_threads):
         t = Thread(target=worker)
         t.daemon = True
         t.start()

    for item in source():
        q.put(item)

    q.join()       # block until all tasks are done

######

###secondary example Queue.join()###

    tasklist = Queue.PriorityQueue()
    tasklist.put('type'), tasklist.put('read'), tasklist.put('demo')
    set(tasklist.queue)
    len(tasklist.queue)
    tasklist.join()
    tasklist.put('exercise')
    tasklist.get(), tasklist,get(), tasklist.get()
    tasklist.done(), tasklist.done(), tasklist.done()
    tasklist.put('read')

######

I assume this is intended for use with multi-threaded applications where a task can be completed via the main process in the queue. However, it is unclear in the documentation exactly how you would go about doing so.  

Jesse Bacon

**Comment by crispybacon** [comment]
The same behavior from a python shell.  Should I put this in as a documentation bug on the main Python project?

**Comment by minrk** [comment]
Queue.get() with no timeout is uninterruptible, so there's nothing that can be done. It is, however, interruptible if you give it a timeout. We have encountered this in our own use, and decided to use `Queue.get(timeout=a ridiculously long time)` instead, which allows to you interrupt the wait with SIGINT. If you want to propose a change to the Python docs, please do.

**Comment by crispybacon** [comment]
That makes sense.  I'll do it like that.  I notice there is no Queue in Python 3.4.  Thank you for the quick response.

**Comment by minrk** [comment]
In Python 3, the `Queue` module has been renamed to `queue`.

**Comment by crispybacon** [comment]
!  I see that now.  It behaves the same.  Thank you.
