### ISSUE TITLE
Add ability to stop Parallel engines from the CLI

### ISSUE THREAD

**Issue by cancan101** [ipython/ipython#8555]
See [SO](http://stackoverflow.com/questions/30930157/stopping-ipcluster-engines-ipython-parallel). @minrk 

Ideally can stop some number of engines started with either of:

```
ipcluster engines --n=8 --daemonize
ipcluster start --n=8 --daemonize
```

Would be helpful for https://github.com/jtriley/StarCluster/issues/538.

**Comment by jakirkham** [comment]
Can you help me understand why `ipcluster stop` doesn't work for this case?

**Comment by cancan101** [comment]
What does `ipcluster stop` if run on the master? Does it shutdown the entire cluster or just the workers?

**Comment by jakirkham** [comment]
The entire cluster.

**Comment by cancan101** [comment]
Ideally there would be some way to stop just the workers.

**Comment by jakirkham** [comment]
What do you intended to accomplish after that? A restart? Or is it just some of the workers? This is what I am trying to understand.

**Comment by cancan101** [comment]
Yes, just to cycle the workers in case there is some issue with those
processes.

**Comment by jakirkham** [comment]
Have you already seen this ( http://ipython.org/ipython-doc/dev/api/generated/IPython.parallel.client.client.html#IPython.parallel.client.client.Client.shutdown )? I don't know if this `restart` feature ever got implemented.

**Comment by cancan101** [comment]
Yes,  but I am looking for a while to do this from the CLI.
