### ISSUE TITLE
When creating folders prompt for folder name

### ISSUE THREAD

**Issue by bluesmoon** [ipython/ipython#8562]
The current behaviour when creating a new folder is to create a new folder called `Untitled` and leave it in the current directory.  This is a problem if you have a large number of people using the system and creating folders at the same time because no one knows who created which of the `Untitled X` folders.

I suggest we do the following:
1. pop up a prompt asking the user for a folder name, and create the new folder with that name.
2. use the same de-duplication logic we have right now to add a number at the end in case of collision
3. Print a message at the top of the screen stating the name of the folder that was just created

**Comment by takluyver** [comment]
Possibly nicer UI, though it might be trickier to implement: when you click 'new folder', add it to the list, making the name a focussed textbox so you can instantly rename it.

**Comment by bluesmoon** [comment]
yes, that would also solve the basic requirement. 

we shouldn't auto-refresh the list until after the rename is done.  My experience with demo'ing IPython to a room full of conference attendees was that in a matter of seconds the directory listing goes from 1 entry to 60 entries and you don't actually know where your entry is.

**Comment by takluyver** [comment]
We could also pin the new item to the top until you're done with making it. I think we already do something similar for uploads.

**Comment by bluesmoon** [comment]
sounds good

**Comment by Carreau** [comment]
(for the record sharing a server is not recommended)

**Comment by gustavoefeiche** [comment]
I am working on this

**Comment by Madhu94** [comment]
@gustavoefeiche I'm guessing this should be tagged as 'notebook' now, and should belong to the notebook repo

**Comment by gustavoefeiche** [comment]
> @gustavoefeiche I'm guessing this should be tagged as 'notebook' now, and should belong to the notebook repo

I have published a [[WIP] pull request](https://github.com/jupyter/notebook/pull/4030) for this issue in the notebook repository. Just waiting for a member to reply :smile:

**Comment by Madhu94** [comment]
Oh, that's great! Thanks for linking it.
