### ISSUE TITLE
Interrupt kernel not working

### ISSUE THREAD

**Issue by cancan101** [ipython/ipython#8563]
I have a kernel that shows "busy" but top does not agree. Further, hitting "Interrupt kernel" shows "interrupting kernel" but then no other indication of success.

There seems to be no way to stop the kernel other than restarting it and no way to further diagnose.

**Comment by takluyver** [comment]
I have also seen kernels get into weird states, though I think we've fixed some bugs in that area. What version of IPython are you on? Is this when you start a kernel, or while it's running code? What platform are you on?

"busy" doesn't necessarily imply it's using a lot of CPU, only that the frontend is waiting for a reply from it. The code running in the kernel can ignore SIGINT; in this case, interrupting the kernel won't do anything.

**Comment by cancan101** [comment]
I am using `IPython 3.1.0`.

The issue that I am having is that there is no way to stop execution short of restarting the kernel.

**Comment by Carreau** [comment]
Update to 3.2 it's an important security-fix release.

**Comment by takluyver** [comment]
That sounds like it's when you've executed code, then. Is this the case with any code? e.g. if you `import time; time.sleep(10)`, can you interrupt it?

Which operating system is this on?

As @Carreau says, please do upgrade to 3.2 promptly.

**Comment by cancan101** [comment]
Upgraded. Thanks.

No, not any code. I have been seeing is sometimes when executing Theano code.

Ubuntu 14.04.1

**Comment by takluyver** [comment]
Theano is the sort of thing that I can imagine might have uninterruptible sections. There's not a lot we can do about that from our side: interrupt means sending SIGINT, and if the kernel ignores it, it will have no effect. You can try talking to the Theano developers about it, I don't know how easy it would be for them to fix.

**Comment by cancan101** [comment]
Is there any way to indicate to the user that the kill either failed or is
still happening / pending?

**Comment by takluyver** [comment]
Well, the fact that the kernel remains busy indicates that it hasn't worked ;-). Unix signals don't include any kind of response, they're a completely fire-and-forget mechanism, so there's no such thing as a 'pending' interrupt.

Most code will either stop almost immediately or not at all, though it's possible for it to handle the signal and do things taking an arbitrarily long time before the kernel reports that it's idle again.

**Comment by cancan101** [comment]
The issue is almost the converse in that I run a cell, see CPU spike and run a while, and then totally stop (ie Theano is no longer actually doing any work). At that point I want kill that cell and re-run it.

I suppose I might have to file this with Theano.

**Comment by cancan101** [comment]
Is there any way to see what line of Python was last executed?

**Comment by takluyver** [comment]
If it's related to Theano specifically, I think you should start with Theano. There might be something we need to change in IPython, but without knowing what Theano's doing that breaks this, it's hard to know what that is.

You can use a debugger to step through the code and see what's happening, or just scatter print statements around to see where it gets to.

**Comment by Carreau** [comment]
Closing as nothing to do on our side. 

Thanks.

**Comment by ahmedrao** [comment]
There was a process named conda.exe in Task manager. I killed that process and I was successfully able to interrupt the kernel
