### ISSUE TITLE
Autoreload error when running a script

### ISSUE THREAD

**Issue by jewfro-cuban** [ipython/ipython#8564]
When running a script I get an error:
```python
Error in callback <bound method AutoreloadMagics.post_execute_hook of <autoreload.AutoreloadMagics object at 0x00000000045E1B70>> (for post_execute):
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\<path_to_env>\lib\site-packages\IPython\extensions\autoreload.py in post_execute_hook(self)
    523         newly_loaded_modules = set(sys.modules) - self.loaded_modules
    524         for modname in newly_loaded_modules:
--> 525             _, pymtime = self._reloader.filename_and_mtime(sys.modules[modname])
    526             if pymtime is not None:
    527                 self._reloader.modules_mtimes[modname] = pymtime

C:\<path_to_env>\lib\site-packages\IPython\extensions\autoreload.py in filename_and_mtime(self, module)
    188
    189         # if hasattr(module, '__name__'):
--> 190         if module.__name__ == '__main__':
    191             # we cannot reload(__main__)
    192             return None, None

AttributeError: 'module' object has no attribute '__name__'
```

I've fixed it locally with:
```python
        if hasattr(module, '__name__'):
            if module.__name__ == '__main__':
                # we cannot reload(__main__)
                return None, None
```

**Comment by Carreau** [comment]
Do you want to make a PR ? I suppose another fix would be `getattr(module, '__name__', None)`. What king of module do not have `__name__` ?

**Comment by jewfro-cuban** [comment]
I haven't tried too much to figure what exactly is the reason but it happened to me in the past as well few times and the above fix let me continue working. Whenever I update to a new release I encounter this behavior so it might be a good idea to make that code part immune to this possibility even if I can't pinpoint the exact reason.
Agreed?

**Comment by Carreau** [comment]
Sure. Are you familiar with git/github ? Do you want to try sending a fix through a Pull-Request ?
(I see from your joining date that you are new, feel free to ask questions on how to do things)

**Comment by jewfro-cuban** [comment]
I've sent a PR:
https://github.com/ipython/ipython/pull/8568

**Comment by Carreau** [comment]
Great ! Will review !

Tip : When you commit, you can also add in the commit message [`fixes #8564`](https://help.github.com/articles/closing-issues-via-commit-messages/#closing-an-issue-in-the-same-repository) , when you push on github it will automatically link the PR (Pull Request) and the target issue. Then when the PR is merged it will auto close the issue !

**Comment by Carreau** [comment]
Also I'm still curious of what kind of module might not have a `__name__` can you share one of the things that make the bug happend ?

**Comment by jewfro-cuban** [comment]
Thanks.
As I've said, at the moment it's hard to pinpoint why it's happening. 
Maybe there's something unusual in my workflow that leads to that.
If I'll have more time I'll try to investigate and extract a sample test script.

**Comment by oceanEngineer** [comment]
I had the same problem with a ipython 4.0.0 and python3.4
I added the hasattr logic above to line 190. It seemed to work, but now it seems like I have new problems. This error is raised from autoreload.
I do not think that I am doing any multicore processing currently, which seems to be an issue with related cases. #7830

[autoreload of __mp_main__ failed: Traceback (most recent call last):
 File "/home/me/.local/lib/python3.4/site-packages/IPython/extensions/autoreload.py", line 248, in check
    superreload(m, reload, self.old_objects)
AttributeError: 'module' object has no attribute '__name__'

**Comment by lukepfister** [comment]
I'm running into this as well-  ipython 4.0.0 and python 3.4.  For what it's worth, I'm installing using Anaconda.

Running this as a script triggers the problem:
    
```python
from scipy.interpolate import interp1d

if __name__ == "__main__":
    print("Hello")
````

My ipython_config.py file contains
```
c.InteractiveShellApp.exec_lines = [
'%load_ext autoreload',
'%autoreload 2',
]
```

The proposed fix seems to work.

**Comment by lukepfister** [comment]
I wound having the same problem described by oceanEngineer.

```python
[autoreload of __mp_main__ failed: Traceback (most recent call last):
  File "/home/luke/software/python/miniconda/envs/nsp/lib/python3.4/site-packages/IPython/extensions/autoreload.py", line 248, in check
    superreload(m, reload, self.old_objects)
AttributeError: 'module' object has no attribute '__name__'
]
```

A simple workaround is to have autoreload skip attempting to reload any modules with module name `__mp__main__`.

So at line 223 of autoreload.py:

```python
 223         for modname in modules:                                                                     
 224             if modname != '__mp_main__':                                                            
 225                 m = sys.modules.get(modname, None)                           
```
and indent the rest as necessary.

**Comment by takluyver** [comment]
#8568 got merged, so I think this is fixed.

**Comment by jewfro-cuban** [comment]
thanks

**Comment by BRubin188** [comment]
I get the same sort of error with my class (Scoring Classes).  I usually axe the Run (pressing the stop button) and the logic works - but this is still bad behavior.  Any insights?  This is using Spyder 3, Python 3

[autoreload of Scoring_Classes failed: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 450, in superreload
    update_generic(old_obj, new_obj)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 387, in update_generic
    update(a, b)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 357, in update_class
    update_instances(old, new)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 317, in update_instances
    update_instances(old, new, obj, visited)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 317, in update_instances
    update_instances(old, new, obj, visited)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 300, in update_instances
    for obj in (obj for obj in objects if id(obj) not in visited):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 300, in <genexpr>
    for obj in (obj for obj in objects if id(obj) not in visited):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 295, in <genexpr>
    if not str(key).startswith('_')
KeyboardInterrupt
