### ISSUE TITLE
Upgraded to 3.2.0 but still seeing 1.2.1

### ISSUE THREAD

**Issue by callmeskywalker** [ipython/ipython#8566]
I have upgraded to 3.2.0 apparently (looking at pip freeze). However when I open IPython or checkout IPython notebooks version I am still seeing 1.2.1. Perhaps this is as it should be? It seemed weird to me when I saw it last night. I am using system Python on Linux Mint. 

![ipython-trouble-0](https://cloud.githubusercontent.com/assets/10120306/8309392/67fe8ee0-1998-11e5-9c63-5e921e22b4be.png)

By the way I am very new to using Github. So if this is type of post is not an issue that should be posted here just let me know where I should go in the future. Thanks!

**Comment by Carreau** [comment]
> By the way I am very new to using Github.

It's ok, no problem it's one of the right place. 

Do you have by any chance IPython installed through apt ? The system IPython might take precedence on your pip-installed one.

**Comment by callmeskywalker** [comment]
That was the issue. I had IPython installed via apt. Also once I removed the IPython packages and ran `ipython notebook` there was a version error with Tornado (for the same reason). Once that was removed both are working. Thanks!

**Comment by rgbkrk** [comment]
Thanks for posting and especially for upgrading, @callmeskywalker!

**Comment by callmeskywalker** [comment]
No problem!

**Comment by Carreau** [comment]
If this is solved for you, usually you can also close the issue on GitHub directly. I'll do it for you.
Have fun with the new version !

**Comment by callmeskywalker** [comment]
Will make sure to close next time. Cheers!
