### ISSUE TITLE
Running "ipython notebook" with Editable/Developer Install Fails on Windows

### ISSUE THREAD

**Issue by tonysimpson** [ipython/ipython#8567]
I'm finding the following issue when running `ipython notebook` in a venv installed with `python setupegg.py develop` or `pip install -e .`

```python
Traceback (most recent call last):
  File "C:\Users\tsimpson\Envs\default\Scripts\ipython-script.py", line 9, in <module>
    load_entry_point('ipython==4.0.0-dev', 'console_scripts', 'ipython')()
  File "c:\work\ipython\IPython\__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\Users\tsimpson\Envs\default\lib\site-packages\traitlets\config\application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "C:\Users\tsimpson\Envs\default\lib\site-packages\traitlets\config\application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\work\ipython\IPython\terminal\ipapp.py", line 302, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "C:\Users\tsimpson\Envs\default\lib\site-packages\traitlets\config\application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\work\ipython\IPython\core\application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "c:\work\ipython\IPython\terminal\ipapp.py", line 297, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "C:\Users\tsimpson\Envs\default\lib\site-packages\traitlets\config\application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\tsimpson\Envs\default\lib\site-packages\traitlets\config\application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "C:\Users\tsimpson\Envs\default\lib\site-packages\traitlets\config\application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\tsimpson\Envs\default\lib\site-packages\traitlets\config\application.py", line 418, in initialize_subcommand
    subapp = import_item(subapp)
  File "C:\Users\tsimpson\Envs\default\lib\site-packages\ipython_genutils\importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named 'notebook'
```
I'm aware that I'm probably doing something wrong, maybe to do with setuptools "extras" I read all the documentation I could find (very little) but couldn't work out if there is some magic I'm missing, I do know "pip install -e . ipython[notebook]" doesn't do anything sensible.

I've read the dev pages and tried boot2docker as recommended (https://github.com/ipython/ipython/wiki/Dev%3A-boot2docker) but found a bug in boot2docker, after some debugging it turns out I'm supposed to enable a CPU feature in my BIOS (VT-x)  https://github.com/docker/docker/issues/12149 to get docker working - I feel my sanity leaving.

I will boot into my Linux partition to see if it works as describe on Linux. If it's just Windows specific I will consider investigating further myself.

If anyone knows anything that might help me or save me time in investigating I'd really appreciate it.

**Comment by Carreau** [comment]
On master the notebook is not more part of IPython, and is [it's own package](github.com/jupyter/notebook) with it's own dependencies that you will have to install in the venv (cf requiirements.txt in each repos).

**Comment by tonysimpson** [comment]
Understood, seems I'm a little behind the times :)

I want to get to a state where I have a working development environment for ipython + jupyter. Following the documentation linked from the IPython website (https://github.com/ipython/ipython/wiki/Dev:-Index) didn't get me to that state, this is a valid issue because it still refers to running `ipython notebook` etc. and I didn't come across any mention of jupyter.

I would like to help update the documentation if that is what is required.

I'm currently working on getting Jupyter working as expected on windows and some encountering some issues.

How should we proceed?
  1. Reopen this issue and we can close it once the documentation has been fixed regarding development setup on windows and clarity around Jupyter split in the IPython Dev docs;
  2. Raise new separate issues for the above.

**Comment by takluyver** [comment]
Are you looking to develop *using* Jupyter/IPython, or do you want to work on the project itself?

If you just want to use it, I recommend that you install the stable version (3.2) for now, following the instructions here: http://ipython.org/install.html . There are no major new features in the development version, just a lot of reorganisation to split up the project into smaller parts.

If you want to work on the notebook, look at the instructions in the [jupyter/notebook README](https://github.com/jupyter/notebook#jupyter-notebook) to get set up.

**Comment by tonysimpson** [comment]
I would like to work on the project itself.

Can we reopen this issue pending the following.

Suggested resolution
------

The documentation at [jupyter/notebook README](https://github.com/jupyter/notebook#jupyter-notebook)  is missing the `gulp css` and `gulp js` steps and would benefit from some note for Windows users on setting up msysgit and node, linking to the ["The Big Split"](https://blog.jupyter.org/2015/04/15/the-big-split/) blog post would be helpful.

The documentation at [Ipython README](https://github.com/ipython/ipython/blob/master/README.rst) needs updating. everything from "Instant running" down is now outdated and the code sections no longer work. As far as I understand it would make sense update the readme to point to the jupyter notebook readme and project page for now.

*I can make pull requests for the above if that would help.*

Nice to have
-----

It would be helpful to have some more documentation on what the plan is for the split and the roadmap going forward. Without this information it's time consuming to decide if something is a bug or just unfinished and needing more work. 

Context
------

My initial goal was to see if I could use HTML5's getusermedia to capture mic audio and camera video in the notebook to make it really easy to play with signal processing. I thought this would be a 1/2 day task but immediately found what looked like a bug in `IPython.display.Javascript`. While trying to setup a dev environment to investigate I came across this issue of the current documentation being out of date and other bugs when running Jupyter on windows.

I would like to help improve Jupyter. The R&D team I used to lead made extensive use of IPython Notebook, we had a sophisticated analysis and client report generation framework built on top of the notebook which was awesome. Currently I find myself with a lot of free time so I'd like to give back.

I will get round to ask on the googlegroup if there is anything I can help but at the moment I'm reading though all the documentation I can find.

**Comment by takluyver** [comment]
I'd rather not reopen this issue, because it would have to be rewritten in terms of documentation problems. You can open one or more new issues if you like, or just start making pull requests. We know that the documentation needs updating. We've been doing quite a bit of work on the docs ([overview page here](http://jupyter.readthedocs.org/en/latest/)), but the READMEs can easily be forgotten.

**Comment by takluyver** [comment]
I've removed the outdated info from this repo's README in #8574
