### ISSUE TITLE
protocol documentation bug for kernel_info_reply?

### ISSUE THREAD

**Issue by stevengj** [ipython/ipython#8571]
The [protocol documentation](http://ipython.org/ipython-doc/dev/development/messaging.html) states that `kernel_info_reply` should include:
```
 # Extension without the dot, e.g. 'py'
    'file_extension': str,
```
However, your [ipkernel implementation](https://github.com/ipython/ipykernel/blob/a4c44ed497ff30c8602e7d89d8156a67d87e8574/ipykernel/ipkernel.py#L110) passes `'file_extension': '.py'`, which includes the dot.

I'm guessing that your implementation is correct, so does that mean that the documentation is wrong?

**Comment by stevengj** [comment]
Also, the documentation refers to the *top level 'language' field*, which no longer exists; I assume that you mean the `language_info.name` field.

**Comment by takluyver** [comment]
The extension is just because that URL is not the latest version of that document - it now lives here:

http://jupyter-client.readthedocs.org/en/latest/messaging.html#kernel-info

I'll make sure the old URL points to that.

The 'top level' issue is still relevant, thanks.

**Comment by stevengj** [comment]
Thanks; I was so used to going to the old URL that it didn't occur to me that it might have moved.

**Comment by stevengj** [comment]
Note that the new docs seem rather hard to find.  Googling any of "jupyter protocol" or "messaging in jupyter" or "jupyter documentation" don't find it, nor is it linked to from https://ipython.org/ipython-doc/dev/development/messaging.html

**Comment by Carreau** [comment]
The top level documentation that link all the rest together has not yet been deployed so google does not index it. And we haven't yet migrated IPython docs. We are working on that for the next two week (plus SciPy).

**Comment by Carreau** [comment]
New documentation should be online now. Closing.
