### ISSUE TITLE
"No kernel" message when connecting to remote notebook server through https

### ISSUE THREAD

**Issue by pmsppinto** [ipython/ipython#8576]
I setup a remote ipython notebook server (password protected) serving notebooks through http. Everything is working fine. The next step was to create a SSL certificate and add it to "c.NotebookApp.certfile=..." in ipython_notebook_config.py. I connected to the server through https and at first sight everything looks ok, but..

On opening a notebook I just get a "connecting to kernel" message before changing to "no kernel" after a little bit. On the console log I see that the "kernel started". Only way around for me is to comment out the certificate line and connect through http (not https).

I already mentioned this on gitter (another user is having the same problem) but not obvious solutions around there.

**Comment by minrk** [comment]
What browser are you using?

**Comment by pmsppinto** [comment]
Safari on OSX Yosemite. 

The notebook server is running on Ubuntu, everything installed from pip, IPython v3.2.

I didn't try other browsers. I'm currently on my phone, can try something else later.

**Comment by takluyver** [comment]
IIRC there was some problem with secure websockets on Safari, which could probably cause the symptoms you see.

**Comment by minrk** [comment]
Safari refuses to connect websockets to untrusted (self-signed) certificates. To use a self-signed cert with Safari, you must trust it explicitly by adding it to your keychain, so that you never have to click through a 'trust this site' confirmation when you start connecting.

**Comment by pmsppinto** [comment]
Ok that solved it! Just added the certificate to the keychain and now it connects to the kernel. Thanks

**Comment by pmsppinto** [comment]
Just wonder if there is way to make it more explicit what the problem is. Can IPython (client side) identify that a web socket is not being connected to? Or is that what the "no kernel" message is saying?
