### ISSUE TITLE
Cannot import pylab after newest update

### ISSUE THREAD

**Issue by lengelhardt** [ipython/ipython#8577]
I just updated to the newest version of ipython (using anaconda on a mac), and now I can't import pylab.  Both "%pylab inline" and "from pylab import *" give me the following error message in an ipython notebook:

ImportError: dlopen(/Users/larryengelhardt/anaconda/lib/python2.7/site-packages/matplotlib/_png.so, 2): Library not loaded: @loader_path/../../../libpng15.15.dylib
  Referenced from: /Users/larryengelhardt/anaconda/lib/python2.7/site-packages/matplotlib/_png.so
  Reason: image not found

**Comment by Carreau** [comment]
Try to upgrade matplotlib, the traceback seem to come from here. 
And also don't use `%pylab` it is an historical artifact. Use `%matplotlib inline`.

**Comment by lengelhardt** [comment]
That did it.  Thanks!

**Comment by Carreau** [comment]
Great !
