### ISSUE TITLE
Notebook CSS table

### ISSUE THREAD

**Issue by ghost** [ipython/ipython#8581]
Hello, 
I am trying to apply a CSS style to a table but it looks like it cannot override the ".rendered_html table" properties.

As you can see in the image below, the table shows two black borders (one around the table with the radius and a second one without the radius):

![image](https://cloud.githubusercontent.com/assets/5657134/8366768/bd96279a-1b65-11e5-9c19-ac34a2e86956.png)

I can apply some magic (%%html) and remove ALL borders but so far it hasn't been possible get rid of the black square (the border without radius). 

NOTE: The second row in the image corresponds to the CSS table specifications.

I will appreciate any help.

Regards!

**Comment by jakobgager** [comment]
IIRC you have to unset the borders for all table elements, i.e. tr, td, th, table
However I'm not an CSS expert maybe there is a more elegant way.

**Comment by Lijantropique** [comment]
Hello,

Thanks for the reply.
I tried to do it from css and it is not working (tried also using id and classes).
The only option is %%html but thatnwould remove ALL the borders for ALL the tables in the nb.

Thanks!

**Comment by Carreau** [comment]
This seem to be know [limitation](http://stackoverflow.com/questions/628301/css3s-border-radius-property-and-border-collapsecollapse-dont-mix-how-can-i) you have to use more restrictive selector.

**Comment by jakobgager** [comment]
I did it like
```python
from IPython.display import HTML
HTML('<table style="border: 0"><tr style="border: 0"><td style="border: 0">\
        Cell 1</td><td style="border: 0">Cell 2</td></tr></table>')
```
which works fine for me and should be identical to pure CSS.

**Comment by Lijantropique** [comment]
After reading and trying out the solutions in Carreau's link, I finally got a CSS that is able of accomplishing what I was looking for:

table{
	border-style: hidden !important;
	border-collapse: collapse;
	background-color: #acd1b2;
	float: left;
	margin-right: 10px;
	border-radius: 35px !important;
	border-bottom-right-radius: 35px !important;
	border-bottom-left-radius: 15px !important;
	box-shadow: 0 0 0 1px #666 !important;
}

Thank you all!
