### ISSUE TITLE
Template path initialization doesn't handle unicode strings

### ISSUE THREAD

**Issue by tomdz** [ipython/ipython#8582]
We package IPython as a .par file and for some reason this makes the `_template_path` a unicode string. Unfortunately, this breaks `template_path` initialization in 3.x since that only checks for ascii strings (https://github.com/ipython/ipython/blob/8b0eef4cb37a85b8a35784f82799352188d90ca3/IPython/html/notebookapp.py#L157). The line should instead check whether `_template_path` is not a list.

**Comment by minrk** [comment]
should be fixed by jupyter/notebook#177
