### ISSUE TITLE
two lines for one return carriage in python cell

### ISSUE THREAD

**Issue by damlatien** [ipython/ipython#8585]
Hi all, 
I have an issue with using python cells: every time I press enter I have two lines adding instead of just one. How can I change this behaviour ?
Thanks

**Comment by Carreau** [comment]
Which version of IPython ? Do you have extensions ?

**Comment by damlatien** [comment]
I have IPython version 3.1.0. I will try to install 3.2 and check if this changes something.

**Comment by Carreau** [comment]
Hum... because this look like  a bug we had in 3.0 ...

**Comment by damlatien** [comment]
I have just installed ipython 3.2, and this is the same: "The version of the notebook server is 3.2.0-8b0eef4"

**Comment by Carreau** [comment]
Can you try in an icognito-window and/or new profile ? What does the JS console say ? which browser / os ?

**Comment by damlatien** [comment]
I use Firefox 38.0 on Kubuntu 15.04
Edit: I found that the problem disappears when I disable a firefox extension (pentadactyl)

**Comment by damlatien** [comment]
You can close this issue, as it is only related to the use of pentadactyl.
Thanks for your help
