### ISSUE TITLE
 How can I get back the progress of notebook after reloading web-page carelessly 

### ISSUE THREAD

**Issue by Coldmooon** [ipython/ipython#8590]
I've been using ipython-notebook to do deep learning. During the running of the code ( training ), I don't stay at the front of my computer and save the notebook  frequently. So, the notebook is usually saved at the end of work. 

The problem is that if I reload notebook's page carelessly when the code is still in running, all of new results are just gone. I don't know how to reconnect to the missing session while the code is still running in the background.

Can anyone help me? Thanks in advance for any help you are able to provide.~!

**Comment by Carreau** [comment]
Hi,

if you are doing something like

```
somethings
#long computation
a = 1
```
then accidentally reload, then later you can still do `print(a)` to see the value of `a`. There is nothing specific to do for that. Though the ids that binds what you want to display are gone when you reload, to 

```
sleep(60)
print(a) 
```

if you reload while it sleeps, there is no way to get what `print(a)` would have done, except  redoing it. 
We are working on that, it will take some time, and it will be automatic once it works. 

In the meantime, separate long computation cell from graphing/plotting/printting, and store intermediate results. 

You then "just" have minimal work to redo if reloading. 

When you reload and something is still happening, you should get a warning asking you if you are sure. 
So this should not happend to you, tell us if this is not the case.

**Comment by Coldmooon** [comment]
Thank you for your suggestions which are very helpful. I'm expecting the next version of ipython-notebook.
