### ISSUE TITLE
%pylab inline  causes dill.dump_session() to raise PicklingError 

### ISSUE THREAD

**Issue by ptocca** [ipython/ipython#8595]
Being able to dump and restore a session is a key feature.
One way of doing that with python is to use dump_session() in the dill package.

In an IPython Notebook
```python
%pylab inline
import dill
dill.dump_session('test.pkl')
```
results in the following
```
PicklingError                             Traceback (most recent call last)
<ipython-input-2-ea6cb5748b9f> in <module>()
----> 1 dill.dump_session('test.pkl')

... long traceback omitted...

C:\WinPython-64bit-3.4.3.3\python-3.4.3.amd64\lib\pickle.py in save_global(self, obj, name)
    918                 raise PicklingError(
    919                     "Can't pickle %r: it's not the same object as %s.%s" %
--> 920                     (obj, module_name, name))
    921 
    922         if self.proto >= 2:

PicklingError: Can't pickle <class 'numpy.float64'>: it's not the same object as numpy.float64
```

Using instead
```python
import numpy as np
%matplotlib inline
``` 
does not result in the issue, though.

There are discussions on this exception with `dill` (in other contexts) suggesting that it is because of a messed-up environment with multiple `numpy` versions in the path, but why would the latter example work then?

The version of the notebook server is 3.1.0-cbccb68 and is running on:
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)]

Thank you

Paolo

**Comment by Carreau** [comment]
I can't even `dump_session` if I import numpy... could it be due to recent numpy about `np.int`/`np.int64` ?

**Comment by Carreau** [comment]
Closing as anyway we don't really encourage using `%pylab inline`, though if someone get a fix it will probably be accepted.
