### ISSUE TITLE
'%precision %e 3' formats all results in engineering notation but with a 3 after the exponential

### ISSUE THREAD

**Issue by Bercio** [ipython/ipython#8596]
es: 
    $ %precision %e 3
    $ 50/3
       1.666667e+01 3
and so on. happens with other numbers too obviously.
Both in Ipython 2 and 3, version 2.3.0, ubuntu 14.10, gnome-terminal.

**Comment by Carreau** [comment]
That's how **Python** behave:

```
>>> '%e hi there' % (50/3)
'1.600000e+01 hi there'
```

Here using `Hi there` instead of 3, you are just doing string formatting.

What you want is the following:

```
>>> '%.2e' % (50/3)
'1.60e+01'
```

So with the precision magic (which is just syntactic sugar)

```
In [1]: %precision %.2e
Out[1]: '%.2e'

In [2]: 5/3
Out[2]: 1.67e+00
```

**Comment by Bercio** [comment]
mmh shouldn't an exception be raised for non-formatting string arguments to
the precision magic ?
For example a ValueError is raised when you pass a non formatting string
not in front of the %e argument.


Lorenzo

**Comment by Carreau** [comment]
> For example a ValueError is raised when you pass a non formatting string
> not in front of the %e argument.

Not quite sure what this mean, too many negation. 

Anything you pass to %precision will be use a string formatter:

```
In [1]: %precision %%c [ %012.7f ] %%$
Out[1]: '%%c [ %012.7f ] %%$'

In [2]: 127/9
Out[2]: %c [ 0014.1111111 ] %$
```

We 'just' pass the string you give to `%precision` to a formatter (after checking that it can actually format one number).

I'm not quite sure why we should raise on some formatting string that are valid.
