### ISSUE TITLE
Volume normalization in IPython.display.Audio should be optional

### ISSUE THREAD

**Issue by mmcdan** [ipython/ipython#8608]
I am manipulating audio using numpy with IPython Notebook and want to use IPython.display.Audio for listening to the numpy arrays. Unfortunately, auto-normalization tampers with the results. Example:

```
# Generate a sound
import IPython
import numpy as np
framerate = 44100
t = np.linspace(0,5,framerate*5)
tone = np.sin(2*np.pi*220*t)
antitone = np.sin(2*np.pi*220*t + np.pi)
IPython.display.Audio(tone+antitone, rate=framerate)
```

Adding a sin wav to itself shifted by 180 deg should give total silence. Instead, auto-normalization amplifies the floating point errors. The problem is in the IPython.lib.display.Audio _make_wav method, which always normalizes the numpy array(see 'scaled' variable). I think that we should have a normalize keyword argument, so that Audio can be used for audio analysis. Something like:

```
Audio(tone+antitone, rate=framerate, normalize=False)
```

**Comment by takluyver** [comment]
That seems reasonable. Do you want to make a PR?

**Comment by mmcdan** [comment]
Sure, will make a PR in the near future.

**Comment by dsblank** [comment]
I am also interested in making a couple of enhancements to Audio:

1. Consider passing in a `maxvalue` value rather than a `normalize` flag. That way, you can still normalize, but to a different value. In the antitone example above, maxvalue would be 1.
2. Adding a `save` method to Audio.

I have code that does the first.

The second can accomplished with:

```python
def save_wav(data, rate, filename):
    audio = Audio(data, rate=rate)
    with open(filename, "wb") as fp:
        fp.write(audio.data)
```
but would be handy to have as a defined method on Audio:

```python
    def save(self, filename):
        with open(filename, "wb") as fp:
            fp.write(self.data)
```

**Comment by drscotthawley** [comment]
@mmcdan @takluyver : Any progress on this?   
The Audio object is distorting my output, even adding a DC offset.  
Have been searching for a while for a bug in my code, before finding this issue. 

Plotting the waveform and listening to it via Audio is totally different -- 
You can directly compare the difference between downloading from Audio, vs. saving via librosa.
How can we get Audio to just leave the signal unaltered?

**Comment by drscotthawley** [comment]
Woops, missed a spot. New PR.

**Comment by musicnerd** [comment]
According to the most recent 'read the docs' there is no 'norm' parameter. (https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#module-IPython.display)  I would really like to have this feature.

**Comment by matangover** [comment]
For anyone looking for a simple workaround (until #11161 is done), to prevent IPython from boosting the volume of quiet clips, you can simply set one sample to 1 (if you're working with floating-point audio), e.g.

```python
import numpy as np
import IPython

# Example audio - A440 for one second
some_audio = np.sin(2 * np.pi * 440 * np.linspace(0, 1, 44100)) / 8
# Hack to disable IPython audio normalization.
some_audio[-1] = 1 

IPython.display.Audio(some_audio, rate=44100)
```
This adds a noticeable click at the end of the clip but at least it doesn't normalize the amplitude.

**Comment by radkoff** [comment]
I'm still experiencing this bug, and I believe I'm using the latest version. Maybe I should open a new issue.

```
jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.1.3
qtconsole        : 4.7.6
ipython          : 7.26.0
ipykernel        : 6.2.0
jupyter client   : 6.1.7
jupyter lab      : not installed
nbconvert        : 5.6.1
ipywidgets       : 7.6.3
nbformat         : 5.0.7
traitlets        : 4.3.3
```

`IPython.__version__` gives me 7.26.0

I'm on `macOS 11.15.2`, using firefox, starting my server with `jupyter notebook`
