### ISSUE TITLE
Anaconda Python notebook dictionary error

### ISSUE THREAD

**Issue by hanbeibei** [ipython/ipython#8609]
Hi

In Anaconda Python notebook 3.4.3(newest), when i execute D = dict(zip(['a','b','c'],[1,2,3])), but got the following error:

```
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)
<ipython-input-101-3b1723a29871> in <module>()
----> 1 D = dict(zip(['a','b','c'],[1,2,3]))
      2 D

TypeError: 'dict' object is not callable
```

but in qtconsole, this statement is valid...

another bug in notebook:

```
for k in D.keys(): print(k, D[k])

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-103-1e7826ecf349> in <module>()
----> 1 for k in D.keys():
      2     print(k, D[k])

AttributeError: 'list' object has no attribute 'keys'
```

also, in qtconsole, it is valid..

I don't know other folks had ever encountered this problem.

Thanks.
Oliver

**Comment by takluyver** [comment]
The first error means that you've previously made a variable called `dict`, and it's seeing that instead of the built-in dict function.

The second error means that D is a list instead of a dictionary.

It's highly unlikely that either of these is caused by the notebook.
