### ISSUE TITLE
HBox and VBox cannot be subclassed

### ISSUE THREAD

**Issue by mwcraig** [ipython/ipython#8610]
When I try to subclass either ``widgets.HBox`` or `widgets.VBox`` I get an error:

```python
from IPython.html import widgets
class Foo(widgets.HBox):
    pass

TypeError: Error when calling the metaclass bases
    function() argument 1 must be code, not str
```

A notebook with `sys_info` and the code to reproduce is at http://nbviewer.ipython.org/gist/mwcraig/5f3097defffe472ba2d4

In my case it actually turns out to be easier to subclass ``FlexBox`` directly anyway, but thought I'd report it.

**Comment by jdfreder** [comment]
Hi Matt,

Both HBox and VBox are helper functions.  Sorry, I know this is misleading.  You can see their source code here: https://github.com/ipython/ipywidgets/blob/master/ipywidgets/widgets/widget_box.py#L70-L78 .

You can inherit from flexbox and pass the kwarg orientation = 'vertical' or 'horizontal' for the effect you are looking for..

**Comment by mwcraig** [comment]
Thanks, just updated the wiki at https://github.com/ipython/ipython/wiki/IPython-3.0-comm-and-widget-migration-document to clarify.

**Comment by jdfreder** [comment]
Ah great!  Thanks for doing that! : )
