### ISSUE TITLE
IPython Notebook Server running in Ubuntu Virtual Box

### ISSUE THREAD

**Issue by dbl001** [ipython/ipython#8612]
I'm trying to access an IPython guest Notebook server from my OS X 10.10.3  host browser (Firefox https://127.0.0.1/8001) where the guest is running Ubuntu 14.04.  

In one of my virtual boxes (e.g. 32 bit Spark) it works, in my 'nupic' 64 bit instance it doesn't work.
In the Spark instance there is a port forwarding statement in the Vagrant file:

ipythonPort = 8001 # Ipython port to forward (also set in IPython notebook config)
...
master.vm.network :forwarded_port, host: ipythonPort, guest: ipythonPort, auto_correct: true # IPython port (set in notebook config)

When I tried adding a similar statement (with a different port) in the 'nupic' Vagrant file, I still couldn't access the notebook server from my browser.

Enabling debug log messages in the iPython notebook server isn't showing my connection attempts.

**Comment by minrk** [comment]
I assume this is entirely a vagrant configuration issue. Can you get a port forwarded to a basic service that doesn't involve IPython?

**Comment by dbl001** [comment]
Is there a log info stream which shows all the HTTPS connection requests submitted to the ipython notebook server?
I set the the debug level but it didn’t show my GET requests.

**Comment by minrk** [comment]
@dbl001 that's why I suspect it's a vagrant issue. Yes, any requests that actually reach the notebook server will be logged, which is why I suspect you need to debug your vagrant network setup.  I would start this by creating a toy application that doesn't involve IPython and trying to connect to it. Once you are certain that you can connect to a particular port in the app in vagrant, then try it with IPython.

**Comment by karenyyng** [comment]
@dbl001 I was also setting up my virtual box running Spark with IPython Notebook. It did not work until I followed the instructions from [this Hortonworks post](https://hortonworks.com/hadoop-tutorial/using-ipython-notebook-with-apache-spark/):

> Within the this newly minted IPython profile for pyspark found at `~/.ipython/profile_pyspark/`, edit the file `ipython_notebook_config.py` with text editor like nano and change the values in the file to resemble values below:

> `c.NotebookApp.ip = '*'` <- I think this is the line that made the notebook port forwarding working for me.

Good luck.

**Comment by dbl001** [comment]
Thanks!  Did you do any port forwarding statements in your Vagrant file?  When I tried this, I got curious errors trying to launch the virtual box.

**Comment by dbl001** [comment]
I don’t have a ‘profile_pyspark’ file:
E.g. -
David-Laxers-MacBook-Pro:Downloads davidlaxer$ sudo find ~ -name profile_pyspark -ls
Password:

$

**Comment by karenyyng** [comment]
@dbl001 
In my setup I did not use Vagrant.
I had to manually configure port forwarding settings from the GUI of virtualbox. This [post](http://www.howtogeek.com/122641/how-to-forward-ports-to-a-virtual-machine-and-use-it-as-a-server/) tells you the buttons to click.
But basically, 

a. navigate to the settings of the virtual machine image that vagrant controls using the virtualbox GUI
b. click on the `network` pane, uncollapse the `advanced` setting then click on `Port Forwarding`  
c. make sure that you have set the ports correctly to forward your Mac requests to the ports where IPython Notebook is running on virtualbox 

I imagine you can configure the same settings via the vagrant file but I have not played with vagrant that much.

If you want to use PySpark via the IPython Notebook interface, you have to configure a IPython profile called `pyspark` so the SparkContext is initialized correctly when you start the IPython Notebook. [This](http://ramhiser.com/2015/02/01/configuring-ipython-notebook-support-for-pyspark/) is a good post for guiding you how to do so. 

Lastly, I had to add the line `c.NotebookApp.ip = '*' ` that I mentioned earlier in `~/.ipython/profile_pyspark/ipython_notebook_config.py`.

**Comment by Carreau** [comment]
Hi, 

This issue has been quiet for almost a year, and I don't think there is anything we can do. It has been marked as no-action, and I'm going to close it to attempt to reduce the number of opened issue. Feel free to reopen if needed. 

Thanks.
