### ISSUE TITLE
Static contributors page in docs seems very out-of-date

### ISSUE THREAD

**Issue by eteq** [ipython/ipython#8613]
I noticed the following static page on the dev docs: https://ipython.org/ipython-doc/dev/about/credits.html, which appears to be very out-of-date (@jdfreder is not on the list, and I am not in the contributors list, even though I see some contributions in the log back to 2010). @jdfreder suggested I mention this here - apparently it may have been replaced by something else?

**Comment by minrk** [comment]
Oh, yikes. I didn't know we even had that page. The page we keep up to date is the [GitHub-stats page](http://ipython.org/ipython-doc/3/whatsnew/github-stats-3.html#issues-closed-in-3-0).

cc @fperez and @ellisonbg for whether we should still have a credits page in the sphinx docs. Perhaps this is the kind of content that should move out of dev docs and onto jupyter.org?

**Comment by takluyver** [comment]
We credit contributors in the release notes of each release. Maybe that's easier than trying to keep one big list up to date?
