### ISSUE TITLE
Setting title of Accordion changes whether Accordion is open

### ISSUE THREAD

**Issue by mwcraig** [ipython/ipython#8615]
In IPython 3.2/Python 3.4/Chrome 43.0.2357.130 , if I create an `Accordion` in one cell, then set its title in another cell, the  `Accordion` changes from open to closed.

A notebook to reproduce is at: http://nbviewer.ipython.org/gist/mwcraig/f026324a1749b00087ba

As mentioned in the notebook, `set_title` needs to be in a separate cell from `display` to expose the bug.

**Comment by mwcraig** [comment]
@jdfreder -- any suggestions for working around this or #8616 ?

**Comment by mwcraig** [comment]
Not sure this should stay open...it does still occur even after ipython/ipywidgets#131

**Comment by jdfreder** [comment]
It shouldn't stay open in ipython/ipython - I'll move it.
