### ISSUE TITLE
use js version of nbagg figures for display

### ISSUE THREAD

**Issue by tacaswell** [ipython/ipython#8617]
The display system shows a png of figure objects, even if they are live nbagg figures and can have a live display.

This may require changes on the mpl side as well.

attn @pelson

**Comment by takluyver** [comment]
I think this is a question of priority between:

1. the `_repr_foo_` methods on an object vs formatters set in our global registry.
2. different mimetypes in the same display message

@minrk will probably know more about this.

**Comment by minrk** [comment]
`%matplotlib anything` will register the figure formatters for inline display when a figure is displayed explicitly or via the displayhook. Perhaps that's inappropriate with the nbagg backend. @tacaswell Can you display an nbagg figure multiple times on one page?

**Comment by tacaswell** [comment]
I don't know enough about how coms work to answer that question.

**Comment by minrk** [comment]
What would you like to happen if a figure is passed to `display` or the displayhook? Text representation? Or another instance of the figure on the page?

**Comment by pelson** [comment]
> Can you display an nbagg figure multiple times on one page?

Yes.

**Comment by tacaswell** [comment]
A second instance in the page, the use case i have in mind is if you some
how over write the out put cell that has your plot and i would like to do

Display(plt.figure(5))

And get the figure back on the page.

**Comment by minrk** [comment]
ok. In that case, we should register a formatter for figures with:

```python
ipython_formatter = get_ipython().display_formatter.ipython_formatter
ipython_formatter.for_type(Figure, func_that_shows_figure)
```

That should take higher priority than any png/etc. formatters that we register.

What's the MPL call that would redisplay the figure?

**Comment by tacaswell** [comment]
`fig.canvas.manager.reshow()`

**Comment by tacaswell** [comment]
or I guess `lambda fig: fig.canvas.manager.reshow()`

**Comment by minrk** [comment]
[this notebook](http://nbviewer.ipython.org/gist/minrk/fec86818f69029766991) should illustrate it (not that you can really tell that the two plots were interactive). It seems like this is something we should be doing in IPython, so I'll add it to the matplotlib enable bits.

**Comment by tacaswell** [comment]
That works, but now we have a pathological case where if you put

```python
fig, ax = plt.subplots()
fig
```

in a cell you get the figure twice (once from the implicit `show` call that is part of setting the figure manager up and once from the reshow called by the implicit display).

**Comment by minrk** [comment]
That's true. The inline backend currently has this problem as well. #8622 enables reshow on display for nbagg.

We have some tracking code in the inline backend to avoid double display on `plt.show()`. This relies on a post_execute hook which displays any figures that haven't been explicitly displayed. The nbagg backend could do similar bookkeeping, I suppose. At what time does the implicit show get called?

**Comment by tacaswell** [comment]
It is in slightly different places in 1.4.3 and master, but given that nbagg only works with IPython, I have no problem with using the same post_execute hook pattern.  Should that live on the IPython side or the mpl side?
