### ISSUE TITLE
BUG: Shortcuts swallowed on Mac in iPython notebook's terminal

### ISSUE THREAD

**Issue by jakirkham** [ipython/ipython#8623]
When trying to using shortcuts on Mac using iPython notebook's terminal, they appear not to work as intended e.g. (copy `⌘+C` and paste `⌘+V`). Generally, they end up being swallowed with no effect.

**Comment by Carreau** [comment]
We are "Just" using terminado library for that. This is a terminado limitation, that would need to be reported upstream. This is also likely due to term.js on which we have no power.

**Comment by jakirkham** [comment]
Thanks for the info. Moved upstream.

**Comment by takluyver** [comment]
@Carreau for issues which are clearly frontend related, it may be better to just talk about term.js - I've just closed @jakirkham's issue reports on terminado - I imagine this is quite frustrating for him/her. We depend on terminado for the pty backend, and term.js for the terminal emulator frontend.

**Comment by jakirkham** [comment]
In @Carreau's defense, he mentioned both terminado and term.js. Knowing little about how this is put together, I simply tried to go to the next thing upstream. Sorry to cause you, @takluyver, trouble.

**Comment by Carreau** [comment]
Don't worry, @takluyver is a feet from me and can slap me when I don't behave. I should have done my job better.

**Comment by jakirkham** [comment]
No worries.

Honestly, I didn't know about this terminal feature in the iPython notebook until very recently. It has been extremely helpful when interacting with Docker containers running an iPython Notebook server or running remotely.

**Comment by takluyver** [comment]
It wasn't there until quite recently, so I think you can be forgiven for not knowing about it ;-)
