### ISSUE TITLE
ipython 1.2.1 without pyzmq

### ISSUE THREAD

**Issue by fairsky66** [ipython/ipython#8627]
Hi there,

How can i install pyzmq for ipython 1.2.1 on a server where I have no root access?

Cheers,

**Comment by Carreau** [comment]
If you are trying to install pyzmq, then it is a pyzmq question. IPython 1.2.1 is not stable anymore, we released 3.2 a few weeks a go, and are about to release 4.0.

You can try to `pip install pyzmq --user`

**Comment by fairsky66** [comment]
Yes, I did that command your provided.
However, the problem I got is 'gcc: permission denied'

so, is there any solution to install pyzmq without gcc? any binary version for centos 5.4 on my shared host

**Comment by minrk** [comment]
You have to compile pyzmq, but you don't have to compile it on the destination machine. On another, sufficiently similar (same OS, Python, etc.) machine, you can make a wheel with `pip wheel pyzmq`, then distribute that wheel to the destination.

**Comment by fairsky66** [comment]
unfortunately, i didn't figure out how to install pyzmq without gcc through pip install or pip wheel.
Either will invoke gcc compiler on my shared host.

**Comment by takluyver** [comment]
On 12 July 2015 at 08:54, Sheng Li <notifications@github.com> wrote:

> unfortunately, i didn't figure out how to install pyzmq without gcc
> through pip install or pip wheel.
> Either will invoke gcc compiler on my shared host.
>
You need to run pip wheel on another machine with the same operating system
where you do have a compiler. That will make a binary package that you can
then install on the system without a compiler.

**Comment by fairsky66** [comment]
okay, i understood now. I will try it in a local vm.
thank you for the clarifying.
