### ISSUE TITLE
Ipython Notebook Does Not Allow Directory Navigation

### ISSUE THREAD

**Issue by kskk02** [ipython/ipython#8630]
I newly Installed Ipython Notebook on Ubuntu 14.04.01 and It doesnt allow me to navigate to any subdirectories from where I executed the ipython notebook command. I do have many subdirectories per the picture and as you can see none of them are listed there, and only the ipynb files in the main directory are listed.

I even did a sudo apt-get upgrade ipython-notebook , so I know I have the latest version too. My Mac laptop seems to work fine so it appears to be a bug specific to the Ubuntu distribution.

![screenshot from 2015-07-11 19 30 01](https://cloud.githubusercontent.com/assets/841159/8636085/63e459f6-2803-11e5-96f7-a390b8749fe3.png)

**Comment by Carreau** [comment]
This definitively **is not** the latest version. cf screenshot. You have an old version. 
Apt-repository of ubuntu are not up to date (complain to ubuntu that takes package to packages things). 
The version you have is a year and a half old, and do not support filesystem browsing. 

You can use conda or pip, and install latest as user. 

<img width="828" alt="screen shot 2015-07-11 at 21 37 46" src="https://cloud.githubusercontent.com/assets/335567/8636104/49e3640e-2815-11e5-84af-8fd1a5c1537c.png">
