### ISSUE TITLE
BUG: iPython notebook (Download PDF via Latex) and iPython nbconvert PDF fail when pdflatex is present

### ISSUE THREAD

**Issue by jakirkham** [ipython/ipython#8633]
Currently, I am trying to convert a notebook to PDF, but seem unable to despite having all the necessary dependencies. See version information below. This is occurring on CentOS 6.6. If I convert to Latex via iPython and use pdflatex to go to PDF, it works.

    $ ipython --version
    3.2.1
    $ pdflatex --version
    pdfTeX using libpoppler 3.141592-1.40.3-2.2 (Web2C 7.5.6)
    kpathsea version 3.5.6
    Copyright 2007 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
    Kpathsea is copyright 2007 Karl Berry and Olaf Weber.
    There is NO warranty.  Redistribution of this software is
    covered by the terms of both the pdfTeX using libpoppler copyright and
    the Lesser GNU General Public License.
    For more information about these matters, see the file
    named COPYING and the pdfTeX using libpoppler source.
    Primary author of pdfTeX using libpoppler: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
    Kpathsea written by Karl Berry, Olaf Weber, and others.
    
    Compiled with libpng 1.2.46; using libpng 1.2.49
    Compiled with zlib 1.2.3; using zlib 1.2.3
    Compiled with libpoppler

**Comment by Carreau** [comment]
We'll need a bit more information, like what command of UI you click onto, tracebacks, and if you can share the notebook.

**Comment by jakirkham** [comment]
Can't share that particular notebook. Let me work on a simple reproducer that I can share. As far as commands go, I tried use from the iPython Notebook "File" > "Download as..." > "PDF via LaTeX (.pdf)".

**Comment by takluyver** [comment]
We would at least need the error it's failing with.

Closing this for now. If you still have problems, please open an issue on the jupyter/nbconvert repo.
