### ISSUE TITLE
remove %install_ext

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#8634]
`%install_ext` is now deprecated.  For 5.0 we can completely remove all reference of it. 

(marking as sprint friendly)

**Comment by minrk** [comment]
I was thinking it might be summer friendly.

**Comment by Carreau** [comment]
haha, fixed.

**Comment by Achifaifa** [comment]
This looks like something interesting to do, ¿Do you mind if I work on it?

**Comment by Carreau** [comment]
It should be pretty easy to do. 

I would though wait for 4.1 to be out before working on a 5.0 feature.

You can though make the PR now, but it might not be merge before we start working on 5.0 which I guess will be around mid-semptember start-of-october ish. 
Up to you. 

@minrk what do you think ?

**Comment by Achifaifa** [comment]
I have some free time now, so I'll just issue a PR when I figure it out so I can get it done and work on other stuff :)

**Comment by Achifaifa** [comment]
Removing the function from IPython/core/magics/extension.py is enough since it's not referenced from anywhere else, right? I haven't found anything else that would end up dead, but asking just in case

**Comment by Carreau** [comment]
> Removing the function from IPython/core/magics/extension.py is enough since it's not referenced from anywhere else, right?

There might be a test lying around somewhere. But that should be about it. 

> Incidentally, ¿How can I figure out where is a function called? ¿Is there some sort of punction or block diagram somewhere? I have made a script that cats every file and then greps for the function, but it seems a bit crappy-ish to me and there must be a better way to do it :)

Most of the time I grep also:
```
$ grep -r install_ext **.py **.txt **.rst
IPython/core/extensions.py:    def install_extension(self, url, filename=None):
IPython/core/magics/extension.py:    def install_ext(self, parameter_s=''):
IPython/core/magics/extension.py:            %install_ext https://bitbucket.org/birkenfeld/ipython-physics/raw/d1310a2ab15d/physics.py
IPython/core/magics/extension.py:        warn("%install_ext` is deprecated, please distribute your extension "
IPython/core/magics/extension.py:            filename = self.shell.extension_manager.install_extension(args,
IPython/core/tests/test_magic.py:        _ip.magic("install_ext %s" % url)
docs/source/interactive/magics-generated.txt:.. magic:: install_ext
docs/source/interactive/magics-generated.txt:        %install_ext https://bitbucket.org/birkenfeld/ipython-physics/raw/d1310a2ab15d/physics.py
docs/source/whatsnew/github-stats-0.13.rst:* :ghpull:`1419`: Add %install_ext magic function.
docs/source/whatsnew/github-stats-0.13.rst:* :ghissue:`1419`: Add %install_ext magic function.
docs/source/whatsnew/version0.13.rst:* **%install_ext**: A new magic function to install an IPython extension from
docs/source/whatsnew/version0.13.rst:  a URL. E.g. ``%install_ext
```

(`**.smth` is fish shell syntax, you can use `*` in bash) 

You might also want to drop a file describing that it has been removed in `docs/source/whatsnew/pr` that describe the changes.

**Comment by minrk** [comment]
I'm not sure what the timeline is for 5.0. For compatibility-breaking things like this that have minimal benefit, I'd want to wait for at least a compelling *new* thing before starting the 5.0 fork.

**Comment by Carreau** [comment]
closed by #8763

**Comment by michaelpacer** [comment]
Is the reason why it was deprecated and removed because it's inclusion demanded relying on setuptools as described https://github.com/ipython/ipython/issues/5742 (referencing https://github.com/ipython/ipython/pull/4673)? 

Based on the recent pro setuptools statements found in https://github.com/jupyter/nbconvert/pull/352 by the strongest opponents of including setuptools in ipython (@minrk @takluyver), perhaps the `%install_ext` magic could be revived with better better safety and reproducibility aspects through the use of setuptools now that it does not affect `sys.path` by default.

**Comment by Carreau** [comment]
> Based on the recent pro setuptools statements found in jupyter/nbconvert#352 by the strongest opponents of including setuptools in ipython (@minrk @takluyver), perhaps the %install_ext magic could be revived with better better safety and reproducibility aspects through the use of setuptools now that it does not affect sys.path by default.

No, nothing related to that; see among other thread of August first [on IPython-dev](https://mail.scipy.org/pipermail/ipython-dev/2016-August/017233.html), quoting myself:

--- 
All the use case of install_ext are covered by pip.
Install_ext has also a lot of issues:
 - less secure than pip [can of euphemism to say gigantic potential
security nightmare]
 - no way to "uninstall_ext"
 - no way to "upgrade ext"
 - no way to express versions
 - no way to list extensions.
 - no way to express dependencies.

I think you see the pattern... improving install_ext was reinventing
managing packages
And as an IPython extension is "just" a python module that define some
magics methods, we now recommend
that extension should just be packages on PyPI.

If you find that publishing a package is too hard, I would suggest
having a look at flit[1]

1: https://pypi.python.org/pypi/flit

---- 

Note that "install_ext" is removed, not "load_ext" there are often a confusion with user. 

`%install_ext` is an historical artefact from a time were packaging was harder than today. 
The answer now is "use pip", (or conda...whatever), all the functionality that people require from install_ext should be in package manager and are one less things we have to care about.  

One of the thing we might want to look at is how to invoke the right pip (or conda) from within a python kernel. But there is already an issue for that.

**Comment by Carreau** [comment]
See https://github.com/ipython/ipython/pull/8601 as well as original post [on Mailing list](https://mail.scipy.org/pipermail/ipython-dev/2015-July/016689.html)

**Comment by janschulz** [comment]
Just one aspect of install_ext isn't covered: that extensions added via `insta_ext` were available in all kernels, extensions added via pip/conda have to be added (and updated) in all individual kernels (I use envs as kernels and have a lot of them :-()

**Comment by Carreau** [comment]
> Just one aspect of install_ext isn't covered: that extensions added via install_ext were available in all kernels, extensions added via pip/conda have to be added (and updated) in all individual kernels (I use envs as kernels and have a lot of them :-()

You can use `pip install --prefix`with the right things on your $PATH that will work covers this use case.

**Comment by takluyver** [comment]
With conda environments, `pip install --user` will work, because conda envs still see packages in your user site-packages (unless you've manually turned this off, as I have). If we keep adding `~/.ipython/extensions` to sys.path for loading extensions, you could also `pip install -t ~/.ipython/extensions`.

I agree that it's a bit inconvenient, but not enough to warrant making our own package manager.
