### ISSUE TITLE
iPython docs reference non-existent example

### ISSUE THREAD

**Issue by clearf** [ipython/ipython#8637]
The docs at http://ipython.org/ipython-doc/dev/parallel/asyncresult.html reference an example at the bottom: 

> When AsyncResult or the AsyncMapResult don’t provide what you need (for instance, handling individual results as they arrive, but with metadata), you can always just split the original result’s msg_ids attribute, and handle them as you like.

> For an example of this, see examples/parallel/customresult.py

I can't find a parallel directory within the examples directory, or a file called customresult.py. Am I looking in the wrong place?

**Comment by Carreau** [comment]
This has no been moved in it's own repo and will be fixed by ipython/ipyparallel#40
