### ISSUE TITLE
Dropdown Widget cut off at the end of the notebook

### ISSUE THREAD

**Issue by aneeshvartakavi** [ipython/ipython#8638]
I'm facing an issue when the dropdown is cut off the end of the notebook (see attached screenshot). I've worked around this in the past by adding empty cells below this cell, but I currently have a list of 300 options and I'm trying to find a better fix. I'm running IPython Notebook 3.2.1.

![screen shot 2015-07-17 at 3 58 38 pm](https://cloud.githubusercontent.com/assets/4122476/8759495/c695b6a8-2ca9-11e5-9f34-a4b757edaa89.png)

**Comment by aneeshvartakavi** [comment]
Oops, I meant to open this issue in ipython/ipwidgets, but I opened it here by mistake, and now I can't delete it.

http://stackoverflow.com/questions/3081521/removing-github-issues

**Comment by takluyver** [comment]
See ipython/ipywidgets#94; closing here.
