### ISSUE TITLE
Instant running not working with the following message  'IPython is a package and cannot be directly executed'

### ISSUE THREAD

**Issue by sukhbinder** [ipython/ipython#8641]
I have downloaded the zip file of Ipython from github and unzipped it on windows PC running under windows 7. 

Trying to run Ipython without installing and i get the following errors

 IPython is a package and cannot be directly executed
 
You can run IPython from this directory without even installing it system-wide by typing at the terminal:

 $ python -m IPython

Tested in Python 3.4 and 2.6 in two windows 7 system

Thanks

**Comment by Carreau** [comment]
Do not download the zip from github they are broken. Install anaconda and use conda to install IPython.

**Comment by takluyver** [comment]
Also, recent releases don't support Python 2.6; if you want to use IPython with that, you need to go back to IPython 1.x.

**Comment by sukhbinder** [comment]
Thanks. But I tried it with I python 3.4 and there was the same issue. 

I cannot use conda, anaconda etc as do not have right to install anything on the system. So was trying to use IPython inflate without any install. 

Thanks

**Comment by takluyver** [comment]
You can install anaconda inside your user account, so it should still work if you don't have admin access.

But if you really need to do it without installing anything at all, download the zip file [from PyPI](https://pypi.python.org/pypi/ipython/3.2.1) and run from that.

**Comment by sukhbinder** [comment]
Thanks. Can't download an exe, I will give pypi a try. 

Thanks
