### ISSUE TITLE
Bug in 3.x: IPython/html/services/contents/manager.py

### ISSUE THREAD

**Issue by gramster** [ipython/ipython#8646]
Either the docstring is wrong or the name parameter is missing in file\_exists; I suspect the latter:

    def file_exists(self, path=''):
        """Does a file exist at the given path?
        Like os.path.isfile
        Override this method in subclasses.
        Parameters
        ----------
        name : string
            The name of the file you are checking.
        path : string
            The relative path to the file's directory (with '/' as separator)
        Returns
        -------
        exists : bool
            Whether the file exists.
        """
        raise NotImplementedError('must be implemented in a subclass')

**Comment by minrk** [comment]
The docstring is wrong.

**Comment by minrk** [comment]
Fixed in jupyter/notebook#219
