### ISSUE TITLE
utils.path.locate_profile changed by `load_subconfig`

### ISSUE THREAD

**Issue by michaelaye** [ipython/ipython#8649]
When using `load_subconfig` in a profile that is **NOT** the default profile, e.g. like so:

```python
c = get_config()

load_subconfig("ipython_config.py", profile='default')
from IPython.utils.path import locate_profile
print("locate_profile(): ", locate_profile())
print("__file__ :", __file__)
```
it changes the result of `IPython.utils.path.locate_profile` to be `default` instead of the current profile:
```bash
$ ipython --profile=pymars
locate_profile():  /Users/klay6683/.ipython/profile_default
__file__ : /Users/klay6683/.ipython/profile_pymars/ipython_config.py
```
I'm not sure this is what this should be doing. It is still useful to have a way to distinguish between the defaults I am loading in and extra stuff I am only doing in this particular profile folder.

**Comment by michaelaye** [comment]
In [6]: print(IPython.sys_info())
{'commit_hash': '2d95975',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/klay6683/miniconda3/lib/python3.4/site-packages/IPython',
 'ipython_version': '3.2.1',
 'os_name': 'posix',
 'platform': 'Darwin-14.3.0-x86_64-i386-64bit',
 'sys_executable': '/Users/klay6683/miniconda3/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.4.3 |Continuum Analytics, Inc.| (default, Mar  6 2015, '
                '12:07:41) \n'
                '[GCC 4.2.1 (Apple Inc. build 5577)]'}

**Comment by takluyver** [comment]
It's not changing it - the default for `locate_profile()` is 'default', not the current profile. You can call `locate_profile('pymars')` to get an explicitly named profile, or something like:

```python
IPython.core.application.Application.instance().profile_dir.location
```

**Comment by michaelaye** [comment]
Oh, shoot, sorry for the noise. So there's no API to just get the profile name inside the config file then?
I'm currently using this hack:
```python
import os.path as osp
prof = [i for i in __file__.split('/') if i.startswith('profile_')][0].split('_')[-1]
c.NotebookApp.notebook_dir = osp.join(c.NotebookApp.notebook_dir,
                                      prof, 'notebooks')
```

**Comment by takluyver** [comment]
If you just want the name, I think something like this should do it:

```python
IPython.core.application.Application.instance().profile
```
