### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by methodds** [ipython/ipython#8652]
Hi,
I am trying to customize my ipython notebooks (v3.21, python 2.77) via custom.css. I can't get the notebooks to change the font color in code cells, every other manipulation works without any problems.

This is my code:

.cm-s-ipython { background-color: #1d1f21; color: #c6c5fe; }

.cm-s-ipython .CodeMirror-gutters {background: #161b1d; border-right: 0px;}
.cm-s-ipython .CodeMirror-linenumber {color: #5a7b8c;}
.cm-s-ipython span.cm-keyword {color: #96cbfe; font-weight: bold;}
.cm-s-ipython span.cm-number {color: #ff73fa;}
.cm-s-ipython span.cm-operator {color: #ededee; font-weight: bold;}
.cm-s-ipython span.cm-meta {color: #005d44;}

Any help would be great!

edit: basically I just want to copy the atom dark theme style: https://github.com/atom/atom-dark-syntax
 if there is an easier way to do this please be so kind to share it with me

**Comment by codybraun** [comment]
Dropping your css into custom.css worked fine for me (and looks really sharp), though I added

    .cm-s-ipython span.cm-variable  {color: #ffffff; font-weight: bold;}

for readability. Can you inspect the text spans and see where that black-font style is coming from if not custom.css?

**Comment by takluyver** [comment]
Closing as out of date. If you're still having trouble, open an issue on the jupyter/notebook repo.
