### ISSUE TITLE
standard front-ends not showing output of execution from other clients

### ISSUE THREAD

**Issue by brunobeltran** [ipython/ipython#8661]
I am led to believe by the closing of issue #1873 (by PR #6123) that when multiple console or qtconsole clients are connected to a kernel, the output of commands put into one should be visible from the other (after the latter refreshes, supposedly the next time that enter is pressed?) I cannot seem to get this feature to work on my install of Debian Jessie, even after updating iPython via pip.

To reproduce (copy/paste'd, not executed in order presented, of course):
[window 1]
```
$ pip install -U ipython
$ ipython kernel
```

[window 2]
```
$  ipython console     --existing kernel-30792.json
IPython Console 3.2.1

In [1]: print(a)
2

In [3]: a
Out[4]: 2

In [5]:
```
[window 3]
```
$ ipython console     --existing kernel-30792.json
IPython Console 3.2.1

In [1]: a = 2

In [2]: a
Out[3]: 2

In [4]: a
Out[5]: 2

In [6]:
```

I expected lines like
```
[remote]In [2]: a
[remote]Out[2]: 2
```
in window 3. Am I missing something? Is this actually an option that needs to be turned on?

This bug also affects qtconsole clients.

```
$ python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': u'2d95975',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python2.7/dist-packages/IPython',
 'ipython_version': '3.2.1',
 'os_name': 'posix',
 'platform': 'Linux-3.16.0-4-amd64-x86_64-with-debian-8.1',
 'sys_executable': '/usr/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.9 (default, Mar  1 2015, 12:57:24) \n[GCC 4.9.2]'}
```
Also appears to affect master; I just got around to trying it in a virtualenv.

**Comment by takluyver** [comment]
It's an option that needs to be turned on. Set e.g. `IPythonWidget.include_other_output=True` (for the Qt console) in [config](http://ipython.org/ipython-doc/3/config/options/qtconsole.html).

**Comment by brunobeltran** [comment]
Thank you, sorry for the noise.

**Comment by brunobeltran** [comment]
Hmm, so this is strange.

Including 
```
c.IPythonWidget.include_other_output = True
```
in my `ipython_qtconsole_config.py` file fixes the problem, but opening `ipython qtconsole` and running
```
%config IPythonWidget.include_other_output = True
```
does not (even after pressing enter, and even after carefully ensuring I'm connecting to the same kernel).

**Comment by minrk** [comment]
The `%config` magic is code that runs in the IPython kernel and updates the kernel's configuration. It has no effect on the frontend.
