### ISSUE TITLE
Can't create notebook on the botton new.

### ISSUE THREAD

**Issue by jiamo** [ipython/ipython#8662]
Using `ipython notebook` command to start notebook server, I can't create new notebook with the 'new button'  on the website.
<img width="259" alt="cannot_create_notebooks" src="https://cloud.githubusercontent.com/assets/732751/8893671/db664604-33cc-11e5-9b9a-f53d9986aeb2.png">

➜  practice git:(master) ✗ ipython --version
3.0.0

**Comment by takluyver** [comment]
What happens if you click 'Python 2' in that menu?

**Comment by jiamo** [comment]
My stupid. 'Python 2' create the notebook! Thanks
