### ISSUE TITLE
Widget warning is not useful

### ISSUE THREAD

**Issue by moorepants** [ipython/ipython#8663]
IPython 3 shows this warning when you import anything from the widgets package:

```:0: FutureWarning: IPython widgets are experimental and may change in the future.```

I understand that this warning could be muted manually but I wanted to express my discontent with it. There are tons of people and projects utilizing the widget functionality which have now been in two major IPython releases. You all may be planning to change the API, but why not cycle through a proper deprecation cycle with warnings for the precise changes you are going to make. This warning is not very useful as it stands and is really just quite annoying. The only thing I can think of that this warning may mean is that you plan to change the widget API without proper deprecation.

I would like to recommend removing this warning and to simply issue specific deprecation warnings when you are actually are going to change the API.

cc @certik

**Comment by certik** [comment]
Indeed, it was quite comical to see this warning on 30+ laptops at the SciPy tutorials. This warning should be off by default.

**Comment by minrk** [comment]
Note that the warning is specifically promising that the widget API is *not* stable enough for deprecation cycles. There will be breaking changes on every release.

**Comment by moorepants** [comment]
I see. That is quite unfortunate then. Maybe you all shouldn't break the API that's been available in two major versions and just create a new package instead. There will be an awful lot of broken code in the wild if the widget API is changed without deprecation.

**Comment by minrk** [comment]
>Maybe you all shouldn't break the API that's been available in two major versions and just create a new package instead.

That's [exactly what we did](https://github.com/ipython/ipywidgets).

> There will be an awful lot of broken code in the wild if the widget API is changed without deprecation.

That's why there's a warning, and we have already done this twice.

**Comment by certik** [comment]
Is the recommendation to use the package instead and not the ipython
notebook ones?

**Comment by minrk** [comment]
IPython 4.0 breaks up into many packages - notebook is a package, qtconsole is a package, widgets are a package, etc. It's moving, not duplication. IPython will not include widgets anymore. We are still ironing out the installation process for the new packages, but they should be ready, soon. I would recommend sticking with IPython stable for now.

**Comment by moorepants** [comment]
So since you are creating a new package and not breaking the current API, can this warning by removed?

**Comment by takluyver** [comment]
The new package is the replacement for the current API - `IPython.html.widgets` won't be there (except as a shim to import ipywidgets) in IPython 4.

**Comment by moorepants** [comment]
Will there be a new API in IPython 4 for widgets?

**Comment by minrk** [comment]
There are no significant changes in 4.0. The only intended change is splitting the repos. As a result, the client-side (javascript) API has changed some, though.

**Comment by moorepants** [comment]
So what is the purpose of the warning if there will be no API changes in 4.0? Couldn't there just be specific warnings for the few JS changes instead?

Would you accept a pull request to IPython 3 that removes this warning?

**Comment by takluyver** [comment]
We'll probably break things for version 5. We're kind of not counting v4, because the idea is that it's broadly the same functionality as v3, just with the packages split up.

Hopefully there will be no more 3.x releases, so there's not much point making PRs against 3.x.

**Comment by moorepants** [comment]
Sorry to keep on with this, but the point of a PR would be to remove this warning in IPython 3. I'd also like to see specific deprecation warnings in IPython 4 if there are big changes coming in 5 instead of this broad warning. The changes made in the widgets API for version 3 caused us lots of headaches and it isn't clear why changing css, etc on widgets are now done with private attrs/methods. I can understand that you all want to clean things up but the current warning seems to tell developers that you all don't care that we have lots of code depending on the widgets API from IPython 2 and 3. I'm just dreading our app breaking on install of future IPython versions with no specific warnings in the previous versions.

**Comment by takluyver** [comment]
We don't know exactly in what ways we're going to break it yet. The warning roughly means that we don't advise building apps on top of widgets at the moment, because it's not a stable API.

Of course, this is kind of a chicken and egg scenario, because if nobody uses widgets, we don't know what we should change. So we need some people using them. But they're probably not ready for apps if it's a serious problem when they break.

**Comment by moorepants** [comment]
Understood. It would have been nice if widgets were an experimental separate package instead of being included in IPython 2.0+. Maybe I'm missing some documentation somewhere but I took the inclusion of widgets in IPython 2.0+ to equate to stability. My vote is still to have a proper deprecation cycle. You have my concerns on file now.  Thanks for answering my questions.

**Comment by minrk** [comment]
>It would have been nice if widgets were an experimental separate package instead of being included in IPython 2.0+.

That would have been much better, and it's what we wanted, too. It just wasn't feasible at the time due to coupling between pieces of IPython. We are working now to remove that coupling, which is allowing us to move widgets to their own home, so they can better communicate their own level of stability.

> Maybe I'm missing some documentation somewhere but I took the inclusion of widgets in IPython 2.0+ to equate to stability.

Precisely what the warning was meant to address - stating explicitly that this is not the case.
