### ISSUE TITLE
BUG: iPython 2.4.0-maint cannot autosave notebook over sshfs

### ISSUE THREAD

**Issue by jat255** [ipython/ipython#8664]
Hello,

I have a drive mounted using sshfs that I seem to have full permissions on. Outside of iPython, I can create files, delete them, execute them, etc. from this mounted folder. 

I am having problems with iPython however. I can create a notebook with no problems, but then cannot save the notebook (overwriting the previous file). iPython creates a new temp file every time it tries to autosave, and complains in the terminal that it cannot save. This is the error:

```
2015-07-27 02:01:08.669 [NotebookApp] Saving notebook at /Sample.ipynb
2015-07-27 02:01:08.850 [NotebookApp] WARNING | Unexpected error while autosaving notebook: ./Sample.ipynb [Errno 1] Operation not permitted
WARNING:tornado.access:400 PUT /api/notebooks/Sample.ipynb (::1) 182.26ms referer=http://localhost:8888/notebooks/Sample.ipynb
```

I am not sure what to make of this, since as my own user I have full access to the path that it's trying to save to, and that it has no problem saving there if the file does not exist already. Any thoughts?

**Comment by takluyver** [comment]
I'd guess that's another consequence of the atomic saving implementation. For 4.0, we're moving to a different way of doing atomic saving (see jupyter/notebook#67), which will hopefully cause fewer problems in cases like this.

**Comment by jat255** [comment]
It turns out that this issue, while made apparent by the way ipython saves checkpoints, is not really ipython's fault. Rather it appears to be a permissions thing with sshfs. For anyone who runs into this problem, a workaround is to change the mount options for your sshfs mount. Adding the following mount options allows saving with no problem:

```
-o workaround=rename,noexec
```

Closing this issue as it is unrelated to ipython, really.
