### ISSUE TITLE
SSL Error behind nginx reverse proxy

### ISSUE THREAD

**Issue by nem2k** [ipython/ipython#8665]
I have an SSL certificate for my server (its a .crt bundle) but I keep getting errors when trying to use it with ipython notebook server

I have nginx setup in windows. Access to ipython is setup via a reverse proxy (followed this here: stackoverflow.com/questions/22665809/how-to-configure-ipython-behind-nginx-in-a-subpath)

I followed the instructions on how to set up a notebook server (ipython.org/ipython-doc/1/interactive/public_server.html#running-a-public-notebook-server). I'm also using the /ipython prefix. I changed the location of my certificate, which is a .crt file and not a .pem, everything else is left the same (besides password)

Whenever I try to access www.domain.com/ipython, I get this error:

<code>
[W 03:43:22.463 NotebookApp] SSL Error on 916 ('127.0.0.1', 1586): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:581)

[E 03:43:22.463 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "C:\Python27\lib\site-packages\tornado\http1connection.py", line 693,
 in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "C:\Python27\lib\site-packages\tornado\gen.py", line 870, in run
        value = future.result()
      File "C:\Python27\lib\site-packages\tornado\concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "C:\Python27\lib\site-packages\tornado\gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "C:\Python27\lib\site-packages\tornado\http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "C:\Python27\lib\site-packages\tornado\gen.py", line 870, in run
        value = future.result()
      File "C:\Python27\lib\site-packages\tornado\concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:581)
</code>

Everythings works on the local machine if I use a self-signed certificate, but it doesn't work remotely. And using a signed certificate does not work locally or remotely, and gives me the error above. Any ideas what the issue might be?

**Comment by minrk** [comment]
If you have IPython configured to use SSL and you are using an nginx proxy, that means you are requiring that nginx make an https connection to the notebook server behind the proxy. That doesn't have any effect on whether the connection to the outside world should use SSL, though. I'm not sure that's actually what you are after. Typically with nginx you do SSL termination at the proxy, and use http for the local connections, in which case you would configure nginx to use SSL, but IPython would *not* have any SSL configuration.

**Comment by nem2k** [comment]
wow of course  you're right, I can't believe that skipped my mind and I was just following the instructions blindly! thanks for reminding me!
