### ISSUE TITLE
Support changing sys.std* streams

### ISSUE THREAD

**Issue by Drekin** [ipython/ipython#8669]
It seems that IPython doesn't reflect when sys.std* streams are changed at runtime. `utils.io` wraps the standard streams at import time rather than resolving them dynamically.

**Comment by Drekin** [comment]
Another similar behavior is in `utils.encoding` where `DEFAULT_ENCODING` is stored at import time rather than being dynamically resolved at runtime.

**Comment by Drekin** [comment]
It is quite a common issue: `colorama` had this issue (https://github.com/tartley/colorama/issues/32), and `progress` has also this issue (https://github.com/verigak/progress/issues/21). I think it shouldn't be assumed that `sys.std*` don't change. There are even `sys.__std*__` attributes capturing the original streams.

I have no idea what else would a change affect, so I'd naively propose to change `utils.io.IOStream` so that instead of a stream, one may give it function returning a stream, so its `stream` attribute becomes a property resolving the stream at runtime. Also, all references to `utils.encoging.DEFAULT_ENCODING` could be changed to an actual call to `utils.encoding.getdefaultencoding`.

**Comment by takluyver** [comment]
We should be able to get rid of our `io.std*` objects on the way to 5.0 - see #9141 and #9118.

While investigating this, I found that pyreadline, which `io.stdout` and `io.stderr` redirect through on Windows, uses WriteConsoleW:

https://github.com/pyreadline/pyreadline/blob/4e4b7b468cfdf2dfef8e2c8c695a64e96c514213/pyreadline/console/console.py#L372

That may be of professional interest to you for win_unicode_console :-)

**Comment by takluyver** [comment]
Actually, I wonder about making `win_unicode_console` a dependency of IPython on Windows, and enabling it in our own code. It enables mostly sane unicode input and output in a command prompt, rather than having to play the codepage game to allow a very limited subset of unicode.

**Comment by Drekin** [comment]
That sounds great to me. Also, thanks for the information regarding `pyreadline`. Actually, I reuse the `pyreadline` readlinehook when present by default – it is just necessary to change its stored encoding.

**Comment by Carreau** [comment]
@takluyver do you want to try to tackle that for 5.0, or should we bump for 6.0 ?

**Comment by takluyver** [comment]
I think we've either fixed or are moving towards fixing the original issue - the stream wrappers in utils.io are deprecated now.

As for using win_unicode_console: I'm not sure how it interacts with prompt_toolkit. It's possible that for input, prompt_toolkit is already doing something smart. @Drekin do you know anything about prompt_toolkit and how it behaves with WUC?

**Comment by Drekin** [comment]
@takluyver I have just tried `prompt_tookit`'s `prompt` function and it seems it work even without WUC (it read correct Unicode characters and it can print a prompt containing Unicode characters as well). When run with WUC enabled, there were no problems. But it was just a brief tryout.

**Comment by takluyver** [comment]
Thanks! That probably lessens the need for us to use WUC - it may still be useful for output, but let's get 5.0 out and look into it after that.

**Comment by takluyver** [comment]
@Carreau I have created a 5.1 milestone.

**Comment by takluyver** [comment]
As we did end up putting WUC into 5.0, I'm closing this.
