### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'IPython/utils/submodule.py'

### ISSUE THREAD

**Issue by timarits** [ipython/ipython#8676]
I downloaded ipython-3.0.0.zip from https://github.com/ipython/ipython/releases and ran the following in my MacBook's terminal:

MacBook-Pro-van-Tim-Eerd:~ timeerd$ python /users/timeerd/downloads/ipython-3.0.0/setup.py install

Response:

Traceback (most recent call last):
  File "/users/timeerd/downloads/ipython-3.0.0/setup.py", line 56, in <module>
    from setupbase import target_update
  File "/Users/timeerd/Downloads/ipython-3.0.0/setupbase.py", line 530, in <module>
    execfile(pjoin('IPython','utils','submodule.py'), globals())
IOError: [Errno 2] No such file or directory: 'IPython/utils/submodule.py'

I checked https://github.com/mattvonrocketstein/ipython/commit/ee35a6fe6e192630c433c8710c9db58513ee5fc1 but that doesn't seem to fix the problem. Any help?

**Comment by takluyver** [comment]
Installation won't work from Github tarballs, though what you're seeing is another problem. We recommend installing ipython using `pip install ipython`.
