### ISSUE TITLE
HelloWidget Example- "No default value found for None trait" error

### ISSUE THREAD

**Issue by klanea** [ipython/ipython#8680]
Hi all,

I just installed a fresh copy IPython via ``pip install --upgrade "ipython[all]"'' on two Debian-based machines and tried to take the "Custom Widget - Hello World" notebook for a test run:
https://github.com/ipython/ipython/blob/master/examples/Interactive%20Widgets/Custom%20Widget%20-%20Hello%20World.ipynb

When I Run All on both machines, I first get an error on the traitlets import, claiming it's not defined. Looks like traitlets doesn't get installed by default. No problem: sudo pip install traitlets. Unfortunately, both instances then fail when I try to instantiate the widget itself:

![capture](https://cloud.githubusercontent.com/assets/13054486/9023442/e9e70114-384f-11e5-9181-2062a1bf46a7.PNG)

I recall this demo used to work fine (last I checked 4-5 months ago). Have changes to traits support on the backend broken this example? Is there a step I'm missing?

I see at least one recent traits-related bug: https://github.com/jupyter/jupyterhub/issues/262
Is there a connection?

Thanks in advance!

**Comment by Carreau** [comment]
@jdfreder can you have a look and close if this not and issues with widgets anymore ?

Thanks !

**Comment by jdfreder** [comment]
I tested this with a fresh install of the notebook, using the same command @klanea provided, and the current version of the mentioned example notebook works fine: https://github.com/ipython/ipywidgets/blob/master/examples/Custom%20Widget%20-%20Hello%20World.ipynb

However, I'd like to point out, this notebook can't be ran with run all, which is as designed.  It's meant to be ran cell by cell, as a tutorial.  The Javascript in the notebook, when ran with run-all, can have race issues.
