### ISSUE TITLE
Dialog for closing unsaved, changed notebook must be clicked twice to leave (prefer once)

### ISSUE THREAD

**Issue by jakirkham** [ipython/ipython#8681]
![ipython_double_click_unsaved_close_720p](https://cloud.githubusercontent.com/assets/3019665/11599955/b802d5a6-9a97-11e5-9659-68b5a64531b6.gif)

On Mac ( 10.9 ), Firefox ( 39.0 ), iPython ( 3.2.1 ) and Python ( 2.7.10 ), when attempting to close an unsaved notebook with changes attempting to leave the notebook without saving the user must click twice. It would be preferable to be only asked once. I have since updated Firefox to ( 40.0.2 ), but the problem persists.

**Comment by takluyver** [comment]
I'm not sure how that would happen. I only get asked once when I test on master.

**Comment by jakirkham** [comment]
Added my OS version in case it is relevant. What browser/OS are you using?

**Comment by takluyver** [comment]
Firefox 39 on Linux.

**Comment by jakirkham** [comment]
Maybe this is related ( https://github.com/makeusabrew/bootbox/issues/46 ).

**Comment by jakirkham** [comment]
Here's a video showing the issue ( https://www.dropbox.com/s/60kbx3gs6g0ufuc/ipython_double_click_unsaved_close.m4v?dl=0 ). Firefox has since been upgraded to 40.0.3.

**Comment by Carreau** [comment]
Thanks for the video !

**Comment by jakirkham** [comment]
Also, seen with notebook version 4.0. Recently saw this on Windows (8?) using Firefox, as well. This can be seen in Firefoxes up to 42.0.

Side note: Should I move this to ( https://github.com/jupyter/notebook/issues )?

**Comment by takluyver** [comment]
Can anyone still reproduce this?

**Comment by jakirkham** [comment]
Definitely. This is still reproducible.

**Comment by minrk** [comment]
Super weird. It seems like a Firefox bug that its own Leave Page dialog (we don't create this dialog, Firefox does) actually allows the page to keep you there after you confirm that you want to leave.

**Comment by jakirkham** [comment]
Though I have seen this sort of Firefox dialog with other things where it doesn't require clicking twice. Maybe there is a hacky workaround for whatever Firefox bug it might be?

**Comment by minrk** [comment]
I'll see if I can figure out a workaround. There is certainly a bug in Firefox that `onbeforeunload` fires twice. Apparently it's been an open, known bug for [at least 40 releases](https://bugzilla.mozilla.org/show_bug.cgi?id=531199).

**Comment by jakirkham** [comment]
Nice find. Wow, I can't believe this has gone on so long. I know I have seen it for awhile but 40 releases!?

This website ( https://repl.it/ ) raises a dialog when you close the window/tab after starting a session (e.g. Python3), but goes away after one click. Maybe there is something in there code that can help, not sure.

**Comment by minrk** [comment]
Should be fixed by jupyter/notebook#1011

**Comment by jakirkham** [comment]
Cool, I'll take it for a spin and let you know how it goes.

**Comment by jakirkham** [comment]
Hmm...doesn't quite do it. I tried to install using `pip install -e .` after checking out that commit. It looked like everything went ok, but maybe something didn't work quite right.

**Comment by takluyver** [comment]
@jakirkham you'll need to rebuild the JS:

http://jupyter-notebook.readthedocs.org/en/latest/development_js.html

You may also need to hit Ctrl-F5 a few times to make sure the old JS is no longer in the browser's cache.

**Comment by Carreau** [comment]
you can also run the notebook with `--NotebookApp.ignore_minified_js=True` to avoid loading minified files.

**Comment by jakirkham** [comment]
Yep you were right. Should have cleared the cache. Looks great. Thanks everyone.
