### ISSUE TITLE
inprocess_qtconsole delayed output after compile to exe with cx_freeze

### ISSUE THREAD

**Issue by xfguo** [ipython/ipython#8682]
I want to embed IPython QT Console into my GUI project. But after I built the inprocess_qtconsole.py into exe with cx_freeze, the IPython command output is always display after I type twice "ENTER" key.

Here is the console output when I direct run inprocess_qtconsole.py with python.exe.

```
In [1]: print 1
1

In [2]: print 2
2

In [3]: print 3
3

In [4]: print 4
4
```

And below is the output when I run the compiled execute file of inprocess_qtconsole

```
In [1]: print 1

In [2]: print 2
1

In [3]: print 3
2

In [4]: print 4
3

In [4]: 

In [4]: 
4
```

----

It seems that the stdout was not be flushed quickly. Because when your command raise an Exception, it will always return feedback immediately.

Can anyone give me some guide to let me find out the issue? Thanks.

**Comment by takluyver** [comment]
I don't know how you'd go about debugging that; the inprocess qtconsole is one of the most quirky, unloved corners of our code, and debugging bugs that only occur in frozen applications is not much fun either.

**Comment by xfguo** [comment]
@takluyver Thanks for your reply.

Could you please tell me what is the recommend way to embed the IPython console to a PyQt project? Thanks again.

**Comment by takluyver** [comment]
* If it's important that the console can access variables in your application, we recommend embedding just the kernel and showing the Qt console in a separate window. There's example code for that [here](https://github.com/ipython/ipykernel/blob/master/examples/embedding/ipkernel_qtapp.py).
* If it's important that the console is visibly a widget in your application, you can use the `RichIPythonWidget` (3.x) or `RichJupyterWidget` (4.x) class in your PyQt code, and run the kernel in a separate process.
* If you need to do both, the in-process kernel is the recommended way to do it, but it's not very well supported. Our architecture is built around the kernel and the interface being separate processes, and putting them in the same process is somewhat awkward.

Docs reference: http://jupyter.org/qtconsole/stable/#embedding-the-qtconsole-in-a-qt-application

**Comment by xfguo** [comment]
Hi @takluyver .

I know the in-process kernel is not the focus of the development, but I speed some time to find the issue and now I fixed it for me. So just let me post what I found.

After I frozen the python code by cx_freeze, there are several warnings which are about *can't find README_STARTUP* and *can't find static files*. I believe these warnings use the `DummySocket` channel and **messed the queue processing**. So it got a delay output. 

In another hand, if the implementation of class `PorfileDir` to find some resources can be more configurable. I think it will be easier to do some fix-up for frozen program.

So far, my ugly way to fix it is just replace two methods with:

```
def check_static_dir(self):
    self._mkdir(self.static_dir)
    custom = os.path.join(self.static_dir, 'custom')
    self._mkdir(custom)
    for fname in (u'custom.js', u'custom.css'):
        src = os.path.join(os.path.dirname(sys.executable), u'ipy-data', 'custom', fname)
        dest = os.path.join(custom, fname)
        if not os.path.exists(dest):
            shutil.copy(src, dest)

def check_startup_dir(self):
    self._mkdir(self.startup_dir)

    readme = os.path.join(self.startup_dir, u'README')
    src = os.path.join(os.path.dirname(sys.executable), u'ipy-data', u'profile', u'README_STARTUP')
    if os.path.exists(src) and not os.path.exists(readme):
        shutil.copy(src, readme
```

**Comment by takluyver** [comment]
Closing here as `inprocess_qtconsole` is no longer part of this repo. If there's still something you'd like us to do, open a new issue on the jupyter/qtconsole repo.
