### ISSUE TITLE
kernel busy and kernel not connected

### ISSUE THREAD

**Issue by MATT68** [ipython/ipython#8689]
Hi'all.
I've been suffering this problem, and after several tries, I think finally found the problem -my problem-.
I hope it helps somebody.

Symptoms:
When I'm trying to run a cell, the kernel is always busy and take a lot to run the cell, and after a while the kernel lost the connection, and shows the break connection icon, up and right, next to the Python 2 text. When I pass the mouse over, it shows: "No connection to kernel".
Experimented with Firefox-Chrome-MS Explorer

Remedy:
I finally have installed firefox v38 -downgrading from v39-. And now, it's working fine and stable.

In firefox v39, the console was showing several messages regarding the SHA-1 security algorithms, and just now -firefox v38- the console is empty of this messages. I think this was the issue. But ...who knows!?

**Comment by takluyver** [comment]
Is this on your own server, or a public notebook server? It sounds like it's not happy about the HTTPS certificate.

**Comment by takluyver** [comment]
Closing as it's not clear what the issue was. If there is still something for us to fix, please open a new issue on the jupyter/notebook repo.
