### ISSUE TITLE
Update IPEP 27

### ISSUE THREAD

**Issue by blink1073** [ipython/ipython#8692]
I have the following suggestions for the [IPEP 27 Wiki](https://github.com/ipython/ipython/wiki/IPEP-27:-Contents-Service):

- "Get an existing file" does not mention [content parameter](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/handlers.py#L123). 
- "Create a Checkpoint" response should have a location like "Location: /api/contents/foo/bar/Untitled0.ipynb/checkpoints/[checkpoint_id]"

**Comment by minrk** [comment]
+1 to both

**Comment by blink1073** [comment]
Done!
