### ISSUE TITLE
Tab display of docstring in function args failing with multiline statement above

### ISSUE THREAD

**Issue by adrn** [ipython/ipython#8697]
My setup:
* IPython 3.2.1
* Clean profile (no local configuration)
* Python 2.7.10
* Mac OS X 10.10.3

I've noticed some strange autocomplete issues since updating to V3 and I think I isolated the root of the problem (or at least one problem...). It seems that tab-display of a function docstring shows the wrong docstring if there is a multi-line statement above the object you are trying to inspect. For example:

```python
a = (1,
     2,
     3)

int()
map()
```

If you put the cursor in the parens in `int()` and Shift+Tab, the docstring for `map` pops up instead.

See video of behavior here:
https://www.youtube.com/watch?v=Zevyejt37Qk&feature=youtu.be

**Comment by Carreau** [comment]
Nice catch, this is because for Python tokenizer `NEWLINE != NL`, one is in a multiple statement, not the other. Should be fixed by #8809 if you want to try it.

**Comment by adrn** [comment]
rockin!
