### ISSUE TITLE
SelectMultiple widget selects only first element from selected_labels or value

### ISSUE THREAD

**Issue by denfromufa** [ipython/ipython#8698]
```
selected=tuple('ab')
def ftest(x):
    global selected
    selected=x
    print(x)
interact(ftest,x=SelectMultiple(description='Test Widget',options=tuple('abc'),selected_labels=selected))
```

**Comment by takluyver** [comment]
@jdfreder, can you take a look?

**Comment by jdfreder** [comment]
This is no longer an issue in ipywidgets 4.0

**Comment by denfromufa** [comment]
ok, I upgraded to ipywidgets 4.0+, which also upgraded the notebook, ipython kernel, etc. It seems quite a mess in transition?

Now only the first SelectMultiple is displayed for multiple arguments. The rest is displayed as {}.

**Comment by denfromufa** [comment]
Server Information:

You are using Jupyter notebook.

The version of the notebook server is 4.0.1-<not found> and is running on:
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]

**Comment by jasongrout** [comment]
This sounds related to https://github.com/ipython/ipywidgets/issues/106, which was solved, I think, by https://github.com/ipython/ipywidgets/pull/113.  Perhaps there is a corner case; I'll check.
