### ISSUE TITLE
conda commands in notebook make cell 'freeze'

### ISSUE THREAD

**Issue by denfromufa** [ipython/ipython#8699]
https://github.com/conda/conda/issues/1492

**Comment by denfromufa** [comment]
in ipython notebook on windows any command involving conda causes the cell to "freeze".

e.g.

```
!conda -h
```

or

```
%%cmd
conda -h
```

This commands work with pip.

The frozen cell requires to restart the kernel.

**Comment by takluyver** [comment]
What does `conda -h` in the terminal give you?

**Comment by denfromufa** [comment]
conda -h works in: powershell, cmd, ipython terminal, ipython qtconsole.

In ipython notebook one-time it is stuck, the other time it shows very weird old command:

C:\Users\***\Documents\Python Scripts>conda install SQLAlchemy --force  1>>conda.install 
The process cannot access the file because it is being used by another process.

which I can kill manually.

**Comment by denfromufa** [comment]
ok, I fixed this problem. the issue was that I had a script with name conda.bat in the path, which was launched every time.

**Comment by takluyver** [comment]
That'd do it, thanks for finding out the issue.

**Comment by denfromufa** [comment]
I think the other problem why it was difficult to troubleshoot is because
the paths in ipython notebook are defined differently than in mentioned
terminals.

**Comment by takluyver** [comment]
Are you launching the notebook from the anaconda launcher GUI? If so, it's probably not picking up modifications to your PATH in some file like `.bash_profile`.

**Comment by denfromufa** [comment]
Nope, I'm launching from command line from c:\user\***\ folder using server
profile.
I did not make modifications to path file, is it in Python or IPYTHON setup?

**Comment by takluyver** [comment]
OK, sorry, I forgot you were on Windows.

What exactly do you mean when you say that the paths are defined differently?

**Comment by denfromufa** [comment]
I meant combination of sys.path and path environment variable, which are
searched for executables.
