### ISSUE TITLE
test_exampleip and dtexample both fail on win32

### ISSUE THREAD

**Issue by ipython** [ipython/ipython#87]
Original Launchpad bug 366982: https://bugs.launchpad.net/ipython/+bug/366982
Reported by: ellisonbg (Brian Granger).

These files are in testing.plugin and they fail on win32 because they make calls to the shell using unix commands like echo, rm, ls, etc.

These tests are currently being skipped by hand in iptest, but these tests should be made cross platform.

**Comment by Carreau** [comment]
This is not relevant anymore, these files do not exists. Closing.
