### ISSUE TITLE
nbconvert --to slides --post fails to serve pages

### ISSUE THREAD

**Issue by dov** [ipython/ipython#8700]
One day prior to me giving a lecture with ipython slides, did https://cdn.jsdelivr.net/reveal.js/2.5.0 return a 403 error. I then tried to follow the instructions on 

http://www.damian.oquanta.info/posts/using-a-local-revealjs-library-with-your-ipython-slides.html

but I don't see any slides! Only the css background.

Here is the command and its output:
> ipython nbconvert --to slides --post serve Untitled0.ipynb 
[NbConvertApp] Using existing profile dir: u'/home/dov/.ipython/profile_default'
[NbConvertApp] Converting notebook Untitled0.ipynb to slides
[NbConvertApp] Support files will be in Untitled0_files/
[NbConvertApp] Loaded template slides_reveal.tpl
[NbConvertApp] Writing 183799 bytes to Untitled0.slides.html
[NbConvertApp] Redirecting reveal.js requests to https://cdn.jsdelivr.net/reveal.js/2.5.0
Serving your slides at http://127.0.0.1:8000/Untitled0.slides.html
Use Control-C to stop this server
Created new window in existing browser session. 

But again, I don't get any slides. 

I guess that I will be using a single html page for
 my presentation tomorrow. :-(

**Comment by jimaek** [comment]
https://cdn.jsdelivr.net/reveal.js/2.5.0 is the version path, the filename is missing
http://www.jsdelivr.com/#!reveal.js

**Comment by dov** [comment]
Perhaps my analysis of the problem was wrong, but I still fail to load local reveal.js . Further analysis shows that I get an error in the javascript window that seems to be related to:

https://github.com/jupyter/nbconvert/pull/62

I.e. when `Reveal.initialize()` is called, it has not yet been defined. I somehow managed to edit the html so that the error does not happen and my slides appear. :-) My presentation is saved tomorrow. 

But there definitely is a race between the external script and the internal call to `Reveal.initialize()`

**Comment by takluyver** [comment]
What version of reveal did you download? I think this was a problem specifically when using newer versions.

Ping @damianavila

**Comment by dov** [comment]
I cloned the git repo, and then checked out tag 2.5.0 to match the default
version used by ipython 2.4.1 .

**Comment by damianavila** [comment]
Maybe related with this: https://github.com/ipython/ipython/issues/7829

Are you using conda/anaconda? Can you check if certifi is installed? Also... can you post the JS console error?

**Comment by dov** [comment]
No, I'm working under Fedora 22 with default python packages.

I'll provide the exact console message later, but basically it was that
"Reveal.initialize is not defined".

I managed to work around it by wrapping it as follows:

requirejs(["reveal.js/js/reveal.js"], function(Reveal) {
    // Full list of configuration options available here:
https://github.com/hakimel/reveal.js#configuration
    Reveal.initialize({
    controls: true,
:
});

Even though this made my slides appear, I still get errors from the
javascript console. I'll post the exact errors when I have more time.


Dov

**Comment by takluyver** [comment]
@damianavila can this be closed, or should it be migrated to nbconvert?

**Comment by damianavila** [comment]
This is pretty old... nad IIRC, it was solved in nbconvert itself, so let's close.

**Comment by dov** [comment]
Indeed I checked with the latest version of ipython on my Fedora 23 system and it is ok now.

**Comment by amitsaha** [comment]
Hi all, I am using `jupyter-nbconvert` installed via Anaconda. I am trying to create my first ever slide show using this toolset:

```
$ ~/anaconda3/bin/jupyter-nbconvert --post serve --to slides dmwp-slides.ipynb 
```

I tried Reveal-3.3, and 2.6.2 as well. On the browser, I get ``Uncaught TypeError: Cannot read property 'initialize' of undefined``. I suspect it's the same issue?

My notebook is here: https://github.com/doingmathwithpython/pycon-us-2016/blob/master/notebooks/slides.ipynb

**Comment by takluyver** [comment]
@amitsaha the latest version of nbconvert is 4.2.0 - can you upgrade and see if you still see the problem?

**Comment by amitsaha** [comment]
@takluyver magically, that solved the issue. Thanks. However I am getting some 404 in the console:

```
http://127.0.0.1:8000/custom.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://127.0.0.1:8000/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
http://127.0.0.1:8000/custom.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

Any thoughts on those?

**Comment by takluyver** [comment]
Ignore them - you can use `custom.css` to customise styles, but it's fine if it's not there. `favicon.ico` is something browsers try to load for every site (to put an icon in the tab bar), but again, it's not necessary.

**Comment by jeevan-kr** [comment]
Facing the same problem even after upgrading nbconvert through
`pip install jupyter --upgrade`

**Comment by juanjosegarciaripoll** [comment]
This problem is back. I created an empty notebook with just a Markdown title and could not export it to slides. The resulting file failed with "Cannot read property 'initialize' of undefined" both on Chrome and on Edge. My version of nbconvert from Anaconda 5.3.1
