### ISSUE TITLE
Maintaining order of entries in ipython_config.py

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#8702]
Currently, the order of entries in `ipython_config.py` (and friends) varies from instantiation to instantiation (just run `ipython profile create` twice to check this), which makes it a little tedious to merge changes between two independently written config files.

Certainly not a big deal but maintaining a consistent order (e.g. sorted) would be better.

**Comment by minrk** [comment]
Should be fixed by ipython/traitlets#62
