### ISSUE TITLE
Long notebook cell output hangs Jupyter

### ISSUE THREAD

**Issue by sakvaua** [ipython/ipython#8703]
One of my notebooks has a pretty long cell output which seems to make Jupyter unresponsive. In ipynb it takes more than 64k lines and I had to manually cut all of the cell output contents so that "outputs": [] to bring it back to life. The bug appears on both 3.2.0 and 3.2.1 versions and on both Windows and Mac.
This is my first bug report. Please be gentle.

**Comment by minrk** [comment]
@sakvaua thanks, this is a longstanding issue open as #6516, so I'll close here. We are investigation various mitigations.
