### ISSUE TITLE
Image update in Markdown

### ISSUE THREAD

**Issue by choies1** [ipython/ipython#8704]
If I add a local image using following command in Markdown, it works well.

![image](https://cloud.githubusercontent.com/assets/10408785/9154119/5aab32cc-3ebc-11e5-9937-54b26e9ec0d4.png)

However, the image from markdown is not updated after I changed the image using same file name.

If I change the image file name, the image from markdown is updated.

Please let me know how I can update the image using markdown in IPython.

My software versions are as follows.

Software |Version
------------ | -------------
Python |	3.4.3 32bit [MSC v.1600 32 bit (Intel)]
IPython |	3.2.0
OS |	Windows 7 6.1.7601 SP1

**Comment by jakobgager** [comment]
You could use a query string added to the filename as proposed e.g. [here](http://stackoverflow.com/a/31036847/2870069) or [here](http://stackoverflow.com/a/126831/2870069)

**Comment by takluyver** [comment]
Closing as most likely a browser caching issue. If there's anything we can do to help it, please reopen in the jupyter/notebook repo.
