### ISSUE TITLE
block keyword to pylab.show raises exception in IPython notebook

### ISSUE THREAD

**Issue by guyer** [ipython/ipython#8705]
IPython 3.2.0-8b0eef4 raises `TypeError: show() got an unexpected keyword argument 'block'` on:
```python
In[] %matplotlib inline
In[] from matplotlib import pylab
In[] pylab.show(block=True)
```

 `pylab.show` documents:
> A single experimental keyword argument, *block*, may be
> set to True or False to override the blocking behavior
> described above.

Note that in my actual use case, the `pylab.show(block=True)` statement is buried in some internal visualization code that has worked in IPython notebook for a long time.

```python
{'commit_hash': u'8b0eef4',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/guyer/anaconda/envs/py2_7/lib/python2.7/site-packages/IPython',
 'ipython_version': '3.2.0',
 'os_name': 'posix',
 'platform': 'Darwin-13.4.0-x86_64-i386-64bit',
 'sys_executable': '/Users/guyer/anaconda/envs/py2_7/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '2.7.10 |Anaconda 2.3.0 (x86_64)| (default, May 28 2015, 17:04:42) \n[GCC 4.2.1 (Apple Inc. build 5577)]'}
```

matplotlib 1.4.3

**Comment by Carreau** [comment]
See ipykernel/pull#54 for a potential fix.
