### ISSUE TITLE
completion when a variable has the same name as a magic

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#8707]
After importing matplotlib, `matplotl<tab>` repeatedly yields the completions `matplotlib` and `%matplotlib`, which is a bit awkward to use (and similarly with other name collisions).  I would suggest completing to `matplotlib` while still printing the two completion possibilities.

**Comment by anntzer** [comment]
Seems to be solved now.  Feel free to close.

**Comment by takluyver** [comment]
Thanks Anthony :-)
