### ISSUE TITLE
getpass in qtconsole echos password to console

### ISSUE THREAD

**Issue by airdrik** [ipython/ipython#8712]
I very much appreciate the work that has been done to support getpass in recent versions of ipython, and it works well in the ipython notebook.
When I tried using it in ipython qtconsole, it echoed the password to the screen which is a big problem (thankfully no one was watching and I was able to clear the screen soon thereafter).

I'm using python 3.4.0, ipython 3.2.1, qt 4.8.5, Ubuntu 14.04

**Comment by Carreau** [comment]
This probably should be moved [there](https://github.com/jupyter/qtconsole), I doubt we will fix it, but we can print a warning.

**Comment by minrk** [comment]
Warning added to qtconsole.
