### ISSUE TITLE
msgpack fails check on Python 3.4

### ISSUE THREAD

**Issue by jseabold** [ipython/ipython#8713]
The check in IPython.kernel.zmq.session.Session._check_packers seems to fail for me in IPython 3.2.1 on Python 3.4. Looks to be a strings vs. bytes issue.

```
In [6]: msg = dict(a=[1, 'hi'])

In [7]: pack = msgpack.packb

In [8]: unpack = msgpack.unpackb

In [9]: pack(msg)
Out[9]: b'\x81\xa1a\x92\x01\xa2hi'

In [10]: unpack(pack(msg))
Out[10]: {b'a': [1, b'hi']}

In [11]: msg
Out[11]: {'a': [1, 'hi']}

In [12]: unpack(pack(msg)) == msg
Out[12]: False

In [13]: msgpack.version
Out[13]: (0, 4, 6)
```

**Comment by jseabold** [comment]
Needs an encoding I guess?

**Comment by minrk** [comment]
Yeah, this is annoying and I opened msgpack/msgpack-python#99 about it a while ago. I've still had it working, but I don't remember exactly what the incantation is.

**Comment by minrk** [comment]
@jseabold I just made [umsgpack](https://pypi.python.org/pypi/umsgpack), which is a thin wrapper around msgpack that makes it distingush text and bytes by default. So you can use:

```python
c.Session.packer = 'umsgpack.packb'
c.Session.unpacker = 'umsgpack.unpackb'
```

and it should work on Python 3.

**Comment by jseabold** [comment]
Ha, thanks. This was pretty much my solution minus the packaging framework.

**Comment by jseabold** [comment]
Might be nice to raise a helpful error message pointing to this package under Python 3?
