### ISSUE TITLE
Notebook error after installing Jupyter

### ISSUE THREAD

**Issue by ppau1** [ipython/ipython#8723]
I just upgraded Jupyter using "pip install --upgrade jupyter". After doing that I am unable to launch Jupyer or IPython notebooks. It seems that the notebook is unable to find a kernel, and opening an existing notebook results in the error message "404 : Not Found".
The output in the Terminal is:

[I 17:07:51.654 NotebookApp] Serving notebooks from local directory: /Users/paupereira/Dropbox/python/econ_simulation
[I 17:07:51.654 NotebookApp] 0 active kernels
[I 17:07:51.654 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 17:07:51.654 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

I am using the Anaconda distribution of Python 2.7.

**Comment by takluyver** [comment]
Do you get any messages in the terminal when you try to open a notebook file?

**Comment by ppau1** [comment]
@takluyver Only the message I copied above.

**Comment by takluyver** [comment]
Can you run with `jupyter notebook --debug`?

**Comment by ppau1** [comment]
Sure. This is the output I get in the terminal.
⚡ jupyter notebook --debug
[D 18:53:16.745 NotebookApp] Config changed:
[D 18:53:16.745 NotebookApp] {'NotebookApp': {'log_level': 10}}
[D 18:53:16.745 NotebookApp] Searching [u'/Users/jsmith', '/Users/jsmith/.jupyter', '/Users/jsmith/anaconda/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 18:53:16.745 NotebookApp] Attempting to load config file jupyter_config.py in path /etc/jupyter
[D 18:53:16.745 NotebookApp] Attempting to load config file jupyter_config.json in path /etc/jupyter
[D 18:53:16.746 NotebookApp] Attempting to load config file jupyter_config.py in path /usr/local/etc/jupyter
[D 18:53:16.746 NotebookApp] Attempting to load config file jupyter_config.json in path /usr/local/etc/jupyter
[D 18:53:16.746 NotebookApp] Attempting to load config file jupyter_config.py in path /Users/jsmith/anaconda/etc/jupyter
[D 18:53:16.746 NotebookApp] Attempting to load config file jupyter_config.json in path /Users/jsmith/anaconda/etc/jupyter
[D 18:53:16.746 NotebookApp] Attempting to load config file jupyter_config.py in path /Users/jsmith/.jupyter
[D 18:53:16.746 NotebookApp] Attempting to load config file jupyter_config.json in path /Users/jsmith/.jupyter
[D 18:53:16.746 NotebookApp] Attempting to load config file jupyter_config.py in path /Users/jsmith
[D 18:53:16.746 NotebookApp] Attempting to load config file jupyter_config.json in path /Users/jsmith
[D 18:53:16.747 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /etc/jupyter
[D 18:53:16.747 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /etc/jupyter
[D 18:53:16.747 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /usr/local/etc/jupyter
[D 18:53:16.747 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /usr/local/etc/jupyter
[D 18:53:16.747 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /Users/jsmith/anaconda/etc/jupyter
[D 18:53:16.747 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /Users/jsmith/anaconda/etc/jupyter
[D 18:53:16.747 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /Users/jsmith/.jupyter
[D 18:53:16.747 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /Users/jsmith/.jupyter
[D 18:53:16.747 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /Users/jsmith
[D 18:53:16.747 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /Users/jsmith
[I 18:53:16.778 NotebookApp] The port 8888 is already in use, trying another random port.
[I 18:53:16.782 NotebookApp] Serving notebooks from local directory: /Users/jsmith
[I 18:53:16.782 NotebookApp] 0 active kernels
[I 18:53:16.782 NotebookApp] The IPython Notebook is running at: http://localhost:8889/
[I 18:53:16.782 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[D 18:53:17.196 NotebookApp] Using contents: services/contents
[D 18:53:17.224 NotebookApp] 200 GET /tree (::1) 30.15ms
[D 18:53:17.372 NotebookApp] 304 GET /custom/custom.css (::1) 5.88ms
[D 18:53:17.780 NotebookApp] 200 GET /static/services/contents.js?v=20150812185316 (::1) 0.74ms
[D 18:53:17.785 NotebookApp] 200 GET /custom/custom.js?v=20150812185316 (::1) 0.64ms
[D 18:53:17.846 NotebookApp] 200 GET /api/config/tree?_=1439419997482 (::1) 0.73ms
[D 18:53:17.852 NotebookApp] 200 GET /api/config/common?_=1439419997483 (::1) 1.12ms
[D 18:53:17.858 NotebookApp] 200 GET /api/terminals?_=1439419997484 (::1) 0.45ms
[D 18:53:17.862 NotebookApp] Found kernel python2 in /Users/jsmith/Library/Jupyter/kernels
[D 18:53:17.863 NotebookApp] Found kernel ir in /Users/jsmith/Library/Jupyter/kernels
[D 18:53:17.863 NotebookApp] Found kernel julia 0.3 in /Users/jsmith/Library/Jupyter/kernels
[D 18:53:17.863 NotebookApp] Found kernel python2 in /Users/jsmith/Library/Jupyter/kernels
[D 18:53:17.863 NotebookApp] Found kernel ir in /Users/jsmith/Library/Jupyter/kernels
[D 18:53:17.863 NotebookApp] Found kernel julia 0.3 in /Users/jsmith/Library/Jupyter/kernels
[D 18:53:17.864 NotebookApp] Found kernel python2 in /Users/jsmith/Library/Jupyter/kernels
[D 18:53:17.864 NotebookApp] Found kernel ir in /Users/jsmith/Library/Jupyter/kernels
[D 18:53:17.864 NotebookApp] Found kernel julia 0.3 in /Users/jsmith/Library/Jupyter/kernels
[D 18:53:17.865 NotebookApp] Found kernel python2 in /Users/jsmith/Library/Jupyter/kernels
[D 18:53:17.865 NotebookApp] Found kernel ir in /Users/jsmith/Library/Jupyter/kernels
[D 18:53:17.865 NotebookApp] Found kernel julia 0.3 in /Users/jsmith/Library/Jupyter/kernels
[D 18:53:17.866 NotebookApp] 200 GET /api/kernelspecs (::1) 4.37ms
[D 18:53:17.868 NotebookApp] 200 GET /api/sessions?_=1439419997485 (::1) 1.31ms
[D 18:53:17.871 NotebookApp] 200 GET /api/terminals?_=1439419997486 (::1) 0.42ms
[W 18:53:17.934 NotebookApp] /Users/jsmith/sublime doesn't exist
[D 18:53:17.935 NotebookApp] 200 GET /api/contents?type=directory&_=1439419997487 (::1) 15.34ms

**Comment by takluyver** [comment]
There's nothing obviously wrong there, though the `/Users/jsmith/sublime doesn't exist` is a bit puzzling.

Can you show a screenshot of the problem in the browser? And open up the JS console in your browser, it may have some more information.

**Comment by ppau1** [comment]
The following file (npm-debug.log) has been created in one of the folders from which I was trying to launch the notebook:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install' ]
2 info using npm@2.11.2
3 info using node@v0.12.5
4 verbose readDependencies loading dependencies from /Users/jsmith/Dropbox/python/econ_simulation/package.json
5 error install Couldn't read dependencies
6 verbose stack Error: ENOENT, open '/Users/jsmith/Dropbox/python/econ_simulation/package.json'
6 verbose stack     at Error (native)
7 verbose cwd /Users/jsmith/Dropbox/python/econ_simulation
8 error Darwin 14.3.0
9 error argv "node" "/usr/local/bin/npm" "install"
10 error node v0.12.5
11 error npm  v2.11.2
12 error path /Users/jsmith/Dropbox/python/econ_simulation/package.json
13 error code ENOPACKAGEJSON
14 error errno -2
15 error package.json ENOENT, open '/Users/jsmith/Dropbox/python/econ_simulation/package.json'
15 error package.json This is most likely not a problem with npm itself.
15 error package.json npm can't find a package.json file in your current directory.
16 verbose exit [ -2, true ]

**Comment by ppau1** [comment]
This is a screenshot a the stuck notebook:
![image](https://cloud.githubusercontent.com/assets/5409044/9239135/e91d4aec-4126-11e5-97f4-fc6f20b928e7.png)

**Comment by takluyver** [comment]
I think the npm stuff is irrelevant - if you're installing from PyPI, it shouldn't be trying to do anything with npm.

It looks like your custom.js may be causing the problem. Can you try removing or renaming that and then trying again? Though we should also ensure that a broken custom.js can't break the whole notebook like that.

**Comment by ppau1** [comment]
I renamed custom.js at ~/.ipython/profile_default/static/custom, and tried to run the notebook again.
This is the output in the terminal now:

⚡ jupyter notebook
[I 19:46:13.087 NotebookApp] Serving notebooks from local directory: /Users/paupereira/Dropbox/python/econ_simulation
[I 19:46:13.087 NotebookApp] 0 active kernels
[I 19:46:13.087 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 19:46:13.087 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 19:46:24.644 NotebookApp] 404 GET /static/components/backbone/backbone-min.map (::1) 6.21ms referer=None

**Comment by takluyver** [comment]
and do you see the same thing in the notebook? Anything in the JS console?

**Comment by ppau1** [comment]
The notebook and the JS console remain exactly the same.

**Comment by takluyver** [comment]
If it still has that error message about `load_extension`, that suggests that it's still seeing your custom.js somehow.

**Comment by ppau1** [comment]
That's strange. Did I renamed the right custom.js file, at ~/.ipython/profile_default/static/custom ?

**Comment by takluyver** [comment]
That sounds right. Maybe your browser has it cached, though. Try to open a notebook, then hit Ctrl-F5 a few times to force-refresh it.

**Comment by Carreau** [comment]
That also look strangely like there is a old server running and you are just hittign the wrong URL and the old server. 

The new custom js should be in JuypyterSomething not IPythonSomething.

**Comment by ppau1** [comment]
Good point! I found the new custom.js file at ~/.jupyter/custom.

It contained the following lines from ICalico notebook tools I had installed before the Jupyter update:

$([IPython.events]).on("app_initialized.NotebookApp", function () {
    IPython.load_extensions("toc");
});

$([IPython.events]).on("app_initialized.NotebookApp", function () {
    IPython.load_extensions("gist");
});

$([IPython.events]).on("app_initialized.NotebookApp", function () {
    IPython.load_extensions('calico-spell-check', 'calico-document-tools', 'calico-cell-tools');
});

After I commented them out I was able to get the notebook working with "jupyter notebook".

Thank you guys for your help!

**Comment by takluyver** [comment]
Aha - yes, we have some migration code that copies your old ipython config to jupyter when you first launch the new version. Glad it's working now.
