### ISSUE TITLE
ipython crash

### ISSUE THREAD

**Issue by nxzwt** [ipython/ipython#8725]
```
wt@mylinux:~> ipython notebook
/usr/lib/python2.7/site-packages/IPython/paths.py:54: UserWarning: Moving ~/.config/ipython to ~/.ipython
  warn('Moving {0} to {1}'.format(cu(xdg_ipdir), cu(ipdir)))
[I 17:42:47.743 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 17:42:48.033 NotebookApp] Serving notebooks from local directory: /home/zhangwt
[I 17:42:48.033 NotebookApp] 0 active kernels 
[I 17:42:48.033 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 17:42:48.033 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Traceback (most recent call last):
  File "/usr/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/lib/python2.7/site-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/lib/python2.7/site-packages/traitlets/config/application.py", line 592, in launch_instance
    app.start()
  File "/usr/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 349, in start
    return self.subapp.start()
  File "/usr/lib/python2.7/site-packages/notebook/notebookapp.py", line 1087, in start
    self.io_loop = ioloop.IOLoop.current()
AttributeError: type object 'IOLoop' has no attribute 'current'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
=====================================
```

using opensuse 13.1
python =2.7.8
ipython = 4.0

**Comment by takluyver** [comment]
What versions of tornado and pyzmq do you have? Ensure they're both up to date.

**Comment by nxzwt** [comment]
tornado = 4.2.1
pyzmq = 14.7.0

thanks!

**Comment by minrk** [comment]
What's sys.path?

**Comment by nxzwt** [comment]
as you can see:
File "/usr/lib/python2.7/site-packages/notebook/notebookapp.py", line 1087, in start
    self.io_loop = ioloop.IOLoop.current()
AttributeError: type object 'IOLoop' has no attribute 'current'

i guess that someting is wrong with IOloop,but i have upgrade ioloop package

**Comment by nxzwt** [comment]
>>> import sys
>>> print sys.path
['', '/usr/lib/python2.7/site-packages/virtualenv-12.0.5-py2.7.egg', '/usr/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg', '/usr/lib/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/local/lib64/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/gtk-2.0', '/usr/lib/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/wx-2.8-gtk2-unicode']

**Comment by minrk** [comment]
IOLoop is part of tornado, and means that either tornado or pyzmq is probably older than what you have listed, most likely due to weird setuptools behavior. What do you get from:

    python -c "import zmq; print zmq.__file__, zmq.__version__"
    python -c "import tornado; print tornado.__file__, tornado.version"

**Comment by nxzwt** [comment]
mylinux:/usr/lib/python2.7/site-packages # python -c "import zmq; print zmq.__file__, zmq.__version__"
zmq/__init__.pyc 14.7.0
mylinux:/usr/lib/python2.7/site-packages # python -c "import tornado; print tornado.__file__, tornado.version"
tornado/__init__.pyc 4.2.1
mylinux:/usr/lib/python2.7/site-packages #

**Comment by nxzwt** [comment]
opensuse13.1 use ipython 1.0 as defautl,,it's OK.I installed pip and upgrade ipython to 4.0,then ipython notebook crash .
if i use ipython only( not with notebook),it works fine.

**Comment by nxzwt** [comment]
mylinux:/usr/lib/python2.7/site-packages # pip install --upgrade notebook
Requirement already up-to-date: notebook in /usr/lib/python2.7/site-packages
Requirement already up-to-date: traitlets in /usr/lib/python2.7/site-packages (from notebook)
/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: tornado>=4 in /usr/lib/python2.7/site-packages (from notebook)
Requirement already up-to-date: jupyter-client in /usr/lib/python2.7/site-packages (from notebook)
Requirement already up-to-date: nbformat in /usr/lib/python2.7/site-packages (from notebook)
Requirement already up-to-date: jupyter-core in /usr/lib/python2.7/site-packages (from notebook)
Requirement already up-to-date: jinja2 in /usr/lib/python2.7/site-packages (from notebook)
Requirement already up-to-date: ipykernel in /usr/lib/python2.7/site-packages (from notebook)
Requirement already up-to-date: terminado>=0.3.3 in /usr/lib/python2.7/site-packages (from notebook)
Requirement already up-to-date: ipython-genutils in /usr/lib/python2.7/site-packages (from notebook)
Requirement already up-to-date: nbconvert in /usr/lib/python2.7/site-packages (from notebook)
Requirement already up-to-date: decorator in /usr/lib/python2.7/site-packages (from traitlets->notebook)
Requirement already up-to-date: certifi in /usr/lib/python2.7/site-packages (from tornado>=4->notebook)
Requirement already up-to-date: backports.ssl-match-hostname in /usr/lib/python2.7/site-packages (from tornado>=4->notebook)
Requirement already up-to-date: pyzmq>=13 in /usr/lib/python2.7/site-packages (from jupyter-client->notebook)
Requirement already up-to-date: jsonschema!=2.5.0,>=2.0 in /usr/lib/python2.7/site-packages (from nbformat->notebook)
Requirement already up-to-date: MarkupSafe in /usr/lib/python2.7/site-packages (from jinja2->notebook)
Requirement already up-to-date: ipython>=4.0.0 in /usr/lib/python2.7/site-packages (from ipykernel->notebook)
Requirement already up-to-date: ptyprocess in /usr/lib/python2.7/site-packages (from terminado>=0.3.3->notebook)
Requirement already up-to-date: pygments in /usr/lib/python2.7/site-packages (from nbconvert->notebook)
Requirement already up-to-date: mistune!=0.6 in /usr/lib/python2.7/site-packages (from nbconvert->notebook)
Requirement already up-to-date: functools32 in /usr/lib/python2.7/site-packages (from jsonschema!=2.5.0,>=2.0->nbformat->notebook)
Requirement already up-to-date: simplegeneric>0.8 in /usr/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel->notebook)
Requirement already up-to-date: pexpect in /usr/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel->notebook)
Requirement already up-to-date: pickleshare in /usr/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel->notebook)
Requirement already up-to-date: path.py in /usr/lib/python2.7/site-packages (from pickleshare->ipython>=4.0.0->ipykernel->notebook)
mylinux:/usr/lib/python2.7/site-packages #

**Comment by nxzwt** [comment]
mylinux:/usr/lib/python2.7/site-packages # ipython
Python 2.7.6 (default, Nov 21 2013, 15:55:38) [GCC]
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import sys

In [2]: print sys.path
['', '/usr/bin', '/usr/lib/python2.7/site-packages/virtualenv-12.0.5-py2.7.egg', '/usr/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg', '/usr/lib/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/local/lib64/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/gtk-2.0', '/usr/lib/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/wx-2.8-gtk2-unicode', '/usr/lib/python2.7/site-packages/IPython/extensions', '/root/.ipython']

In [3]:

**Comment by nxzwt** [comment]
mylinux:/usr/lib/python2.7/site-packages # ipython
Python 2.7.6 (default, Nov 21 2013, 15:55:38) [GCC]
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import ioloop

In [2]: f=ioloop.IOLoop.current()

In [3]: print f
<ioloop.IOLoop object at 0x2eb3ad0>

In [4]:

**Comment by nxzwt** [comment]
in  File "/usr/lib/python2.7/site-packages/notebook/notebookapp.py", there is a line:
from zmq.eventloop import ioloop

what different from zmq and pyzmq?

mylinux:/usr/lib/python2.7/site-packages # ipython
Python 2.7.6 (default, Nov 21 2013, 15:55:38) [GCC]
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from zmq.eventloop import ioloop

In [2]: f = ioloop.IOLoop.current()

In [3]: type f
  File "<ipython-input-3-137204f75e1b>", line 1
    type f
         ^
SyntaxError: invalid syntax


In [4]: print f
<tornado.platform.epoll.EPollIOLoop object at 0x28cd650>

In [5]:

**Comment by nxzwt** [comment]
In [5]:tornado.platform.epoll.EPollIOLoop object at 0x28cd650

**Comment by minrk** [comment]
Something's getting mixed up, because the absence of `IOLoop.current` definitely means an old tornado (<3, I believe) is being imported.

When you are doing the check for the tornado version, make sure you are not in the site-packages dir when you run it.

**Comment by nxzwt** [comment]
ylinux:~ # python -c "import zmq; print zmq.__file__, zmq.__version__"
/usr/lib64/python2.7/site-packages/zmq/__init__.pyc 13.0.0
mylinux:~ # python -c "import tornado; print tornado.__file__, tornado.version"
/usr/lib/python2.7/site-packages/tornado/__init__.pyc 4.2.1
mylinux:~ # pwd
/root
mylinux:~ # 

the version of zmq change to 13.0.0
the path change to "/usr/lib64/python2.7"

**Comment by nxzwt** [comment]
thank you very much,minrk,you are right.

i delte this directory "/usr/lib64/python2.7/site-packages/zmq",then "ipython notebook ",it works fine.
i think "/usr/lib64/python2.7/site-packages/zmq" was chosed first than "/usr/lib/python2.7/site-packages/zmq".
