### ISSUE TITLE
ipython/notebook :  c.NotebookApp.base_url not taken into account on ipython

### ISSUE THREAD

**Issue by chene-vert** [ipython/ipython#8726]
Preliminary remarque for ipython 4.0.0:  

`ipython profile create` creates only 

 * ipython_config.py
 * ipython_kernel_config.py
  
=> **ipython_notebook_config.py** is not created anymore using ipython **4.0.0**

When using previous `ipython_notebook_config.py`.
  **c.NotebookApp.base_url= '/toto/** is not taken into account

The notebook can only be accessed using usual path `notebooks/...` and not `toto/notebooks/...`

I can't make this work on ipython 3.2.1 or 4.0.0

**Comment by takluyver** [comment]
The config file is now (as of 4.0) `~/.jupyter/jupyter_notebook_config.py`, and you can pre-fill it with commented out defaults by running `jupyter notebook --generate-config`.

We've split out the language independent parts to call them *Jupyter*, so IPython is now just the parts about running Python code.

**Comment by chene-vert** [comment]
Thank takluyver,

On windows, I made it work using : `python C:\Python27\Scripts\jupyter-notebook --generate-config`
