### ISSUE TITLE
"{0:#x}".format (0x123) doesnt return immediately

### ISSUE THREAD

**Issue by Maxime5** [ipython/ipython#8732]
Behavior observed with ipython 4.0 (but I had already it will a very old 1.x version)

I type 
"{0:#x}".format (0x123)
then I press the "enter" key, but instead of printing the string value and returning a new prompt, ipython asks for another input:

------------------------------------------------
In [9]: "{0:#x}".format (0x123)
   ...:     
Out[9]: '0x123'

-----------------------------------------------

When not using the "#x" formatter, the behavior is different, and seems correct to me:

------------------------------------------------
In [10]: "{0}".format (0x123)
Out[10]: '291'

------------------------------------------------

Regards,
Maxime

**Comment by takluyver** [comment]
Thanks, we're already tracking this as #2913  - it affects anything with `:#` inside a string.
