### ISSUE TITLE
Backward-compatible widgets import

### ISSUE THREAD

**Issue by danielballan** [ipython/ipython#8734]
Over at lmfit/lmfit-py#246, our NotebookFitter is failing on `from IPython.html.widgets import ...`.

We'll add a version-dependent import in our next release. But could you add a shim of the kind you [mentioned](http://blog.jupyter.org/2015/08/12/first-release-of-jupyter/) in the release announcement?

It occurs to me that this may have been an intentional choice because this particular shim will only work if ipywidgets is installed, and it would therefore be a little janky. How about something like `ImportError: Install ipywidgets.`? I can't decide if I think this is a good idea or not -- I defer to your judgement.

Let me know; I'm happy to write the PR.

cc @stonebig @newville

**Comment by stonebig** [comment]
heum, it doesn't fail yet, there is just this annoying 'deprecation warning', showing up for every package using widgets of IPython3.0

**Comment by Carreau** [comment]
We should already have a shim, so it shouldn't raise:

```
In [1]: import IPython.html.widgets
/~/dev/ipython/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
````

**Comment by newville** [comment]
@danielballan @Carreau (sorry for the dupe!)   I think a message pointing to ipywidgets would be helpful.

**Comment by Carreau** [comment]
@newville not sure what you mean, the warning does say `has moved to "ipywidgets"`.

**Comment by newville** [comment]
@Carreau -- The original report(s) did not show such a message, and simply reported

```python 
     21 else:
     22     # as of IPython 3.x:
---> 23     from IPython.html.widgets import Dropdown
     24     from IPython.html.widgets import Button
     25     from IPython.html.widgets import Box

ImportError: cannot import name Dropdown
```

**Comment by danielballan** [comment]
@newville Hmm. It seems like that report was wrong. I can't reproduce that, with or without `ipywidgets` installed. Closing, unless @stonebig has a reproducible way to generate that reported error. Sorry @Carreau.

**Comment by minrk** [comment]
It could be that when ipywidgets is unavailable it's not reporting the warning correctly.

**Comment by danielballan** [comment]
I tried both with and without ipywidgets. Seems OK.

**Comment by stonebig** [comment]
is there a simple magic option to shut the remaining "shim" warnings down ?

**Comment by Carreau** [comment]
> is there a simple magic option to shut the remaining "shim warnings" down ?

For archive : see post on [Jupyter google group](https://groups.google.com/forum/#!topic/jupyter/GVsCqxTMiNo).
