### ISSUE TITLE
After upgrade to jupyter can't start "jupyter notebook"

### ISSUE THREAD

**Issue by dartdog** [ipython/ipython#8746]
I just updated to jupyter from dev3 ipython.. I get this "jupyter notebook" does not work the "ipython notebook" command works...(both below) Ubuntu 14.04 my Ipython version now shows as 3.1.0-dev

tom@tom-sam:~$ jupyter notebook
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 83, in <module>
    from IPython.paths import get_ipython_dir
ImportError: No module named paths
tom@tom-sam:~$ ipython notebook
[I 14:18:10.186 NotebookApp] Using existing profile dir: u'/home/tom/.ipython/profile_default'
[I 14:18:12.027 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
[I 14:18:12.487 NotebookApp] Serving notebooks from local directory: /home/tom
[I 14:18:12.488 NotebookApp] 0 active kernels 
[I 14:18:12.488 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 14:18:12.488 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Created new window in existing browser session.

**Comment by minrk** [comment]
@dartdog I'm not sure how you got the notebook without upgrading IPython to 4.x, but upgrading should fix it. The IPython import should never have been there, so this should also be fixed by jupyter/notebook#313

**Comment by dartdog** [comment]
Well reran and got this? Stange...
tom@tom-sam:~$ sudo pip install --upgrade jupyter
[sudo] password for tom: 
The directory '/home/tom/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/tom/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: jupyter in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: notebook in /usr/local/lib/python2.7/dist-packages (from jupyter)
Requirement already up-to-date: ipywidgets in /usr/local/lib/python2.7/dist-packages (from jupyter)
Requirement already up-to-date: nbconvert in /usr/local/lib/python2.7/dist-packages (from jupyter)
Requirement already up-to-date: ipykernel in /usr/local/lib/python2.7/dist-packages (from jupyter)
Requirement already up-to-date: jupyter-console in /usr/local/lib/python2.7/dist-packages (from jupyter)
Requirement already up-to-date: qtconsole in /usr/local/lib/python2.7/dist-packages (from jupyter)
Requirement already up-to-date: traitlets in /usr/local/lib/python2.7/dist-packages (from notebook->jupyter)
Requirement already up-to-date: tornado>=4 in /usr/local/lib/python2.7/dist-packages (from notebook->jupyter)
Requirement already up-to-date: jupyter-client in /usr/local/lib/python2.7/dist-packages (from notebook->jupyter)
Requirement already up-to-date: nbformat in /usr/local/lib/python2.7/dist-packages (from notebook->jupyter)
Requirement already up-to-date: jupyter-core in /usr/local/lib/python2.7/dist-packages (from notebook->jupyter)
Requirement already up-to-date: jinja2 in /usr/local/lib/python2.7/dist-packages (from notebook->jupyter)
Requirement already up-to-date: terminado>=0.3.3 in /usr/local/lib/python2.7/dist-packages (from notebook->jupyter)
Requirement already up-to-date: ipython-genutils in /usr/local/lib/python2.7/dist-packages (from notebook->jupyter)
Collecting ipython>=4.0.0dev0 (from ipywidgets->jupyter)
  Downloading ipython-4.0.0-py2-none-any.whl (730kB)
    100% |████████████████████████████████| 733kB 712kB/s 
Requirement already up-to-date: pygments in /usr/local/lib/python2.7/dist-packages (from nbconvert->jupyter)
Requirement already up-to-date: mistune!=0.6 in /usr/local/lib/python2.7/dist-packages (from nbconvert->jupyter)
Requirement already up-to-date: decorator in /usr/local/lib/python2.7/dist-packages (from traitlets->notebook->jupyter)
Requirement already up-to-date: certifi in /usr/local/lib/python2.7/dist-packages (from tornado>=4->notebook->jupyter)
Requirement already up-to-date: backports.ssl-match-hostname in /usr/local/lib/python2.7/dist-packages (from tornado>=4->notebook->jupyter)
Requirement already up-to-date: pyzmq>=13 in /usr/local/lib/python2.7/dist-packages (from jupyter-client->notebook->jupyter)
Requirement already up-to-date: jsonschema!=2.5.0,>=2.0 in /usr/local/lib/python2.7/dist-packages (from nbformat->notebook->jupyter)
Requirement already up-to-date: MarkupSafe in /usr/local/lib/python2.7/dist-packages (from jinja2->notebook->jupyter)
Requirement already up-to-date: ptyprocess in /usr/local/lib/python2.7/dist-packages (from terminado>=0.3.3->notebook->jupyter)
Requirement already up-to-date: simplegeneric>0.8 in /usr/lib/python2.7/dist-packages (from ipython>=4.0.0dev0->ipywidgets->jupyter)
Requirement already up-to-date: pexpect in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0dev0->ipywidgets->jupyter)
Requirement already up-to-date: pickleshare in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0dev0->ipywidgets->jupyter)
Requirement already up-to-date: functools32 in /usr/local/lib/python2.7/dist-packages (from jsonschema!=2.5.0,>=2.0->nbformat->notebook->jupyter)
Requirement already up-to-date: path.py in /usr/local/lib/python2.7/dist-packages (from pickleshare->ipython>=4.0.0dev0->ipywidgets->jupyter)
Installing collected packages: ipython
  Found existing installation: ipython 3.0.0.dev0
    Can't uninstall 'ipython'. No files were found to uninstall.
Successfully installed ipython-3.0.0.dev0

**Comment by minrk** [comment]
This appears to be the problem:

> Can't uninstall 'ipython'. No files were found to uninstall.

pip seems to have confused itself. You may need to manually uninstall the existing IPython before pip will be able to properly upgrade.

**Comment by dartdog** [comment]
Would appreciate any hints as to manual uninstall? I get nervous in that world. (I only know that stuff somewhat vaguely) Thanks!

**Comment by Carreau** [comment]
I would 

```
$ ipython
...
In [1]: import IPython
In [2]: IPython?

Type:        module
String form: <module 'IPython' from '/Users/bussonniermatthias/dev/ipython/IPython/__init__.py'>
File:        ~/dev/ipython/IPython/__init__.py
...
```
nuke `~/dev/ipython` in my case. 

You might get something like `~/anaconda3/lib/python3.4/site-packages/ipython`
Or `.../something/site_package/ipython`, which should be OK to nuke. 
Yon can give us the path, we can tell you if it's ok.

**Comment by dartdog** [comment]
Wow I seem to be in way deep... Got this when I tried that! Fwiw ipython notebook is still working properly!
Appreciate the help!

tom@tom-sam:~$ ipython
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0-dev -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import ipython
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-68a5f6bbf1ac> in <module>()
----> 1 import ipython

ImportError: No module named ipython

In [2]: import Ipython
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-3baa07d1debf> in <module>()
----> 1 import Ipython

ImportError: No module named Ipython

**Comment by Carreau** [comment]
(did you delete your message ?) We can solve that on Gitter if you like.

**Comment by dartdog** [comment]
That did it! Thanks so much. I had the dev version of Ipython installed in the home directory, I renamed it and reran the install upgrade (which seemed to do nothing), but Jupyter now runs...

**Comment by Carreau** [comment]
great ! Can we close ?

**Comment by dartdog** [comment]
for sure..

**Comment by jondoesntgit** [comment]
As @dartdog mentioned, this solved it for me,

    sudo pip install --upgrade jupyter
