### ISSUE TITLE
Plotting in the Notebook.ipynb

### ISSUE THREAD

**Issue by scholfim** [ipython/ipython#8747]
Is "%matplotlib inline" still supported? I'm unable to get it to work.

From the terminal, I type "ipython notebook" and get the ipython notebook to open. Then in the notebook, I enter "%matplotlib inline" and an error is returned saying:
"UsageError: Invalid GUI request u'inline', valid ones are: pyglet, osx, qt5, qt, glut, gtk, gtk3, tk, wx"

System info:
ipython version :3.2.1
ipython-notebook version: 3.2.1
matplotlib 1.4.3
OS: MAC OS 10.10.4
my skill level is beginner 

![screen shot 2015-08-19 at 3 50 38 pm](https://cloud.githubusercontent.com/assets/13874172/9371041/25b54078-468a-11e5-95a1-54d54a17a031.jpg)

**Comment by Carreau** [comment]
The screenshot you show is not the notebook, it is the terminal. 
`inline` is not supported in the terminal as the terminal cannot show images. It should work in the notebook.

**Comment by Carreau** [comment]
(I closed the issue but you can still comment, and we can reopen is necessary)

**Comment by scholfim** [comment]
Hi Carreau,

Thank you, I feel very naive. I will continue with the tutorials. 
![screen shot 2015-08-20 at 8 38 24 am](https://cloud.githubusercontent.com/assets/13874172/9387765/f40a4cb6-4716-11e5-872b-a96c1e8ab312.jpg)

**Comment by Carreau** [comment]
Ok, great, have fun. 
If you have recent enough Matplotlib you can also try `%matplotlib notebook` :-)
