### ISSUE TITLE
Running JS extensions in Jupyter different than IPython NB?

### ISSUE THREAD

**Issue by dartdog** [ipython/ipython#8752]
Getting this?
maybe I need to move /reinstall some stuff?

```python
%%javascript
// does not work!
IPython.load_extensions('IPython-notebook-extensions/usability/python-markdown/main;)
```

Javascript error adding output!
ReferenceError: extensions is not defined
See your browser Javascript console for more details.

**Comment by Carreau** [comment]
You might need to move your extensions in ~/.jupyter/nbextensions. We'll need the error from the browser js console and a bit more info to help.

**Comment by juhasch** [comment]
I have tried to to compile how the new configuration works here: [IPython-contrib Wiki](https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/Home_Jupyter#so-where-can-i-find-things-now)
The official documentation is here:
https://jupyter.readthedocs.org/en/latest/system.html
 
@Carreau: Do you plan adding some documentation about this in your docs ?

**Comment by Carreau** [comment]
> @Carreau: Do you plan adding some documentation about this in your docs ?

Hum, with time, most likely.
With time I woudl also try to migrate my docs t official one once it gets better.

**Comment by dartdog** [comment]
Hmmm I reinstalled with a pip upgrade and the extensions are in /home/tom/.local/share/jupyter/nbextensions/IPython-notebook-extensions/usability (verified with LS in the notebook)
No errors on js console?

**Comment by dartdog** [comment]
got my confg fixed, basically deleting multiple versions of IPython NB that had accumulated, and doing a clean install of both Jupyter and NBextensions...

Good to close this and thanks to all for getting me pointed in the right direction...
