### ISSUE TITLE
Glitch when asking for confirmation to exit

### ISSUE THREAD

**Issue by Achifaifa** [ipython/ipython#8753]
When ipython (console) asks for confirmation to exit, it prints the message every time ctrl+c is pressed

![2015-08-21-001305_633x329_scrot](https://cloud.githubusercontent.com/assets/5968349/9397090/b20b0052-4799-11e5-8b4f-5f0e40895e4e.png)

Steps to replicate:
1.- Open ipython
2.- type 'ctrl+d' to exit
3.- When asked for confirmation, press 'ctrl+c'. The confirmation message will appear again every time you press ctrl+c

Expected result: ipython should either exit or cancel the exit promt and go back to normal operation.

I have no idea about what could be causing this.

**Comment by Achifaifa** [comment]
OK, I think I know what causes this, but I'm having issues getting ipython (From the repo) to work. I'll issue a PR as soon as I manage to fix it.

**Comment by Achifaifa** [comment]
Nevermind, I thought I knew how to fix it but I don't. I changed it in my install by replacing the calls to exit() with calls to ask_exit() in interactiveshell.py (Disables the confirmation prompt), but I understand that doesn't fix the problem

**Comment by Carreau** [comment]
in interactiveshell.py

    def exit(self):
        """Handle interactive exit.

        This method calls the ask_exit callback."""
        if self.confirm_exit:
            if self.ask_yes_no('Do you really want to exit ([y]/n)?','y'):
                self.ask_exit()
        else:
            self.ask_exit()


ask_yes_no does not have a third parameter so loop infinitely on Ctrl-C

def ask_yes_no(prompt, default=None, interrupt=None):
    """Asks a question and returns a boolean (y/n) answer.

    If default is given (one of 'y','n'), it is used if the user input is
    empty. If interrupt is given (one of 'y','n'), it is used if the user
    presses Ctrl-C. Otherwise the question is repeated until an answer is
    given.

    An EOF is treated as the default answer.  If there is no default, an
    exception is raised to prevent infinite loops.

    Valid answers are: y/yes/n/no (match is not case sensitive)."""


My guess is passing ‘no’ , or ‘yes' as third param should fix that. 
The question is which on is the right behavior people will expect. 

Do you want to attempt a PR ?

**Comment by Achifaifa** [comment]
It's not an important thing, so if you don't mind waiting for me to figure it out I can try to fix it. I was having issues getting the ipython from this repository to work (It kept launching the version I had installed on my system), but I should manage to make a PR in a few days.

**Comment by minrk** [comment]
@Achifaifa great! Looking forward to your PR.

**Comment by Achifaifa** [comment]
Well, that took... WAY less time than expected.
