### ISSUE TITLE
MathJax not rendering { n \choose k} correctly.

### ISSUE THREAD

**Issue by vsbuffalo** [ipython/ipython#8754]
Notebooks containing binomial coefficients in markdown cells no longer render binomial coefficients correctly. Instead, there's a 404:

    [W 16:55:41.491 NotebookApp] 404 GET /static/components/MathJax/extensions/TeX/mathchoice.js?rev=2.5.3 (::1) 6.92ms referer=http://localhost:8888/notebooks/x-ancestry.ipynb

and the image is displayed as following:

<img width="343" alt="screen shot 2015-08-20 at 4 21 46 pm" src="https://cloud.githubusercontent.com/assets/160549/9398577/702d8376-475d-11e5-9f7e-f17059bdddeb.png">.

I've confirmed this problem exists on a colleague's machine (Python 2.7.5) as well as my current machine:

    $ python -c "import IPython; print(IPython.sys_info())"

    {'commit_hash': u'7905947',
     'commit_source': 'installation',
     'default_encoding': 'UTF-8',
     'ipython_path': '/usr/local/lib/python2.7/site-packages/IPython',
     'ipython_version': '4.0.0-dev',
     'os_name': 'posix',
     'platform': 'Darwin-14.4.0-x86_64-i386-64bit',
     'sys_executable': '/usr/local/opt/python/bin/python2.7',
     'sys_platform': 'darwin',
     'sys_version': '2.7.9 (default, Feb 10 2015, 03:28:08) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]'}

**Comment by Carreau** [comment]
can you give the raw string of your math expression `{ n \choose k}` seem to work for me, so it might be smth else.

**Comment by NickiRom** [comment]
I am having the same issue.  In markdown I've tried the following, all of which provide the same output as indicated in the OP:

$\binom n k$

$\binom{n}{k}$

${n \choose k}$

**Comment by cedricvanrompay** [comment]
Same issue for me.

```
$ python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': 'f534027',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python3.4/dist-packages/IPython',
 'ipython_version': '4.0.0',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-62-generic-x86_64-with-Ubuntu-14.04-trusty',
 'sys_executable': '/usr/bin/python3',
 'sys_platform': 'linux',
 'sys_version': '3.4.0 (default, Jun 19 2015, 14:20:21) \n[GCC 4.8.2]'}```
```

```
In [1]: from IPython.external.mathjax import install_mathjax ; install_mathjax()
/home/cedricvr/.ipython/nbextensions/mathjax/MathJax.js already exists
Out[1]: 0
```

In the notebook I have a 404 for the same url than @vsbuffalo. However `mathchoice.js` is actually in the directory imported by `install_mathjax()`
```
$ ls .ipython/nbextensions/mathjax/extensions/TeX/ | grep mathchoice
mathchoice.js
```

As a quickfix, is there a way to force the notebook to get MathJax from the CDN ? I tried to remove `/home/cedricvr/.ipython/nbextensions/mathjax` but it did not change anything to the notebook (which could be a trail)

**Comment by Carreau** [comment]
try to remove the mathjax installed by `install_mathjax()` it is not necessary anymore with 4.0, `install_mathjax()` shoud do nothing a raise a deprecation, but it slipped through 4.0 release. 

I advise against getting mathjax from CDN as it might be a remote execution vulnerability, nto oeven sure it is configurable.

I'll like to find the root of the issue at it should be working:

<img width="327" alt="screen shot 2015-08-24 at 15 53 05" src="https://cloud.githubusercontent.com/assets/335567/9441779/5b06287c-4a78-11e5-9aeb-d567509ca39b.png">

**Comment by Carreau** [comment]
Note, I can reproduce on conda-4.0 in an env, so something might be different between dev- and non-dev install or this was fixed by a fix to an unrelate bug.

**Comment by Carreau** [comment]
And this is a difference between a -dev and plain install. If I don't make a dev-install I have te same issue. 
@minrk can this be due to the Mathjax  Components repo ?

**Comment by Carreau** [comment]
Jupyter/notebook#324 should fix it.

**Comment by bitlemon** [comment]
Same problem on the development version:
`[W 18:56:13.052 NotebookApp] 404 GET /static/components/MathJax/extensions/TeX/mathchoice.js?rev=2.5.3 (::1) 18.01ms referer=http://localhost:8888/notebooks/Untitled.ipynb`

![untitled](https://cloud.githubusercontent.com/assets/6962404/10532087/dceed1e4-736e-11e5-895f-de5c2c709942.png)

**Comment by Carreau** [comment]
You most likely had an issue with the install-part of the dev version. 
Did you try in an empty environment ?

**Comment by minrk** [comment]
I just tested and verified that this works in a new virtualenv:

    pip install git+https://github.com/jupyter/notebook#egg=notebook

Perhaps a clean checkout and reinstall?

**Comment by bitlemon** [comment]
Clean reinstall worked out.
