### ISSUE TITLE
ipython doesn't use custom profile when kernel is explicitly specified [windows]

### ISSUE THREAD

**Issue by Evfro** [ipython/ipython#8759]
I have a fresh python 2.7 conda installation with ipython 3.
I create new custom profile named "foo". I also explicitly create a copy of current kernel:
```
ipython kernelspec install-self --user
```
In order to make this kernel not ignored by ipython and visible in the list of kernels in a notebook I have to make 2 things:
1. rename the kernel display name to *"My Python 2"* (in the *kernel.json* file).
2. rename the kernel's folder from *python2* to anything else (otherwise ipython never picks it up)

Now, when I launch ipython notebook
`ipython notebook --profile=foo`
I can explicitly choose which kernel to use: default *"Python 2"* or newly created *"My Python 2"*.

**The problem:**
If I use default "Python 2" kernel, it stores logs and history in the *foo* profile as expected. However, when I choose *"My Python 2"* it doesn't pick up *foo* profile and uses default profile instead. It can be easily verified by checking the file *history.sqlite* located in the profile folder. This file is always created in the default profile whenever *"My Pytthon 2"* kernel is used and no matter what profile name was specified in the `--profile` key. It seems to me as a bug.

I've also noticed that when I use my custom kernel the value of ProfileDir is empty:
```
In[]: 
ip = IPython.get_ipython()
ip.config.ProfileDir

Out[]:
{}
```
And with default "Python 2" kernel it always returns correct location of *foo* profile as one would expect.

**Comment by Carreau** [comment]
I believe that might be the same bug as  https://github.com/jupyter/jupyter_client/pull/61.
You might need to modify your kernelspec to launch the kernel with the `--profile=foo` flag.

**Comment by Evfro** [comment]
Thanks for the great idea!
I tried to add `--profile=foo` to the end of argv:
```
"argv": [
  "python.exe", 
  "-m", 
  "IPython.kernel", 
  "-f", 
  "{connection_file}",
  "--profile=foo"
 ]
```
and it looks like it did the trick. However, in that case `ip.config.ProfileDir` is still empty. I'm not sure whether it affects anything. 
That lead me to the idea of directly adding `--ProfileDir.location=<path_to_the_foo_profile>` instead of `--profile=foo` and it looks like it works as well. So I wonder what is the most appropriate way?

And this way kernelspec becomes dependent on at least the profile name which is not really convenient and is hard to automate. Would be really great to have independent kernelspecs and specify profile only once as a flag to ipython notebook launch.

**Comment by minrk** [comment]
Why are you looking in `ip.config.ProfileDir`? If you want to know the profile directory, it's `ip.profile_dir.location`.

The `config` object is used to set up real objects, but it's not where anything is actually stored at runtime. It's not the place to lookup the current state.

**Comment by minrk** [comment]
> Would be really great to have independent kernelspecs and specify profile only once as a flag to ipython notebook launch.

This wouldn't make sense for the dozens of kernels that are not IPython. That's why we no longer relay notebook arguments to kernels. But we could add a mechanism for specifying extra args for the kernel. It may be tricky to do in a way that is safe, but should be doable and would be useful.

**Comment by Evfro** [comment]
@minrk, thanks for the info!

> Why are you looking in  ip.config.ProfileDir ?

It was not clear where to look in considering my specific problem. In order to understand why specifying the profile doesn't make any effect on where logs are stored I started to compare config parameters of 2 sessions: one within default profile and one within custom profile, both with same the custom kernelspec. And the first difference I could find was exactly the value of `ip.config.ProfileDir` as I described in the initial post.

> If you want to know the profile directory  it's  ip.profile_dir.location

My actual goal is to have ipython storing the history in the right place. If I put either  *--ProfileDir.location=\<path_to_the_foo_profile\>* or *--profile=foo* into the kernelspec it solves the problem, although I'm not a fan of such a hardcoding.
I'm not sure if I understand correctly, are you saying that's it's better/more safe to specify `ip.profile_dir.location` in the kernelspec rather than `ProfileDir.location` or `profile` until there's a better solution?

> we could add a mechanism for specifying extra args for the kernel

That's probably really what I wanted to say. I surely don't need to pass all flags from notebook to kernel. For my particular case I just need both ipython kernel and ipython notebook working in the same profile. I know the Big Split concept, but still it's a bit unintuitive for me why launching notebook like this:
`
ipython notebook --profile=foo
`
leads to notebook working in the foo profile and ipython kernel (with custom kernelspec) working in the default profile. It's important to emphasize that the problem happens only with custom kernel (which is identical to default kernel, except the display name). When I use default Python 2 kernel logs are stored in the `foo` profile as expected. So there's definitely a working mechanism, but it doesn't work with custom kernel for some reason.

**Comment by Evfro** [comment]
I also wonder whether the **env** argument can be used somehow for solving the problem without hardcoding profile name or profile path?

> env (optional): A dictionary of environment variables to set for the kernel. These will be added to the current environment variables before the kernel is started.

**Comment by Carreau** [comment]
With 4.0 the notebook does not have a notion of profile, you already have to set up env variable. And kernel should already be able to get extra env variable, so it should be possible to do something with that.


ip.config.ProfileDir vs ip.profile_dir.location the first is a class default, the second is the value of an instance. 

`--profile-dir` and `--ProfileDir.location` are aliases. `--profile` is like `--profile-dir` but you don't have to specify the full dir path.

**Comment by minrk** [comment]
Sorry, missed the actual goal. Specifying the kernel profile at the notebook command-line has actually stopped working with the current version of IPython/Jupyter (4.0), so the two kernels python2 and my-python2 will both use the default profile. The concept of profiles is not inherited by the Jupyter projects, so there is no `jupyter notebook --profile anything`.

I have been working on [a tool](https://github.com/minrk/a2km) to make it easier to manipulate kernelspecs, which would make things like adding and removing the profile arg to a kernel relatively easy:

```
a2km add-argv mykernel -- --profile foo
a2km rm-argv mykernel -- --profile foo
```

> I also wonder whether the env argument can be used somehow for solving the problem without hardcoding profile name or profile path?

The env will not have an effect on which profile is used, but even if it did, it would be the same as specifying the profile in argv, just a different field.

**Comment by Evfro** [comment]
Thanks for explanations to both of you! Sorry, I've been out for a while. I'll try to setup environmental variables and in case it's not very convenient to work with them I'll play with @minrk a2km tool, which looks like a very handy utility.
