### ISSUE TITLE
nbconvert citations not working for me

### ISSUE THREAD

**Issue by bramtayl** [ipython/ipython#8760]
I'm trying to use citations in IPython. I'm having some isssues.

My notebook has one markdown cell,

```
<cite data-cite="debreu_theory_1959">(Debreu, 1959)</cite>
```

My template looks like this:

```
((*- extends 'article.tplx' -*))

((* block bibliography *))
\bibliographystyle{unsrt}
\bibliography{bibliography}
((* endblock bibliography *))
```

And my bibliography has the section

```
@book{debreu_theory_1959,
  address = {New Haven, {CT}},
  title = {Theory of value: An axiomatic analysis of economic equilibrium},
  shorttitle = {Theory of value},
  url = {http://books.google.com/books?hl=en\&lr=\&id=QkX10epC46cC\&oi=fnd\&pg=PA1\&dq=debreau+theory+of+value\&ots=9DNz2653qg\&sig=fKS1CYQ6ZFmXIUmOgDq3DRLPEmQ},
  timestamp = {2014-04-17 14:32:20},
  number = {17},
  urldate = {2014-04-17},
  publisher = {Yale University Press},
  author = {Debreu, Gerard},
  year = {1959},
  file = {Snapshot:/home/haldane/.mozilla/firefox/8qzu92vh.default/zotero/storage/CIEI6RPS/books.html:text/html}
}
```

My command line call is

```
ipython3 nbconvert --to pdf bibliography.ipynb --template bibliography.tplx
```

The pdf is created, but all it contains is

```
[?]
```

Yes, bibliography.ipynb, bibliography.tplx, and bibliography.bib are all in the same folder.

**Comment by bramtayl** [comment]
Does a log exist somewhere? Everything that gets printed to the terminal seems pleasant enough:

[NbConvertApp] Config changed:
[NbConvertApp] {'NbConvertApp': {'log_level': 10, 'export_format': 'pdf'}, 'TemplateExporter': {'template_file': 'bibliography'}}
[NbConvertApp] IPYTHONDIR set to: /home/haldane/.ipython
[NbConvertApp] Using existing profile dir: '/home/haldane/.ipython/profile_default'
[NbConvertApp] Searching path ['/home/haldane/programming/IPython_Notebook', '/home/haldane/.ipython/profile_default', '/usr/local/etc/ipython', '/etc/ipython'] for config files
[NbConvertApp] Attempting to load config file: ipython_config.py
[NbConvertApp] Attempting to load config file: ipython_nbconvert_config.py
[NbConvertApp] Converting notebook bibliography.ipynb to pdf
[NbConvertApp] Notebook name is 'bibliography'
[NbConvertApp] Applying preprocessor: coalesce_streams
[NbConvertApp] Applying preprocessor: SVG2PDFPreprocessor
[NbConvertApp] Applying preprocessor: ExtractOutputPreprocessor
[NbConvertApp] Applying preprocessor: LatexPreprocessor
[NbConvertApp] Applying preprocessor: HighlightMagicsPreprocessor
[NbConvertApp] Attempting to load template bibliography.tplx
[NbConvertApp] Loaded template bibliography.tplx
[NbConvertApp] Writing 11865 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running pdflatex 3 times: ['pdflatex', 'notebook.tex']
[NbConvertApp] PDF successfully created
[NbConvertApp] Writing 45063 bytes to bibliography.pdf

**Comment by takluyver** [comment]
There isn't a separate log file created, but you can see lower level information with a `--debug` flag.
