### ISSUE TITLE
Formatted docs for magic functions

### ISSUE THREAD

**Issue by lmmx** [ipython/ipython#8762]
I was looking for documentation for the 'magic' functions online, but the [top hit](https://ipython.org/ipython-doc/dev/interactive/tutorial.html) on Google is a tutorial which briefly mentions some of them, and the next hit (which admittedly I only found now embarrassingly) looks right but is missing some (including the one I was originally looking up, hence why I didn't find it sooner).

`%autoindent`, `%cat` and `%clear` for example aren't there, I'm not sure the version they're from.

I did the `%magic` command to get the plaintext docs, and searched pieces of this on Google to try and find any formatted copy online but there wasn't,

* e.g. [searching the documentation for the `%cat` command](https://www.google.co.uk/search?q="Callable+object+storing+the+details+of+one+alias."+"Instances+are+registered+as+magic+functions+to+allow+use+of+aliases.") shows the developer docs, but finds nothing in a readable format.

...so I went ahead and turned the 'man pages' produced by the `%magic` command [into a markdown version](https://github.com/lmmx/devnotes/wiki/IPython-'magic'-function-documentation)

It looks like I may have wasted my time, as even though [that IPython list](https://ipython.org/ipython-doc/dev/interactive/magics.html) is outdated, it seems to have been processed in some way to properly format code blocks and regular `<pre>` elements within a nice `<dl>` definitions list — so I don't know if mine will actually be any use to you... :sweat_smile: was handy for me to read anyway.

( Also this may relate to the issue in the Jupyter repo: [issue 20](https://github.com/jupyter/jupyter/issues/20), for a subcommand to open formatted docs in a browser )

**Comment by Carreau** [comment]
So the relevant docs should now be here : http://ipython.readthedocs.org/en/stable/interactive/magics.html

The things that autogenerate them should be https://github.com/ipython/ipython/blob/master/docs/autogen_magics.py

It does not generate aliases though, as alias are just pass-through shell things. 

It seem that it does not list all, and/or is missing maybe a toc that list all. 
Do you want to give it a shot in a PR ?

**Comment by lmmx** [comment]
Odd that that's the only one of the `docs/*.py` scripts not showing up as executable [missing a #! line] - sure, having a look see now...

**Comment by Carreau** [comment]
There shouldn't need to be executed with a #! as they are compiled and
exec()'d by docs/source/conf.py as part of docs building.

**Comment by takluyver** [comment]
It's not clear what specific tasks this issue was left open to track. Does anyone remember?

**Comment by Carreau** [comment]
Alases seem to not be documented. But ok to close, I don't see anything obviously missing.

**Comment by takluyver** [comment]
OK, I'll open a new issue for that so things are clearer.
