### ISSUE TITLE
PAM plug in and documentation

### ISSUE THREAD

**Issue by episodeyang** [ipython/ipython#8765]
I am writing an iPython client for my lab that allows people to share ipython notebooks as part of a rich text editor and work on them together. Since the server will be hosted on a separate domain, and all the users will connect to the server via a uri, the cookie-based authentication won't work. 

I have looked through the issues and PRs. What is the status on the PAM? patching the code is relatively easy, but since this would be needed by any third-party client, it might make sense to have a repo for a token-based PAM that could be configured in the `profile_config.py` file.

The docker repo is awesome btw!

Ge

**Comment by Carreau** [comment]
I think you might want to open that on jupyter/notebook repo as IPython is now only purely the python-kernel part.

That being said,  if you have a patch for the code that would allow easier configuration, and if it's already written please send a PR. 

though in a multi-user context I think you want to authenticate with https://github.com/jupyter/jupyterhub not with Notebook, as hub deals with multi-user.

**Comment by episodeyang** [comment]
Thanks I will repost this there!
