### ISSUE TITLE
too many hello world - problem with range(x) call

### ISSUE THREAD

**Issue by abhisheki2904** [ipython/ipython#8766]
%%timeit 
range(10)
print ('hello world')
range(15)

i tried this simple line of code on my ipython4.0.0 with jupyter and the result i got was unexpected
it printed 'hello world 'like 1000s of times .. and 2 times the browser got crashed 
the issue is working on both 
firefox and chrome latest versions

**Comment by Carreau** [comment]
Hi, thanks for your bug report. 

What do you expect `%%timeit` to do ? Aren't you confusing `%%timeit` with `%%time` ?

In the above code having "hello world" printed hundreds of time seem expected.

Crashing the browser not expected, but we are aware and working on a fix.

**Comment by abhisheki2904** [comment]
yepp seems right , it works fine with %%time

**Comment by abhisheki2904** [comment]
hi @Carreau , just have a look on the fact that, running a OS command is allowed with !
so if any one execute
 !ipython notebook

it opens up a completely new notebook tab ...which works just fine 
but how will we close it .. because through browser we won't be able to do ctrl+c stuff

**Comment by Carreau** [comment]
> but how will we close it .. because through browser we won't be able to do ctrl+c stuff

Kernel > Interrupt send a Ctrl-C, so you need to do it twice quickly I guess. 
But `!`  is a convenience method, you should't use it for long running or complex process,  use subprocess explicitely. 

Closing as `%%time` works.
