### ISSUE TITLE
zsh autocompletion file

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#8767]
I put together a small zsh autocompletion file for ipython (i.e., something that will autocomplete `ipython note<TAB>` into `ipython notebook` and so on, as well as a few flags).  Is there interest in a PR for it?  If so, where in the source tree should I put it?

**Comment by Carreau** [comment]
Hi,

I I think this would make sens.

We have a bash-completions in `examples/IPython Kernel`, I would but it in
the same folder.
you can drop a file in `docs/source/whatsnew/pr/` that will be compiled in
the releases notes.

**Comment by takluyver** [comment]
This was integrated in jupyter/jupyter_core#48 - closing here.
