### ISSUE TITLE
response from the image window to kernel is not getting passed

### ISSUE THREAD

**Issue by abhisheki2904** [ipython/ipython#8770]
here is a simple part of code ... to display a image and then closing it off on pressing the esc or 'q'

```python
import cv2
img=cv2.imread('/<imagelocation>')
cv2.imshow('image',img)
k=cv2/waitKey(0)
if k == 27 or ord('q'):
     cv2.destroyAllWindows()
```

now the image is shown properly but on pressing 'q' or esc , it hangs and then you have to force quit the image ,
and immediately notebook detects this failure and restart the kernel

**Comment by Carreau** [comment]
What is `cv2` ? [not that](https://pypi.python.org/pypi/cv2) I guess. (I guessed it was open cv).

How does it work in non-notebook, how does it work in non-ipython ?

if it crash non-ipython then it's an (py)opencv bug, not ours. restarting the kernel if the kernel crash is expected.

Also I just tested and it works well here, so it's likely not a bug of ours. 

(Formatting note you can use triple backticks to format code):


    ```python
    import foo
    pass #comment
    ```

**Comment by abhisheki2904** [comment]
for cv2 (it is opencv 3.0.0 )

 in non-notebook environment .. on executing the following code it just pop-up a image-window and on pressing the esc ot 'q' over that window it gets closed

**Comment by Carreau** [comment]
What about just IPython console. Not notebook ?

**Comment by abhisheki2904** [comment]
it seems the problem is with the IPython console itself .
it shows the image and close it on pressing any button ...
but as per rule it should close only on pressing esc or 'q'

**Comment by Carreau** [comment]
Please keep it to one bug per issue. 

1) Is the bug that the kernel crash ?
If so can you reproduce the crash on non-notebook ?

2) is the bug that it close the window on any keypress ?
if so check your above code which is wrong. `cv2/waitKey(0)` is not valid, and `k == 27 or ord('q')` does not what you expect as it reads as `(k == 27) or ord('q')` which should alway be true.. 

testing for 2 on pure python will have shown you that this is not an IPython bug:

```
$ python
>>> def f():
...     import cv2
...     img=cv2.imread('/<image>.jpg')
...     cv2.imshow('image', img)
...     k=cv2.waitKey(0)
...     if k == 27 or ord('q'):
...          cv2.destroyAllWindows()
...
>>> f() #press any keys, window closes
>>>
```

Now that we have corrected your code, and eliminate an unexpected behavior, we are back to the question of crashing that we can reduce to the following : 
```
import cv2
img=cv2.imread('/<image>.jpg')
cv2.imshow('image',img)
cv2.destroyAllWindows()
```

Does this make your kernel crash ?

**Comment by abhisheki2904** [comment]
it seems the issue was with ipython and opencv loading ... now able to get the desired output

**Comment by Carreau** [comment]
Ok, great.

**Comment by victorozoh** [comment]
`import cv2

input = cv2.imread('./images/input.jpg')
cv2.imshow('Hello World', input)
cv2.waitKey(0)
cv2.destroyAllWindows()`

My kernel is crashing with above code. Sometimes, the image loads and then hangs. I am running Python 3.5, Anaconda 64 bit on an Ubuntu 16.04 machine. Please, can anyone help me resolve this?

**Comment by takluyver** [comment]
@abhisheki2904 can you remember what you did to get it working?

**Comment by victorozoh** [comment]
Sometimes I get the error
```Hello World: Fatal IO error 11 (Resource temporarily unavailable) on X server :0
```
Other times, I get the following message
```Hello World: Fatal IO error 0 (Success) on X server :0.
```
After the above message, the image gets displayed. However is gradually gets darker, then the image window freezes and I then have to force quit.
If I run the cv2.imshow() command again after force quitting, the kernel dies and restarts. 
I will greatly appreciate any help as I am new to OpenCV on ubuntu.

**Comment by victorozoh** [comment]
Pardon me for the blank error messages in the previous post
First Error:
Hello World: Fatal IO error 11 (Resource temporarily unavailable) on X server :0

Second error:
Hello World: Fatal IO error 11 (Resource temporarily unavailable) on X server :0

**Comment by Carreau** [comment]
> Pardon me for the blank error messages in the previous post
> First Error:
> Hello World: Fatal IO error 11 (Resource temporarily unavailable) on X server :0
> 
> Second error:
> Hello World: Fatal IO error 11 (Resource temporarily unavailable) on X server :0

Just don't write your message on the first line after the triple quote, it is ment for the language highlighting

    ```language-here,like python, javascript
    content here
    ```
You can edit your comment if you made a mistake. I fixed it for you.

**Comment by vishal0021** [comment]
hey have any one resolved this issue, coz i have same problem.
Here is my code.

import cv2
import numpy as np
import matplotlib.pyplot as plt
                    0
img = cv2.imread('index.jpeg',cv2.IMREAD_GRAYSCALE)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllwindows()
i am running python3 on ubuntu 16.04, when i run this code the image window and consol gets hanged, non responsive, i have tried different consoles to run the code like ipython, spyder, jupyter notebook, ubuntu terminal  same error every time

**Comment by ntirupathirao18** [comment]
@vishal0021  I'm facing the same issue, please can you help me out with the solution if you found any.
