### ISSUE TITLE
Update to latest path.py package breaks ipython

### ISSUE THREAD

**Issue by chrisidefix** [ipython/ipython#8776]
Updating to the latest [`path.py` package](https://github.com/jaraco/path.py), which is a dependency of [`pickleshare`](https://pypi.python.org/pypi/pickleshare), causes ipython to break (see error below).

Easiest solution is to downgrade to `path.py 7.7.1`, but ideally `pickleshare` should implement the corresponding fix, which I issued here: https://github.com/pickleshare/pickleshare/issues/8
The "problematic" change in `path.py` you can find here: https://github.com/jaraco/path.py/commit/62ccb7623d4d048af663f205e21c2ec3f24fa17d

Now, the real question is, should `pickleshare` be replaced with something else, as it doesn't look like an actively maintained project? Or should at least the currently working version for `path.py` be requested as a dependency by `ipython` ?

```
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 7, in <module>
    from IPython import start_ipython
  File "/usr/local/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .terminal.embed import embed
  File "/usr/local/lib/python2.7/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.core.interactiveshell import DummyMod
  File "/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 31, in <module>
    from pickleshare import PickleShareDB
  File "/usr/local/lib/python2.7/site-packages/pickleshare.py", line 41, in <module>
    from path import path as Path
ImportError: cannot import name path
```

**Comment by Carreau** [comment]
Thanks for the report. We have access to PickleShare repository, we'll try to get a fix soon !

**Comment by chrisidefix** [comment]
For now the release has been pulled / put on hold, but good to know upcoming API changes I guess: https://github.com/jaraco/path.py/issues/102#issuecomment-135481508

**Comment by Carreau** [comment]
`pickleshare`  has been updated & released. Can we close this ?
