### ISSUE TITLE
IPython notebook: unable to display nested SVG elements

### ISSUE THREAD

**Issue by snowracer** [ipython/ipython#8780]
I am unable to properly display nested SVG images in an IPython/Jupyter notebook.

Sample code:

    from IPython.display import SVG
    nested_svg="""
    <svg xmlns="http://www.w3.org/2000/svg">
      <svg x="0">
        <rect x="10" y="10" height="80" width="80" style="fill: #0000ff"/>
      </svg>
      <svg x="100">
        <rect x="10" y="10" height="80" width="80" style="fill: #00cc00"/>
      </svg>
    </svg>"""
    SVG(nested_svg)

The image gets displayed, but it is also transformed in the process. The nested svg elements are all moved to the top level:

    <div class="output_subarea output_svg output_result"><div>
      <svg xmlns="http://www.w3.org/2000/svg" style="width: 100%; height: 100%;">
      </svg>
      <svg x="0" style="width: 100%; height: 100%;">
        <rect height="80" style="fill: #0000ff" width="80" x="10" y="10"></rect>
      </svg>
      <svg x="100" style="width: 100%; height: 100%;">
        <rect height="80" style="fill: #00cc00" width="80" x="10" y="10"></rect>
      </svg>
    </div></div>

There is also an added attribute `style="width: 100%; height: 100%;"` in all three svg elements.

I have also tried an alternative method:

    from IPython.display import display_svg
    display_svg(nested_svg, raw=True)

And I have tried to specify height and width of the root svg element. Neither helped.

However, I noticed that in the .ipynb files the SVG is untransformed in the "outputs" sections.

The problem occurs in IPython/Jupyter version 4.0, same as in 3.2. Using Python 2.7.10 Anaconda 2.3.0 (32-bit). I was able to reproduce the problem at try.jupyter.org using Python 3.4.3.

**Comment by Carreau** [comment]
Gosh, I didn't even knew you could nest SVGs... we'll try to have a look thanks !

**Comment by tacaswell** [comment]
I was also surprise, but http://www.w3.org/TR/SVG/struct.html#NewDocument  

It does make sense that this is allowed.

**Comment by takluyver** [comment]
See jupyter/notebook#982
