### ISSUE TITLE
R scan() function does not work

### ISSUE THREAD

**Issue by carloshdezv** [ipython/ipython#8787]
Hi,

Im trying to run this code on ipython 

J <- 3
K <- 5 
X <- scan(n=J*K)
99.3 93.7 103.9 92.5 110.6
112.5 108.3 118.0 99.4 111.8
129.2 140.9 108.3 105.0 116.6
j <- rep(1:J, each=K)
j <- as.factor(j)
X.bar <- mean(X)
Xj.bar <- tapply(X, j, mean)
MSB <- sum((Xj.bar-X.bar)^2) * K / (J-1)
MSW <- sum((X-rep(Xj.bar,each=K))^2)/J/(K-1)
MSB/MSW
qf(0.95, J-1, J*(K-1))
1-MSW/MSB

And then I got this error:

Error in parse(text = x, srcfile = src): <text>:5:6: unexpected numeric constant
4: X <- scan(n=J*K)
5: 99.3 93.7
        ^

Is there any issue with scan function???, this code works well in R or R studio.

Thanks!

**Comment by tacaswell** [comment]
This should probably be reported against https://github.com/IRkernel/IRkernel instead.

**Comment by Carreau** [comment]
Closing as IRkernel issue. Thanks.
