### ISSUE TITLE
init_printing(use_latex='mathjax') not working in ipython notebook 4

### ISSUE THREAD

**Issue by titas99** [ipython/ipython#8790]
Hi,

Previously I used ipython notebook 3, where init_printing(use_latex='mathjax')  worked perfectly for sympy. But recently I upgraded my system, and now in ipython notebook 4 it is not working anymore.

Any help!!!!!!

**Comment by Carreau** [comment]
Seem like a SymPy issue that do not recognize that it is in IPython. I would suggest asking the SymPy devs, but master of sympy seem to be fixed.
