### ISSUE TITLE
ipython/jupyter issue with copy paste in windows

### ISSUE THREAD

**Issue by ifmihai** [ipython/ipython#8793]
I just updated ipython to version 4.00
(kind of confused about all jupyter stuff right now)

anyway, I bump periodically into the same issue with copy paste

Whenever I copy a text from ipython/jupyter (for example copying a parameter to paste it a line below),
when i paste it, it loses the last character, always.

it doesnt matter if i select the text with mouse or keys, same result.

i'm on windows 7, python 2.7.9 32bit, anaconda, ipython 4.00

**Comment by Carreau** [comment]
Can you reproduce on http://codemirror.net/ directly ? Which browser ?

**Comment by ifmihai** [comment]
ah, sorry, forgot to mention

ipython qtconsole

not notebooks (i presume you referred to ipython notebook)

**Comment by Carreau** [comment]
Ah ! I knew I had heard that somewhere else !

Then you are not the only one, it has already been reported [here](https://github.com/jupyter/qtconsole/issues/48) so closing this one as duplicate.

You can track the progress on the other issue. 

Thanks !
