### ISSUE TITLE
Doc error

### ISSUE THREAD

**Issue by olajir** [ipython/ipython#8796]
In security section at https://ipython.org/ipython-doc/1/interactive/public_server.html:

The line
openssl req -x509 -nodes -days 365 -newkey rsa:1024 -keyout mycert.pem -out mycert.pem

should probably read:
openssl req -x509 -nodes -days 365 -newkey rsa:1024 -keyout mycert.**key** -out mycert.pem

otherwise the key file will be overwritten by the certificate file.

**Comment by theSage21** [comment]
Is this change all that is needed?

**Comment by olajir** [comment]
Yes, the -keyout option specifies the name of the output file for the private key. The -out options specifies the file for the certificate. They can not have the same name as this will result in the key-file to be overwritten by the certificate file. I think that the .key extension is commonly used for private keys but I've also seen the use of .pem. If .pem is to be used for the key file then key file name would have to change, e.g.:
openssl req -x509 -nodes -days 365 -newkey rsa:1024 -keyout **mykey**.pem -out mycert.pem

But the naming of the files is a matter of taste as long as their names are not identical.
