### ISSUE TITLE
ipython notebook & script difference - loading DLLs

### ISSUE THREAD

**Issue by denfromufa** [ipython/ipython#8800]
cross-posting here, maybe this is ipython related?
https://github.com/pythonnet/pythonnet/issues/98

**Comment by minrk** [comment]
I don't see how it could be related to IPython, but it's not impossible. IPython doesn't knowingly do anything about loading DLLs. Is the CWD the same in both cases?

**Comment by denfromufa** [comment]
ok, the difference comes between interactive session of python (not only ipython) and running as a python script. So not strictly ipython related, more general issue.
CWD is same.

**Comment by minrk** [comment]
Okay, thanks. I'll close here, then.

**Comment by denfromufa** [comment]
I found bug in pythonnet, but the weird thing is why interactive python interpreter adds empty string to sys.path?

**Comment by minrk** [comment]
Yes, that's normal. Python adds the CWD to the path when running interactively. An empty string indicates this because paths relative to the empty string are in the CWD.

**Comment by denfromufa** [comment]
OK this makes sense, thank you for educating me :)
