### ISSUE TITLE
Which event can initialize the file editor?

### ISSUE THREAD

**Issue by davidshen84** [ipython/ipython#8808]
The `app_initialized.NotebookApp` event can be used to add customization script when initialize the notebook. But now, I want to initialize the file editor.

I have found that `IPython.editor.codemirror.options.indentUnit = 2` can be used to change the indent unit in the file editor, but I could not find a way to invoke the script at the initialization stage.

**Comment by Carreau** [comment]
if you open the javascript console and issue a `IPython.editor.config.update({Editor:{codemirror_options:{indentUnit:2}}})` then it should configure the indent unit to be 2 permanently. 

There  is the event `file_loaded.Editor`, but no equivalent to app_initialized.
