### ISSUE TITLE
Italics/math mode in LaTeX/Markdown produce \nu instead of v

### ISSUE THREAD

**Issue by sondy** [ipython/ipython#8812]
For my planetary physics class we've been working on the $\textit{vis viva}$ equation, which I typeset as
$$v^2 = GM \Big ( \frac{2}{r} - \frac{1}{a} \Big ) .$$
Unfortunately, Markdown in iPython notebooks typesets the italic/math mode v characters to look like a Greek $\nu$, which usually represents frequency rather than velocity.

I'm using Mac OS 10.10.5 with Chrome version 45.0.2454.85 (64-bit), Python 3.4.2, and iPython 4.0.0.

**Comment by sondy** [comment]
Example of italic v characters being typeset as nu. ![screen shot 2015-09-14 at 3 55 30 pm](https://cloud.githubusercontent.com/assets/730062/9863899/10c078f8-5af9-11e5-82a4-c4d8f2be8ad9.png)

**Comment by Carreau** [comment]
That is how MathJax (and LaTex in general) represent `v` in math mode. You can use `\text{v}`, or `\texttt{v}` to have a strait version when in math mode.

**Comment by sondy** [comment]
LaTeXIt (and TeXShop) render italic v as rounded on the bottom, not appearing to be the letter nu.  I'm not interested in a straight v while in math mode, just a rounded one as below.

![screen shot 2015-09-14 at 4 50 05 pm](https://cloud.githubusercontent.com/assets/730062/9864666/af33f17a-5b00-11e5-8261-61ce3e8de024.png)

**Comment by Carreau** [comment]
Then `\mathcal{v}` or `\upsilon` look close, but the redering is done by [mathjax](https://www.mathjax.org/) with STIX font, there is not much we can do:

![screen shot 2015-09-14 at 17 02 27](https://cloud.githubusercontent.com/assets/335567/9864783/6651197c-5b02-11e5-96e5-debf26ed3cba.png)
