### ISSUE TITLE
PDF Creating Failed, ! LaTeX Error: File `adjustbox.sty' not found.

### ISSUE THREAD

**Issue by jsudbang** [ipython/ipython#8814]
Hi,
I'm trying to convert a notebook to PDF. I've downloaded pandoc and BasicTeX, but I'm still getting the following output:

[NbConvertApp] Converting notebook HW1_MATS8001.ipynb to pdf
[NbConvertApp] Writing 15256 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running pdflatex 3 times: [u'pdflatex', u'notebook.tex']
[NbConvertApp] CRITICAL | pdflatex failed: [u'pdflatex', u'notebook.tex']
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./notebook.tex
LaTeX2e <2015/01/01>
Babel <3.9l> and hyphenation patterns for 21 languages loaded.
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/latexconfig/graphics.cfg)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/pdftex-def/pdftex.def
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))

! LaTeX Error: File `adjustbox.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.19     \usepackage
                    {color} % Allow colors to be defined^^M
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on notebook.log.

[NbConvertApp] Running bibtex 1 time: [u'bibtex', u'notebook']
[NbConvertApp] WARNING | bibtex had problems, most likely because there were no citations
[NbConvertApp] Running pdflatex 3 times: [u'pdflatex', u'notebook.tex']
[NbConvertApp] CRITICAL | pdflatex failed: [u'pdflatex', u'notebook.tex']
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./notebook.tex
LaTeX2e <2015/01/01>
Babel <3.9l> and hyphenation patterns for 21 languages loaded.
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/latexconfig/graphics.cfg)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/pdftex-def/pdftex.def
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))

! LaTeX Error: File `adjustbox.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.19     \usepackage
                    {color} % Allow colors to be defined^^M
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on notebook.log.

Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python2.7/site-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 592, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 349, in start
    return self.subapp.start()
  File "/usr/local/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 286, in start
    self.convert_notebooks()
  File "/usr/local/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 409, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/usr/local/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 380, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources)
  File "/usr/local/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 332, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/local/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 166, in from_filename
    return self.from_notebook_node(nbformat.read(f, as_version=4), resources=resources, **kw)
  File "/usr/local/lib/python2.7/site-packages/nbconvert/exporters/pdf.py", line 139, in from_notebook_node
    raise RuntimeError("PDF creating failed")
RuntimeError: PDF creating failed

**Comment by dsblank** [comment]
Some suggestions here:

http://tex.stackexchange.com/questions/116659/latex-error-file-adjustbox-sty-not-found-on-ubuntu-10-04-2

**Comment by adriancooney** [comment]
Had the same issue, you need to install some extra Tex packages. Use `tlmgr`.

    sudo tlmgr install adjustbox

I also had to install some more packages which I assume you will have to too:

    sudo tlmgr install collectbox
    sudo tlmgr install ucs

**Comment by brifordwylie** [comment]
Just ran into the exact same issue (I only have basicTex installed and not the full MacTex). @adriancooney suggestions worked perfectly.

**Comment by gschivley** [comment]
Same issue on a mac with El Capitan, and the suggestion by @adriancooney worked (after I updated tlmgr). Hope others find this helpful.

**Comment by trmanish** [comment]
tlmgr update --self
TeX Live 2015 is frozen forever and will no
longer be updated.  This happens in preparation for a new release.

If you're interested in helping to pretest the new release (when
pretests are available), please read http://tug.org/texlive/pretest.html.
Otherwise, just wait, and the new release will be ready in due time.
tlmgr: package repository http://mirror.hmc.edu/ctan/systems/texlive/tlnet
You don't have permission to change the installation in any way,
specifically, the directory /usr/local/texlive/2015basic/tlpkg/ is not writable.
Please run this program as administrator, or contact your local admin.
tlmgr: An error has occurred. See above messages. Exiting.

**Comment by sicotronic** [comment]
I'm using a Mac with BasicTex installed. I needed to install some extra Tex packages but I still have some error messages coming out.
 
```
sudo tlmgr install adjustbox
sudo tlmgr install collectbox
sudo tlmgr install ucs
```

This is the error message I get now. Does somebody got the same error? Could you solve it?

```
nbconvert failed: PDF creating failed, captured latex output:
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./notebook.tex
LaTeX2e <2015/01/01>
Babel <3.9l> and hyphenation patterns for 21 languages loaded.
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/size11.clo))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/fontenc.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/t1enc.def))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/psnfss/palatino.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/latexconfig/graphics.cfg)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/pdftex-def/pdftex.def
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/caption/caption.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/caption/caption3.sty))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/adjustbox/adjustbox.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/xkeyval/xkvutils.tex)))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/adjustbox/adjcalc.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/adjustbox/trimclip.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/collectbox/collectbox.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/adjustbox/tc-pdftex.def)))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/latexconfig/color.cfg))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/tools/enumerate.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/textcomp.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/upquote/upquote.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/eurosym/eurosym.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/ucs/ucs.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/ucs/data/uni-global.def))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/inputenc.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/ucs/utf8x.def))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/oberdiek/grffile.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.s
ty
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/hobsub-generic.st
y)) (/usr/local/texlive/2015basic/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/url/url.sty))

Package hyperref Message: Driver (autodetected): hpdftex.

(/usr/local/texlive/2015basic/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty)
) (/usr/local/texlive/2015basic/texmf-dist/tex/latex/tools/longtable.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/booktabs/booktabs.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/ulem/ulem.sty)
No file notebook.aux.
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/ts1cmr.fd)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/psnfss/t1ppl.fd)
kpathsea: Running mktextfm pplr8t
/usr/local/texlive/2015basic/texmf-dist/web2c/mktexnam: Could not map source abbreviation  for pplr8t.
/usr/local/texlive/2015basic/texmf-dist/web2c/mktexnam: Need to update ?
mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input pplr8t
This is METAFONT, Version 2.7182818 (TeX Live 2015) (preloaded base=mf)

kpathsea: Running mktexmf pplr8t

! I can't find file `pplr8t'.
<*> ...:=ljfour; mag:=1; nonstopmode; input pplr8t
                                                  
Please type another input file name
! Emergency stop.
<*> ...:=ljfour; mag:=1; nonstopmode; input pplr8t
                                                  
Transcript written on mfput.log.
grep: pplr8t.log: No such file or directory
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input pplr8t' failed to make pplr8t.tfm.
kpathsea: Appending font creation commands to missfont.log.

! Font T1/ppl/m/n/10.95=pplr8t at 10.95pt not loadable: Metric (TFM) file not f
ound.
<to be read again> 
                   relax 
l.270     \begin{document}
                          
? 
! Emergency stop.
<to be read again> 
                   relax 
l.270     \begin{document}
                          
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on notebook.log.
```

**Comment by minrk** [comment]
@sicotronic looks like you are missing the palatino font:

    tlmgr install palatino

**Comment by sicotronic** [comment]
@minrk 
Thank you, that seemed to work, but there is another error coming out... can you help me read these error logs? I can't see what libraries I need to install.
It may be because I'm using Japanese text in the notebook. 

```
nbconvert failed: PDF creating failed, captured latex output:
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./notebook.tex
LaTeX2e <2015/01/01>
Babel <3.9l> and hyphenation patterns for 21 languages loaded.
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/size11.clo))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/fontenc.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/t1enc.def))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/psnfss/palatino.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/latexconfig/graphics.cfg)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/pdftex-def/pdftex.def
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/caption/caption.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/caption/caption3.sty))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/adjustbox/adjustbox.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/xkeyval/xkvutils.tex)))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/adjustbox/adjcalc.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/adjustbox/trimclip.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/collectbox/collectbox.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/adjustbox/tc-pdftex.def)))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/latexconfig/color.cfg))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/tools/enumerate.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/textcomp.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/upquote/upquote.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/eurosym/eurosym.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/ucs/ucs.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/ucs/data/uni-global.def))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/inputenc.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/ucs/utf8x.def))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/oberdiek/grffile.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty))
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.s
ty
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/hobsub-generic.st
y)) (/usr/local/texlive/2015basic/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/url/url.sty))

Package hyperref Message: Driver (autodetected): hpdftex.

(/usr/local/texlive/2015basic/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty)
) (/usr/local/texlive/2015basic/texmf-dist/tex/latex/tools/longtable.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/booktabs/booktabs.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/ulem/ulem.sty)
No file notebook.aux.
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/ts1cmr.fd)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/psnfss/t1ppl.fd)
(/usr/local/texlive/2015basic/texmf-dist/tex/context/base/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/local/texlive/2015basic/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/oberdiek/grfext.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg
)) (/usr/local/texlive/2015basic/texmf-dist/tex/latex/caption/ltcaption.sty)
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
*geometry* verbose mode - [ preamble ] result:
* driver: pdftex
* paper: <default>
* layout: <same size as paper>
* layoutoffset:(h,v)=(0.0pt,0.0pt)
* modes: 
* h-part:(L,W,R)=(72.26999pt, 469.75502pt, 72.26999pt)
* v-part:(T,H,B)=(72.26999pt, 650.43001pt, 72.26999pt)
* \paperwidth=614.295pt
* \paperheight=794.96999pt
* \textwidth=469.75502pt
* \textheight=650.43001pt
* \oddsidemargin=0.0pt
* \evensidemargin=0.0pt
* \topmargin=-37.0pt
* \headheight=12.0pt
* \headsep=25.0pt
* \topskip=11.0pt
* \footskip=30.0pt
* \marginparwidth=59.0pt
* \marginparsep=10.0pt
* \columnsep=10.0pt
* \skip\footins=10.0pt plus 4.0pt minus 2.0pt
* \hoffset=0.0pt
* \voffset=0.0pt
* \mag=1000
* \@twocolumnfalse
* \@twosidefalse
* \@mparswitchfalse
* \@reversemarginfalse
* (1in=72.27pt=25.4mm, 1cm=28.453pt)

(/usr/local/texlive/2015basic/texmf-dist/tex/latex/ucs/ucsencs.def)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/gettitlestring.st
y)) (/usr/local/texlive/2015basic/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/amsfonts/umsb.fd)

LaTeX Warning: No \author given.

(/usr/local/texlive/2015basic/texmf-dist/tex/latex/ucs/data/uni-48.def)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/ucs/data/uninames.dat)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/ucs/data/uni-48.def)

! Package ucs Error: Unknown Unicode character 12518 = U+30E6,
(ucs)                possibly declared in uni-48.def.
(ucs)                Type H to see if it is available with options.

See the ucs package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.278 ...�ーザーのイベントログの調査}
                                                  \label{ux30e6ux30fcux30b6u...

? 
! Emergency stop.
 ...                                              
                                                  
l.278 ...�ーザーのイベントログの調査}
                                                  \label{ux30e6ux30fcux30b6u...

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on notebook.log.
```

**Comment by minrk** [comment]
@sicotronic that looks like unicode problems, which pdflatex doesn't handle at all well. We've switched nbconvert to use `xelatex` by default for this reason, which may fix this case, but we have not made a release with that change, yet. You can try setting that in your config with:

```python
c.PDFExporter.latex_command = ['xelatex', '{filename}']
```

**Comment by anujgupta82** [comment]
@sicotronic: i followed above steps. Got stuck with this error

	/usr/local/texlive/2016basic/texmf-dist/web2c/mktexnam: Need to update ?
	mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input pplr8t
	This is METAFONT, Version 2.7182818 (TeX Live 2016) (preloaded base=mf)

	kpathsea: Running mktexmf pplr8t

	! I can't find file `pplr8t'.
	<*> ...:=ljfour; mag:=1; nonstopmode; input pplr8t

**Comment by ChrisRackauckas** [comment]
How do you handle this on CentOS? `tlmgr` doesn't exist.

**Comment by DanielWeitzenfeld** [comment]
@anujgupta82 try 
```
sudo tlmgr install mathpazo
sudo tlmgr install courier
sudo tlmgr install palatino
```

**Comment by anujgupta82** [comment]
@DanielWeitzenfeld : worked like a charm. thanks

**Comment by koustuvsinha** [comment]
hey guys.. i am running the exact same things but getting this new error : 

```
! I can't find file `pcrr8t'.
<*> ...:=ljfour; mag:=1; nonstopmode; input pcrr8t
Please type another input file name
! Emergency stop.
<*> ...:=ljfour; mag:=1; nonstopmode; input pcrr8t
```

**Comment by mehdirezaie** [comment]
Hey @koustuvsinha , please <a href="https://stackoverflow.com/questions/27177491/compiling-latex-pplr8t-log-font-is-missing">check this out</a>! I tried and it worked pretty well for me
`sudo tlmgr install collection-fontsrecommended`

**Comment by chrisrb10** [comment]
Hi,

I have exactly the problem describe above, and tried the ```sudo tlmgr install adjustbox``` approach above. I was prompted to update tlmgr with: ```tlmgr update --self``` which i tried.
But then received this message:
```
$ tlmgr update --self
tlmgr: package repository http://anorien.csc.warwick.ac.uk/mirrors/CTAN/systems/texlive/tlnet (not verified: gnupg not available)
You don't have permission to change the installation in any way,
specifically, the directory /usr/local/texlive/2017basic/tlpkg/ is not writable.
Please run this program as administrator, or contact your local admin.
tlmgr: An error has occurred. See above messages. Exiting.
```
But I am an admin user (iMac running macOS Sierra 10.12.6) - so can't understand why I am getting this message.

My ultimate objective is to download .ipynb as .pdf - but this seems to be the main barrier. Any suggested solutions?

**Comment by clairetsai818** [comment]
@chrisrb10 I run `sudo tlmgr update --self` successfully. However, the error msg which is `! LaTeX Error: File `adjustbox.sty' not found.` isn't solve by this.

**Comment by holzkohlengrill** [comment]
`sudo pacman -S texlive-latexextra` did it for me.

**Comment by VictorDataEngineer** [comment]
I have done all the suggestions above, as a summary: 

sudo tlmgr update --self
sudo tlmgr install adjustbox
sudo tlmgr install collectbox
sudo tlmgr install ucs
sudo tlmgr install mathpazo
sudo tlmgr install courier
sudo tlmgr install palatino

Thanks @adriancooney , @sicotronic , @DanielWeitzenfeld

**Comment by humpydonkey** [comment]
this is a great thread! solved all my problems!

**Comment by simonkeng** [comment]
Seriously an amazing thread. Thanks everyone who contributed! This helped me through all my problems as well

**Comment by dbinoj** [comment]
For CentOS 7 folks:

```
yum install texlive-*
fmtutil-sys --all
texhash
```

**Comment by izmailoff** [comment]
For Fedora folks, this solved it for me:
`
sudo dnf install texlive-collection-latexextra`

**Comment by kamalhm** [comment]
FOR Arch/Manjaro, Installing texlive-latexextra did it for me

**Comment by seyyaw** [comment]
> Hey @koustuvsinha , please [check this out](https://stackoverflow.com/questions/27177491/compiling-latex-pplr8t-log-font-is-missing)! I tried and it worked pretty well for me
> `sudo tlmgr install collection-fontsrecommended`

This finally helps in my case

**Comment by Kanhalelor** [comment]
`cannot setup TLPDB`

**Comment by ahbon123** [comment]
It raises an new error for my MacBook pro:

```
x@bogon ~ % sudo tlmgr update --self
sudo tlmgr install adjustbox
/usr/local/bin/tlmgr: only MacOSX is supported, not darwin 11.1  (from sw_vers -productVersion: 11.1)

tlmgr: Local TeX Live (2019) is older than remote repository (2020).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.
/usr/local/bin/tlmgr: only MacOSX is supported, not darwin 11.1  (from sw_vers -productVersion: 11.1)

tlmgr: Local TeX Live (2019) is older than remote repository (2020).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.
```
