### ISSUE TITLE
My PyVISA code stopped working after upgrading to 4.0.0

### ISSUE THREAD

**Issue by wenzao** [ipython/ipython#8816]
After upgrading to iPython 4.0.0, my PyVISA code stopped working. I can no longer connect to instrument visa GPIB interface. I downgraded back to iPython 3.2.1 and my code worked again.

**Comment by Carreau** [comment]
Hum, we would need some more details on "Stopped working".

**Comment by wenzao** [comment]
I was able to found the error message, so basically the code `open_resource('GPIB::20')`, which is to connect to an instrument over the given GPIB port, is now broken. The error message is 

> VisaIOError: VI_ERROR_INTF_NUM_NCONFIG (-1073807195): The interface type is valid but the specified interface number is not configured.

**Comment by Carreau** [comment]
o_O, I'm not sure how this could be impacted directly by IPython 4.0, it probably at upgrade time pulles a few dependency that break things. I don't have available GPIB devices to try. 

Not sure how to debug that.

**Comment by wenzao** [comment]
Yeah it's probably a PyVISA problem. Maybe I should file a bug there.

**Comment by Carreau** [comment]
If they can reproduce, even if it's a bug in our code. I'm just not sure how to track it down.

**Comment by takluyver** [comment]
Closing as there's nothing we can do without more info, and it may not be an IPython bug. We can reopen if we find out more about it.
