### ISSUE TITLE
ipython notebook not creating/ignoring settings in 'ipython_notebook_config.py'

### ISSUE THREAD

**Issue by BoZenKhaa** [ipython/ipython#8818]
I am trying to run a notebook server. I installed ipython (version 4.0.0) with Anaconda following the [install directions](http://ipython.org/install.html). 

To set up the server, I followed directions in the [documentation](http://ipython.org/ipython-doc/stable/notebook/public_server.html). 

However, when I ran `ipython profile create nbserver`, i got no  `ipython_notebook_config.py` file. The only files that were created were `ipython_config.py` and `ipython_kernel_config.py`. I copied `ipython_config.py`, renamed it to `ipython_notebook_config.py` and pasted the suggested settings at the end. However, when starting notebook with `ipython notebook --profile=nbserver`, these settings are ignored. 

I can run the server by running `ipython notebook --no-browser --ip=* --port=9999` without any problem. 

Also, running `ipython notebook --config=/home/me/.ipython/profile_nbserver/ipython_notebook_config.py` loads the right settings, even though I had to manually install `ipywidgets`. Some uncaught ssl related exceptions are getting thrown around when connecting to the notebook, I don't know if those are related...

**Comment by BoZenKhaa** [comment]
Ok, I feel dumb now. I followed directions for the wrong version. The correct directions were [here](http://jupyter-notebook.readthedocs.org/en/latest/public_server.html) all the time.

**Comment by Carreau** [comment]
Yeah, sorry, we are working on putting a huge warning at the top of old docs. 
Thanks !

**Comment by schmiani** [comment]
Not dumb at all! I ran into the same exact problem. Thanks for pointing out the solution!

**Comment by NoraGithub** [comment]
Me,too .Thanks
