### ISSUE TITLE
ipython not working under PyCharm, but works fine running under browser

### ISSUE THREAD

**Issue by pangjac** [ipython/ipython#8819]
Dear talents,

ipython notebook have no output if I edit and run under Pycharm: if I push run button, it will run forever. See the little (*) mark at the very start of every line.

However if I open from browser and run, correct output. I suppose there is  wrong configuration under pycharm, any suggestion? 

Thanks!!~

Pycharm:
![image](https://cloud.githubusercontent.com/assets/13987136/9949612/070cf5c6-5d7d-11e5-925c-ecff039d04c1.png)

Browser:
![image](https://cloud.githubusercontent.com/assets/13987136/9949615/1b491fd8-5d7d-11e5-9f47-de0061a8e681.png)

**Comment by Carreau** [comment]
Hello @pangjac 

We are not the one who have written the IPython mode for PyCharm, I suggest you contact the PyCharm developers. 

Thanks.

**Comment by karlloic** [comment]
Hello @pangjac I have the same issue. Did you ever contact PyCharm and get a response?

**Comment by pangjac** [comment]
sadly, no.!!.....Now I separate Pycharm and using Anaconda and virtual env to host ipython notebook :(

**Comment by karlloic** [comment]
Ok thanks

**Comment by kenmaready** [comment]
Same issue here.  I spent so much time trying to get it to work in PyCharm, but never could, so now I'm in Jupyter NB for any deep learning scripts.
