### ISSUE TITLE
Kernel dies

### ISSUE THREAD

**Issue by jwdebelius** [ipython/ipython#8820]
I work both a Jupyter Hub (3.0) and a local copy of Jupyter (4.0) with the IPython 2 kernel. The Hub, especially, (although also my local copy) will frequently crap out and just decide to disconnect from the kernel. I tend to get about 4 hours of run time out of the deal, which is difficult if I'm trying to run memory-intensive code that has a long run time. (On the order of days).

**Comment by minrk** [comment]
Does reloading the page re-establish the connection? When you are running just vanilla Jupyter, is it on localhost or a remote server?

**Comment by JWDebelius** [comment]
Usually, I have to go to the "Kernel" menu, and restart there.
I run my normal Jupyter on localhost.

**Comment by kondor6c** [comment]
Is this still an issue? If it is perhaps we can hop on IRC and work through the problem and get some more details listed. I was looking to try and replicate the issue but I don't have enough details to do that.

**Comment by jwdebelius** [comment]
No, this can be closed.
