### ISSUE TITLE
Notebook rc_file Bug

### ISSUE THREAD

**Issue by cpashartis** [ipython/ipython#8825]
Hi,

I've noticed a (potential) bug with ipython notebook. Roughly a year ago I know this worked, but it seems since the new Jupyter upgrades something went wrong. 

If you load in a rc_file, you cannot have plots inline. Try the following and you will see what I mean

%pylab inline
matplotlib.rc_file('pathtotestrcfile/ipython_notebook.rc')
#new cell
dataset = [1,2,3,4]
#new cell 
plot( range(len(dataset)),dataset)

**If you make a rc file that is empty, you will still see the bug.** One way you can get around the bug, is if you run the entire notebook, then comment out the matplotlib.rc_file line and rerun all the cells again.

Do correct me if this has been brought up / found. I did a quick google search but nothing was found.

**Comment by minrk** [comment]
It would appear that loading an empty rc file resets everything to default, which includes setting `interactive=False`. I think this is what's causing the plots to not show anymore. If you do `plt.show()`, it should draw your plot inline (with default mpl style). Similarly, if you call `matplotlib.interactive(True)`, it should start drawing the plots automatically again.

I'm not sure that loading an rc file is meant to reset interactive, but it does seem to do that (@tacaswell?).

**Comment by tacaswell** [comment]
That is the long standing behavior of `rc_file`.  If you want to update a few rc value in place use the `mpl.style` module.

**Comment by cpashartis** [comment]
Thanks for the responses. This used to work as of 1 year ago so I wasn't sure if you were to consider this a bug.

Thanks again.

**Comment by minrk** [comment]
@cpashartis can you identify a version combination of IPython and mpl where it works?

**Comment by tacaswell** [comment]
The the 'defaults' it falls back to are user configurable (there are hard-coded defaults which are updated from the the system wide `matplotlibrc` file and then the `~/.config/matplotlib/matplotlibrc`).  If at any point you had `interactive: true` in one of your default files it would have worked.  

I think the consensus is that making interactive true by default is is a bad idea because it can mess wit using mpl in scripts.

**Comment by cpashartis** [comment]
@minrk The most recent timestamp in my directory was Jan. 2014. So that would be roughly Ipython 1.1.0. I did not have interactive: True in any of them.

It would seem based on tacaswell's comments, that the best solution would be to create a new rc file with interactive true.

**Comment by tacaswell** [comment]
That is about the opposite of what I suggested.  

You should not put interactive: true in your rcparams file and should use the `style` module.

**Comment by cpashartis** [comment]
Now that I read it again, good point. Thanks again. Also, wanted to say how much I appreciate the work you guys do on these packages. Many people in the scientific community use them, and it is greatly appreciated.
