### ISSUE TITLE
usetex,  ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by xiang-yu** [ipython/ipython#8835]
I am using matplotlib module to plot and save figure, specifically, pyplot, rc module of matplotlib and numpy. 

I am trying to use 

```python
pyplot.rc('text', usetex=True) 
```

error occurred as 

"ValueError: cannot convert float NaN to integer"

Is it a bug?

operating system : ubuntu 14.04

ipython 4.0.0 on python2,7. 

code: 

```python
import os
import timeit
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab  #for contour plot
import matplotlib.cm as cm  # for contour plot
import glob
from scipy.io.idl import readsav
from matplotlib import rc

ad=numpy.zeros(3)
ad[:]=1
fig=plt.figure()
plt.plot(ad,ad)
plt.rc('text', usetex=True)
plt.rc('font', family='serif')
plt.rc('xtick',labelsize=14)
plt.rc('ytick',labelsize=14)
plt.xlabel(r'$a_i \, (\mu m)$',fontsize=20,fontweight='bold')
plt.ylabel(r'$a_j \, (\mu m)$',fontsize=20,fontweight='bold')
plt.show()
```

Is it a bug of "usetex"

**Comment by minrk** [comment]
@xiang-yu you may want to bring this up with matplotlib, since IPython isn't involved in any way. I was able to run your code without any problems, so it might also have to do with your latex installation.
