### ISSUE TITLE
ipython, dpi does not work 

### ISSUE THREAD

**Issue by xiang-yu** [ipython/ipython#8836]
I am trying to save figure with lower resolution, but it seems ipython ignore the value of dpi. Whatever dpi value I set, the saved figure are the same.

code: 
import os
import timeit
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab  #for contour plot
import matplotlib.cm as cm  # for contour plot
import glob
from scipy.io.idl import readsav
from matplotlib import rc

ad=np.zeros(3)
ad[:]=1
fig=plt.figure()
plt.plot(ad,ad)
plt.rc('text', usetex=True)
plt.rc('font', family='serif')
plt.rc('xtick',labelsize=14)
plt.rc('ytick',labelsize=14)
plt.xlabel(r'$a_i \, (\mu m)$',fontsize=20,fontweight='bold')
plt.ylabel(r'$a_j \, (\mu m)$',fontsize=20,fontweight='bold')
fig.savefig('dpi.ps',format='ps',dpi=100)
plt.show()

**Comment by minrk** [comment]
This is a matplotlib question, but I believe that DPI only affects raster formats, e.g. png or jpeg. I don't think DPI affects postscript, since it's a vector format.
