### ISSUE TITLE
Jupyter not displaying correctly

### ISSUE THREAD

**Issue by dwatsonbynes** [ipython/ipython#8840]
![jupytr](https://cloud.githubusercontent.com/assets/6436348/10121370/1443529a-6506-11e5-9475-e19a59548792.JPG)
I installed anaconda, and then launched ipython notebook. Jupyter opened up in web browser. It displays content but without CSS. How to resolve this?

**Comment by minrk** [comment]
What do you see in the javascript console and/or the terminal where the server is running? I suspect the installtion was somehow broken and a reinstall is the right thing to do. Make sure that the notebook *is not running* when you do the reinstall.

**Comment by dwatsonbynes** [comment]
Hi,

My OS : Windows(64-bit).
RAM : 4 GB.
I have uninstalled and reinstalled Dato atleast 5 times now and always the
same problem.
I have removed all the pre-existing python and anaconda applications before
installing dato.
I launch ipython notebook from the dato launcher.
This is the output window that opens :


[image: Inline image 2]

**Comment by minrk** [comment]
Sorry, reinstalling `dato` probably wouldn't affect the notebook. Try reinstalling the `notebook` package.

**Comment by takluyver** [comment]
Closing as probably not an IPython bug.
