### ISSUE TITLE
IPython profile not working with qtconsole

### ISSUE THREAD

**Issue by colin1alexander** [ipython/ipython#8847]
I am using miniconda and ran into the following issue when setting up a profile.

First, I create an environment, activate it and then load IPython (with notebook) and qtconsole.

`$ conda create -n test`
`$ source activate test`
`$ conda install ipython ipython-notebook qtconsole`

From within this environment, I create a test IPython profile:

`$ ipython profile create test_profile`

However, when loading both qtconsole together with this profile, the profile is not recognized.

`ipython qtconsole --profile=test_profile` 
[JupyterQtConsoleApp] WARNING | Unrecognized alias: '--profile=test_profile', it will probably have no effect.

But the profile works just fine without qtconsole.

`ipython --profile=test_profile` 

Python 2.7.10 |Continuum Analytics, Inc.| (default, Sep 15 2015, 14:29:08) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

IPython profile: test_profile

Here are my profiles:

`ipython profile list`

Available profiles in /Users/my_mini/.ipython:
    default
    test_profile

To use any of the above profiles, start IPython with:
    ipython --profile=<name>

**Comment by minrk** [comment]
qtconsole is now part of Jupyter, and not IPython. Jupyter does not have profiles (a Jupyter profile would only configure the UI, and not IPython in any way). If you want to specify the IPython profile when it's a Jupyter kernel, you can add args to the `python2` kernelspec.
