### ISSUE TITLE
reset does not clear cache 

### ISSUE THREAD

**Issue by RafalSkolasinski** [ipython/ipython#8848]
It looks like reset doesn't clear cache from function decorated with ``@lru_cache``.
Here follows simple example that shows the issue.
(Tested with both Py2 and Py3)

In[1]:
```python
s = """
try:
    # Py3
    from functools import lru_cache
except ImportError:
    # Backport to Py2
    from functools32 import lru_cache

@lru_cache()
def f():
    print('running')
"""

with open('test.py', 'w') as f:
    f.write(s)

from test import f

print(1)
f()
print(2)
f()
```

    1
    running
    2

In[1]:
```python
get_ipython().reset()
```

In[2]:
```python
from test import f
print(3)
f() # Shouldn't have cache
print(4)
f()
```

    3
    4

**Comment by minrk** [comment]
Reset just clears IPython's own state (interactive namespace, input/output cache, etc.). It has no way of clearing all state from the entire interpreter without restarting the whole process.

**Comment by RafalSkolasinski** [comment]
But when function is defined in the notebook it has effect and cache is cleared. Shouldn't it work the same when function is imported from external module?

**Comment by minrk** [comment]
In the case of `@lru_cache`, the cache is stored in an attribute on the function itself. When the function lives in the interactive namespace, reset deletes the function object, and thus its class. When the function lives in a module, reset deletes the *reference* to the module function, if any, but it does not delete the original function in the module.

**Comment by RafalSkolasinski** [comment]
I see. Is there any way to achieve this which would not require hitting ``Kernel -> Restart``?
And also is it possible to that on remote engines without shutting them down and starting ipcluster again?

**Comment by minrk** [comment]
You can clear f's cache explicitly:

```python
f.cache_clear()
```

But there isn't a totally general way to clear an interpreter's state without restarting the process. And I am afraid that engines cannot be restarted, only killed.

**Comment by RafalSkolasinski** [comment]
I was concert about situation when f would be imported by some function, not in global namespace. But anyway thanks for clarification.
