### ISSUE TITLE
cross domain CORS request with DELETE, pre-flight request need to be handled

### ISSUE THREAD

**Issue by episodeyang** [ipython/ipython#8849]
Hi!

Escherpad's third-party notebook client implements the kernel shutdown command. This api call is done using the DELETE method.

Since DELETE method is categorized as a Preflighted request by standard, the browser first sends a OPTIONS request to the jupyter server and waits for a properly handled response header before proceeding with the actual request.

It looks like the jupyter notebook server does not handle this preflighted request (with the OPTIONS method). 

reference: [MDN Access control CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS)

**Comment by minrk** [comment]
fixed recently by jupyter/notebook#493

**Comment by episodeyang** [comment]
Thanks @minrk !!
