### ISSUE TITLE
The help page of notebook does not have verticle scrollbar in firefox

### ISSUE THREAD

**Issue by zhou13** [ipython/ipython#8853]
When I try to look up the document, I found that the vertical scrollbar of the help page does not exists in Firefox http://i.imgur.com/oebNjIN.png  In addition, I cannot even scroll the help page using my mouse wheel.

However, if I resize my Firefox windows, the scrollbar will appear: http://i.imgur.com/XIQL80v.png

Such problem does not exist on my chrome browser.

**Comment by minrk** [comment]
@jdfreder I don't suppose you are interested in tackling another pager-related issue?

**Comment by jdfreder** [comment]
Self assigned :)

**Comment by jdfreder** [comment]
I am able to reproduce this, looking at possible solutions now...
