### ISSUE TITLE
docs/Makefile hard-codes usage of "python"

### ISSUE THREAD

**Issue by toddrme2178** [ipython/ipython#8857]
[Makefile](https://github.com/ipython/ipython/blob/master/docs/Makefile) in `docs` hard-codes the use of the `python` executable in several places (lines 74, 80, 86, and 144 in current master).  This means it should always use python 2.x on [PEP 0394](https://www.python.org/dev/peps/pep-0394/)-compliant Python installations.  

Most such makefiles I have seen use a `PYTHON` environment variable, which is set to default to `python` but can be overriden to something like `python3`.

**Comment by minrk** [comment]
Makes sense. Do you want to make a PR?
