### ISSUE TITLE
Dict key completion for other dict-like objects (e.g., xray.Dataset)

### ISSUE THREAD

**Issue by shoyer** [ipython/ipython#8865]
#5304 added auto-completion for `dict` subclasses and `pandas.DataFrame` objects.

I would like to have dictionary key completion work on [`xarray.Dataset`](http://xarray.pydata.org/en/stable/data-structures.html#dataset) objects, which are conceptually very similar to data frames. `Dataset` is a `collections.Mapping` subclass, but it isn't a `dict` or `pandas.DataFrame`.

What's the right way to add this to IPython? I'm happy to issue a PR adding `xarray.Dataset` explicitly to `IPython.core.completer` [alongside `pandas.DataFrame`](https://github.com/ipython/ipython/blob/2880ecf8868419693ef8afb73761552c541140d0/IPython/core/completer.py#L931), but maybe a more generic approach would be appropriate? I'm sure there are many other projects with their own mapping objects that would also be interested.

**Comment by takluyver** [comment]
I think we should do it by checking for some private attribute like `obj._key_completion_safe_`, which package authors (you, in this case) can set to indicate that we should try to complete keys.

Then we'll probably also need to check `obj._this_shouldnt_exist_` (or similar), to override the above for objects that use `__getattr__` to pretend they have arbitrary attributes.

**Comment by MatthewTurk** [comment]
This is something we'd like to explore for yt as well, where dict-like access is used to generate fields on-demand.  So having something generic would be awesome!

**Comment by takluyver** [comment]
#9289 adds this - can you have a look at the proposed API?

**Comment by shoyer** [comment]
Thanks!
