### ISSUE TITLE
Where has sphinxext subpackage gone?

### ISSUE THREAD

**Issue by dr-leo** [ipython/ipython#8867]
I haven't found any up to date docs on this. ipykernel does not contain the sphinxext subpackage. The docs on "migrating to Jupyter/imports" are silent.

So where can I find the latest ipython_directive etc.?

Thanks.

**Comment by minrk** [comment]
The IPython sphinx extension remains in the ipython package, it has not moved. It doesn't use the Jupyter machinery at all, it uses the IPython InteractiveShell directly.

**Comment by dr-leo** [comment]
I see.

My understanding was that IPython has been replaced with Jupyter +
ipykernel. Apparently this is wrong. I'lll further look into this.

Thanks.

Leo

**Comment by minrk** [comment]
@dr-leo Sorry for the miscommunication. IPython isn't going anywhere, it's just shrinking back to a better IPython shell. The `ipykernel` package is a small wrapper around IPython to communicate via the Jupyter protocol.

**Comment by dr-leo** [comment]
Thanks for this helpful clarification. It is much appreciated.

Leo
