### ISSUE TITLE
Feature request - quick export to Excel

### ISSUE THREAD

**Issue by listuk** [ipython/ipython#8869]
Hi,

I often find myself having to export pandas dataframes to Excel for various reasons. This involves saving the dataframe to an excel file and then opening that file in excel. 

It would be very useful if one could right click on a dataframe in a ipython cell then 'export to excel' such that ipython launches excel with a copy of that dataframe contents within it.

Is it possible to have this as a feature?

Thanks

**Comment by minrk** [comment]
I'm sure people would like this, but it's not really in-scope for IPython. Perhaps a custom representation of a data frame that includes this action. I believe DataFrames already have export-to-excel functionality (csv probably works, too, in most cases), so hooking up a button to that in a custom DataFrame representation should be doable.
