### ISSUE TITLE
Ipython crashing with pasting

### ISSUE THREAD

**Issue by fjafjan** [ipython/ipython#8870]
I am running 32 bit ipython on a 64 bit windows 7 machine. 

I am running some pretty short numpy/scipy scripts, and to check some things occuring inside functions I lazily copy paste their contents into ipython to play around with it. However seemingly randomly when pasting certain snippets into ipython it crashes/becomes unresponsive. I have yet to be able to identify what character causes this behaviour. The prompt still flashes, but ctrl+C, ESC, seemingly any sort of button presses etc do nothing, and I have to close the prompt and open a new one to continue. 

When trying to find this bug I read that the preferred way of doing things is to use %paste, but this still can't be desired behaviour since it doesn't object and let you continue but, at least as far as I have tried, completely locks down your prompt. 

EDIT: Here is a snippet of code I tried to paste repeatedly and all caused ipython to lock down when pasting "manually" (right click/C+v)

```
T_world = normalize(x_world_in)
x_world = project(np.dot(T_world, homogenize(x_world_in).T))


T_image = normalize(x_image_in)
x_image = project(np.dot(T_image, homogenize(x_image_in).T))





Kt = get_K(x_image[:,0], x_image[:,1], x_world[:,0], x_world[:,1])

Tr = get_Tr(Kt, x_image[:,0])

C = get_C(Tr)


Ty = get_Ty(C, Tr)
Ty = correct_Ty_sign(Tr, Ty, x_world[0][0], x_world[0][1])

print "we get Ty ", Ty

Tx = get_Tx(Tr, Ty)

R = get_R(Tr, Ty)
xyw = get_xyw( R, x_world[:,0], x_world[:,1], Tx, Ty)

Y_trans = get_Y_trans(xyw, x_image)
Z_approx = xyw[:,2] * x_image[:,1]

f, Tz = get_fTz(Y_trans, Z_approx)

if f < 0:
    print "we picked the wrong solution"
    R = R * array([[1,1,-1],[1,1,-1], [-1,-1,1]])
    xyw = get_xyw(R, x_world[:,0], x_world[:,1], Tx, Ty)
    Y_trans = array([ xyw[:,1], -x_image[:,1]]).transpose()
    Z_approx = xyw[:,2] * x_image[:,1]
    f, Tz = get_fTz(Y_trans, Z_approx)

T = array([Tx, Ty, Tz])

args= (R, T, x_world, x_image)
kwargs = {"args": args}

from scipy.optimize import basinhopping, minimize

guess = basinhopping(est_x_error, [f, Tz, 0], niter = 500, minimizer_kwargs = kwargs)['x']

#~ guess = calibration.est_x_error, [f, Tz, 0], niter = 500, minimizer_kwargs = kwargs)
#~ guess = sp.optimize.basinhopping(calibration.est_x_error, [f, Tz, 0], niter = 500)['x']
#~ res = minimize(calibration.est_x_error, [f, Tz, 0], args=args, method= 'nelder-mead', options={'maxiter':10000, 'maxfev':10000})

print "before optimization f, Tz and kappa are", [f, Tz, 0]
f, Tz, kappa = guess
print "after optimization f, Tz and kappa are", [f, Tz, kappa]
P = calc_P(guess, R, T)

tsai_error = test_P(P, x_world, x_image)
print "normalized error using Tsai calibration is ", tsai_error

image_tsai = camera_project(P, x_world)
image_est = np.dot( np.linalg.inv(T_image), image_tsai)
```

**Comment by minrk** [comment]
When you paste into the terminal, it emulates typing every character, which can get messed up by the autoindent logic. For plain terminals, it's definitely preferable to use `%paste`, which reads from the clipboard directly, then executes the code. If you still want to paste into the terminal, then it's best to use `%cpaste`, which turns off some of the input processing.

When you paste, can you make the very first line a print statement, to verify that it's actually getting hung up pasting, and not during the execution of some of the code?

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. We haven't heard back for more info from the original report, please open a new issue if you end up running into this or something similar again.

Thanks everyone and happy hacking! :bowtie:
