### ISSUE TITLE
Recovery of a stopped interpreter process (ctrl-z) no longer works

### ISSUE THREAD

**Issue by wasade** [ipython/ipython#8872]
I have a non-standard IPython prompt, but the entries below that use ">" are IPython while the entries that use "$" are bash. I'm using OSX 10.10.3. Relevant version info below. For a human description, if I pause the interpreter using ctrl-z, I cannot bring the process back to the foreground. In order to restore the job, I need to issue a break (ctrl-c), followed by a stop (ctrl-z), followed by a 'fg' call to restore. An example is shown below. It used to be the case that, following bringing the job back to the foreground, all that was necessary to restore the prompt was a character return. 

As a sanity test, I performed the same job stopping and restoring without issue using the standard Python interpreter.

I couldn't find this issue described in the issue tracker, but I apologize if this is a known issue. Please let me know if any additional detail is needed.

```python
13:35:45 (mcdonadt@8086):AG> ^Z
[1]+  Stopped                 ipython
(py34-base)13:35:48 (mcdonadt@8086):AG@preprocessing_revitalized$ fg
ipython


doesn't work

^C
^Z
[1]+  Stopped                 ipython
(py34-base)13:35:57 (mcdonadt@8086):AG@preprocessing_revitalized$ fg
ipython
^C
KeyboardInterrupt

13:35:58 (mcdonadt@8086):AG> sys.version_info
Out[10]: sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0)

13:39:30 (mcdonadt@8086):AG>
(py34-base)13:41:54 (mcdonadt@8086):AG@preprocessing_revitalized$ python
Python 3.4.3 |Continuum Analytics, Inc.| (default, Mar  6 2015, 12:07:41)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ^Z
[1]+  Stopped                 python
(py34-base)13:41:58 (mcdonadt@8086):AG@preprocessing_revitalized$ fg
python

>>>
```

**Comment by minrk** [comment]
Does it work if you launch IPython with `python -m IPython` instead of `ipython`? I think this may be related to a weird way that conda is building entrypoints.
