### ISSUE TITLE
Documentation unclear about install kernels

### ISSUE THREAD

**Issue by michaelaye** [ipython/ipython#8873]
The docs say:

> make sure that the desired python installation is active (e.g. activate the environment) and ipython is installed

and 

> run once ipython kernelspec install-self --user (or ipython2 ... or ipython3 ... if you want to install specific python versions)

but when I made sure of the first one, only the ipython version fitting to the version of the active environment is on the path. I think the documentation should make clear that this is only possible using the absolute path to the respective other ipython kernel to install, best with an explicit full command-line example.

On a side note, I am wondering if it's not possible to include this step into the conda install routine? Why would I install the conda ipython package without registering the kernel into an existing (to be checked I guess) jupyter package?

**Comment by minrk** [comment]
> when I made sure of the first one, only the ipython version fitting to the version of the active environment is on the path

This is exactly the goal. You activate the environment of the IPython kernel you want to install, then run `ipython kernelspec install-self` in that environment.

> On a side note, I am wondering if it's not possible to include this step into the conda install routine? 

It is not, because conda only ever touches files in one env at a time. If IPython is installed in one env, it can only put its kernelspec files into that same env. This defeats the purpose, because then the kernelspec isn't accessible to Jupyter in another env.

**Comment by jorisvandenbossche** [comment]
@minrk is the documentation not out of date? Looking back at https://github.com/jupyter/jupyter/issues/23, it seems that `ipython kernelspec install-self` is deprecated, and that you should use `ipython kernel install` instead (https://github.com/ipython/ipykernel/pull/43)

**Comment by minrk** [comment]
@jorisvandenbossche yes, `ipython kernel install` is the way forward. But it's only been out for an hour or so, so it will take a bit for the docs to be updated. See #8877. We will probably try to keep `ipython kernelspec install-self` working, for backward-compatibility reasons.

**Comment by jorisvandenbossche** [comment]
@minrk OK, I was a bit quick :-) (I looked at the dev docs, and since it was already some time in master ..) 
Nice explanation in #8877!

**Comment by michaelaye** [comment]
> It is not, because conda only ever touches files in one env at a time. If IPython is installed in one env, it can only put its kernelspec files into that same env. This defeats the purpose, because then the kernelspec isn't accessible to Jupyter in another env.

I didn't mean the conda install to work across environments, I meant to have it install itself only the current kernel for the current environment. I did a fresh install of miniconda yesterday and was faced with a kernel not found error, even so every required package was installed. Had to execute the lines from the docs to have the kernel found. Would be nice if that at least per environment would work out of the box.

**Comment by minrk** [comment]
Ah, yes. It makes sense for the conda ipykernel package to include its kernelspec in the env. That won't solve every problem (it will still be lower priority than `--user` kernels), but it will at least be present.
