### ISSUE TITLE
ipython does not load libraries which python does

### ISSUE THREAD

**Issue by nicolavianello** [ipython/ipython#8878]
System: OSX 10.11, anaconda python distribution (2.3.0), ipython 4.0.0 version
I try to load a module imported with easy_install.
The module relies on some libraries which are correctly listed in DYLD_LIBRARY_PATH (they are in /usr/local/...) and the module can be loaded in python easily (there are no virtualenv installed, and the python interpreter is the one in ~/anaconda/bin/python) 
The same module does not load in ipython claiming it does not find the libraries
Here is the ipython output

    Python 2.7.10 |Anaconda 2.3.0 (x86_64)| (default, Sep 15 2015, 14:29:08) 
    Type "copyright", "credits" or "license" for more information.
    IPython 4.0.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    Using matplotlib backend: MacOSX 
    Running startu

    In [1]: import MDSplus
    Error importing MDSplus package: dlopen(libTreeShr.dylib, 6): image not found

the libTreeShr.dylib is in /usr/local/mds/lib

    In [2]: os.getenv('DYLD_LIBRARY_PATH')
    Out[2]: '/usr/local/mdsplus/lib/'
    In [3]: os.getenv('LD_LIBRARY_PATH')
    Out[3]: 'usr/local/mdsplus/lib/'

I have to admit that originally the ipython interpreter did not load the library and I added with this script in the ~/.ipython/profile_default/startup
    import os
    import sys
    print 'Running startup'
 
    mdsplus_libs = os.environ['MDSPLUS_DIR']+"/lib/"
    rerun = True

    if not 'DYLD_LIBRARY_PATH' in os.environ:
        os.environ['DYLD_LIBRARY_PATH'] = mdsplus_libs 
    elif not mdsplus_libs in os.environ.get('DYLD_LIBRARY_PATH'):
        os.environ['DYLD_LIBRARY_PATH'] += +mdsplus_libs
    else:
        rerun = False

No issue exists in the normal python interpreter

     Python 2.7.10 |Anaconda 2.3.0 (x86_64)| (default, Sep 15 2015, 14:29:08) 
     [GCC 4.2.1 (Apple Inc. build 5577)] on darwin
     Type "help", "copyright", "credits" or "license" for more information.
     Anaconda is brought to you by Continuum Analytics.
     Please check out: http://continuum.io/thanks and https://anaconda.org
     >>> import MDSplus 
     >>> import os
     >>> os.getenv('DYLD_LIBRARY_PATH')
     '/usr/local/mdsplus/lib'
     >>>

Before asking the solution proposed here  https://www.google.ch/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CB4QFjAAahUKEwiKlc7HsLDIAhVFiywKHbnmCuA&url=https%3A%2F%2Fgroups.google.com%2Fa%2Fcontinuum.io%2Fd%2Ftopic%2Fanaconda%2FPEuOKEM5fdc&usg=AFQjCNGJaYIs-nOfSfqHvU6pebpINVAcLA&sig2=4LQ7Kb-z5ivj_Dx_N2V0-w is not working for me

I don't know how to solve this problem and I can't recognized neither if it is an ipython issue (it seems actually).

**Comment by minrk** [comment]
There does appear to be a difference in your two cases, where one has a trailing slash and the other doesn't. I'm not sure if that's relevant, but can you verify that the behavior is different with the *exact same env*?

**Comment by nicolavianello** [comment]
Hi I've checked now the answer is exactly the same in both the env
Python 

    >>> os.getenv('DYLD_LIBRARY_PATH')
    '/usr/local/mdsplus/lib'

Ipython 

    In [2]: os.getenv('DYLD_LIBRARY_PATH')
    Out[2]: '/usr/local/mdsplus/lib'

and the same with LD_LIBRARY_PATH

**Comment by minrk** [comment]
Hm. IPython doesn't touch anything to do with library paths, so I don't really understand what could be different. Can you share `env | grep LIBRARY` in the shell prior to starting IPython or Python? Can you try setting the env in the shell, and make sure you *don't* modify os.environ once the interpreter has started up?

**Comment by nicolavianello** [comment]
so the output of the command 

    env | grep LIBRARY

is empty actually (the setting is done directly on /etc/profile), whereas if I do an

    echo $DYLD_LIBRARY_PATH
    /usr/local/mdsplus/lib

I've tried to set in the shell the environment again

    export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/mdsplus/lib
    export LD_LIBRARY_PATH=/usr/local/mdsplus/lib

and this is the answer

    Python 2.7.10 |Anaconda 2.3.0 (x86_64)| (default, Sep 15 2015, 14:29:08) 
    [GCC 4.2.1 (Apple Inc. build 5577)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    Anaconda is brought to you by Continuum Analytics.
    Please check out: http://continuum.io/thanks and https://anaconda.org
    >>> import MDSplus
    >>> import os
    >>> os.getenv('DYLD_LIBRARY_PATH')
    '/usr/local/mdsplus/lib:/usr/local/mdsplus/lib'

whereas for ipython

    Python 2.7.10 |Anaconda 2.3.0 (x86_64)| (default, Sep 15 2015, 14:29:08) 
    Type "copyright", "credits" or "license" for more information.
    IPython 4.0.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    Using matplotlib backend: MacOSX

    In [1]: import os
    In [2]: os.getenv('DYLD_LIBRARY_PATH')

As you can see, setting the library in the shell before opening ipython does not load the environment settings. I have to add that this problem only happened after upgrading to OSX 10.11

**Comment by jenshnielsen** [comment]
I can reproduce this on OSX but only when using Conda. It seems to be caused by by the hash bang in the conda script.

```
#!/bin/bash /Users/jhn/miniconda3/bin/python.app
```

**Comment by nicolavianello** [comment]
Is there a fix I can use for this hash bang problem?

**Comment by jenshnielsen** [comment]
I got it working by modifying the hashbang to be 

```
#!/Users/jhn/miniconda3/bin/python
```

but I don't know why the Conda hashbang looks like this and modifying it is on your own risk. It may cause other things to fail

**Comment by minrk** [comment]
This appears to be a conda issue. They seem to be explicitly stripping DYLD_LIBRARY_PATH on entrypoints:

```
(test) $ export DYLD_LIBRARY_PATH=foo
(test) $ ~/conda/envs/test/bin/python -c "import os; print(os.environ.get('DYLD_LIBRARY_PATH'))"
foo
(test) $ ~/conda/envs/test/bin/python.app -c "import os; print(os.environ.get('DYLD_LIBRARY_PATH'))"
None
(test) $ ~/conda/envs/test/bin/ipython -c "import os; print(os.environ.get('DYLD_LIBRARY_PATH'))"
None
(test) $ ~/conda/envs/test/bin/python -m IPython -c "import os; print(os.environ.get('DYLD_LIBRARY_PATH'))"
foo
(test) $ export OTHER_ENV=bar
(test) $ ~/conda/envs/test/bin/python.app -c "import os; print(os.environ.get('OTHER_ENV'))"
bar
```
