### ISSUE TITLE
Change in behavior launching ipython notebooks from anacona environment

### ISSUE THREAD

**Issue by jhamman** [ipython/ipython#8880]
Cross posting this issue from https://github.com/ContinuumIO/anaconda-issues/issues/461.  This may actually be an ipyhon issue, rather than an anaconda issue.

**Comment by jasongrout** [comment]
CCing @minrk.  I've used Min's a2km script to set up different kernels in different environments.  https://github.com/minrk/a2km

**Comment by jasongrout** [comment]
actually, the https://github.com/jupyter/notebook repo is probably more appropriate for this issue.

**Comment by jhamman** [comment]
closing.  future discussion on this topic will be here: https://github.com/jupyter/notebook/issues/541
