### ISSUE TITLE
c.InteractiveShell.colors does not work

### ISSUE THREAD

**Issue by dashesy** [ipython/ipython#8885]
Setting `c.InteractiveShell.colors = 'Linux'` or `%colors Linux` does not work in 4.0.1 and `--colors linux` is deprecated.
I use `QtConsole` because I have many many graphs and want to use `qt` backend not the inline one which is not possible with notebook. So I set the backend in the profile and wanted to also set the dark background color there, but it is not effective.
 
P.S. `pygments` is installed and I do not get any errors or warnings.

**Comment by minrk** [comment]
InteractiveShell.colors only affects IPython (this repo), it does not affect the Jupyter QtConsole. Does it work if you do `jupyter qtconsole --style=monokai`?

**Comment by dashesy** [comment]
That works (so does `ipython qtconsole --style=monokai` but I will start to learn the new name) and I like the style, thanks :)

**Comment by dashesy** [comment]
While providing the syntax on the command line works, `c.JupyterWidget.style = "monokai"` and `c.JupyterWidget.syntax_style = "monokai"` seems to have no effect.

**Comment by takluyver** [comment]
Where are you setting that? The Qt console has its own configuration file, so if you're setting it in `ipython_config.py`, it won't take effect.

http://jupyter.org/qtconsole/stable/config_options.html

**Comment by dashesy** [comment]
You are right. I did a `jupyter qtconsole --generate-config` first and added `c.JupyterWidget.syntax_style = "monokai"` to it and now it works. generate-config for qtconsole was not documented, I sort of guessed it.

**Comment by takluyver** [comment]
It's kind of documented here: http://jupyter.readthedocs.org/en/latest/config.html - but it's a bit tricky because that's not obvious from individual application docs, and we don't want to duplicate that information. We should make sure that page is clearly linked from the Qt console config docs.
