### ISSUE TITLE
Cannot connect to remote kernel

### ISSUE THREAD

**Issue by wuyingmm** [ipython/ipython#8892]
I am trying to start a remote IPython process (kernel) in remote server and connect Spyder or ipython qtconsole or ipython console to it. But all failed :(

The remote server is Ubuntu server running as Virtual Machine (VirtualBox). The IP is 10.0.2.15.

WinPython 2.7 is installed on Windows 7 locally. Spyder version is 2.3.5.2.

I define port forward in VirtualBox from 127.0.1.1:22 to 10.0.2.15:22, by which I can use PuTTY to connect to the remote server by SSH. The connection is by private/public keys, where the public key is on server side and private key saved locally.

Anaconda is installed in the remote server. To start a ipython kernel on the remote server, I use:

![image](https://cloud.githubusercontent.com/assets/4717309/10405853/e29f3ccc-6ed3-11e5-9fda-8ba5f100796f.png)

I copy the kernel-remote.json file from the remote server to my local Windows. 

Then I open a command window in the local machine. I use the command:

![image](https://cloud.githubusercontent.com/assets/4717309/10405886/15077ec2-6ed4-11e5-95fa-cf26cdfc01bc.png)

I get lot of messages:

![image](https://cloud.githubusercontent.com/assets/4717309/10405916/4cbc4dac-6ed4-11e5-9fa8-4899afe2433d.png)

If I use ipython qtconsole, I get the error message:

![image](https://cloud.githubusercontent.com/assets/4717309/10405997/cda29dae-6ed4-11e5-8b74-00648475e2d5.png)

If I use spyder, it crashes directly!!!!!!!!!!!!!

![image](https://cloud.githubusercontent.com/assets/4717309/10406002/e189025e-6ed4-11e5-9e0a-703f6fe4eaa8.png)

I think this is more likely a bug from the ipython. Any idea? Thanks very much.

**Comment by minrk** [comment]
@SylvainCorlay, @ccordoba12 or any other Spyder and/or Windows folks know what's up here?

**Comment by ccordoba12** [comment]
We have received several reports about people not being able to connect to IPython kernels created on Linux from Windows. Unfortunately, we haven't had time to investigate further about it.

However, @SylvainCorlay told me that that use case was working fine for him on a couple of tests.

----

@wuyingmm, could you replace

     ipython console ....

for

    ipython qtconsole ....

and report back?

Maybe that avoids using `multiprocessing` in the background (as your traceback shows), which is known to not work so well with IPython kernels.

----

@stonebig, does WinPython comes with `paramiko`?

**Comment by stonebig** [comment]
no, it doesn't. why this question ?

**Comment by stonebig** [comment]
Couldn't it be that:
- Putty requires some parametrizing tweak ?
- some trafic is not going through port 80 only ?

**Comment by ccordoba12** [comment]
I think paramiko is needed to do ssh connections on Windows. But @SylvainCorlay knows more about :-)

**Comment by stonebig** [comment]
@wuyingmm could you jut `pip install paramiko`and retry ?

**Comment by stonebig** [comment]
hum, I have an issue to include paramiko, as it needs pycripto which doesn't compile easily on windows (it tries to play with `chmod`)

**Comment by SylvainCorlay** [comment]
Indeed paramiko is required on Windows. I don't think that it is included with winpython.

**Comment by stonebig** [comment]
WinPython is not currently a nice fit for @wuyingmm:
- paramiko requires pycrypto which requires a `msys' environnement for a mere compilation from source,
- WinPython doesn't include `msys`.
==> @wuyingmm should consider using an alternative solution for this functionnality.

**Comment by ccordoba12** [comment]
Sylvain, how did you test this? Using Anaconda?

**Comment by SylvainCorlay** [comment]
@ccordoba12 I have tried different combinations and versions.
- For the server side, it was always Linux but I tried the versions from apt-get on Ubuntu and from Anaconda. At the time, the apt-get version was 1.x
- For the client side, I tried on Windows (7) and Linux, using Anaconda only.

**Comment by ccordoba12** [comment]
Ok, thanks for the info Sylvain :-) This means that:

1. Anaconda comes with paramiko on Windows, which is good to know :-)
2. We need to add a paramiko entry in our Dependencies dialog to tell 
our users about it being necessary on Windows.

**Comment by SylvainCorlay** [comment]
We could also disable the remote kernel connection option if paramiko is missing.

**Comment by ccordoba12** [comment]
You're right, both things are necessary: disabling that portion of the 
dialog and adding an entry in Dependencies.

**Comment by wuyingmm** [comment]
Hi,

With the issue I have raised, please note I have installed the paramiko and
pycrypto in my local PC. So it should not be because the paramiko.

Thanks




2015-10-19 17:12 GMT+01:00 Carlos Cordoba <notifications@github.com>:

**Comment by takluyver** [comment]
Closing as probably not an IPython bug. Feel free to continue using comments for discussion.
