### ISSUE TITLE
Error when converting notebook with SVG images to markdown

### ISSUE THREAD

**Issue by edgimar** [ipython/ipython#8896]
To reproduce the problem:

1. Create a notebook that contains the following content in a cell:
    ```python
    %matplotlib inline
    %config InlineBackend.figure_format = 'svg'

    from matplotlib import pyplot as plt
    plt.plot([1,2,3,5,1,1,1])
    ```
2. Execute the cell
3. Save the notebook (e.g. as `mynotebook.ipynb`).
4. Attempt to convert the notebook to markdown:  `ipython nbconvert mynotebook.ipynb --to markdown` -- you will get a traceback for an `UndefinedError: 'IPython.nbformat.notebooknode.NotebookNode object' has no attribute 'svg_filename'`

I'm using ipython version 3.1.0.

**Comment by minrk** [comment]
@edgimar fixed in 3.2 by #8392. Upgrading should do it.
