### ISSUE TITLE
bad rendering of items in "Help" menu in Firefox with ipython4

### ISSUE THREAD

**Issue by stonebig** [ipython/ipython#8897]
I get this strange issue (on windows/firefox):
![ipython4help_issue](https://cloud.githubusercontent.com/assets/4312421/10416172/52386b98-700b-11e5-97d6-b03833542c21.gif)

with this package list :
````
ipykernel (4.0.3)
ipyparallel (4.0.2)
ipython (4.0.0)
ipython-genutils (0.1.0)
ipython-sql (0.3.7.1)
ipywidgets (4.0.3)
jupyter (1.0.0)
jupyter-client (4.0.0)
jupyter-console (4.0.2)
jupyter-core (4.0.6)
````

**Comment by minrk** [comment]
I believe this is fixed in notebook-4.0.6. What version do you have?

**Comment by stonebig** [comment]
it was the version 4.0.5. Ok I update and will re-open if not ok

**Comment by stonebig** [comment]
4.0.6 is not on pypi yet ?

**Comment by minrk** [comment]
This shows 4.0.6 for me: https://pypi.python.org/pypi/notebook Does it not for you?

**Comment by stonebig** [comment]
yes, I didn't look right. 4.0.6 is indeed on pypi since Oct 9th
