### ISSUE TITLE
How to kill idle Jupyterhub Notebook (Python) logged session ?

### ISSUE THREAD

**Issue by Balajideivam** [ipython/ipython#8906]
I want to know how we can kill/session timeout after 10 min if the session is idle. Is there any Configuration paramater we can use?

**Comment by minrk** [comment]
There is an [example](https://github.com/jupyter/jupyterhub/blob/0.2.0/examples/cull-idle/cull_idle_servers.py) demonstrating the culling of idle servers. The Hub tracks the information about last activity, but doesn't act on it. External services can be run to perform actions like this, though.
