### ISSUE TITLE
history of command confused 

### ISSUE THREAD

**Issue by HB6H057** [ipython/ipython#8910]
history of command confused when I press UP key look for it 

![image](https://cloud.githubusercontent.com/assets/5207968/10506481/0710d342-734b-11e5-8f5c-da471109fd30.png)

system info:
```
{'codename': 'An Afternoon Hack',
 'commit_hash': '7c2ea3a',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/we1/Workspace/haitao/env/lib/python2.7/site-packages/IPython',
 'ipython_version': '1.1.0',
 'os_name': 'posix',
 'platform': 'Darwin-14.4.0-x86_64-i386-64bit',
 'sys_executable': '/Users/we1/Workspace/haitao/env/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '2.7.6 (default, Sep  9 2014, 15:04:36) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]'}
```

**Comment by takluyver** [comment]
That looks like a readline issue. Also, IPython 1.1 is really quite old - see if upgrading to a newer version helps.

Closing as there's probably nothing we can do (besides abandoning readline entirely, which is in the works at #9118).

**Comment by HB6H057** [comment]
@takluyver thanks! Good luck to you!
