### ISSUE TITLE
nbconvert --to pdf fails when you have images in markdown

### ISSUE THREAD

**Issue by achampion** [ipython/ipython#8913]
I have a local (same directory) image embedded into a piece of markdown which displays fine:

    ![](my.png)

But convert to pdf fails with:

    LaTeX Warning: File `my.png' not found on input line 948.    
    ! Package pdftex.def Error: File `my.png' not found.    
    See the pdftex.def package documentation for explanation.
    Type  H <return>  for immediate help.
     ...                                                                                                
    l.948 \includegraphics{my.png}                          
    ? 
    ! Emergency stop.

Embedded images should be able to be displayed.
What about other images linked from the web?

**Comment by Carreau** [comment]
Please don't open issues twice, thanks. 

Following up on other issue: https://github.com/jupyter/nbconvert/issues/142
