### ISSUE TITLE
nbconvert to PDF failing when using template

### ISSUE THREAD

**Issue by jamiemcGit** [ipython/ipython#8915]
We are trying to get nbconvert to output as a PDF and hide input cells using the template file (attached)
this error is occurring on Mac OS X Yosemite
notebook file contents and template file contents included below -- also traceback output, etc

Creation of HTML file from the template works well, using the following command=
ipython nbconvert Untitled.ipynb --to slides --template pdf_hide_input.tpl --post serve

However -- creation of PDF output fails with the error shown below -- when running the following command =
ipython nbconvert Untitled.ipynb --template=pdf_hide_input.tpl --to=pdf --output=./Untitled.pdf --execute

testing for Latex output -- the output file is just the same as the template file, apparently indicating that the template file was not processed in the conversion

Error traceback output below
========================
jamie$ ipython nbconvert ~/rmzq/Untitled.ipynb --template=pdf_hide_input.tpl --to=pdf --output=~/rmzq/Untitled.pdf --execute
[NbConvertApp] Converting notebook /Users/jamie/rmzq/Untitled.ipynb to pdf
[NbConvertApp] Executing notebook with kernel: python2
[NbConvertApp] Writing 111 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running pdflatex 3 times: [u'pdflatex', u'notebook.tex']
[NbConvertApp] CRITICAL | pdflatex failed: [u'pdflatex', u'notebook.tex']
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./notebook.tex
LaTeX2e <2015/01/01>
Babel <3.9l> and hyphenation patterns for 79 languages loaded.

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.5 {{ s
        uper() }}
? 
! Emergency stop.
 ...                                              
                                                  
l.5 {{ s
        uper() }}
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on notebook.log.

[NbConvertApp] Running bibtex 1 time: [u'bibtex', u'notebook']
[NbConvertApp] WARNING | bibtex had problems, most likely because there were no citations
[NbConvertApp] Running pdflatex 3 times: [u'pdflatex', u'notebook.tex']
[NbConvertApp] CRITICAL | pdflatex failed: [u'pdflatex', u'notebook.tex']
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./notebook.tex
LaTeX2e <2015/01/01>
Babel <3.9l> and hyphenation patterns for 79 languages loaded.

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.5 {{ s
        uper() }}
? 
! Emergency stop.
 ...                                              
                                                  
l.5 {{ s
        uper() }}
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on notebook.log.

Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Library/Python/2.7/site-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Library/Python/2.7/site-packages/traitlets/config/application.py", line 592, in launch_instance
    app.start()
  File "/Library/Python/2.7/site-packages/IPython/terminal/ipapp.py", line 349, in start
    return self.subapp.start()
  File "/Library/Python/2.7/site-packages/nbconvert/nbconvertapp.py", line 286, in start
    self.convert_notebooks()
  File "/Library/Python/2.7/site-packages/nbconvert/nbconvertapp.py", line 409, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/Library/Python/2.7/site-packages/nbconvert/nbconvertapp.py", line 380, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources)
  File "/Library/Python/2.7/site-packages/nbconvert/nbconvertapp.py", line 332, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/Library/Python/2.7/site-packages/nbconvert/exporters/exporter.py", line 166, in from_filename
    return self.from_notebook_node(nbformat.read(f, as_version=4), resources=resources, **kw)
  File "/Library/Python/2.7/site-packages/nbconvert/exporters/pdf.py", line 139, in from_notebook_node
    raise RuntimeError("PDF creating failed")
RuntimeError: PDF creating failed

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

Template file contents below
=======================
{%- extends 'slides_reveal.tpl' -%}

{% block input_group -%}
{% endblock input_group %}

{%- block header -%}
{{ super() }}
{%- endblock header -%}

Notebook file contents below
=======================
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hola IPython devs\n"
     ]
    }
   ],
   "source": [
    "print \"Hola IPython devs\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}

**Comment by jakobgager** [comment]
Latex template use double braces instead of curly braces to mark jinja blocks, compare with the [shipped templates](https://github.com/jupyter/nbconvert/blob/master/nbconvert/templates/latex/report.tplx). Hence your template has to be adapted.
Moreover, the latex templates are fundamentally different than the other, e.g. reveal templates. So you will have to base your pdf template on a latex template.

**Comment by takluyver** [comment]
There's an example template for hiding input cells in Latex here:

https://github.com/jupyter/ngcm-tutorial/blob/master/Day-2/nbconvert_templates/solutions/hidecode.tplx
