### ISSUE TITLE
How to add R notebook in Jupyterhub? 

### ISSUE THREAD

**Issue by Balajideivam** [ipython/ipython#8917]
Currently I have Python2.7 and 3.4 in my jupyterhub Notebook list. I want to see whether i can add R language also under the Notebook list. 
I found that we have to install r2_kernel which i did and now i am able to see the R listing under the Notebook drop down list. 

My kernel.json file looks like below. 

{"argv": ["/opt/seagate/jupyterhub/anaconda3/bin/python3.4", "-m", "r2_kernel", "-f", "{connection_file}"], "display_name": "R", "language": "R"}

But when I tried to launch this R, I am getting below error message. 

[I 2015-10-19 12:53:49.723 deivamb kernelmanager:85] Kernel started: 7abafcc9-af8a-48fa-b4f2-a1929302409d
/opt/seagate/jupyterhub/anaconda3/bin/python3.4: Error while finding spec for 'r2_kernel.__main__' (<class 'ImportError'>: /seamnt/int001/seagate/jupyterhub/anaconda3/bin/../lib/libreadline.so.6: undefined symbol: PC); 'r2_kernel' is a package and cannot be directly executed
[I 2015-10-19 12:53:52.726 deivamb restarter:103] KernelRestarter: restarting kernel (1/5)
/opt/seagate/jupyterhub/anaconda3/bin/python3.4: Error while finding spec for 'r2_kernel.__main__' (<class 'ImportError'>: /seamnt/int001/seagate/jupyterhub/anaconda3/bin/../lib/libreadline.so.6: undefined symbol: PC); 'r2_kernel' is a package and cannot be directly executed
[I 2015-10-19 12:53:55.732 deivamb restarter:103] KernelRestarter: restarting kernel (2/5)
/opt/seagate/jupyterhub/anaconda3/bin/python3.4: Error while finding spec for 'r2_kernel.__main__' (<class 'ImportError'>: /seamnt/int001/seagate/jupyterhub/anaconda3/bin/../lib/libreadline.so.6: undefined symbol: PC); 'r2_kernel' is a package and cannot be directly executed
[I 2015-10-19 12:53:58.740 deivamb restarter:103] KernelRestarter: restarting kernel (3/5)
/opt/seagate/jupyterhub/anaconda3/bin/python3.4: Error while finding spec for 'r2_kernel.__main__' (<class 'ImportError'>: /seamnt/int001/seagate/jupyterhub/anaconda3/bin/../lib/libreadline.so.6: undefined symbol: PC); 'r2_kernel' is a package and cannot be directly executed
[W 2015-10-19 12:54:00.165 deivamb handlers:188] Timeout waiting for kernel_info reply from 7abafcc9-af8a-48fa-b4f2-a1929302409d
[I 2015-10-19 12:54:01.746 deivamb restarter:103] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 7abafcc9-af8a-48fa-b4f2-a1929302409d restarted
/opt/seagate/jupyterhub/anaconda3/bin/python3.4: Error while finding spec for 'r2_kernel.__main__' (<class 'ImportError'>: /seamnt/int001/seagate/jupyterhub/anaconda3/bin/../lib/libreadline.so.6: undefined symbol: PC); 'r2_kernel' is a package and cannot be directly executed
[W 2015-10-19 12:54:04.753 deivamb restarter:95] KernelRestarter: restart failed

Could you please help me out how to fix this issue? Do I need to install anything on R?

**Comment by minrk** [comment]
It is likely that you want to be using the [IRKernel](https://github.com/IRkernel/IRkernel/), which is a native R kernel for Jupyter, not r2_kernel, a toy Python-based wrapper kernel for R.
