### ISSUE TITLE
NameError in list comprehension when using embed

### ISSUE THREAD

**Issue by mathieulongtin** [ipython/ipython#8918]
This used to work, and stopped working somewhere around six months to a year ago.

```
In [51]: from os.path import getsize

In [52]: ziplen = dict((_, getsize(_)) for _ in zips)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/nrg1/tools/datateam/packages/nuance.com/nvc4-pipeline-utils/nvc4qless.py in <module>()
----> 1 ziplen = dict((_, getsize(_)) for _ in zips)

/nrg1/tools/datateam/packages/nuance.com/nvc4-pipeline-utils/nvc4qless.py in <genexpr>((_,))
----> 1 ziplen = dict((_, getsize(_)) for _ in zips)

NameError: global name 'getsize' is not defined
```

`zips` is a list of paths, but this happens for list comprehension all over the place. Not sure what local/global namespace the list comprehension doesn't get.

**Comment by minrk** [comment]
What version of Python, IPython, etc.? How are you starting IPython?

It seems to be working here:

```python
$> ipython
Python 3.5.0 (/.../conda/bin/python3)
IPython 4.1.0-dev@efabd7f

In [1]: from os.path import getsize

In [2]: zips = !ls *.zip

In [3]: ziplen = dict((_, getsize(_)) for _ in zips)

In [4]: ziplen
Out[4]: 
{'06-ViewFromNib.zip': 19189,
 '06-ViewWithCode.zip': 18770,
 '07-MyTabBar.zip': 50205,
 '07-PushAndPop.zip': 24027,
 '08-MyTableView.zip': 68867,
 '08-Scroll.zip': 1704092,
 '09-MyFlickrTableView.zip': 77113,
 '09-MySQLiteTableView.zip': 44526}
```

**Comment by mathieulongtin** [comment]
Thanks for the prompt reply!

I use Python 2.7.3, and IPython 4.0, but the key part is I use a variation on this:
```
python -c 'from IPython import embed; embed()'
```
In that case, the `globals` come from embedding script, and `getsize` is put in the `locals`. It appears that list comprehensions don't do `locals` lookup. 

When using the ipython command, `globals()` and `locals()` are the same, and the above code works as advertised.

This works in both cases:
```
ziplen= dict()
for _ in zips:
    ziplen[_] = getsize(_)
```

**Comment by minrk** [comment]
This appears to be a duplicate of #62, which was closed, though I can confirm that it is no longer fixed. Can I ask how/why you are using `embed`?

**Comment by mathieulongtin** [comment]
We have an admin utility for our system, but when what you want to do doesn't fit in the existing admin commands, you can drop down to an IPython shell already loaded with some configuration and functions:
```
$ mysystemadmin shell
...
IPython 4.0.0 -- An enhanced Interactive Python.
...
In [1]: 
```

Is there a better way to do this?

**Comment by minrk** [comment]
Unless you are specifically embedding IPython into a calling namespace (e.g. like a debugger breakpoint), then `embed` is not what you want. Django made this mistake, and was fixed to [launch IPython in the normal way](https://github.com/django/django/blob/1.8.5/django/core/management/commands/shell.py#L32) (`IPython.start_ipython()`).

**Comment by mathieulongtin** [comment]
It turns out `import IPython; IPython.start_ipython(user_ns=...)` works as expected, however it loads startup files, which is not necessarily what I wanted.

**Comment by mathieulongtin** [comment]
Deep diving in the code yields this:
```
embed(module=sys.modules['__main__'], user_ns=sys.modules['__main__'].__dict__)
```
That way, globals and locals are the same object, like in the normal shell.

**Comment by mathieulongtin** [comment]
Ok, `start_ipython(argv=[])` is more elegant.
