### ISSUE TITLE
Crash When Closing the Plot Window

### ISSUE THREAD

**Issue by suokunlong** [ipython/ipython#8921]
ipython crashes when I do the following steps:

Startup:
```
$ ipython --pylab

Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:15:05) [MSC v.1600 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
Using matplotlib backend: TkAgg
```

The Code:
```
import pandas as pd

fixed_df = pd.read_csv("https://github.com/jvns/pandas-cookbook/raw/master/data/bikes.csv", sep=';', encoding='latin1', parse_dates=['Date'], dayfirst=True, index_col='Date')

fixed_df['Berri 1'].plot()
fixed_df.plot(figsize=(15, 10))
```

Then you get two figures. Close the "Figure 1" window, then close "Figure 2" window. At this moment python will crash.

When you close "Figure 2" first, then close "Figure 1", there is no crash.

Win10 X86.

**Comment by minrk** [comment]
cc @tacaswell since this seems matplotlib related. Any known issues with the Tk backend on Windows? Since it's brand new Win10, it could be the Tk library itself, I suppose.

**Comment by tacaswell** [comment]
I do not recall any known tk issues off the top of my head.  The dependency on the order the windows are closed is really weird.

@cgohlke is the windows expert mpl relies on.

@suokunlong is there any error message with the crash?  Can you reproduce this without pandas or in the vanilla python repl?

**Comment by cgohlke** [comment]
I recognize this issue. The crash is in Python's tcl86t.dll. It seems to be specific to Python 3.4 and can be reproduced without IPython and Pandas. See http://stackoverflow.com/questions/30729180

**Comment by cgohlke** [comment]
Looks like a bug in the TCL/TK binaries included with Python 3.4. I recompiled tcl/tk/tix for Python 3.4 using the updated versions used in Python 3.5 and the crashes disappear.

**Comment by suokunlong** [comment]
@tacaswell : The error message is like:
alloc: invalid block: 0733A8E0: 38 4

It's exactly the same issue as discussed in http://stackoverflow.com/questions/30729180
Only python3.4+matplotlib is enough to reproduce the crash.

**Comment by minrk** [comment]
@cgohlke thanks for finding it!

**Comment by tacaswell** [comment]
Has this been reported upstream to cpython?
