### ISSUE TITLE
when requesting user input, the cell cursor does not advance forward to the next cell

### ISSUE THREAD

**Issue by denfromufa** [ipython/ipython#8922]
if I have a cell like this:

```
ui_mode=raw_input("Are user inputs interactive? ([Y]/N): ") or 'Y'
```

once I press `Shift+Enter` and `Enter` for user input, then it does not switch to the next cell like it would normally do with other cells

**Comment by Carreau** [comment]
I think this is a notebook issue. Isn't it ?

**Comment by denfromufa** [comment]
This is actually fixed in latest

**Comment by Carreau** [comment]
Cool ! Thanks !
