### ISSUE TITLE
multiline string with escaped newlines

### ISSUE THREAD

**Issue by Gh0str1d3r** [ipython/ipython#8924]
I'm facing a strange behavior in IPython and wonder if this is a bug or if I am doing something wrong. Basically, when I paste this code

```
print('''\
a \
a
a
a
a
a
a
a \
a
''')
```

to my IPython input prompt, it shows this `...:` to ask for more input. The only way to get back to a new input prompt is to press ctrl+c. However, the command is processed as expected by a regular python prompt. Also, when I remove the last `\`, even IPython will eat it:

```
print('''\
a \
a
a
a
a
a
a
a
a
''')
```

Is this a normal behavior?

See also http://stackoverflow.com/questions/33309634/ipython-multiline-string-with-escaped-newlines

**Comment by takluyver** [comment]
This was a bug; it was re-reported as #9841, and fixed by #10157.
