### ISSUE TITLE
Make it easier to set `suppress_errors=False` in IPython.core.Application

### ISSUE THREAD

**Issue by ssanderson** [ipython/ipython#8927]
IPython.core.application swallows exceptions raised during execution of config files unless `suppress_errors` is set to `False`.  When deploying an IPython server, I don't want config errors to be masked, so I'd like to set `suppress_errors=False`, but there's no sane way to set this as far as I can tell.

**Comment by takluyver** [comment]
@minrk maybe an environment variable? Bits affecting how the config loading itself happens probably need some special casing.

**Comment by minrk** [comment]
Yeah, it should be possible to disable it. An environment variable is the easiest way to ensure that it takes effect before any config is loaded.
