### ISSUE TITLE
Can't install ipython notebook for python3.

### ISSUE THREAD

**Issue by piltu007** [ipython/ipython#8936]
I have installed python3 using miniconda by creating an environment. I have installed ipython notebook for python 2 but can't do the same for python 3. Every time I tried to do, the error message is: 
```
>conda install notebook
>Hint: the following packages conflict with each other:
  - notebook
  - python 3.5*

>Use 'conda info notebook' etc. to see the dependencies for each package.

>Note that the following features are enabled:
  - vc14
```
All the dependencies are installed. Please tell me how to install it. Thanks.

**Comment by minrk** [comment]
What OS? I can `conda install python=3.5 notebook` here.

**Comment by piltu007** [comment]
Windows 10. Not working. Same problem as above.

**Comment by minrk** [comment]
Then presumably Continuum has not updated some dependency for Python 3.5 on Windows. There's nothing we can do here about when they issue updates. You can continue to use Python 3.4 until they finish updating packages, or try installing the notebook with `pip`.

**Comment by piltu007** [comment]
still not working.

**Comment by minrk** [comment]
As mentioned above - there is nothing for us to do. Conda hasn't updated their packages for Windows. Hopefully they will soon.
