### ISSUE TITLE
Debugging of arbitrary Python code within IPython notebook

### ISSUE THREAD

**Issue by netheril96** [ipython/ipython#8937]
I want to debug certain object methods in IPython. All the codes are within the notebook, so I don't what filename and line number to use when calling the `%debug` magic. I searched the Internet and the only way found is to modify the code to insert some debugger commands at the breakpoint I want. But I don't want to do that because those new definitions won't carry over to my already instantiated objects. Are there any better ways?

**Comment by takluyver** [comment]
You can `%debug f()` and then use debugger commands like `next`, `step` and `jump` to go through the code. This isn't a great way, but it's a way.
