### ISSUE TITLE
Change kernel args after frontend launch

### ISSUE THREAD

**Issue by minrk** [ipython/ipython#894]
Now that we have the notebook starting kernels, and the qtconsole able to start more than one, it makes sense to be able to change the config of the kernels we start from the frontend.

My most common use case: I startup the notebook server, play around, then get to a notebook where I really wanted to be using pylab mode.  

It should at least be possible to specify whether you want to start a kernel with/without pylab, so the whole notebook server doesn't have to be restarted in order to enable/disable pylab.

**Comment by Carreau** [comment]
Closing, this should be in another repo, and we can now change parameters with kernelspecs.
