### ISSUE TITLE
IPython / Jupyter no longer prints multiple lines of output

### ISSUE THREAD

**Issue by dcarrera** [ipython/ipython#8940]
I just upgraded my lectures from IPython notebooks to Jupyter. I am using the IOctave backend. I have some code cells that have several instructions and I have been relying on them to display the output of every line that has output. For example, I have a code cell like this:

```
%%octave

u = [1 2 3 4 5]
u + [1 1 1 1 1]
u*2
sqrt(u)
```

In the old IPython, this used to print four lines of output. Now it only prints the last line of output. I have looked all over the documentation and I cannot find any way to restore the original functionality. I don't know what happened, but this is going to make notebooks a lot more cumbersome to use in my class until it gets fixed. :-(  Is there an easy option to restore the original functionality?

**Comment by stevengj** [comment]
Probably an IOctave issue.

**Comment by takluyver** [comment]
Ping @blink1073 for IOctave. Closing here, as it's not likely to be an IPython bug.

**Comment by blink1073** [comment]
This is working fine with the latest versions of IPython and oct2py:

```python
In [3]: import oct2py

In [4]: %load_ext oct2py.ipython

In [5]: %paste
%%octave

u = [1 2 3 4 5]
u + [1 1 1 1 1]
u*2
sqrt(u)

## -- End pasted text --
u =

   1   2   3   4   5

ans =

   2   3   4   5   6

ans =

    2    4    6    8   10

ans =

   1.0000   1.4142   1.7321   2.0000   2.2361

In [3]: IPython.__version__
Out[3]: '4.0.1'

In [4]: oct2py.__version__
Out[4]: '3.5.0'
```
