### ISSUE TITLE
IPython 4.0 history search not working

### ISSUE THREAD

**Issue by aklaver** [ipython/ipython#8942]
Python 2.7.10 (default, May 24 2015, 14:46:10) [GCC]
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.

In previous versions of the console IPython I could start typing a fragment, say import, hit the up arrow key and it would take to the last line that started with that fragment. Now it just takes me to the last history line. The previous behavior still works in the qtconsole version.

**Comment by minrk** [comment]
Do you have an inputrc file? Readline config can change this behavior from IPython's defaults.

**Comment by aklaver** [comment]
Should have added in the first post this is on Linux, openSUSE 13.2 to be exact.

I have ~/.inputrc., which is commented out. There is also an /etc/inputrc. It has this:
$if mode=vi
set editing-mode vi
set keymap vi
$endif

I have read that set editing-mode vi sometimes can cause issues, but opening a console and running bind -V shows, among other things, this:

editing-mode is set to `emacs`
keymap is set to `emacs'

so the vi editing mode is not set.

Some playing around found that Ctr + Up arrow works as does Page Up for searching backwards through history.  I tried attaching the inputrc, but I do not the necessary permissions.

**Comment by takluyver** [comment]
@aklaver do you still see this issue? History search is still working for me.

**Comment by aklaver** [comment]
Yes. I just upgraded to IPython 4.0.3 to test on Python 2.7.10. Using the up arrow key by itself does not work, using  Ctrl + up arrow or using Page Up does work. Same behavior using  IPython 4.0.3 on Python 3.4.1.

**Comment by takluyver** [comment]
Could `readline_parse_and_bind` be set anywhere in your config? Could up and down be generating different key sequences from the ones that we set by default (`\e[A` and `\e[B`)? If you put these lines in `~/.inputrc`, does bash behave correctly?

```
"\e[A": history-search-backward
"\e[B": history-search-forward
```

**Comment by aklaver** [comment]
Answer to first question is I have:
profile_default/ipython_config.py:# c.TerminalInteractiveShell.readline_parse_and_bind = ['tab: complete', '"\\C-l": clear-screen', 'set show-all-if-ambiguous on', '"\\C-o": tab-insert', '"\\C-r": reverse-search-history', '"\\C-s": forward-search-history', '"\\C-p": history-search-backward', '"\\C-n": history-search-forward', '"\\e[A": history-search-backward', '"\\e[B": history-search-forward', '"\\C-k": kill-line', '"\\C-u": unix-line-discard']

The readline_parse_and_bind content is repeated and commented out for the other shells as well.

Answer to second question:

Yes, entering the lines in ~/.inputrc makes the history recall behave as before, thanks.

**Comment by takluyver** [comment]
OK, the commented out value it generates is just the default. I don't know why it's not working for you without putting the lines in `~/.inputrc`, but if that works...

Closing for now as I don't know how it can be an IPython bug, and we're moving away from readline for 5.x anyway (#9118).
