### ISSUE TITLE
pprint methods for collections use hard-wired class names

### ISSUE THREAD

**Issue by rmalouf** [ipython/ipython#8944]
The pprint methods for collections classes (`_defaultdict_pprint`, _`ordereddict_pprint`, `_deque_pprint`, and `_counter_pprint`) have explicit class names in the function.  This gives inconsistent results when using subclasses of these classes.  For example `nltk.FreqDist` is a subclass of `collections.Counter`:

```python
In [60]: pprint()
Pretty printing has been turned ON

In [61]: x = nltk.FreqDist(['a','b','a'])

In [62]: x
Out[62]: Counter({'a': 2, 'b': 1})

In [63]: pprint()
Pretty printing has been turned OFF

In [64]: x
Out[64]: FreqDist({'a': 2, 'b': 1})
```

I can't say I fully understand how the pretty printing dispatch works, but I think the fix is to replace this:

```python
def _counter_pprint(obj, p, cycle):
    name = 'Counter'
    with p.group(len(name) + 1, name + '(', ')'):
        if cycle:
            p.text('...')
        elif len(obj):
            p.pretty(dict(obj))
```
with something like:
```python
def _counter_pprint(obj, p, cycle):
    name = obj.__class__.__name__
    with p.group(len(name) + 1, name + '(', ')'):
        if cycle:
            p.text('...')
        elif len(obj):
            p.pretty(dict(obj))
```

**Comment by minrk** [comment]
@rmalouf thanks, fixed by #8945
