### ISSUE TITLE
"Downloads" page is out of date

### ISSUE THREAD

**Issue by abdarraafi** [ipython/ipython#8946]
Your download page is horribly out of date (literally three years as of yesterday): https://github.com/ipython/ipython/downloads

How can I help fix this?

**Comment by Achifaifa** [comment]
I thought all the releasing/downloading stuff was done through [this page](https://github.com/ipython/ipython/releases), you may want to check it out. I didn't even knew that downloads page existed, not sure if it can be PR'd, so I'd ping @minrk .

**Comment by minrk** [comment]
The downloads page hasn't been updated since GitHub downloads was deprecated in 2012, as it says at the bottom of that page. We post releases to PyPI.

**Comment by abdarraafi** [comment]
@minrk in that case, can we get rid of the page? Why leave it up?

**Comment by minrk** [comment]
I don't think there is an option to delete the page. All GitHub repos have it. I suppose we could delete the old files from it, though.
