### ISSUE TITLE
ENH: "store all" option for storemagic

### ISSUE THREAD

**Issue by toddrme2178** [ipython/ipython#8948]
The `storemagic` extension can store user-specified variables.  However, it would be nice if `storemagic` had an option (such as `%store --all`) that store all user-defined variables, or at least all those that are pickleable and not imported from other modules.

**Comment by takluyver** [comment]
[dill](https://pypi.python.org/pypi/dill) has functions for `dump_session()` and `load_session()`, which may interest you.

**Comment by Phyks** [comment]
This is something that could be really useful, to be able to dump / restore a session upon shutdown / startup of the server, and not having to reexecute all the cells. Having it built-in in the kernel could also allow jupyter notebook to automatically dump / restore on shutdown / startup, I think. I will have a look at dill though, which seems really cool to handle this.

**Comment by takluyver** [comment]
It can't work for absolutely everything - you might have handles on external files or network sockets, which can't practically be preserved. This is partly why we haven't tried to push such functionality into core IPython. But do play around with Dill and see how you get on.

**Comment by Phyks** [comment]
I totally get it won't work for everything, such as external files or network sockets. I was thinking about "picklable" variables as of writing my comment, especially as I am doing a lot of scientific computation and was interesting in storing intermediate computation results directly along the notebook rather than having to rerun the full notebook every time.

**Comment by takluyver** [comment]
If there's one step in particular that takes a long time, have a look at [ipycache](https://github.com/rossant/ipycache).

**Comment by Phyks** [comment]
Seems to be a good solution for this problem too. Will have a deeper look at it. Thanks!

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one as a duplicate of #112 and #1035. As @takluyver mentioned, anyone who seeks this functionality should look at [dill](https://pypi.python.org/pypi/dill), which has functions for `dump_session()` and `load_session()`.

Happy hacking! :bowtie:

**Comment by takluyver** [comment]
@ivanov Thank-you for your tireless effort going back to old issues, connecting them up to outcomes and bringing a bit of order back to the issue tracker. I'll stay silent on 99% of them, but I do appreciate it.

:cookie:
