### ISSUE TITLE
IPython kernel installation: consider defaulting --display-name to --name

### ISSUE THREAD

**Issue by cel4** [ipython/ipython#8956]
At the moment `ipython kernel install --name <name>` defaults the `display-name` in the web UI to python2/3 which I find rather unintuitive.

It would probably be reasonable to assume that `name` and `display-name` coincide, unless the user explicitly sets the `--display-name` argument.

**Comment by minrk** [comment]
Migrated to jupyter/jupyter_client#91

**Comment by minrk** [comment]
Migrated to ipython/ipykernel#75
