### ISSUE TITLE
ipcluster launcher for AWS/OpenStack

### ISSUE THREAD

**Issue by jreadey** [ipython/ipython#8957]
Curious if anyone has looked into writing a launcher plugin that would spin up new VMs using the AWS EC2 api (or Nova for OpenStack)?

Idea is that your could easily spin up a new cluster, do some work with the engines, and shut it down.

**Comment by minrk** [comment]
Not that I'm aware of. Should be pretty doable, though. ipyparallel can use launchers from external packages, via their import name:

```python
c.IPClusterEngines.engine_launcher_class = 'mymodule.EC2EngineSetLauncher'
```

**Comment by jreadey** [comment]
@minrk- thanks, I'll try it out and let you know how it goes.
