### ISSUE TITLE
Doc bug? How to check contents of outputs in tests?

### ISSUE THREAD

**Issue by davclark** [ipython/ipython#8964]
For rpy2, it'd be nice to have tests that check for the contents of output cells. Is there a way to do this?

There's too much dynamic code execution around the various run_... functions for me to figure out how to trace through. IPython help (`ip.run_cell_magic?`) raises a AttributeError! I can't find anything in the docs on testing modules that use IPython either.

**Comment by davclark** [comment]
Relevant issue on the rpy2 issue tracker:

https://bitbucket.org/rpy2/rpy2/issues/205/capture-visibility-problems-in-a-unit-test

cc @lgautier

**Comment by minrk** [comment]
We use a `capture_output` context manager in our tests. It separately captures stdout, stderr, and mime-type display outputs:

```python

from IPython.core.interactiveshell import InteractiveShell
from IPython.utils.capture import capture_output

ip = InteractiveShell.instance()

ip.run_cell("""
import sys
from IPython.display import display, HTML
""")
with capture_output() as out:
    ip.run_cell("""
print("hello")
display(HTML("<b>bold</b>"))
print("ERRORED", file=sys.stderr)
""")

assert out.stdout == 'hello\n'
assert out.stderr == 'ERRORED\n'
assert out.outputs[0].data['text/html'] == "<b>bold</b>"
```

**Comment by Carreau** [comment]
Hi, 

This issue has been quiet for almost two years, and I don't think there is anything we can do. It has been marked as no-action, and I'm going to close it to attempt to reduce the number of opened issue. Feel free to reopen if needed. 

Thanks.
