### ISSUE TITLE
cannot start ipython notebook from root c:\ drive - Refusing to serve hidden directory, via 404 Error

### ISSUE THREAD

**Issue by denfromufa** [ipython/ipython#8970]
http://localhost:8888/tree shows 

```
404 : Not Found
You are requesting a page that does not exist!
```

console shows:

```
C:\>ipython notebook
[I 14:28:29.232 NotebookApp] Serving notebooks from local directory: C:\
[I 14:28:29.233 NotebookApp] 0 active kernels
[I 14:28:29.234 NotebookApp] The IPython Notebook is running at: http://localhos
t:8888/
[I 14:28:29.234 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
[I 14:28:29.492 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 14:28:29.515 NotebookApp] 404 GET /tree (::1) 24.00ms referer=None
```

**Comment by Carreau** [comment]
On windows, the is_hidden has extra-check that refuse to serve some kinds of files for other reasons, like drive junction, and so on and so forth. 

Would by any change your C drive have such things, or actually have the hidden flag set ?

**Comment by denfromufa** [comment]
i did not find anything hidden and I did not setup any junctions, looks like the problem is common:

https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/6qSyM2Ixho0

**Comment by Carreau** [comment]
Migrated to jupyter/notebook#984
