### ISSUE TITLE
Block commenting with CMD+/ fails to respect code indent level

### ISSUE THREAD

**Issue by p-i-** [ipython/ipython#8974]
Suppose I have this dummy code:

```
for s in ['foo', 'bar']:
    print(s)
    print(len(s))
    pass
````

... and I wish to comment out both print statements. So I select both lines, and do CMD+/.
```
for s in ['foo', 'bar']:
#     print(s)
#     print(len(s))
    pass
````
This is clearly incorrect. Nobody writes code looking like this. So to fix, the developer has to SHIFT+TAB until the code block is no longer indented, CMD+/ to comment, TAB until the original indent level is restored. Which is *really* clumsy!

It should be respecting the code indentation level:
```
for s in ['foo', 'bar']:
    # print(s)
    # print(len(s))
    pass
````

**Comment by Carreau** [comment]
That's likely a [codemirror](http://codemirror.net/) issue with the commenting addon.
In the meantime you should be able to use multicursor and explicitely insert `#`

**Comment by takluyver** [comment]
Closing as not an IPython issue. It might be a jupyter/notebook issue, but as @Carreau says, it's most likely in CodeMirror.
