### ISSUE TITLE
! after line continuation causes SyntaxError

### ISSUE THREAD

**Issue by kapare** [ipython/ipython#8987]
Hi! I was playing with IPython and something stop working as expected... It took me a bit of testing to found out why and I'm wondering if this is an expected behaviour or not? 
Here the src that cause the problem: https://gist.github.com/kapare/6969b2a58b7855a0b2f3
[1] The line that make SyntaxError: is 98 but it display line 92. 
[2] Splitting the string at 94 cause the SyntaxError? Is it expected?

**Comment by minrk** [comment]
From gitter, a smaller example that reproduces the issue:

```python
str("bla \
bla.")
!pwd
```

**Comment by takluyver** [comment]
The smaller example does not reproduce it for me in master, even when saved to a `.ipy` file. I think it has to be an explicit line continuation within a multiline Python expression, and not on the first line. This reproduces it:

```
str(
"bla \
bla.")
!pwd
```

**Comment by MrMino** [comment]
Neither of the two examples produce `SyntaxError` anymore.
