### ISSUE TITLE
A problem regarding IPython of "ImportError" in scipy

### ISSUE THREAD

**Issue by senkrain** [ipython/ipython#8989]
My Python and IPython are 2.7.10 and 4.0.0 respectfully.
When I run scipy.sparse.linalg on IPython:
![86794d6a-8aea-11e5-89dd-0d83c00525ac](https://cloud.githubusercontent.com/assets/15844146/11162913/70edda34-8af3-11e5-8a14-a89e69b455a2.png)
But actually 'linalg' exists!

When I run the same code on Python idle, it works well:
<img width="455" alt="b72909a0-8aea-11e5-9b1f-c57408f703de" src="https://cloud.githubusercontent.com/assets/15844146/11162915/83cb479a-8af3-11e5-9339-462f937e419d.png">

My spyder information is as follows:
<img width="517" alt="d5b4e2a4-8aea-11e5-9d38-9dc41b39f5db" src="https://cloud.githubusercontent.com/assets/15844146/11162917/97f015b6-8af3-11e5-9f43-1a99719b8233.png">

**Comment by minrk** [comment]
Are `sys.executable` and `sys.path` the same in both cases?

**Comment by Carreau** [comment]
Hi, 

This issue has been quiet for almost two years, and I don't think there is anything we can do. It has been marked as no-action, and I'm going to close it to attempt to reduce the number of opened issue. Feel free to reopen if needed. 

Thanks.
