### ISSUE TITLE
%qtconsole magic broken?

### ISSUE THREAD

**Issue by apodemus** [ipython/ipython#8992]
Running `%qtconsole` from a notebook
Issues the following warning, and does not launch a qtconsole:

`/usr/local/lib/python3.4/site-packages/IPython/parallel.py:13: ShimWarning: The `IPython.parallel` package has been deprecated. You should import from ipyparallel instead.
  "You should import from ipyparallel instead.", ShimWarning)`

Any ideas on how to fix this?

**Comment by minrk** [comment]
Can you share `pip list` or `conda list`?

**Comment by apodemus** [comment]
alabaster (0.7.4)
APLpy (1.0)
astropy (1.1.dev13977)
Babel (1.3)
backports-abc (0.4)
certifi (14.5.14)
cycler (0.9.0)
Cython (0.23.2)
d2to1 (0.2.11)
decorator (4.0.4)
docutils (0.12)
ipykernel (4.1.1)
ipython (4.0.0)
ipython-genutils (0.1.0)
ipywidgets (4.1.1)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.1.1)
jupyter-console (4.0.3)
jupyter-core (4.0.6)
line-profiler (1.0b3)
MarkupSafe (0.23)
matplotlib (1.5.0)
mistune (0.7.1)
mpld3 (0.3git)
nbconvert (4.1.0)
nbformat (4.0.1)
networkx (1.9.1)
nose (1.3.6)
notebook (4.0.6)
numpy (1.10.1)
pandas (0.16.1)
path.py (8.1.2)
pexpect (4.0.1)
photutils (0.2.dev1366)
pickleshare (0.5)
Pillow (2.8.1)
pip (7.1.2)
profilehooks (1.8.1.dev0)
ptyprocess (0.5)
PyAstronomy (0.8.1)
pyfits (3.3)
Pygments (2.0.2)
pyparsing (2.0.5)
pyraf (2.2.dev0)
PySPICE (2.0)
python-dateutil (2.4.2)
pytz (2015.7)
pyzmq (15.0.0)
qtconsole (4.1.0)
readline (6.2.4.1)
scikit-image (0.11.3)
scikit-learn (0.16.1)
scipy (0.15.1)
setuptools (15.2)
simplegeneric (0.8.1)
six (1.10.0)
snowballstemmer (1.2.0)
Sphinx (1.3.1)
sphinx-rtd-theme (0.1.8)
spyder (3.0.0.dev0)
stevedore (0.14.1)
stsci.distutils (0.3.7)
stsci.tools (3.2.2)
sympy (0.7.6.1)
terminado (0.5)
Theano (0.6.0)
tornado (4.3)
traitlets (4.0.0)
uncertainties (2.4.6.1)
virtualenv-clone (0.2.4)
yt (3.2.1)

**Comment by apodemus** [comment]
Turns out this was a total non-issue.  I had a script file named `qtconsole.py` lurking in my home directory that caused the trouble.  Removed the file and the %qtconsole magic now works again!
