### ISSUE TITLE
unable to set the profile when running ipython notebook

### ISSUE THREAD

**Issue by thomasdziedzic** [ipython/ipython#8994]
I created a profile called pyspark using ```ipython profile create pyspark```.

According to ```ipython help notebook``` there is an example of how to use a profile ```ipython notebook --profile=sympy       # use the sympy profile```.

When I try to run ```ipython notebook --profile=pyspark``` I get the following error:

```
[W 18:23:44.765 NotebookApp] Unrecognized alias: '--profile=pyspark', it will probably have no effect.
[W 18:23:44.794 NotebookApp] ipywidgets package not installed.  Widgets are unavailable.
[I 18:23:44.803 NotebookApp] The port 8888 is already in use, trying another random port.
[I 18:23:44.806 NotebookApp] Serving notebooks from local directory: /mnt/notebook
[I 18:23:44.806 NotebookApp] 0 active kernels
[I 18:23:44.806 NotebookApp] The IPython Notebook is running at: http://localhost:8889/
[I 18:23:44.807 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

Using the following versions:

```
$ ipython --version
4.0.0
```

```
$ jupyter --version
4.0.6
```

**Comment by Carreau** [comment]
jupyter/notebook does not have notion of profile. 

`ipython help notebook` had still references to profile, this was an oversight of the `notebook` package that should have been fixed some time ago. The various `ipykernels` you have can have different profiles if you like, but the notebook itself does now know what a profile is. 

I would suggest installing a second kernel with a different name:
```
$ python -m ipykernel install --help
usage: __main__.py [-h] [--user] [--name NAME] [--display-name DISPLAY_NAME]
                   [--prefix PREFIX]

Install the IPython kernel spec.
...
```

And having this kernel use a spark profile.
