### ISSUE TITLE
Nested SVG elements unsupported

### ISSUE THREAD

**Issue by brainstorm** [ipython/ipython#8996]
The plot shows up exactly as advertised in the README.md of the official project **when opened directly via a browser** (as in File->Open File->image.svg):

https://github.com/CSB-IG/pyveplot

But it shows only partially when trying to render it with IPython's Display SVG:

https://gist.github.com/brainstorm/25f69d7a735f6e0127ff

**Comment by brainstorm** [comment]
In other words, here's the output with both `SVG` and `display_html` display modules:

![skarmavbild 2015-11-24 kl 21 54 00](https://cloud.githubusercontent.com/assets/175587/11380394/02cea424-92f6-11e5-94c8-0a93407fca69.png)

And here is the expected result:

![hyplot_intra_inter](https://cloud.githubusercontent.com/assets/175587/11380409/21fe556a-92f6-11e5-8e5d-7c7aab60dca1.png)

Any pointers on how to debug/fix this, are very welcome.

**Comment by brainstorm** [comment]
Same effect with a simple markdown cell:

```
![svg](2156.tsv.svg)
```

On a new fresh tab, opening the file directly via the browser, the image shows without any issue.

**Comment by brainstorm** [comment]
Taking a look at core display SVG:

https://github.com/ipython/ipython/blob/master/IPython/core/display.py#L492

And then at the javascript console, it seems that there's an issue with nested `svg` elements:

![skarmavbild 2015-11-24 kl 22 20 38](https://cloud.githubusercontent.com/assets/175587/11381010/d697bfe0-92f9-11e5-9e49-10c52873274e.png)

Only the first "quadrant" which coincides with the first svg element gets rendered...

**Comment by brainstorm** [comment]
Reported elsewhere since August: http://stackoverflow.com/questions/32246251/ipython-notebook-nested-svg-elements

**Comment by brainstorm** [comment]
Ok, the issue is that the <a href="https://github.com/ipython/ipython/blob/master/IPython/core/display.py#L487">svg display code</a> is wrapping every sub-svg-`path` into a full svg document (compare with javascript console screenshot above):

![skarmavbild 2015-11-24 kl 23 21 35](https://cloud.githubusercontent.com/assets/175587/11382540/bf1341f6-9302-11e5-80d7-fc25e3b48d8c.png)

**Comment by brainstorm** [comment]
Here's a pickled `found_svg` variable from <a href="https://github.com/ipython/ipython/blob/master/IPython/core/display.py#L492">IPython.core.display L#492</a> if anyone wants to get `xml.dom.minidom` to render my nasty svg properly (without having to restart ipython notebook over changes):

https://www.dropbox.com/s/7ohlthza3gw0cyk/multiple_nested_svg.pickle?dl=0

**Comment by takluyver** [comment]
See this issue continued at jupyter/notebook#982.
