### ISSUE TITLE
ipython notebook shift-tab completion function arguments/completion not working 

### ISSUE THREAD

**Issue by datnamer** [ipython/ipython#8999]
Windows 7, python 3.5, Jupyter 4.0 and rackspace hosted Python 3 instance. 

Regular tab works for global scope of exceptions etc, but   I'm not getting function args with shift-tab

**Comment by Carreau** [comment]
Hum, might be an issue for `github.com/jupyter/notebook` repository, but it might also be a IPython one.

Shift-tab will work only if function is imported and in scope (unless you set options like `IPCompleter.greedy`) can you give a more specific example?

**Comment by Carreau** [comment]
Migrated to jupyter/notebook#981
