### ISSUE TITLE
Ipython RuntimeError: PDF creating failed with ! You can't use `macro parameter character #' in horizontal mode.

### ISSUE THREAD

**Issue by ilovetogetspamed** [ipython/ipython#9004]
RuntimeError: PDF creating failed with ! You can't use `macro parameter character #' in horizontal mode.

Source of the error was a RawNBConvert cell.

I had a Python style comment in the RawNBConvert cell of my jupyter notebook which threw the above error when trying to save active notebook as a PDF.. e.g.:

<code>
\# average distance between positions
</code>

if I escape the # character, it works as expected e.g.:

<code>
\\\# average distance between positions
</code>

I'm not sure if this is by design, or a problem with ipython notebook or something else....

[ipython error.txt](https://github.com/ipython/ipython/files/40500/ipython.error.txt)

**Comment by Carreau** [comment]
RawNBConvert cells are passed through unchanged, you have to put valid latex in it if want to convert to latex/PDF.

**Comment by ilovetogetspamed** [comment]
Thanks, I'll keep that in mind going forward.

**Comment by Carreau** [comment]
what you might try to use is triple backtick in markdown cell, or indent 4 spaces in markdown cell too. It will render as monospace font.

**Comment by ilovetogetspamed** [comment]
Thanks for the tip.  I'll try that.
