### ISSUE TITLE
display.Image should allow manual setting of format even when a local file is given

### ISSUE THREAD

**Issue by eteq** [ipython/ipython#9009]
It appears that the `display.Image` class has some non-intuitive (and limiting) behavior for inferring the format of a locally-provided image.  I would have *thought* that supplying the `format` keyword would allow me to override whatever format the IPython machinery decided the local file was in.  This is important for a use case where e.g. temporary files are used, as the file has *no* extension, so you can't guess based on the filename.

However, if I do something like:
```IPython.display.Image(filename='/temp/somerandomfilename', format='jpg')```
to my surprise, it does *not* try to interpret the file as a JPEG, but rather says ``ValueError: Cannot embed the '/temp/somerandomfilename' image format``.

Is there a reason why this is the case, or could this be fixed?

(See also astropy/astropy-tutorials#97 for the context that this was encountered)

**Comment by minrk** [comment]
Supplying format should skip all the detection stuff. Should be fixed by #9022.
