### ISSUE TITLE
NUL (/dev/null) not always enabled on Windows

### ISSUE THREAD

**Issue by codewarrior0** [ipython/ipython#9023]
Python 2.7.9, IPython 4.0.0

I got an error report from a user that indicates a File Not Found when opening the null device:

```
  File "[virtualenv]\lib\site-packages\IPython\__init__.py", line 47, in <module>  
  File "[virtualenv]\lib\site-packages\IPython\core\application.py", line 24, in <module>
  File "[virtualenv]\lib\site-packages\IPython\core\crashhandler.py", line 28, in <module>
  File "[virtualenv]\lib\site-packages\IPython\core\ultratb.py", line 110, in <module>
  File "[virtualenv]\lib\site-packages\IPython\core\debugger.py", line 37, in <module>
  File "[virtualenv]\lib\site-packages\IPython\utils\io.py", line 75, in <module>
IOError: [Errno 2] No such file or directory: 'nul'
```

The faulting line is `devnull = open(os.devnull, 'w') ` where `os.devnull` == `"nul"`

Some googling turns up the fact that `nul`, which is the MS-DOS era null device, is a Windows virtual device that can be disabled via Device Manager.

**Comment by minrk** [comment]
Oh, wow. `os.devnull` isn't trustworthy on Windows? Is there any reason for that to be true? Do you know how/why you disabled the nul device or what should be reliably used instead?

**Comment by codewarrior0** [comment]
Actually, I think you can write this off as a system configuration problem. I read the user's report again and he said the same version of my app worked previously. (I thought it might be related to IPython 4.0.0 which I introduced in my newest release.) 

So something on his system must have changed to mess with the null device.

**Comment by minrk** [comment]
Yeah, IPython has used os.devnull for years. I'm still curious how/why this came up, but glad we don't have to do anything about it.

**Comment by codewarrior0** [comment]
Definitely a system config issue. I'm still not sure why it happened. The user got back to me and said he got it fixed with "some registry fixes". See conversation: https://github.com/Khroki/MCEdit-Unified/issues/534

**Comment by codewarrior0** [comment]
Just want to remark that I got this problem from a user who had just upgraded to Windows 10. It seems like he had some trouble with the upgrade, but I can't really tell because he's Japanese and speaking through a web translator.
