### ISSUE TITLE
Terminal escape codes in output prompt showing up as junk

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#9041]
I don't recall ever seeing this before:

![screenshot from 2015-11-27 11-40-07](https://cloud.githubusercontent.com/assets/327925/11440578/ca29bc00-94fb-11e5-9c18-7e9e4fadf55c.png)

This is with gnome-terminal on a new Fedora installation (on my shiny new laptop). Maybe something has changed in the terminal emulator, but I can't think why it would have done.

**Comment by minrk** [comment]
I thought we fixed this yesterday. What git commit?

**Comment by takluyver** [comment]
Aha, right,  I just pulled it again and it works now. Sorry for the noise!
