### ISSUE TITLE
np-modindex.html not generated by sphinx anymore

### ISSUE THREAD

**Issue by vext01** [ipython/ipython#9043]
Hi,

This is an odd one. It may not even be an IPython bug.

I'm packaging IPython4 and Jupyter for OpenBSD. When I started out an entry for `np-modindex.html` hit the package file list. Then I removed all packages from my system and built ipython on a clean system. Now `np-modindex.html` is not created by sphinx, so building the package fails.

Do you know what determines if that file will be created by sphinx? I wonder if there is a hidden dependency in the IPython build...

I've spent an hour or so trying to figure this out, but I am now stumped...

Cheers

**Comment by Carreau** [comment]
I would say it might a sphinx version problem, the recent version of `np-modindex` seem to be `py-modindex`. The other thing I can see if we upgraded bundled numpydoc to sphinx.ext.napoleon, and np-modindexseem like a custom sphinx domain. But as I dont' find np-modindex, even in our doc archives, I'm not sure what to do. 

Do you have any way to found what was the content of np-modindex to help figure out ?

**Comment by vext01** [comment]
I'm unable to regenerate the `np-modindex.html`, so I can't tell you what's in there. I'm using sphinx-1.2.3.

FWIW: the initial packing list had both a `np-modindex.html` *and* a `py-modindex.html`.

If you think that `np-modindex.html` should not exist, I'm happy to simply exclude this file from the packing list. In the event that the existence of something else causes the file to be created, it simply won't get packaged.

Cheers

**Comment by Carreau** [comment]
So the np-modindex is present in the debian [ipython-doc](https://packages.debian.org/sid/all/ipython-doc) of IPython 2.3.0. 
It is an (almost) exact duplicate of py-modindex, though the header of the sphinx doc has 2 identical link to the 2 pages. So my guess you can likely ignore it. 

If you ever found out why it wasgenerated , feel free to tell us:

```
$ diff -U0 py-modindex.html np-modindex.html
--- py-modindex.html	2014-11-09 23:50:46.000000000 +0100
+++ np-modindex.html	2014-11-09 23:50:46.000000000 +0100
@@ -44 +44 @@
-          <a href="#" title="Python Module Index"
+          <a href="py-modindex.html" title="Python Module Index"
@@ -47 +47 @@
-          <a href="np-modindex.html" title="Python Module Index"
+          <a href="#" title="Python Module Index"
@@ -1798 +1798 @@
-          <a href="#" title="Python Module Index"
+          <a href="py-modindex.html" title="Python Module Index"
@@ -1801 +1801 @@
-          <a href="np-modindex.html" title="Python Module Index"
+          <a href="#" title="Python Module Index"
```

**Comment by vext01** [comment]
OK, many thanks. Let's close this.
