### ISSUE TITLE
cannot find kernel file

### ISSUE THREAD

**Issue by fayeshine** [ipython/ipython#9044]
Use ipython 4.0.0 (python is 2.7.10, integrated in anaconda 2.4) in mac OSX 10.11, when I connect to a existing ipython kernel using a kernel.json file, it shows that it cannot find the kernel file (which can be found in ipython 3.2)

**Comment by takluyver** [comment]
Sorry this has gone unregarded for so long. What are you running to do this? Can you show the exact error message that you're getting?

**Comment by fayeshine** [comment]
I found it can be found in the kernel folder. Thanks

**Comment by takluyver** [comment]
I don't quite understand, but it sounds like you resolved the issue. Thanks!
