### ISSUE TITLE
emacs and ipython on Windows

### ISSUE THREAD

**Issue by luckjiff** [ipython/ipython#9060]
So with IPython Console 3.2.1 I could fire-up python with the following:

(setq
 python-shell-interpreter "C:\\Anaconda2\\python.exe"
 python-shell-interpreter-args "-i C:\\Anaconda2\\Scripts\\ipython-script.py console --pylab")

The --pylab following console is the offending argument.
Is there an equivalent for IPython 4.0

**Comment by takluyver** [comment]
If you just use plain IPython (take the `console` out), `--pylab` should still work.

If you need to use the two-process console, it's a bit harder to get pylab mode. You can still do it by creating a [kernelspec](http://jupyter-client.readthedocs.org/en/latest/kernels.html#kernel-specs) that launches the IPython kernel in pylab mode, and then launching with `<ipython command> console --kernel my_pylab_kernel`.

**Comment by takluyver** [comment]
If you just start ipython normally (if PATH is set up, you can just run `ipython` at a command prompt), and run:

```
%pylab
```

Then:

```
plot([1,2,3])
```

Do you see anything? I.e. is it because it's running in emacs, or is mpl just not showing you the plots by default?

**Comment by luckjiff** [comment]
Thanks again.  So that renders fine.

i am using
http://emacsbinw64.sourceforge.net/
with the standard python mode
http://bzr.savannah.gnu.org/lh/emacs/emacs-24/annotate/head:/lisp/progmodes/python.el

This is described several places including
http://stackoverflow.com/questions/16324497/ipython-in-emacs-no-figure-output

**Comment by takluyver** [comment]
That's odd - it shouldn't be necessary to use `console` to get figures. But I'm not a regular user of either Emacs or Windows, let alone the combination, so I don't really know what to suggest with that.

Have a look at the kernelspec docs I linked above. You can create the default IPython kernelspec using `python -m ipykernel.kernelspec --user`. Then copy it and modify the arguments to use pylab mode.

**Comment by takluyver** [comment]
Closing as there's nothing clear for us to fix here.

**Comment by jinlin82** [comment]
I have exact the same proplem.
ipython 4.2.0+emacs 24.5 on windows 7.

When I use plot function in ipython on emacs, a plot window poped up but freezed.
