### ISSUE TITLE
Regression : %kill_embedded does not work (broken by #6840 )

### ISSUE THREAD

**Issue by ewjoachim** [ipython/ipython#9063]
The Magic [``%kill_embedded``](http://ipython.readthedocs.org/en/stable/api/generated/IPython.terminal.embed.html?highlight=kill_embedded#IPython.terminal.embed.EmbeddedMagics.kill_embedded) flags the embedded shell instance so that it is not started on subsequent calls of ``IPython.embed()``. However, fo this to work, we need to keep the instance in memory otherwise, we'll be flagging new instances all the time and never read the flags we've set.

In [``IPython/terminal/embed.py``](https://github.com/ipython/ipython/blob/master/IPython/terminal/embed.py#L262), we do several things :

* We save the instance that might be the current singleton instance of the ``InteractiveShell`` class
* We remove it from the singleton
* We get ``InteractiveShellEmbed``'s instance (created if existing) and launch the shell
* As soon as it's ended, we delete the instance
* We replace the original shell instance as the singleton instance.

All these things were done by #6840 in an effort to make embed nestable (but then it broke ``%kill_embeded``)

It's clear that the current behaviour makes it completely impossible for ``%kill_embedded`` to work as expected.

What would be preferred for a PR : to store the flag elsewhere or to improve #6840 to not destroy instances ?

**Comment by takluyver** [comment]
I guess it depends whether `%kill_embed` should prevent future embeds at that nesting level, or all future embeds.

Probably the simplest thing would be to store the flag globally and prevent all future embeds in that process.

**Comment by ewjoachim** [comment]
I guess so. In this case, we just need to :
```python
# change 
self.shell.embedded_active = False
# to
self.shell.__cls__.embedded_active = False
```
and that might be enough for a fix. I'll see if I have time to submit a PR, but if you do, please feel free :)

**Comment by Carreau** [comment]
Hum, marking that as 5.0. 

I think it is useful to use multiple `embed()`. One solution would be to add a `name=...` parameter to the constructor and `kill` based on the name. We could also "generate" a name based on `sys._getframe(1).f_code.co_filename+sys._getframe(1).f_lineno`, which would prevent reinvocation on the same line.
