### ISSUE TITLE
Trivial typo in documentation

### ISSUE THREAD

**Issue by zunzun** [ipython/ipython#9066]
The IPython web page

http://ipython.org/notebook.html

contains a trivial typographical error.  The word "toegether" should be spelled "together".

James

**Comment by takluyver** [comment]
Thanks. [Fixed in the source](https://github.com/ipython/ipython-website/commit/a1e08ba89777b19e4455f63a80331084e0c9b827). It well get fixed on the website next time we rebuild it.
