### ISSUE TITLE
Documentation Links Not Working

### ISSUE THREAD

**Issue by abrrba** [ipython/ipython#9072]
The following links referred by the page 

https://github.com/ipython/ipython/wiki/A-gallery-of-interesting-IPython-Notebooks#introductory-tutorials

are not working.

http://nbviewer.ipython.org/github/ipython/ipython/blob/master/examples/Notebook/Running%20Code.ipynb

http://nbviewer.ipython.org/github/ipython/ipython/blob/master/examples/Notebook/Display%20System.ipynb

**Comment by minrk** [comment]
Thanks, fixed.
