### ISSUE TITLE
ipython{,_kernel}_profile.py should always be created with the same order

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#9077]
Currently, ipython{,_kernel}_profile.py from a freshly created profile presents the configurables in a seemingly random order, most due to random dict iteration order (+PYTHONHASHSEED).  This makes diff'ing profiles difficult.
I thus suggest ordering (e.g. by sorting) the entries in the profile file.

**Comment by minrk** [comment]
This has been fixed by ipython/traitlets#62, which will be released as traitlets-4.1 very soon.
