### ISSUE TITLE
Feature request:  Syntax highlighting code displayed with `object??` in qtconsole

### ISSUE THREAD

**Issue by apodemus** [ipython/ipython#9084]

**Comment by Carreau** [comment]
Fixed since last November by https://github.com/ipython/ipython/pull/8947, will be available in next minor revision of IPython.

**Comment by Carreau** [comment]
With Proof: 

<img width="503" alt="screen shot 2015-12-21 at 12 48 20" src="https://cloud.githubusercontent.com/assets/335567/11930130/23d2b778-a7e1-11e5-9cb6-fdd4bb1dca32.png">

**Comment by apodemus** [comment]
super! Thanks @Carreau

**Comment by Carreau** [comment]
I did nothing @gonzolabs did !
