### ISSUE TITLE
Overzealous deprecation

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9085]
I think I was overzealous in #8979 and one of the function (`onlyif_cmds_exist`) is still used, so shouldn't be deprecated, so shouldn't warn.

**Comment by Carreau** [comment]
@parleur that should be easy for you, we can do that tomorrow.

**Comment by jamesfe** [comment]
@Carreau I made a mock pull request (internal to my username here on GH) - but is this what you are looking for? https://github.com/jamesfe/ipython/pull/1

If so, I can make a pull request to this repo.

-jimmy

**Comment by Carreau** [comment]
Hey @jamesfe , yes that seem about right ! Do you want to send a PR to the main repo ? In general feel free to send directly PR to this repo, you can always update the PR later if needed.

Thanks !

**Comment by jamesfe** [comment]
Great, will do!  Thanks, first time contributing and did not want a faux pas.

**Comment by Carreau** [comment]
> Great, will do! Thanks, first time contributing and did not want a faux pas.

You won't faux pas in here. We'll gladly spend an afternoon or more explain to you how to do things instead of doing it ourself quicker. That's what append for my [first PR](https://github.com/ipython/ipython/pull/776), and how I end up staying.

So don't hesitate to ask (even privately by mail if you are afraid of public discussion)

**Comment by jamesfe** [comment]
@Carreau Done.  I appreciate your openness and welcoming attitude...I created a PR here: https://github.com/ipython/ipython/pull/9106
