### ISSUE TITLE
User defined context in print_stack_entry

### ISSUE THREAD

**Issue by JamshedVesuna** [ipython/ipython#9087]
When using `ipdb`'s `set_trace()`, `print_stack_entry` sets the [default context to 3 lines](https://github.com/ipython/ipython/blob/master/IPython/core/debugger.py#L335). While this does preserve space, it can be very helpful to have a user defined context size, rather than continuously hitting `l` (list) to display more lines.

It would be great to add a keyword to `ipdb's`'s `set_trace` (such as `context` or even `c`) that passes a context value to [Pdb](https://github.com/ipython/ipython/blob/master/IPython/core/debugger.py#L201). The change to ipython would be minimal: Adding a `context` keyword to `Pdb` and `print_stack_entry`.

Not sure if there is a cleaner way to integrate this (perhaps into [Tracer's set_trace](https://github.com/ipython/ipython/blob/master/IPython/core/debugger.py#L170)?)

**Comment by Carreau** [comment]
We should likely (also) overwrite `do_where` to take as argument the number of line of context to show.

**Comment by JamshedVesuna** [comment]
@Carreau can you elaborate on overwritting `do_where`?

**Comment by Carreau** [comment]
See #9093 for pull request. 

![do_w](https://cloud.githubusercontent.com/assets/335567/11941616/39cf0252-a831-11e5-9ec4-7487e59da705.gif)

**Comment by JamshedVesuna** [comment]
Cool! Can we integrate `do_where` with `print_stack_entry`? 

See [ipdb#35](https://github.com/gotcha/ipdb/issues/35). It seems like there are two ways of adding user defined context values: By editing `bdb.set_trace()`, or by passing a context keyword to `ipdb.set_trace(context=10)`, and pass that to [IPython's Pdb](https://github.com/ipython/ipython/blob/master/IPython/core/debugger.py#L201) as an instance variable, then use that in `print_stack_entry`.  


Unfortunately, there is no easy way to [amend to your PR](https://help.github.com/articles/checking-out-pull-requests-locally/), so I can include your commits in my PR.

**Comment by Carreau** [comment]
> Unfortunately, there is no easy way to amend to your PR, so I can include your commits in my PR.

Oh, you just have the right to push on my PR, but you can send a PR againt my PR or send a new one. I updated mine to add a `context` kwarg and  instance variable.

**Comment by JamshedVesuna** [comment]
Just created a new PR [#9097](https://github.com/ipython/ipython/pull/9097) that includes your changes + some style fixes to stay consistent with the rest of the package.
