### ISSUE TITLE
update `log.warn` to `log.warning`

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9091]
As said in the documentation : [`warn` is a deprecated alias](https://docs.python.org/3/library/logging.html?highlight=logging#logging.Logger.warning), we should try not to use it. 

Bonus point to add a warning filter in iptest that warn/fail if we use `log.warn`.

**Comment by Carreau** [comment]
> As said in the documentation : warn is a deprecated alias, we should try not to use it.

This is done. Only the bonus remain.

**Comment by jamesfe** [comment]
What's a good way to tackle this?  I'm interested.

**Comment by Carreau** [comment]
> What's a good way to tackle this? I'm interested.

In `ipython/ipython` this is mostly done, there is a testing question, but its likely to be hard.
I would do the same in the notebook repo:  https://github.com/jupyter/notebook/issues/928

Which is basically just go through files, and rename the methods where necessary. 
(which would almost be automatized)

You're not obliged to tackle all occurrences, only one file at a time is enough.

**Comment by srinivasreddy** [comment]
`srinivas@Srini:~/workspace/github/ipython/IPython$ grep -wr . -e log.warn
`

gave me empty results. so we can close this issue.

**Comment by Carreau** [comment]
I think we can. Thanks !
