### ISSUE TITLE
Cannot rename notebook if name change only involves capitalization

### ISSUE THREAD

**Issue by numeratus** [ipython/ipython#9095]
Say, I want to rename "Capitalization.ipynb" as "capitalization.ipynb", I get:

>File already exists: notebooks/capitalization.ipynb

Workaround is to change name in multiple steps. 

Jupyter notebook server is 4.0.6

`Python 2.7.11 (default, Dec  5 2015, 23:52:42) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]`

**Comment by minrk** [comment]
Migrated to jupyter/notebook#911
