### ISSUE TITLE
IPython(3)Lexer fails to tokenize properly on source with magic functions

### ISSUE THREAD

**Issue by captainsafia** [ipython/ipython#9099]
Cross-issue from jupyter/nbconvert#105.

The `IPython3Lexer` and `IPythonLexer` fail to properly tokenize on source with magic functions as seen in the example code below.

```
>>> from IPython.lib import lexers
>>> lexer = lexers.IPython3Lexer()                                                                                                                                                               
>>> fragment = "%%time\nfor i in range(5):\nprint(n)"
>>> other_fragment = "for i in range(5):\nprint(n)"
>>> list(lexer.get_tokens(fragment))
[(Token.Operator, '%%'), (Token.Keyword, 'time'), (Token.Text, '\nfor i in range(5):\nprint(n)\n')]
>>> list(lexer.get_tokens(other_fragment))                                                                                                                                                       
[(Token.Keyword, 'for'), (Token.Text, ' '), (Token.Name, 'i'), (Token.Text, ' '), (Token.Operator.Word, 'in'), (Token.Text, ' '), (Token.Name.Builtin, 'range'), (Token.Punctuation, '('), (Token.Literal.Number.Integer, '5'), (Token.Punctuation, ')'), (Token.Punctuation, ':'), (Token.Text, '\n'), (Token.Name.Builtin, 'print'), (Token.Punctuation, '('), (Token.Name, 'n'), (Token.Punctuation, ')'), (Token.Text, '\n')]
```

The expected behavior is that the remaining part of the source (`for i in range(5): print(n)`) would be tokenized properly so that pygments can syntax highlight appropriately in `nbconvert`. Looking at the test suite, it appears there isn't actually a test case in `test_lexer.py` to test for this specific situation.

I can take a stab at this.

cc: @minrk

**Comment by pythonian4000** [comment]
The problem is in [`IPython/lib/lexers.py`](/ipython/ipython/blob/master/IPython/lib/lexers.py#L54):

```python
ipython_tokens = [
  (r"(?s)(\s*)(%%)(\w+)(.*)", bygroups(Text, Operator, Keyword, Text)),
  (r'(?s)(^\s*)(%%!)([^\n]*\n)(.*)', bygroups(Text, Operator, Text, using(BashLexer))),
...
]
```

If a cell begins in `%%`, the entire cell is treated as text. Bash has been special-cased in one form ([which isn't documented](http://ipython.readthedocs.org/en/stable/interactive/magics.html#cellmagic-bash)); [all other cell magics](http://ipython.readthedocs.org/en/stable/interactive/magics.html#cell-magics) will cause the cells to not be rendered.

A simple fix would be to add tokens above these for each of the built-in cell magics, handling the cell content as appropriate (along the lines of using `BashLexer` above).

A more intelligent fix would be to have each cell magic handler provide its own token, and have `lexers.py` collate and insert them before `ipython_tokens`. This would have the benefit of enabling custom cell magics to define how they get highlighted.

**Comment by captainsafia** [comment]
@pythonian4000 Want to submit a PR?

**Comment by pythonian4000** [comment]
I probably will, but only after I've submitted my PhD thesis :stuck_out_tongue_winking_eye: (I encountered the bug while in the midst of final formatting).

**Comment by marius311** [comment]
A friendly ping to *Dr.* @pythonian4000 :) or @captainsafia  if they wanted to revisit submitting a fix this? As mentioned in the linked Issue from nbsphinx, this also affects notebooks that get rendered to Sphinx, put on readthedocs, etc...

**Comment by mgeier** [comment]
Ping?

**Comment by jeertmans** [comment]
Hello! Sorry to reopen this issue, but I think #11137 may not have fully solved it.

Referring to my https://github.com/spatialaudio/nbsphinx/issues/59#issuecomment-1668146974, I have a similar issue on custom magics, see:

> (Within the notebook viewer)
> 
> ![image](https://user-images.githubusercontent.com/27275099/259025940-7f7d748e-944c-49cf-9ad5-b929c01b4570.png)
> 
> (When exported as HTML)
> 
> ![image](https://user-images.githubusercontent.com/27275099/259025733-a06c7781-2568-4a86-9c5e-eb6112067c1b.png)

**Comment by Carreau** [comment]
We can't deal with custom magics as we don't know their language.

Here the html of nbconvert is "correct" in the sens that it encounters an magic and stop highlighting as "magics" contents are invalid Python. Lab is incorrect, it just happen to still try to  highlight as Python after encountering a syntax error.

There is currently no way as far as I remember to tell the lexer "those magics are actually Python, please keep lexing". I'd be opened to get a PR or an issue describing the need.

**Comment by jeertmans** [comment]
I totally get that it’s impossible to cover all possible custom magics, but I would have imaginer that the lexer would by default assume Python syntax, since it is a Python kernel.

**Comment by Carreau** [comment]
>  I would have imaginer that the lexer would by default assume Python syntax, since it is a Python kernel.

Confirmation bias ?

Most default cell magics are actually invalid Python syntax, so a better assumption would be that magics are not Python by default ? I count 18 non-python cell magics:

> %%!  %%HTML  %%SVG  %%bash  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%ruby  %%script  %%sh  %%svg  %%sx  %%system   %%writefile

and 9 "python" ones:

> %%capture %%debug %%prun %%pypy  %%time  %%timeit [%%python  %%python2  %%python3]

I'm not going to list non-cell magics as the skew would be even worse.  I'll also put the 3 "python" one in square brackets as they happen to by Python as well, but fall into the category of "embedding" another language.
