### ISSUE TITLE
Put %edit contents directly in history

### ISSUE THREAD

**Issue by ipython** [ipython/ipython#91]
Original Launchpad bug 276883: https://bugs.launchpad.net/ipython/+bug/276883
Reported by: fdo.perez (Fernando Perez).

A request by Jose Unpingco:

"""
This is what we discussed at the scipy conference, where doing something like

In: %edit 10

Puts the results of the edit into the history instead of just the %edit 10 command.
"""

**Comment by Carreau** [comment]
This is 1/2 a decade old, and our history system is quite stable, I'm going to close this as there are few chance of anyone working on it. 

Closing, please reopen an new issue if needed. 

Thanks.
