### ISSUE TITLE
Cannot inspect callable that raise in __bool__

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9101]
The following should not raise.
```python
class NoBoolCall:
    
    def __call__(self):
        pass
    def __bool__(self):
        raise NotImplementedError('Must be implemented')
        
b = NoBoolCall()
b?
```

Likely in `oinspect.py`:

```
835:       if callable_obj:
```

Should be `if callable_obj is not None`, though i'm not sure.

**Comment by minrk** [comment]
`is not None` seems like the right change. How did you encounter this?

**Comment by Carreau** [comment]
> How did you encounter this

Nothing you should [ever use in production](https://github.com/Carreau/undefined/blob/master/undefined/__init__.py#L11-L40), replacing a `sys.modules[somethings]` with a custom class with weird behavior.
