### ISSUE TITLE
remove `call_tip` in oinspect.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9102]
Is unused in IPython codebase, and in ipykernel too. 

it also seem like the `if callable_obj` ~ line 835 in oinspect does not have many effect if removed , as the `IPython.utils.signature` utils use for the `definition` of the callable above, is already capable of extracting the callable information. 

We might be able to simplify this logic.

Marking as 5.0 as API breaking, might want a deprecation warning before if we decide it's worth removing.

**Comment by minrk** [comment]
Yup, I think oinspect could stand a refactoring. There's also been discussion of making oinspect itself a standalone package, so it could be used outside IPython.

**Comment by srinivasreddy** [comment]
Raised a PR for this - https://github.com/ipython/ipython/issues/9102

**Comment by jzf2101** [comment]
@Carreau are we ready to close this?

**Comment by jzf2101** [comment]
@minrk ?

**Comment by minrk** [comment]
Yes, thanks!
