### ISSUE TITLE
How to run_cell in InteractiveShell without adding to namespace?

### ISSUE THREAD

**Issue by ooblahman** [ipython/ipython#9105]
I'm trying to use ```run_cell``` from an instantiated ```InteractiveShell``` to run some user code in a given namespace, but I want each call to ```run_cell``` to add nothing to the namespace. That is, the following code would NameError:
```
>>> shell = InteractiveShell({'a': 1, 'b': 2})
>>> shell.run_cell('c=a+b')
>>> shell.run_cell('c+a+b')
```
How would I go about doing this?

**Comment by minrk** [comment]
Probably a post-execute hook to reinitialize the namespace every time:


```python
from IPython.core.interactiveshell import InteractiveShell

user_ns = {'a': 1, 'b': 2}
shell = InteractiveShell.instance()

def reinitialize_user_ns():
    shell.user_ns = user_ns.copy()

shell.events.register('post_run_cell', reinitialize_user_ns)
# run once, to get started
reinitialize_user_ns()

shell.run_cell('c=a+b')
print(shell.user_ns)

shell.run_cell('c+a+b') # NameError
print(shell.user_ns)
```

**Comment by takluyver** [comment]
Why exactly do you want to do that? We should mention that there is a lot of other state beyond the user namespace that the code could change, so just resetting the namespace is not sufficient to isolate the execution of each cell.

Closing for now as there's nothing clear for us to fix; feel free to keep using the comments to discuss it.
