### ISSUE TITLE
"!dir" doesn't work as expected on Python 3.4 / Windows 7 / Ipython .4.0.6 (and Qt Console)

### ISSUE THREAD

**Issue by stonebig** [ipython/ipython#9107]
with Python 3.4.4:
````
import os; import platform; import sys; import locale
print (os.name, platform.system(), platform.release())
print (sys.getdefaultencoding(), sys.getfilesystemencoding())
print( locale.getpreferredencoding(), sys.stdin.encoding, sys.stdout.encoding)

a=!dir
a=a[:10]
c=[b.encode('cp1252').decode('cp850') for b in a]
print ('\n'.join(a))
print ('\n\n**** NEXT TEST ***\n\n', '\n'.join(c))
````
![dos_is_a_pain](https://cloud.githubusercontent.com/assets/4312421/12075492/0b8c4232-b183-11e5-8144-82b78ab23ea3.GIF)

**Comment by Carreau** [comment]
`!dir` is not IPython specific, only `!` is, it's likely we can't fix the dir problem without breaking something else.

**Comment by stonebig** [comment]
couldn't an intermediate `cchardet` or `chardet` layer, for windows legacy platform, optionaly sweat the situation a bit for windows user ?

**Comment by Carreau** [comment]
I think we should just ignore support request from these pesky French users :-P, non mais dis donc. 

I'm sure @takluyver will respond "Mais oui !".

**Comment by stonebig** [comment]
I guess your not japanese.

**Comment by stonebig** [comment]
For the R.I.P. note, the problem seems also there if I launched the jupyter-notebook from powershell.

Is there a way to launch a powershell (and get the answer) with the "!" (or other character) ?

![powershell_launch](https://cloud.githubusercontent.com/assets/4312421/12080240/e012cc52-b254-11e5-8ae7-673d8a1934fc.GIF)

**Comment by stonebig** [comment]
I see an old post there http://stackoverflow.com/questions/19644926/configure-ipython-to-use-powershell-instead-of-cmd

**Comment by stonebig** [comment]
fail... 
![powershell_launch2](https://cloud.githubusercontent.com/assets/4312421/12080307/024c4530-b257-11e5-8f4f-5296847d71ae.GIF)

**Comment by stonebig** [comment]
````
....Looking through the IPython code, I see that it's using os.system() to send the command to the shell, rather than subprocess.call(). That makes things somewhat more complicated, since os.system* just uses COMSPEC, where with subprocess*, you can specify the executable to use.....
````

**Comment by minrk** [comment]
We don't use `os.system` in the kernel, do we? That would not capture any output.

**Comment by takluyver** [comment]
No, in the kernel, it does actually use `subprocess.Popen()`. Start at `InteractiveShell.system_piped` and follow the layers down. But it sounds like `COMSPEC` is the way to configure the shell either way.

It looks like cmd.exe is encoding as cp850, and we're decoding as cp1252. But if `locale.getpreferredencoding()` and `sys.stdin.encoding` are both telling us cp1252, I don't see any way that we can infer that we should use cp850 in that situation. I don't want to introduce encoding guessers here - it's extra complexity and I don't think it would work all that reliably.

If you're really trying to get a list of files, `os.listdir()` will be a much more reliable way to do that than `!dir`.

**Comment by Carreau** [comment]
> I guess your not japanese.

The comment about pesky French user was just because the screenshot was obviously from a french system and that I am one of these French users. I hope no offence was taken.

**Comment by stonebig** [comment]
pas de problème. Would cygwin solve all this issues with windows ? what would I lost as compatibility in the process ?

**Comment by takluyver** [comment]
I expect it would solve some problems and make some others. We don't
generally recommend using cygwin, because it's kind of neither properly one
thing nor the other - it's not quite Unix, but it's not quite windows
either.

**Comment by minrk** [comment]
In my experience, cygwin introduces more problems than it solves.

Can you find any API call that we can make, to which the answer is `cp850`, corresponding to the cmd output? It might be a Python bug that its locale detection doesn't make the right Windows API calls, or there might be something we can do to ask more directly (or tell the program to use a specific encoding unambiguously).

**Comment by stonebig** [comment]
@takluyver I understand your point, we are dealing with legacy DOS here.

@minrk  I see only this:
![dos_is_a_pain_in_the](https://cloud.githubusercontent.com/assets/4312421/12123396/011dbc8a-b3e1-11e5-8b26-21d05a143b30.GIF)

**Comment by stonebig** [comment]
http://ss64.com/nt/chcp.html is most informative.

I'm surprised that my Powershell experiment failed

**Comment by takluyver** [comment]
Closing as it looks like there's nothing we can do about this. We can reopen if someone finds something.
