### ISSUE TITLE
printing of List

### ISSUE THREAD

**Issue by Anil-Verma** [ipython/ipython#9108]
Hey Guys,
There seems to be an issues when we try to make a list and print it in a print statement. it works fine i.e. it prints all the elements in the same line with square brackets []. But when we try to print the list by the name it is printing every single element in different lines. IT causes a problem of readability.

**Comment by minrk** [comment]
When the display-hook is called `IPython.lib.pretty` is used to format the list. It splits 'long' lists across multiple lines. This is deliberate, and generally considered an improvement over `print` for longer lists. Can you provide an example where it doesn't do a good job?

**Comment by takluyver** [comment]
See #8741
