### ISSUE TITLE
ipython tab completion always display all possibilities

### ISSUE THREAD

**Issue by youyou015** [ipython/ipython#9114]
In IPython interactive shell, when press 'TAB', will show some possibilities according your input, if possibilities are too much, will give question like this:

    In [1]: from <tab>
    Display all 497 possibilities? (y or n)

then you can press 'y' or 'n' to determine whether display them.

My problom is that when I use IPython, the question will be shown but **I never has chance to press any key, it will always show all the possibilities blow**.

I have tried IPython 2.4.1 and IPython 4.0.1 in different environment (linux & windows), always has this issue, this is very Annoying when use IPython.

Is this a bug of IPython or any other reasons?

**Comment by takluyver** [comment]
It's readline that displays that message, so I wouldn't think it's a bug in IPython, but it's really weird if you see the same issue on Linux and Windows, because on Windows IPython uses a completely separate readline package written in Python (pyreadline), whereas on Linux it uses GNU readline.

**Comment by youyou015** [comment]
I use cygwin on windows, so seems same as Linux.
But I have just try on my home windows PC, a
![Uploading 2016-01-06 Windows_system32_cmd.exe - ipython.png…]()
fter install python 2.7.11, and use pip install IPython and pyreadline. press tab then no ‘Display all ....’ question show and it just display all possibilities.
![Uploading 2016-01-06 Windows_system32_cmd.exe - ipython.png…]()

**Comment by takluyver** [comment]
Ah, OK. Then it seems likely that your issue is with readline. Do you have any configuration in `.inputrc`?

**Comment by youyou015** [comment]
What's that? I haven't find this file in my Windows user folder or Linux home dir.

**Comment by takluyver** [comment]
It's a configuration file for readline, but it's only there if you create it. If it's not that, I don't know what's going on; I haven't come across that symptom before, and I can't think how to debug it.

**Comment by dsblank** [comment]
I see this same behavior (Linux, with ipython and ipython console). It just
doesn't pause to answer y/n and shows all results.

**Comment by takluyver** [comment]
...actually, I see it too. I just rarely scroll back far enough to see the `Display all N possibilities?` prompt after I've seen a large number of completions, so I hadn't noticed it before.

Still not sure how to debug it. I tried disabling most of the readline options we configure (search for `readline_parse_and_bind` to find them), but it still did the same.

**Comment by Carreau** [comment]
Tagging as 5.0, as it is not critical, but I would be happy if a fix get into 4.1

**Comment by Carreau** [comment]
I would consider that fix on master now that prompt toolkit is used.

**Comment by Carreau** [comment]
I'm closing as fixed now that we have PTK in master.
