### ISSUE TITLE
mock.call inspection consumes all memory

### ISSUE THREAD

**Issue by bartekbrak** [ipython/ipython#9122]
to reproduce:
```
from mock import call
call?
```
Reproduced on python 2.7.10, mock==1.0.1, IPython==4.0.1 and python 3.5, unittest.mock==1.0 so versions shouldn't matter.

The code above will consume all memory.

`call` is actually `call = _Call(from_kall=False)`, `from_kall=True` does not cause the problem, that should be a hint.

While this might be a problem with mock being too magic, this certainly shouldn't lead to a hanged system. I don't use swap, if that matters.

**Comment by takluyver** [comment]
I think mock is being a bit too clever for itself, but IPython definitely shouldn't do that, whatever happens. #9123 should catch it.
