### ISSUE TITLE
IPCompleter  breaks readline completer?

### ISSUE THREAD

**Issue by woosley** [ipython/ipython#9125]
https://gist.github.com/woosley/a41ca2b9f1fa2974c666

```
$python t.py
Prompt ("stop" to quit): <tab><tab><tab>
```
if I disable https://gist.github.com/woosley/a41ca2b9f1fa2974c666#file-gistfile1-py-L5, then I can get tab completion work. 
```
$python t.py
Prompt ("stop" to quit):
list   print  start  stop
```

```
$uname -a
Darwin maddog 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64
$pip list |grep ipython
ipython (4.0.1)
```

**Comment by takluyver** [comment]
Do you have the package `gnureadline` installed? If so, IPython's completion machinery tries to load that in preference to `readline` (which can be dodgy on OS X), which could cause bizarre interference.

**Comment by woosley** [comment]
looks like it is the root cause, other than removing gunreadline, is there any other workarounds?

**Comment by takluyver** [comment]
If your script did `import gnureadline as readline`, I think it would work.
