### ISSUE TITLE
ipython crash on exit when loading modules on startup using 'import x as y'

### ISSUE THREAD

**Issue by sbird** [ipython/ipython#9127]
Description:
ipython (the python3 version of ipython) crashes on exit for me if I loaded a module on startup with
"import x as y" rather than "import x".

For me "$HOME/.ipython/profile_default/startup/00-load-modules.py" 
is a file which loads useful modules.

I noticed that if this file has, eg,:
import math
import numpy

everything is fine. 

However, if I have:

"import math as maths"
or "import numpy as np"
it usually crashes on exit.

The exact error is:

"Fatal Python error: PyImport_GetModuleDict: no module dictionary!

Current thread 0x00007f2842a31700 (most recent call first):
  File "/usr/lib/python3.5/site-packages/traitlets/traitlets.py", line 1076 in on_trait_change
  File "/usr/lib/python3.5/site-packages/IPython/core/extensions.py", line 64 in __del__
zsh: abort (core dumped)  ipython"

To reproduce I start ipython and immediately exit:
> ipython
> exit
(crash)

Additional info:
ipython 4.0.1
Python 3.5.1
Archlinux.

**Comment by sbird** [comment]
On further investigation, it sometimes crashes on exit with "import math" etc as well (but not always and more rarely). importing numpy crashes more commonly than not. It seems possible that the time to perform an import is important somehow.

**Comment by takluyver** [comment]
I don't understand why that would happen, but PR #9040 claims to have fixed something that sounds similar to that. Can you try with IPython from master?

**Comment by sbird** [comment]
It's fixed with master. Thanks!

**Comment by takluyver** [comment]
Great
