### ISSUE TITLE
%timeit -q -o crashes

### ISSUE THREAD

**Issue by charignon** [ipython/ipython#9129]
That's the stracktrace that I have when running: %timeit -q -o !ls

UnboundLocalError                         Traceback (most recent call last)
<ipython-input-1-fec457b70b81> in <module>()
----> 1 get_ipython().magic(u'timeit -q -o !ls')

/Library/Python/2.7/site-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
   2334         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2335         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2336         return self.run_line_magic(magic_name, magic_arg_s)
   2337 
   2338     #-------------------------------------------------------------------------

/Library/Python/2.7/site-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2255                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2256             with self.builtin_trap:
-> 2257                 result = fn(*args,**kwargs)
   2258             return result
   2259 

<decorator-gen-59> in timeit(self, line, cell)

/Library/Python/2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, *a, **k: f(*a, **k)
    194 
    195         if callable(arg):

/Library/Python/2.7/site-packages/IPython/core/magics/execution.pyc in timeit(self, line, cell)
   1060                 print("Compiler time: %.2f s" % tc)
   1061         if return_result:
-> 1062             return TimeitResult(number, repeat, best, worst, all_runs, tc, precision)
   1063 
   1064     @skip_doctest

UnboundLocalError: local variable 'worst' referenced before assignment

**Comment by takluyver** [comment]
Thanks, it looks like that's already been fixed in master by #8852. We just need to get round to doing a 4.1 release.
