### ISSUE TITLE
Python newcomer trying (and failing) to use ipython on pypy3

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ipython/ipython#9134]
So, I'm trying to run `ipython` under PyPy:

```
> ipython
Traceback (most recent call last):
  File "/usr/local/share/pypy3/ipython", line 7, in <module>
    from IPython import start_ipython
  File "/usr/local/Cellar/pypy3/2.4.0/libexec/site-packages/IPython/__init__.py", line 34, in <module>
    raise ImportError('IPython requires Python version 2.7 or 3.3 or above.')
ImportError: IPython requires Python version 2.7 or 3.3 or above.
```

Am I making a foolish newbie error, or is this something that's no longer supported? (The [FAQ mentions this](http://ipython.org/faq.html#can-ipython-run-under-ironpython-pypy-jython-other-python-interpreters), but it sounds very out of date …)

Should be easily reproducible, I don't have a particularly special setup:

```
brew install pypy3
pip_pypy3 install ipython
PATH="/usr/local/share/pypy3:$PATH" ipython
```

> OS X **10.11.2** ‘El Capitan’, Python **3.2.5** via PyPy **2.4.0**, `pip` **7.1.2**, `ipython` **4.0.2** …

**Comment by takluyver** [comment]
Pypy3 implements the Python language at version 3.2, which is pretty old. IPython requires Python 3.3 or above (or 2.7). We rely on the `u''` string prefix which was reintroduced in Python 3.3, so we're unlikely to return to supporting 3.2.
