### ISSUE TITLE
Is there a reason to use"no actions" instead of closing ? 

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9136]
We have [a few issues](https://github.com/ipython/ipython/milestones/no%20action) tagged as `no-action` Is it worth keeping them open ? Isn't that confusing for people that come around and see the issue as "open".

**Comment by takluyver** [comment]
I tend to do that when I think an issue should probably be closed, but I want to give other people a chance to weigh in before we do so. I know issues can be reopened, but sometimes it feels rude to close an issue straight away.

**Comment by Carreau** [comment]
> I tend to do that when I think an issue should probably be closed, but I want to give other people a chance to weigh in before we do so

Ok, faire enough. I just think that some issues clutter the list of issues we work on.
I'll close more often after you when you mark as "no actions".

**Comment by minrk** [comment]
Yeah, I do the same - it's more a signal that there's nothing for us to do, but maybe the conversation is still going on and I don't want closing the issue to seem like I'm shutting it down.
