### ISSUE TITLE
%timeit x in {float("inf"), float("-inf")} fails

### ISSUE THREAD

**Issue by lebigot** [ipython/ipython#9137]
With ``x = 3``, ``%timeit x in {float("inf"), float("-inf")}`` fails even though the Python code is correct:
```
NameError: global name 'inf' is not defined
```

The similar ``%timeit x == float("inf")`` does work.

**Comment by takluyver** [comment]
That's because line magics, for better or for worse, all have `{}` style formatting of Python expressions into the command. So the inside of the set literal will be evaluated, and then repr-ed as a tuple, and %timeit will be trying to test a command like:

```python
x in (inf, -inf)
```

You can escape the braces by doubling them:

```
%timeit x in {{float("inf"), float("-inf")}}
```

**Comment by lebigot** [comment]
Thanks. This makes sense, but I must say that even after many years with IPython I did not know this side of the magic. :) In fact, even if I look for it in the documentation (both in Introducing IPython/Magic Functions and in the Built-in Magic Commands parts), I can't find this piece of information. It would be nice to put this simple fact in a prominent place in the documentation. :)

**Comment by takluyver** [comment]
Yeah, IPython has quite a few more features than I think anyone uses. It probably should be documented somewhere, but there aren't enough prominent places to describe every quirk in a prominent place. ;-)

We've talked before about backing off from this feature, and making it something only some magics do, but it's never been quite enough of an annoyance to get worked on.
