### ISSUE TITLE
[serious] LTS 4.x and drop 2.7 on 5.x ?

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9145]
Well all is in the title.

I'm not sure IPython 4.x is missing a lot of features, we have some annoying bugs that have languished for years, and we more and more tend to [commit code that uses python 3 only features and fails on travis](https://github.com/ipython/ipython/pull/9144#issuecomment-172985454) 

So real question, is it time to start thinking about dropping 2.7 ? 

Obviously there are several level of "dropping support". I'll on purpose do not list change that will On purpose break things on Python 2.7:
   - Drop 2.7 from supported python, at least officially, by which I mean, we remove mention of 2.7 compatibility, but still have unit-test... etc 
   - allow-failure on 2.7, not actively working on fixing 2.7 bugs accept PRs.
   - not release 2.x wheels.
   - marking 5.0 as `requires-python >=3.3` (still leave ability to install from source manually).

I know that people are still attached to 2.7 so I propose to make 4.x "LTS", in the sens of still accepting PRs that fixes things and release at least regularly.

**Comment by takluyver** [comment]
Nah, not for IPython. 5.x is too soon, and I don't want to be stuck supporting the readline stuff that we'll hopefully be dropping from the codebase in 5 or 6.

I think we should consider dropping Python 2 support in the notebook server for maybe version 5 or 6 of that - it would remain possible to run Python 2 notebooks, but you'd have to have Python 3 for the server itself. Once we've done that, we can start to think about dropping Python 2 further down the stack.

**Comment by ivanov** [comment]
Hey gang - doing the standard issues cleanup - closing this one since we've dropped support for 2.7 in master.

:cake: and happy hacking! :bowtie:
