### ISSUE TITLE
nbconvert to pdf processing markdown italics as underline

### ISSUE THREAD

**Issue by mkgilbert** [ipython/ipython#9148]
When I try to convert a simple notebook with a markdown cell with something like: **some text**, it renders immediately in the browser as italics as it should. However, when I create a pdf of this notebook, the resulting output is not italic, but instead is underlined. Does anyone have an idea as to why this might be?

I'm using IPython 4.0.0 and nbconvert 4.1.0

**Comment by Carreau** [comment]
@minrk can you migrate that to nbconvert ?
I would also appreciate a link (potentially in devops repo) on how to use the issue migration script.

**Comment by minrk** [comment]
Migrated to jupyter/nbconvert#200

**Comment by minrk** [comment]
The migrate-issues script [is here](https://github.com/minrk/migrate-issues#usage)
