### ISSUE TITLE
nbconvert -- TypeError: environment can only contain strings

### ISSUE THREAD

**Issue by vancan1ty** [ipython/ipython#9151]
On my system with python 2.7.11, when I attempt to export a document from pynb to pdf, the process fails with the below stack trace, with the error "TypeError: environment can only contain strings".  I fixed the problem on my computer by making the following change to C:/Anaconda/lib/site-packages/nbconvert/exporters/pdf.py:
change line
        env['TEXINPUTS'] = os.pathsep.join([self.texinputs, env.get('TEXINPUTS','')])

to
        env['TEXINPUTS'] = os.pathsep.join([self.texinputs, env.get('TEXINPUTS','')]).encode('ascii','ignore')

Basically it seems that windows doesn't support unicode in env, so you must ensure that the data getting put into env is formatted in ASCII.

## Below is system information about the error and my computer.
"""
$ ipython nbconvert --to pdf geometric_distr_experiment.ipynb
[NbConvertApp] Converting notebook geometric_distr_experiment.ipynb to pdf
[NbConvertApp] Support files will be in geometric_distr_experiment_files\
[NbConvertApp] Making directory geometric_distr_experiment_files
[NbConvertApp] Writing 17154 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running pdflatex 3 times: ['pdflatex', 'notebook.tex']
Traceback (most recent call last):
  File "c:\Anaconda\Scripts\ipython-script.py", line 5, in <module>
    sys.exit(start_ipython())
  File "c:\Anaconda\lib\site-packages\IPython\__init__.py", line 119, in start_i
python
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\Anaconda\lib\site-packages\traitlets\config\application.py", line 589
, in launch_instance
    app.start()
  File "c:\Anaconda\lib\site-packages\IPython\terminal\ipapp.py", line 349, in s
tart
    return self.subapp.start()
  File "c:\Anaconda\lib\site-packages\nbconvert\nbconvertapp.py", line 289, in s
tart
    self.convert_notebooks()
  File "c:\Anaconda\lib\site-packages\nbconvert\nbconvertapp.py", line 412, in c
onvert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "c:\Anaconda\lib\site-packages\nbconvert\nbconvertapp.py", line 383, in c
onvert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources
)
  File "c:\Anaconda\lib\site-packages\nbconvert\nbconvertapp.py", line 335, in e
xport_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources
=resources)
  File "c:\Anaconda\lib\site-packages\nbconvert\exporters\exporter.py", line 165
, in from_filename
    return self.from_notebook_node(nbformat.read(f, as_version=4), resources=res
ources, **kw)
  File "c:\Anaconda\lib\site-packages\nbconvert\exporters\pdf.py", line 144, in
from_notebook_node
    rc = self.run_latex(tex_file)
  File "c:\Anaconda\lib\site-packages\nbconvert\exporters\pdf.py", line 107, in
run_latex
    self.latex_count, log_error)
  File "c:\Anaconda\lib\site-packages\nbconvert\exporters\pdf.py", line 87, in r
un_command
    p = subprocess.Popen(command, stdout=stdout, stdin=null, shell=shell, env=en
v)
  File "c:\Anaconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "c:\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
TypeError: environment can only contain strings

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
"""
## Below is various system information:
$ python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': u'8ff8693',
 'commit_source': 'installation',
 'default_encoding': 'cp437',
 'ipython_path': 'c:\\Anaconda\\lib\\site-packages\\IPython',
 'ipython_version': '4.0.3',
 'os_name': 'nt',
 'platform': 'Windows-7-6.1.7601-SP1',
 'sys_executable': 'c:\\Anaconda\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '2.7.11 |Anaconda 2.3.0 (64-bit)| (default, Jan 19 2016, 12:08:3
1) [MSC v.1500 64 bit (AMD64)]'}

Running Anaconda python distribution.
$ conda list
# packages in environment at c:\Anaconda:
#
_license                  1.1                      py27_1    defaults
alabaster                 0.7.6                    py27_0    defaults
anaconda                  2.3.0                np19py27_0    <unknown>
anaconda-client           1.2.1                    py27_0    defaults
argcomplete               1.0.0                    py27_1    defaults
astropy                   1.0.5                np19py27_1    defaults
babel                     2.1.1                    py27_0    defaults
backports-abc             0.4                       <pip>
backports.ssl-match-hostname 3.4.0.2                   <pip>
backports_abc             0.4                      py27_0    defaults
bcolz                     0.11.3                   py27_0    defaults
beautiful-soup            4.3.2                    py27_1    <unknown>
beautifulsoup4            4.3.2                     <pip>
binstar                   0.12                          2    defaults
bitarray                  0.8.1                    py27_1    <unknown>
blaze                     0.9.0                     <pip>
blaze-core                0.9.0                    py27_0    defaults
blz                       0.6.2                np19py27_1    <unknown>
bokeh                     0.11.0                   py27_1    defaults
boto                      2.38.0                   py27_0    <unknown>
bottleneck                1.0.0                np19py27_0    <unknown>
bzip2                     1.0.6                     vc9_2  [vc9]  defaults
cdecimal                  2.3                      py27_1    <unknown>
certifi                   2015.9.6.2               py27_0    defaults
cffi                      1.2.1                    py27_0    defaults
clyent                    1.2.0                    py27_0    defaults
colorama                  0.3.3                    py27_0    <unknown>
comtypes                  1.1.2                    py27_0    defaults
conda                     3.19.0                   py27_0    defaults
conda-build               1.18.1                   py27_0    defaults
conda-env                 2.4.5                    py27_0    defaults
configobj                 5.0.6                    py27_0    <unknown>
cryptography              1.0.2                    py27_0    defaults
cython                    0.23.4                   py27_0    defaults
cytoolz                   0.7.4                    py27_0    defaults
datashape                 0.5.0                    py27_0    defaults
decorator                 4.0.6                    py27_0    defaults
docutils                  0.12                     py27_1    <unknown>
dynd-python               0.6.5                np19py27_0    <unknown>
enum34                    1.1.2                    py27_0    defaults
et-xmlfile                1.0.1                     <pip>
et_xmlfile                1.0.1                    py27_0    defaults
fastcache                 1.0.2                    py27_0    <unknown>
flask                     0.10.1                   py27_1    <unknown>
freetype                  2.5.5                     vc9_0  [vc9]  defaults
funcsigs                  0.4                      py27_0    <unknown>
futures                   3.0.3                    py27_0    defaults
gevent                    1.0.1                    py27_0    <unknown>
gevent-websocket          0.9.3                    py27_0    <unknown>
greenlet                  0.4.9                    py27_0    defaults
grin                      1.2.1                    py27_2    <unknown>
h5py                      2.5.0                np19py27_2    defaults
hdf5                      1.8.15.1                  vc9_4  [vc9]  defaults
idna                      2.0                      py27_0    <unknown>
ipaddress                 1.0.14                   py27_0    defaults
ipykernel                 4.2.2                    py27_0    defaults
ipython                   4.0.3                    py27_0    defaults
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py27_3    defaults
ipython-qtconsole         4.0.1                    py27_4    defaults
ipython_genutils          0.1.0                    py27_0    defaults
ipywidgets                4.1.1                     <pip>
itsdangerous              0.24                     py27_0    <unknown>
jdcal                     1.2                      py27_0    defaults
jedi                      0.9.0                    py27_0    defaults
jinja2                    2.8                      py27_0    defaults
jpeg                      8d                        vc9_0  [vc9]  defaults
jsonschema                2.4.0                    py27_0    <unknown>
jupyter                   1.0.0                     <pip>
jupyter-client            4.1.1                     <pip>
jupyter-console           4.1.0                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py27_0    defaults
jupyter_core              4.0.6                    py27_0    defaults
launcher                  1.0.0                         4    defaults
libpng                    1.6.17                    vc9_1  [vc9]  defaults
libtiff                   4.0.6                     vc9_1  [vc9]  defaults
llvmlite                  0.8.0                    py27_0    defaults
lxml                      3.5.0                    py27_0    defaults
markupsafe                0.23                     py27_0    <unknown>
matplotlib                1.4.3                np19py27_3    defaults
menuinst                  1.3.2                    py27_0    defaults
mistune                   0.7.1                    py27_0    defaults
mne                       0.9.0                     <pip>
mock                      1.3.0                    py27_0    defaults
msvc_runtime              1.0.1                     vc9_0  [vc9]  defaults
multipledispatch          0.4.8                    py27_0    defaults
nbconvert                 4.1.0                    py27_0    defaults
nbformat                  4.0.1                    py27_0    defaults
networkx                  1.10                     py27_0    defaults
nltk                      3.1                      py27_0    defaults
node-webkit               0.10.1                        0    <unknown>
nose                      1.3.7                    py27_0    <unknown>
notebook                  4.1.0                    py27_0    defaults
numba                     0.23.0               np19py27_0    defaults
numexpr                   2.4.4                np19py27_0    defaults
numpy                     1.9.3                    py27_0    defaults
odo                       0.4.0                    py27_0    defaults
openpyxl                  2.3.2                    py27_0    defaults
openssl                   1.0.2e                    vc9_1  [vc9]  defaults
pandas                    0.17.0               np19py27_0    defaults
patch                     2.5.9                         1    defaults
path.py                   8.1.2                    py27_1    defaults
patsy                     0.4.0                np19py27_0    defaults
pbr                       1.3.0                    py27_0    defaults
pep8                      1.7.0                    py27_0    defaults
pickleshare               0.5                      py27_0    defaults
pillow                    3.1.0                    py27_0    defaults
pip                       7.1.2                    py27_0    defaults
ply                       3.8                      py27_0    defaults
psutil                    3.4.1                    py27_0    defaults
py                        1.4.31                   py27_0    defaults
pyasn1                    0.1.9                    py27_0    defaults
pycosat                   0.6.1                    py27_0    <unknown>
pycparser                 2.14                     py27_0    <unknown>
pycrypto                  2.6.1                    py27_3    <unknown>
pyflakes                  1.0.0                    py27_0    defaults
pygame                    1.9.2a0                  py27_0    https://conda.b
ar.org/krisvanneste/win-64/pygame-1.9.2a0-py27_0.tar.bz2
pygments                  2.0.2                    py27_0    <unknown>
pyopengl                  3.1.1a1              np19py27_0    defaults
pyopenssl                 0.15.1                   py27_1    <unknown>
pyparsing                 2.0.3                    py27_0    <unknown>
pyqt                      4.11.4                   py27_4    defaults
pyreadline                2.1                      py27_0    defaults
pytables                  3.2.2                np19py27_0    defaults
pytest                    2.8.5                    py27_0    defaults
python                    2.7.11                        1    defaults
python-dateutil           2.4.2                    py27_0    <unknown>
pytz                      2015.7                   py27_0    defaults
pywin32                   219                      py27_2    defaults
pyyaml                    3.11                     py27_2    defaults
pyzmq                     15.2.0                   py27_0    defaults
qt                        4.8.7                     vc9_5  [vc9]  defaults
qtconsole                 4.1.1                    py27_0    defaults
requests                  2.9.1                    py27_0    defaults
rope                      0.9.4                    py27_1    <unknown>
runipy                    0.1.3                    py27_0    <unknown>
scikit-image              0.11.3               np19py27_0    <unknown>
scikit-learn              0.16.1               np19py27_0    <unknown>
scipy                     0.16.0               np19py27_0    defaults
setuptools                19.2                     py27_0    defaults
simplegeneric             0.8.1                    py27_0    defaults
singledispatch            3.4.0.3                  py27_0    defaults
sip                       4.16.9                   py27_2    defaults
six                       1.10.0                   py27_0    defaults
snowballstemmer           1.2.0                    py27_0    <unknown>
sockjs-tornado            1.0.1                    py27_0    <unknown>
sphinx                    1.3.1                    py27_0    <unknown>
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py27_0    <unknown>
spyder                    2.3.8                    py27_0    defaults
spyder-app                2.3.8                    py27_0    defaults
sqlalchemy                1.0.11                   py27_0    defaults
ssl_match_hostname        3.4.0.2                  py27_0    <unknown>
statsmodels               0.6.1                np19py27_0    <unknown>
sympy                     0.7.6.1                  py27_0    defaults
tables                    3.2.2                     <pip>
tk                        8.5.18                    vc9_0  [vc9]  defaults
toolz                     0.7.4                    py27_0    defaults
tornado                   4.3                      py27_0    defaults
traitlets                 4.1.0                    py27_0    defaults
ujson                     1.33                     py27_0    <unknown>
unicodecsv                0.14.1                   py27_0    defaults
vispy                     0.4.0.106.gf8a69d0      np19py27_0    defaults
wavelets                  0.1                       <pip>
werkzeug                  0.11.3                   py27_0    defaults
wheel                     0.26.0                   py27_1    defaults
xlrd                      0.9.4                    py27_0    defaults
xlsxwriter                0.8.2                    py27_0    defaults
xlwings                   0.6.4                    py27_0    defaults
xlwt                      1.0.0                    py27_0    <unknown>
zlib                      1.2.8                     vc9_2  [vc9]  defaults

**Comment by minrk** [comment]
This has been fixed by https://github.com/jupyter/nbconvert/pull/165
