### ISSUE TITLE
nbconvert failed: PDF creating failed

### ISSUE THREAD

**Issue by kingkastle** [ipython/ipython#9152]
Hi team, 

My pdf conversion via LaTex fails with the consequent error: 

Any hint?

Thanks!

[W 13:49:47.346 NotebookApp] Notebook student_intervention_v2.ipynb is not trusted
[I 13:49:47.681 NotebookApp] Support files will be in 
[I 13:49:47.681 NotebookApp] Writing 80628 bytes to notebook.tex
[I 13:49:47.713 NotebookApp] Building PDF
[I 13:49:47.713 NotebookApp] Running pdflatex 3 times: [u'pdflatex', u'notebook.tex']
[C 13:49:47.854 NotebookApp] pdflatex failed: [u'pdflatex', u'notebook.tex']
    This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian)
     restricted \write18 enabled.
    entering extended mode
    (./notebook.tex
    LaTeX2e <2011/06/27>
    Babel <3.9h> and hyphenation patterns for 2 languages loaded.
    (/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
    Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
    (/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/graphics.cfg)
    (/usr/share/texlive/texmf-dist/tex/latex/pdftex-def/pdftex.def
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))
    (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/adjustbox.sty
    (/usr/share/texlive/texmf-dist/tex/latex/xkeyval/xkeyval.sty
    (/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkeyval.tex))
    (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/adjcalc.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/trimclip.sty
    (/usr/share/texlive/texmf-dist/tex/latex/collectbox/collectbox.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/tc-pdftex.def))
    (/usr/share/texlive/texmf-dist/tex/latex/ifoddpage/ifoddpage.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/varwidth/varwidth.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty
    (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/color.cfg))
    (/usr/share/texlive/texmf-dist/tex/latex/tools/enumerate.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
    (/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
    For additional information on amsmath, use the `?' option.
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty
    (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/eurosym/eurosym.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/ucs/ucs.sty
    (/usr/share/texlive/texmf-dist/tex/latex/ucs/data/uni-global.def))
    (/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty
    (/usr/share/texlive/texmf-dist/tex/latex/ucs/utf8x.def))
    (/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
    Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
    <2008/02/07> (tvz))
    (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grffile.sty
    (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/etexcmds.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)
    (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
    (/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))
    
    Package hyperref Message: Driver (autodetected): hpdftex.
    
    (/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def
    (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)
    No file notebook.aux.
    (/usr/share/texlive/texmf-dist/tex/context/base/supp-pdf.mkii
    [Loading MPS to PDF converter (version 2006.09.02).]
    ) (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
    (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
    *geometry* driver: auto-detecting
    *geometry* detected driver: pdftex
    
    Package geometry Warning: The marginal notes overrun the paper.
         Add 3.73001pt and more to the right margin.
    
    *geometry* verbose mode - [ preamble ] result:
    * driver: pdftex
    * paper: <default>
    * layout: <same size as paper>
    * layoutoffset:(h,v)=(0.0pt,0.0pt)
    * modes: 
    * h-part:(L,W,R)=(72.26999pt, 469.75502pt, 72.26999pt)
    * v-part:(T,H,B)=(72.26999pt, 650.43001pt, 72.26999pt)
    * \paperwidth=614.295pt
    * \paperheight=794.96999pt
    * \textwidth=469.75502pt
    * \textheight=650.43001pt
    * \oddsidemargin=0.0pt
    * \evensidemargin=0.0pt
    * \topmargin=-37.0pt
    * \headheight=12.0pt
    * \headsep=25.0pt
    * \topskip=10.0pt
    * \footskip=30.0pt
    * \marginparwidth=65.0pt
    * \marginparsep=11.0pt
    * \columnsep=10.0pt
    * \skip\footins=9.0pt plus 4.0pt minus 2.0pt
    * \hoffset=0.0pt
    * \voffset=0.0pt
    * \mag=1000
    * \@twocolumnfalse
    * \@twosidefalse
    * \@mparswitchfalse
    * \@reversemarginfalse
    * (1in=72.27pt=25.4mm, 1cm=28.453pt)
    
    (/usr/share/texlive/texmf-dist/tex/latex/ucs/ucsencs.def)
    (/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsa.fd)
    (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsb.fd)
    
    LaTeX Warning: No \author given.
    
    
    Package hyperref Warning: Difference (2) between bookmark levels is greater 
    (hyperref)                than one, level fixed on input line 233.
    
    [1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]
    ! Undefined control sequence.
    <recently read> \textquotesingle 
                                     
    l.315 ...extquotesingle{}passed\textquotesingle{}}
                                                      ) is the
    ? 
    ! Emergency stop.
    <recently read> \textquotesingle 
                                     
    l.315 ...extquotesingle{}passed\textquotesingle{}}
                                                      ) is the
    !  ==> Fatal error occurred, no output PDF file produced!
    Transcript written on notebook.log.
    
[I 13:49:47.855 NotebookApp] Running bibtex 1 time: [u'bibtex', u'notebook']
[W 13:49:47.873 NotebookApp] bibtex had problems, most likely because there were no citations
[I 13:49:47.874 NotebookApp] Running pdflatex 3 times: [u'pdflatex', u'notebook.tex']
[C 13:49:47.995 NotebookApp] pdflatex failed: [u'pdflatex', u'notebook.tex']
    This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian)
     restricted \write18 enabled.
    entering extended mode
    (./notebook.tex
    LaTeX2e <2011/06/27>
    Babel <3.9h> and hyphenation patterns for 2 languages loaded.
    (/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
    Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
    (/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/graphics.cfg)
    (/usr/share/texlive/texmf-dist/tex/latex/pdftex-def/pdftex.def
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))
    (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/adjustbox.sty
    (/usr/share/texlive/texmf-dist/tex/latex/xkeyval/xkeyval.sty
    (/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkeyval.tex))
    (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/adjcalc.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/trimclip.sty
    (/usr/share/texlive/texmf-dist/tex/latex/collectbox/collectbox.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/tc-pdftex.def))
    (/usr/share/texlive/texmf-dist/tex/latex/ifoddpage/ifoddpage.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/varwidth/varwidth.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty
    (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/color.cfg))
    (/usr/share/texlive/texmf-dist/tex/latex/tools/enumerate.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
    (/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
    For additional information on amsmath, use the `?' option.
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty
    (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/eurosym/eurosym.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/ucs/ucs.sty
    (/usr/share/texlive/texmf-dist/tex/latex/ucs/data/uni-global.def))
    (/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty
    (/usr/share/texlive/texmf-dist/tex/latex/ucs/utf8x.def))
    (/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
    Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
    <2008/02/07> (tvz))
    (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grffile.sty
    (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/etexcmds.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)
    (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
    (/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))
    
    Package hyperref Message: Driver (autodetected): hpdftex.
    
    (/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def
    (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty) (./notebook.aux
    ) (/usr/share/texlive/texmf-dist/tex/context/base/supp-pdf.mkii
    [Loading MPS to PDF converter (version 2006.09.02).]
    ) (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
    (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
    *geometry* driver: auto-detecting
    *geometry* detected driver: pdftex
    
    Package geometry Warning: The marginal notes overrun the paper.
         Add 3.73001pt and more to the right margin.
    
    *geometry* verbose mode - [ preamble ] result:
    * driver: pdftex
    * paper: <default>
    * layout: <same size as paper>
    * layoutoffset:(h,v)=(0.0pt,0.0pt)
    * modes: 
    * h-part:(L,W,R)=(72.26999pt, 469.75502pt, 72.26999pt)
    * v-part:(T,H,B)=(72.26999pt, 650.43001pt, 72.26999pt)
    * \paperwidth=614.295pt
    * \paperheight=794.96999pt
    * \textwidth=469.75502pt
    * \textheight=650.43001pt
    * \oddsidemargin=0.0pt
    * \evensidemargin=0.0pt
    * \topmargin=-37.0pt
    * \headheight=12.0pt
    * \headsep=25.0pt
    * \topskip=10.0pt
    * \footskip=30.0pt
    * \marginparwidth=65.0pt
    * \marginparsep=11.0pt
    * \columnsep=10.0pt
    * \skip\footins=9.0pt plus 4.0pt minus 2.0pt
    * \hoffset=0.0pt
    * \voffset=0.0pt
    * \mag=1000
    * \@twocolumnfalse
    * \@twosidefalse
    * \@mparswitchfalse
    * \@reversemarginfalse
    * (1in=72.27pt=25.4mm, 1cm=28.453pt)
    
    (/usr/share/texlive/texmf-dist/tex/latex/ucs/ucsencs.def)
    (/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
    (./notebook.out) (./notebook.out)
    (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsa.fd)
    (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsb.fd)
    
    LaTeX Warning: No \author given.
    
    
    Package hyperref Warning: Difference (2) between bookmark levels is greater 
    (hyperref)                than one, level fixed on input line 233.
    
    [1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]
    ! Undefined control sequence.
    <recently read> \textquotesingle 
                                     
    l.315 ...extquotesingle{}passed\textquotesingle{}}
                                                      ) is the
    ? 
    ! Emergency stop.
    <recently read> \textquotesingle 
                                     
    l.315 ...extquotesingle{}passed\textquotesingle{}}
                                                      ) is the
    !  ==> Fatal error occurred, no output PDF file produced!
    Transcript written on notebook.log.
    
[W 13:49:47.996 NotebookApp] 500 GET /nbconvert/pdf/student_intervention_v2.ipynb?download=true (127.0.0.1): nbconvert failed: PDF creating failed
[E 13:49:47.998 NotebookApp] {
      "Accept-Language": "es,en-US;q=0.8,en;q=0.6", 
      "Accept-Encoding": "gzip, deflate, sdch", 
      "Connection": "keep-alive", 
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", 
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36", 
      "Host": "localhost:8888", 
      "Referer": "http://localhost:8888/notebooks/student_intervention_v2.ipynb", 
      "Upgrade-Insecure-Requests": "1"
    }
[E 13:49:47.998 NotebookApp] 500 GET /nbconvert/pdf/student_intervention_v2.ipynb?download=true (127.0.0.1) 695.18ms referer=http://localhost:8888/notebooks/student_intervention_v2.ipynb

**Comment by Carreau** [comment]
Migrated to jupyter/nbconvert#201
