### ISSUE TITLE
Dangling semicolon not rejected as wrong syntax

### ISSUE THREAD

**Issue by congma** [ipython/ipython#9153]
I know the semicolon `;` at the end of line input suppresses output in IPython, but a bare, dangling `;` is not rejected as bad syntax when it should.

```python
In [1]: ;
Out[1]: ''
```

Compare with vanilla Python:

```python
>>> ;
  File "<stdin>", line 1
    ;
    ^
SyntaxError: invalid syntax
```

**Comment by takluyver** [comment]
There's actually another purpose for `;` at the beginning of a line: it's a shorthand way to call a function with a string:

```
In [4]: def f(*args):
      :     return args
      : 
      : 

In [5]: ;f 1 2 3
Out[5]: ('1 2 3',)
```

That's what's happening here: your empty line is getting transformed to `("")`. You can see this by running `hist -t` afterwards (t for translated).

**Comment by congma** [comment]
Thanks for the explanation
