### ISSUE TITLE
Export as PDF creates giant images from markdown

### ISSUE THREAD

**Issue by staticfloat** [ipython/ipython#9157]
When taking a notebook such as [this one](https://davinci.cs.washington.edu/ee579/Lab1/Lab1.ipynb) ([HTML preview](https://davinci.cs.washington.edu/ee579/Lab1/Lab1.html)) I get [really ugly .PDF files](https://davinci.cs.washington.edu/ee579/Lab1/Lab1_bad.pdf) from the .pdf export option, because it makes my markdown images huge.  Is there a way to configure the width of these images?  Even if I have to hack an internal IPython/Jupyter tex style class somewhere, that would work for my purposes as I only need to do this occasionally.

If you want to reproduce this manually, you'll need all the images linked to from the notebook, I've included everything you need to run the notebook in [this .zip file](https://davinci.cs.washington.edu/ee579/Lab1/Lab1.zip) (well, except for IJulia itself).

**Comment by takluyver** [comment]
I think the changes proposed in jupyter/nbconvert#178 are relevant to this.

**Comment by staticfloat** [comment]
Yes, that issue seems to contain the fix I need.  I needed to include [this hunk](https://github.com/fperez/nbconvert/blob/29fa65f4ac00ac0c57eff402693d2c58f9253c7c/nbconvert/templates/latex/base.tplx#L19-L37) in my `nbconvert/templates/latex/base.tplx` file, and now everything is fixed.  Thanks!
