### ISSUE TITLE
Cannot build ipython 4.0.3 with setuptools 18.2

### ISSUE THREAD

**Issue by FRidh** [ipython/ipython#9159]
I was just updating [a bunch of Python packages](https://github.com/NixOS/nixpkgs/pull/12552) for Nix, when I get the following error when building ipython 4.0.3:

```
error in ipython setup command: Invalid environment marker: sys_platform == "darwin" and platform_python_implementation == "CPython"
```
Now I'm not familiar with these markers but I can imagine it is related to the pip 8.0.2 update. 

The error occurs with all Python versions.

**Comment by Carreau** [comment]
Hum, can you give us a bit more information at what point you get this error ? Like are you building a wheel ? installing ? Something else ?

**Comment by FRidh** [comment]
We build wheels first using `python setup.py bdist_wheel`, and that's where this error occurs.
I just tested by using pip 7.1.2 again, and the problem still occured. The problem did not occur with ipython 4.0.0. I haven't tested (yet) with 4.0.1 or 4.0.2.

**Comment by FRidh** [comment]
The problem began to occur in 4.0.1. Looking at the changes I think the culprit is https://github.com/ipython/ipython/commit/e2b269a4db1fc6313aef544a463c797e05a214d4

**Comment by Carreau** [comment]
Hum that's likely a [setuptools issue](https://bitbucket.org/pypa/setuptools/issues/387/some-pep-426-environment-markers-are-not) which support `platform_python_implementation` only starting at `18.5`.

**Comment by FRidh** [comment]
Thanks @Carreau 
Then this is an issue we have to solve at Nix I think. We've tried before to upgrade setuptools but it broke many packages. Now however, it seems we have to try either again, or start maintaining patches for those that require different versions.

**Comment by Carreau** [comment]
Yeah, setuptools is the worst, but used everywhere.

Let me reopen, we can try to add a check for setuptools version in setup.py to make the failure more explicit.

**Comment by Carreau** [comment]
Would #9164 helps, or at least be more explicit?
