### ISSUE TITLE
Crash if a subfolder of the current folder has more than 50'000 files

### ISSUE THREAD

**Issue by Gansgar** [ipython/ipython#9165]
iPython "crashes" or better gets stuck forever if at least one subdirectory of my current directory has more than 50'000 files. 

I have this file structure:

notMNIST_large
    A - 50'000 files
    B - 50'000 files
    ...
    J - 50'000 files

If I enter (or start in) the directory "notMNIST_large" iPython gets stuck and the web fronted shows a server failure. A new access to the web fronted gets stuck. All webbrowsers so far are trying to load it, but their wait till I need to kill ipython with a sigterm 3. The response to ^C is still there, but it never shuts down. (Probably yes after a long time that I'm not willing to wait)

**Comment by takluyver** [comment]
Are there any errors in the terminal where you started the notebook?

**Comment by Gansgar** [comment]
No, that would be a really bug. It's just that thr index script (I think) gets stuck during trying of indexing 550'000 mostly png files (I estimate that that would happen with every type of file). I would include a methode before indexing, that goves back an error of to much files if a folder has more than x files. Or something like this.

**Comment by takluyver** [comment]
I'm a bit puzzled that it falls over when a *subdirectory* has lots of files - I thought we only looked at the contents of the current directory. And I'm not sure what the indexing script you're talking about is. Maybe something got added to the project while I was away from it for a few months.

By the way, the notebook is now in a separate repo - https://github.com/jupyter/notebook . No need to reopen this issue, but for future issues that's the right place.

**Comment by takluyver** [comment]
So I can reproduce problems (and I would kind of expect them) if I open the directory containing 50k files in the notebook interface. But you say you see problems even opening the parent directory? Or have I misunderstood?

**Comment by Gansgar** [comment]
Yes. It gets stuck by opening the parent directory

**Comment by takluyver** [comment]
Maybe a browser is prefetching the link to the subdirectory. What browser are you using? Can you try running the notebook with the `--debug` flag, and see if there are any messages like:

```
200 GET /api/contents/A?type=directory...
```

**Comment by takluyver** [comment]
Or like

```
200 GET /tree/A ...
```

**Comment by Gansgar** [comment]
Used Safari, Chrome,  Iceweasel. I can look more precise into the debug lines later.

**Comment by Gansgar** [comment]
Okay. I can reproduce the error, but only on my Debian VMWare Fusion machine. The OS X variant (installed per pip3) worked smoothly and allowed me even to go back. Also for noticing, the folder that I access with the Debian is a shared folder. The read/write speed there is slower. 

I also could only reproduce the error with Iceweasle. In Chrome (OS X) and Safari the webpage just needed a bit to load, but under Iceweasle it showed me an Server Error (At this moment I could only kill it the hard way). Even accessing one of the folders in Chrome/Safari still allowed me to close iPython the normal way.

<img width="800" alt="error" src="https://cloud.githubusercontent.com/assets/14364148/12588691/e10ec6e4-c427-11e5-9c97-3ead19f4ce0f.png">
[error.txt](https://github.com/ipython/ipython/files/105360/error.txt)

**Comment by takluyver** [comment]
Shared folders in VMs are certainly slower, but I'm still mystified as to why it's happening when you're only browsing the parent directory of the ones with many files. Is it actually specific to when the subdirs have many files, or does it affect anything shared directory? If you start `ipython` in there and do `os.listdir('.')`, is it quick?

@minrk @Carreau am I missing something about how the notebook server scans files?

**Comment by Gansgar** [comment]
Works smooth in every other directory. Even reading all this data into a 1.7gb big array in a iPython Notebook works without problem (is just slow). The thing that is actually more interesting is: It only crashes in Iceweasle. Clearly. Every other access after that is not working anymore on any browser. But I can access all those directories  without a problem, except a longer response time for once after that on Chrome or Safari before the crash with Iceweasle.

**Comment by Gansgar** [comment]
It looks like that a bug in the browser results into a crash of iPython

**Comment by minrk** [comment]
I looked through, and I think we list directories in is_hidden as a check for readability. I'm not sure that makes sense to do, though.

**Comment by minrk** [comment]
jupyter/notebook#998 switches to execute access, which should be equivalent and much less expensive.

**Comment by Carreau** [comment]
migrated to https://github.com/jupyter/notebook/issues/999.

Migration script said it was not able to migrate, but still did:

```
$ migrate-issues ipython/ipython jupyter/notebook 9165
Migrating ipython/ipython#9165 to jupyter/notebook
Crash if a subfolder of the current folder has more than 50'000 files
Migrating 14 comments
Waiting for repos/jupyter/notebook/import/issues/434926
#<Sawyer::Resource:0x007f86c3aa9410>
Failed to migrate ipython/ipython/9165
```
