### ISSUE TITLE
Play MIDI files using display.Audio inside notebooks

### ISSUE THREAD

**Issue by arnaldorusso** [ipython/ipython#9169]
Hi,

Is it possible to mange the [Audio class](https://github.com/ipython/ipython/blob/master/IPython/lib/display.py), to accept `.mid` files and let the browser play these files?

Cheers!

**Comment by takluyver** [comment]
Audio is basically a wrapper around an HTML5 `<audio>` element, and I'm pretty sure that doesn't handle midi. So you probably need either something that can 'render' it to a waveform in Python, or a JS component that can play MIDI.

**Comment by arnaldorusso** [comment]
Thanks @takluyver 
Would be useful to implement [MIDIjs](http://midijs.net/midijs_api.html) as an option inside the same wrapper?

**Comment by takluyver** [comment]
I don't think we're likely to integrate something like that, but we'd be happy to see a `MIDI` display object as a package on PyPI - and we can answer questions if you want to do that.

**Comment by takluyver** [comment]
Closing as I don't think it makes sense for us to integrate midi support into IPython. It should be quite possible to do it as a separate package.
