### ISSUE TITLE
Aliases not documented

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#9174]
We have a page documenting magic functions now, but nothing describing the available aliases.

From discussion on #8762

**Comment by Achifaifa** [comment]
There is this tho, which is pretty thorough. 

https://ipython.org/ipython-doc/3/interactive/magics.html

**Comment by Achifaifa** [comment]
Not sure I understand. There is the magic page as linked in #8762 ([link to docs](https://ipython.readthedocs.org/en/stable/interactive/magics.html)), which describes the available magics. What exactly is what is missing now?

**Comment by takluyver** [comment]
Sorry, it should have said 'nothing describing the available *aliases*'. Run `%alias` in IPython for a list of aliases in use on your system.

**Comment by tomowind** [comment]
@takluyver Where should we document the available aliases? In https://ipython.readthedocs.io/en/stable/interactive/magics.html or in http://ipython.readthedocs.io/en/stable/api/generated/IPython.core.alias.html?
