### ISSUE TITLE
[docs] ad --universal to wheel build instructions.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9176]

**Comment by Carreau** [comment]
from @fperez : remove `$` sings in instructions also.

**Comment by minrk** [comment]
This was a mistake. We can't actually use universal wheels because we provide different executables for different Pythons. IPython 4.1.0rc1 installs `ipython3` on Python 2 now.

**Comment by Carreau** [comment]
> This was a mistake. We can't actually use universal wheels because we provide different executables for different Pythons. IPython 4.1.0rc1 installs ipython3 on Python 2 now.

No one fault in particular, should have thought about that too, and that's why we have RC too.
