### ISSUE TITLE
[docs] release process

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9178]
Add step to check what;s new

(and update whats new for 4.1)

**Comment by minrk** [comment]
In general, the release process doc should probably start as a copy of our [existing release process doc](https://github.com/ipython/ipython/wiki/Dev:-Releasing-IPython) that we've used for the last several releases.

**Comment by Carreau** [comment]
I just didn't knew the release process was here.

**Comment by minrk** [comment]
Yeah, sorry about that. Docs aren't useful if people can't find them!

Closed by #9193
