### ISSUE TITLE
set_custom_exc exception handlers don't catch SyntaxError

### ISSUE THREAD

**Issue by asmeurer** [ipython/ipython#9199]
```
In [6]: ipython = get_ipython()

In [7]: def exc_handler(self, etype, value, tb, tb_offset=None):
   ...:     print(etype)
   ...:     return self.showtraceback()
   ...:

In [9]: ipython.set_custom_exc((BaseException,), exc_handler)

In [10]: bad
<class 'NameError'>
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-10-df207dc9143c> in <module>()
----> 1 bad

NameError: name 'bad' is not defined

In [11]: 1f
  File "<ipython-input-11-0cd11c36f170>", line 1
    1f
     ^
SyntaxError: invalid syntax
```

(notice no `<class 'SyntaxError'>`)

I vaguely remember noticing this before in the code because syntax errors are handled specially. 

This causes my [iTerm2 extension](https://iterm2-tools.readthedocs.org/en/latest/ipython.html) to not register syntax errors as "failed" prompts.

**Comment by minrk** [comment]
If I recall correctly, SyntaxErrors are handled differently, since they fail before execution starts. Should be fixable, though.

**Comment by Carreau** [comment]
@asmeureur, is that ok if for now you need to register separately a handler for SyntaxErrors ? 

We can likely fix it for 5.0, but I'd like to have more time to think how `ipython.set_custom_exc` dealing also with syntax error would affect the rest of the machinery. 

That would mean for 5.0 I could likely expose a provisional `_extra_syntax_error_exc(self, etype, value, tb, tb_offset=None)` which is called before our actual handeling of SyntaxError, and refine the API for 6.0.

**Comment by asmeurer** [comment]
How can I register handlers for syntax errors?

**Comment by Carreau** [comment]
> How can I register handlers for syntax errors?

Sorry, I was unclear. 

Is that ok if for 5.0 I add a separate specific method to register handler only  for `SyntaxError` that would be provisional?  Or do you **need** `ipython.set_custom_exc` to also handle `SyntaxError`s ?

**Comment by asmeurer** [comment]
I don't really care if it's separate, as long as it's documented. If it is possible to do the same thing with SyntaxError I don't see why you wouldn't just make `set_custom_exc` do that.

**Comment by Carreau** [comment]
Because, As far as I can tell, `self.showtraceback()` calls `self.showsyntaxerror()` on `SyntaxError`, and  to do what you ask,I need `self.showsyntaxerror()` to call call your handler, which would call  `self.showtraceback()`... which leads to recursion. 

but right now, `self.showtraceback()` is never called,  as `SyntaxError`  never reaches it, as  `showsyntaxerror()` is called at `compiler.ast_parse()` time, even before the code is run.

Agreed in the best word, `set_custom_exc ` should do it, but it likely require **significant** refactor I'm not comfortable doing now.

**Comment by Carreau** [comment]
> Because, As far as I can tell, self.showtraceback() calls self.showsyntaxerror() on SyntaxError, and to do what you ask,I need self.showsyntaxerror() to call call your handler, which would call self.showtraceback()... which leads to recursion.
> 
> but right now, self.showtraceback() is never called, as SyntaxError never reaches it, as showsyntaxerror() is called at compiler.ast_parse() time, even before the code is run.
> 
> Agreed in the best word, set_custom_exc should do it, but it likely require significant refactor I'm not comfortable doing now.

Actually that's not completely true... let me see.

**Comment by takluyver** [comment]
You can still get a syntax error after parsing the code if, for instance, it imports some other code which has a syntax error.

**Comment by Carreau** [comment]
> @takluyver closed this in 0021167 34 minutes ago

I was expecting a PR number , @takluyver did you pushed on master directly ?

**Comment by takluyver** [comment]
Nope, I did that one with the merge button.

**Comment by Carreau** [comment]
```
:
*   commit a9c6dc47b26a9a23008b4180e9f4652ca700d3df
|\  Merge: 4d21841 bfe8da6
| | Author: Thomas Kluyver <takowl@gmail.com>
| | Date:   Wed Jun 1 16:37:54 2016 +0100
| |
| |     Merge pull request #9515 from Carreau/custom_syntax
| |
| |     Custom SyntaxError handler.
| |
| * commit bfe8da61676f6293bcee49c1be286e4452b9ba1b
| | Author: Matthias Bussonnier <bussonniermatthias@gmail.com>
| | Date:   Tue May 31 15:35:43 2016 -0700
| |
| |     Test that custom exceptions handlers can handle `SyntaxError`s
| |
| * commit 0021167631bbadb1b4e82deb4420e99c3cbb6cb8
| | Author: Matthias Bussonnier <bussonniermatthias@gmail.com>
| | Date:   Tue May 31 15:28:34 2016 -0700
| |
| |     Use generic showtraceback() instead of showsyntaxerror()
| |
| |     Should close #9199
| |
* | commit 4d2184138e4ad630f2149b16e53f903185aa2d8f
| | Author: Thomas Kluyver <thomas@kluyver.me.uk>
| | Date:   Wed Jun 1 10:31:05 2016 +0100
| |
| |     Simplify picking debugger class
| |
* | commit b9ee4853d38f873709fd0d246eebed31d27393e5
| | Author: Matthias Bussonnier <bussonniermatthias@gmail.com>
| | Date:   Tue May 31 13:42:09 2016 -0700
| |
| |     Also fall-back on simple debugger if `--simple-prompt`
| |
* | commit 49c798c18d45baf197a3db36f85528448d2148f8
|/  Author: Matthias Bussonnier <bussonniermatthias@gmail.com>
|   Date:   Fri May 27 10:37:51 2016 -0700
|
|       Add flag for simple_prompt.
|
|       As this mode seem to be useful beyond testing, expose it via a flag and
|       make it official.
|
*   commit 7a8a266756dc62de5ee616f0685a5422f5d97a14
|\  Merge: 33883d8 ab23885
| | Author: Thomas Kluyver <takowl@gmail.com>
| | Date:   Tue May 31 16:55:53 2016 +0100
| |
| |     Merge pull request #9511 from pavoljuhas/respect-user-shell
| |
| |     Use default system shell to capture shell output.
```

Apparently yes, but I reviewed the commit a posteriori, and it looks fine to me. `debugger_cls` was just a class attribute, and is now a instance property, but it's fine as this was introduces after 4.x. 

I'm now also wondering if `@property` and `@classmethods` would work at the same time.

**Comment by Carreau** [comment]
Anyway it's ok, and it might just have been a GitHub hiccup.

**Comment by takluyver** [comment]
> I'm now also wondering if @property and @classmethods would work at the same time. 

From what I know of the descriptor protocol, I would guess that you need to write a metaclass to make 'class properties' possible. Happily, in this case, we don't need such a thing.
