### ISSUE TITLE
kernel busy

### ISSUE THREAD

**Issue by akupf** [ipython/ipython#9204]
Hi, 

As soon as I hit this line: 
model = gensim.models.Word2Vec(sentences)
asteriks gets in countline. I restarted the kernel several times but it doesn´t seem to work.

**Comment by minrk** [comment]
Are you sure the code isn't hanging? Does it work if you run it in a regular Python script?

**Comment by akupf** [comment]
Hi Minrk, 

Well, it does run but after a while it ends up giving me a "segmentation fault": "6218 words, keeping 62334515 word types Segmentation fault"

**Comment by takluyver** [comment]
If the code you're running segfaults, that's probably the problem. I'm not sure why you wouldn't get the 'kernel died' dialog, but maybe it's running a subprocess that is segfaulting.

**Comment by akupf** [comment]
I think you are right, it goes beyond ipython´s notebook. I´m asking now in the Gensim´s Forum to see what the problem might be. Thank you all.
