### ISSUE TITLE
Need a shortcut or better way to get quicker edit to my previous code

### ISSUE THREAD

**Issue by rlam3** [ipython/ipython#9205]
Is there a shortcut for me to point my mouse to a certain part of my python code and edit it from there instead of holding my arrow keys? Thanks!

**Comment by takluyver** [comment]
I think this is something which will become possible with #9118 (which should be part of IPython 5)

**Comment by takluyver** [comment]
Mouse support is now available in master - you can set `TerminalInteractiveShell.mouse_support=True` in config to enable it. I enabled it for a while, but it breaks using the mouse for other things in the terminal, like scrolling and selecting text, so we're not going to enable it by default.
