### ISSUE TITLE
Running a Notebook Server link goes to wrong place

### ISSUE THREAD

**Issue by jfenwick** [ipython/ipython#9206]
https://ipython.org/ipython-doc/3/notebook/public_server.html
There's a box on this page that says:
This documentation is for an old version of IPython. You can find docs for newer versions here.

The Here links to the wrong place.
It should go here instead:
http://jupyter-notebook.readthedocs.org/en/latest/public_server.html

**Comment by takluyver** [comment]
The documentation got split up, but the notice on the top of every page is the same.

**Comment by Carreau** [comment]
Closing as by now google should have reindexed things correctly.
