### ISSUE TITLE
display_edit_shortcuts() in User Interface.ipynb get error "Javascript error adding output!"

### ISSUE THREAD

**Issue by weitongwei** [ipython/ipython#9207]
Running the example notebook "User Interface" from http://nbviewer.jupyter.org/github/ipython/ipython/blob/2.x/examples/Notebook/User%20Interface.ipynb,
the function "display_edit_shortcuts()" gives error:
"
Javascript error adding output!
TypeError: t is undefined
See your browser Javascript console for more details.
"  **in Firefox 42.0
**
OR

"Javascript error adding output!

TypeError:Unable to get the properties that are not defined or null reference "length"
See your browser Javascript console for more details.
" ** in IE 11**

**Comment by Carreau** [comment]
You are running an example which is almost 2 years old (version 2.x of IPython). The current version of IPython is 4.0.3 ( 4.1.0 as of a few minutes ago) and Notebook 4.1 has been released a few weeks ago. 

I would likely try more recent examples
