### ISSUE TITLE
Git tag format for IPython releases

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#9213]
For the older releases, we created tags in the format `rel-1.0.0`. For recent releases, we have been making both `rel-4.1.1` and `4.1.1` tags, but this is not documented in the release process docs. Do we:

1. Continue making both, and document this?
2. Switch entirely to the new format, stop making `rel-` tags, and document this?
3. Return to `rel-` tags, stop making the new tags, and optionally delete the new tags we have made?

**Comment by minrk** [comment]
My preference would be for 2, and stop making `rel-` tags when we start 5.x releases. Alternately, leave it with just `rel-`. I wouldn't delete any tags, no matter what we do.

**Comment by takluyver** [comment]
I have no particular preference on the format, but I'd prefer to have just one tag per release.

**Comment by jasongrout** [comment]
I favor tags of the form 'v4.1.1' or 'rel-4.1.1', just so that it's clear that the tag is about version numbers, compared to other stuff.

**Comment by minrk** [comment]
@jasongrout what would an X.Y.Z tag refer to other than a version number?

**Comment by jasongrout** [comment]
It's more about precautionary future-proofing tag names by essentially namespacing them.

**Comment by Carreau** [comment]
Preference for 2: 

> Switch entirely to the new format, stop making rel- tags, and document this.

**Comment by Carreau** [comment]
ping @fperez , @ellisonbg

**Comment by fperez** [comment]
My orginal rationale for that convention was that we had  `dev-X.Y.Z` tags (we've only used it once), plus `rel-X.Y.Z`.  That minimal namespacing helped quickly distinguish the two.

Honestly, now that we have years of data it seems that we're not really using anything but `rel` in practice, and since we could still encode `dev` into the `x.y.z...` format following [semver conventions](http://semver.org/), it probably makes more sense to drop the `rel-, foo-` approach and fall back to pure numbers + semver metadata if/when needed.

**Comment by damianavila** [comment]
yep, +1 to drop `rel`...

**Comment by vincentwoo** [comment]
Hi everyone! This appears to be the last remaining issue in milestone 4.2 and appears to have been decided ipso facto in https://github.com/ipython/ipython/pull/9215. Can this issue be closed, and if so, is a 4.2 release imminent?

**Comment by Carreau** [comment]
> Can this issue be closed, and if so, is a 4.2 release imminent?

Yes we can close. Though unfortunately we don't use milestone for minor revision this way, we mostly use minor milestone to automatically backport PRs. So minor milestone are almost always complete and do not reflect the proximity to a release. 

In the other hand we have not released a new version of IPython in a while, so I don't see any reasons not to.

**Comment by vincentwoo** [comment]
I would definitely love for a new version to be cut!

**Comment by takluyver** [comment]
OK, we're going with the unprefixed format `4.2.0`, and the release process documentation was changed in 1d9e725c3e5397b8756dc941a06a885666ebfae5. Closing.

**Comment by vincentwoo** [comment]
Awesome. Any word on where your head's at regarding releasing `4.2.0`?

**Comment by Carreau** [comment]
Release not were merged [there](https://github.com/ipython/ipython/pull/9410) so it's a question of actually doing the release now, which hopefully shoud happend before end of the day, otherwise end of week I guess.

**Comment by jasongrout** [comment]
To follow up, IPython 4.2 has been released: https://github.com/ipython/ipython/releases/tag/4.2.0

**Comment by vincentwoo** [comment]
420 blaze it
