### ISSUE TITLE
PyQT code can not run twice : Kernel stops

### ISSUE THREAD

**Issue by mvkrdndm** [ipython/ipython#9217]
{'commit_hash': '86d685f',
 'commit_source': 'installation',
 'default_encoding': 'cp857',
 'ipython_path': 'C:\\Anaconda3\\lib\\site-packages\\IPython',
 'ipython_version': '4.1.1',
 'os_name': 'nt',
 'platform': 'Windows-10-10.0.10586-SP0',
 'sys_executable': 'C:\\Anaconda3\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '3.5.1 |Anaconda 2.4.1 (64-bit)| (default, Jan 29 2016, '
                '15:01:46) [MSC v.1900 64 bit (AMD64)]'}

    import sys
    from PyQt4.QtCore import *
    from PyQt4.QtGui import *
    if __name__ == '__main__':
        app = QApplication(sys.argv)
        window = QWidget()
        window.setGeometry(100, 100, 500, 300)
        window.setWindowTitle("PyQT Tuts!")
        window.show()
        sys.exit(app.exec_())  
  
i can not run the code twice it says kernel stopped.this problem occurs in spyder ide with all pyqt versions
http://stackoverflow.com/questions/19459299/running-a-pyqt-application-twice-from-one-prompt-in-spyder
http://stackoverflow.com/questions/33527108/pyqt-examples-not-running-second-time

the problem occur because when you run the code once it holds some of QT variables in memory and when you run the code second time kernel stops

%reset works but it is annoying to type it after every pyqt execution

is there any easy way to fix this is this even considered a bug ? because it is normal to  holds the values right ? ,i am confused

note:the problem cause is not because of spyder ,in spyder **when you use normal python console pyqt runs as long as you want** bu in ipython console it crashes on second run

**Comment by takluyver** [comment]
I think Qt expects that only one Application will be created per process. The first SO question you linked to has a couple of workarounds - closing down the application instance, or reusing it. You can also run `%gui qt`, and then launch your app [like in this example](https://github.com/ipython/ipython/blob/master/examples/IPython%20Kernel/gui/gui-qt.py).

You could easily encapsulate any of these workarounds in a function so you just call `my_run_qt()` to launch your PyQt code again.

I don't think there's anything IPython can do to improve on this. Qt, as a C++ framework, was never designed to be run from an interactive shell.

**Comment by ccordoba12** [comment]
@takluyver, please close this one. @mvkrdndm reported this same issue in spyder-ide/spyder#2970 and a workaround as proposed there.

**Comment by takluyver** [comment]
Thanks Carlos.
