### ISSUE TITLE
Installation fails when installed via `setup_requires` or `install_requires`

### ISSUE THREAD

**Issue by akaihola** [ipython/ipython#9219]
To illustrate this problem, I created a dummy `setup.py`:

    from setuptools import setup
    setup(name='testpackage',
          setup_requires=['ipython'])

Now when I try to install this package, I get a traceback:

    $ virtualenv /tmp/venv
    New python executable in /tmp/venv/bin/python
    Installing setuptools, pip, wheel...done.
    
    $ . /tmp/venv/bin/activate

    $ python setup.py install
    Traceback (most recent call last):
      File "setup.py", line 4, in <module>
        setup_requires=['ipython'])
      File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 836, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1081, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1093, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 629, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 659, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 842, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1070, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1058, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error in ipython setup command: Invalid environment marker: sys_platform == "darwin" and platform_python_implementation == "CPython"

If I use `install_requires` instead:

    from setuptools import setup
    setup(name='testpackage',
          install_requires=['ipython'])

the error is a bit different:

    $ virtualenv /tmp/venv
    New python executable in /tmp/venv/bin/python
    Installing setuptools, pip, wheel...done.

    $ . /tmp/venv/bin/activate

    $ python setup.py install
    running install
    running bdist_egg
    running egg_info
    writing requirements to testpackage.egg-info/requires.txt
    writing testpackage.egg-info/PKG-INFO
    writing top-level names to testpackage.egg-info/top_level.txt
    writing dependency_links to testpackage.egg-info/dependency_links.txt
    reading manifest file 'testpackage.egg-info/SOURCES.txt'
    writing manifest file 'testpackage.egg-info/SOURCES.txt'
    installing library code to build/bdist.linux-x86_64/egg
    running install_lib
    warning: install_lib: 'build/lib' does not exist -- no Python modules to install
    
    creating build/bdist.linux-x86_64/egg
    creating build/bdist.linux-x86_64/egg/EGG-INFO
    copying testpackage.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying testpackage.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying testpackage.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying testpackage.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying testpackage.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    zip_safe flag not set; analyzing archive contents...
    creating 'dist/testpackage-0.0.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
    removing 'build/bdist.linux-x86_64/egg' (and everything under it)
    Processing testpackage-0.0.0-py2.7.egg
    Copying testpackage-0.0.0-py2.7.egg to /tmp/venv/lib/python2.7/site-packages
    Adding testpackage 0.0.0 to easy-install.pth file
    
    Installed /tmp/venv/lib/python2.7/site-packages/testpackage-0.0.0-py2.7.egg
    Processing dependencies for testpackage==0.0.0
    Searching for ipython
    Reading https://pypi.python.org/simple/ipython/
    Best match: ipython 4.1.1
    Downloading https://pypi.python.org/packages/source/i/ipython/ipython-4.1.1.zip#md5=445ff597cccb7818c23c988010f62838
    Processing ipython-4.1.1.zip
    Writing /tmp/easy_install-cGYEzr/ipython-4.1.1/setup.cfg
    Running ipython-4.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-cGYEzr/ipython-4.1.1/egg-dist-tmp-Wl5SCF
    error: Setup script exited with error in ipython setup command: Invalid environment marker: sys_platform == "darwin" and platform_python_implementation == "CPython"

I'm running Python 2.7 on Fedora 23. If I run `pip install ipython` in the virtualenv, it works just fine.

**Comment by minrk** [comment]
What setuptools version, and what about after `pip install --upgrade setuptools pip`?

There's a bug in setuptools that had the wrong value for some environment markers that was fixed a while ago.

**Comment by akaihola** [comment]
@minrk you're right, upgrading setuptools fixed the problem. I had 18.2 and upgraded to 20.0.
