### ISSUE TITLE
ipython.el not compatible with GNU emacs built in python mode

### ISSUE THREAD

**Issue by catphive** [ipython/ipython#922]
Trying to load ipython.el on stock GNU emacs will result in:

Debugger entered--Lisp error: (void-variable py-shell-map)
  byte-code("\301\302\303\"\210\304\305\306#\210\307\310!\207" [py-shell-map add-hook py-shell-hook #[nil "\300\301\302\"\207" [add-hook comint-output-filter-functions ipython-indentation-hook] 3] define-key "
" ipython-send-and-indent provide ipython] 4)
  require(ipython)
  eval((require (quote ipython)) nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)

This is because py-shell-mode is a variable only defined in the alternative python-mode.el available here:
https://launchpad.net/python-mode

The python.el mode that ships with emacs has a different naming scheme for it's variables, which is where this error comes from.

It would be nice if ipython.el worked out of the box without dependencies on a third party mode.

**Comment by minrk** [comment]
ipython.el is gone
