### ISSUE TITLE
TypeError: 'str' object is not callable - restart kernel and its gone

### ISSUE THREAD

**Issue by nafizh** [ipython/ipython#9224]
I was writing some code in an ipython notebook and a strange error came at an unusual place. To simplify, I then wrote this -
```python
 t = 8
 print str(t)
```

And strangely it showed the error 

> TypeError: 'str' object is not callable

I thought am I missing something here? Then I wrote the same code in a python shell and it worked perfectly fine. So, I restarted the kernel and it worked perfectly. 

I don't know if the bug is reproducible. But here is my environment information -

> About IPython Notebook
> Server Information:
> 
> You are using IPython notebook.
> 
> The version of the notebook server is 3.2.0-8b0eef4 and is running on:
> Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, Sep 15 2015, 14:50:01) 
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
> 
> Current Kernel Information:
> 
> Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, Sep 15 2015, 14:50:01) 
> Type "copyright", "credits" or "license" for more information.
> 
> IPython 3.2.0 -- An enhanced Interactive Python.
> Anaconda is brought to you by Continuum Analytics.
> Please check out: http://continuum.io/thanks and https://anaconda.org
> ?         -> Introduction and overview of IPython's features.
> %quickref -> Quick reference.
> help      -> Python's own help system.
> object?   -> Details about 'object', use 'object??' for extra details.
> %guiref   -> A brief reference about the graphical user interface.

**Comment by minrk** [comment]
I'm guessing that at some point in your code, something like this happened:

```python
str = 'a str'
```

So that the `str` name was overridden to refer to a string, rather than the builtin type `str`. That would be why restarting would have fixed it.

**Comment by nafizh** [comment]
Nope, looked for it. Have been burnt enough times to name a string str. You can close the issue, but I believe it was a bug.

**Comment by minrk** [comment]
You can try to find what command it may have been with:

    %history -g str

**Comment by takluyver** [comment]
And if it happens again, see what the value of `str` is.

**Comment by activa8** [comment]
Exactly same error .

And yes , as reported by the previous user, I do see that the error vanishes the moment your restart the kernel.

This is bizzare, because I ran the same code using IDLE and I did not get the 'str' object is not callable error. but the moment you run it using Anaconda and Spyder 3.1.3  on a Windows machine it gives the error.

I dont think we should resolve the issue , any help would be appreciated

**Comment by Carreau** [comment]
Well, if you can reproduce it, please send us the full code that does reproduce it, or we can't really debug this.

Thanks.

**Comment by baskaravishnus** [comment]
I have the same problem.I fix it by restarting the kernel

**Comment by AnupBS28** [comment]
Yes the same issue ! I gone mad resolving this error, and many said that there might be a  variable named str ,but no!!! i was just plotting a regression line and at line "plt.xlabel('size',fontsize=20)"
it was showing this error "TypeError: 'str' object is not callable". Thanks ! it worked after i restarted kernel
