### ISSUE TITLE
Ipython notebook crashes in Win10 - zeromq assertion failure

### ISSUE THREAD

**Issue by jveitchmichaelis** [ipython/ipython#9236]
Hi,

I'm running Python 2.7.11 in Windows 10 x64 pro. Pip list:

```
alabaster (0.7.7)
Babel (2.2.0)
backports-abc (0.4)
backports.ssl-match-
certifi (2015.11.20.
colorama (0.3.6)
cycler (0.9.0)
decorator (4.0.9)
docutils (0.12)
functools32 (3.2.3.p
ipykernel (4.2.2)
ipython (4.1.1)
ipython-genutils (0.
ipywidgets (4.1.1)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.1.
jupyter-console (4.1
jupyter-core (4.0.6)
lxml (3.5.0)
MarkupSafe (0.23)
matplotlib (1.5.1)
mistune (0.7.1)
nbconvert (4.1.0)
nbformat (4.0.1)
notebook (4.1.0)
numpy (1.11.0b3)
path.py (8.1.2)
pickleshare (0.6)
pip (8.0.2)
Pygments (2.1.1)
pyparsing (2.1.0)
pyreadline (2.1)
python-dateutil (2.4
pytz (2015.7)
pyzmq (15.2.0)
qtconsole (4.1.1)
scipy (0.17.0)
setuptools (20.1.1)
simplegeneric (0.8.1
singledispatch (3.4.
six (1.10.0)
snowballstemmer (1.2
Sphinx (1.3.5)
sphinx-rtd-theme (0.
tornado (4.3)
traitlets (4.1.0)
```

Whenever I run a notebook (either using `ipython notebook` or `jupyter notebook`), after a few hours of normal usage with no indications of anything wrong, the NotebookApp crashes with this assertion failure:

```
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
```

I've also seen:

```
Assertion failed: Software caused connection abort (bundled\zeromq\src\signaler.cpp:181)
```

I haven't been able to find anything obvious through Googling or on StackOverflow. The error occurs regardless of whether I'm actually running a command - I can leave the notebook open and go for dinner and come back to find it crashed. I thought it may have been due to interrupting/restarting the kernel, but sometimes it just happens out of the blue.

Thanks!

EDIT:

The most recent crash:

```
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:181)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
Assertion failed: nbytes == sizeof (dummy) (bundled\zeromq\src\signaler.cpp:303)
Assertion failed: ok (bundled\zeromq\src\mailbox.cpp:94)
```

**Comment by minrk** [comment]
The frequency is suspicious. Can you try downgrading pyzmq (to 14.x) and see if you have any better luck?

The mailbox assert is a [known issue on libzmq](https://github.com/zeromq/libzmq/issues/1108). I'm not familiar with the resets, but I've [opened an issue upstream](https://github.com/zeromq/libzmq/issues/1808)

**Comment by jveitchmichaelis** [comment]
Sure, I've downgraded to 14.0, will let you know how it goes. Thanks!

**Comment by jveitchmichaelis** [comment]
Nope, still crashes - same error.

    Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:256)
    Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:137)

**Comment by vinayprabhu** [comment]
Any updates on this? I am facing exactly the same situation.

**Comment by PolarNick239** [comment]
+1, this makes impossible to use embedded ipython scripting console in our application :(

P.S. [here](https://github.com/zeromq/libzmq/issues/1808#issuecomment-242979562) said that zmq 3.2.5 maybe doesn't have this bug, if so - than using pyzmq==13.1.0 can be a workaround. (sadly I wasn't able to install it under windows)

**Comment by VanitarNordic** [comment]
I have the same problem, W10-64x and Firewall=OFF

Did anybody find a solution?

**Comment by rhkarls** [comment]
I had this problem (Win 10), but it was solved by uninstalling Nexus Access Client - if that is of any use to anyone. Others report success uninstall Networx. So if you have any software monitoring network traffic or using tunnels - try uninstalling those perhaps ?

**Comment by VanitarNordic** [comment]
Yes, the problem was Networx

**Comment by sujan-sube** [comment]
I'm having this same issue with Jupyter Notebook. I am running Windows 10 64bit with Jupyter Notebook. I just uninstalled Networx and I am now running code for ML hyperparamter tuning, I will reply back on the status.

**Comment by sujan-sube** [comment]
My code has been running for about 2hrs now and no crash. Seems to be good now, thanks guys 😃
