### ISSUE TITLE
Ipdb prompt glitch in colorized mode

### ISSUE THREAD

**Issue by Unknowny** [ipython/ipython#9243]
Ipdb prompt behaves weird in a certain scenarios.
Symptoms: https://github.com/gotcha/ipdb/issues/79
Faulty commit: d7602375e8678f494eb9c526adefbec8306a9131 from this https://github.com/ipython/ipython/pull/8842 pull request.

**Comment by minrk** [comment]
Thanks for tracking down the relevant change! I'm not sure exactly what's going wrong, but we'll figure it out.

**Comment by takluyver** [comment]
#9244 should fix it.
