### ISSUE TITLE
Garbled color ouput of "object?" on Linux

### ISSUE THREAD

**Issue by x1o** [ipython/ipython#9252]
Executing `object?` for any `object` gives garbled color output on Linux --- escape sequences don't get translated into color attributes. Same result if running ipython in gnome-terminal (TERM=screen-256color), with or without tmux; in xterm; or in Linux console (TERM=linux).

`help(object)` displays colors correctly.

OS: Ubuntu 15.10
ipython version: 2.3.0-2ubuntu1

![screenshot from 2016-02-19 15-12-32](https://cloud.githubusercontent.com/assets/3007504/13175419/641f8dd8-d71b-11e5-9201-35cd3dec59ba.png)

**Comment by takluyver** [comment]
Translating escape sequences into colours is the job of your terminal emulator, not IPython. I can't fathom why all of those different interfaces would fail. The escape sequences look correct, and it's still working for me.

**Comment by Carreau** [comment]
could it be the `\x01` and `\x02` we inject to detect the color escape sequences ?

**Comment by takluyver** [comment]
Those should only be used when generating an input prompt - I don't think we're adding them into the oinspect output.

**Comment by takluyver** [comment]
@x1o just noticed that you're running an old version of IPython. Can you update to the latest release (4.1.1) and see if this still happens?

**Comment by x1o** [comment]
Got working it now. The output of `?object`, if it's long, is piped to a pager. On Ubuntu, it happens to be `less`. Now, by default, `less` doesn't recognize escape sequences as such, and in order to instruct it to do so, it has to be called with the `-r` flag. This is done by appending `-r` to the environmental variable `LESS`.

Hurray! Thanks.

**Comment by takluyver** [comment]
Ah, I think I understand the difference now. Do you have a PAGER environment variable set? If that's set, we invoke whatever it's set to, and if not, we default to `less -r`. It's not set on any of my systems, so I get the default command, which works with colour.

**Comment by x1o** [comment]
$ echo $PAGER
    less
Yes :) Thank you.

**Comment by takluyver** [comment]
Great. Maybe we should translate `less` there to `less -r`. If you want to work on it, the relevant code is in `IPython.core.page.get_pager_cmd`.

**Comment by x1o** [comment]
Well, I can only account for my particular case. Literally a 5-LOC patch: https://github.com/x1o/ipython/pull/1/files?diff=unified
