### ISSUE TITLE
Using javabridge in ipython causes java exceptions

### ISSUE THREAD

**Issue by jbcoe** [ipython/ipython#9253]
Running the following code in ipython leads to a java exception
```
import javabridge
javabridge.start_vm(run_headless=True)
a = javabridge.JWrapper(javabridge.make_instance("java/util/ArrayList","()V"))
a
```
I would hope that a on its own would call the repr method and show the array but instead it give a java exception:
```
Exception in thread "Thread-1" java.lang.NoSuchFieldException: _ipython_display_
        at java.lang.Class.getField(Class.java:1690)
Out[4]: Instance of java.util.ArrayList: []
```
A user-defined class without ipython_display defined works as expected. I'm not sure where the problem lies but the ability to wrap Java classes in python in an interactive session is awesome and it would be worth getting it working nicely.

I'm not sure if the changes that need making need making to javabridge or ipython but I'm happy to have a go once I've some idea where to look.

I've posted a parallel issue on javabridge: https://github.com/CellProfiler/python-javabridge/issues/72

**Comment by takluyver** [comment]
The comment on the parallel issue hits the nail on the head, I think - javabridge should be translating the Java exception into a Python AttributeError. There's probably some impedance mismatch here - in Python it's acceptable for something like this to go "does this object have method X", whereas that's probably not something you'd ever do in Java.

**Comment by jbcoe** [comment]
This is fixed in javabridge. It now works very nicely. I can import (wrapped) java classes into an ipython session. 

Thanks to ipython and javabridge developers for getting this so rapidly resolved.
