### ISSUE TITLE
How can I add React JS to experiment with features?

### ISSUE THREAD

**Issue by cqcn1991** [ipython/ipython#9278]
Hi, I was thinking about writing a ReactJS version of a table of content feature. The problem is that, I need to load 3 js files. 

So, how can I change the **Ipython Notebook** at my local machine, so I can load extra js files? 
(I think Ipython Notebook is essentially a web site running on my pc, so it would be relatively easy to add extra js files just like what I do in Ruby on Rails?)

**Comment by minrk** [comment]
Yes, you can add javascript files by placing them in `nbextensions`. Assuming you have downloaded the javascript files to a directory called `myextension`, you can install them with:

    jupyter nbextension install [--user] myextension

This copies the files to the appropriate destination. You can then load them in your javascript with:

```javascript
require(['nbextensions/myextension/whatever'], function (whatever) {
    do_stuff();
});
```

**Comment by cqcn1991** [comment]
@minrk I installed the dir, but where should I put the code?
```
require(['nbextensions/myextension/whatever'], function (whatever) {
    do_stuff();
});
```

I add a new file in that dir(`C:\ProgramData\jupyter\nbextensions\sidebar_test`) 

```
require(['nbextensions/myextension/react'], function (React) {
    consolo.log("This is a new sidebar");
})

But when I open a Ipython Notebook, there is no console log.
```

**Comment by minrk** [comment]
If it's an always-on extension, you need to do a little more. I was expecting you to want to use it in some display output. To enable an extension at load, assuming you have created `myextensions/main.js`, you would do:

```
jupyter nbextension enable myextensions/main
```

to enable the extension.
