### ISSUE TITLE
 4.3.0: 'module' object has no attribute 'register'

### ISSUE THREAD

**Issue by tdamsma** [ipython/ipython#9279]
Using python 3.5-64 on windows (fully updated) I get an error message starting the ipython kernel for a jupyter notebook. 

    'module' object has no attribute 'register'

[I am not the only one](http://stackoverflow.com/questions/35640934/register-method-missing-in-faulthandler/35652423#35652423). I couldn't find the code that causes the bug, but a simple downgrade to 4.2.2 resolved the issue so there must be something with the latest version that causes this.

**Comment by takluyver** [comment]
ipykernel 4.3.1, coming today, should fix this. 4.3.0 accidentally broke things for Python 3.5 on Windows.

**Comment by Carreau** [comment]
ipykernel now released. Cf releated issue:

https://github.com/ipython/ipykernel/issues/107
