### ISSUE TITLE
TAB key does not indent

### ISSUE THREAD

**Issue by stefanv** [ipython/ipython#9283]
In the git version of IPython, type

```
def foo(a):
    pass<ENTER>
```

The new line is not correctly indented, and the tab key does not insert 4 spaces.

/cc @Carreau @takluyver

**Comment by Carreau** [comment]
Note that tab also try to complete, so we might want to indent only on empty line.

**Comment by takluyver** [comment]
Hi Stefan!

The auto-dedenting is correct, I think - when you use something like `return`, `continue`, `break`, or `pass`, it dedents, because that normally means you've finished the indented block.

Good catch on using the tab key for indentation as well as completion, though - that should work.

**Comment by Carreau** [comment]
Better description of @stefanv problem, `|` is the cursor `<enter>` mean pressing enter.
```
In [1]: def foo():|<enter>
   ...:     1
   ...:
```
result: 

```
In [1]: def foo():
   ...:|
   ...:     1
   ...:
```

**Comment by stefanv** [comment]
The last example above is still broken :/

```
In [3]: def foo(a):
   ...:
   ...:     1
   ...:|
```

**Comment by Carreau** [comment]
Updated @stefanv comment for further precision.

**Comment by stefanv** [comment]
This may be a new issue or same, but I think you should be able to define a function with a space in it:

```
In [1]: def foo():
   ...:     "hello"
   ...:     if 1==0:
   ...:         print(False)
   ...:        |

In [2]: |
```

instead of

```
In [1]: def foo():
   ...:     "hello"
   ...:     if 1==0:
   ...:         print(False)
   ...:
   ...:        |

In [2]:
```

**Comment by takluyver** [comment]
In general, we take a blank line to indicate that input is complete. This has been the idea since forever, although the exact details may have changed. If you want to enter code including blank lines, you can now press F2 to use $EDITOR.

**Comment by Carreau** [comment]
> In general, we take a blank line to indicate that input is complete. This has been the idea since forever, although the exact details may have changed.

I think the question was to make it 2 blank lines. I think with the eddition capabilities of PTK whether it was or not the case I think it make sens to consider.

**Comment by carlsmith** [comment]
*Note: This email is just sharing an idea. You can safely ignore it if
you're busy.​*

I once used a solution to the Return/Enter problem that sounds complicated,
but was really intuitive in practice.

By default, the Enter key would just input a newline, so you could edit
multiline inputs just like a regular text editor, and Ctrl-Enter would
evaluate the input. That's obviously a pretty common approach. What was
novel was what happened if you hit Enter, *and* the input was a single
line, *and* the input was a one-liner (which IPython can determine
statically​). In that case, the shell would evaluate the input when you hit
Enter, as though you'd hit Ctrl-Enter.

​It sounds like you would have to think too much, but you actually just
think in terms of editing chunks of Python using the default keybindings
*or* quickly entering a command and hitting Enter. It feels like the
interpreter just magically knows what you're thinking.

It would obviously be opt-in. Maybe go with *Enable Psychic Return Key* :)

**Comment by carlsmith** [comment]
I once used a solution to the Return/Enter problem that sounds complicated,
but was really intuitive in practice.

By default, <kbd>Enter</kbd> would just input a newline, so you could edit
multiline inputs just like a regular text editor, and <kbd>Ctrl</kbd>+<kbd>Enter</kbd> would
evaluate the input. That's obviously a pretty common approach. What was
novel was what happened if you hit <kbd>Enter</kbd>, *and* the input was a single
line, *and* the input was a one-liner (which IPython can determine
statically​). In that case, the shell would evaluate the input when you hit
<kbd>Enter</kbd>, as though you'd hit <kbd>Ctrl</kbd>+<kbd>Enter</kbd>.

​It sounds like you would have to think too much, but you actually just
think in terms of editing chunks of Python using the default keybindings
or quickly entering a command and hitting <kbd>Enter</kbd>. It feels like the
interpreter just magically knows what you're thinking.

It would obviously be opt-in. Maybe go with *Enable Psychic Return Key* :)

**Comment by Carreau** [comment]
That's mostly how IPython currently work, except there is less distinction multiline/oneline.

- oneline:
   - if the code is valid and complete: Execute
   - otherwise add new line
- multiline.
   - if code valid, complete and have at least one new line at the end: Execute
   - otherwise : add new line.

Add on top: cursor need to be at the end of buffer, and Ctrl-Enter always execute. 
The question is what if you want a white line in your code ?

_Enable Psychic Return Key_ sounds great, like _Write the code I'm thinking of_ :-)

**Comment by carlsmith** [comment]
Yeah, IPython is very similar, but still feels quit different in practice.
The approach I described is less eager to execute, except with line magics
and system commands, where it's the same. With anything else, it assumes
you want to edit a chunk of code, so entering two lines is just a matter of
hitting Return twice.

My style is less efficient when you want to enter a regular Python
one-liner. Often, you don't need to use single line inputs, like if you
want to do a couple of assignments, you can just do it as a two-line block
instead, but still, you often do want to evaluate a single expression, so
it is still a compromise.

Thank you for considering it, Matthias. It's really just food for thought.

**Comment by Carreau** [comment]
I've opened #10319 to track the execution semantics of enter.

Closing this as the bug(s) are fixed.

**Comment by anntzer** [comment]
@Carreau Perhaps related issue (I can open a new one if you prefer): C-Enter is not working for me (either to force execution of a multiline input without having to press enter twice, with the cursor at the end, or to execute a single or multiline input with the cursor NOT at the end of the buffer).  I've tried both vi and emacs input modes on PTK.

**Comment by Carreau** [comment]
> I can open a new one if you prefer

Yes please. Though if by  C you mean Ctrl, there is not much we can do as "Enter" is indistinguishable from `Ctrl+J` so `Ctrl+Enter`  is the same as enter, and `Esc,Enter` (or `Ctrl-[`, `Enter`) should execute.
