### ISSUE TITLE
Terminal cursor is misplaced when debugging Django using ipdb and IPython 4.1.2

### ISSUE THREAD

**Issue by Cahersan** [ipython/ipython#9291]
Using version 4.1.2, the terminal cursor is misplaced when debugging Django using `ipdb` (see attached image).  It only happens when seting `ipdb.set_trace()` for debug purposes in a piece of code, not using `ipython` by itself or `manage.py shell_plus`.This behaviour didn't occur with version 4.0.0.

![image](https://cloud.githubusercontent.com/assets/6106769/13497691/023cb280-e157-11e5-8cee-acc900682bf2.png)

I'm using xfce4-terminal.

Thanks!

**Comment by takluyver** [comment]
Should be fixed in master by #9244.

**Comment by Cahersan** [comment]
Installed from master and tested. No problem at all. Thanks!
