### ISSUE TITLE
DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by DreamFlasher** [ipython/ipython#9293]
After shutdown (ctrl+c) and restart of ipython notebook I get this error:

```
[E 17:26:06.417 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/home/ml/anaconda2/lib/python2.7/site-packages/notebook/base/handlers.py", line 458, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/home/ml/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/home/ml/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "/home/ml/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
        yielded = next(result)
      File "/home/ml/anaconda2/lib/python2.7/site-packages/notebook/services/contents/handlers.py", line 124, in get
        path=path, type=type, format=format, content=content,
      File "/home/ml/anaconda2/lib/python2.7/site-packages/notebook/services/contents/filemanager.py", line 354, in get
        model = self._notebook_model(path, content=content)
      File "/home/ml/anaconda2/lib/python2.7/site-packages/notebook/services/contents/filemanager.py", line 314, in _notebook_model
        self.mark_trusted_cells(nb, path)
      File "/home/ml/anaconda2/lib/python2.7/site-packages/notebook/services/contents/manager.py", line 447, in mark_trusted_cells
        trusted = self.notary.check_signature(nb)
      File "/home/ml/anaconda2/lib/python2.7/site-packages/nbformat/sign.py", line 220, in check_signature
        if self.db is None:
      File "/home/ml/anaconda2/lib/python2.7/site-packages/traitlets/traitlets.py", line 529, in __get__
        return self.get(obj, cls)
      File "/home/ml/anaconda2/lib/python2.7/site-packages/traitlets/traitlets.py", line 508, in get
        value = self._validate(obj, dynamic_default())
      File "/home/ml/anaconda2/lib/python2.7/site-packages/nbformat/sign.py", line 127, in _db_default
        self.init_db(db)
      File "/home/ml/anaconda2/lib/python2.7/site-packages/nbformat/sign.py", line 139, in init_db
        )""")
    DatabaseError: database disk image is malformed
```

The following similar issues did not help in solving:
https://github.com/ipython/ipython/issues/2097
https://github.com/ipython/ipython/issues/7795
https://github.com/ipython/ipython/issues/8294
https://github.com/ipython/ipython/issues/8997

**Comment by DreamFlasher** [comment]
Solved by `rm ~/.local/share/jupyter/nbsignatures.db` -- ipython/jupyter are trashing the hd a bit too much imho, if nobody knows anymore where all the db's are located...

**Comment by takluyver** [comment]
Glad you solved it. We do know where all the databases are located, but it's a bit confusing trying to work it out from bug reports:

* We use two distinct databases: IPython's history database, and Jupyter's notebook signatures database. #2097 is about the former.
* The notebook signatures database moved when we separated Jupyter from IPython. #7795 and #8294 describe the old location of the database you moved.
* #8997 is describing a related but different issue with permissions.

When we release nbformat 4.1, it will catch this error, print a warning, and recreate the signatures database. See jupyter/nbformat#32.

**Comment by DreamFlasher** [comment]
Thanks for the explanation!

**Comment by patelmohitj91** [comment]
@DreamFlasher  Please tell me where to type the code rm ~/.local/share/jupyter/nbsignatures.db
I use a Mac, and have been getting this error when I reinstalled anaconda2. it is installed on Users/apple/anaconda2

**Comment by takluyver** [comment]
The location is different on osx. Run jupyter --data-dir to see where that
file lives.

**Comment by patelmohitj91** [comment]
@takluyver That's to be run on the terminal directly?...or in the Anaconda shell?..I tried a manual search of the anaconda2 folder but to no good..

**Comment by takluyver** [comment]
It should be run in any terminal that you can run `jupyter` from. I'm not sure what you mean by 'Anaconda shell'.

**Comment by patelmohitj91** [comment]
Sure..will try that but it seems that after the anaconda2 installation, it made my mac system unstable due to some code break.. it is not booting up now after a couple of restarts and a hard disk erase seems like the only option.[Disk utility unable to erase the disk].Completely at sea now. :(
Thanks for your inputs @takluyver

**Comment by takluyver** [comment]
Sorry to hear that - I've never heard of Anaconda causing something like that.

**Comment by anantguptadbl** [comment]
Hello @DreamFlasher , I was able to solve this problem my altering the permissions on the nbsignatures.db file

**Comment by feussi** [comment]
http://installion.co.uk/ubuntu/vivid/universe/g/gajim/uninstall/index.html

hat mir geholfen...

**Comment by ctivanovich** [comment]
I solved this issue by going into .ipython folder and removing the corrupted database, which turned out to be ipython's history.sql. I think what may have happened is I was doing a conda update --all while jupyter lab was up, and maybe that corrupted the database since there was an active ipython kernel being used.

**Comment by KrishnaMohanRavilla** [comment]
Guys can u pls tell me how to fix this on windows???

**Comment by DreamFlasher** [comment]
https://github.com/ipython/ipython/issues/9293#issuecomment-191844470

**Comment by KrishnaMohanRavilla** [comment]
Sorry i forgot to mention, I am using google colaboratory.
I am getting this error: database disk image is malformed.
I i try to run my script on ipython it runs fine.

**Comment by Sapna714** [comment]
I have the same problem on colab.. any ideas??

**Comment by KrishnaMohanRavilla** [comment]
i got this error because i was loading my sqlite even before it was uploaded to colab.
So check once by waiting a couple of minutes after uploading the file.
I think this should work. bcz it worked for me.  :p

**Comment by y2k-shubham** [comment]
**@ctivanovich** solution of deleting `history.sqlite` worked for me. References
 - [Error loading IPython Jupyter notebook](https://stackoverflow.com/a/35326875/3679900)
 - [Where is the history file for ipython](https://stackoverflow.com/a/30629448/3679900)

**Comment by michaelaye** [comment]
just happened to me, out of nothing (remote notebook server, client's screen was locked but never shut down).

**Comment by suragnair** [comment]
This can happen when you are out of disk space in the directory where jupyter is running from. Do check if there’s disk space available.

**Comment by Jiyon-Lyu** [comment]
> **[@ctivanovich](https://github.com/ctivanovich)** solution of deleting `history.sqlite` worked for me. References
> 
> * [Error loading IPython Jupyter notebook](https://stackoverflow.com/a/35326875/3679900)
> * [Where is the history file for ipython](https://stackoverflow.com/a/30629448/3679900)

It works for me. Thank you!
