### ISSUE TITLE
Move ipdb away from readline

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#9295]
Another thing I shouldn't forget before 5.0: ipdb still uses readline for user input. Since we're dropping the dependencies on pyreadline and gnureadline, I want to move it over to prompt_toolkit as well. We will also need a plain `input()` variant for use in the kernel (this won't support tab completion, but we have no way of doing completions for the debugger in the kernel anyway).

**Comment by Carreau** [comment]
So AFAICT, we should provide a custom `cmdloop` methods, which is the one inherited from `cmd.Cmd` right ?

**Comment by Carreau** [comment]
done in #9487
