### ISSUE TITLE
'CannedFunction' objects is not callable

### ISSUE THREAD

**Issue by saq7** [ipython/ipython#9307]
I am trying to set up a cluster using [StarCluster](http://star.mit.edu/cluster/) and ipyparallel. When I try to run the following commands, I get the error below. I have never seen a python error
missing a stack trace this way.

    from ipyparallel import Client
    rc = Client()
    ipview = rc[:]
    res = ipview.apply_async(lambda x: x+3, 3)
    res.get()

I get the following error:

    [0:apply]: 
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)<string> in <module>()
    TypeError: 'CannedFunction' object is not callable
    
    [1:apply]: 
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)<string> in <module>()
    TypeError: 'CannedFunction' object is not callable

Not even sure where to start debugging this.

Here is the output from pip freeze on the master node

    apt-xapian-index==0.45
    backports-abc==0.4
    backports.ssl-match-hostname==3.5.0.1
    boto==2.3.0
    certifi==2016.2.28
    chardet==2.0.1
    Cheetah==2.4.4
    cloud-init==0.7.2
    configobj==4.7.2
    Cython==0.17.4
    decorator==4.0.9
    distro-info==0.10
    Django==1.6.1
    docutils==0.10
    drmaa==0.7.5
    dumbo==0.21.36
    euca2ools==2.1.1
    futures==3.0.5
    ipykernel==4.3.1
    ipyparallel==5.0.1
    ipython==4.0.0
    ipython-cluster-helper==0.5.1
    ipython-genutils==0.1.0
    Jinja2==2.6
    jupyter-client==4.2.1
    jupyter-core==4.1.0
    Landscape-Client==13.7.3
    M2Crypto==0.21.1
    Mako==0.7.3
    MarkupSafe==0.15
    matplotlib==1.2.1
    meld3==0.6.10
    mercurial==2.2.2
    mpi4py==1.3.1
    multiprocessing==2.6.2.1
    netifaces==0.10.4
    nose==1.1.2
    numexpr==2.0.1
    numpy==1.8.0
    oauth==1.0.1
    openpyxl==1.5.8
    PAM==0.4.2
    pandas==0.12.0
    paramiko==1.7.7.1
    path.py==8.1.2
    pexpect==4.0.1
    pickleshare==0.6
    Pillow==2.3.0
    prettytable==0.6.1
    pssh==2.2.2
    ptyprocess==0.5.1
    pudb==2013.5.1
    pycrypto==2.6
    pycurl==7.19.0
    Pygments==1.6
    pyOpenSSL==0.13
    pyparsing==1.5.7
    pyserial==2.6
    python-apt===0.8.8ubuntu6
    python-dateutil==1.5
    python-debian===0.1.21-nmu2ubuntu1
    python-distutils-extra==2.37
    pytz==2012rc0
    PyYAML==3.10
    pyzmq==15.2.0
    requests==1.1.0
    roman==1.4.0
    scipy==0.13.2
    simplegeneric==0.8.1
    singledispatch==3.4.0.3
    six==1.10.0
    Sphinx==1.1.3
    ssh-import-id==3.14
    statsmodels==0.4.2
    supervisor==3.0
    tables==2.4.0
    tornado==4.3
    traitlets==4.1.0
    Twisted-Core==12.3.0
    Twisted-Names==12.3.0
    Twisted-Web==12.3.0
    typedbytes==0.3.8
    urllib3==1.5
    urwid==1.1.2
    virtualenv==1.11
    xlrd==0.6.1
    xlwt==0.7.4
    zope.interface==4.0.5

Here is the pip freeze from the only slave node

    apt-xapian-index==0.45
    backports-abc==0.4
    backports.ssl-match-hostname==3.5.0.1
    boto==2.3.0
    certifi==2016.2.28
    chardet==2.0.1
    Cheetah==2.4.4
    cloud-init==0.7.2
    configobj==4.7.2
    Cython==0.17.4
    decorator==4.0.9
    distro-info==0.10
    Django==1.6.1
    docutils==0.10
    drmaa==0.7.5
    dumbo==0.21.36
    euca2ools==2.1.1
    futures==3.0.5
    ipykernel==4.3.1
    ipyparallel==5.0.1
    ipython==4.0.0
    ipython-cluster-helper==0.5.1
    ipython-genutils==0.1.0
    Jinja2==2.6
    jupyter-client==4.2.1
    jupyter-core==4.1.0
    Landscape-Client==13.7.3
    M2Crypto==0.21.1
    Mako==0.7.3
    MarkupSafe==0.15
    matplotlib==1.2.1
    meld3==0.6.10
    mercurial==2.2.2
    mpi4py==1.3.1
    multiprocessing==2.6.2.1
    netifaces==0.10.4
    nose==1.1.2
    numexpr==2.0.1
    numpy==1.8.0
    oauth==1.0.1
    openpyxl==1.5.8
    PAM==0.4.2
    pandas==0.12.0
    paramiko==1.7.7.1
    path.py==8.1.2
    pexpect==4.0.1
    pickleshare==0.6
    Pillow==2.3.0
    prettytable==0.6.1
    pssh==2.2.2
    ptyprocess==0.5.1
    pudb==2013.5.1
    pycrypto==2.6
    pycurl==7.19.0
    Pygments==1.6
    pyOpenSSL==0.13
    pyparsing==1.5.7
    pyserial==2.6
    python-apt===0.8.8ubuntu6
    python-dateutil==1.5
    python-debian===0.1.21-nmu2ubuntu1
    python-distutils-extra==2.37
    pytz==2012rc0
    PyYAML==3.10
    pyzmq==15.2.0
    requests==1.1.0
    roman==1.4.0
    scipy==0.13.2
    simplegeneric==0.8.1
    singledispatch==3.4.0.3
    six==1.10.0
    Sphinx==1.1.3
    ssh-import-id==3.14
    statsmodels==0.4.2
    supervisor==3.0
    tables==2.4.0
    tornado==4.3
    traitlets==4.1.0
    Twisted-Core==12.3.0
    Twisted-Names==12.3.0
    Twisted-Web==12.3.0
    typedbytes==0.3.8
    urllib3==1.5
    urwid==1.1.2
    virtualenv==1.11
    xlrd==0.6.1
    xlwt==0.7.4
    zope.interface==4.0.5

**Comment by Carreau** [comment]
Please dont' open issues twice. 

Closing in favor of https://github.com/ipython/ipyparallel/issues/117

**Comment by saq7** [comment]
sorry about that, wasn't sure where this belonged. thanks for closing

**Comment by Carreau** [comment]
> sorry about that, wasn't sure where this belonged. thanks for closing

No problem. It's mostly the same people on both these repo. I'm mostly closing to avoid duplicate effort in people responding in both issues. I'm also going to lock to avoid people responding here by mistake.
