### ISSUE TITLE
Define a better displayFormatter of function and methods

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9310]
I think it should be possible to define a default formatter for functions that would be better than the defautl one. 

The following is not really useful:

```
In [1]: from inspect import signature
In [2]: signature
Out[2]: <function inspect.signature>
```

Something that would display less than `signature?` or `signature??`, but still a bit better than plain function/methods REPR. 

```
In [1]: from inspect import signature
In [2]: signature
Out[2]: <function inspect.signature(obj, *, follow_wrapped=True)>
```

Seem like a nice standalone project that could be useful. 

Thoughts ?

**Comment by takluyver** [comment]
Yep, I think that would make sense.

**Comment by Madhu94** [comment]
I'm trying this!
