### ISSUE TITLE
Why does body's css set to position absolute?

### ISSUE THREAD

**Issue by cqcn1991** [ipython/ipython#9320]
I'm developing a sidebar extension for ipython notebook, see here:
![toc](https://cloud.githubusercontent.com/assets/2425141/13720167/a7f8a058-e83c-11e5-8e84-4ebda0c660dc.gif)

https://github.com/ipython-contrib/IPython-notebook-extensions/issues/532

Now, I want to add `scrollspy` to let user know where they are
![qq](https://cloud.githubusercontent.com/assets/2425141/13721539/84e25f04-e865-11e5-85cb-a423d8479ff5.png)
http://getbootstrap.com/javascript/#scrollspy

But that requires the `body` set to `position: relative`, and then I realized that the `body` in Ipython Notebook is absolute, And `#site`(the main content div of our notebook) has a fixed height.

So I can't use `scrollspy` here, and I'm wondering why set css (`absolute position` of `body`, `fixed height` of `#site`) this way?

**Comment by Carreau** [comment]
That's seem to be a jupyter/notebook issue and not an IPython one. 

We would have to dig into the history to figure out why, but my guess it's a problem with the pager. And position:relative, likely screw-up scrolling. You are welcome to try, and ask for us to change if you think it is better.

**Comment by cqcn1991** [comment]
@Carreau Yes, I issued this and later find out that it should be reported there. And here is the link
https://github.com/jupyter/notebook/issues/1202
