### ISSUE TITLE
Semicolon doesn't suppress output if followed by a comment

### ISSUE THREAD

**Issue by akhmerov** [ipython/ipython#9321]
ipython version: 4.1.2

Reproducing:
execute a statement
```python
1;
# this is comment
```

Result: `1` is printed.  
execute
```python
1
# this is comment;
```
Result: no output.

Desired result: according to the ipython convention, no output should happen in the first case, and `1` should be printed in the second.

**Comment by takluyver** [comment]
I think this has already been fixed in master by #9228 - the fix should be released as part of 4.2 when that happens.

**Comment by akhmerov** [comment]
You're right, I verified it doesn't happen on master.
