### ISSUE TITLE
nbconvert Fail

### ISSUE THREAD

**Issue by zmckerr** [ipython/ipython#9327]
Not really sure whats going on here but have looked for hours for a fix. Trying to convert a python notebook to static html but showing this internal server error 500:

nbconvert failed: markdown2html requires mistune: dlopen(//anaconda/lib/python3.5/site-packages/mistune.so, 2): no suitable image found.  Did find:
    //anaconda/lib/python3.5/site-packages/mistune.so: malformed mach-o image: load command #12 length (0) too small in //anaconda/lib/python3.5/site-packages/mistune.so

**Comment by minrk** [comment]
That seems like the mistune conda package is broken somehow. You can try reinstalling it:

    conda remove --force mistune
    conda install mistune

If that still doesn't work, you can try reinstalling it with pip:

    conda remove --force mistune
    pip install mistune

**Comment by zmckerr** [comment]
when I try to execute the removal, python ask if I want to proceed (y/n) and I cannot type anything into the command prompt.

**Comment by minrk** [comment]
Hrm. That's a new one. Are you using a regular terminal?

**Comment by zmckerr** [comment]
I've tried in every terminal possible, python 3.5, qtconsole, spyder, jupyter. Seems to show that the kernel is running but noting is actually happening in the activity of my network.

**Comment by takluyver** [comment]
You would normally run that in a terminal - the default one on Mac is just called 'Terminal', and it's nothing to do with IPython, Jupyter or Python. Jupyter frontends can't pass input back to interactive subprocesses. If you want to run it in a Jupyter frontend, use the `--yes` option to skip the confirmation prompt.

**Comment by zmckerr** [comment]
Thanks takluyver, I used the frontend of `--yes` and it worked. Very new to writing code and have trouble knowing where to execute commands. I use jupyter for my physics class and we work within the notebook.

**Comment by rhearty1** [comment]
Thanks for the solution. I had this problem and reinstalling via conda worked for me.
