### ISSUE TITLE
IPython.InteractiveShell.instance() has colors set to 'NoColor' instead of 'Linux' for IPython version >= 4.1

### ISSUE THREAD

**Issue by lesteve** [ipython/ipython#9328]
```python
import IPython

shell = IPython.InteractiveShell.instance()
print(shell.colors)
```

Output for IPython 4.0.3 is `'Linux'`, ouput for IPython 4.1.0 is `'NoColor'`.

It seems like `IPython.terminal.interactiveshell.TerminalInteractiveShell` does not have this problem. Do you recommend using this class instead?

This affects the nose plugin called ipdbplugin if you are wondering. For more details, see https://github.com/flavioamieiro/nose-ipdb/pull/19.

Using git bisect the problem appears in 5f82378290041d392e953e2d45c387b0d1b97f9a. I investigated a little bit more and all I could find was that running the magic `%colors Linux` through this [line](https://github.com/ipython/ipython/blob/aa586fd81940e557a1df54ecd0478f9d67dfb6b4/IPython/core/interactiveshell.py#L2046) ends up setting the shell colors to NoColor because `self.has_readline` is False [here](https://github.com/ipython/ipython/blob/aa586fd81940e557a1df54ecd0478f9d67dfb6b4/IPython/core/magics/basic.py#L354).

The snippet I used to trace the problem in case it is useful:

```python
import IPython

from traitlets import observe

class MyInteractiveShell(IPython.InteractiveShell):
    @observe('colors')
    def _colors_changed(self, change):
        print("{name} changed from {old} to {new}".format(**change))
        import pdb
        pdb.set_trace()

MyInteractiveShell.instance()
```

**Comment by takluyver** [comment]
If you know you want the `Linux` colours, the easiest thing may be to pass that explicitly, rather than instantiating an InteractiveShell to get it.

The idea is that `InteractiveShell` is the common execution machinery shared by terminal IPython and IPython running as a kernel for the notebook/qtconsole/other frontends. `TerminalInteractiveShell` is the subclass of that used in terminal IPython (and `ZMQInteractiveShell`, now in ipykernel, is the subclass for the kernel). I did some refactoring to move the readline initialisation code from IS to TIS. This is the first step in a much larger refactoring I'm working on for IPython 5 - I can't yet say what approach will be equivalent in the future.

**Comment by lesteve** [comment]
> If you know you want the Linux colours, the easiest thing may be to pass that explicitly, rather than instantiating an InteractiveShell to get it.

I think the intent of the code of ipdbplugin is to set the colors consistently with the IPython config (i.e. ~/.ipython/profile_default/ipython_config.py in my case). Would this be a more robust way to get the IPython colors from the config?

```python
from IPython.terminal.ipapp import TerminalIPythonApp
colors = TerminalIPythonApp.instance().shell.colors
```

Better suggestions welcome, obviously !

**Comment by takluyver** [comment]
I think you need to use an `*App` class for it to load config files anyway - unless I've forgotten something, `InteractiveShell` itself will not load config files. Off the top of my head, the snippet you just posted looks reasonable, but I'm tired, so someone else might well think of something better.

**Comment by lesteve** [comment]
You are right, the `*Shell` classes don't seem to care about the config.

This updated snippets seems to do it for me:

```python
from IPython.terminal.ipapp import TerminalIPythonApp
app = TerminalIPythonApp.instance()
app.initialize()
print('colors:', app.shell.colors)
```

Thanks for your help I'll close this issue !
