### ISSUE TITLE
IPython crash on startup - ValueError: embedded null character

### ISSUE THREAD

**Issue by OliverEvans96** [ipython/ipython#9329]
Hi all,

IPython has been working fine, but I killed a process forcefully and now IPython crashes every time on startup via terminal. IPython via jupyter notebook still works fine. Running python from the terminal also works as usual. I'm using:

Python3.5
IPython 4.1.2
CentOS 5.3

Here's the full traceback:

- - - - - - - - - -

[oevans@hamilton chiari]$ ipython
Traceback (most recent call last):
  File "/home/oevans/local/miniconda3/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/home/oevans/local/miniconda3/lib/python3.5/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/oevans/local/miniconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-111>", line 2, in initialize
  File "/home/oevans/local/miniconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/oevans/local/miniconda3/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 306, in initialize
    self.init_shell()
  File "/home/oevans/local/miniconda3/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 322, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "/home/oevans/local/miniconda3/lib/python3.5/site-packages/traitlets/config/configurable.py", line 404, in instance
    inst = cls(*args, **kwargs)
  File "/home/oevans/local/miniconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 483, in __init__
    self.init_readline()
  File "/home/oevans/local/miniconda3/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 435, in init_readline
    self.refill_readline_hist()
  File "/home/oevans/local/miniconda3/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 477, in refill_readline_hist
    stdin_encoding))
ValueError: embedded null character

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

- - - - - - - - - -

Any help would be appreciated.

Thanks,
Oliver Evans

**Comment by takluyver** [comment]
You can probably work around this by moving/removing `~/.ipython/profile_default/history.sqlite`.

**Comment by minrk** [comment]
I guess the history got corrupted somehow. Maybe a None got in somewhere (@takluyver)?

You can move the old history out of the way:

    mv ~/.ipython/profile_default/history.sqlite ~/.ipython/profile_default/history.bad.sqlite

and we can try to figure out what weird stuff got in there afterward.

**Comment by takluyver** [comment]
I think it means there is a null byte (`\x00`) in one of the strings saved to the database, and when we try to pass that to readline, it is not a happy bunny.

**Comment by minrk** [comment]
I'm guessing you will see something a little weird if you do:

```
import os
from IPython.core.history import HistoryAccessor
# or wherever you have moved the history file that's misbehaving
hist_file = os.path.expanduser('~/.ipython/profile_default/history.bad.sqlite')
hist = HistoryAccessor(hist_file=hist_file)
for row in hist.get_tail():
    print(row)
```

**Comment by minrk** [comment]
Yeah, I'm just wondering how it got there. I was thinking there might be a None or an empty string in there, which we could definitely handle.

**Comment by OliverEvans96** [comment]
It worked! Moving the history file out of the way worked perfectly. After moving the history file, I ran the code that minrk posted, and I got:

--
(274, 107, 'a')
(274, 108, 'a[where(a==array(None))]=0')
(274, 109, 'a=array(a)')
(274, 110, 'a[where(a==array(None))]=0')
(274, 111, 'a')
(274, 112, 'a=[2,45,None,5,-2,None,3,5,1,nan]')
(274, 113, 'a[where(a==array(None))]=0')
(274, 114, 'a=array(a)')
(274, 115, 'a=array([2,45,None,5,-2,None,3,5,1,nan])')
(274, 116, 'a[where(a==array(None))]=0')
--

Which seems to be either the last few commands I ran before killing my stuck process. I was doing some funny stuff trying to find None values in a numpy array. Could one of these lines have caused the issue?

Thanks so much for the quick and helpful replies!

**Comment by takluyver** [comment]
None of those look like the problem. If you haven't entered anything private into IPython, can you repeat that with a number like `hist.get_tail(1000)` to dump out the last 1000 entries from your history? It will be a lot of output, so don't paste it all in here, but make a gist or email one of us a text file.

**Comment by OliverEvans96** [comment]
It turns out that I've accidentally deleted the history file, so I suppose we'll never know exactly how I did it. Thanks for the support!

**Comment by takluyver** [comment]
No problem.

@minrk should we catch ValueError for this? This doesn't seem to be a case that comes up very often, but failing-to-start bugs are a pretty major annoyance.

**Comment by minrk** [comment]
@takluyver yeah, let's catch ValueError, and try to include what we were trying to load in a warning, so we can maybe fix the source of the bug the next time it comes up.

**Comment by takluyver** [comment]
In fact we already wrapped it in a try block to catch this, but last time we saw it as a TypeError (maybe a Python 3/2 difference). We also didn't think to issue a warning.

**Comment by BoscoJohnson2001** [comment]
listdir: embedded null character in path
please help me
