### ISSUE TITLE
Renaming a file after specifying an existing name fails the second time and results in potential loss of data.

### ISSUE THREAD

**Issue by arunk054** [ipython/ipython#9330]
Hi..

I just started using IPython Notebook and found this issue. When I hit the Rename button from the drop down menu and enter a name that already exists, it shows up a dialog box with a message that says something like the file already exists. So far so good. But when I close the dialog box and try to enter a different name, it won't take characters that are keyboard shortcuts - such as -'d' or 'c', and even worse, when i hit these characters in the File Rename Textbox, the shortcuts are actually being operated on the notebook while my cursor is still in the text box. For example, if I hit 'd' twice in the textbox, a cell gets deleted in the background, which almost gets unnoticed until you close the textbox and you risk losing data. Although this is a not a frequent issue there is high risk of losing data if someone encounters it.

Following are the steps to reproduce this issue.

1. Create a notebook in a directory, say file1.ipynb.
2. Now in the same directory create a second file say - file2.ipynb.
3. Open the second file and create a few cells and then click File->Rename.
4. Type the name of the first file in the text box that appears, without the file extension. For e.g. file1.
5. A pop-up appears saying file already exists. Press OK.
6. You are now back in the text box to type in a new name. Start using characters that are your Notebook keyboard shortcuts such as 'd' or 'c'. BAM! none of these characters can be used in the text book. 
7. The worst part is if you typed 'd' twice or more, you are going to have one or more of your cells in the file deleted. Close the dialog box clicking cancel only to find your cells deleted or some other strange thing that happened while you were trying to rename the file.

**Comment by minrk** [comment]
What version of the notebook (Help > About)? I think this might already be fixed.

**Comment by arunk054** [comment]
Thanks for looking into this. Yes, you are right I was using an older version and I just updated to Jupyter version 4.1.0 and I don't see that issue. Thank you for taking the time to look into this. I will close this issue now. I guess the next time when I report an issue I will make sure I am always running  the latest version.
