### ISSUE TITLE
Auto-rewrite when autocall is on miscomputes the number of dashes to print and then messes output prompt positioning

### ISSUE THREAD

**Issue by fperez** [ipython/ipython#9331]
Not sure what logic is doing this under the hood, but the problem is pretty obvious:

```
In [1]: autocall 
Automatic calling is: Smart

In [2]: print 1
-> print(1)
1

In [3]: print 1
------------> print(1)
1

In [4]: print 1
-----------------------> print(1)
1
```
On each successive call, more and more dashes get printed (and they aren't the right number even on the first call).  This is certainly a new bug, though I haven't bisected it yet.

Furthermore, once this has happened, the output prompt ends up mis-positioned:

```
In [10]: 3
  Out[10]: 3
```

My `sys_info`:

```
In [9]: print(sys_info())
{'commit_hash': 'aa586fd',
 'commit_source': 'repository',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/fperez/dev/ipython/ipython/IPython',
 'ipython_version': '5.0.0.dev',
 'os_name': 'posix',
 'platform': 'Darwin-15.3.0-x86_64-i386-64bit',
 'sys_executable': '/Users/fperez/usr/conda/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, '
                '11:24:55) \n'
                '[GCC 4.2.1 (Apple Inc. build 5577)]'}
```

**Comment by takluyver** [comment]
Probably related to the prompt_toolkit work, as that has disconnected rewrite prompts from input prompts. See also: #9282.

**Comment by takluyver** [comment]
Surprisingly, it looks like it was not the prompt_toolkit work but #8738 that broke this. Interim fix coming up...
