### ISSUE TITLE
why x is changed in the following program?

### ISSUE THREAD

**Issue by charbit** [ipython/ipython#9334]
from numpy import random

x=random.randn(6)
y=x
y[0]=12
print x[0]

**Comment by takluyver** [comment]
This is not an IPython question - you might want to ask on something like the [learnpython subreddit](https://www.reddit.com/r/learnpython).

However, to answer your question, after you do `y=x`, x and y are two references to the same numpy array. You modify that array using one name and then inspect it using the other, but there's only one array.

If you want y to be an independent copy of that array, so you can change it without affecting x, there's a `.copy()` method:

```
In [1]: import numpy

In [2]: x = numpy.random.randn(6)

In [3]: x
Out[3]: 
array([ 0.97741694, -0.81160099,  1.46948424, -0.09586381, -0.59421026,
       -0.26812574])

In [4]: y = x.copy()

In [5]: y[0] = 12

In [6]: x[0]
Out[6]: 0.97741694212621588

In [7]: y
Out[7]: 
array([ 12.        ,  -0.81160099,   1.46948424,  -0.09586381,
        -0.59421026,  -0.26812574])
```

**Comment by charbit** [comment]
thanks you 
I did not know that y=x is not an independent copy.

best regards


Maurice Charbit
Emeritus Prof.
mob.: 33 (0)6 5230 1171
tel.: 33 (0)1 4581 7178
fax:  33 (0)1 4581 7144
maurice.charbit@telecom-paristech.fr <mailto:maurice.charbit@telecom-paristech.fr>
Adresse:
Institut Mines-Telecom,
46, rue Barrault, 75014 Paris
