### ISSUE TITLE
HTML vs Iframe

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9343]
I was again the witness of people miss-using HTML to display IFrames, and having issues. 

Could we detect in  HTML the usage of `<iframe>....</iframe>` and warn user that there is an iframe object ?

**Comment by takluyver** [comment]
What issues does that cause?

**Comment by Carreau** [comment]
> What issues does that cause?

Mostly people having issues getting the html right (width, height), url escaping, and remove the frameborder. The exact reason why we have an IFrame object.

**Comment by lesley2958** [comment]
could you say a bit more on the issue? maybe produce an example of when this comes up?

**Comment by takluyver** [comment]
The suggestion is to warn when someone is doing this:

```python
from IPython.display import HTML
HTML('<iframe src="..."></iframe>')
```

Instead of this:

```python
from IPython.display import IFrame
IFrame('...')
```

I'm still not convinced that it's worth it, though. A warning is going to be annoying if you do need to put an iframe in HTML, or if the display object is being made by code someone else wrote which you don't want to go and change.

**Comment by JhonnyBillM** [comment]
Hey! I would like to help with this issue.

**Comment by mpenkov** [comment]
This looks like a good first issue. I'll work on this for hacktoberfest.

**Comment by Carreau** [comment]
@meeseeksdev[bot] tag hacktoberfest

**Comment by Carreau** [comment]
Hummm

@meeseeksdev[bot] tag Hacktoberfest

**Comment by ProximaDas** [comment]
Hello! If nobody is working on this, can I pick it up?

**Comment by mpenkov** [comment]
@ProximaDas There's a small change I need to push to close this, otherwise, the task is done.

**Comment by ProximaDas** [comment]
Ah, got it thanks for letting me know!
