### ISSUE TITLE
Math Renderer Issue

### ISSUE THREAD

**Issue by Dulcius75** [ipython/ipython#9347]
I changed the math renderer to MathML through right-clicking on an equation in my notebook, however my browser did not support it and now will not output any equations. Therefore, I am trying to change it back to HTML-CSS but there is now no equations to right-click on in order to change the renderer. Is there a place in the browser which I can select the renderer? I am using Chrome on Windows and IPython version 4.0.3

**Comment by Dulcius75** [comment]
I found out that clearing the cache fixes the issue, unsure of how to delete this. Sorry for the clutter

**Comment by takluyver** [comment]
We disabled the menu where you can select that in jupyter/notebook#1036, because we don't ship all of the pieces MathJax needs to create every output format.
