### ISSUE TITLE
Syntax for getting shell output as a string

### ISSUE THREAD

**Issue by Chiel92** [ipython/ipython#9353]
In the IPython shell, we have a distinguishing syntax for having output returned as a string or as a list.
I'm not sure about the usecase of the latter in its current form, but it appears to exist.

```ipython
In [5]: !echo asdf
asdf

In [6]: !!echo asdf
Out[6]: ['asdf']
```

Could we introduce this syntax for assignment as well?
I.e. like

```ipython
In [7]: test = !echo asdf
In [8]: print(test)
asdf

In [9]: test = !!echo asdf
In [10]: print(test)
['asdf']
```

This would make things concise and consistent. Also, the current way of obtaining a string from a bash command is

```ipython
test = !echo asdf
test = LSString(test.n)
```

Not only does this need two lines of code instead of one, it also has performance overhead for unnecessary splitting and joining the output.

**Comment by takluyver** [comment]
I'm pretty sure that the performance overhead of splitting and joining a Python string is negligible compared to that of shelling out to bash. I don't think we want to introduce more special syntax, and to be honest, I didn't even remember that `!!` existed, and I work on that code.

**Comment by Carreau** [comment]
I'm going to side with Thomas on that one, and you can already use `test.s` to get the string, and as SList inherit a list you can also just use it as is, or use `list(test)`

**Comment by Carreau** [comment]
Closing, feel free to keep asking questions, we can reopen if needed.
