### ISSUE TITLE
tab completion in ipython and show output on browser

### ISSUE THREAD

**Issue by wangdelp** [ipython/ipython#9355]
How do I use tab completion in ipython notebook? When press tab, it will jump to another cell instead of completing the command. 

Another issue: I'd like to show output on the ipython notebook browser, but it always show on the background terminal serving the notebook. What additional configuration do I need to set? 

Thank you.

**Comment by takluyver** [comment]
What are you doing? Both of those things should work by default.

**Comment by wangdelp** [comment]
@takluyver the tab completion never worked for me. For the output, it it showing on browser on one machine that I setup, but on the other, do not know why it is showing in the background terminal.

**Comment by takluyver** [comment]
What OS and Python version?

What are you trying to tab complete? Can you give an example of something you expect to work that doesn't?

**Comment by wangdelp** [comment]
@takluyver I am on cenos os: Linux version 3.10.0-229.7.2.el7.x86_64 (builder@kbuilder.dev.centos.org)
Python 2.7.11 :: Anaconda custom (64-bit)

I am trying to tab complete variable names and commands in ipdb interactive input box. 
For example, when I want to tab complete "var_name" variable by typing "var" in the ipdb input box and press tab, it will jump to other cells.

After I type the full "var_name", and hit enter, the variable value does not show up in the notebook in browser, but show up in the background terminal. 
Thank you.

**Comment by takluyver** [comment]
Ah, OK, now I understand.

1. There is no tab completion in the debugger input box. We're well aware
of that, but the architecture makes it hard to provide completions.

2. The output thing is a bug in ipdb, but I think it already got fixed.
Check that ipdb is up to date, and search the issues on ipdb (it's a
separate project, but also on github)

**Comment by Carreau** [comment]
Closing as this should now be part of Notebook/Lab. and there is not much to do right now. 
Thanks.
