### ISSUE TITLE
Confirm-on-exit broken on master

### ISSUE THREAD

**Issue by fperez** [ipython/ipython#9359]
This is a regression introduced by the new ptshell code, specifically [here](https://github.com/ipython/ipython/blob/master/IPython/terminal/ptshell.py#L260). It should honor the standard `c.TerminalInteractiveShell.confirm_exit = True` flag in `ipython_config.py`.

Pinging @takluyver...

**Comment by fperez** [comment]
The [equivalent code](https://github.com/ipython/ipython/blob/master/IPython/terminal/interactiveshell.py#L789) in `InteractiveShell` checks the `confirm_exit` flag.

**Comment by takluyver** [comment]
Thanks, #9360 should fix this.
