### ISSUE TITLE
ipython notebook CSS not loading

### ISSUE THREAD

**Issue by ShandyYS** [ipython/ipython#9364]
I have tried the way what #6910 said:

> Start regedit and search for application/css in HKEY_CLASSES_ROOT. Replace it with text/css.

but the problem still exist as before.

And the console of firefox showed like this:
(I am sorry that if you have problem with the Chinese,but I think it doesn't matters a lot)

![qq 20160329042541](https://cloud.githubusercontent.com/assets/18125765/14089213/534f15fa-f566-11e5-8b60-c068da5c7e42.png)

And my page looked like this in ALL the browsers:

![qq 20160329042923](https://cloud.githubusercontent.com/assets/18125765/14089499/be8aa9f0-f567-11e5-945c-528832044f49.png)

**Comment by ShandyYS** [comment]
And my page looked like this in ALL the browsers:
![qq 20160329042923](https://cloud.githubusercontent.com/assets/18125765/14089314/ebe598c0-f566-11e5-98f5-675438affaaf.png)

**Comment by takluyver** [comment]
Can you try:

```python
import mimetypes
mimetypes.guess_type('foo.css')
```

**Comment by ShandyYS** [comment]
Thank you for replying!!

It's my first to use python.  Hope what I did is right:

![qq 20160329043654](https://cloud.githubusercontent.com/assets/18125765/14089571/17eb2920-f568-11e5-8926-3f38375cbf0c.png)

**Comment by takluyver** [comment]
OK, that looks correct. If you haven't already done it since you edited the registry, restart your computer to see if that makes a difference.

**Comment by ShandyYS** [comment]
OMG!! After doing above, the page is normal in Firefox now.  But in Chrome still wrong.

BTW, I have restart my computer several times after I change the registry, before asking.....

I think something magic happened after typing the codes you gave me.

I'll try restart again to see if Chrome could go back to normal.

Thank you very much!!!

**Comment by takluyver** [comment]
That sounds like a browser caching issue - after changing the registry, it's starting to work as something cached in the browser expires and is fetched again.

**Comment by ShandyYS** [comment]
After cleaning the caches of the browser, all the things go back to normal.
 I have been stuck in this problem for hours.

Thank you again!
