### ISSUE TITLE
missing diacritical mark after latex completion.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9376]
`F\dot<tab>` display `F` instead of `Ḟ` in cli, the dot is only missing visually. 

![diacritical](https://cloud.githubusercontent.com/assets/335567/14322936/735febd0-fbd3-11e5-99e0-08f633d74300.gif)

Ping @jonathanslenders , @takluyver

**Comment by takluyver** [comment]
From my brief experiments, this appears to display incorrectly in prompt_toolkit (I can see the same issue when I enter it with copy and paste, so it's not specific to our completion machinery). Plain `input()` in Python shows it as expected.

**Comment by jonathanslenders** [comment]
This should be a bug in Python:
```
In [2]: a='F'

In [3]: a
Out[3]: 'Ḟ'

In [4]: for c in a:
   ...:     print(c)
   ...:     
F
```

When iterating through this special character, it removes the dot...

**Comment by Carreau** [comment]
it does not remove it for me, it prints it on the next line:
```
In [7]: for c in a:print(c)
F
 ̇
```

**Comment by takluyver** [comment]
So, just for extra confusion, there are two ways to store the same symbol:

* `Ḟ` : decomposed, two characters
* `Ḟ` : composed, one character

PT appears to be fine with the composed character, but fall over with the decomposed one. This is true for me in ptpython as well as in IPython master.

**Comment by jonathanslenders** [comment]
@Carreau: For me too, it should probably print it on the next line. (I only see whitespace, but I guess my terminal doesn't understand a separate dot.

@takluyver: Yeah, I just noticed. They are not the same F:

[python35] > hexdump wrong-f
0000000 b8e1 009e                              
0000003
jonathan @ arch-jonathan : /tmp
[python35] > hexdump correct-f
0000000 cc46 0087                              
0000003

Let me think how to solve this. Is there a way to convert decomposed characters into one composed character?

**Comment by jonathanslenders** [comment]
I guess the reason that the dot is invisible in the prompt itself, is because prompt-toolkit didn't understood decomposed characters, and handles it as two individual characters. Then wcwidth tells us that the single dot has a width of 0, causing it to be hidden.

**Comment by takluyver** [comment]
Where there is a composed equivalent, yes:

```
unicodedata.normalize('NFC', 'Ḟ')
```

**Comment by takluyver** [comment]
(Github/my browser doesn't seem to display the decomposed form correctly either... unicode is hard!)

**Comment by jonathanslenders** [comment]
Fixed in the pull request above. It merges/composes the character and the dot before inserting it in the buffer. I think, this is the only right thing to do, because cursor movement, length calculations, etcetera are very hard to do on decomposed characters. I made another commit to prompt-toolkit itself to visualise the decomposed parts, if for some reason they end up in the input buffer. (They shouldn't.) But this should help debugging similar issues in the future: https://github.com/jonathanslenders/python-prompt-toolkit/commit/0f7213a434ceec81d48f93901d08e9b205665ea1

**Comment by jonathanslenders** [comment]
Actually, scary because in a normal Python shell ``\delta`` and ``\delta\dot`` visualise the same, but are different variables. The second is actually not even possible, because it doesn't merge after normalizing and the dot remains invisible.

**Comment by jonathanslenders** [comment]
FYI: the latest master commit of prompt-toolkit should handle the display of decomposed characters. Cursor movement (if you go backwards) is interesting. It's possible to insert characters in between the two unicode parts, making the double dot move from one character to the next. Also, the first backspace press will delete the double dot, the next backspace will delete the actual character. The same for delete. I'm not sure whether this has to be fixed, or whether it's actually a good thing.

By the way, my last patch for IPython would not necessarily be needed anymore after a new prompt-toolkit release.

**Comment by jonathanslenders** [comment]
This stackoverflow answer contains many decomposed unicode characters. Everything seems to work fine now.
http://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags
![unicode](https://cloud.githubusercontent.com/assets/216638/14344666/4e93bbca-fca9-11e5-856b-bd9ab94fdc10.png)

**Comment by takluyver** [comment]
Nice, thanks!

I'm honestly not sure what's the right behaviour for editing with decomposed characters. It looks like readline treats the combination as if it were a single character, so you can't manipulate the pieces separately. Maybe that's closer to what a user naively expects? But it's also more confusing when you're trying to work out what's going on...

**Comment by Carreau** [comment]
This works for me now. Closing as solved.

**Comment by randy3k** [comment]
<img width="545" alt="screen shot 2018-06-05 at 1 53 02 pm" src="https://user-images.githubusercontent.com/1690993/40993514-ce031568-68c7-11e8-9a49-4f46a68389de.png">

```
'你̂好̄嗎̃'
```

iTerm 2 v3.1.6beta on macOS 10.13.4
