### ISSUE TITLE
object.__sub<tab> does not propose __subclasses__ as tab-completion

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#9381]
All's in the title.

Probably something to do with being defined on the metaclass, and not that important I guess...

**Comment by takluyver** [comment]
It's possible that the work @liukelly and @Carreau are doing on using Jedi completions will improve this, but I'm not sure.

**Comment by srinivasreddy** [comment]
I tested this on master,

`In [1]: object.__subclasshook__`

that is what i received. I think we can close this issue. @takluyver

**Comment by Carreau** [comment]
> I tested this on master,
> 
> In [1]: object.__subclasshook__
> 
> that is what i received. I think we can close this issue.

Indeed, thanks. Closing.
