### ISSUE TITLE
Different order in sys.path list after importing pkg_resources in __init__.py

### ISSUE THREAD

**Issue by dprada** [ipython/ipython#9383]
I am not sure this is a bug or a problem of ipython, but it affects ipython users.
The problem in ipython appears after importing `pkg_resources` from setuptools 20.6.7 (ipython: `__init__.py` <-- `embed.py` <-- `Ipython.core.interactiveshell` <-- `pickleshare` <-- `path` <-- `pkg-resources`) [ipython 4.1.2 installed through conda 4.0.5]

That is why I think it is worth reporting here also the following issue:
https://github.com/pypa/setuptools/issues/538

**Comment by takluyver** [comment]
Myeh, once again setuptools messes stuff up.

We control pickleshare, so I'm going to have a go at switching from path.py to pathlib, which is in the stdlib in Python 3.

**Comment by takluyver** [comment]
OK, released a new version of pickleshare that doesn't use path.py. There's some more issues to fix, but those are after-lunch issues!
