### ISSUE TITLE
misspellings in class TimeitResult docstring

### ISSUE THREAD

**Issue by zymbolic** [ipython/ipython#9384]
Currently, the docstring of TimeitResult in IPython/core/magics/execution.py reads:

```
Object returned by the timeit magic with info about the run.

Contain the following attributes :

loops: (int) number of loop done per measurement
repeat: (int) number of time the mesurement has been repeated
best: (float) best execusion time / number
all_runs: (list of float) execusion time of each run (in s)
compile_time: (float) time of statement compilation (s)
```

"Execution" and "measurement" are both misspelled, and the description text of loops and repeat could should use "loops" and "times" respectively. Here's what a better version might look like

```
Object returned by the timeit magic with info about the run.

Contains the following attributes :

loops: (int) number of loops done per measurement
repeat: (int) number of times the measurement has been repeated
best: (float) best execution time / number
all_runs: (list of float) execution time of each run (in s)
compile_time: (float) time of statement compilation (s)
```

**Comment by takluyver** [comment]
Thanks, want to make a pull request?

**Comment by zymbolic** [comment]
This is my first time contributing on Github, so I hope everything is OK. This is a very small change which does not affect functionality whatsoever

I created a branch which contains an updated docstring here: https://github.com/zymbolic/ipython/tree/timeit_spelling

If everything looks good I will create a pull request

**Comment by takluyver** [comment]
Looks good to me :)

**Comment by damianavila** [comment]
#9386 was merged... this should be closed.

**Comment by takluyver** [comment]
Yep, thanks @damianavila
