### ISSUE TITLE
Turning off %matplotlib inline (feature request)

### ISSUE THREAD

**Issue by akhmerov** [ipython/ipython#9389]
Apologies if I'm just missing it in the docs.

Currently, (IPython v4.2) it doesn't seem possible to undo calling `%matplotlib inline` if one doesn't want to revert to an interactive backend (one can only switch between different interactive backends). The reason why I believe it is useful to sometimes switch to a non-interactive backend is a combination of:
* Proliferation of using `pyplot` as the plotting interface used by libraries
* Lack of end-user control over which figures get plotted if the figures are created using `pyplot.figure`

If it was possible to have an IPython analog of `matplotlib.use('agg')`, the end user would always have control over which figures are plotted.

**Comment by minrk** [comment]
I don't think it's you, I think we just haven't thought of this. We could make `%matplotlib arg`, for instance. I'm not sure it would do anything other than call `matplotlib.use('agg')`, though.

**Comment by akhmerov** [comment]
Just calling `matplotlib.use('agg')` doesn't switch off the effects of `%matplotlib inline`. I didn't dive into the source, but I assume the inline backend is based on agg and adds some jupyter-specific post-processing (keeping track of created figures and showing them).

**Comment by fperez** [comment]
Indeed, there's a few specific hooks that get added.  If you dig a bit into the code, it should be easy to add a `%matplotlib off` call that unregisters the post-processing to leave things back the way they were before (other than obviously matplotlib having been imported).

It should be clear that this can't undo global actions like initializing a GUI event loop, but it could help some valid use cases...

Care to make a PR?

**Comment by akhmerov** [comment]
> Care to make a PR?

Looked at the code, and the amount of involved machinery is beyond something I can understand and modify within reasonable time, sorry.

Overall IPython here doesn't behave more irreversible than matplotlib itself, so obviously it's not an important issue.

**Comment by tacaswell** [comment]
You can kill off any existing event loops and de-register the `PyOS_INPUTHOOK`.
