### ISSUE TITLE
How to store error messages in `output_history` table inside `history.sqlite`?

### ISSUE THREAD

**Issue by AnushS4t1qbit** [ipython/ipython#9396]
I set `HistoryManager.db_log_output` to `True` in `ipython_config.py`, but I was hoping that error messages would be stored in the `output_history` table as well. Is there any way of doing that?

cc: @takluyver

**Comment by takluyver** [comment]
There is not. Only the 'result' of a cell - the return value from an expression on the last line - is recorded as output in the database.

**Comment by AnushS4t1qbit** [comment]
I see. Thanks.
