### ISSUE TITLE
infinite exception handling loop in case of corrupt SQLite3 db

### ISSUE THREAD

**Issue by dwf** [ipython/ipython#9412]
Traceback here: https://gist.github.com/dwf/c659fdd50285b5a4885c10acc34b77e7

Version 4.1.2 installed via conda.

~~If anyone has a workaround it would be much appreciated.~~ I've worked around it by setting `IPYTHONDIR`, but it seems like this could be handled a bit more gracefully somehow.

**Comment by dwf** [comment]
I should note that somehow removing `~/.ipython` doesn't fix it, which is distressing.

**Comment by dwf** [comment]
One other detail: `/u/wardefar` is a shared NFS home directory. In the past I've seen this problem fixed by having the machine rebooted, but I don't have physical access to it so this is a big impediment.

**Comment by dwf** [comment]
So I just happened upon [this](https://github.com/ipython/ipython/blob/af1c39e08f1c395b947fb3663249549eabbbbe1d/IPython/core/history.py#L137-L142) with some help from our local IT guys, so I guess it's a known failure case. I wonder whether anything can be done to short-circuit the ridiculous traceback I got and *maybe* point the user in the right direction a little quicker.

**Comment by takluyver** [comment]
Hi @dwf! Yep, SQLite plus NFS is a known failure case - unfortunately I don't know of a good way to detect that situation. You're right that this shouldn't be infinitely recursing, though - if moving the database and recreating it once doesn't help, it should probably just disable persistent history entirely and show a warning.

**Comment by minrk** [comment]
Note that's plus *certain NFS configurations/implementations*. I've used IPython on an NFS filesystem for many years without issues. Unfortunately, I have no idea what the actual problem would be.

You can set just the history file in your `ipython_config.py`:

    c.HistoryAccessor.hist_file = '/path/to/local-scratch/ipython-history.sqlite'

I don't think we can detect NFS reasonably, but I think we *can* detect multiple failures of init_db in a row, and fallback to in-memory (no persisted history).

**Comment by dwf** [comment]
> Note that's plus certain NFS configurations/implementations. I've used IPython on an NFS filesystem for many years without issues.

Ditto. Not sure what changed about our configuration recently.

**Comment by minrk** [comment]
#9418 cuts off the infinite retries (at 2) and falls back to :memory: in that case.

**Comment by allanruin** [comment]
I just want to say I have been using jupyter/ipython for years on a cluster that share a NFS storage without problems. However, after some power off accidentally, all ipython in cluster machines are broken due to NFS sqlite issue. I cannot open previous notebooks , and cannot create new ones.
 I upgraded ipython to 5.1.0, at least the sqlite db issue get detected and switch to memory db. 
I was amazed by sqlite db locking issue appearin just after a reboot. Orz

**Comment by Carreau** [comment]
Sorry about that. We should find a better way but that is relatively hard without a massive refactoring.
Do you still have problems ? Because opening notebooks should be unrelated to IPython itself. The notebook might be using a DB though, and this one you should be able to configure.

**Comment by allanruin** [comment]
@Carreau  Thank you for your quick reply, ipython is a excellent tool, I really appreciate your effort.

For future comecrossers, if you are using anconda's jupyter/ipython, and find that you cannot open previous notebooks as well as not able to create new notebook, then is not cause only by the ipython configurations. For example, 

`
[E 10:27:54.767 NotebookApp] Error while saving file: Untitled.ipynb database is locked
    Traceback (most recent call last):
      File "/data/home/zrc/anaconda2/lib/python2.7/site-packages/notebook/services/contents/filemanager.py", line 387, in save
        self.check_and_sign(nb, path)
      File "/data/home/zrc/anaconda2/lib/python2.7/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/data/home/zrc/anaconda2/lib/python2.7/site-packages/nbformat/sign.py", line 246, in sign
        self.store_signature(signature, nb)
      File "/data/home/zrc/anaconda2/lib/python2.7/site-packages/nbformat/sign.py", line 249, in store_signature
        if self.db is None:
      File "/data/home/zrc/anaconda2/lib/python2.7/site-packages/traitlets/traitlets.py", line 439, in __get__
        value = self._validate(obj, dynamic_default())
      File "/data/home/zrc/anaconda2/lib/python2.7/site-packages/nbformat/sign.py", line 127, in _db_default
        self.init_db(db)
      File "/data/home/zrc/anaconda2/lib/python2.7/site-packages/nbformat/sign.py", line 139, in init_db
        )""")
    OperationalError: database is locked

`
above log is cause by ipython, which is unable to lock sqlite file.

however, below error is cause by jupyter that is not able to lock `nbsignatures`.
`
The signatures database cannot be opened; maybe it is corrupted or encrypted.  You may need to rerun your notebooks to ensure that they are trusted to run Javascript.  The old signatures database has been renamed to /data/home/zrc/.local/share/jupyter/nbsignatures.db.bak and a new one has been created.
No answer for 5s: resuming operation...
[W 14:46:29.996 NotebookApp] Failed commiting signatures database to disk.  You may need to move the database file to a non-networked file system, using config option `NotebookNotary.db_file`.  Using in-memory signatures database for the remainder of this session.

[IPKernelApp] ERROR | Failed to open SQLite history :memory (database is locked).
[IPKernelApp] ERROR | History file was moved to :memory-corrupt and a new file created

`
to solved the problem,  you need to find your jupyter_notebook_config.py.(if you do not have such config file, generate it with **jupyter notebook --generate-config**, generally it will be inside ~/.jupyter/  directory),
and change the `**NotebookNotary.db_file** ` to a local filesystem path(etc, /tmp/xxx-signatures)

then everything will be fine again.

**Comment by takluyver** [comment]
Thanks for the defaulted follow up. For reference, the next version of nbformat is going to add a pluggable SignatureStore. The default will still be sqlite, but it should be easier to tell it to use another database for recording trusted notebooks.

**Comment by lamipaul** [comment]
Hi, 
I am stuck on the same issue with SQLITE3 and ipython with a home directory on a nfs
I am looking for a way to work around this issue
@dwf when you say setting the IPYTHONDIR, doing you mean running `export IPYTHONDIR='~/.ipython'` ? 
does anyone else have a quick workaround ? 

Thanks a lot !

**Comment by dwf** [comment]
I mean set `IPYTHONDIR` to a directory *not* on NFS, e.g. `export IPYTHONDIR=/tmp/$(whoami)/.ipython`.
