### ISSUE TITLE
Possible crash reporting 'French' OS error message

### ISSUE THREAD

**Issue by sylvain-bougnoux** [ipython/ipython#9413]
Hi, FYI possible crash with this error:
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 39: ordinal not in range(128)`

**Context**: I am running and external program through ipython; my external program crashed for some reason. As normal ipython caught this error, but while trying to report it, ipython crashed as well. It seems to be due to the tentative to create a string (str) from a unicode one, ie including 'French' accents as reported by windows (see the string s below). 

I am runing python2.7, ipython 4.2, windows7.

Thanks

  ```
File "C:\Program Files (x86)\python27\lib\site-packages\IPython\core\interactiveshell.py", line 2902, in run_code
    self.showtraceback()

  File "C:\Program Files (x86)\python27\lib\site-packages\IPython\core\interactiveshell.py", line 1830, in showtraceback
    value, tb, tb_offset=tb_offset)

  File "C:\Program Files (x86)\python27\lib\site-packages\IPython\core\ultratb.py", line 1392, in structured_traceback
    self.tb = tb

  File "C:\Program Files (x86)\python27\lib\site-packages\IPython\core\ultratb.py", line 1309, in structured_traceback
    elist = self._extract_tb(tb)

  File "C:\Program Files (x86)\python27\lib\site-packages\IPython\core\ultratb.py", line 640, in structured_traceback
    # The exception info should be a single entry in the list.

  File "C:\Program Files (x86)\python27\lib\site-packages\IPython\core\ultratb.py", line 752, in _format_exception_only
    list.append('%s%s:%s %s\n' % (str(stype), Colors.excName,

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 39: ordinal not in range(128)

In [166]: %debug
> c:\program files (x86)\python27\lib\site-packages\ipython\core\ultratb.py(752)_format_exception_only()
    750                 s = self._some_str(value)
    751             if s:
--> 752                 list.append('%s%s:%s %s\n' % (str(stype), Colors.excName,
    753                                               Colors.Normal, s))
    754             else:

ipdb> stype
 '\x1b[1;31mWindowsError\x1b[0m'

ipdb> Colors
{'em': '\x1b[1;36m', 'filenameEm': '\x1b[1;32m', 'excName': '\x1b[1;31m', 'valEm': '\x1b[1;34m', 'nameEm': '\x1b[1;35m', 'line': '\x1b[1;33m', 'topline': '\x1b[1;31m', 'name': '\x1b[0;35m', 'caret': '\x1b[1;37m', 'val': '\x1b[0;32m', 'vName': '\x1b[0;36m', 'Normal': '\x1b[0m', 'filename': '\x1b[0;32m', 'linenoEm': '\x1b[1;32m', 'lineno': '\x1b[0;32m', 'normalEm': '\x1b[1;36m'}

ipdb> print s
[Error 32] Le processus ne peut pas acc�der au fichier car ce fichier est utilis� par un autre processus
```

**Comment by minrk** [comment]
Can you install IPython 4.1 and see if you still have this problem? I suspect this is a regression in 4.2.

Also, if you use non-ascii text on Windows with any regularity, especially files, I would **strongly** recommend upgrading to Python 3 as soon as possible. Python 2 will never run out of problems with unicode, especially on Windows.

**Comment by minrk** [comment]
Installing latest IPython before 4.2:

    pip install 'ipython<4.2'

**Comment by minrk** [comment]
What are `type(stype)` and `type(s)`?

**Comment by minrk** [comment]
And what is the line of code you are running when this happens?

**Comment by sylvain-bougnoux** [comment]
Both are str
 
s is '[Error 32] Le processus ne peut pas acc\xe9der au fichier car ce fichier est utilis\xe9 par un autre processus'
Therefore the \xe9 char, seems unicode and is outside range(128).
You are right, I should move to python 3, but I will miss some packages.
Meanwhile this error/exception could be caught here to avoid the crash.
 
BTW, it does crash with 4.1.2
 
Thanks

**Comment by takluyver** [comment]
> You are right, I should move to python 3, but I will miss some packages.

What packages would you be missing? There are fewer and fewer I know of that don't support Python 3.

**Comment by minrk** [comment]
Don't worry, I'm not proposing that we shouldn't fix it (#9419 should do that). Just that unicode headaches are frequent on Python 2.

**Comment by sylvain-bougnoux** [comment]
J I was asking the same question to myself, maybe my former analysis is out of date nowadays.
Maybe wxPython, which is now Phoenix?
I will try to switch.

**Comment by takluyver** [comment]
Yeah, wxPython seemed to die before Project Phoenix really came to completion. I haven't heard anything about it for ages. There are some snapshot builds here you can try: http://wxpython.org/Phoenix/snapshot-builds/
