### ISSUE TITLE
Ctrl-C in pylab

### ISSUE THREAD

**Issue by memeplex** [ipython/ipython#9415]
I've reported this to bug-readline:

> > using readline  with ipython 4.1.2 and the TkAgg (or GTK3Agg)
> > backend for matplotlib, I observed the following behavior:
> > 
> > 1) open ipython in pylab mode (ipython --pylab or use the %pylab magic once
> > inside the repl).
> > 
> > 2) Type something.
> > 
> > 3) Press Ctrl-C: line edition is not aborted as expected.

And this was Chet answer:

> This is probably the result of the same signal handling issues as with
> SIGWINCH that we discussed a little more than a year ago.  Readline
> catches the signal, sets a flag, and, when it's safe, resends it to the
> calling application.  It expects that if the calling application catches
> SIGINT, it will take care of cleaning up the readline state.  Sometimes
> applications don't want to kill the current line on SIGINT.

Notice it doesn't happen with the Qt5Agg backend.

**Comment by takluyver** [comment]
We have moved away from readline in master, so hopefully this is no longer an issue.

**Comment by tacaswell** [comment]
Which mpl backend you are using should be unrelated to which version of readline you are using so that it works with qt5 is surprising.

This is probably related to the issue that resulted in https://github.com/ludwigschwardt/python-gnureadline/pull/47

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.  We no longer use `pyreadline` and have switched to [prompt_toolkit](http://python-prompt-toolkit.readthedocs.io/en/stable/) since [IPython 5.0](https://blog.jupyter.org/2016/07/08/ipython-5-0-released/). 

Happy hacking! :bowtie:
