### ISSUE TITLE
%aimport'ing multiple modules simultaneously

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#9430]
Minor usability issue: it would be nice if %aimport was able to take multiple space-separated (or whatever delimiter you can come up with) module names rather than having to input them one at a time.

**Comment by srinivasreddy** [comment]
I will take it

**Comment by saritasa** [comment]
c.InteractiveShellApp.extensions = ['autoreload']
c.InteractiveShellApp.exec_lines = ['%autoreload 2']
c.InteractiveShellApp.exec_lines = ['%aimport itertools']
c.InteractiveShellApp.exec_lines = ['%aimport collections']
c.InteractiveShellApp.exec_lines = ['%aimport functools']

inside ipython then only functools is pre-loaded, no itertools, collections though. 

```
Python 3.4.3 (default, Dec 21 2015, 18:37:58) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: dir()
Out[1]: 
['In',
 'Out',
 '_',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 '_sh',
 'exit',
 'functools',
 'get_ipython',
 'quit']

```

**Comment by srinivasreddy** [comment]
riased the PR here #10033

**Comment by srinivasreddy** [comment]
@Carreau let's close this. your PR https://github.com/ipython/ipython/pull/10049

**Comment by takluyver** [comment]
Thanks @srinivasreddy
