### ISSUE TITLE
magic-command %load removes my utf-8 encoding declaration.

### ISSUE THREAD

**Issue by qwertyjune** [ipython/ipython#9446]
Hi all,

I always declare utf-8 encoding #-*- coding: utf-8 -*- on the top of each python source.
But it is removed when I load my source to jupyter notebook by using magic command %load

I tried to find out if there is anything I could fix it, but couldn't.
Would someone advise if there is a way to fix it?
Thank you.

I am using the version below by the way.

The version of the notebook server is 4.2.0-d0fae57 and is running on:

Python 2.7.8 (default, May  7 2016, 15:26:50) 
[GCC 5.3.1 20160413]

Kind regards,
June

**Comment by takluyver** [comment]
Hi June, this is deliberate - because of the way Jupyter and IPython execute your code, it doesn't need an encoding declaration, and it can produce an error if one is found. So `%load` removes it from the code it loads. You should still be able to use non-ascii characters.

**Comment by srinivasreddy** [comment]
@Carreau can we close this, since above said behaviour is intentional? @takluyver

**Comment by takluyver** [comment]
Yup, thanks for the reminder.
