### ISSUE TITLE
Colored prompt for embed() no longer works

### ISSUE THREAD

**Issue by theherk** [ipython/ipython#9450]
In IPython==4.1.1 `embed()` leaves a colored prompt. But since upgrading to 4.2.2, no more colors. I don't know if this indicates anything more significant.

**Comment by takluyver** [comment]
Confirmed in 4.2.0, but the colours are back in master. Some of my early reorganisation to support the prompt_toolkit change may have broken this - sorry about that.

**Comment by theherk** [comment]
Great. Thanks for looking into it and providing more information, @takluyver.
