### ISSUE TITLE
LaTeX color should be white when background is dark

### ISSUE THREAD

**Issue by endolith** [ipython/ipython#9451]
[Change the color of Latex output in IPython (Jupyter)](http://stackoverflow.com/q/35539492/125507) has an example from SymPy:

![njbxw 1](https://cloud.githubusercontent.com/assets/58611/15131358/2ee91f44-161d-11e6-81af-35261137e365.png)

here is an example of Pint using MikTex:

![2016-05-09 19_34_24-spyder python 2 7](https://cloud.githubusercontent.com/assets/58611/15131371/41789d92-161d-11e6-81d0-05e200da10fc.png)

and using matplotlib (I think, since miktex is uninstalled):

![matplotlib](https://cloud.githubusercontent.com/assets/58611/15131665/f2a890a2-161f-11e6-9a61-adca926c8913.png)

[Control LaTeX expression color in ipython qtconsole](http://stackoverflow.com/a/18260452/125507) gives a workaround, but it only applies to SymPy, not other objects that define `_repr_latex_()`, and doesn't work for matplotlib backend.

Ideally the Latex would just be printed in the same color as the plain text.

**Comment by takluyver** [comment]
If IPython is sending Latex output to be rendered by the frontend, I think it's a Qt console issue. Pinging @ccordoba12 . If it's being rendered to an image in IPython before sending it, then it's up to whatever renders it how you configure that.

**Comment by bdaves12** [comment]
Any update to this?
