### ISSUE TITLE
cpaste magic command length limitations?

### ISSUE THREAD

**Issue by GregSilverman** [ipython/ipython#9454]
There seems to be either a limitation on number of lines or number of characters when pasting into `%cpaste`. I am trying to paste in a large method that keeps getting the formatting screwed up (looks like random missed carriage returns, etc.). I also had issues pasting in a string that was 100 columns by 200 rows, where similar bizarre things with the formatting happened  (I was able to use `%paste` as a workaround).  I am using IPython 4.1.2 on top of python 2.7.11.

Please let me know if you need any more information.

**Comment by takluyver** [comment]
In master, multiline paste now works without the cpaste magic, thanks to prompt_toolkit and the 'bracketed paste' standard. Hopefully this will also work better with large amounts of text.

**Comment by GregSilverman** [comment]
Thanks! Any idea why too many lines/large amounts of text get screwy with cpaste magic?

**Comment by takluyver** [comment]
Not really, but as I understand it pasting into a terminal without bracketed paste roughly emulates you typing all of the pasted content really fast. Maybe some data gets out of order or something. It may also depend on the terminal emulator you're using.

**Comment by GregSilverman** [comment]
I'm using iTerm... I just installed the version from master. Looks pretty nice, and indeed, I can paste in large amounts of text with no problems.

**Comment by takluyver** [comment]
Thanks!

**Comment by ivanov** [comment]
IPython 5 has been released, so I am closing this issue.
