### ISSUE TITLE
Document IPYTHON_SUPPRESS_ERRORS

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9493]
See  https://github.com/ipython/ipython/pull/9478/files

**Comment by takluyver** [comment]
Actually, I was so busy looking at the value of that env var that I forgot to think (bikeshed) about the name. 'IPYTHON_SUPPRESS_ERRORS' does not really represent what it is. So before we document it, can we rename it to something like `IPY_SUPPRESS_CONFIG_ERRORS`?
