### ISSUE TITLE
"ipython --matplotlib" prevents KeyboardInterrupt from being processed

### ISSUE THREAD

**Issue by ngoldbaum** [ipython/ipython#9495]
This is running on IPython 4.2.0 running under python 2.7.11 on OSX 10.11. In this example I'm hitting ctrl-c before typing "exit" at the the input prompt:

```
goldbaum at ROUS2 in ~
○ ipython --matplotlib
Python 2.7.11 (default, Jan 22 2016, 08:28:37)
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
Using matplotlib backend: MacOSX

In [1]: exit

KeyboardInterrupt

In [1]:
```

The KeyboardInterrupt isn't getting processed until after I type "exit".

**Comment by keflavich** [comment]
I brought this issue up on IRC, and @ngoldbaum was able to reproduce it, but after freshly installing ipython 4.2.0 from source under python 3.5.1 on OSX 10.9.5, I can no longer reproduce the issue.  It seems to reappear for me sporadically, given that I've reported it previously (https://github.com/ipython/ipython/issues/1157).

**Comment by Carreau** [comment]
>  It seems to reappear for me sporadically

Yes, I ran `python2 -m IPython --matplotlib osx` ~ 50 time, and I was able to see the behavior twice. 
So I'm leaning toward race condition.

**Comment by fperez** [comment]
Indeed, probably a race condition. I haven't looked at the GUI integration code in ages... These are very hard to track down without a solid way to reproduce them, if anyone finds a way to force the problem to show up, please post.

**Comment by ngoldbaum** [comment]
@fperez it seems to happen every time I start IPython. Any suggestions for debug checks to see what's special about my environment?

**Comment by minrk** [comment]
@ngoldbaum which Python installation and how was matplotlib installed?

**Comment by ngoldbaum** [comment]
@minrk this is on the Python from homebrew. I installed matplotlib via pip, using the pip associated homebrew python.

**Comment by tacaswell** [comment]
Could this be related to the readline issues where it was not properly cleaning up on ctrl-c ?

**Comment by Carreau** [comment]
@ngoldbaum can you try with IPython 5.0.0b1 that was just sent out, I just retried ~20 time with it, and was not able to reproduce. 
If it's a readline thing, it should be gone now that we don't use readline anymore.

**Comment by ngoldbaum** [comment]
Hmm, in 5.0.0b1 it doesn't seem to process my Ctrl-C at all, i.e. `KeyboardInterrrupt` never gets printed, even after I type 'exit'.

**Comment by takluyver** [comment]
When an input prompt is active, Ctrl-C clears whatever you've typed in to the prompt, and will not show KeyboardInterrupt. When code is running, Ctrl-C should interrupt it as usual.

**Comment by ngoldbaum** [comment]
In that case everything appears to be working as expected under 5.0.0b1.

**Comment by Carreau** [comment]
> When an input prompt is active, Ctrl-C clears whatever you've typed in to the prompt, and will not show KeyboardInterrupt. When code is running, Ctrl-C should interrupt it as usual.

Should we print a BELL escape sequence on Ctrl-C if the prompt is empty as an indication it "works" ?

**Comment by takluyver** [comment]
I'm not sure it's that useful to BELL just to show we've handled it. This only came up because someone was testing something specific, and I don't think the lack of indication will be an annoyance normally.

**Comment by Carreau** [comment]
Fair enough.
