### ISSUE TITLE
Building a PyQt application which has ptpython as an embedded console pane

### ISSUE THREAD

**Issue by ws1088** [ipython/ipython#9508]
Hi, I am thinking of writing a PyQt application which has menu/widget etc, plus a python console dockable pane which allows user to type python code. Can I use ptpython on that dockable pane? If so that will be awesome!

**Comment by takluyver** [comment]
* Ptpython is a different project, see [here](https://github.com/jonathanslenders/ptpython/). However, IPython is now using the same library, prompt_toolkit, so they're quite similar.
* You could embed either of these into your application using a Qt terminal widget. I think there are some out there, but I haven't used any, so I won't recommend one.
* Alternatively, you could embed the [Jupyter Qtconsole](https://github.com/jupyter/qtconsole). This works in a very different way, but it still lets the user type in Python code and see the output. This is what [Spyder](https://github.com/spyder-ide/spyder) uses, for instance.
