### ISSUE TITLE
Figure out if we do a 4.3

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9509]
Just marking as 5.0 to remember to do that , and fix the 4.3 marked issues **before** doing a 5.0.

**Comment by Carreau** [comment]
Ok, I'm going to take a decision on this one and say "No".

**Comment by minrk** [comment]
Makes sense.

**Comment by cyn19** [comment]
Le vendredi 3 juin 2016, Min RK <notifications@github.com> a écrit :

> Makes sense.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ipython/ipython/issues/9509#issuecomment-223556573>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANrU_J5NZr0M2ujLJcL7NFcosll-3t4Cks5qIBFkgaJpZM4Io8u->
> .
>


-- 
Cynthia gaudreault
