### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'set_active_scheme'

### ISSUE THREAD

**Issue by MattDMo** [ipython/ipython#9512]
I'm running OS X 10.8.5 (yes, I know...) with a freshly-installed version of MacPorts Python 3.5.1. I used `sudo pip install ipython jupyter` to install IPython and Jupyter today (May 30, 2016). The output of `pip list`:
```
appnope (0.1.0)
backports.shutil-get-terminal-size (1.0.0)
cycler (0.10.0)
decorator (4.0.9)
entrypoints (0.2.2)
gitdb (0.6.4)
GitPython (2.0.5)
gnureadline (6.3.3)
ipykernel (4.3.1)
ipython (4.2.0)
ipython-genutils (0.1.0)
ipywidgets (5.1.5)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.2.2)
jupyter-console (4.1.1)
jupyter-core (4.1.0)
MarkupSafe (0.23)
matplotlib (1.5.1)
mistune (0.7.2)
nbconvert (4.2.0)
nbformat (4.0.1)
notebook (4.2.0)
numpy (1.11.0)
pandas (0.18.1)
pexpect (4.1.0)
pickleshare (0.7.2)
pip (8.1.2)
ptyprocess (0.5.1)
Pygments (2.1.3)
pyparsing (2.1.4)
python-dateutil (2.5.3)
pytz (2016.4)
pyzmq (15.2.0)
qtconsole (4.2.1)
readline (6.2.4.1)
setuptools (21.2.1)
simplegeneric (0.8.1)
six (1.10.0)
smmap (0.9.0)
terminado (0.6)
tornado (4.3)
traitlets (4.2.1)
widgetsnbextension (1.2.3)
```

When I try to run IPython notebook, through the console, or via Sublime Text's SublimeREPL, I get the error listed above. I turned on verbose logging in my `ipython_config.py` and produced the report [in this gist](https://gist.github.com/MattDMo/56c5e4f9cc00402a4e03e5044527517d) (I didn't want this bug report to be huge, but I can add it here if you want).

I honestly don't know what's going on. I haven't used this computer since last September-ish (I got a new one), but as I recall IPython was working just fine. I do have several other versions of Python installed via MacPorts, so I suppose that *could* potentially be an issue if they're not completely separated somehow. I haven't tried running in a virtualenv (I can if you want), but since this is a fresh install of 3.5.1 I'm not sure what good it would do. The (non-commented-out) contents of my `ipython_config.py` are as follows:

```py
c = get_config()
c.InteractiveShellApp.exec_lines = ["import numpy as np",
                                    "import pandas as pd",
                                    "from pandas import Series, DataFrame",
                                    "import matplotlib as mpl",
                                    "from pprint import pprint as pp",
                                    "def fixquote(): print('\"'*3)"]
c.InteractiveShellApp.gui = 'osx'
c.InteractiveShellApp.pylab = 'osx'
c.InteractiveShellApp.pylab_import_all = False
c.TerminalIPythonApp.gui = 'osx'
c.TerminalIPythonApp.pylab = 'osx'
c.TerminalIPythonApp.verbose_crash = True
c.TerminalInteractiveShell.colors = 'NoColor'
c.TerminalInteractiveShell.autoindent = True
c.TerminalInteractiveShell.editor = 'subl -w'
c.TerminalInteractiveShell.confirm_exit = False
c.PromptManager.color_scheme = 'NoColor'
c.PlainTextFormatter.pprint = False
c.IPCompleter.omit__names = 0
c.IPCompleter.limit_to__all__ = False
```

If you have any suggestions, I'm all ears. If you need anything else, please just let me know.

**Comment by takluyver** [comment]
Try commenting out this line:

```python
c.PromptManager.color_scheme = 'NoColor' 
```

I'd guess this is a bug in the order of initialisation. It's all too easy to get these with traitlets.

**Comment by MattDMo** [comment]
Wow, that did it! So if this is the issue, is there a way to set the console app to `NoColor`? I don't mind the colors, I was just wondering...

**Comment by takluyver** [comment]
There may not be a good way to do it from a config file, but if you need it, I might try doing it with a [startup file](http://ipython.readthedocs.io/en/stable/interactive/tutorial.html#startup-files). Those should be run after all the objects have been created, so you can get a reference to the shell object with `get_ipython()` and then set the things you need.

**Comment by MattDMo** [comment]
OK, thanks, I had forgotten about those. Do you want me to open an issue in ipython/traitlets so this can be tracked there?

**Comment by takluyver** [comment]
I think it is an IPython issue in that we're not using traitlets carefully enough - traitlets make it easy to run into this kind of thing, but that's down to the way they are. We can leave it open for now, but PromptManager is going away for 5.0, so if it doesn't get fixed by then, we'll close it.

**Comment by Carreau** [comment]
closing as PromptManager is gone now.
