### ISSUE TITLE
Warn if `PromptManager` options set. 

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9530]
PromptManager is unused,  but  it does not warn people if they use such config. 
Should we check in the right place whether `parent.config.get('PromptManager') is not None` and warn if its the case ?

**Comment by minrk** [comment]
Probably in Application, and the check probably ought to be:

```python
if 'PromptManager' in self.config:
```

**Comment by takluyver** [comment]
Matthias did in fact add such a check in #9531, albeit in InteractiveShell rather than Application.

**Comment by minrk** [comment]
Cool, I can't keep up with you guys!

**Comment by Carreau** [comment]
> Cool, I can't keep up with you guys!

I'm sure the two of us couldn't keep up what the 8 of you are doing alone.

**Comment by takluyver** [comment]
8? Has Simula cloned Min a few more times? ;-)

**Comment by Carreau** [comment]
I always assumes 
   - 1 Master Min(d)
   - 6 Clones, 
   - 1 Robot.
 
which total to 8.
