### ISSUE TITLE
Update build instructions.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9535]
swap the update of `__version__` with running the `build_release` as `build_release` in particular check that the version number is complient with pep440

**Comment by willingc** [comment]
@Carreau I'm wondering if we already did this.

Here are the two places that there are build instructions:

1. [IPython stable RTD](http://ipython.readthedocs.io/en/stable/coredev/release_process.html) - it looks like Step 4 has the `build_release` step and Step 5 mentions `_version_extra`.

2. [Consolidated Jupyter/IPython docs from old IPython wiki content](http://jupyter.readthedocs.io/en/latest/development_guide/releasing.html) - Looks like Step 2 has the `build_release` step.

Were you seeing `__version__` somewhere else?

**Comment by Carreau** [comment]
Yep, 1.:

Step 4:

> Running tools/build_release does all the file checking and building that the real release script will do. This makes test installations, checks that the build procedure runs OK, and tests other steps in the release process.

is meant to check the first half of step 5.

> Make sure the version number matches pep440, in particular, rc and beta are not separated by . or the sdist and bdist will appear as different releases. For example, a valid version number for a release candidate (rc) release is: 1.3rc1. Notice that there is no separator between the ‘3’ and the ‘r’.

So doing it **before** make no sens.

**Comment by willingc** [comment]
Will send a draft your way tomorrow @Carreau
