### ISSUE TITLE
IPython issue

### ISSUE THREAD

**Issue by hhsieh** [ipython/ipython#9536]
Hi 

I tried to set up a DigitalOcean instance but am encountering some problem.

Here is the error message that I obtained while I attempted to connect.

[I 16:25:47.833 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 16:25:59.332 NotebookApp] SSL Error on 7 ('50.133.80.154', 49866): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 16:25:59.377 NotebookApp] SSL Error on 8 ('50.133.80.154', 49867): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 16:25:59.475 NotebookApp] SSL Error on 7 ('50.133.80.154', 49868): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 16:25:59.790 NotebookApp] SSL Error on 7 ('50.133.80.154', 49869): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 16:26:38.314 NotebookApp] SSL Error on 7 ('50.133.80.154', 50006): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 16:26:38.404 NotebookApp] SSL Error on 7 ('50.133.80.154', 50007): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 16:26:38.494 NotebookApp] SSL Error on 7 ('50.133.80.154', 50010): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 16:26:38.582 NotebookApp] SSL Error on 7 ('50.133.80.154', 50011): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 16:26:38.671 NotebookApp] SSL Error on 7 ('50.133.80.154', 50012): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 16:26:38.762 NotebookApp] SSL Error on 7 ('50.133.80.154', 50015): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
Write failed: Broken pipe

Could anyone help me out there? Thank you very much!!

Best,
Hsunyi

**Comment by hhsieh** [comment]
And the web(Chrome) shows "the site can't be reached. The connection was reset."
I highly appreciate if anyone can let me know how to fix this. Thanks!!

Best,
Hsunyi

**Comment by Carreau** [comment]
Hum, that's likely a notebook issue. not an IPython one, and seem to be already reported  there:

https://github.com/jupyter/notebook/issues/507

is that it ?

**Comment by hhsieh** [comment]
Thanks. You are right. It's fixed now.
