### ISSUE TITLE
Document all the things for 5.0

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9537]
Assigning @willingc 

No just kidding. 

We should try to gather a migration document and work a bit on the what's new. 

Things to tell users, feel free to complete this list:
- [ ] Vi keybinding 
- [ ] prompt configuration changes

**Comment by Carreau** [comment]
most of this should be documented now. Pushing to 5.1 in case a few things are missing.

**Comment by pavoljuhas** [comment]
The `define_magic` function was removed in c7755fb9b53e2f6928c1532a04ae1f4bc9ced4ff however it is described as supported at the bottom of [custommagics.rst](https://github.com/ipython/ipython/blob/5.0.0/docs/source/config/custommagics.rst).  Please update the documentation.

**Comment by pavoljuhas** [comment]
OK, see #9735.  Feel free to adjust as necessary - I won't have much time for the next 2 weeks.

**Comment by takluyver** [comment]
Closing this, let's open more specific documentation issues that aren't just going to be bumped to the next release for all eternity.
