### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by rornor** [ipython/ipython#9542]
I've read some issues about these Deprecation Warnings, where it is mentioned that they should've been silenced by now, and in that direction I installed 5.0.0b. 
But it's just the same - my Notebook is full with red blocks of Warnings, and I'm not interested in any kind of deprecated warnings from inner working of IPython or related back machinery as they are of no use to me, just causing distraction and my code to look awful.

So finally I thought to drop by and ask for advice how to turn DeprecationWarnings off for good (preferably if there is some undocumented settings so I don't have to rely on startup scripts)?

![clipboard01](https://cloud.githubusercontent.com/assets/3144780/15808783/e873e4ee-2b80-11e6-8450-725060d9b4fa.png)

**Comment by Carreau** [comment]
You will need to update `ipykernel` these do not come from IPython. 
Still strange that your filter does not hide these.

**Comment by ivanov** [comment]
Thank you for your report. I'm not seeing this in notebook version 4.2.2 and ipykernel 4.3.1, so presumably this is something that was fixed between the original report and now (likely via https://github.com/ipython/ipykernel/pull/34) so I am closing this issue . As Matthias pointed out, [ipython/ipykernel](/ipython/ipykernel) would be the appropriate place to report this bug if it does recur.

Happy hacking! :bowtie:
