### ISSUE TITLE
Be good citizen, upload to warehouse

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9552]
cf : https://mail.python.org/pipermail/distutils-sig/2016-June/029083.html

Ping @minrk you might want to do the same for notebook 4.2.2.

**Comment by minrk** [comment]
Cool, thanks! I've updated my pypirc, and will give it a try on next release.

**Comment by Carreau** [comment]
jupyter_qtconsole b1 has been uploaded through warehouse without issues.

**Comment by minrk** [comment]
Same for client 4.3, ipyparallel 5.1. Seems to work.

**Comment by takluyver** [comment]
Great. This is set in the uploader's `.pypirc` file rather than anything in the project, so shall we close the issue?

**Comment by Carreau** [comment]
It's on my `.pypirc` as well, should we ping explicitly our leadership, just in case ?

I don't know if @jhamrick saw that she own a few packages as well. 

Feel free to close if you think it's fine.

**Comment by minrk** [comment]
I've set my pypirc, too. I think we're set. We don't have pypi config elsewhere in config, so I think it's appropriate to leave that outside our own docs as pypi best practices, especially since there's no problem if people haven't done it.
