### ISSUE TITLE
%%python doesn't display rich media anymore

### ISSUE THREAD

**Issue by dsblank** [ipython/ipython#9553]
After updating to the latest everything (I think) the shell magic %%python no longer displays rich media:

![screenshot from 2016-06-06 22 17 39](https://cloud.githubusercontent.com/assets/168568/15844063/2e2b01f2-2c35-11e6-978c-c26ea2065052.png)

I'm pretty sure that this worked before the upgrade.

Here is About from the notebook:
```
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
```

**Comment by Carreau** [comment]
> I'm pretty sure that this worked before the upgrade.

I pretty sure it was not as %%python run things in a subshell, which  capture stdout/err, and display it, so the rich things don't work. 

What version were you using before ?

**Comment by dsblank** [comment]
The last time I had updated was about 4 months ago.

I am almost positive that this worked before, as things that rely on this now no longer work.

BTW, this is on Jupyterhub.

**Comment by minrk** [comment]
@dsblank is it possible that one of your meta-kernels redefined `%%python` to run in the in-memory IPython kernel? Because the default `%%python` shell magic, like all the shell magics, just creates a subprocess and captures terminal output.

**Comment by dsblank** [comment]
@Carreau I was thinking that that might have happened. If that is the explanation, I guess something might have changed to not be able to override the %%python magic with our own. Does that suggest any change that I should look at?

**Comment by dsblank** [comment]
Oops, wrong person.

@minrk  I was thinking that that might have happened. If that is the explanation, I guess something might have changed to not be able to override the %%python magic with our own. Does that suggest any change that I should look at?

**Comment by minrk** [comment]
I'd look for `register_magics` calls, or any reference to language magics. @blink1073 do you have a recollection of a `%%python` magic in metakernel?

**Comment by dsblank** [comment]
@minrk Yes, we have a %%python magic in metakernel. I wrote that part. But I didn't think that had previously replaced IPython's %%python, and now it isn't. But I am checking on that...

**Comment by Carreau** [comment]
Ah, True,  i forgot that Magic could be overwritten. 

We did shed some old magic registering functions so that might be the reason !

**Comment by dsblank** [comment]
I must have been mistaken. Thanks for the info.
