### ISSUE TITLE
TerminalInteractiveShell.highlighting_style_overrides

### ISSUE THREAD

**Issue by klonuo** [ipython/ipython#9557]
``` python
# Override highlighting format for specific tokens
# c.TerminalInteractiveShell.highlighting_style_overrides = {}
```

This setting seem to accept dictionary with Tokens (`from pygments.token import Token`) as keys.

Trying to add such keys:

``` python
c.TerminalInteractiveShell.highlighting_style_overrides = {
    Token.Menu.Completions.Completion.Current: 'bg:#00aaaa #000000',
}
```

raises NameError as Token is not defined. Making it a strings doesn't work, too.

How can I reference them in IPython config, without explicitly importing `Token` in configuration file, which doesn't seem right?

**Comment by Carreau** [comment]
> How can I reference them in IPython config, without explicitly importing Token in configuration file, which doesn't seem right?

Yes you have to import Token. The style thing need to get some updates. In general you should be able to just create your own theme as a pygments extension, register it with an entry point and just use your style name.

**Comment by klonuo** [comment]
Ok @Carreau. While here, just a related question about documenting completion drop-down box (that you suggested on IPython dev list) - did you mean documenting `highlighting_style_overrides()` config function, or making separate reST file for customization of PTK drop-down menu?

**Comment by takluyver** [comment]
@Carreau I wonder if we should support strings of the token names (either with or without the `Token.` prefix), so it can be configured without importing anything, and in JSON config.

**Comment by Carreau** [comment]
> Ok @Carreau. While here, just a related question about documenting customization of completion drop-down box (that you suggested on IPython dev list) - did you mean documenting highlighting_style_overrides() config function, or making separate reST file for customization of PTK drop-down menu?

I mean documenting the general process of customizing colors of IPython, and the available configurations options.

> @Carreau I wonder if we should support strings of the token names (either with or without the Token. prefix), so it can be configured without importing anything, and in JSON config.

Maybe, but I think we need to finish the color-handling refactor before thinking about things like that. 
So I'd like to punt on that for 6.0.

It's also not that hard to actually make a package that ships it's own theme and giving it a name that pushing that into configuration. Might even be easier to write a Pygmetns.style.fromJSON, and a Pygment.style.merge_with_other_style than shoehorn this into a weird "importstring" configuration options.

**Comment by klonuo** [comment]
> I mean documenting the general process of customizing colors of IPython, and the available configurations options.

Ok, I'll wait new PTK feature to stabilize and try to write rst article on customizing IPython console style.

To add in this issue, that all available keys should be in `DEFAULT_STYLE_EXTENSIONS` dict:
```python
from prompt_toolkit.styles import DEFAULT_STYLE_EXTENSIONS
```

**Comment by klonuo** [comment]
> Ok, I'll wait new PTK feature to stabilize and try to write rst article on customizing IPython console style.

Actually I can write about general style options, but focus on Windows console and ConEmu (they both have renderers in PTK) and leave *nix Terminal for somebody else
