### ISSUE TITLE
Upload multiple files usability issue

### ISSUE THREAD

**Issue by zroadhouse-wsm** [ipython/ipython#9580]
When using the Upload button in the file browser, it would be much better if it performed the upload automatically after selecting files for upload. In my example, I want to upload several hundred data files. It is very time consuming to have to click the "Upload" button that appears next to each file.

**Comment by Carreau** [comment]
That's an issue for jupyter/notebook not IPython, and yes we are working on better upload functionality.

**Comment by zroadhouse-wsm** [comment]
Good to hear! Thank you.

**Comment by donghwicha** [comment]
any update on this?

**Comment by stutisehgal** [comment]
> That's an issue for jupyter/notebook not IPython, and yes we are working on better upload functionality.

Any updates?

**Comment by CapitaineNemo** [comment]
Dears , any update for this function ??? Can not google it out .

**Comment by MrMino** [comment]
@CapitaineNemo Please refer to Jupyter/notebook#3747. As previously noted by @Carreau this is not the place to ask about this issue. 

This is the issue tracker for IPython, issues releated to Jupyter Notebooks should are handled in [Jupyter/notebook issue tracker](https://github.com/jupyter/notebook).
