### ISSUE TITLE
Shift+Tab tooltips and doc empty

### ISSUE THREAD

**Issue by m7thon** [ipython/ipython#9581]
With 5.0.0b1, pressing Shift+Tab opens a tooltip with docstring, etc. and holding Shift and pressing Tab displays this in various ways.

With the current master the various display windows are opened but all completely empty. When used with the current jupyter-master, `[object Object]` is shown. See image:
![ipython-5 0 0b2 tooltip](https://cloud.githubusercontent.com/assets/5876537/15904782/9e477b68-2db2-11e6-98ef-95f7f81ffcce.jpg)

**Comment by Carreau** [comment]
Ouuhh thanks. Will investigate.

**Comment by Carreau** [comment]
Fixed by #9576 

Thanks for report and trying !
