### ISSUE TITLE
Behavior of Control-p changed with prompt toolkit and vi bindings

### ISSUE THREAD

**Issue by matthew-brett** [ipython/ipython#9584]
Before the new prompt toolkit changes, in the old readline days, your average vim users would put something like this in their `~/.inputrc`:

```
$include /etc/inputrc
set editing-mode vi
$if mode=vi
set keymap vi-command
$endif
```

With this setup, we startup IPython, and we are in editing mode by default, as seems natural.  In editing mode, Control-p brings up previous lines from the history.   ESC (or its vim equivalents) puts us into navigation mode, which has the same Control-p behavior.

In the new prompt_toolkit terminal emulation, I believe we need to add the following to `~/.ipython/profile_default/ipython_config.py `:

```
# Configuration file for all things ipython
c = get_config()
c.TerminalInteractiveShell.editing_mode = 'vi'
```

In this case, when I start IPython, I am again in editing mode (good) but now Control-p starts autocompletion, until I exit to navigation mode with ESC (etc).   I use Control-p all the time, so it's a significant inconvenience having to prefix all my Control-p's with ESC.   As a vim user, as you can imagine, I hate using the cursor keys, which would be my other option.

It would be good to keep the previous Control-p behavior, and probably by default, but at least available by configuration.

**Comment by minrk** [comment]
cc @jonathanslenders

**Comment by Carreau** [comment]
Thanks @matthew-brett for the detailed explanation. I'll see if we can do something in IPython itself.
