### ISSUE TITLE
Extra blank line needed in multi-line

### ISSUE THREAD

**Issue by chris-b1** [ipython/ipython#9586]
Thanks for the all the fast fixes so far.   This is really minor, so feel free to punt, but it has been tripping me up a little.  In 5.0, if a function contains a return statement, it takes 1 extra line to close the multi-line block compared to previous behavior.  

Note that if that function (or more realistically, an `if` block) doesn't end in a `return`/`pass`, then the old behavior persists.  Let me know if these examples aren't clear.

#### 4.x
```
In [3]: def f(a):
   ...:     return 5
   ...:
```

#### 5.0b2
```
In [10]: def f(a):
    ...:     return 4
    ...:
    ...:

In [11]: def f(a):
    ...:     a = 5
    ...:
```

**Comment by takluyver** [comment]
Yeah, I think I've also noticed that that logic is not quite right. We do something to dedent after a statement like `return`, `continue`, `break` or `pass` (because they typically end an indented block), and I guess that must be interfering. Thanks for filing the issue.

**Comment by Carreau** [comment]
You can force submit with Esc-Enter. 
I don't think that should be a blocker for 5.0 though. Still we have plenty of time to fox ot.

**Comment by takluyver** [comment]
I woulldn't be surprised if it's a pretty easy fix - I'll try to look into it next week if no-one beats me to it.
