### ISSUE TITLE
double quotes do not appear immediately

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#9589]
Typing `"` at the prompt does not print anything -- I need to type another character and both the quote and the following character will appear at the same time.  This is a bit annoying as I am used to typing `""` <left arrow> and fill in the string after (which is still possible... just weird).
This does not happen with single quotes (`'`).

**Comment by takluyver** [comment]
That sounds like something is trying to do combining characters, e.g. " + a -> ä.

This isn't happening for me - can you give more details about your system that might be relevant? Can you try with other terminal emulators?

**Comment by anntzer** [comment]
Arch Linux, tested both with Konsole and xterm.
Typically using a French keyboard layout but switching to US (via setxkbmap) did not help.
Note that it doesn't actually print out a combining character even if I type e.g. `"a`.

**Comment by Carreau** [comment]
That's super weird... let me see if I know someone with a French keyboard local and a linux computer.

**Comment by Carreau** [comment]
@parleur and/or @NelleV if you have a Linux Computer + French keyboard can you try the beta2 of IPython and try to type a double quote?

```
$ pip install ipython --pre
```

Thanks !

**Comment by NelleV** [comment]
I have no problem with the double quote on linux, using bépo.

**Comment by NelleV** [comment]
It works fine using an azerty as well.

**Comment by Carreau** [comment]
Thanks @NelleV 

Humm... @anntzer what locale do you have ? IIRC you are close to Berkeley we might be able to debug that in person. 

I'm going to mark that as "need-info" and not block releases on it for now.

**Comment by anntzer** [comment]
I can drop by D-lab tomorrow if you're around.

**Comment by Carreau** [comment]
Hum Friday might be a bit busy, especially afternoon. You can try to ping me and I can tell you whether I'm available, but it will likely be hard.

**Comment by anntzer** [comment]
How's late morning today like?

**Comment by anntzer** [comment]
11am in front of Barrows?

**Comment by Carreau** [comment]
> 11am in front of Barrows?

I'm there  (north entrance) on the wood bench.

**Comment by Carreau** [comment]
So it's triggered by `--TerminalInteractiveShell.editing_mode='vi'`, @matthew-brett I'm curious why you haven't reported this one ? Or do you never use double quotes ? (can you reproduce it ?)

**Comment by Carreau** [comment]
(that seem to be fixed on ptk master)

**Comment by matthew-brett** [comment]
I usually use single quotes, but I can reproduce it.

**Comment by anntzer** [comment]
I wonder if using double quotes is more an AZERTY thing... (because you don't need to use shift).

**Comment by Carreau** [comment]
closed by #9624
