### ISSUE TITLE
The ! command re-runs shell startup scripts, which can break things in weird cases like mine

### ISSUE THREAD

**Issue by njsmith** [ipython/ipython#9594]
I have some path manipulation stuff inside my shell login scripts (for example `source .../venv/bin/activate`, among other things).

When I use the magic `!` syntax in ipython, it seems to start a login shell, which re-executes my login scripts, and thus potentially overwrites changes that I've made within this particular session (for example, `source some-session-specific-venv/bin/activate`).

Example:
```
~$ pyvenv-3.5 test-venv             
~$ source test-venv/bin/activate
(test-venv) ~$ pip install ipython
[...]
Successfully installed backports.shutil-get-terminal-size-1.0.0 decorator-4.0.10 ipython-4.2.0 ipython-genutils-0.1.0 pexpect-4.1.0 pickleshare-0.7.2 ptyprocess-0.5.1 simplegeneric-0.8.1 traitlets-4.2.1
(test-venv) ~$ rehash
(test-venv) ~$ ipython
Python 3.5.1+ (default, May  9 2016, 11:00:17) 
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
Missing: numpy, matplotlib

In [1]: !echo $PATH
/home/njs/.npm-root/bin:/home/njs/.user-python3.5-64bit/bin:/home/njs/bin:/usr/lib/ccache:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/home/njs/test-venv/bin:/home/njs/.npm-root/bin:/home/njs/.user-python3.5-64bit/bin:/usr/local/games

In [2]: import subprocess

In [3]: subprocess.run("echo $PATH", shell=True)
/home/njs/test-venv/bin:/home/njs/bin:/usr/lib/ccache:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/home/njs/.npm-root/bin:/home/njs/.user-python3.5-64bit/bin:/usr/local/games
Out[3]: CompletedProcess(args='echo $PATH', returncode=0)
```

Notice how in `!echo $PATH`, `/home/njs/.user-python3.5-64bit/bin` comes first, while in `subprocess.run("echo $PATH", shell=True)`, `/home/njs/test-venv/bin` comes first.

The above example uses ipython 4.2.0, but I first encountered this problem with a recent snapshot of IPython master.

CC @Carreau

**Comment by takluyver** [comment]
[Here's the code that `!` calls](https://github.com/ipython/ipython/blob/65aeaabad8ab4b21b1c715b8c450e42fb49fdb3a/IPython/core/interactiveshell.py#L2295). I think the difference is that we're using your `$SHELL` environment variable to pick the shell to run instead of `/bin/sh`.

Every time I deal with all those shell profile and rc files I have to work out which ones run when.

**Comment by njsmith** [comment]
Oh, I see - so it's not the login/non-login thing, it's that you're running a non-login zsh and subprocess is running a non-login /bin/sh and my zsh init scripts are borked. Le sigh. I think that makes it user error, not an ipython bug -- sorry for the noise.

**Comment by njsmith** [comment]
I just fixed my startup scripts, so I think this can be closed ;-)
