### ISSUE TITLE
PTK tab completion with many alternative hard to review and navigate

### ISSUE THREAD

**Issue by matthew-brett** [ipython/ipython#9597]
With the new PTK autocompletion, even with:

```
ipython --TerminalInteractiveShell.display_completions_in_columns=True
```

and after Control-L, the result is a fairly large array of potential completions but:

a) It's not nearly large enough for big namespaces like numpy, and there is no way that I can see the entire list blurted out to the terminal, as was possible with readline and (related);
b) It is hard to navigate the list.   Cursor keys and Control-N/P work to move single elements, but in large panes of options, this is - er - painful.

**Comment by minrk** [comment]
Should completions-in-columns be the default?

**Comment by klonuo** [comment]
related: #9555

**Comment by matthew-brett** [comment]
I guess completion in columns would be a good default, in that it's more similar to the readline version.  I think it's usually what you want, as well.

**Comment by Carreau** [comment]
> Should completions-in-columns be the default?

I would not be against.

**Comment by takluyver** [comment]
One potential reason not to do completions in columns is that we're looking at providing extra info next to each completion. That presumably only works with a single column of completions. So if people get used to multi-column completions now, we may later have to either change the default or hide the new feature behind a setting no-one's likely to find.

It's possibly not a good enough reason to stop us doing it, but it's worth considering.

**Comment by matthew-brett** [comment]
Related - and y'all probably know this - but you can't use the right / left cursor keys to navigate in the pane.  So if I tab complete on `np.`, even after Control-L, I see down to `cos`, but to get to `cosh` I need to do in the order of 100 Control-Ns.

**Comment by jonathanslenders** [comment]
```
but you can't use the right / left cursor keys to navigate in the pane. 
```

This is on my list of improvements for a next version of prompt-toolkit. It's not easy to do right now, because of the decoupling between the UI and the key bindings + completion code. In a next version, this should be easier to implement.
However, adding a key binding that goes forward/backward 10 completions at the time should already be possible.

**Comment by hainm** [comment]
> Should completions-in-columns be the default?

Please please. I find the default completion is very annoying (vs my old habit seeing all the contents at once).

**Comment by Carreau** [comment]
Closing now that we have the multicolumn by default and the 'readlinelike' version.
