### ISSUE TITLE
Adjust delays in IPython/lib/inputhookwx.py and make them configurable.

### ISSUE THREAD

**Issue by ipython** [ipython/ipython#96]
Original Launchpad bug 526243: https://bugs.launchpad.net/ipython/+bug/526243
Reported by: ellisonbg (Brian Granger).

We have a scaling delay parameter that depends on how long IPython has been idle.  Currently it is a bit too long.  We need to tweak these times and make them configurable.

**Comment by Carreau** [comment]
Closing this as it is quite old, and most of our eventloop integration have been refactored. 

Thanks.
