### ISSUE TITLE
"return to editor to correct syntax error" is annoying

### ISSUE THREAD

**Issue by asmeurer** [ipython/ipython#9603]
When I type a syntax error in the IPython console, like `def test()` without the colon, I get a prompt 

```
In [1]: def test
  File "<ipython-input-1-50eadd3e41eb>", line 1
    def test
            ^
SyntaxError: invalid syntax

Return to editor to correct syntax error? [Y/n]
```

This is annoying, and seems completely unnecessary, since with prompt_toolkit you now can reasonable edit the input in the console.

**Comment by asmeurer** [comment]
Also consider that the average Joe who doesn't do any terminal configuration probably has `$EDITOR` set to the default `vi`, and dumping someone who doesn't know what they're doing into `vi` is about the worst user experience you can have.

**Comment by asmeurer** [comment]
Hmm, seems this is because I enabled `autoedit_syntax` in my IPython config a long time ago, not knowing what it was. I guess this is the first version where the setting actually works. Anyway, it does seem that it is in fact disabled by default, so feel free to close.

**Comment by Carreau** [comment]
Let's turn that into "improving the text string of `autoedit_syntax` flag", and you are right, now that we have multiline, we might be able to get rid of this.

**Comment by Carreau** [comment]
I'm going to bump that to 6.0 and it will likely be "remove the feature".

**Comment by takluyver** [comment]
If we agree about removing the feature, we may as well do it for 5.0. It's currently broken if you enable it, so we need to do either remove it or fix it before releasing.
