### ISSUE TITLE
mangled ASCII color codes(?) in __init__ signatures

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#9607]
IPython 5.0b3, PTK master, empty `ipython_config.py`.
```
In [6]: class C:
   ...:     def __init__(self): pass
   ...: 
   ...: 

In [7]: C??
Init signature:
[0mC[0m[1;33m([0m[1;33m)[0m[1;33m[0m[0m

*** ERROR: EOF in multi-line statement


Type:
type
```

**Comment by takluyver** [comment]
It is the colorama package which should be interpreting colour codes on Windows. Can you check that you have that and that it's up to date? I'm pretty sure I did test coloured output on Windows too.

**Comment by anntzer** [comment]
This is on Linux.

**Comment by takluyver** [comment]
OK, I see it too, but don't have time to look into it right now.

**Comment by Carreau** [comment]
Introduced by #9551.
