### ISSUE TITLE
Tab completion no longer works with IPython.core.debugger.Tracer

### ISSUE THREAD

**Issue by ngoldbaum** [ipython/ipython#9612]
Here I'm using the following test script:

```python
from IPython.core.debugger import Tracer

debug_here = Tracer()


local = 12

debug_here()
```

Under IPython 4.2.0, running the test script and doing "loc<tab>" produces the following output:

```
goldbaum at ROUS2 in ~/Documents/test
○ python test.py
--Return--
None
> /Users/goldbaum/Documents/test/test.py(8)<module>()
      4
      5
      6 local = 12
      7
----> 8 debug_here()

ipdb> loc
local              local_gadget_101/  local_tipsy_270/   local_varia_305/
local-vr/          local_gadget_fof/  local_tipsy_302/   locals
local001/          local_owls_302/    local_tipsy_340/
local_enzo_301/    local_pw_270/      local_varia_304/
ipdb> local
```
Where it fills out tab completions based on local variables and some folders I have in the directory I'm running IPython from.

Under IPython 5.0b3, the output looks like this:

```
goldbaum at ROUS2 in ~/Documents/test
○ python test.py
--Return--
None
> /Users/goldbaum/Documents/test/test.py(8)<module>()
      4
      5
      6 local = 12
      7
----> 8 debug_here()

ipdb> loc     
```

Here the tab completion isn't triggered and instead a tab character is printed.

A similar issue is effecting the ipdb package, see https://github.com/gotcha/ipdb/issues/100.

**Comment by takluyver** [comment]
See ipython/ipython#9487 - IPython.core.debugger is now plainer, and the completion functionality is moved to IPython.terminal.debugger. The 'core' variant still works in the notebook, and the PTK-using subclass in 'terminal' relies on having a terminal interface.

**Comment by ngoldbaum** [comment]
Fair enough, closing. Thanks for commenting in the ipdb issue.
