### ISSUE TITLE
bug with pandas in ipython shell

### ISSUE THREAD

**Issue by shelper** [ipython/ipython#9615]

**Comment by takluyver** [comment]
Did you close this because you found a solution?

**Comment by shelper** [comment]
i dont think this is an ipython problem after i did some testing,
However,  dont know how to delete an issue here....

**Comment by takluyver** [comment]
Fair enough. There's no need to delete issues; if there's nothing that needs to be done, we just close them. I just wanted to check because you closed it with no explanation soon after opening it, so it could have been accidental.
