### ISSUE TITLE
Completion usability: auto-complete only unambiguous section, not to first option

### ISSUE THREAD

**Issue by fperez** [ipython/ipython#9629]
Another difference from "old" completion that's wrecking my muscle memory...  On my system, with numba, numpy and numexpr installed, typing `import num<TAB>` produces:

![image](https://cloud.githubusercontent.com/assets/57394/16104944/8b8eb832-333a-11e6-9cd8-e33add8528f4.png)

the problem is that it completes `ba` and pops up the dialog. Say that what I needed was numpy: now I need to either backspace over `ba` and type `py`, or use the tab or arrow keys to get to the numpy completion.

Previously, what we did was to refuse to complete and simply show the options to the user:

![image](https://cloud.githubusercontent.com/assets/57394/16104982/e3a4fbe4-333a-11e6-9069-0c11a58ffc3b.png)

then I could simply look at the options and type the remainder of the word (or enough letters to disambiguate and TAB again).

For this particular pattern, I find the new system extraordinarily annoying, and a major usability regression compared to the old behavior.

**Comment by takluyver** [comment]
I think this was a consequence of the changes to automatically select the first item in the list, because selecting a completion puts the letters there. Note that as a slight improvement on backspacing the completion out, you can press up-arrow once to deselect the completion and get back to the text you had entered.

@jonathanslenders would it be possible to pre-select the first completion in the dropdown, but not insert any characters until the user has confirmed it by pressing enter?

**Comment by jonathanslenders** [comment]
Ok, if you agree, I'll merge the above pull request and this becomes prompt-toolkit 1.0.2.

**Comment by takluyver** [comment]
So just to clarify, that would still keep the 1.0.1 behaviour when there's only one completion - add the remaining text, and don't show the dropdown. But when there's more than one completion, it won't select the first one until you press tab again or down-arrow. Have I got that right?

If so, that sounds good to me. @fperez, do you agree?

**Comment by Carreau** [comment]
> So just to clarify, that would still keep the 1.0.1 behaviour when there's only one completion - add the remaining text, and don't show the dropdown. But when there's more than one completion, it won't select the first one until you press tab again or down-arrow. Have I got that right?

Yes. Just tried.

That would be more consistent with `nu<tab>` that complete and stop to `num`. 
But at some point we cannot completely match readline as `num<tab><tab><tab>` with readline would never cycle through completions and get stuck at `num`.

**Comment by fperez** [comment]
Agreed, @takluyver. And @Carreau, I think it's OK if additional `<tab><tab>` presses then cycle through: that *is* an improvement that PT brings over the capabilities of readline, for  sure.

Thanks folks for your patient entertaining of my obsessiveness... :)

**Comment by jonathanslenders** [comment]
prompt-toolkit 1.0.2 has been released with this fix. Enjoy!

**Comment by Carreau** [comment]
> prompt-toolkit 1.0.2 has been released with this fix. Enjoy!

You are crazy (in the good sense). We need to send you a Jupyter T-Shirt as soon as we receive the new one.

**Comment by jonathanslenders** [comment]
I'd love to have a T-shirt :-)

**Comment by fperez** [comment]
just updated to PT 1.0.2 and ipython-master, loving it. Many thanks everyone!!
