### ISSUE TITLE
Notebook Validation failed: u'execution_count' is a required property

### ISSUE THREAD

**Issue by pythonicassetpricer** [ipython/ipython#9638]
I get this error everytime I save my notebook. Appears to be this issue - 

http://stackoverflow.com/questions/34085676/ipython-notebook-error-notebook-json-is-invalid-uexecution-count-is-a-requi

as it also started for me after accidentally opening the ipynb in pycharm. Any idea how this can be fixed?

**Comment by takluyver** [comment]
I think that if you rerun all the cells in the Jupyter notebook and then save it, that error should go away. If you got it with an up to date version of Pycharm, it would be good if you could also file a bug with Jetbrains that they're creating invalid notebooks!

**Comment by ivanov** [comment]
Thank you for your report. I am going to go ahead and close this issue as it is coming from PyCharm and not caused my IPython itself.

Happy hacking! :bowtie:
