### ISSUE TITLE
%timeit caching warning

### ISSUE THREAD

**Issue by stefanv** [ipython/ipython#9643]
We have noticed that, nowadays, we very often get a warning about caching when using %timeit.  However, this only seems to happen when accessing Python objects, which I guess is kind of intuitive.

So, e.g.:

```
In [82]: d = {0: 1}
In [83]: %timeit d[0] = 1
The slowest run took 26.20 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 54.8 ns per loop
```

But, if you just %timeit 1+1 you won't see any caching message.

@Carreau mentioned that the defaults may need to be tweaked a bit:

> We can try to tweak the default parameters. Maybe the -n -r option can be of help.
> We also have some logic that try to guess the right -n -r values, if you have a really fast (or slow) machine, it might get confused by extreme values.

**Comment by takluyver** [comment]
We show that if there's a factor of 4 difference between the fastest and slowest run, IIRC. But we step up the number of loops we time until it takes long enough to get an accurate reading, so if you time something very fast, the first timings with only a few loops will be dominated by the overhead. Unfortunately it's tricky to distinguish that from a case where something is actually cached and you may not be timing what you think you're timing.

**Comment by Carreau** [comment]
Well, one of the things we could try is starting the tuning at `number=10`, or check whether the 1st tuning loop is below a certain threshold, in which case the overhead is likely the thing we measure. 

You can regardless use explicit -n, -r, in which case there will be no tuning, and you will get a more consistent response.

**Comment by Carreau** [comment]
#9984 have improved timeit significantly, report mean +std instead of best/worst. And have a check a 1e-6 seconds below which it does not warn.  So this is likely fixed. Can any of you confirm ?

**Comment by stefanv** [comment]
The latest version works great, and the std return is very useful.  Thank you!

**Comment by stefanv** [comment]
(The one thing that is slightly unclear is what the phrase 'using standard deviation' means.)

```
10000000 loops, average of 7: 103 ns +- 1.18 ns per loop (using standard deviation)
```

**Comment by Carreau** [comment]
It means that 1.18 is std, and not max=103+1.18 and min=103-1.18.
Do you have a better  phrasing in mind ?

**Comment by stefanv** [comment]
Perhaps: `mean 103 ns, standard deviation 1.18` or `103 ns +- 1.18 s (standard deviation)`
