### ISSUE TITLE
Remove IPython.core.hooks:fix_error_editor (now deprecated) 

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9649]
`fix_error_editor` is pending deprecation as of IPython 5.0 and will be removed
in future versions. It appears to be used only for automatically fixing syntax
error that has been broken for a few years and has thus been removed. 

---

In #9647 patch we recommend to users to complain here if they need it, so that we can Un-Deprecated.

**Comment by augustogoulart** [comment]
@Carreau It seems that nobody has ever complained about deprecating `fix_error_editor`, so I think it's safe to remote it:

https://github.com/ipython/ipython/issues/9649

**Comment by Carreau** [comment]
Closed by #12103
