### ISSUE TITLE
Move `ipython_completions` to Jupyter and check that it actually works..

### ISSUE THREAD

**Issue by fperez** [ipython/ipython#9666]
The [ipython bash/zsh completions support](https://github.com/ipython/ipython/blob/6ff17c08d9ba6f0aaba3808579bfd625c3405534/examples/IPython%20Kernel/ipython-completion.bash) was quite useful, but we should now move most of it to Jupyter and update it to complete on jupyter commands. There may still be a few ipython-specific completions, but most of them are now Jupyter subcommands.

Not sure quite which should be the right repo for it...

**Comment by minrk** [comment]
We could put it in core as an example, or perhaps consider a completions-emitting feature for jupyter commands so that you could do something like:

```bash
eval $(jupyter notebook completions)
```

in .bashrc

**Comment by fperez** [comment]
For simplicity for now, I suggest we move it to core. That may make it even a 5.0 task, since it's trivial and it helps us not to have stale/broken code in the release.

I would just add a comment in the file as `TODO` with your idea, and that can be picked up later if someone cares enough, as I think that's much lower priority.

**Comment by fperez** [comment]
Thanks @minrk for those suggestions, BTW, I think they're both spot-on, and they make the task pretty manageable right now.

**Comment by Carreau** [comment]
closed by #9681
