### ISSUE TITLE
Default syntax higlighting colours are unreadable on light background

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#9670]
![screenshot from 2016-06-28 15-33-23](https://cloud.githubusercontent.com/assets/327925/16419469/c5c44d7c-3d45-11e6-8e1d-f3b7b2ed27b2.png)

Ping @Carreau @fperez 

I had tried to pick a set of colours that are moderately passable on both light and dark background terminals, so I'm kind of annoyed to start IPython today and find that it's assuming a dark background again.

Tracing the code paths through, it looks like you've moved my colour picks under the 'lightbg' option, which is only the default on macs.

**Comment by takluyver** [comment]
Following comment on #1272

**Comment by takluyver** [comment]
See #9672 which leaves the prompt colours as they were but uses the same set of highlighting colours for the default on all platforms.

**Comment by Carreau** [comment]
> I had tried to pick a set of colours that are moderately passable on both light and dark background terminals, so I'm kind of annoyed to start IPython today and find that it's assuming a dark background again.

Sorry about that, the colors seemed pretty bad on @fperez screen, so we decided to use stronger colors.
The reasoning to switch prompt colors is to give feedback when you use `%colors`. 
I honestly forgot the default was different on various platforms. I think you are right that dark theme should be readable on white bg if it can be the default.

**Comment by takluyver** [comment]
I'm fine with having two sets of prompt colours, but I think the default colours really need to be readable both ways round. There's no way of working out which one we're on, and there's a lot of people using each.

I'm sure the colours I picked aren't great, and I'm happy if we can find some more pleasing ones. But in the tests I've done, they are basically legible either way, and I think that has to be a constraint for the defaults.

**Comment by fperez** [comment]
I mostly wanted the explicit 'Linux' color scheme (which now is *not* the default as it used to) to be  really optimized for dark bg, but I fully agree that the default should be readable on both, sorry if in the last updates we didn't cross-check enough.

**Comment by Carreau** [comment]
That the problem, Linux is **still** default on windows and Linux...

**Comment by takluyver** [comment]
The default didn't change, your OS changed ;-)

**Comment by fperez** [comment]
Ah, got it! Well, in any case, the 'default' being different from Linux/LightBG as in #9674, looks like a good solution to me.

**Comment by Carreau** [comment]
@takluyver if you are happy can we close that ?

**Comment by takluyver** [comment]
Yup, thanks.
