### ISSUE TITLE
Navigate through history, ignore consecutive duplicates.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9683]
I think that would be nice,  not sure if it should be moved in PTK.

**Comment by segevfiner** [comment]
I vaguely remember having had to press UP multiple times to skip duplicate/identical history entries in some IPython version, but I'm not seeing this behavior after testing recently. Searching around the code I found this: [jonathanslenders/python-prompt-toolkit/prompt_toolkit/buffer.py#L1127-L1130](https://github.com/jonathanslenders/python-prompt-toolkit/blob/4a27a142de525bb5a84edfb7df0bfa673ef9847e/prompt_toolkit/buffer.py#L1127-L1130) and there is obviously also the referenced PR #9943 which suggests that the version I saw this at were `IPython>=5.0,<5.2`.

Or did you mean something else entirely in this issue? 😃

**Comment by Ritiek** [comment]
I use 5.1.0 but it works fine for me. Using same command consecutively shows up the command only once in the history when pressing up..

**Comment by segevfiner** [comment]
@Ritiek I'm not entirely sure, but I think you will get duplicates only after re-opening IPython since the code in PR #9943 is only used during init. During an IPython session PTK prevents duplicates in the in-memory history but before PR #9943 IPython added duplicates to the history on history load at startup.

**Comment by Ritiek** [comment]
@segevfiner Yeah, you're right. I can see the duplicates now.

**Comment by srinivasreddy** [comment]
safely closed?

**Comment by takluyver** [comment]
Yup, thanks.

**Comment by segevfiner** [comment]
It seems thst IPython might ignore saving and loading consecutive duplicates. But when there are distant duplicates that are still the same they are not skipped over when doing an up/down arrows history search (When you type a partial command and then use the up/down arrows to search though history) or from ctrl-r. That means that you can do:
```python
In [1]: 123
Out [1]: 123

In [2]: 456
Out [2]: 456

In [3]: 123
Out [3]: 123
```

And you will find `123` twice in the history search.

Maybe that's what @Carreau meant or is that a different issue?

**Comment by Carreau** [comment]
> Maybe that's what @Carreau meant or is that a different issue?

I honestly don't remember. I think having no consecutive duplicate is already good. If the question re-present itself, we can think about non-consecutive duplicate. I can see case where non-consecutive are useful.

**Comment by takluyver** [comment]
Yeah, I think non-consecutive duplicates is fine, and this is now working as expected.

**Comment by carlsmith** [comment]
Sorry, but I can't think of any use case for loading duplicates when the user is scrolling though their history. Obviously, dupes must be kept in the history, as each input is indexed, but why would anyone scroll past an item to get to an identical item?

**Comment by Carreau** [comment]
To re-run an analysis with slight modification.

$ ipython
In [ ]: Do stuff
In [ ]: exit
Modify file.
$ IPython
In [ ]: # press up 5 times, enter
In [ ]: # press up 5 times, enter
In [ ]: # press up 5 times, enter
In [ ]: # press up 5 times, enter
In [ ]: # press up 5 times, enter

If you remove duplicate then the "press 5 times" can vary in length.
Especially when you step through a process not having gaps in what you did
in history is extremely convenient.
Of course this is just an example and you should (likely), put that in a
file, but it is a used wokflow :-)

**Comment by MrMino** [comment]
I noticed, after updating my IPython package to 6.1, that the duplicate entries still don't get ignored. IPython does indeed omit them when tracking what you type, but if they are already there, they will not get ignored.

This might make some people think that this ?bug? is still there.
