### ISSUE TITLE
Make ';' suppresion of output optional

### ISSUE THREAD

**Issue by ipython** [ipython/ipython#97]
Original Launchpad bug 509864: https://bugs.launchpad.net/ipython/+bug/509864
Reported by: fdo.perez (Fernando Perez).

We supress output when an input line ends with ';', in contrast to how python itself works.  Make it possible for the user to optionally disable this.

The code is in prompts.py, around line 548 (as of 2010/01/19):

           # do not print output if input ends in ';'
           try:
               if self.input_hist[self.prompt_count].endswith(';\n'):
                   return
           except IndexError:
               # some uses of ipshellembed may fail here
               pass

Reported by Sage, for reference: http://trac.sagemath.org/sage_trac/ticket/6650.

**Comment by Carreau** [comment]
I'm worries of the complexity/benefit ratio of this, and as it hasn't received love in more than 3 years, I'm going to close. 

Feel free to reopen. 

Thanks,
