### ISSUE TITLE
Remove workaround of #9682

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9700]
Reverting the PR should be enough. Marking as 5.1.

**Comment by minrk** [comment]
Linking to #9682 since refs in title don't make links.

**Comment by takluyver** [comment]
Do we know what prompt_toolkit version is the minimum for our fix not to be required?

**Comment by Carreau** [comment]
> Do we know what prompt_toolkit version is the minimum for our fix not to be required?

https://github.com/jonathanslenders/python-prompt-toolkit/commit/4f653f32f1516610689c481f301f54b78d3d242a so >= 1.0.4

**Comment by takluyver** [comment]
#10175 removes this.
