### ISSUE TITLE
Make a 5.0.0rc.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9701]
I think IPython has stabilized a lot since b4, I'm going to cut a RC today.

**Comment by Carreau** [comment]
Crap While uploading through warehouse, warehouse server crashed or whatever. 5.0rc is broken. Might do a rc2 as soon as PyPI comes back online.

**Comment by Carreau** [comment]
Ok, upload whent actually fine and I was able to resume. The tar.gz have matching md5, so rc1 is out.

**Comment by minrk** [comment]
Nice, thanks!
