### ISSUE TITLE
C-k and C-u should clear newline when at end/beginning of line

### ISSUE THREAD

**Issue by asmeurer** [ipython/ipython#9703]
In emacs mode, C-k and C-u should respectively clear a newline. That way you can type them multiple times to clear multiple lines.

**Comment by takluyver** [comment]
@jonathanslenders - I think these are shortcuts that you define, so you may be interested in adjusting them. Otherwise, we can override them.

**Comment by jonathanslenders** [comment]
This should be fixed in prompt-toolkit indeed.

**Comment by jonathanslenders** [comment]
For C-K, it has already been fixed here: https://github.com/jonathanslenders/python-prompt-toolkit/commit/be68caacffec4695379fd241903689e5e6731688
Can you test that?

**Comment by jonathanslenders** [comment]
And the fix for C-u: https://github.com/jonathanslenders/python-prompt-toolkit/commit/41e1152367ba45e293006f20aa8656a670549ce3

**Comment by Carreau** [comment]
Closing as fixed when updating Prompt-Toolkit.
