### ISSUE TITLE
Keybord shortcut Documentation page does not render.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9709]
At least not on RTD, it works for me locally.

**Comment by takluyver** [comment]
Probably needs the autogen script to be run by this section:

https://github.com/ipython/ipython/blob/6f44adf605ed3e55fcbab07d3c0a007a4b6e4a94/docs/source/conf.py#L22-L36

**Comment by Carreau** [comment]
https://www.youtube.com/watch?v=VxDgNORm2uU&feature=youtu.be&t=9s
