### ISSUE TITLE
Deprecate lib/inputhook

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9712]
As far as I understand it is unused. RIght ? 

@takluyver should we sprinkle deprecation warnings for 5.0 ?

**Comment by takluyver** [comment]
Yep, it should be unused with the switch to prompt_toolkit.

I might even risk removing it directly - I'm not aware of anyone using that code for anything else. But the sensible thing to do is to have a deprecation cycle to see if I'm wrong about that.

**Comment by Carreau** [comment]
closed by #9713
