### ISSUE TITLE
ipython Installation problems on OsX El Capitan

### ISSUE THREAD

**Issue by shantanu9847** [ipython/ipython#9716]
I am using the system installation of python which is 2.7.3 and I get the following error message when I do
pip install ipython , I get

```
Installing collected packages: setuptools, appnope, ipython
  Found existing installation: setuptools 1.1.6
    Uninstalling setuptools-1.1.6:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 299, in move
    copytree(src, real_dst, symlinks=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
Error: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', '/tmp/pip-h7Ifnn-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', "[Errno 1] Operation not permitted: '/tmp/pip-h7Ifnn-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', '/tmp/pip-h7Ifnn-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', "[Errno 1] Operation not permitted: '/tmp/pip-h7Ifnn-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', '/tmp/pip-h7Ifnn-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', "[Errno 1] Operation not permitted: '/tmp/pip-h7Ifnn-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', '/tmp/pip-h7Ifnn-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', "[Errno 1] Operation not permitted: '/tmp/pip-h7Ifnn-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', '/tmp/pip-h7Ifnn-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', "[Errno 1] Operation not permitted: '/tmp/pip-h7Ifnn-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib'")]
```
Any ideas?
Thanks

**Comment by takluyver** [comment]
Try upgrading setuptools separately first - you have a really old version.

```
pip install --upgrade setuptools
```

And for good measure:

```
pip install --upgrade pip
```

**Comment by shantanu9847** [comment]
Thanks a lot for the tip, but upgrading setuptools gave a different error :-(

Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 299, in move
    copytree(src, real_dst, symlinks=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
Error: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', '/tmp/pip-yoEyqf-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', "[Errno 1] Operation not permitted: '/tmp/pip-yoEyqf-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', '/tmp/pip-yoEyqf-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', "[Errno 1] Operation not permitted: '/tmp/pip-yoEyqf-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', '/tmp/pip-yoEyqf-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', "[Errno 1] Operation not permitted: '/tmp/pip-yoEyqf-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', '/tmp/pip-yoEyqf-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', "[Errno 1] Operation not permitted: '/tmp/pip-yoEyqf-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', '/tmp/pip-yoEyqf-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', "[Errno 1] Operation not permitted: '/tmp/pip-yoEyqf-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib'")]

shantanu

**Comment by shantanu9847** [comment]
Ok, I was able to fix the setuptools problem and installed setuptools-1.1.6 using
sudo pip install --upgrade setuptools --user python
and I get 
Collecting setuptools
  Downloading setuptools-24.0.2-py2.py3-none-any.whl (441kB)
   
Requirement already up-to-date: python in /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
Installing collected packages: setuptools
Successfully installed setuptools-1.1.6

But I still get the same error ( as reported in the first message) when I try to install ipython after this  :-(
Any ideas?

**Comment by takluyver** [comment]
setuptools 1.1.6 is what you had before. It seems to be confused. Someone more familiar with macs than me may be able to help you more.

**Comment by Carreau** [comment]
That's likely the [System Integrity protection](https://support.apple.com/en-us/HT204899) kicking in.
You just can't modify some system folders even by being root. 

or `easy_install` shenanigans, in which case the following **may help**

```
pip install damnpth; damnpth
```

Try using a non-system Python like the one offered by [brew](http://brew.sh/) or [anaconda](https://www.continuum.io/downloads#_macosx) woudl likely be a more effective way now, and less hassle in the future.

**Comment by shantanu9847** [comment]
thanks to everyone for all replies. so looks like there is no solution unless I install a non-system Python?
shantanu

**Comment by Carreau** [comment]
There might be, but that's the kind of things which is hard through chat. 
Were are you based ? Meeting with an advance Pythonista might help.

**Comment by minrk** [comment]
System Python on OS X does some unpleasant things with sys.path that prevent you from being able to override packages that are considered 'part of the system', which is annoying but makes sense from the system's perspective. If you want to install additional packages and keep things up to date, it is strongly recommended to use a different installation (conda, brew, python.org). If that's not acceptable, you can use virtualenv with system Python.

**Comment by carlsmith** [comment]
Agreed. Especially since El Capitan, if you're using Python for more than a few local scripts, it's really best to leave the system Python alone, and create your own installation.

**Comment by willingc** [comment]
@shantanu9847 I hope these responses from @minrk, @Carreau, and others have answered your question. I'm going to close this question as answered. If you have further questions, please do reopen this issue. Thanks for your interest in IPython.  

## Summary of options
### Option 1 (recommended) Use a non-system Python
Use a Python installation from conda, brew, or python.org. This will simplify installation of additional packages and keeping things up to date.

### Option 2
If Option 1 is not acceptable, you can use virtualenv with system Python.
