### ISSUE TITLE
Stdin gets broken with %run and ^D

### ISSUE THREAD

**Issue by haridsv** [ipython/ipython#972]
It seems like there is some issue with using ^D to end input to interactive scripts started with %run. The first time any interactive script is run, the stdin works as expected, but after ending the input by pressing ^D, any future invocation of any interactive script terminates immediately as if the stdin was already closed. I was able to reproduce it with a very simply script.

E.g., create a script like this and call it t.py:

```
import sys
for line in sys.stdin:
    print line,
```

Run it from ipython like this:

```
Ln [0]: %run t.py
a
b
^DaD
b

Ln [1]:
```

Notice how there is an extra "D". This seems to be some weird thing happening on a Mac, as it happens outside ipython also. I was intrigued and tried this on a linux box also, and though the extra D doesn't show up, the same buggy behavior was observed when running from ipython (you do need to press ^D twice to end the script, which is different from Mac).

Now, for the actual problem.. if you run the same command again, it just exits:

```
Ln [1]: %run t.py

Ln [2]
```

If I put a breakpoint and check the value of sys.stdin.closed, it says False. I didn't go deeper and see where the problem is, but I am guessing it is something to with reusing some virtual terminal somewhere that has the closed state persisted. Restarting the ipython console of course fixes the issue.

I am using Python 2.6.5 on Mac and 2.6.1 on Linux.
IPython version 0.11.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Though we never got this to work as intended in Python2 (I just tested with IPython 5.3), it seems highly unlikely we will ever introduce new code to make this work on Python2 in the 5.x branch.  As notes, this does work as intended in Python 3, and IPython 6.0 release only support Python3.

Thanks everyone and happy hacking! :bowtie:
