### ISSUE TITLE
ipython 5 embed not cleaning up shell title

### ISSUE THREAD

**Issue by ojii** [ipython/ipython#9722]
I've upgraded to ipython 5 and my code that embeds ipython in a script is now causing a little trouble. The embedding is done like this:

```python

import IPython
from IPython.terminal.ipapp import load_default_config
IPython.embed(config=load_default_config())
```

Since the upgrade, if I quit the ipython shell (and exit the Python script completely), the title of my shell is still `IPython: ...`. Previously, the title would be restored after exiting the ipython shell.

Am I embedding it wrong?

**Comment by minrk** [comment]
You are probably doing nothing wrong, it's likely a bit of code that fell out as we switched from readline to prompt-toolkit.

**Comment by Carreau** [comment]
Gnaa, we were **not** setting the terminal title before, and unfortunately I don't think there is an API to push/pop terminal title. 

It's basically your embedding program which is responsible on IPython exit to print to stdout `'\u001b]0;' + title + '\u0007'` to set it back to its previous value.

**Comment by takluyver** [comment]
Maybe we should just not set the terminal title at all when embedded?

**Comment by ojii** [comment]
> Maybe we should just not set the terminal title at all when embedded?

Is there a way for me to have ipython not setting the title?

**Comment by takluyver** [comment]
Try passing `term_title=False` to embed().

**Comment by ojii** [comment]
Thank you, that works for me.

**Comment by takluyver** [comment]
I have made #9801 to make that the default.
