### ISSUE TITLE
Ipython 5 tab completion dialogue does not allow for "shift-tab" reverse traversal of available completions

### ISSUE THREAD

**Issue by msmith491** [ipython/ipython#9724]
{'commit_hash': u'1ba246d',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/matt/Code/cinder/.newton-venv/lib/python2.7/site-pa
ckages/IPython',
 'ipython_version': '5.0.0',
 'os_name': 'posix',
 'platform': 'Darwin-15.5.0-x86_64-i386-64bit',
 'sys_executable': '/Users/matt/Code/cinder/.newton-venv/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '2.7.11 (default, Jan 22 2016, 08:29:18) \n[GCC 4.2.1 Compat
ible Apple LLVM 7.0.2 (clang-700.1.81)]'}

Test Case:
1. open `ipython` 5.0 shell1
2. type `import uuid` and press enter
3. type `uuid.` and hit tab
4. hit tab 3-4 times to scroll through the selection dialogue box
5. now hit shift-tab.  Nothing happens.  The only way to go back in the list is via the arrow keys.

I think shift-tab for reverse scrolling is a well known convention for interacting with selection boxes and is worth supporting

**Comment by takluyver** [comment]
It's working with shift-tab on Linux.

**Comment by msmith491** [comment]
Ok, I've narrowed it down to likely an issue with the terminal mode in Neovim.  Using normal ITerm2 on OS X does not have this issue.  I'll close and take it up with the Neovim team :)
