### ISSUE TITLE
Is it possible to insert arbitrary javascript into --to html conversions

### ISSUE THREAD

**Issue by hassanshaikley** [ipython/ipython#9726]
Hey all,

I want to know if this is possible. 

Or can I trust nbconvert from users to return content that we can show to other users.

Thank you

**Comment by Carreau** [comment]
No, you can't trust nbconvert output. 
For example GitHub  do deactivate the JS exporter in nbconvert, sanitize HTML and iframe it on a different domain just to be safe.
