### ISSUE TITLE
TerminalInteractiveShell.display_completion has no help.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9729]
All in title.

**Comment by Carreau** [comment]
@michaelpacer assigned to you.

**Comment by michaelpacer** [comment]
https://github.com/michaelpacer/ipython/commit/a132e73220e1da44aec39c5c452b8b07f87cdd91 should address it.

**Comment by michaelpacer** [comment]
https://github.com/ipython/ipython/pull/9806 is the pr

**Comment by Carreau** [comment]
FY you can say `Closes #9806` in a commit to autoclose the issue when the PR is merged.

**Comment by Carreau** [comment]
CLose by #9806.
