### ISSUE TITLE
How do I determine whether ipython runs in shell or notebook?

### ISSUE THREAD

**Issue by 2sn** [ipython/ipython#9732]
I would like to automatically load the proper backend on startup, TKAgg or nbagg, respectively.  I have not found a way do this in the config file (some one use "traits" which turn out to be very uncooperative in providing any data).  Could you please help, maybe provide some documentation how this can be done?

**Comment by 2sn** [comment]
PS - this makes, for the time being, the use use of %pylab in the ipython config file not usable, and one has to stick with the -pylab command line option.  Very unfortunately, when starting Jupyther with "jupyter notebook --InteractiveShellApp.matplotlib='nbagg'" the config option is ignored.

**Comment by juhasch** [comment]
There was a similar question some time ago: #4856

I personally use something like this in my profile startup script to detect if IPython is running as a kernel and not in a terminal:
```Python
ip = get_ipython()

if ip.has_trait('kernel'):
    %matplotlib inline
```

**Comment by 2sn** [comment]
Thank you for your reply.

This does not work in the ipython_config.py file, however, because there get_ipython() still returns None.

**Comment by 2sn** [comment]
@juhasch thanks for the hint
I got it to work in `ipython_config.py` using
```python
c = get_config()
[...]
c.InteractiveShellApp.exec_lines = []
[...]
x = """
from IPython import get_ipython
ip = get_ipython()
print(ip)
if ip.has_trait('kernel'):
    %pylab nbagg
%pylab
"""
c.InteractiveShellApp.exec_lines.append(x)
[...]
```

**Comment by takluyver** [comment]
You can also set options for IPython running as a kernel (for a Jupyter frontend, i.e. not IPython in the terminal) using the separate `ipython_kernel_config.py` config file. http://ipython.readthedocs.io/en/stable/config/options/kernel.html

**Comment by 2sn** [comment]
Thanks.  Unfortunately, it seems there is no comparable separate config
file for ipython running as a terminal in case you wanted to set things you
do not want to set in kernel mode.

Sent from my Pixel C.
On 11 Jul 2016 03:53, "Thomas Kluyver" <notifications@github.com> wrote:

You can also set options for IPython running as a kernel (for a Jupyter
frontend, i.e. not IPython in the terminal) using the separate
ipython_kernel_config.py config file.
http://ipython.readthedocs.io/en/stable/config/options/kernel.html

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/ipython/ipython/issues/9732#issuecomment-231601709>,
or mute
the thread
<https://github.com/notifications/unsubscribe/ABNtFr2BfXTZnqa38FaopK652R0wID-8ks5qUTGkgaJpZM4JI1rx>
.

**Comment by takluyver** [comment]
Currently, no, there isn't. We could add one. Hopefully things you set in ipython_kernel_config override things in  ipython_config.
