### ISSUE TITLE
Cannot close last figure window

### ISSUE THREAD

**Issue by crosset** [ipython/ipython#9734]
After updating ipython to 5.0 (from macports), I cannot close last figure window (neither with button in window bar, nor with 'close()'). The mouse cursor becomes spinning wheel inside the window, but I can still type command in the terminal window.

However, if I type clf(), the figure window closes and a new one appears.

This happens only when there is only one figure window remaining. 

Here's my system (OS X  El Capitan, with python/ipython etc. installed via macports) :
```
[~] $ python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': u'<not found>',
 'commit_source': '(none found)',
 'default_encoding': 'UTF-8',
 'ipython_path': '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython',
 'ipython_version': '5.0.0',
 'os_name': 'posix',
 'platform': 'Darwin-15.5.0-x86_64-i386-64bit',
 'sys_executable': '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python',
 'sys_platform': 'darwin',
 'sys_version': '2.7.12 (default, Jun 29 2016, 12:52:38) \n[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]'}
```

**Comment by Carreau** [comment]
Do you use the `%matplotlib` magic ? And/or which matplotlib backend are you using to plot ?

**Comment by crosset** [comment]
Oh, sorry I forgot to mention : I am using the OS X backend (as defined in my matplotlibrc file, so that it is selected automatically when calling "ipython --pylab"). I also tried starting with "ipython" and then doing "%matplotlib osx" but I get the same behavior.

**Comment by Carreau** [comment]
Hum, that might be a macport issue, I'm unable to reproduce with other Python install like homebrew. Whether on py2 or py3, though I'm on Yosemite... 

Can you try a pip-installed version ?

**Comment by therockmandolinist** [comment]
@Carreau I'm experiencing the same issue with py3 on OSX 10.11.5 (EL Capitan) with ipython pip-installed, python3 installed through homebrew.

**Comment by crosset** [comment]
Same issue with python27 installed with macports and ipython-5.0 installed via pip.

However, it works fine with Tk backend (macports install, starting with ipython --pylab-tk), I can close the figure window normally.

**Comment by Carreau** [comment]
hum.. what about pure python shell ?

**Comment by therockmandolinist** [comment]
Pure python 3 shell does not seem to exhibit the same problem as ipython running the same version of python.

**Comment by Carreau** [comment]
@minrk which version of OS X do you have ?

**Comment by crosset** [comment]
No problem when using pure python 2.7 directly (same macports version, with osx backend).

**Comment by marcobardoscia** [comment]
Same problem here:
- El Capitan 10.11.5
- Python 3.4.5
- Matplotlib 1.5.2
- IPython 5.0.0
Python stack installed with Macports. It works fine with TkAgg as backend.

**Comment by kyleniemeyer** [comment]
I also started encountering this problem today, after updating to IPython 5.0.0, with Python 3.5.2 and matplotlib 1.5.1 on OS X 10.11.5. Python installed with homebrew, IPython & matplotlib installed with pip.

This happens regardless of starting IPython with ``--pylab`` or not. The issue started with my IPython upgrade today.

**Comment by minrk** [comment]
I can reproduce this. We didn't need any eventloop integration for OS X before, so we don't have it in the PT stuff. Apparently we need something there, now. I'll investigate what we need.

**Comment by minrk** [comment]
Oops, we do have it and I wrote it. Apparently I wrote it wrong. Still self-assigning and investigating why it misbehaves when the window closes. I'm guessing it's because the app loop has stopped.

**Comment by takluyver** [comment]
@minrk did you get anywhere with this? Should it block 5.1, or shall we bump it to 5.2?

**Comment by minrk** [comment]
I didn't get anywhere last time I looked into it. Let me spend a bit more time on it today. If everything else is done for 5.1 and I still haven't figured it out, we can bump it, but I'd prefer not to.

**Comment by willingc** [comment]
@minrk Perhaps related: https://github.com/ipython/ipython/pull/9312

**Comment by willingc** [comment]
@minrk #9854 looks reasonable to me. Events and layers of eventloops make things challenging. I agree with going with #9854 since least likely to break some other event handling.

**Comment by nirum** [comment]
Has this been fixed? I still have this issue with ipython 5.1

**Comment by leewalsh** [comment]
This problem seemed solved to me sometime around when this issue closed in August, though I can't remember precisely. However, as for @nirum, it has reappeared recently, again I can't say if it corresponded to a particular update.

The scope seems to be a little smaller now. Figures close normally in the GUI interface when I press `⌘w` (`<CMD-W>`) or click the close window button `ⓧ`. The window disappears, and the figure is no longer listed in `plt.get_fignums()`.

However, if I run `plt.close` (with any argument, as long as it ends up closing all figures), then all the figures remain open (i.e., visible in the GUI) but they're grey and frozen (trying to interact via the GUI gives the spinning beach ball). After this, `plt.get_fignums()` returns an empty list.

Creating a new figure closes the frozen figure(s) and proceeds as normal. Running `plt.draw()` also closes them, and creates a single empty figure.

Here's my system currently in case it helps:

    OS X El Capitan 10.11.6
    iTerm2 Build 3.0.11
    Python 2.7.12           (homebrew)
    IPython 5.1.0           (pip)
    matplotlib 1.5.3        (pip)

    IPython.sys_info()
    {'commit_hash': u'5c9c918', 'commit_source': 'installation',
     'default_encoding': 'UTF-8', 'platform': 'Darwin-15.6.0-x86_64-i386-64bit',
     'ipython_path': '/usr/local/lib/python2.7/site-packages/IPython',
     'ipython_version': '5.1.0', 'os_name': 'posix', 'sys_platform': 'darwin',
     'sys_executable': '/usr/local/opt/python/bin/python2.7',
     'sys_version': '2.7.12 (default, Oct 11 2016, 05:24:00) \n[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]'}

**Comment by crosset** [comment]
I also observe exactly the same behavior. I have the same configuration, except I installed python etc through macports.

Cyrille.
