### ISSUE TITLE
`ESC+.` is not working in ipython 5

### ISSUE THREAD

**Issue by konradkonrad** [ipython/ipython#9739]
I used to be able to recall the last argument(s) of the last line(s) via `ESC`+`.`. This no longer works.
To reproduce:
```
$ ipython
...
In [1]: import IPython
In [2]: 
# now hit 'ESC' followed by '.'
In [2]: 
# i.e. nothing happens
```
Desired behaviour (as with `ipython<5.0.0`)
```
$ ipython
...
In [1]: import IPython
In [2]: 
# now hit 'ESC' followed by '.'
In [2]: IPython
# i.e. the last argument of the last line appears in the prompt.
```

Version information:
```
'commit_hash': u'1ba246d',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/me/.virtualenvs/venv/lib/python2.7/site-packages/IPython',
 'ipython_version': '5.0.0',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-45-generic-x86_64-with-debian-jessie-sid',
 'sys_executable': '/home/me/.virtualenvs/venv/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.11 (default, Apr  7 2016, 00:21:37) \n[GCC 4.8.4]'}
```

**Comment by takluyver** [comment]
I guess that's a readline feature - I've never come across it before, but I've just tested in bash and it works. We have moved away from readline, so we no longer get that feature from it (we get a bunch of new features instead ;-). We should document how to add custom shortcuts.

**Comment by konradkonrad** [comment]
> I've never come across it before

Sorry to hear that /s

> We should document how to add custom shortcuts.

You mean, there is a chance for me to get the behaviour back via `~/.ipythonrc` or the like? The muscle memory is strong with me, and being able to use (all?) my shell shortcuts in ipython was always a strong argument for me to use it.

**Comment by takluyver** [comment]
Yes, it should be possible to recreate it, though it will take a bit of fiddling. You can see our shortcut definitions here:
https://github.com/ipython/ipython/blob/master/IPython/terminal/shortcuts.py

I think the easiest way to add a custom one would be with a [startup file](http://ipython.readthedocs.io/en/stable/interactive/tutorial.html#startup-files). The code to add the shortcut will be something like this:

```python
ip = get_ipython()
if getattr(ip, 'pt_cli'):
    registry = ip.pt_cli.application.key_bindings_registry
    registry.add_binding(Keys.Escape, '.',
                     filter=(HasFocus(DEFAULT_BUFFER)
                             & ~HasSelection()
                             & insert_mode))(handlerfunc)
```

**Comment by konradkonrad** [comment]
Thanks @takluyver that was very helpful!
Here is what I came up with:
```python
def yank_last_arg(event):
    """'readline'-style yank-last-arg:
        Insert last argument to the previous command (the last word of the previous history entry).
        Successive calls to yank-last-arg move back through the history list, inserting the last
        word of each line in turn.
        see: https://www.gnu.org/software/bash/manual/bashref.html#Commands-For-History
        note: this doesn't support the numeric argument option of readline's yank-last-arg
    """
    b = event.current_buffer
    hist = ip.history_manager.input_hist_raw
    if not hasattr(b, 'last_arg_at'):
        b.last_arg_at = len(hist)
    if not hasattr(b, 'last_arg_depth') or b.last_arg_at != len(hist):
        b.last_arg_depth = 1 
        b.last_arg_at = len(hist)
    else:
        b.last_arg_depth += 1

    if len(hist) and len(hist) >= b.last_arg_depth:
        lastline = hist[-b.last_arg_depth]

        if b.last_arg_depth > 1:
            b.undo()

        b.save_to_undo_stack()
        if len(lastline.split()):
            b.insert_text(lastline.split()[-1])
```

Would it make sense to PR this into the default shortcuts? Also please advise if there is a better way for the state variables `last_arg_at` and `last_arg_depth`.

**Comment by takluyver** [comment]
I'm not really sure what's the best way to deal with the state; maybe store it in an object you've defined rather than in the buffer object? You could use the `post_execute_cell` [event](http://ipython.readthedocs.io/en/stable/config/callbacks.html) to reset it.

I don't think that shortcut is useful enough in a Python context to go in the defaults, but a simplified version of it would be a good example for documenting how to add custom shortcuts.

**Comment by konradkonrad** [comment]
Thanks, the event based reset is exactly what I was looking for. I've updated [the gist](https://gist.github.com/konradkonrad/7143fa8407804e37132e4ea90175f2d8) accordingly, feel free to use or adjust for documentation!

> I don't think that shortcut is useful enough in a Python context to go in the defaults

For me this is partly about restoring known behaviour. But, while it may not seem useful in the Python context, in the context of IPython (and its superb shell interaction) it has been pretty helpful for me in the past, i.e. this contrived example:
```
In [1]: !head /home/konrad/.ipython/profile_default/startup/01-esc-dot.py
... # that's the one I want!
In [2]: text = open('
# ESC+.
In [2]: text = open('/home/konrad/.ipython/profile_default/startup/01-esc-dot.py').read()
```

Sure, there are probably other ways for doing such, but useful it is. Just my opinion.

Feel free to close and thank you very much for your support!

**Comment by takluyver** [comment]
Thanks, I've borrowed your example back and simplified it to put it in the docs: #9753.
