### ISSUE TITLE
self._eventloop doesn't always exist

### ISSUE THREAD

**Issue by JBKahn** [ipython/ipython#9740]
I was running a Django app locally using honcho and [this line](https://github.com/ipython/ipython/blob/97429bdee9adadbfbb8ebb2ccb2c98d03c36e6bd/IPython/terminal/debugger.py#L38) tried to execute but [this line](https://github.com/ipython/ipython/blob/3dc4dca62aeab6145f6b156d71c031d5305eef85/IPython/terminal/interactiveshell.py#L244) never gets executed to create an eventloop. This is because honcho redirect stdin and it fails [this check](https://github.com/ipython/ipython/blob/3dc4dca62aeab6145f6b156d71c031d5305eef85/IPython/terminal/interactiveshell.py#L207) because it looks like a simple prompt. 

I'm not sure if the solution is as simple as create an eventloop anyway, or if it's a deliberate decision not to. But this prevents the use of ipdb in this case.

**Comment by takluyver** [comment]
How are you getting the debugger?

[This line](https://github.com/ipython/ipython/blob/3dc4dca62aeab6145f6b156d71c031d5305eef85/IPython/terminal/interactiveshell.py#L110) should make it use the more basic plain debugger if `simple_prompt` is True, but I don't think ipdb uses that. Ipdb is maintained as a separate project, so if that's the interface you're using, it will probably need to be fixed there. Pinging @gotcha.

**Comment by JBKahn** [comment]
Oh I see, so `ipdb` shouldn't be calling that function when that line returned pdb as the class?

**Comment by takluyver** [comment]
Yeah - I'm not exactly sure what's the right way for ipdb to check it, but `simple_prompt` should mean nothing's trying to use prompt_toolkit.

**Comment by gotcha** [comment]
@JBKahn Can you open an issue on `ipdb` issue tracker ? Joining a traceback ?

**Comment by JBKahn** [comment]
sure, will do right now.

**Comment by takluyver** [comment]
Closing this for now, as I think the necessary fix is in ipdb, not IPython. We can reopen if there is something for us to change.
