### ISSUE TITLE
Scientific notation of floats not highlighted correctly

### ISSUE THREAD

**Issue by MaxNoe** [ipython/ipython#9742]
Floats with scientific notation do not get highlighted correctly in IPython 5.0 if no decimal marker is given.

![ipython_highlighting](https://cloud.githubusercontent.com/assets/5488440/16776440/a2b0b94e-4865-11e6-9c1e-181c4f8bb0ad.png)

**Comment by takluyver** [comment]
Looks like it's an issue in pygments:

```
In [1]: import pygments

In [2]: pl = pygments.lexers.Python3Lexer()
...
In [5]: list(pl.get_tokens('1e6'))
Out[5]: [(Token.Literal.Number.Integer, '1'), (Token.Name, 'e6'), (Token.Text, '\n')]

In [6]: list(pl.get_tokens('1.0e6'))
Out[6]: [(Token.Literal.Number.Float, '1.0e6'), (Token.Text, '\n')]
```

**Comment by takluyver** [comment]
https://bitbucket.org/birkenfeld/pygments-main/pull-requests/618/add-1e6-as-float-token-for-python3lexer/diff

**Comment by Carreau** [comment]
While you are at it https://www.python.org/dev/peps/pep-0515/ : Underscores in Numeric Literals  ?

**Comment by Carreau** [comment]
I'm marking that as no action, as there is nothing to do on IPython side, and we'll have to wait for Pygments to react. I'll close as well to try to keep the issue list clean.

**Comment by Carreau** [comment]
Feel free to reopen if needed.
