### ISSUE TITLE
"No module named 'cPickle'" How to solve this issue?

### ISSUE THREAD

**Issue by mohammad-py** [ipython/ipython#9743]
Hello guys,
I'm currently working on cs231n course, Deep Learning Stanford University. To follow the assignment task, I encountered with a problem when I tried to run simple source code which is inserted in assignment .zip file!
The error is this:

`
ImportError                               Traceback (most recent call last)
<ipython-input-1-08e4b0da8188> in <module>()
      3 import random
      4 import numpy as np
----> 5 from cs231n.data_utils import load_CIFAR10
      6 import matplotlib.pyplot as plt
      7 

C:\Users\baharrayane\Assignment I\cs231n\data_utils.py in <module>()
----> 1 import cPickle as pickle
      2 import numpy as np
      3 import os
      4 from scipy.misc import imread
      5 

ImportError: No module named 'cPickle'
`

So guys, how can I solve that please help me!

**Comment by takluyver** [comment]
This is for bugs in IPython, not getting help with your homework.

There may be a forum or chat room associated with your class where you can ask. If not, searching online will find you sites like this: http://www.programmingforums.org/post179255.html
