### ISSUE TITLE
Try to be compatible with unicode `__repr__` return in python 2.x

### ISSUE THREAD

**Issue by georgexsh** [ipython/ipython#9744]
as in python2, `__repr__` is not allowed to return unicode object but byte only, If unicode returned, python will try to covert encode, than exception raised:

```python
In [45]: s
Out[45]: Traceback (most recent call last):
  File "venv/local/lib/python2.7/site-packages/IPython/core/formatters.py", line 670, in __call__
    printer.pretty(obj)
  File "venv/local/lib/python2.7/site-packages/IPython/lib/pretty.py", line 383, in pretty
    return _default_pprint(obj, self, cycle)
  File "venv/local/lib/python2.7/site-packages/IPython/lib/pretty.py", line 503, in _default_pprint
    _repr_pprint(obj, p, cycle)
  File "venv/local/lib/python2.7/site-packages/IPython/lib/pretty.py", line 694, in _repr_pprint
    output = repr(obj)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 20-21: ordinal not in range(128)

In [46]: s.__repr__()
Out[46]: u'<ReadOnlyWorksheet "\u8d26\u5355">'
```

Could ipython try to be compatible with this faulty behavior? A possible workaround is to modify [`_repr_pprint()`](https://github.com/ipython/ipython/blob/master/IPython/lib/pretty.py#L694):

```diff
<     output = repr(obj)
---
>     output = obj.__repr__()
```

related with #6799, but not covered by #7853.

**Comment by takluyver** [comment]
Sorry, I don't think we should do this: if people test their code in IPython, it would hide that their `__repr__()` method is broken.

It won't be an issue from IPython 6, because that version will require Python 3 ([blog post](https://blog.jupyter.org/2016/07/08/ipython-5-0-released/)).
