### ISSUE TITLE
`terminal.debugger.TerminalPdb` doesn't respect profile configuration

### ISSUE THREAD

**Issue by bhodorog** [ipython/ipython#9746]
#### Steps to reproduce (tested against cpython 2.7.11 and 3.5.0)
1. Create and activate a new virtualenvironment. `virtualenv /tmp/ipython2 && source /tmp/ipython2/bin/activate`
2. Install latest _ipython_ and _ipdb_ available on PyPI: `pip install ipython ipdb`
3. Configure ipython's default profile to use `TerminalInteractiveShell.display_completions = 'readlinelike'` in ipython_config.py (as per [official docs](http://ipython.readthedocs.io/en/stable/config/options/terminal.html))
4. Run `python -c  'import ipdb; ipdb.set_trace()'`
5. Enter `list.<pres TAB>`
#### Expected:

See completion options displayed commandl line interface CLI like (similar to how readline was displaying them)
#### Actual:

Completion options are displayed using the fancy terminal user interface (TUI) combo box.
## Notes:

I used _ipdb_ in the steps of reproduce because it's how I had came across this issue and it's just a client of `terminal.debugger.TerminalPdb`.

Naively hacking around I got to a probably naive [fix](https://github.com/ipython/ipython/compare/master...bhodorog:terminal-debugger-kb-shortcuts). Looking at the git history of the affected files I'm thinking @takluyver might know more if the reported behaviour is intended or just an unwanted side effect of 5.0 version. In case of latter I'd be more than happy to create a PR with my fix.

In case the detailed infos about used ipython/cpython versions are needed:
[IPython sys info](https://gist.github.com/bhodorog/186ec342d789e7203a8247996349f164) used to reproduce the reported behaviour.

**Comment by takluyver** [comment]
The debugger should inherit at least some shortcuts and options from the terminal shell; I suspect that simply running the same `register_shortcuts` method is a bit oversimplistic, though.

**Comment by ferdynice** [comment]
I like to point out that you do not need ipdb to reproduce, as you can simply enter `%debug` in an IPython shell to drop into the debugger.

Anyway, is there any progress or thoughts about how to fix this? I would very much like to use 'readline like' completions in the ipdb debugger, the new windows style is driving me mad.

Allow me to crosslink to the ipdb issue:
https://github.com/gotcha/ipdb/issues/118

**Comment by bhodorog** [comment]
I hate to say this, but I would have loved to have more time to look closer into the issue and properly understand what @takluyver suggested. Since I've barely had any close contact with IPython (basically I dug through its code when I had the above issue) I tend to take Thomas words very seriously and doubt  that my naive fix is legit.  

If it helps since IPython 5.0 was released I've been constantly installing ipdb in my virtualenvs using `pip install ipdb ipython==4.2.1` which would force the installation of the previous version. I think I've been lucky not needing any of the new features introduced by 5.0 series.

And yes, you're right about reproducing it with IPython's `%debug%` magic command.

**Comment by takluyver** [comment]
Can you try #10305 ?

**Comment by bhodorog** [comment]
Looks good. Give it a try and works just fine. Waiting for the next 5.x now.  Thanks.
