### ISSUE TITLE
Left/Right Key Not Work in ipython 5.0.0 Tab Completion Menu

### ISSUE THREAD

**Issue by myhlivecom** [ipython/ipython#9747]
ipython 5 provides a new terminal interface. The tab completion now shows a menu listing all possible items. If the number of items is too large, the menu lists them over multiple columns. Unfortunately, user can't move the selection cursor in the menu to left/right by left/right key. It only supports to move the cursor by up/down key.

Please improve the cursor navigation in tab completion menu.

**Comment by takluyver** [comment]
See jonathanslenders/python-prompt-toolkit#147

**Comment by Carreau** [comment]
Thanks for the improvement suggestion, I think there are other issues talking about that beyond the one linked above. 

I'm going to mark that as "not IPython" as it's mostly an upstream issue, and close to keep the list of issues shorter. Feel free to reopen or comment if needed.

Thansk !
