### ISSUE TITLE
highlighting_style vs colors

### ISSUE THREAD

**Issue by memeplex** [ipython/ipython#9748]
Maybe I'm not understanding the role of each option, but when I set some value for `highlighting_style` the `colors` option seems to be ignored. For example:

```
c.TerminalInteractiveShell.highlighting_style = 'monokai'
c.InteractiveShell.colors = 'NoColor'
```

has the same effect than

```
c.TerminalInteractiveShell.highlighting_style = 'monokai'
c.InteractiveShell.colors = 'Linux'
```

**Comment by memeplex** [comment]
Ah, colors are for the legacy style. Closing.

**Comment by takluyver** [comment]
`colors` always affects the traceback and oinspect (`foo?`) colours; it only affects the prompt and syntax higlighting when `highlighting_style='legacy'`.

More info here: http://ipython.readthedocs.io/en/stable/config/details.html#terminal-colors
