### ISSUE TITLE
Keybindings for multiline editing are different from Jupyter Notebooks

### ISSUE THREAD

**Issue by MaxNoe** [ipython/ipython#9750]
When editing a multiline statement like `def` in ipython 5.0 `alt`-`enter` executes the cell.

I  the Jupyter Notebook it's `shift`-`enter`.

I think it would be more intuitive if those two were the same.

**Comment by takluyver** [comment]
We can't detect shift-enter or ctrl-enter reliably in the terminal, so it has to be enter and alt-enter.

alt-enter does also execute a cell in the notebook, but it's not the execute-and-select-next we use most often.

**Comment by reckoner** [comment]
Is there a way to configure this? My terminal does not like `alt` keys.

**Comment by takluyver** [comment]
You can try Esc, Enter (i.e. press and release escape, then press enter), which should have the same effect.

You can bind custom keyboard shortcuts (http://ipython.readthedocs.io/en/latest/config/details.html#keyboard-shortcuts ), but only with the key combos that we can actually detect in the terminal.

**Comment by reckoner** [comment]
thanks. I will look into it.
