### ISSUE TITLE
IPython 5 does not allow piping input from file (SyntaxError: unexpected EOF while parsing)

### ISSUE THREAD

**Issue by pitrou** [ipython/ipython#9752]
Say you have:
```
$ cat ipyinput.py 
import os, sys

def foo():
    return 42

sys.stderr.write("foo() result: %s\n" % foo())
os._exit(0)
```

You can pipe this file to IPython 4:
```
$ ipython < ipyinput.py 
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) 
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
foo() result: 42
```

But it fails with IPython 5:
```
$ ipython < ipyinput.py 
/home/antoine/35/lib/python3.5/site-packages/IPython/core/interactiveshell.py:440: UserWarning: As of IPython 5.0 `PromptManager` config will have no effect and has been replaced by TerminalInteractiveShell.prompts_class
  warn('As of IPython 5.0 `PromptManager` config will have no effect'
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
In [1]: In [2]: In [2]:   File "<ipython-input-2-6c730488126c>", line 1
    def foo():
              ^
SyntaxError: unexpected EOF while parsing

In [3]:   File "<ipython-input-3-b22cc0a7d30b>", line 1
    return 42
             ^
SyntaxError: 'return' outside function

In [4]: In [4]: Traceback (most recent call last):
  File "<ipython-input-4-df15ccc19bb7>", line 1, in <module>
    sys.stderr.write("foo() result: %s\n" % foo())
NameError: name 'foo' is not defined
```

**Comment by pitrou** [comment]
Trying to pass some options to disable fancy UI features doesn't work better:
```
$ ipython --quick --no-banner --quiet --colors=NoColor --simple-prompt  < ipyinput.py 

In [1]: 
In [2]: 
In [2]:   File "<ipython-input-2-6c730488126c>", line 1
    def foo():
              ^
SyntaxError: unexpected EOF while parsing


In [3]:   File "<ipython-input-3-b22cc0a7d30b>", line 1
    return 42
             ^
SyntaxError: 'return' outside function
[etc.]
```

**Comment by takluyver** [comment]
With the switch to prompt_toolkit, the primary IPython interface needs a terminal. When `sys.stdin.isatty()` is False, which it is when you pipe input, IPython falls back to a very simple REPL interface (we use this in some tests). This simple interface does not handle multiline input, so as you see, it tries to execute the line `def foo():` by itself.

I'm curious as to the use case - why would you want to pipe to IPython rather than either piping to plain Python, or running the file with IPython `ipython ipyinput.py`?

**Comment by pitrou** [comment]
> why would you want to pipe to IPython rather than either piping to plain Python, or running the file with IPython ipython ipyinput.py?

Because I want to test IPython compatibility of Numba JIT caching.
See https://github.com/numba/numba/blob/master/numba/tests/test_dispatcher.py#L843-L894

**Comment by takluyver** [comment]
Does this not work with `base_cmd + [inputfn]` to pass the filename on the command line? With that, the workaround for exiting shouldn't be necessary, because it will execute automatically when done.

**Comment by pitrou** [comment]
> Does this not work with base_cmd + [inputfn] to pass the filename on the command line?

This does not check what we want to check. Namely, that the user's function is defined on the IPython prompt, not in an input module.

**Comment by pitrou** [comment]
(this has consequences on e.g. the `co_filename` of the function's code object)

**Comment by pitrou** [comment]
Since the culprit is multiline editing, the hackish workaround here is to rewrite the test function as a lambda, but that will work only for very simple functions.

**Comment by takluyver** [comment]
Gotcha. It may be easier to use the IPython API to run individual chunks, e.g.

```python
from IPython.core.interactiveshell import InteractiveShell

shell = InteractiveShell()
res = shell.run_cell("a = 1/0")  # This can be multiline 
print(res.success)   # Boolean indicating if it succeeded; other variables store any error
```

This is the same API that we use to run code that the user enters, so it should be exactly the same. We call run_cell with `store_history=True`, but that will actually record the test code in the user's IPython history, which is annoying, so if you want to do that, please configure a different history file first:

```python
from traitlets.config import Config
c = Config()
c.HistoryAccessor.hist_file = ':memory:'
shell = InteractiveShell(config=c)
```

**Comment by pitrou** [comment]
Thanks for the suggestion. Is InteractiveShell a stable API?

**Comment by takluyver** [comment]
`InteractiveShell.run_cell` is certainly stable; not every method on InteractiveShell is so stable (it's a big class), but we'd generally consider a deprecation cycle necessary for breaking changes to public methods on that class.

The return value from run_cell (an instance of `ExecutionResult`) was added fairly recently; I forget in which release. If you need the tests to run with older IPython versions that don't return that, we can work out what you'd need to do.

**Comment by pitrou** [comment]
Hmm, it seems that run_cell() dumps any exception on stderr. Also, with `silent=True`, the `result` attribute of the `ExecutionResult` doesn't get set. Is there any best practice to use InteractiveShell without having it print stuff on stdout/stderr?

**Comment by takluyver** [comment]
Probably the simplest way is to call it inside the [capture_output](http://ipython.readthedocs.io/en/stable/api/generated/IPython.utils.capture.html#IPython.utils.capture.capture_output) context manager, which temporarily changes `sys.stdin` and sys.stderr`.

If you specifically wanted to change what happens to exceptions, you could also subclass `InteractiveShell` and override `showtraceback`. Subclassing in general is more brittle, though.

**Comment by Carreau** [comment]
Shouldn't it work with `ipython -c` ?
```
$ ipython -c "$(cat foo.py)"
foo() result: 42
```

**Comment by takluyver** [comment]
Closing for now as there are better ways to deal with programmatically running code in IPython, and I don't think we ever explicitly supported piping code in.

**Comment by aminorex** [comment]
This may be preventing use of ipython in an emacs shell?
