### ISSUE TITLE
Documentation needs an example of customizing the prompts

### ISSUE THREAD

**Issue by pitrou** [ipython/ipython#9757]
Customizing the prompts used to be dead simple (e.g. `c.PromptManager.in_template = '>>> '`). Now it has become an order of magnitude more difficult, it would be nice to give a real example in the documentation.

**Comment by takluyver** [comment]
There [is one](http://ipython.readthedocs.io/en/stable/interactive/shell.html#prompt-customization). We had unwittingly documented prompt customisation in two places; #9754 fixes that.

**Comment by pitrou** [comment]
Hmm, I see. I was indeed looking in the wrong place.

**Comment by Crandel** [comment]
Where I need to place my custom class MyPrompt? I want replace IPython.terminal.prompts.Prompts in ipython_config.py
something like this
```c.TerminalInteractiveShell.prompts_class = "my_prompt.MyPrompt" ```
I create my_prompt.py in ~/.ipython/profile_default/startup/ and it`s doesn`t work

**Comment by takluyver** [comment]
If you're doing it like that, the file just has to be somewhere that lets you `import my_prompt`.

`sys.path` is a list of directories where Python will look for modules - you can put it in any of those.

**Comment by Crandel** [comment]
@takluyver Thank you very much, it`s work!!!
