### ISSUE TITLE
IPython 5 - Embeded shell not reopening once exited

### ISSUE THREAD

**Issue by sticke4** [ipython/ipython#9761]
I recently updated to IPython 5 and am observing some strange behavior with the embedded shell functionality. If ipshell is called more than once in the code, once the first embedded shell is exited, the rest are also exited without allowing for interactivity.

So for example, from the [IPython 5 documentation on embedding](https://ipython.readthedocs.io/en/stable/interactive/reference.html#embedding), the sample code provided in embed_class_long does not work as intended. Once the first instance of ipshell is exited, IPython does not stop again when it is called. Below is an excerpt of the code from the documentation to highlight the issue.

``` python
from __future__ import print_function
from traitlets.config.loader import Config
cfg = Config()
# First import the embeddable shell class
from IPython.terminal.embed import InteractiveShellEmbed

ipshell = InteractiveShellEmbed(config=cfg,
                       banner1 = 'Dropping into IPython',
                       exit_msg = 'Leaving Interpreter, back to program.')

ipshell2 = InteractiveShellEmbed(config=cfg,
                        banner1 = 'Second IPython instance.')

print('\nHello. This is printed from the main controller program.\n')

ipshell('***Called from top level. '
        'Hit Ctrl-D to exit interpreter and continue program.\n'
        'Note that if you use %kill_embedded, you can fully deactivate\n'
        'This embedded instance so it will never turn on again')

print('\nBack in caller program, moving along...\n')

def foo(m):
    s = 'spam'
    ipshell('***In foo(). Try %whos, or print s or m:')
    print('foo says m = ',m)

# Some calls to the above functions which will trigger IPython:
print('Main program calling foo("eggs")\n')
foo('eggs')

ipshell2()
```

On my machine, when this runs, I drop into the first ipshell instance with the "Called from the top level" message. I then type exit to leave this embedded shell. I get the exit message as intended, get the print statement "Back in caller program, moving along..." and the statement "Main program calling foo("eggs")" as intended. Then on my shell, I get the "Dropping into IPython" message which is the banner for the first instance of ipshell, but IPython does not stop. Without embedding a shell, the program continues by printing the  "In foo()" statement, as well as the "Leaving Interpreter" exit message. Finally the script gets to ipshell2() and correctly opens a the second instance. 

Before in IPython 4.x, when foo('eggs') was run, a shell would be embedded. The issue is also a problem when used in for loops. If ipshell is called in a for loop and subsequently exited, all the ipshell calls afterwards will be skipped, which is annoying when you want to stop in every iteration of the for loop to inspect variables.

Here is some system information in case it is relevant.

```
'commit_hash': u'1ba246d',
'commit_source': 'installation',
'default_encoding': 'cp437',
'ipython_path': 'C:\\Anaconda\\lib\\site-packages\\IPython',
'ipython_version': '5.0.0',
'os_name': 'nt',
'platform': 'Windows-7-6.1.7601-SP1',
'sys_executable': 'C:\\Anaconda\\python.exe',
'sys_platform': 'win32',
'sys_version': '2.7.11 |Anaconda custom (64-bit)| (default, Feb 16 2016, 09:58:36) [MSC v.1500 64 bit (AMD64)]'}
```

**Comment by takluyver** [comment]
We changed a bit how it decides when to deactivate an embedded shell, there must be something not quite right in that implementation. Pinging @Carreau.

**Comment by takluyver** [comment]
@Carreau will you have time to look at this soon? Bump the milestone to 5.3 if not.

**Comment by Carreau** [comment]
> @Carreau will you have time to look at this soon? Bump the milestone to 5.3 if not.

I might. I'll try to find some time to review all non-assigned and 5.2 issues soon.

**Comment by Carreau** [comment]
> I might. I'll try to find some time to review all non-assigned and 5.2 issues soon.

Ok, so first thanks a lot for the detailed explanation and bug report. 

I've just tried on 5.1 and 5.0 both on linux and OS X, and I can't seem to be able to reproduce the bug. 
I'll see if I can get a windows vm tomorrow, and hope that it comes from windows.

```
bash-4.3# python test.py

Hello. This is printed from the main controller program.

Dropping into IPython

***Called from top level. Hit Ctrl-D to exit interpreter and continue program.
Note that if you use %kill_embedded, you can fully deactivate
This embedded instance so it will never turn on again

In [1]: %kill_embedded
Are you sure you want to kill this embedded instance? [y/N]  Y
This embedded IPython will not reactivate anymore once you exit.

In [2]:
Do you really want to exit ([y]/n)?
Leaving Interpreter, back to program.

Back in caller program, moving along...

Main program calling foo("eggs")

foo says m =  eggs
Second IPython instance.
In [1]: %kill_embedded
Are you sure you want to kill this embedded instance? [y/N]  Y
This embedded IPython will not reactivate anymore once you exit.

In [2]:
Do you really want to exit ([y]/n)?

bash-4.3# python -c 'import IPython; print(IPython.sys_info())'
{'commit_hash': u'1ba246d',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/lib/python2.7/site-packages/IPython',
 'ipython_version': '5.0.0',
 'os_name': 'posix',
 'platform': 'Linux-4.4.27-boot2docker-x86_64-with',
 'sys_executable': '/usr/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.13 (default, Dec 20 2016, 16:33:50) \n[GCC 6.2.1 20160822]'}
```

I'm a bit astonished as how this could be os-specific, but as we have a +1 from @wronglink I'm going to assume you are not the only one.

@wronglink do you experience this on windows as well ?

**Comment by Carreau** [comment]
No , forget what I said. Don't debug at 10pm in the evening.

**Comment by Carreau** [comment]
Ok, there is a misunderstanding/miscodding about the _construction_ location and the _call_ location.
The current code make assumptions and document as if construction and call where always done next to each other as it was _mostly_ done to use with the `embed()` function.

It's easy to fix (split the functionality into kill-instance and kill-location) I think kill-location is what people want. But I'll rethink that tomorrow.

Note for myself (i'm pretty sure I'll understand myself tomorrow) as it's fresh in my brain:
  - Killing location in init does not make sens as you can just store variable on self, but you still kinda-need it for loop that recreate instances.
  - Tomorrow you should be smart enough to figure out is the kill-call-locations and kill-instance-locations can be shared in the same list.
  - Yes it make sens to split the kill-instance and kill-location cause you might want to put the same instance in multiple place.
  -  Use this opportunity to implement a kill&exit.
  - Document why or deprecate empty init_sys_module.

**Comment by Carreau** [comment]
Can you have a look at #10207
