### ISSUE TITLE
Is it a bug that a list of date displays as NULL in R Jupyter notebook?

### ISSUE THREAD

**Issue by DavidBriant** [ipython/ipython#9762]
list(as.Date("2016-05-02")) displays as NULL.

How do I fix this or request for it to be fixed?

Thx

**Comment by takluyver** [comment]
It probably is a bug, but you likely need to file it on [IRkernel](https://github.com/IRkernel/IRkernel), the R backend for Jupyter.

**Comment by takluyver** [comment]
David refiled this as IRkernel/IRkernel#380, closing here.
