### ISSUE TITLE
Installed ipython 5, but no floating autocompletions?

### ISSUE THREAD

**Issue by j-bennet** [ipython/ipython#9763]
Still looks like old ipython:

<img width="579" alt="screenshot 2016-07-14 19 05 27" src="https://cloud.githubusercontent.com/assets/637013/16861507/2c779968-49f6-11e6-8c11-79f538afacd3.png">

Is there a config setting somewhere to enable floating autocomplete?

**Comment by takluyver** [comment]
Have you pressed tab? We're not using the complete as you type functionality for the moment.

**Comment by jeverling** [comment]
For me the floating box also didn't show up when using yakuake, a terminal that drops down from the top of the screen. Guess it's some overlay issue, with a regular terminal it works fine for me. Just commenting in case you use a terminal that overlays other windows too.

**Comment by takluyver** [comment]
No idea why it wouldn't work in yakuake. It's fine in Guake, so it's not something general about overlay terminals. @jonathanslenders, do you know of any terminal emulators where completions don't work?

**Comment by jeverling** [comment]
It works for me now in yakuake too, please excuse the confusion. Must have been an one-time issue with my system or layer 8 problem.

**Comment by j-bennet** [comment]
Oh, I see. I thought as-you-type is supposed to work out of the box, just like in other clis based on prompt_toolkit (pgcli, mycli).

Closing.

**Comment by takluyver** [comment]
We opted to disable complete_while_typing because it's incompatible with the up-arrow history search, which has been a feature of IPython for a long time.
