### ISSUE TITLE
AutoSave , Rename Failed.

### ISSUE THREAD

**Issue by matayru** [ipython/ipython#9767]
I am running jupyter/ipython on win7 and it sudenly will not save. When this happens, I have to uninstall anaconda and reinstall it again.

**Comment by Carreau** [comment]
Hi there, sorry you are having issues. 

This is an bug that likely belong on the https://github.com/jupyter/notebook repository. 

When this happen you likely will have a traceback/error message somewhere in the terminal, or in the browser javascript console. It would help us a lot if you can copy/past or screenshot  of these to figure out what's happening. 

Thanks!
