### ISSUE TITLE
Notebook feature requests

### ISSUE THREAD

**Issue by fperez** [ipython/ipython#977]
This is a meta-issue to list, discuss and shake out ideas for improvements to the notebook.  It can serve as a central page for users to propose ideas and discuss them; as they get more fleshed out and there's a chance of implementing one of them, we can make a separate issue (or pull request, if there's code) for it.

In our docs [we already have some items noted](https://github.com/ipython/ipython/blob/master/docs/source/development/notebook_todo.txt), so that list should be used as a starting point for the discussion.

**Comment by varnion** [comment]
I'd be really nice if we could use citations in markdown cells like those supported by pandocs-citeproc:
http://johnmacfarlane.net/pandoc/README.html#citations
with this:
~~~
    ... in a process called *Muller's Ratchet* [@Muller1964; @Haigh1978].
    .. as suggested by Drake [-@Drake1991].
    My model is based on that by @Hadany2003 who showed...

~~~
we 'd get this:
... in a process called *Muller's Ratchet* (Muller 1964; Haigh 1978).
.. as suggested by Drake (1991).
My model is based on that by Hadany and Beker (2003) who showed...

(I picked up those examples on the blog of [Yoav Ram](http://blog.yoavram.com/citations-in-markdown-using-pandoc/))

Another nice alternative would be proper latex citation syntax, but i think those were already requested.

**Comment by takluyver** [comment]
Citations are possible with syntax like this `<span data-cite='key'></span>`. See my [cite2c](https://github.com/takluyver/cite2c) extension for a way to insert and manage them automatically. For a nicer syntax, we're waiting for [CommonMark](http://commonmark.org/) to standardise a generic inline extension syntax for Markdown. We've talked to John Macfarlane, the author of pandoc, and he's heavily involved in CommonMark, so we're optimisitic about that.

**Comment by varnion** [comment]
whoa, that was fast. thanks! this syntax is a bit ugly, but your extension will save me a LOT of time. 

Now I'll be looking foward to see the progress of CommonMark =D

**Comment by bencharb** [comment]
Recover trashed cells after holding down the "d" key. I've lost many hours of work from accidentally deleting many cells because I've leaned on the "d" key too long, usually when I fall asleep at the keys. The feature could work like this: after leaning on the "d" for about one second, pause the deleting with a modal dialog, "Hit 'y' to continue deleting everything."

**Comment by takluyver** [comment]
I wonder if we can distinguish between the user pressing and holding a key versus pressing it repeatedly. Deleting a cell should ideally require pressing `d` twice, not just holding it down until it automatically repeats. I would imagine that the answer is 'not in any reliable way across different browsers', though.

Multiple undelete is already tracked as an issue: #4924

**Comment by jasongrout** [comment]
We probably can by detecting keydown and keyup events.  At least, I'm pretty sure key repeats don't trigger multiple down/up events.

**Comment by takluyver** [comment]
Yeah, but IIRC, keydown and keyup events are where browser compatibility
goes south.

**Comment by minrk** [comment]
For reference: repeats appear to result in consecutive keydown events without keyup events in between (at least on Chrome + OS X).

If our keyboard shortcuts used keypress instead of keydown, the vast majority of the compatibility and weirdness of browsers and keyboards would go away. There's one caveat, though: we still must use keydown for non-text shortcuts (mainly esc).

**Comment by bencharb** [comment]
Instead of watching keystrokes, could you put a listener on the delete event itself that splashes a nag to when it sees repeated deletes?

**Comment by fbrundu** [comment]
I think it would be nice on big desktop screens to have a two pages layout of one notebook, what do you think?

**Comment by ellisonbg** [comment]
Yep :)

On Tue, Mar 17, 2015 at 11:18 AM, Francesco <notifications@github.com>
wrote:

> I think it would be nice on big desktop screens to have a two pages layout
> of one notebook, what do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/977#issuecomment-82406089>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by brianbreitsch** [comment]
Hello! I'm not sure if this is already available, but is there a way we can have a javascript hook when the notebook text editor gets loaded. Right now I think custom.js only let's you hook into when notebooks get loaded, but I could be wrong.

I'm trying to do this so I can add a codemirror keymap option to the edit dropdown.

**Comment by brianbreitsch** [comment]
It looks like we just need to add  `events.trigger('app_initialized.EditorApp');` to `main.js` under `edit`.
Question: should the event be 'app_initialized.EditorApp' or something else?

**Comment by l00mi** [comment]
Is there already a Feature Request for Block comment/uncomment?

**Comment by dsblank** [comment]
Block comment/uncomment is handled by the editor (CodeMirror). As that is language-dependent, that could be tricky. But control+/ does comment out the block one line at a time, and is very robust... even if the user's selection is a bit off. In any event, CodeMirror would be the place to make the request.

**Comment by l00mi** [comment]
Yes, just discovered that.. unfortunately it seems only to work on US Keyboard layout..

**Comment by tmearnest** [comment]
#### Tabbed notebooks

I was thinking that it would be really nice to have separate "pages" or "tabs" associated with a notebook. These would be essentially subnotebooks that are all connected to the same kernel. The main idea is that it would be easy to separate concerns within the document, e.g. one page for imports, initializations, data loading, another page for defining common functions, then a page for the main calculations. Or if there are multiple parts to the calculation that are logically separable, these could go to different tabs as well. I've been finding myself working with large notebooks with tons of output and it gets cluttered really fast. This kind of organization would fix that problem.

**Comment by takluyver** [comment]
We actually had a plan to have worksheets in notebooks - it was even reflected in earlier versions of the file format. But we didn't do it, and we decided that we probably won't, although we're open to someone doing it as an extension.

We know that working with long notebooks is awkward, and we do have some plans to address this, like collapsible sections or tables of content.

**Comment by MInner** [comment]
Hello everyone! I have no idea of how it could be implemented, but it feels like a somewhat critical, at least I face this problem _very_ often. If something occasionally outputs some huge chunk of text into it's output then chrome (and I guess the same thing applies to other browsers too) becomes super-unresponsive (consumes entire CPU and stuck) trying to render all that text in a cell output. The most unpleasant part is that if you close this unresponsive tab and try to reopen the notebook, you'd very likely to get it corrupted or too huge to be successfully opened :(

Probably, if you could add some internal super-simple profiling thing that could detect (e.g. too much time between two sequential timeout callback calls) those sucks, stop pushing output to notebook cell and suggest user to clear cell (or continue)?

I personally suffer from that effect a lot :( That would be great if you could solve it somehow.

**Comment by niallrobinson** [comment]
I've suffered from this too. It would be lovely to stop this happening. Especially as the only way to recover is to hand edit the notebook!

**Comment by InonS** [comment]
Hi all!
After making what I consider a reasonable effort to find a duplicate, I've decided to chip in with a major request. I know that [**Jupyter**](https://github.com/jupyter/notebook/issues/163) is taking over some of this stuff, but I find it *incredibly detrimental to my productivity* that I can't **refactor code in an IPython notebook**. To do so I either have to edit the ipynb file as text, or to export the whole thing to python code, which defeats the purpose of IPython in the first place. I've even looked at some of the python IDEs (PyDev, PyCharm, Spyder) but I think that IPython is only used there as an interactive console, and the entire concept of the notebook is lost.
Firstly, I'd request a "*rename*" refactor. Later on, maybe some object-oriented stuff like *generation of accessor & mutator methods*. All of this stuff seems pretty straightforward for the most part, and I'd hate to think of the IPyhton project loosing steam just because productivity is handicapped because of it.
Many thanks to all the developers who make this project happen!

**Comment by rossant** [comment]
@InonS [ipymd](https://github.com/rossant/ipymd) might be a partial solution: you can replace the ipynb format by a Markdown document, which makes refactoring easier in a good text editor

**Comment by InonS** [comment]
@rossant Thanks! I took a gander, and confirm that the notebookfile file format probably could and should be more portable, e.g. Markdown.
Still, anything that forces me to do my refactoring in an external text editor is a setback, as far as I'm concerned. A user must be able to do all the development in one environment, this includes both running interactively and refactoring.
Thank you for your feedback!

**Comment by alvinwt** [comment]
Is there a way to run my scripts in the notebooks that persist after closing the browser? I expect that for simulations that run for days, it would be a good feature to have a *screen* like feature to detach the notebook and let the kernel run in the background without having the browser open. I use both the Python and IRKernel for my work which requires running the jobs on servers from my laptop, so leaving the browser on is not an option. This is a feature that would be useful to many people for sure.

**Comment by varnion** [comment]
@alvinwt this would be SO AWESOME. the only way I know is using the ipython nbconvert from ipynb to ipynb, but this is a non interactive solution.

**Comment by InonS** [comment]
@alvinwt, for "running the jobs on servers" non-interactively (i.e. batch processing), would you consider [ipcluster](https://ipython.org/ipython-doc/stable/parallel/index.html)?
@varnion, I think I don't understand how your proposal addresses the OP's concern. Could you please explain?

**Comment by alvinwt** [comment]
@InonS I would try that out if my script is in Python and I have been struggling with understanding the documentation. Currently I work a lot in the IRKernel and it would be nice if the feature is not limited to Python kernels.

**Comment by orome** [comment]
>I'd like to be able to rearrange multiple cells at at a time by dragging them. It'd be nice if you could even do this between notebooks. Sometimes I find that code for data analysis would make more sense in a different notebook, but it sucks to copy/paste it all.

This seems to me like an essential feature that I was hoping would appear eventually. It never takes much time working in a notebook before I realize that things need to be rearranged, and then I hit a dead end and need to switch to a text editor. The omission of this feature alone (at least just multiple selection and rearranging) shapes my entire workflow: start in a notebook and quickly (after a few hours) get so constrained by the inability to move or delete groups of cells that I switch to a conventional text editor.

**Comment by act65** [comment]
Hey, new to this sort of thing (git etc...). I just wanted to add something to the wishlist that you guys seem to keep. 

Can we have a live/interactive version of the markdown preview - like Mou does

![screen shot 2016-02-27 at 9 30 52 am](https://cloud.githubusercontent.com/assets/6046380/13364641/d18dfe94-dd34-11e5-8309-3f0dda1a7c78.png)
