### ISSUE TITLE
Pygments exposure in IPython

### ISSUE THREAD

**Issue by klonuo** [ipython/ipython#9772]
While playing with some code in IPython, I noticed that it doesn't work in editor. For example:

```
>ipython
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pygments

In [2]: [p for p in pygments.styles.get_all_styles()]
Out[2]:
['manni',
 'vs',
 'native',
 'fruity',
 'algol',
 'colorful',
 'vim',
 'autumn',
 'default',
 'trac',
 'pastie',
 'murphy',
 'rrt',
 'paraiso-light',
 'bw',
 'xcode',
 'friendly',
 'paraiso-dark',
 'algol_nu',
 'tango',
 'borland',
 'monokai',
 'emacs',
 'perldoc',
 'igor',
 'lovelace']
```

while in regular Python:

```
>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygments
>>> [p for p in pygments.styles.get_all_styles()]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pygments' has no attribute 'styles'
>>>
```

Why is this and are there other Python modules that can lead to similar ambiguation?

**Comment by takluyver** [comment]
`pygments.styles` is a submodule which isn't loaded by default. However, because IPython uses pygments, the submodule is already loaded when you use pygments inside IPython. So it's a quirk of Python's import system, and if there are other modules affected, they will be the ones that IPython loads.

**Comment by klonuo** [comment]
Ok. `dir()` doesn't seem to reveal anything related. Is it possible to check what is loaded?

**Comment by takluyver** [comment]
`sys.modules` shows you all the modules that are loaded in the current interpreter.

**Comment by Carreau** [comment]
Yep, that's a python thing, not an IPython one. There is not much we can do about that and it will be true for many other modules.
