### ISSUE TITLE
Pretty printing PyPy dicts not as "dictproxy"

### ISSUE THREAD

**Issue by danilobellini** [ipython/ipython#9776]
I'm using IPython pretty printer in my plugin for running doctests with a custom representation printer. It actually works fine in CPython, but it prints all PyPy dicts as proxies.

In CPython 2.7.12 a dict isn't a dictproxy, and it's well known that they appear with curly brackets:

``` python
In [1]: {"this": 1, "is": "a", "test": None}
Out[1]: {'is': 'a', 'test': None, 'this': 1}

In [2]: import types

In [3]: types.DictProxyType is dict
Out[3]: False
```

But in PyPy 5.3.1 (Python 2.7.10), a dict appears as a dictproxy, and these types are actually the same w.r.t. the types module:

``` python
In [1]: {"this": 1, "is": "a", "test": None}
Out[1]: <dictproxy {'is': 'a', 'test': None, 'this': 1}>

In [2]: import types

In [3]: types.DictProxyType is dict
Out[3]: True

In [4]: dict.__name__
Out[4]: 'dict'

In [5]: repr(_1)
Out[5]: "{'this': 1, 'is': 'a', 'test': None}"
```

The last outputs suggests that the assignment to ``_type_pprinters[types.DictProxyType]`` in IPython.lib.pretty replaces the dict printer. Shouldn't that assignment be done with the setdefault method instead?

**Comment by Carreau** [comment]
Hi there, 

Thanks for the investigation, and the detail explanation. Sorry if my question is dumb, I'm  jetlagged and it's late. If in PyPy dict == dictproxy, we have no way to differentiate both? So I'm not sure what you want to print? 

Also we don't overwrite  `repr()`you have to try displaying with `IPython.display.display(object)` that will pick up the `_repr_pretty_`:

```
In [1]: d =  {"this": 1, "is": "a", "test": None}

In [2]: from IPython.display import display

In [3]: display(d)
<dictproxy {'is': 'a', 'test': None, 'this': 1}>
```

Nice to see SO using IPython on pypy BTW :-)

**Comment by Carreau** [comment]
Oh ! I think I know what you mean. 

Yes, make sens, do you want to send a PR ?

**Comment by danilobellini** [comment]
I'll send the PR. I was trying to find a standardized way to test the code, I found one but I'm not sure if it's right. I modified tox.ini to be able to test with PyPy installing the test requirements described in setup.py, but I'm not understanding the test suite (tox.ini and .travis.yml have different ways to run them and there's no setup.py test command). I managed to run tests with tox calling ``iptest --all``, but a lot of tests fail in PyPy.

``` bash
$ tox -e pypy
pypy recreate: /home/danilo/code/github-ipython/ipython/.tox/pypy
[...]
FAILED (SKIP=14, errors=41, failures=6)
[...]
FAILED (SKIP=5, errors=2, failures=4)
[...]
FAILED (SKIP=8, failures=2)
[...]
______________________________________________________________________
Test suite completed for system with the following information:
IPython version: 5.1.0.dev
IPython commit : 58a2cf4 (installation)
IPython package: ~/code/github-ipython/ipython/.tox/pypy/site-packages/IPython
Python version : 2.7.10 (7e8df3df9641, Jun 28 2016, 23:19:52)[PyPy 5.3.1 with GCC 6.1.1 20160602]
sys.executable : ~/code/github-ipython/ipython/.tox/pypy/bin/pypy
Platform       : Linux-4.6.4-1-ARCH-x86_64-with-glibc2.2.5

Tools and libraries available at test time:
   pygments sqlite3

Tools and libraries NOT available at test time:
   matplotlib

Status: ERROR - 3 out of 7 test groups failed (core, lib, utils). Took 95.694s.

You may wish to rerun these, with:
  iptest core lib utils
```

When I apply the proposed change, only this line changes:

```
FAILED (SKIP=5, errors=2, failures=4)
```

it becomes:

```
FAILED (SKIP=5, errors=2, failures=1)
```

Which means it's something that is already being tested somewhere. Should I add some dict representation printer specific test on test_pretty.py, and some other test for dictproxy (that skips on PyPy)? If so, how do I create a dictproxy?

Testing on these is ok no matter the single line change (all with matplotlib, pygments and sqlite3, but PyPy which is without matplotlib):

```
$ tox -r
[...]
Python version : 2.7.12 (default, Jun 28 2016, 08:31:05) [GCC 6.1.1 20160602]
[...]
Python version : 3.3.6 (default, Jun 22 2016, 03:31:41) [GCC 6.1.1 20160602]
[...]
Python version : 3.4.4 (default, Jun 22 2016, 03:53:42) [GCC 6.1.1 20160602]
[...]
Python version : 3.5.2 (default, Jun 28 2016, 08:46:01) [GCC 6.1.1 20160602]
[...]
Python version : 2.7.10 (7e8df3df9641, Jun 28 2016, 23:19:52)[PyPy 5.3.1 with GCC 6.1.1 20160602]
[...]
___________________________________ summary ____________________________________
  py27: commands succeeded
  py33: commands succeeded
  py34: commands succeeded
  py35: commands succeeded
ERROR:   pypy: commands failed
```

Should I add my modified tox.ini to the PR? And a modified .travis.yml (adding it to allow_failure by now)? Or just a single line PR with the proposed change?

**Comment by minrk** [comment]
@danilobellini to run the tests locally (anywhere, regardless of Python version or implementation), generally do:

    pip install ipython[test]
    iptest

The tox config is used by nobody that I'm aware of, and should perhaps be removed, as its presence gives the misleading impression that it is supported or maintained.

We haven't run CI on PyPy, so there are likely various failures due to minor issues. If you want to go through the test suite and find PyPy failures, that would be great! But adding it to allow_failures along with nightly is a sensible start.
