### ISSUE TITLE
IPython.core.debugger.Tracer tab-complete

### ISSUE THREAD

**Issue by papachoco** [ipython/ipython#9781]
In the iPython 4.2.x series calling 

from IPython.core.debugger import Tracer; Tracer()()

allows  tab-completion .. This feature seems to have disappeared in iPython 5.x

Thanks

Carlos

**Comment by takluyver** [comment]
Can you try with `IPython.terminal.debugger` instead of `IPython.core.debugger`?

**Comment by takluyver** [comment]
I've just noticed that there's no convenient way to start the debugger by importing from `IPython.terminal.debugger`. We should make something like a `set_trace()` function or a `Tracer()` class.

**Comment by Carreau** [comment]
https://github.com/ipython/ipython/pull/9731 also will remove the Tracer() class for a simple API, that you can alredy use.
