### ISSUE TITLE
IPython 5.0.0 always returns 0 for readline.get_current_history_length()

### ISSUE THREAD

**Issue by abhishek-anand** [ipython/ipython#9783]
readline history length is always returning 0, this was not an issue in 4.2.1 or 3.2.3. This is despite the history length set to -1, which the[ Python docs](https://docs.python.org/2/library/readline.html#history-file) says should set the history length to infinite. Is this behavior expected?

**IPython vs Python**

<img width="766" alt="screen shot 2016-07-20 at 4 11 41 pm" src="https://cloud.githubusercontent.com/assets/2356550/16984529/2a266576-4e98-11e6-8d66-fd2467da42c6.png">

**Comment by takluyver** [comment]
IPython 5 does not use readline, so this behaviour is expected. You can find the length of the history in the current session like this:

```python
len(get_ipython().history_manager.input_hist_raw) - 1
# -1 because there's an empty first entry to make the h[1] the first real line
```

Or you can get the we've given to prompt_toolkit, which is more closely equivalent to the old readline history, like this:

```python
len(get_ipython().pt_cli.application.buffer.history)
```
