### ISSUE TITLE
IPython 5 + Qt breakage: no QApplication gets created, so inputhook does nothing.

### ISSUE THREAD

**Issue by zpincus** [ipython/ipython#9784]
### Problem
In IPython 4,  `%gui qt` starts up a `QApplication` automatically if one isn't already running, and returns it to the user. This does not happen in IPython 5.

This is a problem because unless a `QApplication` instance has been created, the Qt inputhook doesn't do anything. The relevant code for IPython 5, in [terminal/pt_inputhooks/qt.py](https://github.com/ipython/ipython/blob/master/IPython/terminal/pt_inputhooks/qt.py#L4), looks like this:
```python
def inputhook(context):
    app = QtCore.QCoreApplication.instance()
    if not app:
        return
```

In IPython 4, `%gui qt` winds up (through a complex chain of events) executing [lib. inputhookqt4.create_inputhook_qt4()](https://github.com/ipython/ipython/blob/master/IPython/lib/inputhookqt4.py#L66), which does the following:
```python
        app = QtCore.QCoreApplication.instance()
        if app is None:
            app = QtGui.QApplication([" "])
```
Moreover, in IPython 4, `%gui qt` returns this `QApplication` instance to the user.

None of this happens in IPython 5. Presumably this change was not intentional, and enabling the Qt GUI in IPython 5 should still create a `QApplication`? (There is (ancient?) code in [lib/guisupport.py](https://github.com/ipython/ipython/blob/master/IPython/lib/guisupport.py#L109) that returns or creates a `QApplication`, so someone could use that if they want.)

### Example
The following works fine in IPython 4:
```python
%gui qt
from PyQt5.QtWidgets import QWidget # or PyQt if you use Qt4
w = QWidget()
w.setGeometry(300, 300, 250, 150)
w.setWindowTitle("Test")
w.show()
```
but breaks horribly in IPython 5. This fixes things:
```python
%gui qt
from PyQt5.QtWidgets import QApplication, QWidget
app = QApplication([''])
w = QWidget()
w.setGeometry(300, 300, 250, 150)
w.setWindowTitle("Test")
w.show()
```

Using a virtual environment, one can test this pretty simply by using `pip` to install IPython 4 vs. 5, and pyqt5 via a wheel (statically linked to the Qt libs) that has recently appeared. This is much easier than having fuss with hand-building PyQt etc.

### Resolution 
I would submit a PR, but first I'd like to know where to put the relevant initialization code. 

In IPython 5, factory-functions like `create_inputhook_qt4()` are not employed. Instead, all that happens when [terminal.pt_inputhooks.get_inputhook_func()](https://github.com/ipython/ipython/blob/master/IPython/terminal/pt_inputhooks/__init__.py#L33) is run is that the relevant module in `terminal/pt_inputhooks` gets imported and the `inputhook` function therein is returned. 

Should something like the following be placed at the module-level in [terminal/pt_inputhooks/qt.py](https://github.com/ipython/ipython/blob/master/IPython/terminal/pt_inputhooks/qt.py), such that it gets run on import?
```python
app = QtCore.QCoreApplication.instance()
if app is None:
    app = QtGui.QApplication([''])
```
And if so, should the `inputhook` code just use this module-level `app` variable, or still look it up each time it's called, as it does now? Somehow, having module-level initialization seems a bit gross though.

Alternately, `get_inputhook_func()` could check the module for an `initialize_gui()` function and run that first. Further, if desired, `get_inputhook_func()` could return the result of `initialize_gui()` along with the `inputhook` function, which would allow the QApplication instance to be returned to whoever calls `%gui qt`, as in IPython 4. This seems like a sensible approach, but advice would be welcome. 

Note also that if the `QApplication` instance ever gets deleted, PyQt doesn't keep a reference to it around, so `QtCore.QCoreApplication.instance()` will return `None`. So in any case, one needs to be careful that the instance gets stashed somewhere...

**Comment by Carreau** [comment]
Ouch. I'm unsure having the `%gui <>` returning  an object was meant to be and/or if it should, `%gui` is just here to integrate with eventloop. @takluyver ?

I'm unsure about creating the application in the inputhook. I think that asking the developer to create an Application by himself is reasonable.

**Comment by zpincus** [comment]
Regarding the `QApplication`: do note that creating such an instance is essentially just spinning up a Qt eventloop. It appears that most of the other modules in  `terminal/pt_inputhooks` either construct an eventloop (e.g. glut, pyglet) or rely on an always-available default eventloop procedure or object (gtk, osx, tk). Only qt (and maybe wx, it's hard to tell?) require something external to be created before the `%gui` integration can work.

Moreover, at least for qt, making a `QApplication` instance has been the behavior since well before the 4.x series. So not doing so is definitely a breaking change. It took me the better part of a day to figure out why things were going wonky, and I'm pretty familiar with the IPython / Qt internals (from my spelunking with the last IPython major release, which also broke this stuff :) -- #8757 / #8829). At a minimum some clear documentation about these changes would be helpful.

Also, on IPython 4, one could use matplotlib with qt just by doing `%gui qt` and then importing and using matplotlib. Now because of this change, it only works via `%matplotlib qt`. I know the latter is the recommended way, but this is liable to cause some additional confusion.

**Comment by takluyver** [comment]
Thanks for the detailed investigation; I've created #9789 which makes your example work for me.

I'm still a bit in two minds about this. Other than matplotlib, I'm not quite sure what's a 'natural' scenario for creating a Qt application interactively. Is it literally building a GUI at the prompt, testing a GUI written into a regular file, or using other things like matplotlib which create a GUI as part of library operation?

Qt normally requires you to create a QApplication, so by bypassing that requirement we risk confusing users about what's really going on, and making situations where code runs differently in IPython to plain Python. On the other hand, whatever the arguments against what we did before, consistency is always worth considering.

**Comment by zpincus** [comment]
I'm not sure I really understand the objections to the old behavior of creating a `QApplication`. Isn't the whole point of the GUI integration is to make GUI code run differently in IPython vs. plain-Python? (I.e. to shift responsibility for setting up an eventloop from the user code to IPython.)

To start an eventloop in Qt, a user generally has to create a `QApplication` and then call its `exec_()` method. The Qt integration in IPython 4.x does both tasks (unless the user had already made a `QApplication`, which would get used instead). Currently, IPython 5 requires that a user do the first task and then IPython does the second. Note that **either way**, things in IPython are different from the plain-Python case. The IPython 4.x solution seems to me to be a bit more self-consistent, though.

Moreover, I don't really see how this differs from any of the other GUI integration code. Every GUI toolkit usually requires that an eventloop get created and started as part of starting a GUI program -- yet in every instance, the IPython GUI integration both creates/initializes and runs the eventloop. (It's just that the Qt implementation forgot to take care of all of the usual initialization steps, and unsurprisingly broke as a result.)

For example, look at the code in `terminal/pt_inputhooks/glut.py`: this is **all** stuff that a user generally has to do in their own `main()` function. Does bypassing the requirement to call `glut.glutInit(sys.argv)` and `glut.glutInitDisplayMode(glut_display_mode)` risk confusing users about what's really going on? 

Or would it be more confusing to require that a user run `glut.glutInit(sys.argv)` before `%gui glut` will work correctly? And if that is unacceptable (I certainly think so), is there any meaningful difference from the proposed requirement that a user run `app = QApplication(sys.argv)` before `%gui qt` will work correctly?

**Comment by takluyver** [comment]
> Isn't the whole point of the GUI integration is to make GUI code run differently in IPython vs. plain-Python? (I.e. to shift responsibility for setting up an eventloop from the user code to IPython.)

Not precisely. The point of the GUI integration is to integrate the event loop with the IPython interface, so that you can have both an interactive GUI and an interactive prompt at the same time. That doesn't necessarily imply that IPython has to set up an event loop; it still works if the user creates the event loop and IPython integrates with it.

I'm ambivalent about this, though, and as such I'd probably lean towards preserving the behaviour from previous versions, as you're asking. Maybe @fperez has useful input.

**Comment by tacaswell** [comment]
I am in favor of IPython creating the `qApp` if needed.

**Comment by takluyver** [comment]
Thanks, that's a useful data point.

**Comment by zpincus** [comment]
> > Isn't the whole point of the GUI integration is to make GUI code run differently in IPython vs. plain-Python? (I.e. to shift responsibility for setting up an eventloop from the user code to IPython.)

> Not precisely. 

Sorry, I mis-wrote. This should have been "(I.e. to shift responsibility for **running** an eventloop from the user code to IPython.)" Regardless, it remains true that code that uses GUI integration in IPython will necessarily look and work a little differently from code that does the same task in plain Python. As such, I am not sure how a goal can be to try to avoid "making situations where code runs differently in IPython to plain Python".

Probably the discussion should broaden to the general policy about what the GUI integration should guarantee (or aim to guarantee) for all of the toolkits, so that things can be as consistent as possible. **That is, should `gui <>` aim to guarantee that an eventloop, if already set up, will be integrated with IPython? Or should it aim to guarantee that an eventloop will be set up and run in a way that integrates with IPython?** As far as I understand it, the general behavior of IPython has always been much closer to the latter than the former.

Currently, the GUI integration code does perform necessary initialization and/or eventloop setup for GLUT and GTK. I am pretty certain that no additional steps are required from either IPython or the user for the Pyglet and Tk integration. So for all of those toolkits, `gui <>` will work without any additional steps beyond creating widgets. I don't know enough about GTK3, WX, or OS X to say one way or the other.

**Comment by Carreau** [comment]
I agree that there is a difference in conception of what `gui <>` does, in particular it shoudl be taken into account that `gui` is something that you can set in  you configuration file, so it can be persistent for all your sessions. And in that case, there is no way to access what `%gui` returns. 

The inputhook make IPython code ready to work with an eventloop if present by timesharing event processing. It should likely not guarantee that the event loop should be there. 

I'm not that much familiar with glut/tk/wx, but there might be technical reasons why in these specific cases we do start the eventloop. 

Anyway let's restore the creation of the QtApplication and  discuss further what would be the policy for all the eventlopps.
