### ISSUE TITLE
IPython5 on Windows 7 failed to plot (not inline)

### ISSUE THREAD

**Issue by Morriaty-The-Murderer** [ipython/ipython#9787]
HI
I've recently upgraded IPython 5
```bash
conda update ipython
conda update jupyter_console
```

And this is my sys info
```
 'commit_source': 'installation',
 'default_encoding': 'cp936',
 'ipython_path': 'C:\\Users\\Administrator\\AppData\\Local\\Continuum\\Anaconda2\\lib\\site-packages\\IPython',
 'ipython_version': '5.0.0',
 'os_name': 'nt',
 'platform': 'Windows-7-6.1.7601-SP1',
 'sys_executable': 'C:\\Users\\Administrator\\AppData\\Local\\Continuum\\Anaconda2\\pythonw.exe',
 'sys_platform': 'win32',
 'sys_version': '2.7.11 |Anaconda 2.5.0 (32-bit)| (default, Mar  4 2016, 15:18:41) [MSC v.1500 32 bit (Intel)]'}
```

After update, I found it would fail to plot in jupyter QTconsole with magic `%pylab`, which resulted in error msg `Kernel died, restarting`.

And I've tried other ways to plot , which were all fine:
Run in CPython interpreter or run as a script with `from pylab import *` were both fine.
Run in Jupyter QTconsole with magic `%pylab inline` also worked.

**Comment by takluyver** [comment]
When you run `%pylab`, does it print a message saying which backend you're using?

**Comment by Morriaty-The-Murderer** [comment]
Hi, @takluyver 
This is the output when I typed `%pylab`
```
In [1]: pylab
Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib
```

**Comment by takluyver** [comment]
And just to make sure, can you ensure some other packages are up to date:

```
conda update qtconsole pyqt matplotlib ipykernel
```

**Comment by Morriaty-The-Murderer** [comment]
Hi, @takluyver 
I've updated all the packages you listed, but the issue was still the same as before.

**Comment by takluyver** [comment]
I'm casting around for ideas, because I don't know what's wrong.

* Can you replicate this in other environments, e.g. in `ipython` in a command prompt, or `jupyter console`?
* If you start the qt console from a command prompt, is there any error message displayed in that command prompt when the kernel dies?

**Comment by Morriaty-The-Murderer** [comment]
Hi @takluyver 
I always opened jupyter qtconsole with a Windows shortcut, so I missed the error msg.

If I start the qt console from a command prompt, the error msg was the same as issue [#157](https://github.com/ipython/ipykernel/issues/157)
```
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\tornado\ioloop.py", line 604, in _run_callback
    ret = callback()
  File "C:\Users\Administrator\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\ipykernel\kernelbase.py", line 258, in enter_eventloop
    self.eventloop(self)
  File "C:\Users\Administrator\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\ipykernel\eventloops.py", line 73, in loop_qt4
    _notify_stream_qt(kernel, s)
  File "C:\Users\Administrator\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\ipykernel\eventloops.py", line 23, in _notify_stream_qt
    from IPython.core.interactiveshell import NoOpContext as context
ImportError: cannot import name NoOpContext
```

**Comment by takluyver** [comment]
Oh, right, that error looks familiar. Sorry about that. We're going to put out IPython 5.1 soon to fix it.

**Comment by Morriaty-The-Murderer** [comment]
Hi, @takluyver 
I see the new release and upgrade ipykernel to 4.4. All goes fine.
Thank you!

**Comment by takluyver** [comment]
Great :-)
