### ISSUE TITLE
Sphinx directive and memory usage

### ISSUE THREAD

**Issue by saimn** [ipython/ipython#9790]
We use the sphinx directive to generate many plots and images for several documentation pages, with some data that needs a lot of memory, and it seems that the memory is always increasing during the Sphinx build (which is an issue when we reach the RAM limit of readthedocs, 1Gb). Which means that, when moving from one rst file to another, the memory used by the IPython history from the previous page is not released.
I tried a few hacks, like settings some objects to None or calling `%reset-f` at the end of my rst files, that seems to help a bit, but I still end the build at ~800Mb of RAM usage.

So trying to look more detail at the code, I found a place where the change of rst file is detected to reset the execution count (https://github.com/ipython/ipython/blob/master/IPython/sphinxext/ipython_directive.py#L898), and tried to add a `self.shell.IP.reset()` but again it doesn't help.

Any idea on what can retain the objects in memory and what could be done to start with a fresh IPython shell at the beginning of each rst file ?

**Comment by takluyver** [comment]
Maybe it should be deleting and recreating the shell instance. We don't use `ipython_directive` in our own docs, so I'm not very familiar with it. @tacaswell @mdboom and @chebee7i have all done stuff with it (relatively) recently.

**Comment by saimn** [comment]
Yes, but the `InteractiveShell` is a singleton. It seems that I can force recreating the shell instance with `.clear_instance()` but again it does not any effect on the memory usage. 
```
        if not self.state.document.current_source in self.seen_docs:
            print('>>>>>', self.state.document.current_source)
            self.shell.IP.reset()
            self.shell.IP.clear_instance()
            self.shell = EmbeddedSphinxShell(exec_lines)
            self.shell.directive = self
 ```
There must be something else ?

**Comment by Carreau** [comment]
Hum, maybe the history should be turned off with the directive ?

**Comment by saimn** [comment]
Oh, it seems actually to be due to some quirk with `resource.getrusage(resource.RUSAGE_SELF)` !
This [post](http://fa.bianp.net/blog/2013/different-ways-to-get-memory-consumption-or-lessons-learned-from-memory_profiler/) shows some difference in the memory usage from psutil and the resource module: "*Notably it seems to differ when objects have been recently liberated from the python interpreter*". And if I compare the two on my sphinx build I get much better result from psutil (and coherent with htop, which I forgot to look at before ...):
https://gist.github.com/saimn/ac795656b7d53cc2625276ee48caa213
(For each line executed the 1st figure is from resource and the second from psutil)
So it seems there is no issue after all, sorry for the noise :/

**Comment by chebee7i** [comment]
Just confirming: Are any modifications necessary to keep memory usage down?

**Comment by saimn** [comment]
@chebee7i - Now that I have a more reliable memory measurement, it seems that we still need to end each rst file closing all figures, and doing a `%reset`. With this I end the build at 370Mb of RAM, versus ~1Gb without. But I don't know if there is a good way to handle this directly in the extension.

```
.. ipython::
   :suppress:

   In [4]: plt.close("all")

   In [4]: %reset -f
```
