### ISSUE TITLE
Segmentation fault opening IPython 5.0 on alpine

### ISSUE THREAD

**Issue by amancevice** [ipython/ipython#9797]
I'm running into a segmentation fault when trying to open `ipython` on alpine linux with Python2.7 installed.

Prequisites:
* Install Docker (I am running on Docker OS X)

Steps to reproduce:
* `docker run --rm -it alpine sh` Open a shell in alpine linux
* `apk-add --no-cache python-dev py-pip` Add python and pip packages
* `pip install ipython` Install IPython 5.0
* `ipython --log-level DEBUG` Run IPython in DEBUG mode

Output:
```
[TerminalIPythonApp] IPYTHONDIR set to: /root/.ipython
[TerminalIPythonApp] Using existing profile dir: u'/root/.ipython/profile_default'
[TerminalIPythonApp] Searching path [u'/', u'/root/.ipython/profile_default', '/usr/local/etc/ipython', '/etc/ipython'] for config files
[TerminalIPythonApp] Attempting to load config file: ipython_config.py
[TerminalIPythonApp] Looking for ipython_config in /etc/ipython
[TerminalIPythonApp] Looking for ipython_config in /usr/local/etc/ipython
[TerminalIPythonApp] Looking for ipython_config in /root/.ipython/profile_default
[TerminalIPythonApp] Looking for ipython_config in /
Python 2.7.12 (default, Jun 29 2016, 08:57:23) 
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

[TerminalIPythonApp] Loading IPython extensions...
[TerminalIPythonApp] Loading IPython extension: storemagic
[TerminalIPythonApp] Starting IPython's mainloop...

Segmentation fault
```

This works on Python3 but unfortunately that doesn't help me as not all my packages are updated to work on Python3.

**Comment by amancevice** [comment]
I should add that I've also tried adding the `alpine-sdk` package which installs things like `g++` and `make` with no luck.

**Comment by takluyver** [comment]
In general, IPython cannot be directly responsible for segfaults, because it's pure Python code. So we must be triggering a bug in e.g. Python or sqlite. Try inserting more debugging print statements to see how far it gets before crashing.

**Comment by willingc** [comment]
Looking at the [Alpine issues](https://bugs.alpinelinux.org/projects/alpine/issues) there seems to be several recent segfault issues reported with Alpine.

**Comment by amancevice** [comment]
Interesting, I'll try an older version of alpine. Thanks, @willingc

**Comment by xeor** [comment]
This problem have been haunting me for a couple of days as well. Oddly enough, the latest `alpine:3.4` you get from `docker run -it python:2-alpine sh` works like a charm. Running `pip install ipython && ipython` doesnt give a seg-fault.

> / # cat /etc/os-release
> NAME="Alpine Linux"
> ID=alpine
> VERSION_ID=3.4.0
> PRETTY_NAME="Alpine Linux v3.4"
> HOME_URL="http://alpinelinux.org"
> BUG_REPORT_URL="http://bugs.alpinelinux.org"

They compile python from source ([Dockerfile](https://github.com/docker-library/python/blob/master/2.7/alpine/Dockerfile)).

I tried compiling python as they do, following more or less the `Dockerfile`, but still ended up with a segfaulting ipython.. I probably missed something, but compiling Python on alpine:3.4 didn't do it.

**Some testing**

Basically `apk --no-cache add py-pip && pip install ipython && ipython` with some variations..

* `alpine:3.3` -  didn't work
* `alpine:3.2` -  didn't work
* `pip install 'ipython<=5'` starts ipython `4.2.1`


While researching more, I found https://bugs.alpinelinux.org/issues/5981 which points to a fix @ https://github.com/jonathanslenders/python-prompt-toolkit/pull/364, which explains what is causing this error.

Basically, a version of `fcntl.ioctl` `fcntl.ioctl(fileno, termios.TIOCGWINSZ, buf, True)` doesn't play nice, and `cntl.ioctl(fileno, termios.TIOCGWINSZ, buf)` should be used.

So, I think the most proper work around for now (while we wait for the new `python-prompt-toolkit` version to propagate is to pip install https://github.com/jonathanslenders/python-prompt-toolkit/archive/master.zip. I just tested it, and it works perfectly! :)

**Comment by amancevice** [comment]
Confirmed this works for me as well! Thanks for this, I was able to get deep enough into the stack that I thought the bug might be in prompt_toolkit but I wasn't able to isolate it.

Here is a Dockerfile that got me where I wanted:

```Dockerfile
FROM alpine
RUN apk add --no-cache python-dev py-pip
RUN pip install https://github.com/jonathanslenders/python-prompt-toolkit/archive/master.zip
RUN pip install ipython
CMD ipython
```

**Comment by willingc** [comment]
@xeor Thanks for your update! I'm glad it's working for @amancevice too.

**Comment by amancevice** [comment]
For anyone else having this problem, a new version of [prompt-toolkit](https://github.com/jonathanslenders/python-prompt-toolkit) has been released and fixes this issue.

**Comment by willingc** [comment]
@amancevice Just to clarify for everyone: If one upgrades to the newest version of prompt-toolkit, then no other changes need to made. Correct?

**Comment by amancevice** [comment]
@willingc correct
