### ISSUE TITLE
Tab-completion raises exception

### ISSUE THREAD

**Issue by invisibleroads** [ipython/ipython#9798]
Not sure whether this is an issue with IPython 5.0.0 or pyramid_ipython 0.1, but tab-completion raises an exception when trying to tab-complete the `transaction` module.
1. pip install -U ipython pyramid_ipython transaction
2. pshell development.ini
3. import tran<TAB>    
```
   In [5]: import tranException in thread Thread-127:
   Traceback (most recent call last):
   File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
       self.run()
   File "/usr/lib64/python2.7/threading.py", line 766, in run
       self.__target(_self.__args, *_self.__kwargs)
   File "/usr/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 835, in run
       completions = list(buffer.completer.get_completions(document, complete_event))
   File "/usr/lib/python2.7/site-packages/IPython/terminal/ptutils.py", line 24, in get_completions
       cursor_pos=document.cursor_position_col
   File "/usr/lib/python2.7/site-packages/IPython/core/completer.py", line 84, in comp
       text, matches =  complete(_args, *_kwargs)
   File "/usr/lib/python2.7/site-packages/IPython/core/completer.py", line 1186, in complete
       custom_res = self.dispatch_custom_completer(text)
   File "/usr/lib/python2.7/site-packages/IPython/core/completer.py", line 1110, in dispatch_custom_completer
       res = c(event)
   File "/usr/lib/python2.7/site-packages/IPython/core/completerlib.py", line 253, in module_completer
       return module_completion(event.line)
   File "/usr/lib/python2.7/site-packages/IPython/core/completerlib.py", line 229, in module_completion
       return get_root_modules()
   File "/usr/lib/python2.7/site-packages/IPython/core/completerlib.py", line 119, in get_root_modules
       rootmodules_cache = ip.db.get('rootmodules_cache', {})
   AttributeError: 'NoneType' object has no attribute 'db'
```
@mmerickel

**Comment by mmerickel** [comment]
This does seem to be something specific to pshell or pyramid_ipython as running ipython directly does not exhibit this behavior. I'm open to any suggestions as to what may be causing this.

pyramid_ipython is of course 2 lines of code, so if it's using ipython incorrectly it's hopefully an easy fix.

https://github.com/Pylons/pyramid_ipython/blob/master/pyramid_ipython.py

**Comment by mmerickel** [comment]
This appears to me to be a bug with IPython itself. I can reproduce this outside of pshell/pyramid_ipython.

```
Python 3.5.1 (default, Jan  7 2016, 00:14:17)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from IPython.terminal.embed import InteractiveShellEmbed
>>> IPShell = InteractiveShellEmbed(banner2='hello world\n', user_ns={})
In : IPShell()
Python 3.5.1 (default, Jan  7 2016, 00:14:17)
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

hello world

In [1]: import trException in thread Thread-24:
Traceback (most recent call last):
  File "/Users/michael/.pyenv/versions/3.5.1/lib/python3.5/threading.py", line 914, in _bootstrap_ir
    self.run()
  File "/Users/michael/.pyenv/versions/3.5.1/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/michael/work/oss/pyramid/env/lib/python3.5/site-packages/prompt_toolkit/interface.pyn
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/Users/michael/work/oss/pyramid/env/lib/python3.5/site-packages/IPython/terminal/ptutils.pys
    cursor_pos=document.cursor_position_col
  File "/Users/michael/work/oss/pyramid/env/lib/python3.5/site-packages/IPython/core/completer.py",p
    text, matches =  complete(*args, **kwargs)
  File "/Users/michael/work/oss/pyramid/env/lib/python3.5/site-packages/IPython/core/completer.py",e
    custom_res = self.dispatch_custom_completer(text)
  File "/Users/michael/work/oss/pyramid/env/lib/python3.5/site-packages/IPython/core/completer.py",r
    res = c(event)
  File "/Users/michael/work/oss/pyramid/env/lib/python3.5/site-packages/IPython/core/completerlib.pr
    return module_completion(event.line)
  File "/Users/michael/work/oss/pyramid/env/lib/python3.5/site-packages/IPython/core/completerlib.pn
    return get_root_modules()
  File "/Users/michael/work/oss/pyramid/env/lib/python3.5/site-packages/IPython/core/completerlib.ps
    rootmodules_cache = ip.db.get('rootmodules_cache', {})
AttributeError: 'NoneType' object has no attribute 'db'

In [1]:
```

**Comment by mmerickel** [comment]
I'll also mention that `IPython.terminal.embed.embed(banner2='hello world\n', user_ns={})` does not exhibit this bug, meaning it is doing something more to initialize things beyond what we are doing. I have no idea what it's doing that's so special though.

**Comment by takluyver** [comment]
There's nothing obvious there that should break, although we generally encourage people who don't need it away from the 'embed' interface (which lets the shell see the local namespace of the function that calls it). You should be able to use this API instead to launch IPython:

```python
import IPython
IPython.start_ipython(user_ns=env)
```

**Comment by takluyver** [comment]
I think the key difference in the `embed()` function is that it instantiates `InteractiveShellEmbed` as a singleton with `InteractiveShellEmbed.instance()`. I think it's better to use `start_ipython()` for your purposes, though.

**Comment by mmerickel** [comment]
Hey @takluyver thanks for the suggestion. I tried swapping in `IPython.start_ipython()` and this mostly works fine. However it doesn't appear to have support for `banner2`. Any thoughts how to use this? We're using it to show a table of variables we injected via `user_ns=`.

**Comment by takluyver** [comment]
Try this:

```python
import IPython
from traitlets.config import Config

c = Config()
c.TerminalInteractiveShell.banner2="Hello!"
IPython.start_ipython(user_ns={'q':7}, config=c)
```

Alternatively, print whatever you want, and then pass `display_banner=False`.

**Comment by mmerickel** [comment]
@takluyver this seems to work. Are there any issues I should be aware of with this approach? Is overriding the config preventing the user's default config from being loaded?

**Comment by mmerickel** [comment]
For example, should I use `IPython.terminal.ipapp.load_default_config` instead of constructing my own empty config?

**Comment by takluyver** [comment]
I think it should load config from the file and merge them, but I've had to dig into the code to work that out. If in doubt, make a config file and see what happens.

**Comment by mmerickel** [comment]
Yes, apologies, I just tried it out and it is merging them. This is great, thank you for your help. You can choose what to do with this issue as I think we still exposed a bug in the embedded interpreter but we're able to workaround it with `IPython.start_ipython`.

**Comment by takluyver** [comment]
Great. Yes, I'll leave this open as it does seem like something should be handled better.

**Comment by mmerickel** [comment]
@invisibleroads I've released pyramid_ipython 0.2 which hopefully resolves that.

**Comment by invisibleroads** [comment]
Thank you! I can verify that the fix works.

We use IPython.embed() for debugging, so we might end up running into this issue again.

**Comment by takluyver** [comment]
I think you should be fine with `embed()`, it's only if you instantiate `InteractiveShellEmbed()` directly that it seems to be problematic.

**Comment by vmalloc** [comment]
@takluyver we're hitting this as well (on 5.1), and are unable to switch to `embed` or `start_ipython` since we're using `set_custom_exc` to handle specific exceptions during the input loop.

Any ideas about a possible workaround?

**Comment by hardkrash** [comment]
Discovered in my code that 

This code snippet fails.
```python
shell = InteractiveShellEmbed(config=config, banner1='')
shell()
```

This code snippet works.
```python
shell = InteractiveShellEmbed.instance(config=config, banner1='')
shell()
```

There is something being done differently with the instance method call.

**Comment by takluyver** [comment]
Using `.instance()` creates an instance and sets it as the global shell instance, which the completion machinery uses. Instantiating it directly does not register it as a global shell instance.
