### ISSUE TITLE
":#" holds the code paragraph

### ISSUE THREAD

**Issue by mrazavi64** [ipython/ipython#9800]
If a line contains a string with the ":#" content in ipython shell, ending the line with pressing Enter will add an indention and waits for new input.

```
In [1]: ":#"
   ...:     | <- cursor is here
```

**Comment by takluyver** [comment]
Thanks, it's already tracked as #2913, though I appreciate that's hard to find. Deciding whether to offer another line is kind of black magic.

**Comment by rgbkrk** [comment]
It brings a tear to my eye to see the first issue I ever opened still be a bug. 😂
