### ISSUE TITLE
Unexpected Error while Saving File: Disk I/O Error

### ISSUE THREAD

**Issue by danami6** [ipython/ipython#9802]
One of my ipython users is receiving the following error when attempting to create a new notebook:

![image](https://cloud.githubusercontent.com/assets/17322214/17099611/833d431c-5237-11e6-993c-b4e2260a172f.png)

This error was followed by additional kernel failures:
![image](https://cloud.githubusercontent.com/assets/17322214/17099653/ba69eade-5237-11e6-999e-4922c8ab2a93.png)

![image](https://cloud.githubusercontent.com/assets/17322214/17099659/c353bd3c-5237-11e6-874a-fd79747ac9a5.png)

Appreciate any insights into what could be causing this error. Thank in advance!

**Comment by takluyver** [comment]
Could the disk be full?

**Comment by danami6** [comment]
Thanks for the speedy response @takluyver. The user has cleared some space from his home directory. It also appears that it was affected by a compiler failure issue. When the python program failed to compile, the system kept all the failure logs and did not delete the temporary files generated during the compilation in the root directory (~/.theano). After deleting this folder, the issue was resolved. Thanks again!
