### ISSUE TITLE
IPython5 does not plot with ION mode

### ISSUE THREAD

**Issue by cdiazbas** [ipython/ipython#9811]
Hi,
I have detected that if I do a plot with plt.show(), the figure appears. If I use plt.ion() in order to do not use always show, I do not see anything. Example:

```
import matplotlib.pyplot as plt
plt.plot(x)
plt.show() #=> ok

plt.ion()
plt.plot(x) #=> fail
```

Thanks for all and congratulation for this new version.

**Comment by takluyver** [comment]
In general, you need to use the `%matplotlib` magic to enable mpl integration in IPython. We are working with matplotlib to remove the need for this: matplotlib/matplotlib#6734
