### ISSUE TITLE
__main__.py files not used in directory execution

### ISSUE THREAD

**Issue by controversial** [ipython/ipython#9812]
Take the following directory structure:
```
test_dir
    __main__.py
```
where `__main__.py` reads
```python
print("Hi")
```

Using the standard `python` command, I can:
```
$ python3 test_dir
Hi
```

Under `ipython`, this produces:
```
$ ipython3 test_dir
[TerminalIPythonApp] WARNING | File not found: 'test_dir'
```

This feature was added in Python 2.5. I suspect this error is simply because `ipython` hasn't implemented this functionality yet, but I don't see any open issues.

This feature is documented at https://docs.python.org/3/using/cmdline.html#interface-options.

Is there a specific reason why `ipython` doesn't use [runpy.run_path](https://docs.python.org/3/library/runpy.html#runpy.run_path) for running scripts passed as arguments?

If somebody could point me to a file in which I could patch this, I'd be happy to. I found [these lines](https://github.com/ipython/ipython/blob/master/IPython/core/interactiveshell.py#L2475-L2477) in `safe_execfile`, but `runpy.run_file` isn't entirely equivalent to `py3compat.execfile`, since it doesn't support the `locals` or `compiler` arguments.

**Comment by takluyver** [comment]
Hi! Good catch; the code that runs a file from the command line argument is here: https://github.com/ipython/ipython/blob/0845fa68538de8d2843337928b415b96c36c3843/IPython/core/shellapp.py#L389

It's probably not quite as simple as swapping in the runpy function, because of various functionality that IPython allows, but it shouldn't be too hard to support a directory containing a `__main__.py`.

**Comment by controversial** [comment]
Ok. My thinking with runpy was just that it, as a part of Python, would get
any future changes that were made to this system as soon as the new Python
version was released. But adding this as manually works fine for now. I’ll
try to scrape together a PR right now.

**Comment by controversial** [comment]
See #9813
