### ISSUE TITLE
Readline in IPython 5

### ISSUE THREAD

**Issue by sassanh** [ipython/ipython#9828]
Thanks for this great python shell.

Doesn't IPython 5 use readline? If the answer is "no it doesn't" then it's sad news for me as I find it hard to use python shell without vim mode. I hope if it doesn't use readline you'll find an easy way to bring vim mode support to IPython5.

**Comment by takluyver** [comment]
It does not use readline, however prompt_toolkit (the library that we do use) also supports a vim mode. In the [config file](http://ipython.readthedocs.io/en/stable/config/intro.html), set:

```python
c.TerminalInteractiveShell.editing_mode = 'vi'
```

**Comment by sassanh** [comment]
Thanks
