### ISSUE TITLE
inputrc file is not read any more?

### ISSUE THREAD

**Issue by robertsawko** [ipython/ipython#9830]
I just upgraded to ipython 5.0 on Arch Linux. It seems to be that inputrc file are no longer read. My vi setup does not appear to be functional.

This is my `~/.intputrc`
```
set editing-mode vi

set keymap vi
```

Pyhton shell still reads that correctly, but ipython shell does not. I am at 5.0.0 exactly. I also tried copying my two lines to /etc/inputrc but to no avail.

**Comment by robertsawko** [comment]
Dash it, I've just found your [announcement](http://ipython.readthedocs.io/en/stable/whatsnew/version5.html) on 5.x series:

*IPython no longer uses readline configuration (~/.inputrc). We hope that the functionality you want (e.g. vi input mode) will be available by configuring IPython directly (see Terminal IPython options). If something’s missing, please file an issue.*

**Comment by robertsawko** [comment]
For the confused ones like me, the solution is to edit the profile file. To create a profile file run `ipython profile create`. Then in `~/.ipython/profile_default/ipython_config.py` search for `editing_mode` and change to `vi`.

```
# Shortcut style to use at the prompt. 'vi' or 'emacs'.
c.TerminalInteractiveShell.editing_mode = 'vi'
```

More settings can be found [here](http://ipython.readthedocs.io/en/stable/config/options/terminal.html).

**Comment by takluyver** [comment]
Thanks for working this out before we got to it ;-).
