### ISSUE TITLE
completion should favor displaying the actually completed part of the string rather than the prefix

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#9835]
One screenshot says it all.
![screenshot_20160804_003842](https://cloud.githubusercontent.com/assets/1322974/17394140/6258d5e2-59dc-11e6-8805-a2cf9abd542d.png)

**Comment by minrk** [comment]
cc @jonathanslenders can we truncate on the left as well? Or do we need to do this in IPython, in terms of what we pass to pt as completions?

**Comment by Carreau** [comment]
> cc @jonathanslenders can we truncate on the left as well? Or do we need to do this in IPython, in terms of what we pass to pt as completions?

Yes we can, we can have the displayed completion and the completion text different already, but it requires some refactor of the completion machinery that we want for 6.0.

**Comment by Carreau** [comment]
@anntzer can you try master ? it's curiously fixed even if I'm not sure why.

**Comment by anntzer** [comment]
The issue is still present for me as of (git describe) 5.1.0-526-g3c154253b.

**Comment by Carreau** [comment]
> The issue is still present for me as of (git describe) 5.1.0-526-g3c154253b.

Ha I think I know why. Do you have Jedi installed ?

**Comment by anntzer** [comment]
Actually, the same issue is still present, when completing pathnames.  Could the issue be reopened?  Thanks.
