### ISSUE TITLE
IPython 5: prompt_toolkit in VI editing mode - ESC k puts cursor at the end of line

### ISSUE THREAD

**Issue by mario-grgic** [ipython/ipython#9837]
I'm on Mac OS X 10.11.6, Python 3.5.2 and IPython 5.0.0. I have configured IPython terminal console to use VI editing mode (I have this in my ipython_config.py):

c.TerminalInteractiveShell.editing_mode='vi'

Everything seems to work except when hitting ESC to go to normal mode, and then k to edit previous line. This puts the cursor at the end of the line, unlike BASH/readline vi editing mode that puts the cursor at the beginning of the line. This is an inconsistency with previous versions of IPython and BASH/readline and is rather annoying, since you expect the cursor to be at the beginning of the line and you start typing search forward commands to get it to where you want it, only to realize that you must issue search backward commands or hit ^ to put it at the beginning of the like and proceed as normal. 

I am not aware of a workaround, and if it is possible to remap normal mode command keyboard shortcuts.

This is also reproducible with Python 2.7.x and also on Windows.

**Comment by takluyver** [comment]
Pinging @jonathanslenders

**Comment by jonathanslenders** [comment]
Hi @mario-grgic,

This should have been fixed in the following commit: https://github.com/jonathanslenders/python-prompt-toolkit Can you try to install the latest prompt_toolkit from master and check whether it works?

**Comment by mario-grgic** [comment]
Installed the latest prompt_toolkit 1.0.5 and there is no change in behavior.

**Comment by mario-grgic** [comment]
I see the fix has been committed after 1.0.5 release. I did git clone of the repo, and it is indeed fixed in commit 4aa0404ad7e770763b85764fd42c8dbce94f9c62
