### ISSUE TITLE
Authenticate ipython GUI with Centrify userID and Password option not avaible

### ISSUE THREAD

**Issue by KUMAA299** [ipython/ipython#9847]
Hi,

Want to implement security authentication in ipython for multiple users.Is there any procedure to create multiple userID and password to login.
Is there any feature available in ipython GUI to login using UNIX credentials or as a centrify users.

**Comment by takluyver** [comment]
I guess you're talking about the Jupyter Notebook. If so, [Jupyterhub](http://jupyterhub.readthedocs.io/en/latest/) is probably what you want.

**Comment by KUMAA299** [comment]
Thank you so much for your response.
Can centrify users can login to JupyterHub. Is there any method available to integrate Centrify with JupyterHub for authentication purpose.

**Comment by takluyver** [comment]
Jupyterhub allows for different 'authenticator' plugins to integrate with different sign in systems. I don't know if anyone's written one for Centrify, but if not, it should be possible for you to do that.

http://jupyterhub.readthedocs.io/en/latest/getting-started.html#configuring-authentication
http://jupyterhub.readthedocs.io/en/latest/authenticators.html

**Comment by KUMAA299** [comment]
Thanks for your kind response.
Do JupyterHub provide support to authenticate users using any Active Directory?

**Comment by minrk** [comment]
Literally any authentication mechanism should work, especially if it uses a username and password. If somebody has used it before, e.g. LDAPAuthenticator, you can install an existing custom Authenticator. If you are the first, you may need to write a custom Authenticator to integrate with your authentication system.

I don't know of an existing direct AD authenticator, but I think some people are using AD via LDAP.
