### ISSUE TITLE
The link to Andrew Ng's course is dead

### ISSUE THREAD

**Issue by wagglefoot** [ipython/ipython#9853]
[This does not work](http://nbviewer.jupyter.org/github/jdwittenauer/ipython-notebooks/blob/master/ML-Exercise1.ipynb)

**Comment by takluyver** [comment]
Which page is the link on?

**Comment by wagglefoot** [comment]
https://github.com/ipython/ipython/wiki/A-gallery-of-interesting-IPython-Notebooks

Fourth from the bottom under Statistics, Machine learning (or something along those lines).

**Comment by takluyver** [comment]
Thanks, I've fixed it. Here's the updated link:

http://nbviewer.jupyter.org/github/jdwittenauer/ipython-notebooks/blob/master/notebooks/ml/ML-Exercise1.ipynb

For future reference, that's a wiki page, so if you can find the correct link (I found this by browsing around Github), you can edit it yourself.
