### ISSUE TITLE
No pylab figure display

### ISSUE THREAD

**Issue by cedricmontero** [ipython/ipython#9855]
Dear forum, I have since ipython 5.0.0 (updated via macport) a bug with pylon figure display. The window figure is not appearing (even with pylab.ion() or even forced to show on with pylon.show()). But it appears when I am trying to quit the terminal ipython application (Ctrl+D) and most of the time finishing to crash ipython program running. I am on Mac OS 10.11.6 El Capitan working on Terminal directly with python 2.7.12 and IPython 5.0.0. Is anybody know how to fix this bug ?
Many thanks.

**Comment by takluyver** [comment]
Have you run `%matplotlib`? This was always recommended, but in some circumstances it worked without it. Matplotlib 2.0 should remove the need for it.

**Comment by cedricmontero** [comment]
Matplotlib is show up the window normally (poping up, graph display actions etc) but when I try to close this window the python app is not responding. Then when I force the python app to quit the ipython process in the terminal is 'terminated: 15'.

**Comment by takluyver** [comment]
That sounds like something we've just merged a fix for. Can you try with master? Otherwise, it should be fixed when we release 5.1 - hopefully in the next couple of days.

**Comment by cedricmontero** [comment]
I don't know how to try with another version. I am just doing a self update of mac port from times to times, but I am not an expert on installation.
Many thanks for your active response.

**Comment by takluyver** [comment]
Ok, then it should be fixed by 5.1. I'll close this for now - we can reopen it if there's still a problem with 5.1.
