### ISSUE TITLE
LaTeX Error: File `adjustbox.sty' not found.

### ISSUE THREAD

**Issue by Tagar** [ipython/ipython#9858]
Getting following error in jupyter logs when trying to save jupyter notebook as a PDF.

> [I 15:23:19.317 NotebookApp] Writing 62956 bytes to notebook.tex
> [I 15:23:19.317 NotebookApp] Building PDF
> [I 15:23:19.318 NotebookApp] Running pdflatex 3 times: [u'pdflatex', u'notebook.tex']
> [C 15:23:19.388 NotebookApp] pdflatex failed: [u'pdflatex', u'notebook.tex']
>     This is pdfTeXk, Version 3.141592-1.40.3 (Web2C 7.5.6)
>      %&-line parsing enabled.
>     entering extended mode
>     (./notebook.tex
>     LaTeX2e <2005/12/01>
>     Babel <v3.8h> and hyphenation patterns for english, usenglishmax, dumylang, noh
>     yphenation, arabic, basque, bulgarian, coptic, welsh, czech, slovak, german, ng
>     erman, danish, esperanto, spanish, catalan, galician, estonian, farsi, finnish,
>      french, greek, monogreek, ancientgreek, croatian, hungarian, interlingua, ibyc
>     us, indonesian, icelandic, italian, latin, mongolian, dutch, norsk, polish, por
>     tuguese, pinyin, romanian, russian, slovenian, uppersorbian, serbian, swedish,
>     turkish, ukenglish, ukrainian, loaded.
>     (/usr/share/texmf/tex/latex/base/article.cls
>     Document Class: article 2005/09/16 v1.4f Standard LaTeX document class
>     (/usr/share/texmf/tex/latex/base/size10.clo))
>     (/usr/share/texmf/tex/latex/graphics/graphicx.sty
>     (/usr/share/texmf/tex/latex/graphics/keyval.sty)
>     (/usr/share/texmf/tex/latex/graphics/graphics.sty
>     (/usr/share/texmf/tex/latex/graphics/trig.sty)
>     (/usr/share/texmf/tex/latex/config/graphics.cfg)
>     (/usr/share/texmf/tex/latex/pdftex-def/pdftex.def)))
> 
>     ! LaTeX Error: File `adjustbox.sty' not found.
> 
>     Type X to quit or <RETURN> to proceed,
>     or enter new name. (Default extension: sty)
> 
>     Enter file name:
>     ! Emergency stop.
>     <read *>
> 
>     l.19     \usepackage
>                         {color} % Allow colors to be defined^^M
>     !  ==> Fatal error occurred, no output PDF file produced!
>     Transcript written on notebook.log.
> 
> [I 15:23:19.390 NotebookApp] Running bibtex 1 time: [u'bibtex', u'notebook']
> [W 15:23:19.406 NotebookApp] bibtex had problems, most likely because there were no citations
> [I 15:23:19.408 NotebookApp] Running pdflatex 3 times: [u'pdflatex', u'notebook.tex']
> [C 15:23:19.457 NotebookApp] pdflatex failed: [u'pdflatex', u'notebook.tex']
>     This is pdfTeXk, Version 3.141592-1.40.3 (Web2C 7.5.6)
>      %&-line parsing enabled.
>     entering extended mode
>     (./notebook.tex
>     LaTeX2e <2005/12/01>
>     Babel <v3.8h> and hyphenation patterns for english, usenglishmax, dumylang, noh
>     yphenation, arabic, basque, bulgarian, coptic, welsh, czech, slovak, german, ng
>     erman, danish, esperanto, spanish, catalan, galician, estonian, farsi, finnish,
>      french, greek, monogreek, ancientgreek, croatian, hungarian, interlingua, ibyc
>     us, indonesian, icelandic, italian, latin, mongolian, dutch, norsk, polish, por
>     tuguese, pinyin, romanian, russian, slovenian, uppersorbian, serbian, swedish,
>     turkish, ukenglish, ukrainian, loaded.
>     (/usr/share/texmf/tex/latex/base/article.cls
>     Document Class: article 2005/09/16 v1.4f Standard LaTeX document class
>     (/usr/share/texmf/tex/latex/base/size10.clo))
>     (/usr/share/texmf/tex/latex/graphics/graphicx.sty
>     (/usr/share/texmf/tex/latex/graphics/keyval.sty)
>     (/usr/share/texmf/tex/latex/graphics/graphics.sty
>     (/usr/share/texmf/tex/latex/graphics/trig.sty)
>     (/usr/share/texmf/tex/latex/config/graphics.cfg)
>     (/usr/share/texmf/tex/latex/pdftex-def/pdftex.def)))
> 
>     ! LaTeX Error: File `adjustbox.sty' not found.
> 
>     Type X to quit or <RETURN> to proceed,
>     or enter new name. (Default extension: sty)
> 
>     Enter file name:
>     ! Emergency stop.
>     <read *>
> 
>     l.19     \usepackage
>                         {color} % Allow colors to be defined^^M
>     !  ==> Fatal error occurred, no output PDF file produced!
>     Transcript written on notebook.log.
> 

The version of the notebook server is 4.1.0 and is running on:
Python 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

**Comment by Tagar** [comment]
Also created https://github.com/ipython/ipython/issues/9858

**Comment by takluyver** [comment]
You need the necessary latex packages, which we can't install for you. On my Fedora system, there's a `texlive-adjustbox` package. You may need others as well.

**Comment by takluyver** [comment]
Closing this in favour of the nbconvert issue.
