### ISSUE TITLE
Incorrect tab completion

### ISSUE THREAD

**Issue by rgom** [ipython/ipython#9865]
Hi all,
when using auto-completion for partially entered text, the result is wrong.

For example if there's object d with attribute `config` with attribute `get_all_port_tuples` and one enters `d.config.get<tab>`, completion suggestion appears, but when `get_all_port_tuples` is selected, input contains incorrect `get_port_tuples` (`_all` is stripped off).
After pressing `<enter>` incorrect suggestion is copied to console.

![incorrect_complete_ipython](https://cloud.githubusercontent.com/assets/8234247/17615470/c2986e70-606e-11e6-878e-0e5465775406.png)

Other example (using standard library):
`
import collections
collections.Mu<tab>
`
and ipython offers e.g. `MutableeSequence` or `MutableleMapping`

`
c:\>ipython --version
5.0.0
`
Platform: windows 7

Regards,
Robert

**Comment by takluyver** [comment]
Make sure you have the latest version of [prompt_toolkit](https://pypi.python.org/pypi/prompt_toolkit) installed (1.0.5, at the time of writing).

Pinging @jonathanslenders

**Comment by rgom** [comment]
Thank you @takluyver.
I do have latest (1.0.5) prompt_toolkit installed.

Regards,
Robert

**Comment by zhsj** [comment]
I can confirm.

python3 and ipython 5.0.0

```
$ pip list
decorator (4.0.10)
ipython (5.0.0)
ipython-genutils (0.1.0)
pexpect (4.2.0)
pickleshare (0.7.3)
pip (8.1.2)
pkg-resources (0.0.0)
prompt-toolkit (1.0.5)
ptyprocess (0.5.1)
Pygments (2.1.3)
setuptools (25.1.6)
simplegeneric (0.8.1)
six (1.10.0)
traitlets (4.2.2)
wcwidth (0.1.7)
wheel (0.29.0)
```

First I try the `collections.MutableSequence`

I inputed `collections.Mu<tab>`
![image](https://cloud.githubusercontent.com/assets/227180/17625194/5879cd1a-60da-11e6-8558-9c57be037e08.png)

Then it shows correct completion.

Then I use `<tab>` to select `MutableSequence`

![image](https://cloud.githubusercontent.com/assets/227180/17625245/92eb77dc-60da-11e6-8f57-311051ba4f26.png)

You can see, in the input line, the result is `collections.MutableeSequence`

**Comment by Carreau** [comment]
I've seen it as well (present on PTK master), I think that only appear if you completer to longuest prefix before completions pop-up,
ie to say:

```
collections.Mutable<Tab>
```

Does not have the bug. 

```
collections.Mut<tab><tab>
```

Will have the bug.

**Comment by feiyuw** [comment]
+1
I have the same issue on ipython 5.1, prompt-toolkit 1.0.6.
My env is python 2.7.6 on Linux Mint 17.3 (based on ubuntu 14.04)

**Comment by jonathanslenders** [comment]
I can reproduce it. Looking for a fix.

**Comment by jonathanslenders** [comment]
Hi all, I think that the following commit fixes it: https://github.com/jonathanslenders/python-prompt-toolkit/commit/970c763323749f044931e44fb4d39b205c7b0b85
Could checkout prompt_toolkit master and try again?
Thanks for reporting!

**Comment by zhsj** [comment]
@jonahkichwacoders It works in ipython too.

**Comment by rgom** [comment]
Works like a charm after manually applying the fix to prompt_toolkit.
