### ISSUE TITLE
 How to set InteractiveShellApp config options like ```c.InteractiveShellApp.exec_lines``` use jupyter4.2.1

### ISSUE THREAD

**Issue by Anne623** [ipython/ipython#9866]
Hi, All.
Now I use jupyter notebook 4.2.1, I want to exec lines when IPython start up. In IPython 3.x, I use the config file ```ipython_config.py```, and set ```c.InteractiveShellApp.exec_lines```. But now i use jupyter notebook 4.2.1, I don't know how to set this.

**Comment by Carreau** [comment]
Hi @Anne623 , 

Thanks for your questions; it's true the Jupyter/IPython separation is a bit confusing, but in your case it seem like this should not affect you;

Indeed when you start the Jupyter notebook to write Python, by default it will connect to IPython under the hood. So the `c.InteractiveShellApp.exec_lines` should be executed when you switch to a notebook.

I just tried locally and it seem it works for me:

<img width="539" alt="screen shot 2016-08-14 at 10 23 36" src="https://cloud.githubusercontent.com/assets/335567/17650709/44360f0a-6209-11e6-8e41-731f8be2495b.png">

Let us know if it's not the case for you in which case we can diagnose what's wrong on your system, on if my explanation are unclear. 

Thanks.

**Comment by Anne623** [comment]
@Carreau  Thank you for your reply. I try put ```ipython_config.py``` in dir ```~/.jupyter```, the same dir with  ```jupyter_notebook_config.py```
![image](https://cloud.githubusercontent.com/assets/10845504/17685661/aed07874-6398-11e6-8251-a2bf6834321b.png)
   
I set ```c.InteractiveShellApp.exec_lines = ['test = "hhhhhh in config"']```, while in notebook , I use test, it will be error, it says: name 'test' is not defined. 
    
So I want to know in your case where the file ```ipython_config.py```   put?

**Comment by Carreau** [comment]
Sorry I was uncler @Anne623 ; 

Jupyter has it's own set of config (likely in `~/.jupyter` for you), and these configuration only affect the Jupyter components; not each individual kernels.

 The IPython configuration have not moved, they are likely in `~/.ipython` for you, but you can check with `$ ipython locate`.

I know it is confusing as we are the same people that use both Jupyter and IPython, but as IPython is used by users that don't install Jupyter, and Jupyter is used by users that don't write Python, we tend to think of both project independently, and store configuration in separate directories.

Does that makes sens ? We are always looking for better ways to express the Jupyter vs IPython differences.

For example here is my IPython config, where I srip all the comments:

```
$ cat ~/.ipython/profile_default/ipython_config.py  | grep -v '#'

c.InteractiveShellApp.exec_lines = ['test = "isusse 9866 for Anne623"']
```

With that, both the `ipython` accessed from the command line REPL and the Jupyter notebook have theses lines executed at startup.

**Comment by Anne623** [comment]
@Carreau ,  Thank you very much, Now I know more about the diff between ipython and jupyter.

I was confusing about if I put ipython config in another dir, like ```~/.ipython/profile_myconfig/ipython_config.py```,  and what's the command  to start ipython or jupyter notebook that  jupyter notebook  have these lines executed at startup?

I  know in Ipython3.x , the command is ```ipython notebook --profile=myconfig```   

When I put ipython config in some dir like ```/ipython/config/profile_myconfig/ipython_config.py```, In IPython3.x , I use ```ipython notebook --profile=myconfig --ipython-dir=/ipython/config/```.  But now I don't know how to read these config file.  


Does IPython4.x+ has new doc to learn how to set IPython config?

**Comment by willingc** [comment]
Hi @Anne623,

Perhaps this document will help you. [Migrating from IPython Notebook](http://jupyter.readthedocs.io/en/latest/migrating.html) covers quite a bit of where files are located before (IPython 3.x) and after (IPython 4.x and Jupyter) the code base split.

**Comment by Carreau** [comment]
Ok, all these questions make sens, and thanks @willingc I did not remeber we had these docs. 

Indeed, you want to create multiple kernels, for example `Python 3 [default]` and `Python 3 [myconfig]`

See for example here is my python3 kernel:

```
$ pwd
/usr/local/share/jupyter/kernels

$ tree python3/
python3/
├── kernel.json
├── logo-32x32.png
└── logo-64x64.png

0 directories, 3 files

$ cat python3/kernel.json
{
  "display_name": "Python 3",
  "argv": [
    "/Users/bussonniermatthias/anaconda/bin/python",
    "-m",
    "ipykernel",
    "-f",
    "{connection_file}"
  ],
  "language": "python"
}
```

You want to duplicate this folder, change the `"display_name"`, and add the `"--profile=myprofile"` key of `kernel.json` likely as follow:

```
{
  "display_name": "Python 3 [My Profile]",
  "argv": [
    "/Users/bussonniermatthias/anaconda/bin/python",
    "-m",
    "ipykernel",
    "-f",
    "{connection_file}",
    "--profile=myprofile"
  ],
  "language": "python"
}
```

Then instead of restarting the notebook server, you can select the various kernels from the kernel menu dropdown, at any moment.

**Comment by Anne623** [comment]
@Carreau , It's perfect!  Thank you very much.

**Comment by Carreau** [comment]
> @Carreau , It's perfect! Thank you very much.

Awesome ! If you want to give a shot a writing improvement to the explanation in the docs, we would be happy !
