### ISSUE TITLE
Installing ipython creates ipython3 executable even if python3 isn't installed

### ISSUE THREAD

**Issue by jeffyjefflabs** [ipython/ipython#9869]
We are building a docker image for Jupyter (running in python2) that installs kernels on demand in order to keep the base image small.  We are checking for the existence of an ipython3 executable to determine if we need to install python3 and the python3 kernel, so we were dismayed to find that ipython had created /usr/bin/ipython3 even in the absence of python3.  Obviously this is easy to work around by having our Dockerfile remove /usr/bin/ipython3 immediately after installing ipython, but would it be possible for ipython to check what versions of python exist on the system before creating executables?

**Comment by takluyver** [comment]
How are you installing that? IPython should create `ipython3` only if it's installed by Python 3.

**Comment by takluyver** [comment]
Rats, we've made a universal wheel (`py2.py3`). @Carreau, we need to do separate Python 2 and 3 wheels so that the scripts get installed correctly.

**Comment by takluyver** [comment]
I've released 5.1, so this should work as expected again - installing on Python 3 will create `ipython` and `ipython3`, installing on Python 2, `ipython` and `ipython2`.

**Comment by Carreau** [comment]
> Rats, we've made a universal wheel (py2.py3). @Carreau, we need to do separate Python 2 and 3 wheels so that the scripts get installed correctly.

We need to have a test, or documentation in the release process for this. Otherwise we will make the mistake again.

**Comment by Carreau** [comment]
> I've released 5.1

Woooo !

**Comment by willingc** [comment]
Great job @takluyver 🎆
