### ISSUE TITLE
Syntax highlighting not recognizing some float notations

### ISSUE THREAD

**Issue by zoquda** [ipython/ipython#9878]
## Problem description
Syntax highlighting does not seem to recognize floats written in the no-decimal-point scientific notation.

For example: when I enter `1e2` or `1e-2` into an IPython terminal, then the characters are not all highlighted with the same color. 

Here is a screenshot:
<img width="215" alt="ipython" src="https://cloud.githubusercontent.com/assets/20889585/17681794/137db774-6348-11e6-96f6-c2bcad592066.PNG">

## Environment
* ipython: 5.1.0
* python: 3.5.2
* operating system: Windows 10

**Comment by takluyver** [comment]
We're waiting for a fix in pygments:
https://bitbucket.org/birkenfeld/pygments-main/pull-requests/618/add-1e6-as-float-token-for-python3lexer/diff
