### ISSUE TITLE
Complete request will not work when have execute request.

### ISSUE THREAD

**Issue by Anne623** [ipython/ipython#9880]
Hi, All. 
I know ipython has complete request that auto complete code. like below:
![image](https://cloud.githubusercontent.com/assets/10845504/17685755/9bde11b2-6399-11e6-8874-a7cc441fbb58.png)
But when I have cell is executing, that means has ```exectute request```, the tab key will not working in another cell. 
![image](https://cloud.githubusercontent.com/assets/10845504/17685791/e2fc58b0-6399-11e6-80a3-d025eaf72add.png)
   
while In my normal case,  my execute request will spent a long time, at the same time, I need coding in another cell, so I need use ```tab``` key to auto complete code.  dose it possible?

**Comment by takluyver** [comment]
Sorry, it won't process the completion request until it finishes with the execution request. I think it does some very simple completions in the frontend (i.e. for words you've already used), but the full completions rely on the kernel responding to a message. We'll keep it in mind, but it would require big changes that aren't likely to happen any time soon.
