### ISSUE TITLE
Feature Request: Add pipe operator to IPython

### ISSUE THREAD

**Issue by mario-grgic** [ipython/ipython#9881]
It would be incredibly useful to be able to pass contents of python variable (as string) to external utility. So something like

```
var1 | !grep -i some_string 
```

which would essentially pipe the result of str(var1) to BASH command, in this case grep. 

Currently, you can do something like 

```
!echo -e "$var1" | grep -i some_string 
```

but it does not always work. For example

```
import requests
content = requests.get('http://www.google.com').content
!echo -e "$content" 
```

does not echo the content correctly:

```
<!doctype html><html itemscope= itemtype=http://schema.org/WebPage lang=en-CA><head><meta content=text/html
/bin/bash: out: command not found
/bin/bash: -c: line 1: syntax error near unexpected token `{!_gjuc'
```

**Comment by takluyver** [comment]
It is working, but it literally expands the Python variable into the shell command, with no escaping, so when it hits a `"` inside there, it will close the string you opened for bash.

The `!` system command syntax is a shorthand, and can't do everything you can do by running a subprocess. E.g. without any escaping at all, you could run `echo` directly:

```python
import subprocess
subprocess.call(['echo', '-e', content])
```

Or you could use an environment variable:

```python
import os
os.environ['FOOBAR'] = content
!echo -e $FOOBAR
```

**Comment by Carreau** [comment]
Hi, 

This issue has been quiet for almost a year, and I don't think there is anything we can do. It has been marked as no-action, and I'm going to close it to attempt to reduce the number of opened issue. Feel free to reopen if needed. 

Thanks.

**Comment by kflu** [comment]
IPython seems to support piping: https://stackoverflow.com/a/68749879/695964
