### ISSUE TITLE
No heartbeat

### ISSUE THREAD

**Issue by CAOLINAN** [ipython/ipython#9882]
I want to set the ipengine on the windows.But when the connection is interrupted I have to restart the ipengine and the ipengine get a new id.So anyone can help me? I just want the ipengine can continue to use when the Internet restores.

**Comment by minrk** [comment]
Can you provide more information about what is happening? What sort of machine is this and what sort of network interruption is happening? How long does it last?

**Comment by CAOLINAN** [comment]
Well,I start the ipcontroller on the Centos 7,and the ipengine is started on the Windows Server R2. The Internet of the Windows is  automatic.I want to develop a program which is running stable for serveral  days using the ipengine and the client.I found that if the Internet is interrupted the ipengine will lose heartbeat.And the ipcontroller cann't get the ipengine's ID.Eventhough I set the hearbeat period a large number.It seems that the Internet cann't be interrupted while the system(contains ipcontroller and ipengines)is running.So what should I do to solve the problem or restart the ipengine using it's original ID? Thank you~

**Comment by minrk** [comment]
Network interruptions (sleep, disabling wifi) are handled gracefully when I test, as long as the interruption is no longer than 2x the heartbeat interval. How long is your network interruption? When the interruption happens, do IP addresses change?

**Comment by CAOLINAN** [comment]
I set the heartbeat 60000ms and start nine ipengines,but I found all of them still lost heartbeat a few days.I doubted that it because of the Internet.The Internet uses ethernet network.And the Internet interrupt without regularity.Sometimes it will interrupted for serveral hours. IP address doesn't change.

**Comment by minrk** [comment]
If there internet goes out for several hours, you will need to set some configuration to allow for that level of failure:

```python
# ipcontroller_config.py
c.HeartMonitor.period = 60000 # ping every minute
c.HeartMonitor.max_heartmonitor_misses = 720 # allow 12 hours of interruption before considering an engine gone
```

Now, the engine also notices heartbeats and shuts itself down if no heartbeats arrive for a while. You can disable this entirely:

```python
# ipengine_config.py
c.EngineFactory.max_heartbeat_misses = 0 # disable engine-side heartbeat check
```

All that said, it may be easier to make your workload resilient to engine death, and just let engines disappear and get new engines on the workers when connectivity is restored.

What sort of work are you doing with IPython parallel? It may be that setting the `retries` flag to allow resubmitting tasks to new workers if an engine disappears is all you need.

**Comment by CAOLINAN** [comment]
Thank you very much.I will take your advice.And wish it will succeed.
