### ISSUE TITLE
Can't change variable values in debug mode (%debug magic)

### ISSUE THREAD

**Issue by vladiibine** [ipython/ipython#9887]
IPYthon 5.1.0

Tested it multiple ways - can't change the variables.

Here's a log

```
In [1]: def asdf(aa, bb):
   ...:     if aa == bb:
   ...:         pass
   ...:     return aa, bb
   ...: 

In [2]: %%debug
   ...: myval = asdf(2,3)
   ...: 
NOTE: Enter 'c' at the ipdb>  prompt to continue execution.
*** IndexError: list index out of range
> <string>(2)<module>()

ipdb> s
--Call--
> <ipython-input-1-744c31b385bc>(1)asdf()
----> 1 def asdf(aa, bb):
      2     if aa == bb:
      3         pass
      4     return aa, bb

ipdb> s
> <ipython-input-1-744c31b385bc>(2)asdf()
      1 def asdf(aa, bb):
----> 2     if aa == bb:
      3         pass
      4     return aa, bb

ipdb> a
aa = 2
bb = 3
ipdb> aa = 5555
ipdb> aa
2
ipdb> c

In [3]: myval
Out[3]: (2, 3)
```

**Comment by takluyver** [comment]
I think that's a limitation of the way Python scopes work - you can't easily change local values inside a function dynamically.

**Comment by vladiibine** [comment]
I don't know how to reply to this. 
I only know changing local variables works in IPython 4, and the vanilla python REPL. It works with pydevd. It should just work, that I'm fairly confident about.

**Comment by vladiibine** [comment]
More context: Python 2.7.6

I however could reproduce this behavior in Python 3.4

**Comment by vladiibine** [comment]
More context:
This commit, made it so that when you try to change a variable, while debugging (with `%debug` - for example, but with `Python.core.debugger.Pdb().runcall(myfunc, arg1, arg2)` too), an error will be raised. What it did, was to add the `parseline` method to the Pdb class:
85820d34555eef610d3a08e3b3b1d32c53804dcd

And then this commit made the Pdb class a new-style class. Unfortunately, from this point onward, changing the variable names dowsn't work anymore.
7b8ae1d31a805ebc7bb0f9a6ac6803a9535088fb

It would be totally awesome to get the feature back, but as far as I see, the situation is not the prettiest. Who knows what arcane old-style class magic happened?

Anyway, I'll keep investigating this. I consider this bug very nasty.

**Comment by vladiibine** [comment]
In the 5.1.0 tag I see a workaround has already been implemented.

Considering the function
```
def asdf(aa, bb):
    x = 0
    return aa, bb
```

If in debug mode we hit
`!!a = 9`

Then the value of the variable `a` will indeed change to 9.

@takluyver do you think this was the desirable behavior? I don't know if this is documented, I couldn't find any reference to this. I suspect this to be just temporary workaround.

**Comment by takluyver** [comment]
Oh, that suggests it's something to do with the 'smart' debugger feature added in #9449. @anntzer, could you investigate?

**Comment by anntzer** [comment]
It appears that `curframe` is not set correctly when executing the very first line in a function (so the wrong locals dictionary gets updated).  Unfortunately I can't see a fix for now :-(

**Comment by takluyver** [comment]
I wonder if we should back 'smart' debugging out for now. I'd rather have something that works consistently, even if it's not ideal.

**Comment by anntzer** [comment]
I don't mind if you decide to revert that PR.

**Comment by vladiibine** [comment]
I was thinking that "perhaps" a different approach can be taken. Didn't have time to test it myself, but, instead of checking if keys

This is pseudocode, but I hope I can get the point across:

```
def parseline(self, line):
    if line.startswith('!'):
        evaluate_as_pdb_command(line)

    try:
        evaluate_as_code(line)      # this will execute the code in the expected locals() and globals() context
    except (NameError, SyntaxError) as err:   # if for instance the user passed the `c` command
        evaluate_as_pdb_command(line)   # this will try to evaluate the command
````

I think this avoids most of the problems with the current implementation, but does indeed introduce some new ones. For one, if the user actually wants to execute some code that would normally raise a NameError or SyntaxError, the debugger will try to interpret that as a command.... I don't have a better idea now though.

Thanks for the interest guys!

**Comment by vladiibine** [comment]
I see that in ipython==5.2.1 it doesn't happen anymore! Thanks guys!

**Comment by nonagonal** [comment]
I noticed that in ipython 5.2.2 (and python 2.7.12) any changes made to local variables don't persist if I jump to a place before I made the assignment, e.g.:

```
def f(a=0): 
  print(a)  # line 1
  x=0        # line 2
  print(a)  # line 3
```
1) step to line 2
2) set a=1
3) step to line 3
4) jump to line 1
5) note a=0

but if we jump to line 2 instead, a retains its new value (1).

I'm not sure if this is related to this issue or a separate issue (or if it's intended behavior), does anyone know?
