### ISSUE TITLE
Package error when auto completing

### ISSUE THREAD

**Issue by JASON0916** [ipython/ipython#9890]
![image](https://cloud.githubusercontent.com/assets/6837262/17831317/c6be23f0-6717-11e6-868d-7c5c0d8adbf7.png)

I try to import ClientSession from aiohttp, but there seems to be circulation when analyzing the package

**Comment by takluyver** [comment]
Are you closing this because you resolved it?

**Comment by JASON0916** [comment]
Yes, I retried and that question can't be reproduced, i guess it may be my mistake.
