### ISSUE TITLE
Close milestone 4.2.1?

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#9895]
We still have a 4.2.1 milestone open, with 3 closed issues. Is this being left open deliberately because we still want to do another 4.x series release? Or have we just overlooked it? I'm not planning to make another 4.x release.

@minrk @Carreau

**Comment by Carreau** [comment]
HUm... I'm +1 to close it.

**Comment by minrk** [comment]
If we aren't going to make 4.2.1 (fine by me), I'd move the issues/PRs marked for it to the actual release they got into, then relabel the milestone to something else (e.g. 5.1.1). Otherwise there's a bit of strange signaling that these issues were first fixed in a release that doesn't exist.

**Comment by Carreau** [comment]
moved all in the 5.2 milestone. There was only 1 PR.

**Comment by takluyver** [comment]
Thanks Matthias. I've deleted the 4.2.1 milestone.
