### ISSUE TITLE
/usr/bin/python: No module named IPython

### ISSUE THREAD

**Issue by cancan101** [ipython/ipython#9896]
I have IPython Installed in a virtual env:

```
$ which ipython
/home/ubuntu/.virtualenvs/alex2/bin/ipython
```

```
$ pip freeze | grep ipyt
ipython==5.1.0
ipython-genutils==0.1.0
```

but when I try to open a notebook, I get:

```
[I 16:34:25.527 NotebookApp] KernelRestarter: restarting kernel (1/5)
/usr/bin/python: No module named IPython
```

**Comment by takluyver** [comment]
It's probably trying to run IPython in another Python environment or installation. To install a kernelspec for the `alex2` virtualenv, see http://ipython.readthedocs.io/en/stable/install/kernel_install.html

**Comment by Carreau** [comment]
I'm going to guess this has been fixed and close.

If this is not the case, @cancan101 please let us know. Thanks.
