### ISSUE TITLE
Jupyter console crashes when printing object

### ISSUE THREAD

**Issue by n-witt** [ipython/ipython#9902]
When printing [this](https://github.com/ipython/ipython/files/434312/obj.txt) list of tuples my jupyter console crashes with [this](https://github.com/ipython/ipython/files/434314/stacktrace.txt) stack trace. Interestingly, printing the same object in a Jupyter notebook works just fine.

Installation details:
'commit_hash': '5c9c918',
'commit_source': 'installation',
'default_encoding': 'ANSI_X3.4-1968',
'ipython_version': '5.1.0',
'platform': 'Linux-3.10.0-327.28.2.el7.x86_64-x86_64-with-debian-jessie-sid',
'sys_platform': 'linux',
'sys_version': '3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) \n [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'

**Comment by takluyver** [comment]
It thinks that your terminal encoding is 'ascii', so it can't display unicode characters. Probably the easiest fix is to make sure that your locale is set correctly. E.g. on my system:

```
$ echo $LANG
en_GB.UTF-8
```

**Comment by n-witt** [comment]
@takluyver: You are right. Thank you. I'm running the Jupyter notebook in a Docker container, which messed up my locale settings. In my case `$LANG` was empty, but `locale charmap`, `locale -a` and `locale -m` allowed me to inspect my environment. Now I need to find a way to update those settings properly.
