### ISSUE TITLE
Autocomplete is not working properly with large paths

### ISSUE THREAD

**Issue by PGryllos** [ipython/ipython#9906]
I recently updated my ipython to the newest version 5.1.0 and since then, although many things have undoubtedly been improved, I find the new autocomplete to be problematic in some cases. 

For example I have a file with a really long name `ds_relation_graph_only_users_with_tweets_and_topics.csv`
in the dir `home/user_name/Dropbox/Paper_Link_Prediction/datasets/`

when I am trying to read the file from ipython the autocomplete works correctly until the point I reach the dir but when I click tab to iterate over the filenames weird things happen and the autocomplete ends up returning result like

    ds = pd.read_csv('/home/user_name/Dropbox/Paper_Link_Prediction/datasets/ds_elation_graph_only_users_with_tweets_and_topics.csv')

or like that

    ds = pd.read_csv('/home/user_name/Dropbox/Paper_Link_Prediction/datasets/ds_tasets/ds_relation_graph_only_users_with_tweets.csv'

which are obviously broken and need my fixing to work, which is utterly annoying and contradicts the whole concept of autocomplete, because then I have to manually check what exactly is the name of the file and correct it. The oldest version used to work fine though.

Is this something that can be solved or do I have to revert to the old version?

**Comment by Carreau** [comment]
Can you try to update prompt_toolkit to v 1.0.7 ?

**Comment by PGryllos** [comment]
Thanks, this seems to have solved the problem :)
