### ISSUE TITLE
Get rid of %install_ext from all the docs

### ISSUE THREAD

**Issue by yuvipanda** [ipython/ipython#9910]
The wiki still has several references to it, and %install_ext no longer exists.

**Comment by Carreau** [comment]
meh... the wiki is there mostly for historical reason. We should replace most of the pages by:

"See IPython official documentation and dig through history if you really need something that was there"

**Comment by klonuo** [comment]
I asked the question about `%install_ext` missing from new IPython on mailing list, and got reasonable reply from @Carreau 

However, many of IPython extension are single script programs. Asking to write valid package on pypi seems like unnecessary overkill for existing and possible future extensions. It's much easier to host live extension as a repo on GitHub or even Gist or any server. It does not stop you from writing Python package if necessary. Just look at the wiki: https://github.com/ipython/ipython/wiki/Extensions-Index

IMHO, not having features as full fledged Python package should not restrict IPython extension. `%load_ext` exists, but why manually downloading extension and copying to specific folder, when that job was perfectly handled by `%install_ext` magic? Maybe we can rename this magic to `%download_ext` if you feel against it?

Again IMHO, uninstall/upgrade feature does have enough weight to remove this magic. Running `%install_ext <url>` will upgrade same script, and removing the extension is not critical as it's not loaded by default.

**Comment by Carreau** [comment]
I honestly doubt make a "valid" python package is that hard.

I'm pretty sure I can make an extension into a package in less than 5min. In
most case likely less than 2 (including publish  on PyPI as well, but agreed I
have my credentials set-up); 

Let's take the `ActiveState Code Recipes magics` in your link. 

I haven't look at  it yet; I'm pretty sure I can do the following and it will work:

```
$ pip install flit
$ mkdir test_active_state_recipes
$ cd test_active_state_recipes
$ mkdir test_active_state_recipes
$ curl https://raw.githubusercontent.com/debjan/ipython-recipes-magic/master/recipes.py >> test_active_state_recipes/__init__py
$ # edit above file to give a docstring with to module and set `__version__ = '0.0.1'`
$ git init 
$ flit init # press enter 4 times (5 time maybe) ?
$ git add . 
$ git commit -am 'turn receipe into a package'
$ flit wheel --upload.
```

That should be it; I won't count pushing on GitHub as creating a GitHub repo,
and not harder for a package than just drop a file in gist. 

> IMHO, not having features as full fledged Python package should not restrict IPython extension. %load_ext exists, but why manually downloading extension and copying to specific folder, when that job was perfectly handled by %install_ext magic?

No it was not; `install_ext` was a relatively gross hack, which was probably
convenient, but against all the best practices that we have in open source;
not considering the security issue.

The thought that "Python Packaging is hard" is an historical vestige of how it
was half a decade ago. The time you put into making a package and having people
being able to install it just by it's name is way compensated by the time you
won't have remind user of were your package are, and how to install it. 

I'll try to actually make the above in less than 5 min; I'm currently in a
train so have bad connection, so it's might be slow.

So let's try... See you in 5 hopefully...

**Comment by Carreau** [comment]
`<5 minutes later>` roughly, I got confused by the screen recording.

It took me.... 1min19 sec (I can post the vide on youtube, I recorded myself, but I'm in a train),
Fair enought, I cheated, I copy pasted the curl line, and flit was already installed; but
the package is [there](https://pypi.python.org/pypi/test_active_state_recipes)
and can be "just" pip-installed. 

I'll remove it at some point, as I am not the author; and it'a bad to take credit from someone else. 

I still strongly believe that removing `install_ext` is well worth the cost benefit.
 - It is less functionality to maintain for us
 - Almost nothing (1min20s, let's push to 5min) for authors at least once; just a `flit wheel --upload` on new versions. 
 - A tremendous gain for users that "just" need to `pip-install <name>`

It can be indeed burdensome to write a package with flit as it enforces that the module have a docstring... Though `setup.py` is not much more complicated. Flit through forces you to choose a license; (code without license can't be used), and has a quite easy to remember Cli API. (`flit init`, `flit wheel` and `flit wheel --upload`) being the only 3 things you need to remember. 

I'm also pretty sure the time spent on asking to reintroduce `%install_ext` over the next few years will likely be much greater than the time spent converting these extensions to packages.

**Comment by klonuo** [comment]
:D

This video and your reply in summary can fit nice in extensions wiki ;)
I didn't knew about `flit` and about wheels I only knew that they can easily host compiled libraries.  You showed that the packaging process can be breeze.

Thanks, I dont have any objections about `%install_ext` :)

**Comment by Carreau** [comment]
Flit is relatively recent and is pushing the python-packaging forward as it show some of the limitations see [pep 517](https://www.python.org/dev/peps/pep-0517/) for im process peps. 

Wheels _can_ bundle compiles library, but mostly they are installation archive that can't run arbitrary code at install time. You "Just" have to unpack the wheel in the right location. 

If you happen to play a bit with flit, or package a few extensions improvement of our docs is welcome !

**Comment by klonuo** [comment]
Noted, thanks :)

**Comment by Carreau** [comment]
Done. I also had a quick glance at Stackoverflow
