### ISSUE TITLE
Document \latex and \unicode completions

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9913]
cf comment https://github.com/ipython/ipython/pull/6380#issuecomment-242601680

**Comment by Carreau** [comment]
Marking as 6.0 as then we can assume python 3, and that this kind of completion is availlable.

**Comment by anntzer** [comment]
Note that this still conflicts with the use of \ as path delimiter on Windows (https://github.com/ipython/ipython/issues/8364#issuecomment-96768318), so I'd appreciate if it was togglable (I use vi-mode digraphs for inputting unicode, so I don't need these completions anyways).
