### ISSUE TITLE
investigate os.scandir

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9914]
Starting with Python 3.5 os.scandir is available and is faster than listdir. It is also availlable on PyPI there : https://pypi.python.org/pypi/scandir

Looking as the various usage of listdir and os.walk on our codebase and seeing whether we can replace their usage by scandir/scandir walk should be a relatively simple task that might lead to some performance improvements and maybe even code simplification. 

We should also investigate this on jupyter/notebook and jupyter/nbconvert likely (cc @michaelpacer)

**Comment by takluyver** [comment]
To clarify a bit, it's not that `scandir` is faster than `listdir` by itself. It gets extra information compared to listdir, so it should be faster than using `listdir` *plus* calling something like `os.path.isdir(p)` on each file it returns. We do do precisely that in some places, though.

I believe that `os.walk` uses scandir internally, so it should get a free speed boost without us doing anything.

**Comment by Carreau** [comment]
> To clarify a bit, it's not that scandir is faster than listdir by itself. It gets extra information compared to listdir, so it should be faster than using listdir plus calling something like os.path.isdir(p) on each file it returns. We do do precisely that in some places, though.


> I believe that os.walk uses scandir internally, so it should get a free speed boost without us doing anything.

That's only on 3.5+ IIRC, we can also depend on the scandir package for 3.3 and 3.4 then use the listdir and walk provided by these packages.

**Comment by takluyver** [comment]
Eh, I doubt it's worth adding a dependency for a probably trivial speed-up.

**Comment by oldani** [comment]
I will like to work on this one.

**Comment by jzf2101** [comment]
@Carreau ? @takluyver ?

**Comment by takluyver** [comment]
It would be useful if you could find any places in IPython's code which might benefit from `scandir()` - typically these are places where `listdir()` is used to find files in a directory, followed by checking `isdir()` or `isfile()` on each one. If there aren't any such cases in IPython, we can close this.

Scandir is new in Python 3.5, and IPython still supports Python 3.4 for now, so we won't make the changes until we drop support for that version. But knowing where to change at that point would be useful.

**Comment by oldani** [comment]
Ok, I will do this, thanks:p

**Comment by kd2718** [comment]
Not sure if anyone is still working on this. I might take a look

**Comment by kd2718** [comment]
@takluyver said 
> Scandir is new in Python 3.5, and IPython still supports Python 3.4 for now, so we won't make the changes until we drop support for that version. But knowing where to change at that point would be useful.

Do you still want to just mark the locations to make these changes? Or did we want to look into a module at this point. I think 3.4 is still supported.

**Comment by Carreau** [comment]
> I think 3.4 is still supported.

3.4 has been dropped, at least in IPython.
Already marking the area where there would be a potential speedup would be a useful first step, in IPython but also in notebook, or any other package.

It may be that no code would actually be better and we can close the issue. Which is already a step forward.

**Comment by kd2718** [comment]
@Carreau So are you saying this ticket finished? If so I can look for something else...

**Comment by kd2718** [comment]
got it. Sorry for confusion. I will get on this asap.
