### ISSUE TITLE
Add vi state indicator to prompt

### ISSUE THREAD

**Issue by memeplex** [ipython/ipython#9915]
Maybe I'm missing something but I had to write this somewhat convolved code to get a vi-mode indicator in the prompt a la readline:

``` python
from IPython.terminal.prompts import Prompts, Token
from prompt_toolkit.key_binding.vi_state import InputMode


class MyPrompts(Prompts):

    def in_prompt_tokens(self, cli=None):
        mode = 'ins' if cli.vi_state.input_mode == InputMode.INSERT else 'cmd'
        return [
            (Token.Prompt, '(%s)In [' % mode),
            (Token.PromptNum, str(self.shell.execution_count)),
            (Token.Prompt, ']: ')
        ]

c.TerminalInteractiveShell.prompts_class = MyPrompts
```

I could submit a PR adding an option like `c.TerminalInteractiveShell.vi_state_indicators = '(ins)', '(nav)', '(rep)'` if you're interested. Suggestions are welcome.

**Comment by Carreau** [comment]
Hi @memeplex , 

Vi input mode does not have a lot of love; so improvement are welcome; the only suggestion I would add is to make `(%s)` be nothing be `''` if the input mode is not Vi so that the Prompt can be the same both in emacs on Vi mode.

**Comment by takluyver** [comment]
I wouldn't leap into hardcoding them into the prompt; prompt_toolkit also offers a bottom toolbar and (IIRC) a right-hand prompt. I'd like to use more such functionality from IPython, and it may make sense to put the indicators in one of those.

**Comment by Carreau** [comment]
We haven't moved a lot on this. I think that a simpler way to set the mode int the prompt would be great. 
We can revisit later.

**Comment by Carreau** [comment]
Done. Hardcoded. Further patch and improvement welcommed.

**Comment by alezandro** [comment]
So how do I disable/remove "[nav]" and "[ins]" from the prompt? I would prefer not to see them but still want to use TerminalInteractiveShell.editing_mode=vi

**Comment by Carreau** [comment]
See https://github.com/ipython/ipython/pull/11492 that allow to toggle them.
