### ISSUE TITLE
Update docs on making a release on sdist tar.gz

### ISSUE THREAD

**Issue by willingc** [ipython/ipython#9926]
All release documentation (IPython and other repos) should be updated to reflect only one sdist version is allowed per PEP 527.

> PEP 527, which was just accepted, says that there can only be one sdist per release. Tarballs are already the more common sdist format on PyPI, so let's go with that

- [x] IPython
- [x] Jupyter docs
- [x] JupyterHub docs

Reference #9925 

cc @carreau

**Comment by takluyver** [comment]
- ipython/ipython#9927
- jupyter/notebook#1729

**Comment by willingc** [comment]
Who needs an issue in the issue tracker when @takluyver is in "lightspeed" mode :wink:

**Comment by takluyver** [comment]
I borrowed one of Min's clones for a bit :)

**Comment by willingc** [comment]
- https://github.com/jupyterhub/jupyterhub/pull/718

**Comment by willingc** [comment]
- https://github.com/jupyter/jupyter/pull/199

Closing this since we have covered the major places for the docs.
