### ISSUE TITLE
completion after ( and [

### ISSUE THREAD

**Issue by talkaminker** [ipython/ipython#9930]
autocomplete is not triggered after ( or [

example:
`some_list = [0,5,10]`
`max(so<TAB>`
will result in nothing. BUT adding a space after the (:
`max( so<TAB>` 
Does pop the autocomplete window.

I am pretty sure ipython should autocomplete in these situations and not only after whitespace.

version:
tried 4.2.0 and 5.1 (I think I remember at least one version that it worked, but maybe my memory is bad)

**Comment by Carreau** [comment]
We want to refactor the completion to use Jedi at some point, it should fix most of these issues.

**Comment by talkaminker** [comment]
Will this mean the ipython will not use the kernel for the autocompletion?
Will we still have the greedy option. I love it, and everybody I show it to also loves it.

**Comment by Carreau** [comment]
> Will this mean the ipython will not use the kernel for the autocompletion?


Jedi have option to run in the kernel and inspect the live namespace, so you you will still get kernel completions.

> Will we still have the greedy option. I love it, and everybody I show it to also loves it.

This one will likely get removed, but jedi _does_ allow things like `foo[x].methods().<tab>` to workin many cases and without evaluation so the need for greedy will be less pronounced.

**Comment by talkaminker** [comment]
the Jedi things does sounds good though, great work.
I know it is not a democracy but if there will be a referendum, count me as YES on keeping the greedy option.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. I am seeing the desired behavior in both `5.1.0` and `master` on OS X. Please feel free to re-open with more details if this is not the case for you.

Thanks everyone and happy hacking! :bowtie:

**Comment by ivanov** [comment]
I should add that you might see this issue if you have the greedy completer enabled, in which case https://github.com/ipython/ipython/issues/2657 is the issue keeping track of that defect (which I'm not sure if it's been addressed)
