### ISSUE TITLE
2.x, 3.x patch for bad signature clipping on methods

### ISSUE THREAD

**Issue by rmorshea** [ipython/ipython#9935]
[L81 of signatures.py 2.x through 3.x](https://github.com/ipython/ipython/blob/2.x/IPython/utils/signatures.py#L81) causes bad signature clipping for methods:

``` python
class A(object):
    def f(*args, **kwargs):
        pass
```

`A().f` is shown as having a signature of `(**kwargs)` when it is actually `(*args, **kwargs)`

**Comment by ivanov** [comment]
Hi @rmorshea - thank you for your report. You pointed to code in the `2.x` branch, which is quite old. I'm going to close this issue, since the latest IPython 5.1.0 does not exhibit this behavior:
```python
In [3]: A.f?
Signature: A.f(*args, **kwargs)
Docstring: <no docstring>
File:      ~/code/ipython/<ipython-input-2-05bf11b6b292>
Type:      instancemethod
```

Happy hacking! :bowtie:
