### ISSUE TITLE
Navigation commands for ipython config

### ISSUE THREAD

**Issue by notmatthancock** [ipython/ipython#9938]
I'm opening this issue due to:

> IPython no longer uses readline configuration (~/.inputrc). We hope that the functionality you want (e.g. vi input mode) will be available by configuring IPython directly (see Terminal IPython options). If something’s missing, please file an issue.

My `.inputrc` contained the following

```
"\e[1;5A": beginning-of-line
"\e[1;5B": end-of-line
"\e[1;5C": forward-word
"\e[1;5D": backward-word
```

I don't see any options for these navigation controls in the [options page](http://ipython.readthedocs.io/en/stable/config/options/terminal.html) to change in my `ipython_config.py` file. Are these options not currently available or am I looking in the wrong place?

**Comment by takluyver** [comment]
[Docs on customising keyboard shortcuts](http://ipython.readthedocs.io/en/stable/config/details.html#keyboard-shortcuts)

There must already be functions for those actions defined somewhere in prompt_toolkit, because there are shortcuts for them (e.g. home/end, and Alt+f for forwards word in Emacs mode). So with a bit of digging it should be possible to reuse them. We acknowledge this is not as simple as readline config at present.

**Comment by notmatthancock** [comment]
Thanks. I was able to modify the example in your link to set Ctrl+up/down to beginning/end of line:

```
from IPython import get_ipython
from prompt_toolkit.enums import DEFAULT_BUFFER
from prompt_toolkit.keys import Keys
from prompt_toolkit.filters import HasFocus, HasSelection, ViInsertMode, EmacsInsertMode

ip = get_ipython()
insert_mode = ViInsertMode() | EmacsInsertMode()

def go_start(event):
    buf = event.current_buffer
    buf.cursor_position = buf.document.get_start_of_line_position()

def go_end(event):
    buf = event.current_buffer
    buf.cursor_position = buf.document.get_end_of_line_position()

# Register the shortcut if IPython is using prompt_toolkit
if getattr(ip, 'pt_cli'):
    registry = ip.pt_cli.application.key_bindings_registry
    registry.add_binding(Keys.ControlUp,
                         filter=(HasFocus(DEFAULT_BUFFER)
                                 & ~HasSelection()
                                 & insert_mode))(go_start)
    registry.add_binding(Keys.ControlDown,
                         filter=(HasFocus(DEFAULT_BUFFER)
                                 & ~HasSelection()
                                 & insert_mode))(go_end)
```

I added this to a startup file. I was unable to find functions for moving left/right by word in the [`Buffer` class](https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/buffer.py), but luckily this behavior works by default using Alt+f/b or Ctrl+Left/Right anyway.

**Comment by takluyver** [comment]
Alt-F is registered here in the prompt_toolkit code, for reference:

https://github.com/jonathanslenders/python-prompt-toolkit/blob/99fa7fae61c9b4ed9767ead3b4f9b1318cfa875d/prompt_toolkit/key_binding/bindings/emacs.py#L57

It looks like PT has named commands for some readline functions.

**Comment by notmatthancock** [comment]
Great. I have now in `~/.ipython/profile_default/startup/navs.py`:

```
from IPython import get_ipython
from prompt_toolkit.filters import ViInsertMode, EmacsInsertMode
from prompt_toolkit.keys import Keys
from prompt_toolkit.key_binding.bindings.utils import create_handle_decorator
from prompt_toolkit.key_binding.bindings.named_commands import get_by_name

ip = get_ipython()
insert_mode = ViInsertMode() | EmacsInsertMode()

# Register the shortcut if IPython is using prompt_toolkit
if getattr(ip, 'pt_cli'):
    registry = ip.pt_cli.application.key_bindings_registry
    handle = create_handle_decorator(registry, insert_mode)
    handle(Keys.ControlUp)(get_by_name('beginning-of-line'))
    handle(Keys.ControlDown)(get_by_name('end-of-line'))
    handle(Keys.ControlLeft)(get_by_name('backward-word'))
    handle(Keys.ControlRight)(get_by_name('forward-word'))
```

I'm not sure if this is the proper way to do this, but it appears to be working fine.

**Comment by notmatthancock** [comment]
I will close this since the above appears to resolve the issue.

**Comment by takluyver** [comment]
Thanks! That does look about right. Feel free to reopen (or make a new issue) if you think there are shortcuts we should add to the ones enabled by default.
