### ISSUE TITLE
Ipython 5.1 notebook broken with conda

### ISSUE THREAD

**Issue by d10genes** [ipython/ipython#9951]
Trying to find a home for this issue. It was claimed to belong here in conda/conda#3423. Original below:

If I install the following conda env file

```
name: bug
dependencies:
- python=3.5
- jupyter
```

I get `ImportError: cannot import name 'pexpect'`
Trace and conda list [here](https://gist.github.com/d10genes/3fd2adbb0ed856264466987d678543ab). (adding a `- ipython < 5.1` line seems to fix it).

**Comment by takluyver** [comment]
The line you're getting an error from is not in IPython 5.1:

https://github.com/ipython/ipython/blob/5.1.0/IPython/utils/_process_posix.py#L24

I would guess you've been hit by conda hard linking - at some point pip has overwritten a conda installed IPython in some environment, and now the copy conda links is broken. Try removing the conda installation and installing with pip:

```
conda remove ipython
conda update pip
pip install ipython
```

**Comment by d10genes** [comment]
After those commands, I get 

```
Kernel started: 6f786581-3543-41ff-8b90-7dc12936c9c4
/Users/me/miniconda3/envs/bug/lib/python3.5/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/me/miniconda3/envs/bug/lib/python3.5/site-packages/IPython/kernel/__init__.py", line 31, in <module>
    from ipykernel import comm, inprocess
ImportError: No module named 'ipykernel'
```

My new conda list is [here](https://gist.github.com/05240ff7c3ad8819d1fe185b075eb208)

**Comment by takluyver** [comment]
Sorry, I forgot that conda would remove that too. `pip install ipykernel`.

**Comment by d10genes** [comment]
Thanks, this works for me! Any ideas/suggestions on how to set up the conda file so I don't have to make these changes for every env? Or is it an issue that can only be fixed by conda?

**Comment by takluyver** [comment]
Try a `conda clean -tipsy` (Tarballs, Index, Packages, Source cache, Yes), and maybe `conda update ipykernel` in any env affected. Unfortunately once the files conda tracks are changed, I don't know of a good simple way to restore them. The conda maintainers may have better suggestions.

**Comment by ivanov** [comment]
Seems like @d10genes got to the bottom of this thanks to @takluyver help, so I'm going to go ahead and close this one. Go TEAM!

Happy hacking! :bowtie:
