### ISSUE TITLE
UnicodeEncodeError  in ipython but not in python terminal

### ISSUE THREAD

**Issue by i-frost** [ipython/ipython#9958]
I am having a problem in ipython with a boolean result with pandas dataframe. If i use the result from the str.contains ipython woks but if I use inverse using a ~. Ipython complains.

This is not a problem in the python terminal, Is there some path or something I need to tell ipython about?

Thanks

data[~data['Reason'].str.contains('(Acquir)',case=0)]
   ...: 
/usr/bin/ipython:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  #!/usr/bin/python3
Out[9]: ---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-9-b959ad8a3c4e> in <module>()
----> 1 data[~data['Reason'].str.contains('(Acquir)',case=0)]

/usr/lib/python3.5/site-packages/IPython/core/displayhook.py in __call__(self, result)
    248             self.fill_exec_result(result)
    249             if format_dict:
--> 250                 self.write_format_data(format_dict, md_dict)
    251                 self.log_output(format_dict)
    252             self.finish_displayhook()

/usr/lib/python3.5/site-packages/IPython/core/displayhook.py in write_format_data(self, format_dict, md_dict)
    187                 result_repr = '\n' + result_repr
    188 
--> 189         print(result_repr)
    190 
    191     def update_user_ns(self, result):

UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 10275: ordinal not in range(128)

In [10]:                                                                                                                                           
Do you really want to exit ([y]/n)? y
[ian@alarm git_repo]$ ipython
Python 3.5.2 (default, Jul  3 2016, 09:10:18) 
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

**Comment by takluyver** [comment]
`\u2019` is a unicode fancy quotation mark. For some reason it's detected your terminal encoding as ascii, rather than something like utf-8. What is the environment variable `$LANG` set to? E.g. for me this is `en_GB.UTF-8`.

Assuming your terminal accepts UTF-8 (which is the case on most recent Linux distros), you can set the environment variable [PYTHONIOENCODING](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONIOENCODING) to `utf-8` to override its guess.

**Comment by i-frost** [comment]
It appears to be set to 'C', language of computers! Would it be wise to change this to en_GB.UTF-8?

locale
LANG=C
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=

**Comment by takluyver** [comment]
`C` is the default; that would explain why it's trying to use ascii. I'd recommend setting the locale to something more specific - if it's on a desktop system, there's probably a GUI way to do that systemwide. The first bit is for your human language (so `en_GB` is UK English). The `.UTF-8` suffix tells it to use the UTF-8 encoding.

**Comment by i-frost** [comment]
I changed my locale and export PYTHONIOENCODING to utf-8 in my .bshrc which has fixed it!

Thanks very much for your help:-)

**Comment by takluyver** [comment]
Great, glad you've got it working. I'm going to close this now, as I think it was expected behaviour when the locale is `C`.
