### ISSUE TITLE
IPython notebook documentation — "collection of examples" link broken

### ISSUE THREAD

**Issue by maxime-pico** [ipython/ipython#9966]
Hi,

I was reading the documentation to find out more about IPython and tried to view the "collection of examples" link that illustrates the different types of cells. The link returned me a 404: http://nbviewer.jupyter.org/github/ipython/ipython/blob/master/examples/Notebook/Index.ipynb

Here's where the link is in the doc:
![ipythondoc](https://cloud.githubusercontent.com/assets/4660085/18824545/260c2114-83c3-11e6-998c-0ea2d3071f1a.png)
(this is a screenshot of that page: https://ipython.org/ipython-doc/3/notebook/notebook.html#introduction)

Thanks for your awesome project! I'm just discovering now but it seems really cool :)

Maxime

**Comment by minrk** [comment]
At the top of that page, you will find this message:

<img width="819" alt="screen shot 2016-09-26 at 11 01 17" src="https://cloud.githubusercontent.com/assets/151929/18828529/98b4d156-83d8-11e6-856b-27f2143dd589.png">

The current IPython documentation is [on readthedocs](https://ipython.readthedocs.io/en/stable/).

**Comment by Carreau** [comment]
I'm closing this as no-actions. Feel free to reopen.

**Comment by maxime-pico** [comment]
Sure thank you for your quick answer.

Maxime

On Wed, 28 Sep 2016 at 00:40 Matthias Bussonnier

<
mailto:Matthias Bussonnier <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

I'm closing this as no-actions. Feel free to reopen.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/ipython/ipython/issues/9966#issuecomment-250020171
, or
