### ISSUE TITLE
Audit our warnings

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#9981]
Our warnings should likely be audited to check the following (mostly for deprecation warnings):

Warnings messages should try to mention: 
- Since which version something is deprecated.
- Whether it currently has an effect (or not), and in both case by what it could (should?) be replaced.
- a `stacklevel` value (except maybe at import time, in order to appear at in the right stackframe)

That should be easy for someone to get into the code.

**Comment by Carreau** [comment]
Note, on unix system, the following might be useful:

```
grep -A3 'warn(' **.py |grep -v stacklevel
```

**Comment by souravsingh** [comment]
@Carreau I would like to take a stab at the issue.

**Comment by Carreau** [comment]
Hi @souravsingh, sure, please go ahead and feel free to ask any questions.

See https://github.com/ipython/ipython/pull/9980 for an example.

You can do things in 1 or many PR as you like. 

Thanks ! We appreciate that !

**Comment by jzf2101** [comment]
@souravsingh are you still working on this issue? @Carreau is this issue still relevant?

**Comment by Carreau** [comment]
> @Carreau is this issue still relevant?

Yes, And I believe this will probably stay relevant ad vitam æternam as we are regularly adding/modifying warnings. We should probably just have every now and then someone that add a "Check on yy/mm/dd" on this issue and revisit it every few month every year.

**Comment by souravsingh** [comment]
@jzf2101 I had forgotten about the issue. I am now working on sending a PR.

**Comment by jzf2101** [comment]
@souravsingh you're still interested?

**Comment by souravsingh** [comment]
Yes. I am. I will send a patch quickly.

**Comment by jzf2101** [comment]
@souravsingh I don't see a PR referencing this issue?
