### ISSUE TITLE
Add a metadata value called "expanded" to the JSON display class

### ISSUE THREAD

**Issue by aleury** [ipython/ipython#9999]
I would like to extend the JSON display object class to accept a metadata parameter called `expanded`. The purpose is to be able to control the expansion of a JSON display component used in the [nteract](https://github.com/nteract/nteract) project. Please see https://github.com/nteract/nteract/issues/962 for an example.

**Comment by rgbkrk** [comment]
Example:

![nteract JSON support](https://cloud.githubusercontent.com/assets/1060558/19253579/2198b7b6-8f1a-11e6-89b0-85de1390ddea.png)

**Comment by takluyver** [comment]
Closed by #10000 !
